### ISSUE TITLE
Updating to 1.67.1 causes Jupyter to no longer be able to open.

### ISSUE THREAD

**Issue by Lolologist** [microsoft/vscode-jupyter#10000]
Issue Type: <b>Bug</b>

Jupyter can't start after updating to 1.67.1 and says to open the developer tools to investigate.

Extension version: 2022.4.1011282140
VS Code version: Code 1.67.1 (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:37:16.526Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 3|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id 28e50f8a-52b4-4c5a-a35f-a9afbb6a19e3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes516:30244333
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217
vsclangdc:30486549

```

</details>

Developer log dump here:

`CRITI Extension 'ms-toolsai.jupyter' wants API proposal 'notebookConcatTextDocument' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
log.ts:319 CRITI Extension 'ms-toolsai.jupyter' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): notebookControllerKind, notebookDebugOptions, notebookDeprecated, notebookEditor, notebookEditorDecorationType, notebookEditorEdit, notebookMessaging, notebookMime, notebookCellExecutionState, portsAttributes, textDocumentNotebook, quickPickSortByLabel
product.json (WINS): notebookControllerKind, notebookDebugOptions, notebookDeprecated, notebookEditor, notebookEditorDecorationType, notebookEditorEdit, notebookMessaging, notebookMime, notebookCellExecutionState, portsAttributes, quickPickSortByLabel
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope source.sql.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/sql/syntaxes/sql.tmLanguage.json.
New grammar file: file:///Users/daniel/.vscode/extensions/mtxr.sqltools-0.23.0/language/sql.tmLanguage.json
register @ TMScopeRegistry.ts:47
TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope source.rst.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/restructuredtext/syntaxes/rst.tmLanguage.json.
New grammar file: file:///Users/daniel/.vscode/extensions/trond-snekvik.simple-rst-1.5.2/syntaxes/rst.tmLanguage.json
register @ TMScopeRegistry.ts:47
log.ts:313   ERR [Extension Host] (node:56869) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Electron --trace-deprecation ...` to show where the warning was created)
console.ts:137 [Extension Host] (node:56869) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Electron --trace-deprecation ...` to show where the warning was created)
E @ console.ts:137
notificationsAlerts.ts:42 Extension activation failed, run the 'Developer: Toggle Developer Tools' command for more information.
onDidChangeNotification @ notificationsAlerts.ts:42
log.ts:313   ERR [Extension Host] extension activation failed TypeError: s.notebooks.onDidChangeCellMetadata is not a function
	at u.addEventHandlers (/Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:735175)
	at new u (/Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:733840)
	at Object.t.resolveInstance (/Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2667221)
	at /Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2669159
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2666995)
	at /Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2669159
	at Object.t.resolve (/Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2669422)
	at /Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2652835
	at e._get (/Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2652601)
	at e.get (/Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2651244)
	at e.dynamicValue (/Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2674821)
	at /Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2668648
	at c (/Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2667664)
	at /Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2668588
	at /Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2668077
	at Array.map (<anonymous>)
	at /Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2668049
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2666995)
	at /Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2669159
	at Object.t.resolve (/Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2669422)
	at /Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2652835
	at e._get (/Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2652601)
	at e.get (/Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2651244)
	at a.get (/Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:1109349)
	at /Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:4538183
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:4535892
	at async e.activate (/Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:4535127)
	at async _activate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:8180)
	at async _waitForDepsThenActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:8122)
	at async _initialize (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:7486)
console.ts:137 [Extension Host] extension activation failed TypeError: s.notebooks.onDidChangeCellMetadata is not a function
	at u.addEventHandlers (/Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:735175)
	at new u (/Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:733840)
	at Object.t.resolveInstance (/Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2667221)
	at /Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2669159
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2666995)
	at /Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2669159
	at Object.t.resolve (/Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2669422)
	at /Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2652835
	at e._get (/Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2652601)
	at e.get (/Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2651244)
	at e.dynamicValue (/Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2674821)
	at /Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2668648
	at c (/Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2667664)
	at /Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2668588
	at /Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2668077
	at Array.map (<anonymous>)
	at /Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2668049
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2666995)
	at /Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2669159
	at Object.t.resolve (/Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2669422)
	at /Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2652835
	at e._get (/Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2652601)
	at e.get (/Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2651244)
	at a.get (/Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:1109349)
	at /Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:4538183
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:4535892
	at async e.activate (/Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:4535127)
	at async _activate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:8180)
	at async _waitForDepsThenActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:8122)
	at async _initialize (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:7486)
E @ console.ts:137
notificationsAlerts.ts:42 No Python interpreter is selected. You need to select a Python interpreter to enable features such as IntelliSense, linting, and debugging.`

**Comment by IanMatthewHuff** [comment]
Something odd here. I see you listing the version of the Jupyter extension as 2022.4.xx. But in the callstack shown above it's listing this path:
/Users/daniel/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801

Thats the old version of our extension and would be causing an issue mismatched with a new version of VS Code. Could you please uninstall the Juypter extension, making sure that no jupyters are still installed in the extensions directory and then try re-installing it?

Not sure how it got into that state though.

**Comment by Lolologist** [comment]
@IanMatthewHuff that was the problem. A couple of restarts and it sorted itself out and is using the right version now. Will re-open this if the error pops back up but I think you're good.
