### ISSUE TITLE
extension failed to start

### ISSUE THREAD

**Issue by plokid** [microsoft/vscode-jupyter#10030]
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

the extension failed to start

there are Uncaught Errors in Runtime Status:
```
Extension 'ms-toolsai.jupyter' CANNOT use API proposal: notebookEditor. Its package.json#enabledApiProposals-property declares: but NOT notebookEditor. The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.jupyter
```
also Messages:
```
interactive/toolbar is a proposed menu identifier. It requires 'package.json#enabledApiProposals: ["notebookEditor"]' and is only available when running out of dev or with the following command line switch: --enable-proposed-api ms-toolsai.jupyter
```

### VS Code Version

1.67.1

### Jupyter Extension Version

v2022.4.1021342353

### Jupyter logs

```shell
command 'jupyter.viewOutput' not found
```

### Coding Language and Runtime Version

python v3.8.13

### Language Extension Version (if applicable)

no

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Thanks for filing this issue.
Unfortunately I'm unable to replicate this issue.
I'm using the same version of VS Code and same version of Jupyter extension and it seems to work just fine.

Please could  you try uninstalling the Jupyter extension and trying this again.
If this still fails, please could you provide all of the output from the error console, perhaps there more in the error logs.

**Comment by plokid** [comment]
Yhe error message in Developer Tools
```
workbench.desktop.main.js:2670 [[object Object]]Extension 'ms-python.python' CANNOT use API proposal: testObserver.
Its package.json#enabledApiProposals-property declares:  but NOT testObserver.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-python.python
$onExtensionRuntimeError @ workbench.desktop.main.js:2670
```
```
workbench.desktop.main.js:2670 Error: Extension 'ms-python.python' CANNOT use API proposal: testObserver.
Its package.json#enabledApiProposals-property declares:  but NOT testObserver.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-python.python
	at f (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:81:64186)
	at Object.get testResults [as testResults] (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:97:33907)
	at E.activate (/home/ploki/.vscode-oss/extensions/ms-python.python-2022.6.2/out/client/extension.js:2:717319)
	at /home/ploki/.vscode-oss/extensions/ms-python.python-2022.6.2/out/client/extension.js:2:2210
	at Array.map (<anonymous>)
	at f.activateWorkspace (/home/ploki/.vscode-oss/extensions/ms-python.python-2022.6.2/out/client/extension.js:2:2200)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
$onExtensionRuntimeError @ workbench.desktop.main.js:2670
```
```
workbench.desktop.main.js:71 [Extension Host] extension activation failed Error: Extension 'ms-toolsai.jupyter' CANNOT use API proposal: notebookEditor.
Its package.json#enabledApiProposals-property declares:  but NOT notebookEditor.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.jupyter
	at f (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:81:64186)
	at Object.get onDidChangeVisibleNotebookEditors [as onDidChangeVisibleNotebookEditors] (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:97:43896)
	at new l (/home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:733828)
	at Object.t.resolveInstance (/home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2934945)
	at /home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2936883
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2934719)
	at /home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2936883
	at Object.t.resolve (/home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2937146)
	at /home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2920559
	at e._get (/home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2920325)
	at e.get (/home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2918968)
	at e.dynamicValue (/home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2942545)
	at /home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2936372
	at c (/home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2935388)
	at /home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2936312
	at /home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2935801
	at Array.map (<anonymous>)
	at /home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2935773
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2934719)
	at /home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2936883
	at Object.t.resolve (/home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2937146)
	at /home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2920559
	at e._get (/home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2920325)
	at e.get (/home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2918968)
	at a.get (/home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:1019881)
	at /home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:4807317
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
E @ workbench.desktop.main.js:71
```
```
workbench.desktop.main.js:2670 [[object Object]]Extension 'ms-toolsai.jupyter' CANNOT use API proposal: notebookEditor.
Its package.json#enabledApiProposals-property declares:  but NOT notebookEditor.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.jupyter
$onExtensionRuntimeError @ workbench.desktop.main.js:2670
```
```
workbench.desktop.main.js:2670 Error: Extension 'ms-toolsai.jupyter' CANNOT use API proposal: notebookEditor.
Its package.json#enabledApiProposals-property declares:  but NOT notebookEditor.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.jupyter
	at f (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:81:64186)
	at Object.get onDidChangeVisibleNotebookEditors [as onDidChangeVisibleNotebookEditors] (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:97:43896)
	at new l (/home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:733828)
	at Object.t.resolveInstance (/home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2934945)
	at /home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2936883
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2934719)
	at /home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2936883
	at Object.t.resolve (/home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2937146)
	at /home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2920559
	at e._get (/home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2920325)
	at e.get (/home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2918968)
	at e.dynamicValue (/home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2942545)
	at /home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2936372
	at c (/home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2935388)
	at /home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2936312
	at /home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2935801
	at Array.map (<anonymous>)
	at /home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2935773
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2934719)
	at /home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2936883
	at Object.t.resolve (/home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2937146)
	at /home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2920559
	at e._get (/home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2920325)
	at e.get (/home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:2918968)
	at a.get (/home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:1019881)
	at /home/ploki/.vscode-oss/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:4807317
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
$onExtensionRuntimeError @ workbench.desktop.main.js:2670
```
Additionally,I am using archlinux, both [Community build](https://archlinux.org/packages/community/x86_64/code/) and [official build](https://aur.archlinux.org/packages/visual-studio-code-bin) doesn't work

**Comment by DonJayamanne** [comment]
Looks like you are using a community build of VS Code.
I'd say the problem is with the community build and not a problem of the extensions. Please file a bug agains the community build.

Please could you install the official build of VS Code and provide the stack trace from the developer tools.

**Comment by plokid** [comment]
Well, it worked after deleting `~/.vscode` and `~/.config/Code`
Thank you
