### ISSUE TITLE
Remote conda environments not visible after vscode update

### ISSUE THREAD

**Issue by mbenahmed1** [microsoft/vscode-jupyter#10098]
## Environment data

-   VS Code version: 1.67.2
-   Jupyter Extension version (available under the Extensions sidebar): v2022.5.1001290443
-   Python Extension version (available under the Extensions sidebar): v2022.6.2
-   OS (Windows | Mac | Linux distro) and version: Arch Linux 5.17.9-arch1-1
-   Python and/or Anaconda version: 3.9.12, 4.12.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Remote

## Expected behaviour

Remote conda envs showing up in the kernel selection drop-down menu.

## Actual behaviour

Only local python interpreters show up.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Connect to a remote server.
2. Start jupyter notebook server.
3. Open tunnel to remote server.
4. Copy URL from the jupyter notebook server.
5. Paste URL in jupyter extension existing remote server field.
6. Hit enter.
7. Click on "select kernel"
8. Observe that only local python interpreters are shown while jupyter server on remote machine shows that it finds conda envs (they also show up and work in the browser jupyter editor).

## Logs

Output

`[2022-05-23 09:59:29.592] [exthost] [info] Extension host terminating: renderer closed the socket
[2022-05-23 09:59:29.602] [exthost] [info] Extension host with pid 5344 exiting with code 0
[2022-05-23 09:59:31.614] [exthost] [info] Extension host with pid 6219 started
[2022-05-23 09:59:31.615] [exthost] [info] Skipping acquiring lock for /home/martin/.config/VSCodium/User/workspaceStorage/d89b4d2d8431b2c4971fb50c1fdc0bc2.
[2022-05-23 09:59:31.865] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: true, activationEvent: '*'
[2022-05-23 09:59:31.869] [exthost] [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
[2022-05-23 09:59:31.871] [exthost] [info] ExtensionService#_doActivateExtension vscode.ipynb, startup: true, activationEvent: '*'
[2022-05-23 09:59:31.874] [exthost] [info] ExtensionService#_doActivateExtension mhutchie.git-graph, startup: true, activationEvent: '*'
[2022-05-23 09:59:31.889] [exthost] [info] ExtensionService#_doActivateExtension reduckted.vscode-gitweblinks, startup: true, activationEvent: '*'
[2022-05-23 09:59:31.898] [exthost] [info] ExtensionService#_doActivateExtension Shan.code-settings-sync, startup: true, activationEvent: '*'
[2022-05-23 09:59:32.005] [exthost] [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
[2022-05-23 09:59:32.017] [exthost] [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
[2022-05-23 09:59:33.264] [exthost] [info] Eager extensions activated
[2022-05-23 09:59:33.270] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onStartupFinished'
[2022-05-23 09:59:33.277] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
[2022-05-23 09:59:33.280] [exthost] [info] ExtensionService#_doActivateExtension eamodio.gitlens, startup: false, activationEvent: 'onStartupFinished'
[2022-05-23 09:59:33.319] [exthost] [info] ExtensionService#_doActivateExtension felipecaputo.git-project-manager, startup: false, activationEvent: 'onStartupFinished'
[2022-05-23 09:59:33.337] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-containers, startup: false, activationEvent: 'onStartupFinished'
[2022-05-23 09:59:33.362] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl, startup: false, activationEvent: 'onStartupFinished'
[2022-05-23 09:59:35.291] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
[2022-05-23 09:59:40.221] [exthost] [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter, startup: false, activationEvent: 'onNotebook:jupyter-notebook'
[2022-05-23 09:59:40.387] [exthost] [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter-renderers, startup: false, activationEvent: 'onNotebook:*'
[2022-05-23 09:59:40.475] [exthost] [info] ExtensionService#_doActivateExtension ms-python.python, startup: false, activationEvent: 'onLanguage:python'
`

`VSCodium (1.67.2, undefined, desktop)
Jupyter Extension Version: 2022.5.1001290443.
Python Extension Version: 2022.6.2.
Workspace folder /mnt/git/GNN
info 9:59:40.449: ZMQ install verified.
info 9:59:40.800: Old kernelSpecs (created by Jupyter extension) stored in directory /home/martin/.local/share/jupyter/kernels/__old_vscode_kernelspecs
info 9:59:41.323: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
info 9:59:41.344: Checking for server existence.
info 9:59:41.348: Checking for server usability.
info 9:59:41.348: Starting notebook server.
info 9:59:41.349: Connecting to server
info 9:59:41.352: Connecting to process server
info 9:59:41.352: Connecting server kernel http://localhost:8989/
Connecting to Jupyter server at http://localhost:8989/
info 9:59:41.354: Creating server with url : http://localhost:8989/
info 9:59:41.395: Connection complete server
info 9:59:41.395: Server started.
info 9:59:41.395: Creating server with url : http://localhost:8989/
error 9:59:41.549: Error fetching remote kernels: [a [Error]: Forbidden
	at Function.create (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/node_modules/@jupyterlab/services.js:2:53387)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Object.a.listRunning (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/node_modules/@jupyterlab/services.js:2:41252)
	at async u.getRunningKernels (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:415453)
	at async Promise.all (index 0)
	at async v.listKernels (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:392803)] {
  response: F [Response] {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'http://localhost:8989/api/kernels?1653292781397',
      status: 403,
      statusText: 'Forbidden',
      headers: [I [Headers]],
      counter: 0
    }
  },
  traceback: ''
}
error 9:59:41.640: SessionManager:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at e.dispose (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/node_modules/@jupyterlab/services.js:2:156575)
	at m.dispose (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/node_modules/@jupyterlab/services.js:2:48238)
	at u.dispose (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:414537)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async v.listKernels (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:393957)]
info 9:59:41.655: Starting Jupyter Session id = .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher for /mnt/git/GNN/pytorch_geometric.ipynb (disableUI=true)
info 9:59:41.657: Creating raw notebook for /mnt/git/GNN/pytorch_geometric.ipynb
info 9:59:41.657: Computing working directory /mnt/git/GNN/pytorch_geometric.ipynb
info 9:59:41.668: Starting raw kernel Python 3.10.4 64-bit for interpreter /bin/python
info 9:59:41.673: Kernel launching with ports 9000,9001,9002,9003,9004. Start port is 9000
error 9:59:42.683: Error: Cannot delete password
    at I.$deletePassword (vscode-file://vscode-app/usr/share/vscodium/resources/app/out/vs/workbench/workbench.desktop.main.js:1712:49953)
error 9:59:42.683: Failed to get remote kernels [Error: Remote Jupyter Server connection not provided
	at w.getNotebookServerOptions (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:378025)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async w.getOrCreateServer (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:375417)
	at async l.connect (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:353727)
	at async g.listRemoteKernels (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:471303)
	at async Promise.all (index 1)
	at async g.listKernels (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:470474)
	at async j.loadNotebookControllersImpl (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:600203)]
info 9:59:42.692: Process Execution: > /bin/python -m pip list
> /bin/python -m pip list
info 9:59:42.719: Preferred Remote kernel for /mnt/git/GNN/pytorch_geometric.ipynb is undefined
info 9:59:42.755: Process Execution: > /bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> /bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
error 9:59:42.960: Failed to get remote kernels [Error: Remote Jupyter Server connection not provided
	at w.getNotebookServerOptions (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:378025)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async w.getOrCreateServer (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:375417)
	at async l.connect (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:353727)
	at async g.listRemoteKernels (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:471303)
	at async Promise.all (index 1)
	at async g.listKernels (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:470474)
	at async g.rankKernels (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:469961)]
error 9:59:42.960: Failed to get remote kernels [Error: Remote Jupyter Server connection not provided
	at w.getNotebookServerOptions (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:378025)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async w.getOrCreateServer (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:375417)
	at async l.connect (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:353727)
	at async g.listRemoteKernels (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:471303)
	at async Promise.all (index 1)
	at async g.listKernels (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:470474)
	at async j.loadNotebookControllersImpl (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:600029)]
info 9:59:42.961: Preferred Remote kernel for /mnt/git/GNN/pytorch_geometric.ipynb is undefined
info 9:59:42.961: Find preferred kernel for /mnt/git/GNN/pytorch_geometric.ipynb with metadata {"kernelspec":{"display_name":"Python [conda env:torch-pyg]","language":"python","name":"conda-env-torch-pyg-py"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.12"},"vscode":{"interpreter":{"hash":"43eec52ae2e25fdee062f41bc35729fb531c177f05340703a5c1c13e281532e7"}}} & preferred interpreter /bin/python
info 9:59:42.965: Preferred Remote kernel for /mnt/git/GNN/pytorch_geometric.ipynb is undefined
info 9:59:42.965: Preferred kernel .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher is exact match
info 9:59:42.966: PreferredConnection: .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher found for NotebookDocument: /mnt/git/GNN/pytorch_geometric.ipynb
info 9:59:42.966: TargetController found ID: .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher for document /mnt/git/GNN/pytorch_geometric.ipynb
info 9:59:42.973: No custom variables nor do we have a conda environment
info 9:59:42.983: Process Execution: > /bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"58645a61-e3c6-4e36-a9ec-1ecfa13b0b98" --shell=9002 --transport="tcp" --iopub=9004 --f=/home/martin/.local/share/jupyter/runtime/kernel-6219bDcuPRns0Chb.json
> /bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"58645a61-e3c6-4e36-a9ec-1ecfa13b0b98" --shell=9002 --transport="tcp" --iopub=9004 --f=/home/martin/.local/share/jupyter/runtime/kernel-6219bDcuPRns0Chb.json
info 9:59:42.983: Process Execution: cwd: /mnt/git/GNN
cwd: /mnt/git/GNN
error 9:59:43.3: Failed to get remote kernels [Error: Remote Jupyter Server connection not provided
	at w.getNotebookServerOptions (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:378025)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async w.getOrCreateServer (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:375417)
	at async l.connect (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:353727)
	at async g.listRemoteKernels (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:471303)
	at async Promise.all (index 1)
	at async g.listKernels (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:470474)
	at async j.loadNotebookControllersImpl (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:600203)]
error 9:59:43.4: Failed to get remote kernels [Error: Remote Jupyter Server connection not provided
	at w.getNotebookServerOptions (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:378025)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async w.getOrCreateServer (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:375417)
	at async l.connect (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:353727)
	at async g.listRemoteKernels (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:471303)
	at async Promise.all (index 1)
	at async g.listKernels (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:470474)
	at async g.rankKernels (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:469961)]
info 9:59:43.9: Preferred Remote kernel for /mnt/git/GNN/pytorch_geometric.ipynb is undefined
info 9:59:43.9: Find preferred kernel for /mnt/git/GNN/pytorch_geometric.ipynb with metadata {"kernelspec":{"display_name":"Python [conda env:torch-pyg]","language":"python","name":"conda-env-torch-pyg-py"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.12"},"vscode":{"interpreter":{"hash":"43eec52ae2e25fdee062f41bc35729fb531c177f05340703a5c1c13e281532e7"}}} & preferred interpreter /bin/python
info 9:59:43.12: Preferred Remote kernel for /mnt/git/GNN/pytorch_geometric.ipynb is undefined
info 9:59:43.12: Preferred kernel .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher is exact match
info 9:59:43.34: ipykernel version 6.13.0 for /bin/python
info 9:59:43.34: ipykernel location /usr/lib/python3.10/site-packages/ipykernel/__init__.py for /bin/python
warn 9:59:43.849: StdErr from Kernel Process /usr/lib/python3.10/site-packages/traitlets/traitlets.py:2389: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
/usr/lib/python3.10/site-packages/traitlets/traitlets.py:2343: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '58645a61-e3c6-4e36-a9ec-1ecfa13b0b98' instead of 'b"58645a61-e3c6-4e36-a9ec-1ecfa13b0b98"'.
  warn(

info 9:59:43.858: Kernel Output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049

To connect another client to this kernel, use:
    --existing kernel-6219bDcuPRns0Chb.json

info 9:59:44.95: Started kernel Python 3.10.4 64-bit, (Raw session started and connected)
info 9:59:44.95: Finished connecting 2ba8bce6-ba48-4a52-ab98-21c51221a9f5
info 9:59:44.106: UpdateWorkingDirectoryAndPath in Kernel
info 9:59:44.107: Executing silently Code (idle) = import os\nimport sys\n%cd "/mnt/git/GNN"\nif os.getcwd() not in sys.path:\nsys.path.insert(0, os.ge
info 9:59:44.123: Executing silently Code (completed) = import os\nimport sys\n%cd "/mnt/git/GNN"\nif os.getcwd() not in sys.path:\nsys.path.insert(0, os.ge
info 9:59:44.124: Waiting for idle on (kernel): f7ba459a-3afc-4530-8214-c75cf9dbb066 -> idle
info 9:59:44.124: Finished waiting for idle on (kernel): f7ba459a-3afc-4530-8214-c75cf9dbb066 -> idle
error 9:59:44.132: Failed to get remote kernels [Error: Remote Jupyter Server connection not provided
	at w.getNotebookServerOptions (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:378025)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async w.getOrCreateServer (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:375417)
	at async l.connect (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:353727)
	at async g.listRemoteKernels (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:471303)
	at async Promise.all (index 1)
	at async g.listKernels (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:470474)
	at async j.loadNotebookControllersImpl (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:600029)]
error 9:59:44.144: Failed to get remote kernels [Error: Remote Jupyter Server connection not provided
	at w.getNotebookServerOptions (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:378025)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async w.getOrCreateServer (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:375417)
	at async l.connect (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:353727)
	at async g.listRemoteKernels (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:471303)
	at async Promise.all (index 1)
	at async g.listKernels (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:470474)
	at async j.loadNotebookControllersImpl (/home/martin/.vscode-oss/extensions/ms-toolsai.jupyter-2022.5.1001290443/out/extension.node.js:2:600203)]
`

**Comment by rchiodo** [comment]
Thanks for the issue. It looks like your URI is invalid. This output here:

```
[Symbol(Response internals)]: {
url: 'http://localhost:8989/api/kernels?1653292781397',
status: 403,
statusText: 'Forbidden',
headers: [I [Headers]],
counter: 0
}
},
traceback: ''
}
```

I believe the tunnel URI has to include the token for jupyter server or it won't connect.

Your version of the extension is also old. Newer versions should show an error just trying to enter the URI.

**Comment by mbenahmed1** [comment]
What do you mean by "... the tunnel URI has to include the token ..."?
The command I use for the tunnel is the following:
`ssh -L 8989:localhost:8989 user@remoteserver`

Afterward, I paste the URI from the jupyter server in vscode or in my browser. In the browser, it works just like it should, but in the jupyter extension, I can not select the conda environments. I never entered the URI in the form it is shown there in the log. I don't understand how that URI is formed.

It worked just fine before updating vscode. It also says I already have the latest version of the jupyter extension.

**Comment by rchiodo** [comment]
The browser caches the connection cookie so it should work without a token. 

I'm assuming the jupyter server you ran on the remote machine outputted a token though. That needs to be passed like so even when tunneling.

```
http://localhost:8889/?token=tokenstring
```

At least if you didn't do that, you'd get the problem you're seeing.

Your extension version is this one: 2022.5.1001290443. I'm not sure where that is coming from. I don't believe we shipped that build (maybe you pulled it from the build agents?)

Stable version list should look like this:

![image](https://user-images.githubusercontent.com/19672699/169915043-57fee6dc-c262-4a9c-a4f2-1203c991e9c0.png)

Prerelease version looks like this:

![image](https://user-images.githubusercontent.com/19672699/169915145-5e9ab2b3-2bb1-4bd9-8352-2a4fb371ea54.png)

**Comment by mbenahmed1** [comment]
I always take the URI with the token in the form you described from the terminal output of the server and paste it either in the browser or in the jupyter extension existing server line. I forgot to say that I regularly get warnings from the jupyter server that looks like this:

`[W 09:24:51.586 NotebookApp] Forbidden
[W 09:24:51.586 NotebookApp] 403 GET /api/sessions?1653377091572 (::1) 0.56ms referer=None`

I did not mention it because it is like that since I started using it and it seems it never was a problem in the past. Nonetheless, I do not know why that happens and I think I should question it.

Regarding the version: I have to check on that since I normally use vscodium. I realized that codeOSS (which I used before) is still not genuine Microsoft vscode, but I don't think this is the reason for this problem. Both codeOSS and vscodium show the same version numbers. I also switched the extension store of vscodium back to the Microsoft store in order to get access to proprietary extensions.

**Comment by mbenahmed1** [comment]
Ok, I checked it. It seems this is a problem with vscodium and codeOSS arch Linux packages. The Microsoft branded visual studio code shows the version numbers you posted and it shows the conda environments again. I am sorry for the confusion but I could not think of a reason vscodium/codeOSS should differ from genuine vscode in that regard.
