### ISSUE TITLE
The Kernel crashed while executing cross_validate for the decision tree on the remote server

### ISSUE THREAD

**Issue by yongxin-xu** [microsoft/vscode-jupyter#10090]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I ran the following code on my remote machine through VSCode.
```python
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_validate
from sklearn import preprocessing
from sklearn import tree
import numpy as np
from scipy import stats

covtype = datasets.fetch_covtype()
X = covtype.data
y = covtype.target
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

# get the mode of y
mode_num = stats.mode(y).mode[0]
print('The mode of y is:', mode_num)

y_binary_train = np.where(y_train == mode_num, 1, 0) 
y_binary_test = np.where(y_test == mode_num, 1, 0)
print("y_binary_train", y_binary_train)
print("y_binary_test", y_binary_test)

min_max_scaler = preprocessing.MinMaxScaler()
X_train_minmax = min_max_scaler.fit_transform(X_train)
X_test_minmax = min_max_scaler.fit_transform(X_test)
```

And 
```python
dt = tree.DecisionTreeClassifier()
dt.fit(X_train, y_binary_train)
DTree_perform = cross_validate(dt,X_train,y_binary_train, cv=3, scoring='roc_auc')['test_score'].mean()
DTree_perform_test = dt.score(X_test, y_binary_test)

print("Decision Tree train set score", DTree_perform)
print("Decision Tree test set score", DTree_perform_test)
```
The second piece of code failed with the info: 
```txt 
Canceled future for execute_request message before replies were done
The Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. View Jupyter log for further details.
```

But the same code is working perfectly normally on my local machine, even though my remote machine has better CPU and memory. I used a virtual env with _Python 3.9.5_. I tried many times but the same result is returned. 
I wonder if it is a bug of vscode-jupyter on the remote server or a glitch in my remote server. I suspect it is the former.

### VS Code Version

1.67.1 (Universal)

### Jupyter Extension Version

v2022.4.1021342353

### Jupyter logs

```shell
info 21:4:38.565: Execute Cell 7 /home/yongxin/projects/datascience/hw4/HW4.ipynb
error 21:4:38.682: Cell execution failed without request, for cell Index 7 [o [Error]: Cannot execute code, session has been disposed.
	at _.requestExecute (/home/yongxin/.vscode-server/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:163895)
	at k.executeCodeCell (/home/yongxin/.vscode-server/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:635446)
	at k.execute (/home/yongxin/.vscode-server/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:634859)
	at k.start (/home/yongxin/.vscode-server/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:630159)
	at async t.CellExecutionQueue.executeQueuedCells (/home/yongxin/.vscode-server/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:647254)
	at async t.CellExecutionQueue.start (/home/yongxin/.vscode-server/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:646714)] {
  category: 'sessionDisposed'
}
warn 21:4:38.683: Cell completed with errors [o [Error]: Cannot execute code, session has been disposed.
	at _.requestExecute (/home/yongxin/.vscode-server/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:163895)
	at k.executeCodeCell (/home/yongxin/.vscode-server/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:635446)
	at k.execute (/home/yongxin/.vscode-server/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:634859)
	at k.start (/home/yongxin/.vscode-server/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:630159)
	at async t.CellExecutionQueue.executeQueuedCells (/home/yongxin/.vscode-server/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:647254)
	at async t.CellExecutionQueue.start (/home/yongxin/.vscode-server/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:646714)] {
  category: 'sessionDisposed'
}
info 21:4:38.684: Cancel all remaining cells true || Error || undefined
info 21:4:38.685: Cancel pending cells
info 21:4:38.685: Cell 7 executed with state Error
info 21:4:42.263: Execute Cell 8 /home/yongxin/projects/datascience/hw4/HW4.ipynb
info 21:4:43.721: Restart requested file:///home/yongxin/projects/datascience/hw4/HW4.ipynb
info 21:4:43.722: Restart kernel execution
info 21:4:43.722: Cancel pending cells
info 21:4:43.722: Starting raw kernel env (Python 3.9.5) for interpreter /home/yongxin/projects/datascience/hw4/env/bin/python
info 21:4:43.723: Restarting undefined
info 21:4:43.737: Kernel launching with ports 9040,9041,9042,9043,9044. Start port is 9000
info 21:4:43.839: Process Execution: > ~/projects/datascience/hw4/env/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> ~/projects/datascience/hw4/env/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
info 21:4:43.866: Adding env Variable PYTHONNOUSERSITE to /home/yongxin/projects/datascience/hw4/env/bin/python
info 21:4:43.886: Process Execution: > ~/projects/datascience/hw4/env/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9043 --control=9041 --hb=9040 --Session.signature_scheme="hmac-sha256" --Session.key=b"1c4b9564-837e-4e7d-9786-17ff70bd026d" --shell=9042 --transport="tcp" --iopub=9044 --f=/home/yongxin/.local/share/jupyter/runtime/kernel-649804juHfUC3GQuIH.json
> ~/projects/datascience/hw4/env/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9043 --control=9041 --hb=9040 --Session.signature_scheme="hmac-sha256" --Session.key=b"1c4b9564-837e-4e7d-9786-17ff70bd026d" --shell=9042 --transport="tcp" --iopub=9044 --f=/home/yongxin/.local/share/jupyter/runtime/kernel-649804juHfUC3GQuIH.json
info 21:4:43.886: Process Execution: cwd: ~/projects/datascience/hw4
cwd: ~/projects/datascience/hw4
info 21:4:44.240: ipykernel version 6.13.0 for /home/yongxin/projects/datascience/hw4/env/bin/python
info 21:4:44.240: ipykernel location ~/projects/datascience/hw4/env/lib/python3.9/site-packages/ipykernel/__init__.py for /home/yongxin/projects/datascience/hw4/env/bin/python
warn 21:4:44.734: StdErr from Kernel Process /home/yongxin/projects/datascience/hw4/env/lib/python3.9/site-packages/traitlets/traitlets.py:2389: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
/home/yongxin/projects/datascience/hw4/env/lib/python3.9/site-packages/traitlets/traitlets.py:2343: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '1c4b9564-837e-4e7d-9786-17ff70bd026d' instead of 'b"1c4b9564-837e-4e7d-9786-17ff70bd026d"'.
  warn(

info 21:4:44.746: Kernel Output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-649804juHfUC3GQuIH.json

info 21:4:45.123: Got new session 3c2106b2-987d-422c-b879-756ee7aa2f1c
info 21:4:45.123: Started new restart session
info 21:4:45.129: Executing silently Code (idle) = import sys\nprint(sys.executable)
info 21:4:45.437: Executing silently Code (completed) = import sys\nprint(sys.executable)
info 21:4:45.605: UpdateWorkingDirectoryAndPath in Kernel
info 21:4:45.605: Executing silently Code (idle) = import os\nimport sys\n%cd "/home/yongxin/projects/datascience/hw4"\nif os.getcwd() not in sys.path:
info 21:4:45.645: Executing silently Code (completed) = import os\nimport sys\n%cd "/home/yongxin/projects/datascience/hw4"\nif os.getcwd() not in sys.path:
info 21:4:45.645: Waiting for idle on (kernel): 3c2106b2-987d-422c-b879-756ee7aa2f1c -> idle
info 21:4:45.645: Finished waiting for idle on (kernel): 3c2106b2-987d-422c-b879-756ee7aa2f1c -> idle
info 21:4:46.762: Cancel all remaining cells true || Error || undefined
info 21:4:46.762: Cancel pending cells
info 21:4:46.762: Cell 8 executed with state Error
info 21:4:49.228: Execute Cell 7 /home/yongxin/projects/datascience/hw4/HW4.ipynb
info 21:4:52.748: Cancel all remaining cells true || Error || undefined
info 21:4:52.748: Cancel pending cells
info 21:4:52.748: Cell 7 executed with state Error
info 21:5:10.459: Execute Cell 7 /home/yongxin/projects/datascience/hw4/HW4.ipynb
info 21:5:13.400: Cell 7 executed with state Success
info 21:5:16.53: Execute Cell 8 /home/yongxin/projects/datascience/hw4/HW4.ipynb
error 21:6:3.787: Disposing session as kernel process died ExitCode: undefined, Reason: /home/yongxin/projects/datascience/hw4/env/lib/python3.9/site-packages/traitlets/traitlets.py:2389: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
/home/yongxin/projects/datascience/hw4/env/lib/python3.9/site-packages/traitlets/traitlets.py:2343: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '1c4b9564-837e-4e7d-9786-17ff70bd026d' instead of 'b"1c4b9564-837e-4e7d-9786-17ff70bd026d"'.
  warn(

info 21:6:3.788: Dispose Kernel process
error 21:6:3.788: Raw kernel process exited code: undefined
error 21:6:3.790: Error in waiting for cell to complete [Error: Canceled future for execute_request message before replies were done
	at t.KernelShellFutureHandler.dispose (/home/yongxin/.vscode-server/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:1322339)
	at /home/yongxin/.vscode-server/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:1341391
	at Map.forEach (<anonymous>)
	at v._clearKernelState (/home/yongxin/.vscode-server/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:1341376)
	at v.dispose (/home/yongxin/.vscode-server/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:1334858)
	at /home/yongxin/.vscode-server/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:537744
	at t.swallowExceptions (/home/yongxin/.vscode-server/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:920640)
	at u.dispose (/home/yongxin/.vscode-server/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:537722)
	at t.RawSession.dispose (/home/yongxin/.vscode-server/extensions/ms-toolsai.jupyter-2022.4.1021342353/out/extension.node.js:2:541401)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)]
warn 21:6:3.790: Cell completed with errors {
  message: 'Canceled future for execute_request message before replies were done'
}
info 21:6:3.792: Cancel all remaining cells true || Error || undefined
info 21:6:3.792: Cancel pending cells
info 21:6:3.792: Cell 8 executed with state Error
```

### Coding Language and Runtime Version

Python 3.9.5

### Language Extension Version (if applicable)

Python 3.9.5

### Anaconda Version (if applicable)

N/A

### Running Jupyter locally or remotely?

Remote

**Comment by DonJayamanne** [comment]
>  tried many times but the same result is returned.
> I wonder if it is a bug of vscode-jupyter on the remote server or a glitch in my remote server.

Thanks for filing this issue.
This looks like a a problem with the setup of the remote jupyter server.
With remote Jupyter servers, we merely send the code for execution to the Jupyter server, there's absolutely no setup involved at our end apart from connection.

I'd double check the setup, by setup i mean the installation of the sklean packages on the remove machine. If it works locally, then this means you have it installed correctly & on the remote machine things are either not setup correctly or the kernel is crashing for some other unknown reason. Unfortunately when dealing with remote Jupyter servers, we don't really know why kernels crash.

You might want to optionally look at the logs on the remote jupyter server to figure this out.
Closing this issue as this is specific to a package that's installed on a remote Jupyter server.

**Comment by yongxin-xu** [comment]
Thank you for the suggestions!
