### ISSUE TITLE
Unable to run cells 

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-jupyter#10262]
Testing #10183

I followed the setup steps in the test plan and ran `python -m notebook --no-browser --NotebookApp.allow_origin=*` in my test folder.

At the point where the test plan said to run cells I got an error: 
```
Failed to start the Kernel. 
Unhandled error. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
```

Jupyter log:
```
info 13:52:1.254: Creating server with url : http://127.0.0.1:8888/
info 13:52:2.544: Checking for server existence.
info 13:52:2.546: Checking for server usability.
info 13:52:2.546: Starting notebook server.
info 13:52:2.546: Connecting to server
info 13:52:2.548: Connecting to process server
info 13:52:2.548: Connecting server kernel http://127.0.0.1:8888/
Connecting to Jupyter server at http://127.0.0.1:8888/
info 13:52:2.549: Creating server with url : http://127.0.0.1:8888/
info 13:52:2.550: Connection complete server
info 13:52:2.551: Server started.
info 13:52:2.551: Creating server with url : http://127.0.0.1:8888/
info 13:52:2.625: Creating server with url : http://127.0.0.1:8888/
info 13:52:11.404: Execute Cell 1 /jupyter-notebook/test.ipynb
info 13:52:11.406: Starting Jupyter Session id = 'startUsingRemoteKernelSpec:4eb44a07e51cd9ce5e993df276d57b523b1d6aca9d6bc16dd1e0c4d525f41cb7..python3./C:/Users/alros/AppData/Local/Programs/Python/Python39/python.exe./.-m#ipykernel_launcher' for '/jupyter-notebook/test.ipynb' (disableUI=false)
error 13:52:11.759: Failed to change kernel, re-throwing Error: Unhandled error
warn 13:52:11.761: Error occurred while trying to start the kernel, options.disableUI=false Error: Unhandled error
warn 13:52:11.761: Kernel Error, context = start Error: Unhandled error
info 13:52:11.762: Dispose Kernel '/jupyter-notebook/test.ipynb' associated with '/jupyter-notebook/test.ipynb'
error 13:52:11.763: Error in execution Error: Unhandled error
error 13:52:11.764: Error in execution (get message for cell) Error: Unhandled error
info 13:52:13.776: Creating server with url : http://127.0.0.1:8888/
info 13:52:13.854: Creating server with url : http://127.0.0.1:8888/
```

**Comment by rchiodo** [comment]
@alexr00 your jupyter install may have a problem with it. In the console where jupyter was started did it log any errors?

**Comment by alexr00** [comment]
Yes:

```
[W 09:22:22.198 NotebookApp] 403 GET /api/kernels?1654240942190 (127.0.0.1) 2.080000ms referer=None
[W 09:22:27.662 NotebookApp] Forbidden
[W 09:22:27.663 NotebookApp] 403 GET /api/kernelspecs?1654240947652 (127.0.0.1) 2.540000ms referer=None
[I 09:22:41.134 NotebookApp] Creating new notebook in
[E 09:22:41.389 NotebookApp] Failed to run command:
    ['C:\\Users\\alros\\AppData\\Local\\Programs\\Python\\Python39\\python.exe', '-m', 'ipykernel_launcher', '-f', 'C:\\Users\\alros\\AppData\\Roaming\\jupyter\\runtime\\kernel-0a528b2f-5e94-4058-9260-7b3c276a80b4.json']
        PATH='<here it had my whole path>'
        with kwargs:
    {'stdin': -1, 'stdout': None, 'stderr': None, 'cwd': 'C:\\Users\\alros\\Documents\\testing\\jupyter-notebook', 'close_fds': False}

[E 09:22:41.390 NotebookApp] Uncaught exception POST /api/sessions?1654240961248 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/api/sessions?1654240961248', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "C:\Users\alros\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tornado\web.py", line 1704, in _execute
        result = await result
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 328, in __wakeup
        future.result()
      File "C:\Users\alros\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tornado\gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\alros\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\notebook\services\sessions\handlers.py", line 74, in post
        model = yield maybe_future(
      File "C:\Users\alros\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tornado\gen.py", line 762, in run
        value = future.result()
      File "C:\Users\alros\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tornado\gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\alros\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\notebook\services\sessions\sessionmanager.py", line 98, in create_session
        kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "C:\Users\alros\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tornado\gen.py", line 762, in run
        value = future.result()
      File "C:\Users\alros\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tornado\gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\alros\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\notebook\services\sessions\sessionmanager.py", line 110, in start_kernel_for_session
        kernel_id = yield maybe_future(
      File "C:\Users\alros\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tornado\gen.py", line 762, in run
        value = future.result()
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\futures.py", line 201, in result
        raise self._exception
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 256, in __step
        result = coro.send(None)
      File "C:\Users\alros\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\notebook\services\kernels\kernelmanager.py", line 176, in start_kernel
        kernel_id = await maybe_future(self.pinned_superclass.start_kernel(self, **kwargs))
      File "C:\Users\alros\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\jupyter_client\utils.py", line 26, in wrapped
        raise e
      File "C:\Users\alros\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\jupyter_client\utils.py", line 23, in wrapped
        return loop.run_until_complete(future)
      File "C:\Users\alros\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nest_asyncio.py", line 70, in run_until_complete
        return f.result()
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\futures.py", line 201, in result
        raise self._exception
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 256, in __step
        result = coro.send(None)
      File "C:\Users\alros\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\jupyter_client\multikernelmanager.py", line 186, in _async_start_kernel
        self._add_kernel_when_ready(kernel_id, km, ensure_async(km.start_kernel(**kwargs)))
      File "C:\Users\alros\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\jupyter_client\utils.py", line 26, in wrapped
        raise e
      File "C:\Users\alros\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\jupyter_client\utils.py", line 23, in wrapped
        return loop.run_until_complete(future)
      File "C:\Users\alros\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nest_asyncio.py", line 70, in run_until_complete
        return f.result()
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\futures.py", line 201, in result
        raise self._exception
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 256, in __step
        result = coro.send(None)
      File "C:\Users\alros\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\jupyter_client\manager.py", line 336, in _async_start_kernel
        await ensure_async(self._launch_kernel(kernel_cmd, **kw))
      File "C:\Users\alros\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\jupyter_client\utils.py", line 26, in wrapped
        raise e
      File "C:\Users\alros\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\jupyter_client\utils.py", line 23, in wrapped
        return loop.run_until_complete(future)
      File "C:\Users\alros\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\nest_asyncio.py", line 70, in run_until_complete
        return f.result()
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\futures.py", line 201, in result
        raise self._exception
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 256, in __step
        result = coro.send(None)
      File "C:\Users\alros\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\jupyter_client\manager.py", line 257, in _async_launch_kernel
        connection_info = await self.provisioner.launch_kernel(kernel_cmd, **kw)
      File "C:\Users\alros\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\jupyter_client\provisioning\local_provisioner.py", line 179, in launch_kernel
        self.process = launch_kernel(cmd, **scrubbed_kwargs)
      File "C:\Users\alros\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\jupyter_client\launcher.py", line 169, in launch_kernel
        raise ex
      File "C:\Users\alros\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\jupyter_client\launcher.py", line 157, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 951, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1420, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    FileNotFoundError: [WinError 2] The system cannot find the file specified
[W 09:22:41.491 NotebookApp] Unhandled error
[E 09:22:41.492 NotebookApp] {
      "Host": "localhost:8888",
      "Accept": "*/*",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5070.0 Safari/537.36"
    }
```

**Comment by rchiodo** [comment]
Does this path exist?

```
C:\\Users\\alros\\AppData\\Local\\Programs\\Python\\Python39\\python.exe
```

If it doesn't, this sounds like the same issue Isidor was having. Your default install of jupyter is from an old environment. This file here is probably pointing to the old environment:

```
C:\\Users\alros\\AppData\\Roaming\\jupyter\\kernels\\python3\\kernel.json
```

**Comment by alexr00** [comment]
This path exists, but not the `python.exe`:
```
C:\\Users\\alros\\AppData\\Local\\Programs\\Python\\Python39
```

This file does indeed point to `C:\\Users\\alros\\AppData\\Local\\Programs\\Python\\Python39\\python.exe`, which doesn't exist.
```
C:\\Users\alros\\AppData\\Roaming\\jupyter\\kernels\\python3\\kernel.json
```
