### ISSUE TITLE
Pre-release builds are broken

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#10729]
From what I can tell we can build pre-releases from the commit before this, but not after this 24eaf0269709e24dfe1a197c7bff2454ada4bcce

Basically broken after this PR https://github.com/microsoft/vscode-jupyter/pull/10712

**Comment by sadasant** [comment]
I started investigating this, but I couldn't think of anything specific that could be causing the problem.

In the short run, we can revert my PR and get the build out. How does that sound?

I have also asked @TylerLeonhardt for help.

**Comment by IanMatthewHuff** [comment]
You might already have this, but this looks like the error from the translation tools:
```
2022-07-08T09:09:24.0994773Z [09:09:24] TypeError: Cannot read properties of undefined (reading 'length')
2022-07-08T09:09:24.0995836Z     at encodeEntities (/mnt/vss/_work/1/translations-tools/node_modules/vscode-nls-dev/lib/main.js:544:31)
2022-07-08T09:09:24.0996673Z     at XLF.addFile (/mnt/vss/_work/1/translations-tools/node_modules/vscode-nls-dev/lib/main.js:355:29)
2022-07-08T09:09:24.0997552Z     at Stream.<anonymous> (/mnt/vss/_work/1/translations-tools/node_modules/vscode-nls-dev/lib/main.js:477:22)
2022-07-08T09:09:24.0998357Z     at Stream.stream.write (/mnt/vss/_work/1/translations-tools/node_modules/through/index.js:26:11)
2022-07-08T09:09:24.0999209Z     at DestroyableTransform.ondata (/mnt/vss/_work/1/translations-tools/node_modules/readable-stream/lib/_stream_readable.js:619:20)
2022-07-08T09:09:24.0999828Z     at DestroyableTransform.emit (node:events:390:28)
2022-07-08T09:09:24.1000392Z     at DestroyableTransform.emit (node:domain:537:15)
2022-07-08T09:09:24.1001189Z     at addChunk (/mnt/vss/_work/1/translations-tools/node_modules/readable-stream/lib/_stream_readable.js:291:12)
2022-07-08T09:09:24.1002107Z     at readableAddChunk (/mnt/vss/_work/1/translations-tools/node_modules/readable-stream/lib/_stream_readable.js:278:11)
2022-07-08T09:09:24.1002894Z     at DestroyableTransform.Readable.push (/mnt/vss/_work/1/translations-tools/node_modules/readable-stream/lib/_stream_readable.js:245:10)
```

**Comment by TylerLeonhardt** [comment]
please don't revert this I have a fix
