### ISSUE TITLE
No debugger available after restarting kernel

### ISSUE THREAD

**Issue by alandema** [microsoft/vscode-jupyter#10741]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

-> Debug a cell
-> Stop debugger with disconnect (didn't find any other way to stop debugger)

![2022-07-08 10_59_48-Window](https://user-images.githubusercontent.com/68517641/178007000-0d446d79-077f-42d0-8915-6c82c97e65f4.png)

The cell dropdown menu with debug option disappears. Need to run the cell to get que dropdown menu back.

-> If restar kernel

![2022-07-08 10_58_13-Window](https://user-images.githubusercontent.com/68517641/178006568-572260e3-0cde-46ca-a1d9-3d24444522be.png)

These toasts appears. Sometimes it does not affect anything, but sometimes you need to close and reopen VSCode to be able to run debugger again.

### VS Code Version

1.69

### Jupyter Extension Version

v2022.7.1001902022

### Coding Language and Runtime Version

Python 3.8.6

### Running Jupyter locally or remotely?

Local

**Comment by thisfro** [comment]
I have the excact same problem.

Also using vscode 1.69 and Jupyter extension v2022.6.1001902341.

**Comment by thisfro** [comment]
It seems it always fails when I try to restart the debugging (which I should not do apparently):
```
Visual Studio Code (1.69.0, undefined, desktop)
Jupyter Extension Version: 2022.6.1001902341.
Python Extension Version: 2022.10.0.
Workspace folder /Users/thisfro/repos/jupyter_notebooks
info 14:9:17.278: ZMQ install verified.
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 14:9:17.681: LSP Notebooks experiment is enabled
info 14:9:18.144: Starting Jupyter Session id = 'startUsingPythonInterpreter:.jvsc74a57bd0f0d028b0a62532fd91a233a9564ac4be06422152fd78517d1120a82d2c5ff505./usr/local/Caskroom/miniconda/base/envs/base/python./usr/local/Caskroom/miniconda/base/envs/base/python.-m#ipykernel_launcher' (Python Path: /usr/local/Caskroom/miniconda/base/envs/base, EnvType: Conda, EnvName: 'base', Version: 3.9.12) for '/Users/thisfro/repos/jupyter_notebooks/lidar/example_comparison.ipynb' (disableUI=true)
info 14:9:18.146: Creating raw notebook for resource '/Users/thisfro/repos/jupyter_notebooks/lidar/example_comparison.ipynb'
info 14:9:18.146: Computing working directory for resource '/Users/thisfro/repos/jupyter_notebooks/lidar/example_comparison.ipynb'
info 14:9:18.188: Process Execution: > /usr/local/Caskroom/miniconda/base/envs/base/bin/python -m pip list
> /usr/local/Caskroom/miniconda/base/envs/base/bin/python -m pip list
info 14:9:18.196: Starting raw kernel 'base (Python 3.9.12)' for interpreter /usr/local/Caskroom/miniconda/base/envs/base/bin/python
info 14:9:18.216: Kernel launching with ports 9000,9001,9002,9003,9004. Start port is 9000
info 14:9:18.232: Process Execution: > /usr/local/Caskroom/miniconda/base/envs/base/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> /usr/local/Caskroom/miniconda/base/envs/base/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
info 14:9:18.267: Process Execution: > /usr/local/Caskroom/miniconda/base/envs/base/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"ab08833b-2976-48f3-b19a-7d5132a96998" --shell=9002 --transport="tcp" --iopub=9004 --f=/Users/thisfro/Library/Jupyter/runtime/kernel-v2-19539vmXI3tIJE7CU.json
> /usr/local/Caskroom/miniconda/base/envs/base/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"ab08833b-2976-48f3-b19a-7d5132a96998" --shell=9002 --transport="tcp" --iopub=9004 --f=/Users/thisfro/Library/Jupyter/runtime/kernel-v2-19539vmXI3tIJE7CU.json
info 14:9:18.267: Process Execution: cwd: ~/repos/jupyter_notebooks/lidar
cwd: ~/repos/jupyter_notebooks/lidar
info 14:9:18.582: ipykernel version 6.9.1 for /usr/local/Caskroom/miniconda/base/envs/base/bin/python
info 14:9:18.582: ipykernel location /usr/local/Caskroom/miniconda/base/envs/base/lib/python3.9/site-packages/ipykernel/__init__.py for /usr/local/Caskroom/miniconda/base/envs/base/bin/python
info 14:9:18.876: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
info 14:9:18.893: Preferred Remote kernel for /Users/thisfro/repos/jupyter_notebooks/lidar/example_comparison.ipynb is undefined
info 14:9:18.893: Find preferred kernel for /Users/thisfro/repos/jupyter_notebooks/lidar/example_comparison.ipynb with metadata {"kernelspec":{"display_name":"Python 3.9.12 ('base')","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.12"},"orig_nbformat":4,"vscode":{"interpreter":{"hash":"f0d028b0a62532fd91a233a9564ac4be06422152fd78517d1120a82d2c5ff505"}}} & preferred interpreter /usr/local/Caskroom/miniconda/base/envs/base/bin/python
info 14:9:18.896: Preferred Remote kernel for /Users/thisfro/repos/jupyter_notebooks/lidar/example_comparison.ipynb is undefined
info 14:9:18.896: Preferred kernel .jvsc74a57bd0f0d028b0a62532fd91a233a9564ac4be06422152fd78517d1120a82d2c5ff505./usr/local/Caskroom/miniconda/base/envs/base/python./usr/local/Caskroom/miniconda/base/envs/base/python.-m#ipykernel_launcher is exact match
info 14:9:18.899: PreferredConnection: .jvsc74a57bd0f0d028b0a62532fd91a233a9564ac4be06422152fd78517d1120a82d2c5ff505./usr/local/Caskroom/miniconda/base/envs/base/python./usr/local/Caskroom/miniconda/base/envs/base/python.-m#ipykernel_launcher found for NotebookDocument: /Users/thisfro/repos/jupyter_notebooks/lidar/example_comparison.ipynb
info 14:9:19.203: Widget Message: Received IPyWidgetMessages.IPyWidgets_IsReadyRequest
warn 14:9:19.412: StdErr from Kernel Process /usr/local/Caskroom/miniconda/base/envs/base/lib/python3.9/site-packages/traitlets/traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
/usr/local/Caskroom/miniconda/base/envs/base/lib/python3.9/site-packages/traitlets/traitlets.py:2157: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use 'ab08833b-2976-48f3-b19a-7d5132a96998' instead of 'b"ab08833b-2976-48f3-b19a-7d5132a96998"'.
  warn(

info 14:9:19.429: Kernel Output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-v2-19539vmXI3tIJE7CU.json

info 14:9:19.616: Started kernel base (Python 3.9.12)., (Raw session started and connected)
info 14:9:19.617: Finished connecting e0631417-5d56-49ed-ae04-d727d5ab4592
info 14:9:19.619: UpdateWorkingDirectoryAndPath in Kernel
info 14:9:19.620: Executing silently Code (idle) = import os\nimport sys\n%cd "/Users/thisfro/repos/jupyter_notebooks/lidar"\nif os.getcwd() not in sys.
info 14:9:19.641: Executing silently Code (completed) = import os\nimport sys\n%cd "/Users/thisfro/repos/jupyter_notebooks/lidar"\nif os.getcwd() not in sys. with 1 output(s)
info 14:9:19.641: Waiting for idle on (kernel): 1ca6c3ea-082d-4f27-8813-f6a3c8c57db9 -> idle
info 14:9:19.641: Finished waiting for idle on (kernel): 1ca6c3ea-082d-4f27-8813-f6a3c8c57db9 -> idle
info 14:9:19.695: Widget Message: Received IPyWidgets_kernelOptions in ScriptManager
info 14:9:19.710: Widget Message: Received IPyWidgetMessages.IPyWidgets_kernelOptions
info 14:9:19.994: Widget Message: data-base-url set to https://file%2B.vscode-resource.vscode-cdn.net/Users/thisfro/.vscode/extensions/ms-toolsai.jupyter-2022.6.1001902341/tmp/scripts/92faed4c6e6c2e81a0486f70453eb2a7381d24d053dd5d80c2f2119786e677a5/jupyter
info 14:9:20.96: Preferred Remote kernel for /Users/thisfro/repos/jupyter_notebooks/lidar/example_comparison.ipynb is undefined
info 14:9:20.96: Find preferred kernel for /Users/thisfro/repos/jupyter_notebooks/lidar/example_comparison.ipynb with metadata {"kernelspec":{"display_name":"Python 3.9.12 ('base')","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.12"},"orig_nbformat":4,"vscode":{"interpreter":{"hash":"f0d028b0a62532fd91a233a9564ac4be06422152fd78517d1120a82d2c5ff505"}}} & preferred interpreter /usr/local/Caskroom/miniconda/base/envs/base/bin/python
info 14:9:20.99: Preferred Remote kernel for /Users/thisfro/repos/jupyter_notebooks/lidar/example_comparison.ipynb is undefined
info 14:9:20.99: Preferred kernel .jvsc74a57bd0f0d028b0a62532fd91a233a9564ac4be06422152fd78517d1120a82d2c5ff505./usr/local/Caskroom/miniconda/base/envs/base/python./usr/local/Caskroom/miniconda/base/envs/base/python.-m#ipykernel_launcher is exact match
info 14:9:20.104: Preferred Remote kernel for /Users/thisfro/repos/jupyter_notebooks/lidar/example_comparison.ipynb is undefined
info 14:9:26.237: Loading webview. View is notset
info 14:9:26.238: Loading web view...
info 14:9:26.238: Webview panel created.
info 14:9:26.589: Web view react rendered
info 14:9:26.615: Executing silently Code (idle) = def _VSCODE_getVariable(what_to_get, is_debugging, *args):\n# Query Jupyter server for the info
info 14:9:26.615: Executing silently Code (idle) = def _VSCODE_getVariable(what_to_get, is_debugging, *args):\n# Query Jupyter server for the info
info 14:9:26.635: Executing silently Code (completed) = def _VSCODE_getVariable(what_to_get, is_debugging, *args):\n# Query Jupyter server for the info with 1 output(s)
info 14:9:26.655: Executing silently Code (completed) = def _VSCODE_getVariable(what_to_get, is_debugging, *args):\n# Query Jupyter server for the info with 1 output(s)
info 14:9:54.255: Execute Cell 0 /Users/thisfro/repos/jupyter_notebooks/lidar/example_comparison.ipynb
info 14:9:54.256: Execute Cell 1 /Users/thisfro/repos/jupyter_notebooks/lidar/example_comparison.ipynb
info 14:9:54.256: Execute Cell 2 /Users/thisfro/repos/jupyter_notebooks/lidar/example_comparison.ipynb
info 14:9:54.256: Execute Cell 3 /Users/thisfro/repos/jupyter_notebooks/lidar/example_comparison.ipynb
info 14:9:54.256: Execute Cell 4 /Users/thisfro/repos/jupyter_notebooks/lidar/example_comparison.ipynb
info 14:9:54.256: Execute Cell 5 /Users/thisfro/repos/jupyter_notebooks/lidar/example_comparison.ipynb
info 14:9:54.256: Execute Cell 6 /Users/thisfro/repos/jupyter_notebooks/lidar/example_comparison.ipynb
info 14:9:54.256: Execute Cell 7 /Users/thisfro/repos/jupyter_notebooks/lidar/example_comparison.ipynb
info 14:9:54.256: Execute Cell 8 /Users/thisfro/repos/jupyter_notebooks/lidar/example_comparison.ipynb
info 14:9:54.256: Execute Cell 9 /Users/thisfro/repos/jupyter_notebooks/lidar/example_comparison.ipynb
info 14:9:56.568: Cell 0 executed with state Success
info 14:9:56.603: Cell 1 executed with state Success
info 14:9:58.439: Cancel all remaining cells true || Error || undefined
info 14:9:58.439: Cancel pending cells
info 14:9:58.440: Cell 2 executed with state Error
info 14:9:58.440: Cell 3 executed with state Idle
info 14:9:58.440: Cell 4 executed with state Idle
info 14:9:58.440: Cell 5 executed with state Idle
info 14:9:58.440: Cell 6 executed with state Idle
info 14:9:58.440: Cell 7 executed with state Idle
info 14:9:58.440: Cell 8 executed with state Idle
info 14:9:58.440: Cell 9 executed with state Idle
info 14:10:1.500: Executing silently Code (idle) = import ipykernel\nprint(ipykernel.__version__)
info 14:10:1.508: Executing silently Code (completed) = import ipykernel\nprint(ipykernel.__version__) with 1 output(s)
info 14:10:2.153: Executing silently Code (idle) = import debugpy\ndebugpy.debug_this_thread()
info 14:10:2.184: Executing silently Code (completed) = import debugpy\ndebugpy.debug_this_thread() with 0 output(s)
info 14:10:2.309: Execute Cell 2 /Users/thisfro/repos/jupyter_notebooks/lidar/example_comparison.ipynb
info 14:10:15.585: Cancel all remaining cells true || Error || undefined
info 14:10:15.585: Cancel pending cells
info 14:10:15.585: Cell 2 executed with state Error
info 14:10:15.848: Executing silently Code (idle) = import os\n_VSCODE_fileList = ["/var/folders/7v/6l6vgrcn58jdcjv18grk6w8r0000gn/T/ipykernel_19684/4132
info 14:10:15.858: Executing silently Code (completed) = import os\n_VSCODE_fileList = ["/var/folders/7v/6l6vgrcn58jdcjv18grk6w8r0000gn/T/ipykernel_19684/4132 with 0 output(s)
info 14:13:2.35: Execute Cell 1 /Users/thisfro/repos/jupyter_notebooks/lidar/example_comparison.ipynb
info 14:13:2.70: Cell 1 executed with state Success
info 14:13:3.614: Execute Cell 2 /Users/thisfro/repos/jupyter_notebooks/lidar/example_comparison.ipynb
info 14:13:4.159: Cancel all remaining cells true || Error || undefined
info 14:13:4.159: Cancel pending cells
info 14:13:4.159: Cell 2 executed with state Error
info 14:13:13.719: Executing silently Code (idle) = import ipykernel\nprint(ipykernel.__version__)
info 14:13:13.727: Executing silently Code (completed) = import ipykernel\nprint(ipykernel.__version__) with 1 output(s)
info 14:13:13.860: Executing silently Code (idle) = import debugpy\ndebugpy.debug_this_thread()
info 14:13:13.878: Executing silently Code (completed) = import debugpy\ndebugpy.debug_this_thread() with 0 output(s)
info 14:13:13.975: Execute Cell 2 /Users/thisfro/repos/jupyter_notebooks/lidar/example_comparison.ipynb
info 14:13:35.290: Cancel all remaining cells true || Error || undefined
info 14:13:35.290: Cancel pending cells
info 14:13:35.291: Cell 2 executed with state Error
info 14:13:35.575: Executing silently Code (idle) = import os\n_VSCODE_fileList = ["/var/folders/7v/6l6vgrcn58jdcjv18grk6w8r0000gn/T/ipykernel_19684/4132
info 14:13:35.586: Executing silently Code (completed) = import os\n_VSCODE_fileList = ["/var/folders/7v/6l6vgrcn58jdcjv18grk6w8r0000gn/T/ipykernel_19684/4132 with 0 output(s)
info 14:13:46.241: Execute Cell 1 /Users/thisfro/repos/jupyter_notebooks/lidar/example_comparison.ipynb
info 14:13:46.279: Cell 1 executed with state Success
info 14:13:48.125: Execute Cell 2 /Users/thisfro/repos/jupyter_notebooks/lidar/example_comparison.ipynb
info 14:13:48.631: Cancel all remaining cells true || Error || undefined
info 14:13:48.631: Cancel pending cells
info 14:13:48.631: Cell 2 executed with state Error
info 14:13:50.330: Executing silently Code (idle) = import ipykernel\nprint(ipykernel.__version__)
info 14:13:50.338: Executing silently Code (completed) = import ipykernel\nprint(ipykernel.__version__) with 1 output(s)
info 14:13:50.504: Executing silently Code (idle) = import debugpy\ndebugpy.debug_this_thread()
info 14:13:50.520: Executing silently Code (completed) = import debugpy\ndebugpy.debug_this_thread() with 0 output(s)
info 14:13:50.590: Execute Cell 2 /Users/thisfro/repos/jupyter_notebooks/lidar/example_comparison.ipynb
info 14:13:54.109: Cancel all remaining cells true || Error || undefined
info 14:13:54.109: Cancel pending cells
info 14:13:54.109: Cell 2 executed with state Error
error 14:13:54.232: Debug sessions should start only from the cell toolbar command
info 14:13:54.386: Executing silently Code (idle) = import os\n_VSCODE_fileList = ["/var/folders/7v/6l6vgrcn58jdcjv18grk6w8r0000gn/T/ipykernel_19684/4132
info 14:13:54.396: Executing silently Code (completed) = import os\n_VSCODE_fileList = ["/var/folders/7v/6l6vgrcn58jdcjv18grk6w8r0000gn/T/ipykernel_19684/4132 with 0 output(s)
info 14:13:59.128: Execute Cell 1 /Users/thisfro/repos/jupyter_notebooks/lidar/example_comparison.ipynb
info 14:13:59.184: Cell 1 executed with state Success
info 14:14:0.177: Execute Cell 2 /Users/thisfro/repos/jupyter_notebooks/lidar/example_comparison.ipynb
info 14:14:0.757: Cancel all remaining cells true || Error || undefined
info 14:14:0.757: Cancel pending cells
info 14:14:0.757: Cell 2 executed with state Error
warn 14:17:44.49: Error occurred while trying to restart the kernel, options.disableUI=false ErrorNoTelemetry: debug session not found
    at S.$customDebugAdapterRequest (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1696:7703)
    at v._doInvokeHandler (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1705:13079)
    at v._invokeHandler (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1705:12761)
    at v._receiveRequest (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1705:11531)
    at v._receiveOneMessage (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1705:10233)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1705:8340
    at b.invoke (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:145)
    at r.deliver (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:2266)
    at o.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:1844)
    at a.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:544:19267)
    at g._receiveMessage (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:544:23854)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:544:21388
    at b.invoke (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:145)
    at r.deliver (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:2266)
    at o.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:1844)
    at o.acceptChunk (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:544:16098)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:544:15228
    at Socket.O (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3173:22267)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
warn 14:17:44.51: Kernel Error, context = restart ErrorNoTelemetry: debug session not found
    at S.$customDebugAdapterRequest (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1696:7703)
    at v._doInvokeHandler (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1705:13079)
    at v._invokeHandler (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1705:12761)
    at v._receiveRequest (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1705:11531)
    at v._receiveOneMessage (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1705:10233)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1705:8340
    at b.invoke (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:145)
    at r.deliver (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:2266)
    at o.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:1844)
    at a.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:544:19267)
    at g._receiveMessage (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:544:23854)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:544:21388
    at b.invoke (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:145)
    at r.deliver (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:2266)
    at o.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:1844)
    at o.acceptChunk (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:544:16098)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:544:15228
    at Socket.O (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3173:22267)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
info 14:17:44.62: Process Execution: > /usr/local/Caskroom/miniconda/base/envs/base/bin/python -c "import ipykernel"
> /usr/local/Caskroom/miniconda/base/envs/base/bin/python -c "import ipykernel"
info 14:17:44.375: Dispose Kernel '/Users/thisfro/repos/jupyter_notebooks/lidar/example_comparison.ipynb' associated with '/Users/thisfro/repos/jupyter_notebooks/lidar/example_comparison.ipynb'
info 14:17:44.375: Cancel pending cells
```

Do you observe this too @alandema?

**Comment by amunger** [comment]
Thanks for the bug report, we must not be handling the state change correctly.

I can't get the specific behavior in the description, but if I disconnect an active debug session, and then restart the kernel, I see some unexpected behavior that's most likely related. (prompt to install IPykernel)
