### ISSUE TITLE
Exception when view value in data viewer

### ISSUE THREAD

**Issue by yellowmarlboro** [microsoft/vscode-jupyter#10789]
## Environment data

-   VS Code version: 1.69.1
-   Jupyter Extension version (available under the Extensions sidebar): v2022.6.1101950301
-   Python Extension version (available under the Extensions sidebar): v2022.10.0
-   OS (Windows | Mac | Linux distro) and version: ubuntu22.04 wsl2
-   Python and/or Anaconda version: python3.8.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Remote (wsl)

## Actual behaviour

when i'm debugging my project and i click **view value in data viewer**, it happend error 

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Visual Studio Code (1.69.1, wsl, desktop)
Jupyter Extension Version: 2022.6.1101950301.
Python Extension Version: 2022.10.0.
Multiple Workspace folders opened ...
info 13:51:14.611: ZMQ install verified.
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 13:51:16.499: LSP Notebooks experiment is disabled -- not in treatment group
info 13:51:17.651: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
info 13:51:18.915: Process Execution: > ~/.pyenv/versions/3.8.6/envs/Risk_py38/bin/python -m pip list
> ~/.pyenv/versions/3.8.6/envs/Risk_py38/bin/python -m pip list
info 13:54:18.889: Found debugAdapterPython on Debug Configuration to use
error 13:54:18.892: [TypeError: t.startsWith is not a function
	at C.getDebugAdapterPython (/home/.../.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1101950301/out/extension.node.js:39:274390)
	at C.onVariablePanelShowDataViewerRequest (/home/.../.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1101950301/out/extension.node.js:39:273113)
	at C.<anonymous> (/home/.../.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1101950301/out/extension.node.js:24:464889)
	at o._executeContributedCommand (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:85:62871)
	at o.$executeContributedCommand (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:85:63575)
	at s._doInvokeHandler (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:95:13708)
	at s._invokeHandler (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:95:13390)
	at s._receiveRequest (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:95:12159)
	at s._receiveOneMessage (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:95:10853)
	at /home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:95:8957
	at b.invoke (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at a.fire (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:69:18976)
	at /home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:111:34679
	at b.invoke (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at a.fire (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:69:18976)
	at r._receiveMessage (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:69:23563)
	at /home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:69:21097
	at b.invoke (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at p.acceptChunk (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:69:15807)
	at /home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:69:14937
	at b.invoke (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at f._processReadQueue (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:111:21271)
	at f.acceptFrame (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:111:20927)
	at v._acceptChunk (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:111:18891)
	at /home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:111:15880
	at Socket.R (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:111:13763)
	at Socket.emit (node:events:390:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at TCP.onStreamRead (node:internal/stream_base_commons:199:23)]
warn 13:54:18.893: DataScience Error [TypeError: t.startsWith is not a function
	at C.getDebugAdapterPython (/home/.../.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1101950301/out/extension.node.js:39:274390)
	at C.onVariablePanelShowDataViewerRequest (/home/.../.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1101950301/out/extension.node.js:39:273113)
	at C.<anonymous> (/home/.../.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1101950301/out/extension.node.js:24:464889)
	at o._executeContributedCommand (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:85:62871)
	at o.$executeContributedCommand (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:85:63575)
	at s._doInvokeHandler (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:95:13708)
	at s._invokeHandler (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:95:13390)
	at s._receiveRequest (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:95:12159)
	at s._receiveOneMessage (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:95:10853)
	at /home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:95:8957
	at b.invoke (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at a.fire (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:69:18976)
	at /home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:111:34679
	at b.invoke (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at a.fire (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:69:18976)
	at r._receiveMessage (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:69:23563)
	at /home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:69:21097
	at b.invoke (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at p.acceptChunk (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:69:15807)
	at /home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:69:14937
	at b.invoke (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at p.fire (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at f._processReadQueue (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:111:21271)
	at f.acceptFrame (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:111:20927)
	at v._acceptChunk (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:111:18891)
	at /home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:111:15880
	at Socket.R (/home/.../.vscode-server/bin/.../out/vs/workbench/api/node/extensionHostProcess.js:111:13763)
	at Socket.emit (node:events:390:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at TCP.onStreamRead (node:internal/stream_base_commons:199:23)]

```

</p>
</details>

**Comment by rchiodo** [comment]
Thanks for the bug. 

Looks like a problem right here:
https://github.com/microsoft/vscode-jupyter/blob/923275a8017f1b9756aa0310038479f516ffd937/src/webviews/extension-side/dataviewer/dataViewerCommandRegistry.ts#L150

`debugConfiguration.python` may not exist or be a string.

**Comment by ItamarShDev** [comment]
Can we set this from settings?  
I do have python set up in the debug configuration, yet the error persist 
![image](https://user-images.githubusercontent.com/953371/178913078-2cf6a466-f663-44b8-88a9-dcead288f991.png)

**Comment by DonJayamanne** [comment]
@IanMatthewHuff /cc I think you were looking into some issues related to this.

**Comment by IanMatthewHuff** [comment]
Ahh, this is on me. I messed that up merging with the python code to pull the path. It should just be using the pythonPath not the debugConfiguration.python.
