### ISSUE TITLE
VS Code Jupyter Notebook Session Cannot Generate Request

### ISSUE THREAD

**Issue by ydmykr** [microsoft/vscode-jupyter#10826]
Doing an image classifier project on my Mac. Any cell I run after the:

```
train_x=train_x/255.0
test_x=test_x/255.0
val_x=val_x/255.0
```

gives

```
Error: Session cannot generate requests
Error: Session cannot generate requests
at w.executeCodeCell (/Users/ethan/.vscode/extensions/ms-toolsai.jupyter-2021.8.2041215044/out/client/extension.js:52:301310)
at w.execute (/Users/ethan/.vscode/extensions/ms-toolsai.jupyter-2021.8.2041215044/out/client/extension.js:52:300703)
at w.start (/Users/ethan/.vscode/extensions/ms-toolsai.jupyter-2021.8.2041215044/out/client/extension.js:52:296367)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async t.CellExecutionQueue.executeQueuedCells (/Users/ethan/.vscode/extensions/ms-toolsai.jupyter-2021.8.2041215044/out/client/extension.js:52:311160)
at async t.CellExecutionQueue.start (/Users/ethan/.vscode/extensions/ms-toolsai.jupyter-2021.8.2041215044/out/client/extension.js:52:310700)
```

How would I go about fixing this?

**Comment by amunger** [comment]
closing for now, let us know if this is still an issue after updating
