### ISSUE TITLE
Script source for Widget jupyter-matplotlib@^0.7.4 not found

### ISSUE THREAD

**Issue by godsic** [microsoft/vscode-jupyter#1087]
```
Script source for Widget jupyter-matplotlib@^0.7.4 not found
```
due to
```
Error 2020-11-12 14:25:42: Error downloading from CDN [Error: Parse Error: JS Exception
	at TLSSocket.socketOnData (_http_client.js:456:22)
	at TLSSocket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at TLSSocket.Readable.push (_stream_readable.js:224:10)
	at TLSWrap.onStreamRead (internal/stream_base_commons.js:181:23)] {
  bytesParsed: 136233,
  code: 'HPE_JS_EXCEPTION',
  reason: 'JS Exception',
  rawPacket: <Buffer 7d 2c 22 6a 75 70 79 74 65 72 6c 61 62 22 3a 7b 22 65 78 74 65 6e 73 69 6f 6e 22 3a 22 73 72 63 2f 6c 61 62 5f 65 78 74 65 6e 73 69 6f 6e 22 7d 2c 22 ... 1319 more bytes>
}
```
My `settings.json` contains
```json
{
    "jupyter.logging.level": "debug",
    "jupyter.widgetScriptSources": [
        "unpkg.com",
        "jsdelivr.com"
    ],
}
```
`jupyter --version`:
```
jupyter core     : 4.6.3
jupyter-notebook : 6.1.5
qtconsole        : not installed
ipython          : 7.16.1
ipykernel        : 5.3.4
jupyter client   : 6.1.7
jupyter lab      : 2.2.9
nbconvert        : 6.0.7
ipywidgets       : 7.5.1
nbformat         : 5.0.8
traitlets        : 4.3.3
```
`jupyter labextension list`
```
JupyterLab v2.2.9
Known labextensions:
   app dir: /home/mykola/.local/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        jupyter-matplotlib v0.7.4  enabled  OK
```
`pip3 list --user`:
```
Package             Version
------------------- ---------
appdirs             1.4.4
apptools            4.5.0
argon2-cffi         20.1.0
async-generator     1.10
attrs               20.3.0
backcall            0.2.0
bleach              3.2.1
certifi             2020.6.20
cffi                1.14.3
chardet             3.0.4
cycler              0.10.0
defusedxml          0.6.0
distlib             0.3.1
entrypoints         0.3
envisage            4.9.2
filelock            3.0.12
idna                2.10
importlib-metadata  2.0.0
importlib-resources 3.3.0
ipykernel           5.3.4
ipympl              0.5.8
ipython             7.16.1
ipython-genutils    0.2.0
ipywidgets          7.5.1
jedi                0.17.2
Jinja2              2.11.2
json5               0.9.5
jsonschema          3.2.0
jupyter-client      6.1.7
jupyter-core        4.6.3
jupyterlab          2.2.9
jupyterlab-pygments 0.1.2
jupyterlab-server   1.2.0
kiwisolver          1.3.1
MarkupSafe          1.1.1
matplotlib          3.3.2
mayavi              4.7.2
mistune             0.8.4
nbclient            0.5.1
nbconvert           6.0.7
nbformat            5.0.8
nest-asyncio        1.4.3
notebook            6.1.5
numpy               1.19.4
packaging           20.4
pandas              1.1.4
pandocfilters       1.4.3
parso               0.7.1
pexpect             4.8.0
pickleshare         0.7.5
Pillow              8.0.1
pip                 20.2.4
pipenv              2020.8.13
prometheus-client   0.8.0
prompt-toolkit      3.0.8
ptyprocess          0.6.0
pycparser           2.20
pyface              7.1.0
Pygments            2.7.2
pyparsing           2.4.7
PyQt5               5.15.1
PyQt5-sip           12.8.1
pyrsistent          0.17.3
python-dateutil     2.8.1
pytz                2020.4
pyzmq               19.0.2
requests            2.25.0
scipy               1.5.3
Send2Trash          1.5.0
terminado           0.9.1
testpath            0.4.4
tornado             6.1
traitlets           4.3.3
traits              6.1.1
traitsui            7.1.0
urllib3             1.26.1
virtualenv          20.1.0
virtualenv-clone    0.5.4
vtk                 9.0.1
wcwidth             0.2.5
webencodings        0.5.1
widgetsnbextension  3.5.1
zipp                3.4.0
```

**Comment by joyceerhl** [comment]
@godsic, sorry for the delayed response on this thread. What platform were you on when you encountered this error? We are trying to track down a similar error in #4246.

**Comment by godsic** [comment]
@joyceerhl No worries at all, the platform is `linux`. In particular, a remote ssh session from Fedora 34 client to CentOS 8 host.

**Comment by DonJayamanne** [comment]
@godsic Apologies for not getting back to you. Are you still experiencing this issue?

**Comment by godsic** [comment]
@DonJayamanne Just update to `1.53.2` and latest `Jupyter` extensions and everything works. Thanks!
