### ISSUE TITLE
jupyter notebook interactive window: notebook controller is NOT associated to notebook 

### ISSUE THREAD

**Issue by sbland** [microsoft/vscode-jupyter#10887]
Issue Type: <b>Bug</b>

When trying to run any python code in jupyter interactive window I get the following error: `notebook controller is NOT associated to notebook: vscode-interactive:Interactive-2.interactive. `

This only occurs on a single workspace and happened randomly after workspace had previously been working.

Restarting vscode did not help. I do not have the issue in jupyter notebooks or other workspaces. It was working ok this morning.

Full error: 
```
warn 13:2:40.569: DataScience Error [Error: notebook controller is NOT associated to notebook: vscode-interactive:Interactive-2.interactive
	at Object.createNotebookCellExecution (/home/ubu/.vscode-server/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/vs/workbench/api/node/extensionHostProcess.js:87:104239)
	at Function.create (/home/ubu/.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1201981810/out/extension.node.js:2:1979904)
	at Function.getOrCreate (/home/ubu/.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1201981810/out/extension.node.js:2:1979775)
	at new v (/home/ubu/.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1201981810/out/extension.node.js:2:1972464)
	at Function.fromCell (/home/ubu/.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1201981810/out/extension.node.js:2:1972734)
	at t.CellExecutionFactory.create (/home/ubu/.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1201981810/out/extension.node.js:2:1971621)
	at t.CellExecutionQueue.queueCell (/home/ubu/.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1201981810/out/extension.node.js:2:1999064)
	at b.executeCell (/home/ubu/.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1201981810/out/extension.node.js:2:2016091)
	at p.executeCell (/home/ubu/.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1201981810/out/extension.node.js:24:154835)
	at x.createExecutionPromise (/home/ubu/.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1201981810/out/extension.node.js:2:1883822)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)]
```

Extension version: 2022.6.1201981810
VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 4.19.128-microsoft-standard
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (2.99GB free)|
|Process Argv|--crash-reporter-id f3a0670e-645e-4838-bcdd-287e0fa3f7ca|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (4 x 1992)|
|Memory (System)|7.77GB (3.19GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (4 x 1992)|
|Memory (System)|7.77GB (3.19GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30529770
vsclangdf:30486550
841h4636:30531698

```

</details>

**Comment by greazer** [comment]
We believe this has been reported and fixed. Should be available in v1.70. Alternatively you could try using VS Code insiders which will have this fix in it.

**Comment by sbland** [comment]
Thanks @greazer switching to "pre-release" version did the trick.

**Comment by chmendoza** [comment]
Hi @greazer.  I am seeing this error in v1.70:

![image](https://user-images.githubusercontent.com/6568054/183432408-f104ac3a-920b-447a-bb82-fd82dbd0cc4c.png)


```
info 6:47:15.982: Started kernel jupyter (Python 3.10.5)., (Raw session started and connected)
info 6:47:15.982: Finished connecting f9523834-6e01-4d7b-b1b5-773ddff3ea53
info 6:47:56.124: Generated code for 4 = <ipython-input-4-1469fc410576> with 13 lines
info 6:47:56.128: Starting Jupyter Session id = 'startUsingPythonInterpreter:.jvsc74a57bd0054741104df0334beea3d82414a1bec629a5f37aab4e1f32239d81de90b2c5fe./Users/user/miniconda3/envs/jupyter/python./Users/user/miniconda3/envs/jupyter/python.-m#ipykernel_launcher' (Python Path: /Users/user/miniconda3/envs/jupyter, EnvType: Conda, EnvName: 'jupyter', Version: 3.10.5) for 'Interactive-1.interactive' (disableUI=false)
info 6:47:56.128: Creating raw notebook for resource '/Users/user/repos/some_repo/some_project/scripts/plot_xxx_weights.py'
info 6:47:56.128: Computing working directory for resource '/Users/user/repos/some_repo/some_project/scripts/plot_xxx_weights.py'
error 6:47:56.129: Error in execution (get message for cell) [Error: notebook controller is NOT associated to notebook: vscode-interactive:Interactive-1.interactive
	at Object.createNotebookCellExecution (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:87:104769)
	at Function.create (/Users/user/.vscode/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:1965222)
	at Function.getOrCreate (/Users/user/.vscode/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:1965093)
	at new v (/Users/user/.vscode/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:1957744)
	at Function.fromCell (/Users/user/.vscode/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:1958014)
	at t.CellExecutionFactory.create (/Users/user/.vscode/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:1956901)
	at t.CellExecutionQueue.queueCell (/Users/user/.vscode/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:1984405)
	at t.KernelExecution.executeCell (/Users/user/.vscode/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:2003911)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)]
warn 6:47:56.129: DataScience Error [Error: notebook controller is NOT associated to notebook: vscode-interactive:Interactive-1.interactive
	at Object.createNotebookCellExecution (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:87:104769)
	at Function.create (/Users/user/.vscode/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:1965222)
	at Function.getOrCreate (/Users/user/.vscode/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:1965093)
	at new v (/Users/user/.vscode/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:1957744)
	at Function.fromCell (/Users/user/.vscode/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:1958014)
	at t.CellExecutionFactory.create (/Users/user/.vscode/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:1956901)
	at t.CellExecutionQueue.queueCell (/Users/user/.vscode/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:1984405)
	at t.KernelExecution.executeCell (/Users/user/.vscode/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:2003911)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)]
info 6:47:56.131: Starting raw kernel 'jupyter (Python 3.10.5)' for interpreter /Users/user/miniconda3/envs/jupyter/bin/python
info 6:47:56.136: Process Execution: > ~/miniconda3/envs/jupyter/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> ~/miniconda3/envs/jupyter/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
info 6:47:56.141: Kernel launching with ports 9053,9054,9055,9056,9057. Start port is 9000
info 6:47:56.148: Process Execution: > ~/miniconda3/envs/jupyter/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9056 --control=9054 --hb=9053 --Session.signature_scheme="hmac-sha256" --Session.key=b"148a5e68-e4fe-43d0-8543-afebc2c45d5a" --shell=9055 --transport="tcp" --iopub=9057 --f=/Users/user/Library/Jupyter/runtime/kernel-v2-16087mOTem43Wf1Cq.json
> ~/miniconda3/envs/jupyter/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9056 --control=9054 --hb=9053 --Session.signature_scheme="hmac-sha256" --Session.key=b"148a5e68-e4fe-43d0-8543-afebc2c45d5a" --shell=9055 --transport="tcp" --iopub=9057 --f=/Users/user/Library/Jupyter/runtime/kernel-v2-16087mOTem43Wf1Cq.json
info 6:47:56.148: Process Execution: cwd: ~/repos/some_repo/some_project/scripts
cwd: ~/repos/some_repo/some_project/scripts
info 6:47:56.335: ipykernel version 6.9.1 for /Users/user/miniconda3/envs/jupyter/bin/python
info 6:47:56.335: ipykernel location ~/miniconda3/envs/jupyter/lib/python3.10/site-packages/ipykernel/__init__.py for /Users/user/miniconda3/envs/jupyter/bin/python
warn 6:47:56.747: StdErr from Kernel Process /Users/user/miniconda3/envs/jupyter/lib/python3.10/site-packages/traitlets/traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
/Users/user/miniconda3/envs/jupyter/lib/python3.10/site-packages/traitlets/traitlets.py:2157: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '148a5e68-e4fe-43d0-8543-afebc2c45d5a' instead of 'b"148a5e68-e4fe-43d0-8543-afebc2c45d5a"'.
  warn(

info 6:47:56.756: Kernel Output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-v2-16087mOTem43Wf1Cq.json

info 6:47:56.967: Started kernel jupyter (Python 3.10.5)., (Raw session started and connected)
info 6:47:56.968: Finished connecting f9523834-6e01-4d7b-b1b5-773ddff3ea53
```

I am using

ipykernel                 6.9.1           py310hecd8cb5_0
jupyter                   1.0.0           py310hecd8cb5_8  
jupyter_client            7.2.2           py310hecd8cb5_0  
jupyter_console           6.4.3              pyhd3eb1b0_0  
jupyter_core              4.10.0          py310hecd8cb5_0  
jupyter_server            1.18.1          py310hecd8cb5_0

**Comment by chmendoza** [comment]
It seems that bumping the ipykernel version solves the issue:

python                    3.9.13          h57e37ff_0_cpython    conda-forge
ipykernel                 6.15.1             pyh736e0ef_0    conda-forge
jupyter                   1.0.0            py39h6e9494a_7    conda-forge
jupyter_client            7.3.4              pyhd8ed1ab_0    conda-forge
jupyter_console           6.4.4              pyhd8ed1ab_0    conda-forge
jupyter_core              4.11.1           py39h6e9494a_0    conda-forge

**Comment by ArthurConmy** [comment]
Also getting this @greazer on 1.69:

```
...


info 9:47:35.624: Kernel Output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-v2-28868arCFKg2fUh9I.json

info 9:47:35.677: Started kernel Python 3.9.6 64-bit., (Raw session started and connected)
info 9:47:35.679: Finished connecting aeea1914-472c-4edd-9802-a757a9a216e8
info 9:47:35.685: UpdateWorkingDirectoryAndPath in Kernel
info 9:47:35.686: Executing silently Code (idle) = import types as _VSCODE_types\nimport os\nimport hashlib as _VSCODE_hashlib\nfrom IPython import get_ip
info 9:47:35.748: Executing silently Code (completed) = import types as _VSCODE_types\nimport os\nimport hashlib as _VSCODE_hashlib\nfrom IPython import get_ip with 1 output(s)
info 9:47:35.749: Executing silently Code (idle) = %load_ext autoreload\n%autoreload 2
info 9:47:35.778: Executing silently Code (completed) = %load_ext autoreload\n%autoreload 2 with 0 output(s)
info 9:47:35.779: Waiting for idle on (kernel): ec43366d-1fe5-4542-bde0-efc937e35306 -> idle
info 9:47:35.779: Finished waiting for idle on (kernel): ec43366d-1fe5-4542-bde0-efc937e35306 -> idle
info 9:47:35.791: Executing silently Code (idle) = __file__ = '/home/ubuntu/unity/interp/circuit/projects/paren/nb2.py'
info 9:47:35.792: Executing silently Code (idle) = __file__ = '/home/ubuntu/unity/interp/circuit/projects/paren/nb2.py'
info 9:47:35.839: Executing silently Code (completed) = __file__ = '/home/ubuntu/unity/interp/circuit/projects/paren/nb2.py' with 0 output(s)
info 9:47:35.844: Generated code for 1 = <ipython-input-1-2df1ec7f0a60> with 3 lines
info 9:47:35.848: Executing silently Code (completed) = __file__ = '/home/ubuntu/unity/interp/circuit/projects/paren/nb2.py' with 0 output(s)
info 9:47:35.851: Widget Message: Received IPyWidgets_kernelOptions in ScriptManager
info 9:47:35.853: Widget Message: Received IPyWidgetMessages.IPyWidgets_kernelOptions
error 9:47:35.916: Error in execution (get message for cell) [Error: notebook controller is NOT associated to notebook: vscode-interactive:Interactive-1.interactive
	at Object.createNotebookCellExecution (/home/ubuntu/.vscode-server/bin/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/out/vs/workbench/api/node/extensionHostProcess.js:87:104239)
	at Function.create (/home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1201981810/out/extension.node.js:2:1979904)
	at Function.getOrCreate (/home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1201981810/out/extension.node.js:2:1979775)
	at new v (/home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1201981810/out/extension.node.js:2:1972464)
	at Function.fromCell (/home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1201981810/out/extension.node.js:2:1972734)
	at t.CellExecutionFactory.create (/home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1201981810/out/extension.node.js:2:1971621)
	at t.CellExecutionQueue.queueCell (/home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1201981810/out/extension.node.js:2:1999064)
	at b.executeCell (/home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1201981810/out/extension.node.js:2:2016091)
	at p.executeCell (/home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1201981810/out/extension.node.js:24:154835)
	at x.createExecutionPromise (/home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1201981810/out/extension.node.js:2:1883822)]
warn 9:47:35.921: DataScience Error [Error: notebook controller is NOT associated to notebook: vscode-interactive:Interactive-1.interactive
	at Object.createNotebookCellExecution (/home/ubuntu/.vscode-server/bin/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/out/vs/workbench/api/node/extensionHostProcess.js:87:104239)
	at Function.create (/home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1201981810/out/extension.node.js:2:1979904)
	at Function.getOrCreate (/home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1201981810/out/extension.node.js:2:1979775)
	at new v (/home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1201981810/out/extension.node.js:2:1972464)
	at Function.fromCell (/home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1201981810/out/extension.node.js:2:1972734)
	at t.CellExecutionFactory.create (/home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1201981810/out/extension.node.js:2:1971621)
	at t.CellExecutionQueue.queueCell (/home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1201981810/out/extension.node.js:2:1999064)
	at b.executeCell (/home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1201981810/out/extension.node.js:2:2016091)
	at p.executeCell (/home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1201981810/out/extension.node.js:24:154835)
	at x.createExecutionPromise (/home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1201981810/out/extension.node.js:2:1883822)]
info 9:47:36.47: Widget Message: data-base-url set to https://vscode-remote%2Bssh-002dremote-002brr-002daws.vscode-resource.vscode-cdn.net/home/ubuntu/.vscode-server/extensions/...
```

**Comment by sbland** [comment]
I still get this error occasionally and need to switch kernel then switch back again. Mostly happens when opening a new vscode window

**Comment by loftusa** [comment]
I am getting this error as well. Fresh Ubuntu install.

**Comment by Daniel451** [comment]
Same issue on VSCode `1.73.1` with notebook `6.5.2`, ipykernel `6.18.0`, and jupyter-server `1.23.3`
