### ISSUE TITLE
xelatex (TeX) installed but still giving error

### ISSUE THREAD

**Issue by mumer012001** [microsoft/vscode-jupyter#10910]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Hi, I've already installed MikTex, I can confirm it via cmd. In cmd when I type "xelatex --version" it shows me all the versions but when in vscode I try to export as PDF it shows this error at the end. Please help me!
Error:
If you have not installed xelatex (TeX) you will need to do so before you can export to PDF, for further instructions please look https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex. 

### VS Code Version

1.69.2

### Jupyter Extension Version

v2022.6.1201981810

### Jupyter logs

```shell
info 19:23:54.871: Preferred Remote kernel for c:\Users\Admin\Documents\Learning_Code\Python_Chilla_2_Assignments\Prerequisite_Assignments\Assignment_No#1.ipynb is undefined
info 19:23:54.882: Preferred Remote kernel for c:\Users\Admin\Documents\Learning_Code\Python_Chilla_2_Assignments\Prerequisite_Assignments\Assignment_No#1.ipynb is undefined
info 19:23:54.882: Find preferred kernel for c:\Users\Admin\Documents\Learning_Code\Python_Chilla_2_Assignments\Prerequisite_Assignments\Assignment_No#1.ipynb with metadata {"kernelspec":{"display_name":"Python 3.10.5 64-bit","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.10.5"},"vscode":{"interpreter":{"hash":"a42ccb73e7d9bfdf27e036f1d2b8b681e55fc0743cc5586bc2474d4a60f4b886"}}} & preferred interpreter c:\Users\Admin\AppData\Local\Programs\Python\Python310\python.exe
info 19:23:54.884: Preferred Remote kernel for c:\Users\Admin\Documents\Learning_Code\Python_Chilla_2_Assignments\Prerequisite_Assignments\Assignment_No#1.ipynb is undefined
info 19:23:54.885: Preferred kernel .jvsc74a57bd0a42ccb73e7d9bfdf27e036f1d2b8b681e55fc0743cc5586bc2474d4a60f4b886.c:\Users\Admin\AppData\Local\Programs\Python\Python310\python.exe.c:\Users\Admin\AppData\Local\Programs\Python\Python310\python.exe.-m#ipykernel_launcher is exact match
info 19:23:54.887: PreferredConnection: .jvsc74a57bd0a42ccb73e7d9bfdf27e036f1d2b8b681e55fc0743cc5586bc2474d4a60f4b886.c:\Users\Admin\AppData\Local\Programs\Python\Python310\python.exe.c:\Users\Admin\AppData\Local\Programs\Python\Python310\python.exe.-m#ipykernel_launcher found for NotebookDocument: c:\Users\Admin\Documents\Learning_Code\Python_Chilla_2_Assignments\Prerequisite_Assignments\Assignment_No#1.ipynb
info 19:23:54.997: Preferred Remote kernel for c:\Users\Admin\Documents\Learning_Code\Python_Chilla_2_Assignments\Prerequisite_Assignments\Assignment_No#1.ipynb is undefined
info 19:23:54.997: Find preferred kernel for c:\Users\Admin\Documents\Learning_Code\Python_Chilla_2_Assignments\Prerequisite_Assignments\Assignment_No#1.ipynb with metadata {"kernelspec":{"display_name":"Python 3.10.5 64-bit","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.10.5"},"vscode":{"interpreter":{"hash":"a42ccb73e7d9bfdf27e036f1d2b8b681e55fc0743cc5586bc2474d4a60f4b886"}}} & preferred interpreter c:\Users\Admin\AppData\Local\Programs\Python\Python310\python.exe
info 19:23:54.999: Preferred Remote kernel for c:\Users\Admin\Documents\Learning_Code\Python_Chilla_2_Assignments\Prerequisite_Assignments\Assignment_No#1.ipynb is undefined
info 19:23:54.999: Preferred kernel .jvsc74a57bd0a42ccb73e7d9bfdf27e036f1d2b8b681e55fc0743cc5586bc2474d4a60f4b886.c:\Users\Admin\AppData\Local\Programs\Python\Python310\python.exe.c:\Users\Admin\AppData\Local\Programs\Python\Python310\python.exe.-m#ipykernel_launcher is exact match
info 19:23:55.648: Starting Jupyter Session id = 'startUsingPythonInterpreter:.jvsc74a57bd0a42ccb73e7d9bfdf27e036f1d2b8b681e55fc0743cc5586bc2474d4a60f4b886.c:\Users\Admin\AppData\Local\Programs\Python\Python310\python.exe.c:\Users\Admin\AppData\Local\Programs\Python\Python310\python.exe.-m#ipykernel_launcher' (Python Path: , EnvType: Global, EnvName: '', Version: 3.10.5) for 'c:\Users\Admin\Documents\Learning_Code\Python_Chilla_2_Assignments\Prerequisite_Assignments\Assignment_No#1.ipynb' (disableUI=true)
info 19:23:55.648: Creating raw notebook for resource 'c:\Users\Admin\Documents\Learning_Code\Python_Chilla_2_Assignments\Prerequisite_Assignments\Assignment_No#1.ipynb'
info 19:23:55.649: Computing working directory for resource 'c:\Users\Admin\Documents\Learning_Code\Python_Chilla_2_Assignments\Prerequisite_Assignments\Assignment_No#1.ipynb'
info 19:23:55.658: Starting raw kernel 'Python 3.10.5 64-bit' for interpreter c:\Users\Admin\AppData\Local\Programs\Python\Python310\python.exe
info 19:23:55.847: Kernel launching with ports 9008,9009,9010,9011,9012. Start port is 9000
info 19:23:55.855: Process Execution: > ~\AppData\Local\Programs\Python\Python310\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> ~\AppData\Local\Programs\Python\Python310\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
info 19:23:55.895: Creating daemon process for c:\Users\Admin\AppData\Local\Programs\Python\Python310\python.exe with env variables count 47
info 19:23:55.901: Process Execution: > ~\AppData\Local\Programs\Python\Python310\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_interrupt_daemon -v --ppid 1568
> ~\AppData\Local\Programs\Python\Python310\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_interrupt_daemon -v --ppid 1568
info 19:23:56.381: get interrupthandle daemon
info 19:23:56.388: Process Execution: > ~\AppData\Local\Programs\Python\Python310\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9011 --control=9009 --hb=9008 --Session.signature_scheme="hmac-sha256" --Session.key=b"6f7f1044-15f0-4d31-bcc3-d850b088ec2b" --shell=9010 --transport="tcp" --iopub=9012 --f=c:\Users\Admin\AppData\Roaming\jupyter\runtime\kernel-v2-1568Km18pwcx67RE.json
> ~\AppData\Local\Programs\Python\Python310\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9011 --control=9009 --hb=9008 --Session.signature_scheme="hmac-sha256" --Session.key=b"6f7f1044-15f0-4d31-bcc3-d850b088ec2b" --shell=9010 --transport="tcp" --iopub=9012 --f=c:\Users\Admin\AppData\Roaming\jupyter\runtime\kernel-v2-1568Km18pwcx67RE.json
info 19:23:56.388: Process Execution: cwd: ~\Documents\Learning_Code\Python_Chilla_2_Assignments\Prerequisite_Assignments
cwd: ~\Documents\Learning_Code\Python_Chilla_2_Assignments\Prerequisite_Assignments
info 19:23:57.206: ipykernel version 6.15.1 for c:\Users\Admin\AppData\Local\Programs\Python\Python310\python.exe
info 19:23:57.207: ipykernel location ~\AppData\Local\Programs\Python\Python310\lib\site-packages\ipykernel\__init__.py for c:\Users\Admin\AppData\Local\Programs\Python\Python310\python.exe
warn 19:23:58.477: StdErr from Kernel Process c:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\traitlets\traitlets.py:2392: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(

warn 19:23:58.477: StdErr from Kernel Process c:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\traitlets\traitlets.py:2346: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '6f7f1044-15f0-4d31-bcc3-d850b088ec2b' instead of 'b"6f7f1044-15f0-4d31-bcc3-d850b088ec2b"'.
  warn(

info 19:23:58.557: Kernel Output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing c:\Users\Admin\AppData\Roaming\jupyter\runtime\kernel-v2-1568Km18pwcx67RE.json

info 19:23:58.644: Started kernel Python 3.10.5 64-bit., (Raw session started and connected)
info 19:23:58.645: Finished connecting f818b3ff-0835-488b-9c3c-b5f5179b0c63
info 19:23:58.648: UpdateWorkingDirectoryAndPath in Kernel
info 19:23:58.649: Executing silently Code (idle) = import os\nimport sys\n%cd "c:\Users\Admin\Documents\Learning_Code\Python_Chilla_2_Assignments\Prerequ
info 19:23:58.695: Executing silently Code (completed) = import os\nimport sys\n%cd "c:\Users\Admin\Documents\Learning_Code\Python_Chilla_2_Assignments\Prerequ with 1 output(s)
info 19:23:58.695: Waiting for idle on (kernel): 17d2d5c2-6c73-42c2-af29-94648957d4da -> idle
info 19:23:58.695: Finished waiting for idle on (kernel): 17d2d5c2-6c73-42c2-af29-94648957d4da -> idle
info 19:23:58.707: Widget Message: Received IPyWidgets_kernelOptions in ScriptManager
info 19:23:58.707: Widget Message: Received IPyWidgetMessages.IPyWidgets_kernelOptions
info 19:23:58.726: Widget Message: Received IPyWidgets_kernelOptions in ScriptManager
info 19:23:58.726: Widget Message: Received IPyWidgetMessages.IPyWidgets_kernelOptions
info 19:23:58.773: Widget Message: data-base-url set to https://file%2B.vscode-resource.vscode-cdn.net/c%3A/Users/Admin/.vscode/extensions/ms-toolsai.jupyter-2022.6.1201981810/tmp/scripts/9b8de75c2a7e7de75dbca7e07addc4a9f70c5fc099b8fcbb3304bd2da1191c9a/jupyter
info 19:23:58.773: Widget Message: data-base-url set to https://file%2B.vscode-resource.vscode-cdn.net/c%3A/Users/Admin/.vscode/extensions/ms-toolsai.jupyter-2022.6.1201981810/tmp/scripts/9b8de75c2a7e7de75dbca7e07addc4a9f70c5fc099b8fcbb3304bd2da1191c9a/jupyter
info 19:24:7.801: Process Execution: > ~\AppData\Local\Programs\Python\Python310\python.exe -m jupyter nbconvert ~\AppData\Local\Temp\3b76b5e4-542a-4627-913a-c5a49d6bc3d8\Assignment_No#1.ipynb --to pdf --output tmp-1568F9Upv9I2YNL9.pdf --output-dir ~\AppData\Local\Temp --debug
> ~\AppData\Local\Programs\Python\Python310\python.exe -m jupyter nbconvert ~\AppData\Local\Temp\3b76b5e4-542a-4627-913a-c5a49d6bc3d8\Assignment_No#1.ipynb --to pdf --output tmp-1568F9Upv9I2YNL9.pdf --output-dir ~\AppData\Local\Temp --debug
error 19:24:12.257: Export failed Error: [NbConvertApp] Searching ['C:\\Users\\Admin\\AppData\\Local\\Programs\\Microsoft VS Code', 'C:\\Users\\Admin\\.jupyter', 'C:\\Users\\Admin\\AppData\\Roaming\\Python\\etc\\jupyter', 'c:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python310\\etc\\jupyter', 'C:\\ProgramData\\jupyter'] for config files
[NbConvertApp] Looking for jupyter_config in C:\ProgramData\jupyter
[NbConvertApp] Looking for jupyter_config in c:\Users\Admin\AppData\Local\Programs\Python\Python310\etc\jupyter
[NbConvertApp] Looking for jupyter_config in C:\Users\Admin\AppData\Roaming\Python\etc\jupyter
[NbConvertApp] Looking for jupyter_config in C:\Users\Admin\.jupyter
[NbConvertApp] Looking for jupyter_config in C:\Users\Admin\AppData\Local\Programs\Microsoft VS Code
[NbConvertApp] Looking for jupyter_nbconvert_config in C:\ProgramData\jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in c:\Users\Admin\AppData\Local\Programs\Python\Python310\etc\jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in C:\Users\Admin\AppData\Roaming\Python\etc\jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in C:\Users\Admin\.jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in C:\Users\Admin\AppData\Local\Programs\Microsoft VS Code
[NbConvertApp] Converting notebook c:\Users\Admin\AppData\Local\Temp\3b76b5e4-542a-4627-913a-c5a49d6bc3d8\Assignment_No#1.ipynb to pdf
[NbConvertApp] Notebook name is 'tmp-1568F9Upv9I2YNL9'
[NbConvertApp] Template paths:
	C:\Users\Admin\AppData\Roaming\jupyter\nbconvert\templates\latex
	c:\Users\Admin\AppData\Local\Programs\Python\Python310\share\jupyter\nbconvert\templates\latex
	C:\ProgramData\jupyter\nbconvert\templates\latex
	c:\Users\Admin\AppData\Local\Programs\Python\Python310\share\jupyter\nbconvert\templates\base
	C:\Users\Admin\AppData\Roaming\jupyter
	C:\Users\Admin\AppData\Roaming\jupyter\nbconvert\templates
	C:\Users\Admin\AppData\Roaming\jupyter\nbconvert\templates\compatibility
	C:\Users\Admin\AppData\Roaming\Python\share\jupyter
	C:\Users\Admin\AppData\Roaming\Python\share\jupyter\nbconvert\templates
	C:\Users\Admin\AppData\Roaming\Python\share\jupyter\nbconvert\templates\compatibility
	c:\Users\Admin\AppData\Local\Programs\Python\Python310\share\jupyter
	c:\Users\Admin\AppData\Local\Programs\Python\Python310\share\jupyter\nbconvert\templates
	c:\Users\Admin\AppData\Local\Programs\Python\Python310\share\jupyter\nbconvert\templates\compatibility
	C:\ProgramData\jupyter
	C:\ProgramData\jupyter\nbconvert\templates
	C:\ProgramData\jupyter\nbconvert\templates\compatibility
	C:\Users\Admin\AppData\Roaming\jupyter\nbconvert\templates
	c:\Users\Admin\AppData\Local\Programs\Python\Python310\share\jupyter\nbconvert\templates
	C:\ProgramData\jupyter\nbconvert\templates
[NbConvertApp] Applying preprocessor: TagRemovePreprocessor
[NbConvertApp] Applying preprocessor: RegexRemovePreprocessor
[NbConvertApp] Applying preprocessor: coalesce_streams
[NbConvertApp] Applying preprocessor: SVG2PDFPreprocessor
[NbConvertApp] Applying preprocessor: LatexPreprocessor
[NbConvertApp] Applying preprocessor: HighlightMagicsPreprocessor
[NbConvertApp] Applying preprocessor: ExtractOutputPreprocessor
[NbConvertApp] Attempting to load template index.tex.j2
[NbConvertApp]     template_paths: C:\Users\Admin\AppData\Roaming\jupyter\nbconvert\templates\latex;c:\Users\Admin\AppData\Local\Programs\Python\Python310\share\jupyter\nbconvert\templates\latex;C:\ProgramData\jupyter\nbconvert\templates\latex;c:\Users\Admin\AppData\Local\Programs\Python\Python310\share\jupyter\nbconvert\templates\base;C:\Users\Admin\AppData\Roaming\jupyter;C:\Users\Admin\AppData\Roaming\jupyter\nbconvert\templates;C:\Users\Admin\AppData\Roaming\jupyter\nbconvert\templates\compatibility;C:\Users\Admin\AppData\Roaming\Python\share\jupyter;C:\Users\Admin\AppData\Roaming\Python\share\jupyter\nbconvert\templates;C:\Users\Admin\AppData\Roaming\Python\share\jupyter\nbconvert\templates\compatibility;c:\Users\Admin\AppData\Local\Programs\Python\Python310\share\jupyter;c:\Users\Admin\AppData\Local\Programs\Python\Python310\share\jupyter\nbconvert\templates;c:\Users\Admin\AppData\Local\Programs\Python\Python310\share\jupyter\nbconvert\templates\compatibility;C:\ProgramData\jupyter;C:\ProgramData\jupyter\nbconvert\templates;C:\ProgramData\jupyter\nbconvert\templates\compatibility;C:\Users\Admin\AppData\Roaming\jupyter\nbconvert\templates;c:\Users\Admin\AppData\Local\Programs\Python\Python310\share\jupyter\nbconvert\templates;C:\ProgramData\jupyter\nbconvert\templates
[NbConvertApp] ERROR | Error while converting 'c:\Users\Admin\AppData\Local\Temp\3b76b5e4-542a-4627-913a-c5a49d6bc3d8\Assignment_No#1.ipynb'
Traceback (most recent call last):
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\nbconvert\nbconvertapp.py", line 479, in export_single_notebook
    output, resources = self.exporter.from_filename(
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\nbconvert\exporters\exporter.py", line 189, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\nbconvert\exporters\exporter.py", line 206, in from_file
    return self.from_notebook_node(
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\nbconvert\exporters\pdf.py", line 181, in from_notebook_node
    latex, resources = super().from_notebook_node(nb, resources=resources, **kw)
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\nbconvert\exporters\latex.py", line 74, in from_notebook_node
    return super().from_notebook_node(nb, resources, **kw)
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\nbconvert\exporters\templateexporter.py", line 400, in from_notebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python310\share\jupyter\nbconvert\templates\latex\index.tex.j2", line 8, in top-level template code
    ((* extends cell_style *))
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python310\share\jupyter\nbconvert\templates\latex\style_jupyter.tex.j2", line 176, in top-level template code
    \prompt{(((prompt)))}{(((prompt_color)))}{(((execution_count)))}{(((extra_space)))}
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python310\share\jupyter\nbconvert\templates\latex\base.tex.j2", line 7, in top-level template code
    ((*- extends 'document_contents.tex.j2' -*))
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python310\share\jupyter\nbconvert\templates\latex\document_contents.tex.j2", line 51, in top-level template code
    ((*- block figure scoped -*))
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python310\share\jupyter\nbconvert\templates\latex\display_priority.j2", line 5, in top-level template code
    ((*- extends 'null.j2' -*))
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python310\share\jupyter\nbconvert\templates\latex\null.j2", line 30, in top-level template code
    ((*- block body -*))
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python310\share\jupyter\nbconvert\templates\latex\base.tex.j2", line 215, in block 'body'
    ((( super() )))
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python310\share\jupyter\nbconvert\templates\latex\null.j2", line 32, in block 'body'
    ((*- block any_cell scoped -*))
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python310\share\jupyter\nbconvert\templates\latex\null.j2", line 85, in block 'any_cell'
    ((*- block markdowncell scoped-*)) ((*- endblock markdowncell -*))
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python310\share\jupyter\nbconvert\templates\latex\document_contents.tex.j2", line 68, in block 'markdowncell'
    ((( cell.source | citation2latex | strip_files_prefix | convert_pandoc('markdown+tex_math_double_backslash', 'json',extra_args=[]) | resolve_references | convert_pandoc('json','latex'))))
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\nbconvert\filters\pandoc.py", line 24, in convert_pandoc
    return pandoc(source, from_format, to_format, extra_args=extra_args)
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\nbconvert\utils\pandoc.py", line 51, in pandoc
    check_pandoc_version()
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\nbconvert\utils\pandoc.py", line 99, in check_pandoc_version
    v = get_pandoc_version()
  File "c:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\nbconvert\utils\pandoc.py", line 76, in get_pandoc_version
    raise PandocMissing()
nbconvert.utils.pandoc.PandocMissing: Pandoc wasn't found.
Please check that pandoc is installed:
https://pandoc.org/installing.html
[NbConvertApp] Exiting application: jupyter-nbconvert

    at y.executeCommand (c:\Users\Admin\.vscode\extensions\ms-toolsai.jupyter-2022.6.1201981810\out\extension.node.js:24:395567)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at a.export (c:\Users\Admin\.vscode\extensions\ms-toolsai.jupyter-2022.6.1201981810\out\extension.node.js:24:403122)
    at f.exportToFormat (c:\Users\Admin\.vscode\extensions\ms-toolsai.jupyter-2022.6.1201981810\out\extension.node.js:24:413286)
    at f.performNbConvertExport (c:\Users\Admin\.vscode\extensions\ms-toolsai.jupyter-2022.6.1201981810\out\extension.node.js:24:413090)
    at f.performExport (c:\Users\Admin\.vscode\extensions\ms-toolsai.jupyter-2022.6.1201981810\out\extension.node.js:24:412745)
    at f.exportImpl (c:\Users\Admin\.vscode\extensions\ms-toolsai.jupyter-2022.6.1201981810\out\extension.node.js:24:412263)
    at f.export (c:\Users\Admin\.vscode\extensions\ms-toolsai.jupyter-2022.6.1201981810\out\extension.node.js:24:411987)
    at t.ExportCommands.export (c:\Users\Admin\.vscode\extensions\ms-toolsai.jupyter-2022.6.1201981810\out\extension.node.js:39:200426)
    at o._executeContributedCommand (c:\Users\Admin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:62863)
error 19:24:12.275: If you have not installed xelatex (TeX) you will need to do so before you can export to PDF, for further instructions please look https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex. 
To avoid installing xelatex (TeX) you might want to try exporting to HTML and using your browsers "Print to PDF" feature.
```

### Coding Language and Runtime Version

Python v3.10.5 64bit, don't know about runtime

### Language Extension Version (if applicable)

v2022.10.1

### Running Jupyter locally or remotely?

Local

**Comment by mumer012001** [comment]
Fixed, pandoc was missing even though I already installed it through 'pip' but still, it was showing as missing. Downloaded the installer from pandoc.org and it worked fine.
