### ISSUE TITLE
Interactive window gives no output if in remote mode and kill server

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#11003]
Turn on the new UI:

    "jupyter.showOnlyOneTypeOfKernel": true,

Connect to a remote server (pick remote kernel)
Close VS code
Kill remote server.
Restart VS code.

Run IW. 

I get this:

![image](https://user-images.githubusercontent.com/19672699/182238301-6adf0369-34a3-4b3d-9ff1-bbb5da0c5d5b.png)

Can see all the remote connection failures in the jupyter output:

```
warn 13:14:7.350: Could not fetch kernels from the remote server, falling back to cache: TypeError: request to http://localhost:8888/api/kernels?1659384847309 failed, reason: connect ECONNREFUSED 127.0.0.1:8888
error 13:14:7.350: SessionManager:getKernelSpecs failure:  Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
    at e.dispose (c:\Users\aku91\.vscode\extensions\ms-toolsai.jupyter-2022.7.100\out\node_modules\@jupyterlab\services.js:2:156575)
    at m.dispose (c:\Users\aku91\.vscode\extensions\ms-toolsai.jupyter-2022.7.100\out\node_modules\@jupyterlab\services.js:2:48238)
    at u.dispose (c:\Users\aku91\.vscode\extensions\ms-toolsai.jupyter-2022.7.100\out\extension.node.js:2:418480)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at g.listKernels (c:\Users\aku91\.vscode\extensions\ms-toolsai.jupyter-2022.7.100\out\extension.node.js:2:388693)
info 13:14:10.930: Starting interactive window for resource 'd:\Source\Testing\Testing_3\manualTestFile.py'
error 13:14:10.931: No remote controllers
info 13:14:11.28: Preferred Remote kernel for Interactive-1.interactive is undefined
error 13:14:11.28: No remote controllers
```

**Comment by rchiodo** [comment]
Starts working as soon as I turn off the experiment.

**Comment by amunger** [comment]
there is initially a pop-up, informing of a connection failure, but if you click cancel, then you end up in this situation.
At that point, there is no longer a preferred controller for the IW, and since it is looking for remote kernels only, nothing is selected

**Comment by amunger** [comment]
experiment is gone
