### ISSUE TITLE
Notebook Not Activated (TIMEOUT) using Remote Kernel

### ISSUE THREAD

**Issue by yeokwangeun** [microsoft/vscode-jupyter#11101]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Hi.

There are two development servers I am using right now.
1) login node where VS code remote development is activated
2) gpu node where remote jupyter notebook is activated

I used to select remote jupyter kernel in gpu node, and use jupyter notebook in remote development environment.
However, it suddenly does not work. To be more specific, remote kernel in gpu node is not activated and timeout error message is occured.

How can I fix it?

### VS Code Version

1.7.0

### Jupyter Extension Version

v2022.7.1002181843

### Jupyter logs

```shell
info 13:45:52.858: Creating server with url : http://localhost:8720/
info 13:45:53.446: Creating server with url : http://localhost:8720/
info 13:46:8.117: Execute Cell 0 /home/kwangeun/data/projects/kwangeun/mlvu/hw3/MLVU_HW3/S3D/test.ipynb
info 13:46:8.118: Starting Jupyter Session id = 'startUsingRemoteKernelSpec:c483d88b0358a487987b4ec3be66258278dc0eb8235582295c438285496ca577..python3./home/kwangeun/.conda/envs/py38/python./.-m#ipykernel_launcher' (Python Path: /home/kwangeun/.conda/envs/py38, EnvType: Conda, EnvName: 'py38', Version: 3.8.13) for '/home/kwangeun/data/projects/kwangeun/mlvu/hw3/MLVU_HW3/S3D/test.ipynb' (disableUI=false)
http://localhost:8720/: Kernel started: 847ac385-4c85-45b3-a787-0ce7e60a1752
info 13:46:10.534: Waiting for idle on (kernel): 847ac385-4c85-45b3-a787-0ce7e60a1752 -> unknown
info 13:47:10.534: Finished waiting for idle on (kernel): 847ac385-4c85-45b3-a787-0ce7e60a1752 -> unknown
error 13:47:10.534: Shutting down after failing to wait for idle on (kernel): 847ac385-4c85-45b3-a787-0ce7e60a1752 -> unknown
error 13:47:10.535: Failed to change kernel, re-throwing [s [Error]: The Jupyter notebook server failed to launch in time
	at waitForIdleOnSession (/home/kwangeun/.vscode-server/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:1924148)
	at async w.createNewKernelSession (/home/kwangeun/.vscode-server/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:2198605)
	at async w.connect (/home/kwangeun/.vscode-server/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:2197323)
	at async u.startNew (/home/kwangeun/.vscode-server/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:2205819)
	at async a (/home/kwangeun/.vscode-server/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:2141520)
	at async _.createNotebookInstance (/home/kwangeun/.vscode-server/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:2141683)
	at async _.createNotebook (/home/kwangeun/.vscode-server/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:2142688)] {
  category: 'timeout',
  kernelConnectionMetadata: {
    kind: 'startUsingRemoteKernelSpec',
    interpreter: {
      id: '/home/kwangeun/.conda/envs/py38/bin/python',
      sysPrefix: '/home/kwangeun/.conda/envs/py38',
      envType: 'Conda',
      envName: 'py38',
      envPath: [b],
      architecture: 3,
      sysVersion: '3.8.13 (default, Mar 28 2022, 11:38:47) \n[GCC 7.5.0]',
      version: [Object],
      companyDisplayName: 'Anaconda, Inc.',
      displayName: "Python 3.8.13 ('py38')",
      detailedDisplayName: "Python 3.8.13 ('py38': conda)",
      uri: [b]
    },
    kernelSpec: {
      specFile: undefined,
      interpreterPath: undefined,
      isRegisteredByVSC: undefined,
      name: 'python3',
      argv: [Array],
      language: 'python',
      executable: '/home/kwangeun/.conda/envs/py38/bin/python',
      display_name: 'Python 3 (ipykernel)',
      metadata: [Object],
      env: {},
      interrupt_mode: undefined
    },
    id: 'c483d88b0358a487987b4ec3be66258278dc0eb8235582295c438285496ca577..python3./home/kwangeun/.conda/envs/py38/python./.-m#ipykernel_launcher',
    baseUrl: 'http://localhost:8720/',
    serverId: 'c483d88b0358a487987b4ec3be66258278dc0eb8235582295c438285496ca577'
  }
}
warn 13:47:10.538: Error occurred while trying to start the kernel, options.disableUI=false [s [Error]: The Jupyter notebook server failed to launch in time
	at waitForIdleOnSession (/home/kwangeun/.vscode-server/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:1924148)
	at async w.createNewKernelSession (/home/kwangeun/.vscode-server/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:2198605)
	at async w.connect (/home/kwangeun/.vscode-server/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:2197323)
	at async u.startNew (/home/kwangeun/.vscode-server/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:2205819)
	at async a (/home/kwangeun/.vscode-server/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:2141520)
	at async _.createNotebookInstance (/home/kwangeun/.vscode-server/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:2141683)
	at async _.createNotebook (/home/kwangeun/.vscode-server/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:2142688)] {
  category: 'timeout',
  kernelConnectionMetadata: {
    kind: 'startUsingRemoteKernelSpec',
    interpreter: {
      id: '/home/kwangeun/.conda/envs/py38/bin/python',
      sysPrefix: '/home/kwangeun/.conda/envs/py38',
      envType: 'Conda',
      envName: 'py38',
      envPath: [b],
      architecture: 3,
      sysVersion: '3.8.13 (default, Mar 28 2022, 11:38:47) \n[GCC 7.5.0]',
      version: [Object],
      companyDisplayName: 'Anaconda, Inc.',
      displayName: "Python 3.8.13 ('py38')",
      detailedDisplayName: "Python 3.8.13 ('py38': conda)",
      uri: [b]
    },
    kernelSpec: {
      specFile: undefined,
      interpreterPath: undefined,
      isRegisteredByVSC: undefined,
      name: 'python3',
      argv: [Array],
      language: 'python',
      executable: '/home/kwangeun/.conda/envs/py38/bin/python',
      display_name: 'Python 3 (ipykernel)',
      metadata: [Object],
      env: {},
      interrupt_mode: undefined
    },
    id: 'c483d88b0358a487987b4ec3be66258278dc0eb8235582295c438285496ca577..python3./home/kwangeun/.conda/envs/py38/python./.-m#ipykernel_launcher',
    baseUrl: 'http://localhost:8720/',
    serverId: 'c483d88b0358a487987b4ec3be66258278dc0eb8235582295c438285496ca577'
  }
}
warn 13:47:10.538: Kernel Error, context = start [s [Error]: The Jupyter notebook server failed to launch in time
	at waitForIdleOnSession (/home/kwangeun/.vscode-server/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:1924148)
	at async w.createNewKernelSession (/home/kwangeun/.vscode-server/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:2198605)
	at async w.connect (/home/kwangeun/.vscode-server/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:2197323)
	at async u.startNew (/home/kwangeun/.vscode-server/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:2205819)
	at async a (/home/kwangeun/.vscode-server/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:2141520)
	at async _.createNotebookInstance (/home/kwangeun/.vscode-server/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:2141683)
	at async _.createNotebook (/home/kwangeun/.vscode-server/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:2142688)] {
  category: 'timeout',
  kernelConnectionMetadata: {
    kind: 'startUsingRemoteKernelSpec',
    interpreter: {
      id: '/home/kwangeun/.conda/envs/py38/bin/python',
      sysPrefix: '/home/kwangeun/.conda/envs/py38',
      envType: 'Conda',
      envName: 'py38',
      envPath: [b],
      architecture: 3,
      sysVersion: '3.8.13 (default, Mar 28 2022, 11:38:47) \n[GCC 7.5.0]',
      version: [Object],
      companyDisplayName: 'Anaconda, Inc.',
      displayName: "Python 3.8.13 ('py38')",
      detailedDisplayName: "Python 3.8.13 ('py38': conda)",
      uri: [b]
    },
    kernelSpec: {
      specFile: undefined,
      interpreterPath: undefined,
      isRegisteredByVSC: undefined,
      name: 'python3',
      argv: [Array],
      language: 'python',
      executable: '/home/kwangeun/.conda/envs/py38/bin/python',
      display_name: 'Python 3 (ipykernel)',
      metadata: [Object],
      env: {},
      interrupt_mode: undefined
    },
    id: 'c483d88b0358a487987b4ec3be66258278dc0eb8235582295c438285496ca577..python3./home/kwangeun/.conda/envs/py38/python./.-m#ipykernel_launcher',
    baseUrl: 'http://localhost:8720/',
    serverId: 'c483d88b0358a487987b4ec3be66258278dc0eb8235582295c438285496ca577'
  }
}
info 13:47:10.542: Dispose Kernel '/home/kwangeun/data/projects/kwangeun/mlvu/hw3/MLVU_HW3/S3D/test.ipynb' associated with '/home/kwangeun/data/projects/kwangeun/mlvu/hw3/MLVU_HW3/S3D/test.ipynb'
error 13:47:10.544: Error in execution [s [Error]: The Jupyter notebook server failed to launch in time
	at waitForIdleOnSession (/home/kwangeun/.vscode-server/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:1924148)
	at async w.createNewKernelSession (/home/kwangeun/.vscode-server/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:2198605)
	at async w.connect (/home/kwangeun/.vscode-server/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:2197323)
	at async u.startNew (/home/kwangeun/.vscode-server/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:2205819)
	at async a (/home/kwangeun/.vscode-server/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:2141520)
	at async _.createNotebookInstance (/home/kwangeun/.vscode-server/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:2141683)
	at async _.createNotebook (/home/kwangeun/.vscode-server/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:2142688)] {
  category: 'timeout',
  kernelConnectionMetadata: {
    kind: 'startUsingRemoteKernelSpec',
    interpreter: {
      id: '/home/kwangeun/.conda/envs/py38/bin/python',
      sysPrefix: '/home/kwangeun/.conda/envs/py38',
      envType: 'Conda',
      envName: 'py38',
      envPath: [b],
      architecture: 3,
      sysVersion: '3.8.13 (default, Mar 28 2022, 11:38:47) \n[GCC 7.5.0]',
      version: [Object],
      companyDisplayName: 'Anaconda, Inc.',
      displayName: "Python 3.8.13 ('py38')",
      detailedDisplayName: "Python 3.8.13 ('py38': conda)",
      uri: [b]
    },
    kernelSpec: {
      specFile: undefined,
      interpreterPath: undefined,
      isRegisteredByVSC: undefined,
      name: 'python3',
      argv: [Array],
      language: 'python',
      executable: '/home/kwangeun/.conda/envs/py38/bin/python',
      display_name: 'Python 3 (ipykernel)',
      metadata: [Object],
      env: {},
      interrupt_mode: undefined
    },
    id: 'c483d88b0358a487987b4ec3be66258278dc0eb8235582295c438285496ca577..python3./home/kwangeun/.conda/envs/py38/python./.-m#ipykernel_launcher',
    baseUrl: 'http://localhost:8720/',
    serverId: 'c483d88b0358a487987b4ec3be66258278dc0eb8235582295c438285496ca577'
  }
}
error 13:47:10.544: Error in execution (get message for cell) [s [Error]: The Jupyter notebook server failed to launch in time
	at waitForIdleOnSession (/home/kwangeun/.vscode-server/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:1924148)
	at async w.createNewKernelSession (/home/kwangeun/.vscode-server/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:2198605)
	at async w.connect (/home/kwangeun/.vscode-server/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:2197323)
	at async u.startNew (/home/kwangeun/.vscode-server/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:2205819)
	at async a (/home/kwangeun/.vscode-server/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:2141520)
	at async _.createNotebookInstance (/home/kwangeun/.vscode-server/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:2141683)
	at async _.createNotebook (/home/kwangeun/.vscode-server/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:2142688)] {
  category: 'timeout',
  kernelConnectionMetadata: {
    kind: 'startUsingRemoteKernelSpec',
    interpreter: {
      id: '/home/kwangeun/.conda/envs/py38/bin/python',
      sysPrefix: '/home/kwangeun/.conda/envs/py38',
      envType: 'Conda',
      envName: 'py38',
      envPath: [b],
      architecture: 3,
      sysVersion: '3.8.13 (default, Mar 28 2022, 11:38:47) \n[GCC 7.5.0]',
      version: [Object],
      companyDisplayName: 'Anaconda, Inc.',
      displayName: "Python 3.8.13 ('py38')",
      detailedDisplayName: "Python 3.8.13 ('py38': conda)",
      uri: [b]
    },
    kernelSpec: {
      specFile: undefined,
      interpreterPath: undefined,
      isRegisteredByVSC: undefined,
      name: 'python3',
      argv: [Array],
      language: 'python',
      executable: '/home/kwangeun/.conda/envs/py38/bin/python',
      display_name: 'Python 3 (ipykernel)',
      metadata: [Object],
      env: {},
      interrupt_mode: undefined
    },
    id: 'c483d88b0358a487987b4ec3be66258278dc0eb8235582295c438285496ca577..python3./home/kwangeun/.conda/envs/py38/python./.-m#ipykernel_launcher',
    baseUrl: 'http://localhost:8720/',
    serverId: 'c483d88b0358a487987b4ec3be66258278dc0eb8235582295c438285496ca577'
  }
}
```

### Running Jupyter locally or remotely?

Remote

**Comment by yeokwangeun** [comment]
Thank you for the comment. I can't figure out why but now the jupyter notebook works fine. I guess there were some issues in my servers. Anyway, thank you for you help!
