### ISSUE TITLE
VScode fails to start jupyter

### ISSUE THREAD

**Issue by jhyland01** [microsoft/vscode-jupyter#11102]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Stopped working a couple days ago I think after a VScode update. If I just try to run any cell in a jupyter notebook I get the below error. It's the same for all kernels. Jupyter otherwise works fine from the command line. Also tried the pre-release jupyter extension and no luck. Any help would be much appreciated!

Failed to start the Kernel. 
Traceback (most recent call last):
  File "/Users/johnny/.vscode/extensions/ms-toolsai.jupyter-2022.7.1002181843/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py", line 158, in _start_notebook
    from notebook import notebookapp as app
  File "/Users/johnny/opt/anaconda3/lib/python3.8/site-packages/notebook/notebookapp.py", line 45, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "/Users/johnny/opt/anaconda3/lib/python3.8/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/Users/johnny/opt/anaconda3/lib/python3.8/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/Users/johnny/opt/anaconda3/lib/python3.8/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/Users/johnny/opt/anaconda3/lib/python3.8/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/Users/johnny/opt/anaconda3/lib/python3.8/site-packages/markupsafe/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/johnny/.vscode/extensions/ms-toolsai.jupyter-2022.7.1002181843/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py", line 54, in _decorator
    return func(self, *args, **kwargs)
  File "/Users/johnny/.vscode/extensions/ms-toolsai.jupyter-2022.7.1002181843/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py", line 111, in m_exec_module_observable
    self._start_notebook(args, cwd, env)
  File "/Users/johnny/.vscode/extensions/ms-toolsai.jupyter-2022.7.1002181843/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py", line 160, in _start_notebook
    from notebook import app as app
ImportError: cannot import name 'app' from 'notebook' (/Users/johnny/opt/anaconda3/lib/python3.8/site-packages/notebook/__init__.py)

Failed to run jupyter as observable with args notebook --no-browser --notebook-dir="/Users/johnny...

### VS Code Version

Version: 1.70.1 (Universal) Commit: 6d9b74a70ca9c7733b29f0456fd8195364076dda Date: 2022-08-10T06:09:06.916Z Electron: 18.3.5 Chromium: 100.0.4896.160 Node.js: 16.13.2 V8: 10.0.139.17-electron.0 OS: Darwin arm64 21.6.0

### Jupyter Extension Version

v2022.7.1002181843

### Jupyter logs

```shell
error 8:6:55.950: Error in execution (get message for cell) [i [Error]: Traceback (most recent call last):
  File "/Users/johnny/.vscode/extensions/ms-toolsai.jupyter-2022.7.1002181843/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py", line 158, in _start_notebook
    from notebook import notebookapp as app
  File "/Users/johnny/opt/anaconda3/lib/python3.8/site-packages/notebook/notebookapp.py", line 45, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "/Users/johnny/opt/anaconda3/lib/python3.8/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/Users/johnny/opt/anaconda3/lib/python3.8/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/Users/johnny/opt/anaconda3/lib/python3.8/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/Users/johnny/opt/anaconda3/lib/python3.8/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/Users/johnny/opt/anaconda3/lib/python3.8/site-packages/markupsafe/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/johnny/.vscode/extensions/ms-toolsai.jupyter-2022.7.1002181843/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py", line 54, in _decorator
    return func(self, *args, **kwargs)
  File "/Users/johnny/.vscode/extensions/ms-toolsai.jupyter-2022.7.1002181843/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py", line 111, in m_exec_module_observable
    self._start_notebook(args, cwd, env)
  File "/Users/johnny/.vscode/extensions/ms-toolsai.jupyter-2022.7.1002181843/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py", line 160, in _start_notebook
    from notebook import app as app
ImportError: cannot import name 'app' from 'notebook' (/Users/johnny/opt/anaconda3/lib/python3.8/site-packages/notebook/__init__.py)

Failed to run jupyter as observable with args notebook --no-browser --notebook-dir="/Users/johnny/directory" --config=/var/folders/wh/srwjqw_j5gsbl1y7xdb9jc900000gn/T/a3d6aeff-2cd8-4751-9949-f04b6190dbdc/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0

	at t.JupyterConnectionWaiter.rejectStartPromise (/Users/johnny/.vscode/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:2121027)
	at t._error (/Users/johnny/.vscode/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:2121628)
	at t.__tryOrUnsub (/Users/johnny/.vscode/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:1332520)
	at t.error (/Users/johnny/.vscode/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:1331929)
	at t._error (/Users/johnny/.vscode/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:1330814)
	at t.error (/Users/johnny/.vscode/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:1330508)
	at t.error (/Users/johnny/.vscode/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:2:1328014)
	at /Users/johnny/.vscode/extensions/ms-toolsai.jupyter-2022.7.1002181843/out/extension.node.js:7:30161] {
  category: 'jupyterconnection'
}
```

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, and I'm sorry about this issue.
Looks like some package seems to have been installed into some conda environment that seems to be causing this issue. 

* You could confirm this is a problem with the current update, by just reverting to the previous version and checking whether it works in the previous version or not.
* Please could you provide all of the output from the `Jupyter` output panel. I'd like to see the path to the python environment and then I might have some other suggestions.
* Alternatively you can use the command `Jupyter: Select Interpreter to Start Jupyter Server` 
    * Once you click that you'll get a list of interpterers and you'll also see what's currently selected.
    * You could try selecting another python environment and following through the prompts to install the necessary dependencies such as Jupyter notebook and the like.

**Comment by jhyland01** [comment]
Great thanks,
I installed jupyter_server then reselected the environment in the 'Jupyter: Select Interpreter to Start Jupyter Server' command and we seem to be back in business!
Closing as fixed.
