### ISSUE TITLE
Interleaved prints and sleeps mess up output lines in Julia

### ISSUE THREAD

**Issue by bicycle1885** [microsoft/vscode-jupyter#11136]
## Environment data

-   VS Code version: 1.70.1
-   Jupyter Extension version (available under the Extensions sidebar): v2022.7.1102252217
-   Python Extension version (available under the Extensions sidebar): v2022.12.0
-   OS (Windows | Mac | Linux distro) and version: Mac 12.5 (Monterey)
-   Python and/or Anaconda version: Python 3.10.6 (downloaded from python.org)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local (this also happens on SSH remote)

The Julia version is 1.7.3.

## Expected behaviour

The following code prints a number for each line, from 1 to 20.
```julia
for i in 1:20
    println(i)
    sleep(0.1)
end
```

## Actual behaviour

The output shows two numbers for each line, followed by a blank line (see the screenshot).

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/905683/184918960-1f86cf2e-1ac7-4b2e-9933-6fe3492c06c2.png">

## Steps to reproduce:

1. Start up a new Jupyter Notebook.
2. Write the code shown above in a cell.
3. Run the cell.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Visual Studio Code (1.70.1, undefined, desktop)
Jupyter Extension Version: 2022.7.1102252217.
Python Extension Version: 2022.12.0.
Workspace folder /Users/kenta/tmp
error 17:15:55.105: Exception while attempting zmq : Error: No native build was found for platform=darwin arch=arm64 runtime=electron abi=103 uv=1 armv=8 libc=glibc node=16.13.2 electron=18.3.5
    loaded from: /Users/kenta/.vscode/extensions/ms-toolsai.jupyter-2022.7.1102252217/out/node_modules/zeromq

    at Function.load.path (/Users/kenta/.vscode/extensions/ms-toolsai.jupyter-2022.7.1102252217/out/node_modules/node-gyp-build/index.js:1:3163)
    at load (/Users/kenta/.vscode/extensions/ms-toolsai.jupyter-2022.7.1102252217/out/node_modules/node-gyp-build/index.js:1:648)
    at Object.<anonymous> (/Users/kenta/.vscode/extensions/ms-toolsai.jupyter-2022.7.1102252217/out/node_modules/zeromq/lib/native.js:1:198)
    at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1313)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.r._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:14538)
    at Function.b._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:62507)
    at Function.v._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:61875)
    at Module.require (node:internal/modules/cjs/loader:1059:19)
    at p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:699)
    at Object.<anonymous> (/Users/kenta/.vscode/extensions/ms-toolsai.jupyter-2022.7.1102252217/out/node_modules/zeromq/lib/index.js:1:144)
    at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1313)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.r._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:14538)
    at Function.b._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:62507)
    at Function.v._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:61875)
    at Module.require (node:internal/modules/cjs/loader:1059:19)
    at p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:699)
    at Object.92747 (/Users/kenta/.vscode/extensions/ms-toolsai.jupyter-2022.7.1102252217/out/extension.node.js:17:480874)
    at __webpack_require__ (/Users/kenta/.vscode/extensions/ms-toolsai.jupyter-2022.7.1102252217/out/extension.node.js:17:1359444)
    at l.zmqSupported (/Users/kenta/.vscode/extensions/ms-toolsai.jupyter-2022.7.1102252217/out/extension.node.js:2:2323521)
    at l.isSupportedForLocalLaunch (/Users/kenta/.vscode/extensions/ms-toolsai.jupyter-2022.7.1102252217/out/extension.node.js:2:2323264)
    at l.get isSupported [as isSupported] (/Users/kenta/.vscode/extensions/ms-toolsai.jupyter-2022.7.1102252217/out/extension.node.js:2:2323174)
    at t.registerTypes (/Users/kenta/.vscode/extensions/ms-toolsai.jupyter-2022.7.1102252217/out/extension.node.js:2:2337703)
    at /Users/kenta/.vscode/extensions/ms-toolsai.jupyter-2022.7.1102252217/out/extension.node.js:17:1364938
    at /Users/kenta/.vscode/extensions/ms-toolsai.jupyter-2022.7.1102252217/out/extension.node.js:17:1365693
    at /Users/kenta/.vscode/extensions/ms-toolsai.jupyter-2022.7.1102252217/out/extension.node.js:17:1365701
    at e.activate (/Users/kenta/.vscode/extensions/ms-toolsai.jupyter-2022.7.1102252217/out/extension.node.js:17:1365823)
    at Function._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:17473)
    at Function._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:17131)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:14942
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at v._activate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:8180)
    at v._waitForDepsThenActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:8122)
    at v._initialize (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:7486)
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 17:15:55.285: LSP Notebooks experiment is enabled
info 17:15:55.329: Preferred Remote kernel for Untitled-1.ipynb is undefined
info 17:15:55.329: Find preferred kernel for Untitled-1.ipynb with metadata {"orig_nbformat":4} & preferred interpreter 
info 17:15:55.329: Preferred Remote kernel for Untitled-1.ipynb is undefined
info 17:15:55.369: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
info 17:15:55.414: Process Execution: > /usr/bin/python3 -m pip list
> /usr/bin/python3 -m pip list
info 17:15:55.416: Process Execution: > /usr/bin/python3 -c "import jupyter"
> /usr/bin/python3 -c "import jupyter"
info 17:15:55.417: Process Execution: > /usr/bin/python3 -c "import notebook"
> /usr/bin/python3 -c "import notebook"
info 17:15:55.564: Preferred Remote kernel for Untitled-1.ipynb is undefined
info 17:15:55.564: Find preferred kernel for Untitled-1.ipynb with metadata {"orig_nbformat":4} & preferred interpreter 
info 17:15:55.565: Preferred Remote kernel for Untitled-1.ipynb is undefined
info 17:15:55.566: Preferred Remote kernel for Untitled-1.ipynb is undefined
info 17:16:45.872: Attempting to start a server because of preload conditions ...
info 17:16:45.875: Preferred Remote kernel for /Users/kenta/tmp/Untitled-1.ipynb is undefined
info 17:16:45.876: Checking for server existence.
info 17:16:45.876: Checking for server usability.
info 17:16:45.877: Server not usable (should ask for install now)
info 17:16:45.879: Process Execution: > /usr/bin/python3 -c "import jupyter"
> /usr/bin/python3 -c "import jupyter"
info 17:16:45.879: Process Execution: > /usr/bin/python3 -c "import notebook"
> /usr/bin/python3 -c "import notebook"
info 17:16:45.879: Preferred Remote kernel for /Users/kenta/tmp/Untitled-1.ipynb is undefined
info 17:16:45.879: Find preferred kernel for /Users/kenta/tmp/Untitled-1.ipynb with metadata {"orig_nbformat":4,"language_info":{"name":"python"}} & preferred interpreter /usr/bin/python3
info 17:16:45.880: Preferred Remote kernel for /Users/kenta/tmp/Untitled-1.ipynb is undefined
info 17:16:45.880: Preferred kernel .jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6./usr/bin/python3./usr/bin/python3.-m#ipykernel_launcher is exact match or top match for non python kernels, (false, [object Object], false, false)
info 17:16:45.880: PreferredConnection: .jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6./usr/bin/python3./usr/bin/python3.-m#ipykernel_launcher found for NotebookDocument: /Users/kenta/tmp/Untitled-1.ipynb
error 17:16:45.908: Error starting server in serverPreload:  i [Error]: Jupyter cannot be started. Error attempting to locate Jupyter: Running cells with 'Python 3.8.9 64-bit' requires jupyter and notebook package.
    at S.startServer (/Users/kenta/.vscode/extensions/ms-toolsai.jupyter-2022.7.1102252217/out/extension.node.js:2:2152500)
    at S.createServer (/Users/kenta/.vscode/extensions/ms-toolsai.jupyter-2022.7.1102252217/out/extension.node.js:2:2151620)
    at l.connect (/Users/kenta/.vscode/extensions/ms-toolsai.jupyter-2022.7.1102252217/out/extension.node.js:2:2128799)
    at v.createServerIfNecessary (/Users/kenta/.vscode/extensions/ms-toolsai.jupyter-2022.7.1102252217/out/extension.node.js:2:2160604) {
  category: 'jupyterinstall'
}
```

</p>
</details>

**Comment by bicycle1885** [comment]
#10982 might be a related issue.

**Comment by bicycle1885** [comment]
In addition, I discovered that the second (right) outputs are not printed with a monospace font
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/905683/184923129-827c33a0-adaf-461e-9d7a-30f89f7b1ce8.png">

**Comment by DonJayamanne** [comment]
If you have the Julia extension installed, then please disable that extension. & try this again.
Let me know how that goes.

> covered that the second (right) outputs are not printed with a monospace font

Plaese could you file a seprate issue for this.

**Comment by bicycle1885** [comment]
I wrongly assumed that this extension manages Julia kernels, but they are actually managed by the Julia extension. I find that if I install IJulia.jl and use that kernel with the Julia extension being disabled, the problem disappears. I'm sorry for that.
