### ISSUE TITLE
jupyter can't export PDF

### ISSUE THREAD

**Issue by xxc-zsz** [microsoft/vscode-jupyter#11200]
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I have installed all the needed things referring to this [link](https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex), but I still get the error when I use juoyter to export the PDF.

```
error 16:38:17.519: If you have not installed xelatex (TeX) you will need to do so before you can export to PDF, for further instructions please look https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex. 
To avoid installing xelatex (TeX) you might want to try exporting to HTML and using your browsers "Print to PDF" feature.
```
**Simple example**

![image](https://user-images.githubusercontent.com/108051416/186861976-d9da3c50-a8c0-4c77-8079-297fb05bb543.png)

![image](https://user-images.githubusercontent.com/108051416/186862166-4c1a1b2a-e611-4193-a479-9efe2d2bceb4.png)

![image](https://user-images.githubusercontent.com/108051416/186863215-06ba6a46-6238-4e71-9045-67d457fd1a4e.png)

### VS Code Version

Version: 1.70.2 (system setup) Commit: e4503b30fc78200f846c62cf8091b76ff5547662 Date: 2022-08-16T05:35:13.448Z Electron: 18.3.5 Chromium: 100.0.4896.160 Node.js: 16.13.2 V8: 10.0.139.17-electron.0 OS: Windows_NT x64 10.0.17763

### Jupyter Extension Version

v2022.7.1102252217

### Jupyter logs

```shell
info 16:46:44.112: Process Execution: > c:\WorkSpace\PyTest0802\.venv\Scripts\python.exe -m jupyter nbconvert ~\AppData\Local\Temp\c821287d-0643-4591-a4e0-9770b5436c26\Test01.ipynb --to pdf --output tmp-12656XXR4h5zW7BUU.pdf --output-dir ~\AppData\Local\Temp --debug
> c:\WorkSpace\PyTest0802\.venv\Scripts\python.exe -m jupyter nbconvert ~\AppData\Local\Temp\c821287d-0643-4591-a4e0-9770b5436c26\Test01.ipynb --to pdf --output tmp-12656XXR4h5zW7BUU.pdf --output-dir ~\AppData\Local\Temp --debug
error 16:46:49.231: Export failed [Error: [NbConvertApp] Searching ['C:\\Program Files\\Microsoft VS Code', 'C:\\Users\\Admin\\.jupyter', 'c:\\WorkSpace\\PyTest0802\\.venv\\etc\\jupyter', 'C:\\ProgramData\\jupyter'] for config files
[NbConvertApp] Looking for jupyter_config in C:\ProgramData\jupyter
[NbConvertApp] Looking for jupyter_config in c:\WorkSpace\PyTest0802\.venv\etc\jupyter
[NbConvertApp] Looking for jupyter_config in C:\Users\Admin\.jupyter
[NbConvertApp] Looking for jupyter_config in C:\Program Files\Microsoft VS Code
[NbConvertApp] Looking for jupyter_nbconvert_config in C:\ProgramData\jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in c:\WorkSpace\PyTest0802\.venv\etc\jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in C:\Users\Admin\.jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in C:\Program Files\Microsoft VS Code
[NbConvertApp] Converting notebook c:\Users\Admin\AppData\Local\Temp\c821287d-0643-4591-a4e0-9770b5436c26\Test01.ipynb to pdf
[NbConvertApp] Notebook name is 'tmp-12656XXR4h5zW7BUU'
[NbConvertApp] Template paths:
	c:\WorkSpace\PyTest0802\.venv\share\jupyter\nbconvert\templates\latex
	c:\WorkSpace\PyTest0802\.venv\share\jupyter\nbconvert\templates\base
	C:\Users\Admin\AppData\Roaming\jupyter
	C:\Users\Admin\AppData\Roaming\jupyter\nbconvert\templates
	C:\Users\Admin\AppData\Roaming\jupyter\nbconvert\templates\compatibility
	c:\WorkSpace\PyTest0802\.venv\share\jupyter
	c:\WorkSpace\PyTest0802\.venv\share\jupyter\nbconvert\templates
	c:\WorkSpace\PyTest0802\.venv\share\jupyter\nbconvert\templates\compatibility
	C:\ProgramData\jupyter
	C:\ProgramData\jupyter\nbconvert\templates
	C:\ProgramData\jupyter\nbconvert\templates\compatibility
	c:\WorkSpace\PyTest0802\.venv\share\jupyter\nbconvert\templates
[NbConvertApp] Applying preprocessor: TagRemovePreprocessor
[NbConvertApp] Applying preprocessor: RegexRemovePreprocessor
[NbConvertApp] Applying preprocessor: coalesce_streams
[NbConvertApp] Applying preprocessor: SVG2PDFPreprocessor
[NbConvertApp] Applying preprocessor: LatexPreprocessor
[NbConvertApp] Applying preprocessor: HighlightMagicsPreprocessor
[NbConvertApp] Applying preprocessor: ExtractOutputPreprocessor
[NbConvertApp] Attempting to load template index.tex.j2
[NbConvertApp]     template_paths: c:\WorkSpace\PyTest0802\.venv\share\jupyter\nbconvert\templates\latex;c:\WorkSpace\PyTest0802\.venv\share\jupyter\nbconvert\templates\base;C:\Users\Admin\AppData\Roaming\jupyter;C:\Users\Admin\AppData\Roaming\jupyter\nbconvert\templates;C:\Users\Admin\AppData\Roaming\jupyter\nbconvert\templates\compatibility;c:\WorkSpace\PyTest0802\.venv\share\jupyter;c:\WorkSpace\PyTest0802\.venv\share\jupyter\nbconvert\templates;c:\WorkSpace\PyTest0802\.venv\share\jupyter\nbconvert\templates\compatibility;C:\ProgramData\jupyter;C:\ProgramData\jupyter\nbconvert\templates;C:\ProgramData\jupyter\nbconvert\templates\compatibility;c:\WorkSpace\PyTest0802\.venv\share\jupyter\nbconvert\templates
[NbConvertApp] Writing 19732 bytes to notebook.tex
[NbConvertApp] Building PDF
Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Admin\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\WorkSpace\PyTest0802\.venv\Scripts\jupyter-nbconvert.EXE\__main__.py", line 7, in <module>
  File "c:\WorkSpace\PyTest0802\.venv\lib\site-packages\jupyter_core\application.py", line 269, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "c:\WorkSpace\PyTest0802\.venv\lib\site-packages\traitlets\config\application.py", line 976, in launch_instance
    app.start()
  File "c:\WorkSpace\PyTest0802\.venv\lib\site-packages\nbconvert\nbconvertapp.py", line 426, in start
    self.convert_notebooks()
  File "c:\WorkSpace\PyTest0802\.venv\lib\site-packages\nbconvert\nbconvertapp.py", line 600, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "c:\WorkSpace\PyTest0802\.venv\lib\site-packages\nbconvert\nbconvertapp.py", line 563, in convert_single_notebook
    output, resources = self.export_single_notebook(
  File "c:\WorkSpace\PyTest0802\.venv\lib\site-packages\nbconvert\nbconvertapp.py", line 491, in export_single_notebook
    output, resources = self.exporter.from_filename(
  File "c:\WorkSpace\PyTest0802\.venv\lib\site-packages\nbconvert\exporters\exporter.py", line 190, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "c:\WorkSpace\PyTest0802\.venv\lib\site-packages\nbconvert\exporters\exporter.py", line 207, in from_file
    return self.from_notebook_node(
  File "c:\WorkSpace\PyTest0802\.venv\lib\site-packages\nbconvert\exporters\pdf.py", line 194, in from_notebook_node
    self.run_latex(tex_file)
  File "c:\WorkSpace\PyTest0802\.venv\lib\site-packages\nbconvert\exporters\pdf.py", line 164, in run_latex
    return self.run_command(
  File "c:\WorkSpace\PyTest0802\.venv\lib\site-packages\nbconvert\exporters\pdf.py", line 111, in run_command
    raise OSError(
OSError: xelatex not found on PATH, if you have not installed xelatex you may need to do so. Find further instructions at https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex.

	at y.executeCommand (c:\Users\Admin\.vscode\extensions\ms-toolsai.jupyter-2022.7.1102252217\out\extension.node.js:2:2541516)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async a.export (c:\Users\Admin\.vscode\extensions\ms-toolsai.jupyter-2022.7.1102252217\out\extension.node.js:2:2549071)
	at async f.exportToFormat (c:\Users\Admin\.vscode\extensions\ms-toolsai.jupyter-2022.7.1102252217\out\extension.node.js:2:2559265)
	at async f.performNbConvertExport (c:\Users\Admin\.vscode\extensions\ms-toolsai.jupyter-2022.7.1102252217\out\extension.node.js:2:2559069)
	at async f.performExport (c:\Users\Admin\.vscode\extensions\ms-toolsai.jupyter-2022.7.1102252217\out\extension.node.js:2:2558724)
	at async f.exportImpl (c:\Users\Admin\.vscode\extensions\ms-toolsai.jupyter-2022.7.1102252217\out\extension.node.js:2:2558242)
	at async f.export (c:\Users\Admin\.vscode\extensions\ms-toolsai.jupyter-2022.7.1102252217\out\extension.node.js:2:2557966)
	at async t.ExportCommands.export (c:\Users\Admin\.vscode\extensions\ms-toolsai.jupyter-2022.7.1102252217\out\extension.node.js:17:208429)
	at async a._executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:63914)]
error 16:46:49.232: If you have not installed xelatex (TeX) you will need to do so before you can export to PDF, for further instructions please look https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex. 
To avoid installing xelatex (TeX) you might want to try exporting to HTML and using your browsers "Print to PDF" feature.
```

### Coding Language and Runtime Version

Pyhon 3.9.12

### Language Extension Version (if applicable)

Python v2022.12.1

**Comment by IanMatthewHuff** [comment]
@xxc-zsz At the point this error is happening it's actually nbconvert performing the PDF convert under the covers. Given the error here it sounds like TeX might be installed, but it can't find it on the path. Per some other discussions online it looks like the advice here for getting it onto the path might be helpful, could you please try this out?

https://stackoverflow.com/a/55499329/2654002

**Comment by xxc-zsz** [comment]
Thanks, solved the problem with some hints in the link.
