### ISSUE TITLE
Test failure: Render ipyvolume

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-jupyter#11332]
https://github.com/microsoft/vscode-jupyter/runs/8246707383?check_suite_focus=true

**Comment by DonJayamanne** [comment]
```
2022-09-08T10:26:35.8309026Z NO notebook document for 'file:///tmp/emptyPython0c4c4024-46a2-4ee7-a243-e7c540eaf291..ipynb': Error: NO notebook document for 'file:///tmp/emptyPython0c4c4024-46a2-4ee7-a243-e7c540eaf291..ipynb'
2022-09-08T10:26:35.8310527Z     at v.getNotebookDocument (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:92322)
2022-09-08T10:26:35.8311769Z     at p.$cancelCells (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:106634)
2022-09-08T10:26:35.8313066Z     at r._doInvokeHandler (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:13680)
2022-09-08T10:26:35.8315228Z     at r._invokeHandler (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:13362)
2022-09-08T10:26:35.8316482Z     at r._receiveRequest (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:12132)
2022-09-08T10:26:35.8318072Z     at r._receiveOneMessage (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:10834)
2022-09-08T10:26:35.8319043Z     at /home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:8941
2022-09-08T10:26:35.8319946Z     at g.invoke (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
2022-09-08T10:26:35.8320828Z     at v.deliver (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
2022-09-08T10:26:35.8321969Z     at b.fire (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
2022-09-08T10:26:35.8322837Z     at a.fire (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:19039)
2022-09-08T10:26:35.8323700Z     at /home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:17106
2022-09-08T10:26:35.8324569Z     at g.invoke (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
2022-09-08T10:26:35.8325442Z     at v.deliver (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
2022-09-08T10:26:35.8326336Z     at b.fire (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
2022-09-08T10:26:35.8327203Z     at a.fire (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:19039)
2022-09-08T10:26:35.8328150Z     at MessagePortMain.<anonymous> (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:15146)
2022-09-08T10:26:35.8328691Z     at MessagePortMain.emit (node:events:526:28)
2022-09-08T10:26:35.8329136Z     at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_process_init:5:364)
2022-09-08T10:26:36.0830504Z info 10:26:36.081:  Sending message to Widget renderer {"requestId":"1662632796081","cellIndex":1,"command":"queryInnerHTML"}
2022-09-08T10:26:36.3358666Z info 10:26:36.334:  Sending message to Widget renderer {"requestId":"1662632796334","cellIndex":1,"command":"queryInnerHTML"}
```

**Comment by DonJayamanne** [comment]
Should now be fixed
