### ISSUE TITLE
IPython.display.Code syntax highlighting doesn't work

### ISSUE THREAD

**Issue by davidchall** [microsoft/vscode-jupyter#11402]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

In Jupyter Notebook (official), we can use the `IPython.display.Code` class to display syntax highlighted source code (using pygments in the background). For example,

![image](https://user-images.githubusercontent.com/1804856/191073980-40b5d5b0-a059-4c40-83e8-4265138fb0b0.png)

In Jupyter Notebook (VS Code), the source code is displayed but does not feature syntax highlighting. For example,

![image](https://user-images.githubusercontent.com/1804856/191074818-221b5180-4608-42c6-8acf-5016b00406e5.png)

This problem also occurs with JupterLab (https://github.com/ipython/ipython/issues/11747), so there might be overlap in the root cause.

### VS Code Version

1.71.2

### Jupyter Extension Version

v2022.8.1002431955

### Jupyter logs

```shell
Visual Studio Code (1.71.2, undefined, desktop)
Jupyter Extension Version: 2022.8.1002431955.
Python Extension Version: 2022.14.0.
No workspace folder opened.
info 10:16:57.469: ZMQ install verified.
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 10:16:57.774: LSP Notebooks experiment is enabled
info 10:16:57.808: Preferred Remote kernel for Untitled-1.ipynb is undefined
info 10:16:57.808: Find preferred kernel for Untitled-1.ipynb with metadata {"orig_nbformat":4} & preferred interpreter 
info 10:16:57.809: Preferred Remote kernel for Untitled-1.ipynb is undefined
info 10:16:59.708: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
info 10:17:2.718: Process Execution: > ~\Anaconda3\python.exe -m pip list
> ~\Anaconda3\python.exe -m pip list
info 10:17:6.814: Preferred Remote kernel for Untitled-1.ipynb is undefined
info 10:17:6.814: Find preferred kernel for Untitled-1.ipynb with metadata {"orig_nbformat":4} & preferred interpreter 
info 10:17:6.815: Preferred Remote kernel for Untitled-1.ipynb is undefined
info 10:17:6.818: Preferred Remote kernel for Untitled-1.ipynb is undefined
info 10:17:14.18: Execute Cell 0 Untitled-1.ipynb
info 10:17:14.23: Starting Jupyter Session id = 'startUsingPythonInterpreter:.jvsc<redacted>.c:\Users\davidhall\Anaconda3\python.exe.c:\Users\davidhall\Anaconda3\python.exe.-m#ipykernel_launcher' (Python Path: c:\Users\davidhall\Anaconda3, EnvType: Conda, EnvName: 'base', Version: 3.9.7) for 'Untitled-1.ipynb' (disableUI=false)
info 10:17:14.24: Creating raw notebook for resource 'Untitled-1.ipynb'
info 10:17:14.24: Computing working directory for resource 'Untitled-1.ipynb'
info 10:17:14.25: Starting raw kernel 'base (Python 3.9.7)' for interpreter c:\Users\davidhall\Anaconda3\python.exe
info 10:17:14.348: Process Execution: > ~\Anaconda3\python.exe -c "import ipykernel; print(ipykernel.__version__); print("<redacted>"); print(ipykernel.__file__)"
> ~\Anaconda3\python.exe -c "import ipykernel; print(ipykernel.__version__); print("<redacted>"); print(ipykernel.__file__)"
info 10:17:14.400: Kernel launching with ports 9000,9001,9002,9003,9004. Start port is 9000
info 10:17:14.533: Process Execution: > ~\Anaconda3\python.exe ~\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\pythonFiles\vscode_datascience_helpers\kernel_interrupt_daemon.py --ppid 18684
> ~\Anaconda3\python.exe ~\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\pythonFiles\vscode_datascience_helpers\kernel_interrupt_daemon.py --ppid 18684
info 10:17:14.533: Process Execution: cwd: ~\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\pythonFiles\vscode_datascience_helpers
cwd: ~\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\pythonFiles\vscode_datascience_helpers
info 10:17:14.909: Process Execution: > ~\Anaconda3\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"<redacted>" --shell=9002 --transport="tcp" --iopub=9004 --f=c:\Users\davidhall\AppData\Roaming\jupyter\runtime\kernel-v2-186842mUgiVRw1R24.json
> ~\Anaconda3\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"<redacted>" --shell=9002 --transport="tcp" --iopub=9004 --f=c:\Users\davidhall\AppData\Roaming\jupyter\runtime\kernel-v2-186842mUgiVRw1R24.json
info 10:17:14.909: Process Execution: cwd: ~\AppData\Local\Programs\Microsoft VS Code
cwd: ~\AppData\Local\Programs\Microsoft VS Code
info 10:17:14.912: Widget Message: Received IPyWidgetMessages.IPyWidgets_IsReadyRequest
info 10:17:14.914: ipykernel version 6.15.2 for c:\Users\davidhall\Anaconda3\python.exe
info 10:17:14.914: ipykernel location ~\Anaconda3\lib\site-packages\ipykernel\__init__.py for c:\Users\davidhall\Anaconda3\python.exe
warn 10:17:16.481: StdErr from Kernel Process c:\Users\davidhall\Anaconda3\lib\site-packages\traitlets\traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
c:\Users\davidhall\Anaconda3\lib\site-packages\traitlets\traitlets.py:2157: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '<redacted>' instead of 'b"<redacted>"'.
  warn(

info 10:17:16.535: Kernel Output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing c:\Users\davidhall\AppData\Roaming\jupyter\runtime\kernel-v2-186842mUgiVRw1R24.json

info 10:17:16.616: Started kernel base (Python 3.9.7)., (Raw session started and connected)
info 10:17:16.616: Finished connecting <redacted>
error 10:17:16.624: stat() failed for "untitled:Untitled-1.ipynb?jupyter-notebook" [Error (FileSystemError): Unable to resolve filesystem provider with relative file path 'untitled:Untitled-1.ipynb?jupyter-notebook'
	at Qt._handleError (c:\Users\davidhall\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:30174)
	at Object.stat (c:\Users\davidhall\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:28102)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async b.exists (c:\Users\davidhall\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:7:20271)
	at async y.getCode (c:\Users\davidhall\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:2285764)
	at async Promise.all (index 1)
	at async t.Kernel.gatherInternalStartupCode (c:\Users\davidhall\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:2250440)
	at async t.Kernel.initializeAfterStart (c:\Users\davidhall\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:2249025)
	at async t.Kernel.createJupyterSession (c:\Users\davidhall\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:2246430)
	at async t.Kernel.start (c:\Users\davidhall\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:2241145)
	at async k.wrapKernelMethodImpl (c:\Users\davidhall\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:2492201)] {
  code: 'Unknown'
}
info 10:17:16.625: Executing silently Code (busy) = import os as __VSCODE_os\n__VSCODE_os.environ["PYDEVD_IPYTHON_COMPATIBLE_DEBUGGING"] = "1"\ndel __VSCO
info 10:17:16.794: Executing silently Code (completed) = import os as __VSCODE_os\n__VSCODE_os.environ["PYDEVD_IPYTHON_COMPATIBLE_DEBUGGING"] = "1"\ndel __VSCO with 0 output(s)
info 10:17:16.795: Waiting for idle on (kernel): <redacted> -> idle
info 10:17:16.795: Finished waiting for idle on (kernel): <redacted> -> idle
info 10:17:17.35: Process Execution: > ~\Anaconda3\python.exe ~\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\pythonFiles\printJupyterDataDir.py
> ~\Anaconda3\python.exe ~\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\pythonFiles\printJupyterDataDir.py
info 10:17:17.43: Widget Message: Received IPyWidgets_kernelOptions in ScriptManager
info 10:17:17.44: Widget Message: Received IPyWidgetMessages.IPyWidgets_kernelOptions
info 10:17:17.141: Cell 0 executed with state Success
warn 10:17:17.160: Got a non-existent Jupyer Data Dir file:///c%3A/Users/davidhall/AppData/Roaming/Python/share/jupyter
info 10:17:17.192: Widget Message: data-base-url set to https://file%2B.vscode-resource.vscode-cdn.net/c%3A/Users/davidhall/.vscode/extensions/ms-toolsai.jupyter-2022.8.1002431955/tmp/scripts/<redacted>/jupyter
```

### Coding Language and Runtime Version

Python v3.9.7

### Anaconda Version (if applicable)

conda 4.14.0

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Looks like an issue with the HTML output
