### ISSUE TITLE
Frequent Session Disposal when connected with Remote Jupyter 

### ISSUE THREAD

**Issue by Nikhil-Fulzele** [microsoft/vscode-jupyter#11491]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Recently, in my company, we started using VSCode Jupyter Notebook with remote connection and we started facing quite frequent `sessionDisposed` issues. It is occurring randomly.

Sometime, even while executing the cells it suddenly throws error of `sessionDisposed`.  Sometime, the kernel changes to local python as of sudden.

We found a pattern though, this happens mostly when the internet connection is relatively slow.

We facing this issue only with VS code remote jupyter connection and while using the JupyterHub directly from web browser or other IDE is working fine.

Can you please help understand the issue and possible solution?

### VS Code Version

1.71.2 (Universal)

### Jupyter Extension Version

2022.8.1002431955

### Jupyter logs

```shell
info 9:21:46.183: Executing silently Code (completed) = # Copyright (c) Microsoft Corporation. All rights reserved.\n# Licensed under the MIT License.\n# Sou with 1 output(s)
info 9:21:46.828: Cell 0 executed with state Success
info 9:21:47.82: Cell 1 executed with state Success
info 9:22:2.931: Execute Cell 2 c:\Users\timber\Documents\notebooks\u_python.ipynb
info 9:22:3.189: Cell 2 executed with state Success
info 9:22:3.902: Execute Cell 3 c:\Users\timber\Documents\notebooks\u_python.ipynb
info 9:22:4.546: Cell 3 executed with state Success
info 9:22:9.664: Execute Cell 5 c:\Users\timber\Documents\notebooks\u_python.ipynb
info 9:22:9.963: Cell 5 executed with state Success
info 9:22:40.918: Execute Cell 5 c:\Users\timber\Documents\notebooks\u_python.ipynb
info 9:22:42.698: Cancel all remaining cells true || Error || undefined
info 9:22:42.698: Cancel pending cells
info 9:22:42.698: Cell 5 executed with state Error
info 9:22:57.637: Execute Cell 5 c:\Users\timber\Documents\notebooks\u_python.ipynb
info 9:22:58.345: Cancel all remaining cells true || Error || undefined
info 9:22:58.345: Cancel pending cells
info 9:22:58.345: Cell 5 executed with state Error
info 9:23:2.549: Execute Cell 5 c:\Users\timber\Documents\notebooks\u_python.ipynb
info 9:23:3.761: Cancel all remaining cells true || Error || undefined
info 9:23:3.761: Cancel pending cells
info 9:23:3.761: Cell 5 executed with state Error
info 9:23:12.756: Execute Cell 5 c:\Users\timber\Documents\notebooks\u_python.ipynb
info 9:23:13.40: Cell 5 executed with state Success
info 9:23:18.628: Execute Cell 5 c:\Users\timber\Documents\notebooks\u_python.ipynb
info 9:23:18.919: Cancel all remaining cells true || Error || undefined
info 9:23:18.919: Cancel pending cells
info 9:23:18.919: Cell 5 executed with state Error
info 9:23:51.713: Execute Cell 5 c:\Users\timber\Documents\notebooks\u_python.ipynb
info 9:23:52.115: Cell 5 executed with state Success
info 9:23:54.847: Execute Cell 5 c:\Users\timber\Documents\notebooks\u_python.ipynb
info 9:23:55.240: Cell 5 executed with state Success
info 9:24:2.58: Execute Cell 5 c:\Users\timber\Documents\notebooks\u_python.ipynb
info 9:24:2.368: Cancel all remaining cells true || Error || undefined
info 9:24:2.368: Cancel pending cells
info 9:24:2.368: Cell 5 executed with state Error
info 9:24:5.288: Execute Cell 5 c:\Users\timber\Documents\notebooks\u_python.ipynb
info 9:24:5.533: Cell 5 executed with state Success
info 9:24:7.786: Execute Cell 5 c:\Users\timber\Documents\notebooks\u_python.ipynb
info 9:24:8.96: Cell 5 executed with state Success
info 9:24:30.425: Execute Cell 6 c:\Users\timber\Documents\notebooks\u_python.ipynb
info 9:24:30.740: Cell 6 executed with state Success
info 9:24:45.535: Execute Cell 6 c:\Users\timber\Documents\notebooks\u_python.ipynb
info 9:24:47.602: Cancel all remaining cells true || Error || undefined
info 9:24:47.603: Cancel pending cells
info 9:24:47.603: Cell 6 executed with state Error
info 9:25:21.793: Execute Cell 6 c:\Users\timber\Documents\notebooks\u_python.ipynb
info 9:25:22.92: Cell 6 executed with state Success
info 9:25:27.713: Execute Cell 5 c:\Users\timber\Documents\notebooks\u_python.ipynb
info 9:25:28.32: Cell 5 executed with state Success
info 9:26:36.147: Execute Cell 5 c:\Users\timber\Documents\notebooks\u_python.ipynb
info 9:26:36.424: Cell 5 executed with state Success
info 9:27:38.223: Execute Cell 9 c:\Users\timber\Documents\notebooks\u_python.ipynb
info 9:27:38.510: Cancel all remaining cells true || Error || undefined
info 9:27:38.510: Cancel pending cells
info 9:27:38.510: Cell 9 executed with state Error
info 9:27:41.921: Execute Cell 9 c:\Users\timber\Documents\notebooks\u_python.ipynb
info 9:27:42.220: Cancel all remaining cells true || Error || undefined
info 9:27:42.220: Cancel pending cells
info 9:27:42.220: Cell 9 executed with state Error
info 9:28:51.384: Execute Cell 9 c:\Users\timber\Documents\notebooks\u_python.ipynb
info 9:28:51.671: Cancel all remaining cells true || Error || undefined
info 9:28:51.671: Cancel pending cells
info 9:28:51.671: Cell 9 executed with state Error
info 9:29:4.669: Execute Cell 9 c:\Users\timber\Documents\notebooks\u_python.ipynb
info 9:29:5.417: Cancel all remaining cells true || Error || undefined
info 9:29:5.417: Cancel pending cells
info 9:29:5.417: Cell 9 executed with state Error
info 9:29:8.642: Execute Cell 6 c:\Users\timber\Documents\notebooks\u_python.ipynb
info 9:29:8.878: Cell 6 executed with state Success
info 9:29:10.698: Execute Cell 9 c:\Users\timber\Documents\notebooks\u_python.ipynb
info 9:29:11.254: Cell 9 executed with state Success
info 9:30:42.302: Execute Cell 9 c:\Users\timber\Documents\notebooks\u_python.ipynb
error 9:30:42.316: Cell execution failed without request, for cell Index 9 [o [Error]: Cannot execute code, session has been disposed.
	at k.requestExecute (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:1940004)
	at S.executeCodeCell (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:1984706)
	at S.execute (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:1984288)
	at S.start (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:1980687)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async t.CellExecutionQueue.executeQueuedCells (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:2007873)
	at async t.CellExecutionQueue.start (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:2007243)] {
  category: 'sessionDisposed'
}
warn 9:30:42.316: Cell completed with errors [o [Error]: Cannot execute code, session has been disposed.
	at k.requestExecute (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:1940004)
	at S.executeCodeCell (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:1984706)
	at S.execute (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:1984288)
	at S.start (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:1980687)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async t.CellExecutionQueue.executeQueuedCells (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:2007873)
	at async t.CellExecutionQueue.start (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:2007243)] {
  category: 'sessionDisposed'
}
info 9:30:42.317: Cancel all remaining cells true || Error || undefined
info 9:30:42.317: Cancel pending cells
info 9:30:42.318: Cell 9 executed with state Error
info 9:30:47.698: Execute Cell 6 c:\Users\timber\Documents\notebooks\u_python.ipynb
error 9:30:47.713: Cell execution failed without request, for cell Index 6 [o [Error]: Cannot execute code, session has been disposed.
	at k.requestExecute (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:1940004)
	at S.executeCodeCell (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:1984706)
	at S.execute (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:1984288)
	at S.start (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:1980687)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async t.CellExecutionQueue.executeQueuedCells (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:2007873)
	at async t.CellExecutionQueue.start (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:2007243)] {
  category: 'sessionDisposed'
}
warn 9:30:47.713: Cell completed with errors [o [Error]: Cannot execute code, session has been disposed.
	at k.requestExecute (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:1940004)
	at S.executeCodeCell (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:1984706)
	at S.execute (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:1984288)
	at S.start (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:1980687)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async t.CellExecutionQueue.executeQueuedCells (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:2007873)
	at async t.CellExecutionQueue.start (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:2007243)] {
  category: 'sessionDisposed'
}
info 9:30:47.713: Cancel all remaining cells true || Error || undefined
info 9:30:47.713: Cancel pending cells
info 9:30:47.713: Cell 6 executed with state Error
info 14:0:4.120: Execute Cell 6 c:\Users\timber\Documents\notebooks\u_python.ipynb
error 14:0:4.141: Cell execution failed without request, for cell Index 6 [o [Error]: Cannot execute code, session has been disposed.
	at k.requestExecute (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:1940004)
	at S.executeCodeCell (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:1984706)
	at S.execute (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:1984288)
	at S.start (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:1980687)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async t.CellExecutionQueue.executeQueuedCells (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:2007873)
	at async t.CellExecutionQueue.start (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:2007243)] {
  category: 'sessionDisposed'
}
warn 14:0:4.141: Cell completed with errors [o [Error]: Cannot execute code, session has been disposed.
	at k.requestExecute (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:1940004)
	at S.executeCodeCell (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:1984706)
	at S.execute (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:1984288)
	at S.start (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:1980687)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async t.CellExecutionQueue.executeQueuedCells (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:2007873)
	at async t.CellExecutionQueue.start (c:\Users\timber\.vscode\extensions\ms-toolsai.jupyter-2022.8.1002431955\out\extension.node.js:2:2007243)] {
  category: 'sessionDisposed'
}
info 14:0:4.142: Cancel all remaining cells true || Error || undefined
info 14:0:4.142: Cancel pending cells
info 14:0:4.142: Cell 6 executed with state Error
```

### Language Extension Version (if applicable)

2022.14.0

### Running Jupyter locally or remotely?

Remote

**Comment by DonJayamanne** [comment]
@Nikhil-Fulzele thanks for filing this issue, & I'm sorry you are running into this issue
* please could you install the latest pre-release version of VS Code
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.
Please paste the output here

**Comment by Nikhil-Fulzele** [comment]
@DonJayamanne Thanks for the reply. 
Can you please help me find the pre-release version of VS Code?

Meanwhile, I have updated the Jupyter extension to pre-release version, followed the remaining steps stated above and we will be monitoring the user experience for a week or so. I will update if the issue still persists.

**Comment by DonJayamanne** [comment]
> the pre-release version of VS Code?

sorry i meant pre-regular if jupyter. looks like you got that.
let me know when you get the logs

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
