### ISSUE TITLE
Jupyter Tests failing due to an issue with Cell Tags extension

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#11547]
```
[22:36:02] Using gulpfile ~/work/vscode-jupyter/vscode-jupyter/gulpfile.js
[22:36:02] Starting 'verifyUnhandledErrors'...
Unhandled Promise Rejection with the message TypeError: Cannot read properties of undefined (reading 'apiCell'), TypeError, Cannot read properties of undefined (reading 'apiCell'), TypeError: Cannot read properties of undefined (reading 'apiCell')
    at Object.cellAt (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:36746)
    at TagTreeDataProvider.<anonymous> (/tmp/vscode_jupyter_exts/ms-toolsai.vscode-jupyter-cell-tags-0.1.5/src/cellTagsTreeDataProvider.ts:56:38)
    at Generator.next (<anonymous>)
    at /tmp/vscode_jupyter_exts/ms-toolsai.vscode-jupyter-cell-tags-0.1.5/out/extension-node.js:1214:71
    at new Promise (<anonymous>)
```

https://github.com/microsoft/vscode-jupyter/actions/runs/3193048984/jobs/5211208430

Probably needs to be moved to corresponding repo, but filed here as this blocks the Jupyter tests.
Upto you @rebornix

**Comment by rebornix** [comment]
It should be gone now as we updated the version to 0.1.6. It's a bit weird that we are also validating whether there are exceptions thrown by all extensions.
