### ISSUE TITLE
Can't convert Jupyter notebook to HTML

### ISSUE THREAD

**Issue by stevensryanw** [microsoft/vscode-jupyter#11667]
### Applies To

- [x] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Expected the notebook to be converted to HTML using the built-in export feature.

This was the output:
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/traitlets/traitlets.py", line 645, in get
    value = obj._trait_values[self.name]
KeyError: 'template_paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/jupyter_core/application.py", line 269, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/traitlets/config/application.py", line 976, in launch_instance
    app.start()
  File "/opt/homebrew/lib/python3.10/site-packages/nbconvert/nbconvertapp.py", line 426, in start
    self.convert_notebooks()
  File "/opt/homebrew/lib/python3.10/site-packages/nbconvert/nbconvertapp.py", line 594, in convert_notebooks
    cls = get_exporter(self.export_format)
  File "/opt/homebrew/lib/python3.10/site-packages/nbconvert/exporters/base.py", line 106, in get_exporter
    if getattr(exporter(config=config), "enabled", True):
  File "/opt/homebrew/lib/python3.10/site-packages/nbconvert/exporters/templateexporter.py", line 343, in __init__
    super().__init__(config=config, **kw)
  File "/opt/homebrew/lib/python3.10/site-packages/nbconvert/exporters/exporter.py", line 118, in __init__
    self._init_preprocessors()
  File "/opt/homebrew/lib/python3.10/site-packages/nbconvert/exporters/templateexporter.py", line 509, in _init_preprocessors
    conf = self._get_conf()
  File "/opt/homebrew/lib/python3.10/site-packages/nbconvert/exporters/templateexporter.py", line 527, in _get_conf
    for path in map(Path, self.template_paths):
  File "/opt/homebrew/lib/python3.10/site-packages/traitlets/traitlets.py", line 686, in __get__
    return self.get(obj, cls)
  File "/opt/homebrew/lib/python3.10/site-packages/traitlets/traitlets.py", line 648, in get
    default = obj.trait_defaults(self.name)
  File "/opt/homebrew/lib/python3.10/site-packages/traitlets/traitlets.py", line 1752, in trait_defaults
    return self._get_trait_default_generator(names[0])(self)
  File "/opt/homebrew/lib/python3.10/site-packages/traitlets/traitlets.py", line 1132, in __call__
    return self.func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/nbconvert/exporters/templateexporter.py", line 538, in _template_paths
    template_names = self.get_template_names()
  File "/opt/homebrew/lib/python3.10/site-packages/nbconvert/exporters/templateexporter.py", line 622, in get_template_names
    raise ValueError(
ValueError: No template sub-directory with name 'lab' found in the following paths:
        /Users/ryanstevens/Library/Jupyter
        /Users/ryanstevens/Library/Python/3.10/share/jupyter
        /opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/share/jupyter
        /usr/local/share/jupyter
        /usr/share/jupyter

### VS Code Version

Version: 1.72.2 (Universal)

### Jupyter Extension Version

v2022.9.1202862440

### Jupyter logs

```shell
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/traitlets/traitlets.py", line 645, in get
    value = obj._trait_values[self.name]
KeyError: 'template_paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.10/site-packages/jupyter_core/application.py", line 269, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/traitlets/config/application.py", line 976, in launch_instance
    app.start()
  File "/opt/homebrew/lib/python3.10/site-packages/nbconvert/nbconvertapp.py", line 426, in start
    self.convert_notebooks()
  File "/opt/homebrew/lib/python3.10/site-packages/nbconvert/nbconvertapp.py", line 594, in convert_notebooks
    cls = get_exporter(self.export_format)
  File "/opt/homebrew/lib/python3.10/site-packages/nbconvert/exporters/base.py", line 106, in get_exporter
    if getattr(exporter(config=config), "enabled", True):
  File "/opt/homebrew/lib/python3.10/site-packages/nbconvert/exporters/templateexporter.py", line 343, in __init__
    super().__init__(config=config, **kw)
  File "/opt/homebrew/lib/python3.10/site-packages/nbconvert/exporters/exporter.py", line 118, in __init__
    self._init_preprocessors()
  File "/opt/homebrew/lib/python3.10/site-packages/nbconvert/exporters/templateexporter.py", line 509, in _init_preprocessors
    conf = self._get_conf()
  File "/opt/homebrew/lib/python3.10/site-packages/nbconvert/exporters/templateexporter.py", line 527, in _get_conf
    for path in map(Path, self.template_paths):
  File "/opt/homebrew/lib/python3.10/site-packages/traitlets/traitlets.py", line 686, in __get__
    return self.get(obj, cls)
  File "/opt/homebrew/lib/python3.10/site-packages/traitlets/traitlets.py", line 648, in get
    default = obj.trait_defaults(self.name)
  File "/opt/homebrew/lib/python3.10/site-packages/traitlets/traitlets.py", line 1752, in trait_defaults
    return self._get_trait_default_generator(names[0])(self)
  File "/opt/homebrew/lib/python3.10/site-packages/traitlets/traitlets.py", line 1132, in __call__
    return self.func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/nbconvert/exporters/templateexporter.py", line 538, in _template_paths
    template_names = self.get_template_names()
  File "/opt/homebrew/lib/python3.10/site-packages/nbconvert/exporters/templateexporter.py", line 622, in get_template_names
    raise ValueError(
ValueError: No template sub-directory with name 'lab' found in the following paths:
        /Users/ryanstevens/Library/Jupyter
        /Users/ryanstevens/Library/Python/3.10/share/jupyter
        /opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/share/jupyter
        /usr/local/share/jupyter
        /usr/share/jupyter
```

### Coding Language and Runtime Version

Python Notebook

### Running Jupyter locally or remotely?

Local

**Comment by stevensryanw** [comment]
I tried uninstalling and installing nbconvert but that didn't work

**Comment by amunger** [comment]
which version are you using? with pip you can check with `pip show nbconvert`

**Comment by stevensryanw** [comment]
Hi there I solved it was using a python environment without nbconvert without realizing it. For some reason visual studio code was using its own environment and not the one I had nbconvert installed on.
