### ISSUE TITLE
`jupyter.debugJustMyCode` breaks easily

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode-jupyter#11775]
Testing #11768

* have a cell like below
* use `"jupyter.debugJustMyCode": false,`
* step into on every statements (everytime it pauses): works nicely ✅ 
* change the setting to `"jupyter.debugJustMyCode": true,`
* step into on every statement: works ✅  (not nicely tho https://github.com/microsoft/vscode-jupyter/issues/11774)
* change the setting back to `"jupyter.debugJustMyCode": false,`
* 🐛 step into on every statement doesn't work anymore, it behaves like justMyCode

```py
import ipywidgets as widgets

print(12)

a = widgets.IntSlider(description='a')
a
```

**Comment by roblourens** [comment]
I don't get this one. At this step

> change the setting back to "jupyter.debugJustMyCode": false,

Did you do that in the middle of a debug session? Or step all the way through, change the setting, and start a new session?

The first case should not work (separate discussion about enabling dynamic toggling of this), the second works fine for me.

If the second doesn't work, can you grab a log with `"jupyter.logging.level": "verbose"` enabled?

**Comment by jrieken** [comment]
> Did you do that in the middle of a debug session?

No, I start a new session every time. The log does seem to be helpful. See log and recording below

https://user-images.githubusercontent.com/1794099/198294465-bed3c3c3-3be4-4ebf-9691-baebed9a9868.mp4



<details>
<summary>log</summary>
```
Visual Studio Code - Insiders (1.73.0-insider, undefined, desktop)
Jupyter Extension Version: 2022.10.1103011060.
Python Extension Version: 2022.17.12991026.
Workspace folder /home/parallels/Code/_samples
info 15:08:13.405: ZMQ install verified.
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 15:08:14.016: LSP Notebooks experiment is enabled
info 15:08:14.239: Preferred Remote kernel for /home/parallels/Code/_samples/test.ipynb is undefined
info 15:08:14.466: Preferred Remote kernel for /home/parallels/Code/_samples/test.ipynb is undefined
info 15:08:14.466: Find preferred kernel for /home/parallels/Code/_samples/test.ipynb with metadata {"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.8.10 (default, Jun 22 2022, 20:18:18) \n[GCC 9.4.0]"},"orig_nbformat":4,"vscode":{"interpreter":{"hash":"31f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6"}}} & preferred interpreter /bin/python3
info 15:08:14.467: Preferred Remote kernel for /home/parallels/Code/_samples/test.ipynb is undefined
info 15:08:14.467: Find preferred kernel for /home/parallels/Code/_samples/test.ipynb with metadata {"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.8.10 (default, Jun 22 2022, 20:18:18) \n[GCC 9.4.0]"},"orig_nbformat":4,"vscode":{"interpreter":{"hash":"31f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6"}}} & preferred interpreter /bin/python3
info 15:08:14.716: Preferred Remote kernel for /home/parallels/Code/_samples/test.ipynb is undefined
info 15:08:14.716: Find preferred kernel for /home/parallels/Code/_samples/test.ipynb with metadata {"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.8.10 (default, Jun 22 2022, 20:18:18) \n[GCC 9.4.0]"},"orig_nbformat":4,"vscode":{"interpreter":{"hash":"31f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6"}}} & preferred interpreter /bin/python3
info 15:08:14.716: Preferred Remote kernel for /home/parallels/Code/_samples/test.ipynb is undefined
info 15:08:14.716: Preferred kernel .jvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1./bin/python3./bin/python3.-m#ipykernel_launcher is exact match or top match for non python kernels, (true, [object Object], false, false)
info 15:08:14.717: PreferredConnection: .jvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1./bin/python3./bin/python3.-m#ipykernel_launcher found for NotebookDocument: /home/parallels/Code/_samples/test.ipynb
info 15:08:15.025: Preferred Remote kernel for /home/parallels/Code/_samples/test.ipynb is undefined
info 15:08:15.025: Find preferred kernel for /home/parallels/Code/_samples/test.ipynb with metadata {"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.8.10 (default, Jun 22 2022, 20:18:18) \n[GCC 9.4.0]"},"orig_nbformat":4,"vscode":{"interpreter":{"hash":"31f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6"}}} & preferred interpreter /bin/python3
info 15:08:15.025: Preferred Remote kernel for /home/parallels/Code/_samples/test.ipynb is undefined
info 15:08:15.025: Preferred kernel .jvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1./bin/python3./bin/python3.-m#ipykernel_launcher is exact match or top match for non python kernels, (true, [object Object], false, false)
info 15:08:15.026: PreferredConnection: .jvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1./bin/python3./bin/python3.-m#ipykernel_launcher found for NotebookDocument: /home/parallels/Code/_samples/test.ipynb
info 15:08:16.135: Got empty env vars with python /bin/python3 in 1663ms
info 15:08:16.191: Process Execution: > /bin/python3 -m pip list
> /bin/python3 -m pip list
info 15:08:17.000: Preferred Remote kernel for /home/parallels/Code/_samples/test.ipynb is undefined
info 15:08:17.000: Find preferred kernel for /home/parallels/Code/_samples/test.ipynb with metadata {"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.8.10 (default, Jun 22 2022, 20:18:18) \n[GCC 9.4.0]"},"orig_nbformat":4,"vscode":{"interpreter":{"hash":"31f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6"}}} & preferred interpreter /bin/python3
info 15:08:17.001: Preferred Remote kernel for /home/parallels/Code/_samples/test.ipynb is undefined
info 15:08:17.001: Preferred kernel .jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6./usr/bin/python3./usr/bin/python3.-m#ipykernel_launcher is exact match or top match for non python kernels, (false, undefined, true, false)
info 15:08:17.001: PreferredConnection: .jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6./usr/bin/python3./usr/bin/python3.-m#ipykernel_launcher found for NotebookDocument: /home/parallels/Code/_samples/test.ipynb
info 15:08:17.356: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6./usr/bin/python3./usr/bin/python3.-m#ipykernel_launcher (Python Path: /usr/bin/python3, EnvType: Unknown, EnvName: 'undefined', Version: 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0]) for '/home/parallels/Code/_samples/test.ipynb' (disableUI=true)
info 15:08:17.357: Computing working directory for resource '/home/parallels/Code/_samples/test.ipynb'
info 15:08:18.044: Got empty env vars with python /usr/bin/python3 in 984ms
info 15:08:18.055: Process Execution: > /usr/bin/python3 -m pip list
> /usr/bin/python3 -m pip list
info 15:08:18.056: Got env vars ourselves faster /usr/bin/python3 with env var count 62 in 684ms
info 15:08:18.056: Got env vars ourselves faster /usr/bin/python3 with env var count 62 in 633ms
info 15:08:18.056: Got env vars ourselves faster /usr/bin/python3 with env var count 62 in 633ms
info 15:08:18.070: Process Execution: > /usr/bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> /usr/bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
info 15:08:18.080: Process Execution: > /usr/bin/python3 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"b81f4900-9698-4df2-8d2c-3f7cffc46cc5" --shell=9002 --transport="tcp" --iopub=9004 --f=/home/parallels/.local/share/jupyter/runtime/kernel-v2-144861Hgl8F7mnIoHh.json
> /usr/bin/python3 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"b81f4900-9698-4df2-8d2c-3f7cffc46cc5" --shell=9002 --transport="tcp" --iopub=9004 --f=/home/parallels/.local/share/jupyter/runtime/kernel-v2-144861Hgl8F7mnIoHh.json
info 15:08:18.080: Process Execution: cwd: ~/Code/_samples
cwd: ~/Code/_samples
info 15:08:18.083: Got empty env vars with python /usr/bin/python3 in 711ms
info 15:08:18.084: Got empty env vars with python /usr/bin/python3 in 661ms
info 15:08:18.084: Got empty env vars with python /usr/bin/python3 in 661ms
info 15:08:19.040: ipykernel version & path 6.16.1, ~/.local/lib/python3.8/site-packages/ipykernel/__init__.py for /usr/bin/python3
warn 15:08:20.661: StdErr from Kernel Process /home/parallels/.local/lib/python3.8/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(

warn 15:08:20.661: StdErr from Kernel Process /home/parallels/.local/lib/python3.8/site-packages/traitlets/traitlets.py:2366: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use 'b81f4900-9698-4df2-8d2c-3f7cffc46cc5' instead of 'b"b81f4900-9698-4df2-8d2c-3f7cffc46cc5"'.
  warn(

info 15:08:20.736: Kernel Output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


info 15:08:20.736: Kernel Output: 
info 15:08:20.736: Kernel Output: To connect another client to this kernel, use:
info 15:08:20.736: Kernel Output: To connect another client to this kernel, use:

info 15:08:20.736: Kernel Output: To connect another client to this kernel, use:
    --existing kernel-v2-144861Hgl8F7mnIoHh.json
info 15:08:20.736: Kernel Output: To connect another client to this kernel, use:
    --existing kernel-v2-144861Hgl8F7mnIoHh.json

info 15:08:21.330: Started Kernel Python 3 (pid: 145456)
info 15:08:21.559: UpdateWorkingDirectoryAndPath in Kernel
info 15:08:23.516: Got env vars ourselves faster /usr/bin/python3 with env var count 62 in 1ms
info 15:08:23.572: Process Execution: > /usr/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2022.10.1103011060/pythonFiles/printJupyterDataDir.py
> /usr/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2022.10.1103011060/pythonFiles/printJupyterDataDir.py
info 15:08:27.960: Got empty env vars with python /usr/bin/python3 in 4445ms
info 15:08:33.268: Starting debugging with mode 1
info 15:08:46.310: Ending debug session 355275ca-7e16-46d8-8523-13ecc2fb1fa9
warn 15:08:46.311: StdErr from Kernel Process [IPKernelApp] ERROR | Exception in control handler:
Traceback (most recent call last):
  File "/home/parallels/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 334, in process_control
    await result
  File "/home/parallels/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 953, in debug_request
    reply_content = await reply_content
  File "/home/parallels/.local/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 466, in do_debug_request
    return await self.debugger.process_request(msg)
  File "/home/parallels/.local/lib/python3.8/site-packages/ipykernel/debugger.py", line 665, in process_request
    self.stop()
  File "/home/parallels/.local/lib/python3.8/site-packages/ipykernel/debugger.py", line 408, in stop
    self.debugpy_client.disconnect_tcp_socket()
  File "/home/parallels/.local/lib/python3.8/site-packages/ipykernel/debugger.py", line 254, in disconnect_tcp_socket
    self.debugpy_stream.socket.disconnect(self._get_endpoint())
  File "zmq/backend/cython/socket.pyx", line 668, in zmq.backend.cython.socket.Socket.disconnect
zmq.error.ZMQError: No such file or directory

info 15:08:46.866: Ending debug session 355275ca-7e16-46d8-8523-13ecc2fb1fa9
info 15:08:46.866: Ending debug session 355275ca-7e16-46d8-8523-13ecc2fb1fa9
info 15:08:55.050: Starting debugging with mode 1
warn 15:09:07.003: StdErr from Kernel Process [IPKernelApp] ERROR | Exception in control handler:
Traceback (most recent call last):
  File "/home/parallels/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 334, in process_control
    await result
  File "/home/parallels/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 953, in debug_request
    reply_content = await reply_content
  File "/home/parallels/.local/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 466, in do_debug_request
    return await self.debugger.process_request(msg)
  File "/home/parallels/.local/lib/python3.8/site-packages/ipykernel/debugger.py", line 665, in process_request
    self.stop()
  File "/home/parallels/.local/lib/python3.8/site-packages/ipykernel/debugger.py", line 408, in stop
    self.debugpy_client.disconnect_tcp_socket()
  File "/home/parallels/.local/lib/python3.8/site-packages/ipykernel/debugger.py", line 254, in disconnect_tcp_socket
    self.debugpy_stream.socket.disconnect(self._get_endpoint())
  File "zmq/backend/cython/socket.pyx", line 668, in zmq.backend.cython.socket.Socket.disconnect
zmq.error.ZMQError: No such file or directory

info 15:09:07.013: Ending debug session 21be516c-28ac-482f-88ae-a7dd1753cbc5
info 15:09:07.569: Ending debug session 21be516c-28ac-482f-88ae-a7dd1753cbc5
info 15:09:07.569: Ending debug session 21be516c-28ac-482f-88ae-a7dd1753cbc5
info 15:09:18.008: Starting debugging with mode 1
warn 15:09:28.139: StdErr from Kernel Process [IPKernelApp] ERROR | Exception in control handler:
Traceback (most recent call last):
  File "/home/parallels/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 334, in process_control
    await result
  File "/home/parallels/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 953, in debug_request
    reply_content = await reply_content
  File "/home/parallels/.local/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 466, in do_debug_request
    return await self.debugger.process_request(msg)
  File "/home/parallels/.local/lib/python3.8/site-packages/ipykernel/debugger.py", line 665, in process_request
    self.stop()
  File "/home/parallels/.local/lib/python3.8/site-packages/ipykernel/debugger.py", line 408, in stop
    self.debugpy_client.disconnect_tcp_socket()
  File "/home/parallels/.local/lib/python3.8/site-packages/ipykernel/debugger.py", line 254, in disconnect_tcp_socket
    self.debugpy_stream.socket.disconnect(self._get_endpoint())
  File "zmq/backend/cython/socket.pyx", line 668, in zmq.backend.cython.socket.Socket.disconnect
zmq.error.ZMQError: No such file or directory

info 15:09:28.147: Ending debug session d8394a49-c1a8-46eb-b191-71319c26aac5
info 15:09:28.699: Ending debug session d8394a49-c1a8-46eb-b191-71319c26aac5
info 15:09:28.699: Ending debug session d8394a49-c1a8-46eb-b191-71319c26aac5
info 15:09:55.169: Starting debugging with mode 1
info 15:10:03.988: Ending debug session 454ec54f-7820-4aae-b2a2-26c1800c989d
warn 15:10:04.000: StdErr from Kernel Process [IPKernelApp] ERROR | Exception in control handler:
Traceback (most recent call last):
  File "/home/parallels/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 334, in process_control
    await result
  File "/home/parallels/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 953, in debug_request
    reply_content = await reply_content
  File "/home/parallels/.local/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 466, in do_debug_request
    return await self.debugger.process_request(msg)
  File "/home/parallels/.local/lib/python3.8/site-packages/ipykernel/debugger.py", line 665, in process_request
    self.stop()
  File "/home/parallels/.local/lib/python3.8/site-packages/ipykernel/debugger.py", line 408, in stop
    self.debugpy_client.disconnect_tcp_socket()
  File "/home/parallels/.local/lib/python3.8/site-packages/ipykernel/debugger.py", line 254, in disconnect_tcp_socket
    self.debugpy_stream.socket.disconnect(self._get_endpoint())
  File "zmq/backend/cython/socket.pyx", line 668, in zmq.backend.cython.socket.Socket.disconnect
zmq.error.ZMQError: No such file or directory

info 15:10:04.558: Ending debug session 454ec54f-7820-4aae-b2a2-26c1800c989d
info 15:10:04.558: Ending debug session 454ec54f-7820-4aae-b2a2-26c1800c989d

```
</details>
