### ISSUE TITLE
Data Viewer filter shows no rows when the filter is used on the index of a DataFrame

### ISSUE THREAD

**Issue by delcypher** [microsoft/vscode-jupyter#11833]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

# Issue

When using the data viewer, the filter does not seem to function correctly on the index of a `DataFrame`. When the filter is used no rows match, despite the fact the filter should match rows in the `DataFrame`.

# How to reproduce

1. Run this code in an Juypter notebook

```
import pandas as pd

df = pd.DataFrame(
    {
        'related': [
            '/etc/something',
            '/usr/bin/something',
            '/usr/lib/something'
        ],
        'size': [
            20,
            50,
            100
        ]
    },
    index=[
        '/etc/something',
        '/usr/bin/something',
        '/usr/lib/something'
    ]
)
df
```

2. Click on "JUPYTER: VARIABLES" then click on the the "Show variable snapshot in data viewer" for the `df` variable

<img width="725" alt="image" src="https://user-images.githubusercontent.com/511795/198491839-df8561c9-d5f4-4854-93d7-a9fc215e08a7.png">

3. You'll see something like:

<img width="455" alt="image" src="https://user-images.githubusercontent.com/511795/198492330-8194e1a1-c1b4-4d9b-a564-9d8e8f1aab59.png">

4. Try applying a filter to the `index` column for rows containing `etc`. When I do this no rows show up, even though there is a row that should match this.

<img width="468" alt="image" src="https://user-images.githubusercontent.com/511795/198493849-8d4c07a3-dfe2-42b7-bc6c-911b49082779.png">

5. If I apply the same filter to the `related` column which contains the same content as `index` then the filter works as expected.

<img width="463" alt="image" src="https://user-images.githubusercontent.com/511795/198493957-64891361-bf07-45fc-ab13-cc0053c330b0.png">

As you can see a single row matches where `related` is equal to `/etc/something`.

## Workaround

If I reshape the data to make the `index` a regular column then I can filter as expected.

```
df2 = df.reindex()
```

This is really annoying though. I shouldn't need to reshape the data for the filter to work.

### VS Code Version

Version: 1.72.2 (Universal) Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075 Date: 2022-10-12T22:16:30.254Z (2 wks ago) Electron: 19.0.17 Chromium: 102.0.5005.167 Node.js: 16.14.2 V8: 10.2.154.15-electron.0 OS: Darwin arm64 21.5.0 Sandboxed: No

### Jupyter Extension Version

v2022.9.1202862440

### Jupyter logs

```shell
Visual Studio Code (1.72.2, undefined, desktop)
Jupyter Extension Version: 2022.9.1202862440.
Python Extension Version: 2022.16.1.
No workspace folder opened.
error 20:20:34.611: Exception while attempting zmq : [Error: No native build was found for platform=darwin arch=arm64 runtime=electron abi=106 uv=1 armv=8 libc=glibc node=16.14.2 electron=19.0.17
    loaded from: /Users/dan/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/node_modules/zeromq

	at load.path (/Users/dan/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/node_modules/node-gyp-build/index.js:1:3163)
	at load (/Users/dan/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/node_modules/node-gyp-build/index.js:1:648)
	at Object.<anonymous> (/Users/dan/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/node_modules/zeromq/lib/native.js:1:198)
	at u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1313)
	at Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at c._load (node:electron/js2c/asar_bundle:5:13343)
	at r._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:14565)
	at v._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:65015)
	at E._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:64383)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:699)
	at Object.<anonymous> (/Users/dan/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/node_modules/zeromq/lib/index.js:1:144)
	at u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1313)
	at Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at c._load (node:electron/js2c/asar_bundle:5:13343)
	at r._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:14565)
	at v._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:65015)
	at E._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:64383)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:699)
	at 92747 (/Users/dan/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:17:593435)
	at __webpack_require__ (/Users/dan/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:17:1480895)
	at l.zmqSupported (/Users/dan/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:2:2220878)
	at l.isSupportedForLocalLaunch (/Users/dan/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:2:2220621)
	at get isSupported [as isSupported] (/Users/dan/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:2:2220531)
	at t.registerTypes (/Users/dan/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:2:2235624)
	at /Users/dan/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:2:1640908
	at /Users/dan/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:2:1641663
	at /Users/dan/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:2:1641671
	at t.activate (/Users/dan/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:2:1641793)
	at Fn._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:17678)
	at Fn._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:17338)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:15133
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async E._activate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:88:8191)
	at async E._waitForDepsThenActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:88:8133)
	at async E._initialize (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:88:7497)]
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 20:20:34.798: LSP Notebooks experiment is enabled
info 20:20:35.032: Preferred Remote kernel for /Users/dan/tmp/Untitled-1.ipynb is undefined
info 20:20:35.068: Preferred Remote kernel for /Users/dan/tmp/Untitled-1.ipynb is undefined
info 20:20:35.069: Find preferred kernel for /Users/dan/tmp/Untitled-1.ipynb with metadata {"kernelspec":{"display_name":"Python 3.9.6 ('venv': venv)","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.6"},"orig_nbformat":4,"vscode":{"interpreter":{"hash":"f33023c706ba1456574a441edec8ee577689c2d0ad334a10ab659bbcd3a94035"}}} & preferred interpreter /Volumes/user_data/dev/experiment/venv/bin/python
info 20:20:35.076: Preferred Remote kernel for /Users/dan/tmp/Untitled-1.ipynb is undefined
info 20:20:35.076: Preferred kernel .jvsc74a57bd0f33023c706ba1456574a441edec8ee577689c2d0ad334a10ab659bbcd3a94035./Volumes/user_data/dev/experiment/venv/python./Volumes/user_data/dev/experiment/venv/python.-m#ipykernel_launcher is exact match or top match for non python kernels, (false, [object Object], true, false)
info 20:20:35.076: PreferredConnection: .jvsc74a57bd0f33023c706ba1456574a441edec8ee577689c2d0ad334a10ab659bbcd3a94035./Volumes/user_data/dev/experiment/venv/python./Volumes/user_data/dev/experiment/venv/python.-m#ipykernel_launcher found for NotebookDocument: /Users/dan/tmp/Untitled-1.ipynb
info 20:20:35.148: Got empty env vars with python /usr/bin/python3 in 79ms
info 20:20:35.149: Got empty env vars with python /usr/bin/python3 in 80ms
info 20:20:35.149: Got env vars ourselves faster /usr/bin/python3 with env var count 31 in 80ms
info 20:20:35.149: Got env vars ourselves faster /usr/bin/python3 with env var count 31 in 80ms
info 20:20:35.150: Process Execution: > /usr/bin/python3 -c "import jupyter"
> /usr/bin/python3 -c "import jupyter"
info 20:20:35.150: Process Execution: > /usr/bin/python3 -c "import notebook"
> /usr/bin/python3 -c "import notebook"
info 20:20:35.453: Got env vars ourselves faster /usr/bin/python3 with env var count 31 in 1ms
info 20:20:35.454: Process Execution: > /usr/bin/python3 -m jupyter kernelspec --version
> /usr/bin/python3 -m jupyter kernelspec --version
info 20:20:35.468: Got empty env vars with python /usr/bin/python3 in 16ms
info 20:20:35.531: Got env vars ourselves faster /Volumes/user_data/dev/experiment/venv/bin/python with env var count 38 in 463ms
info 20:20:35.531: Process Execution: > /Volumes/user_data/dev/experiment/venv/bin/python -m pip list
> /Volumes/user_data/dev/experiment/venv/bin/python -m pip list
info 20:20:35.554: Got env vars ourselves faster /usr/bin/python3 with env var count 31 in 1ms
info 20:20:35.554: Process Execution: > /usr/bin/python3 ~/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/pythonFiles/vscode_datascience_helpers/getJupyterKernelspecVersion.py
> /usr/bin/python3 ~/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/pythonFiles/vscode_datascience_helpers/getJupyterKernelspecVersion.py
info 20:20:35.560: Got empty env vars with python /usr/bin/python3 in 7ms
info 20:20:35.611: Got env vars with python /Volumes/user_data/dev/experiment/venv/bin/python, with env var count 38 and custom env var count 0 in 543ms
info 20:20:35.794: Got env vars ourselves faster /usr/bin/python3 with env var count 31 in 0ms
info 20:20:35.794: Got env vars ourselves faster /usr/bin/python3 with env var count 31 in 0ms
info 20:20:35.801: Got empty env vars with python /usr/bin/python3 in 7ms
info 20:20:35.801: Got empty env vars with python /usr/bin/python3 in 7ms
info 20:21:03.874: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd0f33023c706ba1456574a441edec8ee577689c2d0ad334a10ab659bbcd3a94035./Volumes/user_data/dev/experiment/venv/python./Volumes/user_data/dev/experiment/venv/python.-m#ipykernel_launcher (Python Path: /Volumes/user_data/dev/experiment/venv, EnvType: Venv, EnvName: 'venv', Version: 3.9.6) for '/Users/dan/tmp/Untitled-1.ipynb' (disableUI=false)
info 20:21:03.875: Checking for server existence.
info 20:21:03.875: Checking for server usability.
info 20:21:03.875: Starting notebook server.
info 20:21:03.875: Connecting to server
info 20:21:03.875: Launching server
info 20:21:03.877: Starting Notebook
info 20:21:03.880: Generating custom default config at /var/folders/_5/tvvvy5b97k10hjg1q63vk3pm0000gn/T/cd1c3f06-fa1a-4633-8bba-c1dfd231ecc9/jupyter_notebook_config.py
info 20:21:03.880: Starting Jupyter Notebook
Starting Jupyter from /usr/bin/python3
info 20:21:03.881: Got env vars ourselves faster /usr/bin/python3 with env var count 31 in 1ms
info 20:21:03.881: Got env vars ourselves faster /usr/bin/python3 with env var count 31 in 1ms
info 20:21:03.881: Creating daemon pool for /usr/bin/python3 with env variables count 31
info 20:21:03.882: Process Execution: > /usr/bin/python3 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 29122
> /usr/bin/python3 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 29122
info 20:21:03.883: Process Execution: > /usr/bin/python3 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 29122
> /usr/bin/python3 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 29122
info 20:21:03.884: Process Execution: > /usr/bin/python3 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 29122
> /usr/bin/python3 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 29122
info 20:21:03.939: Got empty env vars with python /usr/bin/python3 in 59ms
info 20:21:03.939: Got empty env vars with python /usr/bin/python3 in 59ms
info 20:21:03.988: Got env vars ourselves faster /usr/bin/python3 with env var count 31 in 0ms
info 20:21:03.988: Process Execution: > /usr/bin/python3 (daemon) -m jupyter notebook --no-browser --notebook-dir="/Users/dan/tmp" --config=/var/folders/_5/tvvvy5b97k10hjg1q63vk3pm0000gn/T/cd1c3f06-fa1a-4633-8bba-c1dfd231ecc9/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
> /usr/bin/python3 (daemon) -m jupyter notebook --no-browser --notebook-dir="/Users/dan/tmp" --config=/var/folders/_5/tvvvy5b97k10hjg1q63vk3pm0000gn/T/cd1c3f06-fa1a-4633-8bba-c1dfd231ecc9/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
info 20:21:03.989: Waiting for Jupyter Notebook
info 20:21:03.994: Got empty env vars with python /usr/bin/python3 in 6ms
/Users/dan/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/dan/tmp' instead of '"/Users/dan/tmp"' if you require traitlets >=5.
  warn(
info 20:21:04.546: /Users/dan/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/dan/tmp' instead of '"/Users/dan/tmp"' if you require traitlets >=5.
  warn(

[I 20:21:04.979 NotebookApp] Serving notebooks from local directory: /Users/dan/tmp
info 20:21:04.979: /Users/dan/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/dan/tmp' instead of '"/Users/dan/tmp"' if you require traitlets >=5.
  warn(
[I 20:21:04.979 NotebookApp] Serving notebooks from local directory: /Users/dan/tmp

[I 20:21:04.979 NotebookApp] Jupyter Notebook 6.5.1 is running at:
info 20:21:04.979: /Users/dan/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/dan/tmp' instead of '"/Users/dan/tmp"' if you require traitlets >=5.
  warn(
[I 20:21:04.979 NotebookApp] Serving notebooks from local directory: /Users/dan/tmp
[I 20:21:04.979 NotebookApp] Jupyter Notebook 6.5.1 is running at:

[I 20:21:04.979 NotebookApp] http://localhost:8888/?token=b92aace1814d8f2f0f62cd6aff8c4b0fdefd59b16ed05ebd
info 20:21:04.980: /Users/dan/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/dan/tmp' instead of '"/Users/dan/tmp"' if you require traitlets >=5.
  warn(
[I 20:21:04.979 NotebookApp] Serving notebooks from local directory: /Users/dan/tmp
[I 20:21:04.979 NotebookApp] Jupyter Notebook 6.5.1 is running at:
[I 20:21:04.979 NotebookApp] http://localhost:8888/?token=b92aace1814d8f2f0f62cd6aff8c4b0fdefd59b16ed05ebd

info 20:21:04.980: Process Execution: > /usr/bin/python3 (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> /usr/bin/python3 (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/pythonFiles/vscode_datascience_helpers/getServerInfo.py
info 20:21:04.980: Got env vars ourselves faster /usr/bin/python3 with env var count 31 in 0ms
[I 20:21:04.979 NotebookApp]  or http://127.0.0.1:8888/?token=b92aace1814d8f2f0f62cd6aff8c4b0fdefd59b16ed05ebd
info 20:21:04.980: /Users/dan/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/dan/tmp' instead of '"/Users/dan/tmp"' if you require traitlets >=5.
  warn(
[I 20:21:04.979 NotebookApp] Serving notebooks from local directory: /Users/dan/tmp
[I 20:21:04.979 NotebookApp] Jupyter Notebook 6.5.1 is running at:
[I 20:21:04.979 NotebookApp] http://localhost:8888/?token=b92aace1814d8f2f0f62cd6aff8c4b0fdefd59b16ed05ebd
[I 20:21:04.979 NotebookApp]  or http://127.0.0.1:8888/?token=b92aace1814d8f2f0f62cd6aff8c4b0fdefd59b16ed05ebd

info 20:21:04.981: Process Execution: > /usr/bin/python3 (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> /usr/bin/python3 (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/pythonFiles/vscode_datascience_helpers/getServerInfo.py
info 20:21:04.981: Got env vars ourselves faster /usr/bin/python3 with env var count 31 in 1ms
[I 20:21:04.979 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
info 20:21:04.981: /Users/dan/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/dan/tmp' instead of '"/Users/dan/tmp"' if you require traitlets >=5.
  warn(
[I 20:21:04.979 NotebookApp] Serving notebooks from local directory: /Users/dan/tmp
[I 20:21:04.979 NotebookApp] Jupyter Notebook 6.5.1 is running at:
[I 20:21:04.979 NotebookApp] http://localhost:8888/?token=b92aace1814d8f2f0f62cd6aff8c4b0fdefd59b16ed05ebd
[I 20:21:04.979 NotebookApp]  or http://127.0.0.1:8888/?token=b92aace1814d8f2f0f62cd6aff8c4b0fdefd59b16ed05ebd
[I 20:21:04.979 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

info 20:21:04.981: Got env vars ourselves faster /usr/bin/python3 with env var count 31 in 0ms
[C 20:21:04.982 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/dan/Library/Jupyter/runtime/nbserver-29729-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=b92aace1814d8f2f0f62cd6aff8c4b0fdefd59b16ed05ebd
     or http://127.0.0.1:8888/?token=b92aace1814d8f2f0f62cd6aff8c4b0fdefd59b16ed05ebd
info 20:21:04.982: /Users/dan/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/dan/tmp' instead of '"/Users/dan/tmp"' if you require traitlets >=5.
  warn(
[I 20:21:04.979 NotebookApp] Serving notebooks from local directory: /Users/dan/tmp
[I 20:21:04.979 NotebookApp] Jupyter Notebook 6.5.1 is running at:
[I 20:21:04.979 NotebookApp] http://localhost:8888/?token=b92aace1814d8f2f0f62cd6aff8c4b0fdefd59b16ed05ebd
[I 20:21:04.979 NotebookApp]  or http://127.0.0.1:8888/?token=b92aace1814d8f2f0f62cd6aff8c4b0fdefd59b16ed05ebd
[I 20:21:04.979 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 20:21:04.982 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/dan/Library/Jupyter/runtime/nbserver-29729-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=b92aace1814d8f2f0f62cd6aff8c4b0fdefd59b16ed05ebd
     or http://127.0.0.1:8888/?token=b92aace1814d8f2f0f62cd6aff8c4b0fdefd59b16ed05ebd

info 20:21:04.982: Got env vars ourselves faster /usr/bin/python3 with env var count 31 in 0ms
info 20:21:04.984: Got empty env vars with python /usr/bin/python3 in 4ms
info 20:21:04.988: Got empty env vars with python /usr/bin/python3 in 7ms
info 20:21:04.988: Got empty env vars with python /usr/bin/python3 in 7ms
info 20:21:04.989: Got empty env vars with python /usr/bin/python3 in 7ms
info 20:21:05.565: Connecting to process server
info 20:21:05.565: Connecting server kernel http://localhost:8888/
info 20:21:05.565: Creating server with url : http://localhost:8888/
info 20:21:05.570: Connection complete server
info 20:21:05.570: Server started.
info 20:21:05.593: Process Execution: > /usr/bin/python3 (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> /usr/bin/python3 (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/pythonFiles/vscode_datascience_helpers/getServerInfo.py
info 20:21:05.593: Process Execution: > /usr/bin/python3 (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> /usr/bin/python3 (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/pythonFiles/vscode_datascience_helpers/getServerInfo.py
[I 20:21:05.713 NotebookApp] Creating new notebook in 
info 20:21:05.743: installMissingDependencies /Volumes/user_data/dev/experiment/venv/bin/python, ui.disabled=false for resource '/Users/dan/tmp/Untitled-1.ipynb'
info 20:21:05.743: Got env vars with python /Volumes/user_data/dev/experiment/venv/bin/python, with env var count 38 and custom env var count 0 in 0ms
info 20:21:05.744: Got env vars ourselves faster /Volumes/user_data/dev/experiment/venv/bin/python with env var count 38 in 1ms
info 20:21:05.744: Process Execution: > /Volumes/user_data/dev/experiment/venv/bin/python -c "import ipykernel"
> /Volumes/user_data/dev/experiment/venv/bin/python -c "import ipykernel"
info 20:21:06.024: Spec argv[0] updated from '/Volumes/user_data/dev/experiment/venv/bin/python' to '/Volumes/user_data/dev/experiment/venv/bin/python'
info 20:21:06.025: Got env vars with python /Volumes/user_data/dev/experiment/venv/bin/python, with env var count 38 and custom env var count 0 in 1ms
info 20:21:06.025: Got env vars ourselves faster /Volumes/user_data/dev/experiment/venv/bin/python with env var count 38 in 1ms
[I 20:21:06.068 NotebookApp] Kernel started: 434e0062-fc44-40fa-83be-4856834c28c7, name: python396jvsc74a57bd0f33023c706ba1456574a441edec8ee577689c2d0ad334a10ab659bbcd3a94035
[W 20:21:06.078 NotebookApp] delete /Untitled-1-jvsc-aa571a7b-45f3-474d-86d2-3d0f79de56847a03d082-0990-424d-b41e-1890705b1e9b.ipynb
info 20:21:06.816: Started session for kernel startUsingPythonInterpreter:.jvsc74a57bd0f33023c706ba1456574a441edec8ee577689c2d0ad334a10ab659bbcd3a94035./Volumes/user_data/dev/experiment/venv/python./Volumes/user_data/dev/experiment/venv/python.-m#ipykernel_launcher
info 20:21:06.818: UpdateWorkingDirectoryAndPath in Kernel
info 20:21:06.905: Got env vars with python /Volumes/user_data/dev/experiment/venv/bin/python, with env var count 38 and custom env var count 0 in 0ms
info 20:21:06.905: Got env vars ourselves faster /Volumes/user_data/dev/experiment/venv/bin/python with env var count 38 in 1ms
info 20:21:06.907: Process Execution: > /Volumes/user_data/dev/experiment/venv/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/pythonFiles/printJupyterDataDir.py
> /Volumes/user_data/dev/experiment/venv/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/pythonFiles/printJupyterDataDir.py
info 20:21:13.837: Loading webview. View is notset
info 20:21:13.837: Loading web view...
info 20:21:13.837: Webview panel created.
info 20:21:14.073: Web view react rendered
info 20:21:15.504: Loading webview. View is notset
info 20:21:15.505: Loading web view...
info 20:21:15.505: Webview panel created.
info 20:21:15.507: Got env vars with python /Volumes/user_data/dev/experiment/venv/bin/python, with env var count 38 and custom env var count 0 in 0ms
info 20:21:15.507: Got env vars ourselves faster /Volumes/user_data/dev/experiment/venv/bin/python with env var count 38 in 0ms
info 20:21:15.509: Process Execution: > /Volumes/user_data/dev/experiment/venv/bin/python -c "import pandas;print(pandas.__version__)"
> /Volumes/user_data/dev/experiment/venv/bin/python -c "import pandas;print(pandas.__version__)"
info 20:21:15.801: Web view react rendered
```

### Coding Language and Runtime Version

Python 3.9.6

### Language Extension Version (if applicable)

Python v2022.16.1

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
thanks for the repro case, I see the same behavior
