### ISSUE TITLE
Failed to start jupyter in the environment error

### ISSUE THREAD

**Issue by msminhas93** [microsoft/vscode-jupyter#11868]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I am facing issues with the jupyter extension on Macbook M1 Pro. Suddenly my extension stopped working. 

### VS Code Version

1.72.2

### Jupyter Extension Version

2022.9.1202862440

### Jupyter logs

```shell
Visual Studio Code (1.72.2, undefined, desktop)
Jupyter Extension Version: 2022.9.1202862440.
Python Extension Version: 2022.17.13051012.
Workspace folder /Users/manpreet.minhas/manpreetdata/jupypter-notebooks
error 07:33:45.605: Exception while attempting zmq : [Error: No native build was found for platform=darwin arch=arm64 runtime=electron abi=106 uv=1 armv=8 libc=glibc node=16.14.2 electron=19.0.17
    loaded from: /Users/manpreet.minhas/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/node_modules/zeromq

	at load.path (/Users/manpreet.minhas/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/node_modules/node-gyp-build/index.js:1:3163)
	at load (/Users/manpreet.minhas/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/node_modules/node-gyp-build/index.js:1:648)
	at Object.<anonymous> (/Users/manpreet.minhas/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/node_modules/zeromq/lib/native.js:1:198)
	at u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1313)
	at Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at c._load (node:electron/js2c/asar_bundle:5:13343)
	at r._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:14565)
	at v._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:65015)
	at E._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:64383)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:699)
	at Object.<anonymous> (/Users/manpreet.minhas/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/node_modules/zeromq/lib/index.js:1:144)
	at u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1313)
	at Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at c._load (node:electron/js2c/asar_bundle:5:13343)
	at r._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:14565)
	at v._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:65015)
	at E._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:64383)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:699)
	at 92747 (/Users/manpreet.minhas/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:17:593435)
	at __webpack_require__ (/Users/manpreet.minhas/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:17:1480895)
	at l.zmqSupported (/Users/manpreet.minhas/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:2:2220878)
	at l.isSupportedForLocalLaunch (/Users/manpreet.minhas/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:2:2220621)
	at get isSupported [as isSupported] (/Users/manpreet.minhas/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:2:2220531)
	at t.registerTypes (/Users/manpreet.minhas/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:2:2235624)
	at /Users/manpreet.minhas/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:2:1640908
	at /Users/manpreet.minhas/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:2:1641663
	at /Users/manpreet.minhas/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:2:1641671
	at t.activate (/Users/manpreet.minhas/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:2:1641793)
	at Fn._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:17678)
	at Fn._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:17338)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:15133
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async E._activate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:88:8191)
	at async E._waitForDepsThenActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:88:8133)
	at async E._initialize (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:88:7497)]
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 07:33:45.773: Attempting to start a server because of preload conditions ...
info 07:33:45.777: LSP Notebooks experiment is disabled -- not in treatment group
info 07:33:45.779: Checking for server existence.
info 07:33:45.779: Checking for server usability.
info 07:33:45.807: Loading webview. View is notset
info 07:33:45.807: Loading web view...
info 07:33:45.808: Webview panel created.
info 07:33:45.965: Web view react rendered
info 07:33:46.166: Got env vars ourselves faster /opt/miniconda3/envs/imagesearch/bin/python with env var count 52 in 380ms
info 07:33:46.166: Got env vars ourselves faster /opt/miniconda3/envs/imagesearch/bin/python with env var count 52 in 379ms
info 07:33:46.166: Got env vars ourselves faster /opt/miniconda3/envs/imagesearch/bin/python with env var count 52 in 378ms
info 07:33:46.168: Process Execution: > /opt/miniconda3/envs/imagesearch/bin/python -m pip list
> /opt/miniconda3/envs/imagesearch/bin/python -m pip list
info 07:33:46.169: Process Execution: > /opt/miniconda3/envs/imagesearch/bin/python -c "import jupyter"
> /opt/miniconda3/envs/imagesearch/bin/python -c "import jupyter"
info 07:33:46.169: Process Execution: > /opt/miniconda3/envs/imagesearch/bin/python -c "import notebook"
> /opt/miniconda3/envs/imagesearch/bin/python -c "import notebook"
info 07:33:46.190: Got env vars ourselves faster /opt/miniconda3/envs/imagesearch/bin/python with env var count 52 in 1ms
info 07:33:46.194: Process Execution: > /opt/miniconda3/envs/imagesearch/bin/python -m jupyter kernelspec --version
> /opt/miniconda3/envs/imagesearch/bin/python -m jupyter kernelspec --version
info 07:33:46.509: Starting notebook server.
info 07:33:46.510: Connecting to server
info 07:33:46.510: Launching server
info 07:33:46.510: Starting Notebook
info 07:33:46.510: Got env vars ourselves faster /opt/miniconda3/envs/imagesearch/bin/python with env var count 52 in 1ms
info 07:33:46.510: Got env vars ourselves faster /opt/miniconda3/envs/imagesearch/bin/python with env var count 52 in 1ms
info 07:33:46.524: Generating custom default config at /var/folders/2d/0d1vbdjs5vzffdcg1mgpwnqw0000gp/T/1e5682d6-c7a8-42fe-b638-ad7f266f57e9/jupyter_notebook_config.py
info 07:33:46.525: Starting Jupyter Notebook
Starting Jupyter from /opt/miniconda3/envs/imagesearch/bin/python
info 07:33:46.525: Got env vars ourselves faster /opt/miniconda3/envs/imagesearch/bin/python with env var count 52 in 0ms
info 07:33:46.525: Got env vars ourselves faster /opt/miniconda3/envs/imagesearch/bin/python with env var count 52 in 0ms
info 07:33:46.542: Creating daemon pool for /opt/miniconda3/envs/imagesearch/bin/python with env variables count 52
info 07:33:46.543: Process Execution: > /opt/miniconda3/envs/imagesearch/bin/python -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 9871
> /opt/miniconda3/envs/imagesearch/bin/python -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 9871
info 07:33:46.544: Process Execution: > /opt/miniconda3/envs/imagesearch/bin/python -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 9871
> /opt/miniconda3/envs/imagesearch/bin/python -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 9871
info 07:33:46.544: Process Execution: > /opt/miniconda3/envs/imagesearch/bin/python -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 9871
> /opt/miniconda3/envs/imagesearch/bin/python -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 9871
info 07:33:46.668: Got env vars ourselves faster /opt/miniconda3/envs/imagesearch/bin/python with env var count 52 in 0ms
info 07:33:46.677: Process Execution: > /opt/miniconda3/envs/imagesearch/bin/python (daemon) -m jupyter notebook --no-browser --notebook-dir="/Users/manpreet.minhas/manpreetdata/jupypter-notebooks" --config=/var/folders/2d/0d1vbdjs5vzffdcg1mgpwnqw0000gp/T/1e5682d6-c7a8-42fe-b638-ad7f266f57e9/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
> /opt/miniconda3/envs/imagesearch/bin/python (daemon) -m jupyter notebook --no-browser --notebook-dir="/Users/manpreet.minhas/manpreetdata/jupypter-notebooks" --config=/var/folders/2d/0d1vbdjs5vzffdcg1mgpwnqw0000gp/T/1e5682d6-c7a8-42fe-b638-ad7f266f57e9/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
info 07:33:46.677: Waiting for Jupyter Notebook
error 07:33:46.679: Failed to run jupyter as observable with args notebook --no-browser --notebook-dir="/Users/manpreet.minhas/manpreetdata/jupypter-notebooks" --config=/var/folders/2d/0d1vbdjs5vzffdcg1mgpwnqw0000gp/T/1e5682d6-c7a8-42fe-b638-ad7f266f57e9/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0 [g [Error]: Traceback (most recent call last):
  File "/Users/manpreet.minhas/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py", line 158, in _start_notebook
    from notebook import notebookapp as app
ImportError: cannot import name 'notebookapp' from 'notebook' (unknown location)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/manpreet.minhas/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py", line 54, in _decorator
    return func(self, *args, **kwargs)
  File "/Users/manpreet.minhas/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py", line 111, in m_exec_module_observable
    self._start_notebook(args, cwd, env)
  File "/Users/manpreet.minhas/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py", line 160, in _start_notebook
    from notebook import app as app
ImportError: cannot import name 'app' from 'notebook' (unknown location)

	at /Users/manpreet.minhas/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:7:36028] {
  category: 'daemon'
}
Failed to run jupyter as observable with args notebook --no-browser --notebook-dir="/Users/manpreet.minhas/manpreetdata/jupypter-notebooks" --config=/var/folders/2d/0d1vbdjs5vzffdcg1mgpwnqw0000gp/T/1e5682d6-c7a8-42fe-b638-ad7f266f57e9/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
info 07:33:46.680: Failed to run jupyter as observable with args notebook --no-browser --notebook-dir="/Users/manpreet.minhas/manpreetdata/jupypter-notebooks" --config=/var/folders/2d/0d1vbdjs5vzffdcg1mgpwnqw0000gp/T/1e5682d6-c7a8-42fe-b638-ad7f266f57e9/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0

error 07:33:46.681: Error starting server in serverPreload:  [i [Error]: Traceback (most recent call last):
  File "/Users/manpreet.minhas/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py", line 158, in _start_notebook
    from notebook import notebookapp as app
ImportError: cannot import name 'notebookapp' from 'notebook' (unknown location)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/manpreet.minhas/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py", line 54, in _decorator
    return func(self, *args, **kwargs)
  File "/Users/manpreet.minhas/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py", line 111, in m_exec_module_observable
    self._start_notebook(args, cwd, env)
  File "/Users/manpreet.minhas/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py", line 160, in _start_notebook
    from notebook import app as app
ImportError: cannot import name 'app' from 'notebook' (unknown location)

Failed to run jupyter as observable with args notebook --no-browser --notebook-dir="/Users/manpreet.minhas/manpreetdata/jupypter-notebooks" --config=/var/folders/2d/0d1vbdjs5vzffdcg1mgpwnqw0000gp/T/1e5682d6-c7a8-42fe-b638-ad7f266f57e9/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0

	at t.JupyterConnectionWaiter.rejectStartPromise (/Users/manpreet.minhas/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:2:1992805)
	at t._error (/Users/manpreet.minhas/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:2:1993406)
	at t.__tryOrUnsub (/Users/manpreet.minhas/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:2:1183302)
	at t.error (/Users/manpreet.minhas/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:2:1182711)
	at t._error (/Users/manpreet.minhas/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:2:1181596)
	at t.error (/Users/manpreet.minhas/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:2:1181290)
	at t.error (/Users/manpreet.minhas/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:2:1178796)
	at /Users/manpreet.minhas/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:7:36230] {
  category: 'jupyterconnection'
}
```

### Anaconda Version (if applicable)

4.13.0

### Running Jupyter locally or remotely?

Local

**Comment by IanMatthewHuff** [comment]
@msminhas93 if you run the command "Jupyter: Select Interpreter to start Jupyter Server" in vscode do you have a Python interpreter selected there? If you do, from a terminal are you able to run `jupyter notebook` from that interpreter? Looks like it's failing to start up the jupyter server for you.

**Comment by msminhas93** [comment]
A wrong env was selected! I changed and that fixed the issue. Thanks a ton @IanMatthewHuff!

**Comment by IanMatthewHuff** [comment]
@msminhas93 Awesome. Glad that it helped. 

For what it's worth, we should actually do a better job of surfacing this error on our side. This is a case where there is a difference between the interpreter that we are using to start up Jupyter in general, versus the actual target kernel. In a case like this it's hard for an end user like yourself to see what went wrong. We can look at cleaning this up in the future.

But glad you are up and running in any case.
