### ISSUE TITLE
Broken Language Token Tests

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#11884]
```
 2) DataScience - VSCode semantic token tests
       Edit cells in a notebook:

      Tokens not correct after edit
      + expected - actual

       [
         1
         4
         4
      -  12
      +  11
         1
         1
         2
         5
      -  12
      +  11
         512
         1
         0
         4
      -  12
      +  11
         0
       ]
      
      at Context.<anonymous> (src/test/datascience/notebook/intellisense/semanticTokens.vscode.test.ts:122:16)

  3) DataScience - VSCode semantic token tests
       Special token check:

      Expected tokens not returned
      + expected - actual

       [
         1
         0
         4
      -  15
      +  14
         1
       ]
      
      at Context.<anonymous> (src/test/datascience/notebook/intellisense/semanticTokens.vscode.test.ts:157:16)
```

**Comment by DonJayamanne** [comment]
No longer an issue
