### ISSUE TITLE
Warning about missing feature notebookDebugOptions

### ISSUE THREAD

**Issue by robd003** [microsoft/vscode-jupyter#11995]
### Applies To

- [ ] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

```[critical] Extension 'ms-toolsai.jupyter' wants API proposal 'notebookDebugOptions' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.```

### VS Code Version

1.73.1

### Jupyter Extension Version

v2022.9.1202862440

### Jupyter logs

```shell
Visual Studio Code (1.73.1, undefined, desktop)
Jupyter Extension Version: 2022.9.1202862440.
Python Extension Version: 2022.18.2.
Workspace folder /Users/robd/code/allfactors-django
error 08:45:57.177: Exception while attempting zmq : [Error: No native build was found for platform=darwin arch=arm64 runtime=electron abi=106 uv=1 armv=8 libc=glibc node=16.14.2 electron=19.0.17
    loaded from: /Users/robd/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/node_modules/zeromq

	at load.path (/Users/robd/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/node_modules/node-gyp-build/index.js:1:3163)
	at load (/Users/robd/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/node_modules/node-gyp-build/index.js:1:648)
	at Object.<anonymous> (/Users/robd/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/node_modules/zeromq/lib/native.js:1:198)
	at u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1313)
	at Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at c._load (node:electron/js2c/asar_bundle:5:13343)
	at a._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:14563)
	at v._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:113:64900)
	at w._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:113:64268)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:699)
	at Object.<anonymous> (/Users/robd/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/node_modules/zeromq/lib/index.js:1:144)
	at u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1313)
	at Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at c._load (node:electron/js2c/asar_bundle:5:13343)
	at a._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:14563)
	at v._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:113:64900)
	at w._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:113:64268)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:699)
	at 92747 (/Users/robd/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:17:593435)
	at __webpack_require__ (/Users/robd/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:17:1480895)
	at l.zmqSupported (/Users/robd/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:2:2220878)
	at l.isSupportedForLocalLaunch (/Users/robd/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:2:2220621)
	at get isSupported [as isSupported] (/Users/robd/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:2:2220531)
	at t.registerTypes (/Users/robd/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:2:2235624)
	at /Users/robd/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:2:1640908
	at /Users/robd/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:2:1641663
	at /Users/robd/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:2:1641671
	at t.activate (/Users/robd/.vscode/extensions/ms-toolsai.jupyter-2022.9.1202862440/out/extension.node.js:2:1641793)
	at On._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:17678)
	at On._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:17338)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:15133
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async w._activate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:8304)
	at async w._waitForDepsThenActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:8246)
	at async w._initialize (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:7610)]
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 08:45:57.304: LSP Notebooks experiment is disabled -- not in treatment group
info 08:45:57.520: Got env vars ourselves faster /Users/robd/code/allfactors-django/env/bin/python with env var count 55 in 131ms
info 08:45:57.520: Got env vars ourselves faster /Users/robd/code/allfactors-django/env/bin/python with env var count 55 in 131ms
info 08:45:57.520: Got env vars ourselves faster /Users/robd/code/allfactors-django/env/bin/python with env var count 55 in 131ms
info 08:45:57.520: Process Execution: > ~/code/allfactors-django/env/bin/python -m pip list
> ~/code/allfactors-django/env/bin/python -m pip list
info 08:45:57.521: Process Execution: > ~/code/allfactors-django/env/bin/python -c "import jupyter"
> ~/code/allfactors-django/env/bin/python -c "import jupyter"
info 08:45:57.521: Process Execution: > ~/code/allfactors-django/env/bin/python -c "import notebook"
> ~/code/allfactors-django/env/bin/python -c "import notebook"
info 08:45:57.582: Got env vars with python /Users/robd/code/allfactors-django/env/bin/python, with env var count 55 and custom env var count 14 in 193ms
info 08:45:57.584: Got env vars with python /Users/robd/code/allfactors-django/env/bin/python, with env var count 55 and custom env var count 14 in 195ms
info 08:45:57.585: Got env vars with python /Users/robd/code/allfactors-django/env/bin/python, with env var count 55 and custom env var count 14 in 196ms
```

### Coding Language and Runtime Version

Python 3.10

### Running Jupyter locally or remotely?

Local

**Comment by roblourens** [comment]
That proposed API error will not cause an issue. What actual problem are you seeing? The zmq error may be a real issue

**Comment by DonJayamanne** [comment]
@robd003 `error 08:45:57.177: Exception while attempting zmq : [Error: No native build was found f` is an error that can be ignored.
And as @roblourens  has mentioned the warning with the proposed API too can be ignored.
Closing this issue as there isn't really any problem.

Please feel free to file a separate issue or re-open this if there are problems as a result of this or other (i.e. things not working as expected).
