### ISSUE TITLE
Test failure: Install IPyKernel (install) @kernelInstall

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#12005]
https://github.com/microsoft/vscode-jupyter/actions/runs/3446206002/jobs/5750829405

```
  1) Install IPyKernel (install) @kernelInstall
       Ensure ipykernel install prompt is displayed every time you try to run a cell in an Interactive Window and you can switch kernels:

      Error: Illegal argument: start must be positive
      + expected - actual
```

**Comment by DonJayamanne** [comment]
Looks like a bug in VS Code

@amunger @rebornix @mjbvz /cc
Not sure who owns this area, but based on the call stacks this seem seem to be coming from the attachment area


```
Error: Illegal argument: start must be positive
      + expected - actual


      at T (.vscode-test/vscode-linux-x64-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:7:1279)
      at new jt (.vscode-test/vscode-linux-x64-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:92:56[71](https://github.com/microsoft/vscode-jupyter/actions/runs/3459086767/jobs/5774127948#step:44:72)0)
      at Function.updateCellMetadata (.vscode-test/vscode-linux-x64-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:92:20638)
      at e.AttachmentCleaner.cleanNotebookAttachments (.vscode-test/vscode-linux-x64-insiders/resources/app/extensions/ipynb/dist/ipynbMain.js:1:150859)
      at e.DebounceTrigger.callback [as _callbackFn] (.vscode-test/vscode-linux-x64-insiders/resources/app/extensions/ipynb/dist/ipynbMain.js:1:148296)
      at e.DebounceTrigger.resume (.vscode-test/vscode-linux-x64-insiders/resources/app/extensions/ipynb/dist/ipynbMain.js:1:1476[75](https://github.com/microsoft/vscode-jupyter/actions/runs/3459086767/jobs/5774127948#step:44:76))
      at Timeout._onTimeout (.vscode-test/vscode-linux-x64-insiders/resources/app/extensions/ipynb/dist/ipynbMain.js:1:147802)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)
```
