### ISSUE TITLE
Test failure: Interactive Window Debugging @debugger

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#12006]
https://github.com/microsoft/vscode-jupyter/actions/runs/3446206002/jobs/5750829824
https://github.com/microsoft/vscode-jupyter/actions/runs/3441902799/jobs/5741935471

```
  1) Interactive Window Debugging @debugger
       Debugging with VSCodePythonDebugger @debugger
         Debug a cell from a python file @mandatory:

      Error: Cell 2 did not complete successfully, State = 1
      + expected - actual


      at Timeout.<anonymous> (src/test/common.ts:65:20)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)
```

**Comment by rebornix** [comment]
https://github.com/microsoft/vscode-jupyter/actions/runs/3441902799/jobs/5741935072

is similar

```
  1) Interactive window execution @iw
       Execute cell from Python file @mandatory:

      Error: Cell 2 did not complete successfully, State = 1
      + expected - actual


      at Timeout.<anonymous> (src/test/common.ts:65:20)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)
```

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-jupyter/issues/11917
