### ISSUE TITLE
Connecting to server on web stops working

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#12064]
```
extension.web.bundle.js:4 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'jupyter')
    at E.registerHooks (extension.web.bundle.js:4:1344695)
    at E.init (extension.web.bundle.js:4:1344221)
    at E.getNewApi (extension.web.bundle.js:4:1343959)
    at x.getApi (extension.web.bundle.js:4:1353561)
    at x.hookupOnDidChangeInterpreterEvent (extension.web.bundle.js:4:1355834)
    at x.getInterpreters (extension.web.bundle.js:4:1349296)
    at x.populateCachedListOfInterpreters (extension.web.bundle.js:4:1353761)
    at x.buildListOfInterpretersForFirstTime (extension.web.bundle.js:4:1355489)
    at x.hookupOnDidChangeInterpreterEvent (extension.web.bundle.js:4:1355791)
    at x.get onDidChangeInterpreter [as onDidChangeInterpreter] (extension.web.bundle.js:4:1348746)
    at new t.JupyterExecutionBase (extension.web.bundle.js:4:941965)
```

**Comment by rebornix** [comment]
`pythonExtension.exports.jupyter.registerHooks();` is reading Python exports actually.

**Comment by DonJayamanne** [comment]
> pythonExtension.exports.jupyter.registerHooks(); is reading Python exports actually.

this path should not hit in web. we cannot use pyth9n extension api in web
