### ISSUE TITLE
Cannot export to PDF

### ISSUE THREAD

**Issue by juanjosegarciaripoll** [microsoft/vscode-jupyter#12062]
## Environment data

-   VS Code version: 1.73.0
-   Jupyter Extension version (available under the Extensions sidebar): 2022.9.1303220346
-   Python Extension version (available under the Extensions sidebar): 2022.18.2
-   OS (Windows | Mac | Linux distro) and version: Windows
-   Python and/or Anaconda version: Miniconda
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

I execute the command to export a notebook to PDF, it should run without problems, but apparently an extension that is not automatically installed is required.

## Actual behaviour

The extension aborts with a message captured below

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Create a minimal conda environment
2. Create a notebook in Visual Studio
3. Let the extension install Jupyter's requirement
4. Execute the command to export to PDF

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
[NbConvertApp] WARNING | Config option `template_path` not recognized by `PDFExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
Traceback (most recent call last):
  File "C:\Users\juanj\miniconda3\envs\iQ\Scripts\jupyter-nbconvert-script.py", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\juanj\miniconda3\envs\iQ\Lib\site-packages\jupyter_core\application.py", line 276, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\juanj\miniconda3\envs\iQ\Lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "C:\Users\juanj\miniconda3\envs\iQ\Lib\site-packages\nbconvert\nbconvertapp.py", line 426, in start
    self.convert_notebooks()
  File "C:\Users\juanj\miniconda3\envs\iQ\Lib\site-packages\nbconvert\nbconvertapp.py", line 595, in convert_notebooks
    self.exporter = cls(config=self.config)
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\juanj\miniconda3\envs\iQ\Lib\site-packages\nbconvert\exporters\templateexporter.py", line 342, in __init__
    super().__init__(config=config, **kw)
  File "C:\Users\juanj\miniconda3\envs\iQ\Lib\site-packages\nbconvert\exporters\exporter.py", line 118, in __init__
    self._init_preprocessors()
  File "C:\Users\juanj\miniconda3\envs\iQ\Lib\site-packages\nbconvert\exporters\templateexporter.py", line 507, in _init_preprocessors
    super()._init_preprocessors()
  File "C:\Users\juanj\miniconda3\envs\iQ\Lib\site-packages\nbconvert\exporters\exporter.py", line 279, in _init_preprocessors
    self.register_preprocessor(preprocessor, enabled=True)
  File "C:\Users\juanj\miniconda3\envs\iQ\Lib\site-packages\nbconvert\exporters\exporter.py", line 239, in register_preprocessor
    preprocessor_cls = import_item(preprocessor)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\juanj\miniconda3\envs\iQ\Lib\site-packages\traitlets\utils\importstring.py", line 30, in import_item
    module = __import__(package, fromlist=[obj])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'jupyter_contrib_nbextensions'
```

</p>
</details>

**Comment by Michitronik** [comment]
I have the same issue with VS Code V1.75.0 and Jupyther Extension Version V2023.1.2000312134.

Export is aborted withe the message for further information see output. But there is no information posted.

**Comment by amunger** [comment]
from searching around, it looks like this may be a problem in a specific nbconvert library from [this comment](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1529#issuecomment-1683016069).

You might be able to resolve this with an uninstall/reinstall of that package as is what helped here: https://github.com/microsoft/vscode-jupyter/issues/4347#issuecomment-763787690.

Let us know if you're still having trouble with this.
