### ISSUE TITLE
Data viewer can't find installed version of pandas

### ISSUE THREAD

**Issue by willtalmadge** [microsoft/vscode-jupyter#12170]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

If I create a jupyter notebook cell with the following contents

```python
import pandas as pd
import numpy as np

print("pandas version " + pd.__version__)

pd.DataFrame()

x = np.random.rand(10, 3)
print(x)
```

Set a breakpoint on `print(x)`

Debug the cell

`pandas version 1.5.2` is printed below the cell

The breakpoint pauses execution as expected

Right click the numpy array for `x` then click "View Value in Data Browser"

I get a prompt "Python package 'pandas' version 0.20.0 (or above) is required for viewing data."

The expected behavior is that the installed pandas version 1.5.2 would be found and used by the data viewer

### VS Code Version

Version: 1.73.1 (Universal)

### Jupyter Extension Version

v2022.9.1303220346

### Jupyter logs

```shell
Visual Studio Code (1.73.1, undefined, desktop)
Jupyter Extension Version: 2022.9.1303220346.
Python Extension Version: 2022.18.2.
Workspace folder /Users/will/ensemble
error 22:07:22.972: Exception while attempting zmq : Error: No native build was found for platform=darwin arch=arm64 runtime=electron abi=106 uv=1 armv=8 libc=glibc node=16.14.2 electron=19.0.17
    loaded from: /Users/will/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/node_modules/zeromq

    at Function.load.path (/Users/will/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/node_modules/node-gyp-build/index.js:1:3163)
    at load (/Users/will/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/node_modules/node-gyp-build/index.js:1:648)
    at Object.<anonymous> (/Users/will/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/node_modules/zeromq/lib/native.js:1:198)
    at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1313)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.a._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:14563)
    at Function.v._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:113:64900)
    at Function.w._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:113:64268)
    at Module.apply (node:internal/modules/cjs/loader:1059:19)
    at Module.require (/Users/will/.vscode/extensions/julialang.language-julia-1.38.2/node_modules/diagnostic-channel/dist/src/patchRequire.js:16:46)
    at p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:699)
    at Object.<anonymous> (/Users/will/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/node_modules/zeromq/lib/index.js:1:144)
    at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1313)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.a._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:14563)
    at Function.v._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:113:64900)
    at Function.w._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:113:64268)
    at Module.apply (node:internal/modules/cjs/loader:1059:19)
    at Module.require (/Users/will/.vscode/extensions/julialang.language-julia-1.38.2/node_modules/diagnostic-channel/dist/src/patchRequire.js:16:46)
    at p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:699)
    at Object.92747 (/Users/will/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:17:593435)
    at __webpack_require__ (/Users/will/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:17:1481375)
    at l.zmqSupported (/Users/will/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2221028)
    at l.isSupportedForLocalLaunch (/Users/will/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2220771)
    at l.get isSupported [as isSupported] (/Users/will/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2220681)
    at t.registerTypes (/Users/will/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2235774)
    at /Users/will/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:1640908
    at /Users/will/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:1641663
    at /Users/will/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:1641671
    at t.activate (/Users/will/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:1641793)
    at Function._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:17678)
    at Function._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:17338)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:15133
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at w._activate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:8304)
    at w._waitForDepsThenActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:8246)
    at w._initialize (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:7610)
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 22:07:23.117: LSP Notebooks experiment is disabled -- not in treatment group
info 22:07:23.118: Attempting to start a server because of preload conditions ...
info 22:07:23.122: Checking for server existence.
info 22:07:23.122: Checking for server usability.
info 22:07:23.276: Preferred Remote kernel for /Users/will/ensemble/test.ipynb is undefined
info 22:07:23.276: Find preferred kernel for /Users/will/ensemble/test.ipynb with metadata {"kernelspec":{"display_name":"Python 3.10.8 ('ml221122')","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.10.8"},"orig_nbformat":4,"vscode":{"interpreter":{"hash":"790b2d9ccd0867be0847ea8164e8bdfc25b47db77a0ea33d7fec0934744bf47a"}}} & preferred interpreter /usr/bin/python3
info 22:07:23.284: Preferred Remote kernel for /Users/will/ensemble/test.ipynb is undefined
info 22:07:23.284: Preferred kernel .jvsc74a57bd0790b2d9ccd0867be0847ea8164e8bdfc25b47db77a0ea33d7fec0934744bf47a./Users/will/opt/miniconda3/envs/ml221122/python./Users/will/opt/miniconda3/envs/ml221122/python.-m#ipykernel_launcher is exact match or top match for non python kernels, (false, undefined, true, false)
info 22:07:23.284: PreferredConnection: .jvsc74a57bd0790b2d9ccd0867be0847ea8164e8bdfc25b47db77a0ea33d7fec0934744bf47a./Users/will/opt/miniconda3/envs/ml221122/python./Users/will/opt/miniconda3/envs/ml221122/python.-m#ipykernel_launcher found for NotebookDocument: /Users/will/ensemble/test.ipynb
info 22:07:23.285: Preferred Remote kernel for /Users/will/ensemble/test.ipynb is undefined
info 22:07:23.290: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd0790b2d9ccd0867be0847ea8164e8bdfc25b47db77a0ea33d7fec0934744bf47a./Users/will/opt/miniconda3/envs/ml221122/python./Users/will/opt/miniconda3/envs/ml221122/python.-m#ipykernel_launcher (Python Path: /Users/will/opt/miniconda3/envs/ml221122, EnvType: Conda, EnvName: 'ml221122', Version: 3.10.8) for '/Users/will/ensemble/test.ipynb' (disableUI=true)
info 22:07:23.448: Got empty env vars with python /usr/bin/python3 in 190ms
info 22:07:23.448: Got env vars ourselves faster /usr/bin/python3 with env var count 51 in 190ms
info 22:07:23.449: Process Execution: > /usr/bin/python3 -m pip list
> /usr/bin/python3 -m pip list
error 22:07:23.793: Execing shell command, Class name = b, completed in 516ms, has a falsy return value, Arg 1: "~/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/pythonFiles/printEnvVariables.py", Arg 2: "" Error: Command failed: conda activate ml221117 && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /Users/will/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/pythonFiles/printEnvVariables.py

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.



    at ChildProcess.exithandler (node:child_process:408:12)
    at ChildProcess.emit (node:events:526:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:526:28)
    at Pipe.<anonymous> (node:net:687:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: "conda activate ml221117 && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /Users/will/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/pythonFiles/printEnvVariables.py"
}
error 22:07:23.794: Execing shell command, Class name = b, completed in 503ms, has a falsy return value, Arg 1: "~/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/pythonFiles/printEnvVariables.py", Arg 2: "" Error: Command failed: conda activate ml221122 && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /Users/will/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/pythonFiles/printEnvVariables.py

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.



    at ChildProcess.exithandler (node:child_process:408:12)
    at ChildProcess.emit (node:events:526:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:526:28)
    at Pipe.<anonymous> (node:net:687:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: "conda activate ml221122 && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /Users/will/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/pythonFiles/printEnvVariables.py"
}
info 22:07:23.800: Registering dummy command feature
info 22:07:23.801: Registering dummy command feature
info 22:07:24.679: Got env vars with python /Users/will/opt/miniconda3/envs/ml221122/bin/python, with env var count 54 and custom env var count 0 in 1390ms
info 22:07:24.680: Process Execution: > ~/opt/miniconda3/envs/ml221122/bin/python -m pip list
> ~/opt/miniconda3/envs/ml221122/bin/python -m pip list
info 22:07:24.726: Got env vars with python /Users/will/opt/miniconda3/envs/ml221117/bin/python, with env var count 54 and custom env var count 0 in 1467ms
info 22:07:24.727: Process Execution: > ~/opt/miniconda3/envs/ml221117/bin/python -c "import notebook"
> ~/opt/miniconda3/envs/ml221117/bin/python -c "import notebook"
info 22:07:24.766: Got env vars with python /Users/will/opt/miniconda3/envs/ml221117/bin/python, with env var count 54 and custom env var count 0 in 1507ms
info 22:07:24.766: Process Execution: > ~/opt/miniconda3/envs/ml221117/bin/python -c "import jupyter"
> ~/opt/miniconda3/envs/ml221117/bin/python -c "import jupyter"
info 22:07:24.846: Got env vars with python /Users/will/opt/miniconda3/envs/ml221117/bin/python, with env var count 54 and custom env var count 0 in 0ms
info 22:07:24.848: Process Execution: > ~/opt/miniconda3/envs/ml221117/bin/python -m jupyter kernelspec --version
> ~/opt/miniconda3/envs/ml221117/bin/python -m jupyter kernelspec --version
info 22:07:25.052: Starting notebook server.
info 22:07:25.052: Connecting to server
info 22:07:25.052: Launching server
info 22:07:25.053: Starting Notebook
info 22:07:25.053: Got env vars with python /Users/will/opt/miniconda3/envs/ml221117/bin/python, with env var count 54 and custom env var count 0 in 1ms
info 22:07:25.053: Got env vars with python /Users/will/opt/miniconda3/envs/ml221117/bin/python, with env var count 54 and custom env var count 0 in 1ms
info 22:07:25.058: Generating custom default config at /var/folders/cj/_s6jtmjj4vq6_n0ncbzbjk3r0000gn/T/af24c86d-8578-4904-ae33-f829b87f7c43/jupyter_notebook_config.py
info 22:07:25.058: Starting Jupyter Notebook
Starting Jupyter from ~/opt/miniconda3/envs/ml221117/bin/python
info 22:07:25.059: Got env vars with python /Users/will/opt/miniconda3/envs/ml221117/bin/python, with env var count 54 and custom env var count 0 in 0ms
info 22:07:25.060: Got env vars with python /Users/will/opt/miniconda3/envs/ml221117/bin/python, with env var count 54 and custom env var count 0 in 1ms
info 22:07:25.060: Creating daemon pool for /Users/will/opt/miniconda3/envs/ml221117/bin/python with env variables count 54
info 22:07:25.062: Process Execution: > ~/opt/miniconda3/envs/ml221117/bin/python -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 63813
> ~/opt/miniconda3/envs/ml221117/bin/python -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 63813
info 22:07:25.065: Process Execution: > ~/opt/miniconda3/envs/ml221117/bin/python -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 63813
> ~/opt/miniconda3/envs/ml221117/bin/python -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 63813
info 22:07:25.065: Process Execution: > ~/opt/miniconda3/envs/ml221117/bin/python -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 63813
> ~/opt/miniconda3/envs/ml221117/bin/python -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 63813
info 22:07:25.121: Got env vars with python /Users/will/opt/miniconda3/envs/ml221117/bin/python, with env var count 54 and custom env var count 0 in 2ms
info 22:07:25.122: Process Execution: > ~/opt/miniconda3/envs/ml221117/bin/python (daemon) -m jupyter notebook --no-browser --notebook-dir="/Users/will/ensemble" --config=/var/folders/cj/_s6jtmjj4vq6_n0ncbzbjk3r0000gn/T/af24c86d-8578-4904-ae33-f829b87f7c43/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
> ~/opt/miniconda3/envs/ml221117/bin/python (daemon) -m jupyter notebook --no-browser --notebook-dir="/Users/will/ensemble" --config=/var/folders/cj/_s6jtmjj4vq6_n0ncbzbjk3r0000gn/T/af24c86d-8578-4904-ae33-f829b87f7c43/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
info 22:07:25.122: Waiting for Jupyter Notebook
/Users/will/opt/miniconda3/envs/ml221117/lib/python3.10/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/will/ensemble' instead of '"/Users/will/ensemble"' if you require traitlets >=5.
  warn(
info 22:07:25.715: /Users/will/opt/miniconda3/envs/ml221117/lib/python3.10/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/will/ensemble' instead of '"/Users/will/ensemble"' if you require traitlets >=5.
  warn(

[I 22:07:25.648 NotebookApp] Serving notebooks from local directory: /Users/will/ensemble
info 22:07:25.715: /Users/will/opt/miniconda3/envs/ml221117/lib/python3.10/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/will/ensemble' instead of '"/Users/will/ensemble"' if you require traitlets >=5.
  warn(
[I 22:07:25.648 NotebookApp] Serving notebooks from local directory: /Users/will/ensemble

[I 22:07:25.648 NotebookApp] Jupyter Notebook 6.5.2 is running at:
info 22:07:25.715: /Users/will/opt/miniconda3/envs/ml221117/lib/python3.10/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/will/ensemble' instead of '"/Users/will/ensemble"' if you require traitlets >=5.
  warn(
[I 22:07:25.648 NotebookApp] Serving notebooks from local directory: /Users/will/ensemble
[I 22:07:25.648 NotebookApp] Jupyter Notebook 6.5.2 is running at:

[I 22:07:25.648 NotebookApp] http://localhost:8888/?token=f117aae51104b3d87178d4fef5734026ebf326a6c45d1e20
info 22:07:25.715: /Users/will/opt/miniconda3/envs/ml221117/lib/python3.10/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/will/ensemble' instead of '"/Users/will/ensemble"' if you require traitlets >=5.
  warn(
[I 22:07:25.648 NotebookApp] Serving notebooks from local directory: /Users/will/ensemble
[I 22:07:25.648 NotebookApp] Jupyter Notebook 6.5.2 is running at:
[I 22:07:25.648 NotebookApp] http://localhost:8888/?token=f117aae51104b3d87178d4fef5734026ebf326a6c45d1e20

info 22:07:25.716: Process Execution: > ~/opt/miniconda3/envs/ml221117/bin/python (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> ~/opt/miniconda3/envs/ml221117/bin/python (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/pythonFiles/vscode_datascience_helpers/getServerInfo.py
info 22:07:25.716: Got env vars with python /Users/will/opt/miniconda3/envs/ml221117/bin/python, with env var count 54 and custom env var count 0 in 1ms
[I 22:07:25.648 NotebookApp]  or http://127.0.0.1:8888/?token=f117aae51104b3d87178d4fef5734026ebf326a6c45d1e20
info 22:07:25.716: /Users/will/opt/miniconda3/envs/ml221117/lib/python3.10/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/will/ensemble' instead of '"/Users/will/ensemble"' if you require traitlets >=5.
  warn(
[I 22:07:25.648 NotebookApp] Serving notebooks from local directory: /Users/will/ensemble
[I 22:07:25.648 NotebookApp] Jupyter Notebook 6.5.2 is running at:
[I 22:07:25.648 NotebookApp] http://localhost:8888/?token=f117aae51104b3d87178d4fef5734026ebf326a6c45d1e20
[I 22:07:25.648 NotebookApp]  or http://127.0.0.1:8888/?token=f117aae51104b3d87178d4fef5734026ebf326a6c45d1e20

info 22:07:25.717: Process Execution: > ~/opt/miniconda3/envs/ml221117/bin/python (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> ~/opt/miniconda3/envs/ml221117/bin/python (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/pythonFiles/vscode_datascience_helpers/getServerInfo.py
info 22:07:25.717: Got env vars with python /Users/will/opt/miniconda3/envs/ml221117/bin/python, with env var count 54 and custom env var count 0 in 1ms
[I 22:07:25.648 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
info 22:07:25.717: /Users/will/opt/miniconda3/envs/ml221117/lib/python3.10/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/will/ensemble' instead of '"/Users/will/ensemble"' if you require traitlets >=5.
  warn(
[I 22:07:25.648 NotebookApp] Serving notebooks from local directory: /Users/will/ensemble
[I 22:07:25.648 NotebookApp] Jupyter Notebook 6.5.2 is running at:
[I 22:07:25.648 NotebookApp] http://localhost:8888/?token=f117aae51104b3d87178d4fef5734026ebf326a6c45d1e20
[I 22:07:25.648 NotebookApp]  or http://127.0.0.1:8888/?token=f117aae51104b3d87178d4fef5734026ebf326a6c45d1e20
[I 22:07:25.648 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

info 22:07:25.718: Got env vars with python /Users/will/opt/miniconda3/envs/ml221117/bin/python, with env var count 54 and custom env var count 0 in 1ms
[C 22:07:25.651 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/will/Library/Jupyter/runtime/nbserver-64063-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=f117aae51104b3d87178d4fef5734026ebf326a6c45d1e20
     or http://127.0.0.1:8888/?token=f117aae51104b3d87178d4fef5734026ebf326a6c45d1e20
info 22:07:25.718: /Users/will/opt/miniconda3/envs/ml221117/lib/python3.10/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/will/ensemble' instead of '"/Users/will/ensemble"' if you require traitlets >=5.
  warn(
[I 22:07:25.648 NotebookApp] Serving notebooks from local directory: /Users/will/ensemble
[I 22:07:25.648 NotebookApp] Jupyter Notebook 6.5.2 is running at:
[I 22:07:25.648 NotebookApp] http://localhost:8888/?token=f117aae51104b3d87178d4fef5734026ebf326a6c45d1e20
[I 22:07:25.648 NotebookApp]  or http://127.0.0.1:8888/?token=f117aae51104b3d87178d4fef5734026ebf326a6c45d1e20
[I 22:07:25.648 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 22:07:25.651 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/will/Library/Jupyter/runtime/nbserver-64063-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=f117aae51104b3d87178d4fef5734026ebf326a6c45d1e20
     or http://127.0.0.1:8888/?token=f117aae51104b3d87178d4fef5734026ebf326a6c45d1e20

info 22:07:25.719: Got env vars with python /Users/will/opt/miniconda3/envs/ml221117/bin/python, with env var count 54 and custom env var count 0 in 1ms
info 22:07:25.959: Connecting to process server
info 22:07:25.959: Connecting server kernel http://localhost:8888/
info 22:07:25.960: Creating server with url : http://localhost:8888/
info 22:07:25.965: Connection complete server
info 22:07:25.965: Server started.
info 22:07:25.970: Process Execution: > ~/opt/miniconda3/envs/ml221117/bin/python (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> ~/opt/miniconda3/envs/ml221117/bin/python (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/pythonFiles/vscode_datascience_helpers/getServerInfo.py
info 22:07:25.970: Process Execution: > ~/opt/miniconda3/envs/ml221117/bin/python (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> ~/opt/miniconda3/envs/ml221117/bin/python (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/pythonFiles/vscode_datascience_helpers/getServerInfo.py
[I 22:07:26.041 NotebookApp] Creating new notebook in 
info 22:07:26.070: installMissingDependencies /Users/will/opt/miniconda3/envs/ml221122/bin/python, ui.disabled=true for resource '/Users/will/ensemble/test.ipynb'
info 22:07:26.070: Got env vars with python /Users/will/opt/miniconda3/envs/ml221122/bin/python, with env var count 54 and custom env var count 0 in 0ms
info 22:07:26.072: Process Execution: > ~/opt/miniconda3/envs/ml221122/bin/python -c "import ipykernel"
> ~/opt/miniconda3/envs/ml221122/bin/python -c "import ipykernel"
info 22:07:26.197: Spec argv[0] updated from '/Users/will/opt/miniconda3/envs/ml221122/bin/python' to '/Users/will/opt/miniconda3/envs/ml221122/bin/python'
info 22:07:26.897: Got env vars with python /Users/will/opt/miniconda3/envs/ml221122/bin/python, with env var count 55 and custom env var count 0 in 700ms
[I 22:07:26.932 NotebookApp] Kernel started: f712db9b-2e64-4dd8-8621-523321f0ba7c, name: python3108jvsc74a57bd0790b2d9ccd0867be0847ea8164e8bdfc25b47db77a0ea33d7fec0934744bf47a
[W 22:07:26.942 NotebookApp] delete /test-jvsc-a41eefa1-b96b-4d4a-9a51-d5ab7eca8879659b3393-effe-49ac-9000-08779bbfffef.ipynb
info 22:07:27.419: Started session for kernel startUsingPythonInterpreter:.jvsc74a57bd0790b2d9ccd0867be0847ea8164e8bdfc25b47db77a0ea33d7fec0934744bf47a./Users/will/opt/miniconda3/envs/ml221122/python./Users/will/opt/miniconda3/envs/ml221122/python.-m#ipykernel_launcher
info 22:07:27.421: UpdateWorkingDirectoryAndPath in Kernel
info 22:07:27.487: Got env vars with python /Users/will/opt/miniconda3/envs/ml221122/bin/python, with env var count 55 and custom env var count 0 in 0ms
info 22:07:27.488: Process Execution: > ~/opt/miniconda3/envs/ml221122/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/pythonFiles/printJupyterDataDir.py
> ~/opt/miniconda3/envs/ml221122/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/pythonFiles/printJupyterDataDir.py
warn 22:07:27.503: Got a non-existent Jupyer Data Dir file:///Users/will/.local/share/jupyter
info 22:15:27.836: Got env vars ourselves faster /usr/bin/python3 with env var count 51 in 1ms
info 22:15:27.837: Process Execution: > /usr/bin/python3 -c "import pandas;print(pandas.__version__)"
> /usr/bin/python3 -c "import pandas;print(pandas.__version__)"
info 22:15:27.855: Got empty env vars with python /usr/bin/python3 in 19ms
warn 22:15:27.867: Failed to get version of Pandas to use the Data Viewer. Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pandas'

error 22:15:30.187: Error: Python package 'pandas' version 0.20.0 (or above) is required for viewing data.
    at s.promptInstall (/Users/will/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:17:380349)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
warn 22:15:30.187: DataScience Error Error: Python package 'pandas' version 0.20.0 (or above) is required for viewing data.
    at s.promptInstall (/Users/will/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:17:380349)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Coding Language and Runtime Version

python 3.10.8

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
