### ISSUE TITLE
Kernel keeps crashing on Ubuntu 22.04 and conda

### ISSUE THREAD

**Issue by SCLeoX** [microsoft/vscode-jupyter#12182]
### Applies To

- [ ] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

It refuses to start. In the logs, I find nothing of importance.

### VS Code Version

Version: 1.72.2 Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075 Date: 2022-10-12T22:16:26.920Z Electron: 19.0.17 Chromium: 102.0.5005.167 Node.js: 16.14.2 V8: 10.2.154.15-electron.0 OS: Linux x64 5.15.0-52-generic snap Sandboxed: No

### Jupyter Extension Version

v2022.9.1303220346

### Jupyter logs

```shell
info 18:18:02.540: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd00f711cfddf796f1137f011238a9ad294e4ea77238969e96ccb7dd83a9dcb9d27./home/rin/miniconda3/envs/rl/python./home/rin/miniconda3/envs/rl/python.-m#ipykernel_launcher (Python Path: /home/rin/miniconda3/envs/rl, EnvType: Conda, EnvName: 'rl', Version: 3.10.8) for '/media/rin/F64AC4534AC411F3/Data/GT/BayRn/v.ipynb' (disableUI=false)
[I 18:18:02.544 NotebookApp] Creating new notebook in 
info 18:18:02.595: installMissingDependencies /home/rin/miniconda3/envs/rl/bin/python, ui.disabled=false for resource '/media/rin/F64AC4534AC411F3/Data/GT/BayRn/v.ipynb'
info 18:18:02.595: Got env vars with python /home/rin/miniconda3/envs/rl/bin/python, with env var count 86 and custom env var count 0 in 0ms
info 18:18:02.595: Got env vars ourselves faster /home/rin/miniconda3/envs/rl/bin/python with env var count 85 in 0ms
info 18:18:02.602: Process Execution: > ~/miniconda3/envs/rl/bin/python -c "import ipykernel"
> ~/miniconda3/envs/rl/bin/python -c "import ipykernel"
info 18:18:02.680: Spec argv[0] updated from '/home/rin/miniconda3/envs/rl/bin/python' to '/home/rin/miniconda3/envs/rl/bin/python'
info 18:18:02.681: Got env vars with python /home/rin/miniconda3/envs/rl/bin/python, with env var count 87 and custom env var count 0 in 1ms
info 18:18:02.681: Got env vars ourselves faster /home/rin/miniconda3/envs/rl/bin/python with env var count 85 in 1ms
[I 18:18:02.699 NotebookApp] Kernel started: a2238af7-b3ba-468e-a9e1-a9d6973d534b, name: python3108jvsc74a57bd00f711cfddf796f1137f011238a9ad294e4ea77238969e96ccb7dd83a9dcb9d27
[W 18:18:02.708 NotebookApp] delete /v-jvsc-5fd59949-81e1-4559-8fb3-7a5400ecb894d5e745d8-0771-432f-bbdb-25476a183667.ipynb
[I 18:18:05.693 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
[I 18:18:08.708 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
[I 18:18:11.724 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
[I 18:18:14.739 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
[I 18:18:17.756 NotebookApp] KernelRestarter: restarting kernel (5/5), new random ports
[W 18:18:20.772 NotebookApp] KernelRestarter: restart failed
[W 18:18:20.772 NotebookApp] Kernel a2238af7-b3ba-468e-a9e1-a9d6973d534b died, removing from map.
error 18:18:22.709: Session disposed while waiting for session to be idle.
error 18:18:22.709: Failed to change kernel, re-throwing a [Error]: Kernel rl (Python 3.10.8) is not usable. Check the Jupyter output tab for more information.
    at k.waitForIdleOnSession (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:1790657)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at k.createNewKernelSession (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2077553)
    at k.connect (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2076271)
    at u.startNew (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2084916)
    at s (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2014143)
    at _.createNotebookInstance (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2014306)
    at _.createNotebook (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2015245)
    at t.Kernel.createJupyterSession (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2100804)
    at t.Kernel.start (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2095530)
    at Function.wrapKernelMethodImpl (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2349214) {
  category: 'invalidkernel',
  kernelConnectionMetadata: {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: undefined,
      interpreterPath: '/home/rin/miniconda3/envs/rl/bin/python',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'python3108jvsc74a57bd00f711cfddf796f1137f011238a9ad294e4ea77238969e96ccb7dd83a9dcb9d27',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: "Python 3.10.8 ('rl')",
      metadata: [Object],
      env: {},
      interrupt_mode: undefined
    },
    interpreter: {
      id: '/home/rin/miniconda3/envs/rl/bin/python',
      sysPrefix: '/home/rin/miniconda3/envs/rl',
      envType: 'Conda',
      envName: 'rl',
      envPath: [p],
      architecture: 3,
      sysVersion: '3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:26:04) [GCC 10.4.0]',
      version: [Object],
      companyDisplayName: 'Anaconda, Inc.',
      displayName: "Python 3.10.8 ('rl')",
      detailedDisplayName: "Python 3.10.8 ('rl': conda)",
      uri: [p]
    },
    id: '.jvsc74a57bd00f711cfddf796f1137f011238a9ad294e4ea77238969e96ccb7dd83a9dcb9d27./home/rin/miniconda3/envs/rl/python./home/rin/miniconda3/envs/rl/python.-m#ipykernel_launcher'
  }
}
warn 18:18:22.710: Error occurred while trying to start the kernel, options.disableUI=false a [Error]: Kernel rl (Python 3.10.8) is not usable. Check the Jupyter output tab for more information.
    at k.waitForIdleOnSession (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:1790657)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at k.createNewKernelSession (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2077553)
    at k.connect (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2076271)
    at u.startNew (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2084916)
    at s (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2014143)
    at _.createNotebookInstance (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2014306)
    at _.createNotebook (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2015245)
    at t.Kernel.createJupyterSession (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2100804)
    at t.Kernel.start (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2095530)
    at Function.wrapKernelMethodImpl (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2349214) {
  category: 'invalidkernel',
  kernelConnectionMetadata: {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: undefined,
      interpreterPath: '/home/rin/miniconda3/envs/rl/bin/python',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'python3108jvsc74a57bd00f711cfddf796f1137f011238a9ad294e4ea77238969e96ccb7dd83a9dcb9d27',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: "Python 3.10.8 ('rl')",
      metadata: [Object],
      env: {},
      interrupt_mode: undefined
    },
    interpreter: {
      id: '/home/rin/miniconda3/envs/rl/bin/python',
      sysPrefix: '/home/rin/miniconda3/envs/rl',
      envType: 'Conda',
      envName: 'rl',
      envPath: [p],
      architecture: 3,
      sysVersion: '3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:26:04) [GCC 10.4.0]',
      version: [Object],
      companyDisplayName: 'Anaconda, Inc.',
      displayName: "Python 3.10.8 ('rl')",
      detailedDisplayName: "Python 3.10.8 ('rl': conda)",
      uri: [p]
    },
    id: '.jvsc74a57bd00f711cfddf796f1137f011238a9ad294e4ea77238969e96ccb7dd83a9dcb9d27./home/rin/miniconda3/envs/rl/python./home/rin/miniconda3/envs/rl/python.-m#ipykernel_launcher'
  }
}
warn 18:18:22.710: Kernel Error, context = start a [Error]: Kernel rl (Python 3.10.8) is not usable. Check the Jupyter output tab for more information.
    at k.waitForIdleOnSession (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:1790657)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at k.createNewKernelSession (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2077553)
    at k.connect (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2076271)
    at u.startNew (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2084916)
    at s (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2014143)
    at _.createNotebookInstance (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2014306)
    at _.createNotebook (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2015245)
    at t.Kernel.createJupyterSession (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2100804)
    at t.Kernel.start (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2095530)
    at Function.wrapKernelMethodImpl (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2349214) {
  category: 'invalidkernel',
  kernelConnectionMetadata: {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: undefined,
      interpreterPath: '/home/rin/miniconda3/envs/rl/bin/python',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'python3108jvsc74a57bd00f711cfddf796f1137f011238a9ad294e4ea77238969e96ccb7dd83a9dcb9d27',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: "Python 3.10.8 ('rl')",
      metadata: [Object],
      env: {},
      interrupt_mode: undefined
    },
    interpreter: {
      id: '/home/rin/miniconda3/envs/rl/bin/python',
      sysPrefix: '/home/rin/miniconda3/envs/rl',
      envType: 'Conda',
      envName: 'rl',
      envPath: [p],
      architecture: 3,
      sysVersion: '3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:26:04) [GCC 10.4.0]',
      version: [Object],
      companyDisplayName: 'Anaconda, Inc.',
      displayName: "Python 3.10.8 ('rl')",
      detailedDisplayName: "Python 3.10.8 ('rl': conda)",
      uri: [p]
    },
    id: '.jvsc74a57bd00f711cfddf796f1137f011238a9ad294e4ea77238969e96ccb7dd83a9dcb9d27./home/rin/miniconda3/envs/rl/python./home/rin/miniconda3/envs/rl/python.-m#ipykernel_launcher'
  }
}
info 18:18:22.711: Got env vars with python /home/rin/miniconda3/envs/rl/bin/python, with env var count 86 and custom env var count 0 in 1ms
info 18:18:22.711: Got env vars ourselves faster /home/rin/miniconda3/envs/rl/bin/python with env var count 85 in 1ms
info 18:18:22.716: Process Execution: > ~/miniconda3/envs/rl/bin/python -c "import ipykernel"
> ~/miniconda3/envs/rl/bin/python -c "import ipykernel"
info 18:18:22.796: Dispose Kernel '/media/rin/F64AC4534AC411F3/Data/GT/BayRn/v.ipynb' associated with '/media/rin/F64AC4534AC411F3/Data/GT/BayRn/v.ipynb'
error 18:18:22.797: Error in execution a [Error]: Kernel rl (Python 3.10.8) is not usable. Check the Jupyter output tab for more information.
    at k.waitForIdleOnSession (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:1790657)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at k.createNewKernelSession (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2077553)
    at k.connect (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2076271)
    at u.startNew (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2084916)
    at s (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2014143)
    at _.createNotebookInstance (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2014306)
    at _.createNotebook (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2015245)
    at t.Kernel.createJupyterSession (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2100804)
    at t.Kernel.start (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2095530)
    at Function.wrapKernelMethodImpl (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2349214) {
  category: 'invalidkernel',
  kernelConnectionMetadata: {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: undefined,
      interpreterPath: '/home/rin/miniconda3/envs/rl/bin/python',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'python3108jvsc74a57bd00f711cfddf796f1137f011238a9ad294e4ea77238969e96ccb7dd83a9dcb9d27',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: "Python 3.10.8 ('rl')",
      metadata: [Object],
      env: {},
      interrupt_mode: undefined
    },
    interpreter: {
      id: '/home/rin/miniconda3/envs/rl/bin/python',
      sysPrefix: '/home/rin/miniconda3/envs/rl',
      envType: 'Conda',
      envName: 'rl',
      envPath: [p],
      architecture: 3,
      sysVersion: '3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:26:04) [GCC 10.4.0]',
      version: [Object],
      companyDisplayName: 'Anaconda, Inc.',
      displayName: "Python 3.10.8 ('rl')",
      detailedDisplayName: "Python 3.10.8 ('rl': conda)",
      uri: [p]
    },
    id: '.jvsc74a57bd00f711cfddf796f1137f011238a9ad294e4ea77238969e96ccb7dd83a9dcb9d27./home/rin/miniconda3/envs/rl/python./home/rin/miniconda3/envs/rl/python.-m#ipykernel_launcher'
  }
}
error 18:18:22.797: Error in execution (get message for cell) a [Error]: Kernel rl (Python 3.10.8) is not usable. Check the Jupyter output tab for more information.
    at k.waitForIdleOnSession (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:1790657)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at k.createNewKernelSession (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2077553)
    at k.connect (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2076271)
    at u.startNew (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2084916)
    at s (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2014143)
    at _.createNotebookInstance (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2014306)
    at _.createNotebook (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2015245)
    at t.Kernel.createJupyterSession (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2100804)
    at t.Kernel.start (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2095530)
    at Function.wrapKernelMethodImpl (/home/rin/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2349214) {
  category: 'invalidkernel',
  kernelConnectionMetadata: {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: undefined,
      interpreterPath: '/home/rin/miniconda3/envs/rl/bin/python',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'python3108jvsc74a57bd00f711cfddf796f1137f011238a9ad294e4ea77238969e96ccb7dd83a9dcb9d27',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: "Python 3.10.8 ('rl')",
      metadata: [Object],
      env: {},
      interrupt_mode: undefined
    },
    interpreter: {
      id: '/home/rin/miniconda3/envs/rl/bin/python',
      sysPrefix: '/home/rin/miniconda3/envs/rl',
      envType: 'Conda',
      envName: 'rl',
      envPath: [p],
      architecture: 3,
      sysVersion: '3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:26:04) [GCC 10.4.0]',
      version: [Object],
      companyDisplayName: 'Anaconda, Inc.',
      displayName: "Python 3.10.8 ('rl')",
      detailedDisplayName: "Python 3.10.8 ('rl': conda)",
      uri: [p]
    },
    id: '.jvsc74a57bd00f711cfddf796f1137f011238a9ad294e4ea77238969e96ccb7dd83a9dcb9d27./home/rin/miniconda3/envs/rl/python./home/rin/miniconda3/envs/rl/python.-m#ipykernel_launcher'
  }
}
[W 18:19:02.713 NotebookApp] Timeout waiting for kernel_info reply from a2238af7-b3ba-468e-a9e1-a9d6973d534b
[E 18:19:02.714 NotebookApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: a2238af7-b3ba-468e-a9e1-a9d6973d534b)
```

### Coding Language and Runtime Version

Python 3.10.8

### Language Extension Version (if applicable)

v2022.16.1

### Anaconda Version (if applicable)

22.9.0

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Thanks for filing this issue and I'm sorry you are running into this issue.
Based on the logs, we're unable to start the kernel in the python environment `/home/rin/miniconda3/envs/rl/bin/python`

Please could you try the following:
* activate the conda environment `rl`
* Install jupyter notebook into that if its not already installed
* Start jupyter from that conda environment
* Try running a notebook with some sample code and verify it works

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
