### ISSUE TITLE
Fail to activate the Jupyter extension

### ISSUE THREAD

**Issue by cameron-chen** [microsoft/vscode-jupyter#12200]
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

The latest pre-release version of the Jupyter extension cannot be activated as reported by https://github.com/microsoft/vscode-jupyter/issues/11938#issuecomment-1325302330. 

A history version works for me: v2022.11.1003281132

### VS Code Version

1.73.1

### Jupyter Extension Version

v2022.11.1003301027

### Jupyter logs

```shell
Visual Studio Code (1.73.1, ssh-remote, desktop)
Jupyter Extension Version: 2022.11.1003301027.
Python Extension Version: 2022.19.13251009.
Workspace folder /***
info 17:34:03.699: ZMQ install verified.
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
error 17:34:04.188: Failure during activation. [TypeError: s.notebooks.createNotebookControllerDetectionTask is not a function
	at h.startRefreshWithPython (/***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:2:2070921)
	at h.activate (/***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:2:2069968)
	at /***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:17:163983
	at Array.map (<anonymous>)
	at c.activateSync (/***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:17:163973)
	at /***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:2:1576749]
error 17:34:04.189: sendStartupTelemetry() failed. [TypeError: s.notebooks.createNotebookControllerDetectionTask is not a function
	at h.startRefreshWithPython (/***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:2:2070921)
	at h.activate (/***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:2:2069968)
	at /***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:17:163983
	at Array.map (<anonymous>)
	at c.activateSync (/***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:17:163973)
	at /***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:2:1576749]
error 17:34:04.189: extension activation failed [TypeError: s.notebooks.createNotebookControllerDetectionTask is not a function
	at h.startRefreshWithPython (/***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:2:2070921)
	at h.activate (/***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:2:2069968)
	at /***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:17:163983
	at Array.map (<anonymous>)
	at c.activateSync (/***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:17:163973)
	at /***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:2:1576749]
error 17:34:04.207: Failed to active the Jupyter Extension [TypeError: s.notebooks.createNotebookControllerDetectionTask is not a function
	at h.startRefreshWithPython (/***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:2:2070921)
	at h.activate (/***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:2:2069968)
	at /***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:17:163983
	at Array.map (<anonymous>)
	at c.activateSync (/***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:17:163973)
	at /***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:2:1576749]
```

### Coding Language and Runtime Version

Python v3.8.13

### Language Extension Version (if applicable)

Pylance v2022.11.30

### Anaconda Version (if applicable)

conda v4.11.0

### Running Jupyter locally or remotely?

Remote

**Comment by amunger** [comment]
this is likely because you're using stable vs code with pre-release jupyter. If you need the features from pre-release jupyter, you'll need to switch to insiders vs code. Can you try that and see if it works for you?

**Comment by maxbane** [comment]
I hit this same error after switching to the pre-release version of mstoolsai.jupyter, which I only did because it is the workaround mentioned in #11938. Probably you are right that it is failing because vs code itself is not pre-release (insiders)... some quick thoughts:

- This means that the workaround for #11938 is no longer good unless the user ALSO changes their vs code version.
- I kind of wonder, if pre-release jupyter depends on pre-release vs code, then why is it even possible to click "Switch to Pre-Release Version" on the extension page when not running pre-release vs code? Is it not possible to declare a dependency there?

**Comment by amunger** [comment]
We missed bumping the version requirement in pre-release until a few days ago and should be fixed in the latest. Can you try updating to the latest and see if it still occurs?

**Comment by cameron-chen** [comment]
> We missed bumping the version requirement in pre-release until a few days ago and should be fixed in the latest. Can you try updating to the latest and see if it still occurs?

I am not sure if you mean stable vs code works well with the pre-release version of mstoolsai.jupyter for now. If true, I checked and found out the issue is still there: 

```
Visual Studio Code (1.73.1, ssh-remote, desktop)
Jupyter Extension Version: 2022.11.1003301027.
Python Extension Version: 2022.19.13251009.
Workspace folder /***
info 11:32:28.679: ZMQ install verified.
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
error 11:32:29.157: Failure during activation. [TypeError: s.notebooks.createNotebookControllerDetectionTask is not a function
	at h.startRefreshWithPython (/***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:2:2070921)
	at h.activate (/***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:2:2069968)
	at /***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:17:163983
	at Array.map (<anonymous>)
	at c.activateSync (/***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:17:163973)
	at /***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:2:1576749]
error 11:32:29.158: sendStartupTelemetry() failed. [TypeError: s.notebooks.createNotebookControllerDetectionTask is not a function
	at h.startRefreshWithPython (/***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:2:2070921)
	at h.activate (/***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:2:2069968)
	at /***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:17:163983
	at Array.map (<anonymous>)
	at c.activateSync (/***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:17:163973)
	at /***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:2:1576749]
error 11:32:29.158: extension activation failed [TypeError: s.notebooks.createNotebookControllerDetectionTask is not a function
	at h.startRefreshWithPython (/***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:2:2070921)
	at h.activate (/***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:2:2069968)
	at /***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:17:163983
	at Array.map (<anonymous>)
	at c.activateSync (/***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:17:163973)
	at /***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:2:1576749]
error 11:32:29.175: Failed to active the Jupyter Extension [TypeError: s.notebooks.createNotebookControllerDetectionTask is not a function
	at h.startRefreshWithPython (/***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:2:2070921)
	at h.activate (/***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:2:2069968)
	at /***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:17:163983
	at Array.map (<anonymous>)
	at c.activateSync (/***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:17:163973)
	at /***/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:2:1576749]
```

**Comment by amunger** [comment]
Ok, I have it cleared up now. There is still an issue where pre-release jupyter is using a proposed API that is not available in stable VSCode. We bumped the required version in our pre-release to enforce the dependency and prevent these versions being used together, but since we already pushed a pre-release version with this bad configuration, it will be used by default as the latest compatible version available.

This will resolve by next week when the new stable releases go live, but for now, the workarounds for now are to install VSCode insiders or downgrade the Jupyter extension to v2022.11.1003281132. Sorry for the inconvenience

**Comment by cameron-chen** [comment]
That is great. Thanks a lot.

**Comment by DonJayamanne** [comment]
Closing this issue for now as this has been fixed and once you upgrade to the latest -version of vscode (to be relaesed this wek), then this shoudl work as exptected

**Comment by kylebarron** [comment]
This is indeed now working for me as of vscode 1.74.0
