### ISSUE TITLE
Editing and running large jupyter notebook files extremely slow when operating on a remote machine

### ISSUE THREAD

**Issue by TTTPOB** [microsoft/vscode-jupyter#12284]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

1. connect to a remote linux server using `Remote-SSH` extension
2. open a big jupyter notebook file containing multiple figures
3. type `print(1)`
4. this command takes 5s to execute
5. note: I am editing the notebook at a remote linux machine, no matter I use local kernel (of course local kernel on server), or I start a jupyter server manually in background and let vscode connect to kernel of this "remote" server, this issue exists.

also, I observed the bandwidth usage spiked when I was opening the file, saveing the file and running the command, so I guess is this extension working by pull the remote notebook to local and then push it back to remote? if the answer is yes, I think this may be the origin of the problem?

In my scenario (bioinformatics analysis like single-cell rna-seq data processing), plotting multiple figures in the save notebook is a common operation, I think the notebook may easily go as big as 20M, so this issue is annoying.

this is the file (zipped) I use to reproduce this issue
[large_notebook.zip](https://github.com/microsoft/vscode-jupyter/files/10143160/large_notebook.zip)

### VS Code Version

1.73.1

### Jupyter Extension Version

v2022.9.1303220346

### Jupyter logs

```shell
Visual Studio Code (1.73.1, ssh-remote, desktop)
Jupyter Extension Version: 2022.9.1303220346.
Python Extension Version: 2022.18.2.
Workspace folder /home/username/playground/temp/2022.12.03.jupyter_slow_issue
error 01:28:34.158: Exception while attempting zmq : [Error: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /NAS392047/home/username/.vscode-server/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/node_modules/zeromq/prebuilds/linux-x64/electron.napi.glibc.node)
	at Object.Module._extensions..node (node:internal/modules/cjs/loader:1187:18)
	at Module.load (node:internal/modules/cjs/loader:981:32)
	at Function.Module._load (node:internal/modules/cjs/loader:822:12)
	at Function.a._load (/NAS392047/home/username/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/workbench/api/node/extensionHostProcess.js:118:14563)
	at Function.v._load (/NAS392047/home/username/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/workbench/api/node/extensionHostProcess.js:113:64900)
	at Function.w._load (/NAS392047/home/username/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/workbench/api/node/extensionHostProcess.js:113:64268)
	at Module.require (node:internal/modules/cjs/loader:1005:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at load (/NAS392047/home/username/.vscode-server/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/node_modules/node-gyp-build/index.js:1:566)
	at Object.<anonymous> (/NAS392047/home/username/.vscode-server/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/node_modules/zeromq/lib/native.js:1:136)
	at Module._compile (node:internal/modules/cjs/loader:1103:14)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
	at Module.load (node:internal/modules/cjs/loader:981:32)
	at Function.Module._load (node:internal/modules/cjs/loader:822:12)
	at Function.a._load (/NAS392047/home/username/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/workbench/api/node/extensionHostProcess.js:118:14563)
	at Function.v._load (/NAS392047/home/username/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/workbench/api/node/extensionHostProcess.js:113:64900)
	at Function.w._load (/NAS392047/home/username/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/workbench/api/node/extensionHostProcess.js:113:64268)
	at Module.require (node:internal/modules/cjs/loader:1005:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Object.<anonymous> (/NAS392047/home/username/.vscode-server/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/node_modules/zeromq/lib/index.js:1:82)
	at Module._compile (node:internal/modules/cjs/loader:1103:14)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
	at Module.load (node:internal/modules/cjs/loader:981:32)
	at Function.Module._load (node:internal/modules/cjs/loader:822:12)
	at Function.a._load (/NAS392047/home/username/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/workbench/api/node/extensionHostProcess.js:118:14563)
	at Function.v._load (/NAS392047/home/username/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/workbench/api/node/extensionHostProcess.js:113:64900)
	at Function.w._load (/NAS392047/home/username/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/workbench/api/node/extensionHostProcess.js:113:64268)
	at Module.require (node:internal/modules/cjs/loader:1005:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Object.92747 (/NAS392047/home/username/.vscode-server/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:17:593435)
	at __webpack_require__ (/NAS392047/home/username/.vscode-server/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:17:1481375)
	at l.zmqSupported (/NAS392047/home/username/.vscode-server/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2221028)
	at l.isSupportedForLocalLaunch (/NAS392047/home/username/.vscode-server/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2220771)
	at l.get isSupported [as isSupported] (/NAS392047/home/username/.vscode-server/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2220681)
	at t.registerTypes (/NAS392047/home/username/.vscode-server/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2235774)
	at /NAS392047/home/username/.vscode-server/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:1640908
	at /NAS392047/home/username/.vscode-server/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:1641663
	at /NAS392047/home/username/.vscode-server/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:1641671
	at t.activate (/NAS392047/home/username/.vscode-server/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:1641793)
	at Function._callActivateOptional (/NAS392047/home/username/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/workbench/api/node/extensionHostProcess.js:104:17678)
	at Function._callActivate (/NAS392047/home/username/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/workbench/api/node/extensionHostProcess.js:104:17338)
	at /NAS392047/home/username/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/workbench/api/node/extensionHostProcess.js:104:15133
	at async w._activate (/NAS392047/home/username/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/workbench/api/node/extensionHostProcess.js:90:8304)
	at async w._waitForDepsThenActivate (/NAS392047/home/username/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/workbench/api/node/extensionHostProcess.js:90:8246)
	at async w._initialize (/NAS392047/home/username/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/workbench/api/node/extensionHostProcess.js:90:7610)] {
  code: 'ERR_DLOPEN_FAILED'
}
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 01:28:34.479: LSP Notebooks experiment is disabled -- not in treatment group
info 01:28:35.061: Preferred Remote kernel for /home/username/playground/temp/2022.12.03.jupyter_slow_issue/large_notebook.ipynb is undefined
info 01:28:35.080: Preferred Remote kernel for /home/username/playground/temp/2022.12.03.jupyter_slow_issue/large_notebook.ipynb is undefined
info 01:28:35.081: Find preferred kernel for /home/username/playground/temp/2022.12.03.jupyter_slow_issue/large_notebook.ipynb with metadata {"kernelspec":{"display_name":"Base Python 3.8.10","language":"python","name":"base"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.8.12"},"orig_nbformat":4,"vscode":{"interpreter":{"hash":"243c53d8bbc9a8f04ffea94a8cd938689e243d149b5d754965677f26be0a94ba"}}} & preferred interpreter /home/username/anaconda/envs/jupyter_slow/bin/python
info 01:28:35.371: Preferred Remote kernel for /home/username/playground/temp/2022.12.03.jupyter_slow_issue/large_notebook.ipynb is undefined
info 01:28:35.372: Preferred kernel .base./home/username/anaconda/python./home/username/anaconda/python.-m#ipykernel_launcher is exact match or top match for non python kernels, (false, undefined, true, false)
info 01:28:35.373: PreferredConnection: .base./home/username/anaconda/python./home/username/anaconda/python.-m#ipykernel_launcher found for NotebookDocument: /home/username/playground/temp/2022.12.03.jupyter_slow_issue/large_notebook.ipynb
error 01:28:35.533: Execing shell command, Class name = b, completed in 353ms, has a falsy return value, Arg 1: "~/anaconda/envs/jupyter_slow && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /NAS392047/home/username/.vscode-server/extensions/ms-toolsai.jupyter-2022.9.1303220346/pythonFiles/printEnvVariables.py", Arg 2: "" [Error: Command failed: conda activate /home/username/anaconda/envs/jupyter_slow && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /NAS392047/home/username/.vscode-server/extensions/ms-toolsai.jupyter-2022.9.1303220346/pythonFiles/printEnvVariables.py

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.



	at ChildProcess.exithandler (node:child_process:399:12)
	at ChildProcess.emit (node:events:526:28)
	at maybeClose (node:internal/child_process:1092:16)
	at Socket.<anonymous> (node:internal/child_process:451:11)
	at Socket.emit (node:events:526:28)
	at Pipe.<anonymous> (node:net:687:12)] {
  killed: false,
  code: 1,
  signal: null,
  cmd: "conda activate /home/username/anaconda/envs/jupyter_slow && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /NAS392047/home/username/.vscode-server/extensions/ms-toolsai.jupyter-2022.9.1303220346/pythonFiles/printEnvVariables.py"
}
error 01:28:35.638: Execing shell command, Class name = b, completed in 372ms, has a falsy return value, Arg 1: "~/.vscode-server/extensions/ms-toolsai.jupyter-2022.9.1303220346/pythonFiles/printEnvVariables.py", Arg 2: "" [Error: Command failed: conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /NAS392047/home/username/.vscode-server/extensions/ms-toolsai.jupyter-2022.9.1303220346/pythonFiles/printEnvVariables.py

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.



	at ChildProcess.exithandler (node:child_process:399:12)
	at ChildProcess.emit (node:events:526:28)
	at maybeClose (node:internal/child_process:1092:16)
	at Socket.<anonymous> (node:internal/child_process:451:11)
	at Socket.emit (node:events:526:28)
	at Pipe.<anonymous> (node:net:687:12)] {
  killed: false,
  code: 1,
  signal: null,
  cmd: "conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /NAS392047/home/username/.vscode-server/extensions/ms-toolsai.jupyter-2022.9.1303220346/pythonFiles/printEnvVariables.py"
}
info 01:28:35.813: Registering dummy command feature
info 01:28:39.105: Got env vars with python /home/username/anaconda/envs/jupyter_slow/bin/python, with env var count 56 and custom env var count 0 in 4027ms
info 01:28:39.146: Process Execution: > ~/anaconda/envs/jupyter_slow/bin/python -m pip list
> ~/anaconda/envs/jupyter_slow/bin/python -m pip list
info 01:28:41.589: Got env vars with python /home/username/anaconda/bin/python, with env var count 116 and custom env var count 0 in 6503ms
info 01:28:41.633: Process Execution: > ~/anaconda/bin/python -c "import jupyter"
> ~/anaconda/bin/python -c "import jupyter"
info 01:28:41.673: Got env vars with python /home/username/anaconda/bin/python, with env var count 116 and custom env var count 0 in 6587ms
info 01:28:41.711: Process Execution: > ~/anaconda/bin/python -c "import notebook"
> ~/anaconda/bin/python -c "import notebook"
info 01:28:41.810: Got env vars with python /home/username/anaconda/bin/python, with env var count 116 and custom env var count 0 in 6345ms
info 01:28:41.858: Process Execution: > ~/anaconda/bin/python -m pip list
> ~/anaconda/bin/python -m pip list
info 01:28:41.935: Got env vars with python /home/username/anaconda/bin/python, with env var count 116 and custom env var count 0 in 2ms
info 01:28:41.983: Process Execution: > ~/anaconda/bin/python -m jupyter kernelspec --version
> ~/anaconda/bin/python -m jupyter kernelspec --version
info 01:28:42.411: Got env vars with python /home/username/anaconda/bin/python, with env var count 116 and custom env var count 0 in 1ms
info 01:28:42.412: Got env vars with python /home/username/anaconda/bin/python, with env var count 116 and custom env var count 0 in 2ms
```
```


### Coding Language and Runtime Version

python v3, I've tried 3.7 8 9 11, all of them have this issue

### Language Extension Version (if applicable)

v2022.18.2

### Anaconda Version (if applicable)

4.10.1

### Running Jupyter locally or remotely?

N/A or Not sure

**Comment by neelnanda-io** [comment]
Strong +1! I've also been very blocked by this issue.

**Comment by neelnanda-io** [comment]
Digging into it, it looks like a pretty unavoidable issue of the plotting libraries I'm using - either plotly or holoviews injects about 3MB of Javascript when first run into the notebook file, so the file size automatically becomes pretty large.

**Comment by roblourens** [comment]
Merging this into https://github.com/microsoft/vscode/issues/138784
