### ISSUE TITLE
Invalid message: Session is already started in 1.73.1

### ISSUE THREAD

**Issue by sofeikov** [microsoft/vscode-jupyter#12288]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

An attempt to debug a cell causes this message to appear. I'm on Ubuntu 18.04.
The debug session is attempted by pressing Ctrl-Shift-Alt-Enter

### VS Code Version

Version: 1.73.1 Commit: 6261075646f055b99068d3688932416f2346dd3b Date: 2022-11-09T03:54:53.913Z Electron: 19.0.17 Chromium: 102.0.5005.167 Node.js: 16.14.2 V8: 10.2.154.15-electron.0 OS: Linux x64 4.15.0-200-generic Sandboxed: No

### Jupyter Extension Version

v2022.9.1303220346

### Jupyter logs

```shell
warn 10:52:48.760: StdErr from Kernel Process [IPKernelApp] ERROR | Exception in control handler:
Traceback (most recent call last):
  File "/home/sofeikov/anaconda3/envs/titanic/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 334, in process_control
    await result
  File "/home/sofeikov/anaconda3/envs/titanic/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 953, in debug_request
    reply_content = await reply_content
  File "/home/sofeikov/anaconda3/envs/titanic/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 466, in do_debug_request
    return await self.debugger.process_request(msg)
  File "/home/sofeikov/anaconda3/envs/titanic/lib/python3.10/site-packages/ipykernel/debugger.py", line 657, in process_request
    self.stop()
  File "/home/sofeikov/anaconda3/envs/titanic/lib/python3.10/site-packages/ipykernel/debugger.py", line 400, in stop
    self.debugpy_client.disconnect_tcp_socket()
  File "/home/sofeikov/anaconda3/envs/titanic/lib/python3.10/site-packages/ipykernel/debugger.py", line 246, in disconnect_tcp_socket
    self.debugpy_stream.socket.disconnect(self._get_endpoint())
  File "zmq/backend/cython/socket.pyx", line 662, in zmq.backend.cython.socket.Socket.disconnect
zmq.error.ZMQError: No such file or directory
```
```


### Coding Language and Runtime Version

3.10.8

### Language Extension Version (if applicable)

_No response_

### Anaconda Version (if applicable)

conda 22.11.0

### Running Jupyter locally or remotely?

Local

**Comment by tekumara** [comment]
I see this everytime, it appears at the end when the debugging completes and control returns back to the notebook viewer.

eg:
```
debug 17:01:37.003: [Debug] to kernel: {"command":"continue","arguments":{"threadId":1},"type":"request","seq":48}
debug 17:01:37.003: [Debug] to kernel, mapped: {"command":"continue","arguments":{"threadId":1},"type":"request","seq":48}
debug 17:01:37.127: [Debug] response: {"seq":63,"type":"response","request_seq":48,"success":true,"command":"continue","body":{"allThreadsContinued":true}}
debug 17:01:37.181: [Debug] event: {"header":{"msg_id":"94d9537e-54f3688e7d94bc9c1ee78072_52143_396","msg_type":"debug_event","username":"tekumara","session":"94d9537e-54f3688e7d94bc9c1ee78072","date":"2023-02-27T06:01:37.126746Z","version":"5.3"},"msg_id":"94d9537e-54f3688e7d94bc9c1ee78072_52143_396","msg_type":"debug_event","parent_header":{"date":"2023-02-27T06:01:37.003000Z","msg_id":"adad38be-6bba-420c-9510-3dd9d590ddae","msg_type":"debug_request","session":"a749f92a-13cd-4db5-9788-3b94e60a2152","username":"","version":"5.2"},"metadata":{},"content":{"seq":64,"type":"event","event":"continued","body":{"threadId":1,"allThreadsContinued":true}},"buffers":[],"channel":"iopub"}
debug 17:01:37.654: End cell 0 execution @ 1677477697653, started @ 1677477686520, elapsed time = 11.133s
info 17:01:37.654: Cancel all remaining cells true || Error || undefined
debug 17:01:37.654: Cancel pending cells
debug 17:01:37.654: Cell 0 executed with state Error
debug 17:01:37.654: VSCodeNotebookController::handleExecution, Class name = _v, completed in 11135ms, has a falsy return value
debug 17:01:37.661: Executing silently Code (idle) = import os as _VSCODE_os\n_VSCODE_fileList = ["/var/folders/5y/hhvf46cx393_j75q4gm7tvzw0000gq/T/ipyker
debug 17:01:37.669: [Debug] to kernel: {"command":"disconnect","arguments":{"restart":false},"type":"request","seq":49}
debug 17:01:37.669: [Debug] to kernel, mapped: {"command":"disconnect","arguments":{"restart":false},"type":"request","seq":49}
debug 17:01:37.670: Executing silently Code (completed) = import os as _VSCODE_os\n_VSCODE_fileList = ["/var/folders/5y/hhvf46cx393_j75q4gm7tvzw0000gq/T/ipyker with 0 output(s)
debug 17:01:37.673: [Debug] event: {"header":{"msg_id":"94d9537e-54f3688e7d94bc9c1ee78072_52143_405","msg_type":"debug_event","username":"tekumara","session":"94d9537e-54f3688e7d94bc9c1ee78072","date":"2023-02-27T06:01:37.672584Z","version":"5.3"},"msg_id":"94d9537e-54f3688e7d94bc9c1ee78072_52143_405","msg_type":"debug_event","parent_header":{"date":"2023-02-27T06:01:37.669000Z","msg_id":"14a7885b-5126-48fa-a357-3e10de393b05","msg_type":"debug_request","session":"a749f92a-13cd-4db5-9788-3b94e60a2152","username":"","version":"5.2"},"metadata":{},"content":{"seq":65,"type":"event","event":"terminated"},"buffers":[],"channel":"iopub"}
debug 17:01:37.675: [Debug] response: {"seq":66,"type":"response","request_seq":49,"success":true,"command":"disconnect"}
debug 17:01:37.680: [Debug] to kernel: {"command":"disconnect","arguments":{"restart":false},"type":"request","seq":50}
debug 17:01:37.680: [Debug] to kernel, mapped: {"command":"disconnect","arguments":{"restart":false},"type":"request","seq":50}
info 17:01:37.682: Ending debug session f0089a88-381a-4961-9c69-2925e05b3fc2
[IPKernelApp] ERROR | Exception in control handler:
Traceback (most recent call last):
  File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 337, in process_control
    await result
  File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 958, in debug_request
    reply_content = await reply_content
  File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 504, in do_debug_request
    return await self.debugger.process_request(msg)
  File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/ipykernel/debugger.py", line 737, in process_request
    self.stop()
  File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/ipykernel/debugger.py", line 447, in stop
    self.debugpy_client.disconnect_tcp_socket()
  File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/ipykernel/debugger.py", line 280, in disconnect_tcp_socket
    self.debugpy_stream.socket.disconnect(self._get_endpoint())
  File "zmq/backend/cython/socket.pyx", line 664, in zmq.backend.cython.socket.Socket.disconnect
zmq.error.ZMQError: No such file or directory
info 17:01:39.685: Ending debug session f0089a88-381a-4961-9c69-2925e05b3fc2
info 17:01:39.685: Ending debug session f0089a88-381a-4961-9c69-2925e05b3fc2
```

**Comment by roblourens** [comment]
I don't think that error is a problem. It looks like this log shows successful debugging?

**Comment by joyceerhl** [comment]
Please reopen if you can provide more context and this still repros @sofeikov
