### ISSUE TITLE
Kernel from kernel picker shows for 0.5 seconds and disappears

### ISSUE THREAD

**Issue by kolibril13** [microsoft/vscode-jupyter#12291]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

As can be seen in the screen recording, the kernel .venv shows for half second at the top right, and then disappears.
This only happens in already existing notebooks. 
My fix to this problem: When a new notebook is generated, the .venv shows in the kernel picker from the new notebook.
The  .venv is still available when switching from the new notebook to the already existing notebook.

https://user-images.githubusercontent.com/44469195/205506149-b2c639fb-8643-4790-a473-f55116df93a5.mov

### VS Code Version

Version: 1.73.1

### Jupyter Extension Version

v2022.9.1303220346

### Jupyter logs

```shell
Visual Studio Code (1.73.1, undefined, desktop)
Jupyter Extension Version: 2022.9.1303220346.
Python Extension Version: 2022.18.2.
Workspace folder /Users/jan-hendrik/projects/jupyter-capture-output
error 22:53:46.994: Exception while attempting zmq : [Error: No native build was found for platform=darwin arch=arm64 runtime=electron abi=106 uv=1 armv=8 libc=glibc node=16.14.2 electron=19.0.17
    loaded from: /Users/jan-hendrik/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/node_modules/zeromq

	at load.path (/Users/jan-hendrik/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/node_modules/node-gyp-build/index.js:1:3163)
	at load (/Users/jan-hendrik/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/node_modules/node-gyp-build/index.js:1:648)
	at Object.<anonymous> (/Users/jan-hendrik/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/node_modules/zeromq/lib/native.js:1:198)
	at u._compile (/Applications/Visual Studio.app/Contents/Resources/app/out/vs/loader.js:4:1313)
	at Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at c._load (node:electron/js2c/asar_bundle:5:13343)
	at a._load (/Applications/Visual Studio.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:14563)
	at v._load (/Applications/Visual Studio.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:113:64900)
	at w._load (/Applications/Visual Studio.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:113:64268)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at p (/Applications/Visual Studio.app/Contents/Resources/app/out/vs/loader.js:4:699)
	at Object.<anonymous> (/Users/jan-hendrik/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/node_modules/zeromq/lib/index.js:1:144)
	at u._compile (/Applications/Visual Studio.app/Contents/Resources/app/out/vs/loader.js:4:1313)
	at Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at c._load (node:electron/js2c/asar_bundle:5:13343)
	at a._load (/Applications/Visual Studio.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:14563)
	at v._load (/Applications/Visual Studio.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:113:64900)
	at w._load (/Applications/Visual Studio.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:113:64268)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at p (/Applications/Visual Studio.app/Contents/Resources/app/out/vs/loader.js:4:699)
	at 92747 (/Users/jan-hendrik/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:17:593435)
	at __webpack_require__ (/Users/jan-hendrik/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:17:1481375)
	at l.zmqSupported (/Users/jan-hendrik/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2221028)
	at l.isSupportedForLocalLaunch (/Users/jan-hendrik/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2220771)
	at get isSupported [as isSupported] (/Users/jan-hendrik/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2220681)
	at t.registerTypes (/Users/jan-hendrik/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2235774)
	at /Users/jan-hendrik/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:1640908
	at /Users/jan-hendrik/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:1641663
	at /Users/jan-hendrik/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:1641671
	at t.activate (/Users/jan-hendrik/.vscode/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:1641793)
	at On._callActivateOptional (/Applications/Visual Studio.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:17678)
	at On._callActivate (/Applications/Visual Studio.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:17338)
	at /Applications/Visual Studio.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:15133
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async w._activate (/Applications/Visual Studio.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:8304)
	at async w._waitForDepsThenActivate (/Applications/Visual Studio.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:8246)
	at async w._initialize (/Applications/Visual Studio.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:7610)]
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 22:53:47.191: Old kernelSpecs (created by Jupyter Extension) stored in directory /Users/jan-hendrik/Library/Jupyter/kernels/__old_vscode_kernelspecs
info 22:53:47.193: LSP Notebooks experiment is disabled -- not in treatment group
info 22:53:47.289: Got env vars ourselves faster /Users/jan-hendrik/projects/jupyter-capture-output/.venv/bin/python with env var count 42 in 81ms
info 22:53:47.291: Process Execution: > ~/projects/jupyter-capture-output/.venv/bin/python -m pip list
> ~/projects/jupyter-capture-output/.venv/bin/python -m pip list
info 22:53:47.898: Got env vars ourselves faster /Users/jan-hendrik/opt/anaconda3/envs/napari-env/bin/python with env var count 44 in 675ms
info 22:53:47.898: Got env vars ourselves faster /Users/jan-hendrik/opt/anaconda3/envs/napari-env/bin/python with env var count 44 in 674ms
info 22:53:47.902: Process Execution: > ~/opt/anaconda3/envs/napari-env/bin/python -c "import jupyter"
> ~/opt/anaconda3/envs/napari-env/bin/python -c "import jupyter"
info 22:53:47.904: Process Execution: > ~/opt/anaconda3/envs/napari-env/bin/python -c "import notebook"
> ~/opt/anaconda3/envs/napari-env/bin/python -c "import notebook"
info 22:53:48.035: Preferred Remote kernel for /Users/jan-hendrik/projects/jupyter-capture-output/cap_example_notebook.ipynb is undefined
info 22:53:48.035: Find preferred kernel for /Users/jan-hendrik/projects/jupyter-capture-output/cap_example_notebook.ipynb with metadata {"kernelspec":{"display_name":"Python 3.10.8 ('.venv': poetry)","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.10.8"},"vscode":{"interpreter":{"hash":"c0ecd88a104f88ac7ba030faad3447e6f9cb751f1846846a28271507b5fa719a"}}} & preferred interpreter /Users/jan-hendrik/projects/jupyter-capture-output/.venv/bin/python
info 22:53:48.039: Preferred Remote kernel for /Users/jan-hendrik/projects/jupyter-capture-output/cap_example_notebook.ipynb is undefined
info 22:53:48.039: Preferred kernel .jvsc74a57bd0c0ecd88a104f88ac7ba030faad3447e6f9cb751f1846846a28271507b5fa719a./Users/jan-hendrik/projects/jupyter-capture-output/.venv/python./Users/jan-hendrik/projects/jupyter-capture-output/.venv/python.-m#ipykernel_launcher is exact match or top match for non python kernels, (false, [object Object], true, false)
info 22:53:48.039: PreferredConnection: .jvsc74a57bd0c0ecd88a104f88ac7ba030faad3447e6f9cb751f1846846a28271507b5fa719a./Users/jan-hendrik/projects/jupyter-capture-output/.venv/python./Users/jan-hendrik/projects/jupyter-capture-output/.venv/python.-m#ipykernel_launcher found for NotebookDocument: /Users/jan-hendrik/projects/jupyter-capture-output/cap_example_notebook.ipynb
info 22:53:48.148: Got env vars ourselves faster /Users/jan-hendrik/opt/anaconda3/envs/napari-env/bin/python with env var count 44 in 1ms
info 22:53:48.154: Process Execution: > ~/opt/anaconda3/envs/napari-env/bin/python -m jupyter kernelspec --version
> ~/opt/anaconda3/envs/napari-env/bin/python -m jupyter kernelspec --version
info 22:53:48.155: Got env vars with python /Users/jan-hendrik/projects/jupyter-capture-output/.venv/bin/python, with env var count 42 and custom env var count 0 in 947ms
info 22:53:48.263: Preferred Remote kernel for /Users/jan-hendrik/projects/jupyter-capture-output/cap_example_notebook.ipynb is undefined
info 22:53:48.671: Got env vars ourselves faster /Users/jan-hendrik/opt/anaconda3/envs/napari-env/bin/python with env var count 44 in 0ms
info 22:53:48.671: Got env vars ourselves faster /Users/jan-hendrik/opt/anaconda3/envs/napari-env/bin/python with env var count 44 in 0ms
info 22:53:48.774: Got env vars with python /Users/jan-hendrik/opt/anaconda3/envs/napari-env/bin/python, with env var count 44 and custom env var count 0 in 1550ms
info 22:53:48.803: Got env vars with python /Users/jan-hendrik/opt/anaconda3/envs/napari-env/bin/python, with env var count 44 and custom env var count 0 in 1579ms
info 22:53:49.026: Got env vars with python /Users/jan-hendrik/opt/anaconda3/envs/napari-env/bin/python, with env var count 44 and custom env var count 0 in 879ms
info 22:53:49.400: Got env vars with python /Users/jan-hendrik/opt/anaconda3/envs/napari-env/bin/python, with env var count 44 and custom env var count 0 in 729ms
info 22:53:49.400: Got env vars with python /Users/jan-hendrik/opt/anaconda3/envs/napari-env/bin/python, with env var count 44 and custom env var count 0 in 729ms
```
```


### Coding Language and Runtime Version

_No response_

### Language Extension Version (if applicable)

_No response_

### Anaconda Version (if applicable)

_No response_

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, and sorry you are running into this bug
I believe this has been resolved in the latest pre-release version of the jupyter extension
Please could you install vsocde insiders and the pre-release version of the Jupyter and Python extnesions and confirm this issue has been fixed.

I'm going to close this as i believe this has been resolved.
If the problem still persists even after testing (as described above), please feel free to re-open this issue or create a new one

**Comment by kolibril13** [comment]
That is great to hear!
As the next VS Code release is just a few days ahead, I'll test it as soon as the new version is out.

**Comment by DonJayamanne** [comment]
Please remember 

> If the problem still persists even after testing (as described above), please feel free to re-open this issue or create a new one

Basically I want to ensure this is fixed and you are unblocked.
