### ISSUE TITLE
Autocomplete doesn't work when the notebook is in a hidden directory.

### ISSUE THREAD

**Issue by qiaomo** [microsoft/vscode-jupyter#12351]
## Environment data

-   VS Code version: 1.74.0 (Universal)
-   Jupyter Extension version: v2022.11.1003412109
-   Python Extension version: v2022.20.0
-   OS and version: macOS Ventura 13.0.1
-   Python version: 3.9.6
-   Type of virtual environment used: N/A
-   Jupyter server running: Local and RemoteSSH

## Expected behaviour

Autocomplete works fine in hidden directory.

## Actual behaviour

Autocomplete doesn't work when the notebook is in a hidden directory.

#### in the normal directory (./test/t.ipynb)
![图片](https://user-images.githubusercontent.com/14953431/206373706-b85eb61d-5b43-43c4-a99d-f4910f756248.png)

#### in the hidden directory (./.test/t.ipynb)
![图片](https://user-images.githubusercontent.com/14953431/206374000-35d9ca64-4082-4748-a352-1ec0db794136.png)

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Visual Studio Code (1.74.0, undefined, desktop)
Jupyter Extension Version: 2022.11.1003412109.
Python Extension Version: 2022.20.0.
Workspace folder /Users/hawberr/Projects/aitest/juypter
warn 14:35:51.901: Exception while attempting zmq : Error: No native build was found for platform=darwin arch=arm64 runtime=electron abi=106 uv=1 armv=8 libc=glibc node=16.14.2 electron=19.1.8
    loaded from: /Users/hawberr/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/node_modules/zeromq

    at Function.load.path (/Users/hawberr/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/node_modules/node-gyp-build/index.js:1:3163)
    at load (/Users/hawberr/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/node_modules/node-gyp-build/index.js:1:648)
    at Object.<anonymous> (/Users/hawberr/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/node_modules/zeromq/lib/native.js:1:198)
    at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1313)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.r._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:120:13379)
    at Function.w._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:61900)
    at Function.v._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:61293)
    at Module.require (node:internal/modules/cjs/loader:1059:19)
    at p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:699)
    at Object.<anonymous> (/Users/hawberr/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/node_modules/zeromq/lib/index.js:1:144)
    at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1313)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.r._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:120:13379)
    at Function.w._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:61900)
    at Function.v._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:61293)
    at Module.require (node:internal/modules/cjs/loader:1059:19)
    at p (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:699)
    at Object.92747 (/Users/hawberr/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:17:442832)
    at __webpack_require__ (/Users/hawberr/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:17:1241219)
    at c.zmqSupported (/Users/hawberr/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:2187160)
    at c.isSupportedForLocalLaunch (/Users/hawberr/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:2186903)
    at c.get isSupported [as isSupported] (/Users/hawberr/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:2186813)
    at t.registerTypes (/Users/hawberr/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:2202584)
    at /Users/hawberr/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:1576202
    at /Users/hawberr/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:1576861
    at /Users/hawberr/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:1576869
    at t.activate (/Users/hawberr/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:1576991)
    at Function.db (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:15127)
    at Function.cb (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:14825)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:12823
    at v.n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:92:7006)
    at v.m (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:92:6969)
    at v.l (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:92:6426)
用户属于试验组 "jupyterTestcf"
用户属于试验组 "jupyterEnhancedDataViewer"
info 14:35:52.073: LSP Notebooks experiment is enabled
info 14:35:52.270: Attempting to start a server because of preload conditions ...
info 14:35:52.271: Checking for server existence.
info 14:35:52.271: Checking for server usability.
info 14:35:52.337: Find preferred kernel for /Users/hawberr/Projects/aitest/juypter/.test/t.ipynb with metadata {"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"name":"python","version":"3.9.6 (default, Sep 26 2022, 11:37:49) \n[Clang 14.0.0 (clang-1400.0.29.202)]"},"orig_nbformat":4,"vscode":{"interpreter":{"hash":"31f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6"}}} & preferred interpreter /usr/bin/python3
info 14:35:52.337: Find preferred kernel for /Users/hawberr/Projects/aitest/juypter/.test/t.ipynb with metadata {"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"name":"python","version":"3.9.6 (default, Sep 26 2022, 11:37:49) \n[Clang 14.0.0 (clang-1400.0.29.202)]"},"orig_nbformat":4,"vscode":{"interpreter":{"hash":"31f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6"}}} & preferred interpreter /usr/bin/python3
info 14:35:52.338: Find preferred kernel for /Users/hawberr/Projects/aitest/juypter/test/t.ipynb with metadata {"language_info":{"name":"python"},"orig_nbformat":4} & preferred interpreter /usr/bin/python3
info 14:35:52.339: Find preferred kernel for /Users/hawberr/Projects/aitest/juypter/test/t.ipynb with metadata {"language_info":{"name":"python"},"orig_nbformat":4} & preferred interpreter /usr/bin/python3
info 14:35:52.348: Find preferred kernel for /Users/hawberr/Projects/aitest/juypter/.test/t.ipynb with metadata {"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"name":"python","version":"3.9.6 (default, Sep 26 2022, 11:37:49) \n[Clang 14.0.0 (clang-1400.0.29.202)]"},"orig_nbformat":4,"vscode":{"interpreter":{"hash":"31f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6"}}} & preferred interpreter /usr/bin/python3
info 14:35:52.348: Find preferred kernel for /Users/hawberr/Projects/aitest/juypter/test/t.ipynb with metadata {"language_info":{"name":"python"},"orig_nbformat":4} & preferred interpreter /usr/bin/python3
info 14:35:52.349: Preferred kernel .jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6./usr/bin/python3./usr/bin/python3.-m#ipykernel_launcher is exact match or top match for non python kernels, (true, [object Object], true, false)
info 14:35:52.349: PreferredConnection: .jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6./usr/bin/python3./usr/bin/python3.-m#ipykernel_launcher found for NotebookDocument: /Users/hawberr/Projects/aitest/juypter/.test/t.ipynb
info 14:35:52.351: Find preferred kernel for /Users/hawberr/Projects/aitest/juypter/.test/t.ipynb with metadata {"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"name":"python","version":"3.9.6 (default, Sep 26 2022, 11:37:49) \n[Clang 14.0.0 (clang-1400.0.29.202)]"},"orig_nbformat":4,"vscode":{"interpreter":{"hash":"31f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6"}}} & preferred interpreter /usr/bin/python3
info 14:35:52.351: Find preferred kernel for /Users/hawberr/Projects/aitest/juypter/test/t.ipynb with metadata {"language_info":{"name":"python"},"orig_nbformat":4} & preferred interpreter /usr/bin/python3
info 14:35:52.354: Preferred kernel .jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6./usr/bin/python3./usr/bin/python3.-m#ipykernel_launcher is exact match or top match for non python kernels, (false, [object Object], true, false)
info 14:35:52.355: PreferredConnection: .jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6./usr/bin/python3./usr/bin/python3.-m#ipykernel_launcher found for NotebookDocument: /Users/hawberr/Projects/aitest/juypter/.test/t.ipynb
info 14:35:52.467: Preferred kernel .jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6./usr/bin/python3./usr/bin/python3.-m#ipykernel_launcher is exact match or top match for non python kernels, (false, [object Object], false, false)
info 14:35:52.467: PreferredConnection: .jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6./usr/bin/python3./usr/bin/python3.-m#ipykernel_launcher found for NotebookDocument: /Users/hawberr/Projects/aitest/juypter/test/t.ipynb
info 14:35:52.474: Got empty env vars with python /usr/bin/python3 in 134ms
info 14:35:52.477: Got empty env vars with python /usr/bin/python3 in 138ms
info 14:35:52.478: Process Execution: > /usr/bin/python3 -c "import jupyter"
> /usr/bin/python3 -c "import jupyter"
info 14:35:52.479: Process Execution: > /usr/bin/python3 -c "import notebook"
> /usr/bin/python3 -c "import notebook"
info 14:35:52.479: Process Execution: > /usr/bin/python3 -m pip list
> /usr/bin/python3 -m pip list
info 14:35:52.480: Got empty env vars with python /usr/bin/python3 in 138ms
info 14:35:52.573: Process Execution: > /usr/bin/python3 -m jupyter kernelspec --version
> /usr/bin/python3 -m jupyter kernelspec --version
info 14:35:52.576: Got empty env vars with python /usr/bin/python3 in 4ms
info 14:35:52.749: Starting notebook server.
info 14:35:52.750: Connecting to server
info 14:35:52.750: Launching server
info 14:35:52.750: Starting Notebook
info 14:35:52.754: Got empty env vars with python /usr/bin/python3 in 5ms
info 14:35:52.755: Generating custom default config at /var/folders/9h/242ymx2d0yl2m56x_wbbpjkw0000gn/T/ec35dab8-37d6-42e6-8fac-43a0aa233151/jupyter_notebook_config.py
info 14:35:52.755: Starting Jupyter Notebook
从 /usr/bin/python3 启动 Jupyter
info 14:35:52.755: Creating daemon pool for /usr/bin/python3 with env variables count 48
info 14:35:52.756: Process Execution: > /usr/bin/python3 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 18978
> /usr/bin/python3 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 18978
info 14:35:52.757: Process Execution: > /usr/bin/python3 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 18978
> /usr/bin/python3 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 18978
info 14:35:52.757: Process Execution: > /usr/bin/python3 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 18978
> /usr/bin/python3 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 18978
info 14:35:52.758: Got empty env vars with python /usr/bin/python3 in 9ms
info 14:35:52.766: Got empty env vars with python /usr/bin/python3 in 11ms
info 14:35:52.770: Got empty env vars with python /usr/bin/python3 in 15ms
info 14:35:52.842: Process Execution: > /usr/bin/python3 (daemon) -m jupyter notebook --no-browser --notebook-dir="/Users/hawberr/Projects/aitest/juypter" --config=/var/folders/9h/242ymx2d0yl2m56x_wbbpjkw0000gn/T/ec35dab8-37d6-42e6-8fac-43a0aa233151/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
> /usr/bin/python3 (daemon) -m jupyter notebook --no-browser --notebook-dir="/Users/hawberr/Projects/aitest/juypter" --config=/var/folders/9h/242ymx2d0yl2m56x_wbbpjkw0000gn/T/ec35dab8-37d6-42e6-8fac-43a0aa233151/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
info 14:35:52.842: Waiting for Jupyter Notebook
info 14:35:52.846: Got empty env vars with python /usr/bin/python3 in 5ms
/Users/hawberr/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/hawberr/Projects/aitest/juypter' instead of '"/Users/hawberr/Projects/aitest/juypter"' if you require traitlets >=5.
  warn(
info 14:35:53.001: /Users/hawberr/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/hawberr/Projects/aitest/juypter' instead of '"/Users/hawberr/Projects/aitest/juypter"' if you require traitlets >=5.
  warn(

[I 14:35:53.149 NotebookApp] Serving notebooks from local directory: /Users/hawberr/Projects/aitest/juypter
info 14:35:53.155: /Users/hawberr/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/hawberr/Projects/aitest/juypter' instead of '"/Users/hawberr/Projects/aitest/juypter"' if you require traitlets >=5.
  warn(
[I 14:35:53.149 NotebookApp] Serving notebooks from local directory: /Users/hawberr/Projects/aitest/juypter

[I 14:35:53.150 NotebookApp] Jupyter Notebook 6.5.2 is running at:
info 14:35:53.156: /Users/hawberr/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/hawberr/Projects/aitest/juypter' instead of '"/Users/hawberr/Projects/aitest/juypter"' if you require traitlets >=5.
  warn(
[I 14:35:53.149 NotebookApp] Serving notebooks from local directory: /Users/hawberr/Projects/aitest/juypter
[I 14:35:53.150 NotebookApp] Jupyter Notebook 6.5.2 is running at:

[I 14:35:53.150 NotebookApp] http://localhost:8888/?token=43b310bc66b891649c811e41a47bac52832447632da626af
info 14:35:53.157: /Users/hawberr/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/hawberr/Projects/aitest/juypter' instead of '"/Users/hawberr/Projects/aitest/juypter"' if you require traitlets >=5.
  warn(
[I 14:35:53.149 NotebookApp] Serving notebooks from local directory: /Users/hawberr/Projects/aitest/juypter
[I 14:35:53.150 NotebookApp] Jupyter Notebook 6.5.2 is running at:
[I 14:35:53.150 NotebookApp] http://localhost:8888/?token=43b310bc66b891649c811e41a47bac52832447632da626af

info 14:35:53.157: Process Execution: > /usr/bin/python3 (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> /usr/bin/python3 (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/getServerInfo.py
[I 14:35:53.150 NotebookApp]  or http://127.0.0.1:8888/?token=43b310bc66b891649c811e41a47bac52832447632da626af
info 14:35:53.159: /Users/hawberr/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/hawberr/Projects/aitest/juypter' instead of '"/Users/hawberr/Projects/aitest/juypter"' if you require traitlets >=5.
  warn(
[I 14:35:53.149 NotebookApp] Serving notebooks from local directory: /Users/hawberr/Projects/aitest/juypter
[I 14:35:53.150 NotebookApp] Jupyter Notebook 6.5.2 is running at:
[I 14:35:53.150 NotebookApp] http://localhost:8888/?token=43b310bc66b891649c811e41a47bac52832447632da626af
[I 14:35:53.150 NotebookApp]  or http://127.0.0.1:8888/?token=43b310bc66b891649c811e41a47bac52832447632da626af

info 14:35:53.163: Process Execution: > /usr/bin/python3 (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> /usr/bin/python3 (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/getServerInfo.py
[I 14:35:53.150 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
info 14:35:53.165: /Users/hawberr/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/hawberr/Projects/aitest/juypter' instead of '"/Users/hawberr/Projects/aitest/juypter"' if you require traitlets >=5.
  warn(
[I 14:35:53.149 NotebookApp] Serving notebooks from local directory: /Users/hawberr/Projects/aitest/juypter
[I 14:35:53.150 NotebookApp] Jupyter Notebook 6.5.2 is running at:
[I 14:35:53.150 NotebookApp] http://localhost:8888/?token=43b310bc66b891649c811e41a47bac52832447632da626af
[I 14:35:53.150 NotebookApp]  or http://127.0.0.1:8888/?token=43b310bc66b891649c811e41a47bac52832447632da626af
[I 14:35:53.150 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

info 14:35:53.169: Got empty env vars with python /usr/bin/python3 in 12ms
[C 14:35:53.154 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/hawberr/Library/Jupyter/runtime/nbserver-19015-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=43b310bc66b891649c811e41a47bac52832447632da626af
     or http://127.0.0.1:8888/?token=43b310bc66b891649c811e41a47bac52832447632da626af
info 14:35:53.169: /Users/hawberr/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/hawberr/Projects/aitest/juypter' instead of '"/Users/hawberr/Projects/aitest/juypter"' if you require traitlets >=5.
  warn(
[I 14:35:53.149 NotebookApp] Serving notebooks from local directory: /Users/hawberr/Projects/aitest/juypter
[I 14:35:53.150 NotebookApp] Jupyter Notebook 6.5.2 is running at:
[I 14:35:53.150 NotebookApp] http://localhost:8888/?token=43b310bc66b891649c811e41a47bac52832447632da626af
[I 14:35:53.150 NotebookApp]  or http://127.0.0.1:8888/?token=43b310bc66b891649c811e41a47bac52832447632da626af
[I 14:35:53.150 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 14:35:53.154 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/hawberr/Library/Jupyter/runtime/nbserver-19015-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=43b310bc66b891649c811e41a47bac52832447632da626af
     or http://127.0.0.1:8888/?token=43b310bc66b891649c811e41a47bac52832447632da626af

info 14:35:53.179: Got empty env vars with python /usr/bin/python3 in 19ms
info 14:35:53.193: Got empty env vars with python /usr/bin/python3 in 28ms
info 14:35:53.202: Got empty env vars with python /usr/bin/python3 in 33ms
info 14:35:53.253: Got empty env vars with python /usr/bin/python3 in 3ms
info 14:35:53.309: Connecting to process server
info 14:35:53.309: Connecting server kernel http://localhost:8888/
info 14:35:53.309: Creating server with url : http://localhost:8888/
info 14:35:53.311: Connection complete server
info 14:35:53.311: Server started.
info 14:35:53.323: Process Execution: > /usr/bin/python3 (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> /usr/bin/python3 (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/getServerInfo.py
info 14:35:53.323: Process Execution: > /usr/bin/python3 (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> /usr/bin/python3 (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/getServerInfo.py
error 14:36:08.234: Live Notebook not available for /Users/hawberr/Projects/aitest/juypter/.test/t.ipynb
error 14:36:08.402: Live Notebook not available for /Users/hawberr/Projects/aitest/juypter/.test/t.ipynb
error 14:36:09.537: Live Notebook not available for /Users/hawberr/Projects/aitest/juypter/.test/t.ipynb
error 14:36:09.753: Live Notebook not available for /Users/hawberr/Projects/aitest/juypter/.test/t.ipynb
error 14:36:20.152: Live Notebook not available for /Users/hawberr/Projects/aitest/juypter/test/t.ipynb
error 14:36:25.139: Live Notebook not available for /Users/hawberr/Projects/aitest/juypter/test/t.ipynb
error 14:36:25.312: Live Notebook not available for /Users/hawberr/Projects/aitest/juypter/test/t.ipynb
error 14:36:26.052: Live Notebook not available for /Users/hawberr/Projects/aitest/juypter/test/t.ipynb
```

</p>
</details>

**Comment by DonJayamanne** [comment]
Its been almost a year since this issue was created and we haven't had any similar reports
Closing this issue as stale.
