### ISSUE TITLE
"from numpy.typing import NDArray" prevents variables from loading in variables view

### ISSUE THREAD

**Issue by walker2041** [microsoft/vscode-jupyter#12375]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Any time NDArray from the numpy.typing module is present in a jupyter notebook project, it prevents any of the variables from loading in the variable view window, indefinitely. This does not occur with other types from the same module, such as ArrayLike.

PROBLEM: After importing NDArray (**VARIABLES NOT LOADING**):
![image](https://user-images.githubusercontent.com/91851972/206787498-e0dfad73-3f7d-40d0-a855-39172f9b5687.png)

Before importing NDArray:
![image](https://user-images.githubusercontent.com/91851972/206787457-30f97d1b-3c7f-4c2e-8097-17e7ea7f5723.png)

After importing and then deleting NDArray with the del command, all variables load instantly as expected:
![image](https://user-images.githubusercontent.com/91851972/206787576-ffcb0b67-1431-44bf-9307-1615d6eecb0d.png)

The same problem does not occur with "ArrayLike" from the same module:
![image](https://user-images.githubusercontent.com/91851972/206787881-f52d33d8-462c-4665-b45c-8db004cb430f.png)

### VS Code Version

Version: 1.74.0 (user setup) Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91 Date: 2022-12-05T16:38:16.075Z Electron: 19.1.8 Chromium: 102.0.5005.167 Node.js: 16.14.2 V8: 10.2.154.15-electron.0 OS: Windows_NT x64 10.0.19044 Sandboxed: No

### Jupyter Extension Version

v2022.11.1003412109

### Jupyter logs

```shell
Visual Studio Code (1.74.0, undefined, desktop)
Jupyter Extension Version: 2022.11.1003412109.
Python Extension Version: 2022.20.0.
Workspace folder c:\python_dev\tinkering
info 15:11:19.467: ZMQ install verified.
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 15:11:20.342: LSP Notebooks experiment is enabled
info 15:11:22.079: Find preferred kernel for c:\python_dev\tinkering\tkinter_wireframes\projection.ipynb with metadata {"kernelspec":{"display_name":"Python 3.10.8 64-bit","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.10.8"},"orig_nbformat":4,"vscode":{"interpreter":{"hash":"5710389c97d25e658141aa9aea3719821c2f3fe528dbcdf64aee5c75cf47b0a1"}}} & preferred interpreter c:\python_dev\.venv\Scripts\python.exe
info 15:11:22.081: Find preferred kernel for c:\python_dev\tinkering\tkinter_wireframes\projection.ipynb with metadata {"kernelspec":{"display_name":"Python 3.10.8 64-bit","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.10.8"},"orig_nbformat":4,"vscode":{"interpreter":{"hash":"5710389c97d25e658141aa9aea3719821c2f3fe528dbcdf64aee5c75cf47b0a1"}}} & preferred interpreter c:\python_dev\.venv\Scripts\python.exe
info 15:11:22.091: Find preferred kernel for c:\python_dev\tinkering\tkinter_wireframes\projection.ipynb with metadata {"kernelspec":{"display_name":"Python 3.10.8 64-bit","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.10.8"},"orig_nbformat":4,"vscode":{"interpreter":{"hash":"5710389c97d25e658141aa9aea3719821c2f3fe528dbcdf64aee5c75cf47b0a1"}}} & preferred interpreter c:\python_dev\.venv\Scripts\python.exe
info 15:11:22.578: Process Execution: > c:\python_dev\.venv\Scripts\python.exe -m pip list
> c:\python_dev\.venv\Scripts\python.exe -m pip list
info 15:11:23.151: Got env vars with python c:\python_dev\.venv\Scripts\python.exe, with env var count 61 and custom env var count 54 in 1072ms
info 15:11:23.764: Preferred kernel .jvsc74a57bd0dd08567add178c037b5a25e5042a6e91670212a9e0d84cafb374bfd29a8a216f.c:\python_dev\.venv\Scripts\python.exe.c:\python_dev\.venv\Scripts\python.exe.-m#ipykernel_launcher is exact match or top match for non python kernels, (true, [object Object], false, false)
info 15:11:23.769: PreferredConnection: .jvsc74a57bd0dd08567add178c037b5a25e5042a6e91670212a9e0d84cafb374bfd29a8a216f.c:\python_dev\.venv\Scripts\python.exe.c:\python_dev\.venv\Scripts\python.exe.-m#ipykernel_launcher found for NotebookDocument: c:\python_dev\tinkering\tkinter_wireframes\projection.ipynb
info 15:11:23.887: Find preferred kernel for c:\python_dev\tinkering\tkinter_wireframes\projection.ipynb with metadata {"kernelspec":{"display_name":"Python 3.10.8 64-bit","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.10.8"},"orig_nbformat":4,"vscode":{"interpreter":{"hash":"5710389c97d25e658141aa9aea3719821c2f3fe528dbcdf64aee5c75cf47b0a1"}}} & preferred interpreter c:\python_dev\.venv\Scripts\python.exe
info 15:11:23.890: Preferred kernel .jvsc74a57bd05710389c97d25e658141aa9aea3719821c2f3fe528dbcdf64aee5c75cf47b0a1.c:\Users\pcwal\AppData\Local\Programs\Python\Python310\python.exe.c:\Users\pcwal\AppData\Local\Programs\Python\Python310\python.exe.-m#ipykernel_launcher is exact match or top match for non python kernels, (false, undefined, true, false)
info 15:11:23.896: PreferredConnection: .jvsc74a57bd05710389c97d25e658141aa9aea3719821c2f3fe528dbcdf64aee5c75cf47b0a1.c:\Users\pcwal\AppData\Local\Programs\Python\Python310\python.exe.c:\Users\pcwal\AppData\Local\Programs\Python\Python310\python.exe.-m#ipykernel_launcher found for NotebookDocument: c:\python_dev\tinkering\tkinter_wireframes\projection.ipynb
info 15:11:24.028: Loading webview. View is notset
info 15:11:24.033: Loading web view...
info 15:11:24.035: Webview panel created.
info 15:11:24.207: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd05710389c97d25e658141aa9aea3719821c2f3fe528dbcdf64aee5c75cf47b0a1.c:\Users\pcwal\AppData\Local\Programs\Python\Python310\python.exe.c:\Users\pcwal\AppData\Local\Programs\Python\Python310\python.exe.-m#ipykernel_launcher (Python Path: , EnvType: Unknown, EnvName: '', Version: 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]) for 'c:\python_dev\tinkering\tkinter_wireframes\projection.ipynb' (disableUI=true)
info 15:11:24.208: Computing working directory for resource 'c:\python_dev\tinkering\tkinter_wireframes\projection.ipynb'
info 15:11:24.591: Got empty env vars with python c:\Users\pcwal\AppData\Local\Programs\Python\Python310\python.exe in 641ms
info 15:11:24.603: Process Execution: > ~\AppData\Local\Programs\Python\Python310\python.exe -m pip list
> ~\AppData\Local\Programs\Python\Python310\python.exe -m pip list
info 15:11:24.614: Process Execution: > ~\AppData\Local\Programs\Python\Python310\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> ~\AppData\Local\Programs\Python\Python310\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
info 15:11:24.633: Process Execution: > ~\AppData\Local\Programs\Python\Python310\python.exe ~\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003412109\pythonFiles\vscode_datascience_helpers\kernel_interrupt_daemon.py --ppid 3308
> ~\AppData\Local\Programs\Python\Python310\python.exe ~\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003412109\pythonFiles\vscode_datascience_helpers\kernel_interrupt_daemon.py --ppid 3308
info 15:11:24.633: Process Execution: cwd: ~\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003412109\pythonFiles\vscode_datascience_helpers
cwd: ~\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003412109\pythonFiles\vscode_datascience_helpers
info 15:11:24.783: Got empty env vars with python c:\Users\pcwal\AppData\Local\Programs\Python\Python310\python.exe in 538ms
info 15:11:24.805: Got empty env vars with python c:\Users\pcwal\AppData\Local\Programs\Python\Python310\python.exe in 289ms
info 15:11:24.805: Got empty env vars with python c:\Users\pcwal\AppData\Local\Programs\Python\Python310\python.exe in 288ms
info 15:11:24.856: Web view react rendered
info 15:11:25.074: Got empty env vars with python c:\Users\pcwal\AppData\Local\Programs\Python\Python310\python.exe in 454ms
info 15:11:25.393: Process Execution: > ~\AppData\Local\Programs\Python\Python310\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"54e44b5e-352e-404c-8d16-16a1b094a3f2" --shell=9002 --transport="tcp" --iopub=9004 --f=c:\Users\pcwal\AppData\Roaming\jupyter\runtime\kernel-v2-330876p94P4BtOVm.json
> ~\AppData\Local\Programs\Python\Python310\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"54e44b5e-352e-404c-8d16-16a1b094a3f2" --shell=9002 --transport="tcp" --iopub=9004 --f=c:\Users\pcwal\AppData\Roaming\jupyter\runtime\kernel-v2-330876p94P4BtOVm.json
info 15:11:25.393: Process Execution: cwd: c:\python_dev\tinkering\tkinter_wireframes
cwd: c:\python_dev\tinkering\tkinter_wireframes
info 15:11:26.097: ipykernel version & path 6.16.0, ~\AppData\Roaming\Python\Python310\site-packages\ipykernel\__init__.py for c:\Users\pcwal\AppData\Local\Programs\Python\Python310\python.exe
info 15:11:28.905: Kernel Output: To connect another client to this kernel, use: --existing c:\Users\pcwal\AppData\Roaming\jupyter\runtime\kernel-v2-330876p94P4BtOVm.json

info 15:11:29.042: Started Kernel Python 3.10.8 (pid: 16676)
info 15:11:29.047: UpdateWorkingDirectoryAndPath in Kernel
info 15:11:29.120: Process Execution: > ~\AppData\Local\Programs\Python\Python310\python.exe ~\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003412109\pythonFiles\printJupyterDataDir.py
> ~\AppData\Local\Programs\Python\Python310\python.exe ~\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003412109\pythonFiles\printJupyterDataDir.py
info 15:11:29.222: Got empty env vars with python c:\Users\pcwal\AppData\Local\Programs\Python\Python310\python.exe in 111ms
warn 15:11:58.198: StdErr from Kernel Process [IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "C:\Users\pcwal\AppData\Roaming\Python\Python310\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "C:\Users\pcwal\AppData\Roaming\Python\Python310\site-packages\ipykernel\kernelbase.py", line 797, in inspect_request
    reply_content = self.do_inspect(
  File "C:\Users\pcwal\AppData\Roaming\Python\Python310\site-packages\ipykernel\ipkernel.py", line 517, in do_inspect
    bundle = self.shell.object_inspect_mime(
  File "C:\Users\pcwal\AppData\Roaming\Python\Python310\site-packages\IPython\core\interactiveshell.py", line 1732, in object_inspect_mime
    return self.inspector._get_info(
  File "C:\Users\pcwal\AppData\Roaming\Python\Python310\site-packages\IPython\core\oinspect.py", line 591, in _get_info
    info = self.info(obj, oname=oname, info=info, detail_level=detail_level)
  File "C:\Users\pcwal\AppData\Roaming\Python\Python310\site-packages\IPython\core\oinspect.py", line 874, in info
    names = [sub.__name__ for sub in type.__subclasses__(obj)]
TypeError: descriptor '__subclasses__' for 'type' objects doesn't apply to a 'types.GenericAlias' object

warn 15:11:59.932: StdErr from Kernel Process [IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "C:\Users\pcwal\AppData\Roaming\Python\Python310\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "C:\Users\pcwal\AppData\Roaming\Python\Python310\site-packages\ipykernel\kernelbase.py", line 797, in inspect_request
    reply_content = self.do_inspect(
  File "C:\Users\pcwal\AppData\Roaming\Python\Python310\site-packages\ipykernel\ipkernel.py", line 517, in do_inspect
    bundle = self.shell.object_inspect_mime(
  File "C:\Users\pcwal\AppData\Roaming\Python\Python310\site-packages\IPython\core\interactiveshell.py", line 1732, in object_inspect_mime
    return self.inspector._get_info(
  File "C:\Users\pcwal\AppData\Roaming\Python\Python310\site-packages\IPython\core\oinspect.py", line 591, in _get_info
    info = self.info(obj, oname=oname, info=info, detail_level=detail_level)
  File "C:\Users\pcwal\AppData\Roaming\Python\Python310\site-packages\IPython\core\oinspect.py", line 874, in info
    names = [sub.__name__ for sub in type.__subclasses__(obj)]
TypeError: descriptor '__subclasses__' for 'type' objects doesn't apply to a 'types.GenericAlias' object
```

### Coding Language and Runtime Version

Python v3.10.8

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
thanks for the issue.

repro cell:

```
from numpy.typing import NDArray
a = 1
```

then open the variables view

**Comment by amunger** [comment]
works in the built-in variable view, `"notebook.variablesView": true`
