### ISSUE TITLE
Broken LSP tests

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#12503]
```
1) VSCode Intellisense Notebook Diagnostics @lsp
       Add cells and make sure errors show up:

      Error: No diagnostics found for vscode-notebook-cell:/tmp/emptyPythonb54b6b0b-c35c-4ec0-b1d9-1d94a5a02ac1..ipynb#W1sZmlsZQ%3D%3D
      + expected - actual


      at Timeout.<anonymous> (src/test/common.ts:66:20)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)

  2) VSCode Intellisense Notebook Hover @lsp
       Insert cell and get hover text:

      Error: No hovers found for vscode-notebook-cell:/tmp/emptyPython535824fb-a443-440a-a00e-fb17e3aa8959..ipynb#W1sZmlsZQ%3D%3D
      + expected - actual


      at Timeout.<anonymous> (src/test/common.ts:66:20)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)

  3) VSCode semantic token tests @lsp
       Open a notebook and add a bunch of cells:

      TypeError: Cannot read properties of undefined (reading 'startOffset')
      + expected - actual
```

**Comment by DonJayamanne** [comment]
Closing, as these will be removed.
