### ISSUE TITLE
Command `Jupyter: Specify Jupyter Server for Connections` fails

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode-jupyter#12550]
Type: <b>Bug</b>

1. Use VS Code Insiders.
2. Install pre-release version of Jupyter extension.
3. Configure `"notebook.kernelPicker.type": "mru"`
4. Use Command Palette to run `Jupyter: Specify Jupyter Server for Connections`
5. The expected quickpick doesn't appear.
6. Find this in the `Jupyter` channel on the Output tab of Panel:
```
error 20:44:20.216: Failed to select Jupyter Uri, Class name = yo, completed in 3ms, has a falsy return value, Arg 1: "commandPalette", Arg 2: undefined, Return Value: undefined [TypeError: t._createParsedCallSite is not a function
	at /home/irisowner/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.1.2000141019/out/extension.node.js:2:757576
	at Array.map (<anonymous>)
	at Object.t.Qc (/home/irisowner/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.1.2000141019/out/extension.node.js:2:756882)
	at aa.determineExtensionFromCallStack (/home/irisowner/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.1.2000141019/out/extension.node.js:2:2124497)
	at lf.createProvider (/home/irisowner/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.1.2000141019/out/extension.node.js:17:228294)
	at lf.registerProvider (/home/irisowner/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.1.2000141019/out/extension.node.js:17:227209)
	at m_._activateProvider (/home/irisowner/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.1.2000141019/out/extension.node.js:17:806473)
	at e (/home/irisowner/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.1.2000141019/out/extension.node.js:17:806219)
	at /home/irisowner/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.1.2000141019/out/extension.node.js:17:806385
	at invoke (/home/irisowner/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.1.2000141019/out/extension.node.js:2:804389)
	at o.fire (/home/irisowner/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.1.2000141019/out/extension.node.js:2:805154)
	at Ca.set features [as features] (/home/irisowner/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.1.2000141019/out/extension.node.js:2:2132702)
	at Ca._updateFeatures (/home/irisowner/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.1.2000141019/out/extension.node.js:2:2133346)
	at /home/irisowner/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.1.2000141019/out/extension.node.js:2:2133188
	at h.invoke (/vscode/vscode-server-insiders/bin/linux-x64/7ef08adcc620ba1e4fcda7530c8bc907264acae9-insider/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at p.deliver (/vscode/vscode-server-insiders/bin/linux-x64/7ef08adcc620ba1e4fcda7530c8bc907264acae9-insider/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
	at d.fire (/vscode/vscode-server-insiders/bin/linux-x64/7ef08adcc620ba1e4fcda7530c8bc907264acae9-insider/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
	at t.$acceptConfigurationChanged (/vscode/vscode-server-insiders/bin/linux-x64/7ef08adcc620ba1e4fcda7530c8bc907264acae9-insider/out/vs/workbench/api/node/extensionHostProcess.js:107:24469)
	at /vscode/vscode-server-insiders/bin/linux-x64/7ef08adcc620ba1e4fcda7530c8bc907264acae9-insider/out/vs/workbench/api/node/extensionHostProcess.js:107:23953
	at processTicksAndRejections (node:internal/process/task_queues:96:5)]
```

Extension version: 2023.1.2000141019
VS Code version: Code - Insiders 1.75.0-insider (7ef08adcc620ba1e4fcda7530c8bc907264acae9, 2023-01-16T11:28:36.819Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.79.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.79.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.84GB (1.44GB free)|
|Process Argv|--enable-proposed-api intersystems-community.vscode-objectscript --enable-proposed-api georgejames.objectscript-notebooks|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: vscode-iris-jupyter-server devcontainer|
|OS|Linux x64 5.15.79.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|Memory (System)|7.68GB (4.79GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: vscode-iris-jupyter-server devcontainer|
|OS|Linux x64 5.15.79.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|Memory (System)|7.68GB (4.79GB free)|
|VM|0%|
</details>

**Comment by amunger** [comment]
aside from the command failing, it looks like the mru kernel picker also doesn't list an option to connect to a remote server anymore

![image](https://user-images.githubusercontent.com/2019016/212971865-2a455f50-3c92-4dac-8078-b37ab2729c66.png)

**Comment by DonJayamanne** [comment]
Thanks I too can repro this issue (with the powertoys extension installed)

**Comment by DonJayamanne** [comment]
@Tyriar seems to be happening after the changes to bundling of the extension.
Any help would be great here.

**Comment by DonJayamanne** [comment]
Summary:
* Found that the code does not fail in dev
* Code does not fail when bundling using webpack and using development mode
* Fails when using webpack with production mode
* Seems to be an issue with context of the function (`this` inside a function seems to point to something else)
