### ISSUE TITLE
xeus-cling kernel doesn't work in VS Code Jupyter notebook on WSL remote

### ISSUE THREAD

**Issue by ianholst** [microsoft/vscode-jupyter#12653]
Cling (C++ interpreter) and xeus-cling (Jupyter kernel) don't really work on Windows, so I wanted to install them in WSL and then use the VS Code WSL extension to use them in a Jupyter notebook, just like I can with the Python kernel. However, I run into several errors.

- Ubuntu 22.04 running in WSL on Windows 11
- VS Code 1.74.3
- Jupyter Extension v2022.11.1003412109
- Python 3.10.8, conda 23.1.0

## Steps to reproduce:

On WSL Ubuntu:

1. Install miniconda
2. Install jupyter notebook: `conda install notebook`
3. Install xeus-cling: `conda install -c conda-forge xeus-cling` (takes some time)

On Windows:

4. Start VS Code, load a "remote" folder on WSL with the WSL extension
5. Install Jupyter VS Code extension on WSL remote
6. Create a new notebook in VS Code
7. Select the "C++11" kernel
8. Add code to the first cell, like `int a = 1;`
9. Try to change the langage setting for the first cell because it is marked as Python, but C++ is not even an option
10. Select "Auto Detect" for the language, this correctly detects it as C++, but then it doesn't do anything when the cell is run
11. Change the cell language to Python and run it, it starts the correct kernel (`xcpp`) but doesn't seem to connect and times out. The output from the Jupyter console is below.

![error](https://user-images.githubusercontent.com/2507974/214923414-d5e2f92c-fc46-424d-9ce0-f530fa11a992.png)

Interestingly, a few things do work:

- Running `jupyter notebook` from a WSL terminal, connecting to the Jupyter web browser interface in Windows, and creating a new C++ notebook (this shows that `xeus-cling` can work in WSL)
![cppBrowser](https://user-images.githubusercontent.com/2507974/214923443-40692195-76cf-4497-9612-f7f8f8fc3beb.png)

- Running `jupyter notebook` from a WSL terminal, creating a new notebook in VS Code, connnecting to the remote Jupyter server in VS Code (pasting the URI given), and changing the kernel to C++ (this shows that `xeus-cling` can work in VS Code). This is not a bad solution, just less convenient than starting the kernel from VS Code.
![cppRemoteServer](https://user-images.githubusercontent.com/2507974/214923476-a0da05c8-7ed9-4400-8ff7-b00e02da313d.png)

- Starting a Python notebook in a WSL VS Code window (this shows that `ipykernel` works in WSL in VS Code, just not `xeus-cling`)
![pythonWSL](https://user-images.githubusercontent.com/2507974/214923496-a5251229-e1e5-4c5b-a062-4799f672ce0c.png)

So it looks like the only thing that doesn't work is starting the C++ kernel from VS Code while connected to WSL. I haven't tested if this is the case for other non-Python kernels in WSL.

Jupyter output:

```
Visual Studio Code (1.74.3, wsl, desktop)
Jupyter Extension Version: 2022.11.1003412109.
Python Extension not installed.
Workspace folder /home/holst
info 00:17:56.543: ZMQ install verified.
info 00:17:57.396: LSP Notebooks experiment is disabled -- not using Pylance
info 00:17:57.473: Preferred Remote kernel for Untitled-1.ipynb is undefined
info 00:17:57.473: Preferred Remote kernel for Untitled-1.ipynb is undefined
info 00:17:57.507: Preferred Remote kernel for Untitled-1.ipynb is undefined
info 00:17:57.512: Preferred Remote kernel for Untitled-1.ipynb is undefined
info 00:17:57.512: Preferred Remote kernel for Untitled-1.ipynb is undefined
info 00:17:57.513: Find preferred kernel for Untitled-1.ipynb with metadata {"orig_nbformat":4} & preferred interpreter <undefined>
info 00:17:57.526: Preferred Remote kernel for Untitled-1.ipynb is undefined
info 00:17:57.531: Preferred Remote kernel for Untitled-1.ipynb is undefined
info 00:17:57.532: Find preferred kernel for Untitled-1.ipynb with metadata {"orig_nbformat":4} & preferred interpreter <undefined>
info 00:17:57.537: Preferred Remote kernel for Untitled-1.ipynb is undefined
error 00:18:08.648: Live Notebook not available for Untitled-1.ipynb
error 00:18:08.880: Live Notebook not available for Untitled-1.ipynb
error 00:18:09.170: Live Notebook not available for Untitled-1.ipynb
info 00:18:11.536: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd076df894008c9161b46d0aeb2ecdf4bcbe142a194f145dabc1a9d8e8ed72cd6cd#xcpp11./home/holst/miniconda3/python././home/holst/miniconda3/bin/xcpp#-f#{connection_file}#-std=c++11 (Python Path: /home/holst/miniconda3, EnvType: Conda, EnvName: 'base', Version: 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:26:04) [GCC 10.4.0]) for 'Untitled-1.ipynb' (disableUI=false)
info 00:18:11.539: Computing working directory for resource 'Untitled-1.ipynb'
info 00:18:11.608: Launching Raw Kernel & not daemon C++11 # /home/holst/miniconda3/bin/xcpp
info 00:18:11.612: No custom variables nor do we have a conda environment
info 00:18:11.636: Process Execution: > ~/miniconda3/bin/xcpp -std=c++11 --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"f961a222-d613-41b9-ba96-baffc59f27ae" --shell=9002 --transport="tcp" --iopub=9004 --f=/home/holst/.local/share/jupyter/runtime/kernel-v2-19399ckj0FSsMM3Hy.json
> ~/miniconda3/bin/xcpp -std=c++11 --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"f961a222-d613-41b9-ba96-baffc59f27ae" --shell=9002 --transport="tcp" --iopub=9004 --f=/home/holst/.local/share/jupyter/runtime/kernel-v2-19399ckj0FSsMM3Hy.json
info 00:18:11.636: Process Execution: cwd: ~
cwd: ~
warn 00:18:11.752: StdErr from Kernel Process registering handler for SIGSEGV

warn 00:18:11.797: StdErr from Kernel Process error: unsupported option '--ip=127.0.0.1'

warn 00:18:11.798: StdErr from Kernel Process error: unsupported option '--stdin=9003'

warn 00:18:11.799: StdErr from Kernel Process error: unsupported option '--control=9001'

warn 00:18:11.801: StdErr from Kernel Process error: unsupported option '--hb=9000'

warn 00:18:11.808: StdErr from Kernel Process error: unsupported option '--Session.signature_scheme="hmac-sha256"'

warn 00:18:11.813: StdErr from Kernel Process error: unsupported option '--Session.key=b"f961a222-d613-41b9-ba96-baffc59f27ae"'

warn 00:18:11.816: StdErr from Kernel Process error: unsupported option '--shell=9002'

warn 00:18:11.818: StdErr from Kernel Process error: unsupported option '--transport="tcp"'

warn 00:18:11.820: StdErr from Kernel Process error: unsupported option '--iopub=9004'

warn 00:18:11.826: StdErr from Kernel Process error: unsupported option '--f=/home/holst/.local/share/jupyter/runtime/kernel-v2-19399ckj0FSsMM3Hy.json'

info 00:18:13.812: Process Execution: > ~/miniconda3/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> ~/miniconda3/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
info 00:18:14.229: ipykernel version & path 6.19.2, ~/miniconda3/lib/python3.10/site-packages/ipykernel/__init__.py for /home/holst/miniconda3/bin/python
warn 00:18:14.924: StdErr from Kernel Process Starting xeus-cling kernel...

If you want to connect to this kernel from an other client, just copy and paste the following content inside of a `kernel.json` file. And then run for example:

# jupyter console --existing kernel.json

kernel.json
\```
{
    "transport": "tcp",
    "ip": "127.0.0.1",
    "control_port": 61007,
    "shell_port": 55148,
    "stdin_port": 56462,
    "iopub_port": 62652,
    "hb_port": 55815,
    "signature_scheme": "hmac-sha256",
    "key": "8b56c87956e942eb801a0f6bd54d47b1"
}
\```

warn 00:18:14.925: StdErr from Kernel Process Run with XEUS 3.0.5

error 00:19:11.657: waitUntilUsed timed out [Error: timeout
	at Timeout.<anonymous> (/home/holst/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:1230814)
	at listOnTimeout (node:internal/timers:559:17)
	at processTimers (node:internal/timers:502:7)]
error 00:19:11.697: Disposing kernel process due to an error [s [Error]: Unable to start Kernel 'C++11' due to connection timeout.
View Jupyter [log](command:jupyter.viewOutput) for further details.
	at /home/holst/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:2164255
	at async x.launch (/home/holst/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:2164326)] {
  category: 'timeout',
  kernelConnectionMetadata: f {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: '/home/holst/miniconda3/share/jupyter/kernels/xcpp11/kernel.json',
      interpreterPath: '/home/holst/miniconda3/bin/python',
      isRegisteredByVSC: 'registeredByNewVersionOfExtForCustomKernelSpec',
      name: 'pythonjvsc74a57bd076df894008c9161b46d0aeb2ecdf4bcbe142a194f145dabc1a9d8e8ed72cd6cd',
      argv: [Array],
      language: 'C++11',
      executable: '/home/holst/miniconda3/bin/xcpp',
      display_name: 'C++11',
      metadata: [Object]
    },
    interpreter: {
      id: '/home/holst/miniconda3/bin/python',
      sysPrefix: '/home/holst/miniconda3',
      envPath: [d],
      displayPath: [Object],
      envName: 'base',
      displayName: 'base',
      envType: 'Conda',
      version: [Object],
      uri: [d]
    },
    id: '.jvsc74a57bd076df894008c9161b46d0aeb2ecdf4bcbe142a194f145dabc1a9d8e8ed72cd6cd#xcpp11./home/holst/miniconda3/python././home/holst/miniconda3/bin/xcpp#-f#{connection_file}#-std=c++11'
  }
}
error 00:19:11.703: registering handler for SIGSEGV
error: unsupported option '--ip=127.0.0.1'
error: unsupported option '--stdin=9003'
error: unsupported option '--control=9001'
error: unsupported option '--hb=9000'
error: unsupported option '--Session.signature_scheme="hmac-sha256"'
error: unsupported option '--Session.key=b"f961a222-d613-41b9-ba96-baffc59f27ae"'
error: unsupported option '--shell=9002'
error: unsupported option '--transport="tcp"'
error: unsupported option '--iopub=9004'
error: unsupported option '--f=/home/holst/.local/share/jupyter/runtime/kernel-v2-19399ckj0FSsMM3Hy.json'
Starting xeus-cling kernel...

If you want to connect to this kernel from an other client, just copy and paste the following content inside of a `kernel.json` file. And then run for example:

# jupyter console --existing kernel.json

kernel.json
\```
{
    "transport": "tcp",
    "ip": "127.0.0.1",
    "control_port": 61007,
    "shell_port": 55148,
    "stdin_port": 56462,
    "iopub_port": 62652,
    "hb_port": 55815,
    "signature_scheme": "hmac-sha256",
    "key": "8b56c87956e942eb801a0f6bd54d47b1"
}
\```
Run with XEUS 3.0.5

info 00:19:11.704: Dispose Kernel process 19448.
error 00:19:11.748: Kernel Launcher. launch, Class name = r, completed in 60205ms, has a falsy return value, Arg 1: {"id":".jvsc74a57bd076df894008c9161b46d0aeb2ecdf4bcbe142a194f145dabc1a9d8e8ed72cd6cd#xcpp11./home/holst/miniconda3/python././home/holst/miniconda3/bin/xcpp#-f#{connection_file}#-std=c++11","kernelSpec":{"specFile":"/home/holst/miniconda3/share/jupyter/kernels/xcpp11/kernel.json","interpreterPath":"/home/holst/miniconda3/bin/python","isRegisteredByVSC":"registeredByNewVersionOfExtForCustomKernelSpec","name":"pythonjvsc74a57bd076df894008c9161b46d0aeb2ecdf4bcbe142a194f145dabc1a9d8e8ed72cd6cd","argv":["/home/holst/miniconda3/bin/xcpp","-f","{connection_file}","-std=c++11"],"language":"C++11","executable":"/home/holst/miniconda3/bin/xcpp","display_name":"C++11","metadata":{"vscode":{"originalSpecFile":"/home/holst/miniconda3/share/jupyter/kernels/xcpp11/kernel.json","originalDisplayName":"C++11"}}},"interpreter":{"id":"/home/holst/miniconda3/bin/python","sysPrefix":"/home/holst/miniconda3","envPath":"/home/holst/miniconda3","displayPath":{"$mid":1,"path":"/home/holst/miniconda3","scheme":"vscode-remote","authority":"wsl+ubuntu"},"envName":"base","displayName":"base","envType":"Conda","version":{"major":3,"minor":10,"patch":8,"raw":"3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:26:04) [GCC 10.4.0]"},"path":"/home/holst/miniconda3/bin/python"},"kind":"startUsingPythonInterpreter"}, Arg 2: 60000, Arg 3: "Untitled-1.ipynb", Arg 4: "~", Arg 5: <argument cannot be serialized for logging> [s [Error]: Unable to start Kernel 'C++11' due to connection timeout.
View Jupyter [log](command:jupyter.viewOutput) for further details.
	at /home/holst/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:2164255
	at async x.launch (/home/holst/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:2164326)] {
  category: 'timeout',
  kernelConnectionMetadata: f {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: '/home/holst/miniconda3/share/jupyter/kernels/xcpp11/kernel.json',
      interpreterPath: '/home/holst/miniconda3/bin/python',
      isRegisteredByVSC: 'registeredByNewVersionOfExtForCustomKernelSpec',
      name: 'pythonjvsc74a57bd076df894008c9161b46d0aeb2ecdf4bcbe142a194f145dabc1a9d8e8ed72cd6cd',
      argv: [Array],
      language: 'C++11',
      executable: '/home/holst/miniconda3/bin/xcpp',
      display_name: 'C++11',
      metadata: [Object]
    },
    interpreter: {
      id: '/home/holst/miniconda3/bin/python',
      sysPrefix: '/home/holst/miniconda3',
      envPath: [d],
      displayPath: [Object],
      envName: 'base',
      displayName: 'base',
      envType: 'Conda',
      version: [Object],
      uri: [d]
    },
    id: '.jvsc74a57bd076df894008c9161b46d0aeb2ecdf4bcbe142a194f145dabc1a9d8e8ed72cd6cd#xcpp11./home/holst/miniconda3/python././home/holst/miniconda3/bin/xcpp#-f#{connection_file}#-std=c++11'
  }
}
error 00:19:11.752: Failed to connect raw kernel session: Error: Unable to start Kernel 'C++11' due to connection timeout.
View Jupyter [log](command:jupyter.viewOutput) for further details.
warn 00:19:11.757: Error occurred while trying to start the kernel, options.disableUI=false [s [Error]: Unable to start Kernel 'C++11' due to connection timeout.
View Jupyter [log](command:jupyter.viewOutput) for further details.
	at /home/holst/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:2164255
	at async x.launch (/home/holst/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:2164326)] {
  category: 'timeout',
  kernelConnectionMetadata: f {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: '/home/holst/miniconda3/share/jupyter/kernels/xcpp11/kernel.json',
      interpreterPath: '/home/holst/miniconda3/bin/python',
      isRegisteredByVSC: 'registeredByNewVersionOfExtForCustomKernelSpec',
      name: 'pythonjvsc74a57bd076df894008c9161b46d0aeb2ecdf4bcbe142a194f145dabc1a9d8e8ed72cd6cd',
      argv: [Array],
      language: 'C++11',
      executable: '/home/holst/miniconda3/bin/xcpp',
      display_name: 'C++11',
      metadata: [Object]
    },
    interpreter: {
      id: '/home/holst/miniconda3/bin/python',
      sysPrefix: '/home/holst/miniconda3',
      envPath: [d],
      displayPath: [Object],
      envName: 'base',
      displayName: 'base',
      envType: 'Conda',
      version: [Object],
      uri: [d]
    },
    id: '.jvsc74a57bd076df894008c9161b46d0aeb2ecdf4bcbe142a194f145dabc1a9d8e8ed72cd6cd#xcpp11./home/holst/miniconda3/python././home/holst/miniconda3/bin/xcpp#-f#{connection_file}#-std=c++11'
  }
}
warn 00:19:11.765: Kernel Error, context = start [s [Error]: Unable to start Kernel 'C++11' due to connection timeout.
View Jupyter [log](command:jupyter.viewOutput) for further details.
	at /home/holst/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:2164255
	at async x.launch (/home/holst/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:2164326)] {
  category: 'timeout',
  kernelConnectionMetadata: f {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: '/home/holst/miniconda3/share/jupyter/kernels/xcpp11/kernel.json',
      interpreterPath: '/home/holst/miniconda3/bin/python',
      isRegisteredByVSC: 'registeredByNewVersionOfExtForCustomKernelSpec',
      name: 'pythonjvsc74a57bd076df894008c9161b46d0aeb2ecdf4bcbe142a194f145dabc1a9d8e8ed72cd6cd',
      argv: [Array],
      language: 'C++11',
      executable: '/home/holst/miniconda3/bin/xcpp',
      display_name: 'C++11',
      metadata: [Object]
    },
    interpreter: {
      id: '/home/holst/miniconda3/bin/python',
      sysPrefix: '/home/holst/miniconda3',
      envPath: [d],
      displayPath: [Object],
      envName: 'base',
      displayName: 'base',
      envType: 'Conda',
      version: [Object],
      uri: [d]
    },
    id: '.jvsc74a57bd076df894008c9161b46d0aeb2ecdf4bcbe142a194f145dabc1a9d8e8ed72cd6cd#xcpp11./home/holst/miniconda3/python././home/holst/miniconda3/bin/xcpp#-f#{connection_file}#-std=c++11'
  }
}
info 00:19:13.990: Process Execution: > ~/miniconda3/bin/python -c "import ipykernel"
> ~/miniconda3/bin/python -c "import ipykernel"
info 00:19:14.932: Dispose Kernel 'Untitled-1.ipynb' associated with 'Untitled-1.ipynb'
error 00:19:14.937: Error in execution [s [Error]: Unable to start Kernel 'C++11' due to connection timeout.
View Jupyter [log](command:jupyter.viewOutput) for further details.
	at /home/holst/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:2164255
	at async x.launch (/home/holst/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:2164326)] {
  category: 'timeout',
  kernelConnectionMetadata: f {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: '/home/holst/miniconda3/share/jupyter/kernels/xcpp11/kernel.json',
      interpreterPath: '/home/holst/miniconda3/bin/python',
      isRegisteredByVSC: 'registeredByNewVersionOfExtForCustomKernelSpec',
      name: 'pythonjvsc74a57bd076df894008c9161b46d0aeb2ecdf4bcbe142a194f145dabc1a9d8e8ed72cd6cd',
      argv: [Array],
      language: 'C++11',
      executable: '/home/holst/miniconda3/bin/xcpp',
      display_name: 'C++11',
      metadata: [Object]
    },
    interpreter: {
      id: '/home/holst/miniconda3/bin/python',
      sysPrefix: '/home/holst/miniconda3',
      envPath: [d],
      displayPath: [Object],
      envName: 'base',
      displayName: 'base',
      envType: 'Conda',
      version: [Object],
      uri: [d]
    },
    id: '.jvsc74a57bd076df894008c9161b46d0aeb2ecdf4bcbe142a194f145dabc1a9d8e8ed72cd6cd#xcpp11./home/holst/miniconda3/python././home/holst/miniconda3/bin/xcpp#-f#{connection_file}#-std=c++11'
  }
}
error 00:19:14.945: Error in execution (get message for cell) [s [Error]: Unable to start Kernel 'C++11' due to connection timeout.
View Jupyter [log](command:jupyter.viewOutput) for further details.
	at /home/holst/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:2164255
	at async x.launch (/home/holst/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003412109/out/extension.node.js:2:2164326)] {
  category: 'timeout',
  kernelConnectionMetadata: f {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: '/home/holst/miniconda3/share/jupyter/kernels/xcpp11/kernel.json',
      interpreterPath: '/home/holst/miniconda3/bin/python',
      isRegisteredByVSC: 'registeredByNewVersionOfExtForCustomKernelSpec',
      name: 'pythonjvsc74a57bd076df894008c9161b46d0aeb2ecdf4bcbe142a194f145dabc1a9d8e8ed72cd6cd',
      argv: [Array],
      language: 'C++11',
      executable: '/home/holst/miniconda3/bin/xcpp',
      display_name: 'C++11',
      metadata: [Object]
    },
    interpreter: {
      id: '/home/holst/miniconda3/bin/python',
      sysPrefix: '/home/holst/miniconda3',
      envPath: [d],
      displayPath: [Object],
      envName: 'base',
      displayName: 'base',
      envType: 'Conda',
      version: [Object],
      uri: [d]
    },
    id: '.jvsc74a57bd076df894008c9161b46d0aeb2ecdf4bcbe142a194f145dabc1a9d8e8ed72cd6cd#xcpp11./home/holst/miniconda3/python././home/holst/miniconda3/bin/xcpp#-f#{connection_file}#-std=c++11'
  }
}

```

**Comment by ianholst** [comment]
Update: the (slightly janky) Jupyter kernel included with Cling works properly in WSL remote VS Code notebooks. It is a huge pain to build and install though. xeus-cling still does not work properly.

**Comment by DonJayamanne** [comment]
> xeus-cling still does not work properly.

thanks for filing this issue and providing the logs.
Can you confirm this issue persists even when using Jupyter Notebooks (in WSL outside VSCode).
If yes, then pelase could you provide the corresopnding logs from WSL when running Jupyter
You can run Jupyter notebook as follows `jupyter notebook` or `python -m jupyter notebook`

**Comment by ianholst** [comment]
Yes, sorry if it wasn't clear in the original post, xeus-cling does work in WSL when used in the web browser Jupyter notebook. I put in a screenshot showing that. If you want the output in the console when I do that, here it is:

```
[I 22:29:38.503 NotebookApp] Writing notebook server cookie secret to /home/holst/.local/share/jupyter/runtime/notebook_cookie_secret
[I 22:29:38.657 NotebookApp] Serving notebooks from local directory: /home/holst
[I 22:29:38.657 NotebookApp] Jupyter Notebook 6.5.2 is running at:
[I 22:29:38.657 NotebookApp] http://localhost:8888/?token=32afb232835ecef7e3105d2136ddbe1429af843bdb85d8c0
[I 22:29:38.657 NotebookApp]  or http://127.0.0.1:8888/?token=32afb232835ecef7e3105d2136ddbe1429af843bdb85d8c0
[I 22:29:38.658 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 22:29:39.564 NotebookApp] No web browser found: could not locate runnable browser.
[C 22:29:39.564 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///home/holst/.local/share/jupyter/runtime/nbserver-1185-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=32afb232835ecef7e3105d2136ddbe1429af843bdb85d8c0
     or http://127.0.0.1:8888/?token=32afb232835ecef7e3105d2136ddbe1429af843bdb85d8c0
[I 22:29:44.230 NotebookApp] 302 GET /?token=32afb232835ecef7e3105d2136ddbe1429af843bdb85d8c0 (127.0.0.1) 0.520000ms
[I 22:29:52.101 NotebookApp] Creating new notebook in
[I 22:29:52.192 NotebookApp] Writing notebook-signing key to /home/holst/.local/share/jupyter/notebook_secret
[W 22:29:53.139 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20230129222938 (127.0.0.1) 15.470000ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=xcpp11
[I 22:29:53.142 NotebookApp] Kernel started: d34414a7-0eea-4d12-b03c-3266c08393ba, name: xcpp11
```

**Comment by DonJayamanne** [comment]
Thanks for the response
Please could you install vscode insiders and the pre-release version of Jupyter extension
next could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
