### ISSUE TITLE
The kernel failed to start due to missing module 'pysqlite2'

### ISSUE THREAD

**Issue by leeway00** [microsoft/vscode-jupyter#12730]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

The kernel is crashing for every virtual environment which was working well. I updated the extension a few hours ago, and every environments are crashing now.

I checked jupyter notebook and jupyter lab, and both of them are working. The kernel is only crashing in vscode.

The log seems similar to https://github.com/microsoft/vscode-jupyter/issues/10110, although none of the method suggested there are working for my problem.

### VS Code Version

1.75.0

### Jupyter Extension Version

v2023.1.2000312134

### Jupyter logs

```shell
error 17:03:06.367: Error in execution Er [Error]: Jupyter server crashed. Unable to connect. 
Error code from Jupyter: 1
Traceback (most recent call last):
  File "/Users/hun/miniforge3/lib/python3.9/site-packages/notebook/services/sessions/sessionmanager.py", line 9, in <module>

    import sqlite3
  File "/Users/hun/miniforge3/lib/python3.9/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/Users/hun/miniforge3/lib/python3.9/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: dlopen(/Users/hun/miniforge3/lib/python3.9/lib-dynload/_sqlite3.cpython-39-darwin.so, 0x0002): Symbol not found: _sqlite3_enable_load_extension
  Referenced from: <F761FEDE-124A-3302-BCF5-7D683493D28B> /Users/hun/miniforge3/lib/python3.9/lib-dynload/_sqlite3.cpython-39-darwin.so
  Expected in:     <3870AC8E-1780-3CA6-A2A7-8B978A52921A> /usr/lib/libsqlite3.dylib

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hun/miniforge3/bin/jupyter-notebook", line 5, in <module>

    from notebook.notebookapp import main
  File "/Users/hun/miniforge3/lib/python3.9/site-packages/notebook/notebookapp.py", line 82, in <module>

    from .services.sessions.sessionmanager import SessionManager

  File "/Users/hun/miniforge3/lib/python3.9/site-packages/notebook/services/sessions/sessionmanager.py", line 12, in <module>

    from pysqlite2 import dbapi2 as sqlite3
ModuleNotFoundError: No module named 'pysqlite2'

    at Sm.rejectStartPromise (/Users/hun/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:254981)
    at t._complete (/Users/hun/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:255541)
    at t.n (/Users/hun/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:700797)
    at t.__tryOrUnsub (/Users/hun/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:701037)
    at t.complete (/Users/hun/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:700930)
    at t._complete (/Users/hun/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:699446)
    at t.complete (/Users/hun/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:699145)
    at ChildProcess.<anonymous> (/Users/hun/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:1800927)
    at Object.onceWrapper (node:events:646:26)
    at ChildProcess.emit (node:events:538:35)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  category: 'jupyterconnection'
}
error 17:03:06.367: Error in execution (get message for cell) Er [Error]: Jupyter server crashed. Unable to connect. 
Error code from Jupyter: 1
Traceback (most recent call last):
  File "/Users/hun/miniforge3/lib/python3.9/site-packages/notebook/services/sessions/sessionmanager.py", line 9, in <module>

    import sqlite3
  File "/Users/hun/miniforge3/lib/python3.9/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/Users/hun/miniforge3/lib/python3.9/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: dlopen(/Users/hun/miniforge3/lib/python3.9/lib-dynload/_sqlite3.cpython-39-darwin.so, 0x0002): Symbol not found: _sqlite3_enable_load_extension
  Referenced from: <F761FEDE-124A-3302-BCF5-7D683493D28B> /Users/hun/miniforge3/lib/python3.9/lib-dynload/_sqlite3.cpython-39-darwin.so
  Expected in:     <3870AC8E-1780-3CA6-A2A7-8B978A52921A> /usr/lib/libsqlite3.dylib

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hun/miniforge3/bin/jupyter-notebook", line 5, in <module>

    from notebook.notebookapp import main
  File "/Users/hun/miniforge3/lib/python3.9/site-packages/notebook/notebookapp.py", line 82, in <module>

    from .services.sessions.sessionmanager import SessionManager

  File "/Users/hun/miniforge3/lib/python3.9/site-packages/notebook/services/sessions/sessionmanager.py", line 12, in <module>

    from pysqlite2 import dbapi2 as sqlite3
ModuleNotFoundError: No module named 'pysqlite2'

    at Sm.rejectStartPromise (/Users/hun/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:254981)
    at t._complete (/Users/hun/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:255541)
    at t.n (/Users/hun/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:700797)
    at t.__tryOrUnsub (/Users/hun/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:701037)
    at t.complete (/Users/hun/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:700930)
    at t._complete (/Users/hun/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:699446)
    at t.complete (/Users/hun/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:699145)
    at ChildProcess.<anonymous> (/Users/hun/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:1800927)
    at Object.onceWrapper (node:events:646:26)
    at ChildProcess.emit (node:events:538:35)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  category: 'jupyterconnection'
}
```

### Coding Language and Runtime Version

Python 3.9.7, 3.9.15, 3.10

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Thanks for filling this issue and sorry you are running into this

please install the latest pre-release version of the Jupyter Extension

The latest pre-release version is `v2023.2.****`

Click the `Switch to Pre-Release Version` in the extension page (see below)
<img width="572" alt="Screenshot 2023-02-04 at 09 24 37" src="https://user-images.githubusercontent.com/1948812/216722719-fd8e14dc-783f-4859-8235-012b1bc796d9.png">

if that does not work, 
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by leeway00** [comment]
@DonJayamanne  Thank you. It is working after switching to Pre-Release Version.

**Comment by DonJayamanne** [comment]
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/12726
@leeway00 thanks for the confirmation
