### ISSUE TITLE
Kernel creation failed, when connected to remote jupyter server

### ISSUE THREAD

**Issue by lokesh-kurre** [microsoft/vscode-jupyter#12733]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I connected the locally created jupyter server from docker as remote jupyter server.
And I tried to run the code in notebook, after selecting kernel to be present in remote server

**Expected:**
New kernel should be created for the current new notebook.

**Actually Happened:**
Got Error saying,
```
Failed to start the Kernel. 
'_xsrf' argument missing from POST. 
View Jupyter log for further details
```

### VS Code Version

Version: 1.75.0 Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164 Date: 2023-02-01T15:29:17.766Z Electron: 19.1.9 Chromium: 102.0.5005.194 Node.js: 16.14.2 V8: 10.2.154.23-electron.0 OS: Linux x64 5.15.0-58-generic Sandboxed: No

### Jupyter Extension Version

v2023.1.2000312134

### Jupyter logs

```shell
info 00:22:04.564: Starting Jupyter Session startUsingRemoteKernelSpec, 05a206bc846560e1b90e0f32f042a315daffe0edb6ff8a5c5d7a19ec34ae8909..python3./usr/bin/python3./.-m#ipykernel_launcher for '/home/kali/Documents/vscode/python/test/opencv-test/code/test.ipynb' (disableUI=false)
error 00:22:04.581: Backing file not supported: Error: '_xsrf' argument missing from POST
error 00:22:04.591: Failed to change kernel, re-throwing [Ap [Error]: 
	at new pn (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:1628691)
	at new Ap (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:127546)
	at /home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:278397
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)

Error: '_xsrf' argument missing from POST
	at t.create (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:68927)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async t.startSession (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:81011)
	at async d.startNew (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:77195)] {
  category: 'unknown',
  originalException: [t [Error]: '_xsrf' argument missing from POST
  	at t.create (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:68927)
  	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
  	at async t.startSession (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:81011)
  	at async d.startNew (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:77195)] {
    response: L [Response] {
      size: 0,
      timeout: 0,
      [Symbol(Body internals)]: [Object],
      [Symbol(Response internals)]: [Object]
    },
    traceback: ''
  }
}
warn 00:22:04.593: Error occurred while trying to start the kernel, options.disableUI=false [Ap [Error]: 
	at new pn (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:1628691)
	at new Ap (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:127546)
	at /home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:278397
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)

Error: '_xsrf' argument missing from POST
	at t.create (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:68927)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async t.startSession (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:81011)
	at async d.startNew (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:77195)] {
  category: 'unknown',
  originalException: [t [Error]: '_xsrf' argument missing from POST
  	at t.create (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:68927)
  	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
  	at async t.startSession (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:81011)
  	at async d.startNew (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:77195)] {
    response: L [Response] {
      size: 0,
      timeout: 0,
      [Symbol(Body internals)]: [Object],
      [Symbol(Response internals)]: [Object]
    },
    traceback: ''
  }
}
warn 00:22:04.593: Kernel Error, context = start [Ap [Error]: 
	at new pn (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:1628691)
	at new Ap (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:127546)
	at /home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:278397
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)

Error: '_xsrf' argument missing from POST
	at t.create (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:68927)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async t.startSession (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:81011)
	at async d.startNew (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:77195)] {
  category: 'unknown',
  originalException: [t [Error]: '_xsrf' argument missing from POST
  	at t.create (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:68927)
  	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
  	at async t.startSession (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:81011)
  	at async d.startNew (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:77195)] {
    response: L [Response] {
      size: 0,
      timeout: 0,
      [Symbol(Body internals)]: [Object],
      [Symbol(Response internals)]: [Object]
    },
    traceback: ''
  }
}
info 00:22:04.597: Dispose Kernel '/home/kali/Documents/vscode/python/test/opencv-test/code/test.ipynb' associated with '/home/kali/Documents/vscode/python/test/opencv-test/code/test.ipynb'
error 00:22:04.599: Error in execution [Ap [Error]: 
	at new pn (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:1628691)
	at new Ap (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:127546)
	at /home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:278397
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)

Error: '_xsrf' argument missing from POST
	at t.create (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:68927)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async t.startSession (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:81011)
	at async d.startNew (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:77195)] {
  category: 'unknown',
  originalException: [t [Error]: '_xsrf' argument missing from POST
  	at t.create (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:68927)
  	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
  	at async t.startSession (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:81011)
  	at async d.startNew (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:77195)] {
    response: L [Response] {
      size: 0,
      timeout: 0,
      [Symbol(Body internals)]: [Object],
      [Symbol(Response internals)]: [Object]
    },
    traceback: ''
  }
}
error 00:22:04.600: Error in execution (get message for cell) [Ap [Error]: 
	at new pn (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:1628691)
	at new Ap (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:127546)
	at /home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:278397
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)

Error: '_xsrf' argument missing from POST
	at t.create (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:68927)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async t.startSession (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:81011)
	at async d.startNew (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:77195)] {
  category: 'unknown',
  originalException: [t [Error]: '_xsrf' argument missing from POST
  	at t.create (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:68927)
  	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
  	at async t.startSession (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:81011)
  	at async d.startNew (/home/kali/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:77195)] {
    response: L [Response] {
      size: 0,
      timeout: 0,
      [Symbol(Body internals)]: [Object],
      [Symbol(Response internals)]: [Object]
    },
    traceback: ''
  }
}
info 00:22:06.599: Creating server with url : http://localhost:8888/
```

### Coding Language and Runtime Version

Python3.8

### Language Extension Version (if applicable)

v2023.2.0

### Running Jupyter locally or remotely?

Remote

**Comment by DonJayamanne** [comment]
Thanks you for filing this issue
> locally created jupyter server from docker as remote jupyter server.

Please could you share the exact command line used to start jupyter 

Also, please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

Please provide all of the logs, thank you

**Comment by lokesh-kurre** [comment]
[answer](https://stackoverflow.com/questions/75343770/problem-with-kernel-creation-in-vscode-while-connected-to-remote-jupyter-server) 
When I debug the issue I found the reason behind it, I already posted in this link. This issue doesn't seems to be because of Bug.
