### ISSUE TITLE
Export to pdf failed

### ISSUE THREAD

**Issue by Will-Zhao0** [microsoft/vscode-jupyter#12742]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Export to pdf failed even though tex installed, it seems tex is not recognized.

### VS Code Version

1.75.0

### Jupyter Extension Version

2023.1.2000312134

### Jupyter logs

```shell
Visual Studio Code (1.75.0, ssh-remote, desktop)
Jupyter Extension Version: 2023.1.2000312134.
Python Extension Version: 2023.2.0.
Workspace folder /home/cz015
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 22:58:24.769: LSP Notebooks experiment is enabled
info 22:58:24.834: Find preferred kernel for /home/cz015/csci349/labs/lab05.ipynb with metadata {"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.12"},"vscode":{"interpreter":{"hash":"d28bb2eb23bdb66e7f836e575cc413c5e3a5ddfd80fc8cb4c42c9ff652ef3dba"}}} & preferred interpreter /home/cz015/.conda/envs/learn/bin/python
info 22:58:24.836: Find preferred kernel for /home/cz015/csci349/labs/lab05.ipynb with metadata {"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.12"},"vscode":{"interpreter":{"hash":"d28bb2eb23bdb66e7f836e575cc413c5e3a5ddfd80fc8cb4c42c9ff652ef3dba"}}} & preferred interpreter /home/cz015/.conda/envs/learn/bin/python
info 22:58:24.876: Find preferred kernel for /home/cz015/csci349/labs/lab05.ipynb with metadata {"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.12"},"vscode":{"interpreter":{"hash":"d28bb2eb23bdb66e7f836e575cc413c5e3a5ddfd80fc8cb4c42c9ff652ef3dba"}}} & preferred interpreter /home/cz015/.conda/envs/learn/bin/python
info 22:58:24.877: Preferred kernel .jvsc74a57bd0d28bb2eb23bdb66e7f836e575cc413c5e3a5ddfd80fc8cb4c42c9ff652ef3dba./home/cz015/.conda/envs/learn/python./home/cz015/.conda/envs/learn/python.-m#ipykernel_launcher is exact match or top match for non python kernels, (true, [object Object], true, false)
info 22:58:24.877: PreferredConnection: .jvsc74a57bd0d28bb2eb23bdb66e7f836e575cc413c5e3a5ddfd80fc8cb4c42c9ff652ef3dba./home/cz015/.conda/envs/learn/python./home/cz015/.conda/envs/learn/python.-m#ipykernel_launcher found for NotebookDocument: /home/cz015/csci349/labs/lab05.ipynb
info 22:58:24.885: Find preferred kernel for /home/cz015/csci349/labs/lab05.ipynb with metadata {"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.12"},"vscode":{"interpreter":{"hash":"d28bb2eb23bdb66e7f836e575cc413c5e3a5ddfd80fc8cb4c42c9ff652ef3dba"}}} & preferred interpreter /home/cz015/.conda/envs/learn/bin/python
info 22:58:24.940: Preferred kernel .jvsc74a57bd0d28bb2eb23bdb66e7f836e575cc413c5e3a5ddfd80fc8cb4c42c9ff652ef3dba./home/cz015/.conda/envs/learn/python./home/cz015/.conda/envs/learn/python.-m#ipykernel_launcher is exact match or top match for non python kernels, (false, [object Object], true, false)
info 22:58:24.940: PreferredConnection: .jvsc74a57bd0d28bb2eb23bdb66e7f836e575cc413c5e3a5ddfd80fc8cb4c42c9ff652ef3dba./home/cz015/.conda/envs/learn/python./home/cz015/.conda/envs/learn/python.-m#ipykernel_launcher found for NotebookDocument: /home/cz015/csci349/labs/lab05.ipynb
info 22:58:31.211: Process Execution: > ~/.conda/envs/learn/bin/python -m pip list
> ~/.conda/envs/learn/bin/python -m pip list
info 22:58:47.631: Process Execution: > ~/.conda/envs/learn/bin/python -c "import nbconvert;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> ~/.conda/envs/learn/bin/python -c "import nbconvert;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 22:58:48.387: Process Execution: > ~/.conda/envs/learn/bin/python -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> ~/.conda/envs/learn/bin/python -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 22:58:52.200: Process Execution: > ~/.conda/envs/learn/bin/python -m jupyter nbconvert /tmp/e6dabe11-183d-4519-96d4-8586d648a1eb/lab05.ipynb --to pdf --output tmp-959302tWMKfYnrhLf8.pdf --output-dir /tmp --debug
> ~/.conda/envs/learn/bin/python -m jupyter nbconvert /tmp/e6dabe11-183d-4519-96d4-8586d648a1eb/lab05.ipynb --to pdf --output tmp-959302tWMKfYnrhLf8.pdf --output-dir /tmp --debug
error 22:58:53.803: Export failed Error: [NbConvertApp] Searching ['/home/cz015', '/home/cz015/.jupyter', '/home/cz015/.local/etc/jupyter', '/home/cz015/.conda/envs/learn/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[NbConvertApp] Looking for jupyter_config in /etc/jupyter
[NbConvertApp] Looking for jupyter_config in /usr/local/etc/jupyter
[NbConvertApp] Looking for jupyter_config in /home/cz015/.conda/envs/learn/etc/jupyter
[NbConvertApp] Looking for jupyter_config in /home/cz015/.local/etc/jupyter
[NbConvertApp] Looking for jupyter_config in /home/cz015/.jupyter
[NbConvertApp] Looking for jupyter_config in /home/cz015
[NbConvertApp] Looking for jupyter_nbconvert_config in /etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /usr/local/etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /home/cz015/.conda/envs/learn/etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /home/cz015/.local/etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /home/cz015/.jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /home/cz015
[NbConvertApp] Converting notebook /tmp/e6dabe11-183d-4519-96d4-8586d648a1eb/lab05.ipynb to pdf
[NbConvertApp] Notebook name is 'tmp-959302tWMKfYnrhLf8'
[NbConvertApp] Template paths:
	/home/cz015/.local/share/jupyter/nbconvert/templates/latex
	/home/cz015/.conda/envs/learn/share/jupyter/nbconvert/templates/latex
	/home/cz015/.conda/envs/learn/share/jupyter/nbconvert/templates/base
	/home/cz015/.local/share/jupyter
	/home/cz015/.local/share/jupyter/nbconvert/templates
	/home/cz015/.local/share/jupyter/nbconvert/templates/compatibility
	/home/cz015/.conda/envs/learn/share/jupyter
	/home/cz015/.conda/envs/learn/share/jupyter/nbconvert/templates
	/home/cz015/.conda/envs/learn/share/jupyter/nbconvert/templates/compatibility
	/usr/local/share/jupyter
	/usr/local/share/jupyter/nbconvert/templates
	/usr/local/share/jupyter/nbconvert/templates/compatibility
	/usr/share/jupyter
	/usr/share/jupyter/nbconvert/templates
	/usr/share/jupyter/nbconvert/templates/compatibility
	/home/cz015/.local/share/jupyter/nbconvert/templates
	/home/cz015/.conda/envs/learn/share/jupyter/nbconvert/templates
[NbConvertApp] Applying preprocessor: TagRemovePreprocessor
[NbConvertApp] Applying preprocessor: RegexRemovePreprocessor
[NbConvertApp] Applying preprocessor: coalesce_streams
[NbConvertApp] Applying preprocessor: SVG2PDFPreprocessor
[NbConvertApp] Applying preprocessor: LatexPreprocessor
[NbConvertApp] Applying preprocessor: HighlightMagicsPreprocessor
[NbConvertApp] Applying preprocessor: ExtractOutputPreprocessor
[NbConvertApp] Attempting to load template index.tex.j2
[NbConvertApp]     template_paths: /home/cz015/.local/share/jupyter/nbconvert/templates/latex:/home/cz015/.conda/envs/learn/share/jupyter/nbconvert/templates/latex:/home/cz015/.conda/envs/learn/share/jupyter/nbconvert/templates/base:/home/cz015/.local/share/jupyter:/home/cz015/.local/share/jupyter/nbconvert/templates:/home/cz015/.local/share/jupyter/nbconvert/templates/compatibility:/home/cz015/.conda/envs/learn/share/jupyter:/home/cz015/.conda/envs/learn/share/jupyter/nbconvert/templates:/home/cz015/.conda/envs/learn/share/jupyter/nbconvert/templates/compatibility:/usr/local/share/jupyter:/usr/local/share/jupyter/nbconvert/templates:/usr/local/share/jupyter/nbconvert/templates/compatibility:/usr/share/jupyter:/usr/share/jupyter/nbconvert/templates:/usr/share/jupyter/nbconvert/templates/compatibility:/home/cz015/.local/share/jupyter/nbconvert/templates:/home/cz015/.conda/envs/learn/share/jupyter/nbconvert/templates
YAML parse exception at line 4, column 90:
mapping values are not allowed in this context
Traceback (most recent call last):
  File "/home/cz015/.conda/envs/learn/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "/home/cz015/.conda/envs/learn/lib/python3.9/site-packages/jupyter_core/application.py", line 269, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "/home/cz015/.conda/envs/learn/lib/python3.9/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/home/cz015/.conda/envs/learn/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 369, in start
    self.convert_notebooks()
  File "/home/cz015/.conda/envs/learn/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 541, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/home/cz015/.conda/envs/learn/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 506, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/home/cz015/.conda/envs/learn/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 435, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/home/cz015/.conda/envs/learn/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 190, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/cz015/.conda/envs/learn/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 208, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/home/cz015/.conda/envs/learn/lib/python3.9/site-packages/nbconvert/exporters/pdf.py", line 168, in from_notebook_node
    latex, resources = super().from_notebook_node(
  File "/home/cz015/.conda/envs/learn/lib/python3.9/site-packages/nbconvert/exporters/latex.py", line 72, in from_notebook_node
    return super().from_notebook_node(nb, resources, **kw)
  File "/home/cz015/.conda/envs/learn/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 392, in from_notebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
  File "/home/cz015/.conda/envs/learn/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/cz015/.conda/envs/learn/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/cz015/.conda/envs/learn/share/jupyter/nbconvert/templates/latex/index.tex.j2", line 8, in top-level template code
    ((* extends cell_style *))
  File "/home/cz015/.conda/envs/learn/share/jupyter/nbconvert/templates/latex/style_jupyter.tex.j2", line 176, in top-level template code
    \prompt{(((prompt)))}{(((prompt_color)))}{(((execution_count)))}{(((extra_space)))}
  File "/home/cz015/.conda/envs/learn/share/jupyter/nbconvert/templates/latex/base.tex.j2", line 7, in top-level template code
    ((*- extends 'document_contents.tex.j2' -*))
  File "/home/cz015/.conda/envs/learn/share/jupyter/nbconvert/templates/latex/document_contents.tex.j2", line 51, in top-level template code
    ((*- block figure scoped -*))
  File "/home/cz015/.conda/envs/learn/share/jupyter/nbconvert/templates/latex/display_priority.j2", line 5, in top-level template code
    ((*- extends 'null.j2' -*))
  File "/home/cz015/.conda/envs/learn/share/jupyter/nbconvert/templates/latex/null.j2", line 30, in top-level template code
    ((*- block body -*))
  File "/home/cz015/.conda/envs/learn/share/jupyter/nbconvert/templates/latex/base.tex.j2", line 215, in block 'body'
    ((( super() )))
  File "/home/cz015/.conda/envs/learn/share/jupyter/nbconvert/templates/latex/null.j2", line 32, in block 'body'
    ((*- block any_cell scoped -*))
  File "/home/cz015/.conda/envs/learn/share/jupyter/nbconvert/templates/latex/null.j2", line 85, in block 'any_cell'
    ((*- block markdowncell scoped-*)) ((*- endblock markdowncell -*))
  File "/home/cz015/.conda/envs/learn/share/jupyter/nbconvert/templates/latex/document_contents.tex.j2", line 68, in block 'markdowncell'
    ((( cell.source | citation2latex | strip_files_prefix | convert_pandoc('markdown+tex_math_double_backslash', 'json',extra_args=[]) | resolve_references | convert_pandoc('json','latex'))))
  File "/home/cz015/.conda/envs/learn/lib/python3.9/site-packages/nbconvert/filters/filter_links.py", line 16, in resolve_references
    return applyJSONFilters([resolve_one_reference], source)
  File "/home/cz015/.conda/envs/learn/lib/python3.9/site-packages/pandocfilters.py", line 203, in applyJSONFilters
    doc = json.loads(source)
  File "/home/cz015/.conda/envs/learn/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/cz015/.conda/envs/learn/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/cz015/.conda/envs/learn/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

    at aw.executeCommand (/home/cz015/.vscode-server/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:596939)
    at gw.export (/home/cz015/.vscode-server/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:600970)
    at Ew.exportToFormat (/home/cz015/.vscode-server/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:605493)
    at Ew.performNbConvertExport (/home/cz015/.vscode-server/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:605321)
    at Ew.performExport (/home/cz015/.vscode-server/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:604998)
    at Ew.exportImpl (/home/cz015/.vscode-server/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:604626)
    at Ew.export (/home/cz015/.vscode-server/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:604382)
    at E_.export (/home/cz015/.vscode-server/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:740363)
    at s.h (/home/cz015/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:96:108008)
error 22:58:53.803: If you have not installed xelatex (TeX) you will need to do so before you can export to PDF, for further instructions please look https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex. 
To avoid installing xelatex (TeX) you might want to try exporting to HTML and using your browsers "Print to PDF" feature.
```

### Running Jupyter locally or remotely?

Remote

**Comment by amunger** [comment]
Do you have the correct tex library installed, and have you tried following the instructions in the linked document: https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex

**Comment by Will-Zhao0** [comment]
Yes, and it has been working find until the last update

>tex -v
TeX 3.141592653 (TeX Live 2021)
kpathsea version 6.3.3
Copyright 2021 D.E. Knuth.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the TeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the TeX source.
Primary author of TeX: D.E. Knuth.

**Comment by amunger** [comment]
sorry for letting this drop. It looks like others have had success by uninstall/reinstalling the nbconvert library in the python environment: https://github.com/microsoft/vscode-jupyter/issues/4347#issuecomment-763787690

Give that a try if you're still having trouble with this.
