### ISSUE TITLE
ipython display() with display_id is broken in the last release (v2023.1.2000312134)

### ISSUE THREAD

**Issue by xl0** [microsoft/vscode-jupyter#12755]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

It looks like we have an issue with how IPython display updates are handled. 
Minimal code to reproduce: 

```python
from IPython.display import display, HTML
import time


handle1 = display(HTML("<h2>Hello!</h2>"), display_id=True)
handle2 = display(HTML("<h2>World!</h2>"), display_id=True)
time.sleep(1)
handle1.update(HTML("<h2>I love</h2>"))
handle2.update(HTML("<h2>Pizza</h2>"))
```

Results in Jupyter and vscode-jupyter v2022.11.1003412109:
"Hello!"
"World!"

After 1 second replaced by
"I love"
"Pizza"

Results in vscode-jupyter v2023.1.2000312134 and current pre-release:
"Hello!"
"World!"

After 1 second replaced by
"Pizza"

This bug affects the popular fast.ai deep learning framework, breaking progress /metric racking during training, rendering it not usable in vscode-jupyter.

### VS Code Version

Version: 1.75.0 Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164 Date: 2023-02-01T15:29:17.766Z Electron: 19.1.9 Chromium: 102.0.5005.194 Node.js: 16.14.2 V8: 10.2.154.23-electron.0 OS: Linux x64 5.4.0-135-generic Sandboxed: No

### Jupyter Extension Version

v2023.1.2000312134

### Jupyter logs

```shell
Visual Studio Code (1.75.0, undefined, desktop)
Jupyter Extension Version: 2023.1.2000312134.
Python Extension Version: 2023.2.0.
Workspace folder /home/xl0/work/tmp
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 11:06:36.755: LSP Notebooks experiment is enabled
info 11:06:37.088: Find preferred kernel for /home/xl0/work/tmp/Untitled.ipynb with metadata {"kernelspec":{"display_name":"torch","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.10.6"},"vscode":{"interpreter":{"hash":"6be5eb67bb380238eb3fdb5608a5262f71c7ac5508d0890c6e2462bfc99ed11d"}}} & preferred interpreter /usr/bin/python
info 11:06:37.089: Find preferred kernel for /home/xl0/work/tmp/Untitled.ipynb with metadata {"kernelspec":{"display_name":"torch","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.10.6"},"vscode":{"interpreter":{"hash":"6be5eb67bb380238eb3fdb5608a5262f71c7ac5508d0890c6e2462bfc99ed11d"}}} & preferred interpreter /usr/bin/python
info 11:06:37.145: Find preferred kernel for /home/xl0/work/tmp/Untitled.ipynb with metadata {"kernelspec":{"display_name":"torch","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.10.6"},"vscode":{"interpreter":{"hash":"6be5eb67bb380238eb3fdb5608a5262f71c7ac5508d0890c6e2462bfc99ed11d"}}} & preferred interpreter /usr/bin/python
info 11:06:37.157: Find preferred kernel for /home/xl0/work/tmp/Untitled.ipynb with metadata {"kernelspec":{"display_name":"torch","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.10.6"},"vscode":{"interpreter":{"hash":"6be5eb67bb380238eb3fdb5608a5262f71c7ac5508d0890c6e2462bfc99ed11d"}}} & preferred interpreter /usr/bin/python
info 11:06:37.331: Preferred kernel .jvsc74a57bd06be5eb67bb380238eb3fdb5608a5262f71c7ac5508d0890c6e2462bfc99ed11d./home/xl0/mambaforge/envs/torch/python./home/xl0/mambaforge/envs/torch/python.-m#ipykernel_launcher is exact match or top match for non python kernels, (false, undefined, true, false)
info 11:06:37.331: PreferredConnection: .jvsc74a57bd06be5eb67bb380238eb3fdb5608a5262f71c7ac5508d0890c6e2462bfc99ed11d./home/xl0/mambaforge/envs/torch/python./home/xl0/mambaforge/envs/torch/python.-m#ipykernel_launcher found for NotebookDocument: /home/xl0/work/tmp/Untitled.ipynb
info 11:06:37.473: Process Execution: > /usr/bin/python -m pip list
> /usr/bin/python -m pip list
info 11:06:37.488: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd06be5eb67bb380238eb3fdb5608a5262f71c7ac5508d0890c6e2462bfc99ed11d./home/xl0/mambaforge/envs/torch/python./home/xl0/mambaforge/envs/torch/python.-m#ipykernel_launcher (Python Path: /home/xl0/mambaforge/envs/torch, EnvType: Conda, EnvName: 'torch', Version: 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:35:26) [GCC 10.4.0]) for '/home/xl0/work/tmp/Untitled.ipynb' (disableUI=true)
info 11:06:39.943: Process Execution: > ~/mambaforge/envs/torch/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> ~/mambaforge/envs/torch/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
info 11:06:40.002: Process Execution: > ~/mambaforge/envs/torch/bin/python -m pip list
> ~/mambaforge/envs/torch/bin/python -m pip list
info 11:06:40.098: Process Execution: > ~/mambaforge/envs/torch/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9013 --control=9011 --hb=9010 --Session.signature_scheme="hmac-sha256" --Session.key=b"aaf24f24-7670-435d-a555-20a790f04b8f" --shell=9012 --transport="tcp" --iopub=9014 --f=/home/xl0/.local/share/jupyter/runtime/kernel-v2-10480545D1fpdSk8XXJ.json
> ~/mambaforge/envs/torch/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9013 --control=9011 --hb=9010 --Session.signature_scheme="hmac-sha256" --Session.key=b"aaf24f24-7670-435d-a555-20a790f04b8f" --shell=9012 --transport="tcp" --iopub=9014 --f=/home/xl0/.local/share/jupyter/runtime/kernel-v2-10480545D1fpdSk8XXJ.json
info 11:06:40.098: Process Execution: cwd: ~/work/tmp
cwd: ~/work/tmp
info 11:06:40.144: ipykernel version & path 6.19.2, ~/mambaforge/envs/torch/lib/python3.10/site-packages/ipykernel/__init__.py for /home/xl0/mambaforge/envs/torch/bin/python
warn 11:06:40.798: StdErr from Kernel Process /home/xl0/mambaforge/envs/torch/lib/python3.10/site-packages/traitlets/traitlets.py:2544: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(

warn 11:06:40.798: StdErr from Kernel Process /home/xl0/mambaforge/envs/torch/lib/python3.10/site-packages/traitlets/traitlets.py:2495: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use 'aaf24f24-7670-435d-a555-20a790f04b8f' instead of 'b"aaf24f24-7670-435d-a555-20a790f04b8f"'.
  warn(

info 11:06:40.948: Started Kernel torch (Python 3.10.6) (pid: 1048262)
info 11:06:41.464: Process Execution: > ~/mambaforge/envs/torch/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/pythonFiles/printJupyterDataDir.py
> ~/mambaforge/envs/torch/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/pythonFiles/printJupyterDataDir.py
```

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
@xl0 Thanks for filing this issue, and sorry about this.
Just wanted to clarify, did this work in the previous version?

**Comment by xl0** [comment]
Yes, it works in the previous release and in Jupyter.

**Comment by DonJayamanne** [comment]
@xl0 
This issue has been resolved in tehe latest pre-release version of the Jupyter extension, please install that to get around this issue for now.

The latest pre-release version is `v2023.2.****`

Click the `Switch to Pre-Release Version` in the extension page (see below)
<img width="572" alt="Screenshot 2023-02-04 at 09 24 37" src="https://user-images.githubusercontent.com/1948812/216722719-fd8e14dc-783f-4859-8235-012b1bc796d9.png">

Please feel free to ping here or create a new issue if that still does not work

**Comment by xl0** [comment]
@DonJayamanne , thank you. It looks like the pre-release has an unrelated problem, as it fails to activate:

```
Visual Studio Code (1.75.0, undefined, desktop)
Jupyter Extension Version: 2023.2.1000392435.
Python Extension Version: 2023.2.0.
Workspace folder /home/xl0/work/tmp
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
error 11:57:06.977: Failure during activation. [Error: Extensions may only call createRendererMessaging() for renderers they contribute (got jupyter-error-renderer)
	at R.createRendererMessaging (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:95776)
	at Object.createRendererMessaging (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:117:51491)
	at Mw.activate (/home/xl0/.vscode/extensions/ms-toolsai.jupyter-2023.2.1000392435/out/extension.node.js:17:616628)
	at /home/xl0/.vscode/extensions/ms-toolsai.jupyter-2023.2.1000392435/out/extension.node.js:17:773870
	at Array.map (<anonymous>)
	at o_.activateSync (/home/xl0/.vscode/extensions/ms-toolsai.jupyter-2023.2.1000392435/out/extension.node.js:17:773860)
	at /home/xl0/.vscode/extensions/ms-toolsai.jupyter-2023.2.1000392435/out/extension.node.js:17:877444]
error 11:57:06.979: sendStartupTelemetry() failed. [Error: Extensions may only call createRendererMessaging() for renderers they contribute (got jupyter-error-renderer)
	at R.createRendererMessaging (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:95776)
	at Object.createRendererMessaging (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:117:51491)
	at Mw.activate (/home/xl0/.vscode/extensions/ms-toolsai.jupyter-2023.2.1000392435/out/extension.node.js:17:616628)
	at /home/xl0/.vscode/extensions/ms-toolsai.jupyter-2023.2.1000392435/out/extension.node.js:17:773870
	at Array.map (<anonymous>)
	at o_.activateSync (/home/xl0/.vscode/extensions/ms-toolsai.jupyter-2023.2.1000392435/out/extension.node.js:17:773860)
	at /home/xl0/.vscode/extensions/ms-toolsai.jupyter-2023.2.1000392435/out/extension.node.js:17:877444]
error 11:57:06.980: extension activation failed [Error: Extensions may only call createRendererMessaging() for renderers they contribute (got jupyter-error-renderer)
	at R.createRendererMessaging (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:95776)
	at Object.createRendererMessaging (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:117:51491)
	at Mw.activate (/home/xl0/.vscode/extensions/ms-toolsai.jupyter-2023.2.1000392435/out/extension.node.js:17:616628)
	at /home/xl0/.vscode/extensions/ms-toolsai.jupyter-2023.2.1000392435/out/extension.node.js:17:773870
	at Array.map (<anonymous>)
	at o_.activateSync (/home/xl0/.vscode/extensions/ms-toolsai.jupyter-2023.2.1000392435/out/extension.node.js:17:773860)
	at /home/xl0/.vscode/extensions/ms-toolsai.jupyter-2023.2.1000392435/out/extension.node.js:17:877444]
error 11:57:06.988: Failed to active the Jupyter Extension [Error: Extensions may only call createRendererMessaging() for renderers they contribute (got jupyter-error-renderer)
	at R.createRendererMessaging (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:95776)
	at Object.createRendererMessaging (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:117:51491)
	at Mw.activate (/home/xl0/.vscode/extensions/ms-toolsai.jupyter-2023.2.1000392435/out/extension.node.js:17:616628)
	at /home/xl0/.vscode/extensions/ms-toolsai.jupyter-2023.2.1000392435/out/extension.node.js:17:773870
	at Array.map (<anonymous>)
	at o_.activateSync (/home/xl0/.vscode/extensions/ms-toolsai.jupyter-2023.2.1000392435/out/extension.node.js:17:773860)
	at /home/xl0/.vscode/extensions/ms-toolsai.jupyter-2023.2.1000392435/out/extension.node.js:17:877444]
info 11:57:07.267: Find preferred kernel for /home/xl0/work/tmp/Untitled.ipynb with metadata {"kernelspec":{"display_name":"torch","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.10.6"},"vscode":{"interpreter":{"hash":"6be5eb67bb380238eb3fdb5608a5262f71c7ac5508d0890c6e2462bfc99ed11d"}}} & preferred interpreter /home/xl0/mambaforge/envs/torch/bin/python
info 11:57:07.267: Find preferred kernel for /home/xl0/work/tmp/Untitled.ipynb with metadata {"kernelspec":{"display_name":"torch","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.10.6"},"vscode":{"interpreter":{"hash":"6be5eb67bb380238eb3fdb5608a5262f71c7ac5508d0890c6e2462bfc99ed11d"}}} & preferred interpreter /home/xl0/mambaforge/envs/torch/bin/python
info 11:57:07.297: Find preferred kernel for /home/xl0/work/tmp/Untitled.ipynb with metadata {"kernelspec":{"display_name":"torch","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.10.6"},"vscode":{"interpreter":{"hash":"6be5eb67bb380238eb3fdb5608a5262f71c7ac5508d0890c6e2462bfc99ed11d"}}} & preferred interpreter /home/xl0/mambaforge/envs/torch/bin/python
info 11:57:07.298: Preferred kernel .jvsc74a57bd06be5eb67bb380238eb3fdb5608a5262f71c7ac5508d0890c6e2462bfc99ed11d./home/xl0/mambaforge/envs/torch/python./home/xl0/mambaforge/envs/torch/python.-m#ipykernel_launcher is exact match or top match for non python kernels, (true, [object Object], true, false)
info 11:57:07.298: PreferredConnection: .jvsc74a57bd06be5eb67bb380238eb3fdb5608a5262f71c7ac5508d0890c6e2462bfc99ed11d./home/xl0/mambaforge/envs/torch/python./home/xl0/mambaforge/envs/torch/python.-m#ipykernel_launcher found for NotebookDocument: /home/xl0/work/tmp/Untitled.ipynb
```

**Comment by DonJayamanne** [comment]
I will get that fixed asap
