### ISSUE TITLE
pyenv: jupyter-notebook: command not found

### ISSUE THREAD

**Issue by nagydavid** [microsoft/vscode-jupyter#12758]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I started to get the following error: 
Error code from Jupyter: 127.

I am using a Rosetta version of Python on Mac M1. Until now I did not have any issue.

The virtual env workflow of mine.:

- pyenv shell miniforge3-latest
- osx-64 conda create -n my_env
- conda activate my_env
- conda config --env --set subdir osx-64
- conda install jupyter

I tried with pipenv setup, also rosetta:

- arch --x86_64 /opt/homebrew/bin/pyenv install 3.10.6
- pyenv shell 3.10.6
- pipenv shell
- pip install jupyter

### VS Code Version

1.75

### Jupyter Extension Version

6.5.2

### Jupyter logs

```shell
error 09:42:29.297: Error in execution (get message for cell) Er [Error]: Jupyter server crashed. Unable to connect. 
Error code from Jupyter: 127
pyenv: jupyter-notebook: command not found


The `jupyter-notebook' command exists in these Python versions:

  miniforge3-latest/envs/owf_x86


Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.

    at Sm.rejectStartPromise (/Users/davidnagy/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:254981)
    at t._complete (/Users/davidnagy/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:255541)
    at t.n (/Users/davidnagy/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:700797)
    at t.__tryOrUnsub (/Users/davidnagy/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:701037)
    at t.complete (/Users/davidnagy/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:700930)
    at t._complete (/Users/davidnagy/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:699446)
    at t.complete (/Users/davidnagy/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:699145)
    at ChildProcess.<anonymous> (/Users/davidnagy/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:1800927)
    at Object.onceWrapper (node:events:646:26)
    at ChildProcess.emit (node:events:538:35)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  category: 'jupyterconnection'
}
```
```


### Coding Language and Runtime Version

python 3.10.6-9, 3.8.16, 3.9.16

### Language Extension Version (if applicable)

_No response_

### Anaconda Version (if applicable)

22.9.0

### Running Jupyter locally or remotely?

None

**Comment by DonJayamanne** [comment]
Sorry you are running into this issue and thanks for filing this issue.
A new version will be released (some time today/tomorrow), in the mean time please install the latest pre-release version of the Jupyter extension.

The latest pre-release version is `v2023.2.****`

Click the `Switch to Pre-Release Version` in the extension page (see below)
<img width="572" alt="Screenshot 2023-02-04 at 09 24 37" src="https://user-images.githubusercontent.com/1948812/216722719-fd8e14dc-783f-4859-8235-012b1bc796d9.png">

If the pre-release does not work please feel free to re-open this issue, comment on it or create a new issue and I will look into it

**Comment by DonJayamanne** [comment]
Closing this issue as I believe this has been resolved, and a new version will be released soon.
Once again you can install the pre-release version to get around this for now
