### ISSUE TITLE
Cell printout sometimes blank

### ISSUE THREAD

**Issue by philnagel** [microsoft/vscode-jupyter#12769]
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I use the interactive window feature in VSCode frequently. In this case,  I first used the "Run current file in interactive window" function, and then execute functions as needed directly in the interactive window.
I noticed that when running any given function, sometimes the cell itself that usually displays the function call and the time it took to run, would be blank.

When I run a function, the cell area should display the above-mentioned information. Instead, sometimes, the area is blank, the entire cell is missing, including its outline and the buttons (see below screenshot for a normal (8) and a broken cell (9)).

I was able to reproduce this with the following steps:

1. Place this function in a python file:
```
def tester():
    print('test') 
```
2. Run the file in a new interactive window.
3. In the interactive window, execute `tester()`.
4. Subsequently, execute again by using the up-arrow and shift+enter.
5. After several iterations, the behavior starts to happen on random executions.

This seemed to start after a recent update of VS Code, I am not sure which version I was on before. I also tried switching the Python extension and Jupyter to the pre-release versions, but this did not improve the behavior. 
I am able to reproduce this on my Windows machine when connecting to it via the VS Code Remote SSH extensions, and also directly on the Windows machine. I am also able to reproduce on my M1 Mac.

![image](https://user-images.githubusercontent.com/17130646/217378378-39251056-42ea-4c9e-bfbd-50806570d4c0.png)

### VS Code Version

1.75.0

### Jupyter Extension Version

v2023.1.2010391206

### Jupyter logs

```shell
Visual Studio Code (1.75.0, undefined, desktop)
Jupyter Extension Version: 2023.1.2010391206.
Python Extension Version: 2023.2.0.
No workspace folder opened.
warn 16:16:34.178: Exception while attempting zmq : No native build was found for platform=darwin arch=arm64 runtime=electron abi=106 uv=1 armv=8 libc=glibc node=16.14.2 electron=19.1.9
    loaded from: /Users/philna/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/node_modules/zeromq

User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 16:16:34.286: LSP Notebooks experiment is enabled
warn 16:16:34.405: No interpreter with path /Users/philna/miniconda3/envs/py38bmi/bin/python found in Python API, will convert Uri path to string as Id file:///Users/philna/miniconda3/envs/py38bmi/bin/python
info 16:16:36.044: Starting interactive window for resource '' with controller '.jvsc74a57bd0d6a5fd60f3d57f3ff394f219d50e0ed21b55ce24f29a9ec41616724bea57d880./Users/philna/miniconda3/envs/py38bmi/python./Users/philna/miniconda3/envs/py38bmi/python.-m#ipykernel_launcher (Interactive)'
info 16:16:36.112: Attempting to start a server because of preload conditions ...
info 16:16:36.113: Checking for server existence.
info 16:16:37.241: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd0d6a5fd60f3d57f3ff394f219d50e0ed21b55ce24f29a9ec41616724bea57d880./Users/philna/miniconda3/envs/py38bmi/python./Users/philna/miniconda3/envs/py38bmi/python.-m#ipykernel_launcher (Python Path: /Users/philna/miniconda3/envs/py38bmi, EnvType: Conda, EnvName: 'py38bmi', Version: 3.8.13 (default, Mar 28 2022, 06:13:39) 
[Clang 12.0.0 ]) for '/Interactive-1.interactive' (disableUI=false)
info 16:16:37.467: Process Execution: > ~/miniconda3/envs/py38bmi/bin/python -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> ~/miniconda3/envs/py38bmi/bin/python -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 16:16:37.468: Process Execution: > ~/miniconda3/envs/py38bmi/bin/python -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> ~/miniconda3/envs/py38bmi/bin/python -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 16:16:37.470: Process Execution: > ~/miniconda3/envs/py38bmi/bin/python -m pip list
> ~/miniconda3/envs/py38bmi/bin/python -m pip list
info 16:16:37.940: Process Execution: > ~/miniconda3/envs/py38bmi/bin/python -m jupyter kernelspec --version
> ~/miniconda3/envs/py38bmi/bin/python -m jupyter kernelspec --version
info 16:16:38.149: Connecting to server
info 16:16:38.149: Launching server
info 16:16:38.150: Starting Notebook
info 16:16:38.151: Generating custom default config at /var/folders/kd/k606zhh56r7f40v79633ygg89p8r0v/T/101ef4e9-4ac1-4c9b-975b-76c66adb1458/jupyter_notebook_config.py
Starting Jupyter from ~/miniconda3/envs/py38bmi/bin/python with arguments --no-browser --notebook-dir="/" --config=/var/folders/kd/k606zhh56r7f40v79633ygg89p8r0v/T/101ef4e9-4ac1-4c9b-975b-76c66adb1458/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
info 16:16:38.153: Process Execution: > ~/miniconda3/envs/py38bmi/bin/python -m jupyter notebook --no-browser --notebook-dir="/" --config=/var/folders/kd/k606zhh56r7f40v79633ygg89p8r0v/T/101ef4e9-4ac1-4c9b-975b-76c66adb1458/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
> ~/miniconda3/envs/py38bmi/bin/python -m jupyter notebook --no-browser --notebook-dir="/" --config=/var/folders/kd/k606zhh56r7f40v79633ygg89p8r0v/T/101ef4e9-4ac1-4c9b-975b-76c66adb1458/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
/Users/philna/miniconda3/envs/py38bmi/lib/python3.8/site-packages/traitlets/traitlets.py:2392: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/' instead of '"/"' if you require traitlets >=5.
  warn(
[W 2023-02-07 16:16:40.745 LabApp] 'notebook_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-02-07 16:16:40.745 LabApp] 'config_file' was found in both NotebookApp and ServerApp. This is likely a recent change. This config will only be set in NotebookApp. Please check if you should also config these traits in ServerApp for your purpose.
[W 2023-02-07 16:16:40.745 LabApp] 'iopub_data_rate_limit' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-02-07 16:16:40.745 LabApp] 'iopub_data_rate_limit' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-02-07 16:16:40.745 LabApp] 'iopub_data_rate_limit' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2023-02-07 16:16:40.749 LabApp] JupyterLab extension loaded from /Users/philna/miniconda3/envs/py38bmi/lib/python3.8/site-packages/jupyterlab
[I 2023-02-07 16:16:40.749 LabApp] JupyterLab application directory is /Users/philna/miniconda3/envs/py38bmi/share/jupyter/lab
[I 16:16:40.752 NotebookApp] Serving notebooks from local directory: /
[I 16:16:40.752 NotebookApp] Jupyter Notebook 6.4.12 is running at:
[I 16:16:40.752 NotebookApp] http://localhost:8888/?token=6d7079a116aa1d840ac36fd846238b292c9cccc526e52b82
[I 16:16:40.752 NotebookApp]  or http://127.0.0.1:8888/?token=6d7079a116aa1d840ac36fd846238b292c9cccc526e52b82
[I 16:16:40.752 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
info 16:16:40.754: Process Execution: > ~/miniconda3/envs/py38bmi/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> ~/miniconda3/envs/py38bmi/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/pythonFiles/vscode_datascience_helpers/getServerInfo.py
[C 16:16:40.762 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/philna/Library/Jupyter/runtime/nbserver-40834-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=6d7079a116aa1d840ac36fd846238b292c9cccc526e52b82
     or http://127.0.0.1:8888/?token=6d7079a116aa1d840ac36fd846238b292c9cccc526e52b82
info 16:16:40.764: Process Execution: > ~/miniconda3/envs/py38bmi/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> ~/miniconda3/envs/py38bmi/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/pythonFiles/vscode_datascience_helpers/getServerInfo.py
info 16:16:41.371: Connecting server kernel http://localhost:8888/
info 16:16:41.371: Creating server with url : http://localhost:8888/
info 16:16:41.374: Server started.
[I 16:16:41.810 NotebookApp] Creating new notebook in 
[E 16:16:41.868 NotebookApp] Error while saving file: Untitled.ipynb [Errno 30] Read-only file system: '/Untitled.ipynb'
    Traceback (most recent call last):
      File "/Users/philna/miniconda3/envs/py38bmi/lib/python3.8/site-packages/notebook/services/contents/filemanager.py", line 493, in save
        self._save_notebook(os_path, nb)
      File "/Users/philna/miniconda3/envs/py38bmi/lib/python3.8/site-packages/notebook/services/contents/fileio.py", line 289, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/Users/philna/miniconda3/envs/py38bmi/lib/python3.8/contextlib.py", line 113, in __enter__
        return next(self.gen)
      File "/Users/philna/miniconda3/envs/py38bmi/lib/python3.8/site-packages/notebook/services/contents/fileio.py", line 209, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/Users/philna/miniconda3/envs/py38bmi/lib/python3.8/contextlib.py", line 113, in __enter__
        return next(self.gen)
      File "/Users/philna/miniconda3/envs/py38bmi/lib/python3.8/site-packages/notebook/services/contents/fileio.py", line 104, in atomic_writing
        fileobj = open(path, 'w', encoding=encoding, **kwargs)
    OSError: [Errno 30] Read-only file system: '/Untitled.ipynb'
[W 16:16:41.899 NotebookApp] 500 POST /api/contents?1675808201375 (127.0.0.1): Unexpected error while saving file: Untitled.ipynb [Errno 30] Read-only file system: '/Untitled.ipynb'
[W 16:16:41.899 NotebookApp] Unexpected error while saving file: Untitled.ipynb [Errno 30] Read-only file system: '/Untitled.ipynb'
[E 16:16:41.899 NotebookApp] {
      "Host": "localhost:8888",
      "Accept": "*/*",
      "User-Agent": "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
    }
[E 16:16:41.899 NotebookApp] 500 POST /api/contents?1675808201375 (127.0.0.1) 521.020000ms referer=None
[I 16:16:41.905 NotebookApp] Creating new notebook in 
[E 16:16:41.907 NotebookApp] Error while saving file: Untitled.ipynb [Errno 30] Read-only file system: '/Untitled.ipynb'
    Traceback (most recent call last):
      File "/Users/philna/miniconda3/envs/py38bmi/lib/python3.8/site-packages/notebook/services/contents/filemanager.py", line 493, in save
        self._save_notebook(os_path, nb)
      File "/Users/philna/miniconda3/envs/py38bmi/lib/python3.8/site-packages/notebook/services/contents/fileio.py", line 289, in _save_notebook
        with self.atomic_writing(os_path, encoding='utf-8') as f:
      File "/Users/philna/miniconda3/envs/py38bmi/lib/python3.8/contextlib.py", line 113, in __enter__
        return next(self.gen)
      File "/Users/philna/miniconda3/envs/py38bmi/lib/python3.8/site-packages/notebook/services/contents/fileio.py", line 209, in atomic_writing
        with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
      File "/Users/philna/miniconda3/envs/py38bmi/lib/python3.8/contextlib.py", line 113, in __enter__
        return next(self.gen)
      File "/Users/philna/miniconda3/envs/py38bmi/lib/python3.8/site-packages/notebook/services/contents/fileio.py", line 104, in atomic_writing
        fileobj = open(path, 'w', encoding=encoding, **kwargs)
    OSError: [Errno 30] Read-only file system: '/Untitled.ipynb'
[W 16:16:41.907 NotebookApp] 500 POST /api/contents?1675808201900 (127.0.0.1): Unexpected error while saving file: Untitled.ipynb [Errno 30] Read-only file system: '/Untitled.ipynb'
[W 16:16:41.907 NotebookApp] Unexpected error while saving file: Untitled.ipynb [Errno 30] Read-only file system: '/Untitled.ipynb'
info 16:16:41.908: installMissingDependencies /Users/philna/miniconda3/envs/py38bmi/bin/python, ui.disabled=false for resource ''
info 16:16:41.909: Process Execution: > ~/miniconda3/envs/py38bmi/bin/python -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> ~/miniconda3/envs/py38bmi/bin/python -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
[E 16:16:41.907 NotebookApp] {
      "Host": "localhost:8888",
      "Accept": "*/*",
      "User-Agent": "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
    }
[E 16:16:41.907 NotebookApp] 500 POST /api/contents?1675808201900 (127.0.0.1) 2.910000ms referer=None
info 16:16:42.073: Spec argv[0] updated from '/Users/philna/miniconda3/envs/py38bmi/bin/python' to '/Users/philna/miniconda3/envs/py38bmi/bin/python'
[I 16:16:42.122 NotebookApp] Kernel started: 535ee16d-8bd2-4620-88f7-68e814d25157, name: pythonjvsc74a57bd0d6a5fd60f3d57f3ff394f219d50e0ed21b55ce24f29a9ec41616724bea57d880
[IPKernelApp] WARNING | Unknown error in handling startup files:
info 16:16:43.362: Started session for kernel startUsingPythonInterpreter:.jvsc74a57bd0d6a5fd60f3d57f3ff394f219d50e0ed21b55ce24f29a9ec41616724bea57d880./Users/philna/miniconda3/envs/py38bmi/python./Users/philna/miniconda3/envs/py38bmi/python.-m#ipykernel_launcher
info 16:16:43.386: Process Execution: > ~/miniconda3/envs/py38bmi/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/pythonFiles/printJupyterDataDir.py
> ~/miniconda3/envs/py38bmi/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/pythonFiles/printJupyterDataDir.py
warn 16:16:43.426: Got a non-existent Jupyer Data Dir file:///Users/philna/.local/share/jupyter
info 16:16:43.651: Generated code for 1 = <ipython-input-1-2938fa9b886f> with 2 lines
```

### Coding Language and Runtime Version

Python 3.8.13 & 3.7.11

### Language Extension Version (if applicable)

v2023.2.0

### Running Jupyter locally or remotely?

Both

**Comment by roblourens** [comment]
I believe this is https://github.com/microsoft/vscode/issues/173590, fix en route
