### ISSUE TITLE
Poetry Environments do not seem to work with interactive setups anymore

### ISSUE THREAD

**Issue by macintacos** [microsoft/vscode-jupyter#12761]
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I've done the following many times in the past:

1. Open up my Poetry project in VSCode
2. Encounter an issue I want to prototype using a new interactive shell script. To do this, I always did the following:
	1. Create a new Untitled editor
	2. Switch to Python language
	3. Type `# %%` at the top.
	4. Code up what I want to test.
	5. _Because the projects I work on cannot have their dependencies modified directly,_ I go to my terminal, `poetry shell` to activate the environment, and then manually run `pip install ipykernel` - this doesn't update our dependencies but allows me to mess around/prototype as I see fit. After doing this, I could go and click "Run Cell" on my test code and it would always "just work".

For some reason, the above doesn't work anymore. I'm not sure if this is purely an issue with the Python's extension (I just filed an issue about Poetry environments so maybe it's related: https://github.com/microsoft/vscode-python/issues/20658) or this one, but no matter what I do (even if I give up and add `ipykernel` _to my project dependencies directly_) I get the following error:

```
Running cells with 'xbar-plugins-dmDxmpHP-py3.10' requires the ipykernel package.
Run the following command to install 'ipykernel' into the Python environment. 
Command: '/ -m pip install ipykernel -U --force-reinstall'
```

I activate the environment and run `python -m pip install ipykernel -U --force-reinstall` and it installs stuff, but no matter what I continue to get that error. The logs even seem to suggest that I don't have `pip` installed in my current environment, which doesn't make sense (and isn't true anyway):

```
$ which pip
/Users/macinburrito/Library/Caches/pypoetry/virtualenvs/xbar-plugins-dmDxmpHP-py3.10/bin/pip
```

Any ideas what could be going on here?

### VS Code Version

1.75.0

### Jupyter Extension Version

v2023.1.2000312134

### Jupyter logs

```shell
warn 10:28:56.226: Module pip not installed in environment /Users/macinburrito/Library/Caches/pypoetry/virtualenvs/xbar-plugins-dmDxmpHP-py3.10/bin/python Error: spawn / EACCES
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /',
  path: '/',
  spawnargs: [ '-c', "import pip;print('6af208d0-cb9c-427f-b937-ff563e17efdf')" ]
}
error 10:28:58.607: Failed to change kernel, re-throwing df [Error]: Kernel xbar-plugins-dmDxmpHP-py3.10 (Python 3.10.9) is not usable. Check the Jupyter output tab for more information.
    at Vf.ensureKernelIsUsable (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:221498)
    at Um.createSession (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:277363)
    at Um.createNewKernelSession (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:274988)
    at Um.connect (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:273916)
    at Km.startNew (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:281707)
    at a (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:245682)
    at lm.createNotebookInstance (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:245833)
    at lm.createNotebook (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:246529)
    at Zm.createJupyterSession (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:306419) {
  category: 'noipykernel',
  kernelConnectionMetadata: Zd {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: '/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/temp/jupyter/kernels/pythonjvsc74a57bd01e3066baed583ed4330843280cbc2bd87df1fc3b574d795c6f1aacbf79986a36/kernel.json',
      interpreterPath: '/Users/macinburrito/Library/Caches/pypoetry/virtualenvs/xbar-plugins-dmDxmpHP-py3.10/bin/python',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'pythonjvsc74a57bd01e3066baed583ed4330843280cbc2bd87df1fc3b574d795c6f1aacbf79986a36',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: 'xbar-plugins-dmDxmpHP-py3.10',
      metadata: [Object],
      env: {}
    },
    interpreter: {
      id: '/Users/macinburrito/Library/Caches/pypoetry/virtualenvs/xbar-plugins-dmDxmpHP-py3.10/bin/python',
      sysPrefix: '/Users/macinburrito/Library/Caches/pypoetry/virtualenvs/xbar-plugins-dmDxmpHP-py3.10',
      envPath: [f],
      displayPath: [Object],
      envName: 'xbar-plugins-dmDxmpHP-py3.10',
      displayName: 'xbar-plugins-dmDxmpHP-py3.10',
      envType: 'Poetry',
      version: [Object],
      uri: [f]
    },
    id: '.jvsc74a57bd01e3066baed583ed4330843280cbc2bd87df1fc3b574d795c6f1aacbf79986a36./Users/macinburrito/Library/Caches/pypoetry/virtualenvs/xbar-plugins-dmDxmpHP-py3.10/python./Users/macinburrito/Library/Caches/pypoetry/virtualenvs/xbar-plugins-dmDxmpHP-py3.10/python.-m#ipykernel_launcher'
  },
  reason: 1
}
warn 10:28:58.608: Error occurred while trying to start the kernel, options.disableUI=false df [Error]: Kernel xbar-plugins-dmDxmpHP-py3.10 (Python 3.10.9) is not usable. Check the Jupyter output tab for more information.
    at Vf.ensureKernelIsUsable (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:221498)
    at Um.createSession (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:277363)
    at Um.createNewKernelSession (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:274988)
    at Um.connect (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:273916)
    at Km.startNew (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:281707)
    at a (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:245682)
    at lm.createNotebookInstance (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:245833)
    at lm.createNotebook (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:246529)
    at Zm.createJupyterSession (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:306419) {
  category: 'noipykernel',
  kernelConnectionMetadata: Zd {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: '/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/temp/jupyter/kernels/pythonjvsc74a57bd01e3066baed583ed4330843280cbc2bd87df1fc3b574d795c6f1aacbf79986a36/kernel.json',
      interpreterPath: '/Users/macinburrito/Library/Caches/pypoetry/virtualenvs/xbar-plugins-dmDxmpHP-py3.10/bin/python',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'pythonjvsc74a57bd01e3066baed583ed4330843280cbc2bd87df1fc3b574d795c6f1aacbf79986a36',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: 'xbar-plugins-dmDxmpHP-py3.10',
      metadata: [Object],
      env: {}
    },
    interpreter: {
      id: '/Users/macinburrito/Library/Caches/pypoetry/virtualenvs/xbar-plugins-dmDxmpHP-py3.10/bin/python',
      sysPrefix: '/Users/macinburrito/Library/Caches/pypoetry/virtualenvs/xbar-plugins-dmDxmpHP-py3.10',
      envPath: [f],
      displayPath: [Object],
      envName: 'xbar-plugins-dmDxmpHP-py3.10',
      displayName: 'xbar-plugins-dmDxmpHP-py3.10',
      envType: 'Poetry',
      version: [Object],
      uri: [f]
    },
    id: '.jvsc74a57bd01e3066baed583ed4330843280cbc2bd87df1fc3b574d795c6f1aacbf79986a36./Users/macinburrito/Library/Caches/pypoetry/virtualenvs/xbar-plugins-dmDxmpHP-py3.10/python./Users/macinburrito/Library/Caches/pypoetry/virtualenvs/xbar-plugins-dmDxmpHP-py3.10/python.-m#ipykernel_launcher'
  },
  reason: 1
}
warn 10:28:58.609: Kernel Error, context = start df [Error]: Kernel xbar-plugins-dmDxmpHP-py3.10 (Python 3.10.9) is not usable. Check the Jupyter output tab for more information.
    at Vf.ensureKernelIsUsable (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:221498)
    at Um.createSession (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:277363)
    at Um.createNewKernelSession (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:274988)
    at Um.connect (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:273916)
    at Km.startNew (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:281707)
    at a (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:245682)
    at lm.createNotebookInstance (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:245833)
    at lm.createNotebook (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:246529)
    at Zm.createJupyterSession (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:306419) {
  category: 'noipykernel',
  kernelConnectionMetadata: Zd {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: '/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/temp/jupyter/kernels/pythonjvsc74a57bd01e3066baed583ed4330843280cbc2bd87df1fc3b574d795c6f1aacbf79986a36/kernel.json',
      interpreterPath: '/Users/macinburrito/Library/Caches/pypoetry/virtualenvs/xbar-plugins-dmDxmpHP-py3.10/bin/python',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'pythonjvsc74a57bd01e3066baed583ed4330843280cbc2bd87df1fc3b574d795c6f1aacbf79986a36',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: 'xbar-plugins-dmDxmpHP-py3.10',
      metadata: [Object],
      env: {}
    },
    interpreter: {
      id: '/Users/macinburrito/Library/Caches/pypoetry/virtualenvs/xbar-plugins-dmDxmpHP-py3.10/bin/python',
      sysPrefix: '/Users/macinburrito/Library/Caches/pypoetry/virtualenvs/xbar-plugins-dmDxmpHP-py3.10',
      envPath: [f],
      displayPath: [Object],
      envName: 'xbar-plugins-dmDxmpHP-py3.10',
      displayName: 'xbar-plugins-dmDxmpHP-py3.10',
      envType: 'Poetry',
      version: [Object],
      uri: [f]
    },
    id: '.jvsc74a57bd01e3066baed583ed4330843280cbc2bd87df1fc3b574d795c6f1aacbf79986a36./Users/macinburrito/Library/Caches/pypoetry/virtualenvs/xbar-plugins-dmDxmpHP-py3.10/python./Users/macinburrito/Library/Caches/pypoetry/virtualenvs/xbar-plugins-dmDxmpHP-py3.10/python.-m#ipykernel_launcher'
  },
  reason: 1
}
warn 10:28:58.609: Jupyter Kernel Dependency Error, reason=1 df [Error]: Kernel xbar-plugins-dmDxmpHP-py3.10 (Python 3.10.9) is not usable. Check the Jupyter output tab for more information.
    at Vf.ensureKernelIsUsable (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:221498)
    at Um.createSession (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:277363)
    at Um.createNewKernelSession (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:274988)
    at Um.connect (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:273916)
    at Km.startNew (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:281707)
    at a (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:245682)
    at lm.createNotebookInstance (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:245833)
    at lm.createNotebook (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:246529)
    at Zm.createJupyterSession (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:306419) {
  category: 'noipykernel',
  kernelConnectionMetadata: Zd {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: '/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/temp/jupyter/kernels/pythonjvsc74a57bd01e3066baed583ed4330843280cbc2bd87df1fc3b574d795c6f1aacbf79986a36/kernel.json',
      interpreterPath: '/Users/macinburrito/Library/Caches/pypoetry/virtualenvs/xbar-plugins-dmDxmpHP-py3.10/bin/python',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'pythonjvsc74a57bd01e3066baed583ed4330843280cbc2bd87df1fc3b574d795c6f1aacbf79986a36',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: 'xbar-plugins-dmDxmpHP-py3.10',
      metadata: [Object],
      env: {}
    },
    interpreter: {
      id: '/Users/macinburrito/Library/Caches/pypoetry/virtualenvs/xbar-plugins-dmDxmpHP-py3.10/bin/python',
      sysPrefix: '/Users/macinburrito/Library/Caches/pypoetry/virtualenvs/xbar-plugins-dmDxmpHP-py3.10',
      envPath: [f],
      displayPath: [Object],
      envName: 'xbar-plugins-dmDxmpHP-py3.10',
      displayName: 'xbar-plugins-dmDxmpHP-py3.10',
      envType: 'Poetry',
      version: [Object],
      uri: [f]
    },
    id: '.jvsc74a57bd01e3066baed583ed4330843280cbc2bd87df1fc3b574d795c6f1aacbf79986a36./Users/macinburrito/Library/Caches/pypoetry/virtualenvs/xbar-plugins-dmDxmpHP-py3.10/python./Users/macinburrito/Library/Caches/pypoetry/virtualenvs/xbar-plugins-dmDxmpHP-py3.10/python.-m#ipykernel_launcher'
  },
  reason: 1
}
info 10:28:58.609: Dispose Kernel '/Interactive-1.interactive' associated with 'Untitled-1'
error 10:28:58.610: Error in execution (get message for cell) df [Error]: Kernel xbar-plugins-dmDxmpHP-py3.10 (Python 3.10.9) is not usable. Check the Jupyter output tab for more information.
    at Vf.ensureKernelIsUsable (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:221498)
    at Um.createSession (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:277363)
    at Um.createNewKernelSession (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:274988)
    at Um.connect (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:273916)
    at Km.startNew (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:281707)
    at a (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:245682)
    at lm.createNotebookInstance (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:245833)
    at lm.createNotebook (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:246529)
    at Zm.createJupyterSession (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:306419) {
  category: 'noipykernel',
  kernelConnectionMetadata: Zd {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: '/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/temp/jupyter/kernels/pythonjvsc74a57bd01e3066baed583ed4330843280cbc2bd87df1fc3b574d795c6f1aacbf79986a36/kernel.json',
      interpreterPath: '/Users/macinburrito/Library/Caches/pypoetry/virtualenvs/xbar-plugins-dmDxmpHP-py3.10/bin/python',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'pythonjvsc74a57bd01e3066baed583ed4330843280cbc2bd87df1fc3b574d795c6f1aacbf79986a36',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: 'xbar-plugins-dmDxmpHP-py3.10',
      metadata: [Object],
      env: {}
    },
    interpreter: {
      id: '/Users/macinburrito/Library/Caches/pypoetry/virtualenvs/xbar-plugins-dmDxmpHP-py3.10/bin/python',
      sysPrefix: '/Users/macinburrito/Library/Caches/pypoetry/virtualenvs/xbar-plugins-dmDxmpHP-py3.10',
      envPath: [f],
      displayPath: [Object],
      envName: 'xbar-plugins-dmDxmpHP-py3.10',
      displayName: 'xbar-plugins-dmDxmpHP-py3.10',
      envType: 'Poetry',
      version: [Object],
      uri: [f]
    },
    id: '.jvsc74a57bd01e3066baed583ed4330843280cbc2bd87df1fc3b574d795c6f1aacbf79986a36./Users/macinburrito/Library/Caches/pypoetry/virtualenvs/xbar-plugins-dmDxmpHP-py3.10/python./Users/macinburrito/Library/Caches/pypoetry/virtualenvs/xbar-plugins-dmDxmpHP-py3.10/python.-m#ipykernel_launcher'
  },
  reason: 1
}
warn 10:28:58.610: DataScience Error df [Error]: Kernel xbar-plugins-dmDxmpHP-py3.10 (Python 3.10.9) is not usable. Check the Jupyter output tab for more information.
    at Vf.ensureKernelIsUsable (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:221498)
    at Um.createSession (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:277363)
    at Um.createNewKernelSession (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:274988)
    at Um.connect (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:273916)
    at Km.startNew (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:281707)
    at a (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:245682)
    at lm.createNotebookInstance (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:245833)
    at lm.createNotebook (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:246529)
    at Zm.createJupyterSession (/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:306419) {
  category: 'noipykernel',
  kernelConnectionMetadata: Zd {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: '/Users/macinburrito/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/temp/jupyter/kernels/pythonjvsc74a57bd01e3066baed583ed4330843280cbc2bd87df1fc3b574d795c6f1aacbf79986a36/kernel.json',
      interpreterPath: '/Users/macinburrito/Library/Caches/pypoetry/virtualenvs/xbar-plugins-dmDxmpHP-py3.10/bin/python',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'pythonjvsc74a57bd01e3066baed583ed4330843280cbc2bd87df1fc3b574d795c6f1aacbf79986a36',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: 'xbar-plugins-dmDxmpHP-py3.10',
      metadata: [Object],
      env: {}
    },
    interpreter: {
      id: '/Users/macinburrito/Library/Caches/pypoetry/virtualenvs/xbar-plugins-dmDxmpHP-py3.10/bin/python',
      sysPrefix: '/Users/macinburrito/Library/Caches/pypoetry/virtualenvs/xbar-plugins-dmDxmpHP-py3.10',
      envPath: [f],
      displayPath: [Object],
      envName: 'xbar-plugins-dmDxmpHP-py3.10',
      displayName: 'xbar-plugins-dmDxmpHP-py3.10',
      envType: 'Poetry',
      version: [Object],
      uri: [f]
    },
    id: '.jvsc74a57bd01e3066baed583ed4330843280cbc2bd87df1fc3b574d795c6f1aacbf79986a36./Users/macinburrito/Library/Caches/pypoetry/virtualenvs/xbar-plugins-dmDxmpHP-py3.10/python./Users/macinburrito/Library/Caches/pypoetry/virtualenvs/xbar-plugins-dmDxmpHP-py3.10/python.-m#ipykernel_launcher'
  },
  reason: 1
}
[W 10:28:58.613 NotebookApp] delete /Untitled-1-jvsc-e7525c1b-dd00-4a82-ae2d-f15322ab7664be713a66-8aaa-4fbf-a1a4-6772ab75ac2f.ipynb
```

### Coding Language and Runtime Version

Python 3.10.9, Poetry 1.3.2

### Language Extension Version (if applicable)

v2023.2.0

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
@macintacos 
Please could you try installing the latest release (a new version was released earlier today), please install that and let me know how things go
If that does not work, then please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by DonJayamanne** [comment]
Closing this issue as I believe this has been resolved, if it does not work please feel free to ping here and I'll re-open this or please re-open this issue or create a new one and I'll look into it

**Comment by macintacos** [comment]
Seems to work great now, thanks!
