### ISSUE TITLE
Kernal Unable to Shutdown on Closing the File

### ISSUE THREAD

**Issue by AaronNing** [microsoft/vscode-jupyter#12774]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

NOTE: similar to the closed issue #9442 .

Hi! This problem exists in vscode jupyter extension v2023.1.2000312134 and the pre-released v2023.2.1000381022. Closing the notebook in the vscode window does not shutdown the kernal. 

vscode version: 1.75.0

When doing this:

> Set this setting to 'verbose'
> `"jupyter.loggingLevel": "verbose"`
> Open a notebook
> Run a cell
> Clear the jupyter output window after the cell finishes running
> Close the notebook
> Send back the output from the jupyter output tab again.

where the notebook is put in path `/home/UNAME_MASKED/projects/PROJ_NAME_MASKED/notebooks/data/test_shutdown.ipynb` and the following commands are run:
```
import torch
torch.randn([1000,1000,1000]).to('cuda:4')
```

**No outputs** showed during clearing, saving or closing. 

---

However, copying the notebook to my user directory (`~/`), and then repeating the test steps, makes the notebook **successfully** shutdown on close.
In this case, here's the outputs when closing the tag:
```
info 13:38:33.725: Disposing kernel .jvsc74a57bd0bc647066252c151e8b77172140ebafaaf9f6fd759b9f41976512ca56a38c2bc9./home/UNAME_MASKED/miniconda3/envs/sc/python./home/UNAME_MASKED/miniconda3/envs/sc/python.-m#ipykernel_launcher for notebook /home/UNAME_MASKED/test_shutdown.ipynb due to selection of another kernel or closing of the notebook
info 13:38:33.725: Dispose Kernel '/home/UNAME_MASKED/test_shutdown.ipynb' associated with '/home/UNAME_MASKED/test_shutdown.ipynb'
debug 13:38:33.726: Cancel pending cells
debug 13:38:33.726: Shutdown session - current session, called from Error: 
	at Bp.shutdownImplementation (/home/UNAME_MASKED/.vscode-server/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:134167)
	at Bp.dispose (/home/UNAME_MASKED/.vscode-server/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:128671)
	at /home/UNAME_MASKED/.vscode-server/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:302456
	at Zm.dispose (/home/UNAME_MASKED/.vscode-server/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:302664)
	at _v.onDidChangeSelectedNotebooks (/home/UNAME_MASKED/.vscode-server/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:478382)
	at f.invoke (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at g.deliver (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
	at d.fire (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
	at C.$acceptNotebookAssociation (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:98:90730)
	at l.N (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:106:11239)
	at l.M (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:106:10957)
	at l.H (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:106:10044)
	at l.G (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:106:9022)
	at /home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:106:7810
	at f.invoke (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at g.deliver (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
	at d.fire (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
	at p.fire (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:72:14861)
	at /home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:122:15815
	at f.invoke (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at g.deliver (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
	at d.fire (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
	at p.fire (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:72:14861)
	at t.E (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:72:18927)
	at /home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:72:16915
	at f.invoke (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at g.deliver (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
	at d.fire (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
	at h.acceptChunk (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:72:12592)
	at /home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:72:11879
	at f.invoke (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at g.deliver (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
	at d.fire (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
	at d.t (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:72:28518)
debug 13:38:33.727: shutdownSession c43509ad-fa20-4b7b-b9e3-d4d0c73afa79, .jvsc74a57bd0bc647066252c151e8b77172140ebafaaf9f6fd759b9f41976512ca56a38c2bc9./home/UNAME_MASKED/miniconda3/envs/sc/python./home/UNAME_MASKED/miniconda3/envs/sc/python.-m#ipykernel_launcher - start
debug 13:38:33.727: Session can be shutdown .jvsc74a57bd0bc647066252c151e8b77172140ebafaaf9f6fd759b9f41976512ca56a38c2bc9./home/UNAME_MASKED/miniconda3/envs/sc/python./home/UNAME_MASKED/miniconda3/envs/sc/python.-m#ipykernel_launcher
info 13:38:33.727: Dispose Kernel process 136351.
debug 13:38:33.743: Kernel got disposed, hence there is no longer a kernel associated with /home/UNAME_MASKED/test_shutdown.ipynb
debug 13:38:33.745: Disposing request as the cell was deleted /home/UNAME_MASKED/test_shutdown.ipynb
debug 13:38:33.754: Cancel executions after closing notebook /home/UNAME_MASKED/test_shutdown.ipynb
debug 13:38:33.757: Storing Preferred remote kernel for /home/UNAME_MASKED/test_shutdown.ipynb is undefined
debug 13:38:33.794: Disposed Kernel process 136351.
debug 13:38:33.794: shutdownSession c43509ad-fa20-4b7b-b9e3-d4d0c73afa79, .jvsc74a57bd0bc647066252c151e8b77172140ebafaaf9f6fd759b9f41976512ca56a38c2bc9./home/UNAME_MASKED/miniconda3/envs/sc/python./home/UNAME_MASKED/miniconda3/envs/sc/python.-m#ipykernel_launcher - shutdown complete
debug 13:38:33.796: Shutdown session - get restart session
debug 13:38:33.796: Shutdown session -- complete
debug 13:38:34.314: KernelProcess Exit Exit - undefined /home/UNAME_MASKED/miniconda3/envs/sc/lib/python3.8/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
/home/UNAME_MASKED/miniconda3/envs/sc/lib/python3.8/site-packages/traitlets/traitlets.py:2366: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '23078666-3236-480e-a3d6-28187eb88f39' instead of 'b"23078666-3236-480e-a3d6-28187eb88f39"'.
  warn(
```

### VS Code Version

1.75.0

### Jupyter Extension Version

v2023.1.2000312134

### Running Jupyter locally or remotely?

None

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.
* 

Please close the notebook and provide the logs

**Comment by AaronNing** [comment]
> Please could you enable logging as follows:
> 
> * Open settings & go into `Jupyter->Logging`
> * Change the value to `verbose`
> * Reload VS Code,
> * Attempt to repro the issue & then copy the output from the `Jupyter` output panel.
> 
> Please close the notebook and provide the logs

Thanks, sure.

**NOTE**: After closing all notebooks and reloading vscode, I find the problem disappeared. Here are the log outputs. However, I am pretty sure the problem exists in some situations, maybe when I have too many notebooks opened. When I find this problem the next time, I will reopen the issue and provide the complete logs. Thank you!

Here are the logs when **I tried to reproduce the issue but failed**. I am not sure it is helpful or not, so I attach them here ayway.

#### reload vscode and open the notebook
```
too long for github, needed?
```

#### run the cells
```
too long for github, needed?
```

#### clear all outputs, save and close
```
info 13:28:23.231: Disposing kernel .jvsc74a57bd0bc647066252c151e8b77172140ebafaaf9f6fd759b9f41976512ca56a38c2bc9./home/UNAME_MASKED/miniconda3/envs/sc/python./home/UNAME_MASKED/miniconda3/envs/sc/python.-m#ipykernel_launcher for notebook /home/UNAME_MASKED/projects/PNAME_MASKED/notebooks/MERFISH/test_shutdown.ipynb due to selection of another kernel or closing of the notebook
info 13:28:23.231: Dispose Kernel '/home/UNAME_MASKED/projects/PNAME_MASKED/notebooks/MERFISH/test_shutdown.ipynb' associated with '/home/UNAME_MASKED/projects/PNAME_MASKED/notebooks/MERFISH/test_shutdown.ipynb'
debug 13:28:23.232: Cancel pending cells
debug 13:28:23.233: Shutdown session - current session, called from Error: 
	at Bp.shutdownImplementation (/home/UNAME_MASKED/.vscode-server/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:17:134167)
	at Bp.dispose (/home/UNAME_MASKED/.vscode-server/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:17:128671)
	at /home/UNAME_MASKED/.vscode-server/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:17:302456
	at Zm.dispose (/home/UNAME_MASKED/.vscode-server/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:17:302664)
	at _v.onDidChangeSelectedNotebooks (/home/UNAME_MASKED/.vscode-server/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:17:478382)
	at f.invoke (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at g.deliver (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
	at d.fire (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
	at C.$acceptNotebookAssociation (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:98:90730)
	at l.N (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:106:11239)
	at l.M (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:106:10957)
	at l.H (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:106:10044)
	at l.G (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:106:9022)
	at /home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:106:7810
	at f.invoke (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at g.deliver (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
	at d.fire (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
	at p.fire (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:72:14861)
	at /home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:122:15815
	at f.invoke (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at g.deliver (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
	at d.fire (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
	at p.fire (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:72:14861)
	at t.E (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:72:18927)
	at /home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:72:16915
	at f.invoke (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at g.deliver (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
	at d.fire (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
	at h.acceptChunk (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:72:12592)
	at /home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:72:11879
	at f.invoke (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at g.deliver (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
	at d.fire (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
	at d.t (/home/UNAME_MASKED/.vscode-server/bin/e2816fe719a4026ffa1ee0189dc89bdfdbafb164/out/vs/workbench/api/node/extensionHostProcess.js:72:28518)
debug 13:28:23.234: shutdownSession 2e1f899c-233b-490d-a004-bfbd5d3ac1c1, .jvsc74a57bd0bc647066252c151e8b77172140ebafaaf9f6fd759b9f41976512ca56a38c2bc9./home/UNAME_MASKED/miniconda3/envs/sc/python./home/UNAME_MASKED/miniconda3/envs/sc/python.-m#ipykernel_launcher - start
debug 13:28:23.234: Session can be shutdown .jvsc74a57bd0bc647066252c151e8b77172140ebafaaf9f6fd759b9f41976512ca56a38c2bc9./home/UNAME_MASKED/miniconda3/envs/sc/python./home/UNAME_MASKED/miniconda3/envs/sc/python.-m#ipykernel_launcher
info 13:28:23.234: Dispose Kernel process 132864.
debug 13:28:23.250: Kernel got disposed, hence there is no longer a kernel associated with /home/UNAME_MASKED/projects/PNAME_MASKED/notebooks/MERFISH/test_shutdown.ipynb
debug 13:28:23.256: Disposing request as the cell was deleted /home/UNAME_MASKED/projects/PNAME_MASKED/notebooks/MERFISH/test_shutdown.ipynb
debug 13:28:23.260: Cancel executions after closing notebook /home/UNAME_MASKED/projects/PNAME_MASKED/notebooks/MERFISH/test_shutdown.ipynb
debug 13:28:23.264: Storing Preferred remote kernel for /home/UNAME_MASKED/projects/PNAME_MASKED/notebooks/MERFISH/test_shutdown.ipynb is undefined
debug 13:28:23.299: Disposed Kernel process 132864.
debug 13:28:23.299: shutdownSession 2e1f899c-233b-490d-a004-bfbd5d3ac1c1, .jvsc74a57bd0bc647066252c151e8b77172140ebafaaf9f6fd759b9f41976512ca56a38c2bc9./home/UNAME_MASKED/miniconda3/envs/sc/python./home/UNAME_MASKED/miniconda3/envs/sc/python.-m#ipykernel_launcher - shutdown complete
debug 13:28:23.302: Shutdown session - get restart session
debug 13:28:23.302: Shutdown session -- complete
debug 13:28:23.585: KernelProcess Exit Exit - undefined /home/UNAME_MASKED/miniconda3/envs/sc/lib/python3.8/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
/home/UNAME_MASKED/miniconda3/envs/sc/lib/python3.8/site-packages/traitlets/traitlets.py:2366: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '401e7d8c-05c4-4768-bbe4-decaf11f0118' instead of 'b"401e7d8c-05c4-4768-bbe4-decaf11f0118"'.
  warn(
```

**Comment by DonJayamanne** [comment]
@AaronNing 
sorry i missed this
Yes, the logs are requried, please could you save them to a text file and then upload the text files to an issue here

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.

**Comment by cipri-tom** [comment]
Hello,

I am seeing the same issue. I have set logging to Verbose, then reloaded the window. Here attached you will find the logs.

- At 13:00, I have reloaded the window.
- I wait one minute. At 13:01, I opened the notebook
- I wait one minute. At 13:02, I ran the first cell
- I wait one minute. At 13:03, I close the notebook (you will notice there is no entry in logs at 13:03). 
- I wait one minute. At 13:04 I copy all from Output > Jupyter 


Contents of first cell:

```python
import fiftyone as fo
# import json
import ujson as json
from PIL import Image
import numpy as np
import pandas as pd

from pathlib import Path
```




[vscode-jupyter-closing.log](https://github.com/microsoft/vscode-jupyter/files/12419432/vscode-jupyter-closing.log)


I can still see the kernel running, both in `ps -ef`, and in `Jupyter Power tools` > _Active jupyter sessions_ : 

![Screenshot 2023-08-23 at 15 05 49](https://github.com/microsoft/vscode-jupyter/assets/2991890/05f2aaeb-bb3c-4db8-8a0a-4733c1d270c6)

Note there is no notebook tab opened. 

At this point, I realise I can click _Stop_ button (⏹️ ), which generates the following lines in the output:

```
13:06:50.176 [info] Interrupt kernel execution
13:06:50.176 [debug] Cancel pending cells
13:06:50.178 [info] Interrupt requested ~/ODISE/notebooks/process-iSAID.ipynb
13:06:50.179 [info] Interrupt kernel execution
13:06:50.180 [info] Interrupting kernel: pythonjvsc74a57bd02124a9dfd21b2e4b4b151fbb71e480ecc5b2e888175381ca9a5e114ed5217ff5
13:06:50.181 [info] Interrupting kernel via SIGINT
13:06:50.186 [info] Interrupt requested & sent for ~/ODISE/notebooks/process-iSAID.ipynb in notebookEditor.
```

So _Stop_ is actually interrupt, not full shut down.

**Comment by DonJayamanne** [comment]
@cipri-tom I'm sorry you are running into this, please could you file a new issue and I'll take a look
