### ISSUE TITLE
Unhandled @jupyterlab kernel exception

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#12797]
[23:49:51] Starting 'verifyUnhandledErrors'...
Unhandled Promise Rejection with the message Error: Canceled future for kernel_info_request message before replies were done, Error, Canceled future for kernel_info_request message before replies were done, Error: Canceled future for kernel_info_request message before replies were done
    at KernelShellFutureHandler.dispose (/home/runner/work/vscode-jupyter/vscode-jupyter/node_modules/@jupyterlab/services/src/kernel/future.ts:192:9)
    at /home/runner/work/vscode-jupyter/vscode-jupyter/node_modules/@jupyterlab/services/src/kernel/default.ts:1085:14
    at Map.forEach (<anonymous>)
    at KernelConnection._clearKernelState (/home/runner/work/vscode-jupyter/vscode-jupyter/node_modules/@jupyterlab/services/src/kernel/default.ts:1084:19)

from https://github.com/microsoft/vscode-jupyter/actions/runs/4129418932/jobs/7134993966

**Comment by DonJayamanne** [comment]
No longer an issue
