### ISSUE TITLE
Debugging for ipynb is not working for Python 3.8.10 in Remote window

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-jupyter#12847]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

* Create an Azure ML Compute instance with SSH enabled
* Either connect through Azure ML - Remote extension or Remote - SSH extension
* Open a notebook (.ipynb) file
* Select the kernel __azureml_py38 (Python 3.8.10)__
* Debug a cell
* The breakpoints are never hit
* Repeat with kernel __azureml_py310_sdkv2__
* Breakpoints are hit fine

### VS Code Version

Version: 1.75.0 (user setup) Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164 Date: 2023-02-01T15:23:45.584Z Electron: 19.1.9 Chromium: 102.0.5005.194 Node.js: 16.14.2 V8: 10.2.154.23-electron.0 OS: Windows_NT x64 10.0.22623 Sandboxed: Yes

### Jupyter Extension Version

v2023.1.2010391206 

### Jupyter logs

```shell
Visual Studio Code (1.75.0, ssh-remote, desktop)
Jupyter Extension Version: 2023.1.2010391206.
Python Extension not installed.
Workspace folder /home/azureuser/cloudfiles/code/Users/shsuman
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 07:30:52.189: LSP Notebooks experiment is disabled -- not using Pylance
info 07:30:52.272: Find preferred kernel for /home/azureuser/cloudfiles/code/Users/shsuman/test.ipynb with metadata {"kernelspec":{"display_name":"azureml_py38","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.8.13"},"vscode":{"interpreter":{"hash":"6d65a8c07f5b6469e0fc613f182488c0dccce05038bbda39e5ac9075c0454d11"}}} & preferred interpreter <undefined>
info 07:30:52.274: Find preferred kernel for /home/azureuser/cloudfiles/code/Users/shsuman/test.ipynb with metadata {"kernelspec":{"display_name":"azureml_py38","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.8.13"},"vscode":{"interpreter":{"hash":"6d65a8c07f5b6469e0fc613f182488c0dccce05038bbda39e5ac9075c0454d11"}}} & preferred interpreter <undefined>
info 07:30:52.400: Find preferred kernel for /home/azureuser/cloudfiles/code/Users/shsuman/test.ipynb with metadata {"kernelspec":{"display_name":"azureml_py38","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.8.13"},"vscode":{"interpreter":{"hash":"6d65a8c07f5b6469e0fc613f182488c0dccce05038bbda39e5ac9075c0454d11"}}} & preferred interpreter <undefined>
info 07:30:52.404: Find preferred kernel for /home/azureuser/cloudfiles/code/Users/shsuman/test.ipynb with metadata {"kernelspec":{"display_name":"azureml_py38","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.8.13"},"vscode":{"interpreter":{"hash":"6d65a8c07f5b6469e0fc613f182488c0dccce05038bbda39e5ac9075c0454d11"}}} & preferred interpreter <undefined>
info 07:31:02.199: LSP Notebooks experiment is enabled
info 07:31:09.301: Find preferred kernel for /home/azureuser/cloudfiles/code/Users/shsuman/test.ipynb with metadata {"kernelspec":{"display_name":"azureml_py38","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.8.13"},"vscode":{"interpreter":{"hash":"6d65a8c07f5b6469e0fc613f182488c0dccce05038bbda39e5ac9075c0454d11"}}} & preferred interpreter /anaconda/envs/jupyter_env/bin/python
info 07:31:09.312: Preferred kernel .jvsc74a57bd06d65a8c07f5b6469e0fc613f182488c0dccce05038bbda39e5ac9075c0454d11./anaconda/envs/azureml_py38/python./anaconda/envs/azureml_py38/python.-m#ipykernel_launcher is exact match or top match for non python kernels, (false, undefined, true, false)
info 07:31:09.312: PreferredConnection: .jvsc74a57bd06d65a8c07f5b6469e0fc613f182488c0dccce05038bbda39e5ac9075c0454d11./anaconda/envs/azureml_py38/python./anaconda/envs/azureml_py38/python.-m#ipykernel_launcher found for NotebookDocument: /home/azureuser/cloudfiles/code/Users/shsuman/test.ipynb
info 07:31:10.766: Process Execution: > /bin/python3 -m pip list
> /bin/python3 -m pip list
info 07:31:10.832: Process Execution: > /bin/python3 -c "import pip;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> /bin/python3 -c "import pip;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 07:31:10.885: Process Execution: > /anaconda/envs/jupyter_env/bin/python -m pip list
> /anaconda/envs/jupyter_env/bin/python -m pip list
error 07:31:11.202: interpreterPackages getPackageInformation, Class name = xl, completed in 1697ms, has a falsy return value, Arg 1: {"interpreter":{"id":"/bin/python3","sysPrefix":"/usr","displayPath":{"$mid":1,"path":"/bin/python3","scheme":"file"},"envName":"","uri":{"$mid":1,"fsPath":"/bin/python3","external":"file:///bin/python3","path":"/bin/python3","scheme":"file"},"displayName":"","envType":"Unknown","version":{"major":3,"minor":8,"patch":10,"raw":"3.8.10 (default, Nov 14 2022, 12:59:47) \n[GCC 9.4.0]"}}} [Qa [Error]: Module 'pip' not installed.
	at Xa.execModule (/home/azureuser/.vscode-server/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:2:1806741)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async xl.getPackageInformation (/home/azureuser/.vscode-server/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:17:38262)] {
  category: 'notinstalled',
  moduleName: 'pip'
}
info 07:31:12.164: Process Execution: > /anaconda/envs/azureml_py38/bin/python -m pip list
> /anaconda/envs/azureml_py38/bin/python -m pip list
info 07:32:07.891: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd06d65a8c07f5b6469e0fc613f182488c0dccce05038bbda39e5ac9075c0454d11./anaconda/envs/azureml_py38/python./anaconda/envs/azureml_py38/python.-m#ipykernel_launcher (Python Path: /anaconda/envs/azureml_py38, EnvType: Conda, EnvName: 'azureml_py38', Version: 3.8.10 (default, Jun  4 2021, 15:09:15) 
[GCC 7.5.0]) for '/home/azureuser/cloudfiles/code/Users/shsuman/test.ipynb' (disableUI=true)
info 07:32:07.958: Process Execution: > /anaconda/envs/azureml_py38/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> /anaconda/envs/azureml_py38/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
info 07:32:08.011: Process Execution: > /anaconda/envs/azureml_py38/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"09b51ad3-0973-4308-bba4-76bab21c9cde" --shell=9002 --transport="tcp" --iopub=9004 --f=/home/azureuser/.local/share/jupyter/runtime/kernel-v2-116847epCsRic29jh.json
> /anaconda/envs/azureml_py38/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"09b51ad3-0973-4308-bba4-76bab21c9cde" --shell=9002 --transport="tcp" --iopub=9004 --f=/home/azureuser/.local/share/jupyter/runtime/kernel-v2-116847epCsRic29jh.json
info 07:32:08.011: Process Execution: cwd: ~/cloudfiles/code/Users/shsuman
cwd: ~/cloudfiles/code/Users/shsuman
info 07:32:08.185: ipykernel version & path 6.8.0, /anaconda/envs/azureml_py38/lib/python3.8/site-packages/ipykernel/__init__.py for /anaconda/envs/azureml_py38/bin/python
warn 07:32:11.182: StdErr from Kernel Process /anaconda/envs/azureml_py38/lib/python3.8/site-packages/traitlets/traitlets.py:2544: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(

warn 07:32:11.182: StdErr from Kernel Process /anaconda/envs/azureml_py38/lib/python3.8/site-packages/traitlets/traitlets.py:2495: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '09b51ad3-0973-4308-bba4-76bab21c9cde' instead of 'b"09b51ad3-0973-4308-bba4-76bab21c9cde"'.
  warn(

warn 07:32:14.249: Didn't get response for requestKernelInfo after 3000ms.
info 07:32:14.250: Started Kernel azureml_py38 (Python 3.8.10) (pid: 12358)
info 07:32:19.564: Process Execution: > /anaconda/envs/azureml_py38/bin/python ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.1.2010391206/pythonFiles/printJupyterDataDir.py
> /anaconda/envs/azureml_py38/bin/python ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.1.2010391206/pythonFiles/printJupyterDataDir.py
info 07:32:23.139: Starting debugging with mode 1
info 07:33:12.695: Disposing kernel .jvsc74a57bd06d65a8c07f5b6469e0fc613f182488c0dccce05038bbda39e5ac9075c0454d11./anaconda/envs/azureml_py38/python./anaconda/envs/azureml_py38/python.-m#ipykernel_launcher for notebook /home/azureuser/cloudfiles/code/Users/shsuman/test.ipynb due to selection of another kernel or closing of the notebook
info 07:33:12.695: Dispose Kernel '/home/azureuser/cloudfiles/code/Users/shsuman/test.ipynb' associated with '/home/azureuser/cloudfiles/code/Users/shsuman/test.ipynb'
info 07:33:12.698: Dispose Kernel process 12358.
info 07:33:13.011: Skipping sending message request because session is disposed
info 07:33:13.011: Skipping sending message request because session is disposed
info 07:33:13.027: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd02139c70ac98f3202d028164a545621647e07f47fd6f5d8ac55cf952bf7c15ed1./anaconda/envs/azureml_py310_sdkv2/python./anaconda/envs/azureml_py310_sdkv2/python.-m#ipykernel_launcher (Python Path: /anaconda/envs/azureml_py310_sdkv2, EnvType: Conda, EnvName: 'azureml_py310_sdkv2', Version: 3.10.9 (main, Jan 11 2023, 15:21:40) [GCC 11.2.0]) for '/home/azureuser/cloudfiles/code/Users/shsuman/test.ipynb' (disableUI=true)
error 07:33:15.507: Failed to disconnect debug session Canceled: Canceled
    at a.P (vscode-file://vscode-app/c:/Users/shsuman/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:890:44301)
    at vscode-file://vscode-app/c:/Users/shsuman/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:890:44228
info 07:33:15.508: Ending debug session 0fa08cf4-9135-47a6-8f6c-276fb5ca7754
info 07:33:15.918: Ending debug session 0fa08cf4-9135-47a6-8f6c-276fb5ca7754
info 07:33:15.919: Ending debug session 0fa08cf4-9135-47a6-8f6c-276fb5ca7754
info 07:33:18.050: Process Execution: > /anaconda/envs/azureml_py310_sdkv2/bin/python -m pip list
> /anaconda/envs/azureml_py310_sdkv2/bin/python -m pip list
info 07:33:18.105: Process Execution: > /anaconda/envs/azureml_py310_sdkv2/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"792056b1-c826-49c6-aaca-63131ececca2" --shell=9002 --transport="tcp" --iopub=9004 --f=/home/azureuser/.local/share/jupyter/runtime/kernel-v2-11684KlL9uTxjq7Tk.json
> /anaconda/envs/azureml_py310_sdkv2/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"792056b1-c826-49c6-aaca-63131ececca2" --shell=9002 --transport="tcp" --iopub=9004 --f=/home/azureuser/.local/share/jupyter/runtime/kernel-v2-11684KlL9uTxjq7Tk.json
info 07:33:18.105: Process Execution: cwd: ~/cloudfiles/code/Users/shsuman
cwd: ~/cloudfiles/code/Users/shsuman
info 07:33:18.121: Process Execution: > /anaconda/envs/azureml_py310_sdkv2/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> /anaconda/envs/azureml_py310_sdkv2/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
info 07:33:19.337: Starting debugging with mode 1
info 07:33:20.076: ipykernel version & path 6.9.1, /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/ipykernel/__init__.py for /anaconda/envs/azureml_py310_sdkv2/bin/python
warn 07:33:24.356: StdErr from Kernel Process /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/traitlets/traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(

warn 07:33:24.356: StdErr from Kernel Process /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/traitlets/traitlets.py:2157: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '792056b1-c826-49c6-aaca-63131ececca2' instead of 'b"792056b1-c826-49c6-aaca-63131ececca2"'.
  warn(

warn 07:33:27.553: Didn't get response for requestKernelInfo after 3001ms.
info 07:33:27.554: Started Kernel azureml_py310_sdkv2 (Python 3.10.9) (pid: 12510)
info 07:33:31.298: Process Execution: > /anaconda/envs/azureml_py310_sdkv2/bin/python ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.1.2010391206/pythonFiles/printJupyterDataDir.py
> /anaconda/envs/azureml_py310_sdkv2/bin/python ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.1.2010391206/pythonFiles/printJupyterDataDir.py
info 07:40:34.167: Loading webview. View is notset
info 07:40:34.168: Loading web view...
info 07:40:34.169: Webview panel created.
info 07:40:36.583: Web view react rendered
info 07:40:43.961: Ending debug session 92eef3cd-ca1e-4947-83c9-22fce8e739b6
warn 07:40:44.029: StdErr from Kernel Process [IPKernelApp] ERROR | Exception in control handler:
Traceback (most recent call last):
  File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 295, in process_control
    await result
  File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 871, in debug_request
    reply_content = await reply_content
  File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 433, in do_debug_request
    return await self.debugger.process_request(msg)
  File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/ipykernel/debugger.py", line 672, in process_request
    self.stop()
  File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/ipykernel/debugger.py", line 396, in stop
    self.debugpy_client.disconnect_tcp_socket()
  File "/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/ipykernel/debugger.py", line 235, in disconnect_tcp_socket
    self.debugpy_stream.socket.disconnect(self._get_endpoint())
  File "zmq/backend/cython/socket.pyx", line 662, in zmq.backend.cython.socket.Socket.disconnect
zmq.error.ZMQError: No such file or directory

error 07:40:46.460: Jupyter Extension (Error in requestVariables, method:requestVariables): Canceled: Canceled
    at a.P (vscode-file://vscode-app/c:/Users/shsuman/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:890:44301)
    at vscode-file://vscode-app/c:/Users/shsuman/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:890:44228
error 07:40:46.460: Jupyter Extension (Error in requestVariables, method:requestVariables): Canceled: Canceled
    at a.P (vscode-file://vscode-app/c:/Users/shsuman/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:890:44301)
    at vscode-file://vscode-app/c:/Users/shsuman/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:890:44228
info 07:40:47.103: Ending debug session 92eef3cd-ca1e-4947-83c9-22fce8e739b6
info 07:40:47.103: Ending debug session 92eef3cd-ca1e-4947-83c9-22fce8e739b6
```

### Coding Language and Runtime Version

Python v3.8.10

### Language Extension Version (if applicable)

v2023.2.0

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, and I'm very sorry for missing this issue and sorry you are running into this issue.

> ile "zmq/backend/cython/socket.pyx", line 662, in zmq.backend.cython.socket.Socket.disconnect
zmq.error.ZMQError: No such file or directory


Looks like you have some issues with the python package ipykernel and zmq, I would suggest either re-installing these packages or creating a new environment.

That should fix this issue, if not please ping and I will re-open this issue or pleaes feel free to re-open this issue or create a new one.

**Comment by shsuman** [comment]
@DonJayamanne Upgrading the ipykernel fixes the issue. The problem lies with the v6.8.0 of the ipykernel, v6.21.3 works fine, any particular reason that might be happening ?

**Comment by shsuman** [comment]
Just a friendly ping @DonJayamanne

**Comment by roblourens** [comment]
I know that there have been debug issues that are fixed in newer ipykernel releases. If it's fixed in the latest, is there still an issue for us to address?

**Comment by shsuman** [comment]
@roblourens I have asked the Azure ML team to upgrade the ipykernel versions in their upcoming image releases.

**Comment by roblourens** [comment]
Cool, so nothing for us to do then?
