### ISSUE TITLE
Kernel list is not accurate, points to non-existent kernel.json

### ISSUE THREAD

**Issue by jose-a-sa** [microsoft/vscode-jupyter#12856]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I removed a conda environment named "sage" and it still appears in the "Jupyter Kernel list". Already check every single instance of jupyter in every single conda environment and deleted all the kernel.json when conda failed to do so after doing a deep "find /".
I uninstalled conda completely, cleaned all the .conda, .jupyter, etc folders. When that didn't work I thought it might be some residual cache in VSCode and did a clean reinstall too, with no success.
The strange thing is if I use the command `> Jupyter: Filter Kernels` and the remove the culprits, the "jupyter.kernels.filter" list in settings.json points to non-existent files `~/Library/Jupyter/kernels/<env>/kernel.json`.

### VS Code Version

1.75.1

### Jupyter Extension Version

v2023.1.2010391206

### Jupyter logs

```shell
[W 00:25:29.957 NotebookApp] delete /NN-Deep-Learning/week2-jvsc-bf8abe2f-b19f-42c0-890e-3222856eb41d87f8f891-ffe7-4fc5-9f1f-c0f768607f27.ipynb
info 00:25:40.476: Started session for kernel startUsingLocalKernelSpec:.tf./opt/homebrew/Caskroom/miniforge/base/envs/tf/bin/python3.10./opt/homebrew/Caskroom/miniforge/base/envs/tf/bin/python3.10.-m#ipykernel_launcher
info 00:25:51.258: Disposing kernel .tf./opt/homebrew/Caskroom/miniforge/base/envs/tf/bin/python3.10./opt/homebrew/Caskroom/miniforge/base/envs/tf/bin/python3.10.-m#ipykernel_launcher for notebook /Users/jose/MEGA/Source/Coursera/NN-Deep-Learning/week2.ipynb due to selection of another kernel or closing of the notebook
info 00:25:51.258: Dispose Kernel '/Users/jose/MEGA/Source/Coursera/NN-Deep-Learning/week2.ipynb' associated with '/Users/jose/MEGA/Source/Coursera/NN-Deep-Learning/week2.ipynb'
[I 00:25:51.267 NotebookApp] Kernel shutdown: fdd60c22-97b7-431f-bb66-41c95dbd5ed0
info 00:25:51.303: Starting Jupyter Session startUsingLocalKernelSpec, .python3./opt/homebrew/Caskroom/miniforge/base/envs/sage/python./.-m#ipykernel_launcher for '/Users/jose/MEGA/Source/Coursera/NN-Deep-Learning/week2.ipynb' (disableUI=true)
[I 00:25:51.382 NotebookApp] Creating new notebook in /NN-Deep-Learning
[I 00:25:51.408 NotebookApp] Kernel started: bae07158-8988-40af-8947-c4e6595377cc, name: python3
[W 00:25:51.417 NotebookApp] delete /NN-Deep-Learning/week2-jvsc-768928c5-2b5f-4c6f-b526-46d042a9257ff3506a30-8b9c-4c42-8457-91a34cdba955.ipynb
info 00:25:56.447: Started session for kernel startUsingLocalKernelSpec:.python3./opt/homebrew/Caskroom/miniforge/base/envs/sage/python./.-m#ipykernel_launcher
[E 00:25:56.452 NotebookApp] Uncaught exception, closing connection.
    Traceback (most recent call last):
      File "/opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.9/site-packages/tornado/iostream.py", line 702, in _handle_events
        self._handle_write()
      File "/opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.9/site-packages/tornado/iostream.py", line 976, in _handle_write
        self._write_buffer.advance(num_bytes)
      File "/opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.9/site-packages/tornado/iostream.py", line 182, in advance
        assert 0 < size <= self._size
    AssertionError
Exception in callback None()
handle: <Handle cancelled>
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 206, in _handle_events
    handler_func(fileobj, events)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.9/site-packages/tornado/iostream.py", line 702, in _handle_events
    self._handle_write()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.9/site-packages/tornado/iostream.py", line 976, in _handle_write
    self._write_buffer.advance(num_bytes)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.9/site-packages/tornado/iostream.py", line 182, in advance
    assert 0 < size <= self._size
AssertionError
[I 00:25:56.457 NotebookApp] Starting buffering for bae07158-8988-40af-8947-c4e6595377cc:2210a3b5-7402-49bd-b5a7-c3f36410ef7c
[I 00:25:56.462 NotebookApp] Restoring connection for bae07158-8988-40af-8947-c4e6595377cc:2210a3b5-7402-49bd-b5a7-c3f36410ef7c
[I 00:25:56.463 NotebookApp] Replaying 2 buffered messages
```

### Running Jupyter locally or remotely?

Local

**Comment by jamescooke** [comment]
This looks like https://github.com/jupyter/notebook/issues/6721 - could this be the underlying issue?

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
