### ISSUE TITLE
Failure to start Jupyter with error message `--allow-root`

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#12876]
Sometimes we fail to start Jupyter due to the following error message

![Screenshot 2023-02-20 at 13 49 46](https://user-images.githubusercontent.com/1948812/219998252-0e8958c0-cc60-4ed5-b30b-c68bcb3c18d7.png)

````
Error code from Jupyter: 1
/opt/conda/lib/python3.9/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/workspaces/sample4R' instead of '"/workspaces/sample4R"' if you require traitlets >=5.
  warn(

[C 02:48:09.471 NotebookApp] Running as root is not recommended. Use --allow-root to bypass.

	at qm.rejectStartPromise (/root/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.2.100/out/extension.node.js:17:244435)
	at t._complete (/root/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.2.100/out/extension.node.js:17:245018)
	at t.n (/root/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.2.100/out/extension.node.js:2:642373)
	at t.__tryOrUnsub (/root/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.2.100/out/extension.node.js:2:642613)
	at t.complete (/root/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.2.100/out/extension.node.js:2:642506)
	at t._complete (/root/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.2.100/out/extension.node.js:2:641022)
	at t.complete (/root/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.2.100/out/extension.node.js:2:640721)
	at ChildProcess.<anonymous> (/root/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.2.100/out/extension.node.js:2:1777984)
	at Object.onceWrapper (node:events:646:26)
	at ChildProcess.emit (node:events:538:35)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)] {
```

The user isn't aware of what is wrong.

**Comment by DonJayamanne** [comment]
Closing as we rarely start jupyter these days.
