### ISSUE TITLE
qsl Widget does not render

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#12885]
Originally filed by [matthai](https://github.com/matthai) here https://github.com/microsoft/vscode-jupyter/issues/12843#issuecomment-1437750979

I have the same problem. My setup is perhaps even simpler.

I am running a fresh install of code-insider locally on an ubuntu 20.04 machine. I am trying to run the qsl package from pip (`pip install qsl` in a fresh env) via the 3 lines of code below, which works on the web-based jupyter. My project has only one root.

On the web-based jupyter client, this works fine.

On vscode with ipywidgets 8.0.4 and pre-release versions of jupyter and python extensions, I get:

![sshot](https://user-images.githubusercontent.com/755774/220225570-21b3c1e4-841d-4f85-85da-38092989b399.png)

The contents of the error are very similar to that of @christasich:

[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'MediaLabelerModel' from module 'qslwidgets'
Error: No version of module qslwidgets is registered
    at ph.loadClass (https://file+.vscode-resource.vscode-cdn.net/home/matthai/.vscode-insiders/extensions/ms-toolsai.jupyter-renderers-1.0.15/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4099813)
    at ph.loadClass (https://file+.vscode-resource.vscode-cdn.net/home/matthai/.vscode-insiders/extensions/ms-toolsai.jupyter-renderers-1.0.15/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4403287)
    at ph.loadModelClass (https://file+.vscode-resource.vscode-cdn.net/home/matthai/.vscode-insiders/extensions/ms-toolsai.jupyter-renderers-1.0.15/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4097773)
    at ph._make_model (https://file+.vscode-resource.vscode-cdn.net/home/matthai/.vscode-insiders/extensions/ms-toolsai.jupyter-renderers-1.0.15/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4094616)
    at ph.new_model (https://file+.vscode-resource.vscode-cdn.net/home/matthai/.vscode-insiders/extensions/ms-toolsai.jupyter-renderers-1.0.15/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4092246)
    at ph.handle_comm_open (https://file+.vscode-resource.vscode-cdn.net/home/matthai/.vscode-insiders/extensions/ms-toolsai.jupyter-renderers-1.0.15/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4091039)
    at https://file+.vscode-resource.vscode-cdn.net/home/matthai/.vscode-insiders/extensions/ms-toolsai.jupyter-renderers-1.0.15/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4402511
    at g._handleCommOpen (https://file+.vscode-resource.vscode-cdn.net/home/matthai/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.2.1000521025/out/webviews/webview-side/ipywidgetsKernel/ipywidgetsKernel.js:2:36493)
    at async g._handleMessage (https://file+.vscode-resource.vscode-cdn.net/home/matthai/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.2.1000521025/out/webviews/webview-side/ipywidgetsKernel/ipywidgetsKernel.js:2:38387)

**Comment by DonJayamanne** [comment]
This works for me,

![Screenshot 2023-02-21 at 13 54 55](https://user-images.githubusercontent.com/1948812/220235878-bff7cab3-a2ef-4af3-8369-b480fd390459.png)

@matthai please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by matthai** [comment]
@DonJayamanne great to see it can work!

I switched Jupyter->Logging to verbose, restarted vs code and re-ran the code.

I get exactly the same result (attached). Is the "Jupyter output panel" you mention just the area below the cell?

![qslout2](https://user-images.githubusercontent.com/755774/220460158-0bb8ab42-802e-45b7-ad12-519c19a8ee8c.png)
![jupsetting](https://user-images.githubusercontent.com/755774/220460160-fab0675f-5c40-4197-bd07-3c21fd791983.png)

**Comment by DonJayamanne** [comment]
> Attempt to repro the issue & then copy the output from the Jupyter output panel.

You can get the output from here
* Open the command palette
* Select the command `Jupyter: Show Output`
* Ensure you copy all of the contents, and please do this after you have replicated the issue

Also note:
* Please open your developer tools via the command `Toggle Developer tools`
* Ensure you have the network tab open
* Then open the notebook and replicate the issue
There might be some network issues logged in here and I'd be interested in seeing them 
If there are any, then please capture a screenshot of those network errors

**Comment by matthai** [comment]
Here you go
![network](https://user-images.githubusercontent.com/755774/220471636-b6ba4ab6-964e-4f6c-b805-b25e540b2b69.png)
[jupout.txt](https://github.com/microsoft/vscode-jupyter/files/10798236/jupout.txt)

**Comment by matthai** [comment]
@DonJayamanne , note that the output of the jupyter comment is in the file `jupout.txt` at the bottom of my previous post. It's a bit hard to notice.

**Comment by DonJayamanne** [comment]
[ms-toolsai-jupyter-insiders.vsix.zip](https://github.com/microsoft/vscode-jupyter/files/10798366/ms-toolsai-jupyter-insiders.vsix.zip)

This issue was just identified in another place and i have a fix for this
You can verify the fix by installing the above VSIX
* Download the file
* Extract it
* Install it in VS Code using the command `Install from VSIX`
* Reload VS Code Insiders and test again

That should fix it, if not, please comment here https://github.com/microsoft/vscode-jupyter/issues/12843

Closing as a duplicate of https://github.com/microsoft/vscode-jupyter/issues/12843

**Comment by matthai** [comment]
Hallelujah, @DonJayamanne that worked. Thanks!

**Comment by DonJayamanne** [comment]
Thank you for your patience and feedback, this fix will be in the next insiders (hence the next relase as well)
