### ISSUE TITLE
Pip module Unable to parse debugpy output

### ISSUE THREAD

**Issue by lambda-science** [microsoft/vscode-jupyter#12913]
## Environment data

-   VS Code version: 1.75.1
-   Jupyter Extension version (available under the Extensions sidebar): v2023.1.2010391206
-   Python Extension version (available under the Extensions sidebar): v2023.2.0
-   OS (Windows | Mac | Linux distro) and version: Linux 22.04
-   Python and/or Anaconda version: 3.8.16
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): poetry / venv
-   Jupyter server running: Remote

## Expected behaviour

Debugger should run fine

## Actual behaviour

Error message

## Steps to reproduce:

Create a script.py file
```
#%%
print("hello world")
```
click "debug cell" on top of the file
Get this error:
`Pip module Unable to parse debugpy output, please log an issue with https://github.com/microsoft/vscode-jupyter is required for debugging cells. You will need to install it to debug cells. 
View Jupyter [log](command:jupyter.viewOutput) for further details.`
And in the logs:  
`warn 16:16:53.394: StdErr from Kernel Process /home/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/force_pydevd.py:18: UserWarning: incompatible copy of pydevd already imported:`
## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```python-traceback
info 16:16:52.752: Generated code for 10 = <ipython-input-10-6ba20cd7bd9d> with 3 lines
info 16:16:52.789: start debugging
info 16:16:52.789: enable debugger attach
info 16:16:52.845: Appending paths: undefined
warn 16:16:53.394: StdErr from Kernel Process /home/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/force_pydevd.py:18: UserWarning: incompatible copy of pydevd already imported:
 /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/__init__.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/_pydev_calltip_util.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/_pydev_completer.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/_pydev_execfile.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/_pydev_filesystem_encoding.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/_pydev_imports_tipper.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/_pydev_saved_modules.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/_pydev_tipper_common.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/fsnotify/__init__.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/pydev_console_utils.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/pydev_imports.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/pydev_is_thread_alive.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/pydev_log.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/pydev_monkey.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/pydev_override.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydev_bundle/pydev_umd.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/__init__.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/_debug_adapter/__init__.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/_debug_adapter/pydevd_base_schema.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/_debug_adapter/pydevd_schema.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/_debug_adapter/pydevd_schema_log.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevconsole_code.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_additional_thread_info.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_additional_thread_info_regular.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_api.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_breakpoints.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_bytecode_utils.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_collect_bytecode_info.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm_constants.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_command_line_handling.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_concurrency_analyser/__init__.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_concurrency_analyser/pydevd_concurrency_logger.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_concurrency_analyser/pydevd_thread_wrappers.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_console.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_constants.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_custom_frames.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_cython.cpython-38-x86_64-linux-gnu.so
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_cython_wrapper.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_daemon_thread.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_defaults.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_dont_trace.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_dont_trace_files.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_exec2.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_extension_api.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_extension_utils.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_filtering.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame_utils.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_import_class.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_io.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_json_debug_options.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_net_command.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_net_command_factory_json.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_net_command_factory_xml.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_plugin_utils.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_reload.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_resolver.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_safe_repr.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_save_locals.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_source_mapping.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_suspended_frames.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_thread_lifecycle.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_timeout.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_trace_api.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_trace_dispatch.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_traceproperty.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_utils.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vm_type.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_xml.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_frame_eval/__init__.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pyde
warn 16:16:53.396: StdErr from Kernel Process vd_frame_eval/pydevd_frame_eval_main.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_frame_eval/vendored/__init__.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_frame_eval/vendored/bytecode/__init__.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_frame_eval/vendored/bytecode/bytecode.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_frame_eval/vendored/bytecode/cfg.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_frame_eval/vendored/bytecode/concrete.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_frame_eval/vendored/bytecode/flags.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_frame_eval/vendored/bytecode/instr.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/pydev_ipython/__init__.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/pydevconsole.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/pydevd_file_utils.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/pydevd_plugins/__init__.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/pydevd_plugins/django_debug.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/pydevd_plugins/extensions/__init__.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/pydevd_plugins/extensions/types/__init__.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/pydevd_plugins/extensions/types/pydevd_helpers.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/pydevd_plugins/extensions/types/pydevd_plugin_numpy_types.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/pydevd_plugins/extensions/types/pydevd_plugin_pandas_types.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/pydevd_plugins/extensions/types/pydevd_plugins_django_form_str.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/pydevd_plugins/jinja2_debug.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/pydevd_plugins/pydevd_line_validation.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/debugpy/_vendored/pydevd/pydevd_tracing.py
  /big/meyer/code-project/MyoQuant-SDH-Train/.venv/lib/python3.8/site-packages/pydevd_plugins/extensions/pydevd_plugin_omegaconf.py
  warnings.warn(msg + ':\n {}'.format('\n  '.join(_unvendored)))

error 16:16:54.458: Error in execution (get message for cell) e_ [Error]: Pip module Unable to parse debugpy output, please log an issue with https://github.com/microsoft/vscode-jupyter is required for debugging cells. You will need to install it to debug cells.
    at r_.connectToLocal (/big/meyer/.vscode-server/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:17:719686)
    at r_.connect (/big/meyer/.vscode-server/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:17:718091)
    at r_.startDebugSession (/big/meyer/.vscode-server/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:17:717347)
    at qS.createExecutionPromise (/big/meyer/.vscode-server/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:17:699146) {
  category: 'notinstalled',
  kernelConnectionMetadata: Zd {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: '/home/meyer/.vscode-server/extensions/ms-toolsai.jupyter-2023.1.2010391206/temp/jupyter/kernels/pythonjvsc74a57bd072f151f06f73a7f1387c41c20c6e81dd1f2de7c0f647fc647e5076786050674c/kernel.json',
      interpreterPath: '/home/meyer/code-project/MyoQuant-SDH-Train/.venv/bin/python',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'pythonjvsc74a57bd072f151f06f73a7f1387c41c20c6e81dd1f2de7c0f647fc647e5076786050674c',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: '.venv',
      metadata: [Object],
      env: {}
    },
    interpreter: {
      id: '/home/meyer/code-project/MyoQuant-SDH-Train/.venv/bin/python',
      sysPrefix: '/home/meyer/code-project/MyoQuant-SDH-Train/.venv',
      envPath: [f],
      displayPath: [Object],
      envName: '.venv',
      displayName: '.venv',
      envType: 'Poetry',
      version: [Object],
      uri: [f]
    },
    id: '.jvsc74a57bd072f151f06f73a7f1387c41c20c6e81dd1f2de7c0f647fc647e5076786050674c./home/meyer/code-project/MyoQuant-SDH-Train/.venv/python./home/meyer/code-project/MyoQuant-SDH-Train/.venv/python.-m#ipykernel_launcher'
  }
}
warn 16:16:54.462: DataScience Error e_ [Error]: Pip module Unable to parse debugpy output, please log an issue with https://github.com/microsoft/vscode-jupyter is required for debugging cells. You will need to install it to debug cells.
    at r_.connectToLocal (/big/meyer/.vscode-server/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:17:719686)
    at r_.connect (/big/meyer/.vscode-server/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:17:718091)
    at r_.startDebugSession (/big/meyer/.vscode-server/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:17:717347)
    at qS.createExecutionPromise (/big/meyer/.vscode-server/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:17:699146) {
  category: 'notinstalled',
  kernelConnectionMetadata: Zd {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: '/home/meyer/.vscode-server/extensions/ms-toolsai.jupyter-2023.1.2010391206/temp/jupyter/kernels/pythonjvsc74a57bd072f151f06f73a7f1387c41c20c6e81dd1f2de7c0f647fc647e5076786050674c/kernel.json',
      interpreterPath: '/home/meyer/code-project/MyoQuant-SDH-Train/.venv/bin/python',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'pythonjvsc74a57bd072f151f06f73a7f1387c41c20c6e81dd1f2de7c0f647fc647e5076786050674c',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: '.venv',
      metadata: [Object],
      env: {}
    },
    interpreter: {
      id: '/home/meyer/code-project/MyoQuant-SDH-Train/.venv/bin/python',
      sysPrefix: '/home/meyer/code-project/MyoQuant-SDH-Train/.venv',
      envPath: [f],
      displayPath: [Object],
      envName: '.venv',
      displayName: '.venv',
      envType: 'Poetry',
      version: [Object],
      uri: [f]
    },
    id: '.jvsc74a57bd072f151f06f73a7f1387c41c20c6e81dd1f2de7c0f647fc647e5076786050674c./home/meyer/code-project/MyoQuant-SDH-Train/.venv/python./home/meyer/code-project/MyoQuant-SDH-Train/.venv/python.-m#ipykernel_launcher'
  }
}

```

</p>
</details>

**Comment by shayandavoodii** [comment]
I have the same issue:  
```
Pip module Unable to parse debugpy output, please log an issue with https://github.com/microsoft/vscode-jupyter is required for debugging cells. You will need to install it to debug cells. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
```
And the OUTPUT:
```
info 17:44:42.978: Generated code for 6 = <ipython-input-6-400f211cb238> with 7 lines
info 17:44:42.989: start debugging
info 17:44:42.989: enable debugger attach
info 17:44:43.010: Appending paths: undefined
error 17:44:43.868: Error in execution (get message for cell) e_ [Error]: Pip module Unable to parse debugpy output, please log an issue with https://github.com/microsoft/vscode-jupyter is required for debugging cells. You will need to install it to debug cells.
    at r_.connectToLocal (c:\Users\Shayan\.vscode\extensions\ms-toolsai.jupyter-2023.1.2010391206\out\extension.node.js:17:719686)
    at r_.connect (c:\Users\Shayan\.vscode\extensions\ms-toolsai.jupyter-2023.1.2010391206\out\extension.node.js:17:718091)
    at r_.startDebugSession (c:\Users\Shayan\.vscode\extensions\ms-toolsai.jupyter-2023.1.2010391206\out\extension.node.js:17:717347)
    at qS.createExecutionPromise (c:\Users\Shayan\.vscode\extensions\ms-toolsai.jupyter-2023.1.2010391206\out\extension.node.js:17:699146) {
  category: 'notinstalled',
  kernelConnectionMetadata: Zd {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: 'c:\\Users\\Shayan\\.vscode\\extensions\\ms-toolsai.jupyter-2023.1.2010391206\\temp\\jupyter\\kernels\\pythonjvsc74a57bd06cbee39f9ce2f60c5e0a785f10053bbc329aa91d4c31b27386f4117b09213a92\\kernel.json',
      interpreterPath: 'c:\\Users\\Shayan\\miniconda3\\envs\\3.9\\python.exe',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'pythonjvsc74a57bd06cbee39f9ce2f60c5e0a785f10053bbc329aa91d4c31b27386f4117b09213a92',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: '3.9',
      metadata: [Object],
      env: {}
    },
    interpreter: {
      id: 'C:\\USERS\\SHAYAN\\MINICONDA3\\ENVS\\3.9\\PYTHON.EXE',
      sysPrefix: 'C:\\Users\\Shayan\\miniconda3\\envs\\3.9',
      envPath: [f],
      displayPath: [Object],
      envName: '3.9',
      displayName: '3.9',
      envType: 'Conda',
      version: [Object],
      uri: [f]
    },
    id: '.jvsc74a57bd06cbee39f9ce2f60c5e0a785f10053bbc329aa91d4c31b27386f4117b09213a92.c:\\Users\\Shayan\\miniconda3\\envs\\3.9\\python.exe.c:\\Users\\Shayan\\miniconda3\\envs\\3.9\\python.exe.-m#ipykernel_launcher'
  }
}
warn 17:44:43.869: DataScience Error e_ [Error]: Pip module Unable to parse debugpy output, please log an issue with https://github.com/microsoft/vscode-jupyter is required for debugging cells. You will need to install it to debug cells.
    at r_.connectToLocal (c:\Users\Shayan\.vscode\extensions\ms-toolsai.jupyter-2023.1.2010391206\out\extension.node.js:17:719686)
    at r_.connect (c:\Users\Shayan\.vscode\extensions\ms-toolsai.jupyter-2023.1.2010391206\out\extension.node.js:17:718091)
    at r_.startDebugSession (c:\Users\Shayan\.vscode\extensions\ms-toolsai.jupyter-2023.1.2010391206\out\extension.node.js:17:717347)
    at qS.createExecutionPromise (c:\Users\Shayan\.vscode\extensions\ms-toolsai.jupyter-2023.1.2010391206\out\extension.node.js:17:699146) {
  category: 'notinstalled',
  kernelConnectionMetadata: Zd {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: 'c:\\Users\\Shayan\\.vscode\\extensions\\ms-toolsai.jupyter-2023.1.2010391206\\temp\\jupyter\\kernels\\pythonjvsc74a57bd06cbee39f9ce2f60c5e0a785f10053bbc329aa91d4c31b27386f4117b09213a92\\kernel.json',
      interpreterPath: 'c:\\Users\\Shayan\\miniconda3\\envs\\3.9\\python.exe',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'pythonjvsc74a57bd06cbee39f9ce2f60c5e0a785f10053bbc329aa91d4c31b27386f4117b09213a92',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: '3.9',
      metadata: [Object],
      env: {}
    },
    interpreter: {
      id: 'C:\\USERS\\SHAYAN\\MINICONDA3\\ENVS\\3.9\\PYTHON.EXE',
      sysPrefix: 'C:\\Users\\Shayan\\miniconda3\\envs\\3.9',
      envPath: [f],
      displayPath: [Object],
      envName: '3.9',
      displayName: '3.9',
      envType: 'Conda',
      version: [Object],
      uri: [f]
    },
    id: '.jvsc74a57bd06cbee39f9ce2f60c5e0a785f10053bbc329aa91d4c31b27386f4117b09213a92.c:\\Users\\Shayan\\miniconda3\\envs\\3.9\\python.exe.c:\\Users\\Shayan\\miniconda3\\envs\\3.9\\python.exe.-m#ipykernel_launcher'
  }
}
```

**Comment by roblourens** [comment]
I'm guessing this is the same as https://github.com/microsoft/vscode-jupyter/issues/12801, should have a fix out in the near future

**Comment by artkpv** [comment]
I also got this. Under pipenv (python 3.8) on Archlinux, VS Code:

![image](https://github.com/microsoft/vscode-jupyter/assets/3657998/466bc7f0-37f3-41db-8a33-459064ffebbd)
