### ISSUE TITLE
Debugger - Uncaught exception in ZMQStream callback

### ISSUE THREAD

**Issue by tekumara** [microsoft/vscode-jupyter#12945]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

1. Run debugger in a cell
1. Start stepping through
1. Info box `Reconnecting to the kernel .venv (Python 3.9.13)` pops up...    

### VS Code Version

Version: 1.75.1 (Universal) Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf

### Jupyter Extension Version

v2023.1.2010391206

### Jupyter logs

```shell
info 15:58:07.676: Started session for kernel startUsingPythonInterpreter:.jvsc74a57bd0f59249d332647baa27896e48b602655774b2ab27cda0296fe135a6398572f9c3./Users/tekumara/code/fakesnow/.venv/python./Users/tekumara/code/fakesnow/.venv/python.-m#ipykernel_launcher
    info 15:58:07.697: Process Execution: > ~/code/fakesnow/.venv/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/pythonFiles/printJupyterDataDir.py
    > ~/code/fakesnow/.venv/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/pythonFiles/printJupyterDataDir.py
    info 15:58:18.992: Starting debugging with mode 1
    [E 15:58:47.080 NotebookApp] Uncaught exception in ZMQStream callback
        Traceback (most recent call last):
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
            f = callback(*args, **kwargs)
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 308, in stream_callback
            return callback(self, msg)
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/notebook/services/kernels/handlers.py", line 572, in _on_zmq_reply
            super()._on_zmq_reply(stream, msg)
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/notebook/base/zmqhandlers.py", line 256, in _on_zmq_reply
            self.write_message(msg, binary=isinstance(msg, bytes))
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/tornado/websocket.py", line 339, in write_message
            return self.ws_connection.write_message(message, binary=binary)
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/tornado/websocket.py", line 1086, in write_message
            fut = self._write_frame(True, opcode, message, flags=flags)
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/tornado/websocket.py", line 1061, in _write_frame
            return self.stream.write(frame)
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/tornado/iostream.py", line 546, in write
            self._handle_write()
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/tornado/iostream.py", line 976, in _handle_write
            self._write_buffer.advance(num_bytes)
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/tornado/iostream.py", line 182, in advance
            assert 0 < size <= self._size
        AssertionError
    [I 15:58:47.081 NotebookApp] Starting buffering for fc1f0057-3fd6-44ec-9937-dcd994c26fdc:72261fc2-21ce-408e-9ce4-8722fcfbe3b5
    [E 15:58:47.083 NotebookApp] Uncaught exception in zmqstream callback
        Traceback (most recent call last):
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 621, in _handle_events
            self._handle_recv()
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 650, in _handle_recv
            self._run_callback(callback, msg)
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
            f = callback(*args, **kwargs)
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 308, in stream_callback
            return callback(self, msg)
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/notebook/services/kernels/handlers.py", line 572, in _on_zmq_reply
            super()._on_zmq_reply(stream, msg)
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/notebook/base/zmqhandlers.py", line 256, in _on_zmq_reply
            self.write_message(msg, binary=isinstance(msg, bytes))
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/tornado/websocket.py", line 339, in write_message
            return self.ws_connection.write_message(message, binary=binary)
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/tornado/websocket.py", line 1086, in write_message
            fut = self._write_frame(True, opcode, message, flags=flags)
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/tornado/websocket.py", line 1061, in _write_frame
            return self.stream.write(frame)
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/tornado/iostream.py", line 546, in write
            self._handle_write()
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/tornado/iostream.py", line 976, in _handle_write
            self._write_buffer.advance(num_bytes)
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/tornado/iostream.py", line 182, in advance
            assert 0 < size <= self._size
        AssertionError
    [E 15:58:47.084 NotebookApp] Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x11148dee0>)
        Traceback (most recent call last):
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/tornado/ioloop.py", line 740, in _run_callback
            ret = callback()
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 705, in <lambda>
            self.io_loop.add_callback(lambda: self._handle_events(self.socket, 0))
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 621, in _handle_events
            self._handle_recv()
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 650, in _handle_recv
            self._run_callback(callback, msg)
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
            f = callback(*args, **kwargs)
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 308, in stream_callback
            return callback(self, msg)
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/notebook/services/kernels/handlers.py", line 572, in _on_zmq_reply
            super()._on_zmq_reply(stream, msg)
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/notebook/base/zmqhandlers.py", line 256, in _on_zmq_reply
            self.write_message(msg, binary=isinstance(msg, bytes))
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/tornado/websocket.py", line 339, in write_message
            return self.ws_connection.write_message(message, binary=binary)
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/tornado/websocket.py", line 1086, in write_message
            fut = self._write_frame(True, opcode, message, flags=flags)
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/tornado/websocket.py", line 1061, in _write_frame
            return self.stream.write(frame)
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/tornado/iostream.py", line 546, in write
            self._handle_write()
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/tornado/iostream.py", line 976, in _handle_write
            self._write_buffer.advance(num_bytes)
          File "/Users/tekumara/code/fakesnow/.venv/lib/python3.9/site-packages/tornado/iostream.py", line 182, in advance
            assert 0 < size <= self._size
        AssertionError
    [I 15:58:47.089 NotebookApp] Restoring connection for fc1f0057-3fd6-44ec-9937-dcd994c26fdc:72261fc2-21ce-408e-9ce4-8722fcfbe3b5
    [I 15:58:47.592 NotebookApp] Replaying 3 buffered messages
```

### Coding Language and Runtime Version

Python 3.9.13

### Language Extension Version (if applicable)

v2023.2.0

### Running Jupyter locally or remotely?

Local

**Comment by tekumara** [comment]
With debug logs:
```
debug 17:07:23.101: [Debug] to kernel: {"command":"threads","type":"request","seq":142}
debug 17:07:23.101: [Debug] to kernel, mapped: {"command":"threads","type":"request","seq":142}
debug 17:07:23.105: [Debug] response: {"seq":227,"type":"response","request_seq":142,"success":true,"command":"threads","body":{"threads":[{"id":1,"name":"MainThread"},{"id":2,"name":"Thread-3"},{"id":3,"name":"Thread-4"},{"id":4,"name":"IPythonHistorySavingThread"},{"id":5,"name":"Thread-2"}]}}
debug 17:07:23.111: [Debug] to kernel: {"command":"stackTrace","arguments":{"threadId":1,"startFrame":0,"levels":1},"type":"request","seq":143}
debug 17:07:23.111: [Debug] to kernel, mapped: {"command":"stackTrace","arguments":{"threadId":1,"startFrame":0,"levels":1},"type":"request","seq":143}
debug 17:07:23.116: [Debug] response: {"seq":228,"type":"response","request_seq":143,"success":true,"command":"stackTrace","body":{"stackFrames":[{"id":35,"name":"_scan_keywords","line":857,"column":1,"source":{"path":"/Users/tekumara/code3/sqlglot/sqlglot/tokens.py","sourceReference":0}}],"totalFrames":6}}
debug 17:07:23.486: [Debug] to kernel: {"command":"next","arguments":{"threadId":1},"type":"request","seq":144}
debug 17:07:23.486: [Debug] to kernel, mapped: {"command":"next","arguments":{"threadId":1},"type":"request","seq":144}
debug 17:07:23.491: [Debug] response: {"seq":229,"type":"response","request_seq":144,"success":true,"command":"next"}
debug 17:07:23.513: [Debug] event: {"header":{"msg_id":"236e13e8-425692d13373a3c8487b2264_54387_538","msg_type":"debug_event","username":"tekumara","session":"236e13e8-425692d13373a3c8487b2264","date":"2023-02-27T06:07:23.511724Z","version":"5.3"},"msg_id":"236e13e8-425692d13373a3c8487b2264_54387_538","msg_type":"debug_event","parent_header":{"date":"2023-02-27T06:07:23.486000Z","msg_id":"474a2786-e9d5-407d-8d7b-0f1c75f9d0db","msg_type":"debug_request","session":"bffc5d8d-c643-4d70-8986-1cd8b5d54873","username":"","version":"5.2"},"metadata":{},"content":{"seq":230,"type":"event","event":"continued","body":{"threadId":1,"allThreadsContinued":true}},"buffers":[],"channel":"iopub"}
debug 17:07:23.513: [Debug] event: {"header":{"msg_id":"236e13e8-425692d13373a3c8487b2264_54387_539","msg_type":"debug_event","username":"tekumara","session":"236e13e8-425692d13373a3c8487b2264","date":"2023-02-27T06:07:23.512964Z","version":"5.3"},"msg_id":"236e13e8-425692d13373a3c8487b2264_54387_539","msg_type":"debug_event","parent_header":{"date":"2023-02-27T06:07:23.486000Z","msg_id":"474a2786-e9d5-407d-8d7b-0f1c75f9d0db","msg_type":"debug_request","session":"bffc5d8d-c643-4d70-8986-1cd8b5d54873","username":"","version":"5.2"},"metadata":{},"content":{"seq":231,"type":"event","event":"stopped","body":{"reason":"step","threadId":1,"preserveFocusHint":false,"allThreadsStopped":true}},"buffers":[],"channel":"iopub"}
debug 17:07:23.516: [Debug] to kernel: {"command":"threads","type":"request","seq":145}
debug 17:07:23.516: [Debug] to kernel, mapped: {"command":"threads","type":"request","seq":145}
debug 17:07:23.520: [Debug] response: {"seq":233,"type":"response","request_seq":145,"success":true,"command":"threads","body":{"threads":[{"id":1,"name":"MainThread"},{"id":2,"name":"Thread-3"},{"id":3,"name":"Thread-4"},{"id":4,"name":"IPythonHistorySavingThread"},{"id":5,"name":"Thread-2"}]}}
debug 17:07:23.524: [Debug] to kernel: {"command":"scopes","arguments":{"frameId":35},"type":"request","seq":146}
debug 17:07:23.524: [Debug] to kernel, mapped: {"command":"scopes","arguments":{"frameId":35},"type":"request","seq":146}
debug 17:07:23.527: [Debug] to kernel: {"command":"stackTrace","arguments":{"threadId":1,"startFrame":0,"levels":1},"type":"request","seq":147}
debug 17:07:23.527: [Debug] to kernel, mapped: {"command":"stackTrace","arguments":{"threadId":1,"startFrame":0,"levels":1},"type":"request","seq":147}
[E 17:07:23.528 NotebookApp] Uncaught exception in ZMQStream callback
    Traceback (most recent call last):
      File "/Users/tekumara/code/dt-snowflake-utils/.venv/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
        f = callback(*args, **kwargs)
      File "/Users/tekumara/code/dt-snowflake-utils/.venv/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 308, in stream_callback
        return callback(self, msg)
      File "/Users/tekumara/code/dt-snowflake-utils/.venv/lib/python3.9/site-packages/notebook/services/kernels/handlers.py", line 572, in _on_zmq_reply
        super()._on_zmq_reply(stream, msg)
      File "/Users/tekumara/code/dt-snowflake-utils/.venv/lib/python3.9/site-packages/notebook/base/zmqhandlers.py", line 256, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/Users/tekumara/code/dt-snowflake-utils/.venv/lib/python3.9/site-packages/tornado/websocket.py", line 339, in write_message
        return self.ws_connection.write_message(message, binary=binary)
      File "/Users/tekumara/code/dt-snowflake-utils/.venv/lib/python3.9/site-packages/tornado/websocket.py", line 1086, in write_message
        fut = self._write_frame(True, opcode, message, flags=flags)
      File "/Users/tekumara/code/dt-snowflake-utils/.venv/lib/python3.9/site-packages/tornado/websocket.py", line 1061, in _write_frame
        return self.stream.write(frame)
      File "/Users/tekumara/code/dt-snowflake-utils/.venv/lib/python3.9/site-packages/tornado/iostream.py", line 546, in write
        self._handle_write()
      File "/Users/tekumara/code/dt-snowflake-utils/.venv/lib/python3.9/site-packages/tornado/iostream.py", line 976, in _handle_write
        self._write_buffer.advance(num_bytes)
      File "/Users/tekumara/code/dt-snowflake-utils/.venv/lib/python3.9/site-packages/tornado/iostream.py", line 182, in advance
        assert 0 < size <= self._size
    AssertionError
[E 17:07:23.528 NotebookApp] Uncaught exception in zmqstream callback
    Traceback (most recent call last):
      File "/Users/tekumara/code/dt-snowflake-utils/.venv/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 621, in _handle_events
        self._handle_recv()
      File "/Users/tekumara/code/dt-snowflake-utils/.venv/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 650, in _handle_recv
        self._run_callback(callback, msg)
      File "/Users/tekumara/code/dt-snowflake-utils/.venv/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
        f = callback(*args, **kwargs)
      File "/Users/tekumara/code/dt-snowflake-utils/.venv/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 308, in stream_callback
        return callback(self, msg)
      File "/Users/tekumara/code/dt-snowflake-utils/.venv/lib/python3.9/site-packages/notebook/services/kernels/handlers.py", line 572, in _on_zmq_reply
        super()._on_zmq_reply(stream, msg)
      File "/Users/tekumara/code/dt-snowflake-utils/.venv/lib/python3.9/site-packages/notebook/base/zmqhandlers.py", line 256, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/Users/tekumara/code/dt-snowflake-utils/.venv/lib/python3.9/site-packages/tornado/websocket.py", line 339, in write_message
        return self.ws_connection.write_message(message, binary=binary)
      File "/Users/tekumara/code/dt-snowflake-utils/.venv/lib/python3.9/site-packages/tornado/websocket.py", line 1086, in write_message
        fut = self._write_frame(True, opcode, message, flags=flags)
      File "/Users/tekumara/code/dt-snowflake-utils/.venv/lib/python3.9/site-packages/tornado/websocket.py", line 1061, in _write_frame
        return self.stream.write(frame)
      File "/Users/tekumara/code/dt-snowflake-utils/.venv/lib/python3.9/site-packages/tornado/iostream.py", line 546, in write
        self._handle_write()
      File "/Users/tekumara/code/dt-snowflake-utils/.venv/lib/python3.9/site-packages/tornado/iostream.py", line 976, in _handle_write
        self._write_buffer.advance(num_bytes)
      File "/Users/tekumara/code/dt-snowflake-utils/.venv/lib/python3.9/site-packages/tornado/iostream.py", line 182, in advance
        assert 0 < size <= self._size
    AssertionError
Exception in callback BaseAsyncIOLoop._handle_events(38, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(38, 1)>
Traceback (most recent call last):
  File "/Users/tekumara/.pyenv/versions/3.9.13/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/tekumara/code/dt-snowflake-utils/.venv/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 206, in _handle_events
    handler_func(fileobj, events)
  File "/Users/tekumara/code/dt-snowflake-utils/.venv/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 621, in _handle_events
    self._handle_recv()
  File "/Users/tekumara/code/dt-snowflake-utils/.venv/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 650, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/tekumara/code/dt-snowflake-utils/.venv/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/Users/tekumara/code/dt-snowflake-utils/.venv/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 308, in stream_callback
    return callback(self, msg)
  File "/Users/tekumara/code/dt-snowflake-utils/.venv/lib/python3.9/site-packages/notebook/services/kernels/handlers.py", line 572, in _on_zmq_reply
    super()._on_zmq_reply(stream, msg)
  File "/Users/tekumara/code/dt-snowflake-utils/.venv/lib/python3.9/site-packages/notebook/base/zmqhandlers.py", line 256, in _on_zmq_reply
    self.write_message(msg, binary=isinstance(msg, bytes))
  File "/Users/tekumara/code/dt-snowflake-utils/.venv/lib/python3.9/site-packages/tornado/websocket.py", line 339, in write_message
    return self.ws_connection.write_message(message, binary=binary)
  File "/Users/tekumara/code/dt-snowflake-utils/.venv/lib/python3.9/site-packages/tornado/websocket.py", line 1086, in write_message
    fut = self._write_frame(True, opcode, message, flags=flags)
  File "/Users/tekumara/code/dt-snowflake-utils/.venv/lib/python3.9/site-packages/tornado/websocket.py", line 1061, in _write_frame
    return self.stream.write(frame)
  File "/Users/tekumara/code/dt-snowflake-utils/.venv/lib/python3.9/site-packages/tornado/iostream.py", line 546, in write
    self._handle_write()
  File "/Users/tekumara/code/dt-snowflake-utils/.venv/lib/python3.9/site-packages/tornado/iostream.py", line 976, in _handle_write
    self._write_buffer.advance(num_bytes)
  File "/Users/tekumara/code/dt-snowflake-utils/.venv/lib/python3.9/site-packages/tornado/iostream.py", line 182, in advance
    assert 0 < size <= self._size
AssertionError
debug 17:07:23.545: [Debug] to kernel: {"command":"stackTrace","arguments":{"threadId":1,"startFrame":0,"levels":20},"type":"request","seq":148}
debug 17:07:23.545: [Debug] to kernel, mapped: {"command":"stackTrace","arguments":{"threadId":1,"startFrame":0,"levels":20},"type":"request","seq":148}
```

Possibly interesting - the stack trace is referencing the `dt-snowflake-utils` venv, which is not the currently selected venv.

**Comment by roblourens** [comment]
Is this still happening for you?

@DonJayamanne  Do you know anything about these errors `Uncaught exception in zmqstream callback`

**Comment by jamescooke** [comment]
@roblourens I've found these issues while searching on GH - however, it looks like https://github.com/jupyter/notebook/issues/6721 could be the underlying issue since the stacktraces are very similar. Hope that's helpful 🙏🏻

**Comment by roblourens** [comment]
Thanks. I'll close this, having not heard back and hoping it's an instance of the upstream issue
