### ISSUE TITLE
Kernel with Python 3.6.15 is not usable. Failed to install ipykernel package

### ISSUE THREAD

**Issue by sadasant** [microsoft/vscode-jupyter#12954]
## Environment data

-   VS Code version: 1.76.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2023.2.1000561009
-   Python Extension version (available under the Extensions sidebar): v2023.3.10581011
-   OS (Windows | Mac | Linux distro) and version: Mac Ventura 13.2.1 
-   Python and/or Anaconda version: Python 3.6.15, Anaconda 23.1.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: N/A

## Expected behaviour

It should be able to install `ipykernel`

## Actual behaviour

It fails to install `ipykernel`. The output of the cell says:

```
Running cells with 'dw234' requires the ipykernel package.
Run the following command to install 'ipykernel' into the Python environment. 
Command: 'conda install -n python36 ipykernel --update-deps --force-reinstall'
```

## Steps to reproduce:

1. Create a Conda environment with Python 3.6 with: `conda create --name python36 python=3.6`
2. Try to connect to it.

## Logs

```
info 21:18:51.756: Attempting to start a server because of preload conditions ...
info 21:18:59.801: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd007cd4a3cc944f24b7944b4cd916e9617fa19be525c6c1d419a40ac5c6e7182bb./opt/anaconda3/envs/python36/python./opt/anaconda3/envs/python36/python.-m#ipykernel_launcher (Python Path: /opt/anaconda3/envs/python36, EnvType: Conda, EnvName: 'python36', Version: 3.6.15 | packaged by conda-forge | (default, Dec  3 2021, 18:49:43) 
[GCC Clang 11.1.0]) for '/Users/sadasant/notebooks/project/daniel.ipynb' (disableUI=true)
[I 21:18:59.812 NotebookApp] Creating new notebook in /project
info 21:18:59.829: installMissingDependencies /opt/anaconda3/envs/python36/bin/python, ui.disabled=true for resource '/Users/sadasant/notebooks/project/daniel.ipynb'
info 21:18:59.834: Process Execution: > /opt/anaconda3/envs/python36/bin/python -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> /opt/anaconda3/envs/python36/bin/python -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
warn 21:19:00.222: Error occurred while trying to start the kernel, options.disableUI=true Nf [Error]: Kernel python36 (Python 3.6.15) is not usable. Check the Jupyter output tab for more information.
    at pm.ensureKernelIsUsable (/Users/sadasant/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.2.1000561009/out/extension.node.js:17:210571)
    at dg.createSession (/Users/sadasant/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.2.1000561009/out/extension.node.js:17:266955)
    at dg.createNewKernelSession (/Users/sadasant/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.2.1000561009/out/extension.node.js:17:264580)
    at dg.connect (/Users/sadasant/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.2.1000561009/out/extension.node.js:17:263508)
    at ug.startNew (/Users/sadasant/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.2.1000561009/out/extension.node.js:17:271299)
    at a (/Users/sadasant/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.2.1000561009/out/extension.node.js:17:234755)
    at Nm.createNotebookInstance (/Users/sadasant/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.2.1000561009/out/extension.node.js:17:234906)
    at Nm.createNotebook (/Users/sadasant/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.2.1000561009/out/extension.node.js:17:235602)
    at Pg.createJupyterSession (/Users/sadasant/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.2.1000561009/out/extension.node.js:17:296515) {
  category: 'noipykernel',
  kernelConnectionMetadata: Zs {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: '/Users/sadasant/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.2.1000561009/temp/jupyter/kernels/pythonjvsc74a57bd007cd4a3cc944f24b7944b4cd916e9617fa19be525c6c1d419a40ac5c6e7182bb/kernel.json',
      interpreterPath: '/opt/anaconda3/envs/python36/bin/python',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'pythonjvsc74a57bd007cd4a3cc944f24b7944b4cd916e9617fa19be525c6c1d419a40ac5c6e7182bb',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: 'python36',
      metadata: [Object],
      env: {}
    },
    interpreter: {
      id: '/opt/anaconda3/envs/python36/bin/python',
      sysPrefix: '/opt/anaconda3/envs/python36',
      envPath: [f],
      displayPath: [f],
      envName: 'python36',
      displayName: 'python36',
      envType: 'Conda',
      version: [Object],
      uri: [f]
    },
    id: '.jvsc74a57bd007cd4a3cc944f24b7944b4cd916e9617fa19be525c6c1d419a40ac5c6e7182bb./opt/anaconda3/envs/python36/python./opt/anaconda3/envs/python36/python.-m#ipykernel_launcher'
  },
  reason: 4
}
```

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by DonJayamanne** [comment]
Oh wait, Python 3.6 is no longer supported, I would suggest you install a different version of Python (i.e. upgrade to a later version(

**Comment by DonJayamanne** [comment]
https://devguide.python.org/versions/
