### ISSUE TITLE
Error executing Jupyter command 'notebook': [Errno 2] No such file or directory. 

### ISSUE THREAD

**Issue by robcamp-code** [microsoft/vscode-jupyter#12963]
When I run a notebook cell I get "Error executing Jupyter command 'notebook': [Errno 2] No such file or directory."
I tried reinstalling ipykernel and using different conda environments / python versions and neither seemed to have nay effect.

## Environment data

-   VS Code version: 1.75.1
-   Jupyter Extension version: 2023.1.2010391206
-   Python Extension version: v2023.2.0
-   MAC M1
-   Python version: 3.10.9
-   Tried both venv and conda
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

`from pathlib import Path`
> cell runs properly
## Actual behaviour
`from pathlib import Path`
> Failed to start the Kernel. 
>Jupyter server crashed. Unable to connect. 
>Error code from Jupyter: 1
>Error executing Jupyter command 'notebook': [Errno 2] No such file or directory. 

## Steps to reproduce:

Use vscode versions above on mac m1 above install jupyter notebook and run a cell. 

## Logs

  ```
Error code from Jupyter: 1
  Error executing Jupyter command 'notebook': [Errno 2] No such file or directory

	at Sm.rejectStartPromise (/Users/robertcampbell/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:17:254981)
	at t._complete (/Users/robertcampbell/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:17:255541)
	at t.n (/Users/robertcampbell/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:2:700797)
	at t.__tryOrUnsub (/Users/robertcampbell/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:2:701037)
	at t.complete (/Users/robertcampbell/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:2:700930)
	at t._complete (/Users/robertcampbell/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:2:699446)
	at t.complete (/Users/robertcampbell/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:2:699145)
	at ChildProcess.<anonymous> (/Users/robertcampbell/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:2:1800927)
	at Object.onceWrapper (node:events:646:26)
	at ChildProcess.emit (node:events:538:35)
	at ChildProcess._handle.onexit (node:internal/child_process:291:12)] {
  category: 'jupyterconnection'
}

```

**Comment by DonJayamanne** [comment]
@robcamp-code Sorry you are running into this issue, this has been fixed in  the latest pre-release version of the Jupyter extension

Closing this issue as fixed, if the following does not work, please do let me know and I will re-open this issue, optionally please feel freel to re-open this issue or create a new one.

Instructions for testing the fix:
Open the extensions page, search for Jupyter and click the button `Switch to Pre-Release Version`  
Similarly please install the `Pre-Release` version of the Python extension.

<img width="572" alt="Screenshot 2023-02-04 at 09 24 37" src="https://user-images.githubusercontent.com/1948812/216722719-fd8e14dc-783f-4859-8235-012b1bc796d9.png">
