### ISSUE TITLE
execute selection in Interactive Window doesn't work with a conda interpreter

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#13046]
1. create a conda environment and set it as the active interpreter
2. open a python file and add a few print statements
3. select multiple lines and press shift+enter to execute in the IW
:bug: no cell is added to the IW

This is crashing in the attempt to normalize the selection with normalizeSelection.py ([related issue](https://github.com/microsoft/vscode-jupyter/issues/13045))

error in dev tools: 

```
Error: Error processing line 7 of C:\Users\aamunger\AppData\Roaming\Python\Python310\site-packages\pywin32.pth:


    at sendOutput (c:\src\vscode-jupyter\src\platform\common\process\proc.node.ts:123:38)
    at Socket.<anonymous> (c:\src\vscode-jupyter\src\platform\common\process\proc.node.ts:130:56)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
    at Pipe.callbackTrampoline (node:internal/async_hooks:130:17)
```

**Comment by amunger** [comment]
fixed by no longer normalizing with that py script.
