### ISSUE TITLE
Extension activation failed, run the 'Developer: Toggle Developer Tools' command for more information.

### ISSUE THREAD

**Issue by Voilett** [microsoft/vscode-jupyter#13064]
## Environment data
版本: 1.76.1 (system setup)
提交: 5e805b79fcb6ba4c2d23712967df89a089da575b
日期: 2023-03-08T16:32:00.131Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19045
沙盒化: No

## Actual behaviour

I get an error when I open the jupyter notebook, jupyter extension gives an errore: endsWith is not a function.
now my python version and jupyter version are the latest.

**Comment by amunger** [comment]
Do you have a callstack for that error in the devtools? execute the command `Developer: Toggle Developer tools` to open it

**Comment by amunger** [comment]
can you confirm which version of the jupyter extension you are using when getting this error? you can check in the extensions view.

Can you also try the pre-release version of both Jupyter and Python to check if the issue was fixed there.

**Comment by Voilett** [comment]
Yes, I have tried the pre-release version of both Jupyter and Python, buy it doesn't work. And I have tried many versions of both Jupyter and Python, now they are the lastest version, Jupyter's version is v2023.2.1200692131, Python's version is v2023.4.1.

**Comment by amunger** [comment]
can you provide the error callstack for that newer version (from Developer tools)? I just realized the previous one was for an older version that I can't get the bundled code for anymore.

**Comment by Voilett** [comment]
workbench.desktop.main.js:90 [Extension Host] stack trace: TypeError: e.endsWith is not a function
	at c:\Users\123\.vscode\extensions\ms-toolsai.jupyter-2023.2.1200692131\out\extension.node.js:2:1763061
	at Array.filter (<anonymous>)
	at new jc (c:\Users\123\.vscode\extensions\ms-toolsai.jupyter-2023.2.1200692131\out\extension.node.js:2:1763047)
	at t.resolveInstance (c:\Users\123\.vscode\extensions\ms-toolsai.jupyter-2023.2.1200692131\out\extension.node.js:2:519268)
	at c:\Users\123\.vscode\extensions\ms-toolsai.jupyter-2023.2.1200692131\out\extension.node.js:2:521206
	at t.resolve (c:\Users\123\.vscode\extensions\ms-toolsai.jupyter-2023.2.1200692131\out\extension.node.js:2:521469)
	at c:\Users\123\.vscode\extensions\ms-toolsai.jupyter-2023.2.1200692131\out\extension.node.js:2:507316
	at e._get (c:\Users\123\.vscode\extensions\ms-toolsai.jupyter-2023.2.1200692131\out\extension.node.js:2:507082)
	at e.get (c:\Users\123\.vscode\extensions\ms-toolsai.jupyter-2023.2.1200692131\out\extension.node.js:2:505725)
	at Sy.get (c:\Users\123\.vscode\extensions\ms-toolsai.jupyter-2023.2.1200692131\out\extension.node.js:24:70064)
	at c:\Users\123\.vscode\extensions\ms-toolsai.jupyter-2023.2.1200692131\out\extension.node.js:24:558692
	at c:\Users\123\.vscode\extensions\ms-toolsai.jupyter-2023.2.1200692131\out\extension.node.js:24:559069
	at c:\Users\123\.vscode\extensions\ms-toolsai.jupyter-2023.2.1200692131\out\extension.node.js:24:559077
	at JE (c:\Users\123\.vscode\extensions\ms-toolsai.jupyter-2023.2.1200692131\out\extension.node.js:24:560734)
	at Ui.db (f:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:14833)
	at Ui.cb (f:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:14532)
	at f:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:108:12550
	at async f.n (f:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:6818)
	at async f.m (f:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:6781)
	at async f.l (f:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:94:6238)
T @ workbench.desktop.main.js:90

**Comment by Voilett** [comment]
Thank you very much. It's working fine.
