### ISSUE TITLE
Can't connect to new conda environment with Python 3.7

### ISSUE THREAD

**Issue by sadasant** [microsoft/vscode-jupyter#13078]
## Environment data

-   VS Code version: 1.77.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2023.3.1000752049
-   Python Extension version (available under the Extensions sidebar): v2023.5.10731006
-   OS (Windows | Mac | Linux distro) and version: MacOS Ventura 13.2.1
-   Python and/or Anaconda version: Anaconda 23.1.0, Python 3.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: N/A

## Expected behaviour

It should work

## Actual behaviour

It crashes. The error is:

```
Running cells with 'python375' requires the ipykernel package.
Run the following command to install 'ipykernel' into the Python environment. 
Command: 'conda install -n python375 ipykernel --update-deps --force-reinstall'
```

## Steps to reproduce:

I created a new conda environment with `conda create --name python37 python=3.7`, then in a new `ipynb`, I entered this in a Python cell:

```python
print("HELLO WORLD")
```

## Logs

```
warn 19:17:05.736: Jupyter Kernel Dependency Error, reason=2 nm [Error]: Kernel python375 (Python 3.7.16) is not usable. Check the Jupyter output tab for more information.
    at Nm.ensureKernelIsUsable (/Users/danielrodriguez/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.3.1000752049/out/extension.node.js:17:175951)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Ig.createSession (/Users/danielrodriguez/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.3.1000752049/out/extension.node.js:17:232247)
    at Ig.createNewKernelSession (/Users/danielrodriguez/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.3.1000752049/out/extension.node.js:17:229691)
    at Ig.connect (/Users/danielrodriguez/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.3.1000752049/out/extension.node.js:17:228619)
    at Og.startNew (/Users/danielrodriguez/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.3.1000752049/out/extension.node.js:17:236579)
    at a (/Users/danielrodriguez/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.3.1000752049/out/extension.node.js:17:200224)
    at tg.createNotebookInstance (/Users/danielrodriguez/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.3.1000752049/out/extension.node.js:17:200375)
    at tg.createNotebook (/Users/danielrodriguez/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.3.1000752049/out/extension.node.js:17:201071)
    at zg.createJupyterSession (/Users/danielrodriguez/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.3.1000752049/out/extension.node.js:17:261603) {
  category: 'noipykernel',
  kernelConnectionMetadata: da {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: '/Users/danielrodriguez/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.3.1000752049/temp/jupyter/kernels/pythonjvsc74a57bd0c3343514311384b15c5129fed27564ad0699aab64b8f83effb560a8c0ff08567/kernel.json',
      interpreterPath: '/opt/anaconda3/envs/python375/bin/python',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'pythonjvsc74a57bd0c3343514311384b15c5129fed27564ad0699aab64b8f83effb560a8c0ff08567',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: 'python375',
      metadata: [Object],
      env: {}
    },
    interpreter: {
      id: '/opt/anaconda3/envs/python375/bin/python',
      sysPrefix: '/opt/anaconda3/envs/python375',
      envPath: [w],
      displayPath: [w],
      envName: 'python375',
      displayName: 'python375',
      envType: 'Conda',
      version: [Object],
      uri: [w]
    },
    id: '.jvsc74a57bd0c3343514311384b15c5129fed27564ad0699aab64b8f83effb560a8c0ff08567./opt/anaconda3/envs/python375/python./opt/anaconda3/envs/python375/python.-m#ipykernel_launcher'
  },
  reason: 2
}
info 19:17:05.737: Dispose Kernel 'Untitled-1.ipynb' associated with 'Untitled-1.ipynb'
error 19:17:05.740: Error in execution nm [Error]: Kernel python375 (Python 3.7.16) is not usable. Check the Jupyter output tab for more information.
    at Nm.ensureKernelIsUsable (/Users/danielrodriguez/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.3.1000752049/out/extension.node.js:17:175951)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Ig.createSession (/Users/danielrodriguez/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.3.1000752049/out/extension.node.js:17:232247)
    at Ig.createNewKernelSession (/Users/danielrodriguez/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.3.1000752049/out/extension.node.js:17:229691)
    at Ig.connect (/Users/danielrodriguez/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.3.1000752049/out/extension.node.js:17:228619)
    at Og.startNew (/Users/danielrodriguez/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.3.1000752049/out/extension.node.js:17:236579)
    at a (/Users/danielrodriguez/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.3.1000752049/out/extension.node.js:17:200224)
    at tg.createNotebookInstance (/Users/danielrodriguez/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.3.1000752049/out/extension.node.js:17:200375)
    at tg.createNotebook (/Users/danielrodriguez/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.3.1000752049/out/extension.node.js:17:201071)
    at zg.createJupyterSession (/Users/danielrodriguez/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.3.1000752049/out/extension.node.js:17:261603) {
  category: 'noipykernel',
  kernelConnectionMetadata: da {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: '/Users/danielrodriguez/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.3.1000752049/temp/jupyter/kernels/pythonjvsc74a57bd0c3343514311384b15c5129fed27564ad0699aab64b8f83effb560a8c0ff08567/kernel.json',
      interpreterPath: '/opt/anaconda3/envs/python375/bin/python',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'pythonjvsc74a57bd0c3343514311384b15c5129fed27564ad0699aab64b8f83effb560a8c0ff08567',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: 'python375',
      metadata: [Object],
      env: {}
    },
    interpreter: {
      id: '/opt/anaconda3/envs/python375/bin/python',
      sysPrefix: '/opt/anaconda3/envs/python375',
      envPath: [w],
      displayPath: [w],
      envName: 'python375',
      displayName: 'python375',
      envType: 'Conda',
      version: [Object],
      uri: [w]
    },
    id: '.jvsc74a57bd0c3343514311384b15c5129fed27564ad0699aab64b8f83effb560a8c0ff08567./opt/anaconda3/envs/python375/python./opt/anaconda3/envs/python375/python.-m#ipykernel_launcher'
  },
  reason: 2
}
error 19:17:05.741: Error in execution (get message for cell) nm [Error]: Kernel python375 (Python 3.7.16) is not usable. Check the Jupyter output tab for more information.
    at Nm.ensureKernelIsUsable (/Users/danielrodriguez/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.3.1000752049/out/extension.node.js:17:175951)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Ig.createSession (/Users/danielrodriguez/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.3.1000752049/out/extension.node.js:17:232247)
    at Ig.createNewKernelSession (/Users/danielrodriguez/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.3.1000752049/out/extension.node.js:17:229691)
    at Ig.connect (/Users/danielrodriguez/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.3.1000752049/out/extension.node.js:17:228619)
    at Og.startNew (/Users/danielrodriguez/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.3.1000752049/out/extension.node.js:17:236579)
    at a (/Users/danielrodriguez/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.3.1000752049/out/extension.node.js:17:200224)
    at tg.createNotebookInstance (/Users/danielrodriguez/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.3.1000752049/out/extension.node.js:17:200375)
    at tg.createNotebook (/Users/danielrodriguez/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.3.1000752049/out/extension.node.js:17:201071)
    at zg.createJupyterSession (/Users/danielrodriguez/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.3.1000752049/out/extension.node.js:17:261603) {
  category: 'noipykernel',
  kernelConnectionMetadata: da {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: '/Users/danielrodriguez/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.3.1000752049/temp/jupyter/kernels/pythonjvsc74a57bd0c3343514311384b15c5129fed27564ad0699aab64b8f83effb560a8c0ff08567/kernel.json',
      interpreterPath: '/opt/anaconda3/envs/python375/bin/python',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'pythonjvsc74a57bd0c3343514311384b15c5129fed27564ad0699aab64b8f83effb560a8c0ff08567',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: 'python375',
      metadata: [Object],
      env: {}
    },
    interpreter: {
      id: '/opt/anaconda3/envs/python375/bin/python',
      sysPrefix: '/opt/anaconda3/envs/python375',
      envPath: [w],
      displayPath: [w],
      envName: 'python375',
      displayName: 'python375',
      envType: 'Conda',
      version: [Object],
      uri: [w]
    },
    id: '.jvsc74a57bd0c3343514311384b15c5129fed27564ad0699aab64b8f83effb560a8c0ff08567./opt/anaconda3/envs/python375/python./opt/anaconda3/envs/python375/python.-m#ipykernel_launcher'
  },
  reason: 2
}
```

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by sadasant** [comment]
Done! Here's the `Jupyter` output from the output panel: https://gist.github.com/sadasant/4165e34fc08b81baa8048074abb6b624

I don't see any Jupyter Server Console.

**Comment by DonJayamanne** [comment]
@sadasant please could you update to the latest pre-release version of the Jupyter extesnion and let me know how that goes
Again, please do share all the logs if you run into an issue.

**Comment by DonJayamanne** [comment]
Closing as its a environment issue.

**Comment by sadasant** [comment]
Thank you, @DonJayamanne ! I made this issue on conda after our conversation: https://github.com/conda/conda/issues/12494
