### ISSUE TITLE
Restarting kernel is slow in general, but sometimes gets completely stuck.

### ISSUE THREAD

**Issue by tajtac** [microsoft/vscode-jupyter#13083]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Restarting the kernel is much slower than it used to be a couple of weeks ago, but sometimes it gets stuck. I get a message in the bottom right that says "Restarting Kernel: ..." that never goes away and the notebook is irresponsive. The only solution is to quit vscode and restart.

I tried deleting all my user settings and reinstalling the latest version of vscode, but it didn't help.

### VS Code Version

1.76.2

### Jupyter Extension Version

v2023.2.1200692131

### Jupyter logs

```shell
Visual Studio Code (1.76.2, undefined, desktop)
Jupyter Extension Version: 2023.2.1200692131.
Python Extension Version: 2023.4.1.
Workspace folder /Users/vt/Library/CloudStorage/OneDrive-purdue.edu/Research/BayesianNN
warn 14:39:17.187: Exception while attempting zmq : No native build was found for platform=darwin arch=arm64 runtime=electron abi=106 uv=1 armv=8 libc=glibc node=16.14.2 electron=19.1.11
    loaded from: /Users/vt/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/out/node_modules/zeromq

User belongs to experiment group 'jupyterEnhancedDataViewer'
User belongs to experiment group 'jupyterTestcf'
info 14:39:17.280: Attempting to start a server because of preload conditions ...
info 14:39:17.289: LSP Notebooks experiment is enabled
info 14:39:17.299: Checking for server existence.
warn 14:39:17.511: Failed to get activated env vars with python /usr/bin/python3 in 146ms
warn 14:39:17.513: Failed to get activated env vars with python /usr/bin/python3 in 147ms
info 14:39:17.524: Process Execution: > /usr/bin/python3 -c "import site;print("USER_BASE_VALUE");print(site.USER_SITE);print("USER_BASE_VALUE");"
> /usr/bin/python3 -c "import site;print("USER_BASE_VALUE");print(site.USER_SITE);print("USER_BASE_VALUE");"
info 14:39:17.528: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd0a665b5d41d17b532ea9890333293a1b812fa0b73c9c25c950b3cedf1bebd0438./opt/homebrew/bin/python3.9./opt/homebrew/bin/python3.9.-m#ipykernel_launcher (Python Path: , EnvType: Unknown, EnvName: '', Version: 3.9.16 (main, Dec  7 2022, 10:02:13) 
[Clang 14.0.0 (clang-1400.0.29.202)]) for 'Untitled-1.ipynb' (disableUI=true)
info 14:39:17.576: Process Execution: > /usr/bin/python3 -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> /usr/bin/python3 -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 14:39:17.576: Process Execution: > /usr/bin/python3 -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> /usr/bin/python3 -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
warn 14:39:17.587: Failed to get activated env vars with python /opt/homebrew/bin/python3.9 in 59ms
info 14:39:17.588: Process Execution: > /opt/homebrew/bin/python3.9 -c "import site;print("USER_BASE_VALUE");print(site.USER_SITE);print("USER_BASE_VALUE");"
> /opt/homebrew/bin/python3.9 -c "import site;print("USER_BASE_VALUE");print(site.USER_SITE);print("USER_BASE_VALUE");"
info 14:39:17.617: Process Execution: > /opt/homebrew/bin/python3.9 -m pip list
> /opt/homebrew/bin/python3.9 -m pip list
warn 14:39:17.794: Failed to get activated env vars with python /usr/bin/python3 in 106ms
info 14:39:17.795: Process Execution: > /usr/bin/python3 -m jupyter kernelspec --version
> /usr/bin/python3 -m jupyter kernelspec --version
info 14:39:17.968: Connecting to server
info 14:39:17.968: Launching server
info 14:39:17.968: Starting Notebook
info 14:39:17.971: Generating custom default config at /var/folders/1f/rngrmz8x3lsd60h6dd90ncwm0000gr/T/2e6011f4-c088-4eb6-a243-6a3724775252/jupyter_notebook_config.py
Starting Jupyter from /usr/bin/python3 with arguments --no-browser --notebook-dir="/Users/vt/Library/CloudStorage/OneDrive-purdue.edu/Research/BayesianNN" --config=/var/folders/1f/rngrmz8x3lsd60h6dd90ncwm0000gr/T/2e6011f4-c088-4eb6-a243-6a3724775252/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
warn 14:39:18.050: Failed to get activated env vars with python /usr/bin/python3 in 83ms
warn 14:39:18.057: Failed to get activated env vars with python /usr/bin/python3 in 90ms
warn 14:39:18.057: Failed to get activated env vars with python /usr/bin/python3 in 86ms
warn 14:39:18.068: Failed to get activated env vars with python /usr/bin/python3 in 10ms
info 14:39:18.070: Process Execution: > /usr/bin/python3 -m jupyter notebook --no-browser --notebook-dir="/Users/vt/Library/CloudStorage/OneDrive-purdue.edu/Research/BayesianNN" --config=/var/folders/1f/rngrmz8x3lsd60h6dd90ncwm0000gr/T/2e6011f4-c088-4eb6-a243-6a3724775252/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
> /usr/bin/python3 -m jupyter notebook --no-browser --notebook-dir="/Users/vt/Library/CloudStorage/OneDrive-purdue.edu/Research/BayesianNN" --config=/var/folders/1f/rngrmz8x3lsd60h6dd90ncwm0000gr/T/2e6011f4-c088-4eb6-a243-6a3724775252/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
/Users/vt/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/Users/vt/Library/CloudStorage/OneDrive-purdue.edu/Research/BayesianNN' instead of '"/Users/vt/Library/CloudStorage/OneDrive-purdue.edu/Research/BayesianNN"' if you require traitlets >=5.
  warn(
info 14:39:18.333: Process Execution: > ~/miniforge3/bin/python -m pip list
> ~/miniforge3/bin/python -m pip list
[I 14:39:18.470 NotebookApp] The port 8888 is already in use, trying another port.
[I 14:39:18.472 NotebookApp] Serving notebooks from local directory: /Users/vt/Library/CloudStorage/OneDrive-purdue.edu/Research/BayesianNN
[I 14:39:18.472 NotebookApp] Jupyter Notebook 6.5.2 is running at:
[I 14:39:18.472 NotebookApp] http://localhost:8889/?token=cb6237fe7eac4febcbff75ee34ebdea9e4e70a60485ddcc8
[I 14:39:18.472 NotebookApp]  or http://127.0.0.1:8889/?token=cb6237fe7eac4febcbff75ee34ebdea9e4e70a60485ddcc8
[I 14:39:18.472 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 14:39:18.474 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/vt/Library/Jupyter/runtime/nbserver-4782-open.html
    Or copy and paste one of these URLs:
        http://localhost:8889/?token=cb6237fe7eac4febcbff75ee34ebdea9e4e70a60485ddcc8
     or http://127.0.0.1:8889/?token=cb6237fe7eac4febcbff75ee34ebdea9e4e70a60485ddcc8
warn 14:39:18.475: Failed to get activated env vars with python /usr/bin/python3 in 3ms
info 14:39:18.476: Process Execution: > /usr/bin/python3 ~/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> /usr/bin/python3 ~/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/pythonFiles/vscode_datascience_helpers/getServerInfo.py
warn 14:39:18.476: Failed to get activated env vars with python /usr/bin/python3 in 2ms
info 14:39:18.477: Process Execution: > /usr/bin/python3 ~/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> /usr/bin/python3 ~/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/pythonFiles/vscode_datascience_helpers/getServerInfo.py
info 14:39:18.715: Connecting local server kernel http://localhost:8889/
info 14:39:18.715: Creating server with url : http://localhost:8889/
info 14:39:18.718: Server started.
[I 14:39:18.846 NotebookApp] Creating new notebook in 
info 14:39:18.889: installMissingDependencies /opt/homebrew/bin/python3.9, ui.disabled=true for resource 'Untitled-1.ipynb'
warn 14:39:18.891: Failed to get activated env vars with python /opt/homebrew/bin/python3.9 in 1ms
info 14:39:18.892: Process Execution: > /opt/homebrew/bin/python3.9 -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> /opt/homebrew/bin/python3.9 -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 14:39:19.018: Spec argv[0] updated from '/opt/homebrew/bin/python3.9' to '/opt/homebrew/bin/python3.9'
warn 14:39:19.021: Failed to get activated env vars with python /opt/homebrew/bin/python3.9 in 2ms
[I 14:39:19.063 NotebookApp] Kernel started: 514be770-fd65-42ab-b36c-130dde6d212e, name: pythonjvsc74a57bd0a665b5d41d17b532ea9890333293a1b812fa0b73c9c25c950b3cedf1bebd0438
[W 14:39:19.105 NotebookApp] delete /Untitled-1-jvsc-65c7111d-e7b6-47b2-a34a-6700d14f0b4222d67711-d864-479b-9e83-b22faf1adc1f.ipynb
info 14:39:29.618: Started session for kernel startUsingPythonInterpreter:.jvsc74a57bd0a665b5d41d17b532ea9890333293a1b812fa0b73c9c25c950b3cedf1bebd0438./opt/homebrew/bin/python3.9./opt/homebrew/bin/python3.9.-m#ipykernel_launcher
warn 14:39:29.666: Failed to get activated env vars with python /opt/homebrew/bin/python3.9 in 2ms
info 14:39:29.667: Process Execution: > /opt/homebrew/bin/python3.9 ~/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/pythonFiles/printJupyterDataDir.py
> /opt/homebrew/bin/python3.9 ~/.vscode/extensions/ms-toolsai.jupyter-2023.2.1200692131/pythonFiles/printJupyterDataDir.py
info 14:39:39.730: Restart kernel execution
info 14:39:39.730: Restart requested untitled:Untitled-1.ipynb?jupyter-notebook
info 14:39:39.731: Restarting 514be770-fd65-42ab-b36c-130dde6d212e
[I 14:39:39.765 NotebookApp] Creating new notebook in 
info 14:39:39.781: installMissingDependencies /opt/homebrew/bin/python3.9, ui.disabled=false for resource 'Untitled-1.ipynb'
warn 14:39:39.784: Failed to get activated env vars with python /opt/homebrew/bin/python3.9 in 3ms
info 14:39:39.785: Process Execution: > /opt/homebrew/bin/python3.9 -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> /opt/homebrew/bin/python3.9 -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 14:39:39.883: Spec argv[0] updated from '/opt/homebrew/bin/python3.9' to '/opt/homebrew/bin/python3.9'
warn 14:39:39.886: Failed to get activated env vars with python /opt/homebrew/bin/python3.9 in 3ms
[I 14:39:39.929 NotebookApp] Kernel started: a7d6c001-8d34-4b6f-81bf-6226a48ea109, name: pythonjvsc74a57bd0a665b5d41d17b532ea9890333293a1b812fa0b73c9c25c950b3cedf1bebd0438
[W 14:39:39.987 NotebookApp] delete /Untitled-1-jvsc-2ff4e790-4218-4b21-b851-76e127ad531b1f1ca9f7-466f-480b-86b1-5afdd9b491d0.ipynb
info 14:39:49.594: Got new session a7d6c001-8d34-4b6f-81bf-6226a48ea109
info 14:39:49.594: Started new restart session
[I 14:39:49.622 NotebookApp] Kernel shutdown: 514be770-fd65-42ab-b36c-130dde6d212e
info 14:40:05.582: Restart kernel execution
info 14:40:05.583: Restart requested untitled:Untitled-1.ipynb?jupyter-notebook
info 14:40:05.583: Restarting a7d6c001-8d34-4b6f-81bf-6226a48ea109
[I 14:40:05.614 NotebookApp] Creating new notebook in 
info 14:40:05.630: installMissingDependencies /opt/homebrew/bin/python3.9, ui.disabled=false for resource 'Untitled-1.ipynb'
warn 14:40:05.634: Failed to get activated env vars with python /opt/homebrew/bin/python3.9 in 3ms
info 14:40:05.635: Process Execution: > /opt/homebrew/bin/python3.9 -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> /opt/homebrew/bin/python3.9 -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 14:40:05.732: Spec argv[0] updated from '/opt/homebrew/bin/python3.9' to '/opt/homebrew/bin/python3.9'
warn 14:40:05.735: Failed to get activated env vars with python /opt/homebrew/bin/python3.9 in 3ms
[I 14:40:05.777 NotebookApp] Kernel started: 6f3eb0cf-235e-4a59-9627-165cea8e75b1, name: pythonjvsc74a57bd0a665b5d41d17b532ea9890333293a1b812fa0b73c9c25c950b3cedf1bebd0438
[W 14:40:05.827 NotebookApp] delete /Untitled-1-jvsc-d78b2d3f-c8bb-4727-a235-44d340afc7923a43c0bd-d3d3-4fce-8231-5cfb08467089.ipynb
info 14:40:10.474: Got new session 6f3eb0cf-235e-4a59-9627-165cea8e75b1
info 14:40:10.474: Started new restart session
[I 14:40:10.497 NotebookApp] Kernel shutdown: a7d6c001-8d34-4b6f-81bf-6226a48ea109
info 14:40:13.769: Restart kernel execution
info 14:40:13.769: Restart requested untitled:Untitled-1.ipynb?jupyter-notebook
info 14:40:13.769: Restarting 6f3eb0cf-235e-4a59-9627-165cea8e75b1
[I 14:40:13.792 NotebookApp] Creating new notebook in 
info 14:40:13.812: installMissingDependencies /opt/homebrew/bin/python3.9, ui.disabled=false for resource 'Untitled-1.ipynb'
warn 14:40:13.816: Failed to get activated env vars with python /opt/homebrew/bin/python3.9 in 4ms
info 14:40:13.817: Process Execution: > /opt/homebrew/bin/python3.9 -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> /opt/homebrew/bin/python3.9 -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 14:40:13.916: Spec argv[0] updated from '/opt/homebrew/bin/python3.9' to '/opt/homebrew/bin/python3.9'
warn 14:40:13.919: Failed to get activated env vars with python /opt/homebrew/bin/python3.9 in 3ms
[I 14:40:13.961 NotebookApp] Kernel started: 0c4ed6ef-1cb0-4028-a8fe-4c09d146238e, name: pythonjvsc74a57bd0a665b5d41d17b532ea9890333293a1b812fa0b73c9c25c950b3cedf1bebd0438
[W 14:40:14.007 NotebookApp] delete /Untitled-1-jvsc-2a803320-a942-4755-a82f-b77684578dcdc1a958e5-5ee8-4687-9e8c-c82d81bd27c1.ipynb
info 14:40:19.600: Got new session 0c4ed6ef-1cb0-4028-a8fe-4c09d146238e
info 14:40:19.600: Started new restart session
[I 14:40:19.627 NotebookApp] Kernel shutdown: 6f3eb0cf-235e-4a59-9627-165cea8e75b1
info 14:40:22.186: Restart kernel execution
info 14:40:22.186: Restart requested untitled:Untitled-1.ipynb?jupyter-notebook
info 14:40:22.186: Restarting 0c4ed6ef-1cb0-4028-a8fe-4c09d146238e
[I 14:40:22.208 NotebookApp] Creating new notebook in 
info 14:40:22.248: installMissingDependencies /opt/homebrew/bin/python3.9, ui.disabled=false for resource 'Untitled-1.ipynb'
warn 14:40:22.251: Failed to get activated env vars with python /opt/homebrew/bin/python3.9 in 3ms
info 14:40:22.252: Process Execution: > /opt/homebrew/bin/python3.9 -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> /opt/homebrew/bin/python3.9 -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 14:40:22.357: Spec argv[0] updated from '/opt/homebrew/bin/python3.9' to '/opt/homebrew/bin/python3.9'
warn 14:40:22.361: Failed to get activated env vars with python /opt/homebrew/bin/python3.9 in 4ms
[I 14:40:22.404 NotebookApp] Kernel started: 89aa4826-4b2b-4450-a20c-b0bbcc5400bf, name: pythonjvsc74a57bd0a665b5d41d17b532ea9890333293a1b812fa0b73c9c25c950b3cedf1bebd0438
[W 14:40:22.457 NotebookApp] delete /Untitled-1-jvsc-42dc58ca-aa50-45a2-8c7c-d6f8b9c99d06ddad085a-7b21-43a3-90d8-f21ed3b55527.ipynb
info 14:40:32.965: Got new session 89aa4826-4b2b-4450-a20c-b0bbcc5400bf
info 14:40:32.965: Started new restart session
[E 14:40:32.966 NotebookApp] Uncaught exception in ZMQStream callback
    Traceback (most recent call last):
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
        f = callback(*args, **kwargs)
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/zmq/eventloop/zmqstream.py", line 308, in stream_callback
        return callback(self, msg)
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/notebook/services/kernels/handlers.py", line 572, in _on_zmq_reply
        super()._on_zmq_reply(stream, msg)
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/notebook/base/zmqhandlers.py", line 256, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/tornado/websocket.py", line 339, in write_message
        return self.ws_connection.write_message(message, binary=binary)
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/tornado/websocket.py", line 1086, in write_message
        fut = self._write_frame(True, opcode, message, flags=flags)
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/tornado/websocket.py", line 1061, in _write_frame
        return self.stream.write(frame)
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/tornado/iostream.py", line 546, in write
        self._handle_write()
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/tornado/iostream.py", line 976, in _handle_write
        self._write_buffer.advance(num_bytes)
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/tornado/iostream.py", line 182, in advance
        assert 0 < size <= self._size
    AssertionError
[E 14:40:32.972 NotebookApp] Uncaught exception in zmqstream callback
    Traceback (most recent call last):
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/zmq/eventloop/zmqstream.py", line 621, in _handle_events
        self._handle_recv()
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/zmq/eventloop/zmqstream.py", line 650, in _handle_recv
        self._run_callback(callback, msg)
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
        f = callback(*args, **kwargs)
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/zmq/eventloop/zmqstream.py", line 308, in stream_callback
        return callback(self, msg)
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/notebook/services/kernels/handlers.py", line 572, in _on_zmq_reply
        super()._on_zmq_reply(stream, msg)
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/notebook/base/zmqhandlers.py", line 256, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/tornado/websocket.py", line 339, in write_message
        return self.ws_connection.write_message(message, binary=binary)
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/tornado/websocket.py", line 1086, in write_message
        fut = self._write_frame(True, opcode, message, flags=flags)
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/tornado/websocket.py", line 1061, in _write_frame
        return self.stream.write(frame)
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/tornado/iostream.py", line 546, in write
        self._handle_write()
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/tornado/iostream.py", line 976, in _handle_write
        self._write_buffer.advance(num_bytes)
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/tornado/iostream.py", line 182, in advance
        assert 0 < size <= self._size
    AssertionError
[E 14:40:32.972 NotebookApp] Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x108551a60>)
    Traceback (most recent call last):
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/tornado/ioloop.py", line 740, in _run_callback
        ret = callback()
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/zmq/eventloop/zmqstream.py", line 705, in <lambda>
        self.io_loop.add_callback(lambda: self._handle_events(self.socket, 0))
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/zmq/eventloop/zmqstream.py", line 621, in _handle_events
        self._handle_recv()
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/zmq/eventloop/zmqstream.py", line 650, in _handle_recv
        self._run_callback(callback, msg)
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
        f = callback(*args, **kwargs)
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/zmq/eventloop/zmqstream.py", line 308, in stream_callback
        return callback(self, msg)
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/notebook/services/kernels/handlers.py", line 572, in _on_zmq_reply
        super()._on_zmq_reply(stream, msg)
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/notebook/base/zmqhandlers.py", line 256, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/tornado/websocket.py", line 339, in write_message
        return self.ws_connection.write_message(message, binary=binary)
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/tornado/websocket.py", line 1086, in write_message
        fut = self._write_frame(True, opcode, message, flags=flags)
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/tornado/websocket.py", line 1061, in _write_frame
        return self.stream.write(frame)
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/tornado/iostream.py", line 546, in write
        self._handle_write()
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/tornado/iostream.py", line 976, in _handle_write
        self._write_buffer.advance(num_bytes)
      File "/Users/vt/Library/Python/3.9/lib/python/site-packages/tornado/iostream.py", line 182, in advance
        assert 0 < size <= self._size
    AssertionError
[I 14:40:32.988 NotebookApp] Kernel shutdown: 0c4ed6ef-1cb0-4028-a8fe-4c09d146238e
```

### Coding Language and Runtime Version

Python v3.9.16

### Running Jupyter locally or remotely?

Local

**Comment by tajtac** [comment]
Update: The issue was resolved by updating pyzmq from 25.0.0 to 25.0.1
