### ISSUE TITLE
Test failure: Contributed Local Kernel Spec Finder (only fails on Windows)

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#13236]
https://github.com/microsoft/vscode-jupyter/actions/runs/4561652951/jobs/8047862257

```
  1) Contributed Local Kernel Spec Finder Unix
       without active Python
         If two kernelspecs share the same interpreter, but have different env variables, then both should be listed:

      Incorrect # of kernels
      + expected - actual

      -2
      +4
      
      at verifyKernels (out\kernels\raw\finder\contributedKerneFinder.node.unit.test.js:10405:21)
      at verifyKernelsAndIfFailedThenWaitForAnotherChangeEventAndRetry (out\kernels\raw\finder\contributedKerneFinder.node.unit.test.js:10763:13)
      at Context.<anonymous> (out\kernels\raw\finder\contributedKerneFinder.node.unit.test.js:10840:11)

  2) Contributed Local Kernel Spec Finder Unix
       without active Python
         Discover multiple global kernelspecs and a custom Python kernelspecs with env vars:

      Incorrect # of kernels
      + expected - actual

      -3
      +5
      
      at verifyKernels (out\kernels\raw\finder\contributedKerneFinder.node.unit.test.js:10405:21)
      at verifyKernelsAndIfFailedThenWaitForAnotherChangeEventAndRetry (out\kernels\raw\finder\contributedKerneFinder.node.unit.test.js:10763:13)
      at Context.<anonymous> (out\kernels\raw\finder\contributedKerneFinder.node.unit.test.js:10880:11)

```

**Comment by DonJayamanne** [comment]
No longer flaky
