### ISSUE TITLE
intellisense doesn't work in jupyter notebooks on a remote server when an anaconda env is chosen for running the kernel

### ISSUE THREAD

**Issue by radekosmulski** [microsoft/vscode-jupyter#13268]

**Comment by radekosmulski** [comment]
This is quite interesting, because turns out it sometimes works with Anaconda envs!

This is for system python where intelisense has always worked for me so far:
```
[Info  - 12:54:46 PM] (3767) Pylance language server 2023.3.40 (pyright 04471971) starting
[Info  - 12:54:46 PM] (3767) Server root directory: /home/radek/.vscode-server/extensions/ms-python.vscode-pylance-2023.3.40/dist
[Info  - 12:54:46 PM] (3767) Starting service instance "ai_experiments"
[Info  - 12:54:46 PM] (3767) Auto-indent enabled
[Info  - 12:54:46 PM] (3767) No configuration file found.
[Info  - 12:54:46 PM] (3767) No pyproject.toml file found.
[Info  - 12:54:46 PM] (3767) Setting pythonPath for service "ai_experiments": "/bin/python3"
[Warn  - 12:54:46 PM] (3767) stubPath /home/radek/workspace/ai_experiments/typings is not a valid directory.
[Info  - 12:54:46 PM] (3767) Assuming Python version 3.10
[Info  - 12:54:46 PM] (3767) Assuming Python platform Linux
[Info  - 12:54:46 PM] (3767) Searching for source files
[Info  - 12:54:46 PM] (3767) No source files found.
[Info  - 12:54:46 PM] (3767) Background analysis(1) root directory: /home/radek/.vscode-server/extensions/ms-python.vscode-pylance-2023.3.40/dist
[Info  - 12:54:46 PM] (3767) Background analysis(1) started
[Info  - 12:54:47 PM] (3767) Indexer background runner(2) root directory: /home/radek/.vscode-server/extensions/ms-python.vscode-pylance-2023.3.40/dist (index)
[Info  - 12:54:47 PM] (3767) Indexing(2) started
[Info  - 12:54:47 PM] (3767) scanned(2) 151 files over 1 exec env
[Info  - 12:54:48 PM] (3767) indexed(2) 88 files over 1 exec env
[Info  - 12:54:48 PM] (3767) Indexing finished(2).
```

I then switched to using an Anaconda env and... to my surprise it worked! (I reloaded the window though using command palette, not sure if that played a role).

But to reproduce the error I created a new file and picked the kernel only when I wanted to run the code. Then the issue came up again. There is an issue that comes up in the logs:

```
[Info  - 12:56:32 PM] (4105) Pylance language server 2023.3.40 (pyright 04471971) starting
[Info  - 12:56:32 PM] (4105) Server root directory: /home/radek/.vscode-server/extensions/ms-python.vscode-pylance-2023.3.40/dist
[Info  - 12:56:32 PM] (4105) Starting service instance "ai_experiments"
[Info  - 12:56:32 PM] (4105) Auto-indent enabled
[Info  - 12:56:32 PM] (4105) No configuration file found.
[Info  - 12:56:32 PM] (4105) No pyproject.toml file found.
[Info  - 12:56:32 PM] (4105) Setting pythonPath for service "ai_experiments": "/bin/python3"
[Warn  - 12:56:32 PM] (4105) stubPath /home/radek/workspace/ai_experiments/typings is not a valid directory.
[Info  - 12:56:32 PM] (4105) Assuming Python version 3.10
[Info  - 12:56:32 PM] (4105) Assuming Python platform Linux
[Info  - 12:56:32 PM] (4105) Searching for source files
[Info  - 12:56:32 PM] (4105) No source files found.
[Info  - 12:56:32 PM] (4105) Starting service instance "ai_experiments"
[Info  - 12:56:32 PM] (4105) No configuration file found.
[Info  - 12:56:32 PM] (4105) No pyproject.toml file found.
[Info  - 12:56:32 PM] (4105) Setting pythonPath for service "ai_experiments": "/home/radek/miniconda3/envs/rapids-22.10/bin/python"
[Warn  - 12:56:32 PM] (4105) stubPath /home/radek/workspace/ai_experiments/typings is not a valid directory.
[Info  - 12:56:32 PM] (4105) Assuming Python version 3.8
[Info  - 12:56:32 PM] (4105) Assuming Python platform Linux
[Info  - 12:56:32 PM] (4105) Searching for source files
[Info  - 12:56:32 PM] (4105) No source files found.
[Info  - 12:56:32 PM] (4105) Background analysis(1) root directory: /home/radek/.vscode-server/extensions/ms-python.vscode-pylance-2023.3.40/dist
[Info  - 12:56:32 PM] (4105) Background analysis(1) started
[Info  - 12:56:33 PM] (4105) Background analysis(2) root directory: /home/radek/.vscode-server/extensions/ms-python.vscode-pylance-2023.3.40/dist
[Info  - 12:56:33 PM] (4105) Background analysis(2) started
[Info  - 12:56:33 PM] (4105) Indexer background runner(3) root directory: /home/radek/.vscode-server/extensions/ms-python.vscode-pylance-2023.3.40/dist (index)
[Info  - 12:56:33 PM] (4105) Indexing(3) started
[Info  - 12:56:33 PM] (4105) scanned(3) 469 files over 1 exec env
[Info  - 12:56:37 PM] (4105) [IDX(3)] Long operation: index execution environment /home/radek/workspace/ai_experiments (3440ms)
[Info  - 12:56:37 PM] (4105) [IDX(3)] Long operation: index packages /home/radek/workspace/ai_experiments (3447ms)
[Info  - 12:56:37 PM] (4105) indexed(3) 304 files over 1 exec env
[Info  - 12:56:37 PM] (4105) Indexing finished(3).
[Info  - 12:59:14 PM] (4105) Indexer background runner(4) root directory: /home/radek/.vscode-server/extensions/ms-python.vscode-pylance-2023.3.40/dist (index)
[Info  - 12:59:14 PM] (4105) Indexing(4) started
[Info  - 12:59:15 PM] (4105) scanned(4) 151 files over 1 exec env
[Info  - 12:59:16 PM] (4105) indexed(4) 88 files over 1 exec env
[Info  - 12:59:16 PM] (4105) Indexing finished(4).
[Info  - 12:59:29 PM] (4105) Starting service instance "ai_experiments"
[Info  - 12:59:29 PM] (4105) No configuration file found.
[Info  - 12:59:29 PM] (4105) No pyproject.toml file found.
[Info  - 12:59:29 PM] (4105) Setting pythonPath for service "ai_experiments": "/home/radek/miniconda3/envs/rapids-22.10/bin/python"
[Warn  - 12:59:29 PM] (4105) stubPath /home/radek/workspace/ai_experiments/typings is not a valid directory.
[Info  - 12:59:29 PM] (4105) Assuming Python version 3.8
[Info  - 12:59:29 PM] (4105) Assuming Python platform Linux
[Info  - 12:59:29 PM] (4105) Searching for source files
[Info  - 12:59:29 PM] (4105) No source files found.
[Info  - 12:59:29 PM] (4105) Background analysis(5) root directory: /home/radek/.vscode-server/extensions/ms-python.vscode-pylance-2023.3.40/dist
[Info  - 12:59:29 PM] (4105) Background analysis(5) started
[Info  - 12:59:29 PM] (4105) Indexer background runner(6) root directory: /home/radek/.vscode-server/extensions/ms-python.vscode-pylance-2023.3.40/dist (index)
[Info  - 12:59:29 PM] (4105) Indexing(6) started
[Info  - 12:59:29 PM] (4105) scanned(6) 469 files over 1 exec env
Error: Debug Failure. False expression: Chained file path doesn't match prefixCellFilePath
    at _0x20038d (/home/radek/.vscode-server/extensions/ms-python.vscode-pylance-2023.3.40/dist/server.bundle.js:1:474758)
    at /home/radek/.vscode-server/extensions/ms-python.vscode-pylance-2023.3.40/dist/server.bundle.js:1:478944
    at _0x18414c (/home/radek/.vscode-server/extensions/ms-python.vscode-pylance-2023.3.40/dist/server.bundle.js:1:478976)
    at _0x2998c7._onDidChangeNotebookDocumentAsync (/home/radek/.vscode-server/extensions/ms-python.vscode-pylance-2023.3.40/dist/server.bundle.js:1:444100)
[Info  - 12:59:33 PM] (4105) [IDX(6)] Long operation: index execution environment /home/radek/workspace/ai_experiments (3515ms)
[Info  - 12:59:33 PM] (4105) [IDX(6)] Long operation: index packages /home/radek/workspace/ai_experiments (3526ms)
[Info  - 12:59:33 PM] (4105) indexed(6) 304 files over 1 exec env
[Info  - 12:59:33 PM] (4105) Indexing finished(6).
```

And interestingly, if I reload the window (`Developer: Reload window`) the issue goes away!
