### ISSUE TITLE
Unable to run Jupyer (.ipynb) file on VS Code in Windows 10 

### ISSUE THREAD

**Issue by kshitijdwivedi28** [microsoft/vscode-jupyter#13266]
## Environment data

-   VS Code version: 1.77.0
-   Jupyter Extension version (available under the Extensions sidebar):  v2023.3.1000892223
-   Python Extension version (available under the Extensions sidebar): v2023.6.0
-   OS (Windows | Mac | Linux distro) and version: Windows NT x64 10.0.19044
-   Python and/or Anaconda version: 3.11.2 / 3.10.2 / 3.9.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

More about VS-Code
Version: 1.77.0 (user setup)
Commit: 7f329fe6c66b0f86ae1574c2911b681ad5a45d63
Date: 2023-03-29T10:02:16.981Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: Yes

## Expected behaviour

The jupyter file was running the code normally a month ago.

## Actual behaviour

Now, it is unable to run even one cell. When I run a simple cell with print statement, it is showing the below error.

Failed to start the Kernel. 
Unable to start Kernel 'Python 3.11.2' due to connection timeout. 
View Jupyter [log](command:jupyter.viewOutput) for further details.

I can see the same error with all 3 versions of Python that I have on my machine. 3.11.2, 3.10.2 and 3.9.6

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Just created a .ipynb file in VS-Code
2. Type code in the first cell
3. Run the first cell.

![jupyter_error_1](https://user-images.githubusercontent.com/59132346/229819977-b8b89f80-b71f-4acf-ae46-9dbd6671e768.gif)

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

###Here is the log Output
<details>
  <summary>Show Logs</summary>
  
```
info 19:38:29.506: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd0940fca01b5b7d761b8a024f4cb9167d58a6b13380a41f119b3f90fb33b0fc9db.c:\Users\Kshitij Dwivedi\AppData\Local\Programs\Python\Python311\python.exe.c:\Users\Kshitij Dwivedi\AppData\Local\Programs\Python\Python311\python.exe.-m#ipykernel_launcher (Python Path: , EnvType: Unknown, EnvName: '', Version: 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]) for 'd:\Programming_and_Coding\College_Labs\8th_Sem\LAB 2 - MNB\test.ipynb' (disableUI=true)
warn 19:38:29.691: Failed to get activated env vars for c:\Users\Kshitij Dwivedi\AppData\Local\Programs\Python\Python311\python.exe in 179ms
info 19:38:29.699: Process Execution: > ~\AppData\Local\Programs\Python\Python311\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> ~\AppData\Local\Programs\Python\Python311\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
warn 19:38:29.701: Failed to get activated env vars for c:\Users\Kshitij Dwivedi\AppData\Local\Programs\Python\Python311\python.exe in 193ms
info 19:38:29.713: Process Execution: > ~\AppData\Local\Programs\Python\Python311\python.exe -m pip list
> ~\AppData\Local\Programs\Python\Python311\python.exe -m pip list
warn 19:38:29.774: Failed to get activated env vars for c:\Users\Kshitij Dwivedi\AppData\Local\Programs\Python\Python311\python.exe in 86ms
warn 19:38:29.778: Failed to get activated env vars for c:\Users\Kshitij Dwivedi\AppData\Local\Programs\Python\Python311\python.exe in 90ms
info 19:38:29.789: Process Execution: > ~\AppData\Local\Programs\Python\Python311\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9045 --control=9043 --hb=9042 --Session.signature_scheme="hmac-sha256" --Session.key=b"1f6878e0-7dbd-4ec1-bc18-d9bc7122171a" --shell=9044 --transport="tcp" --iopub=9046 --f="c:\Users\Kshitij Dwivedi\AppData\Roaming\jupyter\runtime\kernel-v2-15788z1U23ocWAYDV.json"
> ~\AppData\Local\Programs\Python\Python311\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9045 --control=9043 --hb=9042 --Session.signature_scheme="hmac-sha256" --Session.key=b"1f6878e0-7dbd-4ec1-bc18-d9bc7122171a" --shell=9044 --transport="tcp" --iopub=9046 --f="c:\Users\Kshitij Dwivedi\AppData\Roaming\jupyter\runtime\kernel-v2-15788z1U23ocWAYDV.json"
info 19:38:29.789: Process Execution: cwd: d:\Programming_and_Coding\College_Labs\8th_Sem\LAB 2 - MNB
cwd: d:\Programming_and_Coding\College_Labs\8th_Sem\LAB 2 - MNB
info 19:38:30.395: ipykernel version & path 6.22.0, ~\AppData\Roaming\Python\Python311\site-packages\ipykernel\__init__.py for c:\Users\Kshitij Dwivedi\AppData\Local\Programs\Python\Python311\python.exe
error 19:39:29.799: waitUntilUsed timed out [Error: timeout
	at Timeout.<anonymous> (c:\Users\Kshitij Dwivedi\.vscode\extensions\ms-toolsai.jupyter-2023.3.1000892223\out\151.node.js:1:17183)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)]
error 19:39:29.800: Disposing kernel process due to an error [Jp [Error]: Unable to start Kernel 'Python 3.11.2' due to connection timeout. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
	at c:\Users\Kshitij Dwivedi\.vscode\extensions\ms-toolsai.jupyter-2023.3.1000892223\out\extension.node.js:17:59931
	at async th.launch (c:\Users\Kshitij Dwivedi\.vscode\extensions\ms-toolsai.jupyter-2023.3.1000892223\out\extension.node.js:17:59973)] {
  category: 'timeout',
  kernelConnectionMetadata: da {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: 'c:\\Users\\Kshitij Dwivedi\\.vscode\\extensions\\ms-toolsai.jupyter-2023.3.1000892223\\temp\\jupyter\\kernels\\pythonjvsc74a57bd0940fca01b5b7d761b8a024f4cb9167d58a6b13380a41f119b3f90fb33b0fc9db\\kernel.json',
      interpreterPath: 'c:\\Users\\Kshitij Dwivedi\\AppData\\Local\\Programs\\Python\\Python311\\python.exe',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'pythonjvsc74a57bd0940fca01b5b7d761b8a024f4cb9167d58a6b13380a41f119b3f90fb33b0fc9db',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: 'Python 3',
      metadata: [Object],
      env: {}
    },
    interpreter: {
      id: 'C:\\USERS\\KSHITIJ DWIVEDI\\APPDATA\\LOCAL\\PROGRAMS\\PYTHON\\PYTHON311\\PYTHON.EXE',
      sysPrefix: 'C:\\Users\\Kshitij Dwivedi\\AppData\\Local\\Programs\\Python\\Python311',
      displayPath: [E],
      envName: '',
      displayName: '',
      envType: 'Unknown',
      isCondaEnvWithoutPython: false,
      version: [Object],
      uri: [E]
    },
    id: '.jvsc74a57bd0940fca01b5b7d761b8a024f4cb9167d58a6b13380a41f119b3f90fb33b0fc9db.c:\\Users\\Kshitij Dwivedi\\AppData\\Local\\Programs\\Python\\Python311\\python.exe.c:\\Users\\Kshitij Dwivedi\\AppData\\Local\\Programs\\Python\\Python311\\python.exe.-m#ipykernel_launcher'
  }
}
error 19:39:29.801: 
info 19:39:29.801: Dispose Kernel process 4804.
error 19:39:29.909: Kernel Launcher. launch, Class name = ah, completed in 60396ms, has a falsy return value, Arg 1: {"id":".jvsc74a57bd0940fca01b5b7d761b8a024f4cb9167d58a6b13380a41f119b3f90fb33b0fc9db.c:\\Users\\Kshitij Dwivedi\\AppData\\Local\\Programs\\Python\\Python311\\python.exe.c:\\Users\\Kshitij Dwivedi\\AppData\\Local\\Programs\\Python\\Python311\\python.exe.-m#ipykernel_launcher","kernelSpec":{"specFile":"c:\\Users\\Kshitij Dwivedi\\.vscode\\extensions\\ms-toolsai.jupyter-2023.3.1000892223\\temp\\jupyter\\kernels\\pythonjvsc74a57bd0940fca01b5b7d761b8a024f4cb9167d58a6b13380a41f119b3f90fb33b0fc9db\\kernel.json","interpreterPath":"c:\\Users\\Kshitij Dwivedi\\AppData\\Local\\Programs\\Python\\Python311\\python.exe","isRegisteredByVSC":"registeredByNewVersionOfExt","name":"pythonjvsc74a57bd0940fca01b5b7d761b8a024f4cb9167d58a6b13380a41f119b3f90fb33b0fc9db","argv":["python","-m","ipykernel_launcher","-f","{connection_file}"],"language":"python","executable":"python","display_name":"Python 3","metadata":{"interpreter":{"path":"c:\\Users\\Kshitij Dwivedi\\AppData\\Local\\Programs\\Python\\Python311\\python.exe"}},"env":{}},"interpreter":{"id":"C:\\USERS\\KSHITIJ DWIVEDI\\APPDATA\\LOCAL\\PROGRAMS\\PYTHON\\PYTHON311\\PYTHON.EXE","sysPrefix":"C:\\Users\\Kshitij Dwivedi\\AppData\\Local\\Programs\\Python\\Python311","displayPath":"c:\\Users\\Kshitij Dwivedi\\AppData\\Local\\Programs\\Python\\Python311\\python.exe","envName":"","displayName":"","envType":"Unknown","isCondaEnvWithoutPython":false,"version":{"major":3,"minor":11,"patch":2,"raw":"3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]"},"path":"c:\\Users\\Kshitij Dwivedi\\AppData\\Local\\Programs\\Python\\Python311\\python.exe"},"kind":"startUsingPythonInterpreter"}, Arg 2: 60000, Arg 3: "/d:/Programming_and_Coding/College_Labs/8th_Sem/LAB 2 - MNB/test.ipynb", Arg 4: "d:\\Programming_and_Coding\\College_Labs\\8th_Sem\\LAB 2 - MNB", Arg 5: <argument cannot be serialized for logging> [Jp [Error]: Unable to start Kernel 'Python 3.11.2' due to connection timeout. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
	at c:\Users\Kshitij Dwivedi\.vscode\extensions\ms-toolsai.jupyter-2023.3.1000892223\out\extension.node.js:17:59931
	at async th.launch (c:\Users\Kshitij Dwivedi\.vscode\extensions\ms-toolsai.jupyter-2023.3.1000892223\out\extension.node.js:17:59973)] {
  category: 'timeout',
  kernelConnectionMetadata: da {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: 'c:\\Users\\Kshitij Dwivedi\\.vscode\\extensions\\ms-toolsai.jupyter-2023.3.1000892223\\temp\\jupyter\\kernels\\pythonjvsc74a57bd0940fca01b5b7d761b8a024f4cb9167d58a6b13380a41f119b3f90fb33b0fc9db\\kernel.json',
      interpreterPath: 'c:\\Users\\Kshitij Dwivedi\\AppData\\Local\\Programs\\Python\\Python311\\python.exe',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'pythonjvsc74a57bd0940fca01b5b7d761b8a024f4cb9167d58a6b13380a41f119b3f90fb33b0fc9db',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: 'Python 3',
      metadata: [Object],
      env: {}
    },
    interpreter: {
      id: 'C:\\USERS\\KSHITIJ DWIVEDI\\APPDATA\\LOCAL\\PROGRAMS\\PYTHON\\PYTHON311\\PYTHON.EXE',
      sysPrefix: 'C:\\Users\\Kshitij Dwivedi\\AppData\\Local\\Programs\\Python\\Python311',
      displayPath: [E],
      envName: '',
      displayName: '',
      envType: 'Unknown',
      isCondaEnvWithoutPython: false,
      version: [Object],
      uri: [E]
    },
    id: '.jvsc74a57bd0940fca01b5b7d761b8a024f4cb9167d58a6b13380a41f119b3f90fb33b0fc9db.c:\\Users\\Kshitij Dwivedi\\AppData\\Local\\Programs\\Python\\Python311\\python.exe.c:\\Users\\Kshitij Dwivedi\\AppData\\Local\\Programs\\Python\\Python311\\python.exe.-m#ipykernel_launcher'
  }
}
error 19:39:29.909: Failed to connect raw kernel session: Error: Unable to start Kernel 'Python 3.11.2' due to connection timeout. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
warn 19:39:29.909: Error occurred while trying to start the kernel, options.disableUI=false [Jp [Error]: Unable to start Kernel 'Python 3.11.2' due to connection timeout. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
	at c:\Users\Kshitij Dwivedi\.vscode\extensions\ms-toolsai.jupyter-2023.3.1000892223\out\extension.node.js:17:59931
	at async th.launch (c:\Users\Kshitij Dwivedi\.vscode\extensions\ms-toolsai.jupyter-2023.3.1000892223\out\extension.node.js:17:59973)] {
  category: 'timeout',
  kernelConnectionMetadata: da {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: 'c:\\Users\\Kshitij Dwivedi\\.vscode\\extensions\\ms-toolsai.jupyter-2023.3.1000892223\\temp\\jupyter\\kernels\\pythonjvsc74a57bd0940fca01b5b7d761b8a024f4cb9167d58a6b13380a41f119b3f90fb33b0fc9db\\kernel.json',
      interpreterPath: 'c:\\Users\\Kshitij Dwivedi\\AppData\\Local\\Programs\\Python\\Python311\\python.exe',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'pythonjvsc74a57bd0940fca01b5b7d761b8a024f4cb9167d58a6b13380a41f119b3f90fb33b0fc9db',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: 'Python 3',
      metadata: [Object],
      env: {}
    },
    interpreter: {
      id: 'C:\\USERS\\KSHITIJ DWIVEDI\\APPDATA\\LOCAL\\PROGRAMS\\PYTHON\\PYTHON311\\PYTHON.EXE',
      sysPrefix: 'C:\\Users\\Kshitij Dwivedi\\AppData\\Local\\Programs\\Python\\Python311',
      displayPath: [E],
      envName: '',
      displayName: '',
      envType: 'Unknown',
      isCondaEnvWithoutPython: false,
      version: [Object],
      uri: [E]
    },
    id: '.jvsc74a57bd0940fca01b5b7d761b8a024f4cb9167d58a6b13380a41f119b3f90fb33b0fc9db.c:\\Users\\Kshitij Dwivedi\\AppData\\Local\\Programs\\Python\\Python311\\python.exe.c:\\Users\\Kshitij Dwivedi\\AppData\\Local\\Programs\\Python\\Python311\\python.exe.-m#ipykernel_launcher'
  }
}
warn 19:39:29.910: Kernel Error, context = start [Jp [Error]: Unable to start Kernel 'Python 3.11.2' due to connection timeout. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
	at c:\Users\Kshitij Dwivedi\.vscode\extensions\ms-toolsai.jupyter-2023.3.1000892223\out\extension.node.js:17:59931
	at async th.launch (c:\Users\Kshitij Dwivedi\.vscode\extensions\ms-toolsai.jupyter-2023.3.1000892223\out\extension.node.js:17:59973)] {
  category: 'timeout',
  kernelConnectionMetadata: da {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: 'c:\\Users\\Kshitij Dwivedi\\.vscode\\extensions\\ms-toolsai.jupyter-2023.3.1000892223\\temp\\jupyter\\kernels\\pythonjvsc74a57bd0940fca01b5b7d761b8a024f4cb9167d58a6b13380a41f119b3f90fb33b0fc9db\\kernel.json',
      interpreterPath: 'c:\\Users\\Kshitij Dwivedi\\AppData\\Local\\Programs\\Python\\Python311\\python.exe',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'pythonjvsc74a57bd0940fca01b5b7d761b8a024f4cb9167d58a6b13380a41f119b3f90fb33b0fc9db',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: 'Python 3',
      metadata: [Object],
      env: {}
    },
    interpreter: {
      id: 'C:\\USERS\\KSHITIJ DWIVEDI\\APPDATA\\LOCAL\\PROGRAMS\\PYTHON\\PYTHON311\\PYTHON.EXE',
      sysPrefix: 'C:\\Users\\Kshitij Dwivedi\\AppData\\Local\\Programs\\Python\\Python311',
      displayPath: [E],
      envName: '',
      displayName: '',
      envType: 'Unknown',
      isCondaEnvWithoutPython: false,
      version: [Object],
      uri: [E]
    },
    id: '.jvsc74a57bd0940fca01b5b7d761b8a024f4cb9167d58a6b13380a41f119b3f90fb33b0fc9db.c:\\Users\\Kshitij Dwivedi\\AppData\\Local\\Programs\\Python\\Python311\\python.exe.c:\\Users\\Kshitij Dwivedi\\AppData\\Local\\Programs\\Python\\Python311\\python.exe.-m#ipykernel_launcher'
  }
}
warn 19:39:29.934: Failed to get activated env vars for c:\Users\Kshitij Dwivedi\AppData\Local\Programs\Python\Python311\python.exe in 22ms
info 19:39:29.944: Process Execution: > ~\AppData\Local\Programs\Python\Python311\python.exe -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> ~\AppData\Local\Programs\Python\Python311\python.exe -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 19:39:30.451: Dispose Kernel 'd:\Programming_and_Coding\College_Labs\8th_Sem\LAB 2 - MNB\test.ipynb' associated with 'd:\Programming_and_Coding\College_Labs\8th_Sem\LAB 2 - MNB\test.ipynb'
error 19:39:30.454: Error in execution [Jp [Error]: Unable to start Kernel 'Python 3.11.2' due to connection timeout. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
	at c:\Users\Kshitij Dwivedi\.vscode\extensions\ms-toolsai.jupyter-2023.3.1000892223\out\extension.node.js:17:59931
	at async th.launch (c:\Users\Kshitij Dwivedi\.vscode\extensions\ms-toolsai.jupyter-2023.3.1000892223\out\extension.node.js:17:59973)] {
  category: 'timeout',
  kernelConnectionMetadata: da {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: 'c:\\Users\\Kshitij Dwivedi\\.vscode\\extensions\\ms-toolsai.jupyter-2023.3.1000892223\\temp\\jupyter\\kernels\\pythonjvsc74a57bd0940fca01b5b7d761b8a024f4cb9167d58a6b13380a41f119b3f90fb33b0fc9db\\kernel.json',
      interpreterPath: 'c:\\Users\\Kshitij Dwivedi\\AppData\\Local\\Programs\\Python\\Python311\\python.exe',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'pythonjvsc74a57bd0940fca01b5b7d761b8a024f4cb9167d58a6b13380a41f119b3f90fb33b0fc9db',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: 'Python 3',
      metadata: [Object],
      env: {}
    },
    interpreter: {
      id: 'C:\\USERS\\KSHITIJ DWIVEDI\\APPDATA\\LOCAL\\PROGRAMS\\PYTHON\\PYTHON311\\PYTHON.EXE',
      sysPrefix: 'C:\\Users\\Kshitij Dwivedi\\AppData\\Local\\Programs\\Python\\Python311',
      displayPath: [E],
      envName: '',
      displayName: '',
      envType: 'Unknown',
      isCondaEnvWithoutPython: false,
      version: [Object],
      uri: [E]
    },
    id: '.jvsc74a57bd0940fca01b5b7d761b8a024f4cb9167d58a6b13380a41f119b3f90fb33b0fc9db.c:\\Users\\Kshitij Dwivedi\\AppData\\Local\\Programs\\Python\\Python311\\python.exe.c:\\Users\\Kshitij Dwivedi\\AppData\\Local\\Programs\\Python\\Python311\\python.exe.-m#ipykernel_launcher'
  }
}
error 19:39:30.455: Error in execution (get message for cell) [Jp [Error]: Unable to start Kernel 'Python 3.11.2' due to connection timeout. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
	at c:\Users\Kshitij Dwivedi\.vscode\extensions\ms-toolsai.jupyter-2023.3.1000892223\out\extension.node.js:17:59931
	at async th.launch (c:\Users\Kshitij Dwivedi\.vscode\extensions\ms-toolsai.jupyter-2023.3.1000892223\out\extension.node.js:17:59973)] {
  category: 'timeout',
  kernelConnectionMetadata: da {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: 'c:\\Users\\Kshitij Dwivedi\\.vscode\\extensions\\ms-toolsai.jupyter-2023.3.1000892223\\temp\\jupyter\\kernels\\pythonjvsc74a57bd0940fca01b5b7d761b8a024f4cb9167d58a6b13380a41f119b3f90fb33b0fc9db\\kernel.json',
      interpreterPath: 'c:\\Users\\Kshitij Dwivedi\\AppData\\Local\\Programs\\Python\\Python311\\python.exe',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'pythonjvsc74a57bd0940fca01b5b7d761b8a024f4cb9167d58a6b13380a41f119b3f90fb33b0fc9db',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: 'Python 3',
      metadata: [Object],
      env: {}
    },
    interpreter: {
      id: 'C:\\USERS\\KSHITIJ DWIVEDI\\APPDATA\\LOCAL\\PROGRAMS\\PYTHON\\PYTHON311\\PYTHON.EXE',
      sysPrefix: 'C:\\Users\\Kshitij Dwivedi\\AppData\\Local\\Programs\\Python\\Python311',
      displayPath: [E],
      envName: '',
      displayName: '',
      envType: 'Unknown',
      isCondaEnvWithoutPython: false,
      version: [Object],
      uri: [E]
    },
    id: '.jvsc74a57bd0940fca01b5b7d761b8a024f4cb9167d58a6b13380a41f119b3f90fb33b0fc9db.c:\\Users\\Kshitij Dwivedi\\AppData\\Local\\Programs\\Python\\Python311\\python.exe.c:\\Users\\Kshitij Dwivedi\\AppData\\Local\\Programs\\Python\\Python311\\python.exe.-m#ipykernel_launcher'
  }
}

```
</details>

## From the above log the common error I found was : 
warn 19:38:29.701: Failed to get activated env vars for c:\Users\Kshitij Dwivedi\AppData\Local\Programs\Python\Python311\python.exe in 193ms

with all the 3 python versions I have. 3.11.2 / 3.10.2 / 3.9.6

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment]
Thanks for filing this issue  and sorry you are running into this.

It looks like you might have some anti-virus software or the like that is blocking some ports or the like and preventing the kernel from connecting over the sockets.
I suspect this would fail even with the older version of the Jupyter exetnsion and VS Code as well, i.e. something seems to have changed on your machine that seems to prevent kernels from starting.


Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by kshitijdwivedi28** [comment]
Hi! @DonJayamanne 
It's great to see a prompt reply form you.

And thanks a lot, changing the Jupyter->Logging value from `debug` to `verbose` fixed the issue. 

Also, I wondered how you figured it out? Well I guess no less the answer is Knowledge and Experience. 
However, I'm also willing to contribute to the community and also learn how things work beyond the eyesight of a novice programmer. 
It'd be nice if you can give a head start in this :)
