### ISSUE TITLE
Markdown cell not rendering in python interactive window if no internet connection

### ISSUE THREAD

**Issue by rlevitin** [microsoft/vscode-jupyter#1331]
## Environment data

VS Code Version: 1.37.0-insider
Extension Version: 2019.6.242221
OS - Windows 10 17763.615. Using remote development 0.15.0 to run code on a linux box
Python 3.6.8 64-bit with anaconda (conda env)

## Expected behaviour
When I run a markdown code block, it should display the text as markdown in the python interactive viewer.

## Actual behaviour
A blank cell loads with no output. Regular python code blocks run as expected. Markdown just comes up blank.

## Steps to reproduce:
1. Create a new file "test.py"
2. Code block 
```
#%% [markdown]
# Test Print
# This should print out
# ## This should print as a heading

#%%
print("Test")

```

## Logs
Output for `Python` in the `Output` panel:

```
Starting Microsoft Python language server.
Starting Jedi Python language engine.
```

Output from `Console`:

```
workbench.main.js:242 [Extension Host] Info Python Extension: 2019-08-05 11:31:02: Submitting code for 364114ed-361f-4257-8d33-a094d695fea0
workbench.main.js:242 [Extension Host] Info Python Extension: 2019-08-05 11:31:02: Waiting for jupyter server and web panel ...
2
workbench.main.js:242 [Extension Host] Info Python Extension: 2019-08-05 11:31:02: Wait for sys info for 364114ed-361f-4257-8d33-a094d695fea0 0
workbench.main.js:242 [Extension Host] Info Python Extension: 2019-08-05 11:31:02: Finished execution for 62bff78a-274a-4fd2-b722-08b5935188d9
workbench.main.js:242 [Extension Host] rejected promise not handled within 1 second: TypeError: Cannot read property 'version' of undefined
workbench.main.js:242 [Extension Host] stack trace: TypeError: Cannot read property 'version' of undefined
	at f.getLanguageServerFolderName (/home/rlevitin/.vscode-server-insiders/extensions/ms-python.python-2019.6.24221/out/client/extension.js:75:111924)
	at process._tickCallback (internal/process/next_tick.js:68:7)
workbench.main.js:3414 [[object Object]]Cannot read property 'version' of undefined
workbench.main.js:3414 TypeError: Cannot read property 'version' of undefined
	at f.getLanguageServerFolderName (/home/rlevitin/.vsco…ent/extension.js:75)
	at process._tickCallback (internal/process/next_tick.js:68)
workbench.main.js:3038 [Embedded Page] Uncaught ReferenceError: MathJax is not defined
workbench.main.js:242 [Extension Host] rejected promise not handled within 1 second: TypeError: Cannot read property 'version' of undefined
workbench.main.js:242 [Extension Host] stack trace: TypeError: Cannot read property 'version' of undefined
	at f.getLanguageServerFolderName (/home/rlevitin/.vscode-server-insiders/extensions/ms-python.python-2019.6.24221/out/client/extension.js:75:111924)
	at process._tickCallback (internal/process/next_tick.js:68:7)
workbench.main.js:3414 [[object Object]]Cannot read property 'version' of undefined
workbench.main.js:3414 TypeError: Cannot read property 'version' of undefined
	at f.getLanguageServerFolderName (/home/rlevitin/.vsco…ent/extension.js:75)
	at process._tickCallback (internal/process/next_tick.js:68)
workbench.main.js:242 [Extension Host] ApplicationInsights:Sender 
Array(2)
DevTools failed to parse SourceMap: https://ticino.blob.core.windows.net/sourcemaps/92da68a…/core/vs/workbench/workbench.main.js.map
```

![image](https://user-images.githubusercontent.com/1235172/62475938-10f39900-b774-11e9-9cfc-22ea052785c0.png)

I have looked at Issue microsoft/vscode-python#3108. The output looks to be a similar problem but my machine is not offline... not sure why this is happening. It was working fine last week.

**Comment by joyceerhl** [comment]
Closing as VS Code ships KaTeX for markdown math rendering and doesn't rely on downloading MathJax. The new native interactive window relies on VS Code for markdown rendering. Please file a bug at https://github.com/microsoft/vscode if something isn't working.
