### ISSUE TITLE
404 Not found when trying to connect to jupyter server from VSCode

### ISSUE THREAD

**Issue by asmagr** [microsoft/vscode-jupyter#13332]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I created an access token from my jupyterhub control panel then created a jupyter notebook on vscode and when changing the kernel to the one I needed it gave me this error : connection failure. verify the server is running and reachable from a browser. (Invalid response : 404 Not found). When connected from vscode.dev jupyter servers must be started with specific options to connect. click here for more information. (it gives this link : https://github.com/microsoft/vscode-jupyter/wiki/Connecting-to-a-remote-Jupyter-server-from-vscode.dev)

I tired and the server is accessible so there's no problem from that side. And I also followed a tutorial on how to create the url from my server hub and token.
I don't know about the "options to connect" though. 

### VS Code Version

1.77.3

### Jupyter Extension Version

v2023.3.1201040234

### Jupyter logs

```shell
Visual Studio Code (1.77.3, undefined, desktop)
Jupyter Extension Version: 2023.3.1201040234.
Python Extension Version: 2023.6.0.
No workspace folder opened.
User belongs to experiment group 'jupyterEnhancedDataViewer'
User belongs to experiment group 'jupyterTestcf'
info 20:18:01.613: LSP Notebooks experiment is enabled
info 20:18:11.359: Process Execution: > ~/opt/anaconda3/bin/python -m pip list
> ~/opt/anaconda3/bin/python -m pip list
info 20:21:50.587: Creating server with url : https://ibisc.univ-evry.fr/user/agraiess/
warn 20:21:51.302: Uri verification error [t [Error]: Invalid response: 404 Not Found
	at t.create (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:68194)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async t.listRunning (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:55998)
	at async jg.getRunningKernels (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:237503)
	at async Promise.all (index 0)
	at async Ki.validateRemoteConnection (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:1706158)
	at async go (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:1712829)
	at async /Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:24:492157] {
  response: L [Response] {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [Gunzip], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://www.ibisc.univ-evry.fr/user/agraiess/api/kernels?1681582910612',
      status: 404,
      statusText: 'Not Found',
      headers: [T [Headers]],
      counter: 1
    }
  },
  traceback: ''
}
error 20:21:51.312: SessionManager:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at e.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:171555)
	at u.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:62984)
	at jg.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:236617)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)]
info 20:28:37.868: Creating server with url : https://ibisc.univ-evry.fr/user/agraiess/
warn 20:28:38.565: Uri verification error [t [Error]: Invalid response: 404 Not Found
	at t.create (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:68194)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async t.listRunning (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:55998)
	at async jg.getRunningKernels (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:237503)
	at async Promise.all (index 0)
	at async Ki.validateRemoteConnection (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:1706158)
	at async go (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:1712829)
	at async /Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:24:492157] {
  response: L [Response] {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [Gunzip], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://www.ibisc.univ-evry.fr/user/agraiess/api/kernels?1681583317869',
      status: 404,
      statusText: 'Not Found',
      headers: [T [Headers]],
      counter: 1
    }
  },
  traceback: ''
}
error 20:28:38.585: SessionManager:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at e.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:171555)
	at u.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:62984)
	at jg.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:236617)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)]
info 20:33:54.056: Creating server with url : https://ibisc.univ-evry.fr/user/agraiess/
info 20:33:54.719: Creating server with url : https://ibisc.univ-evry.fr/user/agraiess/
warn 20:33:54.808: Uri verification error [t [Error]: Invalid response: 404 Not Found
	at t.create (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:68194)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async t.listRunning (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:55998)
	at async jg.getRunningKernels (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:237503)
	at async Promise.all (index 0)
	at async Ki.validateRemoteConnection (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:1706158)
	at async go (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:1712829)
	at async /Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:24:492157] {
  response: L [Response] {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [Gunzip], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://www.ibisc.univ-evry.fr/user/agraiess/api/kernels?1681583634062',
      status: 404,
      statusText: 'Not Found',
      headers: [T [Headers]],
      counter: 1
    }
  },
  traceback: ''
}
error 20:33:54.808: SessionManager:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at e.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:171555)
	at u.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:62984)
	at jg.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:236617)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)]
info 20:33:54.904: Creating server with url : https://ibisc.univ-evry.fr/user/agraiess/
warn 20:33:55.944: Uri verification error [t [Error]: Invalid response: 404 Not Found
	at t.create (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:68194)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async t.listRunning (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:55998)
	at async jg.getRunningKernels (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:237503)
	at async Promise.all (index 0)
	at async Ki.validateRemoteConnection (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:1706158)
	at async go (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:1712829)
	at async /Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:24:492157] {
  response: L [Response] {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [Gunzip], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://www.ibisc.univ-evry.fr/user/agraiess/api/kernels?1681583634720',
      status: 404,
      statusText: 'Not Found',
      headers: [T [Headers]],
      counter: 1
    }
  },
  traceback: ''
}
error 20:33:55.951: SessionManager:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at e.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:171555)
	at u.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:62984)
	at jg.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:236617)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)]
warn 20:33:56.328: Uri verification error [t [Error]: Invalid response: 404 Not Found
	at t.create (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:68194)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async t.listRunning (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:55998)
	at async jg.getRunningKernels (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:237503)
	at async Promise.all (index 0)
	at async Ki.validateRemoteConnection (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:1706158)
	at async go (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:1712829)
	at async /Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:24:492157] {
  response: L [Response] {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [Gunzip], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://www.ibisc.univ-evry.fr/user/agraiess/api/kernels?1681583634906',
      status: 404,
      statusText: 'Not Found',
      headers: [T [Headers]],
      counter: 1
    }
  },
  traceback: ''
}
error 20:33:56.328: SessionManager:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at e.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:171555)
	at u.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:62984)
	at jg.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:236617)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)]
info 20:33:56.424: Creating server with url : https://ibisc.univ-evry.fr/user/agraiess/
info 20:33:56.583: Creating server with url : https://ibisc.univ-evry.fr/user/agraiess/
info 20:33:56.727: Creating server with url : https://ibisc.univ-evry.fr/user/agraiess/
info 20:33:56.879: Creating server with url : https://ibisc.univ-evry.fr/user/agraiess/
info 20:33:57.036: Creating server with url : https://ibisc.univ-evry.fr/user/agraiess/
info 20:33:57.191: Creating server with url : https://ibisc.univ-evry.fr/user/agraiess/
info 20:33:57.326: Creating server with url : https://ibisc.univ-evry.fr/user/agraiess/
warn 20:33:57.812: Uri verification error [t [Error]: Invalid response: 404 Not Found
	at t.create (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:68194)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async t.listRunning (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:55998)
	at async jg.getRunningKernels (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:237503)
	at async Promise.all (index 0)
	at async Ki.validateRemoteConnection (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:1706158)
	at async go (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:1712829)
	at async /Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:24:492157] {
  response: L [Response] {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [Gunzip], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://www.ibisc.univ-evry.fr/user/agraiess/api/kernels?1681583636426',
      status: 404,
      statusText: 'Not Found',
      headers: [T [Headers]],
      counter: 1
    }
  },
  traceback: ''
}
error 20:33:58.458: SessionManager:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at e.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:171555)
	at u.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:62984)
	at jg.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:236617)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)]
warn 20:33:58.766: Uri verification error [t [Error]: Invalid response: 404 Not Found
	at t.create (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:68194)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async t.listRunning (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:55998)
	at async jg.getRunningKernels (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:237503)
	at async Promise.all (index 0)
	at async Ki.validateRemoteConnection (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:1706158)
	at async go (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:1712829)
	at async /Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:24:492157] {
  response: L [Response] {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [Gunzip], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://www.ibisc.univ-evry.fr/user/agraiess/api/kernels?1681583636584',
      status: 404,
      statusText: 'Not Found',
      headers: [T [Headers]],
      counter: 1
    }
  },
  traceback: ''
}
error 20:33:59.219: SessionManager:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at e.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:171555)
	at u.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:62984)
	at jg.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:236617)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)]
warn 20:33:59.397: Uri verification error [t [Error]: Invalid response: 404 Not Found
	at t.create (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:68194)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async t.listRunning (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:55998)
	at async jg.getRunningKernels (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:237503)
	at async Promise.all (index 0)
	at async Ki.validateRemoteConnection (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:1706158)
	at async go (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:1712829)
	at async /Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:24:492157] {
  response: L [Response] {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [Gunzip], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://www.ibisc.univ-evry.fr/user/agraiess/api/kernels?1681583636729',
      status: 404,
      statusText: 'Not Found',
      headers: [T [Headers]],
      counter: 1
    }
  },
  traceback: ''
}
error 20:34:00.297: SessionManager:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at e.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:171555)
	at u.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:62984)
	at jg.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:236617)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)]
warn 20:34:00.297: Uri verification error [t [Error]: Invalid response: 404 Not Found
	at t.create (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:68194)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async t.listRunning (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:55998)
	at async jg.getRunningKernels (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:237503)
	at async Promise.all (index 0)
	at async Ki.validateRemoteConnection (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:1706158)
	at async go (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:1712829)
	at async /Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:24:492157] {
  response: L [Response] {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [Gunzip], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://www.ibisc.univ-evry.fr/user/agraiess/api/kernels?1681583636880',
      status: 404,
      statusText: 'Not Found',
      headers: [T [Headers]],
      counter: 1
    }
  },
  traceback: ''
}
warn 20:34:00.299: Uri verification error [t [Error]: Invalid response: 404 Not Found
	at t.create (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:68194)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async t.listRunning (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:55998)
	at async jg.getRunningKernels (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:237503)
	at async Promise.all (index 0)
	at async Ki.validateRemoteConnection (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:1706158)
	at async go (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:1712829)
	at async /Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:24:492157] {
  response: L [Response] {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [Gunzip], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://www.ibisc.univ-evry.fr/user/agraiess/api/kernels?1681583637037',
      status: 404,
      statusText: 'Not Found',
      headers: [T [Headers]],
      counter: 1
    }
  },
  traceback: ''
}
error 20:34:00.301: SessionManager:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at e.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:171555)
	at u.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:62984)
	at jg.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:236617)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)]
error 20:34:01.006: SessionManager:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at e.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:171555)
	at u.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:62984)
	at jg.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:236617)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)]
warn 20:34:01.122: Uri verification error [t [Error]: Invalid response: 404 Not Found
	at t.create (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:68194)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async t.listRunning (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:55998)
	at async jg.getRunningKernels (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:237503)
	at async Promise.all (index 0)
	at async Ki.validateRemoteConnection (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:1706158)
	at async go (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:1712829)
	at async /Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:24:492157] {
  response: L [Response] {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [Gunzip], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://www.ibisc.univ-evry.fr/user/agraiess/api/kernels?1681583637193',
      status: 404,
      statusText: 'Not Found',
      headers: [T [Headers]],
      counter: 1
    }
  },
  traceback: ''
}
error 20:34:01.122: SessionManager:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at e.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:171555)
	at u.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:62984)
	at jg.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:236617)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)]
warn 20:34:01.252: Uri verification error [t [Error]: Invalid response: 404 Not Found
	at t.create (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:68194)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async t.listRunning (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:55998)
	at async jg.getRunningKernels (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:237503)
	at async Promise.all (index 0)
	at async Ki.validateRemoteConnection (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:1706158)
	at async go (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:1712829)
	at async /Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:24:492157] {
  response: L [Response] {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [Gunzip], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://www.ibisc.univ-evry.fr/user/agraiess/api/kernels?1681583637327',
      status: 404,
      statusText: 'Not Found',
      headers: [T [Headers]],
      counter: 1
    }
  },
  traceback: ''
}
error 20:34:01.253: SessionManager:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at e.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:171555)
	at u.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:62984)
	at jg.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:236617)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)]
info 20:34:06.798: Creating server with url : https://ibisc.univ-evry.fr/user/agraiess/
warn 20:34:07.455: Uri verification error [t [Error]: Invalid response: 404 Not Found
	at t.create (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:68194)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async t.listRunning (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:55998)
	at async jg.getRunningKernels (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:237503)
	at async Promise.all (index 0)
	at async Ki.validateRemoteConnection (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:1706158)
	at async go (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:1712829)
	at async /Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:24:492157] {
  response: L [Response] {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [Gunzip], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://www.ibisc.univ-evry.fr/user/agraiess/api/kernels?1681583646800',
      status: 404,
      statusText: 'Not Found',
      headers: [T [Headers]],
      counter: 1
    }
  },
  traceback: ''
}
error 20:34:07.482: SessionManager:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at e.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:171555)
	at u.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:62984)
	at jg.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:236617)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)]
info 20:42:48.396: Creating server with url : https://ibisc.univ-evry.fr/user/agraiess/
warn 20:42:49.067: Uri verification error [t [Error]: Invalid response: 404 Not Found
	at t.create (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:68194)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async t.listRunning (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:55998)
	at async jg.getRunningKernels (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:237503)
	at async Promise.all (index 0)
	at async Ki.validateRemoteConnection (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:1706158)
	at async go (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:1712829)
	at async /Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:24:492157] {
  response: L [Response] {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [Gunzip], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://www.ibisc.univ-evry.fr/user/agraiess/api/kernels?1681584168399',
      status: 404,
      statusText: 'Not Found',
      headers: [T [Headers]],
      counter: 1
    }
  },
  traceback: ''
}
error 20:42:49.078: SessionManager:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at e.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:171555)
	at u.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:2:62984)
	at jg.dispose (/Users/asma/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:236617)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)]
```

### Language Extension Version (if applicable)

v2023.6.0

### Running Jupyter locally or remotely?

None

**Comment by DonJayamanne** [comment]
> verify the server is running and reachable from a browser. (Invalid response : 404 Not found)

Since you're getting a 404 error this is an indication of the fact that the server cannot be reached.
I've tried the URL `https://www.ibisc.univ-evry.fr/user/agraiess` and that does return a 404, please could you verify this works in the browser for you.

> I tired and the server is accessible so there's no problem from that side. And I also followed a tutorial on how to create the url from my server hub and token.

Have you tried `https://www.ibisc.univ-evry.fr/user/agraiess` or some other URL?

Can you open a window in inconito (private) mode and try to navigate to the address `https://www.ibisc.univ-evry.fr/user/agraiess` and let me know how that works. I'm assuming this will not work for you.

**Comment by asmagr** [comment]
Thank you for replying and sorry for the inconvenience it was a dumb mistake when copying the URL.
