### ISSUE TITLE
Cell runs continuously whenever the variable explorer is opened

### ISSUE THREAD

**Issue by chuyaowang** [microsoft/vscode-jupyter#13406]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I have found that whenever I use the JUPYTER:VARIABLES tab to view the variables, the cells will soon start to run indefinitely. Restarting the kernel does not solve the issue. I had to quit and re-open vscode for the cells to run again.

### VS Code Version

1.71.0

### Jupyter Extension Version

v2022.8.1002431955

### Jupyter logs

```shell
info 18:5:55.593: Executing silently Code (completed) = def _VSCODE_getVariable(what_to_get, is_debugging, *args):\n# Query Jupyter server for the info with 1 output(s)
[E 18:05:55.654 NotebookApp] Uncaught exception in ZMQStream callback
    Traceback (most recent call last):
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 556, in _run_callback
        callback(*args, **kwargs)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 278, in stream_callback
        return callback(self, msg)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/notebook/services/kernels/handlers.py", line 547, in _on_zmq_reply
        super()._on_zmq_reply(stream, msg)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/notebook/base/zmqhandlers.py", line 251, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/websocket.py", line 339, in write_message
        return self.ws_connection.write_message(message, binary=binary)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/websocket.py", line 1086, in write_message
        fut = self._write_frame(True, opcode, message, flags=flags)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/websocket.py", line 1061, in _write_frame
        return self.stream.write(frame)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/iostream.py", line 546, in write
        self._handle_write()
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/iostream.py", line 976, in _handle_write
        self._write_buffer.advance(num_bytes)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/iostream.py", line 182, in advance
        assert 0 < size <= self._size
    AssertionError
[I 18:05:55.655 NotebookApp] Starting buffering for 98fc732b-7b5b-498d-ac7d-5ea2b73fe83d:d3c72ae6-7573-41c2-8501-c7e7d376ca4c
[E 18:05:55.659 NotebookApp] Uncaught exception in zmqstream callback
    Traceback (most recent call last):
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 577, in _handle_events
        self._handle_recv()
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 606, in _handle_recv
        self._run_callback(callback, msg)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 556, in _run_callback
        callback(*args, **kwargs)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 278, in stream_callback
        return callback(self, msg)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/notebook/services/kernels/handlers.py", line 547, in _on_zmq_reply
        super()._on_zmq_reply(stream, msg)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/notebook/base/zmqhandlers.py", line 251, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/websocket.py", line 339, in write_message
        return self.ws_connection.write_message(message, binary=binary)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/websocket.py", line 1086, in write_message
        fut = self._write_frame(True, opcode, message, flags=flags)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/websocket.py", line 1061, in _write_frame
        return self.stream.write(frame)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/iostream.py", line 546, in write
        self._handle_write()
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/iostream.py", line 976, in _handle_write
        self._write_buffer.advance(num_bytes)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/iostream.py", line 182, in advance
        assert 0 < size <= self._size
    AssertionError
[E 18:05:55.661 NotebookApp] Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x105207310>)
    Traceback (most recent call last):
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/ioloop.py", line 740, in _run_callback
        ret = callback()
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 661, in <lambda>
        self.io_loop.add_callback(lambda: self._handle_events(self.socket, 0))
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 577, in _handle_events
        self._handle_recv()
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 606, in _handle_recv
        self._run_callback(callback, msg)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 556, in _run_callback
        callback(*args, **kwargs)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 278, in stream_callback
        return callback(self, msg)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/notebook/services/kernels/handlers.py", line 547, in _on_zmq_reply
        super()._on_zmq_reply(stream, msg)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/notebook/base/zmqhandlers.py", line 251, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/websocket.py", line 339, in write_message
        return self.ws_connection.write_message(message, binary=binary)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/websocket.py", line 1086, in write_message
        fut = self._write_frame(True, opcode, message, flags=flags)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/websocket.py", line 1061, in _write_frame
        return self.stream.write(frame)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/iostream.py", line 546, in write
        self._handle_write()
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/iostream.py", line 976, in _handle_write
        self._write_buffer.advance(num_bytes)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/iostream.py", line 182, in advance
        assert 0 < size <= self._size
    AssertionError
[I 18:05:55.662 NotebookApp] Restoring connection for 98fc732b-7b5b-498d-ac7d-5ea2b73fe83d:d3c72ae6-7573-41c2-8501-c7e7d376ca4c
[I 18:05:55.664 NotebookApp] Replaying 1 buffered messages
[E 18:05:55.666 NotebookApp] Uncaught exception in ZMQStream callback
    Traceback (most recent call last):
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 556, in _run_callback
        callback(*args, **kwargs)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 278, in stream_callback
        return callback(self, msg)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/notebook/services/kernels/handlers.py", line 547, in _on_zmq_reply
        super()._on_zmq_reply(stream, msg)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/notebook/base/zmqhandlers.py", line 251, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/websocket.py", line 339, in write_message
        return self.ws_connection.write_message(message, binary=binary)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/websocket.py", line 1086, in write_message
        fut = self._write_frame(True, opcode, message, flags=flags)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/websocket.py", line 1061, in _write_frame
        return self.stream.write(frame)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/iostream.py", line 546, in write
        self._handle_write()
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/iostream.py", line 976, in _handle_write
        self._write_buffer.advance(num_bytes)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/iostream.py", line 182, in advance
        assert 0 < size <= self._size
    AssertionError
[E 18:05:55.667 NotebookApp] Uncaught exception in zmqstream callback
    Traceback (most recent call last):
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 577, in _handle_events
        self._handle_recv()
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 606, in _handle_recv
        self._run_callback(callback, msg)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 556, in _run_callback
        callback(*args, **kwargs)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 278, in stream_callback
        return callback(self, msg)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/notebook/services/kernels/handlers.py", line 547, in _on_zmq_reply
        super()._on_zmq_reply(stream, msg)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/notebook/base/zmqhandlers.py", line 251, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/websocket.py", line 339, in write_message
        return self.ws_connection.write_message(message, binary=binary)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/websocket.py", line 1086, in write_message
        fut = self._write_frame(True, opcode, message, flags=flags)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/websocket.py", line 1061, in _write_frame
        return self.stream.write(frame)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/iostream.py", line 546, in write
        self._handle_write()
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/iostream.py", line 976, in _handle_write
        self._write_buffer.advance(num_bytes)
      File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/iostream.py", line 182, in advance
        assert 0 < size <= self._size
    AssertionError
error 18:5:55.668: Python Daemon (pid: 99155): Exception in callback BaseAsyncIOLoop._handle_events(38, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(38, 1)>
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 206, in _handle_events
    handler_func(fileobj, events)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 577, in _handle_events
    self._handle_recv()
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 606, in _handle_recv
    self._run_callback(callback, msg)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 556, in _run_callback
    callback(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 278, in stream_callback
    return callback(self, msg)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/notebook/services/kernels/handlers.py", line 547, in _on_zmq_reply
    super()._on_zmq_reply(stream, msg)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/notebook/base/zmqhandlers.py", line 251, in _on_zmq_reply
    self.write_message(msg, binary=isinstance(msg, bytes))
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/websocket.py", line 339, in write_message
    return self.ws_connection.write_message(message, binary=binary)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/websocket.py", line 1086, in write_message
    fut = self._write_frame(True, opcode, message, flags=flags)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/websocket.py", line 1061, in _write_frame
    return self.stream.write(frame)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/iostream.py", line 546, in write
    self._handle_write()
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/iostream.py", line 976, in _handle_write
    self._write_buffer.advance(num_bytes)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/tornado/iostream.py", line 182, in advance
    assert 0 < size <= self._size
AssertionError
info 18:5:58.730: Executing silently Code (busy) = def _VSCODE_getVariable(what_to_get, is_debugging, *args):\n# Query Jupyter server for the info
info 18:6:0.693: Executing silently Code (busy) = def _VSCODE_getVariable(what_to_get, is_debugging, *args):\n# Query Jupyter server for the info
info 18:6:3.428: Execute Cell 11 /Users/myuser/Projects/learning/codetest.ipynb
```

### Coding Language and Runtime Version

Python 3.11.3

### Language Extension Version (if applicable)

Python v2022.16.1

### Anaconda Version (if applicable)

conda 23.3.1

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, unfortunately you have a failrly old version of the Jupyter extension
Please could you install the latest versions of Jupyter + Python extensions and VS Code

Also, you seem to be running into issues in the python packages installed, there are some known issues with some of the pakcages.
Please consider installing the following versions as described below
`python -m pip install "jupyter-client<8" "pyzmq<25"`
Possibly related to https://github.com/microsoft/vscode-jupyter/issues/12775

I believe this will resolve the issue you are running into, hence closing this issue
If the problem persists, please feel free to re-open this issue or ping here and we'll re-open this or please feel free to create a new issue and we'll look into it.
