### ISSUE TITLE
Juputer Notebook can't launch with a specific conda env

### ISSUE THREAD

**Issue by Fqlox** [microsoft/vscode-jupyter#13431]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

My specific conda environnement does not launch. When executing a cell, VSCode ask to install Jupyter & Dependecies. I proceed and wait. When installed on my environnement, I re-execute the cell  and it prompts an error:
```
Running cells with 'dlib' requires the ipykernel package.
Run the following command to install 'ipykernel' into the Python environment. 
Command: 'conda install -n dlib ipykernel --update-deps --force-reinstall'
```

I tried installing ipykernel outside of vscode and restarting vscode. It gives the same issue.
Note that other conda environnements work well.

### VS Code Version

1.77.3

### Jupyter Extension Version

v2023.3.1201040234

### Jupyter logs

```shell
warn 14:18:03.435: Kernel Error, context = start [zp [Error]: The kernel died. Error: Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/site-packages/ipykernel/connect.py", line 16, in <module>
    import jupyter_client
  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/site-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/site-packages/jupyter_client/connect.py", line 35, in <module>
    from jupyter_core.paths import jupyter_data_dir, jupyter_runtime_dir, secure_write
ImportError: cannot import name 'secure_write'... View Jupyter [log](command:jupyter.viewOutput) for further details.
	at ChildProcess.<anonymous> (/Users/MyUserName/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:58325)
	at ChildProcess.emit (node:events:538:35)
	at ChildProcess._handle.onexit (node:internal/child_process:291:12)] {
  category: 'kerneldied',
  kernelConnectionMetadata: da {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: '/Users/MyUserName/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/temp/jupyter/kernels/pythonjvsc74a57bd03cde7710b48ec1c9d216904046334830b5599c8953d42175b6c4c9b1647415b4/kernel.json',
      interpreterPath: '/usr/local/Caskroom/miniconda/base/envs/dlib/bin/python',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'pythonjvsc74a57bd03cde7710b48ec1c9d216904046334830b5599c8953d42175b6c4c9b1647415b4',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: 'dlib',
      metadata: [Object],
      env: {}
    },
    interpreter: {
      id: '/usr/local/Caskroom/miniconda/base/envs/dlib/bin/python',
      sysPrefix: '/usr/local/Caskroom/miniconda/base/envs/dlib',
      envPath: [E],
      displayPath: [E],
      envName: 'dlib',
      displayName: 'dlib',
      envType: 'Conda',
      isCondaEnvWithoutPython: false,
      version: [Object],
      uri: [E]
    },
    id: '.jvsc74a57bd03cde7710b48ec1c9d216904046334830b5599c8953d42175b6c4c9b1647415b4./usr/local/Caskroom/miniconda/base/envs/dlib/python./usr/local/Caskroom/miniconda/base/envs/dlib/python.-m#ipykernel_launcher'
  },
  exitCode: 1,
  stdErr: 'Traceback (most recent call last):\n' +
    '  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/runpy.py", line 193, in _run_module_as_main\n' +
    '    "__main__", mod_spec)\n' +
    '  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/runpy.py", line 85, in _run_code\n' +
    '    exec(code, run_globals)\n' +
    '  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/site-packages/ipykernel_launcher.py", line 15, in <module>\n' +
    '    from ipykernel import kernelapp as app\n' +
    '  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/site-packages/ipykernel/__init__.py", line 2, in <module>\n' +
    '    from .connect import *\n' +
    '  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/site-packages/ipykernel/connect.py", line 16, in <module>\n' +
    '    import jupyter_client\n' +
    '  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/site-packages/jupyter_client/__init__.py", line 4, in <module>\n' +
    '    from .connect import *\n' +
    '  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/site-packages/jupyter_client/connect.py", line 35, in <module>\n' +
    '    from jupyter_core.paths import jupyter_data_dir, jupyter_runtime_dir, secure_write\n' +
    "ImportError: cannot import name 'secure_write'\n"
}
info 14:18:03.442: Process Execution: > /usr/local/Caskroom/miniconda/base/envs/dlib/bin/python -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> /usr/local/Caskroom/miniconda/base/envs/dlib/bin/python -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 14:18:03.740: installMissingDependencies /usr/local/Caskroom/miniconda/base/envs/dlib/bin/python, ui.disabled=false for resource '/Users/MyUserName/Documents/Python/facerecoDalle/TestComparaison.ipynb'
info 14:18:03.745: Process Execution: > /usr/local/Caskroom/miniconda/base/envs/dlib/bin/python -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> /usr/local/Caskroom/miniconda/base/envs/dlib/bin/python -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 14:18:05.375: Process Execution: > conda install -c conda-forge --name dlib --update-deps --force-reinstall ipykernel -y
> conda install -c conda-forge --name dlib --update-deps --force-reinstall ipykernel -y
info 14:18:12.198: Loading webview. View is notset
info 14:18:12.199: Loading web view...
info 14:18:12.200: Webview panel created.
info 14:18:12.637: Web view react rendered
info 14:18:34.084: Process Execution: > /usr/local/Caskroom/miniconda/base/envs/dlib/bin/python -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> /usr/local/Caskroom/miniconda/base/envs/dlib/bin/python -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 14:18:36.108: Dispose Kernel '/Users/MyUserName/Documents/Python/facerecoDalle/TestComparaison.ipynb' associated with '/Users/MyUserName/Documents/Python/facerecoDalle/TestComparaison.ipynb'
error 14:18:36.110: Error in execution [zp [Error]: The kernel died. Error: Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/site-packages/ipykernel/connect.py", line 16, in <module>
    import jupyter_client
  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/site-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/site-packages/jupyter_client/connect.py", line 35, in <module>
    from jupyter_core.paths import jupyter_data_dir, jupyter_runtime_dir, secure_write
ImportError: cannot import name 'secure_write'... View Jupyter [log](command:jupyter.viewOutput) for further details.
	at ChildProcess.<anonymous> (/Users/MyUserName/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:58325)
	at ChildProcess.emit (node:events:538:35)
	at ChildProcess._handle.onexit (node:internal/child_process:291:12)] {
  category: 'kerneldied',
  kernelConnectionMetadata: da {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: '/Users/MyUserName/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/temp/jupyter/kernels/pythonjvsc74a57bd03cde7710b48ec1c9d216904046334830b5599c8953d42175b6c4c9b1647415b4/kernel.json',
      interpreterPath: '/usr/local/Caskroom/miniconda/base/envs/dlib/bin/python',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'pythonjvsc74a57bd03cde7710b48ec1c9d216904046334830b5599c8953d42175b6c4c9b1647415b4',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: 'dlib',
      metadata: [Object],
      env: {}
    },
    interpreter: {
      id: '/usr/local/Caskroom/miniconda/base/envs/dlib/bin/python',
      sysPrefix: '/usr/local/Caskroom/miniconda/base/envs/dlib',
      envPath: [E],
      displayPath: [E],
      envName: 'dlib',
      displayName: 'dlib',
      envType: 'Conda',
      isCondaEnvWithoutPython: false,
      version: [Object],
      uri: [E]
    },
    id: '.jvsc74a57bd03cde7710b48ec1c9d216904046334830b5599c8953d42175b6c4c9b1647415b4./usr/local/Caskroom/miniconda/base/envs/dlib/python./usr/local/Caskroom/miniconda/base/envs/dlib/python.-m#ipykernel_launcher'
  },
  exitCode: 1,
  stdErr: 'Traceback (most recent call last):\n' +
    '  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/runpy.py", line 193, in _run_module_as_main\n' +
    '    "__main__", mod_spec)\n' +
    '  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/runpy.py", line 85, in _run_code\n' +
    '    exec(code, run_globals)\n' +
    '  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/site-packages/ipykernel_launcher.py", line 15, in <module>\n' +
    '    from ipykernel import kernelapp as app\n' +
    '  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/site-packages/ipykernel/__init__.py", line 2, in <module>\n' +
    '    from .connect import *\n' +
    '  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/site-packages/ipykernel/connect.py", line 16, in <module>\n' +
    '    import jupyter_client\n' +
    '  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/site-packages/jupyter_client/__init__.py", line 4, in <module>\n' +
    '    from .connect import *\n' +
    '  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/site-packages/jupyter_client/connect.py", line 35, in <module>\n' +
    '    from jupyter_core.paths import jupyter_data_dir, jupyter_runtime_dir, secure_write\n' +
    "ImportError: cannot import name 'secure_write'\n"
}
error 14:18:36.111: Error in execution (get message for cell) [zp [Error]: The kernel died. Error: Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/site-packages/ipykernel/connect.py", line 16, in <module>
    import jupyter_client
  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/site-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/site-packages/jupyter_client/connect.py", line 35, in <module>
    from jupyter_core.paths import jupyter_data_dir, jupyter_runtime_dir, secure_write
ImportError: cannot import name 'secure_write'... View Jupyter [log](command:jupyter.viewOutput) for further details.
	at ChildProcess.<anonymous> (/Users/MyUserName/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/out/extension.node.js:17:58325)
	at ChildProcess.emit (node:events:538:35)
	at ChildProcess._handle.onexit (node:internal/child_process:291:12)] {
  category: 'kerneldied',
  kernelConnectionMetadata: da {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: '/Users/MyUserName/.vscode/extensions/ms-toolsai.jupyter-2023.3.1201040234/temp/jupyter/kernels/pythonjvsc74a57bd03cde7710b48ec1c9d216904046334830b5599c8953d42175b6c4c9b1647415b4/kernel.json',
      interpreterPath: '/usr/local/Caskroom/miniconda/base/envs/dlib/bin/python',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'pythonjvsc74a57bd03cde7710b48ec1c9d216904046334830b5599c8953d42175b6c4c9b1647415b4',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: 'dlib',
      metadata: [Object],
      env: {}
    },
    interpreter: {
      id: '/usr/local/Caskroom/miniconda/base/envs/dlib/bin/python',
      sysPrefix: '/usr/local/Caskroom/miniconda/base/envs/dlib',
      envPath: [E],
      displayPath: [E],
      envName: 'dlib',
      displayName: 'dlib',
      envType: 'Conda',
      isCondaEnvWithoutPython: false,
      version: [Object],
      uri: [E]
    },
    id: '.jvsc74a57bd03cde7710b48ec1c9d216904046334830b5599c8953d42175b6c4c9b1647415b4./usr/local/Caskroom/miniconda/base/envs/dlib/python./usr/local/Caskroom/miniconda/base/envs/dlib/python.-m#ipykernel_launcher'
  },
  exitCode: 1,
  stdErr: 'Traceback (most recent call last):\n' +
    '  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/runpy.py", line 193, in _run_module_as_main\n' +
    '    "__main__", mod_spec)\n' +
    '  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/runpy.py", line 85, in _run_code\n' +
    '    exec(code, run_globals)\n' +
    '  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/site-packages/ipykernel_launcher.py", line 15, in <module>\n' +
    '    from ipykernel import kernelapp as app\n' +
    '  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/site-packages/ipykernel/__init__.py", line 2, in <module>\n' +
    '    from .connect import *\n' +
    '  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/site-packages/ipykernel/connect.py", line 16, in <module>\n' +
    '    import jupyter_client\n' +
    '  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/site-packages/jupyter_client/__init__.py", line 4, in <module>\n' +
    '    from .connect import *\n' +
    '  File "/usr/local/Caskroom/miniconda/base/envs/dlib/lib/python3.6/site-packages/jupyter_client/connect.py", line 35, in <module>\n' +
    '    from jupyter_core.paths import jupyter_data_dir, jupyter_runtime_dir, secure_write\n' +
    "ImportError: cannot import name 'secure_write'\n"
}
info 14:18:36.118: Process Execution: > /usr/local/Caskroom/miniconda/base/envs/dlib/bin/python -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> /usr/local/Caskroom/miniconda/base/envs/dlib/bin/python -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf'
```

### Coding Language and Runtime Version

python 3.6, dlib 19.22.0, jupyter-core 4.5.0 

### Anaconda Version (if applicable)

conda 22.9.0

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Thanks for filing this issue
It looks like the Python environment `dlib` is corrupted in some form, by corrupted I mean some of the packages are not installed correctly or you have some broken/older version of a pakcage that doesn't work correctly

There seem to be some solutions here https://stackoverflow.com/questions/58792782/importerror-cannot-import-name-secure-write-while-updating-python-in-conda-e

Closing this issue as this is an issue with the Python environment itself and not with the Jupyter extension.
Please update the relevant packages or please try creating a new environment.
