### ISSUE TITLE
Using remote kernel inside of a container failed reason: Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by lgonzalezsa** [microsoft/vscode-jupyter#13475]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Good to mention, locally works fine.
Build my standard container and try to connect to the existing Jupyter kernel and got error:

```bash
19:18:36.612 [info] Started Kernel the_env (Python 3.9.16) (pid: 1595)
19:18:36.612 [info] Started new session 3d78d4af-7781-4857-b875-8b51a07dbaa3
19:18:36.907 [info] Process Execution: /opt/conda/envs/the_env/bin/python ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/pythonFiles/printJupyterDataDir.py
19:19:22.706 [error] Error fetching kernels from https://the_host:8000/user/gonluisr/ (the_host, jupyter): [FetchError: request to https://the_host:8000/user/gonluisr/api/kernels?1683573562270 failed, reason: Client network socket disconnected before secure TLS connection was established
	at ClientRequest.<anonymous> (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:2:1139284)
	at ClientRequest.emit (node:events:513:28)
	at TLSSocket.socketErrorListener (node:_http_client:481:9)
	at TLSSocket.emit (node:events:513:28)
	at emitErrorNT (node:internal/streams/destroy:157:8)
	at emitErrorCloseNT (node:internal/streams/destroy:122:3)
	at processTicksAndRejections (node:internal/process/task_queues:83:21)]
19:19:22.837 [error] UniversalRemoteKernelFinder: Failed to get kernels without cache [FetchError: request to https://the_host:8000/user/gonluisr/api/kernels?1683573562270 failed, reason: Client network socket disconnected before secure TLS connection was established
	at ClientRequest.<anonymous> (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:2:1139284)
	at ClientRequest.emit (node:events:513:28)
	at TLSSocket.socketErrorListener (node:_http_client:481:9)
	at TLSSocket.emit (node:events:513:28)
	at emitErrorNT (node:internal/streams/destroy:157:8)
	at emitErrorCloseNT (node:internal/streams/destroy:122:3)
	at processTicksAndRejections (node:internal/process/task_queues:83:21)]
19:19:22.837 [error] SessionManager:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at e.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:2:171555)
	at u.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:2:62984)
	at jf.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:17:176229)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Bf.listKernelsFromConnection (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:17:189405)
	at async ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:17:186840]
19:19:22.855 [info] End refreshing Kernel Picker (1683573512246)
```

### VS Code Version

1.78.0

### Jupyter Extension Version

v2023.4.1011241018

### Jupyter logs

```shell
19:18:36.612 [info] Started Kernel the_env (Python 3.9.16) (pid: 1595)
19:18:36.612 [info] Started new session 3d78d4af-7781-4857-b875-8b51a07dbaa3
19:18:36.907 [info] Process Execution: /opt/conda/envs/the_env/bin/python ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/pythonFiles/printJupyterDataDir.py
19:19:22.706 [error] Error fetching kernels from https://the_host:8000/user/gonluisr/ (the_host, jupyter): [FetchError: request to https://the_host:8000/user/gonluisr/api/kernels?1683573562270 failed, reason: Client network socket disconnected before secure TLS connection was established
	at ClientRequest.<anonymous> (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:2:1139284)
	at ClientRequest.emit (node:events:513:28)
	at TLSSocket.socketErrorListener (node:_http_client:481:9)
	at TLSSocket.emit (node:events:513:28)
	at emitErrorNT (node:internal/streams/destroy:157:8)
	at emitErrorCloseNT (node:internal/streams/destroy:122:3)
	at processTicksAndRejections (node:internal/process/task_queues:83:21)]
19:19:22.837 [error] UniversalRemoteKernelFinder: Failed to get kernels without cache [FetchError: request to https://the_host:8000/user/gonluisr/api/kernels?1683573562270 failed, reason: Client network socket disconnected before secure TLS connection was established
	at ClientRequest.<anonymous> (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:2:1139284)
	at ClientRequest.emit (node:events:513:28)
	at TLSSocket.socketErrorListener (node:_http_client:481:9)
	at TLSSocket.emit (node:events:513:28)
	at emitErrorNT (node:internal/streams/destroy:157:8)
	at emitErrorCloseNT (node:internal/streams/destroy:122:3)
	at processTicksAndRejections (node:internal/process/task_queues:83:21)]
19:19:22.837 [error] SessionManager:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at e.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:2:171555)
	at u.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:2:62984)
	at jf.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:17:176229)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Bf.listKernelsFromConnection (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:17:189405)
	at async ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:17:186840]
19:19:22.855 [info] End refreshing Kernel Picker (1683573512246)
```

### Coding Language and Runtime Version

Python 3.9.16

### Language Extension Version (if applicable)

Python Extension v2023.8.0

### Anaconda Version (if applicable)

micromamba 1.3.1

### Running Jupyter locally or remotely?

Remote

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, and sorry you are running into this.
Are you by any chance using a proxy server or the like to connect to `https://the_host:8000/user/gonluisr`]

I haven't seen this error before and based on some quick searching the error message `Client network socket disconnected before secure TLS connection was established` seems to be related to proxy servers. hence  the above question.

**Comment by lgonzalezsa** [comment]
Thanks for the triage, definitely the proxy setting affects, as matter a of fact not needed inside the container, then remove it and all works as expected. Closing! thanks!
