### ISSUE TITLE
Unable to connect to Kernel of updated remote Jupyter Server without restarting VSCode

### ISSUE THREAD

**Issue by rjra2611** [microsoft/vscode-jupyter#13488]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Hey,

I have implemented the interface IJupyterUriProvider to connect my remote Jupyter servers.

Whenever I update my remote Jupyter server than in that case I'm unable to connect to the new remote kernels
The connection to the new remote Jupyter server seems to be successful as I don't get any errors (which I do when I tried with wrong server uri) and `getServerUri` method is successfully resolved.

The only way I'm able to connect to the kernel of the updated remote Jupyter server is by restarting (closing and reopening) the VSCode.

Attaching the verbose logs for both the cases

[without restart.txt](https://github.com/microsoft/vscode-jupyter/files/11452820/without.restart.txt)
[After restart.txt](https://github.com/microsoft/vscode-jupyter/files/11452821/After.restart.txt)

The difference I notice in the logs is that the `After restart.txt` logs contains

```
18:35:56.349 [debug] Disposing session manager
```
which doesn't happen without restart once both have logged `No controller, hence notebook communications cannot be initialized`

### VS Code Version

Visual Studio Code (1.78.1, undefined, desktop)

### Jupyter Extension Version

Jupyter Extension Version: 2023.4.1011241018.

### Jupyter logs

```shell
Attached the Logs in the Issues Description
```

### Running Jupyter locally or remotely?

None

**Comment by DonJayamanne** [comment]
Thanks for using the API and filing this issue.

If the Uri changes, are you triggering the `onDidChangeHandles` event in the `IJupyterUriProvider`?
If not, then I would suggest doing that

**Comment by rjra2611** [comment]
Hey, 

Can I ask if there are any updates on the issue? Happy to provide more debugging information if required.

**Comment by rjra2611** [comment]
> Are you providing a new handle, ie is the handle different after you update the server or is it the same.

Nope, the handle seems to be the same i.e what was provided initially when registering an instance of `IJupyterUriProvider`.

The new server uri (`IJupyterServerUri`) is provided when `getServerUri` is called. I believe `IJupyterServerUri` doesn't have an attribute to provide handle therefore, I believe the handle always remains the same. 


> Also please could you test this against the latest pre release version in vscode insiders.
> I fixed a few issues in this area recently

Got it, will try to test with https://code.visualstudio.com/insiders/#

**Comment by DonJayamanne** [comment]
If the server Uri changes, then please create a new handle and trigger a change instead of returning the new server Uri from the getServerUri method.
Also ensure the old handle is no longer returned in the list of handles.

Try that and let me know how it goes

**Comment by rjra2611** [comment]
Hey, Thanks

Triggering the handle change and sending the updated handle list does seem to trigger getServerUri but when trying to run the notebook with the kernel of the updated server then the notebook throws:

```
02:07:10.556 [debug] VSCodeNotebookController::handleExecution, Class name = Dy (started execution)
02:07:10.556 [debug] Execute Cell 1 d:\quantconnect\vscode-lean-init\Creative Yellow Green Hornet\research.ipynb
02:07:10.557 [debug] start the kernel, options.disableUI=false for d:\quantconnect\vscode-lean-init\Creative Yellow Green Hornet\research.ipynb
02:07:10.557 [debug] Execute Cell 2 d:\quantconnect\vscode-lean-init\Creative Yellow Green Hornet\research.ipynb
02:07:10.557 [debug] start the kernel, options.disableUI=false for d:\quantconnect\vscode-lean-init\Creative Yellow Green Hornet\research.ipynb
02:07:10.557 [debug] End cell 1 execution @ undefined, started @ undefined, elapsed time = 0s
02:07:10.557 [error] Error in execution Error: notebook controller is DISPOSED
    at Object.createNotebookCellExecution (c:\<username>s\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:100:97574)
    at Function.create (c:\<username>s\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.4.1011241018-win32-x64\out\extension.node.js:17:194831)
    at Function.getOrCreate (c:\<username>s\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.4.1011241018-win32-x64\out\extension.node.js:17:194711)
    at Dy.createCellExecutionIfNecessary (c:\<username>s\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.4.1011241018-win32-x64\out\extension.node.js:24:200053)
    at Dy.executeCell (c:\<username>s\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.4.1011241018-win32-x64\out\extension.node.js:24:200510)
    at async Promise.all (index 0)
    at Dy.handleExecution (c:\<username>s\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.4.1011241018-win32-x64\out\extension.node.js:24:197326)
02:07:10.558 [error] Error in execution (get message for cell) Error: notebook controller is DISPOSED
    at Object.createNotebookCellExecution (c:\<username>s\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:100:97574)
    at Function.create (c:\<username>s\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.4.1011241018-win32-x64\out\extension.node.js:17:194831)
    at Function.getOrCreate (c:\<username>s\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.4.1011241018-win32-x64\out\extension.node.js:17:194711)
    at Dy.createCellExecutionIfNecessary (c:\<username>s\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.4.1011241018-win32-x64\out\extension.node.js:24:200053)
    at Dy.executeCell (c:\<username>s\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.4.1011241018-win32-x64\out\extension.node.js:24:200510)
    at async Promise.all (index 0)
    at Dy.handleExecution (c:\<username>s\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.4.1011241018-win32-x64\out\extension.node.js:24:197326)
02:07:10.558 [error] Error in execution Error: notebook controller is DISPOSED
    at Object.createNotebookCellExecution (c:\<username>s\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:100:97574)
    at Function.create (c:\<username>s\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.4.1011241018-win32-x64\out\extension.node.js:17:194831)
    at Function.getOrCreate (c:\<username>s\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.4.1011241018-win32-x64\out\extension.node.js:17:194711)
    at Dy.createCellExecutionIfNecessary (c:\<username>s\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.4.1011241018-win32-x64\out\extension.node.js:24:200053)
    at Dy.executeCell (c:\<username>s\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.4.1011241018-win32-x64\out\extension.node.js:24:200510)
    at async Promise.all (index 1)
    at Dy.handleExecution (c:\<username>s\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.4.1011241018-win32-x64\out\extension.node.js:24:197326)
02:07:10.558 [error] Error in execution (get message for cell) Error: notebook controller is DISPOSED
    at Object.createNotebookCellExecution (c:\<username>s\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:100:97574)
    at Function.create (c:\<username>s\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.4.1011241018-win32-x64\out\extension.node.js:17:194831)
    at Function.getOrCreate (c:\<username>s\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.4.1011241018-win32-x64\out\extension.node.js:17:194711)
    at Dy.createCellExecutionIfNecessary (c:\<username>s\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.4.1011241018-win32-x64\out\extension.node.js:24:200053)
    at Dy.executeCell (c:\<username>s\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.4.1011241018-win32-x64\out\extension.node.js:24:200510)
    at async Promise.all (index 1)
    at Dy.handleExecution (c:\<username>s\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.4.1011241018-win32-x64\out\extension.node.js:24:197326)
02:07:10.562 [error] VSCodeNotebookController::handleExecution, Class name = Dy, completed in 6ms, has a falsy return value Error: notebook controller is DISPOSED
    at Object.createNotebookCellExecution (c:\<username>s\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:100:97574)
    at Function.create (c:\<username>s\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.4.1011241018-win32-x64\out\extension.node.js:17:194831)
    at Function.getOrCreate (c:\<username>s\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.4.1011241018-win32-x64\out\extension.node.js:17:194711)
    at gm (c:\<username>s\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.4.1011241018-win32-x64\out\extension.node.js:17:203807)
    at Dy.executeCell (c:\<username>s\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.4.1011241018-win32-x64\out\extension.node.js:24:200881)
    at async Promise.all (index 0)
    at Dy.handleExecution (c:\<username>s\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.4.1011241018-win32-x64\out\extension.node.js:24:197326)
```

**Comment by DonJayamanne** [comment]
Ok I think understand what's happening
Questions
1. Why is the server changing, ie why do you need to start a new server

The way the UI works is, if the server/handle changes, then the previously selected notebook kernel is deleted/disposed and the user will need to  select another kernel and run a cell

2. What is different between the new and the old server. Are the tokens/auth details different
3.

**Comment by rjra2611** [comment]
Hey, thanks for the quick response!

> Why is the server changing, ie why do you need to start a new server

We have servers running on CPU/GPU and users toggle between them.

> What is different between the new and the old server. Are the tokens/auth details different

Yup, both server uri and auth tokens are different 

> The way the UI works is, if the server/handle changes, then the previously selected notebook kernel is deleted/disposed and the user will need to select another kernel and run a cell

The way I'm tackling this is on server uri change:

- Close all the open notebooks to dispose old kernel

```
for (const editor of editors) {
    await vscode.window.showNotebookDocument(editor.notebook);
    await vscode.commands.executeCommand('workbench.action.closeActiveEditor');
}
```

- use `openNotebookDocument` API to open and connect with the new kernel as you suggested earlier

The new kernel does reflect on the notebook but when I run the notebook it throws with the error shared in the previous comment

**Comment by rjra2611** [comment]
Even if I don't close the notebooks and use the `openNotebookDocument` API to switch the new kernels. It seems to succesfully connect to new kernel ( I can see it going from `select kernel` to `my new kernel`) and also the below logs seems to suggest that it connected to the new kernel but I get the error on running the notebook cell

```
03:30:22.453 [info] Connecting remote server kernel <server-uri>
03:30:22.456 [debug] Connection complete server
03:30:24.105 [debug] Disposing session manager
03:30:24.105 [debug] SessionManager - dispose contents manager
03:30:24.105 [debug] ShutdownSessionAndConnection - dispose session manager
03:30:24.105 [debug] Finished disposing jupyter session manager
03:30:24.105 [debug] UniversalRemoteKernelFinder: Writing 10 remote kernel connection metadata to cache
03:30:24.117 [info] End refreshing Kernel Picker (1684360601494)
```

**Comment by DonJayamanne** [comment]
1. Looks like you are not using the latest pre-release version of the Jupyter extension, please can you test this again the latest pre-release version of the Jupyter extension and vs code insiders

* Please install latest VS Code Insiders
* Open the extensions page, search for Jupyter and click the button `Switch to Pre-Release Version`
* Similarly please install the latest `Pre-Release` version of the Python extension

<img width="572" alt="Screenshot 2023-02-04 at 09 24 37" src="https://user-images.githubusercontent.com/1948812/216722719-fd8e14dc-783f-4859-8235-012b1bc796d9.png">

> both server uri 

2. Sorry to ask this again, but is host name and port number different or is part of the query string different in the Uri.

3. Finally, after you have implemented the new changes and installed vscode insiders and the latest pre-release, please can you try this again and share the logs.
Thanks, still trying to figure out where this is going wrong.
thanks for your patience

**Comment by rjra2611** [comment]
Hey, 

Did a test with VSCode insiders, Jupyter Pre Release, and Python Pre Release but got the same bug.

[VSCode Insider Debug logs.txt](https://github.com/microsoft/vscode-jupyter/files/11506160/VSCode.Insider.Debug.logs.txt)

> is host name and port number different or is part of the query string different in the Uri.

No, it's part of the uri itself.

**Comment by DonJayamanne** [comment]
I beleive I've identified the issues here, unfortunately the fixes will take a while to get into the product as there is quite a lot that needs to be fixed in this space.
I have a PR with the changes, but trying to find a safe way to ship these changes in the next releaes. Will keep you posted

**Comment by NightMachinery** [comment]
https://github.com/microsoft/vscode/issues/186903

**Comment by DonJayamanne** [comment]
@rjra2611 plese can you test the latest relese version, I believe this should be fixed now.

**Comment by DonJayamanne** [comment]
Closing for now, if this issue persists, please feel free to create a new issue.
You might also be interested in this issue
https://github.com/microsoft/vscode-jupyter/issues/13894

We're looking at making the API stable and simplifying it.

**Comment by roblourens** [comment]
Looks like there is nothing to verify here?
