### ISSUE TITLE
Kernal Crashed

### ISSUE THREAD

**Issue by MuhammedM294** [microsoft/vscode-jupyter#13591]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I tried to get a summary of the vgg19 deep learning model using PyTorch. 

            from torchsummary import summary 
            from torchvision import models
            import torch
            
            vgg19 = models.vgg19(pretrained=True)
            summary(vgg19 , torch.zeros(1,3,64,64))

### VS Code Version

Version: 1.78.2 (user setup) 

### Jupyter Extension Version

v2023.4.1011241018

### Jupyter logs

```shell
17:03:43.114 [error] Disposing session as kernel process died ExitCode: undefined, Reason: 0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
~/anaconda3/envs/cv/lib/python3.11/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
~/anaconda3/envs/cv/lib/python3.11/site-packages/traitlets/traitlets.py:2499: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use 'ed092d0f-46f0-4ef2-ac09-bec7ceff30df' instead of 'b"ed092d0f-46f0-4ef2-ac09-bec7ceff30df"'.
  warn(

17:03:43.114 [info] Dispose Kernel process 758.
17:03:43.114 [error] Raw kernel process exited code: undefined
17:03:43.117 [error] Error in waiting for cell to complete Error: Canceled future for execute_request message before replies were done
    at t.KernelShellFutureHandler.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:2:32419)
    at ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:2:51471
    at Map.forEach (<anonymous>)
    at v._clearKernelState (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:2:51456)
    at v.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:2:44938)
    at ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:105531
    at te (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:2:1587099)
    at Zg.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:105507)
    at nv.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:112790)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
17:03:43.118 [warn] Cell completed with errors {
  message: 'Canceled future for execute_request message before replies were done'
}
17:03:43.119 [warn] Cancel all remaining cells due to cancellation or failure in execution
17:06:22.076 [info] Restart requested ~/projects/EuroSat/workflow.ipynb
17:06:23.168 [info] Process Execution: ~/anaconda3/envs/cv/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
17:06:23.176 [info] Process Execution: ~/anaconda3/envs/cv/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"d7a047a1-f1e5-4619-8ef3-ff4f786992ee" --shell=9002 --transport="tcp" --iopub=9004 --f=~/.local/share/jupyter/runtime/kernel-v2-515Fd31ApiS8QbM.json
    > cwd: ~/projects/EuroSat
17:06:23.346 [info] ipykernel version & path 6.23.1, ~/anaconda3/envs/cv/lib/python3.11/site-packages/ipykernel/__init__.py for ~/anaconda3/envs/cv/bin/python
17:06:23.484 [warn] StdErr from Kernel Process 0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
17:06:23.592 [info] Started Kernel cv (Python 3.11.3) (pid: 1700)
17:06:23.592 [info] Started new session f3996261-b73e-4fc8-a110-57ead7fbbc42
17:06:23.593 [info] Shutdown old session undefined
17:06:23.812 [warn] Cancel all remaining cells due to cancellation or failure in execution
17:06:39.721 [error] Disposing session as kernel process died ExitCode: undefined, Reason: 0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.

17:06:39.721 [info] Dispose Kernel process 1700.
17:06:39.721 [error] Raw kernel process exited code: undefined
17:06:39.722 [error] Error in waiting for cell to complete Error: Canceled future for execute_request message before replies were done
    at t.KernelShellFutureHandler.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:2:32419)
    at ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:2:51471
    at Map.forEach (<anonymous>)
    at v._clearKernelState (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:2:51456)
    at v.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:2:44938)
    at ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:105531
    at te (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:2:1587099)
    at Zg.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:105507)
    at nv.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:112790)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
17:06:39.723 [warn] Cell completed with errors {
  message: 'Canceled future for execute_request message before replies were done'
}
17:06:39.723 [warn] Cancel all remaining cells due to cancellation or failure in execution
18:17:56.830 [error] Cell execution failed without request, for cell Index 21 Error: Cannot execute code, session has been disposed.
    > at rv.requestExecute (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:17:164062)
18:17:56.830 [warn] Cell completed with errors Error: Cannot execute code, session has been disposed.
    > at rv.requestExecute (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:17:164062)
18:17:56.831 [warn] Cancel all remaining cells due to cancellation or failure in execution
18:18:05.779 [error] Error in execution Error: The kernel 'cv (Python 3.11.3)' died. Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. View Jupyter [log](command:jupyter.viewOutput) for further details.
    > Kernel Id = .jvsc74a57bd0af4a7d9ad8cd36f0aaec98b72604fbf39b128beb9ba36c75429da20bf2c40f2f.~/anaconda3/envs/cv/python.~/anaconda3/envs/cv/python.-m#ipykernel_launcher
    > Interpreter Id = ~/anaconda3/envs/cv/bin/python
    > at Function.verifyKernelState (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:189226)
    > originalException = undefined
18:18:05.780 [error] Error in execution (get message for cell) Error: The kernel 'cv (Python 3.11.3)' died. Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. View Jupyter [log](command:jupyter.viewOutput) for further details.
    > Kernel Id = .jvsc74a57bd0af4a7d9ad8cd36f0aaec98b72604fbf39b128beb9ba36c75429da20bf2c40f2f.~/anaconda3/envs/cv/python.~/anaconda3/envs/cv/python.-m#ipykernel_launcher
    > Interpreter Id = ~/anaconda3/envs/cv/bin/python
    > at Function.verifyKernelState (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:189226)
    > originalException = undefined
18:18:59.196 [info] Restart requested ~/projects/EuroSat/workflow.ipynb
```

### Coding Language and Runtime Version

Python 3.11.3

### Language Extension Version (if applicable)

v2023.8.0

### Anaconda Version (if applicable)

conda 23.3.1

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
@MuhammedM294 thank you for filing this issue and sorry you are running into this.
Based on the logs the kernel has crashed, and we've seen similar issues in the past when kernels crash when using PyTorch or similar modules.

Please could you try the following
* Install Jupyter notebook into the same python environment `/anaconda3/envs/cv`
* Then launch jupyter from the same environemnt and run the same notebook and verify it works.

**Comment by MuhammedM294** [comment]
@DonJayamanne Thank you for your response. Actually, it works with jupyter notebook without any issues. The problem happens when I tried to use the Jupyter extension within VS.

**Comment by DonJayamanne** [comment]
Can you try the following
* Run the following in Jupyter Notebook and take a screenshot of the output
```python
import sys
sys.executable
```
* Then run the above code in Jupyter Notebook within VS Code as well and take a screenshot of the same.
* Finally, please could you share ALL of the logs from the Jupyter extension
    * Please reload VS Code (so you start with a clean slate)
    * Run the cell in the notebook
    * Capture the logs (paste all of the logs)

**Comment by DonJayamanne** [comment]
Thank you for getting back, As suspected, you are not using the same Environment to run Jupyter. In Jupyter Notebook you are using the python envioronment `/usr/bin/python3`.

I would suggest you use the same environment in VS Code as well to get things working.
You can go into the kernel picker, select `Python Environment` and then select the same `/usr/bin/python3`.


If you wish to use `cv` conda environment, then it looks like that environment needs to be fixed, somethign isn't working in that environment. I would suggest either creating a new environment or re-installing all of the packages in that environment.

**Comment by MuhammedM294** [comment]
@DonJayamanne  I just switched the kernel to `/usr/bin/python3` and it worked well. Thanks a lot for your time.
