### ISSUE TITLE
Viewing a Pandas DataFrame with uuids in a column  fails with SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by wligtenberg** [microsoft/vscode-jupyter#13619]
### Applies To

- [ ] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I have recreated the error in the following minimal example.

Add a breakpoint on line 5, and use View Value in Data Viewer on the `df` variable.
Note the error (mentioned below) and it seems to hang, the progress bar continues to change, but nothing happens.

I expected the DataFrame to show with the uuids visible. (a similar issue arose with bytearrays (containing the uuids))
```
import uuid
import pandas as pd

df = pd.DataFrame({"uuid" : [uuid.uuid1(), uuid.uuid1()]})
print(df)
```

### VS Code Version

1.78.2

### Jupyter Extension Version

2023.4.1011241018

### Jupyter logs

```shell
21:10:23.247 [error] [SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at Pb.getDataFrameRows (~/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:265079)
	at async jk.getRows (~/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:553013)
	at async ~/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:541076
	at async wk.wrapRequest (~/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:541353)]
21:10:23.249 [warn] DataScience Error [SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at Pb.getDataFrameRows (~/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:265079)
	at async jk.getRows (~/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:553013)
	at async ~/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:541076
	at async wk.wrapRequest (~/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:541353)]
```

### Coding Language and Runtime Version

Python 3.8.10

### Language Extension Version (if applicable)

2023.8.0

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
closing as the jupyter data viewer was deprecated https://github.com/microsoft/vscode-jupyter/issues/15486
