### ISSUE TITLE
Testing Linux arm32: Failed to launch

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-jupyter#13614]
Testing #13587

Running `print("Hello World")` failed:

```
Visual Studio Code - Insiders (1.79.0-insider, dev-container, desktop)
Jupyter Extension Version: 2023.5.1001530929.
Python Extension Version: 2023.9.11491011.
Platform: linux (arm).
Workspace folder /workspaces/vscode, Home = /root
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
08:51:59.740 [info] Start refreshing Interpreter Kernel Picker (1685523119739)
08:51:59.849 [info] Using Pylance
08:52:04.608 [warn] Failed to get activated env vars for /usr/local/python/current/bin/python in 73ms
08:52:04.650 [info] Process Execution: /usr/local/python/current/bin/python -c "import site;print("USER_BASE_VALUE");print(site.USER_BASE);print("USER_BASE_VALUE");"
08:52:04.850 [info] Process Execution: /usr/local/python/current/bin/python -m pip list
08:52:08.997 [info] End refreshing Interpreter Kernel Picker (1685523119739)
08:53:01.590 [info] Handle Execution of Cells 0 for Untitled-1.ipynb
08:53:01.621 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd0eb4a0ac80907d7f44e1a5e88d3d3381b33e3dbedd3a24d113e876f30a0c46bee./usr/local/python/current/python./usr/local/python/current/python.-m#ipykernel_launcher  (Python Path: /usr/local/python/current/bin/python, Unknown, 3.10.6) for 'Untitled-1.ipynb' (disableUI=false)
08:53:01.912 [warn] Failed to get activated env vars for /usr/local/python/current/bin/python in 272ms
08:53:01.935 [info] Process Execution: /usr/local/python/current/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
08:53:01.955 [info] Process Execution: /usr/local/python/current/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"56906d1d-0d57-4e82-954e-16d9797a4e2a" --shell=9002 --transport="tcp" --iopub=9004 --f=~/.local/share/jupyter/runtime/kernel-v2-4089iV5tMqRHiWRA.json
    > cwd: /workspaces/vscode
08:53:02.124 [warn] Stderr output when getting ipykernel version & path Traceback (most recent call last):
    File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'ipykernel' for /usr/local/python/current/bin/python
08:53:02.152 [warn] StdErr from Kernel Process /usr/local/python/current/bin/python: No module named ipykernel_launcher
08:53:02.176 [error] Disposing kernel process due to an error Error: The kernel died. Error: /usr/local/python/current/bin/python: No module named ipykernel_launcher... View Jupyter [log](command:jupyter.viewOutput) for further details.
    > Kernel Id = .jvsc74a57bd0eb4a0ac80907d7f44e1a5e88d3d3381b33e3dbedd3a24d113e876f30a0c46bee./usr/local/python/current/python./usr/local/python/current/python.-m#ipykernel_launcher
    > Interpreter Id = /usr/local/python/current/bin/python
    > at ChildProcess.<anonymous> (~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.5.1001530929-linux-armhf/out/extension.node.js:24:92741)
    > stdErr = /usr/local/python/current/bin/python: No module named ipykernel_launcher
08:53:02.177 [info] Dispose Kernel process 5843.
08:53:02.191 [error] Kernel Launcher. launch, Class name = Hg, completed in 556ms, has a falsy return value, Arg 1: ".jvsc74a57bd0eb4a0ac80907d7f44e1a5e88d3d3381b33e3dbedd3a24d113e876f30a0c46bee./usr/local/python/current/python./usr/local/python/current/python.-m#ipykernel_launcher", Arg 2: 60000, Arg 3: "Untitled-1.ipynb", Arg 4: "/workspaces/vscode", Arg 5: "" Error: The kernel died. Error: /usr/local/python/current/bin/python: No module named ipykernel_launcher... View Jupyter [log](command:jupyter.viewOutput) for further details.
    > Kernel Id = .jvsc74a57bd0eb4a0ac80907d7f44e1a5e88d3d3381b33e3dbedd3a24d113e876f30a0c46bee./usr/local/python/current/python./usr/local/python/current/python.-m#ipykernel_launcher
    > Interpreter Id = /usr/local/python/current/bin/python
    > at ChildProcess.<anonymous> (~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.5.1001530929-linux-armhf/out/extension.node.js:24:92741)
    > stdErr = /usr/local/python/current/bin/python: No module named ipykernel_launcher
08:53:02.194 [error] Failed to connect raw kernel session: Error: The kernel died. Error: /usr/local/python/current/bin/python: No module named ipykernel_launcher... View Jupyter [log](command:jupyter.viewOutput) for further details.
08:53:02.201 [warn] Error occurred while trying to start the kernel, options.disableUI=false Error: The kernel died. Error: /usr/local/python/current/bin/python: No module named ipykernel_launcher... View Jupyter [log](command:jupyter.viewOutput) for further details.
    > Kernel Id = .jvsc74a57bd0eb4a0ac80907d7f44e1a5e88d3d3381b33e3dbedd3a24d113e876f30a0c46bee./usr/local/python/current/python./usr/local/python/current/python.-m#ipykernel_launcher
    > Interpreter Id = /usr/local/python/current/bin/python
    > at ChildProcess.<anonymous> (~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.5.1001530929-linux-armhf/out/extension.node.js:24:92741)
    > stdErr = /usr/local/python/current/bin/python: No module named ipykernel_launcher
08:53:02.204 [warn] Kernel Error, context = start Error: The kernel died. Error: /usr/local/python/current/bin/python: No module named ipykernel_launcher... View Jupyter [log](command:jupyter.viewOutput) for further details.
    > Kernel Id = .jvsc74a57bd0eb4a0ac80907d7f44e1a5e88d3d3381b33e3dbedd3a24d113e876f30a0c46bee./usr/local/python/current/python./usr/local/python/current/python.-m#ipykernel_launcher
    > Interpreter Id = /usr/local/python/current/bin/python
    > at ChildProcess.<anonymous> (~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.5.1001530929-linux-armhf/out/extension.node.js:24:92741)
    > stdErr = /usr/local/python/current/bin/python: No module named ipykernel_launcher
08:53:02.239 [info] Process Execution: /usr/local/python/current/bin/python -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
08:53:02.421 [info] Check & install missing Kernel dependencies for /usr/local/python/current/bin/python, ui.disabled=false for resource 'Untitled-1.ipynb'
08:53:02.443 [info] Process Execution: /usr/local/python/current/bin/python -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
08:53:02.644 [info] Process Execution: /usr/local/python/current/bin/python -c "import pip;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
08:53:07.106 [info] Process Execution: /usr/local/python/current/bin/python -c "import pip;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
08:53:07.400 [warn] Failed to get activated env vars for /usr/local/python/current/bin/python in 70ms
08:53:07.420 [info] Process Execution: /usr/local/python/current/bin/python -m pip install -U --user ipykernel
08:54:50.788 [error] Failed to install ipykernel ERROR: Could not build wheels for pyzmq, which is required to install pyproject.toml-based projects

08:54:50.807 [info] Dispose Kernel 'Untitled-1.ipynb' associated with 'Untitled-1.ipynb'
08:54:50.812 [error] Error in execution Error: The kernel died. Error: /usr/local/python/current/bin/python: No module named ipykernel_launcher... View Jupyter [log](command:jupyter.viewOutput) for further details.
    > Kernel Id = .jvsc74a57bd0eb4a0ac80907d7f44e1a5e88d3d3381b33e3dbedd3a24d113e876f30a0c46bee./usr/local/python/current/python./usr/local/python/current/python.-m#ipykernel_launcher
    > Interpreter Id = /usr/local/python/current/bin/python
    > at ChildProcess.<anonymous> (~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.5.1001530929-linux-armhf/out/extension.node.js:24:92741)
    > stdErr = /usr/local/python/current/bin/python: No module named ipykernel_launcher
08:54:50.819 [error] Error in execution (get message for cell) Error: The kernel died. Error: /usr/local/python/current/bin/python: No module named ipykernel_launcher... View Jupyter [log](command:jupyter.viewOutput) for further details.
    > Kernel Id = .jvsc74a57bd0eb4a0ac80907d7f44e1a5e88d3d3381b33e3dbedd3a24d113e876f30a0c46bee./usr/local/python/current/python./usr/local/python/current/python.-m#ipykernel_launcher
    > Interpreter Id = /usr/local/python/current/bin/python
    > at ChildProcess.<anonymous> (~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.5.1001530929-linux-armhf/out/extension.node.js:24:92741)
    > stdErr = /usr/local/python/current/bin/python: No module named ipykernel_launcher
08:54:50.912 [warn] Failed to get activated env vars for /usr/local/python/current/bin/python in 86ms
08:54:50.934 [info] Process Execution: /usr/local/python/current/bin/python -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
08:54:51.165 [info] End cell 0 execution @ undefined, started @ undefined, elapsed time = 0s
```

<img width="1496" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/9205389/f9a08f3b-1cda-4b7f-b1bc-8e624225e8e3">

Running that command in the terminal:

```
root@1b5ff43b415a:/workspaces/vscode# /usr/local/python/current/bin/python -m pip install ipykernel -U --user --force-reinstall
Collecting ipykernel
  Using cached ipykernel-6.23.1-py3-none-any.whl (152 kB)
Collecting comm>=0.1.1 (from ipykernel)
  Using cached comm-0.1.3-py3-none-any.whl (6.6 kB)
Collecting debugpy>=1.6.5 (from ipykernel)
  Using cached debugpy-1.6.7-py2.py3-none-any.whl (4.9 MB)
Collecting ipython>=7.23.1 (from ipykernel)
  Using cached ipython-8.13.2-py3-none-any.whl (797 kB)
Collecting jupyter-client>=6.1.12 (from ipykernel)
  Using cached jupyter_client-8.2.0-py3-none-any.whl (103 kB)
Collecting jupyter-core!=5.0.*,>=4.12 (from ipykernel)
  Using cached jupyter_core-5.3.0-py3-none-any.whl (93 kB)
Collecting matplotlib-inline>=0.1 (from ipykernel)
  Using cached matplotlib_inline-0.1.6-py3-none-any.whl (9.4 kB)
Collecting nest-asyncio (from ipykernel)
  Using cached nest_asyncio-1.5.6-py3-none-any.whl (5.2 kB)
Collecting packaging (from ipykernel)
  Using cached packaging-23.1-py3-none-any.whl (48 kB)
Collecting psutil (from ipykernel)
  Using cached psutil-5.9.5-cp310-abi3-linux_armv7l.whl
Collecting pyzmq>=20 (from ipykernel)
  Using cached pyzmq-25.1.0.tar.gz (1.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting tornado>=6.1 (from ipykernel)
  Using cached tornado-6.3.2-cp38-abi3-linux_armv7l.whl
Collecting traitlets>=5.4.0 (from ipykernel)
  Using cached traitlets-5.9.0-py3-none-any.whl (117 kB)
Collecting backcall (from ipython>=7.23.1->ipykernel)
  Using cached backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting decorator (from ipython>=7.23.1->ipykernel)
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting jedi>=0.16 (from ipython>=7.23.1->ipykernel)
  Using cached jedi-0.18.2-py2.py3-none-any.whl (1.6 MB)
Collecting pickleshare (from ipython>=7.23.1->ipykernel)
  Using cached pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 (from ipython>=7.23.1->ipykernel)
  Using cached prompt_toolkit-3.0.38-py3-none-any.whl (385 kB)
Collecting pygments>=2.4.0 (from ipython>=7.23.1->ipykernel)
  Using cached Pygments-2.15.1-py3-none-any.whl (1.1 MB)
Collecting stack-data (from ipython>=7.23.1->ipykernel)
  Using cached stack_data-0.6.2-py3-none-any.whl (24 kB)
Collecting pexpect>4.3 (from ipython>=7.23.1->ipykernel)
  Using cached pexpect-4.8.0-py2.py3-none-any.whl (59 kB)
Collecting python-dateutil>=2.8.2 (from jupyter-client>=6.1.12->ipykernel)
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting platformdirs>=2.5 (from jupyter-core!=5.0.*,>=4.12->ipykernel)
  Using cached platformdirs-3.5.1-py3-none-any.whl (15 kB)
Collecting parso<0.9.0,>=0.8.0 (from jedi>=0.16->ipython>=7.23.1->ipykernel)
  Using cached parso-0.8.3-py2.py3-none-any.whl (100 kB)
Collecting ptyprocess>=0.5 (from pexpect>4.3->ipython>=7.23.1->ipykernel)
  Using cached ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Collecting wcwidth (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython>=7.23.1->ipykernel)
  Using cached wcwidth-0.2.6-py2.py3-none-any.whl (29 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->jupyter-client>=6.1.12->ipykernel)
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting executing>=1.2.0 (from stack-data->ipython>=7.23.1->ipykernel)
  Using cached executing-1.2.0-py2.py3-none-any.whl (24 kB)
Collecting asttokens>=2.1.0 (from stack-data->ipython>=7.23.1->ipykernel)
  Using cached asttokens-2.2.1-py2.py3-none-any.whl (26 kB)
Collecting pure-eval (from stack-data->ipython>=7.23.1->ipykernel)
  Using cached pure_eval-0.2.2-py3-none-any.whl (11 kB)
Building wheels for collected packages: pyzmq
  Building wheel for pyzmq (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pyzmq (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [162 lines of output]
      /tmp/pip-build-env-xdbjqnda/overlay/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py:265: UserWarning: Unknown distribution option: 'cffi_modules'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running build_py
      copying zmq/__init__.py -> build/lib.linux-armv7l-cpython-310/zmq
      copying zmq/_typing.py -> build/lib.linux-armv7l-cpython-310/zmq
      copying zmq/asyncio.py -> build/lib.linux-armv7l-cpython-310/zmq
      copying zmq/decorators.py -> build/lib.linux-armv7l-cpython-310/zmq
      copying zmq/_future.py -> build/lib.linux-armv7l-cpython-310/zmq
      copying zmq/constants.py -> build/lib.linux-armv7l-cpython-310/zmq
      copying zmq/error.py -> build/lib.linux-armv7l-cpython-310/zmq
      creating build/lib.linux-armv7l-cpython-310/zmq/devices
      copying zmq/devices/monitoredqueue.py -> build/lib.linux-armv7l-cpython-310/zmq/devices
      copying zmq/devices/__init__.py -> build/lib.linux-armv7l-cpython-310/zmq/devices
      copying zmq/devices/proxysteerabledevice.py -> build/lib.linux-armv7l-cpython-310/zmq/devices
      copying zmq/devices/basedevice.py -> build/lib.linux-armv7l-cpython-310/zmq/devices
      copying zmq/devices/monitoredqueuedevice.py -> build/lib.linux-armv7l-cpython-310/zmq/devices
      copying zmq/devices/proxydevice.py -> build/lib.linux-armv7l-cpython-310/zmq/devices
      creating build/lib.linux-armv7l-cpython-310/zmq/sugar
      copying zmq/sugar/tracker.py -> build/lib.linux-armv7l-cpython-310/zmq/sugar
      copying zmq/sugar/stopwatch.py -> build/lib.linux-armv7l-cpython-310/zmq/sugar
      copying zmq/sugar/frame.py -> build/lib.linux-armv7l-cpython-310/zmq/sugar
      copying zmq/sugar/__init__.py -> build/lib.linux-armv7l-cpython-310/zmq/sugar
      copying zmq/sugar/socket.py -> build/lib.linux-armv7l-cpython-310/zmq/sugar
      copying zmq/sugar/attrsettr.py -> build/lib.linux-armv7l-cpython-310/zmq/sugar
      copying zmq/sugar/poll.py -> build/lib.linux-armv7l-cpython-310/zmq/sugar
      copying zmq/sugar/context.py -> build/lib.linux-armv7l-cpython-310/zmq/sugar
      copying zmq/sugar/version.py -> build/lib.linux-armv7l-cpython-310/zmq/sugar
      creating build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/test_context.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/test_message.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/test_monqueue.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/test_proxy_steerable.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/test_cython.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/test_ext.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/test_mypy.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/test_version.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/test_ssh.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/test_poll.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/test_draft.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/__init__.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/test_monitor.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/test_z85.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/test_retry_eintr.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/test_pubsub.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/test_multipart.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/test_security.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/test_reqrep.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/test_zmqstream.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/test_log.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/test_socket.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/test_future.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/test_pair.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/conftest.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/test_error.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/test_etc.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/test_constants.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/test_auth.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/test_imports.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/test_asyncio.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/test_includes.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/test_cffi_backend.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/test_win32_shim.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/test_decorators.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/test_device.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/tests/test_ioloop.py -> build/lib.linux-armv7l-cpython-310/zmq/tests
      creating build/lib.linux-armv7l-cpython-310/zmq/green
      copying zmq/green/__init__.py -> build/lib.linux-armv7l-cpython-310/zmq/green
      copying zmq/green/device.py -> build/lib.linux-armv7l-cpython-310/zmq/green
      copying zmq/green/poll.py -> build/lib.linux-armv7l-cpython-310/zmq/green
      copying zmq/green/core.py -> build/lib.linux-armv7l-cpython-310/zmq/green
      creating build/lib.linux-armv7l-cpython-310/zmq/green/eventloop
      copying zmq/green/eventloop/__init__.py -> build/lib.linux-armv7l-cpython-310/zmq/green/eventloop
      copying zmq/green/eventloop/ioloop.py -> build/lib.linux-armv7l-cpython-310/zmq/green/eventloop
      copying zmq/green/eventloop/zmqstream.py -> build/lib.linux-armv7l-cpython-310/zmq/green/eventloop
      creating build/lib.linux-armv7l-cpython-310/zmq/ssh
      copying zmq/ssh/__init__.py -> build/lib.linux-armv7l-cpython-310/zmq/ssh
      copying zmq/ssh/forward.py -> build/lib.linux-armv7l-cpython-310/zmq/ssh
      copying zmq/ssh/tunnel.py -> build/lib.linux-armv7l-cpython-310/zmq/ssh
      creating build/lib.linux-armv7l-cpython-310/zmq/utils
      copying zmq/utils/__init__.py -> build/lib.linux-armv7l-cpython-310/zmq/utils
      copying zmq/utils/strtypes.py -> build/lib.linux-armv7l-cpython-310/zmq/utils
      copying zmq/utils/win32.py -> build/lib.linux-armv7l-cpython-310/zmq/utils
      copying zmq/utils/interop.py -> build/lib.linux-armv7l-cpython-310/zmq/utils
      copying zmq/utils/jsonapi.py -> build/lib.linux-armv7l-cpython-310/zmq/utils
      copying zmq/utils/z85.py -> build/lib.linux-armv7l-cpython-310/zmq/utils
      copying zmq/utils/monitor.py -> build/lib.linux-armv7l-cpython-310/zmq/utils
      copying zmq/utils/garbage.py -> build/lib.linux-armv7l-cpython-310/zmq/utils
      creating build/lib.linux-armv7l-cpython-310/zmq/eventloop
      copying zmq/eventloop/__init__.py -> build/lib.linux-armv7l-cpython-310/zmq/eventloop
      copying zmq/eventloop/future.py -> build/lib.linux-armv7l-cpython-310/zmq/eventloop
      copying zmq/eventloop/ioloop.py -> build/lib.linux-armv7l-cpython-310/zmq/eventloop
      copying zmq/eventloop/zmqstream.py -> build/lib.linux-armv7l-cpython-310/zmq/eventloop
      copying zmq/eventloop/_deprecated.py -> build/lib.linux-armv7l-cpython-310/zmq/eventloop
      creating build/lib.linux-armv7l-cpython-310/zmq/auth
      copying zmq/auth/base.py -> build/lib.linux-armv7l-cpython-310/zmq/auth
      copying zmq/auth/__init__.py -> build/lib.linux-armv7l-cpython-310/zmq/auth
      copying zmq/auth/ioloop.py -> build/lib.linux-armv7l-cpython-310/zmq/auth
      copying zmq/auth/asyncio.py -> build/lib.linux-armv7l-cpython-310/zmq/auth
      copying zmq/auth/thread.py -> build/lib.linux-armv7l-cpython-310/zmq/auth
      copying zmq/auth/certs.py -> build/lib.linux-armv7l-cpython-310/zmq/auth
      creating build/lib.linux-armv7l-cpython-310/zmq/backend
      copying zmq/backend/__init__.py -> build/lib.linux-armv7l-cpython-310/zmq/backend
      copying zmq/backend/select.py -> build/lib.linux-armv7l-cpython-310/zmq/backend
      creating build/lib.linux-armv7l-cpython-310/zmq/backend/cffi
      copying zmq/backend/cffi/devices.py -> build/lib.linux-armv7l-cpython-310/zmq/backend/cffi
      copying zmq/backend/cffi/message.py -> build/lib.linux-armv7l-cpython-310/zmq/backend/cffi
      copying zmq/backend/cffi/__init__.py -> build/lib.linux-armv7l-cpython-310/zmq/backend/cffi
      copying zmq/backend/cffi/socket.py -> build/lib.linux-armv7l-cpython-310/zmq/backend/cffi
      copying zmq/backend/cffi/utils.py -> build/lib.linux-armv7l-cpython-310/zmq/backend/cffi
      copying zmq/backend/cffi/context.py -> build/lib.linux-armv7l-cpython-310/zmq/backend/cffi
      copying zmq/backend/cffi/_poll.py -> build/lib.linux-armv7l-cpython-310/zmq/backend/cffi
      copying zmq/backend/cffi/error.py -> build/lib.linux-armv7l-cpython-310/zmq/backend/cffi
      creating build/lib.linux-armv7l-cpython-310/zmq/backend/cython
      copying zmq/backend/cython/__init__.py -> build/lib.linux-armv7l-cpython-310/zmq/backend/cython
      creating build/lib.linux-armv7l-cpython-310/zmq/log
      copying zmq/log/handlers.py -> build/lib.linux-armv7l-cpython-310/zmq/log
      copying zmq/log/__init__.py -> build/lib.linux-armv7l-cpython-310/zmq/log
      copying zmq/log/__main__.py -> build/lib.linux-armv7l-cpython-310/zmq/log
      copying zmq/__init__.pxd -> build/lib.linux-armv7l-cpython-310/zmq
      copying zmq/__init__.pyi -> build/lib.linux-armv7l-cpython-310/zmq
      copying zmq/py.typed -> build/lib.linux-armv7l-cpython-310/zmq
      copying zmq/devices/monitoredqueue.pxd -> build/lib.linux-armv7l-cpython-310/zmq/devices
      copying zmq/sugar/__init__.pyi -> build/lib.linux-armv7l-cpython-310/zmq/sugar
      copying zmq/tests/cython_ext.pyx -> build/lib.linux-armv7l-cpython-310/zmq/tests
      copying zmq/utils/buffers.pxd -> build/lib.linux-armv7l-cpython-310/zmq/utils
      copying zmq/utils/mutex.h -> build/lib.linux-armv7l-cpython-310/zmq/utils
      copying zmq/utils/getpid_compat.h -> build/lib.linux-armv7l-cpython-310/zmq/utils
      copying zmq/utils/zmq_compat.h -> build/lib.linux-armv7l-cpython-310/zmq/utils
      copying zmq/utils/ipcmaxlen.h -> build/lib.linux-armv7l-cpython-310/zmq/utils
      copying zmq/utils/pyversion_compat.h -> build/lib.linux-armv7l-cpython-310/zmq/utils
      copying zmq/utils/compiler.json -> build/lib.linux-armv7l-cpython-310/zmq/utils
      copying zmq/utils/config.json -> build/lib.linux-armv7l-cpython-310/zmq/utils
      copying zmq/backend/__init__.pyi -> build/lib.linux-armv7l-cpython-310/zmq/backend
      copying zmq/backend/cffi/_cdefs.h -> build/lib.linux-armv7l-cpython-310/zmq/backend/cffi
      copying zmq/backend/cython/libzmq.pxd -> build/lib.linux-armv7l-cpython-310/zmq/backend/cython
      copying zmq/backend/cython/socket.pxd -> build/lib.linux-armv7l-cpython-310/zmq/backend/cython
      copying zmq/backend/cython/__init__.pxd -> build/lib.linux-armv7l-cpython-310/zmq/backend/cython
      copying zmq/backend/cython/checkrc.pxd -> build/lib.linux-armv7l-cpython-310/zmq/backend/cython
      copying zmq/backend/cython/message.pxd -> build/lib.linux-armv7l-cpython-310/zmq/backend/cython
      copying zmq/backend/cython/context.pxd -> build/lib.linux-armv7l-cpython-310/zmq/backend/cython
      copying zmq/backend/cython/constant_enums.pxi -> build/lib.linux-armv7l-cpython-310/zmq/backend/cython
      running build_ext
      running configure
      Using bundled libzmq
      already have bundled/zeromq
      already have platform.hpp
      checking for timer_create
      arm-linux-gnueabihf-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/include/python3.10 -c /tmp/timer_createl8zt45e1.c -o tmp/timer_createl8zt45e1.o
      arm-linux-gnueabihf-gcc tmp/timer_createl8zt45e1.o -L/usr/lib/arm-linux-gnueabihf -o a.out
      ok
      ************************************************
      ************************************************
      ************************************************
      building 'zmq.libzmq' extension
      creating build/temp.linux-armv7l-cpython-310/buildutils
      creating build/temp.linux-armv7l-cpython-310/bundled
      creating build/temp.linux-armv7l-cpython-310/bundled/zeromq
      creating build/temp.linux-armv7l-cpython-310/bundled/zeromq/src
      arm-linux-gnueabihf-g++ -std=c++11 -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DZMQ_HAVE_CURVE=1 -DZMQ_USE_TWEETNACL=1 -DZMQ_USE_EPOLL=1 -DZMQ_IOTHREADS_USE_EPOLL=1 -DZMQ_POLL_BASED_ON_POLL=1 -Ibundled/zeromq/include -Ibundled -I/usr/include/python3.10 -c buildutils/initlibzmq.cpp -o build/temp.linux-armv7l-cpython-310/buildutils/initlibzmq.o
      error: command 'arm-linux-gnueabihf-g++' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyzmq
Failed to build pyzmq
ERROR: Could not build wheels for pyzmq, which is required to install pyproject.toml-based projects
root@1b5ff43b415a:/workspaces/vscode# 
```

**Comment by DonJayamanne** [comment]
> error: command 'arm-linux-gnueabihf-g++' failed: No such file or directory
      [end of output]

Looks like a user environment issue.
Basically we have a python environment into which ipykernel cannot be installed.
I will document how to find and install a version of python that can be installed into this Linux arm.

The original issue has been tested successfully, as the native zmq module has been successfully loaded by the extension, is just execution of python code that failed due to a setup issue.

**Comment by DonJayamanne** [comment]
Closing this issue as this is not a problem with the extension itself, but a problem with installing ipykernel into Python (which is beyond the control of this extension).
I.e. its a user setup/environment issue.
