### ISSUE TITLE
Not detecting ipykernel package in python virtualenvs on nixos

### ISSUE THREAD

**Issue by data-stepper** [microsoft/vscode-jupyter#13679]
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I usually create python virtual environments for my development workflow so I can quickly install packages (and not have to go through the entire building process of nixos environments).
First, I create a python interpreter with the following `shell.nix` configuration script:

```
{ pkgs ? import <nixpkgs> { } }:

let
  pythonEnv = pkgs.python310.withPackages (ps:
    with ps; [
      requests
      yfinance
      ipykernel
      pandas
      matplotlib
      pandas-datareader
      jupyter
      notebook
    ]);
in pkgs.mkShell {
  buildInputs =
    [ pythonEnv pkgs.python310Packages.pip pkgs.python310Packages.virtualenv ];
  shellHook = ''
    zsh
  '';
}
```

Then, to add more packages later on, I would create a virtual env and install some more packages using pip (including `ipykernel`, `jupyter` and `notebook`, which are correctly installed in the venv according to pip).
When selecting this venv kernel as my notebook kernel, vscode won't run any cells with it complaining:

```
Running cells with 'venv' requires the ipykernel package.
Run the following command to install 'ipykernel' into the Python environment. 
Command: '/home/bent/Documents/playgrounds/venv/bin/python -m pip install ipykernel -U --force-reinstall'
```

I can run the notebooks using the python executable from the nix environment directly (however, there it is annoying to install some specific packages) by setting my python interpreter to e.g. `/nix/store/icdvqyyg7v7gdnxm4r4l67l8qrn39w5k-python3-3.10.11-env/bin/python`.
Have I done something wrong when setting up the nix environment or the virtual environment?

Thanks in advance for any help.

### VS Code Version

Version: 1.78.2 Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435 Date: 2023-05-10T14:47:05.613Z Electron: 22.5.2 Chromium: 108.0.5359.215 Node.js: 16.17.1 V8: 10.8.168.25-electron.0 OS: Linux x64 6.3.5 Sandboxed: No

### Jupyter Extension Version

v2023.4.1011241018

### Jupyter logs

```shell
23:10:09.718 [warn] Jupyter Kernel Dependency Error, reason=1 Error: Kernel venv (Python 3.10.11) is not usable. Check the Jupyter output tab for more information.
    > Kernel Id = .jvsc74a57bd06168c971328f7efa99e46049f9f2a315448b0a196f636e873bf14b10301e23da.~/Documents/playgrounds/venv/python.~/Documents/playgrounds/venv/python.-m#ipykernel_launcher
    > Interpreter Id = ~/Documents/playgrounds/venv/bin/python
    > at bh.ensureKernelIsUsable (~/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:17:100933)
    > reason = 1
23:10:09.718 [info] Dispose Kernel '~/Documents/playgrounds/portfolio_opt.ipynb' associated with '~/Documents/playgrounds/portfolio_opt.ipynb'
23:10:09.720 [error] Error in execution Error: Kernel venv (Python 3.10.11) is not usable. Check the Jupyter output tab for more information.
    > Kernel Id = .jvsc74a57bd06168c971328f7efa99e46049f9f2a315448b0a196f636e873bf14b10301e23da.~/Documents/playgrounds/venv/python.~/Documents/playgrounds/venv/python.-m#ipykernel_launcher
    > Interpreter Id = ~/Documents/playgrounds/venv/bin/python
    > at bh.ensureKernelIsUsable (~/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:17:100933)
    > reason = 1
23:10:09.720 [error] Error in execution (get message for cell) Error: Kernel venv (Python 3.10.11) is not usable. Check the Jupyter output tab for more information.
    > Kernel Id = .jvsc74a57bd06168c971328f7efa99e46049f9f2a315448b0a196f636e873bf14b10301e23da.~/Documents/playgrounds/venv/python.~/Documents/playgrounds/venv/python.-m#ipykernel_launcher
    > Interpreter Id = ~/Documents/playgrounds/venv/bin/python
    > at bh.ensureKernelIsUsable (~/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:17:100933)
    > reason = 1
23:10:09.720 [error] Error in execution Error: Kernel venv (Python 3.10.11) is not usable. Check the Jupyter output tab for more information.
    > Kernel Id = .jvsc74a57bd06168c971328f7efa99e46049f9f2a315448b0a196f636e873bf14b10301e23da.~/Documents/playgrounds/venv/python.~/Documents/playgrounds/venv/python.-m#ipykernel_launcher
    > Interpreter Id = ~/Documents/playgrounds/venv/bin/python
    > at bh.ensureKernelIsUsable (~/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:17:100933)
    > reason = 1
23:10:09.720 [error] Error in execution (get message for cell) Error: Kernel venv (Python 3.10.11) is not usable. Check the Jupyter output tab for more information.
    > Kernel Id = .jvsc74a57bd06168c971328f7efa99e46049f9f2a315448b0a196f636e873bf14b10301e23da.~/Documents/playgrounds/venv/python.~/Documents/playgrounds/venv/python.-m#ipykernel_launcher
    > Interpreter Id = ~/Documents/playgrounds/venv/bin/python
    > at bh.ensureKernelIsUsable (~/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:17:100933)
    > reason = 1
23:10:09.721 [error] Error in execution Error: Kernel venv (Python 3.10.11) is not usable. Check the Jupyter output tab for more information.
    > Kernel Id = .jvsc74a57bd06168c971328f7efa99e46049f9f2a315448b0a196f636e873bf14b10301e23da.~/Documents/playgrounds/venv/python.~/Documents/playgrounds/venv/python.-m#ipykernel_launcher
    > Interpreter Id = ~/Documents/playgrounds/venv/bin/python
    > at bh.ensureKernelIsUsable (~/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:17:100933)
    > reason = 1
23:10:09.721 [error] Error in execution (get message for cell) Error: Kernel venv (Python 3.10.11) is not usable. Check the Jupyter output tab for more information.
    > Kernel Id = .jvsc74a57bd06168c971328f7efa99e46049f9f2a315448b0a196f636e873bf14b10301e23da.~/Documents/playgrounds/venv/python.~/Documents/playgrounds/venv/python.-m#ipykernel_launcher
    > Interpreter Id = ~/Documents/playgrounds/venv/bin/python
    > at bh.ensureKernelIsUsable (~/.vscode/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:17:100933)
    > reason = 1
```

### Coding Language and Runtime Version

Python 3.10.11

### Language Extension Version (if applicable)

v2023.9.11461009

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Thank you for filing this issue and sorry you are running into this.
I haven't tried NixOS myself, will have a look at that.

**Comment by data-stepper** [comment]
Thanks for looking into it, I think you may be able to replicate this issue just using the nix package manager (even on nixos).

I am currently working around it by starting the jupyter server from the command line and then connecting manually using the URL (so ipykernel is certainly installed).

Would just be great if it works natively (also for future NixOS users who don't know how to manually connect to the jupyter server I guess).

**Comment by DonJayamanne** [comment]
Thanks for this feature requets, however this issue hasn't reveived any upvotes since.
Hence closing this issue.
