### ISSUE TITLE
Clear Jupyter Remote Server List command fails to parse URIs  

### ISSUE THREAD

**Issue by TobyWallage** [microsoft/vscode-jupyter#13693]
Trying to remove old Remote jupyter server URIs, but the command `Jupyter: Clear Jupyter Remote Server List` fails as it seems to be trying to parse the old URIs.

## Environment data

-   VS Code version: 1.79
-   Jupyter Extension version (available under the Extensions sidebar): v2023.5.1001582324
-   Python Extension version (available under the Extensions sidebar): v2023.10.0
-   OS (Windows | Mac | Linux distro) and version: Windows 10 Pro 22H2
-   Python and/or Anaconda version: Python 3.9.12 / Anaconda 2022.05
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Remote

## Expected behaviour

`Jupyter: Clear Jupyter Remote Server List` clears Remote server list with no error

## Actual behaviour

command fails and Server list is not cleared
![image](https://github.com/microsoft/vscode-jupyter/assets/106962588/08d91a99-e133-4f2c-8777-9a5b49b7891c)

## Logs

<details>

<summary>
<code>
Visual Studio Code (1.79.1, undefined, desktop)
Jupyter Extension Version: 2023.5.1001582324.
Python Extension Version: 2023.10.0.
Platform: win32 (x64).
No workspace folder opened.
18:09:27.905 [info] Start refreshing Interpreter Kernel Picker (1686676167905)
18:09:27.982 [info] Using Pylance
18:09:28.146 [error] Failed to parse remote URI http://127.0.0.1:12001/?token=c996887770c1fb03bdf6435a1615bf8b69bf7b382b8e7caf [Error: Invalid remote URI
	at qr (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:2:1694598)
	at hk.parseUri (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:24:529924)
	at c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:24:527677]
18:09:28.147 [error] Failed to parse remote URI http://127.0.0.1:12001/?token=c996887770c1fb03bdf6435a1615bf8b69bf7b382b8e7caf [Error: Invalid remote URI
	at qr (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:2:1694598)
	at hk.parseUri (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:24:529924)
	at c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:24:527677]
18:09:28.147 [error] Failed to parse remote URI http://127.0.0.1:12001/ [Error: Invalid remote URI
	at qr (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:2:1694598)
	at hk.parseUri (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:24:529924)
	at c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:24:527677]
18:09:28.147 [error] Failed to parse remote URI http://127.0.0.1:12001/?token=68124e9a0261b101f6f2cc5923eb43e723f18b7565cd679a [Error: Invalid remote URI
	at qr (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:2:1694598)
	at hk.parseUri (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:24:529924)
	at c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:24:527677]
18:09:28.147 [error] Failed to parse remote URI http://127.0.0.1:12001/?token=68124e9a0261b101f6f2cc5923eb43e723f18b7565cd679a [Error: Invalid remote URI
	at qr (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:2:1694598)
	at hk.parseUri (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:24:529924)
	at c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:24:527677]
18:09:28.147 [error] Failed to parse remote URI http://localhost:12001/?token=68124e9a0261b101f6f2cc5923eb43e723f18b7565cd679a [Error: Invalid remote URI
	at qr (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:2:1694598)
	at hk.parseUri (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:24:529924)
	at c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:24:527677]
18:09:28.147 [error] Failed to parse remote URI http://127.0.0.1:12001/?token=68124e9a0261b101f6f2cc5923eb43e723f18b7565cd679a [Error: Invalid remote URI
	at qr (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:2:1694598)
	at hk.parseUri (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:24:529924)
	at c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:24:527677]
18:09:28.147 [error] Failed to parse remote URI http://127.0.0.1:12001/?token=68124e9a0261b101f6f2cc5923eb43e723f18b7565cd679a [Error: Invalid remote URI
	at qr (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:2:1694598)
	at hk.parseUri (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:24:529924)
	at c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:24:527677]
18:09:28.149 [error] Failed to parse remote URI http://0.0.0.0:19655/?token=04fd3976a56771b0888bba33fc7b7fb5c57f4a525cd1c7b1 [Error: Invalid remote URI
	at qr (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:2:1694598)
	at c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:17:126648
	at async Promise.all (index 1)
	at async c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:17:126492]
</code>
</summary>

<p>
</p>
</details>

**Comment by TobyWallage** [comment]
Where are the URIs stored locally?
I think it would be helpful for reproducing this but haven't been able to find anything

**Comment by DonJayamanne** [comment]
Sorry you are running into this and thanks for filing this issue.
The URI are stored in a protected storage.
We should be able to fix this error, however I'd like to understand why you are using this command.
This command isn't generally meant to be used, we added this as a fallback to clear some items.

Are you running into some issues that made you want to clear the list of URLs?

**Comment by TobyWallage** [comment]
Yes, when I connected to a jupyter notebook server, the extension was unable to find any kernels and for some reason I just assumed it was due to having too many stored previous servers.
However my experience seems very similar to issue #13699 

Upon changing to an older version of vscode (1.78.2) and an older version of the jupyter extension (v2023.3.1201040234)
as suggested in #13699 , the `Clear Jupyter Remote Server List` command works and my problem finding kernels like #13699 was also fixed.

I'm fine with this issue being closed if you think this is related to #13699

**Comment by fverd** [comment]
> Yes, when I connected to a jupyter notebook server, the extension was unable to find any kernels and for some reason I just assumed it was due to having too many stored previous servers. However my experience seems very similar to issue #13699
> 
> Upon changing to an older version of vscode (1.78.2) and an older version of the jupyter extension (v2023.3.1201040234) as suggested in #13699 , the `Clear Jupyter Remote Server List` command works and my problem finding kernels like #13699 was also fixed.
> 
> I'm fine with this issue being closed if you think this is related to #13699

Had the same problem, this worked for me. Thanks
