### ISSUE TITLE
Crash after last vscode or(and) extension update

### ISSUE THREAD

**Issue by reallaborious** [microsoft/vscode-jupyter#13728]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

The extension host crashes during the attempt to open any .ipynb after the updating of vscodium and (presumably) jupyter extension. Settings weren't changed, it just stopped working after the last update.

![Screenshot from 2023-06-19 18-50-00](https://github.com/microsoft/vscode-jupyter/assets/30012770/d3a6baa0-6bbc-4892-809d-a96690969fd7)

command (from logs):
/bin/python3 -m ipykernel_launcher --ip=127.0.0.1  ... 
works fine in bash.

OS: Ubuntu Ubuntu 20.04.6 LTS

### VS Code Version

1.79.2 release 23166

### Jupyter Extension Version

2023.3.100 (tried on 2023.2.100 as well)

### Jupyter logs

```shell
info 18:40:24.468: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1./bin/python3./bin/python3.-m#ipykernel_launcher (Python Path: , EnvType: Unknown, EnvName: '', Version: 3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0]) for '/home/vladimir/smth.ipynb' (disableUI=true)
warn 18:40:24.675: Failed to get activated env vars with python /bin/python3 in 204ms
info 18:40:24.692: Process Execution: > /bin/python3 -m pip list
> /bin/python3 -m pip list
warn 18:40:24.699: Failed to get activated env vars with python /bin/python3 in 210ms
info 18:40:24.718: Process Execution: > /bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> /bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
warn 18:40:24.846: Failed to get activated env vars with python /bin/python3 in 202ms
warn 18:40:24.848: Failed to get activated env vars with python /bin/python3 in 202ms
info 18:40:24.888: Process Execution: > /bin/python3 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9108 --control=9106 --hb=9105 --Session.signature_scheme="hmac-sha256" --Session.key=b"9216928d-cfd1-487e-80b8-251889328067" --shell=9107 --transport="tcp" --iopub=9109 --f=/home/vladimir/.local/share/jupyter/runtime/kernel-v2-2399829KRQO6xc7xDX5.json
> /bin/python3 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9108 --control=9106 --hb=9105 --Session.signature_scheme="hmac-sha256" --Session.key=b"9216928d-cfd1-487e-80b8-251889328067" --shell=9107 --transport="tcp" --iopub=9109 --f=/home/vladimir/.local/share/jupyter/runtime/kernel-v2-2399829KRQO6xc7xDX5.json
info 18:40:24.889: Process Execution: cwd: ~/ipython
cwd: ~/ipython
info 18:40:25.127: ipykernel version & path 6.7.0, ~/.local/lib/python3.8/site-packages/ipykernel/__init__.py for /bin/python3
```

### Coding Language and Runtime Version

python 3.8.10

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
Can you provide the `window` logs from the output panel?

**Comment by reallaborious** [comment]
this? (~/.config/VSCodium/logs/20230619T180531/window1)
[window1.zip](https://github.com/microsoft/vscode-jupyter/files/11796974/window1.zip)

**Comment by amunger** [comment]
Select window in the dropdown of the output panel:

<img width="645" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/2019016/5524a16f-dda7-479c-8a8b-73e04d32447e">

or use `Developer: toggle developer tools` and look for an error in the console.

Does the same crash happen in normal vscode?

**Comment by amunger** [comment]
It looks like the notebook editor wasn't registered for some reason, and the ipynb extension that contributes the editor is built-in to core. So this seems like a bug in codium.

```
2023-06-19 18:29:38.175 [error] Error: Cannot open resource with notebook editor type 'jupyter-notebook', please check if you have the right extension installed and enabled.
    at Go.setInput (vscode-file://vscode-app/snap/codium/327/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:2609:20621)
    at async e.EditorPanes.doSetInput (vscode-file://vscode-app/snap/codium/327/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:2292:32197)
    at async e.EditorPanes.doOpenEditor (vscode-file://vscode-app/snap/codium/327/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:2292:30116)
    at async e.EditorPanes.openEditor (vscode-file://vscode-app/snap/codium/327/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:2292:28864)
    at async vscode-file://vscode-app/snap/codium/327/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:2477:16809
    at async cn.doHandleCloseConfirmation (vscode-file://vscode-app/snap/codium/327/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:2477:21471)
    at async cn.handleCloseConfirmation (vscode-file://vscode-app/snap/codium/327/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:2477:20705)
    at async cn.doCloseEditorWithConfirmationHandling (vscode-file://vscode-app/snap/codium/327/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:2477:19254)
    at async e.CloseOneEditorAction.run (vscode-file://vscode-app/snap/codium/327/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:2305:100371)
    at async P.runAction (vscode-file://vscode-app/snap/codium/327/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:93:17636)
    at async P.run (vscode-file://vscode-app/snap/codium/327/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:93:17536)
2023-06-19 18:29:51.296 [error] Extension host (LocalProcess) terminated unexpectedly. No extensions were activated.
```

closing as external
