### ISSUE TITLE
Crash after warning: "It seems that frozen modules are being used, which may make the debugger miss breakpoints"

### ISSUE THREAD

**Issue by MarcBresson** [microsoft/vscode-jupyter#13721]
### Applies To

- [X] Notebooks (.ipynb files)
- [x] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Multiple times today I had the same kernel crash in jupyter. It happens after ffmpeg running with a subprocess, but it does not happen every single time.

On the log I put down below, there are 2 crashes, but only the second one has been displayed under a cell:

```
Cannot execute code, session has been disposed. Please try restarting the Kernel.

The Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. View Jupyter [log](command:jupyter.viewOutput) for further details.
```

I looked into vs code to provide the suggested argument, but there is no settings to do such a thing.

### VS Code Version

Version: 1.79.1 (system setup) Commit: 4cb974a7aed77a74c7813bdccd99ee0d04901215 Date: 2023-06-12T16:14:05.102Z Electron: 22.5.7 Chromium: 108.0.5359.215 Node.js: 16.17.1 V8: 10.8.168.25-electron.0 OS: Windows_NT x64 10.0.22631

### Jupyter Extension Version

v2023.5.1001582324

### Jupyter logs

```shell
17:47:23.461 [info] Kernel acknowledged execution of cell 1 @ 1687016843458
17:50:12.458 [info] End cell 1 execution @ 1687017012456, started @ 1687016843458, elapsed time = 168.998s
17:50:37.636 [info] Handle Execution of Cells 2 for ~\Documents\JustDance\JustDance assembler\video_building.ipynb
17:50:37.645 [info] Kernel acknowledged execution of cell 2 @ 1687017037641
17:50:54.062 [info] End cell 2 execution @ 1687017054059, started @ 1687017037641, elapsed time = 16.418s
17:52:03.222 [info] Handle Execution of Cells 2 for ~\Documents\JustDance\JustDance assembler\video_building.ipynb
17:52:03.239 [info] Kernel acknowledged execution of cell 2 @ 1687017123231
17:52:03.383 [error] Disposing session as kernel process died ExitCode: 3221225477, Reason: 0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.

17:52:03.383 [info] Dispose Kernel process 1388.
17:52:03.384 [error] Raw kernel process exited code: 3221225477
17:52:03.389 [error] Error in waiting for cell to complete [Error: Canceled future for execute_request message before replies were done
	at t.KernelShellFutureHandler.dispose (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:2:32375)
	at c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:2:51427
	at Map.forEach (<anonymous>)
	at y._clearKernelState (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:2:51412)
	at y.dispose (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:2:44894)
	at c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:24:112498
	at ne (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:2:1586779)
	at cy.dispose (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:24:112474)
	at uy.dispose (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:24:119757)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)]
17:52:03.391 [warn] Cell completed with errors {
  message: 'Canceled future for execute_request message before replies were done'
}
17:52:03.393 [info] End cell 2 execution @ 1687017123393, started @ 1687017123231, elapsed time = 0.162s
17:52:03.394 [warn] Cancel all remaining cells due to cancellation or failure in execution
17:52:03.491 [info] End cell 2 execution @ undefined, started @ undefined, elapsed time = 0s
17:52:28.048 [info] Handle Execution of Cells 3 for ~\Documents\JustDance\JustDance assembler\video_building.ipynb
17:52:03.383 [error] Disposing session as kernel process died ExitCode: 3221225477, Reason: 0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.

17:52:03.383 [info] Dispose Kernel process 1388.
17:52:03.384 [error] Raw kernel process exited code: 3221225477
17:52:03.389 [error] Error in waiting for cell to complete [Error: Canceled future for execute_request message before replies were done
	at t.KernelShellFutureHandler.dispose (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:2:32375)
	at c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:2:51427
	at Map.forEach (<anonymous>)
	at y._clearKernelState (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:2:51412)
	at y.dispose (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:2:44894)
	at c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:24:112498
	at ne (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:2:1586779)
	at cy.dispose (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:24:112474)
	at uy.dispose (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1001582324-win32-x64\out\extension.node.js:24:119757)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)]
17:52:03.391 [warn] Cell completed with errors {
  message: 'Canceled future for execute_request message before replies were done'
}
17:52:03.393 [info] End cell 2 execution @ 1687017123393, started @ 1687017123231, elapsed time = 0.162s
17:52:03.394 [warn] Cancel all remaining cells due to cancellation or failure in execution
```

### Coding Language and Runtime Version

Python 3.11.3

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Thanks for filing this, and I'm very sorry for not getting to this sooner, 
Are you still running into this issue?
Please can you try to debug a simple hello world such as a for loop without importing any python modules/packages.

**Comment by MarcBresson** [comment]
Hello, it works well when I do that. It seems like the issue comes from cv2.

My (very) temp solution was to call a new python kernel through bash so that the crash doesn't impact the main python kernel.

After further inspection, it also happens when I run the script outside of jupyter, it is just that the kernel crashes silently.
