### ISSUE TITLE
Selecting a kernel from remote server searches for kernels "forever", Failed to parse remote URI

### ISSUE THREAD

**Issue by janpetrov** [microsoft/vscode-jupyter#13758]
## Environment data

-   VS Code version: Version: 1.79.2 (Universal)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5d
-   Jupyter Extension version (available under the Extensions sidebar): v2023.5.1101742258
-   Python Extension version (available under the Extensions sidebar): v2023.10.1
-   OS (Windows | Mac | Linux distro) and version: mac Ventura 13.3
-   Python and/or Anaconda version: 3.9.16
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: remote

## Expected behaviour

When selecting a kernel from an existing jupyter server a list of running kernels is presented so that the user can pick one.

## Actual behaviour

No list of kernels is presented but the blue progress bar (perhaps indicating ongoing search for kernels) runs forever without producing any result.

## Steps to reproduce

Command-Shift-P -> Select Kernel -> Existing Jupyter Server -> http://toyen.sklik-vyzkum.ko1.os.scif.cz:10891/lab?token=mytoken -> some name of the kernel -> blue progress bar running indefinitely

See please the log below. Please note that there are two "failed to parse" messages: one regarding the currently entered server, another regarding a server that I entered some time before. The addresses of servers are given exactly as printed out by jupyter lab. VS Code is apparently able to communicate with the server as it returns an error message if no token or a wrong token is given.

## Log (Command-Shift-P -> Jupyter: Show output)

18:16:33.350 [error] Failed to parse remote URI http://toyen.sklik-vyzkum.ko1.os.scif.cz:10891/lab?token=mytoken Error: Invalid remote URI
    at qr (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.5.1101742258-linux-x64/out/extension.node.js:2:1694598)
    at hk.parseUri (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.5.1101742258-linux-x64/out/extension.node.js:24:530090)
    at ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.5.1101742258-linux-x64/out/extension.node.js:24:528878
    at b.invoke (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at deliver (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
    at n.fire (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
    at f._fireDidAccept (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:102:114142)
    at E.$onDidAccept (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:102:112352)
    at s.N (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:112:11717)
    at s.M (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:112:11435)
    at s.H (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:112:10516)
    at s.G (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:112:9494)
    at ~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:112:8282
    at b.invoke (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at deliver (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
    at n.fire (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
    at p.fire (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:73:14783)
    at ~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:128:32461
    at b.invoke (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at deliver (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
    at n.fire (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
    at p.fire (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:73:14783)
    at D.E (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:73:18830)
    at ~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:73:16818
    at b.invoke (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at deliver (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
    at n.fire (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
    at h.acceptChunk (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:73:12514)
    at ~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:73:11801
    at b.invoke (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at deliver (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
    at n.fire (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
    at E.u (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:128:20017)

18:16:46.410 [error] Failed to setup finder for Select Kernel Error: 'Failed to parse remote URI http://jp2.sklik-vyzkum.ko1.os.scif.cz:10791?token=xyz
    at qr (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.5.1101742258-linux-x64/out/extension.node.js:2:1694682)
    at ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.5.1101742258-linux-x64/out/extension.node.js:17:126648
    at async Promise.all (index 0)
    at ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.5.1101742258-linux-x64/out/extension.node.js:17:126492

**Comment by DonJayamanne** [comment]
Thank you for filling this issue and I’m sorry you are running into this problem

Looks like a duplicate of #13602 
Please open the command palette then select the command 
‘ Jupyter: Clear Jupyter Remote Server List’
 once since please re-enter the url and try again

this should work

**Comment by janpetrov** [comment]
I am sorry, but this is not a duplicate. I cleared the remote server list (even before posting the issue), and it does not alleviate the error. (Please note that I also know about another issue where clearing server list failed, but this is not my case.) Moreover 13602 is related to connecting to Codespace server and some remapping of ports (not this case). There seems to be some mistake regarding parsing URIs
Failed to parse remote URI http://toyen.sklik-vyzkum.ko1.os.scif.cz:10891/lab?token=mytoken Error: Invalid remote URI
This is precisely the URI I wish to connect to, so it is difficult to see how clearing remote server list could help.

Jupyter output after clearing server list (please note that Jupyter: Clear Remote Server List does not output anything in Jupyter output)

01:28:18.370 [error] Failed to parse remote URI http://toyen.sklik-vyzkum.ko1.os.scif.cz:10891/lab?token=mytoken Error: Invalid remote URI
    at qr (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.5.1101742258-linux-x64/out/extension.node.js:2:1694598)
    at hk.parseUri (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.5.1101742258-linux-x64/out/extension.node.js:24:530090)
    at ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.5.1101742258-linux-x64/out/extension.node.js:24:528878
    at b.invoke (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at deliver (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
    at n.fire (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
    at f._fireDidAccept (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:102:114142)
    at E.$onDidAccept (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:102:112352)
    at s.N (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:112:11717)
    at s.M (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:112:11435)
    at s.H (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:112:10516)
    at s.G (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:112:9494)
    at ~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:112:8282
    at b.invoke (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at deliver (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
    at n.fire (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
    at p.fire (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:73:14783)
    at ~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:128:32461
    at b.invoke (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at deliver (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
    at n.fire (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
    at p.fire (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:73:14783)
    at D.E (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:73:18830)
    at ~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:73:18009
    at b.invoke (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at deliver (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
    at n.fire (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
    at h.acceptChunk (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:73:12514)
    at ~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:73:11801
    at b.invoke (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at deliver (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
    at n.fire (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
    at E.u (~/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/out/vs/workbench/api/node/extensionHostProcess.js:128:20017)
01:28:39.181 [error] Failed to setup finder for Select Kernel Error: 'Failed to parse remote URI http://jp2.sklik-vyzkum.ko1.os.scif.cz:10791?token=xyz
    at qr (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.5.1101742258-linux-x64/out/extension.node.js:2:1694682)
    at ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.5.1101742258-linux-x64/out/extension.node.js:17:126648
    at async Promise.all (index 0)
    at ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.5.1101742258-linux-x64/out/extension.node.js:17:126492

**Comment by janpetrov** [comment]
Please note that the remote URI which VS Code failed to parse could be open in a web browser (and the jupyter session there was flawless).

**Comment by DonJayamanne** [comment]
I’m sorry you’re still running into this issue.

Please  Could you install vscode insiders and the latest pre-release version of the Jupyter extension 2023.6.100* and let me know if the problem still exists in that version, 

if not then we know it’s fixed in the main branch, else it’sa completely new issue and  would require more logging and investigation

**Comment by janpetrov** [comment]
Thank you for your help and quick reopening of the issue. The bug is fixed in the main branch. When connecting to a kernel from vscode insiders as suggested, all is fine. I have tested this multiple times, with both jupyter lab and jupyter notebook URI. Connecting also works (please excuse I have omitted this potentially important source of information) when VS Code is SSH connected to a host or attached to a running container.

**Comment by DonJayamanne** [comment]
Thank you very much for texting this again and getting back

**Comment by Dgelemi** [comment]
Adding to this, I had the same issue on VScode main one after latest update; installing insider version solved the problem.

**Comment by mogg3** [comment]
I also have this issue. It works when i use the insider version, but when will this be fixed in the main one? The insider version's Side by Side editing is quite a pain to use at the moment...

**Comment by DonJayamanne** [comment]
The latest release (with fixes from insiders version) will be released some time this week

**Comment by Dgelemi** [comment]
Thanks. For info the version 1.8.0 is not working for me

**Comment by Dgelemi** [comment]
new update today and issue fixed for me; thank you.
