### ISSUE TITLE
Export to HTML does nothing

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#13775]
Testing #13768

1. Click export to HTML
2. Immediately get notification that export happened, click yes to open created file
3. :bug: nothing happens, no file created in workspace, no errors

**Comment by DonJayamanne** [comment]
@joyceerhl  can you try this with the stable version of the extension as well

I think you’re running into an existing issue
Please confirm you are using the web for this test

**Comment by joyceerhl** [comment]
Confirming I used insiders.vscode.dev + a GitHub repo when I reproed this

**Comment by joyceerhl** [comment]
To be clear, I'm using the Jupyter pre-release and a localhost Jupyter server with a GitHub repository in insiders.vscode.dev

If I access the same localhost url printed when I started the server, I can create a notebook and export to HTML without issue via the Jupyter Notebook browser UI (not in insiders.vscode.dev)

There are several issues/questions for me:
1. Export to HTML does not work at all
2. Why do I still get a notification asking whether I want to open the exported file if no export was created? I should have seen an error message

**Comment by joyceerhl** [comment]
FWIW I see this when exporting a notebook from insiders.vscode.dev, but exporting a notebook from the Jupyter Notebook works fine

```
[E 09:11:38.592 NotebookApp] Uncaught exception in zmqstream callback
    Traceback (most recent call last):
      File "C:\Users\huer\Source\Repos\vscode-pull-request-github\.venv\Lib\site-packages\zmq\eventloop\zmqstream.py", line 634, in _handle_events
        self._handle_recv()
      File "C:\Users\huer\Source\Repos\vscode-pull-request-github\.venv\Lib\site-packages\zmq\eventloop\zmqstream.py", line 663, in _handle_recv
        self._run_callback(callback, msg)
      File "C:\Users\huer\Source\Repos\vscode-pull-request-github\.venv\Lib\site-packages\zmq\eventloop\zmqstream.py", line 584, in _run_callback
        f = callback(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\huer\Source\Repos\vscode-pull-request-github\.venv\Lib\site-packages\zmq\eventloop\zmqstream.py", line 308, in stream_callback
        return callback(self, msg)
               ^^^^^^^^^^^^^^^^^^^
      File "C:\Users\huer\Source\Repos\vscode-pull-request-github\.venv\Lib\site-packages\notebook\services\kernels\handlers.py", line 572, in _on_zmq_reply
        super()._on_zmq_reply(stream, msg)
      File "C:\Users\huer\Source\Repos\vscode-pull-request-github\.venv\Lib\site-packages\notebook\base\zmqhandlers.py", line 256, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "C:\Users\huer\Source\Repos\vscode-pull-request-github\.venv\Lib\site-packages\tornado\websocket.py", line 334, in write_message
        return self.ws_connection.write_message(message, binary=binary)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\huer\Source\Repos\vscode-pull-request-github\.venv\Lib\site-packages\tornado\websocket.py", line 1081, in write_message
        fut = self._write_frame(True, opcode, message, flags=flags)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\huer\Source\Repos\vscode-pull-request-github\.venv\Lib\site-packages\tornado\websocket.py", line 1056, in _write_frame
        return self.stream.write(frame)
               ^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\huer\Source\Repos\vscode-pull-request-github\.venv\Lib\site-packages\tornado\iostream.py", line 539, in write  
        self._handle_write()
      File "C:\Users\huer\Source\Repos\vscode-pull-request-github\.venv\Lib\site-packages\tornado\iostream.py", line 965, in _handle_write
        self._write_buffer.advance(num_bytes)
      File "C:\Users\huer\Source\Repos\vscode-pull-request-github\.venv\Lib\site-packages\tornado\iostream.py", line 182, in advance
        assert 0 < size <= self._size
               ^^^^^^^^^^^^^^^^^^^^^^
    AssertionError
[E 09:11:38.611 NotebookApp] Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x00000280B1B002C0>)
    Traceback (most recent call last):
      File "C:\Users\huer\Source\Repos\vscode-pull-request-github\.venv\Lib\site-packages\tornado\ioloop.py", line 738, in _run_callback
        ret = callback()
              ^^^^^^^^^^
      File "C:\Users\huer\Source\Repos\vscode-pull-request-github\.venv\Lib\site-packages\zmq\eventloop\zmqstream.py", line 718, in <lambda>
        self.io_loop.add_callback(lambda: self._handle_events(self.socket, 0))
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\huer\Source\Repos\vscode-pull-request-github\.venv\Lib\site-packages\zmq\eventloop\zmqstream.py", line 634, in _handle_events
        self._handle_recv()
      File "C:\Users\huer\Source\Repos\vscode-pull-request-github\.venv\Lib\site-packages\zmq\eventloop\zmqstream.py", line 663, in _handle_recv
        self._run_callback(callback, msg)
      File "C:\Users\huer\Source\Repos\vscode-pull-request-github\.venv\Lib\site-packages\zmq\eventloop\zmqstream.py", line 584, in _run_callback
        f = callback(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\huer\Source\Repos\vscode-pull-request-github\.venv\Lib\site-packages\zmq\eventloop\zmqstream.py", line 308, in stream_callback
        return callback(self, msg)
               ^^^^^^^^^^^^^^^^^^^
      File "C:\Users\huer\Source\Repos\vscode-pull-request-github\.venv\Lib\site-packages\notebook\services\kernels\handlers.py", line 572, in _on_zmq_reply
        super()._on_zmq_reply(stream, msg)
      File "C:\Users\huer\Source\Repos\vscode-pull-request-github\.venv\Lib\site-packages\notebook\base\zmqhandlers.py", line 256, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "C:\Users\huer\Source\Repos\vscode-pull-request-github\.venv\Lib\site-packages\tornado\websocket.py", line 334, in write_message
        return self.ws_connection.write_message(message, binary=binary)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\huer\Source\Repos\vscode-pull-request-github\.venv\Lib\site-packages\tornado\websocket.py", line 1081, in write_message
        fut = self._write_frame(True, opcode, message, flags=flags)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\huer\Source\Repos\vscode-pull-request-github\.venv\Lib\site-packages\tornado\websocket.py", line 1056, in _write_frame
        return self.stream.write(frame)
               ^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\huer\Source\Repos\vscode-pull-request-github\.venv\Lib\site-packages\tornado\iostream.py", line 539, in write  
        self._handle_write()
      File "C:\Users\huer\Source\Repos\vscode-pull-request-github\.venv\Lib\site-packages\tornado\iostream.py", line 965, in _handle_write
        self._write_buffer.advance(num_bytes)
      File "C:\Users\huer\Source\Repos\vscode-pull-request-github\.venv\Lib\site-packages\tornado\iostream.py", line 182, in advance
        assert 0 < size <= self._size
               ^^^^^^^^^^^^^^^^^^^^^^
    AssertionError
[I 09:11:38.602 NotebookApp] Restoring connection for f98af434-2dc7-4b46-b621-8b682577f682:5a5dc456-3100-41d2-9b5e-eca9d4d47f11
[I 09:11:38.994 NotebookApp] Replaying 1 buffered messages
[W 09:11:39.220 NotebookApp] 405 OPTIONS /nbextensions/%5C%5Cjupyter-js-widgets%5C%5Cextension.js (::1) 5.000000ms referer=None
[W 09:11:41.458 NotebookApp] 404 GET /nbextensions/%5C%5Cjupyter-js-widgets%5C%5Cextension.js (::1) 2231.880000ms referer=None
```

**Comment by joyceerhl** [comment]
If I try this with stable Jupyter (v2023.5.1101742258) I cannot even connect to a Jupyter server. I paste in the localhost url with token in the kernel picker and then I see this in the server logs

```
[W 09:24:28.585 NotebookApp] Forbidden
[W 09:24:28.585 NotebookApp] 403 GET /api/kernelspecs?1687883068539 (::1) 0.000000ms referer=None
[W 09:24:28.606 NotebookApp] Forbidden
[W 09:24:28.607 NotebookApp] 403 GET /api/kernelspecs?1687883068542 (::1) 2.780000ms referer=None
[W 09:24:28.609 NotebookApp] Forbidden
[W 09:24:28.609 NotebookApp] 403 GET /api/kernels?1687883068540 (::1) 4.090000ms referer=None
[W 09:24:28.611 NotebookApp] Forbidden
[W 09:24:28.612 NotebookApp] 403 GET /api/kernels?1687883068543 (::1) 1.640000ms referer=None
[W 09:24:28.632 NotebookApp] Forbidden
[W 09:24:28.633 NotebookApp] 403 GET /api/kernels?1687883068547 (::1) 4.990000ms referer=None
[W 09:24:28.638 NotebookApp] Forbidden
[W 09:24:28.639 NotebookApp] 403 GET /api/sessions?1687883068548 (::1) 9.990000ms referer=None
[W 09:24:28.641 NotebookApp] Forbidden
[W 09:24:28.643 NotebookApp] 403 GET /api/kernels?1687883068549 (::1) 13.990000ms referer=None
[W 09:24:28.647 NotebookApp] Forbidden
[W 09:24:28.649 NotebookApp] 403 GET /api/sessions?1687883068549 (::1) 3.030000ms referer=None
[W 09:24:28.673 NotebookApp] Forbidden
[W 09:24:28.674 NotebookApp] 403 GET /api/kernelspecs?1687883068617 (::1) 2.570000ms referer=None
[W 09:24:28.683 NotebookApp] Forbidden
[W 09:24:28.684 NotebookApp] 403 GET /api/kernelspecs?1687883068603 (::1) 2.000000ms referer=None
```
