### ISSUE TITLE
Kernel picker spins forever detecting kernels 

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#13794]
Testing microsoft/vscode#13768

1. Connect to remote Jupyter server running on localhost in a notebook in insiders.vscode.dev
2. Kill the server
3. Reload window 
4. :bug: Detecting Kernels... spins forever in kernel status 

<img width="169" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/30305945/2ce12d30-6585-49ae-bb37-4778f44faff2">

**Comment by DonJayamanne** [comment]
@joyceerhl please can you share the logs from the Jupyter extension.

**Comment by seldomworks** [comment]
I have the same issue.   Logs below. Note that I do get past the password prompt and get a prompt to change the server name. Password is correct but I do get the warning regardless

`11:01:05.242 [warn] Password for http://localhost:8888/ was invalid.
11:01:09.110 [error] Failed to setup finder for Select Kernel Error: 'Failed to parse remote URI  http://san-p174-a23-16-04:8888
    at qr (c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1101742258-win32-x64\out\extension.node.js:2:1694682)
    at c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1101742258-win32-x64\out\extension.node.js:17:126648
    at async Promise.all (index 4)
    at c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.5.1101742258-win32-x64\out\extension.node.js:17:126492`

**Comment by DonJayamanne** [comment]
@seldomworks  please could you create a separate issue

**Comment by seldomworks** [comment]
> @seldomworks sorry you are running into this, please could you create a separate issue, I believe the reasons are unrelated

Sure. Filed https://github.com/microsoft/vscode-jupyter/issues/13827

**Comment by joyceerhl** [comment]
```
Visual Studio Code - Insiders (1.80.0-insider, undefined, vscode.dev)
Jupyter Extension Version: 2023.5.1101742258.
Python Extension Version: 2023.11.11811010.
Opened workspace folder.
09:04:28.290 [error] Python extension is not exporting the jupyter API
09:04:28.389 [warn] Failed to get active interpreter from Python for workspace /microsoft/vscode TypeError: Cannot read properties of undefined (reading 'getActiveEnvironmentPath')
09:04:28.447 [error] Failed to parse remote URI local TypeError: Failed to construct 'URL': Invalid URL
09:04:32.096 [error] Unable to determine the caller of the extension API for trace stack. Error: 
    at u.determineExtensionFromCallStack (https://ms-toolsai.vscode-unpkg.net/ms-toolsai/jupyter/2023.5.1101742258/extension/out/extension.web.bundle.js#vscode-extension:11:327826)
    at m (https://ms-toolsai.vscode-unpkg.net/ms-toolsai/jupyter/2023.5.1101742258/extension/out/extension.web.bundle.js#vscode-extension:26:113813)
    at Object.registerRemoteServerProvider (https://ms-toolsai.vscode-unpkg.net/ms-toolsai/jupyter/2023.5.1101742258/extension/out/extension.web.bundle.js#vscode-extension:26:114412)
    at Object.eval (https://github.vscode-unpkg.net/GitHub/codespaces/1.14.8/node_modules/js-sha256/src/sha256.js:1:1)
    at Generator.next (<anonymous>)
    at fulfilled (https://github.vscode-unpkg.net/GitHub/codespaces/1.14.8/node_modules/js-sha256/src/sha256.js:1:1)
09:04:32.103 [error] Unable to determine the caller of the extension API for trace stack. Error: 
    at u.determineExtensionFromCallStack (https://ms-toolsai.vscode-unpkg.net/ms-toolsai/jupyter/2023.5.1101742258/extension/out/extension.web.bundle.js#vscode-extension:11:327826)
    at w.createProvider (https://ms-toolsai.vscode-unpkg.net/ms-toolsai/jupyter/2023.5.1101742258/extension/out/extension.web.bundle.js#vscode-extension:4:901889)
    at w.registerProvider (https://ms-toolsai.vscode-unpkg.net/ms-toolsai/jupyter/2023.5.1101742258/extension/out/extension.web.bundle.js#vscode-extension:4:900553)
    at Object.registerRemoteServerProvider (https://ms-toolsai.vscode-unpkg.net/ms-toolsai/jupyter/2023.5.1101742258/extension/out/extension.web.bundle.js#vscode-extension:26:114489)
    at Object.eval (https://github.vscode-unpkg.net/GitHub/codespaces/1.14.8/node_modules/js-sha256/src/sha256.js:1:1)
    at Generator.next (<anonymous>)
    at fulfilled (https://github.vscode-unpkg.net/GitHub/codespaces/1.14.8/node_modules/js-sha256/src/sha256.js:1:1)

```

**Comment by NightMachinery** [comment]
https://github.com/microsoft/vscode/issues/186903

**Comment by DonJayamanne** [comment]
@joyceerhl please can you test this with the latest pre-release version of =jupyter extension and latest vscode insiders and let me know if this still reopros.

**Comment by joyceerhl** [comment]
No longer repros
