### ISSUE TITLE
Tensorboard keep hanging in remote-ssh and remote-container

### ISSUE THREAD

**Issue by YoungJaeBae** [microsoft/vscode-jupyter#13902]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

Expected: 
Opening Integrated TensorBoard Session

Actual:
Trying to open integrated tensorboard session. 
Extension keeps hanging with message box "Starting TensorBoard session...". 
Eventually output error message "We failed to start a TensorBoard session due to the following error: Timed out after 60 seconds waiting for TensorBoard to launch."

## Steps to reproduce:

extension versions
- Remote-SSH/: 0.102.0
- Dev Containers: 0.299.0

- System info
-- local
CPUs	Apple M1 (8 x 24)
GPU Status	2d_canvas: enabled canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled metal: disabled_off multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok video_decode: enabled video_encode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled webgpu: enabled
Load (avg)	2, 2, 1
Memory (System)	8.00GB (0.70GB free)
Process Argv	--crash-reporter-id 45125d79-806f-49e7-90a0-109e870d561a
Screen Reader	no
VM	0%
-- remote
Remote	Container pytorch/pytorch:latest
OS	Linux x64 5.11.0-27-generic
CPUs	Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 x 4561)
Memory (System)	46.96GB (39.09GB free)
VM	0%

Versions of related python packages
torch                   1.13.1
torch-tb-profiler       0.4.1
tensorboard             2.6.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1

1. Launch TensorBoard Session

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.8
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```

2023-07-12 06:01:21.702 [info] > conda run -n base --no-capture-output python ~/.vscode-server/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py -c "import tensorboard; print(tensorboard.__version__)"
2023-07-12 06:01:26.206 [info] > conda run -n base --no-capture-output python ~/.vscode-server/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2023.12.0/pythonFiles/tensorboard_launcher.py ./log
2023-07-12 06:01:26.721 [error] Traceback (most recent call last):
  File "/root/.vscode-server/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py", line 26, in <module>
    runpy.run_path(module, run_name="__main__")
  File "/opt/conda/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/opt/conda/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code

2023-07-12 06:01:26.721 [error]     exec(code, run_globals)
  File "/root/.vscode-server/extensions/ms-python.python-2023.12.0/pythonFiles/tensorboard_launcher.py", line 36, in <module>
    main(logdir)
  File "/root/.vscode-server/extensions/ms-python.python-2023.12.0/pythonFiles/tensorboard_launcher.py", line 17, in main
    tb = program.TensorBoard()
  File "/opt/conda/lib/python3.10/site-packages/tensorboard/lazy.py", line 65, in __getattr__
    return getattr(load_once(self), attr_name)
  File "/opt/conda/lib/python3.10/site-packages/tensorboard/lazy.py", line 97, in wrapper
    cache[arg] = f(arg)
  File "/opt/conda/lib/python3.10/site-packages/tensorboard/lazy.py", line 50, in load_once
    module = load_fn()
  File "/opt/conda/lib/python3.10/site-packages/tensorboard/__init__.py", line 99, in program
    return importlib.import_module("tensorboard.program")
  File "/opt/conda/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import

2023-07-12 06:01:26.721 [error]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

2023-07-12 06:01:26.721 [error]   File "/opt/conda/lib/python3.10/site-packages/tensorboard/program.py", line 52, in <module>
    from tensorboard.backend import application
  File "/opt/conda/lib/python3.10/site-packages/tensorboard/backend/application.py", line 34, in <module>

2023-07-12 06:01:26.721 [error]     from tensorboard import plugin_util
  File "/opt/conda/lib/python3.10/site-packages/tensorboard/plugin_util.py", line 20, in <module>
    from tensorboard._vendor.bleach.sanitizer import Cleaner
  File "/opt/conda/lib/python3.10/site-packages/tensorboard/_vendor/bleach/__init__.py", line 5, in <module>

2023-07-12 06:01:26.721 [error]     from tensorboard._vendor.bleach.linkifier import (
  File "/opt/conda/lib/python3.10/site-packages/tensorboard/_vendor/bleach/linkifier.py", line 4, in <module>
    from tensorboard._vendor import html5lib
  File "/opt/conda/lib/python3.10/site-packages/tensorboard/_vendor/html5lib/__init__.py", line 25, in <module>

2023-07-12 06:01:26.721 [error]     from .html5parser import HTMLParser, parse, parseFragment
  File "/opt/conda/lib/python3.10/site-packages/tensorboard/_vendor/html5lib/html5parser.py", line 8, in <module>
    from . import _tokenizer
  File "/opt/conda/lib/python3.10/site-packages/tensorboard/_vendor/html5lib/_tokenizer.py", line 16, in <module>

2023-07-12 06:01:26.721 [error]     from ._trie import Trie
  File "/opt/conda/lib/python3.10/site-packages/tensorboard/_vendor/html5lib/_trie/__init__.py", line 3, in <module>
    from .py import Trie as PyTrie
  File "/opt/conda/lib/python3.10/site-packages/tensorboard/_vendor/html5lib/_trie/py.py", line 6, in <module>

2023-07-12 06:01:26.721 [error]     from ._base import Trie as ABCTrie
  File "/opt/conda/lib/python3.10/site-packages/tensorboard/_vendor/html5lib/_trie/_base.py", line 3, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/opt/conda/lib/python3.10/collections/__init__.py)

2023-07-12 06:01:26.736 [error] ERROR conda.cli.main_run:execute(47): `conda run python /root/.vscode-server/extensions/ms-python.python-2023.12.0/pythonFiles/get_output_via_markers.py /root/.vscode-server/extensions/ms-python.python-2023.12.0/pythonFiles/tensorboard_launcher.py /workspace/log` failed. (See above for error)

```
</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

formatting
• provider: "black"

```

</p>
</details>

Extension version: 2023.12.0
VS Code version: Code 1.80.0 (Universal) (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T13:39:33.766Z)
OS version: Darwin arm64 22.5.0
Modes:
Remote OS version: Linux x64 5.11.0-27-generic

**Comment by DonJayamanne** [comment]
> I always install the tensorboard package with interactive menu of vscode. Is there any chance that the default channel of tensorboard package causing problem?

I'm sorry but I do not know what could be causing this issue.
Given the fact that this is installed by the end user, and not by the Jupyter extension I'm closing this issue as one related to `user setup`

I'm glad you managed to solve this your self.
