### ISSUE TITLE
Can't export a pdf. The html export works fine.

### ISSUE THREAD

**Issue by Axze-rgb** [microsoft/vscode-jupyter#13912]
## Environment data

-   VS Code version: Version: 1.80.1

-   Jupyter Extension version (available under the Extensions sidebar): 
v2023.6.1101941928
-   Python Extension version (available under the Extensions sidebar): 
 2023.12.0.
-   OS (Windows | Mac | Linux distro) and version: 
Ubuntu 20.04
-   Python and/or Anaconda version: 
mamba 1.4.2
conda 23.1.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): 
conda
-   Jupyter server running: 
Local

## Expected behaviour

producing a pdf of the notebook
## Actual behaviour

failure, here is the debug console

```
Visual Studio Code (1.80.1, undefined, desktop)
Jupyter Extension Version: 2023.6.1101941928.
Python Extension Version: 2023.12.0.
Platform: linux (x64).
No workspace folder opened.
12:34:32.593 [info] User belongs to experiment group 'FastKernelPicker'
12:34:32.864 [info] Start refreshing Kernel Picker (1689417272864)
12:34:32.868 [info] Using Pylance
12:34:32.906 [info] End refreshing Kernel Picker (1689417272864)
12:34:32.999 [info] Start refreshing Interpreter Kernel Picker
12:34:32.999 [info] Start refreshing Kernel Picker (1689417272999)
12:34:34.792 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd003807dcc214718de3fef1abbc62da4d562d2ddd650787426faadb17d03c3a4b6.~/anaconda3/python.~/anaconda3/python.-m#ipykernel_launcher  (Python Path: ~/anaconda3/bin/python, Conda, 3.10.9) for '~/Data/MAexperiment/test.ipynb' (disableUI=true)
12:34:37.072 [info] End refreshing Kernel Picker (1689417272999)
12:34:37.160 [info] Process Execution: ~/anaconda3/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
12:34:37.184 [info] Process Execution: ~/anaconda3/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"15a163ba-4fdd-4bc7-97cf-615e13e5fd82" --shell=9002 --transport="tcp" --iopub=9004 --f=~/.local/share/jupyter/runtime/kernel-v2-21678gETypl8j7njb.json
    > cwd: ~/Data/MAexperiment
12:34:37.267 [info] Process Execution: ~/mambaforge/envs/jupyter/bin/python -m pip list
12:34:37.289 [info] Process Execution: ~/anaconda3/bin/python -m pip list
12:34:37.461 [info] ipykernel version & path 6.19.2, ~/anaconda3/lib/python3.10/site-packages/ipykernel/__init__.py for ~/anaconda3/bin/python
12:34:38.218 [info] Started Kernel anaconda3 (Python 3.10.9) (pid: 21864)
12:34:38.218 [info] Started new session 77784324-08d0-4543-9a87-a96afe5362c4
12:34:38.334 [info] Process Execution: ~/anaconda3/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/pythonFiles/printJupyterDataDir.py
12:34:44.507 [info] Process Execution: ~/anaconda3/bin/python -c "import nbconvert;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
12:34:45.204 [info] Process Execution: ~/anaconda3/bin/python -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
12:34:45.252 [info] Process Execution: ~/anaconda3/bin/python -m jupyter nbconvert /tmp/729403b1-bd85-41b1-96df-2cdb432c7f07/test.ipynb --to pdf --output tmp-21678JukQg5nhYv2s.pdf --output-dir /tmp --debug
12:34:47.166 [error] Export failed Error: [NbConvertApp] Searching ['~/anaconda3/etc/jupyter', '~/.jupyter', '~/.local/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[NbConvertApp] Looking for jupyter_config in /etc/jupyter
[NbConvertApp] Looking for jupyter_config in /usr/local/etc/jupyter
[NbConvertApp] Looking for jupyter_config in ~/.local/etc/jupyter
[NbConvertApp] Looking for jupyter_config in ~/.jupyter
[NbConvertApp] Looking for jupyter_config in ~/anaconda3/etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /usr/local/etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in ~/.local/etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in ~/.jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in ~/anaconda3/etc/jupyter
[NbConvertApp] Converting notebook /tmp/729403b1-bd85-41b1-96df-2cdb432c7f07/test.ipynb to pdf
[NbConvertApp] Notebook name is 'tmp-21678JukQg5nhYv2s'
[NbConvertApp] Template paths:
	~/anaconda3/share/jupyter/nbconvert/templates/latex
	~/anaconda3/share/jupyter/nbconvert/templates/base
	~/anaconda3/share/jupyter
	~/anaconda3/share/jupyter/nbconvert/templates
	~/anaconda3/share/jupyter/nbconvert/templates/compatibility
	~/.local/share/jupyter
	~/.local/share/jupyter/nbconvert/templates
	~/.local/share/jupyter/nbconvert/templates/compatibility
	/usr/local/share/jupyter
	/usr/local/share/jupyter/nbconvert/templates
	/usr/local/share/jupyter/nbconvert/templates/compatibility
	/usr/share/jupyter
	/usr/share/jupyter/nbconvert/templates
	/usr/share/jupyter/nbconvert/templates/compatibility
	~/anaconda3/share/jupyter/nbconvert/templates
[NbConvertApp] Applying preprocessor: TagRemovePreprocessor
[NbConvertApp] Applying preprocessor: RegexRemovePreprocessor
[NbConvertApp] Applying preprocessor: coalesce_streams
[NbConvertApp] Applying preprocessor: SVG2PDFPreprocessor
[NbConvertApp] Applying preprocessor: LatexPreprocessor
[NbConvertApp] Applying preprocessor: HighlightMagicsPreprocessor
[NbConvertApp] Applying preprocessor: ExtractOutputPreprocessor
[NbConvertApp] Attempting to load template index.tex.j2
[NbConvertApp]     template_paths: ~/anaconda3/share/jupyter/nbconvert/templates/latex:~/anaconda3/share/jupyter/nbconvert/templates/base:~/anaconda3/share/jupyter:~/anaconda3/share/jupyter/nbconvert/templates:~/anaconda3/share/jupyter/nbconvert/templates/compatibility:~/.local/share/jupyter:~/.local/share/jupyter/nbconvert/templates:~/.local/share/jupyter/nbconvert/templates/compatibility:/usr/local/share/jupyter:/usr/local/share/jupyter/nbconvert/templates:/usr/local/share/jupyter/nbconvert/templates/compatibility:/usr/share/jupyter:/usr/share/jupyter/nbconvert/templates:/usr/share/jupyter/nbconvert/templates/compatibility:~/anaconda3/share/jupyter/nbconvert/templates
[NbConvertApp] ERROR | Error while converting '/tmp/729403b1-bd85-41b1-96df-2cdb432c7f07/test.ipynb'
Traceback (most recent call last):
  File "~/anaconda3/lib/python3.10/site-packages/nbconvert/nbconvertapp.py", line 488, in export_single_notebook
    output, resources = self.exporter.from_filename(
  File "~/anaconda3/lib/python3.10/site-packages/nbconvert/exporters/exporter.py", line 189, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "~/anaconda3/lib/python3.10/site-packages/nbconvert/exporters/exporter.py", line 206, in from_file
    return self.from_notebook_node(
  File "~/anaconda3/lib/python3.10/site-packages/nbconvert/exporters/pdf.py", line 181, in from_notebook_node
    latex, resources = super().from_notebook_node(nb, resources=resources, **kw)
  File "~/anaconda3/lib/python3.10/site-packages/nbconvert/exporters/latex.py", line 74, in from_notebook_node
    return super().from_notebook_node(nb, resources, **kw)
  File "~/anaconda3/lib/python3.10/site-packages/nbconvert/exporters/templateexporter.py", line 413, in from_notebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
  File "~/anaconda3/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "~/anaconda3/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "~/anaconda3/share/jupyter/nbconvert/templates/latex/index.tex.j2", line 8, in top-level template code
    ((* extends cell_style *))
  File "~/anaconda3/share/jupyter/nbconvert/templates/latex/style_jupyter.tex.j2", line 176, in top-level template code
    \prompt{(((prompt)))}{(((prompt_color)))}{(((execution_count)))}{(((extra_space)))}
  File "~/anaconda3/share/jupyter/nbconvert/templates/latex/base.tex.j2", line 7, in top-level template code
    ((*- extends 'document_contents.tex.j2' -*))
  File "~/anaconda3/share/jupyter/nbconvert/templates/latex/document_contents.tex.j2", line 51, in top-level template code
    ((*- block figure scoped -*))
  File "~/anaconda3/share/jupyter/nbconvert/templates/latex/display_priority.j2", line 5, in top-level template code
    ((*- extends 'null.j2' -*))
  File "~/anaconda3/share/jupyter/nbconvert/templates/latex/null.j2", line 30, in top-level template code
    ((*- block body -*))
  File "~/anaconda3/share/jupyter/nbconvert/templates/latex/base.tex.j2", line 215, in block 'body'
    ((( super() )))
  File "~/anaconda3/share/jupyter/nbconvert/templates/latex/null.j2", line 32, in block 'body'
    ((*- block any_cell scoped -*))
  File "~/anaconda3/share/jupyter/nbconvert/templates/latex/null.j2", line 85, in block 'any_cell'
    ((*- block markdowncell scoped-*)) ((*- endblock markdowncell -*))
  File "~/anaconda3/share/jupyter/nbconvert/templates/latex/document_contents.tex.j2", line 68, in block 'markdowncell'
    ((( cell.source | citation2latex | strip_files_prefix | convert_pandoc('markdown+tex_math_double_backslash', 'json',extra_args=[]) | resolve_references | convert_pandoc('json','latex'))))
  File "~/anaconda3/lib/python3.10/site-packages/nbconvert/filters/pandoc.py", line 24, in convert_pandoc
    return pandoc(source, from_format, to_format, extra_args=extra_args)
  File "~/anaconda3/lib/python3.10/site-packages/nbconvert/utils/pandoc.py", line 51, in pandoc
    check_pandoc_version()
  File "~/anaconda3/lib/python3.10/site-packages/nbconvert/utils/pandoc.py", line 99, in check_pandoc_version
    v = get_pandoc_version()
  File "~/anaconda3/lib/python3.10/site-packages/nbconvert/utils/pandoc.py", line 76, in get_pandoc_version
    raise PandocMissing()
nbconvert.utils.pandoc.PandocMissing: Pandoc wasn't found.
Please check that pandoc is installed:
https://pandoc.org/installing.html
[NbConvertApp] Exiting application: jupyter-nbconvert

    at qw.executeCommand (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:24:325581)
    at Xw.export (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:24:329446)
    at aS.exportToFormat (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:24:333899)
    at aS.performNbConvertExport (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:24:333727)
    at aS.performExport (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:24:333402)
    at aS.exportImpl (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:24:333030)
    at aS.export (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:24:332786)
    at f_.export (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:24:472378)
    at e.$vL.h (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:64077)
12:34:47.167 [error] If you have not installed xelatex (TeX) you will need to do so before you can export to PDF, for further instructions please look https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex. 
To avoid installing xelatex (TeX) you might want to try exporting to HTML and using your browsers "Print to PDF" feature.

```
However, xelatex is installed because

```
which xelatex
/usr/bin/xelatex

```

## Steps to reproduce:

Here is the notebook I made

```
mamba activate jupyter 
visudo     
```                       

then

a markdown block 
`this is a test
`
a bash block with the command
`ls`

and when I do "export to pdf" I have the error output above. The html export works without issues.
It seems the problem comes from latex but I have latex installed. any idea? Thanks a lot

Here is the link of the html [](https://drive.google.com/file/d/1LFzYtfXo_qdBq8HUWDvfIMxrbQC7zWbI/view?usp=sharing)

**Comment by DonJayamanne** [comment]
Thank you for filing this issue and sorry you are running into this.

Based on the logs, it looks lik eyou do not have `pandoc` installed, please install the necessary libraries.
If that does not work please feel free to ping here or feel free to create a new issue
