### ISSUE TITLE
Error: uv_os_get_passwd returned ENOENT

### ISSUE THREAD

**Issue by buchbergerd** [microsoft/vscode-jupyter#13963]
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Hello,

when opening a python file, vs code reports

"Extension activation failed, run the 'Developer: Toggle Developer Tools' command for more information.
Source: Jupyter (Extension).".

Unfortunately, the extension can not be used.
One thing that might be of interest: My user is not listed in /etc/passwd as we use LDAP. VS Code and every file etc. is local.

Thanks in advance!

### VS Code Version

Version: 1.80.1 Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771 Date: 2023-07-12T17:22:25.257Z Electron: 22.3.14 ElectronBuildId: 21893604 Chromium: 108.0.5359.215 Node.js: 16.17.1 V8: 10.8.168.25-electron.0 OS: Linux x64 5.19.0-46-generic snap

### Jupyter Extension Version

v2023.6.1101941928

### Jupyter logs

```shell
Command 'Jupyter:Schow Output' resulted in an error
command 'jupyter.viewOutput' not found

From the Developer Tools:


notificationsAlerts.ts:42 Extension activation failed, run the 'Developer: Toggle Developer Tools' command for more information.
c @ notificationsAlerts.ts:42
log.ts:441   ERR [Extension Host] extension activation failed Error: No matching bindings found for serviceIdentifier: Symbol(IExtensions)
	at /home/USER/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:2:534020
	at b (/home/USER/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:2:534309)
	at w (/home/USER/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:2:534396)
	at t.plan (/home/USER/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:2:535475)
	at /home/USER/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:2:519947
	at e._get (/home/USER/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:2:519466)
	at e._getButThrowIfAsync (/home/USER/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:2:519526)
	at e.get (/home/USER/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:2:515221)
	at gb.get (/home/USER/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:24:231680)
	at ks (/home/USER/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:2:1739411)
	at /home/USER/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:24:622600
	at yP (/home/USER/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:24:622650)
	at Tn.eb (/snap/code/134/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:113:13743)
	at Tn.db (/snap/code/134/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:113:13456)
	at /snap/code/134/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:113:11577
	at async w.n (/snap/code/134/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:6194)
	at async w.m (/snap/code/134/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:6157)
	at async w.l (/snap/code/134/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:5614)
console.ts:137 [Extension Host] extension activation failed Error: No matching bindings found for serviceIdentifier: Symbol(IExtensions)
	at /home/USER/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:2:534020
	at b (/home/USER/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:2:534309)
	at w (/home/USER/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:2:534396)
	at t.plan (/home/USER/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:2:535475)
	at /home/USER/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:2:519947
	at e._get (/home/USER/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:2:519466)
	at e._getButThrowIfAsync (/home/USER/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:2:519526)
	at e.get (/home/USER/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:2:515221)
	at gb.get (/home/USER/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:24:231680)
	at ks (/home/USER/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:2:1739411)
	at /home/USER/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:24:622600
	at yP (/home/USER/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:24:622650)
	at Tn.eb (/snap/code/134/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:113:13743)
	at Tn.db (/snap/code/134/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:113:13456)
	at /snap/code/134/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:113:11577
	at async w.n (/snap/code/134/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:6194)
	at async w.m (/snap/code/134/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:6157)
	at async w.l (/snap/code/134/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:5614)
v @ console.ts:137
console.ts:137 [Extension Host] rejected promise not handled within 1 second: SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
v @ console.ts:137
console.ts:137 [Extension Host] stack trace: SystemError: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
	at new SystemError (node:internal/errors:238:5)
	at new NodeError (node:internal/errors:349:7)
	at userInfo (node:os:347:11)
	at /home/USER/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:24:615981
	at /home/USER/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:24:617204
	at /home/USER/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:24:622532
	at /home/USER/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:24:622540
	at yP (/home/USER/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:24:622650)
	at Tn.eb (/snap/code/134/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:113:13743)
	at Tn.db (/snap/code/134/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:113:13456)
	at /snap/code/134/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:113:11577
	at async w.n (/snap/code/134/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:6194)
	at async w.m (/snap/code/134/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:6157)
	at async w.l (/snap/code/134/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:5614)
v @ console.ts:137
mainThreadExtensionService.ts:81 [ms-toolsai.jupyter]A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:81
mainThreadExtensionService.ts:82 SystemError: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
	at new SystemError (node:internal/errors:238:5)
	at new NodeError (node:internal/errors:349:7)
	at userInfo (node:os:347:11)
	at /home/USER/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:24:615981
	at /home/USER/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:24:617204
	at /home/USER/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:24:622532
	at /home/USER/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:24:622540
	at yP (/home/USER/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-linux-x64/out/extension.node.js:24:622650)
	at Tn.eb (/snap/code/134/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:113:13743)
	at Tn.db (/snap/code/134/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:113:13456)
	at /snap/code/134/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:113:11577
	at async w.n (/snap/code/134/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:6194)
	at async w.m (/snap/code/134/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:6157)
	at async w.l (/snap/code/134/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:5614)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:82
log.ts:421
```

### Coding Language and Runtime Version

Python 3.10.6

### Language Extension Version (if applicable)

v2023.12.0

### Anaconda Version (if applicable)

N/A

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
Hopefully that change fixes the issue, should be available in the pre-release version of the extension tomorrow, or you can try installing the built visx directly:
[ms-toolsai-jupyter-insiders.vsix (11).zip](https://github.com/microsoft/vscode-jupyter/files/12131047/ms-toolsai-jupyter-insiders.vsix.11.zip)

**Comment by buchbergerd** [comment]
Thank you very much!
