### ISSUE TITLE
Pick python disappears when changing tabs

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode-jupyter#13979]
Testing #13974

I took the step to select a codespace as my kernel and then select the cores/ codespace numbers. I switch tabs while it was loading. When I came back I saw a new picker that said something along the lines of "pick your python". I then switch tabs again while this picker was available when I returned it was gone. I see the following error in my jupyter output but unsure if it is related. Thanks

jupyter logs:
<img width="1710" alt="Screenshot 2023-07-25 at 9 08 34 AM" src="https://github.com/microsoft/vscode-jupyter/assets/26030610/7c4e77ee-f175-4f1d-b6dd-ab61d69adb12">

windows logs
```
2023-07-25 09:04:56.812 [warning] Ignoring the error while validating workspace folder vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/eleanorjboyd/inc_dec_example_repo - ENOPRO: No file system provider found for resource 'vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/eleanorjboyd/inc_dec_example_repo'
2023-07-25 09:04:56.907 [info] Found additional builtin gallery extensions in env [{"id":"github.codespaces","preRelease":false},{"id":"ms-vscode.anycode","preRelease":false},{"id":"github.remotehub","preRelease":false},{"id":"GitHub.vscode-pull-request-github","preRelease":false},{"id":"github.github-vscode-theme","preRelease":false}]
2023-07-25 09:04:59.467 [info] Updating additional builtin extensions cache
2023-07-25 09:05:09.710 [info] Migrating workspace extension storage from github.codespaces to GitHub.codespaces...
2023-07-25 09:05:09.710 [info] Migrated workspace extension storage from github.codespaces to GitHub.codespaces
2023-07-25 09:05:09.711 [error] No provider registered with : Error: No provider registered with 
	at Object.getRepositoryProvider (https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.38.1/extension/dist/browser/extension.js#vscode-extension:61:7121)
	at Object.getProviderRootUri (https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.38.1/extension/dist/browser/extension.js#vscode-extension:61:12753)
	at Object.getVirtualRootUri (https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.38.1/extension/dist/browser/extension.js#vscode-extension:61:13252)
	at Object.onDocumentChanged (https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.38.1/extension/dist/browser/extension.js#vscode-extension:61:3716)
	at _.w (https://v--1r3dkl4ugdkrisqre6gn8ocj6e3nh548isv6rac0cnfu148agf2s.vscode-cdn.net/stable/74f6148eb9ea00507ec113ec51c489d6ffb4b771/out/vs/base/worker/workerMain.js:15:1902)
	at _.fire (https://v--1r3dkl4ugdkrisqre6gn8ocj6e3nh548isv6rac0cnfu148agf2s.vscode-cdn.net/stable/74f6148eb9ea00507ec113ec51c489d6ffb4b771/out/vs/base/worker/workerMain.js:15:2119)
	at y.$acceptDocumentAndEditorsDelta (../../../vs/workbench/api/worker/extensionHostWorker.js:82:92955)
	at s.N (../../../vs/workbench/api/worker/extensionHostWorker.js:84:48079)
	at s.M (../../../vs/workbench/api/worker/extensionHostWorker.js:84:47845)
	at s.H (../../../vs/workbench/api/worker/extensionHostWorker.js:84:46926)
	at s.G (../../../vs/workbench/api/worker/extensionHostWorker.js:84:46141)
	at y.eval [as value] (../../../vs/workbench/api/worker/extensionHostWorker.js:84:44832)
	at _.w (https://v--1r3dkl4ugdkrisqre6gn8ocj6e3nh548isv6rac0cnfu148agf2s.vscode-cdn.net/stable/74f6148eb9ea00507ec113ec51c489d6ffb4b771/out/vs/base/worker/workerMain.js:15:1902)
	at _.fire (https://v--1r3dkl4ugdkrisqre6gn8ocj6e3nh548isv6rac0cnfu148agf2s.vscode-cdn.net/stable/74f6148eb9ea00507ec113ec51c489d6ffb4b771/out/vs/base/worker/workerMain.js:15:2119)
	at l.port1.onmessage (../../../vs/workbench/api/worker/extensionHostWorker.js:91:3853)
2023-07-25 09:05:10.513 [error] No provider registered with : Error: No provider registered with 
	at Object.getRepositoryProvider (https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.38.1/extension/dist/browser/extension.js#vscode-extension:61:7121)
	at Object.getProviderRootUri (https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.38.1/extension/dist/browser/extension.js#vscode-extension:61:12753)
	at Object.getVirtualRootUri (https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.38.1/extension/dist/browser/extension.js#vscode-extension:61:13252)
	at Object.onDocumentChanged (https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.38.1/extension/dist/browser/extension.js#vscode-extension:61:3716)
	at _.w (https://v--1r3dkl4ugdkrisqre6gn8ocj6e3nh548isv6rac0cnfu148agf2s.vscode-cdn.net/stable/74f6148eb9ea00507ec113ec51c489d6ffb4b771/out/vs/base/worker/workerMain.js:15:1902)
	at _.x (https://v--1r3dkl4ugdkrisqre6gn8ocj6e3nh548isv6rac0cnfu148agf2s.vscode-cdn.net/stable/74f6148eb9ea00507ec113ec51c489d6ffb4b771/out/vs/base/worker/workerMain.js:15:1972)
	at _.fire (https://v--1r3dkl4ugdkrisqre6gn8ocj6e3nh548isv6rac0cnfu148agf2s.vscode-cdn.net/stable/74f6148eb9ea00507ec113ec51c489d6ffb4b771/out/vs/base/worker/workerMain.js:15:2188)
	at y.eval [as value] (../../../vs/workbench/api/worker/extensionHostWorker.js:84:16535)
	at _.w (https://v--1r3dkl4ugdkrisqre6gn8ocj6e3nh548isv6rac0cnfu148agf2s.vscode-cdn.net/stable/74f6148eb9ea00507ec113ec51c489d6ffb4b771/out/vs/base/worker/workerMain.js:15:1902)
	at _.fire (https://v--1r3dkl4ugdkrisqre6gn8ocj6e3nh548isv6rac0cnfu148agf2s.vscode-cdn.net/stable/74f6148eb9ea00507ec113ec51c489d6ffb4b771/out/vs/base/worker/workerMain.js:15:2119)
	at e.$kL.acceptDocumentsAndEditorsDelta (../../../vs/workbench/api/worker/extensionHostWorker.js:82:13399)
	at e.$kL.$acceptDocumentsAndEditorsDelta (../../../vs/workbench/api/worker/extensionHostWorker.js:82:11770)
	at s.N (../../../vs/workbench/api/worker/extensionHostWorker.js:84:48079)
	at s.M (../../../vs/workbench/api/worker/extensionHostWorker.js:84:47845)
	at s.H (../../../vs/workbench/api/worker/extensionHostWorker.js:84:46926)
	at s.G (../../../vs/workbench/api/worker/extensionHostWorker.js:84:46002)
	at y.eval [as value] (../../../vs/workbench/api/worker/extensionHostWorker.js:84:44832)
	at _.w (https://v--1r3dkl4ugdkrisqre6gn8ocj6e3nh548isv6rac0cnfu148agf2s.vscode-cdn.net/stable/74f6148eb9ea00507ec113ec51c489d6ffb4b771/out/vs/base/worker/workerMain.js:15:1902)
	at _.fire (https://v--1r3dkl4ugdkrisqre6gn8ocj6e3nh548isv6rac0cnfu148agf2s.vscode-cdn.net/stable/74f6148eb9ea00507ec113ec51c489d6ffb4b771/out/vs/base/worker/workerMain.js:15:2119)
	at l.port1.onmessage (../../../vs/workbench/api/worker/extensionHostWorker.js:91:3853)
2023-07-25 09:08:14.226 [error] No provider registered with : Error: No provider registered with 
    at Object.getRepositoryProvider (https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.38.1/extension/dist/browser/extension.js#vscode-extension:61:7121)
    at Object.getProviderRootUri (https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.38.1/extension/dist/browser/extension.js#vscode-extension:61:12753)
    at Object.getVirtualRootUri (https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.38.1/extension/dist/browser/extension.js#vscode-extension:61:13252)
    at Object.onDocumentChanged (https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.38.1/extension/dist/browser/extension.js#vscode-extension:61:3716)
    at _.w (https://v--1r3dkl4ugdkrisqre6gn8ocj6e3nh548isv6rac0cnfu148agf2s.vscode-cdn.net/stable/74f6148eb9ea00507ec113ec51c489d6ffb4b771/out/vs/base/worker/workerMain.js:15:1902)
    at _.x (https://v--1r3dkl4ugdkrisqre6gn8ocj6e3nh548isv6rac0cnfu148agf2s.vscode-cdn.net/stable/74f6148eb9ea00507ec113ec51c489d6ffb4b771/out/vs/base/worker/workerMain.js:15:1972)
    at _.fire (https://v--1r3dkl4ugdkrisqre6gn8ocj6e3nh548isv6rac0cnfu148agf2s.vscode-cdn.net/stable/74f6148eb9ea00507ec113ec51c489d6ffb4b771/out/vs/base/worker/workerMain.js:15:2188)
    at y.eval [as value] (../../../vs/workbench/api/worker/extensionHostWorker.js:84:16535)
    at _.w (https://v--1r3dkl4ugdkrisqre6gn8ocj6e3nh548isv6rac0cnfu148agf2s.vscode-cdn.net/stable/74f6148eb9ea00507ec113ec51c489d6ffb4b771/out/vs/base/worker/workerMain.js:15:1902)
    at _.fire (https://v--1r3dkl4ugdkrisqre6gn8ocj6e3nh548isv6rac0cnfu148agf2s.vscode-cdn.net/stable/74f6148eb9ea00507ec113ec51c489d6ffb4b771/out/vs/base/worker/workerMain.js:15:2119)
    at e.$kL.acceptDocumentsAndEditorsDelta (../../../vs/workbench/api/worker/extensionHostWorker.js:82:13399)
    at e.$kL.$acceptDocumentsAndEditorsDelta (../../../vs/workbench/api/worker/extensionHostWorker.js:82:11770)
    at s.N (../../../vs/workbench/api/worker/extensionHostWorker.js:84:48079)
    at s.M (../../../vs/workbench/api/worker/extensionHostWorker.js:84:47845)
    at s.H (../../../vs/workbench/api/worker/extensionHostWorker.js:84:46926)
    at s.G (../../../vs/workbench/api/worker/extensionHostWorker.js:84:46002)
    at y.eval [as value] (../../../vs/workbench/api/worker/extensionHostWorker.js:84:44832)
    at _.w (https://v--1r3dkl4ugdkrisqre6gn8ocj6e3nh548isv6rac0cnfu148agf2s.vscode-cdn.net/stable/74f6148eb9ea00507ec113ec51c489d6ffb4b771/out/vs/base/worker/workerMain.js:15:1902)
    at _.fire (https://v--1r3dkl4ugdkrisqre6gn8ocj6e3nh548isv6rac0cnfu148agf2s.vscode-cdn.net/stable/74f6148eb9ea00507ec113ec51c489d6ffb4b771/out/vs/base/worker/workerMain.js:15:2119)
    at MessagePort.l.port1.onmessage (../../../vs/workbench/api/worker/extensionHostWorker.js:91:3853)
2023-07-25 09:12:31.695 [error] No provider registered with : Error: No provider registered with 
    at Object.getRepositoryProvider (https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.38.1/extension/dist/browser/extension.js#vscode-extension:61:7121)
    at Object.getProviderRootUri (https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.38.1/extension/dist/browser/extension.js#vscode-extension:61:12753)
    at Object.getVirtualRootUri (https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.38.1/extension/dist/browser/extension.js#vscode-extension:61:13252)
    at Object.onDocumentChanged (https://ms-vscode.vscode-unpkg.net/ms-vscode/remote-repositories/0.38.1/extension/dist/browser/extension.js#vscode-extension:61:3716)
    at _.w (https://v--1r3dkl4ugdkrisqre6gn8ocj6e3nh548isv6rac0cnfu148agf2s.vscode-cdn.net/stable/74f6148eb9ea00507ec113ec51c489d6ffb4b771/out/vs/base/worker/workerMain.js:15:1902)
    at _.x (https://v--1r3dkl4ugdkrisqre6gn8ocj6e3nh548isv6rac0cnfu148agf2s.vscode-cdn.net/stable/74f6148eb9ea00507ec113ec51c489d6ffb4b771/out/vs/base/worker/workerMain.js:15:1972)
    at _.fire (https://v--1r3dkl4ugdkrisqre6gn8ocj6e3nh548isv6rac0cnfu148agf2s.vscode-cdn.net/stable/74f6148eb9ea00507ec113ec51c489d6ffb4b771/out/vs/base/worker/workerMain.js:15:2188)
    at y.eval [as value] (../../../vs/workbench/api/worker/extensionHostWorker.js:84:16535)
    at _.w (https://v--1r3dkl4ugdkrisqre6gn8ocj6e3nh548isv6rac0cnfu148agf2s.vscode-cdn.net/stable/74f6148eb9ea00507ec113ec51c489d6ffb4b771/out/vs/base/worker/workerMain.js:15:1902)
    at _.fire (https://v--1r3dkl4ugdkrisqre6gn8ocj6e3nh548isv6rac0cnfu148agf2s.vscode-cdn.net/stable/74f6148eb9ea00507ec113ec51c489d6ffb4b771/out/vs/base/worker/workerMain.js:15:2119)
    at e.$kL.acceptDocumentsAndEditorsDelta (../../../vs/workbench/api/worker/extensionHostWorker.js:82:13399)
    at e.$kL.$acceptDocumentsAndEditorsDelta (../../../vs/workbench/api/worker/extensionHostWorker.js:82:11770)
    at s.N (../../../vs/workbench/api/worker/extensionHostWorker.js:84:48079)
    at s.M (../../../vs/workbench/api/worker/extensionHostWorker.js:84:47845)
    at s.H (../../../vs/workbench/api/worker/extensionHostWorker.js:84:46926)
    at s.G (../../../vs/workbench/api/worker/extensionHostWorker.js:84:46002)
    at y.eval [as value] (../../../vs/workbench/api/worker/extensionHostWorker.js:84:44832)
    at _.w (https://v--1r3dkl4ugdkrisqre6gn8ocj6e3nh548isv6rac0cnfu148agf2s.vscode-cdn.net/stable/74f6148eb9ea00507ec113ec51c489d6ffb4b771/out/vs/base/worker/workerMain.js:15:1902)
    at _.fire (https://v--1r3dkl4ugdkrisqre6gn8ocj6e3nh548isv6rac0cnfu148agf2s.vscode-cdn.net/stable/74f6148eb9ea00507ec113ec51c489d6ffb4b771/out/vs/base/worker/workerMain.js:15:2119)
    at MessagePort.l.port1.onmessage (../../../vs/workbench/api/worker/extensionHostWorker.js:91:3853)
```

**Comment by DonJayamanne** [comment]
> k the step to select a codespace as my kernel and then select the cores/ codespace numbers. I switch tabs while it was loading. When I came back I saw a new picker that said something along the lines of "pick your python". I then switch tabs again while this picker was available when I returned it was gone. I see the following error in my jupyter out

Closing this issue as this quick pick is provided by codespaces extension and not the Jupyter extension

@rebornix /cc
