### ISSUE TITLE
Bug in Jupyter extension for VS Code

### ISSUE THREAD

**Issue by saga-gnassingbe** [microsoft/vscode-jupyter#13999]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I have updated the Jupyter extension for VS Code to the latest version (July 2023). VS Code fails to launch the extension. Older versions (e.g. November 2022) of this extension can launched successfully.

Main error message:

[ms-toolsai.jupyter]Invalid regular expression: **/SagaGnassingbe(Sigma/**: Unterminated group
$onExtensionRuntimeError @ mainThreadExtensionService.ts:81
mainThreadExtensionService.ts:82 SyntaxError: Invalid regular expression: **/SagaGnassingbe(Sigma/**: Unterminated group
	at new RegExp (<anonymous>)

### VS Code Version

Version: 1.80.2 (system setup) Commit: 2ccd690cbff1569e4a83d7c43d45101f817401dc Date: 2023-07-27T20:40:28.909Z Electron: 22.3.14 ElectronBuildId: 22695494 Chromium: 108.0.5359.215 Node.js: 16.17.1 V8: 10.8.168.25-electron.0 OS: Windows_NT x64 10.0.22621

### Jupyter Extension Version

v2023.6.1101941928

### Jupyter logs

```shell
workbench.desktop.main.js:sourcemap:627  INFO [perf] Render performance baseline is 53ms
workbench.desktop.main.js:sourcemap:762 Extension activation failed, run the 'Developer: Toggle Developer Tools' command for more information.
c @ workbench.desktop.main.js:sourcemap:762
workbench.desktop.main.js:sourcemap:627   ERR [Extension Host] extension activation failed Error: No matching bindings found for serviceIdentifier: Symbol(IExtensions)
	at c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:2:534020
	at b (c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:2:534309)
	at w (c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:2:534396)
	at t.plan (c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:2:535475)
	at c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:2:519947
	at e._get (c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:2:519466)
	at e._getButThrowIfAsync (c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:2:519526)
	at e.get (c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:2:515221)
	at gb.get (c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:24:231680)
	at ks (c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:2:1739411)
	at c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:24:622600
	at yP (c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:24:622650)
	at Tn.eb (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:13743)
	at Tn.db (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:13456)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:11577
	at async w.n (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:6194)
	at async w.m (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:6157)
	at async w.l (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:5614)
workbench.desktop.main.js:sourcemap:131 [Extension Host] extension activation failed Error: No matching bindings found for serviceIdentifier: Symbol(IExtensions)
	at c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:2:534020
	at b (c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:2:534309)
	at w (c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:2:534396)
	at t.plan (c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:2:535475)
	at c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:2:519947
	at e._get (c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:2:519466)
	at e._getButThrowIfAsync (c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:2:519526)
	at e.get (c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:2:515221)
	at gb.get (c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:24:231680)
	at ks (c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:2:1739411)
	at c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:24:622600
	at yP (c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:24:622650)
	at Tn.eb (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:13743)
	at Tn.db (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:13456)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:11577
	at async w.n (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:6194)
	at async w.m (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:6157)
	at async w.l (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:5614)
v @ workbench.desktop.main.js:sourcemap:131
workbench.desktop.main.js:sourcemap:131 [Extension Host] rejected promise not handled within 1 second: SyntaxError: Invalid regular expression: /SagaGnassingbe(Sigma/: Unterminated group
v @ workbench.desktop.main.js:sourcemap:131
workbench.desktop.main.js:sourcemap:131 [Extension Host] stack trace: SyntaxError: Invalid regular expression: /SagaGnassingbe(Sigma/: Unterminated group
	at new RegExp (<anonymous>)
	at new uP (c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:24:613181)
	at c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:24:615945
	at c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:24:617204
	at c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:24:622532
	at c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:24:622540
	at yP (c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:24:622650)
	at Tn.eb (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:13743)
	at Tn.db (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:13456)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:11577
	at async w.n (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:6194)
	at async w.m (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:6157)
	at async w.l (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:5614)
v @ workbench.desktop.main.js:sourcemap:131
workbench.desktop.main.js:sourcemap:1962 [ms-toolsai.jupyter]Invalid regular expression: /SagaGnassingbe(Sigma/: Unterminated group
$onExtensionRuntimeError @ workbench.desktop.main.js:sourcemap:1962
workbench.desktop.main.js:sourcemap:1962 SyntaxError: Invalid regular expression: /SagaGnassingbe(Sigma/: Unterminated group
	at new RegExp (<anonymous>)
	at new uP (c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:24:613181)
	at c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:24:615945
	at c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:24:617204
	at c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:24:622532
	at c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:24:622540
	at yP (c:\Users\SagaGnassingbe_Sigma\.vscode\extensions\ms-toolsai.jupyter-2023.6.1101941928-win32-x64\out\extension.node.js:24:622650)
	at Tn.eb (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:13743)
	at Tn.db (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:13456)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:113:11577
	at async w.n (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:6194)
	at async w.m (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:6157)
	at async w.l (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:5614)
$onExtensionRuntimeError @ workbench.desktop.main.js:sourcemap:1962
DevTools failed to load source map: Could not load content for https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/SagaGnassingbe_Sigma/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/client_renderer/preload.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/SagaGnassingbe_Sigma/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-win32-x64/out/webviews/webview-side/ipywidgetsKernel/ipywidgetsKernel.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
```

### Coding Language and Runtime Version

Python  3.10.12

### Anaconda Version (if applicable)

conda 22.9.0

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
it looks like `os.userInfo()` is providing a username where the `_` is replaced with a `(`.
We should escape special characters when creating these regexes, but in this case it still wouldn't obfuscate that info in the logs as intended. cc @DonJayamanne

**Comment by saga-gnassingbe** [comment]
Hello Aaron,

The additional information from my side:


  *   Windows username contains a left bracket. Until yesterday, it was also the case for the user folder under c:\users\ .
  *   Yesterday I did put some effort into modifying the user folder name, by replacing the left bracket with “_”. I thought that this would resolve the issue with the Jupyter extension not launching. But modifying the user folder name did not resolve the issue.
  *   The bottom line is: the Jupyter extension code does not replace “_” with a left bracket.
  *   My problem on Windows OS side: there seems to be no way to modify the username after installation of the OS.

KR,

Saga.

------------------------------------------------------------------------------------------------------------------------------
This email and all attachments are confidential and intended solely for the addressee. If you are not the intended recipient,
please delete this email immediately and notify us by email or telephone. Any disclosure, distribution, or use of the information
contained in this email by persons or organizations other than the intended recipient is prohibited.
-------------------------------------------------
[A picture containing text, clipart  Description automatically generated]
Saga Gnassingbe
SiTelSo GmbH
Schelmenwasenstr. 32
70567 Stuttgart

Phone: +49 160 9913 2274
E-Mail: ***@***.******@***.***>
Web: https://sitelso.net<https://sitelso.net/>

Stuttgart Local Court, Commercial Register Number (HRB) 786256
Managing Director: Saga Gnassingbe
Registered Office: 71144 Steinenbronn

**Comment by amunger** [comment]
thanks for the clarification, should be easy enough to fix then.
