### ISSUE TITLE
Kernel stuck due to large variables being loaded

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#14006]
Originally filed by @Fred-Wu here https://github.com/microsoft/vscode-jupyter/issues/14004#issuecomment-1657367827

I am just about to report the same on 

OS: macOS Ventura 13.5, M1
Python 3.10.12/3.11.4
VS Code version: Code 1.80.2
Jupyter: v2023.6.1101941928

This happens to me while jupyter variables pane keeps "loading variables" from a file, which converts the file to a list and dict of 400,000.  

<img width="552" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/4111978/d58a83f6-6bf7-44dd-8311-56f1d80b142a">

<img width="409" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/4111978/9f34d780-8fd4-4fc1-936b-e4d155edfb7a">

But event after "VARIABLES" pane loading successfully,   it was still stuck when I just tried to show the first one. 

<img width="351" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/4111978/32bf9aab-ad54-4cb5-b909-3a08b5a769f2">

When I restarted Kernel, the output pane shows the following

```
[error] stat() failed for "vscode-notebook-cell:~/Documents/Studies/Coursera/Deep%20Learning/Sequence%20Models/Week%202/Operations_on_word_vectors_v2a.ipynb#W3sZmlsZQ%3D%3D" 
[Unavailable (FileSystemError): ENOPRO: No file system provider found for resource 'vscode-notebook-cell:~/Documents/Studies/Coursera/Deep%20Learning/Sequence%20Models/Week%202/Operations_on_word_vectors_v2a.ipynb#W3sZmlsZQ%3D%3D'
	at ii.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:101:27301)
	at Object.stat (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:101:24574)
	at async mu.exists (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:17:17828)
	at async l_.getWorkingDirectory (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:24:465224)
	at async l_.getCode (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:24:464690)
	at async Promise.all (index 1)
	at async eg.gatherInternalStartupCode (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:24:963)
	at async eg.initializeAfterStart (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:17:219511)
	at async eg.restart (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:17:213846)
	at async Jy.wrapKernelMethodImpl (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:24:198557)] {
  code: 'Unavailable'
```

Otherwise, running codes just show some boring messages

```
11:33:11.888 [info] Generated code for 1 = <ipython-input-1-1d7d0b7308ea> with 2 lines
11:33:11.912 [info] Kernel acknowledged execution of cell 6 @ 1690767191907
11:33:11.915 [info] End cell 6 execution @ 1690767191913, started @ 1690767191907, elapsed time = 0.006s
11:33:16.739 [info] Generated code for 2 = <ipython-input-2-e76c3f3a02a5> with 2 lines
11:33:16.759 [info] Kernel acknowledged execution of cell 7 @ 1690767196757
11:33:18.918 [info] End cell 7 execution @ 1690767198916, started @ 1690767196757, elapsed time = 2.159s
11:33:22.081 [info] Generated code for 3 = <ipython-input-3-4bde853e0d27> with 1 lines
11:33:22.098 [info] Kernel acknowledged execution of cell 8 @ 1690767202096
11:33:24.209 [info] End cell 8 execution @ 1690767204207, started @ 1690767202096, elapsed time = 2.111s
11:35:20.532 [info] Generated code for 4 = <ipython-input-4-1d7d0b7308ea> with 2 lines
```

**Comment by DonJayamanne** [comment]
@roblourens I believe this is a known issue, basically we have a very large variable and that blocks execution.
To my knowledge we refresh variables regularly (after every execution and the like) and that seems to be the cause of this issue.
At least thats what I believe is going on here, though I'm not sure whether the delay is in returning the values (large payload), or computing the variables in the kernels or other

**Comment by Fred-Wu** [comment]
Thanks for creating this for me. 

This was the first time I encountered this, which was after the recent update. 
Certainly, there are some similar issue reported,  such as #13998. 
I wonder it might be related.

**Comment by Fred-Wu** [comment]
Additional info is that, if I hide variable pane without opening it or checking it, everything runs fast. 
However, once I run the code, and opens the variable pane, then it becomes stuck again. 

<img width="591" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/4111978/424ef170-e3f8-4f7b-a6ca-ae0a4b3628b1">

**Comment by amunger** [comment]
The new variable view, available with the setting `notebook.variablesView` enabled, should both run variable retrieval on a background thread and also handle large values with much better performance. 
I'll leave this open until we start switching over to that view though.

**Comment by amunger** [comment]
closing in favor of moving to the new variables view
