### ISSUE TITLE
${fileDirname} fails when workspace is under '/'

### ISSUE THREAD

**Issue by sciencebug** [microsoft/vscode-jupyter#14000]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

when i open a folder ('/app') under my fs root in vscode and then open a notebook and run `os.getcwd()` the returned path is '/', not the folder itself.
this is only true for notebooks in the folder's root. a notebook in a subfolder returns the subfolder, as expected.

if i change "Jupyter: Notebook File Root" from ${fileDirname} to ${workspaceFolder}, `os.getcwd()` always returns '/app', even in subfolders, as expected.

moving the folder somewhere else fixes the problem, e.g. "/home/me/app" or "/usr/src/app".

i am running on WSL2 as a normal user. the issue persists in container-attached vscode with both root and normal users.

tested with both release, and pre-release versions of jupyter and python extensions

### VS Code Version

Version: 1.80.2 (user setup) Commit: 2ccd690cbff1569e4a83d7c43d45101f817401dc Date: 2023-07-27T20:40:28.909Z Electron: 22.3.14 ElectronBuildId: 22695494 Chromium: 108.0.5359.215 Node.js: 16.17.1 V8: 10.8.168.25-electron.0 OS: Windows_NT x64 10.0.22621

### Jupyter Extension Version

v2023.7.1001901100

### Coding Language and Runtime Version

Python v3.11.4

### Language Extension Version (if applicable)

Python v2023.13.12091005

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
thanks for the bug, I can repro. not sure why this is happening after taking a quick look

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by amunger** [comment]
<details>
<summary>Jupyter Logs</summary>

```
Visual Studio Code - Insiders (1.85.0-insider, wsl, desktop)
Jupyter Extension Version: 2023.11.1003351000.
Python Extension Version: 2023.20.0.
Pylance Extension Version: 2023.11.10.
Platform: linux (x64).
Workspace folder /app, Home = /home/aamunger
09:31:19.726 [debug] Get Custom Env Variables, Class name = _m (started execution), Arg 1: undefined, Arg 2: "RunPythonCode"
09:31:19.739 [info] Start refreshing Kernel Picker (1701451879739)
09:31:19.772 [info] Using Pylance
09:31:20.727 [info] Start refreshing Interpreter Kernel Picker
09:31:20.751 [debug] No controller, hence notebook communications cannot be initialized for editor /app/1.ipynb
09:31:20.770 [debug] Preferred Remote kernel for /app/1.ipynb is undefined
09:31:22.662 [debug] Get Custom Env Variables, Class name = _m, completed in 2937ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
09:31:22.663 [debug] Jupyter Paths /kernels: 
09:31:22.669 [debug] Kernel Spec Root Paths, /usr/share/jupyter/kernels, /usr/local/share/jupyter/kernels, ~/.local/share/jupyter/kernels
09:31:22.679 [debug] Error in detecting whether url is isJupyterHub: FetchError: request to http://127.0.0.1:8888/hub/api failed, reason: connect ECONNREFUSED 127.0.0.1:8888
09:31:22.765 [debug] Search for KernelSpecs in Interpreter /bin/python3
09:31:22.766 [debug] Finding Global Python KernelSpecs
09:31:22.769 [debug] Search for KernelSpecs in Interpreter /usr/bin/python3
09:31:22.772 [debug] Full interpreter list is length: 2, /bin/python3::Unknown:/bin/python3, /usr/bin/python3::Unknown:/usr/bin/python3
09:31:22.859 [error] Failed to validate Password info [D [FetchError]: request to http://127.0.0.1:8888/tree? failed, reason: connect ECONNREFUSED 127.0.0.1:8888
	at ClientRequest.<anonymous> (~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.11.1003351000-linux-x64/dist/node_modules/node-fetch.js:1:306417)
	at ClientRequest.emit (node:events:513:28)
	at Socket.socketErrorListener (node:_http_client:502:9)
	at Socket.emit (node:events:513:28)
	at emitErrorNT (node:internal/streams/destroy:151:8)
	at emitErrorCloseNT (node:internal/streams/destroy:116:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)] {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
09:31:22.944 [error] Error fetching kernels from http://127.0.0.1:8888/ (local1): [FetchError: request to http://127.0.0.1:8888/api/kernels?1701451882906 failed, reason: connect ECONNREFUSED 127.0.0.1:8888
	at ClientRequest.<anonymous> (~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.11.1003351000-linux-x64/dist/node_modules/node-fetch.js:1:306417)
	at ClientRequest.emit (node:events:513:28)
	at Socket.socketErrorListener (node:_http_client:502:9)
	at Socket.emit (node:events:513:28)
	at emitErrorNT (node:internal/streams/destroy:151:8)
	at emitErrorCloseNT (node:internal/streams/destroy:116:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)]
09:31:22.944 [debug] Disposing Jupyter Lab Helper
09:31:22.944 [debug] SessionManager - dispose contents manager
09:31:22.945 [debug] ShutdownSessionAndConnection - dispose session manager
09:31:22.946 [debug] Finished disposing Jupyter Lab Helper
09:31:22.946 [error] UniversalRemoteKernelFinder: Failed to get kernels without cache [FetchError: request to http://127.0.0.1:8888/api/kernels?1701451882906 failed, reason: connect ECONNREFUSED 127.0.0.1:8888
	at ClientRequest.<anonymous> (~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.11.1003351000-linux-x64/dist/node_modules/node-fetch.js:1:306417)
	at ClientRequest.emit (node:events:513:28)
	at Socket.socketErrorListener (node:_http_client:502:9)
	at Socket.emit (node:events:513:28)
	at emitErrorNT (node:internal/streams/destroy:151:8)
	at emitErrorCloseNT (node:internal/streams/destroy:116:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)]
09:31:22.947 [debug] UniversalRemoteKernelFinder: Writing 0 remote kernel connection metadata to cache
09:31:22.947 [error] Jupyter Lab Helper:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at v.dispose (~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.11.1003351000-linux-x64/dist/node_modules/@jupyterlab/services.js:11:10935)
	at ni.dispose (~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.11.1003351000-linux-x64/dist/node_modules/@jupyterlab/services.js:11:29299)
	at r.dispose (~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.11.1003351000-linux-x64/dist/extension.node.js:138:4517)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Promise.all (index 0)
	at async rT.listKernelsFromConnection (~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.11.1003351000-linux-x64/dist/extension.node.js:235:22644)
	at async ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.11.1003351000-linux-x64/dist/extension.node.js:235:20130]
09:31:22.958 [debug] Kernels for interpreter /bin/python3 are .jvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1./bin/python3./bin/python3.-m#ipykernel_launcher
09:31:22.959 [debug] Kernels for interpreter /usr/bin/python3 are .jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6./usr/bin/python3./usr/bin/python3.-m#ipykernel_launcher
09:31:23.054 [debug] Conda file returned by Python Extension is conda
09:31:23.083 [debug] Python API env change detected, add => '/app/.venv/bin/python'
09:31:23.137 [debug] KernelProvider switched kernel to id = .jvsc74a57bd0026d69f88b532a5652e86a2c423a2c9b09db65f0944232314c8121562750e7b3./app/.venv/python./app/.venv/python.-m#ipykernel_launcher
09:31:23.137 [debug] start the kernel, options.disableUI=true for /app/1.ipynb
09:31:23.140 [debug] Initialize notebook communications for editor /app/1.ipynb
09:31:23.140 [debug] Resolving notebook UI Comms (resolve) for /app/1.ipynb
09:31:23.141 [debug] initialize CommonMessageCoordinator
09:31:23.143 [debug] Registering commtarget jupyter.widget
09:31:23.143 [debug] IPyWidgetMessageDispatcher.initialize
09:31:23.143 [debug] Attempting to determine version of IPyWidgets
09:31:23.145 [debug] Controller selection change completed
09:31:23.145 [debug] Waiting for IPyWidgets version
09:31:23.145 [debug] Waiting for IPyWidgets version promise
09:31:23.151 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd0026d69f88b532a5652e86a2c423a2c9b09db65f0944232314c8121562750e7b3./app/.venv/python./app/.venv/python.-m#ipykernel_launcher  (Python Path: /app/.venv/bin/python, Venv, .venv, 3.8.2) for '/app/1.ipynb' (disableUI=true)
09:31:23.152 [debug] Creating raw notebook for resource '/app/1.ipynb'
09:31:23.157 [debug] Python API env change detected, update => '/app/.venv/bin/python'
09:31:23.159 [debug] Python API env change detected, update => '/app/.venv/bin/python'
09:31:23.163 [debug] Search for KernelSpecs in Interpreter /app/.venv/bin/python
09:31:23.191 [debug] Full interpreter list is length: 3, /bin/python3::Unknown:/bin/python3, /usr/bin/python3::Unknown:/usr/bin/python3, /app/.venv/bin/python:.venv:Venv:/app/.venv/bin/python
09:31:23.689 [debug] Getting activated env variables, Class name = Ip (started execution), Arg 1: "/app/1.ipynb", Arg 2: "/app/.venv/bin/python", Arg 3: undefined
09:31:23.689 [debug] Get Custom Env Variables, Class name = _m (started execution), Arg 1: "/app/1.ipynb", Arg 2: "RunPythonCode"
09:31:23.690 [debug] Get Custom Env Variables, Class name = _m, completed in 1ms, has a truthy return value, Arg 1: "/app/1.ipynb", Arg 2: "RunPythonCode"
09:31:23.826 [debug] Loading kernelspec from /app/.venv/share/jupyter/kernels/python3/kernel.json for /app/.venv/bin/python
09:31:23.909 [debug] Kernel Specs found in interpreter /app/.venv/bin/python are [{"specFile":"/app/.venv/share/jupyter/kernels/python3/kernel.json","interpreterPath":"/app/.venv/bin/python","isRegisteredByVSC":"registeredByNewVersionOfExt","name":"pythonjvsc74a57bd0026d69f88b532a5652e86a2c423a2c9b09db65f0944232314c8121562750e7b3","argv":["python","-m","ipykernel_launcher","-f","{connection_file}"],"language":"python","executable":"python","display_name":"Python 3 (ipykernel)","metadata":{"debugger":true,"vscode":{"originalSpecFile":"/app/.venv/share/jupyter/kernels/python3/kernel.json","originalDisplayName":"Python 3 (ipykernel)"}}}]
09:31:23.910 [debug] Hiding default kernel spec 'Python 3 (ipykernel)', 'pythonjvsc74a57bd0026d69f88b532a5652e86a2c423a2c9b09db65f0944232314c8121562750e7b3', /python for interpreter /app/.venv/bin/python and spec /app/.venv/share/jupyter/kernels/python3/kernel.json
09:31:23.910 [debug] Kernels for interpreter /app/.venv/bin/python are .jvsc74a57bd0026d69f88b532a5652e86a2c423a2c9b09db65f0944232314c8121562750e7b3./app/.venv/python./app/.venv/python.-m#ipykernel_launcher
09:31:23.912 [debug] Launching kernel .jvsc74a57bd0026d69f88b532a5652e86a2c423a2c9b09db65f0944232314c8121562750e7b3./app/.venv/python./app/.venv/python.-m#ipykernel_launcher for /app/1.ipynb in /app with ports 9001, 9000, 9004, 9002, 9003
09:31:23.961 [debug] Got env vars with python /app/.venv/bin/python, with env var count 40 in 272ms. 
    PATH value is /app/.venv/bin:~/.vscode-server-insiders/bin/c6b48c364dde70c12bf977f1da50acda0fd801e3/bin/remote-cli:~/.nvm/versions/node/v16.14.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Python311/Scripts/:/mnt/c/Python311/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files (x86)/ATI Technologies/ATI.ACE/Core-Static:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files/Microsoft VS Code Insiders/bin:/Docker/host/bin:/mnt/c/Program Files/PowerShell/7/:/mnt/c/Program Files/Git/cmd:/mnt/c/Users/<username>/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/<username>/AppData/Local/Programs/Microsoft VS Code Insiders/bin:/mnt/c/Users/<username>/AppData/Roaming/nvm:/mnt/c/Program Files/nodejs:/mnt/c/Users/<username>/AppData/Local/Programs/Microsoft VS Code Exploration/bin:/mnt/c/Users/<username>/.dotnet/tools:/mnt/c/Users/<username>/.deno/bin:/mnt/c/ProgramData/chocolatey/lib/deno:/mnt/c/Users/<username>/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/<username>/AppData/Local/Microsoft/WindowsApps:/snap/bin and 
    Path value is undefined
09:31:23.961 [debug] Prepend PATH with python bin for /app/.venv/bin/python
09:31:23.961 [debug] Activated Env Variables for /app/.venv/bin/python, 
    PATH value is /app/.venv/bin:~/.vscode-server-insiders/bin/c6b48c364dde70c12bf977f1da50acda0fd801e3/bin/remote-cli:~/.nvm/versions/node/v16.14.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Python311/Scripts/:/mnt/c/Python311/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files (x86)/ATI Technologies/ATI.ACE/Core-Static:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files/Microsoft VS Code Insiders/bin:/Docker/host/bin:/mnt/c/Program Files/PowerShell/7/:/mnt/c/Program Files/Git/cmd:/mnt/c/Users/<username>/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/<username>/AppData/Local/Programs/Microsoft VS Code Insiders/bin:/mnt/c/Users/<username>/AppData/Roaming/nvm:/mnt/c/Program Files/nodejs:/mnt/c/Users/<username>/AppData/Local/Programs/Microsoft VS Code Exploration/bin:/mnt/c/Users/<username>/.dotnet/tools:/mnt/c/Users/<username>/.deno/bin:/mnt/c/ProgramData/chocolatey/lib/deno:/mnt/c/Users/<username>/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/<username>/AppData/Local/Microsoft/WindowsApps:/snap/bin and 
    Path value is undefined
09:31:23.962 [debug] Getting activated env variables, Class name = Ip, completed in 274ms, has a truthy return value, Arg 1: "/app/1.ipynb", Arg 2: "/app/.venv/bin/python", Arg 3: undefined
09:31:23.975 [info] Process Execution: /app/.venv/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
09:31:23.975 [debug] Kernel Env Variables for ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.11.1003351000-linux-x64/temp/jupyter/kernels/pythonjvsc74a57bd0026d69f88b532a5652e86a2c423a2c9b09db65f0944232314c8121562750e7b3/kernel.json, PATH value is /app/.venv/bin:~/.vscode-server-insiders/bin/c6b48c364dde70c12bf977f1da50acda0fd801e3/bin/remote-cli:~/.nvm/versions/node/v16.14.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Python311/Scripts/:/mnt/c/Python311/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files (x86)/ATI Technologies/ATI.ACE/Core-Static:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files/Microsoft VS Code Insiders/bin:/Docker/host/bin:/mnt/c/Program Files/PowerShell/7/:/mnt/c/Program Files/Git/cmd:/mnt/c/Users/<username>/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/<username>/AppData/Local/Programs/Microsoft VS Code Insiders/bin:/mnt/c/Users/<username>/AppData/Roaming/nvm:/mnt/c/Program Files/nodejs:/mnt/c/Users/<username>/AppData/Local/Programs/Microsoft VS Code Exploration/bin:/mnt/c/Users/<username>/.dotnet/tools:/mnt/c/Users/<username>/.deno/bin:/mnt/c/ProgramData/chocolatey/lib/deno:/mnt/c/Users/<username>/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/<username>/AppData/Local/Microsoft/WindowsApps:/snap/bin
09:31:23.991 [info] Process Execution: /app/.venv/bin/python -m ipykernel_launcher --f=~/.local/share/jupyter/runtime/kernel-v2-85706wO79XFb6cWi.json
    > cwd: /app
09:31:24.050 [debug] Getting activated env variables, Class name = Ip (started execution), Arg 1: "/app", Arg 2: "/app/.venv/bin/python", Arg 3: undefined
09:31:24.050 [debug] Get Custom Env Variables, Class name = _m (started execution), Arg 1: "/app", Arg 2: "RunPythonCode"
09:31:24.051 [debug] Get Custom Env Variables, Class name = _m, completed in 1ms, has a truthy return value, Arg 1: "/app", Arg 2: "RunPythonCode"
09:31:24.052 [debug] Got env vars with python /app/.venv/bin/python, with env var count 40 in 2ms. 
    PATH value is /app/.venv/bin:~/.vscode-server-insiders/bin/c6b48c364dde70c12bf977f1da50acda0fd801e3/bin/remote-cli:~/.nvm/versions/node/v16.14.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Python311/Scripts/:/mnt/c/Python311/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files (x86)/ATI Technologies/ATI.ACE/Core-Static:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files/Microsoft VS Code Insiders/bin:/Docker/host/bin:/mnt/c/Program Files/PowerShell/7/:/mnt/c/Program Files/Git/cmd:/mnt/c/Users/<username>/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/<username>/AppData/Local/Programs/Microsoft VS Code Insiders/bin:/mnt/c/Users/<username>/AppData/Roaming/nvm:/mnt/c/Program Files/nodejs:/mnt/c/Users/<username>/AppData/Local/Programs/Microsoft VS Code Exploration/bin:/mnt/c/Users/<username>/.dotnet/tools:/mnt/c/Users/<username>/.deno/bin:/mnt/c/ProgramData/chocolatey/lib/deno:/mnt/c/Users/<username>/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/<username>/AppData/Local/Microsoft/WindowsApps:/snap/bin and 
    Path value is undefined
09:31:24.052 [debug] Prepend PATH with python bin for /app/.venv/bin/python
09:31:24.052 [debug] Activated Env Variables for /app/.venv/bin/python, 
    PATH value is /app/.venv/bin:~/.vscode-server-insiders/bin/c6b48c364dde70c12bf977f1da50acda0fd801e3/bin/remote-cli:~/.nvm/versions/node/v16.14.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Python311/Scripts/:/mnt/c/Python311/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files (x86)/ATI Technologies/ATI.ACE/Core-Static:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files/Microsoft VS Code Insiders/bin:/Docker/host/bin:/mnt/c/Program Files/PowerShell/7/:/mnt/c/Program Files/Git/cmd:/mnt/c/Users/<username>/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/<username>/AppData/Local/Programs/Microsoft VS Code Insiders/bin:/mnt/c/Users/<username>/AppData/Roaming/nvm:/mnt/c/Program Files/nodejs:/mnt/c/Users/<username>/AppData/Local/Programs/Microsoft VS Code Exploration/bin:/mnt/c/Users/<username>/.dotnet/tools:/mnt/c/Users/<username>/.deno/bin:/mnt/c/ProgramData/chocolatey/lib/deno:/mnt/c/Users/<username>/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/<username>/AppData/Local/Microsoft/WindowsApps:/snap/bin and 
    Path value is undefined
09:31:24.052 [debug] Getting activated env variables, Class name = Ip, completed in 2ms, has a truthy return value, Arg 1: "/app", Arg 2: "/app/.venv/bin/python", Arg 3: undefined
09:31:24.065 [info] Process Execution: /app/.venv/bin/python -m pip list
09:31:24.250 [debug] Full interpreter list is length: 3, /bin/python3::Unknown:/bin/python3, /usr/bin/python3::Unknown:/usr/bin/python3, /app/.venv/bin/python:.venv:Venv:/app/.venv/bin/python
09:31:24.250 [debug] Refreshed Environments
09:31:24.291 [debug] ipykernel version & path 6.27.1, /app/.venv/lib/python3.8/site-packages/ipykernel/__init__.py for /app/.venv/bin/python
09:31:24.558 [debug] Kernel output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-v2-85706wO79XFb6cWi.json

09:31:24.659 [debug] Waiting for Raw Session to be ready in postStartRawSession
09:31:24.659 [debug] Waiting for Raw session to be ready, status: connected
09:31:24.660 [debug] Raw session connected
09:31:24.660 [debug] Waiting for Raw session to be ready
09:31:24.660 [debug] Waited for Raw session to be ready & got status: connected
09:31:24.660 [debug] Successfully waited for Raw Session to be ready in postStartRawSession
09:31:24.660 [debug] Kernel status is 'unknown' before requesting kernel info and after ready
09:31:24.660 [debug] Sending request for kernelInfo
09:31:24.738 [debug] Got response for requestKernelInfo
09:31:24.738 [debug] Successfully completed postStartRawSession
09:31:24.741 [debug] Executing silently Code (idle) = import sys as _VSCODE_sys\nprint(_VSCODE_sys.executable); del _VSCODE_sys
09:31:24.754 [debug] Executing silently Code (completed) = import sys as _VSCODE_sys\nprint(_VSCODE_sys.executable); del _VSCODE_sys with 1 output(s)
09:31:24.754 [debug] End sendTelemetryForPythonKernelExecutable after 13ms
09:31:24.754 [debug] Started running kernel initialization for /app/1.ipynb
09:31:24.755 [debug] Executing silently Code (idle) = try:\nimport ipywidgets as _VSCODE_ipywidgets\nprint("e976ee50-99ed-4aba-9b6b-9dcd5634d07d:IPy
09:31:24.764 [debug] Executing silently Code (completed) = try:\nimport ipywidgets as _VSCODE_ipywidgets\nprint("e976ee50-99ed-4aba-9b6b-9dcd5634d07d:IPy with 0 output(s)
09:31:24.764 [debug] Determined IPyWidgets Version as undefined
09:31:24.766 [debug] Executing silently Code (idle) = import os as _VSCODE_os\nimport sys as _VSCODE_sys\n%cd "/"\nif _VSCODE_os.getcwd() not in _VSCODE_sys.
09:31:24.780 [debug] Executing silently Code (completed) = import os as _VSCODE_os\nimport sys as _VSCODE_sys\n%cd "/"\nif _VSCODE_os.getcwd() not in _VSCODE_sys. with 1 output(s)
09:31:24.780 [debug] Requesting Kernel info
09:31:24.781 [debug] Got Kernel info
09:31:24.781 [debug] End running kernel initialization, now waiting for idle
09:31:24.781 [debug] Waiting for idle on (kernel): 53776026-84a6-434b-bbc0-51c9d670d9cf -> idle
09:31:24.781 [debug] Finished waiting for idle on (kernel): 53776026-84a6-434b-bbc0-51c9d670d9cf -> idle
09:31:24.781 [debug] End running kernel initialization, session is idle
09:31:24.784 [debug] IPyWidgetScriptSource.initialize
09:31:24.784 [debug] IPyWidgetMessageDispatcher.initialize
09:31:24.786 [debug] getDataDirsImpl, Class name = rn (started execution), Arg 1: "/app/1.ipynb", Arg 2: "/app/.venv/bin/python"
09:31:24.786 [debug] Get Custom Env Variables, Class name = _m (started execution), Arg 1: undefined, Arg 2: "RunPythonCode"
09:31:24.788 [debug] Get Custom Env Variables, Class name = _m, completed in 2ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
09:31:24.788 [debug] Jupyter Paths : 
09:31:24.841 [info] Process Execution: /app/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.11.1003351000-linux-x64/pythonFiles/printJupyterDataDir.py
09:31:24.875 [debug] getDataDirsImpl, Class name = rn, completed in 89ms, has a truthy return value, Arg 1: "/app/1.ipynb", Arg 2: "/app/.venv/bin/python"
09:31:25.250 [info] End refreshing Kernel Picker (1701451879739)
09:31:43.021 [info] Handle Execution of Cells 0 for /app/1.ipynb
09:31:43.030 [debug] Cell Index:0 sent to kernel
09:31:43.041 [debug] Start cell 0 execution @ 1701451903040 (clear output)
09:31:43.042 [info] Kernel acknowledged execution of cell 0 @ 1701451903040
09:31:43.049 [info] End cell 0 execution after 0.009s, completed @ 1701451903049, started @ 1701451903040
09:31:43.050 [debug] Cell 0 executed with state Success
```

</details>
