### ISSUE TITLE
Python: Launch TensorBoard uses incorrect conda environment

### ISSUE THREAD

**Issue by Jbartlett6** [microsoft/vscode-jupyter#14009]
Type: <b>Bug</b>

# Behaviour
When running `Python: Launch Tensorboard` from the Command Palette I get an error stating that the TensorBoard package is required:

![image](https://github.com/microsoft/vscode-python/assets/63283592/867b39ff-1bf9-42a0-84e9-9e81a11e4123)

I can check in my conda environment to see that TensorBoard is installed: 

```
conda list -n jxb_env tensorboard*
# packages in environment at /bask/projects/d/duanj-ai-imaging/miniconda3/envs/jxb_env:
#
# Name                    Version                   Build  Channel
tensorboard               2.10.0             pyhd8ed1ab_1    conda-forge
tensorboard-data-server   0.6.0            py38h2b97feb_0    conda-forge
tensorboard-plugin-wit    1.8.1              pyhd8ed1ab_0    conda-forge
```

When I proceed to install tensorboard, as prompted, the conda environment I am working in cannot be found. Instead, an attempt is made to install TensorBoard to my conda environment within my already launched environment (`miniconda3/envs/jxb_env/envs/jxb_env`): 

```
/bask/projects/d/duanj-ai-imaging/miniconda3/envs/jxb_env/bin/python3 /bask/homes/j/jxb1336/.vscode-server/extensions/ms-python.python-2023.12.0/pythonFiles/shell_exec.py conda install -c conda-forge --name jxb_env tensorboard -y /tmp/tmp-4037458U3MGZRltoShE.log
Executing command in shell >> conda install -c conda-forge --name jxb_env tensorboard -y

EnvironmentLocationNotFound: Not a conda environment: /bask/projects/d/duanj-ai-imaging/miniconda3/envs/jxb_env/envs/jxb_env

Traceback (most recent call last):
  File "/bask/homes/j/jxb1336/.vscode-server/extensions/ms-python.python-2023.12.0/pythonFiles/shell_exec.py", line 26, in <module>
    subprocess.check_call(shell_args, stdout=sys.stdout, stderr=sys.stderr)
  File "/bask/projects/d/duanj-ai-imaging/miniconda3/envs/jxb_env/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'install', '-c', 'conda-forge', '--name', 'jxb_env', 'tensorboard', '-y']' returned non-zero exit status 1.
```

## Expected vs. Actual

Expected: To launch Tensorboard extensions and to be able to select --logdir

## Steps to reproduce:
1. Run `Python: Select Interpreter` from the Command Palette and select required conda environment. 
2. Run `Python: LaunchTensorboard` from the Command Palette. (Result: Get error stating TensorBoard is not installed)
3. When prompted, attempt to install TensorBoard (Result: Cannot find environment to install tensorboard). 

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.13
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2023.12.0
VS Code version: Code 1.80.2 (2ccd690cbff1569e4a83d7c43d45101f817401dc, 2023-07-27T20:40:28.909Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Remote OS version: Linux x64 4.18.0-348.2.1.el8_5.x86_64
Remote OS version: Linux x64 4.18.0-348.2.1.el8_5.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.67GB (5.44GB free)|
|Process Argv|--crash-reporter-id f04932ae-1681-4cbf-95d6-1e055d080d24|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: Basknode|
|OS|Linux x64 4.18.0-348.2.1.el8_5.x86_64|
|CPUs|Intel(R) Xeon(R) Platinum 8360Y CPU @ 2.40GHz (144 x 858)|
|Memory (System)|503.53GB (460.64GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: Bask|
|OS|Linux x64 4.18.0-348.2.1.el8_5.x86_64|
|CPUs|Intel(R) Xeon(R) Silver 4214 CPU @ 2.20GHz (48 x 2200)|
|Memory (System)|188.58GB (167.21GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
282f8724:30602487
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
a2ce3375:30757347
57b77579:30736110
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
hideindicator:30785051
pythongtdpath:30769146
i26e3531:30792625
gsofb:30797622
pythonnosmt12:30797651
pythonnoceb:30797650
e537b577:30795824
dsvsc013:30795093
dsvsc014cf:30797590

```

</details>

**Comment by DonJayamanne** [comment]
@karthiknadig 
Looks like the code is failing over in the Python exetnsion, the path to the conda environment is wrong, see the error message

> /bask/projects/d/duanj-ai-imaging/miniconda3/envs/jxb_env/bin/python3 /bask/homes/j/jxb1336/.vscode-server/extensions/ms-python.python-2023.12.0/pythonFiles/shell_exec.py conda install -c conda-forge --name jxb_env tensorboard -y /tmp/tmp-4037458U3MGZRltoShE.log
Executing command in shell >> conda install -c conda-forge --name jxb_env tensorboard -y
>
> EnvironmentLocationNotFound: Not a conda environment: /bask/projects/d/duanj-ai-imaging/miniconda3/envs/jxb_env/envs/jxb_env
>
>Traceback (most recent call last):
  File "/bask/homes/j/jxb1336/.vscode-server/extensions/ms-python.python-2023.12.0/pythonFiles/shell_exec.py", line 26, in <module>
    subprocess.check_call(shell_args, stdout=sys.stdout, stderr=sys.stderr)

**Comment by karrtikr** [comment]
Moving over to Python extension to investigate further.
