### ISSUE TITLE
Kernel crashes while loading pre-trained BLIP-2 model

### ISSUE THREAD

**Issue by lzytitan494** [microsoft/vscode-jupyter#14108]
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I tried to run the BLIP-2 model for Image Captioning from this blog https://huggingface.co/blog/blip-2. All cells above it work fine, but as soon as this cell runs for about a minute kernel dies.
`model = Blip2ForConditionalGeneration.from_pretrained("Salesforce/blip2-opt-2.7b", torch_dtype=torch.float16)`
![Screenshot 2023-08-12 005642](https://github.com/microsoft/vscode-jupyter/assets/97222085/42647cdf-0b84-41e8-b254-010c795ecf97)

### VS Code Version

1.81.1

### Jupyter Extension Version

v2023.7.1002162226

### Jupyter logs

```shell
00:00:53.273 [info] Kernel acknowledged execution of cell 2 @ 1691778653269
00:01:54.379 [error] Disposing session as kernel process died ExitCode: undefined, Reason: 
00:01:54.413 [info] Dispose Kernel process 8995.
00:01:54.422 [error] Raw kernel process exited code: undefined
00:01:54.504 [error] Error in waiting for cell to complete Error: Canceled future for execute_request message before replies were done
    at t.KernelShellFutureHandler.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.7.1002162226-linux-x64/out/extension.node.js:2:32375)
    at ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.7.1002162226-linux-x64/out/extension.node.js:2:51427
    at Map.forEach (<anonymous>)
    at y._clearKernelState (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.7.1002162226-linux-x64/out/extension.node.js:2:51412)
    at y.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.7.1002162226-linux-x64/out/extension.node.js:2:44894)
    at ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.7.1002162226-linux-x64/out/extension.node.js:24:114648
    at ae (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.7.1002162226-linux-x64/out/extension.node.js:2:1588852)
    at rv.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.7.1002162226-linux-x64/out/extension.node.js:24:114624)
    at sv.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.7.1002162226-linux-x64/out/extension.node.js:24:117994)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
00:01:54.521 [warn] Cell completed with errors {
  message: 'Canceled future for execute_request message before replies were done'
}
00:01:54.542 [info] End cell 2 execution @ 1691778714538, started @ 1691778653269, elapsed time = 61.269s
00:01:54.546 [warn] Cancel all remaining cells due to cancellation or failure in execution
```

### Coding Language and Runtime Version

Python v3.10.12

### Running Jupyter locally or remotely?

Local

**Comment by lzytitan494** [comment]
Yes, It ran for the first time, but after that, I cannot run this.

**Comment by lzytitan494** [comment]
It got resolved there was some file access error on my side, after that it works fine.
