### ISSUE TITLE
Add support for custom Kernel Launchers/Provisioners

### ISSUE THREAD

**Issue by jrowen** [microsoft/vscode-jupyter#14172]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When using a custom kernel via the extension, the metadata.kernel_provisioner details appear to be ignored.

For example, install some custom provisions using `pip install gateway-provisioners` (https://github.com/jupyter-server/gateway_provisioners).  You can validate they installed correctly using `jupyter kernelspec provisioners`.  Now create a `kernel.spec` that uses a custom provisioner (e.g. `jupyter docker-spec install`).  

When switching to the custom kernel, I see an error and log output like shown below, indicating that the custom provisioner is being ignored.  If instead I run from a terminal (`jupyter console --kernel docker_python`), I can see that these variables are defined, and therefore the custom provisioner is being used.

### VS Code Version

1.81.1

### Jupyter Extension Version

v2023.7.1002162226

### Jupyter logs

```shell
20:19:51.499 [debug] KernelProvider switched kernel to id = .docker_python./python./.python#~/.local/share/jupyter/kernels/docker_python/scripts/launch_docker.py#--kernel-id#{kernel_id}#--port-range#{port_range}#--response-address#{response_address}#--public-key#{public_key}#--kernel-class-name#ipykernel.ipkernel.ipythonkernel#--connection-file#{connection_file}
```

### Coding Language and Runtime Version

Python v3.9

### Running Jupyter locally or remotely?

Remote

**Comment by DonJayamanne** [comment]
> When switching to the custom kernel, I see an error and log output like shown below, indicating that the custom provisioner is being ignored.

Please can you share the logs, you forgot to share that information

**Comment by jrowen** [comment]
I actually included the one log line that shows the launch parameters are not being resolved.  Let me know if you need more detail.

**Comment by DonJayamanne** [comment]
Thats not the full argument list, that is just an ID generated (used for internal use).

>  I see an error and log o

I do not see any errors in the logs you have provided.
Please could you share that.

**Comment by jrowen** [comment]
Here is a more detailed log.  In it, you can see parameters like `{port_range}` aren't being resolved when switching to the new kernel, which seems to indicate the custom provisioner is being ignored.
```
13:41:40.620 [debug] KernelProvider switched kernel to id = .docker_python./python./.python#~/.local/share/jupyter/kernels/docker_python/scripts/launch_docker.py#--kernel-id#{kernel_id}#--port-range#{port_range}#--response-address#{response_address}#--public-key#{public_key}#--kernel-class-name#ipykernel.ipkernel.ipythonkernel
13:41:40.621 [debug] Initialize notebook communications for editor /mnt/efsdev/<username>/test.ipynb
13:41:40.622 [debug] Resolving notebook UI Comms (resolve) for /mnt/efsdev/<username>/test.ipynb
13:41:40.623 [debug] initialize CommonMessageCoordinator
13:41:40.624 [debug] Registering commtarget jupyter.widget
13:41:40.624 [debug] IPyWidgetMessageDispatcher.initialize
13:41:40.625 [debug] Attempting to determine version of IPyWidgets
13:41:40.626 [debug] Controller selection change completed
13:41:40.626 [debug] Waiting for IPyWidgets version promise
13:41:40.626 [debug] Version of IPyWidgets 7 determined after 0.001s
13:41:41.319 [debug] IPyWidgetMessageDispatcher.initialize
13:41:41.319 [debug] Web view is ready to receive widget messages
13:41:51.670 [info] Handle Execution of Cells 1 for /mnt/efsdev/<username>/test.ipynb
13:41:51.672 [debug] start the kernel, options.disableUI=false for /mnt/efsdev/<username>/test.ipynb
13:41:51.674 [info] Starting Kernel startUsingLocalKernelSpec, .docker_python./python./.python#~/.local/share/jupyter/kernels/docker_python/scripts/launch_docker.py#--kernel-id#{kernel_id}#--port-range#{port_range}#--response-address#{response_address}#--public-key#{public_key}#--kernel-class-name#ipykernel.ipkernel.ipythonkernel  for '/mnt/efsdev/<username>/test.ipynb' (disableUI=false)
13:41:51.676 [debug] Creating raw notebook for resource '/mnt/efsdev/<username>/test.ipynb'
13:41:51.679 [debug] Kernel Launcher. launch, Class name = Ky (started execution), Arg 1: "~/.local/share/jupyter/kernels/docker_python/scripts/launch_docker.py#--kernel-id#{kernel_id}#--port-range#{port_range}#--response-address#{response_address}#--public-key#{public_key}#--kernel-class-name#ipykernel.ipkernel.ipythonkernel", Arg 2: 60000, Arg 3: "/mnt/efsdev/<username>/test.ipynb", Arg 4: "/mnt/efsdev/<username>/nlp/sagemaker/test", Arg 5: ""
13:41:51.699 [info] Dispose Kernel process undefined.
13:41:51.700 [error] Kernel Launcher. launch, Class name = Ky, completed in 21ms, has a falsy return value, Arg 1: "~/.local/share/jupyter/kernels/docker_python/scripts/launch_docker.py#--kernel-id#{kernel_id}#--port-range#{port_range}#--response-address#{response_address}#--public-key#{public_key}#--kernel-class-name#ipykernel.ipkernel.ipythonkernel", Arg 2: 60000, Arg 3: "/mnt/efsdev/<username>/test.ipynb", Arg 4: "/mnt/efsdev/<username>/nlp/sagemaker/test", Arg 5: "" [Error: Connection file not found in kernelspec json args, python ~/.local/share/jupyter/kernels/docker_python/scripts/launch_docker.py --kernel-id {kernel_id} --port-range {port_range} --response-address {response_address} --public-key {public_key} --kernel-class-name ipykernel.ipkernel.IPythonKernel
	at Ly.updateConnectionArgs (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.7.1002162226/out/extension.node.js:24:94424)
	at Ly.launch (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.7.1002162226/out/extension.node.js:24:90548)
	at Ly.i.value (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.7.1002162226/out/extension.node.js:2:1695691)
	at Ky.launchProcess (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.7.1002162226/out/extension.node.js:24:101920)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.7.1002162226/out/extension.node.js:24:100416]
13:41:51.702 [debug] Disposed Kernel process undefined.
13:41:51.702 [error] Failed to connect raw kernel session: Error: Connection file not found in kernelspec json args, python ~/.local/share/jupyter/kernels/docker_python/scripts/launch_docker.py --kernel-id {kernel_id} --port-range {port_range} --response-address {response_address} --public-key {public_key} --kernel-class-name ipykernel.ipkernel.IPythonKernel
13:41:51.702 [debug] Shutdown session -- complete
```
In this case, the `kernel.json` file is the following
```
{
  "argv": [
    "python",
    "/home/<username>/.local/share/jupyter/kernels/docker_python/scripts/launch_docker.py",
    "--kernel-id",
    "{kernel_id}",
    "--port-range",
    "{port_range}",
    "--response-address",
    "{response_address}",
    "--public-key",
    "{public_key}",
    "--kernel-class-name",
    "ipykernel.ipkernel.IPythonKernel"
  ],
  "display_name": "Docker Python",
  "language": "python3",
  "interrupt_mode": "signal",
  "metadata": {
    "debugger": true,
    "kernel_provisioner": {
      "provisioner_name": "docker-provisioner",
      "config": {
        "image_name": "da4cbecb-6ec7-4e3e-93c1-853d0cf6ca3c",
        "launch_timeout": 30,
        "port_range": "40000..60000"
      }
    }
  }
}
```
If I switch the kernel via the command line, I see these parameters being resolved.
```
$ jupyter console --kernel docker_python
[ZMQTerminalIPythonApp] ResponseManager is bound to port 8877 for remote kernel connection information.
[ZMQTerminalIPythonApp] DockerProvisioner: kernel launched. Kernel image: da4cbecb-6ec7-4e3e-93c1-853d0cf6ca3c, KernelID: 830bb406-83e9-4201-ae11-7dd08b93cc26, cmd: '['python', '/home/<username>/.local/share/jupyter/kernels/docker_python/scripts/launch_docker.py', '--kernel-id', '830bb406-83e9-4201-ae11-7dd08b93cc26', '--port-range', '40000..60000', '--response-address', '172.17.0.2:8877', '--public-key', 'MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCdSOltNdoeSJD2G9VofQO3d2nxIdgXHWzsW13s5ZAj3uWqFuiTxHIiiWRWOLNqUO2/LHOqdVoAWsnTfBRxbTYoeaa7kwsXpYnILioRo3NqKyMVxL/PgB8ka0cD0IB4nQdaDZfgXZOrUbyzUpxyZzV3LzTffj6a+UefMYqJ3WL1ewIDAQAB', '--kernel-class-name', 'ipykernel.ipkernel.IPythonKernel']'
```

**Comment by DonJayamanne** [comment]
Thanks, I think i understand whats going on here
Will look into this

**Comment by DonJayamanne** [comment]
I've had a look at this, and this is a custom Jupyter Server plugin that provides its own way to launch kernels.
The Jupyter extension in VS Code currently only supports one way of launching Jupyter kernels, and thats the standard model of launching local jupyter kernels.


Updating this as a feature request.

**Comment by DonJayamanne** [comment]
Its been a while and there haven't been enough upvotes on this issue.
Hence closing this
