### ISSUE TITLE
Error: notebook controller is DISPOSED

### ISSUE THREAD

**Issue by detrin** [microsoft/vscode-jupyter#14203]
I am coming from https://github.com/microsoft/vscode-jupyter/discussions/11653#discussioncomment-6840992

## Environment data

-   VS Code version:
> 1.80.1
> 74f6148eb9ea00507ec113ec51c489d6ffb4b771
> arm64
-   Jupyter Extension version (available under the Extensions sidebar): Jupyter==v2023.6.1101941928
-   Python Extension version (available under the Extensions sidebar):python==v2023.14.0
-   OS (Windows | Mac | Linux distro) and version: mac
-   Python and/or Anaconda version: python3.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local 

## Expected behaviour

Not crashing.

## Actual behaviour

![image](https://github.com/microsoft/vscode-jupyter/assets/18104456/a6f997cc-82c3-4361-8dac-eae3eb3ae1c1)

## Steps to reproduce:

No idea, sometimes it crashes, especially today is a bad day

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
15:42:01.152 [debug] Initialize notebook communications for editor ~/Documents/projects/PSW_devel/workflow/Workflow.ipynb
15:42:01.152 [debug] Resolving notebook UI Comms (resolve) for ~/Documents/projects/PSW_devel/workflow/Workflow.ipynb
15:42:01.152 [debug] initialize CommonMessageCoordinator
15:42:01.153 [debug] IPyWidgetScriptSource.initialize
15:42:01.153 [debug] IPyWidgetMessageDispatcher.initialize
15:42:01.153 [debug] Attempting to determine version of IPyWidgets
15:42:01.154 [debug] Controller selection change completed
15:42:01.154 [debug] Waiting for IPyWidgets version promise
15:42:01.154 [debug] Version of IPyWidgets 7 determined after 0.001s
15:42:01.154 [debug] Getting activated env variables, Class name = ta (started execution), Arg 1: "~/Documents/projects/PSW_devel/workflow", Arg 2: <Uri:~/Documents/projects/PSW_devel/workflow/env/bin/python>, Arg 3: undefined
15:42:01.155 [debug] Get Custom Env Variables, Class name = Jc (started execution), Arg 1: "~/Documents/projects/PSW_devel/workflow", Arg 2: "RunPythonCode"
15:42:01.155 [debug] Get Custom Env Variables, Class name = Jc, completed in 0ms, has a truthy return value, Arg 1: "~/Documents/projects/PSW_devel/workflow", Arg 2: "RunPythonCode"
15:42:01.155 [debug] Got env vars with python ~/Documents/projects/PSW_devel/workflow/env/bin/python, with env var count 61 in 0ms. 
    PATH value is ~/Documents/projects/PSW_devel/workflow/env/bin:~/.rye/shims:~/.pyenv/shims:~/.nvm/versions/node/v18.9.0/bin:~/opt/miniconda3/condabin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Applications/Racket v8.7/bin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:~/.cargo/bin and 
    Path value is undefined
15:42:01.155 [debug] Prepend PATH with python bin for ~/Documents/projects/PSW_devel/workflow/env/bin/python, 
    PATH value is ~/Documents/projects/PSW_devel/workflow/env/bin:~/.rye/shims:~/.pyenv/shims:~/.nvm/versions/node/v18.9.0/bin:~/opt/miniconda3/condabin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Applications/Racket v8.7/bin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:~/.cargo/bin and 
    Path value is undefined
15:42:01.156 [debug] Activated Env Variables for ~/Documents/projects/PSW_devel/workflow/env/bin/python, 
    PATH value is ~/Documents/projects/PSW_devel/workflow/env/bin:~/.rye/shims:~/.pyenv/shims:~/.nvm/versions/node/v18.9.0/bin:~/opt/miniconda3/condabin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Applications/Racket v8.7/bin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:~/.cargo/bin and 
    Path value is undefined
15:42:01.156 [debug] Getting activated env variables, Class name = ta, completed in 2ms, has a truthy return value, Arg 1: "~/Documents/projects/PSW_devel/workflow", Arg 2: <Uri:~/Documents/projects/PSW_devel/workflow/env/bin/python>, Arg 3: undefined
15:42:01.157 [info] Process Execution: ~/Documents/projects/PSW_devel/workflow/env/bin/python -m pip list
15:42:01.158 [info] Handle Execution of Cells 2,4,6,8,10,11,13,15,17,18,20,22,24,25,27,30,32,34,36,38,39,40,42,44,45,47,48,51,53,55,57,59,62,63,64,66,67,69,70,73,74,77,78,80,81,82,84,87,88,90,94,96,101,103,105,107,109,110,111,112,115,117,119,121,124,126,128,130,132,135,136,137,138,139,141,143,147,148,150,152,154,157,158,160,164,166,167,168,169,171,172,174,176,177,181,182,184,185,187,188,189,191,193,195,197,199,201,204,206,207,209,211,213,214,215,216,218,220,222,224,227,229,230,231,232,234,236,237,239,241,243,244,245,247,248,249,251,254,256,258,260,261,262,263,266,268,270,272,273,275,276,281,283,285,287,289,291,293,294,296,298,299,300,302,303,305 for ~/Documents/projects/PSW_devel/workflow/Workflow.ipynb
15:42:01.158 [debug] start the kernel, options.disableUI=false for ~/Documents/projects/PSW_devel/workflow/Workflow.ipynb
15:42:01.158 [debug] start the kernel, options.disableUI=false for ~/Documents/projects/PSW_devel/workflow/Workflow.ipynb
15:42:01.158 [debug] start the kernel, options.disableUI=false for ~/Documents/projects/PSW_devel/workflow/Workflow.ipynb
15:42:01.158 [debug] start the kernel, options.disableUI=false for ~/Documents/projects/PSW_devel/workflow/Workflow.ipynb
15:42:01.158 [debug] start the kernel, options.disableUI=false for ~/Documents/projects/PSW_devel/workflow/Workflow.ipynb
15:42:01.158 [debug] start the kernel, options.disableUI=false for ~/Documents/projects/PSW_devel/workflow/Workflow.ipynb
15:42:01.158 [debug] start the kernel, options.disableUI=false for ~/Documents/projects/PSW_devel/workflow/Workflow.ipynb
15:42:01.158 [debug] start the kernel, options.disableUI=false for ~/Documents/projects/PSW_devel/workflow/Workflow.ipynb
15:42:01.158 [debug] start the kernel, options.disableUI=false for ~/Documents/projects/PSW_devel/workflow/Workflow.ipynb
15:42:01.158 [debug] start the kernel, options.disableUI=false for ~/Documents/projects/PSW_devel/workflow/Workflow.ipynb
15:42:01.158 [debug] start the kernel, options.disableUI=false for ~/Documents/projects/PSW_devel/workflow/Workflow.ipynb

similar output skipped due to the length

15:42:01.160 [debug] start the kernel, options.disableUI=false for ~/Documents/projects/PSW_devel/workflow/Workflow.ipynb
15:42:01.160 [debug] start the kernel, options.disableUI=false for ~/Documents/projects/PSW_devel/workflow/Workflow.ipynb
15:42:01.178 [error] Error in execution Error: notebook controller is DISPOSED
    at Object.createNotebookCellExecution (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:101:96540)
    at Function.create (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:17:182931)
    at Function.getOrCreate (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:17:182804)
    at new lg (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:24:22900)
    at Function.fromCell (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:24:23088)
    at cg.create (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:24:22072)
    at ug.queueCell (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:24:30547)
    at pg.executeCell (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:24:34890)

similar output skipped due to the length

15:42:01.219 [error] Error in execution (get message for cell) Error: notebook controller is DISPOSED
    at Object.createNotebookCellExecution (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:101:96540)
    at Function.create (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:17:182931)
    at Function.getOrCreate (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:17:182804)
    at new lg (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:24:22900)
    at Function.fromCell (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:24:23088)
    at cg.create (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:24:22072)
    at ug.queueCell (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:24:30547)
    at pg.executeCell (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:24:34890)
15:42:01.219 [error] Error in execution Error: notebook controller is DISPOSED
    at Object.createNotebookCellExecution (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:101:96540)
    at Function.create (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:17:182931)
    at Function.getOrCreate (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:17:182804)
    at new lg (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:24:22900)
    at Function.fromCell (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:24:23088)
    at cg.create (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:24:22072)
    at ug.queueCell (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:24:30547)
    at pg.executeCell (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:24:34890)
15:42:01.219 [error] Error in execution (get message for cell) Error: notebook controller is DISPOSED
    at Object.createNotebookCellExecution (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:101:96540)
    at Function.create (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:17:182931)
    at Function.getOrCreate (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:17:182804)
    at new lg (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:24:22900)
    at Function.fromCell (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:24:23088)
    at cg.create (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:24:22072)
    at ug.queueCell (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:24:30547)
    at pg.executeCell (~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/out/extension.node.js:24:34890)
15:42:01.221 [debug] Start cell 4 execution @ undefined
15:42:01.221 [debug] Start cell 6 execution @ undefined

similar output skipped due to the length

15:42:01.244 [debug] Start cell 302 execution @ undefined
15:42:01.244 [debug] Start cell 303 execution @ undefined
15:42:01.244 [debug] Start cell 305 execution @ undefined
15:42:01.252 [debug] Execution Request Sent to Kernel for cell 2
15:42:05.661 [info] End cell 4 execution @ undefined, started @ undefined, elapsed time = 0s
15:42:05.661 [info] End cell 6 execution @ undefined, started @ undefined, elapsed time = 0s
15:42:05.661 [info] End cell 8 execution @ undefined, started @ undefined, elapsed time = 0s

similar output skipped due to the length

15:42:05.732 [info] End cell 300 execution @ undefined, started @ undefined, elapsed time = 0s
15:42:05.732 [info] End cell 302 execution @ undefined, started @ undefined, elapsed time = 0s
15:42:05.733 [info] End cell 303 execution @ undefined, started @ undefined, elapsed time = 0s
15:42:05.733 [info] End cell 305 execution @ undefined, started @ undefined, elapsed time = 0s
15:42:05.759 [debug] IPyWidgetMessageDispatcher.initialize
15:42:05.759 [debug] Web view is ready to receive widget messages
15:42:07.449 [debug] Widget Message: Received IPyWidgets_kernelOptions in ScriptManager
15:42:07.449 [debug] Widget Message: Received IPyWidgetMessages.IPyWidgets_kernelOptions
15:42:07.450 [debug] IPyWidgetMessageDispatcher.initialize
15:42:07.450 [debug] IPyWidgetMessageDispatcher.initialize
15:42:07.450 [debug] Widget Message: Waiting for model to be available before rendering it 9b672f456cad410ea8e7b6eefba66430
15:42:07.450 [debug] Widget Message: Waiting for model to be available before rendering it f3b87a1209eb45a58970c67e652577c4
15:42:07.450 [debug] Widget Message: Received IPyWidgets_kernelOptions in ScriptManager
15:42:07.450 [debug] Widget Message: Received IPyWidgetMessages.IPyWidgets_kernelOptions
15:42:07.451 [debug] Widget Message: Received IPyWidgets_kernelOptions in ScriptManager
15:42:07.451 [debug] Widget Message: Received IPyWidgetMessages.IPyWidgets_kernelOptions
15:42:07.451 [debug] IPyWidgetMessageDispatcher.initialize
15:42:07.451 [debug] IPyWidgetMessageDispatcher.initialize
15:42:07.452 [debug] Widget Message: data-base-url set to https://file%2B.vscode-resource.vscode-cdn.net~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/temp/scripts/249b9e76a749eefd6484007bcb94ca207284e7e217bd27f3024f9a011f594632/jupyter
15:42:07.453 [debug] Widget Message: Received IPyWidgets_kernelOptions in ScriptManager
15:42:07.453 [debug] Widget Message: Received IPyWidgetMessages.IPyWidgets_kernelOptions
15:42:07.453 [debug] Widget Message: data-base-url set to https://file%2B.vscode-resource.vscode-cdn.net~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/temp/scripts/249b9e76a749eefd6484007bcb94ca207284e7e217bd27f3024f9a011f594632/jupyter
15:42:07.453 [debug] Widget Message: Received IPyWidget scripts [{"moduleName":"jupyterlab-plotly","scriptUri":"https://file%2B.vscode-resource.vscode-cdn.net~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/temp/scripts/249b9e76a749eefd6484007bcb94ca207284e7e217bd27f3024f9a011f594632/jupyter/nbextensions/jupyterlab-plotly/index","source":"local"}]
15:42:07.454 [debug] Widget Message: Source for IPyWidget jupyterlab-plotly found in local @ https://file%2B.vscode-resource.vscode-cdn.net~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/temp/scripts/249b9e76a749eefd6484007bcb94ca207284e7e217bd27f3024f9a011f594632/jupyter/nbextensions/jupyterlab-plotly/index.
15:42:07.454 [debug] Widget Message: Registering IPyWidget jupyterlab-plotly found in https://file%2B.vscode-resource.vscode-cdn.net~/.vscode/extensions/ms-toolsai.jupyter-2023.6.1101941928-darwin-arm64/temp/scripts/249b9e76a749eefd6484007bcb94ca207284e7e217bd27f3024f9a011f594632/jupyter/nbextensions/jupyterlab-plotly/index.
15:42:07.546 [debug] Start cell 2 execution @ 1693230127500 (clear output)
15:42:07.546 [info] Kernel acknowledged execution of cell 2 @ 1693230127500
15:42:07.548 [info] End cell 2 execution @ 1693230127546, started @ 1693230127500, elapsed time = 0.046s
15:42:07.549 [debug] Cell 2 executed with state Success
15:42:10.071 [debug] Version of IPyWidgets 7 determined after 0s
15:42:12.185 [debug] Version of IPyWidgets 7 determined after 0s
15:42:12.185 [debug] Version of IPyWidgets 7 determined after 0s
15:42:12.186 [debug] Version of IPyWidgets 7 determined after 0s
15:42:12.187 [debug] Version of IPyWidgets 7 determined after 0s
15:42:12.195 [debug] Version of IPyWidgets 7 determined after 0s
15:42:12.195 [debug] Version of IPyWidgets 7 determined after 0s
15:42:12.637 [debug] Version of IPyWidgets 7 determined after 0s
15:42:12.873 [debug] Version of IPyWidgets 7 determined after 0s
15:42:12.982 [debug] Version of IPyWidgets 7 determined after 0s
```

</p>
</details>

**Comment by detrin** [comment]
I just updated it to 

> 1.80.2
> 2ccd690cbff1569e4a83d7c43d45101f817401dc
> arm64

We will see whether it persists. I have to say that it is probably something like 50 times I have seen this kind of error in past 2 years. SO I doubt this is linked to specific versions, but to something deeper.

**Comment by DonJayamanne** [comment]
Sorry you are running into this, 
Please enable verbose logging so we have the necessary logs if this happens again.
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by detrin** [comment]
@DonJayamanne WHat other logs do you need if not those I included from Jupyter itself? See Issue -> logs.

**Comment by DonJayamanne** [comment]
I’d need the full logs, looks like the controller/kernel was disposed earlier and that information is missing from the logs

**Comment by detrin** [comment]
> I’d need the full logs, looks like the controller/kernel was disposed earlier and that information is missing from the logs

The logs I provided are since the error started occurring, before that it was just a normal notebook with regular execution. I am not sure what more do you need. Because I believe there is no more relevant information.

**Comment by DonJayamanne** [comment]
> I am not sure what more do you need. Because I believe there is no more relevant information.

I believe there will be
There should be logs/messagesof when the controller got disposed, hence the request for the logs

**Comment by detrin** [comment]
> > I am not sure what more do you need. Because I believe there is no more relevant information.
> 
> I believe there will be There should be logs/messagesof when the controller got disposed, hence the request for the logs

Well, we will need to wait for another crash then, there were ca 15 in two years.

**Comment by jlustgarten** [comment]
I got this error similarly:
Error: Debug Failure. Cell path not found for cell vscode-notebook-cell://wsl%2Bubuntu/***DIR***/Coding/SpacyNER/jupyter/train_model_match.ipynb#W3sdnNjb2RlLXJlbW90ZQ%3D%3D
    at _0x5e8922.getNotebookCellPath (/***DIR***/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.11/dist/server.bundle.js:1:261668)
    at _0x8f195a.decodeTextDocumentUri (/***DIR***/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.11/dist/server.bundle.js:1:230980)
    at _0x45a7e7.onDidCloseTextDocument (/***DIR***/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.11/dist/server.bundle.js:1:901599)
    at /***DIR***/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.11/dist/pyright.bundle.js:1:1144202
    at /***DIR***/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.11/dist/vendor.bundle.js:2:1234062
    at oe (/***DIR***/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.11/dist/vendor.bundle.js:2:1234284)
    at /***DIR***/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.11/dist/vendor.bundle.js:2:1230224
    at Immediate.<anonymous> (/***DIR***/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.11/dist/vendor.bundle.js:2:1230244)
    at processImmediate (node:internal/timers:476:21)

2023-11-06 16:41:27.383 [info] [Error - 4:41:27 PM] Server process exited with code 1.
2023-11-06 16:41:27.385 [info] [Info  - 4:41:27 PM] Connection to server got closed. Server will restart.
2023-11-06 16:41:27.385 [info] true
2023-11-06 16:41:27.775 [info] [Info  - 4:41:27 PM] (112005) Pylance language server 2023.11.11 (pyright 64c9c3ff) starting
2023-11-06 16:41:27.775 [info] [Info  - 4:41:27 PM] (112005) Server root directory: /***DIR***/.vscode-server/extensions/ms-python.vscode-pylance-2023.11.11/dist
2023-11-06 16:41:27.781 [info] [Error - 4:41:27 PM] Server initialization failed.
2023-11-06 16:41:27.781 [info]   Message: Request initialize failed with message: You may install and use any number of copies of the software only with Microsoft Visual Studio, Visual Studio for Mac, Visual Studio Code, Azure DevOps, Team Foundation Server, and successor Microsoft products and services (collectively, the “Visual Studio Products and Services”) to develop and test your applications. The software is licensed, not sold. This agreement only gives you some rights to use the software. Microsoft reserves all other rights. You may not: work around any technical limitations in the software that only allow you to use it in certain ways; reverse engineer, decompile or disassemble the software, or otherwise attempt to derive the source code for the software, except and to the extent required by third party licensing terms governing use of certain open source components that may be included in the software; remove, minimize, block, or modify any notices of Microsoft or its suppliers in the software; use the software in any way that is against the law or to create or propagate malware; or share, publish, distribute, or lease the software (except for any distributable code, subject to the terms above), provide the software as a stand-alone offering for others to use, or transfer the software or this agreement to any third party.

----- [e556c713f436c0ecb35ee944b51384c09ca83c88074e9adb1f78af895bc55f42]

  Code: -32603 
2023-11-06 16:41:27.781 [info] [Error - 4:41:27 PM] Pylance client: couldn't create connection to server.
2023-11-06 16:41:27.781 [info]   Message: Request initialize failed with message: You may install and use any number of copies of the software only with Microsoft Visual Studio, Visual Studio for Mac, Visual Studio Code, Azure DevOps, Team Foundation Server, and successor Microsoft products and services (collectively, the “Visual Studio Products and Services”) to develop and test your applications. The software is licensed, not sold. This agreement only gives you some rights to use the software. Microsoft reserves all other rights. You may not: work around any technical limitations in the software that only allow you to use it in certain ways; reverse engineer, decompile or disassemble the software, or otherwise attempt to derive the source code for the software, except and to the extent required by third party licensing terms governing use of certain open source components that may be included in the software; remove, minimize, block, or modify any notices of Microsoft or its suppliers in the software; use the software in any way that is against the law or to create or propagate malware; or share, publish, distribute, or lease the software (except for any distributable code, subject to the terms above), provide the software as a stand-alone offering for others to use, or transfer the software or this agreement to any third party.

----- [e556c713f436c0ecb35ee944b51384c09ca83c88074e9adb1f78af895bc55f42]

  Code: -32603 
2023-11-06 16:41:27.781 [info] [Error - 4:41:27 PM] Restarting server failed
2023-11-06 16:41:27.781 [info]   Message: Request initialize failed with message: You may install and use any number of copies of the software only with Microsoft Visual Studio, Visual Studio for Mac, Visual Studio Code, Azure DevOps, Team Foundation Server, and successor Microsoft products and services (collectively, the “Visual Studio Products and Services”) to develop and test your applications. The software is licensed, not sold. This agreement only gives you some rights to use the software. Microsoft reserves all other rights. You may not: work around any technical limitations in the software that only allow you to use it in certain ways; reverse engineer, decompile or disassemble the software, or otherwise attempt to derive the source code for the software, except and to the extent required by third party licensing terms governing use of certain open source components that may be included in the software; remove, minimize, block, or modify any notices of Microsoft or its suppliers in the software; use the software in any way that is against the law or to create or propagate malware; or share, publish, distribute, or lease the software (except for any distributable code, subject to the terms above), provide the software as a stand-alone offering for others to use, or transfer the software or this agreement to any third party.

----- [e556c713f436c0ecb35ee944b51384c09ca83c88074e9adb1f78af895bc55f42]

  Code: -32603

**Comment by DonJayamanne** [comment]
@jlustgarten 
Please can you disable the pylance extension and try again
Pylance versions are known to cause issues with execution of Jupiter notebooks

**Comment by detrin** [comment]
> @jlustgarten @detrin Please can you disable the pylance extension and try again Pylance versions are known to cause issues with execution of Jupiter notebooks

I will. So far I didn't get the error again.

**Comment by DonJayamanne** [comment]
Thanks
Closing this issue for now
