### ISSUE TITLE
`aggdraw.Draw` causes kernel to die, not in web interface, only in VS Code

### ISSUE THREAD

**Issue by danielfaust** [microsoft/vscode-jupyter#14243]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

After installing aggdraw in a conda environment via `conda install -c conda-forge aggdraw` I had the following issue:

I ran this cell

```python
import aggdraw
# print('aggdraw version', aggdraw.__version__) # = 1.3.16
d = aggdraw.Draw("RGB", (100, 100), (0,0,0))
```

and after a very short time the kernel died. Same happens when I use `agg_draw = aggdraw.Draw(pil_image)`.

The result was `The Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. View Jupyter [log](command:jupyter.viewOutput) for further details.`

It is possible to use the cell for complex drawing and a following cell to print some text even after using `time.sleep(5)`, but sooner or later the message of the crashed kernel comes up and then it's no longer possible to re-run the notebook.

Clicking "Restart" hangs up the restarting task, it stays at "Restarting Kernel: Python 3.11". I then need to remove the kernel via the web ui because the small "Restarting Kernel" notification offers no way to abort this.

VS Code is running locally on Windows (192.168.30.41), the Jupyter instance is running on a Linux server (192.168.30.25), to which VS Code is also connected via the SSH Extension (Visual Studio Code Remote).

miniconda got installed around 3 days ago.

### VS Code Version

Version: 1.81.1 (user setup) Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794 Date: 2023-08-09T22:22:42.175Z Electron: 22.3.18 ElectronBuildId: 22689846 Chromium: 108.0.5359.215 Node.js: 16.17.1 V8: 10.8.168.25-electron.0 OS: Windows_NT x64 10.0.22621

### Jupyter Extension Version

v2023.7.1002162226

### Jupyter logs

```shell
[D 2023-09-02 00:43:55.831 ServerApp] Accepting token-authenticated request from 192.168.30.41
[D 2023-09-02 00:43:55.832 ServerApp] 200 GET /api/sessions?1693608235866 (51f58065604841788378348310d01476@192.168.30.41) 1.12ms
[D 2023-09-02 00:43:55.832 ServerApp] Accepting token-authenticated request from 192.168.30.41
[D 2023-09-02 00:43:55.838 ServerApp] 200 GET /api/contents/notebooks/Mapping?content=1&1693608235866 (51f58065604841788378348310d01476@192.168.30.41) 7.19ms
[I 2023-09-02 00:43:56.189 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), keep random ports
[W 2023-09-02 00:43:56.189 ServerApp] kernel c74a501a-185c-4460-a98b-856f5d262c4c restarted
[D 2023-09-02 00:43:56.192 ServerApp] Websocket closed c74a501a-185c-4460-a98b-856f5d262c4c:7fb8392c-61ee-4454-a288-79098c81f89b
[I 2023-09-02 00:43:56.192 ServerApp] Starting buffering for c74a501a-185c-4460-a98b-856f5d262c4c:7fb8392c-61ee-4454-a288-79098c81f89b
[D 2023-09-02 00:43:56.192 ServerApp] Clearing buffer for c74a501a-185c-4460-a98b-856f5d262c4c
[D 2023-09-02 00:43:56.195 ServerApp] Accepting token-authenticated request from 192.168.30.25
[D 2023-09-02 00:43:56.196 ServerApp] Generating new user for token-authenticated request: 2c09be001d1c46848ac775834800c1e4
[D 2023-09-02 00:43:56.201 ServerApp] Starting kernel: ['/home/user/miniconda3/envs/gdal/bin/python3', '-m', 'ipykernel_launcher', '-f', '/home/user/.local/share/jupyter/runtime/kernel-c74a501a-185c-4460-a98b-856f5d262c4c.json']
[D 2023-09-02 00:43:56.204 ServerApp] Connecting to: tcp://127.0.0.1:43485
[D 2023-09-02 00:43:56.205 ServerApp] 101 GET /api/kernels/c74a501a-185c-4460-a98b-856f5d262c4c/channels?session_id=7fb8392c-61ee-4454-a288-79098c81f89b&token=[secret] (2c09be001d1c46848ac775834800c1e4@192.168.30.25) 10.12ms
[D 2023-09-02 00:43:56.206 ServerApp] Opening websocket /api/kernels/c74a501a-185c-4460-a98b-856f5d262c4c/channels
[I 2023-09-02 00:43:56.206 ServerApp] Connecting to kernel c74a501a-185c-4460-a98b-856f5d262c4c.
[D 2023-09-02 00:43:56.206 ServerApp] Getting buffer for c74a501a-185c-4460-a98b-856f5d262c4c
[I 2023-09-02 00:43:56.206 ServerApp] Restoring connection for c74a501a-185c-4460-a98b-856f5d262c4c:7fb8392c-61ee-4454-a288-79098c81f89b
[D 2023-09-02 00:43:56.206 ServerApp] Nudge: not nudging busy kernel c74a501a-185c-4460-a98b-856f5d262c4c
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[D 2023-09-02 00:43:56.562 ServerApp] activity on c74a501a-185c-4460-a98b-856f5d262c4c: status (busy)
[D 2023-09-02 00:43:56.563 ServerApp] activity on c74a501a-185c-4460-a98b-856f5d262c4c: status (idle)
[D 2023-09-02 00:43:56.569 ServerApp] activity on c74a501a-185c-4460-a98b-856f5d262c4c: status (busy)
[D 2023-09-02 00:43:56.576 ServerApp] activity on c74a501a-185c-4460-a98b-856f5d262c4c: execute_input
[D 2023-09-02 00:43:56.580 ServerApp] activity on c74a501a-185c-4460-a98b-856f5d262c4c: stream
[D 2023-09-02 00:43:56.581 ServerApp] activity on c74a501a-185c-4460-a98b-856f5d262c4c: status (idle)
[D 2023-09-02 00:44:05.741 ServerApp] Accepting token-authenticated request from 192.168.20.25
[D 2023-09-02 00:44:05.741 ServerApp] Generating new user for token-authenticated request: 0dd7402b8a7042068fe8ff0b45ed9bce
[D 2023-09-02 00:44:05.741 ServerApp] 200 GET /api/kernels?1693608245737 (0dd7402b8a7042068fe8ff0b45ed9bce@192.168.20.25) 1.27ms
[D 2023-09-02 00:44:05.742 ServerApp] Accepting token-authenticated request from 192.168.20.25
```

### Coding Language and Runtime Version

Python 3.11.4 (main, Jul  5 2023, 13:45:01) [GCC 11.2.0] on linux

### Language Extension Version (if applicable)

Python v2023.14.0

### Anaconda Version (if applicable)

 conda 23.5.2 (miniconda latest, Python 3.11)

### Running Jupyter locally or remotely?

Remote

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by danielfaust** [comment]
Hi @DonJayamanne, here you go:

```
Visual Studio Code (1.81.1, ssh-remote, desktop)
Jupyter Extension Version: 2023.7.1002162226.
Python Extension Version: 2023.14.0.
Platform: linux (x64).
Workspace folder ~/python/jupyter/notebooks, Home = /home/user
09:36:43.905 [info] Telemetry is disabled
09:36:43.906 [info] Telemetry level is off
09:36:43.906 [info] Experiments are disabled, only manually opted experiments are active.
09:36:44.153 [info] Start refreshing Interpreter Kernel Picker (1693640204153)
09:36:44.166 [info] Using Pylance
09:36:44.846 [info] Loading webview. View is notset
09:36:44.847 [info] Loading web view...
09:36:44.848 [info] Webview panel created.
09:36:45.190 [warn] No interpreter with path ~/miniconda3/envs/gdal/bin/python3 found in Python API, will convert Uri path to string as Id ~/miniconda3/envs/gdal/bin/python3
09:36:45.191 [warn] No interpreter with path ~/python/venvs/p3-pki-2022-05-09/bin/python3 found in Python API, will convert Uri path to string as Id ~/python/venvs/p3-pki-2022-05-09/bin/python3
09:36:45.314 [info] Web view react rendered
09:36:45.543 [warn] Failed to get activated env vars for ~/.pyenv/versions/3.10.7/bin/python in 350ms
09:36:45.544 [error] Unable to determine site packages path for python ~/.pyenv/versions/3.10.7/bin/python (Pyenv)
09:36:45.557 [info] Process Execution: ~/.pyenv/versions/3.10.7/bin/python -m pip list
09:36:47.103 [info] End refreshing Interpreter Kernel Picker (1693640204153)
09:36:56.194 [info] Handle Execution of Cells 0 for ~/python/jupyter/notebooks/Mapping/Aggdraw-Memory-Test.ipynb
09:36:56.196 [info] Starting Kernel startUsingRemoteKernelSpec, 184b11b7311271c053b<username>f8bc12cca1fc5c208be3395f5de8fd3696dcb773871..gdal.~/miniconda3/envs/gdal/bin/python3./.-m#ipykernel_launcher  for '~/python/jupyter/notebooks/Mapping/Aggdraw-Memory-Test.ipynb' (disableUI=false)
09:36:56.651 [info] Started new session 77717b32-fee8-4d15-9733-6c68a9ede8<username>
09:36:56.652 [info] Started session for kernel startUsingRemoteKernelSpec:184b11b7311271c053b<username>f8bc12cca1fc5c208be3395f5de8fd3696dcb773871..gdal.~/miniconda3/envs/gdal/bin/python3./.-m#ipykernel_launcher
09:36:56.735 [info] Kernel acknowledged execution of cell 0 @ 1693640216721
09:36:56.781 [info] End cell 0 execution @ 1693640216738, started @ 1693640216721, elapsed time = 0.017s
09:36:56.821 [info] End refreshing Interpreter Kernel Picker (1693640204153)
09:36:59.286 [error] Jupyter Extension (Error in requestVariables, method:requestVariables): Error: Canceled future for execute_request message before replies were done
    at t.KernelShellFutureHandler.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.7.1002162226-linux-x64/out/extension.node.js:2:32375)
    at ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.7.1002162226-linux-x64/out/extension.node.js:2:26594
    at Map.forEach (<anonymous>)
    at v._clearKernelState (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.7.1002162226-linux-x64/out/extension.node.js:2:26579)
    at ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.7.1002162226-linux-x64/out/extension.node.js:2:29022
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
09:36:59.367 [info] End cell 0 execution @ undefined, started @ 1693640216738, elapsed time = -1693640216.738s
```

**Comment by DonJayamanne** [comment]
> causes kernel to die, not in web interface, only in VS Code

based on the logs you are running the code against a remote Jupyter kernel.

I find I it hard to understand how it didn’t fail when you run the same code outside vscode, as is the exact same environment 

Can you code the variables view on the bottom of your screen. I think that panel is open, please close that and try again
It’s possible that’s thinking some code that causes the crash

**Comment by danielfaust** [comment]
"Can you code the variables view": I assume this was a typo.

You are correct. The variable view was open and when I closed it the error disappeared.

The lower-right popup-notification `The kernel 'Python 3.11 -- gdal' died and is being automatically restarted by Jupyter. Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. View Jupyter [log](command:jupyter.viewOutput) for further details.` no longer appears.

Without the variables view the UI is consistent and healthy.

**Comment by danielfaust** [comment]
Regarding the last added information with the two cells: This works in a simple notebook, but not in a larger one. In any case, closing the variable view "fixes" the issue 100%.

**Comment by DonJayamanne** [comment]
Plese can you try the following:
* Start jupyter on the same machine (i think wsl)
* Launch jupyter and run the same code
* If it crashes, please share logs from terminal

**Comment by danielfaust** [comment]
VS code is running on one machine (Windows) and Jupyter on another one (in a Linux VM hosted on a server).

If I use Jupyter's web interface via http://host:port/lab/tree/notebooks/Mapping/Aggdraw-Test.ipynb then the Kernel does not crash.

**Comment by DonJayamanne** [comment]
> When I use Jupyter's web interface via http://host:port/lab/tree/notebooks/Mapping/Aggdraw-Test.ipynb then the Kernel does not crash.

Yes thats what I wanted you to try.
thats fine, you do not need to do anything else.

thanks
I will follow this at my end.

**Comment by DonJayamanne** [comment]
Btw, I can now replicate this at my end

**Comment by DonJayamanne** [comment]
Steps to repro
* Run the following code
```python
import aggdraw
from PIL import Image, ImageDraw
 
print('aggdraw version', aggdraw.__version__)
# aggdraw version 1.3.12 -- on aiohttp
# aggdraw version 1.3.16 -- in conda

# WARN `USE_AGGDRAW = True` causes the kernel to crash 
USE_AGGDRAW = True

img = Image.new("RGB", (256, 256), "white")

if USE_AGGDRAW:
    agg_draw = aggdraw.Draw(img)
else:
    draw = ImageDraw.Draw(img)

# Diagonal line
p1 = (0,0)
p2 = (255,255)

if USE_AGGDRAW:
    pen = aggdraw.Pen(color=(255,0,0), width=10, opacity=127)
    agg_draw.line((p1[0], p1[1], p2[0], p2[1]), pen)
else:
    draw.line([p1, p2], fill="red", width=10)

if USE_AGGDRAW:
    agg_draw.flush()

display(img)
```
* Run the code `globals()`

**Comment by DonJayamanne** [comment]
Looks like a duplicate of https://github.com/pytroll/aggdraw/issues/58

Basically trying to inspect the details of the pen variable causes the crash.

**Comment by danielfaust** [comment]
You're right. I just enabled debugging in Jupyter (which I had to do twice), and then, when running the cell, the kernel crashes. Even stepping over `agg_draw = aggdraw.Draw(img)` is enough to cause the crash.

Thank you for your help.

**Comment by DonJayamanne** [comment]
> Thank you for your help and my apologies for not having checked this.


No need to apologise, that’s why we ask these questions
Thank you for your cooperation
