### ISSUE TITLE
User belongs to experiment group & zmq crash

### ISSUE THREAD

**Issue by serialprimate** [microsoft/vscode-jupyter#1440]
## Environment data

-   VS Code version: 1.51 (Installed as a snap)
-   Extension version (available under the Extensions sidebar): v2020.10.332292344
-   OS and version: Ubuntu 20.04 LTS
-   Python version (& distribution if applicable, e.g. Anaconda): XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Relevant/affected Python packages and their versions: 3.8.5
-   Relevant/affected Python-related VS Code extensions and their versions: None
-   Value of the `python.languageServer` setting: Jedi

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

No experiment group messages.
No zmq crash.

## Actual behaviour

```
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'DeprecatePythonPath - control'
User belongs to experiment group 'RunByLine - experiment'
User belongs to experiment group 'CustomEditorSupport - control'
User belongs to experiment group 'pythonaacf'
Error 2020-11-07 19:19:11: Exception while attempting zmq : [Error: /snap/core/current/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/matt/.vscode/extensions/ms-python.python-2020.10.332292344/out/client/node_modules/zeromq/prebuilds/linux-x64/electron.napi.glibc.node)
	at process.func [as dlopen] (electron/js2c/asar.js:140:31)
	at Object.Module._extensions..node (internal/modules/cjs/loader.js:1081:18)
	at Object.func [as .node] (electron/js2c/asar.js:140:31)
	at Module.load (internal/modules/cjs/loader.js:862:32)
	at Module._load (internal/modules/cjs/loader.js:774:14)
	at Function.Module._load (electron/js2c/asar.js:769:28)
	at Function.t._load (/snap/code/49/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1064:776)
	at Function.i._load (/snap/code/49/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1034:665)
	at Function.n._load (/snap/code/49/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1030:844)
	at Module.require (internal/modules/cjs/loader.js:899:19)
	at r (/snap/code/49/usr/share/code/resources/app/out/vs/loader.js:17:346)
	at load (/home/matt/.vscode/extensions/ms-python.python-2020.10.332292344/out/client/node_modules/node-gyp-build/index.js:21:10)
	at Object.<anonymous> (/home/matt/.vscode/extensions/ms-python.python-2020.10.332292344/out/client/node_modules/zeromq/lib/native.js:6:43)
	at Module.i._compile (/snap/code/49/usr/share/code/resources/app/out/vs/loader.js:17:571)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1051:10)
	at Module.load (internal/modules/cjs/loader.js:862:32)
	at Module._load (internal/modules/cjs/loader.js:774:14)
	at Function.Module._load (electron/js2c/asar.js:769:28)
	at Function.t._load (/snap/code/49/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1064:776)
	at Function.i._load (/snap/code/49/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1034:665)
	at Function.n._load (/snap/code/49/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1030:844)
	at Module.require (internal/modules/cjs/loader.js:899:19)
	at r (/snap/code/49/usr/share/code/resources/app/out/vs/loader.js:17:346)
	at Object.<anonymous> (/home/matt/.vscode/extensions/ms-python.python-2020.10.332292344/out/client/node_modules/zeromq/lib/index.js:3:16)
	at Module.i._compile (/snap/code/49/usr/share/code/resources/app/out/vs/loader.js:17:571)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1051:10)
	at Module.load (internal/modules/cjs/loader.js:862:32)
	at Module._load (internal/modules/cjs/loader.js:774:14)
	at Function.Module._load (electron/js2c/asar.js:769:28)
	at Function.t._load (/snap/code/49/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1064:776)
	at Function.i._load (/snap/code/49/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1034:665)
	at Function.n._load (/snap/code/49/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1030:844)
	at Module.require (internal/modules/cjs/loader.js:899:19)
	at r (/snap/code/49/usr/share/code/resources/app/out/vs/loader.js:17:346)
	at Object.<anonymous> (/home/matt/.vscode/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:32:307712)
	at n (/home/matt/.vscode/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:1:186)
	at /home/matt/.vscode/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:733074
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async d.zmqSupportedImpl (/home/matt/.vscode/extensions/ms-python.python-2020.10.332292344/out/client/extension.js:56:733041)]
> conda --version
> pyenv root
> python3.7 ~/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda info --json
> python ~/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
Starting Jedi Python language engine.
Python interpreter path: ./.venv/bin/python3
> conda --version
```

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

Can't. Appears to be confined to a pre-existing workspace.

I tried:
Python: Clear Workspace Interpreter Setting
Python: Reset Stored Info for Untrusted Interpreters

Don't know?

Is the zmq error because of the snap container?

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
As above.
```

</p>
</details>

**Comment by joyceerhl** [comment]
Oh that does make sense. Basically the snap install doesn't have the version of libstdc++ that our ZMQ prebuilds require, and VSCode insiders does not pick up the system libstdc++ because it's running against the snap.

**Comment by joyceerhl** [comment]
Not really sure what we can do here. One of these needs to happen:
- vscode snap package should include the version of libstdc++ that we need (doesn't seem tenable, vscode should not have to account for extension dependencies)
- change zmq prebuild version to require version of libstdc++ that is available in vscode snap
- don't think it's possible to install libstdc++ into the snap, so that's not an option
- snap should resolve dependencies from system if they can't be resolved from inside the snap package

@serialprimate Can I ask if you are able to use our Jupyter notebooks at all even with the zmq crash? IIRC we are supposed to fall back to using the `jupyter` package if zmq is unusable. If Jupyter notebooks aren't working at all this is a bigger problem, since that implies that all users who install vscode via snap won't be able to use our extension.

**Comment by serialprimate** [comment]
@joyceerhl I don't use Jupyter notebooks at all.

Also I reported the snap issue, but there wasn't even one response. Perhaps I shouldn't use it. :-)

**Comment by isvoboda** [comment]
Seems related to microsoft/vscode#112336

**Comment by isvoboda** [comment]
I don't know how important the `zmq` related error is but the latest VSCode release (1.53.0) noted:

> After some changes to the build system, we were able to go back as far as using gcc-5 toolchain, which brings the minimum GLIBCXX requirement to 3.4.21. 

`vscode-jupyter` requirement is 3.4.22 so it fails if vscode distribution is the snap package.
