### ISSUE TITLE
unable to start kernel

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#14406]
Type: <b>Bug</b>

specific to the 32 bit windows visx
as soon as I changed my log setting to verbose it stopped repro'ing

it looks like it was trying to use the full jupyter package on kernel startup, but only checks for raw dependencies when checking packages.

Extension version: 2023.9.1002771829
VS Code version: Code 1.83.0 (4268e464763087044d0c1b5bdd37ebbe683cadfa, 2023-09-29T20:48:47.268Z)
OS version: Windows_NT ia32 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|31.92GB (13.89GB free)|
|Process Argv|--crash-reporter-id 9c3b3f47-b71f-450c-8005-d45b40fa2d8b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
vscrpc:30673769
a9j8j154:30646983
showlangstatbar:30737416
962ge761:30841074
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingt:30839829
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448

```

</details>

<details>
<summary>logs</summary>

```
Visual Studio Code (1.83.0, undefined, desktop)
Jupyter Extension Version: 2023.9.1002771829.
Python Extension Version: 2023.17.12751008.
Platform: win32 (ia32).
Workspace folder c:\src\test\ws1, Home = c:\Users\aamunger
14:42:04.610 [warn] Exception while attempting zmq : No native build was found for platform=win32 arch=ia32 runtime=electron abi=116 uv=1 libc=glibc node=18.15.0 electron=25.8.4
    loaded from: ~\.vscode\extensions\ms-toolsai.jupyter-2023.9.1002771829\out\node_modules\zeromq

14:42:04.610 [warn] Exception while attempting zmq (fallback) : No native build was found for platform=win32 arch=ia32 runtime=electron abi=116 uv=1 libc=glibc node=18.15.0 electron=25.8.4
    loaded from: ~\.vscode\extensions\ms-toolsai.jupyter-2023.9.1002771829\out\node_modules\zeromqold

14:42:04.654 [info] User belongs to experiment group 'NewJupyterSession'
14:42:05.062 [info] Attempting to start a server because of preload conditions ...
14:42:05.070 [info] Start refreshing Kernel Picker (1696282925070)
14:42:05.081 [info] Using Pylance
14:42:06.373 [info] Start refreshing Interpreter Kernel Picker
14:42:08.598 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd05577a0588acd48e8513cd26001cbcedde50e555ef84a73abc59505d5f4efb112.c:\src\test\ws1\.venv\Scripts\python.exe.c:\src\test\ws1\.venv\Scripts\python.exe.-m#ipykernel_launcher  (Python Path: c:\src\test\ws1\.venv\Scripts\python.exe, Venv, .venv, 3.10.11) for 'c:\src\test\ws1\nb1.ipynb' (disableUI=true)
14:42:10.072 [warn] Failed to get activated env vars for ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe in 2842ms
14:42:10.286 [info] Process Execution: ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -c "import site;print("USER_BASE_VALUE");print(site.USER_SITE);print("USER_BASE_VALUE");"
14:42:10.893 [info] Process Execution: ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -m pip list
14:42:11.404 [info] Process Execution: c:\src\test\ws1\.venv\Scripts\python.exe -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
14:42:11.424 [info] Process Execution: c:\src\test\ws1\.venv\Scripts\python.exe -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
14:42:11.444 [info] Process Execution: c:\src\test\ws1\.venv\Scripts\python.exe -m pip list
14:42:13.405 [info] Process Execution: c:\src\test\ws1\.venv\Scripts\python.exe -m jupyter kernelspec --version
14:42:18.952 [info] Launching server
14:42:18.954 [info] Starting Notebook
14:42:18.962 [info] Generating custom default config at ~\AppData\Local\Temp\c579e770-dddd-4bd7-8685-80d34e78a48a\jupyter_notebook_config.py
14:42:19.031 [info] Process Execution: c:\src\test\ws1\.venv\Scripts\python.exe -m jupyter notebook --no-browser --notebook-dir="c:\\src\\test\\ws1" --config=~\AppData\Local\Temp\c579e770-dddd-4bd7-8685-80d34e78a48a\jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
14:42:21.225 [error] Failed to start the Jupyter Server Error: Jupyter Server crashed. Unable to connect. 
Error code from Jupyter: 1
usage: jupyter.py [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
                  [--paths] [--json] [--debug]
                  [subcommand]

Jupyter: Interactive Computing

positional arguments:
  subcommand     the subcommand to launch

options:
  -h, --help     show this help message and exit
  --version      show the versions of core jupyter packages and exit
  --config-dir   show Jupyter config dir
  --data-dir     show Jupyter data dir
  --runtime-dir  show Jupyter runtime dir
  --paths        show all Jupyter paths. Add --json for machine-readable
                 format.
  --json         output paths as machine-readable json
  --debug        output debug information about paths

Available subcommands: 1.0.0 kernel kernelspec migrate run troubleshoot

Jupyter command `jupyter-notebook` not found.
    > at Zf.rejectStartPromise (~\.vscode\extensions\ms-toolsai.jupyter-2023.9.1002771829\out\extension.node.js:17:116610)
    > interpreter = [object Object]
14:42:21.225 [error] Error starting server in serverPreload:  Error: Jupyter Server crashed. Unable to connect. 
Error code from Jupyter: 1
usage: jupyter.py [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
                  [--paths] [--json] [--debug]
                  [subcommand]

Jupyter: Interactive Computing

positional arguments:
  subcommand     the subcommand to launch

options:
  -h, --help     show this help message and exit
  --version      show the versions of core jupyter packages and exit
  --config-dir   show Jupyter config dir
  --data-dir     show Jupyter data dir
  --runtime-dir  show Jupyter runtime dir
  --paths        show all Jupyter paths. Add --json for machine-readable
                 format.
  --json         output paths as machine-readable json
  --debug        output debug information about paths

Available subcommands: 1.0.0 kernel kernelspec migrate run troubleshoot

Jupyter command `jupyter-notebook` not found.
    > at Zf.rejectStartPromise (~\.vscode\extensions\ms-toolsai.jupyter-2023.9.1002771829\out\extension.node.js:17:116610)
    > interpreter = [object Object]
14:42:21.227 [warn] Error occurred while trying to start the kernel, options.disableUI=true Error: Jupyter Server crashed. Unable to connect. 
Error code from Jupyter: 1
usage: jupyter.py [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
                  [--paths] [--json] [--debug]
                  [subcommand]

Jupyter: Interactive Computing

positional arguments:
  subcommand     the subcommand to launch

options:
  -h, --help     show this help message and exit
  --version      show the versions of core jupyter packages and exit
  --config-dir   show Jupyter config dir
  --data-dir     show Jupyter data dir
  --runtime-dir  show Jupyter runtime dir
  --paths        show all Jupyter paths. Add --json for machine-readable
                 format.
  --json         output paths as machine-readable json
  --debug        output debug information about paths

Available subcommands: 1.0.0 kernel kernelspec migrate run troubleshoot

Jupyter command `jupyter-notebook` not found.
    > at Zf.rejectStartPromise (~\.vscode\extensions\ms-toolsai.jupyter-2023.9.1002771829\out\extension.node.js:17:116610)
    > interpreter = [object Object]
14:42:25.994 [info] End refreshing Kernel Picker (1696282925070)
14:42:56.157 [info] Handle Execution of Cells 1 for c:\src\test\ws1\nb1.ipynb
14:42:56.160 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd05577a0588acd48e8513cd26001cbcedde50e555ef84a73abc59505d5f4efb112.c:\src\test\ws1\.venv\Scripts\python.exe.c:\src\test\ws1\.venv\Scripts\python.exe.-m#ipykernel_launcher  (Python Path: c:\src\test\ws1\.venv\Scripts\python.exe, Venv, .venv, 3.10.11) for 'c:\src\test\ws1\nb1.ipynb' (disableUI=false)
14:42:56.160 [info] Launching server
14:42:56.162 [info] Starting Notebook
14:42:56.164 [info] Generating custom default config at ~\AppData\Local\Temp\48512625-d1a8-4491-86c7-0212fcc23d7e\jupyter_notebook_config.py
14:42:56.208 [info] Process Execution: c:\src\test\ws1\.venv\Scripts\python.exe -m jupyter notebook --no-browser --notebook-dir="c:\\src\\test\\ws1" --config=~\AppData\Local\Temp\48512625-d1a8-4491-86c7-0212fcc23d7e\jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
14:42:57.971 [error] Failed to start the Jupyter Server Error: Jupyter Server crashed. Unable to connect. 
Error code from Jupyter: 1
usage: jupyter.py [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
                  [--paths] [--json] [--debug]
                  [subcommand]

Jupyter: Interactive Computing

positional arguments:
  subcommand     the subcommand to launch

options:
  -h, --help     show this help message and exit
  --version      show the versions of core jupyter packages and exit
  --config-dir   show Jupyter config dir
  --data-dir     show Jupyter data dir
  --runtime-dir  show Jupyter runtime dir
  --paths        show all Jupyter paths. Add --json for machine-readable
                 format.
  --json         output paths as machine-readable json
  --debug        output debug information about paths

Available subcommands: 1.0.0 kernel kernelspec migrate run troubleshoot

Jupyter command `jupyter-notebook` not found.
    > at Zf.rejectStartPromise (~\.vscode\extensions\ms-toolsai.jupyter-2023.9.1002771829\out\extension.node.js:17:116610)
    > interpreter = [object Object]
14:42:57.971 [warn] Error occurred while trying to start the kernel, options.disableUI=false Error: Jupyter Server crashed. Unable to connect. 
Error code from Jupyter: 1
usage: jupyter.py [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
                  [--paths] [--json] [--debug]
                  [subcommand]

Jupyter: Interactive Computing

positional arguments:
  subcommand     the subcommand to launch

options:
  -h, --help     show this help message and exit
  --version      show the versions of core jupyter packages and exit
  --config-dir   show Jupyter config dir
  --data-dir     show Jupyter data dir
  --runtime-dir  show Jupyter runtime dir
  --paths        show all Jupyter paths. Add --json for machine-readable
                 format.
  --json         output paths as machine-readable json
  --debug        output debug information about paths

Available subcommands: 1.0.0 kernel kernelspec migrate run troubleshoot

Jupyter command `jupyter-notebook` not found.
    > at Zf.rejectStartPromise (~\.vscode\extensions\ms-toolsai.jupyter-2023.9.1002771829\out\extension.node.js:17:116610)
    > interpreter = [object Object]
14:42:57.972 [warn] Kernel Error, context = start Error: Jupyter Server crashed. Unable to connect. 
Error code from Jupyter: 1
usage: jupyter.py [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
                  [--paths] [--json] [--debug]
                  [subcommand]

Jupyter: Interactive Computing

positional arguments:
  subcommand     the subcommand to launch

options:
  -h, --help     show this help message and exit
  --version      show the versions of core jupyter packages and exit
  --config-dir   show Jupyter config dir
  --data-dir     show Jupyter data dir
  --runtime-dir  show Jupyter runtime dir
  --paths        show all Jupyter paths. Add --json for machine-readable
                 format.
  --json         output paths as machine-readable json
  --debug        output debug information about paths

Available subcommands: 1.0.0 kernel kernelspec migrate run troubleshoot

Jupyter command `jupyter-notebook` not found.
    > at Zf.rejectStartPromise (~\.vscode\extensions\ms-toolsai.jupyter-2023.9.1002771829\out\extension.node.js:17:116610)
    > interpreter = [object Object]
14:42:57.998 [info] Process Execution: c:\src\test\ws1\.venv\Scripts\python.exe -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
14:43:01.464 [info] Dispose Kernel 'c:\src\test\ws1\nb1.ipynb' associated with 'c:\src\test\ws1\nb1.ipynb'
14:43:01.466 [error] Error in execution Error: Jupyter Server crashed. Unable to connect. 
Error code from Jupyter: 1
usage: jupyter.py [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
                  [--paths] [--json] [--debug]
                  [subcommand]

Jupyter: Interactive Computing

positional arguments:
  subcommand     the subcommand to launch

options:
  -h, --help     show this help message and exit
  --version      show the versions of core jupyter packages and exit
  --config-dir   show Jupyter config dir
  --data-dir     show Jupyter data dir
  --runtime-dir  show Jupyter runtime dir
  --paths        show all Jupyter paths. Add --json for machine-readable
                 format.
  --json         output paths as machine-readable json
  --debug        output debug information about paths

Available subcommands: 1.0.0 kernel kernelspec migrate run troubleshoot

Jupyter command `jupyter-notebook` not found.
    > at Zf.rejectStartPromise (~\.vscode\extensions\ms-toolsai.jupyter-2023.9.1002771829\out\extension.node.js:17:116610)
    > interpreter = [object Object]
14:43:01.467 [error] Error in execution (get message for cell) Error: Jupyter Server crashed. Unable to connect. 
Error code from Jupyter: 1
usage: jupyter.py [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
                  [--paths] [--json] [--debug]
                  [subcommand]

Jupyter: Interactive Computing

positional arguments:
  subcommand     the subcommand to launch

options:
  -h, --help     show this help message and exit
  --version      show the versions of core jupyter packages and exit
  --config-dir   show Jupyter config dir
  --data-dir     show Jupyter data dir
  --runtime-dir  show Jupyter runtime dir
  --paths        show all Jupyter paths. Add --json for machine-readable
                 format.
  --json         output paths as machine-readable json
  --debug        output debug information about paths

Available subcommands: 1.0.0 kernel kernelspec migrate run troubleshoot

Jupyter command `jupyter-notebook` not found.
    > at Zf.rejectStartPromise (~\.vscode\extensions\ms-toolsai.jupyter-2023.9.1002771829\out\extension.node.js:17:116610)
    > interpreter = [object Object]
14:43:01.545 [info] End cell 1 execution @ undefined, started @ undefined, elapsed time = 0s

```

</details

**Comment by amunger** [comment]
This works now, so feel free to close if you think it was just a fluke. It did last through a couple of reloads though

**Comment by DonJayamanne** [comment]
@amunger please can you check the logs, is zmq used or is jupyter used to run kernels on windows 32 bit?

**Comment by amunger** [comment]
eventually zmq is used when it started working
