### ISSUE TITLE
`print('hello')` crashes IRkernel on hpc remote-ssh connection (X11 issue?)

### ISSUE THREAD

**Issue by mkarikom** [microsoft/vscode-jupyter#14462]
## Environment data

-   VS Code version: Version: 1.82.3 (Universal)
Commit: fdb98833154679dbaa7af67a5a29fe19e55c2b73
-   Jupyter Extension version (available under the Extensions sidebar): v2023.8.1002501831
-   Python Extension version (available under the Extensions sidebar): v2023.18.0
-   OS (Windows | Mac | Linux distro) and version: local MacOS 14.0, remote RHEL 8.6
-   Python and/or Anaconda version: 3.10.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: N/A

## Expected behaviour
Executing the following R code should print something
```
print('hello')
hello
```
## Actual behaviour (see full jupyter logs below)

Cannot execute code, session has been disposed. Please try restarting the Kernel.
The Kernel crashed while executing code in the the current cell or a previous cell. 

Please review the code in the cell(s) to identify a possible cause of the failure. Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. View Jupyter [log](command:jupyter.viewOutput) for further details.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. launch R in terminal
2. `install.packages('IRkernel')`
3. `IRkernel::installspec(user = TRUE)`
4. create new Jupyter notebook
5. select kernel based on `$which R`, in my case I enter the absolute path of a manually-loaded hpc module `/sw/pkgs/arc/stacks/gcc/10.3.0/R/4.3.1/bin/R`
6. execute the first code cell:
```
print('hello')
``` 

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
11:00:46.177 [warn] No interpreter for Pylance for Notebook URI "Untitled-2.ipynb"
11:00:52.200 [info] Starting Kernel startUsingLocalKernelSpec, .ir./sw/pkgs/arc/stacks/gcc/10.3.0/R/4.3.1/lib64/R/bin/R././sw/pkgs/arc/stacks/gcc/10.3.0/r/4.3.1/lib64/r/bin/r#--slave#-e#irkernel::main()#--args#{connection_file}  for 'Untitled-2.ipynb' (disableUI=true)
11:00:52.202 [warn] No interpreter for Pylance for Notebook URI "Untitled-2.ipynb"
11:00:52.207 [info] Launching Raw Kernel R # /sw/pkgs/arc/stacks/gcc/10.3.0/R/4.3.1/lib64/R/bin/R
11:00:52.276 [info] Process Execution: /sw/pkgs/arc/stacks/gcc/10.3.0/R/4.3.1/lib64/R/bin/R --slave -e IRkernel::main() --args ~/.local/share/jupyter/runtime/kernel-v2-411848XEN0UdNLt0c7.json
    > cwd: /scratch/group_root/d1/<username>/aerts_test
11:00:53.753 [info] Started Kernel R (pid: 414772)
11:00:53.753 [info] Started new session 47118250-1aad-4667-81af-18b7fc2705c3
11:01:01.533 [info] Handle Execution of Cells 0 for Untitled-2.ipynb
11:01:01.538 [info] Kernel acknowledged execution of cell 0 @ 1696690861536
11:01:01.564 [warn] StdErr from Kernel Process Error in dev.control(displaylist = "enable") : 
  dev.control() called without an open graphics device
Calls: <Anonymous> ... tryCatch -> tryCatchList -> evaluate -> dev.control
In addition: Warning messages:
1: In grSoftVersion() :
11:01:01.564 [warn] StdErr from Kernel Process unable to load shared object '/sw/pkgs/arc/stacks/gcc/10.3.0/R/4.3.1/lib64/R/modules//R_X11.so':
  libjpeg.so.8: cannot open shared object file: No such file or directory
2: In cairoVersion() :
  unable to load shared object '/sw/pkgs/arc/stacks/gcc/10.3.0/R/4.3.1/lib64/R/library/grDevices/libs//cairo.so':
  libjpeg.so.8: cannot open shared object file: No such file or directory
3: In ok_device(filename, ...) : failed to load cairo DLL
Execution halted
11:01:01.851 [error] Disposing session as kernel process died ExitCode: 1, Reason: Error in dev.control(displaylist = "enable") : 
  dev.control() called without an open graphics device
Calls: <Anonymous> ... tryCatch -> tryCatchList -> evaluate -> dev.control
In addition: Warning messages:
1: In grSoftVersion() :
  unable to load shared object '/sw/pkgs/arc/stacks/gcc/10.3.0/R/4.3.1/lib64/R/modules//R_X11.so':
  libjpeg.so.8: cannot open shared object file: No such file or directory
2: In cairoVersion() :
  unable to load shared object '/sw/pkgs/arc/stacks/gcc/10.3.0/R/4.3.1/lib64/R/library/grDevices/libs//cairo.so':
  libjpeg.so.8: cannot open shared object file: No such file or directory
3: In ok_device(filename, ...) : failed to load cairo DLL
Execution halted

11:01:01.851 [info] Dispose Kernel process 414772.
11:01:01.852 [error] Raw kernel process exited code: 1
11:01:01.852 [error] Error in waiting for cell to complete [Error: Canceled future for execute_request message before replies were done
	at t.KernelShellFutureHandler.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.8.1002501831-linux-x64/out/extension.node.js:2:32375)
	at ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.8.1002501831-linux-x64/out/extension.node.js:2:51427
	at Map.forEach (<anonymous>)
	at v._clearKernelState (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.8.1002501831-linux-x64/out/extension.node.js:2:51412)
	at v.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.8.1002501831-linux-x64/out/extension.node.js:2:44894)
	at ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.8.1002501831-linux-x64/out/extension.node.js:24:110056
	at ce (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.8.1002501831-linux-x64/out/extension.node.js:2:1588855)
	at yy.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.8.1002501831-linux-x64/out/extension.node.js:24:110032)
	at Sy.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.8.1002501831-linux-x64/out/extension.node.js:24:113402)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)]
11:01:01.853 [warn] Cell completed with errors {
  message: 'Canceled future for execute_request message before replies were done'
}
11:01:01.853 [info] End cell 0 execution @ 1696690861853, started @ 1696690861536, elapsed time = 0.317s
11:01:01.854 [warn] Cancel all remaining cells due to cancellation or failure in execution
11:01:01.920 [info] End cell 0 execution @ undefined, started @ undefined, elapsed time = 0s

```

</p>
</details>

**Comment by mkarikom** [comment]
Ok, I figured it out.
The issue is that you need to have a conda environment e.g. `mRenv`, and install R **inside** of that.
Then, when you select a kernel for a new ipynb notebook, you have to select "Jupyter kernel" and let the extension figure out that R is available `myRenv`, and select the auto-populated R option under `myRenv`.
Here is what I did to get all that to happen:

1. `conda create --name my_r_env r-irkernel r-essentials` 
2. `conda activate my_r_env`
3. `IRkernel::installspec(user = TRUE)`
4. select a kernel -> jupyter kernel -> R (myRenv) /R
