### ISSUE TITLE
Notebooks cannot be opened on WSL2 with Miniconda

### ISSUE THREAD

**Issue by stefnotch** [microsoft/vscode-jupyter#14542]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I'm on a Windows PC, with an Ubuntu WSL2 machine. Python is installed in the Ubuntu environment.

Then, I did the following steps
1. I installed miniconda in the WSL, using their official Linux "Quick command line install" instructions at https://docs.conda.io/projects/miniconda/en/latest/
```bash
mkdir -p ~/miniconda3
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
rm -rf ~/miniconda3/miniconda.sh

~/miniconda3/bin/conda init bash
```
2. I created a new conda environment using
```bash
conda create --name gcv_exercise_1 python=3.11
conda activate gcv_exercise_1
conda install matplotlib numpy scikit-image pillow
conda install -n gcv_exercise_1 ipykernel --update-deps --force-reinstall
```

3. I installed all the Python and Jupyter extensions in the WSL. I *only* installed them in the WSL.

4. I configured VSCode to use the Python from there

![image](https://github.com/microsoft/vscode-jupyter/assets/10220080/507d88e5-efcb-4201-a64e-f5b68f8f0aa8)

5. I created a new .ipynb file. It does not get opened as an interactive Python file. This is a problem.
![image](https://github.com/microsoft/vscode-jupyter/assets/10220080/9b4ed92f-5002-45cf-9604-7905f73081cd)

6. Then I tried F1 -> Jupyter: Create interactive window. This also results in an error message.
![image](https://github.com/microsoft/vscode-jupyter/assets/10220080/e19f7922-ecb9-42bc-ad94-51ca9789b6d7)

7. After that, I tried F1 -> Jupyter: Import Jupyter Notebook. That also resulted in an error, see output log.

What else should I try to help you with reproducing and figuring out this issue?

### VS Code Version

Version: 1.83.1 (user setup) Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc Date: 2023-10-10T23:48:05.904Z Electron: 25.8.4 ElectronBuildId: 24154031 Chromium: 114.0.5735.289 Node.js: 18.15.0 V8: 11.4.183.29-electron.0 OS: Windows_NT x64 10.0.19045

### Jupyter Extension Version

v2023.9.1102792234

### Jupyter logs

```shell
Visual Studio Code (1.83.1, wsl, desktop)
Jupyter Extension Version: 2023.9.1102792234.
Python Extension Version: 2023.18.0.
Platform: linux (x64).
Workspace folder ~/cv/exercise_1, Home = /home/stefnotch
13:10:42.461 [info] User belongs to experiment group 'NewJupyterSession'
13:10:42.929 [info] Start refreshing Kernel Picker (1697800242929)
13:10:42.950 [info] Using Pylance
13:10:45.366 [info] End refreshing Kernel Picker (1697800242929)
13:10:47.621 [info] Process Execution: ~/miniconda3/envs/gcv_exercise_1/bin/python -m pip list
13:14:32.251 [info] Starting interactive window for resource '' with controller '.jvsc74a57bd024d109f3b7a3546e0168a8b344c1f9d92f67b36e8ce35a560ab6c6446d1c9b0a.~/miniconda3/envs/gcv_exercise_1/python.~/miniconda3/envs/gcv_exercise_1/python.-m#ipykernel_launcher (Interactive)'
13:20:47.802 [info] Start refreshing Kernel Picker (1697800847802)
13:20:48.818 [info] End refreshing Kernel Picker (1697800847802)
13:23:21.178 [info] Starting interactive window for resource '' with controller '.jvsc74a57bd024d109f3b7a3546e0168a8b344c1f9d92f67b36e8ce35a560ab6c6446d1c9b0a.~/miniconda3/envs/gcv_exercise_1/python.~/miniconda3/envs/gcv_exercise_1/python.-m#ipykernel_launcher (Interactive)'
13:24:10.436 [error] listenForErrors Error: Missing viewType for 'vscode-remote://wsl%2Bubuntu~/cv/exercise_1/test.ipynb'
    at r.resolve (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2349:71025)
    at async g.$tryOpenNotebook (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2349:10168)
13:24:10.437 [warn] DataScience Error Error: Missing viewType for 'vscode-remote://wsl%2Bubuntu~/cv/exercise_1/test.ipynb'
    at r.resolve (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2349:71025)
    at async g.$tryOpenNotebook (vscode-file://vscode-app/c:/Users/<username>/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2349:10168)
```

### Anaconda Version (if applicable)

conda 23.9.0 (Miniconda)

### Running Jupyter locally or remotely?

None

**Comment by stefnotch** [comment]
![image](https://github.com/microsoft/vscode-jupyter/assets/10220080/69e0aad1-f460-42ca-a1dc-d3bf9ebe1a1d)

Turns out that the problem is between the keyboard and the chair. Ages ago, I must have gone through the default extensions and disabled the ones where I was certain that I wouldn't need them.
