### ISSUE TITLE
"Run File in Interactive Window" and "Run All Cells" are swapped

### ISSUE THREAD

**Issue by Jacob-Stevens-Haas** [microsoft/vscode-jupyter#14551]
If a file has cell definition (`# %%`), anything preceding a cell isn't included in "Run File in Interactive Window".  However, at least in my mind, "Run File" means run the whole file.  This is confusing because the command "Run All Cells" exists, but has the **opposite behvaior**: it joins the code above the first cell with the first cell and then running.   

This could be a consequence of a choice for the behavior of "Run Cells Above Current Cell", discussed in #2753.

## Environment data

-   VS Code version: 1.83.1
-   Jupyter Extension version (available under the Extensions sidebar): v2023.9.1102792234
-   Python Extension version (available under the Extensions sidebar): v2023.18.0
-   OS (Windows | Mac | Linux distro) and version: Linux 6.2.0-35-generic, 22.04.1-Ubuntu
-   Python and/or Anaconda version: 3.10.12
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local | Remote | Local

## Actual behaviour

"Run File" only runs cells
"Run All Cells" runs the whole file

## Expected behaviour

"Run File" runs the whole file.
"Run All Cells" only runs cells
## Steps to reproduce:

_debug.py_
```python
x = 1

# %%
x
```
"Run File in Interactive Window" begins with the cell, raising `NameError: x is not defined`
"Run all Cells" combines them in a cell:
```
x = 1
# %%
x
```
## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Visual Studio Code (1.83.1, undefined, desktop)
Jupyter Extension Version: 2023.9.1102792234.
Python Extension Version: 2023.18.0.
Platform: linux (x64).
Workspace folder ~/github/matplotlib, Home = /home/xenophon
10:09:01.342 [info] User belongs to experiment group 'NewJupyterSession'
10:09:02.065 [debug] Get Custom Env Variables, Class name = Kl (started execution), Arg 1: undefined, Arg 2: "RunPythonCode"
10:09:02.066 [info] Start refreshing Kernel Picker (1698138542066)
10:09:02.096 [info] Using Pylance
10:09:02.146 [debug] Get Custom Env Variables, Class name = Kl, completed in 81ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
10:09:02.146 [debug] Jupyter Paths /kernels: 
10:09:02.147 [debug] Kernel Spec Root Paths, /usr/share/jupyter/kernels, /usr/local/share/jupyter/kernels, ~/.local/share/jupyter/kernels
10:09:02.147 [debug] Search for KernelSpecs in Interpreter ~/github/matplotlib/env/bin/python
10:09:02.147 [debug] Finding Global Python KernelSpecs
10:09:02.153 [debug] Getting activated env variables, Class name = za (started execution), Arg 1: "~/github/matplotlib", Arg 2: "~/github/matplotlib/env/bin/python", Arg 3: undefined
10:09:02.153 [debug] Get Custom Env Variables, Class name = Kl (started execution), Arg 1: "~/github/matplotlib", Arg 2: "RunPythonCode"
10:09:02.154 [debug] Get Custom Env Variables, Class name = Kl, completed in 1ms, has a truthy return value, Arg 1: "~/github/matplotlib", Arg 2: "RunPythonCode"
10:09:02.163 [debug] Search for KernelSpecs in Interpreter /bin/python2
10:09:02.164 [debug] Finding Global Python KernelSpecs
10:09:02.170 [debug] Search for KernelSpecs in Interpreter /bin/python3
10:09:02.171 [debug] Search for KernelSpecs in Interpreter /usr/bin/python2
10:09:02.171 [debug] Search for KernelSpecs in Interpreter /usr/bin/python3
10:09:02.172 [debug] Search for KernelSpecs in Interpreter ~/github/gen-experiments/env/bin/python
10:09:02.173 [debug] Full interpreter list is length: 6, ~/github/matplotlib/env/bin/python:env:Venv:~/github/matplotlib/env/bin/python, /bin/python2::Unknown:/bin/python2, /bin/python3::Unknown:/bin/python3, /usr/bin/python2::Unknown:/usr/bin/python2, /usr/bin/python3::Unknown:/usr/bin/python3, ~/github/gen-experiments/env/bin/python:env:Venv:~/github/gen-experiments/env/bin/python
10:09:03.394 [debug] Kernels for interpreter /bin/python2 are .jvsc74a57bd0e55666fbbf217aa3df372b978577f47b6009e2f78e2ec76a584f49cd54a1e62c./bin/python2./bin/python2.-m#ipykernel_launcher
10:09:03.396 [debug] Kernels for interpreter /bin/python3 are .jvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1./bin/python3./bin/python3.-m#ipykernel_launcher
10:09:03.396 [debug] Kernels for interpreter /usr/bin/python2 are .jvsc74a57bd0f92b2924b84ff19c1c3dc485f7644d4486f64738191026bf8e6de303969141b5./usr/bin/python2./usr/bin/python2.-m#ipykernel_launcher
10:09:03.396 [debug] Kernels for interpreter /usr/bin/python3 are .jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6./usr/bin/python3./usr/bin/python3.-m#ipykernel_launcher
10:09:03.629 [debug] creating new code watcher with matching document file://~/github/matplotlib/debugme.py
10:09:03.630 [debug] CodeLensFactory: Generating new code lenses for version 1 of document file://~/github/matplotlib/debugme.py for commands jupyter.runcell, jupyter.runallcellsabove, jupyter.debugcell, jupyter.debugcontinue, jupyter.debugstop, jupyter.debugstepover
10:09:03.728 [debug] Loading kernelspec from ~/.local/share/jupyter/kernels/.home.<username>.github.gen-experiments.env.bin.python/kernel.json 
10:09:03.729 [debug] Loading kernelspec from ~/.local/share/jupyter/kernels/python3/kernel.json 
10:09:03.729 [debug] Loading kernelspec from ~/github/matplotlib/env/share/jupyter/kernels/python3/kernel.json for ~/github/matplotlib/env/bin/python
10:09:05.516 [debug] Loading kernelspec from ~/github/gen-experiments/env/share/jupyter/kernels/python3/kernel.json for ~/github/gen-experiments/env/bin/python
10:09:06.074 [debug] Kernel Specs found in interpreter ~/github/matplotlib/env/bin/python are [{"specFile":"~/github/matplotlib/env/share/jupyter/kernels/python3/kernel.json","interpreterPath":"~/github/matplotlib/env/bin/python","isRegisteredByVSC":"registeredByNewVersionOfExt","name":"pythonjvsc74a57bd0ac41613be2e2e7597f4b5c6871b04d8d72092470c8a206a3a55eb0b51c9f3fb8","argv":["python","-m","ipykernel_launcher","-f","{connection_file}"],"language":"python","executable":"python","display_name":"Python 3 (ipykernel)","metadata":{"debugger":true,"vscode":{"originalSpecFile":"~/github/matplotlib/env/share/jupyter/kernels/python3/kernel.json","originalDisplayName":"Python 3 (ipykernel)"}}}]
10:09:06.074 [debug] Hiding default kernel spec 'Python 3 (ipykernel)', 'pythonjvsc74a57bd0ac41613be2e2e7597f4b5c6871b04d8d72092470c8a206a3a55eb0b51c9f3fb8', /python for interpreter ~/github/matplotlib/env/bin/python and spec ~/github/matplotlib/env/share/jupyter/kernels/python3/kernel.json
10:09:06.074 [debug] Kernels for interpreter ~/github/matplotlib/env/bin/python are .jvsc74a57bd0ac41613be2e2e7597f4b5c6871b04d8d72092470c8a206a3a55eb0b51c9f3fb8.~/github/matplotlib/env/python.~/github/matplotlib/env/python.-m#ipykernel_launcher
10:09:06.075 [debug] Conda file returned by Python Extension is conda
10:09:06.079 [debug] Kernel Specs found in interpreter ~/github/gen-experiments/env/bin/python are [{"specFile":"~/github/gen-experiments/env/share/jupyter/kernels/python3/kernel.json","interpreterPath":"~/github/gen-experiments/env/bin/python","isRegisteredByVSC":"registeredByNewVersionOfExt","name":"pythonjvsc74a57bd083e2710d0cc33b37f5605bb899276d50043cb11e2f8259d41c24cf4a12e55a10","argv":["python","-m","ipykernel_launcher","-f","{connection_file}"],"language":"python","executable":"python","display_name":"Python 3 (ipykernel)","metadata":{"debugger":true,"vscode":{"originalSpecFile":"~/github/gen-experiments/env/share/jupyter/kernels/python3/kernel.json","originalDisplayName":"Python 3 (ipykernel)"}}}]
10:09:06.079 [debug] Hiding default kernel spec 'Python 3 (ipykernel)', 'pythonjvsc74a57bd083e2710d0cc33b37f5605bb899276d50043cb11e2f8259d41c24cf4a12e55a10', /python for interpreter ~/github/gen-experiments/env/bin/python and spec ~/github/gen-experiments/env/share/jupyter/kernels/python3/kernel.json
10:09:06.079 [debug] Kernels for interpreter ~/github/gen-experiments/env/bin/python are .jvsc74a57bd083e2710d0cc33b37f5605bb899276d50043cb11e2f8259d41c24cf4a12e55a10.~/github/gen-experiments/env/python.~/github/gen-experiments/env/python.-m#ipykernel_launcher
10:09:06.533 [debug] Got env vars with python ~/github/matplotlib/env/bin/python, with env var count 75 in 4380ms. 
    PATH value is ~/github/matplotlib/env/bin:~/.local/bin:~/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin and 
    Path value is undefined
10:09:06.533 [debug] Prepend PATH with python bin for ~/github/matplotlib/env/bin/python, 
    PATH value is ~/github/matplotlib/env/bin:~/.local/bin:~/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin and 
    Path value is undefined
10:09:06.533 [debug] Activated Env Variables for ~/github/matplotlib/env/bin/python, 
    PATH value is ~/github/matplotlib/env/bin:~/.local/bin:~/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin and 
    Path value is undefined
10:09:06.534 [debug] Getting activated env variables, Class name = za, completed in 4381ms, has a truthy return value, Arg 1: "~/github/matplotlib", Arg 2: "~/github/matplotlib/env/bin/python", Arg 3: undefined
10:09:06.575 [info] Process Execution: ~/github/matplotlib/env/bin/python -m pip list
10:09:06.843 [info] End refreshing Kernel Picker (1698138542066)
10:09:21.080 [debug] Updating cache with Local kernels startUsingLocalKernelSpec:'..home.<username>.github.gen-experiments.env.bin.python.~/github/gen-experiments/env/python.~/github/gen-experiments/env/python.-m#ipykernel_launcher (interpreter id = ~/github/gen-experiments/env/bin/python)', Added = , Updated = , Removed = 
10:09:30.100 [info] Starting interactive window for resource '~/github/matplotlib/debugme.py' with controller '.jvsc74a57bd0ac41613be2e2e7597f4b5c6871b04d8d72092470c8a206a3a55eb0b51c9f3fb8.~/github/matplotlib/env/python.~/github/matplotlib/env/python.-m#ipykernel_launcher (Interactive)'
10:09:30.270 [info] Start refreshing Interpreter Kernel Picker
10:09:30.270 [info] Start refreshing Kernel Picker (1698138570270)
10:09:30.293 [debug] No controller, hence notebook communications cannot be initialized for editor /Interactive-1.interactive
10:09:30.361 [debug] Initialize notebook communications for editor /Interactive-1.interactive
10:09:30.361 [debug] Resolving notebook UI Comms (resolve) for /Interactive-1.interactive
10:09:30.361 [debug] initialize CommonMessageCoordinator
10:09:30.363 [debug] IPyWidgetMessageDispatcher.initialize
10:09:30.364 [debug] Attempting to determine version of IPyWidgets
10:09:30.367 [debug] Controller selection change completed
10:09:30.772 [debug] Interactive Window Editor Created: untitled:/Interactive-1.interactive with input box: vscode-interactive-input:/InteractiveInput-1
10:09:30.781 [debug] Attempting to determine version of IPyWidgets
10:09:30.796 [debug] start the kernel, options.disableUI=false for /Interactive-1.interactive
10:09:30.801 [debug] Waiting for IPyWidgets version
10:09:30.801 [debug] Waiting for IPyWidgets version promise
10:09:30.801 [debug] Waiting for IPyWidgets version
10:09:30.801 [debug] Waiting for IPyWidgets version promise
10:09:30.803 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd0ac41613be2e2e7597f4b5c6871b04d8d72092470c8a206a3a55eb0b51c9f3fb8.~/github/matplotlib/env/python.~/github/matplotlib/env/python.-m#ipykernel_launcher  (Python Path: ~/github/matplotlib/env/bin/python, Venv, env, 3.10.12) for '/Interactive-1.interactive' (disableUI=false)
10:09:30.807 [debug] Creating raw notebook for resource '~/github/matplotlib/debugme.py'
10:09:30.815 [debug] Kernel Launcher. launch, Class name = ty (started execution), Arg 1: "~/github/matplotlib/env/python.~/github/matplotlib/env/python.-m#ipykernel_launcher", Arg 2: 60000, Arg 3: "~/github/matplotlib/debugme.py", Arg 4: "~/github/matplotlib", Arg 5: ""
10:09:30.832 [debug] Getting activated env variables, Class name = za (started execution), Arg 1: "~/github/matplotlib/debugme.py", Arg 2: "~/github/matplotlib/env/bin/python", Arg 3: undefined
10:09:30.832 [debug] Get Custom Env Variables, Class name = Kl (started execution), Arg 1: "~/github/matplotlib/debugme.py", Arg 2: "RunPythonCode"
10:09:30.833 [debug] Get Custom Env Variables, Class name = Kl, completed in 1ms, has a truthy return value, Arg 1: "~/github/matplotlib/debugme.py", Arg 2: "RunPythonCode"
10:09:30.834 [debug] Got env vars with python ~/github/matplotlib/env/bin/python, with env var count 75 in 2ms. 
    PATH value is ~/github/matplotlib/env/bin:~/.local/bin:~/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin and 
    Path value is undefined
10:09:30.834 [debug] Prepend PATH with python bin for ~/github/matplotlib/env/bin/python, 
    PATH value is ~/github/matplotlib/env/bin:~/.local/bin:~/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin and 
    Path value is undefined
10:09:30.835 [debug] Activated Env Variables for ~/github/matplotlib/env/bin/python, 
    PATH value is ~/github/matplotlib/env/bin:~/.local/bin:~/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin and 
    Path value is undefined
10:09:30.835 [debug] Getting activated env variables, Class name = za, completed in 3ms, has a truthy return value, Arg 1: "~/github/matplotlib/debugme.py", Arg 2: "~/github/matplotlib/env/bin/python", Arg 3: undefined
10:09:30.878 [info] Process Execution: ~/github/matplotlib/env/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
10:09:30.916 [debug] Launching kernel in kernelProcess.ts, Class name = Zv (started execution), Arg 1: "~/github/matplotlib", Arg 2: ""
10:09:30.930 [debug] Kernel Env Variables for ~/.vscode/extensions/ms-toolsai.jupyter-2023.9.1102792234-linux-x64/temp/jupyter/kernels/pythonjvsc74a57bd0ac41613be2e2e7597f4b5c6871b04d8d72092470c8a206a3a55eb0b51c9f3fb8/kernel.json, PATH value is ~/github/matplotlib/env/bin:~/.local/bin:~/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
10:09:30.975 [info] Process Execution: ~/github/matplotlib/env/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"0292e11d-630a-43b7-b06c-39215f5bd1b0" --shell=9002 --transport="tcp" --iopub=9004 --f=~/.local/share/jupyter/runtime/kernel-v2-31453znNyWIPmyDS2.json
    > cwd: ~/github/matplotlib
10:09:30.977 [debug] Launching kernel in kernelProcess.ts, Class name = Zv, completed in 60ms, has a truthy return value, Arg 1: "~/github/matplotlib", Arg 2: ""
10:09:31.469 [debug] Full interpreter list is length: 6, /bin/python2::Unknown:/bin/python2, /bin/python3::Unknown:/bin/python3, /usr/bin/python2::Unknown:/usr/bin/python2, /usr/bin/python3::Unknown:/usr/bin/python3, ~/github/matplotlib/env/bin/python:env:Venv:~/github/matplotlib/env/bin/python, ~/github/gen-experiments/env/bin/python:env:Venv:~/github/gen-experiments/env/bin/python
10:09:31.469 [debug] Refreshed Environments
10:09:31.520 [info] ipykernel version & path 6.25.2, ~/github/matplotlib/env/lib/python3.10/site-packages/ipykernel/__init__.py for ~/github/matplotlib/env/bin/python
10:09:31.965 [debug] KernelProcess output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-v2-31453znNyWIPmyDS2.json

10:09:31.966 [debug] Kernel Output: To connect another client to this kernel, use: --existing kernel-v2-31453znNyWIPmyDS2.json

10:09:32.018 [debug] Kernel Launcher. launch, Class name = ty, completed in 1203ms, has a truthy return value, Arg 1: "~/github/matplotlib/env/python.~/github/matplotlib/env/python.-m#ipykernel_launcher", Arg 2: 60000, Arg 3: "~/github/matplotlib/debugme.py", Arg 4: "~/github/matplotlib", Arg 5: ""
10:09:32.033 [debug] Waiting for Raw Session to be ready in postStartRawSession
10:09:32.033 [debug] Waiting for Raw session to be ready, currently connected
10:09:32.033 [debug] Raw session connected
10:09:32.033 [debug] Waiting for Raw session to be ready for 30s
10:09:32.034 [debug] Waited for Raw session to be ready & got connected
10:09:32.034 [debug] Successfully waited for Raw Session to be ready in postStartRawSession
10:09:32.034 [debug] Kernel status before requesting kernel info and after ready is unknown
10:09:32.034 [debug] Sending request for kernelInfo
10:09:32.067 [debug] Got response for requestKernelInfo
10:09:32.067 [debug] Successfully completed postStartRawSession
10:09:32.071 [debug] Begin sendTelemetryForPythonKernelExecutable
10:09:32.071 [debug] Executing silently Code (idle) = import sys as _VSCODE_sys\nprint(_VSCODE_sys.executable); del _VSCODE_sys
10:09:32.121 [debug] Executing silently Code (completed) = import sys as _VSCODE_sys\nprint(_VSCODE_sys.executable); del _VSCODE_sys with 1 output(s)
10:09:32.122 [debug] End sendTelemetryForPythonKernelExecutable
10:09:32.123 [debug] Started running kernel initialization for /Interactive-1.interactive
10:09:32.124 [debug] Executing silently Code (idle) = try:\nimport ipywidgets as _VSCODE_ipywidgets\nprint("e976ee50-99ed-4aba-9b6b-9dcd5634d07d:IPy
10:09:32.227 [debug] Executing silently Code (completed) = try:\nimport ipywidgets as _VSCODE_ipywidgets\nprint("e976ee50-99ed-4aba-9b6b-9dcd5634d07d:IPy with 1 output(s)
10:09:32.227 [debug] Determined IPyWidgets Version as 8 and event fired
10:09:32.228 [debug] Version of IPyWidgets 8 determined after 1.864s
10:09:32.228 [debug] Version of IPyWidgets 8 determined after 1.447s
10:09:32.231 [debug] Executing silently Code (idle) = import types as _VSCODE_types\nimport os\nimport hashlib as _VSCODE_hashlib\nfrom IPython import get_ip
10:09:32.271 [debug] Executing silently Code (completed) = import types as _VSCODE_types\nimport os\nimport hashlib as _VSCODE_hashlib\nfrom IPython import get_ip with 1 output(s)
10:09:32.272 [debug] Requesting Kernel info
10:09:32.273 [debug] Got Kernel info
10:09:32.273 [debug] End running kernel initialization, now waiting for idle
10:09:32.274 [debug] Waiting for 60000ms idle on (kernel): 0a2a972e-a56c-4196-885d-589c3b8732c2 -> idle
10:09:32.276 [debug] Finished waiting for idle on (kernel): 0a2a972e-a56c-4196-885d-589c3b8732c2 -> idle
10:09:32.277 [debug] End running kernel initialization, session is idle
10:09:32.279 [debug] IPyWidgetScriptSource.initialize
10:09:32.280 [debug] Registering commtarget jupyter.widget
10:09:32.280 [debug] IPyWidgetMessageDispatcher.initialize
10:09:32.283 [debug] getDataDirsImpl, Class name = vf (started execution), Arg 1: "~/github/matplotlib/debugme.py", Arg 2: "~/github/matplotlib/env/bin/python"
10:09:32.291 [debug] Get Custom Env Variables, Class name = Kl (started execution), Arg 1: undefined, Arg 2: "RunPythonCode"
10:09:32.292 [debug] Get Custom Env Variables, Class name = Kl, completed in 1ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
10:09:32.292 [debug] Jupyter Paths : 
10:09:32.294 [debug] Initializing __file__ in setFileInKernel with file://~/github/matplotlib/debugme.py for mode perFile
10:09:32.299 [debug] Executing silently Code (idle) = __file__ = '~/github/matplotlib/debugme.py'
10:09:32.353 [info] Process Execution: ~/github/matplotlib/env/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2023.9.1102792234-linux-x64/pythonFiles/printJupyterDataDir.py
10:09:32.362 [info] Generated code for 1 = <ipython-input-1-3ed2b5c50886> with 2 lines
10:09:32.379 [debug] Executing silently Code (completed) = __file__ = '~/github/matplotlib/debugme.py' with 0 output(s)
10:09:32.415 [debug] Execution Request Sent to Kernel for cell 1
10:09:32.452 [debug] Start cell 1 execution @ 1698138572452 (clear output)
10:09:32.453 [info] Kernel acknowledged execution of cell 1 @ 1698138572452
10:09:32.455 [debug] getDataDirsImpl, Class name = vf, completed in 172ms, has a truthy return value, Arg 1: "~/github/matplotlib/debugme.py", Arg 2: "~/github/matplotlib/env/bin/python"
10:09:32.470 [info] End refreshing Kernel Picker (1698138570270)
10:09:32.927 [info] End cell 1 execution @ 1698138572918, started @ 1698138572452, elapsed time = 0.466s
10:09:32.928 [warn] Cancel all remaining cells due to cancellation or failure in execution
10:09:32.928 [debug] Cancel pending cells
10:09:32.933 [debug] Cell 1 executed with state Error
10:09:32.976 [debug] IPyWidgetMessageDispatcher.initialize
10:09:32.977 [debug] Web view is ready to receive widget messages
10:09:33.073 [debug] Widget Message: Received IPyWidgets_kernelOptions in ScriptManager
10:09:33.073 [debug] Widget Message: Received IPyWidgetMessages.IPyWidgets_kernelOptions
10:09:33.073 [debug] IPyWidgetMessageDispatcher.initialize
10:09:33.074 [debug] IPyWidgetMessageDispatcher.initialize
10:09:33.081 [debug] Widget Message: data-base-url set to https://file%2B.vscode-resource.vscode-cdn.net~/.vscode/extensions/ms-toolsai.jupyter-2023.9.1102792234-linux-x64/temp/scripts/0eddfbf9f25366767103f02fcb0d358df14e43d2e00f3ec2a72c2633ad48760d/jupyter
10:09:33.084 [debug] Widget Message: Received IPyWidgets_kernelOptions in ScriptManager
10:09:33.084 [debug] Widget Message: Received IPyWidgetMessages.IPyWidgets_kernelOptions
10:09:33.085 [debug] Widget Message: data-base-url set to https://file%2B.vscode-resource.vscode-cdn.net~/.vscode/extensions/ms-toolsai.jupyter-2023.9.1102792234-linux-x64/temp/scripts/0eddfbf9f25366767103f02fcb0d358df14e43d2e00f3ec2a72c2633ad48760d/jupyter
10:09:33.085 [debug] Widget Message: Received IPyWidget scripts [{"moduleName":"jupyterlab-plotly","scriptUri":"https://file%2B.vscode-resource.vscode-cdn.net~/.vscode/extensions/ms-toolsai.jupyter-2023.9.1102792234-linux-x64/temp/scripts/0eddfbf9f25366767103f02fcb0d358df14e43d2e00f3ec2a72c2633ad48760d/jupyter/nbextensions/jupyterlab-plotly/index","source":"local"}]
10:09:33.086 [debug] Widget Message: Source for IPyWidget jupyterlab-plotly found in local @ https://file%2B.vscode-resource.vscode-cdn.net~/.vscode/extensions/ms-toolsai.jupyter-2023.9.1102792234-linux-x64/temp/scripts/0eddfbf9f25366767103f02fcb0d358df14e43d2e00f3ec2a72c2633ad48760d/jupyter/nbextensions/jupyterlab-plotly/index.
10:09:33.086 [debug] Widget Message: Registering IPyWidget jupyterlab-plotly found in https://file%2B.vscode-resource.vscode-cdn.net~/.vscode/extensions/ms-toolsai.jupyter-2023.9.1102792234-linux-x64/temp/scripts/0eddfbf9f25366767103f02fcb0d358df14e43d2e00f3ec2a72c2633ad48760d/jupyter/nbextensions/jupyterlab-plotly/index.
10:09:46.475 [debug] Updating cache with Local kernels startUsingLocalKernelSpec:'..home.<username>.github.gen-experiments.env.bin.python.~/github/gen-experiments/env/python.~/github/gen-experiments/env/python.-m#ipykernel_launcher (interpreter id = ~/github/gen-experiments/env/bin/python)', Added = , Updated = , Removed = 
10:32:21.324 [info] Disposing kernel .jvsc74a57bd0ac41613be2e2e7597f4b5c6871b04d8d72092470c8a206a3a55eb0b51c9f3fb8.~/github/matplotlib/env/python.~/github/matplotlib/env/python.-m#ipykernel_launcher for notebook /Interactive-1.interactive due to selection of another kernel or closing of the notebook
10:32:21.325 [info] Dispose Kernel '/Interactive-1.interactive' associated with '~/github/matplotlib/debugme.py'
10:32:21.325 [debug] Cancel pending cells
10:32:21.326 [debug] Shutdown session 0a2a972e-a56c-4196-885d-589c3b8732c2, .jvsc74a57bd0ac41613be2e2e7597f4b5c6871b04d8d72092470c8a206a3a55eb0b51c9f3fb8.~/github/matplotlib/env/python.~/github/matplotlib/env/python.-m#ipykernel_launcher - start called from Error: 
	at xy.shutdown (~/.vscode/extensions/ms-toolsai.jupyter-2023.9.1102792234-linux-x64/out/extension.node.js:24:123857)
	at xy.disposeAsync (~/.vscode/extensions/ms-toolsai.jupyter-2023.9.1102792234-linux-x64/out/extension.node.js:24:123279)
	at ~/.vscode/extensions/ms-toolsai.jupyter-2023.9.1102792234-linux-x64/out/extension.node.js:17:236128
	at Qg.dispose (~/.vscode/extensions/ms-toolsai.jupyter-2023.9.1102792234-linux-x64/out/extension.node.js:17:236342)
	at tw.onDidChangeSelectedNotebooks (~/.vscode/extensions/ms-toolsai.jupyter-2023.9.1102792234-linux-x64/out/extension.node.js:24:221271)
	at c.z (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at c.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at m.$acceptNotebookAssociation (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:101912)
	at i.S (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:134:10827)
	at i.Q (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:134:10593)
	at i.M (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:134:9683)
	at i.L (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:134:8762)
	at s.value (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:134:7565)
	at c.z (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at c.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at m.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:14010)
	at s.value (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:7902)
	at c.z (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at c.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at m.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:14010)
	at MessagePortMain.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:6182)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
10:32:21.327 [info] Dispose Kernel process 32051.
10:32:21.360 [debug] Kernel got disposed, hence there is no longer a kernel associated with /Interactive-1.interactive
10:32:21.364 [debug] Shutdown session 0a2a972e-a56c-4196-885d-589c3b8732c2, .jvsc74a57bd0ac41613be2e2e7597f4b5c6871b04d8d72092470c8a206a3a55eb0b51c9f3fb8.~/github/matplotlib/env/python.~/github/matplotlib/env/python.-m#ipykernel_launcher - shutdown complete
10:32:21.376 [debug] Closing interactive window: untitled:/Interactive-1.interactive
10:32:21.376 [info] Dispose Kernel '/Interactive-1.interactive' associated with '~/github/matplotlib/debugme.py'
10:32:21.377 [debug] Cancel executions after closing notebook /Interactive-1.interactive
10:32:21.390 [debug] Disposed Kernel process 32051.
10:32:21.408 [debug] KernelProcess Exited, Exit Code - undefined

```

</p>
</details>

**Comment by Jacob-Stevens-Haas** [comment]
Oops, I saw I had some typos in the above comment.  The description was correct and accurate, but below that I swapped "actual" and "expected" headers.
