### ISSUE TITLE
Python interactive window and others not working when running in WSL.

### ISSUE THREAD

**Issue by rasmus98** [microsoft/vscode-jupyter#1455]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. Open vs code in wsl

2. try to open an interactive window or even the "python - get started" window

3. See nothing :(

![image](https://user-images.githubusercontent.com/37410554/94135292-8da77200-fe63-11ea-81dd-631bf430cf3b.png)

Strangely, this has worked in the past on my pc, but after some update (dont know which one) it suddenly does not.

I have tried running in new WSL distro using --export and --import as is descibed here:
https://stackoverflow.com/questions/51584765/how-do-you-install-multiple-separate-instances-of-ubuntu-in-wsl

I have also tried deleting the .vscode-server folder to force a reinstall, reinstalled vs code, downgraded to version 1.48, installed the insider version as well as of cause restarted windows. Nothing works. These diagnostics is from the insider build to avoid having this be a duplicate of the numerous other similar bug reports.

Similar to other reporters, the developer tools report a number of 404 errors accessing files:
`
Failed to load resource: the server responded with a status of 404 (Not Found)
require.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
ipywidgets.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
monaco.bundle.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
commons.initial.bundle.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
interactiveWindow.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
require.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
ipywidgets.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
monaco.bundle.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
commons.initial.bundle.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
interactiveWindow.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
font-awesome.min.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
`
As an example, the path to require.js is:
`
vscode-webview-resource://76cbf23d-3806-44d8-8d30-dcdf83840ad2/file///home/rasmus/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/out/datascience-ui/notebook/require.js
`
I have no clue about the first part, but 
`
/home/rasmus/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/out/datascience-ui/notebook/require.js
`
exists as a file in my wsl, so i am stuck from here.

## output from python as requested:¨

`User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'RunByLine - experiment'
User belongs to experiment group 'CustomEditorSupport - control'
> conda --version
> pyenv root
> python3.7 ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda info --json
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
Error 2020-09-24 12:54:32: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://wsl+ubuntu-20.04/home/rasmus/.config/Code - Insiders/User/settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/home/rasmus/.config/Code - Insiders/User/settings.json')
	at _handleError (/home/rasmus/.vscode-server-insiders/bin/73b33dcbc8204c23ae30b53ce129b32c6da98197/out/vs/server/remoteExtensionHostProcess.js:747:838)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async y.readText (/home/rasmus/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/out/client/extension.js:1:498533)
	at async p.doesFileNeedToBeFixed (/home/rasmus/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/out/client/extension.js:56:960982)
	at async /home/rasmus/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/out/client/extension.js:56:960109
	at async Promise.all (index 0)
	at async p.getFilesToBeFixed (/home/rasmus/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/out/client/extension.js:56:960055)
	at async p.updateTestSettings (/home/rasmus/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/out/client/extension.js:56:959682)] {
  code: 'FileNotFound',
  name: 'EntryNotFound (FileSystemError)'
}
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
Error 2020-09-24 12:54:32: Jupyter Kernel Spec not found for a local connection
Error 2020-09-24 12:54:32: Failed to initialize S Failed to find a kernelspec to use for ipykernel launch
Error 2020-09-24 12:54:32: Failed to initialize ipywidgetHandler Failed to find a kernelspec to use for ipykernel launch
Error 2020-09-24 12:54:32: DataScience Error Failed to find a kernelspec to use for ipykernel launch
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
Starting Jedi Python language engine.
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
Error 2020-09-24 12:54:32: Diagnostic Code: InvalidPythonInterpreterDiagnostic, Message: No Python interpreter is selected. You need to select a Python interpreter to enable features such as IntelliSense, linting, and debugging.
Diagnostic Code: InvalidPythonInterpreterDiagnostic, Message: No Python interpreter is selected. You need to select a Python interpreter to enable features such as IntelliSense, linting, and debugging.
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
Error 2020-09-24 12:54:32: Jupyter Kernel Spec not found for a local connection
Error 2020-09-24 12:54:32: DataScience Error Failed to find a kernelspec to use for ipykernel launch
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: /mnt/c/Users/Rasmus/Programming/MLIntro/assignment2
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: /mnt/c/Users/Rasmus/Programming/MLIntro/assignment2
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: /mnt/c/Users/Rasmus/Programming/MLIntro/assignment2
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: /mnt/c/Users/Rasmus/Programming/MLIntro/assignment2
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: /mnt/c/Users/Rasmus/Programming/MLIntro/assignment2
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: /mnt/c/Users/Rasmus/Programming/MLIntro/assignment2
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py site --user-site
cwd: /mnt/c/Users/Rasmus/Programming/MLIntro/assignment2
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py site --user-site
cwd: /mnt/c/Users/Rasmus/Programming/MLIntro/assignment2
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text /mnt/c/Users/Rasmus/Programming/MLIntro/assignment2/Nielsen_h2.py
cwd: /mnt/c/Users/Rasmus/Programming/MLIntro/assignment2
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text /mnt/c/Users/Rasmus/Programming/MLIntro/assignment2/Nielsen_h2.py
cwd: /mnt/c/Users/Rasmus/Programming/MLIntro/assignment2
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import pylint"
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import pylint"

Linter 'pylint' is not installed. Please install it or select another linter".
Error: spawn C:\Users\rasmu\anaconda3\python.exe ENOENT
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> C:\Users\rasmu\anaconda3\python.exe ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> /bin/python3 ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py pip --version
Error 2020-09-24 12:54:40: Failed to download and store experiments, Class name = b, completed in 12872ms, has a falsy return value, , Return Value: undefined [Error: getaddrinfo EAI_AGAIN raw.githubusercontent.com
	at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)] {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'raw.githubusercontent.com'
}
Error 2020-09-24 12:54:40: Failed to initialize experiments, Class name = b, completed in 12873ms, has a falsy return value, , Return Value: undefined [Error: getaddrinfo EAI_AGAIN raw.githubusercontent.com
	at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)] {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'raw.githubusercontent.com'
}
Starting Jedi Python language engine.
Python interpreter path: /bin/python3
> /bin/python3 ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: /mnt/c/Users/Rasmus/Programming/MLIntro/assignment2
> /bin/python3 ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: /mnt/c/Users/Rasmus/Programming/MLIntro/assignment2
> /bin/python3 ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: /mnt/c/Users/Rasmus/Programming/MLIntro/assignment2
> /bin/python3 ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: /mnt/c/Users/Rasmus/Programming/MLIntro/assignment2
> /bin/python3 ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: /mnt/c/Users/Rasmus/Programming/MLIntro/assignment2
> /bin/python3 ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: /mnt/c/Users/Rasmus/Programming/MLIntro/assignment2
> /bin/python3 ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py site --user-site
cwd: /mnt/c/Users/Rasmus/Programming/MLIntro/assignment2
> /bin/python3 ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py site --user-site
cwd: /mnt/c/Users/Rasmus/Programming/MLIntro/assignment2
> /bin/python3 ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/completion.py
> /bin/python3 ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/completion.py
Error 2020-09-24 12:54:41: stderr jediProxy Error (stderr) /home/rasmus/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/completion.py:584: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).get_names instead.
  jedi.api.names(

> /bin/python3 ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text /mnt/c/Users/Rasmus/Programming/MLIntro/assignment2/Nielsen_h2.py
cwd: /mnt/c/Users/Rasmus/Programming/MLIntro/assignment2
> /bin/python3 ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text /mnt/c/Users/Rasmus/Programming/MLIntro/assignment2/Nielsen_h2.py
cwd: /mnt/c/Users/Rasmus/Programming/MLIntro/assignment2
> /bin/python3 ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /bin/python3 ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
Error 2020-09-24 12:54:44: Jupyter Kernel Spec not found for a local connection
> /bin/python3 ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /bin/python3 ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /bin/python3 ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /bin/python3 ~/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
##########Linting Output - pylint##########

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)

> conda --version
Error 2020-09-24 12:55:33: stderr jediProxy Error (stderr) /home/rasmus/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/completion.py:592: DeprecationWarning: Providing the line is now done in the functions themselves like `Script(...).complete(line, column)`
  script = jedi.Script(
/home/rasmus/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/completion.py:592: DeprecationWarning: Providing the column is now done in the functions themselves like `Script(...).complete(line, column)`
  script = jedi.Script(

Error 2020-09-24 12:55:33: stderr jediProxy Error (stderr) /home/rasmus/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/completion.py:592: DeprecationWarning: Deprecated since version 0.17.0. Use the project API instead, which means Script(project=Project(dir, sys_path=sys_path)) instead.
  script = jedi.Script(

Error 2020-09-24 12:55:33: stderr jediProxy Error (stderr) /home/rasmus/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/completion.py:626: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).infer instead.
  script.goto_definitions(), request["id"]

Error 2020-09-24 12:58:07: stderr jediProxy Error (stderr) /home/rasmus/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/completion.py:592: DeprecationWarning: Providing the line is now done in the functions themselves like `Script(...).complete(line, column)`
  script = jedi.Script(
/home/rasmus/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/completion.py:592: DeprecationWarning: Providing the column is now done in the functions themselves like `Script(...).complete(line, column)`
  script = jedi.Script(

Error 2020-09-24 12:58:07: stderr jediProxy Error (stderr) /home/rasmus/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/completion.py:592: DeprecationWarning: Deprecated since version 0.17.0. Use the project API instead, which means Script(project=Project(dir, sys_path=sys_path)) instead.
  script = jedi.Script(

Error 2020-09-24 12:58:07: stderr jediProxy Error (stderr) /home/rasmus/.vscode-server-insiders/extensions/ms-python.python-2020.9.111407/pythonFiles/completion.py:626: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).infer instead.
  script.goto_definitions(), request["id"]

`

**Comment by FabiJa** [comment]
I have the same error on two machines. I have VS Code 1.51.1 on WSL2 with Win10. The only errors I could find in the logs are:
`main.js:626 GET vscode-webview-resource://0a0207ab-94fa-49a1-a55e-54d9b9549c61/file///home/…oolsai.jupyter-2020.11.399280825/out/datascience-ui/notebook/ipywidgets.js 404 (Not Found)
main.js:626 GET vscode-webview-resource://0a0207ab-94fa-49a1-a55e-54d9b9549c61/file///home/…er-2020.11.399280825/out/datascience-ui/notebook/commons.initial.bundle.js net::ERR_ABORTED 404 (Not Found)
main.js:626 GET vscode-webview-resource://0a0207ab-94fa-49a1-a55e-54d9b9549c61/file///home/…sai.jupyter-2020.11.399280825/out/datascience-ui/notebook/monaco.bundle.js net::ERR_ABORTED 404 (Not Found)
main.js:626 GET vscode-webview-resource://0a0207ab-94fa-49a1-a55e-54d9b9549c61/file///home/…lsai.jupyter-2020.11.399280825/out/datascience-ui/notebook/nativeEditor.js net::ERR_ABORTED 404 (Not Found)
5
index.html?platform=electron:1 GET vscode-webview-resource://0a0207ab-94fa-49a1-a55e-54d9b9549c61/file///home/…s-toolsai.jupyter-2020.11.399280825/out/datascience-ui/notebook/require.js net::ERR_ABORTED 404 (Not Found)`

and sometimes:
`font-awesome.min.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
require.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
ipywidgets.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
monaco.bundle.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
commons.initial.bundle.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
nativeEditor.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
require.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
ipywidgets.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
monaco.bundle.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
commons.initial.bundle.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
nativeEditor.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
font-awesome.min.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)`

**Comment by DonJayamanne** [comment]
@FabiJa Please could you update your extensions to the latest versions & let us know whether you experience the same issues.

**Comment by DonJayamanne** [comment]
Closing this issue due to inactivity.
If this issue still exists, please do get back to us or please feel free to file a new issue
