### ISSUE TITLE
Invalid JupyterHub URL specified

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#14566]
found while verifying https://github.com/microsoft/vscode-jupyter/issues/8134, but maybe specific to Windows

I got a server running in WSL.
I can connect to that jupyter hub server in the vscode window that is connected to WSL, and in the browser.
But when I try to connect from a regular Windows workspace, I get the error `Invalid JupyterHub URL specified`

<img width="462" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/2019016/74fa7c1a-ecff-4d00-a8cb-f82c92a69f58">

**Comment by DonJayamanne** [comment]
Please can you share the logs from JupyterHub extension?

**Comment by amunger** [comment]
the port is forwarded 8000-> 8000

http://localhost:8000 in a private browser opens the jupyter hub sign in page, http://localhost:8000/hub/api returns 

```
{
    "version": "4.0.2"
}
```

<details>
<summary>jupyterhub extension logs</summary>
```
14:00:43.548 [error] Error sending request to http://localhost:8000/hub/api FetchError: request to http://localhost:8000/hub/api failed, reason: connect ECONNREFUSED 127.0.0.1:8000
    > at ClientRequest.<anonymous> (c:\Users\aamunger\.vscode-insiders\extensions\ms-toolsai.jupyter-hub-2023.10.1002931100\dist\extension.node.js:63581:18)
    > type = system
    > errno = ECONNREFUSED
    > code = ECONNREFUSED
14:00:43.553 [error] Error sending request to http://localhost:8000/hub/api FetchError: request to http://localhost:8000/hub/api failed, reason: connect ECONNREFUSED 127.0.0.1:8000
    > at ClientRequest.<anonymous> (c:\Users\aamunger\.vscode-insiders\extensions\ms-toolsai.jupyter-hub-2023.10.1002931100\dist\extension.node.js:63581:18)
    > type = system
    > errno = ECONNREFUSED
    > code = ECONNREFUSED
14:00:49.044 [error] Error sending request to http://localhost:8000/hub/api FetchError: request to http://localhost:8000/hub/api failed, reason: connect ECONNREFUSED 127.0.0.1:8000
    > at ClientRequest.<anonymous> (c:\Users\aamunger\.vscode-insiders\extensions\ms-toolsai.jupyter-hub-2023.10.1002931100\dist\extension.node.js:63581:18)
    > type = system
    > errno = ECONNREFUSED
    > code = ECONNREFUSED
14:00:49.047 [error] Error sending request to http://localhost:8000/hub/api FetchError: request to http://localhost:8000/hub/api failed, reason: connect ECONNREFUSED 127.0.0.1:8000
    > at ClientRequest.<anonymous> (c:\Users\aamunger\.vscode-insiders\extensions\ms-toolsai.jupyter-hub-2023.10.1002931100\dist\extension.node.js:63581:18)
    > type = system
    > errno = ECONNREFUSED
    > code = ECONNREFUSED
14:00:49.047 [error] Failed to determine base url for http://localhost:8000/ Error: Unable to determine base url of Jupyter Hub Server
    > at getJupyterHubBaseUrl (c:\Users\aamunger\.vscode-insiders\extensions\ms-toolsai.jupyter-hub-2023.10.1002931100\dist\extension.node.js:64314:9)
14:01:10.377 [error] Error sending request to http://localhost:8000/hub/api/users/aamunger/tokens/a4 FetchError: request to http://localhost:8000/hub/api/users/aamunger/tokens/a4 failed, reason: connect ECONNREFUSED 127.0.0.1:8000
    > at ClientRequest.<anonymous> (c:\Users\aamunger\.vscode-insiders\extensions\ms-toolsai.jupyter-hub-2023.10.1002931100\dist\extension.node.js:63581:18)
    > type = system
    > errno = ECONNREFUSED
    > code = ECONNREFUSED
14:01:14.294 [error] Error sending request to http://localhost:8000/hub/api FetchError: request to http://localhost:8000/hub/api failed, reason: connect ECONNREFUSED 127.0.0.1:8000
    > at ClientRequest.<anonymous> (c:\Users\aamunger\.vscode-insiders\extensions\ms-toolsai.jupyter-hub-2023.10.1002931100\dist\extension.node.js:63581:18)
    > type = system
    > errno = ECONNREFUSED
    > code = ECONNREFUSED
14:01:14.297 [error] Error sending request to http://localhost:8000/hub/api FetchError: request to http://localhost:8000/hub/api failed, reason: connect ECONNREFUSED 127.0.0.1:8000
    > at ClientRequest.<anonymous> (c:\Users\aamunger\.vscode-insiders\extensions\ms-toolsai.jupyter-hub-2023.10.1002931100\dist\extension.node.js:63581:18)
    > type = system
    > errno = ECONNREFUSED
    > code = ECONNREFUSED
14:01:19.438 [error] Error sending request to http://localhost:8000/hub/api FetchError: request to http://localhost:8000/hub/api failed, reason: connect ECONNREFUSED 127.0.0.1:8000
    > at ClientRequest.<anonymous> (c:\Users\aamunger\.vscode-insiders\extensions\ms-toolsai.jupyter-hub-2023.10.1002931100\dist\extension.node.js:63581:18)
    > type = system
    > errno = ECONNREFUSED
    > code = ECONNREFUSED
14:01:19.441 [error] Error sending request to http://localhost:8000/hub/api FetchError: request to http://localhost:8000/hub/api failed, reason: connect ECONNREFUSED 127.0.0.1:8000
    > at ClientRequest.<anonymous> (c:\Users\aamunger\.vscode-insiders\extensions\ms-toolsai.jupyter-hub-2023.10.1002931100\dist\extension.node.js:63581:18)
    > type = system
    > errno = ECONNREFUSED
    > code = ECONNREFUSED
14:01:19.441 [error] Failed to determine base url for http://localhost:8000/ Error: Unable to determine base url of Jupyter Hub Server
    > at getJupyterHubBaseUrl (c:\Users\aamunger\.vscode-insiders\extensions\ms-toolsai.jupyter-hub-2023.10.1002931100\dist\extension.node.js:64314:9)
14:01:28.877 [error] Error sending request to http://localhost:8000/hub/api FetchError: request to http://localhost:8000/hub/api failed, reason: connect ECONNREFUSED 127.0.0.1:8000
    > at ClientRequest.<anonymous> (c:\Users\aamunger\.vscode-insiders\extensions\ms-toolsai.jupyter-hub-2023.10.1002931100\dist\extension.node.js:63581:18)
    > type = system
    > errno = ECONNREFUSED
    > code = ECONNREFUSED
14:01:28.881 [error] Error sending request to http://localhost:8000/hub/api FetchError: request to http://localhost:8000/hub/api failed, reason: connect ECONNREFUSED 127.0.0.1:8000
    > at ClientRequest.<anonymous> (c:\Users\aamunger\.vscode-insiders\extensions\ms-toolsai.jupyter-hub-2023.10.1002931100\dist\extension.node.js:63581:18)
    > type = system
    > errno = ECONNREFUSED
    > code = ECONNREFUSED
14:01:28.881 [error] Failed to determine base url for http://localhost:8000/ Error: Unable to determine base url of Jupyter Hub Server
    > at getJupyterHubBaseUrl (c:\Users\aamunger\.vscode-insiders\extensions\ms-toolsai.jupyter-hub-2023.10.1002931100\dist\extension.node.js:64314:9)
14:01:39.214 [error] Error sending request to http://localhost:8000/hub/api FetchError: request to http://localhost:8000/hub/api failed, reason: connect ECONNREFUSED 127.0.0.1:8000
    > at ClientRequest.<anonymous> (c:\Users\aamunger\.vscode-insiders\extensions\ms-toolsai.jupyter-hub-2023.10.1002931100\dist\extension.node.js:63581:18)
    > type = system
    > errno = ECONNREFUSED
    > code = ECONNREFUSED
14:01:39.216 [error] Error sending request to http://localhost:8000/hub/api FetchError: request to http://localhost:8000/hub/api failed, reason: connect ECONNREFUSED 127.0.0.1:8000
    > at ClientRequest.<anonymous> (c:\Users\aamunger\.vscode-insiders\extensions\ms-toolsai.jupyter-hub-2023.10.1002931100\dist\extension.node.js:63581:18)
    > type = system
    > errno = ECONNREFUSED
    > code = ECONNREFUSED
14:01:39.216 [error] Failed to determine base url for http://localhost:8000/ Error: Unable to determine base url of Jupyter Hub Server
    > at getJupyterHubBaseUrl (c:\Users\aamunger\.vscode-insiders\extensions\ms-toolsai.jupyter-hub-2023.10.1002931100\dist\extension.node.js:64314:9)
14:03:18.879 [error] Error sending request to http://localhost:8000/hub/api FetchError: request to http://localhost:8000/hub/api failed, reason: connect ECONNREFUSED 127.0.0.1:8000
    > at ClientRequest.<anonymous> (c:\Users\aamunger\.vscode-insiders\extensions\ms-toolsai.jupyter-hub-2023.10.1002931100\dist\extension.node.js:63581:18)
    > type = system
    > errno = ECONNREFUSED
    > code = ECONNREFUSED
14:03:18.882 [error] Error sending request to http://localhost:8000/hub/api FetchError: request to http://localhost:8000/hub/api failed, reason: connect ECONNREFUSED 127.0.0.1:8000
    > at ClientRequest.<anonymous> (c:\Users\aamunger\.vscode-insiders\extensions\ms-toolsai.jupyter-hub-2023.10.1002931100\dist\extension.node.js:63581:18)
    > type = system
    > errno = ECONNREFUSED
    > code = ECONNREFUSED
14:03:18.882 [error] Failed to determine base url for http://localhost:8000/ Error: Unable to determine base url of Jupyter Hub Server
    > at getJupyterHubBaseUrl (c:\Users\aamunger\.vscode-insiders\extensions\ms-toolsai.jupyter-hub-2023.10.1002931100\dist\extension.node.js:64314:9)
```
</details>

**Comment by gloryfromca** [comment]
same problem.
https://jupyter.internal.gllue.com/hub/api

`    
version: "1.2.2"
`


jupyterhub extension logs
`
15:07:51.818 [error] Error sending request to https://jupyter.internal.xxxx.com/hub/api FetchError: request to https://jupyter.internal.xxxx.com/hub/api failed, reason: Client network socket disconnected before secure TLS connection was established
    > at ClientRequest.<anonymous> (/home/zh/.vscode/extensions/ms-toolsai.jupyter-hub-2023.10.1003012305/dist/extension.node.js:63581:18)
    > type = system
    > errno = ECONNRESET
    > code = ECONNRESET
15:07:51.818 [error] Failed to determine base url for https://jupyter.internal.xxxx.com/user/chandler.xxxx@xxxx.com?token=e4ccdb3284a64032a532b95243fc6679 Error: Unable to determine base url of Jupyter Hub Server
    > at getJupyterHubBaseUrl (/home/zh/.vscode/extensions/ms-toolsai.jupyter-hub-2023.10.1003012305/dist/extension.node.js:64314:9)
`

**Comment by gloryfromca** [comment]
same problem.

**Comment by DonJayamanne** [comment]
@gloryfromca are you also using WSL?

**Comment by DonJayamanne** [comment]
@amunger @gloryfromca  please can you let me know if you're still running into this issue with the latest versions.
