### ISSUE TITLE
Failed to start the Kernel: Provided host 127.0.0.1 could NOT be bound. Please provide a different host address or hostname

### ISSUE THREAD

**Issue by Duckle29** [microsoft/vscode-jupyter#14678]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I tried to start a notebook that's been working fine for a year, however today no notebooks can run.

### VS Code Version

Version: 1.84.1 (user setup) Commit: 2b35e1e6d88f1ce073683991d1eff5284a32690f Date: 2023-11-06T12:35:59.022Z Electron: 25.9.2 ElectronBuildId: 24603566 Chromium: 114.0.5735.289 Node.js: 18.15.0 V8: 11.4.183.29-electron.0 OS: Windows_NT x64 10.0.19045

### Jupyter Extension Version

v2023.10.1003070148

### Jupyter logs

```shell
11:44:36.755 [info] Handle Execution of Cells 0 for ~\local_projects\Jupyter\Notebooks\T.Base.ipynb
11:44:36.756 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd0b66976817410ff70648f0320b55f494704ad45738efd372816a4e6a6c143b5dd.~\local_projects\Jupyter\.venv\Scripts\python.exe.~\local_projects\Jupyter\.venv\Scripts\python.exe.-m#ipykernel_launcher  (Python Path: ~\local_projects\Jupyter\.venv\Scripts\python.exe, Poetry, .venv, 3.11.6) for '~\local_projects\Jupyter\Notebooks\T.Base.ipynb' (disableUI=false)
11:44:36.758 [error] Kernel Launcher. launch, Class name = Fv, completed in 1ms, has a falsy return value, Arg 1: "~\\local_projects\\Jupyter\\.venv\\Scripts\\python.exe.c:\\Users\\<username>\\local_projects\\Jupyter\\.venv\\Scripts\\python.exe.-m#ipykernel_launcher", Arg 2: 60000, Arg 3: "/c:/Users/<username>/local_projects/Jupyter/Notebooks/T.Base.ipynb", Arg 4: "~\\local_projects\\Jupyter\\Notebooks", Arg 5: "" [Error: Provided host 127.0.0.1 could NOT be bound. Please provide a different host address or hostname
	at ~\.vscode\extensions\ms-toolsai.jupyter-2023.10.1003070148-win32-x64\out\351.node.js:1:3100
	at ~\.vscode\extensions\ms-toolsai.jupyter-2023.10.1003070148-win32-x64\out\351.node.js:1:7210
	at a (~\.vscode\extensions\ms-toolsai.jupyter-2023.10.1003070148-win32-x64\out\351.node.js:1:10200)
	at ~\.vscode\extensions\ms-toolsai.jupyter-2023.10.1003070148-win32-x64\out\351.node.js:1:9686
	at ~\.vscode\extensions\ms-toolsai.jupyter-2023.10.1003070148-win32-x64\out\351.node.js:1:2742
	at Server.o (~\.vscode\extensions\ms-toolsai.jupyter-2023.10.1003070148-win32-x64\out\351.node.js:1:1458)
	at Object.onceWrapper (node:events:628:26)
	at Server.emit (node:events:513:28)
	at emitErrorNT (node:net:1767:8)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)]
11:44:36.758 [error] Failed to connect raw kernel session: Error: Provided host 127.0.0.1 could NOT be bound. Please provide a different host address or hostname
11:44:36.758 [error] Failed to connect raw kernel session: Error: Provided host 127.0.0.1 could NOT be bound. Please provide a different host address or hostname
11:44:36.762 [info] Process Execution: ~\local_projects\Jupyter\.venv\Scripts\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
11:44:37.078 [warn] Error occurred while trying to start the kernel, options.disableUI=false Error: Failed to start the Kernel '.venv (Python 3.11.6)'. 
View Jupyter [log](command:jupyter.viewOutput) for further details. Provided host 127.0.0.1 could NOT be bound. Please provide a different host address or hostname
    > at new Qi (~\.vscode\extensions\ms-toolsai.jupyter-2023.10.1003070148-win32-x64\out\extension.node.js:2:2213037)
    > originalException = Error: Provided host 127.0.0.1 could NOT be bound. Please provide a different host address or hostname
11:44:37.079 [warn] Kernel Error, context = start Error: Failed to start the Kernel '.venv (Python 3.11.6)'. 
View Jupyter [log](command:jupyter.viewOutput) for further details. Provided host 127.0.0.1 could NOT be bound. Please provide a different host address or hostname
    > at new Qi (~\.vscode\extensions\ms-toolsai.jupyter-2023.10.1003070148-win32-x64\out\extension.node.js:2:2213037)
    > originalException = Error: Provided host 127.0.0.1 could NOT be bound. Please provide a different host address or hostname
11:44:37.084 [info] Process Execution: ~\local_projects\Jupyter\.venv\Scripts\python.exe -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
11:44:37.368 [info] Dispose Kernel '~\local_projects\Jupyter\Notebooks\T.Base.ipynb' associated with '~\local_projects\Jupyter\Notebooks\T.Base.ipynb'
11:44:37.369 [error] Error in execution Error: Failed to start the Kernel '.venv (Python 3.11.6)'. 
View Jupyter [log](command:jupyter.viewOutput) for further details. Provided host 127.0.0.1 could NOT be bound. Please provide a different host address or hostname
    > at new Qi (~\.vscode\extensions\ms-toolsai.jupyter-2023.10.1003070148-win32-x64\out\extension.node.js:2:2213037)
    > originalException = Error: Provided host 127.0.0.1 could NOT be bound. Please provide a different host address or hostname
11:44:37.369 [error] Error in execution (get message for cell) Error: Failed to start the Kernel '.venv (Python 3.11.6)'. 
View Jupyter [log](command:jupyter.viewOutput) for further details. Provided host 127.0.0.1 could NOT be bound. Please provide a different host address or hostname
    > at new Qi (~\.vscode\extensions\ms-toolsai.jupyter-2023.10.1003070148-win32-x64\out\extension.node.js:2:2213037)
    > originalException = Error: Provided host 127.0.0.1 could NOT be bound. Please provide a different host address or hostname
11:44:37.421 [info] End cell 0 execution @ undefined, started @ undefined, elapsed time = 0s
```

### Coding Language and Runtime Version

Python 3.11.6 (also 3.8.10 previously)

### Running Jupyter locally or remotely?

Local

**Comment by Duckle29** [comment]
This seems to be the same issue as https://github.com/microsoft/vscode-jupyter/issues/13598

**Comment by Duckle29** [comment]
After a reboot of my PC it seemed happy again. Something must've been hogging the port that jupyter wanted or something
