### ISSUE TITLE
Errors not reported correctly

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#14914]
Run the following code  in a notebook cell with IPython 8.12.0 and 8.12.1
```python
import pandas
df = pandas.DataFrame([])

# Important: only fails inside of an "exec" call:
exec("df.foobarbaz()")
```

Upstream issue https://github.com/ipython/ipython/issues/14057

Output from 8.12.0
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[3], [line 5](vscode-notebook-cell:?execution_count=3&line=5)
      [2](vscode-notebook-cell:?execution_count=3&line=2) df = pandas.DataFrame([])
      [4](vscode-notebook-cell:?execution_count=3&line=4) # Important: only fails inside of an "exec" call:
----> [5](vscode-notebook-cell:?execution_count=3&line=5) exec("df.foobarbaz()")

File <string>:1

File [~/demo/.venv/lib/python3.11/site-packages/pandas/core/generic.py:6204](https://file+.vscode-resource.vscode-cdn.net/Users/donjayamanne/demo/outputs_/~/demo/.venv/lib/python3.11/site-packages/pandas/core/generic.py:6204), in NDFrame.__getattr__(self, name)
   [6197](https://file+.vscode-resource.vscode-cdn.net/Users/donjayamanne/demo/outputs_/~/demo/.venv/lib/python3.11/site-packages/pandas/core/generic.py:6197) if (
   [6198](https://file+.vscode-resource.vscode-cdn.net/Users/donjayamanne/demo/outputs_/~/demo/.venv/lib/python3.11/site-packages/pandas/core/generic.py:6198)     name not in self._internal_names_set
   [6199](https://file+.vscode-resource.vscode-cdn.net/Users/donjayamanne/demo/outputs_/~/demo/.venv/lib/python3.11/site-packages/pandas/core/generic.py:6199)     and name not in self._metadata
   [6200](https://file+.vscode-resource.vscode-cdn.net/Users/donjayamanne/demo/outputs_/~/demo/.venv/lib/python3.11/site-packages/pandas/core/generic.py:6200)     and name not in self._accessors
   [6201](https://file+.vscode-resource.vscode-cdn.net/Users/donjayamanne/demo/outputs_/~/demo/.venv/lib/python3.11/site-packages/pandas/core/generic.py:6201)     and self._info_axis._can_hold_identifiers_and_holds_name(name)
   [6202](https://file+.vscode-resource.vscode-cdn.net/Users/donjayamanne/demo/outputs_/~/demo/.venv/lib/python3.11/site-packages/pandas/core/generic.py:6202) ):
   [6203](https://file+.vscode-resource.vscode-cdn.net/Users/donjayamanne/demo/outputs_/~/demo/.venv/lib/python3.11/site-packages/pandas/core/generic.py:6203)     return self[name]
-> [6204](https://file+.vscode-resource.vscode-cdn.net/Users/donjayamanne/demo/outputs_/~/demo/.venv/lib/python3.11/site-packages/pandas/core/generic.py:6204) return object.__getattribute__(self, name)

AttributeError: 'DataFrame' object has no attribute 'foobarbaz'
```

Output from 8.12.1
```
Unexpected exception formatting exception. Falling back to standard exception
Traceback (most recent call last):
  File "/Users/donjayamanne/demo/.venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/fv/524cyb9j03s16612v0f52g4h0000gn/T/ipykernel_55543/6910153.py", line 5, in <module>
    exec("df.foobarbaz()")
  File "<string>", line 1, in <module>
  File "/Users/donjayamanne/demo/.venv/lib/python3.11/site-packages/pandas/core/generic.py", line 6204, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'foobarbaz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/donjayamanne/demo/.venv/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 2105, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/donjayamanne/demo/.venv/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1396, in structured_traceback
    return FormattedTB.structured_traceback(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/donjayamanne/demo/.venv/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1287, in structured_traceback
    return VerboseTB.structured_traceback(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/donjayamanne/demo/.venv/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1140, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/donjayamanne/demo/.venv/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1030, in format_exception_as_a_whole
    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/donjayamanne/demo/.venv/lib/python3.11/site-packages/IPython/core/ultratb.py", line 1122, in get_records
    FrameInfo(
  File "/Users/donjayamanne/demo/.venv/lib/python3.11/site-packages/IPython/core/ultratb.py", line 766, in __init__
    ix = inspect.getsourcelines(frame)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/donjayamanne/.pyenv/versions/3.11.5/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/inspect.py", line 1244, in getsourcelines
    lines, lnum = findsource(object)
                  ^^^^^^^^^^^^^^^^^^
  File "/Users/donjayamanne/.pyenv/versions/3.11.5/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/inspect.py", line 1081, in findsource
    raise OSError('could not get source code')
OSError: could not get source code
```

**Comment by DonJayamanne** [comment]
If we try to extract the error message from the `execute_reply` message, the traceback is not available.
The right way is what we're doing today, there's no work around to getting this working without fixing the issue in ipython itself.

@kycutler @pawang_microsoft
My suggestion is for you to wrap your code in try catch blocks and print the formatted error youselves if you just need a pretty error message.
