### ISSUE TITLE
Unable to connect to the remote server (Azure Ml compute instance)

### ISSUE THREAD

**Issue by kbokh** [microsoft/vscode-jupyter#14925]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

- Open a notebook
- Select kernel
- Azure ML compute instance
- [compute instance name]
- Message:  "Unable to connect to the remote server"

### VS Code Version

1.85.1

### Jupyter Extension Version

1.0.17

### Jupyter logs

```
Visual Studio Code (1.85.1, undefined, desktop)
Jupyter Extension Version: 2023.11.1003402403.
Python Extension Version: 2023.22.1.
Pylance Extension Version: 2023.12.100.
Platform: linux (x64).
Workspace folder *********/intrackai-mlpipelines, Home = /home/******
15:10:12.396 [info] Telemetry is disabled
15:10:12.396 [info] Experiments are disabled, only manually opted experiments are active.
15:10:12.396 [info] User belongs to experiment group 'KernelCompletions'
15:10:12.795 [debug] Get Custom Env Variables, Class name = _m (started execution), Arg 1: undefined, Arg 2: "RunPythonCode"
15:10:12.795 [info] Start refreshing Kernel Picker (1702905012795)
15:10:12.824 [info] Using Pylance
15:10:13.746 [debug] creating new code watcher with matching document file:///************.py
15:10:13.917 [debug] Get Custom Env Variables, Class name = _m, completed in 1122ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
15:10:13.917 [debug] Jupyter Paths /kernels: 
15:10:13.917 [debug] Kernel Spec Root Paths, /usr/share/jupyter/kernels, /usr/local/share/jupyter/kernels, ~/.local/share/jupyter/kernels
15:10:14.055 [debug] Search for KernelSpecs in Interpreter ~/.conda/envs/hu_detector_yolo_pipeline/bin/python
15:10:14.055 [debug] Finding Global Python KernelSpecs
15:10:14.058 [debug] Search for KernelSpecs in Interpreter /bin/python
15:10:14.059 [debug] Search for KernelSpecs in Interpreter /sbin/python
15:10:14.059 [debug] Search for KernelSpecs in Interpreter /usr/bin/python
15:10:14.059 [debug] Search for KernelSpecs in Interpreter /usr/sbin/python
15:10:14.060 [debug] Search for KernelSpecs in Interpreter ~/.pyenv/versions/3.11.7/bin/python
15:10:14.060 [debug] Search for KernelSpecs in Interpreter ~/.pyenv/versions/3.11.4/bin/python
15:10:14.061 [debug] Search for KernelSpecs in Interpreter ~/.pyenv/versions/3.11.5/bin/python
15:10:14.062 [debug] Search for KernelSpecs in Interpreter ~/.pyenv/versions/3.9.16/bin/python
15:10:14.063 [debug] Search for KernelSpecs in Interpreter ~/.pyenv/versions/3.9.17/bin/python
15:10:14.063 [debug] Search for KernelSpecs in Interpreter ~/.conda/envs/json2yolo/bin/python
15:10:14.064 [debug] Search for KernelSpecs in Interpreter ~/.conda/envs/yolov8-rknn/bin/python
15:10:14.065 [debug] Search for KernelSpecs in Interpreter ~/.conda/envs/yolov8-rknn-38/bin/python
15:10:14.065 [debug] Search for KernelSpecs in Interpreter /opt/miniconda3/bin/python
15:10:14.068 [debug] Full interpreter list is length: 14, /bin/python::Unknown:/bin/python, /sbin/python::Unknown:/sbin/python, /usr/bin/python::Unknown:/usr/bin/python, /usr/sbin/python::Unknown:/usr/sbin/python, ~/.pyenv/versions/3.11.7/bin/python::Pyenv:~/.pyenv/versions/3.11.7/bin/python, ~/.pyenv/versions/3.11.4/bin/python::Pyenv:~/.pyenv/versions/3.11.4/bin/python, ~/.pyenv/versions/3.11.5/bin/python::Pyenv:~/.pyenv/versions/3.11.5/bin/python, ~/.conda/envs/hu_detector_yolo_pipeline/bin/python:hu_detector_yolo_pipeline:Conda:~/.conda/envs/hu_detector_yolo_pipeline/bin/python, ~/.pyenv/versions/3.9.16/bin/python::Pyenv:~/.pyenv/versions/3.9.16/bin/python, ~/.pyenv/versions/3.9.17/bin/python::Pyenv:~/.pyenv/versions/3.9.17/bin/python, ~/.conda/envs/json2yolo/bin/python:json2yolo:Conda:~/.conda/envs/json2yolo/bin/python, ~/.conda/envs/yolov8-rknn/bin/python:yolov8-rknn:Conda:~/.conda/envs/yolov8-rknn/bin/python, ~/.conda/envs/yolov8-rknn-38/bin/python:yolov8-rknn-38:Conda:~/.conda/envs/yolov8-rknn-38/bin/python, /opt/miniconda3/bin/python:base:Conda:/opt/miniconda3/bin/python
15:10:14.071 [debug] Getting activated env variables, Class name = Ip (started execution), Arg 1: "/home/DATA/Projects/bosch/repositories/intrackai-mlpipelines", Arg 2: "~/.conda/envs/hu_detector_yolo_pipeline/bin/python", Arg 3: undefined
15:10:14.071 [debug] Get Custom Env Variables, Class name = _m (started execution), Arg 1: "/home/DATA/Projects/bosch/repositories/intrackai-mlpipelines", Arg 2: "RunPythonCode"
15:10:14.072 [debug] Get Custom Env Variables, Class name = _m, completed in 1ms, has a truthy return value, Arg 1: "/home/DATA/Projects/bosch/repositories/intrackai-mlpipelines", Arg 2: "RunPythonCode"
15:10:14.932 [debug] Kernels for interpreter /bin/python are .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher
15:10:14.932 [debug] Kernels for interpreter /sbin/python are .jvsc74a57bd0d2152fd7f0bbc62aa1baff8c990435d1e2c7175d001561303988032604c11a48./sbin/python./sbin/python.-m#ipykernel_launcher
15:10:14.933 [debug] Kernels for interpreter /usr/bin/python are .jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher
15:10:14.933 [debug] Kernels for interpreter /usr/sbin/python are .jvsc74a57bd04e1d9a8909477db77738c33245c29c7265277ef753467dede8cf3f814cde494e./usr/sbin/python./usr/sbin/python.-m#ipykernel_launcher
15:10:14.933 [debug] Kernels for interpreter ~/.pyenv/versions/3.11.4/bin/python are .jvsc74a57bd0402f9b616585feb8f90ec5ebb31b9b2a27c8dee33948888051769d706912825c.~/.pyenv/versions/3.11.4/python.~/.pyenv/versions/3.11.4/python.-m#ipykernel_launcher
15:10:14.934 [debug] Kernels for interpreter ~/.pyenv/versions/3.11.5/bin/python are .jvsc74a57bd01dc7ad663f5f86dc054c4387b7220c20c8dca708c54f863cec01a78695e5223b.~/.pyenv/versions/3.11.5/python.~/.pyenv/versions/3.11.5/python.-m#ipykernel_launcher
15:10:14.934 [debug] Kernels for interpreter ~/.pyenv/versions/3.9.16/bin/python are .jvsc74a57bd0d34c42009812b3d81dbc267f5d50f42df8f3191f74056bf17a9f768a7fcd4ca5.~/.pyenv/versions/3.9.16/python.~/.pyenv/versions/3.9.16/python.-m#ipykernel_launcher
15:10:14.935 [debug] Kernels for interpreter ~/.pyenv/versions/3.9.17/bin/python are .jvsc74a57bd0f08045e8eaa392ff6a23f69b51aded312ecebc68095f745a1532af570c785efc.~/.pyenv/versions/3.9.17/python.~/.pyenv/versions/3.9.17/python.-m#ipykernel_launcher
15:10:14.935 [debug] Kernels for interpreter ~/.conda/envs/json2yolo/bin/python are .jvsc74a57bd005b59298713a90a73d10c126e67d7c2507ef179460729b93db55a50f18a98411.~/.conda/envs/json2yolo/python.~/.conda/envs/json2yolo/python.-m#ipykernel_launcher
15:10:14.935 [debug] Kernels for interpreter ~/.conda/envs/yolov8-rknn/bin/python are .jvsc74a57bd0314a5b4f3d0e39e952ccb727d73bff297d27384b8d77d3083fd73796b1ba212f.~/.conda/envs/yolov8-rknn/python.~/.conda/envs/yolov8-rknn/python.-m#ipykernel_launcher
15:10:14.935 [debug] Kernels for interpreter ~/.conda/envs/yolov8-rknn-38/bin/python are .jvsc74a57bd03c50692cc43a9530108b5ac16f83e99e52a4952ca0e8fcb898f9d22121538465.~/.conda/envs/yolov8-rknn-38/python.~/.conda/envs/yolov8-rknn-38/python.-m#ipykernel_launcher
15:10:14.936 [debug] Kernels for interpreter /opt/miniconda3/bin/python are .jvsc74a57bd03d597f4c481aa0f25dceb95d2a0067e73c0966dcbd003d741d821a7208527ecf./opt/miniconda3/python./opt/miniconda3/python.-m#ipykernel_launcher
15:10:15.043 [error] The API registerRemoteServerProvider has being deprecated and will be removed soon, please use createJupyterServerCollection.
15:10:15.085 [debug] Error in detecting whether url is isJupyterHub: FetchError: request to http://cvat.sylon.cloud:8888/hub/api failed, reason: connect EHOSTUNREACH 192.168.1.15:8888
15:10:15.087 [debug] Error in detecting whether url is isJupyterHub: FetchError: request to http://cvat.sylon.cloud:8888/hub/api failed, reason: connect EHOSTUNREACH 192.168.1.15:8888
15:10:15.151 [debug] Loading kernelspec from ~/.conda/envs/hu_detector_yolo_pipeline/share/jupyter/kernels/python3/kernel.json for ~/.conda/envs/hu_detector_yolo_pipeline/bin/python
15:10:15.152 [debug] Loading kernelspec from ~/.pyenv/versions/3.11.7/share/jupyter/kernels/python3/kernel.json for ~/.pyenv/versions/3.11.7/bin/python
15:10:15.161 [error] Failed to validate Password info [D [FetchError]: request to http://cvat.sylon.cloud:8888/tree? failed, reason: connect EHOSTUNREACH 192.168.1.15:8888
	at ClientRequest.<anonymous> (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1003402403-linux-x64/dist/node_modules/node-fetch.js:1:306479)
	at ClientRequest.emit (node:events:525:35)
	at ClientRequest.emit (node:domain:489:12)
	at Socket.socketErrorListener (node:_http_client:502:9)
	at Socket.emit (node:events:513:28)
	at Socket.emit (node:domain:489:12)
	at emitErrorNT (node:internal/streams/destroy:151:8)
	at emitErrorCloseNT (node:internal/streams/destroy:116:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)] {
  type: 'system',
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH'
}
15:10:15.196 [error] Failed to validate Password info [D [FetchError]: request to http://cvat.sylon.cloud:8888/tree? failed, reason: connect EHOSTUNREACH 192.168.1.15:8888
	at ClientRequest.<anonymous> (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1003402403-linux-x64/dist/node_modules/node-fetch.js:1:306479)
	at ClientRequest.emit (node:events:525:35)
	at ClientRequest.emit (node:domain:489:12)
	at Socket.socketErrorListener (node:_http_client:502:9)
	at Socket.emit (node:events:513:28)
	at Socket.emit (node:domain:489:12)
	at emitErrorNT (node:internal/streams/destroy:151:8)
	at emitErrorCloseNT (node:internal/streams/destroy:116:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)] {
  type: 'system',
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH'
}
15:10:15.325 [error] Error fetching kernels from http://cvat.sylon.cloud:8888/ (cvat.sylon.cloud): [FetchError: request to http://cvat.sylon.cloud:8888/api/kernels?1702905015194 failed, reason: connect EHOSTUNREACH 192.168.1.15:8888
	at ClientRequest.<anonymous> (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1003402403-linux-x64/dist/node_modules/node-fetch.js:1:306479)
	at ClientRequest.emit (node:events:525:35)
	at ClientRequest.emit (node:domain:489:12)
	at Socket.socketErrorListener (node:_http_client:502:9)
	at Socket.emit (node:events:513:28)
	at Socket.emit (node:domain:489:12)
	at emitErrorNT (node:internal/streams/destroy:151:8)
	at emitErrorCloseNT (node:internal/streams/destroy:116:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)]
15:10:15.325 [debug] Disposing Jupyter Lab Helper
15:10:15.325 [debug] SessionManager - dispose contents manager
15:10:15.325 [debug] ShutdownSessionAndConnection - dispose session manager
15:10:15.919 [debug] Kernel Specs found in interpreter ~/.conda/envs/hu_detector_yolo_pipeline/bin/python are [{"specFile":"~/.conda/envs/hu_detector_yolo_pipeline/share/jupyter/kernels/python3/kernel.json","interpreterPath":"~/.conda/envs/hu_detector_yolo_pipeline/bin/python","isRegisteredByVSC":"registeredByNewVersionOfExt","name":"pythonjvsc74a57bd0b41d971347ac7a0dbffae1d8334ad1192a19401e38f7b483c03ca650c340f428","argv":["python","-m","ipykernel_launcher","-f","{connection_file}"],"language":"python","executable":"python","display_name":"Python 3 (ipykernel)","metadata":{"debugger":true,"vscode":{"originalSpecFile":"~/.conda/envs/hu_detector_yolo_pipeline/share/jupyter/kernels/python3/kernel.json","originalDisplayName":"Python 3 (ipykernel)"}}}]
15:10:15.920 [debug] Hiding default kernel spec 'Python 3 (ipykernel)', 'pythonjvsc74a57bd0b41d971347ac7a0dbffae1d8334ad1192a19401e38f7b483c03ca650c340f428', /python for interpreter ~/.conda/envs/hu_detector_yolo_pipeline/bin/python and spec ~/.conda/envs/hu_detector_yolo_pipeline/share/jupyter/kernels/python3/kernel.json
15:10:15.920 [debug] Kernels for interpreter ~/.conda/envs/hu_detector_yolo_pipeline/bin/python are .jvsc74a57bd0b41d971347ac7a0dbffae1d8334ad1192a19401e38f7b483c03ca650c340f428.~/.conda/envs/hu_detector_yolo_pipeline/python.~/.conda/envs/hu_detector_yolo_pipeline/python.-m#ipykernel_launcher
15:10:15.920 [debug] Kernel Specs found in interpreter ~/.pyenv/versions/3.11.7/bin/python are [{"specFile":"~/.pyenv/versions/3.11.7/share/jupyter/kernels/python3/kernel.json","interpreterPath":"~/.pyenv/versions/3.11.7/bin/python","isRegisteredByVSC":"registeredByNewVersionOfExt","name":"pythonjvsc74a57bd0159d64c10af258c22a9c8a79ecdc41c23434fd60f4f448e75c66a1c3226f6eba","argv":["python","-m","ipykernel_launcher","-f","{connection_file}"],"language":"python","executable":"python","display_name":"Python 3 (ipykernel)","metadata":{"debugger":true,"vscode":{"originalSpecFile":"~/.pyenv/versions/3.11.7/share/jupyter/kernels/python3/kernel.json","originalDisplayName":"Python 3 (ipykernel)"}}}]
15:10:15.921 [debug] Hiding default kernel spec 'Python 3 (ipykernel)', 'pythonjvsc74a57bd0159d64c10af258c22a9c8a79ecdc41c23434fd60f4f448e75c66a1c3226f6eba', /python for interpreter ~/.pyenv/versions/3.11.7/bin/python and spec ~/.pyenv/versions/3.11.7/share/jupyter/kernels/python3/kernel.json
15:10:15.921 [debug] Kernels for interpreter ~/.pyenv/versions/3.11.7/bin/python are .jvsc74a57bd0159d64c10af258c22a9c8a79ecdc41c23434fd60f4f448e75c66a1c3226f6eba.~/.pyenv/versions/3.11.7/python.~/.pyenv/versions/3.11.7/python.-m#ipykernel_launcher
15:10:19.357 [error] Error fetching kernels from http://cvat.sylon.cloud:8888/ (cvat.sylon.cloud): [FetchError: request to http://cvat.sylon.cloud:8888/api/kernels?1702905015197 failed, reason: connect EHOSTUNREACH 192.168.1.15:8888
	at ClientRequest.<anonymous> (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1003402403-linux-x64/dist/node_modules/node-fetch.js:1:306479)
	at ClientRequest.emit (node:events:525:35)
	at ClientRequest.emit (node:domain:489:12)
	at Socket.socketErrorListener (node:_http_client:502:9)
	at Socket.emit (node:events:513:28)
	at Socket.emit (node:domain:489:12)
	at emitErrorNT (node:internal/streams/destroy:151:8)
	at emitErrorCloseNT (node:internal/streams/destroy:116:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)]
15:10:19.357 [debug] Disposing Jupyter Lab Helper
15:10:19.357 [debug] SessionManager - dispose contents manager
15:10:19.357 [debug] ShutdownSessionAndConnection - dispose session manager
15:10:19.358 [debug] Finished disposing Jupyter Lab Helper
15:10:19.358 [error] Jupyter Lab Helper:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at v.dispose (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1003402403-linux-x64/dist/node_modules/@jupyterlab/services.js:11:10935)
	at ni.dispose (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1003402403-linux-x64/dist/node_modules/@jupyterlab/services.js:11:29299)
	at r.dispose (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1003402403-linux-x64/dist/extension.node.js:138:4517)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Promise.all (index 0)
	at async rT.listKernelsFromConnection (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1003402403-linux-x64/dist/extension.node.js:235:22644)
	at async ~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1003402403-linux-x64/dist/extension.node.js:235:20130]
15:10:19.358 [error] UniversalRemoteKernelFinder: Failed to get kernels without cache [FetchError: request to http://cvat.sylon.cloud:8888/api/kernels?1702905015197 failed, reason: connect EHOSTUNREACH 192.168.1.15:8888
	at ClientRequest.<anonymous> (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1003402403-linux-x64/dist/node_modules/node-fetch.js:1:306479)
	at ClientRequest.emit (node:events:525:35)
	at ClientRequest.emit (node:domain:489:12)
	at Socket.socketErrorListener (node:_http_client:502:9)
	at Socket.emit (node:events:513:28)
	at Socket.emit (node:domain:489:12)
	at emitErrorNT (node:internal/streams/destroy:151:8)
	at emitErrorCloseNT (node:internal/streams/destroy:116:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)]
15:10:19.358 [debug] UniversalRemoteKernelFinder: Writing 0 remote kernel connection metadata to cache
15:10:21.778 [debug] Conda file returned by Python Extension is /opt/miniconda3/bin/conda
15:10:22.555 [debug] Finished disposing Jupyter Lab Helper
15:10:22.556 [error] UniversalRemoteKernelFinder: Failed to get kernels without cache [FetchError: request to http://cvat.sylon.cloud:8888/api/kernels?1702905015194 failed, reason: connect EHOSTUNREACH 192.168.1.15:8888
	at ClientRequest.<anonymous> (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1003402403-linux-x64/dist/node_modules/node-fetch.js:1:306479)
	at ClientRequest.emit (node:events:525:35)
	at ClientRequest.emit (node:domain:489:12)
	at Socket.socketErrorListener (node:_http_client:502:9)
	at Socket.emit (node:events:513:28)
	at Socket.emit (node:domain:489:12)
	at emitErrorNT (node:internal/streams/destroy:151:8)
	at emitErrorCloseNT (node:internal/streams/destroy:116:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)]
15:10:22.556 [debug] UniversalRemoteKernelFinder: Writing 0 remote kernel connection metadata to cache
15:10:22.556 [error] Jupyter Lab Helper:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at v.dispose (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1003402403-linux-x64/dist/node_modules/@jupyterlab/services.js:11:10935)
	at ni.dispose (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1003402403-linux-x64/dist/node_modules/@jupyterlab/services.js:11:29299)
	at r.dispose (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1003402403-linux-x64/dist/extension.node.js:138:4517)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Promise.all (index 0)
	at async rT.listKernelsFromConnection (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1003402403-linux-x64/dist/extension.node.js:235:22644)
	at async ~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1003402403-linux-x64/dist/extension.node.js:235:20130]
15:10:24.780 [info] End refreshing Kernel Picker (1702905012795)
15:10:34.227 [debug] Got env vars with python ~/.conda/envs/hu_detector_yolo_pipeline/bin/python, with env var count 95 in 20156ms. 
    PATH value is ~/.conda/envs/hu_detector_yolo_pipeline/bin:/opt/miniconda3/condabin:/opt/google-cloud-cli/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_systems/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin:~/.local/share/JetBrains/Toolbox/scripts and 
    Path value is undefined
15:10:34.227 [debug] Prepend PATH with python bin for ~/.conda/envs/hu_detector_yolo_pipeline/bin/python
15:10:34.227 [debug] Activated Env Variables for ~/.conda/envs/hu_detector_yolo_pipeline/bin/python, 
    PATH value is ~/.conda/envs/hu_detector_yolo_pipeline/bin:/opt/miniconda3/condabin:/opt/google-cloud-cli/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_systems/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/var/lib/snapd/snap/bin:~/.local/share/JetBrains/Toolbox/scripts and 
    Path value is undefined
15:10:34.227 [debug] Getting activated env variables, Class name = Ip, completed in 20156ms, has a truthy return value, Arg 1: "/home/DATA/Projects/bosch/repositories/intrackai-mlpipelines", Arg 2: "~/.conda/envs/hu_detector_yolo_pipeline/bin/python", Arg 3: undefined
15:10:34.268 [info] Process Execution: ~/.conda/envs/hu_detector_yolo_pipeline/bin/python -m pip list
15:10:54.929 [info] Start refreshing Interpreter Kernel Picker
15:10:54.930 [info] Start refreshing Kernel Picker (1702905054930)
15:10:55.000 [debug] Preferred Remote kernel for /home/DATA/Projects/bosch/repositories/intrackai-mlpipelines/pipelines/hu_detector_pipeline/hu_detector_yolo_pipeline/hu_detector_yolo_pipeline.ipynb is undefined
15:10:55.025 [warn] No interpreter for Pylance for Notebook URI "/home/DATA/Projects/bosch/repositories/intrackai-mlpipelines/pipelines/hu_detector_pipeline/hu_detector_yolo_pipeline/hu_detector_yolo_pipeline.ipynb"
15:10:55.030 [debug] No controller, hence notebook communications cannot be initialized for editor /home/DATA/Projects/bosch/repositories/intrackai-mlpipelines/pipelines/hu_detector_pipeline/hu_detector_yolo_pipeline/hu_detector_yolo_pipeline.ipynb
15:11:02.056 [debug] Full interpreter list is length: 14, /bin/python::Unknown:/bin/python, /sbin/python::Unknown:/sbin/python, /usr/bin/python::Unknown:/usr/bin/python, /usr/sbin/python::Unknown:/usr/sbin/python, ~/.pyenv/versions/3.11.7/bin/python::Pyenv:~/.pyenv/versions/3.11.7/bin/python, ~/.pyenv/versions/3.11.4/bin/python::Pyenv:~/.pyenv/versions/3.11.4/bin/python, ~/.pyenv/versions/3.11.5/bin/python::Pyenv:~/.pyenv/versions/3.11.5/bin/python, ~/.conda/envs/hu_detector_yolo_pipeline/bin/python:hu_detector_yolo_pipeline:Conda:~/.conda/envs/hu_detector_yolo_pipeline/bin/python, ~/.pyenv/versions/3.9.16/bin/python::Pyenv:~/.pyenv/versions/3.9.16/bin/python, ~/.pyenv/versions/3.9.17/bin/python::Pyenv:~/.pyenv/versions/3.9.17/bin/python, ~/.conda/envs/json2yolo/bin/python:json2yolo:Conda:~/.conda/envs/json2yolo/bin/python, ~/.conda/envs/yolov8-rknn/bin/python:yolov8-rknn:Conda:~/.conda/envs/yolov8-rknn/bin/python, ~/.conda/envs/yolov8-rknn-38/bin/python:yolov8-rknn-38:Conda:~/.conda/envs/yolov8-rknn-38/bin/python, /opt/miniconda3/bin/python:base:Conda:/opt/miniconda3/bin/python
15:11:02.056 [debug] Refreshed Environments
15:11:03.057 [info] End refreshing Kernel Picker (1702905054930)
15:13:27.596 [error] Error in validating the Remote Uri azureml_compute_instances./subscriptions/ae5bb58f-e820-4cdd-9e25-dfe765a6edbe/resourceGroups/intrack-dev-ai/providers/Microsoft.MachineLearningServices/workspaces/IntrackDevAIv2/computes/bko4fe4 [Error: Unable to get resolved server information for ms-toolsai.vscode-ai:azureml_compute_instances:/subscriptions/ae5bb58f-e820-4cdd-9e25-dfe765a6edbe/resourceGroups/intrack-dev-ai/providers/Microsoft.MachineLearningServices/workspaces/IntrackDevAIv2/computes/bko4fe4
	at Dn.validateRemoteUri (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1003402403-linux-x64/dist/extension.node.js:138:8486)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Jo.addJupyterServer (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1003402403-linux-x64/dist/extension.node.js:138:10211)
	at async ~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1003402403-linux-x64/dist/extension.node.js:265:125188]
15:13:27.598 [info] Start refreshing Kernel Picker (1702905207598)
15:13:27.603 [debug] Preferred Remote kernel for /home/DATA/Projects/bosch/repositories/intrackai-mlpipelines/pipelines/hu_detector_pipeline/hu_detector_yolo_pipeline/hu_detector_yolo_pipeline.ipynb is undefined
15:13:27.688 [error] UniversalRemoteKernelFinder: Failed to get kernels without cache [Error: Unable to get resolved server information for ms-toolsai.vscode-ai:azureml_compute_instances:/subscriptions/ae5bb58f-e820-4cdd-9e25-dfe765a6edbe/resourceGroups/intrack-dev-ai/providers/Microsoft.MachineLearningServices/workspaces/IntrackDevAIv2/computes/bko4fe4
	at Dn.createConnectionInfo (~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1003402403-linux-x64/dist/extension.node.js:138:7497)
	at async ~/.vscode/extensions/ms-toolsai.jupyter-2023.11.1003402403-linux-x64/dist/extension.node.js:235:20130]
15:13:27.689 [debug] UniversalRemoteKernelFinder: Writing 0 remote kernel connection metadata to cache
15:13:27.745 [info] End refreshing Kernel Picker (1702905207598)
15:13:42.977 [debug] Preferred Remote kernel for /home/DATA/Projects/bosch/repositories/intrackai-mlpipelines/pipelines/hu_detector_pipeline/hu_detector_yolo_pipeline/hu_detector_yolo_pipeline.ipynb is undefined
15:14:40.197 [debug] Preferred Remote kernel for /home/DATA/Projects/bosch/repositories/intrackai-mlpipelines/pipelines/hu_detector_pipeline/hu_detector_yolo_pipeline/hu_detector_yolo_pipeline.ipynb is undefined
```

### Running Jupyter locally or remotely?

Remote

**Comment by kbokh** [comment]
@shsuman

**Comment by kbokh** [comment]
macbook - the same

**Comment by DonJayamanne** [comment]
@sevillal @shsuman should this issue be transferred to the AzML extension repo?

**Comment by shsuman** [comment]
@DonJayamanne Actually, I wanted your insights on Jupyter logs as I cannot see any error in the Azure ML logs.

Do you see anything that might help us in isolating the error ?

**Comment by PaulJulitz** [comment]
I have the same error
![image](https://github.com/microsoft/vscode-jupyter/assets/55134692/a4e677f4-1762-492b-95e6-309d94024291)

**Comment by DonJayamanne** [comment]
@shsuman @sevillal 
Please can you find the name of the setting that enables the use of the new Jupyter Server API.
I believe that will be a good work around.

Temporary Solutions:
* Install VS Code Insiders and the stable version of the Jupyter extension
* Enable the hidden setting in AzML extension that makes use of the new Jupyter Server API in Jupyter extension

**Comment by DonJayamanne** [comment]
@PaulJulitz @kbokh 
I'm sorry you are running into this issue.
For the moment I would suggest reverting the Jupyter extension back to version 2023.10.*

**Comment by shsuman** [comment]
@DonJayamanne  This is the hidden setting:

`azureML.useNewJupyterApi`

**Comment by shsuman** [comment]
@DonJayamanne I am not able to repro this issue with Jupyter extension v2023.11.1003402403 and Azure ML extension v0.42.0

**Comment by PaulJulitz** [comment]
> @PaulJulitz @kbokh I'm sorry you are running into this issue. For the moment I would suggest reverting the Jupyter extension back to version 2023.10.*

@DonJayamanne Thank you. 
The rollback for the Jupyter extension worked. 
![image](https://github.com/microsoft/vscode-jupyter/assets/55134692/5aa03862-06ab-482a-afd1-10b39221ca7b)

**Comment by PaulJulitz** [comment]
> @PaulJulitz @kbokh I'm sorry you are running into this issue. For the moment I would suggest reverting the Jupyter extension back to version 2023.10.*

@DonJayamanne Thank you
The rollback for the Jupyter extension worked.
![image](https://github.com/microsoft/vscode-jupyter/assets/55134692/49c1c7fb-580b-4a26-851d-22e15e11bf09)
![image](https://github.com/microsoft/vscode-jupyter/assets/55134692/ac23b0d4-4e27-4999-93d0-bb83df3f0840)

**Comment by DonJayamanne** [comment]
Given this issue is very old, and the API has been stable for a while, I'm closing this issue for now.
If this problem still persists, please do feel free to ping here or create a new issue and we will look into this.
