### ISSUE TITLE
Cannot start new kernel with the message "Waiting for Jupyter Session to be idle"

### ISSUE THREAD

**Issue by atbug** [microsoft/vscode-jupyter#15143]
## Environment data

-   VS Code version: 1.86.0 (Universal)
-   Jupyter Extension version (available under the Extensions sidebar): 2024.1.0
-   Python Extension version (available under the Extensions sidebar): 2024..00
-   OS (Windows | Mac | Linux distro) and version: Mac (Arm)
-   Python and/or Anaconda version: Python 3.9.18
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Remote

## Expected behaviour

On a cluster, I run a jupyter server on a computing node and try to connect to the server with vscode notebook. I expect it to connect to the server and start a new session.

I use remote - tunnels extension to connect to the cluster login node.

I can connect to the server and start a new jupyter lab session with my browser.

## Actual behaviour

The session is stuck at "Waiting for Jupyter Session to be idle"

## Logs

<details>

Jupyter extension log

```
11:18:21.063 [info] Start refreshing Kernel Picker (1707247101063)
11:18:21.112 [info] End refreshing Kernel Picker (1707247101063)
11:18:22.648 [info] Dispose Kernel '~/WORKS/tTMD_TB/simulations/utilities/playground.ipynb' associated with '~/WORKS/tTMD_TB/simulations/utilities/playground.ipynb'
11:18:24.648 [info] Start refreshing Kernel Picker (1707247104648)
11:18:24.676 [info] End refreshing Kernel Picker (1707247104648)
11:18:29.960 [info] Handle Execution of Cells 2 for ~/WORKS/tTMD_TB/simulations/utilities/playground.ipynb
11:18:29.961 [info] Starting Kernel startUsingRemoteKernelSpec, dde01a5ee1235ff381acf210fe6585a582d38faeac656dfa05f0f07e70f11edf..julia-1.10./mmfs1/gscratch/cmt/wangc/.julia/juliaup/julia-1.10.0+0.x64.linux.gnu/bin/julia././mmfs1/gscratch/cmt/wangc/.julia/juliaup/julia-1.10.0+0.x64.linux.gnu/bin/julia#-i#--color=yes#--project=@.#~/.julia/packages/ijulia/vo51o/src/kernel.jl#{connection_file}  for '~/WORKS/tTMD_TB/simulations/utilities/playground.ipynb' (disableUI=false)
11:18:30.042 [info] http://n3411:19333/: Kernel started: 7bd04d71-8449-4f39-bad5-f9a0fc4b86ac
11:19:30.043 [error] Shutting down after failing to wait for idle on (kernel): 7bd04d71-8449-4f39-bad5-f9a0fc4b86ac -> unknown
11:19:30.043 [info] Started session for kernel startUsingRemoteKernelSpec:dde01a5ee1235ff381acf210fe6585a582d38faeac656dfa05f0f07e70f11edf..julia-1.10./mmfs1/gscratch/cmt/wangc/.julia/juliaup/julia-1.10.0+0.x64.linux.gnu/bin/julia././mmfs1/gscratch/cmt/wangc/.julia/juliaup/julia-1.10.0+0.x64.linux.gnu/bin/julia#-i#--color=yes#--project=@.#~/.julia/packages/ijulia/vo51o/src/kernel.jl#{connection_file}
11:19:30.045 [warn] Failed to request KernelInfo Error: Could not send message: status is not connected
    at n._sendMessage (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.0-linux-x64/dist/node_modules/@jupyterlab/services.js:11:35565)
    at n._sendKernelShellControl (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.0-linux-x64/dist/node_modules/@jupyterlab/services.js:11:34854)
    at n.sendShellMessage (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.0-linux-x64/dist/node_modules/@jupyterlab/services.js:11:34646)
    at Object.t [as handleShellMessage] (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.0-linux-x64/dist/node_modules/@jupyterlab/services.js:11:44621)
    at n.requestKernelInfo (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.0-linux-x64/dist/node_modules/@jupyterlab/services.js:11:36974)
    at r5 (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.0-linux-x64/dist/extension.node.js:252:26242)
    at a_.initializeAfterStart (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.0-linux-x64/dist/extension.node.js:252:39489)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at processTimers (node:internal/timers:509:9)
    at a_.createJupyterSession (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.0-linux-x64/dist/extension.node.js:252:36279)
11:20:30.045 [error] Shutting down after failing to wait for idle on (kernel): 7bd04d71-8449-4f39-bad5-f9a0fc4b86ac -> unknown
11:20:31.048 [info] Kernel got disposed as a result of session.onDisposed ~/WORKS/tTMD_TB/simulations/utilities/playground.ipynb & _ignoreJupyterSessionDisposedErrors = false.
11:20:31.050 [warn] Error occurred while trying to start the kernel, options.disableUI=false Error: The Jupyter notebook server failed to launch in time
    > Kernel Id = dde01a5ee1235ff381acf210fe6585a582d38faeac656dfa05f0f07e70f11edf..julia-1.10./mmfs1/gscratch/cmt/wangc/.julia/juliaup/julia-1.10.0+0.x64.linux.gnu/bin/julia././mmfs1/gscratch/cmt/wangc/.julia/juliaup/julia-1.10.0+0.x64.linux.gnu/bin/julia#-i#--color=yes#--project=@.#~/.julia/packages/ijulia/vo51o/src/kernel.jl#{connection_file}
    > at ay (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.0-linux-x64/dist/extension.node.js:249:27876)
11:20:31.050 [warn] Kernel Error, context = start Error: The Jupyter notebook server failed to launch in time
    > Kernel Id = dde01a5ee1235ff381acf210fe6585a582d38faeac656dfa05f0f07e70f11edf..julia-1.10./mmfs1/gscratch/cmt/wangc/.julia/juliaup/julia-1.10.0+0.x64.linux.gnu/bin/julia././mmfs1/gscratch/cmt/wangc/.julia/juliaup/julia-1.10.0+0.x64.linux.gnu/bin/julia#-i#--color=yes#--project=@.#~/.julia/packages/ijulia/vo51o/src/kernel.jl#{connection_file}
    > at ay (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.0-linux-x64/dist/extension.node.js:249:27876)
11:20:31.066 [info] Dispose Kernel '~/WORKS/tTMD_TB/simulations/utilities/playground.ipynb' associated with '~/WORKS/tTMD_TB/simulations/utilities/playground.ipynb'
11:20:31.066 [error] Error in execution Error: The Jupyter notebook server failed to launch in time
    > Kernel Id = dde01a5ee1235ff381acf210fe6585a582d38faeac656dfa05f0f07e70f11edf..julia-1.10./mmfs1/gscratch/cmt/wangc/.julia/juliaup/julia-1.10.0+0.x64.linux.gnu/bin/julia././mmfs1/gscratch/cmt/wangc/.julia/juliaup/julia-1.10.0+0.x64.linux.gnu/bin/julia#-i#--color=yes#--project=@.#~/.julia/packages/ijulia/vo51o/src/kernel.jl#{connection_file}
    > at ay (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.0-linux-x64/dist/extension.node.js:249:27876)
11:20:31.067 [error] Error in execution (get message for cell) Error: The Jupyter notebook server failed to launch in time
    > Kernel Id = dde01a5ee1235ff381acf210fe6585a582d38faeac656dfa05f0f07e70f11edf..julia-1.10./mmfs1/gscratch/cmt/wangc/.julia/juliaup/julia-1.10.0+0.x64.linux.gnu/bin/julia././mmfs1/gscratch/cmt/wangc/.julia/juliaup/julia-1.10.0+0.x64.linux.gnu/bin/julia#-i#--color=yes#--project=@.#~/.julia/packages/ijulia/vo51o/src/kernel.jl#{connection_file}
    > at ay (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.0-linux-x64/dist/extension.node.js:249:27876)
11:20:31.134 [info] End cell 2 execution after 0s, completed @ undefined, started @ undefined
11:20:33.066 [info] Start refreshing Kernel Picker (1707247233066)
11:20:33.122 [info] End refreshing Kernel Picker (1707247233066)
```

Jupyter server log

```
[I 2024-02-06 11:18:19.645 ServerApp] User 8e6d6d3df58e4454b8d24107ae45e6f6 logged in.
[I 2024-02-06 11:18:19.646 ServerApp] 302 POST /login? (8e6d6d3df58e4454b8d24107ae45e6f6@10.64.64.20) 49.18ms
[I 2024-02-06 11:18:30.035 ServerApp] Kernel started: 7bd04d71-8449-4f39-bad5-f9a0fc4b86ac
Starting kernel event loops.
[I 2024-02-06 11:18:32.092 ServerApp] Adapting from protocol version 5.0 (kernel 7bd04d71-8449-4f39-bad5-f9a0fc4b86ac) to 5.3 (client).
[W 2024-02-06 11:18:32.093 ServerApp] 400 GET /api/kernels/7bd04d71-8449-4f39-bad5-f9a0fc4b86ac/channels?session_id=6a144608-cc34-4ed4-8aab-5e0a14f7fd5c (8e6d6d3df58e4454b8d24107ae45e6f6@10.64.64.20) 2048.90ms referer=None
[W 2024-02-06 11:19:46.277 ServerApp] Replacing stale connection: 7bd04d71-8449-4f39-bad5-f9a0fc4b86ac:6a144608-cc34-4ed4-8aab-5e0a14f7fd5c
[I 2024-02-06 11:19:46.277 ServerApp] Adapting from protocol version 5.0 (kernel 7bd04d71-8449-4f39-bad5-f9a0fc4b86ac) to 5.3 (client).
[W 2024-02-06 11:19:46.279 ServerApp] 400 GET /api/kernels/7bd04d71-8449-4f39-bad5-f9a0fc4b86ac/channels?session_id=6a144608-cc34-4ed4-8aab-5e0a14f7fd5c (8e6d6d3df58e4454b8d24107ae45e6f6@10.64.64.20) 4.76ms referer=None
[I 2024-02-06 11:20:30.051 ServerApp] Kernel shutdown: 7bd04d71-8449-4f39-bad5-f9a0fc4b86ac
```
</details>

**Comment by DonJayamanne** [comment]
Sorry for never getting back to you on this issue, somehow this slipped through the cracks.
We have made a lot of improvements and fixes in this space and believe this may have been resolved.
Please ensure you update to the latest version of VS code and the extensions.
Closing as I believe it may have been resolved,
If not please ping here and I'll reopen this or feel free to create a new issue.
