### ISSUE TITLE
Notebook screen cheese

### ISSUE THREAD

**Issue by johnbullnz** [microsoft/vscode-jupyter#15180]
Type: <b>Bug</b>

Extension version: 2024.1.1
VS Code version: Code - Insiders 1.87.0-insider (8fa84589eef3538dbc763ff98dc7d5a8a0c56374, 2024-02-09T05:47:15.236Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.0-91-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (1.02GB free)|
|Process Argv|--crash-reporter-id 267211ba-9702-4b1c-bd4f-a2ba84ab9547|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: 2024-pavement-design-loading-maps @ nuc|
|OS|Linux x64 5.15.0-91-generic|
|CPUs|11th Gen Intel(R) Core(TM) i7-11700B @ 3.20GHz (16 x 3200)|
|Memory (System)|30.93GB (24.07GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vscod805:30301674
vsaa593:30376534
py29gd2263:30784851
vscaat:30438846
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
welcomedialogc:30812479
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
pydisww1:30959800
d34g3935:30961436
edj9j583:30943796
fegfb526:30952798
7j2b6412:30951517
e3gdj431:30946825
ccp2r3:30958153

```

</details>

Running a devcontainer on a remote server (SSH) with the notebook saved on a network share. The issue doesn't present itself when the notebook is saved on the devcontainer filesystem.

Steps to reproduce:
1. Create a new notebook
2. Display some text and an image
3. Save the notebook (screen cheese occurs on notebook save)

See screenshot and `Output: Window` log below.

![image](https://github.com/microsoft/vscode-jupyter/assets/28794045/97c7986f-5bdc-4e94-9cb5-b50014be4921)

```
2024-02-13 11:10:48.987 [error] Whitespace not found: Error: Whitespace not found
    at E.getWhitespacePosition (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1092:48934)
    at T.getWhitespacePosition (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1092:50257)
    at I.j (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1098:10592)
    at I.layout (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1098:10075)
    at m.splice2 (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1692:42424)
    at vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1692:40897
    at Array.forEach (<anonymous>)
    at m.lb (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1692:40666)
    at h.value (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1692:40052)
    at o.y (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at o.z (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1972)
    at o.fire (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2188)
    at x (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1688:160835)
    at h.value (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1688:161500)
    at o.y (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at o.z (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1972)
    at o.fire (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2188)
    at h.value (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1690:19920)
    at s.y (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at s.fire (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at s.resume (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:3188)
    at d.applyEdits (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1690:23497)
    at d.reset (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1690:21960)
    at h.update (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1706:15086)
    at async m.cb (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2228:54636)
    at async m.$ (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2228:54373)
    at async m.Z (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2228:53814)
    at async $.lb (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2228:65450)
    at async $.kb (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2228:64720)
    at async Object.factory (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2228:63485)
2024-02-13 11:10:49.073 [error] Whitespace not found: Error: Whitespace not found
    at E.getWhitespacePosition (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1092:48934)
    at T.getWhitespacePosition (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1092:50257)
    at I.j (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1098:10592)
    at I.layout (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1098:10075)
    at m.updateElementHeight2 (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1692:51032)
    at Ce (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2605:22819)
    at ze.layoutNotebookCell (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2605:23026)
    at h.value (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2605:11549)
    at g.y (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at g.z (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1972)
    at g.fire (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2188)
    at g.fire (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:3317)
    at l.qb (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1688:134027)
    at l.layoutChange (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1688:133937)
    at l.updateOutputHeight (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1688:136682)
    at ze.Qc (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2605:33544)
    at h.value (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1894:2046)
    at o.y (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at o.fire (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1213:20327
    at vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1213:19983
    at Set.forEach (<anonymous>)
    at F.onmessage (vscode-file://vscode-app/c:/Users/nztac/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1213:19971)

```

**Comment by sirno** [comment]
I get similar rendering issues, when running the sequence `jupyter.interactive.clearAllCells`, `jupyter.runallcells`.

Same error message in `Output: Window`

**Comment by sirno** [comment]
For me all is good again

**Comment by rebornix** [comment]
We had a fix yesterday and this issue should now be fixed. Thank for the bug report!
