### ISSUE TITLE
Cannot preview data in VScode

### ISSUE THREAD

**Issue by Scolymus** [microsoft/vscode-jupyter#15305]
## Environment data

-   VS Code version: 1.87.0, attached-container, desktop
-   Jupyter Extension version (available under the Extensions sidebar): 2024.2.2024022602
-   Python Extension version (available under the Extensions sidebar): 2024.2.1
-   OS (Windows | Mac | Linux distro) and version: Ubuntu docker 
-   Python and/or Anaconda version: python:3.11 docker.
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local | Remote | N/A. I'm using the extension from VS.code

## Expected behaviour

I have a class that derives a DataFrame (yeah, weird thing...). This object is not recognized by Jupyter to preview, and therefore we added a method called "as_df", which basically does:

```   def as_df(self) -> pd.DataFrame:
            return pd.DataFrame(self)
``` 

Then by using this the jupyter extension was able to show the df in vs.code.

## Actual behaviour

I never restart, but the other day I had to restart vs.code and now I'm getting:

`Traceback (most recent call last): File "<string>", line 1, in <module> NameError: name 'as_df' is not defined. View Jupyter [log](command:jupyter.viewOutput) for further details.`

I guess it updated something. I haven't tried going to a previous release of vs.code, but I tried with jupyter extension, and no luck. Also I tried to update the pandas version within the docker (I'm vieweing it from inside dev containers) and no luck neither.

Note: Sometimes I even get a message (different, attaching it in the log section) for simple df.

May it be related with [ticket](https://github.com/microsoft/vscode-jupyter/issues/10516)?

## Steps to reproduce:

Create a breakpoint, and see the df variable.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Visual Studio Code (1.87.0, attached-container, desktop)
Jupyter Extension Version: 2024.2.2024022602.
Python Extension Version: 2024.2.1.
Pylance Extension Version: 2024.2.3.
Platform: linux (arm64).
Workspace folder /code, Home = /root
11:34:15.106 [info] Start refreshing Kernel Picker (1709724855106)
11:34:15.114 [info] Using Pylance
11:34:16.589 [info] End refreshing Kernel Picker (1709724855106)
11:34:17.233 [info] Start refreshing Kernel Picker (1709724857233)
11:34:17.582 [warn] Failed to get activated env vars for /usr/local/bin/python in 319ms
11:34:17.716 [info] Process Execution: /usr/local/bin/python -c "import site;print("USER_BASE_VALUE");print(site.USER_BASE);print("USER_BASE_VALUE");"
11:34:17.788 [info] Process Execution: /usr/local/bin/python -m pip list
11:34:18.287 [info] End refreshing Kernel Picker (1709724857233)
11:36:12.720 [info] Found debugAdapterPython on Debug Configuration to use
11:36:12.746 [warn] Failed to get activated env vars for /usr/local/bin/python in 15ms
11:36:12.771 [info] Process Execution: /usr/local/bin/python -c "import pandas;print(pandas.__version__);print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d")"
11:36:13.193 [error] Error [CodeExpectedError]: Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'as_df' is not defined

    at l.Q (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:936:38118)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:936:37657
11:36:13.194 [warn] DataScience Error Error [CodeExpectedError]: Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'as_df' is not defined

    at l.Q (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:936:38118)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:936:37657
```

</p>

Second possible log trace (for some normal df):
<p>
```
12:14:21.798 [info] Process Execution: /usr/local/bin/python -c "import pandas;print(pandas.__version__);print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d")"
12:14:22.208 [error] Error [CodeExpectedError]: Traceback (most recent call last):
  File "~/.vscode-server/extensions/ms-python.python-2024.2.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 1195, in internal_evaluate_expression_json
    pydevd_vars.evaluate_expression(py_db, frame, expression, is_exec=True)
  File "~/.vscode-server/extensions/ms-python.python-2024.2.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py", line 370, in new_func
    return _run_with_unblock_threads(original_func, py_db, curr_thread, frame, expression, is_exec)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.vscode-server/extensions/ms-python.python-2024.2.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py", line 334, in _run_with_unblock_threads
    return _run_with_interrupt_thread(original_func, py_db, curr_thread, frame, expression, is_exec)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.vscode-server/extensions/ms-python.python-2024.2.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py", line 305, in _run_with_interrupt_thread
    return original_func(py_db, frame, expression, is_exec)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.vscode-server/extensions/ms-python.python-2024.2.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py", line 548, in evaluate_expression
    compiled = _compile_as_exec(expression)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.vscode-server/extensions/ms-python.python-2024.2.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py", line 412, in _compile_as_exec
    return compile(expression_to_evaluate, '<string>', 'exec', _ASYNC_COMPILE_FLAGS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1
    _VSCODE_getVariable("info", True, [0:16] )
                                        ^
SyntaxError: invalid syntax

    at l.Q (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:936:38118)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:936:37657
12:14:22.208 [warn] DataScience Error Error [CodeExpectedError]: Traceback (most recent call last):
  File "~/.vscode-server/extensions/ms-python.python-2024.2.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 1195, in internal_evaluate_expression_json
    pydevd_vars.evaluate_expression(py_db, frame, expression, is_exec=True)
  File "~/.vscode-server/extensions/ms-python.python-2024.2.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py", line 370, in new_func
    return _run_with_unblock_threads(original_func, py_db, curr_thread, frame, expression, is_exec)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.vscode-server/extensions/ms-python.python-2024.2.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py", line 334, in _run_with_unblock_threads
    return _run_with_interrupt_thread(original_func, py_db, curr_thread, frame, expression, is_exec)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.vscode-server/extensions/ms-python.python-2024.2.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py", line 305, in _run_with_interrupt_thread
    return original_func(py_db, frame, expression, is_exec)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.vscode-server/extensions/ms-python.python-2024.2.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py", line 548, in evaluate_expression
    compiled = _compile_as_exec(expression)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.vscode-server/extensions/ms-python.python-2024.2.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_vars.py", line 412, in _compile_as_exec
    return compile(expression_to_evaluate, '<string>', 'exec', _ASYNC_COMPILE_FLAGS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1
    _VSCODE_getVariable("info", True, [0:16] )
                                        ^
SyntaxError: invalid syntax

    at l.Q (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:936:38118)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:936:37657
```
</p>
</details>

**Comment by amunger** [comment]
what action are you taking when you see that error? It sounds like your `as_df` method isn't being added correctly (did the imported file change?), but I'm not sure why the extension's code is trying to call it.

Is that second log showing that a standard dataframe object is also failing in some way?

**Comment by Scolymus** [comment]
No, the imported file haven't changed. I never restart the laptop, and I had to do it for some updates, so I guess a new VS.code / jupyter version was updated.

To see this error I put a breakpoint and try to see the variable data. In the variables section, under "RUN AND DEBUG" section, I right click over the "as_df" property, and it lists a context menu with the option "View Value in Data Previewer", as it was doing before, but when clicking, it shows that error.

When doing the same on other pure dataframes I have seen the second log error. Interesting, there after trying to click on "View Value in Data Previewer" for a second time in the same breakpoint, before continuing, it opened the data preview.

**Comment by Scolymus** [comment]
One thing I discovered, if I do in debug terminal `t = self.myobject.as_df` I can preview the t dataframe, but still not directly from self.myobject.as_df

**Comment by amunger** [comment]
I can get the DataWrangler data viewer to come up successfully from the debugger variables view for the as_df property in this code:

```
import pandas as pd

class B:
    data = {'a': [1, 2, 3], 'b': [4, 5, 6]}
    as_df = pd.DataFrame(data)

b = B()
print('breakpoint here')
```

Let me know if that's not the case your after
