### ISSUE TITLE
duplicate entries when creating a new venv

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#15360]
1. Open a workspace with a venv in it
2. close all editors and reload vscode
3. delete the .venv
4. Create a new notebook
5. Use the kernel picker to create a new venv
:bug: lots of duplicate interpreter entries

![image](https://github.com/microsoft/vscode-jupyter/assets/2019016/65f11b6e-6a5e-4913-a786-12df272a207b)

<details>
<summary>Jupyter logs</summary>

```
Visual Studio Code - Insiders (1.88.0-insider, undefined, desktop)
Jupyter Extension Version: 2024.3.2024031201.
Python Extension Version: 2024.3.10660538.
Pylance Extension Version: 2024.2.105.
Platform: win32 (x64).
Workspace folder c:\src\test\5, Home = c:\Users\aamunger
13:11:26.657 [info] User belongs to experiment group 'KernelCompletions'
13:11:27.507 [debug] Get Custom Env Variables, Class name = Wm (started execution), Arg 1: undefined, Arg 2: "RunPythonCode"
13:11:27.508 [info] Start refreshing Kernel Picker (1710360687508)
13:11:27.546 [info] Using Pylance
13:11:27.581 [debug] Search for KernelSpecs in Interpreter ~\AppData\Local\Programs\Python\Python37\python.exe
13:11:27.582 [debug] Search for KernelSpecs in Interpreter ~\AppData\Local\miniconda3\envs\.condaenv\python.exe
13:11:27.583 [debug] Search for KernelSpecs in Interpreter c:\SRC\TEST\7\.CONDA\python.exe
13:11:27.583 [debug] Search for KernelSpecs in Interpreter c:\src\test\2\.conda\python.exe
13:11:27.583 [debug] Search for KernelSpecs in Interpreter ~\AppData\Local\Programs\Python\Python311\python.exe
13:11:27.583 [debug] Search for KernelSpecs in Interpreter ~\AppData\Local\Programs\Python\Python39\python.exe
13:11:27.584 [debug] Search for KernelSpecs in Interpreter ~\AppData\Local\Microsoft\WindowsApps\python3.9.exe
13:11:27.584 [debug] Search for KernelSpecs in Interpreter c:\src\test\5\.venv\Scripts\python.exe
13:11:27.584 [debug] Finding Global Python KernelSpecs
13:11:27.585 [debug] Kernels for interpreter ~\APPDATA\LOCAL\MINICONDA3\PYTHON.EXE are 
13:11:27.586 [debug] Kernels for interpreter C:\PYTHON310\PYTHON.EXE are 
13:11:27.587 [debug] Get Custom Env Variables, Class name = Wm, completed in 80ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
13:11:27.588 [debug] Jupyter Paths kernels: 
13:11:27.589 [debug] Kernel Spec Root Paths, ~\AppData\Roaming\jupyter\kernels, c:\ProgramData\jupyter\kernels
13:11:27.751 [debug] Preferred Remote kernel for Untitled-1.ipynb is undefined
13:11:29.960 [debug] Kernels for interpreter ~\APPDATA\LOCAL\MINICONDA3\ENVS\.CONDAENV\PYTHON.EXE are .jvsc74a57bd0a1d418fd286a2cf83ecc39394756f5e73e9f2639fce2378573983699688d4f61.~\AppData\Local\miniconda3\envs\.condaenv\python.exe.~\AppData\Local\miniconda3\envs\.condaenv\python.exe.-m#ipykernel_launcher
13:11:29.960 [debug] Kernels for interpreter ~\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON311\PYTHON.EXE are .jvsc74a57bd0b414f0a7af59a62087a3c034b1bf0fb2182b989016e422ac3c8654c8d5741714.~\AppData\Local\Programs\Python\Python311\python.exe.~\AppData\Local\Programs\Python\Python311\python.exe.-m#ipykernel_launcher
13:11:29.961 [debug] Kernels for interpreter ~\APPDATA\LOCAL\MICROSOFT\WINDOWSAPPS\PYTHON3.9.EXE are .jvsc74a57bd0176980a33df66f0dfe3342e384ae95411c4a6e61b32e15a537ffe394a9f57c82.~\AppData\Local\Microsoft\WindowsApps\python3.9.exe.~\AppData\Local\Microsoft\WindowsApps\python3.9.exe.-m#ipykernel_launcher
13:11:29.962 [debug] Kernels for interpreter ~\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON39\PYTHON.EXE are .jvsc74a57bd062fb0c6e64fc1ec314e6acba0833e2af97b61408f181466b2334aa893bb27a78.~\AppData\Local\Programs\Python\Python39\python.exe.~\AppData\Local\Programs\Python\Python39\python.exe.-m#ipykernel_launcher
13:11:29.962 [debug] Kernels for interpreter C:\SRC\TEST\5\.VENV\SCRIPTS\PYTHON.EXE are .jvsc74a57bd0d350a59252404aced913989f8c7fc96755762dc112aec5d6f77276e00ed38a49.c:\src\test\5\.venv\Scripts\python.exe.c:\src\test\5\.venv\Scripts\python.exe.-m#ipykernel_launcher
13:11:37.187 [debug] Loading kernelspec from ~\AppData\Local\Programs\Python\Python37\share\jupyter\kernels\python3\kernel.json for ~\AppData\Local\Programs\Python\Python37\python.exe
13:11:37.188 [debug] Loading kernelspec from c:\src\test\2\.conda\share\jupyter\kernels\python3\kernel.json for c:\src\test\2\.conda\python.exe
13:11:37.189 [debug] Loading kernelspec from c:\SRC\TEST\7\.CONDA\share\jupyter\kernels\python3\kernel.json for c:\SRC\TEST\7\.CONDA\python.exe
13:11:37.304 [debug] Hiding default kernel spec 'Python 3 (ipykernel)', 'python379jvsc74a57bd0c425ebb03616a8a25d4d93a3e4bafd01d56f1c50213fc0be01320c989c46a1ea', python for interpreter ~\AppData\Local\Programs\Python\Python37\python.exe and spec ~\AppData\Local\Programs\Python\Python37\share\jupyter\kernels\python3\kernel.json
13:11:37.305 [debug] Kernels for interpreter ~\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON37\PYTHON.EXE are .jvsc74a57bd0c425ebb03616a8a25d4d93a3e4bafd01d56f1c50213fc0be01320c989c46a1ea.~\AppData\Local\Programs\Python\Python37\python.exe.~\AppData\Local\Programs\Python\Python37\python.exe.-m#ipykernel_launcher
13:11:37.306 [debug] Hiding default kernel spec 'Python 3 (ipykernel)', 'python3813jvsc74a57bd0569b6500128a5daa99d2b996725b7d7eae797a774f437c3f9124d6cd683cd1fb', c:\src\test\2\.conda\python.exe for interpreter c:\src\test\2\.conda\python.exe and spec c:\src\test\2\.conda\share\jupyter\kernels\python3\kernel.json
13:11:37.307 [debug] Kernels for interpreter C:\SRC\TEST\2\.CONDA\PYTHON.EXE are .jvsc74a57bd0569b6500128a5daa99d2b996725b7d7eae797a774f437c3f9124d6cd683cd1fb.c:\src\test\2\.conda\python.exe.c:\src\test\2\.conda\python.exe.-m#ipykernel_launcher
13:11:37.307 [debug] Hiding default kernel spec 'Python 3 (ipykernel)', 'python3915jvsc74a57bd0f303698a459e01b364e04846299a5cd77d497b05e88e160c36f095d30fa7801f', c:\SRC\TEST\7\.CONDA\python.exe for interpreter c:\SRC\TEST\7\.CONDA\python.exe and spec c:\SRC\TEST\7\.CONDA\share\jupyter\kernels\python3\kernel.json
13:11:37.307 [debug] Kernels for interpreter C:\SRC\TEST\7\.CONDA\PYTHON.EXE are .jvsc74a57bd0f303698a459e01b364e04846299a5cd77d497b05e88e160c36f095d30fa7801f.c:\SRC\TEST\7\.CONDA\python.exe.c:\SRC\TEST\7\.CONDA\python.exe.-m#ipykernel_launcher
13:11:37.311 [debug] Loading kernelspec from ~\AppData\Roaming\jupyter\kernels\.venvkernel\kernel.json 
13:11:37.311 [debug] Loading kernelspec from ~\AppData\Roaming\jupyter\kernels\.venvkernel2\kernel.json 
13:11:37.312 [debug] Loading kernelspec from ~\AppData\Roaming\jupyter\kernels\.venvnokernel\kernel.json 
13:11:37.312 [debug] Loading kernelspec from ~\AppData\Roaming\jupyter\kernels\bash\kernel.json 
13:11:37.312 [debug] Loading kernelspec from ~\AppData\Roaming\jupyter\kernels\deno\kernel.json 
13:11:37.312 [debug] Loading kernelspec from ~\AppData\Roaming\jupyter\kernels\incompleteSpec\kernel.json 
13:11:37.312 [debug] Loading kernelspec from ~\AppData\Roaming\jupyter\kernels\julia-1.7\kernel.json 
13:11:37.312 [debug] Loading kernelspec from ~\AppData\Roaming\jupyter\kernels\julia-1.9\kernel.json 
13:11:37.312 [debug] Loading kernelspec from c:\ProgramData\jupyter\kernels\global\kernel.json 
13:11:37.312 [debug] Loading kernelspec from c:\ProgramData\jupyter\kernels\java\kernel.json 
13:11:37.313 [debug] Loading kernelspec from c:\ProgramData\jupyter\kernels\python3\kernel.json 
13:11:39.005 [error] UniversalRemoteKernelFinder: Failed to get kernels without cache Ip [Error]: invalid json response body at https://ubiquitous-space-guide-r7w7rqpjvv3576g-8000.app.github.dev/hub/api/authorizations/token reason: Unexpected end of JSON input
    at pn.getJupyterServerUri (~\.vscode-insiders\extensions\ms-toolsai.jupyter-2024.3.2024031201-win32-x64\dist\extension.node.js:198:18892)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at pn.createConnectionInfo (~\.vscode-insiders\extensions\ms-toolsai.jupyter-2024.3.2024031201-win32-x64\dist\extension.node.js:198:16612)
    at ~\.vscode-insiders\extensions\ms-toolsai.jupyter-2024.3.2024031201-win32-x64\dist\extension.node.js:308:17634 {
  category: 'remotejupyterserveruriprovider',
  isJupyterError: true,
  serverProviderHandle: {
    id: 'UserJupyterServerPickerProviderId',
    handle: 'b01648b2-a8e2-51be-82d9-6c812624ad5e',
    extensionId: 'ms-toolsai.jupyter-hub'
  },
  originalError: FetchError: invalid json response body at https://ubiquitous-space-guide-r7w7rqpjvv3576g-8000.app.github.dev/hub/api/authorizations/token reason: Unexpected end of JSON input
      at ~\.vscode-insiders\extensions\ms-toolsai.jupyter-hub-2023.10.1003492320\dist\extension.node.js:62750:40
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at generateNewApiTokenOldWay (~\.vscode-insiders\extensions\ms-toolsai.jupyter-hub-2023.10.1003492320\dist\extension.node.js:64214:18)
      at JupyterServerIntegration.resolveJupyterServerImpl (~\.vscode-insiders\extensions\ms-toolsai.jupyter-hub-2023.10.1003492320\dist\extension.node.js:65305:20) {
    type: 'invalid-json'
  }
}
13:11:39.009 [debug] UniversalRemoteKernelFinder: Writing 0 remote kernel connection metadata to cache
13:11:39.038 [info] End refreshing Kernel Picker (1710360687508)
13:11:44.806 [debug] Conda file returned by Python Extension is conda
13:11:58.169 [debug] Python API env change detected, add => '~\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON310\PYTHON.EXE'
13:11:58.172 [debug] Finding Global Python KernelSpecs
13:11:58.179 [info] Start refreshing Kernel Picker (1710360718179)
13:11:58.183 [debug] Kernels for interpreter ~\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON310\PYTHON.EXE are 
13:11:58.202 [warn] Kernel Spec for 'global' (c:\ProgramData\jupyter\kernels\global\kernel.json) hidden, as we cannot find a matching interpreter argv = 'C:\venvs\venvRepro\Scripts\python.exe'. To resolve this, please change 'C:\venvs\venvRepro\Scripts\python.exe' to point to the fully qualified Python executable.
13:11:58.205 [warn] No interpreter with path c:\src\vscode-jupyter\.venvkernel\Scripts\python.exe found in Python API, will convert Uri path to string as Id c:\src\vscode-jupyter\.venvkernel\Scripts\python.exe
13:11:58.211 [warn] No interpreter with path c:\src\vscode-jupyter\src\test\datascience\.venvkernel\Scripts\python2.exe found in Python API, will convert Uri path to string as Id c:\src\vscode-jupyter\src\test\datascience\.venvkernel\Scripts\python2.exe
13:11:58.215 [warn] No interpreter with path c:\src\vscode-jupyter\.venvnokernel\Scripts\python.exe found in Python API, will convert Uri path to string as Id c:\src\vscode-jupyter\.venvnokernel\Scripts\python.exe
13:12:03.678 [debug] Controller startUsingPythonInterpreter:'.jvsc74a57bd00b3f6e928dda7c09aa57d1fbbe96e60fed18fb335015da481ed8ef7212ae02ea.~\AppData\Local\Programs\Python\Python310\python.exe.~\AppData\Local\Programs\Python\Python310\python.exe.-m#ipykernel_launcher' for view = 'jupyter-notebook' is no longer a valid
13:12:03.678 [debug] Controller startUsingPythonInterpreter:'.jvsc74a57bd00b3f6e928dda7c09aa57d1fbbe96e60fed18fb335015da481ed8ef7212ae02ea.~\AppData\Local\Programs\Python\Python310\python.exe.~\AppData\Local\Programs\Python\Python310\python.exe.-m#ipykernel_launcher (Interactive)' for view = 'interactive' is no longer a valid
13:12:03.678 [warn] Disposing old controller startUsingPythonInterpreter:'.jvsc74a57bd00b3f6e928dda7c09aa57d1fbbe96e60fed18fb335015da481ed8ef7212ae02ea.~\AppData\Local\Programs\Python\Python310\python.exe.~\AppData\Local\Programs\Python\Python310\python.exe.-m#ipykernel_launcher' for view = 'jupyter-notebook'
13:12:03.678 [debug] Disposing controller .jvsc74a57bd00b3f6e928dda7c09aa57d1fbbe96e60fed18fb335015da481ed8ef7212ae02ea.~\AppData\Local\Programs\Python\Python310\python.exe.~\AppData\Local\Programs\Python\Python310\python.exe.-m#ipykernel_launcher associated with connection .jvsc74a57bd00b3f6e928dda7c09aa57d1fbbe96e60fed18fb335015da481ed8ef7212ae02ea.~\AppData\Local\Programs\Python\Python310\python.exe.~\AppData\Local\Programs\Python\Python310\python.exe.-m#ipykernel_launcher 
13:12:03.680 [warn] Disposing old controller startUsingPythonInterpreter:'.jvsc74a57bd00b3f6e928dda7c09aa57d1fbbe96e60fed18fb335015da481ed8ef7212ae02ea.~\AppData\Local\Programs\Python\Python310\python.exe.~\AppData\Local\Programs\Python\Python310\python.exe.-m#ipykernel_launcher (Interactive)' for view = 'interactive'
13:12:03.680 [debug] Disposing controller .jvsc74a57bd00b3f6e928dda7c09aa57d1fbbe96e60fed18fb335015da481ed8ef7212ae02ea.~\AppData\Local\Programs\Python\Python310\python.exe.~\AppData\Local\Programs\Python\Python310\python.exe.-m#ipykernel_launcher (Interactive) associated with connection .jvsc74a57bd00b3f6e928dda7c09aa57d1fbbe96e60fed18fb335015da481ed8ef7212ae02ea.~\AppData\Local\Programs\Python\Python310\python.exe.~\AppData\Local\Programs\Python\Python310\python.exe.-m#ipykernel_launcher 
13:12:03.682 [debug] Python API env change detected, remove => '~\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON310\PYTHON.EXE'
13:12:03.735 [debug] Detected change in Active Python environment via Python API
13:12:03.737 [debug] Detected change in Active Python environment via Python API
13:12:03.745 [debug] Controller startUsingPythonInterpreter:'.jvsc74a57bd0d350a59252404aced913989f8c7fc96755762dc112aec5d6f77276e00ed38a49.c:\src\test\5\.venv\Scripts\python.exe.c:\src\test\5\.venv\Scripts\python.exe.-m#ipykernel_launcher' for view = 'jupyter-notebook' is no longer a valid
13:12:03.745 [debug] Controller startUsingPythonInterpreter:'.jvsc74a57bd0d350a59252404aced913989f8c7fc96755762dc112aec5d6f77276e00ed38a49.c:\src\test\5\.venv\Scripts\python.exe.c:\src\test\5\.venv\Scripts\python.exe.-m#ipykernel_launcher (Interactive)' for view = 'interactive' is no longer a valid
13:12:03.745 [warn] Disposing old controller startUsingPythonInterpreter:'.jvsc74a57bd0d350a59252404aced913989f8c7fc96755762dc112aec5d6f77276e00ed38a49.c:\src\test\5\.venv\Scripts\python.exe.c:\src\test\5\.venv\Scripts\python.exe.-m#ipykernel_launcher' for view = 'jupyter-notebook'
13:12:03.745 [debug] Disposing controller .jvsc74a57bd0d350a59252404aced913989f8c7fc96755762dc112aec5d6f77276e00ed38a49.c:\src\test\5\.venv\Scripts\python.exe.c:\src\test\5\.venv\Scripts\python.exe.-m#ipykernel_launcher associated with connection .jvsc74a57bd0d350a59252404aced913989f8c7fc96755762dc112aec5d6f77276e00ed38a49.c:\src\test\5\.venv\Scripts\python.exe.c:\src\test\5\.venv\Scripts\python.exe.-m#ipykernel_launcher 
13:12:03.746 [warn] Disposing old controller startUsingPythonInterpreter:'.jvsc74a57bd0d350a59252404aced913989f8c7fc96755762dc112aec5d6f77276e00ed38a49.c:\src\test\5\.venv\Scripts\python.exe.c:\src\test\5\.venv\Scripts\python.exe.-m#ipykernel_launcher (Interactive)' for view = 'interactive'
13:12:03.746 [debug] Disposing controller .jvsc74a57bd0d350a59252404aced913989f8c7fc96755762dc112aec5d6f77276e00ed38a49.c:\src\test\5\.venv\Scripts\python.exe.c:\src\test\5\.venv\Scripts\python.exe.-m#ipykernel_launcher (Interactive) associated with connection .jvsc74a57bd0d350a59252404aced913989f8c7fc96755762dc112aec5d6f77276e00ed38a49.c:\src\test\5\.venv\Scripts\python.exe.c:\src\test\5\.venv\Scripts\python.exe.-m#ipykernel_launcher 
13:12:03.750 [debug] Python API env change detected, remove => 'C:\SRC\TEST\5\.VENV\SCRIPTS\PYTHON.EXE'
13:12:04.041 [warn] Kernel Spec for '.venvnokernel' (~\AppData\Roaming\jupyter\kernels\.venvnokernel\kernel.json) hidden, as we cannot find a matching interpreter argv = 'C:\src\vscode-jupyter\.venvnokernel\Scripts\python.exe'. To resolve this, please change 'C:\src\vscode-jupyter\.venvnokernel\Scripts\python.exe' to point to the fully qualified Python executable.
13:12:04.045 [warn] Kernel Spec for '.venvkernel' (~\AppData\Roaming\jupyter\kernels\.venvkernel\kernel.json) hidden, as we cannot find a matching interpreter argv = 'C:\src\vscode-jupyter\.venvkernel\Scripts\python.exe'. To resolve this, please change 'C:\src\vscode-jupyter\.venvkernel\Scripts\python.exe' to point to the fully qualified Python executable.
13:12:04.361 [warn] The following kernels use interpreters that are no longer valid or not recognized by Python extension, Kernels startUsingPythonInterpreter:'id=.jvsc74a57bd0d350a59252404aced913989f8c7fc96755762dc112aec5d6f77276e00ed38a49.c:\src\test\5\.venv\Scripts\python.exe.c:\src\test\5\.venv\Scripts\python.exe.-m#ipykernel_launcher'(interpreterId='c:\SRC\TEST\5\.VENV\SCRIPTS\PYTHON.EXE') and valid interpreter ids include ~\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON37\PYTHON.EXE, ~\APPDATA\LOCAL\MINICONDA3\PYTHON.EXE, ~\APPDATA\LOCAL\MINICONDA3\ENVS\.CONDAENV\PYTHON.EXE, C:\SRC\TEST\7\.CONDA\PYTHON.EXE, C:\SRC\TEST\2\.CONDA\PYTHON.EXE, C:\PYTHON310\PYTHON.EXE, ~\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON311\PYTHON.EXE, ~\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON39\PYTHON.EXE, ~\APPDATA\LOCAL\MICROSOFT\WINDOWSAPPS\PYTHON3.9.EXE
13:12:04.361 [debug] Local Python connection deleted startUsingPythonInterpreter:'.jvsc74a57bd0d350a59252404aced913989f8c7fc96755762dc112aec5d6f77276e00ed38a49.c:\src\test\5\.venv\Scripts\python.exe.c:\src\test\5\.venv\Scripts\python.exe.-m#ipykernel_launcher: (interpreter id=c:\SRC\TEST\5\.VENV\SCRIPTS\PYTHON.EXE)'
13:12:04.362 [info] End refreshing Kernel Picker (1710360718179)
13:12:04.692 [debug] Interpreter removed ~\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON310\PYTHON.EXE
13:12:04.753 [debug] Interpreter removed C:\SRC\TEST\5\.VENV\SCRIPTS\PYTHON.EXE

```

</details>

**Comment by DonJayamanne** [comment]
Transferring to Python ext as this is contributed by the Python extension
