### ISSUE TITLE
Unable to create an interactive window

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#15382]
## Environment data

-   VS Code version: Stable
-   Jupyter Extension version (available under the Extensions sidebar): Stable/Insiders

* Open a Python fiule
* Create a code cell
* Run the cell in IW
* IW fails to open

```
  ERR Error: The Interactive Window model could not be resolved
    at ee.setInput (interactiveEditor.ts:426:10)
    at async d.S (editorPanes.ts:445:4)
    at async d.L (editorPanes.ts:270:34)
    at async d.openEditor (editorPanes.ts:146:12)
    at async editorGroupView.ts:1124:49
    at async u.run (interactive.contribution.ts:419:22)
```

![Screenshot 2024-03-19 at 01 40 01](https://github.com/microsoft/vscode-jupyter/assets/1948812/8ada5da2-1b6d-4e3a-9d36-7ac0b820987d)

**Comment by DonJayamanne** [comment]
Ok, I had disabled the ipynb extension.
My bad
