### ISSUE TITLE
Matplotlib widget extension seemed to hang interactive python notebook server

### ISSUE THREAD

**Issue by Jacfger** [microsoft/vscode-jupyter#15391]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

Not hang.

When matplotlib widget is loaded in python interactive mode, the plot will eventually cause Jupyter core to hangs. And it is not possible to submit next block of code or do anything until restarting the jupyter server.

## Steps to reproduce:

```
import matplotlib.pyplot as plt
import numpy as np
%matplotlib widget

plt.plot(np.array([1, 2, 3, 4]))
```
This code, and try to keep resizing the plot by dragging around. My actual problem didn't occur because of dragging but rather than other interactive elements, but the overall response is the same where the Jupyter notebook core freeze and unable to submit further code.

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.13
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>
Python Output
```
Experiment 'pythonaacf' is active
Experiment 'pythonRecommendTensorboardExt' is active
Experiment 'pythonREPLSmartSend' is active
Experiment 'pythonTerminalEnvVarActivation' is active
Experiment 'pythonTestAdapter' is active
> conda info --json
Python interpreter path: ~/miniconda3/bin/python
> conda info --json
shell: zsh
> ~/.conda/bin/conda info --json
> ~/miniconda3/bin/conda info --json
> ~/.conda/bin/conda info --json
shell: zsh
> ~/miniconda3/bin/conda info --json
shell: zsh
> /bin/python3 -I ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/get_output_via_markers.py ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/interpreterInfo.py
> /usr/bin/python3 -I ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/get_output_via_markers.py ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/interpreterInfo.py
> ~/miniconda3/bin/conda run -n base --no-capture-output python ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/get_output_via_markers.py ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/printEnvVariables.py
shell: zsh
> ~/miniconda3/bin/python -I ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/get_output_via_markers.py ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/interpreterInfo.py
> ~/miniconda3/bin/conda run -n base --no-capture-output python ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/get_output_via_markers.py ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/printEnvVariables.py
shell: bash
Starting Pylance language server.
> ~/miniconda3/bin/conda run -n base --no-capture-output python ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/get_output_via_markers.py ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/printEnvVariables.py
shell: bash
> ~/miniconda3/bin/conda run -n base --no-capture-output python ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/get_output_via_markers.py ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/printEnvVariables.py
shell: bash
> ~/miniconda3/bin/conda run -n base --no-capture-output python ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/get_output_via_markers.py ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/printEnvVariables.py
shell: bash
> ~/miniconda3/bin/conda run -n base --no-capture-output python ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/get_output_via_markers.py ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/printEnvVariables.py
shell: bash
> ~/miniconda3/bin/conda run -n base --no-capture-output python ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/get_output_via_markers.py ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/printEnvVariables.py
shell: bash
> ~/miniconda3/bin/conda run -n base --no-capture-output python ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/get_output_via_markers.py ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/printEnvVariables.py
shell: bash
> ~/miniconda3/bin/conda run -n base --no-capture-output python ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/get_output_via_markers.py ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/printEnvVariables.py
shell: bash
> ~/miniconda3/bin/conda run -n base --no-capture-output python ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/get_output_via_markers.py ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/printEnvVariables.py
shell: bash
> ~/miniconda3/bin/conda run -n base --no-capture-output python ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/get_output_via_markers.py ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/printEnvVariables.py
shell: bash
> ~/miniconda3/bin/conda run -n base --no-capture-output python ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/get_output_via_markers.py ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/printEnvVariables.py
shell: bash
> ~/miniconda3/bin/conda info --json
> ~/miniconda3/bin/conda run -n base --no-capture-output python ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/get_output_via_markers.py ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/printEnvVariables.py
shell: bash
> ~/miniconda3/bin/conda run -n base --no-capture-output python ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/get_output_via_markers.py ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/printEnvVariables.py
shell: bash
> ~/miniconda3/bin/conda run -n base --no-capture-output python ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/get_output_via_markers.py ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/printEnvVariables.py
shell: bash
> ~/miniconda3/bin/conda run -n base --no-capture-output python ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/get_output_via_markers.py ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/printEnvVariables.py
shell: bash
> ~/miniconda3/bin/conda run -n base --no-capture-output python ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/get_output_via_markers.py ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/printEnvVariables.py
shell: bash
> ~/miniconda3/bin/conda run -n base --no-capture-output python ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/get_output_via_markers.py ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/printEnvVariables.py
shell: bash
> ~/miniconda3/bin/conda run -n base --no-capture-output python ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/get_output_via_markers.py ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/printEnvVariables.py
shell: bash
> ~/miniconda3/bin/conda run -n base --no-capture-output python ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/get_output_via_markers.py ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/printEnvVariables.py
shell: bash
> ~/miniconda3/bin/conda run -n base --no-capture-output python ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/get_output_via_markers.py ~/.vscode-server-insiders/extensions/ms-python.python-2023.6.1/pythonFiles/printEnvVariables.py
shell: bash
```

Jupyter Output (partial)
```
Traceback (most recent call last):
  File "~/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 395, in dispatch_shell
    msg = self.session.deserialize(msg, content=True, copy=False)
  File "~/.local/lib/python3.10/site-packages/jupyter_client/session.py", line 1067, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'c1a2ffae921de1cbfb8acd81c29fba9598a5334c59e9567a19478529805772fd'
[IPKernelApp] ERROR | Invalid Message
Traceback (most recent call last):
  File "~/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 395, in dispatch_shell
    msg = self.session.deserialize(msg, content=True, copy=False)
  File "~/.local/lib/python3.10/site-packages/jupyter_client/session.py", line 1067, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'c99a55fab18b0a5bef6afc613bfddc9223f3a862523256d61bb72c0a5eb9d740'

18:13:46.520 [warn] StdErr from Kernel Process [IPKernelApp] ERROR | Invalid Message
Traceback (most recent call last):
  File "~/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 395, in dispatch_shell
    msg = self.session.deserialize(msg, content=True, copy=False)
  File "~/.local/lib/python3.10/site-packages/jupyter_client/session.py", line 1067, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'9bdaf878a57a6e3469336fb3b3b9739725ea9458b0239facc6efa0c03834cc55'
[IPKernelApp] ERROR | Invalid Message
Traceback (most recent call last):
  File "~/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 395, in dispatch_shell
    msg = self.session.deserialize(msg, content=True, copy=False)
  File "~/.local/lib/python3.10/site-packages/jupyter_client/session.py", line 1067, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'c1a2ffae921de1cbfb8acd81c29fba9598a5334c59e9567a19478529805772fd'
[IPKernelApp] ERROR | Invalid Message
Traceback (most recent call last):
  File "~/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 395, in dispatch_shell
    msg = self.session.deserialize(msg, content=True, copy=False)
  File "~/.local/lib/python3.10/site-packages/jupyter_client/session.py", line 1067, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'c99a55fab18b0a5bef6afc613bfddc9223f3a862523256d61bb72c0a5eb9d740'
18:13:46.730 [debug] KernelProcess error: [IPKernelApp] ERROR | Invalid Message
Traceback (most recent call last):
  File "~/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 395, in dispatch_shell
    msg = self.session.deserialize(msg, content=True, copy=False)
  File "~/.local/lib/python3.10/site-packages/jupyter_client/session.py", line 1067, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'6239a178be7e2a21b487732e6f6f664afa39dba7ff8c22e06108016098b3db77'

18:13:46.731 [warn] StdErr from Kernel Process [IPKernelApp] ERROR | Invalid Message
Traceback (most recent call last):
  File "~/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 395, in dispatch_shell
    msg = self.session.deserialize(msg, content=True, copy=False)
  File "~/.local/lib/python3.10/site-packages/jupyter_client/session.py", line 1067, in deserialize
    raise ValueError("Duplicate Signature: %r" % signature)
ValueError: Duplicate Signature: b'6239a178be7e2a21b487732e6f6f664afa39dba7ff8c22e06108016098b3db77'
18:14:02.816 [debug] CodeLensFactory: Generating new code lenses for version 921 of document file://~/<username>-backup/<username>-inference-submission/case_study_inference_h8.py for commands jupyter.runcell, jupyter.runallcellsabove, jupyter.debugcell, jupyter.debugcontinue, jupyter.debugstop, jupyter.debugstepover
18:14:03.566 [debug] CodeLensFactory: Generating new code lenses for version 925 of document file://~/<username>-backup/<username>-inference-submission/case_study_inference_h8.py for commands jupyter.runcell, jupyter.runallcellsabove, jupyter.debugcell, jupyter.debugcontinue, jupyter.debugstop, jupyter.debugstepover
18:14:04.302 [debug] CodeLensFactory: Generating new code lenses for version 926 of document file://~/<username>-backup/<username>-inference-submission/case_study_inference_h8.py for commands jupyter.runcell, jupyter.runallcellsabove, jupyter.debugcell, jupyter.debugcontinue, jupyter.debugstop, jupyter.debugstepover
18:14:05.056 [debug] CodeLensFactory: Generating new code lenses for version 931 of document file://~/<username>-backup/<username>-inference-submission/case_study_inference_h8.py for commands jupyter.runcell, jupyter.runallcellsabove, jupyter.debugcell, jupyter.debugcontinue, jupyter.debugstop, jupyter.debugstepover
18:14:05.418 [info] Generated code for 2 = <ipython-input-2-935f643be3eb> with 2 lines
18:14:05.440 [debug] Start cell 2 execution @ 1710843245440
18:14:10.737 [debug] Executing silently Code (idle) = def _VSCODE_getVariable(what_to_get, is_debugging, *args):\n# Query Jupyter server for the info a
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

formatting
• autopep8Args: "<placeholder>"
• provider: "black"
• yapfArgs: "<placeholder>"

```

</p>
</details>

Extension version: 2023.22.1
VS Code version: Code - Insiders 1.84.0-insider (55d1cfea45b665bb54e46d11bd3ccddf9e66108b, 2023-10-09T06:13:04.640Z)
OS version: Darwin arm64 22.6.0
Modes:
Connection to 'ssh-remote+james3' could not be established
Remote OS version: Linux x64 5.15.0-97-generic
Remote OS version: Linux x64 5.15.0-97-generic
Remote OS version: Linux x64 5.15.0-97-generic
Remote OS version: Linux x64 5.15.0-97-generic
Remote OS version: Linux x64 5.15.0-97-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 4, 5|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|--crash-reporter-id a536a798-1418-4ca3-ac36-49c36072a4b9|
|Screen Reader|no|
|VM|0%|

Connection to 'ssh-remote+james3' could not be established

|Item|Value|
|---|---|
|Remote|SSH: james3|
|OS|Linux x64 5.15.0-97-generic|
|CPUs|Intel(R) Xeon(R) Gold 6342 CPU @ 2.80GHz (96 x 2900)|
|Memory (System)|503.52GB (288.67GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: james3|
|OS|Linux x64 5.15.0-97-generic|
|CPUs|Intel(R) Xeon(R) Gold 6342 CPU @ 2.80GHz (96 x 2893)|
|Memory (System)|503.52GB (288.65GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: james3|
|OS|Linux x64 5.15.0-97-generic|
|CPUs|Intel(R) Xeon(R) Gold 6342 CPU @ 2.80GHz (96 x 2526)|
|Memory (System)|503.52GB (288.69GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: james3|
|OS|Linux x64 5.15.0-97-generic|
|CPUs|Intel(R) Xeon(R) Gold 6342 CPU @ 2.80GHz (96 x 2893)|
|Memory (System)|503.52GB (288.68GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: james3|
|OS|Linux x64 5.15.0-97-generic|
|CPUs|Intel(R) Xeon(R) Gold 6342 CPU @ 2.80GHz (96 x 2900)|
|Memory (System)|503.52GB (288.65GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593:30376534
py29gd2263:30784851
c4g48928:30535728
vscrp:30624060
2i9eh265:30646982
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
bf62j303:30968145
cppperfnew:30980852
8082a590:30961435
bg6jg535:30979844
78248357:30976997
ccp2r3:30958153
pythonait:30973460

```

</details>

**Comment by DonJayamanne** [comment]
Sorry you are running into this issue, and thank you for filing this issue.

Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by Jacfger** [comment]
I failed to replicate this bug after updating the extensions. The newer version might have fixed the problem, but also this bug has not been consistent from the beginning anyway. If I encountered it again I will re-open this issue with the related logs.
