### ISSUE TITLE
Iteractive window does not render error messages

### ISSUE THREAD

**Issue by sfo** [microsoft/vscode-jupyter#15438]
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Running code that generates an error in interactive window does not produce a proper error message output.
This is demonstrated in the following screenshot. While at first, everything is working properly, following errors are not rendered at all:

![vscode_python_missing_errormessage](https://github.com/microsoft/vscode-jupyter/assets/571497/8bf04cfd-595a-4e61-a294-f9877afcdaeb)

Executing erroneous python code via the prompt in the bottom part of the interactive window works properly, e.g. `assert False` gives the expected message:
```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[27], [line 1](vscode-notebook-cell:?execution_count=27&line=1)
----> [1](vscode-notebook-cell:?execution_count=27&line=1) assert False

AssertionError:
```

### VS Code Version

Version: 1.88.0-insider
Commit: 99a19815253d91900be5ec1016e0ecc7cc9a6950
Date: 2024-03-14T05:49:03.003Z
Electron: 28.2.6
ElectronBuildId: 27476517
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.7.9-100.fc38.x86_64 snap

### Jupyter Extension Version

v2024.3.2024032601 (pre-release)

### Jupyter logs

```shell
07:00:23.343 [info] Generated code for 29 = <ipython-input-29-4535399a4ad5> with 5 lines
07:00:23.507 [error] Failed to handle iopub message as a result of some comm message {
  header: {
    msg_id: '7d348e26-d2f7519966a3888d31c5a650_273254_362',
    msg_type: 'error',
    username: '<username>',
    session: '7d348e26-d2f7519966a3888d31c5a650',
    date: '2024-03-27T06:00:23.498408Z',
    version: '5.3'
  },
  parent_header: {
    date: '2024-03-27T06:00:23.372000Z',
    msg_id: 'b756e4a0-adda-432f-8f64-e8515033a5a3',
    msg_type: 'execute_request',
    session: 'f5c87c88-7334-4d70-bcf1-8829935e28f5',
    username: '602e0908-affe-4666-888e-cee19927f27e',
    version: '5.2'
  },
  metadata: {},
  content: {
    traceback: [
      '\x1B[0;31m---------------------------------------------------------------------------\x1B[0m',
      '\x1B[0;31mNameError\x1B[0m                                 Traceback (most recent call last)',
      'Cell \x1B[0;32mIn[26], line 5\x1B[0m\n' +
        '\x1B[1;32m      3\x1B[0m mu \x1B[38;5;241m=\x1B[39m y_pred[:, \x1B[38;5;241m0\x1B[39m, :]\n' +
        '\x1B[1;32m      4\x1B[0m sig \x1B[38;5;241m=\x1B[39m y_pred[:, \x1B[38;5;241m1\x1B[39m, :]\n' +
        '\x1B[0;32m----> 5\x1B[0m y_true[:, \x1B[43mtensorflow\x1B[49m\x1B[38;5;241m.\x1B[39mnewaxis]\n',
      "\x1B[0;31mNameError\x1B[0m: name 'tensorflow' is not defined"
    ],
    ename: 'NameError',
    evalue: "name 'tensorflow' is not defined"
  },
  idents: [
    <Buffer 6b 65 72 6e 65 6c 2e 37 34 61 30 32 31 32 32 2d 37 61 64 62 2d 34 39 65 62 2d 61 30 63 39 2d 35 34 32 62 36 62 61 66 64 36 37 39 2e 65 72 72 6f 72>
  ],
  buffers: [],
  channel: 'iopub'
} [Error: Illegal value for `line`
	at b.t (/var/lib/snapd/snap/code-insiders/1573/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:151:961)
	at Object.lineAt (/var/lib/snapd/snap/code-insiders/1573/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:151:90)
	at H_.parseStackTrace (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.2024032601-linux-x64/dist/extension.node.js:325:2666)
	at hd.handleError (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.2024032601-linux-x64/dist/extension.node.js:325:18950)
	at hd.handleIOPub (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.2024032601-linux-x64/dist/extension.node.js:325:9126)
	at hd.onKernelIOPubMessage (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.2024032601-linux-x64/dist/extension.node.js:325:7057)
	at k (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.2024032601-linux-x64/dist/extension.node.js:40:20361)
	at Object.p [as emit] (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.2024032601-linux-x64/dist/extension.node.js:40:20022)
	at i.emit (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.2024032601-linux-x64/dist/extension.node.js:40:18129)
	at wT.onIOPubMessage (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.2024032601-linux-x64/dist/extension.node.js:342:18603)
	at M (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.2024032601-linux-x64/dist/node_modules/@jupyterlab/services/lib/kernel/nonSerializingKernel.js:1:19784)
	at Object.d [as emit] (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.2024032601-linux-x64/dist/node_modules/@jupyterlab/services/lib/kernel/nonSerializingKernel.js:1:19461)
	at i.emit (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.2024032601-linux-x64/dist/node_modules/@jupyterlab/services/lib/kernel/nonSerializingKernel.js:1:17653)
	at n._handleMessage (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.2024032601-linux-x64/dist/node_modules/@jupyterlab/services/lib/kernel/nonSerializingKernel.js:11:96714)]
07:00:23.507 [error] Cell (index = 25) execution completed with errors (2). [Error: Illegal value for `line`
	at b.t (/var/lib/snapd/snap/code-insiders/1573/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:151:961)
	at Object.lineAt (/var/lib/snapd/snap/code-insiders/1573/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:151:90)
	at H_.parseStackTrace (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.2024032601-linux-x64/dist/extension.node.js:325:2666)
	at hd.handleError (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.2024032601-linux-x64/dist/extension.node.js:325:18950)
	at hd.handleIOPub (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.2024032601-linux-x64/dist/extension.node.js:325:9126)
	at hd.onKernelIOPubMessage (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.2024032601-linux-x64/dist/extension.node.js:325:7057)
	at k (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.2024032601-linux-x64/dist/extension.node.js:40:20361)
	at Object.p [as emit] (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.2024032601-linux-x64/dist/extension.node.js:40:20022)
	at i.emit (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.2024032601-linux-x64/dist/extension.node.js:40:18129)
	at wT.onIOPubMessage (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.2024032601-linux-x64/dist/extension.node.js:342:18603)
	at M (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.2024032601-linux-x64/dist/node_modules/@jupyterlab/services/lib/kernel/nonSerializingKernel.js:1:19784)
	at Object.d [as emit] (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.2024032601-linux-x64/dist/node_modules/@jupyterlab/services/lib/kernel/nonSerializingKernel.js:1:19461)
	at i.emit (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.2024032601-linux-x64/dist/node_modules/@jupyterlab/services/lib/kernel/nonSerializingKernel.js:1:17653)
	at n._handleMessage (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.2024032601-linux-x64/dist/node_modules/@jupyterlab/services/lib/kernel/nonSerializingKernel.js:11:96714)]
07:00:23.507 [warn] Cell completed with errors undefined
07:00:23.508 [info] Cell 25 completed in 0.127s (start: 1711519223380, end: 1711519223507)
07:00:23.510 [warn] Cell completed with errors [gd [Error]: name 'tensorflow' is not defined
	at r.execute (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.2024032601-linux-x64/dist/extension.node.js:327:4943)] {
  ename: 'NameError',
  evalue: "name 'tensorflow' is not defined",
  traceback: [
    '\x1B[0;31m---------------------------------------------------------------------------\x1B[0m',
    '\x1B[0;31mNameError\x1B[0m                                 Traceback (most recent call last)',
    'Cell \x1B[0;32mIn[26], line 5\x1B[0m\n' +
      '\x1B[1;32m      3\x1B[0m mu \x1B[38;5;241m=\x1B[39m y_pred[:, \x1B[38;5;241m0\x1B[39m, :]\n' +
      '\x1B[1;32m      4\x1B[0m sig \x1B[38;5;241m=\x1B[39m y_pred[:, \x1B[38;5;241m1\x1B[39m, :]\n' +
      '\x1B[0;32m----> 5\x1B[0m y_true[:, \x1B[43mtensorflow\x1B[49m\x1B[38;5;241m.\x1B[39mnewaxis]\n',
    "\x1B[0;31mNameError\x1B[0m: name 'tensorflow' is not defined"
  ]
}
```

### Coding Language and Runtime Version

Python 3.10.13

### Language Extension Version (if applicable)

v2024.3.10861011 (pre-release)

### Anaconda Version (if applicable)

conda 23.11.0

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
I couldn't actually get this to repro, it might depend on the version of ipykernel/Ipython, but pretty obvious where the bug is.

verification: Running a cell from a python file should display the error with the cell in the IW

```
# %%
assert False
```

**Comment by andreamah** [comment]
<img width="967" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/31675041/3dd1ea3f-a0c5-40fd-85bb-e02a618e1a75">

Not sure whether this is the correct verification?
