### ISSUE TITLE
Cell freezes on run (WSL, Docker, mamba)

### ISSUE THREAD

**Issue by aaronshenhao** [microsoft/vscode-jupyter#15662]
## Environment data

-   VS Code version: 1.89.0
-   Jupyter Extension version (available under the Extensions sidebar): v2024.4.0
-   Python Extension version (available under the Extensions sidebar): v2024.6.0
-   OS (Windows | Mac | Linux distro) and version: Microsoft Windows 11 Home Version 10.0.22631 Build 22631
-   Python and/or Anaconda version: Python 3.12.3, mamba 1.4.2, conda 23.3.1
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Mamba running on Docker
-   Jupyter server running: Remote

## Expected behaviour

Clicking run on a cell should run it, and the execution should complete in a reasonable time.

## Actual behaviour

The cell runs indefinitely or outputs the following error message:

```
Failed to connect to the remote Jupyter Server 'http://127.0.0.1:8888/'. Verify the server is running and reachable. ('_xsrf' argument missing from POST).
```

## Steps to reproduce:

1. Setup the environment by creating the mamba image using the mamba dockerfile, then run `docker compose up` in the project directory. It should bind to the current directory and set up a server at "127.0.0.1:8888".

**Mamba Dockerfile**
```dockerfile
FROM ubuntu:jammy

WORKDIR /workspace

RUN apt-get update && \
    apt-get install aria2 curl git -y && \
    curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh" && \
    bash Miniforge3-$(uname)-$(uname -m).sh -bfp /opt/miniforge3 && \
    rm Miniforge3-$(uname)-$(uname -m).sh

# Not really necessary
ENV PATH=/opt/miniforge3/bin:$PATH
RUN mamba init
```

**Dockerfile**
```dockerfile
FROM mamba

WORKDIR /app

COPY environment.yml .
RUN mamba env create -f environment.yml
```

**docker-compose.yaml**
```
services:
  jupyter:
    build: .
    ports:
      - 8888:8888
    volumes:
      - .:/app # Bind mount, changes will be reflected in host
    command:
      [
        "mamba",
        "run",
        "--no-capture-output", # For mamba/conda to show output
        "-n",
        "real-estate",
        "jupyter",
        "lab",
        "--ip=0.0.0.0", # So it listens on all interfaces, not just localhost
        "--port=8888",
        "--allow-root", # To allow running as root (prevent permission errors)
        "--NotebookApp.token=''", # To prevent Jupiter lab asking for tokens
        "--NotebookApp.password=''"
      ]
```

**environment.yml**
```yml
name: real-estate
channels:
  - conda-forge
dependencies:
  - folium
  - geopandas
  - jupyterlab
```

2. Create a new `.ipynb` file and with a single cell: `print("Hello world")`

3. Click run. When asked to select a kernal, click "Existing Jupyter Server", use `http://127.0.0.1:8888` as the remote server, and select the recommended kernal (should be in `/opt/miniforge3/envs/real-estate/bin...`).

Other details:
- The host machine should not have git, python, mamba or jupyter installed.
- Verify that it works as expected when accessed through the browser.
- Code is in WSL partition.
- Using Docker on Windows with WSL2 backend.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
2024-05-04 17:42:19 [I 2024-05-04 07:42:19.168 ServerApp] Kernel started: 356d67b6-803f-4beb-a109-3bd9eaf6feb8
2024-05-04 17:42:19 0.00s - Debugger warning: It seems that frozen modules are being used, which may
2024-05-04 17:42:19 0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
2024-05-04 17:42:19 0.00s - to python to disable frozen modules.
2024-05-04 17:42:19 0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
2024-05-04 17:42:19 [I 2024-05-04 07:42:19.647 ServerApp] Connecting to kernel 356d67b6-803f-4beb-a109-3bd9eaf6feb8.
2024-05-04 17:42:20 [I 2024-05-04 07:42:20.034 ServerApp] Connecting to kernel 7188db61-2215-4129-a12f-733cd183054a.
2024-05-04 17:42:21 [W 2024-05-04 07:42:21.010 ServerApp] 400 GET /api/contents/test.ipynb?type=notebook&content=1&hash=1&1714808540998 (172.18.0.1): Unreadable Notebook: /app/test.ipynb NotJSONError("Notebook does not appear to be JSON: ''")
2024-05-04 17:42:21 [W 2024-05-04 07:42:21.010 ServerApp] wrote error: 'Unreadable Notebook: /app/test.ipynb NotJSONError("Notebook does not appear to be JSON: \'\'")'
2024-05-04 17:42:21     Traceback (most recent call last):
2024-05-04 17:42:21       File "/opt/miniforge3/envs/real-estate/lib/python3.12/site-packages/tornado/web.py", line 1790, in _execute
2024-05-04 17:42:21         result = await result
2024-05-04 17:42:21                  ^^^^^^^^^^^^
2024-05-04 17:42:21       File "/opt/miniforge3/envs/real-estate/lib/python3.12/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
2024-05-04 17:42:21         return await out
2024-05-04 17:42:21                ^^^^^^^^^
2024-05-04 17:42:21       File "/opt/miniforge3/envs/real-estate/lib/python3.12/site-packages/jupyter_server/services/contents/handlers.py", line 154, in get
2024-05-04 17:42:21         model = await ensure_async(
2024-05-04 17:42:21                 ^^^^^^^^^^^^^^^^^^^
2024-05-04 17:42:21       File "/opt/miniforge3/envs/real-estate/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 198, in ensure_async
2024-05-04 17:42:21         result = await obj
2024-05-04 17:42:21                  ^^^^^^^^^
2024-05-04 17:42:21       File "/opt/miniforge3/envs/real-estate/lib/python3.12/site-packages/jupyter_server/services/contents/filemanager.py", line 919, in get
2024-05-04 17:42:21         model = await self._notebook_model(path, content=content, require_hash=require_hash)
2024-05-04 17:42:21                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-04 17:42:21       File "/opt/miniforge3/envs/real-estate/lib/python3.12/site-packages/jupyter_server/services/contents/filemanager.py", line 865, in _notebook_model
2024-05-04 17:42:21         nb, bytes_content = await self._read_notebook(
2024-05-04 17:42:21                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-04 17:42:21       File "/opt/miniforge3/envs/real-estate/lib/python3.12/site-packages/jupyter_server/services/contents/fileio.py", line 470, in _read_notebook
2024-05-04 17:42:21         raise HTTPError(
2024-05-04 17:42:21     tornado.web.HTTPError: HTTP 400: Bad Request (Unreadable Notebook: /app/test.ipynb NotJSONError("Notebook does not appear to be JSON: ''"))
```

</p>
</details>

**Comment by xzhbio** [comment]
@aaronshenhao i've got the same issue, have you already fix it?

**Comment by aaronshenhao** [comment]
@xzhbio Unfortunately, I have not been able to figure it out. I have a
slight suspicion that it could be caused by using Jupyter Labs instead of
the classic Jupyter Notebook, although I haven't verified this.

I provided a Docker image, so the problem should be theoretically
reproducible, if someone wants to figure it out.

**Comment by DonJayamanne** [comment]
@aaronshenhao 
Please can you try this with a password, currently you are trying to connect to a server without a password.
Would like to see if thats the case.

**Comment by aaronshenhao** [comment]
@DonJayamanne 
It worked when I set the password in `jupyter_lab_config.py`. However, it is quite a lengthy process to set the password, as it involves logging into the container in interactive mode, asking Jupyter to generate the config file, moving the file back to the host, generating a hashed password in the container, updating the config file, then updating the Docker code to copy over the config file.

Hopefully the password-less mode can be fixed. I'm glad the source of the problem has been found.

**Comment by DonJayamanne** [comment]
> Hopefully the password-less mode can be fixed. I'm glad the source of the problem has been found.

Closing for now.
