### ISSUE TITLE
Interactive window keeps executing same cell when encountering an import statement

### ISSUE THREAD

**Issue by sfo** [microsoft/vscode-jupyter#15689]
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

The interactive window keeps "reloading" the last cell that includes an `import` statement instead of running the currently selected cell.

Take this example:
```
# %%
import sys

# %%
print("Hello, World!")
```

Running the code cell-by-cell, the second cell will never execute. Instead, the first one is executed over and over again.
When running the whole script at once (either by "Run Above" or "Run Current File in Interactive Window"), it executes just fine. However, any subsequent execution of any cell results in the same behavior.

Furthermore, the interactive window does not react to "Clear All" and "Restart" commands.

The first part of the log shows the execution of the whole file, the second part (after unresponsive restart and close of interactive window) shows the cell-by-cell execution. 
Here you can clearly see, that jupyter keeps executing the same cell over and over again, no matter what cell got run actually.

When replacing the first cell with anything else but an import statement, this behavior does not occur.

I also append the "Window" Log, since this may give some more insights. At least, you can see that the "realCode" key refers to a value that reflects the content of the first cell, instead of the second one.

### VS Code Version

Version: 1.90.0-insider
Commit: 3028408922e78cc9ca15ee761372a7c0603fa375
Date: 2024-05-13T12:38:35.735Z
Electron: 29.3.1
ElectronBuildId: 9464424
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 6.8.8-200.fc39.x86_64 snap

### Jupyter Extension Version

v2024.4.2024042601 (pre-release)

### Jupyter logs

```shell
11:36:31.267 [info] Starting interactive window for resource '~/Documents/project/code/stuff/mwe/vscode_interactive.py' with controller '.jvsc74a57bd0475742735b2c0f8ffd8a182e92a93177e52aa8807bdbb63d79fe8f975540a35f./home/~/.anaconda3/envs/phd_model_py310_tf213/python./home/~/.anaconda3/envs/phd_model_py310_tf213/python.-m#ipykernel_launcher (Interactive)'
11:36:31.337 [info] Process Execution: ~/.anaconda3/envs/phd_model_py310_tf213/bin/python -m pip list
11:36:31.414 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd0475742735b2c0f8ffd8a182e92a93177e52aa8807bdbb63d79fe8f975540a35f./home/~/.anaconda3/envs/phd_model_py310_tf213/python./home/~/.anaconda3/envs/phd_model_py310_tf213/python.-m#ipykernel_launcher  (Python Path: ~/.anaconda3/envs/phd_model_py310_tf213/bin/python, Conda, phd_model_py310_tf213 (Python 3.10.14), 3.10.14) for '/Interactive-1.interactive' (disableUI=false)
11:36:31.420 [info] Process Execution: ~/.anaconda3/envs/phd_model_py310_tf213/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
11:36:31.430 [info] Process Execution: ~/.anaconda3/envs/phd_model_py310_tf213/bin/python -m ipykernel_launcher --f=/home/~/.local/share/jupyter/runtime/kernel-v2-61157iJmEqxt4es7z.json
    > cwd: ~/Documents/project
11:36:31.941 [info] Generated code for 1 = <ipython-input-1-792c8b1b29ec> with 2 lines
11:36:31.953 [info] Cell 1 completed in 0.002s (start: 1715679391950, end: 1715679391952)
11:36:31.954 [info] Generated code for 2 = <ipython-input-2-2b32baf42753> with 2 lines
11:36:31.971 [info] Cell 2 completed in 0.002s (start: 1715679391969, end: 1715679391971)
11:36:34.746 [info] Disposing kernel .jvsc74a57bd0475742735b2c0f8ffd8a182e92a93177e52aa8807bdbb63d79fe8f975540a35f./home/~/.anaconda3/envs/phd_model_py310_tf213/python./home/~/.anaconda3/envs/phd_model_py310_tf213/python.-m#ipykernel_launcher for notebook /Interactive-1.interactive due to selection of another kernel or closing of the notebook
11:36:34.746 [info] Dispose Kernel '/Interactive-1.interactive' associated with '~/Documents/project/code/stuff/mwe/vscode_interactive.py'
11:36:34.754 [info] Dispose Kernel '/Interactive-1.interactive' associated with '~/Documents/project/code/stuff/mwe/vscode_interactive.py'
11:36:36.794 [info] Starting interactive window for resource '~/Documents/project/code/stuff/mwe/vscode_interactive.py' with controller '.jvsc74a57bd0475742735b2c0f8ffd8a182e92a93177e52aa8807bdbb63d79fe8f975540a35f./home/~/.anaconda3/envs/phd_model_py310_tf213/python./home/~/.anaconda3/envs/phd_model_py310_tf213/python.-m#ipykernel_launcher (Interactive)'
11:36:36.933 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd0475742735b2c0f8ffd8a182e92a93177e52aa8807bdbb63d79fe8f975540a35f./home/~/.anaconda3/envs/phd_model_py310_tf213/python./home/~/.anaconda3/envs/phd_model_py310_tf213/python.-m#ipykernel_launcher  (Python Path: ~/.anaconda3/envs/phd_model_py310_tf213/bin/python, Conda, phd_model_py310_tf213 (Python 3.10.14), 3.10.14) for '/Interactive-1.interactive' (disableUI=false)
11:36:36.941 [info] Process Execution: ~/.anaconda3/envs/phd_model_py310_tf213/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
11:36:36.950 [info] Process Execution: ~/.anaconda3/envs/phd_model_py310_tf213/bin/python -m ipykernel_launcher --f=/home/~/.local/share/jupyter/runtime/kernel-v2-611574CfX26tXx6Dk.json
    > cwd: ~/Documents/project
11:36:37.459 [info] Generated code for 1 = <ipython-input-1-792c8b1b29ec> with 2 lines
11:36:37.470 [info] Cell 1 completed in 0.003s (start: 1715679397467, end: 1715679397470)
11:36:38.715 [info] Generated code for 2 = <ipython-input-2-792c8b1b29ec> with 2 lines
11:36:38.722 [info] Cell 1 completed in 0.002s (start: 1715679398720, end: 1715679398722)
```

### Window logs

<details>

```shell
2024-05-14 12:02:55.429 [debug] Open new interactive window: untitled:/Interactive-1.interactive vscode-interactive-input:/InteractiveInput-1
2024-05-14 12:02:55.486 [debug] Webview(f61e038a-9698-43f3-9a0f-ad8c065facb2): will update content
2024-05-14 12:02:55.512 [debug] _performCellEdits [{"resource":{"$mid":1,"fsPath":"/Interactive-1.interactive","external":"untitled:/Interactive-1.interactive","path":"/Interactive-1.interactive","scheme":"untitled"},"cellEdit":{"editType":5,"metadata":{"metadata":{"kernelspec":{"display_name":"phd_model_py310_tf213","language":"python","name":"python3"},"language_info":{"name":"python","version":"3.10.14"}}}}}]
2024-05-14 12:02:55.538 [debug] Webview(f61e038a-9698-43f3-9a0f-ad8c065facb2): webview ready
2024-05-14 12:02:55.576 [debug] New interactive window opened. Notebook editor id b29c15ec-3ef9-434c-9b0b-baf0df3baa48
2024-05-14 12:02:55.580 [debug] loadLocalResource - begin. requestUri=file:///home/stanley/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.4.0-linux-x64/dist/webviews/webview-side/ipywidgetsKernel/ipywidgetsKernel.js
2024-05-14 12:02:55.581 [debug] loadLocalResource - found resource to load. requestUri=file:///home/stanley/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.4.0-linux-x64/dist/webviews/webview-side/ipywidgetsKernel/ipywidgetsKernel.js, resourceToLoad=file:///home/stanley/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.4.0-linux-x64/dist/webviews/webview-side/ipywidgetsKernel/ipywidgetsKernel.js
2024-05-14 12:02:55.581 [debug] loadLocalResource - begin. requestUri=file:///home/stanley/.vscode-insiders/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/node_modules/%40vscode/jupyter-ipywidgets7/dist/ipywidgets.js
2024-05-14 12:02:55.581 [debug] loadLocalResource - found resource to load. requestUri=file:///home/stanley/.vscode-insiders/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/node_modules/%40vscode/jupyter-ipywidgets7/dist/ipywidgets.js, resourceToLoad=file:///home/stanley/.vscode-insiders/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/node_modules/%40vscode/jupyter-ipywidgets7/dist/ipywidgets.js
2024-05-14 12:02:55.581 [debug] loadLocalResource - begin. requestUri=file:///home/stanley/.vscode-insiders/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js
2024-05-14 12:02:55.581 [debug] loadLocalResource - found resource to load. requestUri=file:///home/stanley/.vscode-insiders/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js, resourceToLoad=file:///home/stanley/.vscode-insiders/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js
2024-05-14 12:02:55.581 [debug] loadLocalResource - begin. requestUri=file:///home/stanley/.vscode-insiders/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/client_renderer/preload.js
2024-05-14 12:02:55.582 [debug] loadLocalResource - found resource to load. requestUri=file:///home/stanley/.vscode-insiders/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/client_renderer/preload.js, resourceToLoad=file:///home/stanley/.vscode-insiders/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/client_renderer/preload.js
2024-05-14 12:02:55.583 [debug] _performCellEdits [{"resource":{"$mid":1,"fsPath":"/Interactive-1.interactive","external":"untitled:/Interactive-1.interactive","path":"/Interactive-1.interactive","scheme":"untitled"},"cellEdit":{"editType":1,"index":0,"count":0,"cells":[{"cellKind":1,"language":"markdown","source":"_Connecting to phd_model_py310_tf213 (Python 3.10.14)..._","metadata":{"isInteractiveWindowMessageCell":true},"internalMetadata":{},"outputs":[]}]}}]
2024-05-14 12:02:55.613 [debug] _performCellEdits [{"resource":{"$mid":1,"fsPath":"/Interactive-1.interactive","external":"untitled:/Interactive-1.interactive","path":"/Interactive-1.interactive","scheme":"untitled"},"cellEdit":{"editType":1,"index":1,"count":0,"cells":[{"cellKind":2,"language":"python","source":"import sys","metadata":{"interactiveWindowCellMarker":"# %%","interactive":{"uristring":"file:///home/stanley/Documents/project/code/stuff/mwe/vscode_interactive.py","lineIndex":0,"originalSource":"# %%\nimport sys\n"},"id":"a687621a-87f2-421b-b482-9a8202af99a1"},"internalMetadata":{},"outputs":[]}]}}]
2024-05-14 12:02:55.798 [debug] loadLocalResource - begin. requestUri=file:///var/lib/snapd/snap/code-insiders/1630/usr/share/code-insiders/resources/app/extensions/markdown-language-features/notebook-out/index.js
2024-05-14 12:02:55.798 [debug] loadLocalResource - found resource to load. requestUri=file:///var/lib/snapd/snap/code-insiders/1630/usr/share/code-insiders/resources/app/extensions/markdown-language-features/notebook-out/index.js, resourceToLoad=file:///var/lib/snapd/snap/code-insiders/1630/usr/share/code-insiders/resources/app/extensions/markdown-language-features/notebook-out/index.js
2024-05-14 12:02:55.808 [debug] loadLocalResource - begin. requestUri=file:///var/lib/snapd/snap/code-insiders/1630/usr/share/code-insiders/resources/app/extensions/ipynb/notebook-out/cellAttachmentRenderer.js
2024-05-14 12:02:55.809 [debug] loadLocalResource - found resource to load. requestUri=file:///var/lib/snapd/snap/code-insiders/1630/usr/share/code-insiders/resources/app/extensions/ipynb/notebook-out/cellAttachmentRenderer.js, resourceToLoad=file:///var/lib/snapd/snap/code-insiders/1630/usr/share/code-insiders/resources/app/extensions/ipynb/notebook-out/cellAttachmentRenderer.js
2024-05-14 12:02:55.809 [debug] loadLocalResource - begin. requestUri=file:///var/lib/snapd/snap/code-insiders/1630/usr/share/code-insiders/resources/app/extensions/markdown-math/notebook-out/katex.js
2024-05-14 12:02:55.809 [debug] loadLocalResource - found resource to load. requestUri=file:///var/lib/snapd/snap/code-insiders/1630/usr/share/code-insiders/resources/app/extensions/markdown-math/notebook-out/katex.js, resourceToLoad=file:///var/lib/snapd/snap/code-insiders/1630/usr/share/code-insiders/resources/app/extensions/markdown-math/notebook-out/katex.js
2024-05-14 12:02:55.809 [debug] loadLocalResource - begin. requestUri=file:///home/stanley/.vscode-insiders/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/client_renderer/markdown.js
2024-05-14 12:02:55.809 [debug] loadLocalResource - found resource to load. requestUri=file:///home/stanley/.vscode-insiders/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/client_renderer/markdown.js, resourceToLoad=file:///home/stanley/.vscode-insiders/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/client_renderer/markdown.js
2024-05-14 12:02:55.866 [debug] loadLocalResource - begin. requestUri=file:///var/lib/snapd/snap/code-insiders/1630/usr/share/code-insiders/resources/app/extensions/markdown-math/notebook-out/katex.min.css
2024-05-14 12:02:55.866 [debug] loadLocalResource - found resource to load. requestUri=file:///var/lib/snapd/snap/code-insiders/1630/usr/share/code-insiders/resources/app/extensions/markdown-math/notebook-out/katex.min.css, resourceToLoad=file:///var/lib/snapd/snap/code-insiders/1630/usr/share/code-insiders/resources/app/extensions/markdown-math/notebook-out/katex.min.css
2024-05-14 12:02:56.070 [debug] _performCellEdits [{"resource":{"$mid":1,"fsPath":"/Interactive-1.interactive","external":"untitled:/Interactive-1.interactive","path":"/Interactive-1.interactive","scheme":"untitled"},"cellEdit":{"editType":3,"index":1,"metadata":{"interactiveWindowCellMarker":"# %%","interactive":{"uristring":"file:///home/stanley/Documents/project/code/stuff/mwe/vscode_interactive.py","lineIndex":0,"originalSource":"# %%\nimport sys\n"},"id":"a687621a-87f2-421b-b482-9a8202af99a1","generatedCode":{"line":2,"endLine":3,"firstNonBlankLineIndex":1,"debuggerStartLine":1,"executionCount":1,"startOffset":0,"endOffset":17,"deleted":false,"code":"# %%\nimport sys\n","trimmedRightCode":"# %%\nimport sys\n","realCode":"# %%\nimport sys\n\n","runtimeLine":1,"runtimeFile":"<ipython-input-1-792c8b1b29ec>","id":"a687621a-87f2-421b-b482-9a8202af99a1","timestamp":1715680976068,"lineOffsetRelativeToIndexOfFirstLineInCell":0,"hasCellMarker":true}}}}]
2024-05-14 12:02:56.074 [debug] NotebookExecution#ctor untitled:/Interactive-1.interactive
2024-05-14 12:02:56.074 [debug] CellExecution#ctor untitled:/Interactive-1.interactive, 1
2024-05-14 12:02:56.075 [debug] CellExecution#confirm untitled:/Interactive-1.interactive, 1
2024-05-14 12:02:56.078 [debug] _performTextEdits [{"resource":{"$mid":1,"external":"vscode-notebook-cell:/Interactive-1.interactive#W0sdW50aXRsZWQ%3D","path":"/Interactive-1.interactive","scheme":"vscode-notebook-cell","fragment":"W0sdW50aXRsZWQ="},"textEdit":{"text":"Connected to phd_model_py310_tf213 (Python 3.10.14)","range":{"startLineNumber":1,"startColumn":1,"endLineNumber":2,"endColumn":1}},"versionId":2}]
2024-05-14 12:02:56.079 [error] Error: vscode-notebook-cell:/Interactive-1.interactive#W0sdW50aXRsZWQ%3D has changed in the meantime
    at o.apply (vscode-file://vscode-app/var/lib/snapd/snap/code-insiders/1630/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:808:4118)
    at async g.o (vscode-file://vscode-app/var/lib/snapd/snap/code-insiders/1630/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2200:24775)
    at async g.perform (vscode-file://vscode-app/var/lib/snapd/snap/code-insiders/1630/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2200:24351)
    at async m.apply (vscode-file://vscode-app/var/lib/snapd/snap/code-insiders/1630/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2200:26103)
2024-05-14 12:02:56.079 [warning] IGNORING workspace edit: Error: vscode-notebook-cell:/Interactive-1.interactive#W0sdW50aXRsZWQ%3D has changed in the meantime
2024-05-14 12:02:56.080 [debug] CellExecution#updateExecution untitled:/Interactive-1.interactive, 1, [ExecutionState]
2024-05-14 12:02:56.081 [debug] CellExecution#updateExecution untitled:/Interactive-1.interactive, 1, [ExecutionState]
2024-05-14 12:02:56.082 [debug] CellExecution#updateExecution untitled:/Interactive-1.interactive, 1, [ExecutionState]
2024-05-14 12:02:56.083 [debug] CellExecution#updateExecution untitled:/Interactive-1.interactive, 1, [ExecutionState]
2024-05-14 12:02:56.083 [debug] CellExecution#updateExecution untitled:/Interactive-1.interactive, 1, [Output]
2024-05-14 12:03:05.817 [debug] _performCellEdits [{"resource":{"$mid":1,"fsPath":"/Interactive-1.interactive","external":"untitled:/Interactive-1.interactive","path":"/Interactive-1.interactive","scheme":"untitled"},"cellEdit":{"editType":1,"index":2,"count":0,"cells":[{"cellKind":2,"language":"python","source":"print(\"Hello, World!\")","metadata":{"interactiveWindowCellMarker":"# %%","interactive":{"uristring":"file:///home/stanley/Documents/project/code/stuff/mwe/vscode_interactive.py","lineIndex":3,"originalSource":"# %%\nprint(\"Hello, World!\")\n"},"id":"87ff3831-0e3f-432e-b640-1e56565a7063"},"internalMetadata":{},"outputs":[]}]}}]
2024-05-14 12:03:05.820 [debug] _performCellEdits [{"resource":{"$mid":1,"fsPath":"/Interactive-1.interactive","external":"untitled:/Interactive-1.interactive","path":"/Interactive-1.interactive","scheme":"untitled"},"cellEdit":{"editType":3,"index":1,"metadata":{"interactiveWindowCellMarker":"# %%","interactive":{"uristring":"file:///home/stanley/Documents/project/code/stuff/mwe/vscode_interactive.py","lineIndex":0,"originalSource":"# %%\nimport sys\n"},"id":"a687621a-87f2-421b-b482-9a8202af99a1","generatedCode":{"line":2,"endLine":3,"firstNonBlankLineIndex":1,"debuggerStartLine":1,"executionCount":2,"startOffset":0,"endOffset":17,"deleted":false,"code":"# %%\nimport sys\n","trimmedRightCode":"# %%\nimport sys\n","realCode":"# %%\nimport sys\n\n","runtimeLine":1,"runtimeFile":"<ipython-input-2-792c8b1b29ec>","id":"a687621a-87f2-421b-b482-9a8202af99a1","timestamp":1715680985818,"lineOffsetRelativeToIndexOfFirstLineInCell":0,"hasCellMarker":true}}}}]
2024-05-14 12:03:05.823 [debug] NotebookExecution#ctor untitled:/Interactive-1.interactive
2024-05-14 12:03:05.824 [debug] CellExecution#ctor untitled:/Interactive-1.interactive, 1
2024-05-14 12:03:05.827 [debug] CellExecution#confirm untitled:/Interactive-1.interactive, 1
2024-05-14 12:03:05.840 [debug] CellExecution#updateExecution untitled:/Interactive-1.interactive, 1, [ExecutionState]
2024-05-14 12:03:05.843 [debug] CellExecution#updateExecution untitled:/Interactive-1.interactive, 1, [ExecutionState]
2024-05-14 12:03:05.844 [debug] CellExecution#updateExecution untitled:/Interactive-1.interactive, 1, [ExecutionState]
2024-05-14 12:03:05.846 [debug] CellExecution#updateExecution untitled:/Interactive-1.interactive, 1, [ExecutionState]
2024-05-14 12:03:05.847 [debug] CellExecution#updateExecution untitled:/Interactive-1.interactive, 1, [Output]
2024-05-14 12:03:10.889 [debug] _performCellEdits [{"resource":{"$mid":1,"fsPath":"/Interactive-1.interactive","external":"untitled:/Interactive-1.interactive","path":"/Interactive-1.interactive","scheme":"untitled"},"cellEdit":{"editType":1,"index":2,"count":0,"cells":[{"cellKind":2,"language":"python","source":"print(\"Hello, World!\")","metadata":{"interactiveWindowCellMarker":"# %%","interactive":{"uristring":"file:///home/stanley/Documents/project/code/stuff/mwe/vscode_interactive.py","lineIndex":3,"originalSource":"# %%\nprint(\"Hello, World!\")\n"},"id":"f17b33f7-37ec-4927-bb21-a5496b779eb1"},"internalMetadata":{},"outputs":[]}]}}]
2024-05-14 12:03:10.890 [debug] _performCellEdits [{"resource":{"$mid":1,"fsPath":"/Interactive-1.interactive","external":"untitled:/Interactive-1.interactive","path":"/Interactive-1.interactive","scheme":"untitled"},"cellEdit":{"editType":3,"index":1,"metadata":{"interactiveWindowCellMarker":"# %%","interactive":{"uristring":"file:///home/stanley/Documents/project/code/stuff/mwe/vscode_interactive.py","lineIndex":0,"originalSource":"# %%\nimport sys\n"},"id":"a687621a-87f2-421b-b482-9a8202af99a1","generatedCode":{"line":2,"endLine":3,"firstNonBlankLineIndex":1,"debuggerStartLine":1,"executionCount":3,"startOffset":0,"endOffset":17,"deleted":false,"code":"# %%\nimport sys\n","trimmedRightCode":"# %%\nimport sys\n","realCode":"# %%\nimport sys\n\n","runtimeLine":1,"runtimeFile":"<ipython-input-3-792c8b1b29ec>","id":"a687621a-87f2-421b-b482-9a8202af99a1","timestamp":1715680990890,"lineOffsetRelativeToIndexOfFirstLineInCell":0,"hasCellMarker":true}}}}]
2024-05-14 12:03:10.892 [debug] NotebookExecution#ctor untitled:/Interactive-1.interactive
2024-05-14 12:03:10.892 [debug] CellExecution#ctor untitled:/Interactive-1.interactive, 1
2024-05-14 12:03:10.894 [debug] CellExecution#confirm untitled:/Interactive-1.interactive, 1
2024-05-14 12:03:10.896 [debug] CellExecution#updateExecution untitled:/Interactive-1.interactive, 1, [ExecutionState]
2024-05-14 12:03:10.897 [debug] CellExecution#updateExecution untitled:/Interactive-1.interactive, 1, [ExecutionState]
2024-05-14 12:03:10.898 [debug] CellExecution#updateExecution untitled:/Interactive-1.interactive, 1, [ExecutionState]
2024-05-14 12:03:10.899 [debug] CellExecution#updateExecution untitled:/Interactive-1.interactive, 1, [ExecutionState]
2024-05-14 12:03:10.900 [debug] CellExecution#updateExecution untitled:/Interactive-1.interactive, 1, [Output]
```

</details>

### Coding Language and Runtime Version

Python 3.10.14

### Language Extension Version (if applicable)

Python v2024.7.11341012 (pre-release)

### Anaconda Version (if applicable)

mamba 1.5.1 / conda 23.5.2

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
this should be fixed in the latest insiders. Can you try updating and check if it still an issue?

**Comment by sfo** [comment]
It is working again, as of version

Version: 1.90.0-insider
Commit: bbc4ba1eff648ee542972589216f211b7a6a08f2
Date: 2024-05-14T05:47:50.971Z
Electron: 29.3.1
ElectronBuildId: 9464424
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 6.8.9-200.fc39.x86_64 snap
