### ISSUE TITLE
nglview not working with vscode-jupyter

### ISSUE THREAD

**Issue by gcrth** [microsoft/vscode-jupyter#15757]
Related issue https://github.com/nglviewer/nglview/issues/1085.

```
pip install nglview==3.1.0
```
```
import nglview
view = nglview.show_pdbid("3pqr")  # load "3pqr" from RCSB PDB and display viewer widget
view
```
The example above works in jupyter notebook, but it does not work in vscode. Changing version of nglview and ipywidgets does not fix the problem.

The important part of the log is 
```
Failed to load model class 'ColormakerRegistryModel' from module 'nglview-js-widgets'
Error: No version of module nglview-js-widgets is registered
```
nglview-js-widgets is in the cdn https://cdn.jsdelivr.net/npm/nglview-js-widgets/.
jupyter.widgetScriptSources has been configured per https://github.com/microsoft/vscode-jupyter/wiki/IPyWidget-Support-in-VS-Code-Python.
It seems that something goes wrong when loading the module.

**Comment by nightroxide** [comment]
Same issue for me

**Comment by DonJayamanne** [comment]
There seems to be some change in nglview that seems to be causing this issue in VS code.
Sorry for the trouble, will try to get to the bottom of this.
Please can you try installing an older version of nglview and see if that makes a difference.

**Comment by 4doom4** [comment]
@DonJayamanne I tried it with 2.7.7 and get the same outcome. Maybe this trace helps (is from 3.1.2 nglview though)

[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'ColormakerRegistryModel' from module 'nglview-js-widgets'
Error: No version of module nglview-js-widgets is registered
    at ph.loadClass (https://file+.vscode-resource.vscode-cdn.net/Users/xxxxx/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.18/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4099813)
    at ph.loadClass (https://file+.vscode-resource.vscode-cdn.net/Users/xxxxx/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.18/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4403287)
    at ph.loadModelClass (https://file+.vscode-resource.vscode-cdn.net/Users/xxxxx/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.18/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4097773)
    at ph._make_model (https://file+.vscode-resource.vscode-cdn.net/Users/xxxxx/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.18/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4094616)
    at ph.new_model (https://file+.vscode-resource.vscode-cdn.net/Users/xxxxx/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.18/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4092246)
    at ph.handle_comm_open (https://file+.vscode-resource.vscode-cdn.net/Users/xxxxx/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.18/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4091039)
    at https://file+.vscode-resource.vscode-cdn.net/Users/xxxxx/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.18/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4402511
    at n._handleCommOpen (https://file+.vscode-resource.vscode-cdn.net/Users/xxxxx/.vscode/extensions/ms-toolsai.jupyter-2024.5.0-darwin-arm64/dist/webviews/webview-side/ipywidgetsKernel/ipywidgetsKernel.js:3:80955)
    at async n._handleMessage (https://file+.vscode-resource.vscode-cdn.net/Users/xxxxx/.vscode/extensions/ms-toolsai.jupyter-2024.5.0-darwin-arm64/dist/webviews/webview-side/ipywidgetsKernel/ipywidgetsKernel.js:3:82830)

**Comment by LuhuanWu** [comment]
same issue here

**Comment by laisFK** [comment]
Helo, I have the same problem in VSC, please someone found a solution? Thanks

**Comment by 4doom4** [comment]
> There seems to be some change in nglview that seems to be causing this issue in VS code. Sorry for the trouble, will try to get to the bottom of this. Please can you try installing an older version of nglview and see if that makes a difference. You might need to re-load VS Code after doing that.

I tried many different versions and got version 3.0.8 (installed via conda conda-forge::nglview=3.0.8) to work with VScode on linux version 1.91.1

Hope this helps

**Comment by DonJayamanne** [comment]
This seems to be caused by some upstream issue in nglview, I haven't had a chance to identify the root cause as of yet.

**Comment by hainm** [comment]
There is a change in NGL (which is being used by nglview) in the way it is packaged. The change happened after nglview 3.8. But nglview works fine with notebook (using lab) and lab.

**Comment by DonJayamanne** [comment]
@hainm its still failing at my end in Jupyter lab
This is with the latest version of nglview


![Image](https://github.com/user-attachments/assets/54521cb5-29e6-4947-b5c1-dd15f198ef02)

**Comment by hainm** [comment]
Can you please try install nglview via conda/mamba from conda-forget channel? 

I am surprised that it doesn't work for you since I tried myself before publishing the package. Cheers

**Comment by hainm** [comment]
@DonJayamanne 
I've tried again with my mac:
<img width="1477" alt="image" src="https://github.com/user-attachments/assets/d481b558-6d51-40c8-b5a7-649307f280f6">

`lab 4.2.4`

Exact steps:
```
mamba create -n test python=3.11 -c conda-forge -y
source activate test
mamba install jupyterlab -c conda-forge -y
mamba install nglview=3.1.2 -c conda-forge -y
jupyter-lab
```

**Comment by MarcSkovMadsen** [comment]
There is the same problem for Bokeh/ Panel. See https://github.com/bokeh/jupyter_bokeh/issues/201

**Comment by invemichele** [comment]
@DonJayamanne 
With `v2024.8.0` no matter the nglview version I try, I always get the error in the OP.

Reverting back to `v2024.7.0` and nglview==3.0.8 works

**Comment by DonJayamanne** [comment]
@invemichele You are running into https://github.com/microsoft/vscode-jupyter/issues/16008

**Comment by OWissett** [comment]
I am also still experiencing this issue, too!

**Comment by nate-russell** [comment]
Same issue for me as well.

**Comment by RestartDK** [comment]
I can confirm when using `pip` when I downgraded to `nglview=3.0.8` it worked locally on my vscode jupyter notebook.

**Comment by DonJayamanne** [comment]
Closing in favor of upstream issue https://github.com/nglviewer/ngl/issues/1014

**Comment by hai-schrodinger** [comment]
@DonJayamanne I don't think two issues you quoted relate to this issue. Nglview is still working fine in jupyterlab. So it makes sense it should work in vscode too?

**Comment by janhurst** [comment]
setting this as closed implies a resolution... surely leaving open (or some other state) pending something upstream better reflects the state of the issue?

**Comment by DonJayamanne** [comment]
Closing this issue doesn't mean its fixed, it just means that there's nothing that can be done in this repo to resolve this issue.
Here's an example of how a similar issue was closed due to the root cause lying else where https://github.com/jupyter-widgets/ipywidgets/issues/3878

Leaving it open implies that the issue lies in this reop and it will be looked into, that just leads to future confusion and the like.

**Comment by DonJayamanne** [comment]
@hai-schrodinger nglview doesn't work in VS Code after 3.0.8 as you pointed out.
https://github.com/nglviewer/ngl/issues/1014#issuecomment-2231303813

based on my understanding thats the problem, see here (from the above issue)
Happy to re-open if you can clarify this comment.
![Image](https://github.com/user-attachments/assets/a7809e6c-17b7-483c-8eb6-aa3ba079ef14)

**Comment by DonJayamanne** [comment]
@janhurst 
I'm closing this issue as the problem doesn't lie in the Jupyter extension.
Leaving it open leads to the assumption that this is being actively looked at, and the fact that its a problem with this repo when it isn't
Here's one example of closing such issues when its not related https://github.com/jupyter-widgets/ipywidgets/issues/3878

But currently waiting for a clarification, if after that we can confirm its a problem in this repo I'm happy to reopen this,

**Comment by hai-schrodinger** [comment]
Hi,

Yes, it’s coincidence and it might the cause.

3.0.8 works for both vscode and jupyterlab
3.0.10 works for jupyterlab but not for vscode.
So it means there is something in vscode that doesn’t follow jupyter (lab)

Cheers
Hai

**Comment by hainm** [comment]
Thank you. That makes sense. Then I think it’s good to close this.

Best

**Comment by hai-schrodinger** [comment]
Thanks Don.

Does vscode have a plan to use lab instead?
(Just curious since I am going to fix nglview anyway, if it’s possible)

Hai

**Comment by DonJayamanne** [comment]
> Thanks Don. Does vscode have a plan to use lab instead? 

Unfortunately not at this stage, simply because the widgets placed in `nbextensions` folder  is still a supported by IPyWidgets

**Comment by hainm** [comment]
Guys,

Please try latest version, v3.1.4
`pip3 install nglview==3.1.4`
(conda version will be released later via conda-forge)

**Comment by hainm** [comment]
> ~Closing in favor of upstream issue [nglviewer/ngl#1014](https://github.com/nglviewer/ngl/issues/1014) 

It's indeed an issue with `NGL` (2.2.2). I have to distribute two versions for nbclassic (and VSCode; use NGL 2.1.1) and for jupyterlab (use NGL 2.2.2)

**Comment by DonJayamanne** [comment]
Thanks for looking into this and fixing it
