### ISSUE TITLE
Jupyter notebook current working directory is the $HOME directory, rather than the file directory or the workspace directory.

### ISSUE THREAD

**Issue by kheuton** [microsoft/vscode-jupyter#15755]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Recently my notebooks using relative imports stopped working. When investigating why, I found that the notebooks were working inside my home directory, not the file directory or workspace directory (the same, in this case). These same imports worked within the last few weeks.

What I expected to happen:
Relative imports should work without modifying the path when both the notebook and the module being imported are in the same directory, and that directory is also the workspace root.

What actually happened:
Relative imports failed due to not finding the module

### VS Code Version

Version: 1.90.0 (user setup) Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573 Date: 2024-06-04T19:33:54.889Z Electron: 29.4.0 ElectronBuildId: 9593362 Chromium: 122.0.6261.156 Node.js: 20.9.0 V8: 12.2.281.27-electron.0 OS: Windows_NT x64 10.0.22631

### Jupyter Extension Version

v2024.5.0

### Jupyter logs

```shell
11:57:23.971 [warn] Cell completed with errors hd [Error]: No module named 'plotting_funcs'
    at r.execute (/cluster/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.5.0-linux-x64/dist/extension.node.js:307:4958)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  ename: 'ModuleNotFoundError',
  evalue: "No module named 'plotting_funcs'",
  traceback: [
    '\x1B[0;31m---------------------------------------------------------------------------\x1B[0m',
    '\x1B[0;31mModuleNotFoundError\x1B[0m                       Traceback (most recent call last)',
    'Cell \x1B[0;32mIn[4], line 6\x1B[0m\n' +
      "\x1B[1;32m      2\x1B[0m get_ipython()\x1B[38;5;241m.\x1B[39mrun_line_magic(\x1B[38;5;124m'\x1B[39m\x1B[38;5;124mautoreload\x1B[39m\x1B[38;5;124m'\x1B[39m, \x1B[38;5;124m'\x1B[39m\x1B[38;5;124m2\x1B[39m\x1B[38;5;124m'\x1B[39m)\n" +
      '\x1B[1;32m      4\x1B[0m \x1B[38;5;28;01mimport\x1B[39;00m \x1B[38;5;21;01mscipy\x1B[39;00m\n' +
      '\x1B[0;32m----> 6\x1B[0m \x1B[38;5;28;01mfrom\x1B[39;00m \x1B[38;5;21;01mplotting_funcs\x1B[39;00m \x1B[38;5;28;01mimport\x1B[39;00m sample_and_plot\n',
    "\x1B[0;31mModuleNotFoundError\x1B[0m: No module named 'plotting_funcs'"
  ]
}
```

### Coding Language and Runtime Version

Python 3.11.7

### Language Extension Version (if applicable)

v2024.8.0

### Anaconda Version (if applicable)

mamba 1.4.2 conda 23.3.1

### Running Jupyter locally or remotely?

Remote

**Comment by vishu-tyagi** [comment]
I think I'm facing something related to this. Earlier, I could start the jupyter server from any directory, and `os.getcwd()` would return the path where the jupyter notebook is saved (which is the desired behavior, and relative imports will work). However, now `os.getcwd()` outputs the directory where the jupyter server was started (so, you'd have to cd into your notebook directory to make relative imports work).

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel (use the command `Jupyter: Show Output` to get to the logs).

**Comment by kheuton** [comment]
Here's the logs:

```Visual Studio Code (1.91.1, tunnel, desktop)
Jupyter Extension Version: 2024.6.0.
Python Extension Version: 2024.10.0.
Pylance Extension Version: 2024.7.1.
Platform: linux (x64).
Workspace folder ~/code/NLP-for-ORI, Home = /cluster/home/kheuto01
11:07:42.059 [warn] Exception while attempting zmq : /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /cluster/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/dist/node_modules/zeromq/prebuilds/linux-x64/node.napi.glibc.node)
11:07:42.060 [warn] Exception while attempting zmq (fallback) : /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /cluster/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/dist/node_modules/zeromqold/prebuilds/linux-x64/node.napi.glibc.node)
11:07:46.366 [warn] Disposing old controller startUsingPythonInterpreter:'.jvsc74a57bd0a304f1d4008e0f20ff3a8a077570ba29fe9fcbeb1e88d6b88d19f0e4e4c3be5b.d:\anaconda3\python.exe.d:\anaconda3\python.exe.-m#ipykernel_launcher' for view = 'jupyter-notebook'
11:07:46.367 [warn] Disposing old controller startUsingPythonInterpreter:'.jvsc74a57bd0a304f1d4008e0f20ff3a8a077570ba29fe9fcbeb1e88d6b88d19f0e4e4c3be5b.d:\anaconda3\python.exe.d:\anaconda3\python.exe.-m#ipykernel_launcher (Interactive)' for view = 'interactive'
11:07:55.621 [info] Process Execution: /cluster/tufts/hugheslab/~/mambaforge/envs/pip_k2_tf/bin/python -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
11:07:55.627 [info] Process Execution: /cluster/tufts/hugheslab/~/mambaforge/envs/pip_k2_tf/bin/python -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
11:07:55.755 [info] Process Execution: /cluster/tufts/hugheslab/~/mambaforge/envs/pip_k2_tf/bin/python -m jupyter kernelspec --version
11:09:12.104 [warn] Disposing old controller startUsingPythonInterpreter:'.jvsc74a57bd0b83ee439a2684417ed34826a0a27762c20d85a86ee4e8f0c25ef4ac939ee13a7./cluster/tufts/hugheslab/~/miniconda3/envs/hashpy2/python./cluster/tufts/hugheslab/~/miniconda3/envs/hashpy2/python.-m#ipykernel_launcher' for view = 'jupyter-notebook'
11:09:12.104 [warn] Disposing old controller startUsingPythonInterpreter:'.jvsc74a57bd0b83ee439a2684417ed34826a0a27762c20d85a86ee4e8f0c25ef4ac939ee13a7./cluster/tufts/hugheslab/~/miniconda3/envs/hashpy2/python./cluster/tufts/hugheslab/~/miniconda3/envs/hashpy2/python.-m#ipykernel_launcher (Interactive)' for view = 'interactive'
11:09:26.996 [info] Starting Kernel (Python Path: /cluster/tufts/hugheslab/~/mambaforge/envs/nlp4ori/bin/python, Conda, 3.11.9) for '~/code/NLP-for-ORI/notebooks/BERTDemo.ipynb' (disableUI=true)
11:09:27.001 [info] Starting Jupyter Server
11:09:27.019 [info] Process Execution: /cluster/tufts/hugheslab/~/mambaforge/envs/pip_k2_tf/bin/python -m jupyter notebook --no-browser --NotebookApp.iopub_data_rate_limit=10000000000.0 --KernelManager.autorestart=False 
11:09:31.867 [info] Process Execution: /cluster/tufts/hugheslab/~/mambaforge/envs/nlp4ori/bin/python -m pip list
11:09:40.874 [info] Process Execution: /cluster/tufts/hugheslab/~/mambaforge/envs/pip_k2_tf/bin/python /cluster/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/pythonFiles/vscode_datascience_helpers/getServerInfo.py
11:09:40.957 [info] Process Execution: /cluster/tufts/hugheslab/~/mambaforge/envs/pip_k2_tf/bin/python /cluster/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/pythonFiles/vscode_datascience_helpers/getServerInfo.py
11:09:41.068 [info] Process Execution: /cluster/tufts/hugheslab/~/mambaforge/envs/pip_k2_tf/bin/python /cluster/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/pythonFiles/vscode_datascience_helpers/getServerInfo.py
11:09:43.221 [info] Check & install missing Kernel dependencies for /cluster/tufts/hugheslab/~/mambaforge/envs/nlp4ori/bin/python, ui.disabled=true for resource '~/code/NLP-for-ORI/notebooks/BERTDemo.ipynb'
11:09:43.226 [info] Process Execution: /cluster/tufts/hugheslab/~/mambaforge/envs/nlp4ori/bin/python -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
11:09:45.349 [info] RegisterKernel for .jvsc74a57bd06f6fef4eae6ba61f78857a926e65c7e18cf19c3c02bbc8746561a98c40cafa9a./cluster/tufts/hugheslab/~/mambaforge/envs/nlp4ori/python./cluster/tufts/hugheslab/~/mambaforge/envs/nlp4ori/python.-m#ipykernel_launcher into ~/.vscode-server/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/temp/jupyter/kernels/python3119jvsc74a57bd06f6fef4eae6ba61f78857a926e65c7e18cf19c3c02bbc8746561a98c40cafa9a/kernel.json
11:09:46.398 [info] http://localhost:8888: Kernel started: aeef6648-8fa9-4ce1-ae43-c20dbbf8ebb2
11:09:54.423 [info] Started session for kernel startUsingPythonInterpreter:.jvsc74a57bd06f6fef4eae6ba61f78857a926e65c7e18cf19c3c02bbc8746561a98c40cafa9a./cluster/tufts/hugheslab/~/mambaforge/envs/nlp4ori/python./cluster/tufts/hugheslab/~/mambaforge/envs/nlp4ori/python.-m#ipykernel_launcher
11:09:54.819 [info] Kernel successfully started
11:09:54.837 [info] Process Execution: /cluster/tufts/hugheslab/~/mambaforge/envs/nlp4ori/bin/python /cluster/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/pythonFiles/printJupyterDataDir.py
11:20:41.776 [info] Attempting to start a server because of preload conditions ...
11:20:54.653 [info] Starting Kernel (Python Path: /cluster/tufts/hugheslab/~/mambaforge/envs/nlp4ori/bin/python, Conda, 3.11.9) for '~/code/NLP-for-ORI/notebooks/InvestigateData.ipynb' (disableUI=true)
11:20:54.653 [info] Check & install missing Kernel dependencies for /cluster/tufts/hugheslab/~/mambaforge/envs/nlp4ori/bin/python, ui.disabled=true for resource '~/code/NLP-for-ORI/notebooks/InvestigateData.ipynb'
11:21:01.276 [info] Process Execution: /cluster/tufts/hugheslab/~/mambaforge/envs/nlp4ori/bin/python -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
11:21:01.281 [info] Process Execution: /cluster/tufts/hugheslab/~/mambaforge/envs/nlp4ori/bin/python -m pip list
11:21:03.004 [info] http://localhost:8888: Kernel started: 86a0f328-954b-4adf-a54f-6a30fa5591be
11:21:07.717 [info] Started session for kernel startUsingPythonInterpreter:.jvsc74a57bd06f6fef4eae6ba61f78857a926e65c7e18cf19c3c02bbc8746561a98c40cafa9a./cluster/tufts/hugheslab/~/mambaforge/envs/nlp4ori/python./cluster/tufts/hugheslab/~/mambaforge/envs/nlp4ori/python.-m#ipykernel_launcher
11:21:08.060 [info] Kernel successfully started
11:22:02.392 [warn] Cell completed with errors Qd [Error]: [Errno 2] No such file or directory: './data/Data.xlsx'
    at n.execute (/cluster/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/dist/extension.node.js:297:4958)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  ename: 'FileNotFoundError',
  evalue: "[Errno 2] No such file or directory: './data/Data.xlsx'",
  traceback: [
    '\x1B[0;31m---------------------------------------------------------------------------\x1B[0m',
    '\x1B[0;31mFileNotFoundError\x1B[0m                         Traceback (most recent call last)',
    'Cell \x1B[0;32mIn[2], line 2\x1B[0m\n' +
      '\x1B[1;32m      1\x1B[0m \x1B[38;5;66;03m# read excel file\x1B[39;00m\n' +
      "\x1B[0;32m----> 2\x1B[0m \x1B[43mpd\x1B[49m\x1B[38;5;241;43m.\x1B[39;49m\x1B[43mread_excel\x1B[49m\x1B[43m(\x1B[49m\x1B[38;5;124;43m'\x1B[39;49m\x1B[38;5;124;43m./data/Data.xlsx\x1B[39;49m\x1B[38;5;124;43m'\x1B[39;49m\x1B[43m)\x1B[49m\n",
    'File \x1B[0;32m/cluster/tufts/hugheslab/~/mambaforge/envs/nlp4ori/lib/python3.11/site-packages/pandas/io/excel/_base.py:495\x1B[0m, in \x1B[0;36mread_excel\x1B[0;34m(io, sheet_name, header, names, index_col, usecols, dtype, engine, converters, true_values, false_values, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, parse_dates, date_parser, date_format, thousands, decimal, comment, skipfooter, storage_options, dtype_backend, engine_kwargs)\x1B[0m\n' +
      '\x1B[1;32m    493\x1B[0m \x1B[38;5;28;01mif\x1B[39;00m \x1B[38;5;129;01mnot\x1B[39;00m \x1B[38;5;28misinstance\x1B[39m(io, ExcelFile):\n' +
      '\x1B[1;32m    494\x1B[0m     should_close \x1B[38;5;241m=\x1B[39m \x1B[38;5;28;01mTrue\x1B[39;00m\n' +
      '\x1B[0;32m--> 495\x1B[0m     io \x1B[38;5;241m=\x1B[39m \x1B[43mExcelFile\x1B[49m\x1B[43m(\x1B[49m\n' +
      '\x1B[1;32m    496\x1B[0m \x1B[43m        \x1B[49m\x1B[43mio\x1B[49m\x1B[43m,\x1B[49m\n' +
      '\x1B[1;32m    497\x1B[0m \x1B[43m        \x1B[49m\x1B[43mstorage_options\x1B[49m\x1B[38;5;241;43m=\x1B[39;49m\x1B[43mstorage_options\x1B[49m\x1B[43m,\x1B[49m\n' +
      '\x1B[1;32m    498\x1B[0m \x1B[43m        \x1B[49m\x1B[43mengine\x1B[49m\x1B[38;5;241;43m=\x1B[39;49m\x1B[43mengine\x1B[49m\x1B[43m,\x1B[49m\n' +
      '\x1B[1;32m    499\x1B[0m \x1B[43m        \x1B[49m\x1B[43mengine_kwargs\x1B[49m\x1B[38;5;241;43m=\x1B[39;49m\x1B[43mengine_kwargs\x1B[49m\x1B[43m,\x1B[49m\n' +
      '\x1B[1;32m    500\x1B[0m \x1B[43m    \x1B[49m\x1B[43m)\x1B[49m\n' +
      '\x1B[1;32m    501\x1B[0m \x1B[38;5;28;01melif\x1B[39;00m engine \x1B[38;5;129;01mand\x1B[39;00m engine \x1B[38;5;241m!=\x1B[39m io\x1B[38;5;241m.\x1B[39mengine:\n' +
      '\x1B[1;32m    502\x1B[0m     \x1B[38;5;28;01mraise\x1B[39;00m \x1B[38;5;167;01mValueError\x1B[39;00m(\n' +
      '\x1B[1;32m    503\x1B[0m         \x1B[38;5;124m"\x1B[39m\x1B[38;5;124mEngine should not be specified when passing \x1B[39m\x1B[38;5;124m"\x1B[39m\n' +
      '\x1B[1;32m    504\x1B[0m         \x1B[38;5;124m"\x1B[39m\x1B[38;5;124man ExcelFile - ExcelFile already has the engine set\x1B[39m\x1B[38;5;124m"\x1B[39m\n' +
      '\x1B[1;32m    505\x1B[0m     )\n',
    'File \x1B[0;32m/cluster/tufts/hugheslab/~/mambaforge/envs/nlp4ori/lib/python3.11/site-packages/pandas/io/excel/_base.py:1550\x1B[0m, in \x1B[0;36mExcelFile.__init__\x1B[0;34m(self, path_or_buffer, engine, storage_options, engine_kwargs)\x1B[0m\n' +
      '\x1B[1;32m   1548\x1B[0m     ext \x1B[38;5;241m=\x1B[39m \x1B[38;5;124m"\x1B[39m\x1B[38;5;124mxls\x1B[39m\x1B[38;5;124m"\x1B[39m\n' +
      '\x1B[1;32m   1549\x1B[0m \x1B[38;5;28;01melse\x1B[39;00m:\n' +
      '\x1B[0;32m-> 1550\x1B[0m     ext \x1B[38;5;241m=\x1B[39m \x1B[43minspect_excel_format\x1B[49m\x1B[43m(\x1B[49m\n' +
      '\x1B[1;32m   1551\x1B[0m \x1B[43m        \x1B[49m\x1B[43mcontent_or_path\x1B[49m\x1B[38;5;241;43m=\x1B[39;49m\x1B[43mpath_or_buffer\x1B[49m\x1B[43m,\x1B[49m\x1B[43m \x1B[49m\x1B[43mstorage_options\x1B[49m\x1B[38;5;241;43m=\x1B[39;49m\x1B[43mstorage_options\x1B[49m\n' +
      '\x1B[1;32m   1552\x1B[0m \x1B[43m    \x1B[49m\x1B[43m)\x1B[49m\n' +
      '\x1B[1;32m   1553\x1B[0m     \x1B[38;5;28;01mif\x1B[39;00m ext \x1B[38;5;129;01mis\x1B[39;00m \x1B[38;5;28;01mNone\x1B[39;00m:\n' +
      '\x1B[1;32m   1554\x1B[0m         \x1B[38;5;28;01mraise\x1B[39;00m \x1B[38;5;167;01mValueError\x1B[39;00m(\n' +
      '\x1B[1;32m   1555\x1B[0m             \x1B[38;5;124m"\x1B[39m\x1B[38;5;124mExcel file format cannot be determined, you must specify \x1B[39m\x1B[38;5;124m"\x1B[39m\n' +
      '\x1B[1;32m   1556\x1B[0m             \x1B[38;5;124m"\x1B[39m\x1B[38;5;124man engine manually.\x1B[39m\x1B[38;5;124m"\x1B[39m\n' +
      '\x1B[1;32m   1557\x1B[0m         )\n',
    'File \x1B[0;32m/cluster/tufts/hugheslab/~/mambaforge/envs/nlp4ori/lib/python3.11/site-packages/pandas/io/excel/_base.py:1402\x1B[0m, in \x1B[0;36minspect_excel_format\x1B[0;34m(content_or_path, storage_options)\x1B[0m\n' +
      '\x1B[1;32m   1399\x1B[0m \x1B[38;5;28;01mif\x1B[39;00m \x1B[38;5;28misinstance\x1B[39m(content_or_path, \x1B[38;5;28mbytes\x1B[39m):\n' +
      '\x1B[1;32m   1400\x1B[0m     content_or_path \x1B[38;5;241m=\x1B[39m BytesIO(content_or_path)\n' +
      '\x1B[0;32m-> 1402\x1B[0m \x1B[38;5;28;01mwith\x1B[39;00m \x1B[43mget_handle\x1B[49m\x1B[43m(\x1B[49m\n' +
      '\x1B[1;32m   1403\x1B[0m \x1B[43m    \x1B[49m\x1B[43mcontent_or_path\x1B[49m\x1B[43m,\x1B[49m\x1B[43m \x1B[49m\x1B[38;5;124;43m"\x1B[39;49m\x1B[38;5;124;43mrb\x1B[39;49m\x1B[38;5;124;43m"\x1B[39;49m\x1B[43m,\x1B[49m\x1B[43m \x1B[49m\x1B[43mstorage_options\x1B[49m\x1B[38;5;241;43m=\x1B[39;49m\x1B[43mstorage_options\x1B[49m\x1B[43m,\x1B[49m\x1B[43m \x1B[49m\x1B[43mis_text\x1B[49m\x1B[38;5;241;43m=\x1B[39;49m\x1B[38;5;28;43;01mFalse\x1B[39;49;00m\n' +
      '\x1B[1;32m   1404\x1B[0m \x1B[43m\x1B[49m\x1B[43m)\x1B[49m \x1B[38;5;28;01mas\x1B[39;00m handle:\n' +
      '\x1B[1;32m   1405\x1B[0m     stream \x1B[38;5;241m=\x1B[39m handle\x1B[38;5;241m.\x1B[39mhandle\n' +
      '\x1B[1;32m   1406\x1B[0m     stream\x1B[38;5;241m.\x1B[39mseek(\x1B[38;5;241m0\x1B[39m)\n',
    'File \x1B[0;32m/cluster/tufts/hugheslab/~/mambaforge/envs/nlp4ori/lib/python3.11/site-packages/pandas/io/common.py:882\x1B[0m, in \x1B[0;36mget_handle\x1B[0;34m(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)\x1B[0m\n' +
      '\x1B[1;32m    873\x1B[0m         handle \x1B[38;5;241m=\x1B[39m \x1B[38;5;28mopen\x1B[39m(\n' +
      '\x1B[1;32m    874\x1B[0m             handle,\n' +
      '\x1B[1;32m    875\x1B[0m             ioargs\x1B[38;5;241m.\x1B[39mmode,\n' +
      '\x1B[0;32m   (...)\x1B[0m\n' +
      '\x1B[1;32m    878\x1B[0m             newline\x1B[38;5;241m=\x1B[39m\x1B[38;5;124m"\x1B[39m\x1B[38;5;124m"\x1B[39m,\n' +
      '\x1B[1;32m    879\x1B[0m         )\n' +
      '\x1B[1;32m    880\x1B[0m     \x1B[38;5;28;01melse\x1B[39;00m:\n' +
      '\x1B[1;32m    881\x1B[0m         \x1B[38;5;66;03m# Binary mode\x1B[39;00m\n' +
      '\x1B[0;32m--> 882\x1B[0m         handle \x1B[38;5;241m=\x1B[39m \x1B[38;5;28;43mopen\x1B[39;49m\x1B[43m(\x1B[49m\x1B[43mhandle\x1B[49m\x1B[43m,\x1B[49m\x1B[43m \x1B[49m\x1B[43mioargs\x1B[49m\x1B[38;5;241;43m.\x1B[39;49m\x1B[43mmode\x1B[49m\x1B[43m)\x1B[49m\n' +
      '\x1B[1;32m    883\x1B[0m     handles\x1B[38;5;241m.\x1B[39mappend(handle)\n' +
      '\x1B[1;32m    885\x1B[0m \x1B[38;5;66;03m# Convert BytesIO or file objects passed with an encoding\x1B[39;00m\n',
    "\x1B[0;31mFileNotFoundError\x1B[0m: [Errno 2] No such file or directory: './data/Data.xlsx'"
  ]
}
```

This part is strange, I don't know why there's a ~ in the middle of `/cluster/tufts/hugheslab/~/mambaforge/envs/nlp4ori/bin/python`. Without the ~, that's the path to my python executable. No part of that path is my home directory

`11:20:41.776 [info] Attempting to start a server because of preload conditions ...
11:20:54.653 [info] Starting Kernel (Python Path: /cluster/tufts/hugheslab/~/mambaforge/envs/nlp4ori/bin/python, Conda, 3.11.9) for '~/code/NLP-for-ORI/notebooks/InvestigateData.ipynb' (disableUI=true)`

**Comment by DonJayamanne** [comment]
Thanks, however it doesn't look like you have enabled `trace`  logging.
My instrcutions weren't correct, I mentioned `verbose` and its since been renamed to `trace`
Please can you change that, reload VS Code and try again , then share the logs


![Image](https://github.com/user-attachments/assets/17504c13-ab6f-4efb-94f2-5e3ea18c1025)

**Comment by DonJayamanne** [comment]
> s strange, I don't know why there's a ~ in the middle of /cluster/tufts/hugheslab/~/mambaforge/en

You can ignore this.
Its likely the original value in place of `~` was one of the following `~/code/NLP-for-ORI`, `/cluster/home/kheuto01` or the like.
We try to avoid placing user names and home directories all over, this way users can strip the user name from the top of the logs and share it (with minimal changes), else if you did want to remove your user name from the logs (for privacy reasons), then you'd have to scan the entire log.
