### ISSUE TITLE
Can't debug jupyter notebook after error if also debugging a regular python script

### ISSUE THREAD

**Issue by johnmbarrett** [microsoft/vscode-jupyter#15763]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Apologies if this has been reported before, but I could not find an existing issue for this exact scenario. Essentially, if you try to debug a Jupyter notebook cell in VS Code while simultaneously debugging a normal Python script, and that cell errors before you hit the breakpoint, you will no longer be able to debug that notebook at least until you close and reopen the editor. This is an issue if I've launched a long running Python script from VS Code and want to work on a Jupyter notebook while it runs, as I often do.

### Steps to reproduce

1) Download [this Python script](https://github.com/user-attachments/files/15811255/debugtest.txt).
2) Create a Jupyter notebook with one cell containing the following:
```
import numpy as np

filename = 'C:\\tmp\\tmp.npy' # change to a valid path for your system

np.save(filename,False) # so Pylance doesn't detect the code after the assertion as unreachable

assert np.load(filename)

print('hello, world!')
```
3) Place a breakpoint on the last line of the notebook cell.
4) Debug the script you downloaded in step 1 using the VS Code python debugger (Run and Debug sidebar -> 'Start Debugging' green arrow). It will take a long time to complete.
5) While the script is running, debug the notebook cell you created in steps 2-3. It will fail before the breakpoint is hit with an AssertionError.
6) Repeat step 5.

### Expected behaviour

You can still debug the notebook cell

### Actual behaviour

The below error message pops up and the little drop-down menu next to the cell's run button disappears, preventing further debugging. It will not come back until you reopen the editor (at best) or restart VS code entirely (at worst).

![error_message](https://github.com/microsoft/vscode-jupyter/assets/19190699/8d9589df-1f4e-4804-af23-efa4dc20a703)

### VS Code Version

Version: 1.90.0 (user setup) Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573 Date: 2024-06-04T19:33:54.889Z Electron: 29.4.0 ElectronBuildId: 9593362 Chromium: 122.0.6261.156 Node.js: 20.9.0 V8: 12.2.281.27-electron.0 OS: Windows_NT x64 10.0.19045

### Jupyter Extension Version

v2024.5.0 (also affects pre-release version v2024.6.2024060601)

### Jupyter logs

```shell
Visual Studio Code (1.90.0, undefined, desktop)
Jupyter Extension Version: 2024.5.0.
Python Extension Version: 2024.8.0.
Pylance Extension Version: 2024.6.1.
Platform: win32 (x64).
Workspace folder ~\Documents\python\debugtest, Home = c:\Users\jmb9770
16:52:40.665 [info] Starting Kernel (Python Path: ~\Anaconda3\envs\kilosort4\python.exe, Conda, 3.10.0) for '~\Documents\python\debugtest\debugtest.ipynb' (disableUI=true)
16:53:05.370 [info] Process Execution: ~\Anaconda3\envs\kilosort4\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
16:53:05.438 [info] Process Execution: ~\Anaconda3\envs\kilosort4\python.exe c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.5.0-win32-x64\pythonFiles\vscode_datascience_helpers\kernel_interrupt_daemon.py --ppid 23700
    > cwd: ~\.vscode\extensions\ms-toolsai.jupyter-2024.5.0-win32-x64\pythonFiles\vscode_datascience_helpers
16:53:05.491 [info] Process Execution: ~\Anaconda3\envs\kilosort4\python.exe -m pip list
16:53:06.331 [info] Process Execution: ~\Anaconda3\envs\kilosort4\python.exe -m ipykernel_launcher --f=c:\Users\~\AppData\Roaming\jupyter\runtime\kernel-v2-23700UxsnWYBr5sNt.json
    > cwd: ~\Documents\python\debugtest
16:53:09.147 [info] Kernel successfully started
16:53:09.165 [info] Process Execution: ~\Anaconda3\envs\kilosort4\python.exe c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.5.0-win32-x64\pythonFiles\printJupyterDataDir.py
16:53:11.994 [warn] Cell completed with errors [hd [Error]: AssertionError
	at r.execute (c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.5.0-win32-x64\dist\extension.node.js:307:4958)] {
  ename: 'AssertionError',
  evalue: '',
  traceback: [
    '\x1B[1;31m---------------------------------------------------------------------------\x1B[0m',
    '\x1B[1;31mAssertionError\x1B[0m                            Traceback (most recent call last)',
    'Cell \x1B[1;32mIn[1], line 7\x1B[0m\n' +
      "\x1B[0;32m      3\x1B[0m filename \x1B[38;5;241m=\x1B[39m \x1B[38;5;124m'\x1B[39m\x1B[38;5;124mC:\x1B[39m\x1B[38;5;130;01m\\\\\x1B[39;00m\x1B[38;5;124mtmp\x1B[39m\x1B[38;5;130;01m\\\\\x1B[39;00m\x1B[38;5;124mtmp.npy\x1B[39m\x1B[38;5;124m'\x1B[39m \x1B[38;5;66;03m# change to a valid path for your system\x1B[39;00m\n" +
      '\x1B[0;32m      5\x1B[0m np\x1B[38;5;241m.\x1B[39msave(filename,\x1B[38;5;28;01mFalse\x1B[39;00m)\n' +
      '\x1B[1;32m----> 7\x1B[0m \x1B[38;5;28;01massert\x1B[39;00m np\x1B[38;5;241m.\x1B[39mload(filename)\n' +
      "\x1B[0;32m      9\x1B[0m \x1B[38;5;28mprint\x1B[39m(\x1B[38;5;124m'\x1B[39m\x1B[38;5;124mhello, world!\x1B[39m\x1B[38;5;124m'\x1B[39m)\n",
    '\x1B[1;31mAssertionError\x1B[0m: '
  ]
}
16:53:13.656 [info] Starting debugging with mode 1
16:53:16.738 [warn] Cell completed with errors [hd [Error]: AssertionError
	at r.execute (c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.5.0-win32-x64\dist\extension.node.js:307:4958)] {
  ename: 'AssertionError',
  evalue: '',
  traceback: [
    '\x1B[1;31m---------------------------------------------------------------------------\x1B[0m',
    '\x1B[1;31mAssertionError\x1B[0m                            Traceback (most recent call last)',
    'Cell \x1B[1;32mIn[2], line 7\x1B[0m\n' +
      "\x1B[0;32m      3\x1B[0m filename \x1B[38;5;241m=\x1B[39m \x1B[38;5;124m'\x1B[39m\x1B[38;5;124mC:\x1B[39m\x1B[38;5;130;01m\\\\\x1B[39;00m\x1B[38;5;124mtmp\x1B[39m\x1B[38;5;130;01m\\\\\x1B[39;00m\x1B[38;5;124mtmp.npy\x1B[39m\x1B[38;5;124m'\x1B[39m \x1B[38;5;66;03m# change to a valid path for your system\x1B[39;00m\n" +
      '\x1B[0;32m      5\x1B[0m np\x1B[38;5;241m.\x1B[39msave(filename,\x1B[38;5;28;01mFalse\x1B[39;00m)\n' +
      '\x1B[1;32m----> 7\x1B[0m \x1B[38;5;28;01massert\x1B[39;00m np\x1B[38;5;241m.\x1B[39mload(filename)\n' +
      "\x1B[0;32m      9\x1B[0m \x1B[38;5;28mprint\x1B[39m(\x1B[38;5;124m'\x1B[39m\x1B[38;5;124mhello, world!\x1B[39m\x1B[38;5;124m'\x1B[39m)\n",
    '\x1B[1;31mAssertionError\x1B[0m: '
  ]
}
16:53:16.748 [info] Ending debug session 7c2b0e51-f3e6-4ad1-8925-c7b4cf426e29
16:53:18.788 [info] Starting debugging with mode 1
16:53:20.960 [info] Ending debug session 7c2b0e51-f3e6-4ad1-8925-c7b4cf426e29
16:53:20.960 [info] Ending debug session 7c2b0e51-f3e6-4ad1-8925-c7b4cf426e29
```

### Coding Language and Runtime Version

Python 3.9.15

### Language Extension Version (if applicable)

v2024.8.0 (also affects pre-release version v2024.9.11641010)

### Anaconda Version (if applicable)

23.3.1

### Running Jupyter locally or remotely?

Local

**Comment by johnmbarrett** [comment]
Quick update since I'm at it again: it seems like this issue only arises if you hit the error before hitting a break point. In this situation (simultaneously debugging a Python script and a Jupyter notebook), if a break point is hit first and then I step over or continue through a line that errors, I can still continue to debug the notebook as many times as I want.

**Comment by DonJayamanne** [comment]
@johnmbarrett are you still running into this issue with the latest version of Jupyter, Python  and Python debugger extensions

**Comment by johnmbarrett** [comment]
Latest version of everything appears to have pushed everything one iteration down the road, i.e. I can debug twice but not three times before running into the error. Version info:

Version: 1.96.0 (user setup)
Commit: 138f619c86f1199955d53b4166bef66ef252935c
Date: 2024-12-11T02:29:09.626Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.19045
Jupyter: 2024.11.0
Python: 2024.22.0
Python debugger: 2024.14.0

Lemme know if there are pre-release versions you want me to try

**Comment by johnmbarrett** [comment]
I pressed the wrong button and closed the issue by accident

**Comment by DonJayamanne** [comment]
> ore, but I could not find an existing issue for this exact scenario. Essentially, if you try to debug a Jupyter notebook cell in VS Code while simultaneously debugging a normal Python script, and 

Unfortunately we have no plans to support this scenario.
I.e. debugging notebook and Python file side by side.
