### ISSUE TITLE
Extension 'vscode.ipynb' is not known or not activated

### ISSUE THREAD

**Issue by JunbeiZhang** [microsoft/vscode-jupyter#15781]
## Environment data

-   VS Code version: 1.90.1
-   Jupyter Extension version (available under the Extensions sidebar): v2024.5.0
-   Python Extension version (available under the Extensions sidebar): v2024.9.11711009 (pre-release)
-   OS (Windows | Mac | Linux distro) and version: windows11
-   Python and/or Anaconda version: python 3.11
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N
-   Jupyter server running: Local 

## Expected behaviour

transform .py to .ipynb

## Actual behaviour

error
![actual](https://github.com/microsoft/vscode-jupyter/assets/103248424/ed099977-9b67-44c9-a191-47c4980c0c4b)

## Steps to reproduce:

ctrl+shift+p

>jupyter:export current python file as jupyter notebook

error:Extension 'vscode.ipynb' is not known or not activated

## Logs

19:37:36.848 [warn] DataScience Error Error: Extension 'vscode.ipynb' is not known or not activated
    at b.getActivatedExtension (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:143:3653)
    at u.getExtensionExports (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:159:8971)
    at ne.get exports [as exports] (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:159:23149)
    at vI.serialize (c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.5.2024052901-win32-x64\dist\extension.node.js:374:13260)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.5.2024052901-win32-x64\dist\extension.node.js:341:12092
    at G0.waitWithStatus (c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.5.2024052901-win32-x64\dist\extension.node.js:341:1141)
    at Ko.exportFile (c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.5.2024052901-win32-x64\dist\extension.node.js:341:12045)
    at Ko.listenForErrors (c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.5.2024052901-win32-x64\dist\extension.node.js:341:11653)
    at h (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:200468)

**Comment by DonJayamanne** [comment]
I'm sorry you are running into this issue.
Are you still running into this problem

**Comment by JunbeiZhang** [comment]
Yes, I still can’t use Jupiter extension



发自我的iPhone


------------------ Original ------------------
From: Don Jayamanne ***@***.***&gt;
Date: Mon,Jun 24,2024 9:32 PM
To: microsoft/vscode-jupyter ***@***.***&gt;
Cc: Junbei Zhang ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [microsoft/vscode-jupyter] Extension 'vscode.ipynb' is not knownor not activated (Issue #15781)





 
I'm sorry you are running into this issue.
 Are you still running into this problem

**Comment by sbroth** [comment]
I am having the exact same issue. I tried downgrading Jupyter to the previous version, and it still did not work.

**Comment by JunbeiZhang** [comment]
me too, I try to reload it, but still can't work.

**Comment by DonJayamanne** [comment]
I'm sorry you are running into this, 
@sbroth @JunbeiZhang Please can you disable all extensions and try this again.
Also, can you search for the ipynb extension and ensure it is enabled, see below on searching for this.
![Screenshot 2024-06-28 at 11 16 19](https://github.com/microsoft/vscode-jupyter/assets/1948812/473c1372-42b9-4dd5-84b7-70b1d6fc705a)

![Screenshot 2024-06-28 at 11 17 02](https://github.com/microsoft/vscode-jupyter/assets/1948812/991b4a63-26a3-4e96-88e2-d45fb593358d)

**Comment by JunbeiZhang** [comment]
<img width="581" alt="@builtin" src="https://github.com/microsoft/vscode-jupyter/assets/103248424/7cb24f9d-c88b-4a41-9be9-e0e885f25cf7">
<img width="673" alt="jupyter_extension" src="https://github.com/microsoft/vscode-jupyter/assets/103248424/d7c2753e-1fb4-4e63-9cce-773a2670decc">
I try jupyter again with and without extensions, making sure .ipynb support is ok.
But I still can't use it, it comes the same error.

**Comment by jinang99** [comment]
Hi @JunbeiZhang @sbroth, 
Try switching to a pre-release version for the Jupyter extension pack [v2024.4.2024042601 (pre-release)] in VS Code. That worked for us!

**Comment by jeet183** [comment]
Thanks @jinang99!
This solved my issue.

**Comment by DonJayamanne** [comment]
If this issue still persists, please ping here or feel free to create a new issue.
Closing as I think this no longer exists.

**Comment by forestGoroli** [comment]
I'm still facing the same error:
When I use: `jupyter:export current python file as jupyter notebook`, 
I got: 
> Extension 'vscode.ipynb' is not known or not activated


I checked the versions below, but they didn't work (I got the above error)
- v2024.8.2024080201 (pre-release)
- v2024.7.0
- v2024.4.2024042601 (pre-release) <- Even though jinang99 succeeded with this version, I still got the error.
- v2024.3.0


The following versions work fine:
- v2024.2.2024022602 (pre-release)
- v2024.2.0


I suspect something was changed between these versions...

**Comment by korsbakken** [comment]
I also have the exact same issue, with both v2024.7.0 and v2024.8.2024080201 (pre-release). I think this issue needs to be reopened.

**Comment by staqd** [comment]
there is a workaround, you can use in your terminal:
pip install jupytext
jupytext --to notebook your_file_name.py

**Comment by cburik** [comment]
I'm still running into this issue on v2024.9.1 ; downgrading to 2024.2 solves the issue.

**Comment by DonJayamanne** [comment]
@cburik Please can you update VS Code, Jupyter extensions to the latest versions and see if you can still repro this issue.
* If you can, then please can you select the command `Toggle Developer Tools` (from the command palette), then select the `console` window and look for any errors.
* Next, please can you select the command `Output: Focus on Output View`, then select the item `Extension Host`
Please copy and past those logs (might contain some errors).

Thanks

**Comment by cburik** [comment]
Honestly, I can't reproduce the bug anymore. Haven't updated VSCode between Friday and today (it's the latest release). I just switched back to Jupyter extension v2024.9.1 and tried to reproduce the error, but I can't. I haven't even restarted VSCode, only reloaded the extensions after updating back to v2024.9.1.

**Comment by DonJayamanne** [comment]
Thank you, let’s close this issue for now

**Comment by SIHranova** [comment]
I am also facing this issue. Have uninstalled and reinstalled python and jupyter extensions. This is my error log. I am currently using the console work-around. 

Visual Studio Code (1.94.2, undefined, desktop)
Jupyter Extension Version: 2024.9.1.
Python Extension Version: 2024.16.1.
Pylance Extension Version: 2024.10.1.
Platform: linux (x64).
Temp Storage folder ~/.config/Code/User/globalStorage/ms-toolsai.jupyter/version-2024.9.1
Workspace folder ~/Nextcloud2/projects/BayesTwoGalaxiesTask, Home = /home/terra
10:32:31.827 [info] Process Execution: ~/miniforge3/envs/dp_torch/bin/python -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
10:32:31.832 [info] Process Execution: ~/miniforge3/envs/dp_torch/bin/python -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
10:32:31.849 [info] Process Execution: ~/miniforge3/envs/dp_torch/bin/python -m jupyter kernelspec --version
10:32:31.951 [error] listenForErrors [Error: Extension 'vscode.ipynb' is not known or not activated
	at E0.getActivatedExtension (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:1754)
	at hB.getExtensionExports (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:10934)
	at get exports (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:24330)
	at Gb.serialize (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.9.1-linux-x64/dist/extension.node.js:364:13260)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async /home/~/.vscode/extensions/ms-toolsai.jupyter-2024.9.1-linux-x64/dist/extension.node.js:331:12092
	at async i0.waitWithStatus (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.9.1-linux-x64/dist/extension.node.js:331:1141)
	at async ko.exportFile (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.9.1-linux-x64/dist/extension.node.js:331:12045)
	at async ko.listenForErrors (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.9.1-linux-x64/dist/extension.node.js:331:11653)
	at async T0.h (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:32837)]
10:32:31.951 [warn] DataScience Error [Error: Extension 'vscode.ipynb' is not known or not activated
	at E0.getActivatedExtension (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:1754)
	at hB.getExtensionExports (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:10934)
	at get exports (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:24330)
	at Gb.serialize (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.9.1-linux-x64/dist/extension.node.js:364:13260)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async /home/~/.vscode/extensions/ms-toolsai.jupyter-2024.9.1-linux-x64/dist/extension.node.js:331:12092
	at async i0.waitWithStatus (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.9.1-linux-x64/dist/extension.node.js:331:1141)
	at async ko.exportFile (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.9.1-linux-x64/dist/extension.node.js:331:12045)
	at async ko.listenForErrors (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.9.1-linux-x64/dist/extension.node.js:331:11653)
	at async T0.h (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:32837)]
10:33:24.236 [error] listenForErrors [Error: Extension 'vscode.ipynb' is not known or not activated
	at E0.getActivatedExtension (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:1754)
	at hB.getExtensionExports (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:10934)
	at get exports (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:24330)
	at Gb.serialize (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.9.1-linux-x64/dist/extension.node.js:364:13260)
	at async /home/~/.vscode/extensions/ms-toolsai.jupyter-2024.9.1-linux-x64/dist/extension.node.js:331:12092
	at async i0.waitWithStatus (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.9.1-linux-x64/dist/extension.node.js:331:1141)
	at async ko.exportFile (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.9.1-linux-x64/dist/extension.node.js:331:12045)
	at async ko.listenForErrors (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.9.1-linux-x64/dist/extension.node.js:331:11653)
	at async T0.h (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:32837)]
10:33:24.236 [warn] DataScience Error [Error: Extension 'vscode.ipynb' is not known or not activated
	at E0.getActivatedExtension (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:1754)
	at hB.getExtensionExports (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:10934)
	at get exports (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:24330)
	at Gb.serialize (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.9.1-linux-x64/dist/extension.node.js:364:13260)
	at async /home/~/.vscode/extensions/ms-toolsai.jupyter-2024.9.1-linux-x64/dist/extension.node.js:331:12092
	at async i0.waitWithStatus (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.9.1-linux-x64/dist/extension.node.js:331:1141)
	at async ko.exportFile (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.9.1-linux-x64/dist/extension.node.js:331:12045)
	at async ko.listenForErrors (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.9.1-linux-x64/dist/extension.node.js:331:11653)
	at async T0.h (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:32837)]
10:35:14.702 [error] listenForErrors [Error: Extension 'vscode.ipynb' is not known or not activated
	at E0.getActivatedExtension (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:1754)
	at hB.getExtensionExports (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:10934)
	at get exports (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:24330)
	at Gb.serialize (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.9.1-linux-x64/dist/extension.node.js:364:13260)
	at async /home/~/.vscode/extensions/ms-toolsai.jupyter-2024.9.1-linux-x64/dist/extension.node.js:331:12092
	at async i0.waitWithStatus (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.9.1-linux-x64/dist/extension.node.js:331:1141)
	at async ko.exportFile (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.9.1-linux-x64/dist/extension.node.js:331:12045)
	at async ko.listenForErrors (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.9.1-linux-x64/dist/extension.node.js:331:11653)
	at async T0.h (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:32837)]
10:35:14.702 [warn] DataScience Error [Error: Extension 'vscode.ipynb' is not known or not activated
	at E0.getActivatedExtension (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:1754)
	at hB.getExtensionExports (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:10934)
	at get exports (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:24330)
	at Gb.serialize (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.9.1-linux-x64/dist/extension.node.js:364:13260)
	at async /home/~/.vscode/extensions/ms-toolsai.jupyter-2024.9.1-linux-x64/dist/extension.node.js:331:12092
	at async i0.waitWithStatus (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.9.1-linux-x64/dist/extension.node.js:331:1141)
	at async ko.exportFile (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.9.1-linux-x64/dist/extension.node.js:331:12045)
	at async ko.listenForErrors (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.9.1-linux-x64/dist/extension.node.js:331:11653)
	at async T0.h (file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:114:32837)]
