### ISSUE TITLE
Trying to export python code to jupyter notebook file fails with error: Extension 'vscode.ipynb' is not known or not activated. View Jupyter log for further details. 

### ISSUE THREAD

**Issue by Coderx7** [microsoft/vscode-jupyter#15828]
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Expected to get the ipynb version without any issues!
[vscode-Screencast from 07-06-2024 05:15:34 PM.WEBM](https://github.com/microsoft/vscode-jupyter/assets/5382892/178db742-48c6-47cf-98db-701824ab332f)

### VS Code Version

Version: 1.91.0 Commit: ea1445cc7016315d0f5728f8e8b12a45dc0a7286 Date: 2024-07-01T18:52:41.959Z Electron: 29.4.0 ElectronBuildId: 9728852 Chromium: 122.0.6261.156 Node.js: 20.9.0 V8: 12.2.281.27-electron.0 OS: Linux x64 6.5.0-41-generic snap

### Jupyter Extension Version

v2024.6.0

### Jupyter logs

```shell
17:20:23.508 [error] listenForErrors [Error: Extension 'vscode.ipynb' is not known or not activated
	at w.getActivatedExtension (/snap/code/163/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:144:3676)
	at m.getExtensionExports (/snap/code/163/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:9019)
	at get exports (/snap/code/163/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:23221)
	at Hb.serialize (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/dist/extension.node.js:364:13260)
	at async /home/~/.vscode/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/dist/extension.node.js:331:12092
	at async YT.waitWithStatus (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/dist/extension.node.js:331:1141)
	at async ko.exportFile (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/dist/extension.node.js:331:12045)
	at async ko.listenForErrors (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/dist/extension.node.js:331:11653)
	at async f.h (/snap/code/163/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:204392)]
17:20:23.508 [warn] DataScience Error [Error: Extension 'vscode.ipynb' is not known or not activated
	at w.getActivatedExtension (/snap/code/163/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:144:3676)
	at m.getExtensionExports (/snap/code/163/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:9019)
	at get exports (/snap/code/163/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:160:23221)
	at Hb.serialize (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/dist/extension.node.js:364:13260)
	at async /home/~/.vscode/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/dist/extension.node.js:331:12092
	at async YT.waitWithStatus (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/dist/extension.node.js:331:1141)
	at async ko.exportFile (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/dist/extension.node.js:331:12045)
	at async ko.listenForErrors (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/dist/extension.node.js:331:11653)
	at async f.h (/snap/code/163/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:154:204392)]
```

### Coding Language and Runtime Version

Python v3.11.9

### Language Extension Version (if applicable)

v2024.8.1

### Anaconda Version (if applicable)

not sure maybe Anaconda 2023.07-2 (Aug 04, 2023)

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
Can you try opening a notebook first and then see if exporting works? We might just need to ensure that the ipynb extension is activated at that point.
