### ISSUE TITLE
Failure to determine calling extension from callstack in web

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#15867]
<details>
  <summary>Show Logs</summary>
  
```
Visual Studio Code - Insiders (1.92.0-insider, undefined, vscode.dev)
Jupyter Extension Version: 2024.6.0.
Python Extension Version: 2024.11.2024072302.
Pylance Extension Version: 2024.7.101.
No workspace folder opened.
23:29:21.909 [error] Unable to determine the caller of the extension API for trace stack. Error: 
    at VI.determineExtensionFromCallStack (https://ms-toolsai.vscode-unpkg.net/ms-toolsai/jupyter/2024.6.0+web/extension/dist/extension.web.bundle.js#vscode-extension:155:48528)
    at Object.createJupyterServerCollection (https://ms-toolsai.vscode-unpkg.net/ms-toolsai/jupyter/2024.6.0+web/extension/dist/extension.web.bundle.js#vscode-extension:155:28598)
    at bo.eval (https://github.vscode-unpkg.net/GitHub/codespaces/1.17.2/node_modules/google-protobuf/google-protobuf.js:31:203)
    at Generator.next (<anonymous>)
    at fulfilled (https://github.vscode-unpkg.net/GitHub/codespaces/1.17.2/node_modules/google-protobuf/google-protobuf.js:31:203)
23:29:25.827 [info] Starting Kernel (Synapse PySpark) for 'Untitled-1.ipynb' (disableUI=false)
23:29:25.839 [error] Failed to change kernel, re-throwing Error: Invalid body response: {"path":"Untitled-1-jvsc-6e33b1dd-888b-45a6-889d-3bf23232c0b6eeed7f55-acdf-4fc4-8612-6d4f819d7818.ipynb","kernel":{"name":"synapse_pyspark"},"name":"Untitled-1-64f3b4bf-bd37-4627-a767-1566c838cb13.ipynb","type":"notebook"}.
    > at new r (https://ms-toolsai.vscode-unpkg.net/ms-toolsai/jupyter/2024.6.0+web/extension/dist/extension.web.bundle.js#vscode-extension:73:4502)
    > originalException = TypeError: Invalid body response: {"path":"Untitled-1-jvsc-6e33b1dd-888b-45a6-889d-3bf23232c0b6eeed7f55-acdf-4fc4-8612-6d4f819d7818.ipynb","kernel":{"name":"synapse_pyspark"},"name":"Untitled-1-64f3b4bf-bd37-4627-a767-1566c838cb13.ipynb","type":"notebook"}.
23:29:25.840 [warn] Error occurred while trying to start the kernel, options.disableUI=false Error: Failed to connect to the remote Jupyter Server 'https://synapse-remote-jupyter-server/'. Verify the server is running and reachable. (Invalid body response: {"path":"Untitled-1-jvsc-6e33b1dd-888b-45a6-889d-3bf23232c0b6eeed7f55-acdf-4fc4-8612-6d4f819d7818.ipynb","kernel":{"name":"synapse_pyspark"},"name":"Untitled-1-64f3b4bf-bd37-4627-a767-1566c838cb13.ipynb","type":"notebook"}.).
    > at Hd.create (https://ms-toolsai.vscode-unpkg.net/ms-toolsai/jupyter/2024.6.0+web/extension/dist/extension.web.bundle.js#vscode-extension:246:2830)
    > url = https://synapse-remote-jupyter-server/
    > serverProviderHandle = [object Object]
    > originalError = Error: Invalid body response: {"path":"Untitled-1-jvsc-6e33b1dd-888b-45a6-889d-3bf23232c0b6eeed7f55-acdf-4fc4-8612-6d4f819d7818.ipynb","kernel":{"name":"synapse_pyspark"},"name":"Untitled-1-64f3b4bf-bd37-4627-a767-1566c838cb13.ipynb","type":"notebook"}.
    > baseUrl = https://synapse-remote-jupyter-server/
    > vslsStack = Hd.create (https://ms-toolsai.vscode-unpkg.net/ms-toolsai/jupyter/2024.6.0+web/extension/dist/extension.web.bundle.js#vscode-extension:246:2830),async iA.createJupyterSession (https://ms-toolsai.vscode-unpkg.net/ms-toolsai/jupyter/2024.6.0+web/extension/dist/extension.web.bundle.js#vscode-extension:246:24213),async iA.startJupyterSession (https://ms-toolsai.vscode-unpkg.net/ms-toolsai/jupyter/2024.6.0+web/extension/dist/extension.web.bundle.js#vscode-extension:246:22187),async qr.wrapKernelMethodImpl (https://ms-toolsai.vscode-unpkg.net/ms-toolsai/jupyter/2024.6.0+web/extension/dist/extension.web.bundle.js#vscode-extension:260:78246)
23:29:25.840 [warn] Kernel Error, context = start Error: Failed to connect to the remote Jupyter Server 'https://synapse-remote-jupyter-server/'. Verify the server is running and reachable. (Invalid body response: {"path":"Untitled-1-jvsc-6e33b1dd-888b-45a6-889d-3bf23232c0b6eeed7f55-acdf-4fc4-8612-6d4f819d7818.ipynb","kernel":{"name":"synapse_pyspark"},"name":"Untitled-1-64f3b4bf-bd37-4627-a767-1566c838cb13.ipynb","type":"notebook"}.).
    > at Hd.create (https://ms-toolsai.vscode-unpkg.net/ms-toolsai/jupyter/2024.6.0+web/extension/dist/extension.web.bundle.js#vscode-extension:246:2830)
    > url = https://synapse-remote-jupyter-server/
    > serverProviderHandle = [object Object]
    > originalError = Error: Invalid body response: {"path":"Untitled-1-jvsc-6e33b1dd-888b-45a6-889d-3bf23232c0b6eeed7f55-acdf-4fc4-8612-6d4f819d7818.ipynb","kernel":{"name":"synapse_pyspark"},"name":"Untitled-1-64f3b4bf-bd37-4627-a767-1566c838cb13.ipynb","type":"notebook"}.
    > baseUrl = https://synapse-remote-jupyter-server/
    > vslsStack = Hd.create (https://ms-toolsai.vscode-unpkg.net/ms-toolsai/jupyter/2024.6.0+web/extension/dist/extension.web.bundle.js#vscode-extension:246:2830),async iA.createJupyterSession (https://ms-toolsai.vscode-unpkg.net/ms-toolsai/jupyter/2024.6.0+web/extension/dist/extension.web.bundle.js#vscode-extension:246:24213),async iA.startJupyterSession (https://ms-toolsai.vscode-unpkg.net/ms-toolsai/jupyter/2024.6.0+web/extension/dist/extension.web.bundle.js#vscode-extension:246:22187),async qr.wrapKernelMethodImpl (https://ms-toolsai.vscode-unpkg.net/ms-toolsai/jupyter/2024.6.0+web/extension/dist/extension.web.bundle.js#vscode-extension:260:78246)
23:29:25.842 [info] Dispose Kernel 'Untitled-1.ipynb' associated with 'Untitled-1.ipynb'

```
</details>

**Comment by DonJayamanne** [comment]
Closing for now as not reported
