### ISSUE TITLE
Can't connect to remote kernel when from vscode ssh workspace

### ISSUE THREAD

**Issue by oscarpitcho** [microsoft/vscode-jupyter#15873]
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I am running jupyterlab on a cluster which I have ssh access to. I can successfully run Jupyter and tunnel it to my machine such that I can open it from the browser. However, when trying to connect to the remote server from vscode this throws the following error:

![image](https://github.com/user-attachments/assets/82fb890c-7861-407f-a867-cbc44881221b)

Furthermore, this only occurs trying to connect to the remote server from a vscode session itself connected to the remote server.

VSCode when opened normally has no issues connecting to the remote server.

### VS Code Version

Version: 1.91.1 Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729 Date: 2024-07-09T22:08:12.169Z Electron: 29.4.0 ElectronBuildId: 9728852 Chromium: 122.0.6261.156 Node.js: 20.9.0 V8: 12.2.281.27-electron.0 OS: Linux x64 5.15.0-116-generic

### Jupyter Extension Version

v2024.6.0

### Jupyter logs

```shell
}
16:56:17.958 [debug] Kernel Spec Root Paths, /usr/share/jupyter/kernels, /usr/local/share/jupyter/kernels, ~/.local/share/jupyter/kernels
16:56:18.324 [debug] Controller startUsingPythonInterpreter:'.jvsc74a57bd05a2f0a0613e950d5d63b554a7dbbd397fdfa50dd9c76ebeeec21d430f42b3718./home/oscar/miniconda3./home/oscar/miniconda3.-m#ipykernel_launcher' for view = 'jupyter-notebook' is no longer a valid
16:56:18.324 [debug] Controller startUsingPythonInterpreter:'.jvsc74a57bd05a2f0a0613e950d5d63b554a7dbbd397fdfa50dd9c76ebeeec21d430f42b3718./home/oscar/miniconda3./home/oscar/miniconda3.-m#ipykernel_launcher (Interactive)' for view = 'interactive' is no longer a valid
16:56:18.324 [warn] Disposing old controller startUsingPythonInterpreter:'.jvsc74a57bd05a2f0a0613e950d5d63b554a7dbbd397fdfa50dd9c76ebeeec21d430f42b3718./home/oscar/miniconda3./home/oscar/miniconda3.-m#ipykernel_launcher' for view = 'jupyter-notebook'
16:56:18.325 [debug] Disposing controller .jvsc74a57bd05a2f0a0613e950d5d63b554a7dbbd397fdfa50dd9c76ebeeec21d430f42b3718./home/oscar/miniconda3./home/oscar/miniconda3.-m#ipykernel_launcher associated with connection .jvsc74a57bd05a2f0a0613e950d5d63b554a7dbbd397fdfa50dd9c76ebeeec21d430f42b3718./home/oscar/miniconda3./home/oscar/miniconda3.-m#ipykernel_launcher 
16:56:18.326 [warn] Disposing old controller startUsingPythonInterpreter:'.jvsc74a57bd05a2f0a0613e950d5d63b554a7dbbd397fdfa50dd9c76ebeeec21d430f42b3718./home/oscar/miniconda3./home/oscar/miniconda3.-m#ipykernel_launcher (Interactive)' for view = 'interactive'
16:56:18.326 [debug] Disposing controller .jvsc74a57bd05a2f0a0613e950d5d63b554a7dbbd397fdfa50dd9c76ebeeec21d430f42b3718./home/oscar/miniconda3./home/oscar/miniconda3.-m#ipykernel_launcher (Interactive) associated with connection .jvsc74a57bd05a2f0a0613e950d5d63b554a7dbbd397fdfa50dd9c76ebeeec21d430f42b3718./home/oscar/miniconda3./home/oscar/miniconda3.-m#ipykernel_launcher 
16:56:19.329 [debug] Interpreter removed /home/oscar/miniconda3
16:56:21.485 [debug] Refreshed Environments
16:56:22.486 [debug] End refreshing Kernel Picker (1721854566222)
16:57:26.315 [debug] Error in detecting whether url is isJupyterHub: FetchError: request to http://127.0.0.1:4444/hub/api failed, reason: connect ECONNREFUSED 127.0.0.1:4444
16:58:29.191 [debug] Error in detecting whether url is isJupyterHub: FetchError: request to http://127.0.0.1:4444/hub/api failed, reason: connect ECONNREFUSED 127.0.0.1:4444
16:59:21.450 [debug] Error in detecting whether url is isJupyterHub: FetchError: request to http://127.0.0.1:4444/hub/api failed, reason: connect ECONNREFUSED 127.0.0.1:4444



(Tried several times to connect)
```

### Running Jupyter locally or remotely?

Remote

**Comment by oscarpitcho** [comment]
I am adding the following more detailed error logs: 

`13:51:22.555 [debug] Start refreshing Kernel Picker (1721929882555)
13:51:22.563 [debug] Error in detecting whether url is isJupyterHub: FetchError: request to http://127.0.0.1:4444/hub/api failed, reason: connect ECONNREFUSED 127.0.0.1:4444
13:51:22.567 [error] Failed to validate Password info [D [FetchError]: request to http://127.0.0.1:4444/ failed, reason: connect ECONNREFUSED 127.0.0.1:4444
	at ClientRequest.<anonymous> (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/dist/node_modules/node-fetch.js:1:306417)
	at ClientRequest.emit (node:events:518:28)
	at Socket.socketErrorListener (node:_http_client:495:9)
	at Socket.emit (node:events:518:28)
	at emitErrorNT (node:internal/streams/destroy:169:8)
	at emitErrorCloseNT (node:internal/streams/destroy:128:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)] {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
13:51:22.582 [error] Error fetching kernels from http://127.0.0.1:4444/ (127.0.0.1): [FetchError: request to http://127.0.0.1:4444/api/kernels?1721929882571 failed, reason: connect ECONNREFUSED 127.0.0.1:4444
	at ClientRequest.<anonymous> (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/dist/node_modules/node-fetch.js:1:306417)
	at ClientRequest.emit (node:events:518:28)
	at Socket.socketErrorListener (node:_http_client:495:9)
	at Socket.emit (node:events:518:28)
	at emitErrorNT (node:internal/streams/destroy:169:8)
	at emitErrorCloseNT (node:internal/streams/destroy:128:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)]
13:51:22.584 [error] Jupyter Lab Helper:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at v.dispose (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/dist/node_modules/@jupyterlab/services.js:11:10935)
	at ni.dispose (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/dist/node_modules/@jupyterlab/services.js:11:29299)
	at /home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/dist/extension.node.js:181:15205
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)]
13:51:22.590 [debug] Error in detecting whether url is isJupyterHub: FetchError: request to http://127.0.0.1:4444/hub/api failed, reason: connect ECONNREFUSED 127.0.0.1:4444
13:51:22.593 [error] Failed to validate Password info [D [FetchError]: request to http://127.0.0.1:4444/ failed, reason: connect ECONNREFUSED 127.0.0.1:4444
	at ClientRequest.<anonymous> (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/dist/node_modules/node-fetch.js:1:306417)
	at ClientRequest.emit (node:events:518:28)
	at Socket.socketErrorListener (node:_http_client:495:9)
	at Socket.emit (node:events:518:28)
	at emitErrorNT (node:internal/streams/destroy:169:8)
	at emitErrorCloseNT (node:internal/streams/destroy:128:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)] {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
13:51:22.606 [error] Error fetching kernels from http://127.0.0.1:4444/ (127.0.0.1): [FetchError: request to http://127.0.0.1:4444/api/kernels?1721929882597 failed, reason: connect ECONNREFUSED 127.0.0.1:4444
	at ClientRequest.<anonymous> (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/dist/node_modules/node-fetch.js:1:306417)
	at ClientRequest.emit (node:events:518:28)
	at Socket.socketErrorListener (node:_http_client:495:9)
	at Socket.emit (node:events:518:28)
	at emitErrorNT (node:internal/streams/destroy:169:8)
	at emitErrorCloseNT (node:internal/streams/destroy:128:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)]
13:51:22.608 [error] Jupyter Lab Helper:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at v.dispose (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/dist/node_modules/@jupyterlab/services.js:11:10935)
	at ni.dispose (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/dist/node_modules/@jupyterlab/services.js:11:29299)
	at /home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/dist/extension.node.js:181:15205
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)]
13:51:22.608 [error] UniversalRemoteKernelFinder: Failed to get kernels without cache [FetchError: request to http://127.0.0.1:4444/api/kernels?1721929882597 failed, reason: connect ECONNREFUSED 127.0.0.1:4444
	at ClientRequest.<anonymous> (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/dist/node_modules/node-fetch.js:1:306417)
	at ClientRequest.emit (node:events:518:28)
	at Socket.socketErrorListener (node:_http_client:495:9)
	at Socket.emit (node:events:518:28)
	at emitErrorNT (node:internal/streams/destroy:169:8)
	at emitErrorCloseNT (node:internal/streams/destroy:128:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)]
13:51:22.653 [debug] End refreshing Kernel Picker (1721929882555)`

**Comment by DonJayamanne** [comment]
Thank you for the detailed logs and sorry you are running into this.

> Furthermore, this only occurs trying to connect to the remote server from a vscode session itself connected to the remote server.
VSCode when opened normally has no issues connecting to the remote server.


Where is this server running, on your current machine or the remote SSH server?
I.e. is Jupyter and VS Code remote running on the same server/machine?

**Comment by oscarpitcho** [comment]
Good question: That actually helped me fix it.

The issue was that the jupyter server was running on a compute node and vscode was connecting to the head node of the cluster. Hence, I had to create an ssh tunnel not between my machine and the compute node but between the head node and the compute node.

Thanks,
Oscar
________________________________

**Comment by joseph-siefert** [comment]
Im experiencing the same issue, can you please elaborate how you fixed it?

**Comment by DonJayamanne** [comment]
Please can you file a new issue
