### ISSUE TITLE
Same issue as issue 13319 - Cant find the follow up issue

### ISSUE THREAD

**Issue by Joemungandar** [microsoft/vscode-jupyter#16120]
> @Jacob-Stevens-Haas ~Please can you create a new issue, your scenario could be different.~
> 
> Never mind, I'e created a new issue.
> 
> In the future, please create new issues instead of commenting on old closed issues, this ensures we do not miss out on such comments.  

 _Originally posted by @DonJayamanne in [#13319](https://github.com/microsoft/vscode-jupyter/issues/13319#issuecomment-1681432581)_

Sorry if I just have overseen it: I am facing the exact problem mentioned in the Issue 13319 and it is said at the end that there will be a follow-up issue. I cant find it though... can anyone help?

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `trace`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel (use the command `Jupyter: Show Output` to get to the logs).

**Comment by Joemungandar** [comment]
Hi DonJaymanne,

thank you for your quick reply. Unfortunately I dont know, where exactly I can start with "Open Settings & go into Jupyter -> Logging. Maybe I should have mentioned, that I am Using Linux Manjaro as OS, so I am not sure where I can look that up.

When I run `jupyter -h` I get this output in my terminal:
`usage: jupyter [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir] [--paths] [--json]
               [--debug]
               [subcommand]

Jupyter: Interactive Computing

positional arguments:
  subcommand     the subcommand to launch

options:
  -h, --help     show this help message and exit
  --version      show the versions of core jupyter packages and exit
  --config-dir   show Jupyter config dir
  --data-dir     show Jupyter data dir
  --runtime-dir  show Jupyter runtime dir
  --paths        show all Jupyter paths. Add --json for machine-readable format.
  --json         output paths as machine-readable json
  --debug        output debug information about paths

Available subcommands: kernel kernelspec migrate run troubleshoot
`
And `jupyter --paths`

`config:
    /home/<USER>/.jupyter
    /home/<USER>/.local/etc/jupyter
    /usr/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /home/<USER>/.local/share/jupyter
    /usr/share/jupyter
runtime:
    /home/<USER>/.local/share/jupyter/runtime
`

**Comment by DonJayamanne** [comment]
* Please can you describe the exact problem
* Please capture screenshots of the issue
*  know, where exactly I can start with "Open Settings & go into Jupyter -> Logging".
    * Open VS Code then go into the command palette and search for `Open Settings (UI)`
    * Enter the text `Jupyter Logging`
    * Select the value `trace`
    * Save and reload VS Code
* Replicate the issue
* Open your command palette again and select `Jupyter: Show Output`
* Copy all of the output from the output panel and paste it here.

**Comment by Joemungandar** [comment]
Of course, sorry.
My problem is, that I can not run ".ipynb"-Files on my Linux Manjaro Laptop, becase every time, when I press the Button "Select Kernel", I dont get any suggestions of which Kernel I can Pick.
Picture:
![Image](https://github.com/user-attachments/assets/b5f8aaaa-7bc7-48c3-81f8-4da57b404251)

And the Log I get looks like this: (Sorry, this is quite a mess...)
```
Code - OSS (1.93.1, undefined, desktop)
Jupyter Extension Version: 2024.8.1.
Python Extension Version: 2024.14.1.
Pylance Extension not installed.
Platform: linux (x64).
Temp Storage folder ~/.config/Code - OSS/User/globalStorage/ms-toolsai.jupyter/version-2024.8.1
Workspace folder ~/PythonProjects/WB_KI_Oktober2024, Home = /home/raydrake
08:40:46.672 [debug] Start refreshing Kernel Picker (1728888046672)
08:40:46.673 [error] Error in activating extension, failed in gy [Error: Extension 'ms-toolsai.jupyter' CANNOT use API proposal: notebookKernelSource.
Its package.json#enabledApiProposals-property declares:  but NOT notebookKernelSource.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.jupyter
	at P (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:149:59064)
	at Object.createNotebookControllerDetectionTask (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:171:54611)
	at i (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:299:6231)
	at gy.startRefreshWithPython (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:299:6454)
	at gy.activate (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:299:4678)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:373:28494
	at Array.map (<anonymous>)
	at nI.activate (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:373:28480)
	at _G (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:436:2110)
	at async the (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:438:454)]
08:40:46.679 [error] Error in activating extension, failed in Qy [Error: Extension 'ms-toolsai.jupyter' CANNOT use API proposal: notebookKernelSource.
Its package.json#enabledApiProposals-property declares:  but NOT notebookKernelSource.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.jupyter
	at P (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:149:59064)
	at Object.registerKernelSourceActionProvider (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:171:54746)
	at Qy.activate (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:116342)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:373:28494
	at Array.map (<anonymous>)
	at nI.activate (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:373:28480)
	at _G (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:436:2110)
	at async the (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:438:454)]
08:40:46.995 [trace] Search for KernelSpecs in Interpreter /bin/python
08:40:46.996 [trace] Search for KernelSpecs in Interpreter /sbin/python
08:40:46.997 [trace] Search for KernelSpecs in Interpreter /usr/bin/python
08:40:46.998 [trace] Search for KernelSpecs in Interpreter /usr/sbin/python
08:40:46.999 [trace] Kernel Spec for 'Python 3 (ipykernel)' (/usr/share/jupyter/kernels/python3/kernel.json) is hidden. (isDefaultKernelSpec = true, language = python, registrationInfo = undefined)
08:40:47.002 [debug] Get Custom Env Variables, Class name = Cm, completed in 330ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
08:40:47.002 [debug] Jupyter Paths /kernels: 
08:40:47.003 [debug] Kernel Spec Root Paths, /usr/share/jupyter/kernels, /usr/local/share/jupyter/kernels, ~/.local/share/jupyter/kernels
08:40:47.008 [warn] Failed to attach variable provider [Error: Extension 'ms-toolsai.jupyter' CANNOT use API proposal: notebookVariableProvider.
Its package.json#enabledApiProposals-property declares:  but NOT notebookVariableProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.jupyter
	at P (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:149:59064)
	at set variableProvider (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:161:237136)
	at n.create (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:86445)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:101040
	at Array.forEach (<anonymous>)
	at By.addImpl (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:101013)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:99999
	at Array.forEach (<anonymous>)
	at By.batchAdd (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:99969)
	at By.createNotebookControllers (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:98791)
	at By.loadControllersImpl (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:98251)
	at By.loadControllers (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:97901)
	at By.<anonymous> (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:96781)
	at r.B (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.fire (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:949)
	at i.value (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:285:19835)
	at r.B (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.C (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:802)
	at r.fire (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:1018)
	at Zy.buildDummyEnvironment (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:145257)]
08:40:47.009 [warn] Failed to attach variable provider [Error: Extension 'ms-toolsai.jupyter' CANNOT use API proposal: notebookVariableProvider.
Its package.json#enabledApiProposals-property declares:  but NOT notebookVariableProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.jupyter
	at P (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:149:59064)
	at set variableProvider (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:161:237136)
	at n.create (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:86445)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:101040
	at Array.forEach (<anonymous>)
	at By.addImpl (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:101013)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:99999
	at Array.forEach (<anonymous>)
	at By.batchAdd (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:99969)
	at By.createNotebookControllers (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:98791)
	at By.loadControllersImpl (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:98251)
	at By.loadControllers (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:97901)
	at By.<anonymous> (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:96781)
	at r.B (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.fire (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:949)
	at i.value (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:285:19835)
	at r.B (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.C (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:802)
	at r.fire (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:1018)
	at Zy.buildDummyEnvironment (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:145257)]
08:40:47.012 [warn] Failed to attach variable provider [Error: Extension 'ms-toolsai.jupyter' CANNOT use API proposal: notebookVariableProvider.
Its package.json#enabledApiProposals-property declares:  but NOT notebookVariableProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.jupyter
	at P (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:149:59064)
	at set variableProvider (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:161:237136)
	at n.create (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:86445)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:101040
	at Array.forEach (<anonymous>)
	at By.addImpl (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:101013)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:99999
	at Array.forEach (<anonymous>)
	at By.batchAdd (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:99969)
	at By.createNotebookControllers (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:98791)
	at By.loadControllersImpl (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:98251)
	at By.loadControllers (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:97901)
	at By.<anonymous> (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:96781)
	at r.B (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.fire (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:949)
	at i.value (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:285:19835)
	at r.B (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.C (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:802)
	at r.fire (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:1018)
	at Zy.buildDummyEnvironment (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:145257)]
08:40:47.013 [warn] Failed to attach variable provider [Error: Extension 'ms-toolsai.jupyter' CANNOT use API proposal: notebookVariableProvider.
Its package.json#enabledApiProposals-property declares:  but NOT notebookVariableProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.jupyter
	at P (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:149:59064)
	at set variableProvider (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:161:237136)
	at n.create (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:86445)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:101040
	at Array.forEach (<anonymous>)
	at By.addImpl (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:101013)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:99999
	at Array.forEach (<anonymous>)
	at By.batchAdd (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:99969)
	at By.createNotebookControllers (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:98791)
	at By.loadControllersImpl (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:98251)
	at By.loadControllers (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:97901)
	at By.<anonymous> (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:96781)
	at r.B (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.fire (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:949)
	at i.value (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:285:19835)
	at r.B (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.C (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:802)
	at r.fire (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:1018)
	at Zy.buildDummyEnvironment (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:145257)]
08:40:47.016 [warn] Failed to attach variable provider [Error: Extension 'ms-toolsai.jupyter' CANNOT use API proposal: notebookVariableProvider.
Its package.json#enabledApiProposals-property declares:  but NOT notebookVariableProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.jupyter
	at P (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:149:59064)
	at set variableProvider (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:161:237136)
	at n.create (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:86445)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:101040
	at Array.forEach (<anonymous>)
	at By.addImpl (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:101013)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:99999
	at Array.forEach (<anonymous>)
	at By.batchAdd (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:99969)
	at By.createNotebookControllers (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:98791)
	at By.loadControllersImpl (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:98251)
	at By.loadControllers (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:97901)
	at By.<anonymous> (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:96781)
	at r.B (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.fire (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:949)
	at i.value (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:285:19835)
	at r.B (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.C (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:802)
	at r.fire (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:1018)
	at Zy.buildDummyEnvironment (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:145257)]
08:40:47.017 [warn] Failed to attach variable provider [Error: Extension 'ms-toolsai.jupyter' CANNOT use API proposal: notebookVariableProvider.
Its package.json#enabledApiProposals-property declares:  but NOT notebookVariableProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.jupyter
	at P (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:149:59064)
	at set variableProvider (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:161:237136)
	at n.create (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:86445)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:101040
	at Array.forEach (<anonymous>)
	at By.addImpl (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:101013)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:99999
	at Array.forEach (<anonymous>)
	at By.batchAdd (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:99969)
	at By.createNotebookControllers (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:98791)
	at By.loadControllersImpl (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:98251)
	at By.loadControllers (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:97901)
	at By.<anonymous> (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:96781)
	at r.B (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.fire (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:949)
	at i.value (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:285:19835)
	at r.B (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.C (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:802)
	at r.fire (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:1018)
	at Zy.buildDummyEnvironment (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:145257)]
08:40:47.020 [warn] Failed to attach variable provider [Error: Extension 'ms-toolsai.jupyter' CANNOT use API proposal: notebookVariableProvider.
Its package.json#enabledApiProposals-property declares:  but NOT notebookVariableProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.jupyter
	at P (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:149:59064)
	at set variableProvider (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:161:237136)
	at n.create (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:86445)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:101040
	at Array.forEach (<anonymous>)
	at By.addImpl (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:101013)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:99999
	at Array.forEach (<anonymous>)
	at By.batchAdd (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:99969)
	at By.createNotebookControllers (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:98791)
	at By.loadControllersImpl (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:98251)
	at By.loadControllers (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:97901)
	at By.<anonymous> (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:96781)
	at r.B (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.fire (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:949)
	at i.value (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:285:19835)
	at r.B (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.C (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:802)
	at r.fire (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:1018)
	at Zy.buildDummyEnvironment (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:145257)]
08:40:47.021 [warn] Failed to attach variable provider [Error: Extension 'ms-toolsai.jupyter' CANNOT use API proposal: notebookVariableProvider.
Its package.json#enabledApiProposals-property declares:  but NOT notebookVariableProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.jupyter
	at P (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:149:59064)
	at set variableProvider (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:161:237136)
	at n.create (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:86445)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:101040
	at Array.forEach (<anonymous>)
	at By.addImpl (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:101013)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:99999
	at Array.forEach (<anonymous>)
	at By.batchAdd (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:99969)
	at By.createNotebookControllers (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:98791)
	at By.loadControllersImpl (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:98251)
	at By.loadControllers (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:97901)
	at By.<anonymous> (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:96781)
	at r.B (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.fire (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:949)
	at i.value (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:285:19835)
	at r.B (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.C (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:802)
	at r.fire (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:1018)
	at Zy.buildDummyEnvironment (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:145257)]
08:40:47.098 [trace] Conda file is conda
```

**Comment by DonJayamanne** [comment]
> The missing proposal MUST be ad

You are running into this issue because you aren’t using the official version of vscode 
You need to install the official version of vscode

**Comment by Joemungandar** [comment]
```
extra/code 1.93.1-1 (14.9 MiB 87.0 MiB) (Installed)
    The Open Source build of Visual Studio Code (vscode) editor
```

This is unfortunately the only version of vscode I am able to install on Linux Manjaro... Not sure how I can install "the official version of vscode".
Or does this mean in other words, that I cannot use vscode properly from my Linux-Distribution?

**Comment by Joemungandar** [comment]
> Thank you for the logs
> 
> > The missing proposal MUST be ad
> 
> You are running into this issue because you aren’t using the official version of vscode You need to install the official version of vscode
I find it kinda sad, that this issue got closed before I even got the chance to reply...
Can you at least answer me before you close the issue?
