### ISSUE TITLE
Disposing request as the cell (0) was deleted then Dispose Kernel

### ISSUE THREAD

**Issue by yuuuxt** [microsoft/vscode-jupyter#16129]
### Applies To

- [x] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

open a notebook, run some arbitrary cells, wait for a while then running cell gets frozen. Interrupt doesn't work. Select the same kernel again doesn't work.

Reload the window to reset it, and it would start again.

### VS Code Version

1.93.1

### Jupyter Extension Version

2024.8.1

### Jupyter logs

```
Visual Studio Code (1.93.1, ssh-remote, desktop)
Jupyter Extension Version: 2024.8.1.
Python Extension Version: 2024.14.1.
Pylance Extension Version: 2024.10.1.
Platform: linux (x64).

...

23:43:21.232 [info] Kernel successfully started

...

23:46:20.680 [info] Disposing request as the cell (0) was deleted <path_to_notebook>.ipynb
23:46:20.682 [info] Dispose Kernel '<path_to_notebook>.ipynb' associated with '<path_to_notebook>.ipynb'
```

### Running Jupyter locally or remotely?

None

**Comment by DonJayamanne** [comment]
Please can you try disabling auto-save. 
There's a known issue with auto save, if its turned off then you should not run into this issue.
This isn't a solution, but would like to narrow down the issue and figure out if you are running into the same issue.

**Comment by yuuuxt** [comment]
Hi, the auto-save feature has been turned off, in fact I never used that feature.

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `trace`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel (use the command `Jupyter: Show Output` to get to the logs).

**Comment by yuuuxt** [comment]
a complete trace log is as follows:

```
Visual Studio Code (1.93.1, ssh-remote, desktop)
Jupyter Extension Version: 2024.8.1.
Python Extension Version: 2024.14.1.
Pylance Extension Version: 2024.10.1.
Platform: linux (x64).
Temp Storage folder ~/.vscode-server/data/User/globalStorage/ms-toolsai.jupyter/version-2024.8.1
Workspace folder <path-to-the-repo>, Home = <home-folder>
09:23:36.341 [debug] Start refreshing Kernel Picker (1729214616341)
09:23:36.373 [trace] Preferred Remote kernel for <path-to-the-repo>/notebooks/scratch.ipynb is undefined
09:23:36.584 [trace] Search for KernelSpecs in Interpreter /bin/python
09:23:36.586 [trace] Search for KernelSpecs in Interpreter /usr/bin/python
09:23:36.586 [trace] Search for KernelSpecs in Interpreter <path-to-the-repo>/.venv/bin/python
09:23:36.586 [trace] Search for KernelSpecs in Interpreter ~/.pyenv/versions/3.10.12/bin/python
09:23:36.587 [trace] Search for KernelSpecs in Interpreter ~/.pyenv/versions/3.10.13/bin/python
09:23:36.587 [trace] Search for KernelSpecs in Interpreter ~/.pyenv/versions/3.11.7/bin/python
09:23:36.587 [trace] Search for KernelSpecs in Interpreter ~/.pyenv/versions/3.8.10/bin/python
09:23:36.587 [trace] Search for KernelSpecs in Interpreter ~/.pyenv/versions/3.9.17/bin/python
09:23:36.588 [debug] Get Custom Env Variables, Class name = Cm, completed in 247ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
09:23:36.588 [debug] Jupyter Paths /kernels: 
09:23:36.588 [debug] Kernel Spec Root Paths, /usr/share/jupyter/kernels, /usr/local/share/jupyter/kernels, ~/.local/share/jupyter/kernels
09:23:36.596 [trace] No controller, hence notebook communications cannot be initialized for editor <path-to-the-repo>/notebooks/scratch.ipynb
09:23:36.596 [debug] Start refreshing Interpreter Kernel Picker
09:23:36.674 [trace] Hiding default KernelSpec /python for interpreter <path-to-the-repo>/.venv/bin/python (KernelSpec file <path-to-the-repo>/.venv/share/jupyter/kernels/python3/kernel.json)
09:23:36.682 [trace] Python API env change detected, add => '<local-laptop-python.exe>'
09:23:36.683 [trace] No Kernels found in interpreter <local-laptop-python.exe>
09:23:36.837 [debug] KernelProvider switched kernel to id = .jvsc74a57bd00bac6a20ef6f090fa6d1f00c72ce83a550de067dd8c54602d1c750614e225a9c.<path-to-the-repo>/.venv/python.<path-to-the-repo>/.venv/python.-m#ipykernel_launcher
09:23:36.838 [debug] start the kernel, options.disableUI=true for <path-to-the-repo>/notebooks/scratch.ipynb
09:23:36.851 [trace] Registering commtarget jupyter.widget
09:23:36.852 [debug] Controller selection change completed
09:23:36.863 [debug] Get Custom Env Variables, Class name = Cm, completed in 0ms, has a truthy return value, Arg 1: "<path-to-the-repo>", Arg 2: "RunPythonCode"
09:23:36.864 [info] Starting Kernel (Python Path: <path-to-the-repo>/.venv/bin/python, Venv, 3.12.6) for '<path-to-the-repo>/notebooks/scratch.ipynb' (disableUI=true)
09:23:36.864 [trace] Creating raw notebook for resource '<path-to-the-repo>/notebooks/scratch.ipynb'
09:23:36.872 [debug] Get Custom Env Variables, Class name = Cm, completed in 0ms, has a truthy return value, Arg 1: "<path-to-the-repo>/notebooks/scratch.ipynb", Arg 2: "RunPythonCode"
09:23:37.105 [debug] Launching kernel .jvsc74a57bd00bac6a20ef6f090fa6d1f00c72ce83a550de067dd8c54602d1c750614e225a9c.<path-to-the-repo>/.venv/python.<path-to-the-repo>/.venv/python.-m#ipykernel_launcher for <path-to-the-repo>/notebooks/scratch.ipynb in /<path-to-the-repo>/notebooks with ports 9024, 9023, 9027, 9025, 9026
09:23:37.286 [trace] Conda file is conda
09:23:37.372 [debug] Got env vars from Python Ext in 509ms for <path-to-the-repo>/.venv/bin/python, with env var count 60.
09:23:37.372 [trace] Prepend PATH with python bin for <path-to-the-repo>/.venv/bin/python
09:23:37.372 [debug] Getting activated env variables, Class name = gd, completed in 509ms, has a truthy return value, Arg 1: "<path-to-the-repo>", Arg 2: "<path-to-the-repo>/.venv/bin/python", Arg 3: undefined
09:23:37.374 [info] Process Execution: <path-to-the-repo>/.venv/bin/python -m pip list
09:23:37.375 [debug] Got env vars from Python Ext in 503ms for <path-to-the-repo>/.venv/bin/python, with env var count 60.
09:23:37.375 [trace] Prepend PATH with python bin for <path-to-the-repo>/.venv/bin/python
09:23:37.375 [debug] Getting activated env variables, Class name = gd, completed in 503ms, has a truthy return value, Arg 1: "<path-to-the-repo>/notebooks/scratch.ipynb", Arg 2: "<path-to-the-repo>/.venv/bin/python", Arg 3: undefined
09:23:37.376 [info] Process Execution: <path-to-the-repo>/.venv/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
09:23:37.378 [info] Process Execution: <path-to-the-repo>/.venv/bin/python -m ipykernel_launcher --f=/home/~/.local/share/jupyter/runtime/kernel-v3729df144cc26f4174f437bb095dd63db803dd1ed.json
    > cwd: /<path-to-the-repo>/notebooks
09:23:37.378 [debug] Kernel process 1464306.
09:23:37.387 [info] Process Execution: <path-to-the-repo>/.venv/bin/python -c "import pip;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
09:23:37.395 [debug] Module pip is not installed. Output 
09:23:37.455 [trace] ipykernel version & path 6.29.5, <path-to-the-repo>/.venv/lib/python3.12/site-packages/ipykernel/__init__.py for <path-to-the-repo>/.venv/bin/python
09:23:37.552 [debug] Kernel output 1464306: To connect another client to this kernel, use:
--existing kernel-v3729df144cc26f4174f437bb095dd63db803dd1ed.json
09:23:37.593 [debug] Waiting for Raw Session to be ready in postStartRawSession
09:23:37.593 [debug] Waiting for Raw session to be ready, status: connected
09:23:37.593 [trace] Raw session connected
09:23:37.594 [debug] Waited for Raw session to be ready & got status: connected
09:23:37.594 [debug] Successfully waited for Raw Session to be ready in postStartRawSession
09:23:37.594 [debug] Kernel status is 'unknown' before requesting kernel info and after ready
09:23:37.594 [debug] Sending request for kernelInfo
09:23:37.629 [trace] Got response for requestKernelInfo
09:23:37.629 [debug] Successfully completed postStartRawSession after 1 attempt(s) in 35ms
09:23:37.630 [trace] Executing silently Code (idle) = import sys as _VSCODE_sys\nprint(_VSCODE_sys.executable); del _VSCODE_sys
09:23:37.633 [trace] Executing silently Code (completed) = import sys as _VSCODE_sys\nprint(_VSCODE_sys.executable); del _VSCODE_sys with 1 output(s)
09:23:37.633 [trace] Started running kernel initialization for <path-to-the-repo>/notebooks/scratch.ipynb
09:23:37.633 [trace] Executing silently Code (idle) = try:\nimport ipywidgets as _VSCODE_ipywidgets\nprint("e976ee50-99ed-4aba-9b6b-9dcd5634d07d:IPy
09:23:37.636 [trace] Executing silently Code (completed) = try:\nimport ipywidgets as _VSCODE_ipywidgets\nprint("e976ee50-99ed-4aba-9b6b-9dcd5634d07d:IPy with 0 output(s)
09:23:37.636 [trace] Determined IPyWidgets Version as undefined
09:23:37.637 [trace] Executing silently Code (idle) = def __VSCODE_inject_module():\ndef __VSCODE_call_function(function, callback, data=None):
09:23:37.644 [trace] Executing silently Code (completed) = def __VSCODE_inject_module():\ndef __VSCODE_call_function(function, callback, data=None): with 0 output(s)
09:23:37.644 [debug] Requesting Kernel info
09:23:37.644 [trace] Got Kernel info
09:23:37.645 [trace] End running kernel initialization, now waiting for idle
09:23:37.645 [trace] Waiting for idle on (kernel): bb1ca49d-071d-4db8-b7a9-989e100d61e0 -> idle
09:23:37.645 [trace] Finished waiting for idle on (kernel): bb1ca49d-071d-4db8-b7a9-989e100d61e0 -> idle
09:23:37.645 [trace] End running kernel initialization, session is idle
09:23:37.646 [trace] Registering Kernel Completion Provider from kernel .venv (Python 3.12.6) for language python
09:23:37.647 [trace] IPyWidgetScriptSource.initialize
09:23:37.648 [info] Kernel successfully started
09:23:37.649 [debug] getDataDirsImpl, Class name = Mr (started execution), Arg 1: "<path-to-the-repo>/notebooks/scratch.ipynb", Arg 2: "<path-to-the-repo>/.venv/bin/python"
09:23:37.649 [debug] Get Custom Env Variables, Class name = Cm, completed in 0ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
09:23:37.650 [debug] Jupyter Paths : 
09:23:37.653 [info] Process Execution: <path-to-the-repo>/.venv/bin/python /home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.8.1-linux-x64/pythonFiles/printJupyterDataDir.py
09:23:37.664 [debug] Got an empty Jupyter Data Dir from <path-to-the-repo>/.venv/bin/python, stderr = undefined
09:23:37.664 [debug] getDataDirsImpl, Class name = Mr, completed in 15ms, has a truthy return value, Arg 1: "<path-to-the-repo>/notebooks/scratch.ipynb", Arg 2: "<path-to-the-repo>/.venv/bin/python", Return Value: <Uri:/home/~/.local/share/jupyter>, <Uri:<path-to-the-repo>/.venv/share/jupyter>, <Uri:/usr/local/share/jupyter>, <Uri:/usr/share/jupyter>
09:23:38.705 [debug] Controller startUsingPythonInterpreter:'.jvsc74a57bd0f86ea39fb1b7b52ee951baa67d0c8394c3b9635a744de7e75e505756b9a35202.<local-laptop-python.exe>.<local-laptop-python.exe>.-m#ipykernel_launcher' for view = 'jupyter-notebook' is no longer a valid
09:23:38.705 [debug] Controller startUsingPythonInterpreter:'.jvsc74a57bd0f86ea39fb1b7b52ee951baa67d0c8394c3b9635a744de7e75e505756b9a35202.<local-laptop-python.exe>.<local-laptop-python.exe>.-m#ipykernel_launcher (Interactive)' for view = 'interactive' is no longer a valid
09:23:38.706 [warn] Disposing old controller startUsingPythonInterpreter:'.jvsc74a57bd0f86ea39fb1b7b52ee951baa67d0c8394c3b9635a744de7e75e505756b9a35202.<local-laptop-python.exe>.<local-laptop-python.exe>.-m#ipykernel_launcher' for view = 'jupyter-notebook'
09:23:38.706 [debug] Disposing controller .jvsc74a57bd0f86ea39fb1b7b52ee951baa67d0c8394c3b9635a744de7e75e505756b9a35202.<local-laptop-python.exe>.<local-laptop-python.exe>.-m#ipykernel_launcher associated with connection .jvsc74a57bd0f86ea39fb1b7b52ee951baa67d0c8394c3b9635a744de7e75e505756b9a35202.<local-laptop-python.exe>.<local-laptop-python.exe>.-m#ipykernel_launcher 
09:23:38.707 [warn] Disposing old controller startUsingPythonInterpreter:'.jvsc74a57bd0f86ea39fb1b7b52ee951baa67d0c8394c3b9635a744de7e75e505756b9a35202.<local-laptop-python.exe>.<local-laptop-python.exe>.-m#ipykernel_launcher (Interactive)' for view = 'interactive'
09:23:38.707 [debug] Disposing controller .jvsc74a57bd0f86ea39fb1b7b52ee951baa67d0c8394c3b9635a744de7e75e505756b9a35202.<local-laptop-python.exe>.<local-laptop-python.exe>.-m#ipykernel_launcher (Interactive) associated with connection .jvsc74a57bd0f86ea39fb1b7b52ee951baa67d0c8394c3b9635a744de7e75e505756b9a35202.<local-laptop-python.exe>.<local-laptop-python.exe>.-m#ipykernel_launcher 
09:23:38.707 [trace] Python API env change detected, remove => '<local-laptop-python.exe>'
09:23:38.712 [trace] Python API env change detected, update => '<path-to-the-repo>/.venv/bin/python'
09:23:38.713 [trace] Python API env change detected, update => '/home/~/.pyenv/versions/3.10.12/bin/python'
09:23:38.714 [trace] Python API env change detected, update => '/home/~/.pyenv/versions/3.10.13/bin/python'
09:23:38.715 [trace] Python API env change detected, update => '/home/~/.pyenv/versions/3.11.7/bin/python'
09:23:38.716 [trace] Python API env change detected, update => '/home/~/.pyenv/versions/3.8.10/bin/python'
09:23:38.716 [trace] Python API env change detected, update => '/home/~/.pyenv/versions/3.9.17/bin/python'
09:23:38.717 [trace] Python API env change detected, update => '/bin/python'
09:23:38.717 [trace] Python API env change detected, update => '/usr/bin/python'
09:23:38.719 [debug] Refreshed Environments
09:23:39.580 [debug] Interpreter for Pylance for Notebook URI "<path-to-the-repo>/notebooks/scratch.ipynb" is <path-to-the-repo>/.venv/bin/python
09:23:39.708 [debug] Interpreter removed <local-laptop-python.exe>
09:23:48.002 [trace] Disposing Jupyter Lab Helper
09:23:48.002 [trace] SessionManager - dispose contents manager
09:23:48.002 [trace] ShutdownSessionAndConnection - dispose session manager
09:23:48.002 [trace] Finished disposing Jupyter Lab Helper
09:23:48.003 [trace] UniversalRemoteKernelFinder: Writing 1 remote kernel connection metadata to cache
09:23:48.005 [debug] End refreshing Kernel Picker (1729214616341)
09:23:54.268 [debug] Handle Execution of Cells 3 for <path-to-the-repo>/notebooks/scratch.ipynb
09:23:54.270 [trace] Execute Notebook <path-to-the-repo>/notebooks/scratch.ipynb. Step 1
09:23:54.271 [trace] Connect to Kernel <path-to-the-repo>/notebooks/scratch.ipynb. Step 2
09:23:54.272 [trace] Connected to Kernel <path-to-the-repo>/notebooks/scratch.ipynb. Step 3
09:23:54.273 [trace] executeCell 3. Step 4
09:23:54.276 [trace] Cell Index:3 sent to kernel
09:23:54.286 [trace] Start cell 3 execution @ 1729214634286 (clear output)
09:23:54.287 [debug] Kernel acknowledged execution of cell 3 @ 1729214634286
09:23:54.289 [trace] Cell 3 completed in 0.003s (start: 1729214634286, end: 1729214634289)
09:23:54.290 [trace] Cell 3 executed successfully
09:26:37.019 [debug] Disposing kernel associated with <path-to-the-repo>/notebooks/scratch.ipynb, isClosed=true
09:26:37.019 [info] Dispose Kernel '<path-to-the-repo>/notebooks/scratch.ipynb' associated with '<path-to-the-repo>/notebooks/scratch.ipynb'
09:26:37.019 [debug] Cancel pending cells
09:26:37.020 [debug] Shutdown session bb1ca49d-071d-4db8-b7a9-989e100d61e0, .jvsc74a57bd00bac6a20ef6f090fa6d1f00c72ce83a550de067dd8c54602d1c750614e225a9c.<path-to-the-repo>/.venv/python.<path-to-the-repo>/.venv/python.-m#ipykernel_launcher - start called from Error: 
	at R_.shutdown (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.8.1-linux-x64/dist/extension.node.js:304:1140)
	at R_.dispose (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.8.1-linux-x64/dist/extension.node.js:304:623)
	at bs (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.8.1-linux-x64/dist/extension.node.js:115:867)
	at e (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.8.1-linux-x64/dist/extension.node.js:285:31789)
	at n_.dispose (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.8.1-linux-x64/dist/extension.node.js:285:32034)
	at fy.disposeOldKernel (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.8.1-linux-x64/dist/extension.node.js:285:23341)
	at fy.<anonymous> (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.8.1-linux-x64/dist/extension.node.js:285:21548)
	at i.value (/home/~/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/vs/workbench/api/node/extensionHostProcess.js:171:28704)
	at r.B (/home/~/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.C (/home/~/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/vs/workbench/api/node/extensionHostProcess.js:90:802)
	at r.fire (/home/~/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/vs/workbench/api/node/extensionHostProcess.js:90:1018)
	at g.$acceptDocumentAndEditorsDelta (/home/~/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/vs/workbench/api/node/extensionHostProcess.js:166:9528)
	at y.S (/home/~/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/vs/workbench/api/node/extensionHostProcess.js:158:5968)
	at y.Q (/home/~/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/vs/workbench/api/node/extensionHostProcess.js:158:5734)
	at y.M (/home/~/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/vs/workbench/api/node/extensionHostProcess.js:158:4767)
	at y.L (/home/~/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/vs/workbench/api/node/extensionHostProcess.js:158:3823)
	at i.value (/home/~/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/vs/workbench/api/node/extensionHostProcess.js:158:2297)
	at r.B (/home/~/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.fire (/home/~/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/vs/workbench/api/node/extensionHostProcess.js:90:949)
	at a.fire (/home/~/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/vs/workbench/api/node/extensionHostProcess.js:115:14463)
	at i.value (/home/~/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/vs/workbench/api/node/extensionHostProcess.js:184:8635)
	at r.B (/home/~/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.fire (/home/~/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/vs/workbench/api/node/extensionHostProcess.js:90:949)
	at a.fire (/home/~/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/vs/workbench/api/node/extensionHostProcess.js:115:14463)
	at h.A (/home/~/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/vs/workbench/api/node/extensionHostProcess.js:115:17622)
	at i.value (/home/~/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/vs/workbench/api/node/extensionHostProcess.js:115:15980)
	at r.B (/home/~/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.fire (/home/~/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/vs/workbench/api/node/extensionHostProcess.js:90:949)
	at m.acceptChunk (/home/~/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/vs/workbench/api/node/extensionHostProcess.js:115:12209)
	at /home/~/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/vs/workbench/api/node/extensionHostProcess.js:115:11479
	at Socket.b (/home/~/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/vs/workbench/api/node/extensionHostProcess.js:181:14623)
	at Socket.emit (node:events:519:28)
	at addChunk (node:internal/streams/readable:559:12)
	at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
	at Readable.push (node:internal/streams/readable:390:5)
	at Pipe.onStreamRead (node:internal/stream_base_commons:191:23)
09:26:37.020 [debug] Dispose Kernel process 1464306.
09:26:37.023 [debug] Kernel got disposed, hence there is no longer a kernel associated with <path-to-the-repo>/notebooks/scratch.ipynb
09:26:37.024 [debug] Notebook document <path-to-the-repo>/notebooks/scratch.ipynb got closed
09:26:37.025 [debug] Cancel executions after closing notebook <path-to-the-repo>/notebooks/scratch.ipynb
09:26:37.048 [debug] KernelProcess Exited 1464306, Exit Code - undefined 
09:26:37.048 [debug] Disposed Kernel process 1464306.
09:26:37.048 [debug] Shutdown session bb1ca49d-071d-4db8-b7a9-989e100d61e0, .jvsc74a57bd00bac6a20ef6f090fa6d1f00c72ce83a550de067dd8c54602d1c750614e225a9c.<path-to-the-repo>/.venv/python.<path-to-the-repo>/.venv/python.-m#ipykernel_launcher - shutdown complete
```

**Comment by DonJayamanne** [comment]
> 09:26:37.019 [debug] Disposing kernel associated with <path-to-the-repo>/notebooks/scratch.ipynb, isClosed=true

* Can you verify you do not have auto save turned on
* Also while executing , did you manually save the notebook

**Comment by yuuuxt** [comment]
![Image](https://github.com/user-attachments/assets/3c0c1325-f767-48a4-b12b-9eef1bbe39d0)

I didn't save while executing. The cell executed was value `1`. In the log it shows the execution time: `Cell 3 completed in 0.003s`

**Comment by DonJayamanne** [comment]
@yuuuxt Do you have this same notebook in some other editor such as Jupyter Lab or the like or another instance of VS Code?

> 09:26:37.019 [debug] Disposing kernel associated with <path-to-the-repo>/notebooks/scratch.ipynb, isClosed=true

Asking as the above message indicates the fact that the notebook was closed and trying to narrow down this issue.
Thanks, and sorry you are still running into this.
Can you try disabling all extensions except for Jupyter, Python and try this again.

**Comment by yuuuxt** [comment]
>Do you have this same notebook in some other editor such as Jupyter Lab or the like or another instance of VS Code?

No, the repo with the notebook is opened in one vscode instance only.

>Can you try disabling all extensions except for Jupyter, Python and try this again.

Will  do in spare time.

**Comment by alabamagan** [comment]
Any chance you installed extension Continue? Maybe you are encountering this issue https://github.com/continuedev/continue/issues/1463

**Comment by yuuuxt** [comment]
@alabamagan Yes you are right. I downgraded Continue to 0.8.27. It's been 1day till now and the issue hasn't appeared again yet. @DonJayamanne feel free to close the issue, thx.
