### ISSUE TITLE
Linux-Manjaro, VS-Code, Jupyter-Notebook Extension - "Select Kernel" doesnt find anything

### ISSUE THREAD

**Issue by Joemungandar** [microsoft/vscode-jupyter#16127]
This issue:

https://github.com/microsoft/vscode-jupyter/issues/16120

got closed too quickly and the issue still exists for me.
I have installed 
```
extra/code 1.93.1-1 (14.9 MiB 87.0 MiB) (Installed)
    The Open Source build of Visual Studio Code (vscode) editor
```
on my linux manjaro Laptop and that is (as far as I know) the only version that works on Linux manjaro.
The solution of the issue before:
> Thank you for the logs
> 
> > The missing proposal MUST be ad
> 
> You are running into this issue because you aren’t using the official version of vscode You need to install the official version of vscode

Doesnt work for me so I want to know if there is an alternative solution for me.
Here are the jupyter Logs from today:

```
Code - OSS (1.93.1, undefined, desktop)
Jupyter Extension Version: 2024.8.1.
Python Extension Version: 2024.14.1.
Pylance Extension not installed.
Platform: linux (x64).
Temp Storage folder ~/.config/Code - OSS/User/globalStorage/ms-toolsai.jupyter/version-2024.8.1
Workspace folder ~/PythonProjects/WB_KI_Oktober2024, Home = /home/raydrake
08:43:59.093 [debug] Start refreshing Kernel Picker (1729061039093)
08:43:59.094 [error] Error in activating extension, failed in gy [Error: Extension 'ms-toolsai.jupyter' CANNOT use API proposal: notebookKernelSource.
Its package.json#enabledApiProposals-property declares:  but NOT notebookKernelSource.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.jupyter
	at P (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:149:59064)
	at Object.createNotebookControllerDetectionTask (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:171:54611)
	at i (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:299:6231)
	at gy.startRefreshWithPython (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:299:6454)
	at gy.activate (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:299:4678)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:373:28494
	at Array.map (<anonymous>)
	at nI.activate (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:373:28480)
	at _G (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:436:2110)
	at async the (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:438:454)]
08:43:59.101 [error] Error in activating extension, failed in Qy [Error: Extension 'ms-toolsai.jupyter' CANNOT use API proposal: notebookKernelSource.
Its package.json#enabledApiProposals-property declares:  but NOT notebookKernelSource.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.jupyter
	at P (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:149:59064)
	at Object.registerKernelSourceActionProvider (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:171:54746)
	at Qy.activate (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:116342)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:373:28494
	at Array.map (<anonymous>)
	at nI.activate (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:373:28480)
	at _G (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:436:2110)
	at async the (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:438:454)]
08:43:59.170 [trace] Search for KernelSpecs in Interpreter /bin/python
08:43:59.171 [trace] Search for KernelSpecs in Interpreter /sbin/python
08:43:59.171 [trace] Search for KernelSpecs in Interpreter /usr/bin/python
08:43:59.172 [trace] Search for KernelSpecs in Interpreter /usr/sbin/python
08:43:59.172 [trace] Kernel Spec for 'Python 3 (ipykernel)' (/usr/share/jupyter/kernels/python3/kernel.json) is hidden. (isDefaultKernelSpec = true, language = python, registrationInfo = undefined)
08:43:59.174 [debug] Get Custom Env Variables, Class name = Cm, completed in 81ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
08:43:59.174 [debug] Jupyter Paths /kernels: 
08:43:59.175 [debug] Kernel Spec Root Paths, /usr/share/jupyter/kernels, /usr/local/share/jupyter/kernels, ~/.local/share/jupyter/kernels
08:43:59.180 [warn] Failed to attach variable provider [Error: Extension 'ms-toolsai.jupyter' CANNOT use API proposal: notebookVariableProvider.
Its package.json#enabledApiProposals-property declares:  but NOT notebookVariableProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.jupyter
	at P (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:149:59064)
	at set variableProvider (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:161:237136)
	at n.create (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:86445)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:101040
	at Array.forEach (<anonymous>)
	at By.addImpl (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:101013)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:99999
	at Array.forEach (<anonymous>)
	at By.batchAdd (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:99969)
	at By.createNotebookControllers (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:98791)
	at By.loadControllersImpl (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:98251)
	at By.loadControllers (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:97901)
	at By.<anonymous> (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:96781)
	at r.B (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.fire (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:949)
	at i.value (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:285:19835)
	at r.B (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.C (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:802)
	at r.fire (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:1018)
	at Zy.buildDummyEnvironment (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:145257)]
08:43:59.181 [warn] Failed to attach variable provider [Error: Extension 'ms-toolsai.jupyter' CANNOT use API proposal: notebookVariableProvider.
Its package.json#enabledApiProposals-property declares:  but NOT notebookVariableProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.jupyter
	at P (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:149:59064)
	at set variableProvider (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:161:237136)
	at n.create (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:86445)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:101040
	at Array.forEach (<anonymous>)
	at By.addImpl (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:101013)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:99999
	at Array.forEach (<anonymous>)
	at By.batchAdd (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:99969)
	at By.createNotebookControllers (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:98791)
	at By.loadControllersImpl (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:98251)
	at By.loadControllers (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:97901)
	at By.<anonymous> (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:96781)
	at r.B (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.fire (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:949)
	at i.value (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:285:19835)
	at r.B (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.C (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:802)
	at r.fire (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:1018)
	at Zy.buildDummyEnvironment (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:145257)]
08:43:59.182 [warn] Failed to attach variable provider [Error: Extension 'ms-toolsai.jupyter' CANNOT use API proposal: notebookVariableProvider.
Its package.json#enabledApiProposals-property declares:  but NOT notebookVariableProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.jupyter
	at P (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:149:59064)
	at set variableProvider (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:161:237136)
	at n.create (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:86445)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:101040
	at Array.forEach (<anonymous>)
	at By.addImpl (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:101013)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:99999
	at Array.forEach (<anonymous>)
	at By.batchAdd (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:99969)
	at By.createNotebookControllers (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:98791)
	at By.loadControllersImpl (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:98251)
	at By.loadControllers (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:97901)
	at By.<anonymous> (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:96781)
	at r.B (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.fire (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:949)
	at i.value (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:285:19835)
	at r.B (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.C (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:802)
	at r.fire (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:1018)
	at Zy.buildDummyEnvironment (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:145257)]
08:43:59.183 [warn] Failed to attach variable provider [Error: Extension 'ms-toolsai.jupyter' CANNOT use API proposal: notebookVariableProvider.
Its package.json#enabledApiProposals-property declares:  but NOT notebookVariableProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.jupyter
	at P (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:149:59064)
	at set variableProvider (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:161:237136)
	at n.create (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:86445)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:101040
	at Array.forEach (<anonymous>)
	at By.addImpl (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:101013)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:99999
	at Array.forEach (<anonymous>)
	at By.batchAdd (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:99969)
	at By.createNotebookControllers (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:98791)
	at By.loadControllersImpl (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:98251)
	at By.loadControllers (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:97901)
	at By.<anonymous> (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:96781)
	at r.B (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.fire (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:949)
	at i.value (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:285:19835)
	at r.B (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.C (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:802)
	at r.fire (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:1018)
	at Zy.buildDummyEnvironment (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:145257)]
08:43:59.185 [warn] Failed to attach variable provider [Error: Extension 'ms-toolsai.jupyter' CANNOT use API proposal: notebookVariableProvider.
Its package.json#enabledApiProposals-property declares:  but NOT notebookVariableProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.jupyter
	at P (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:149:59064)
	at set variableProvider (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:161:237136)
	at n.create (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:86445)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:101040
	at Array.forEach (<anonymous>)
	at By.addImpl (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:101013)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:99999
	at Array.forEach (<anonymous>)
	at By.batchAdd (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:99969)
	at By.createNotebookControllers (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:98791)
	at By.loadControllersImpl (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:98251)
	at By.loadControllers (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:97901)
	at By.<anonymous> (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:96781)
	at r.B (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.fire (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:949)
	at i.value (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:285:19835)
	at r.B (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.C (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:802)
	at r.fire (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:1018)
	at Zy.buildDummyEnvironment (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:145257)]
08:43:59.185 [warn] Failed to attach variable provider [Error: Extension 'ms-toolsai.jupyter' CANNOT use API proposal: notebookVariableProvider.
Its package.json#enabledApiProposals-property declares:  but NOT notebookVariableProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.jupyter
	at P (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:149:59064)
	at set variableProvider (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:161:237136)
	at n.create (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:86445)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:101040
	at Array.forEach (<anonymous>)
	at By.addImpl (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:101013)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:99999
	at Array.forEach (<anonymous>)
	at By.batchAdd (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:99969)
	at By.createNotebookControllers (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:98791)
	at By.loadControllersImpl (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:98251)
	at By.loadControllers (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:97901)
	at By.<anonymous> (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:96781)
	at r.B (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.fire (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:949)
	at i.value (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:285:19835)
	at r.B (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.C (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:802)
	at r.fire (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:1018)
	at Zy.buildDummyEnvironment (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:145257)]
08:43:59.187 [warn] Failed to attach variable provider [Error: Extension 'ms-toolsai.jupyter' CANNOT use API proposal: notebookVariableProvider.
Its package.json#enabledApiProposals-property declares:  but NOT notebookVariableProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.jupyter
	at P (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:149:59064)
	at set variableProvider (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:161:237136)
	at n.create (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:86445)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:101040
	at Array.forEach (<anonymous>)
	at By.addImpl (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:101013)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:99999
	at Array.forEach (<anonymous>)
	at By.batchAdd (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:99969)
	at By.createNotebookControllers (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:98791)
	at By.loadControllersImpl (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:98251)
	at By.loadControllers (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:97901)
	at By.<anonymous> (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:96781)
	at r.B (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.fire (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:949)
	at i.value (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:285:19835)
	at r.B (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.C (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:802)
	at r.fire (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:1018)
	at Zy.buildDummyEnvironment (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:145257)]
08:43:59.188 [warn] Failed to attach variable provider [Error: Extension 'ms-toolsai.jupyter' CANNOT use API proposal: notebookVariableProvider.
Its package.json#enabledApiProposals-property declares:  but NOT notebookVariableProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api ms-toolsai.jupyter
	at P (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:149:59064)
	at set variableProvider (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:161:237136)
	at n.create (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:86445)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:101040
	at Array.forEach (<anonymous>)
	at By.addImpl (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:101013)
	at /home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:99999
	at Array.forEach (<anonymous>)
	at By.batchAdd (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:99969)
	at By.createNotebookControllers (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:98791)
	at By.loadControllersImpl (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:98251)
	at By.loadControllers (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:97901)
	at By.<anonymous> (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:96781)
	at r.B (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.fire (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:949)
	at i.value (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:285:19835)
	at r.B (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:732)
	at r.C (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:802)
	at r.fire (/usr/lib/code/out/vs/workbench/api/node/extensionHostProcess.js:90:1018)
	at Zy.buildDummyEnvironment (/home/~/.vscode-oss/extensions/ms-toolsai.jupyter-2024.8.1-universal/dist/extension.node.js:304:145257)]
08:43:59.226 [trace] Conda file is conda
08:43:59.379 [debug] creating new code watcher with matching document file:///home/~/PythonProjects/WB_KI_Oktober2024/Tag_04/classifier_formant.py
08:44:00.521 [debug] Start refreshing Interpreter Kernel Picker
08:44:00.566 [trace] No controller, hence notebook communications cannot be initialized for editor ~/PythonProjects/WB_KI_Oktober2024/Tag_01/hello_world.ipynb
08:44:00.857 [trace] Python API env change detected, update => '/bin/python'
08:44:00.860 [trace] Python API env change detected, update => '/sbin/python'
08:44:00.863 [trace] Python API env change detected, update => '/usr/bin/python'
08:44:00.864 [trace] Python API env change detected, update => '/usr/sbin/python'
08:44:00.869 [debug] Refreshed Environments
```

**Comment by Joemungandar** [comment]
Okay, I found a solution
When I start code like this:
`code --enable-proposed-api ms-toolsai.jupyter --enable-proposed-api ms-python.python`

I can select the kerne
