### ISSUE TITLE
Failed to start the Kernel - Forbidden Error

### ISSUE THREAD

**Issue by Johnnsy1024** [microsoft/vscode-jupyter#16131]
## Environment data

-   VS Code version: 1.94.2 (Universal)
-   Jupyter Extension version (available under the Extensions sidebar): V2024.10.2024100401
-   Python Extension version (available under the Extensions sidebar): v2024.16.1
-   OS (Windows | Mac | Linux distro) and version: Linux distro
-   Python and/or Anaconda version: 3.11.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): uv
-   Jupyter server running: Remote

## Expected behaviour

Run jupyter cell successfully

## Actual behaviour
![Image](https://github.com/user-attachments/assets/f88ed329-3f9b-4e01-8ce0-e05eef8e74ab)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

Error occurred while trying to start the kernel, options.disableUI=true Error: Forbidden     > at new n (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.2024100401-linux-x64/dist/extension.node.js:98:4480)     > originalException = Error: Forbidden

**Comment by DonJayamanne** [comment]
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `trace`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel (use the command `Jupyter: Show Output` to get to the logs).

**Comment by Johnnsy1024** [comment]
OK, I follow your suggestions and get the detailed log as follows:

17:39:45.238 [error] Error in execution (get message for cell) [iy [Error]: 
	at new n (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.2024100401-linux-x64/dist/extension.node.js:98:4480)
	at new iy (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.2024100401-linux-x64/dist/extension.node.js:282:27198)
	at tu.createNewSession (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.2024100401-linux-x64/dist/extension.node.js:285:5302)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async tu.connectToOrCreateSession (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.2024100401-linux-x64/dist/extension.node.js:285:4277)
	at async tu.create (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.2024100401-linux-x64/dist/extension.node.js:285:1980)
	at async i_.createJupyterSession (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.2024100401-linux-x64/dist/extension.node.js:285:35993)
	at async i_.startJupyterSession (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.2024100401-linux-x64/dist/extension.node.js:285:34001)
	at async n.wrapKernelMethodImpl (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.2024100401-linux-x64/dist/extension.node.js:304:82604)

Error: Forbidden
	at r.create (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.2024100401-linux-x64/dist/node_modules/@jupyterlab/services.js:11:1006)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Object.jh [as startSession] (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.2024100401-linux-x64/dist/node_modules/@jupyterlab/services.js:11:53619)
	at async pi.startNew (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.2024100401-linux-x64/dist/node_modules/@jupyterlab/services.js:11:59886)
	at async tu.createNewSession (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.2024100401-linux-x64/dist/extension.node.js:285:5045)
	at async tu.connectToOrCreateSession (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.2024100401-linux-x64/dist/extension.node.js:285:4277)
	at async tu.create (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.2024100401-linux-x64/dist/extension.node.js:285:1980)
	at async i_.createJupyterSession (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.2024100401-linux-x64/dist/extension.node.js:285:35993)
	at async i_.startJupyterSession (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.2024100401-linux-x64/dist/extension.node.js:285:34001)
	at async n.wrapKernelMethodImpl (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.2024100401-linux-x64/dist/extension.node.js:304:82604)] {
  category: 'unknown',
  isJupyterError: true,
  originalException: [r [Error]: Forbidden
  	at r.create (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.2024100401-linux-x64/dist/node_modules/@jupyterlab/services.js:11:1006)
  	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  	at async Object.jh [as startSession] (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.2024100401-linux-x64/dist/node_modules/@jupyterlab/services.js:11:53619)
  	at async pi.startNew (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.2024100401-linux-x64/dist/node_modules/@jupyterlab/services.js:11:59886)
  	at async tu.createNewSession (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.2024100401-linux-x64/dist/extension.node.js:285:5045)
  	at async tu.connectToOrCreateSession (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.2024100401-linux-x64/dist/extension.node.js:285:4277)
  	at async tu.create (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.2024100401-linux-x64/dist/extension.node.js:285:1980)
  	at async i_.createJupyterSession (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.2024100401-linux-x64/dist/extension.node.js:285:35993)
  	at async i_.startJupyterSession (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.2024100401-linux-x64/dist/extension.node.js:285:34001)
  	at async n.wrapKernelMethodImpl (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.2024100401-linux-x64/dist/extension.node.js:304:82604)] {
    response: p [Response] {
      size: 0,
      timeout: 0,
      [Symbol(Body internals)]: [Object],
      [Symbol(Response internals)]: [Object]
    },
    traceback: ''
  }
}
17:39:45.304 [trace] Cell 0 completed in 0s (start: undefined, end: undefined)

And what should I do next?
Thanks

**Comment by DonJayamanne** [comment]
Please can you share the full logs,
I need all of the logs, as I'd like to get the version infomraiton, Python version, startup information, etc all from the logs.
