### ISSUE TITLE
ref system dll version inconsistent

### ISSUE THREAD

**Issue by nczsl** [microsoft/vscode-jupyter#16303]
### Applies To

- [ ] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

error CS1705: 标识为“Synario.BizModel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null”的程序集“Synario.BizModel”所使用的“System.Data.Common, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”版本高于所引用的标识为“System.Data.Common, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”的程序集“System.Data.Common”

error CS1705: 标识为“Synario.BizModel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null”的程序集“Synario.BizModel”所使用的“System.Data.Common, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”版本高于所引用的标识为“System.Data.Common, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”的程序集“System.Data.Common”

error CS1705: 标识为“Synario.BizModel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null”的程序集“Synario.BizModel”所使用的“System.Data.Common, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”版本高于所引用的标识为“System.Data.Common, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”的程序集“System.Data.Common”

//----------------------------
<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Synario.CodeModel\Synario.CodeModel.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    
  </PropertyGroup>

</Project>

```csharp
//gen.csx
#load "./common.csx"
using Synario.Util;
using Synario.CodeModel;
using Synario.BizModel;
// using System.Data;

Console.WriteLine("load Synario.BizModel successed!");

public BizAgent LoadTestBizAgent() {
  var bizag = new BizAgent("TestBizAgent");
  var dbag = new DbAgent("TestDBAgent");
  var table1 = new MetaType("User"); // MetaType : DataTable
  table1.Columns.Add("Id", typeof(int));
  table1.Columns.Add("Name", typeof(string));
  table1.Columns.Add("Age", typeof(int));
  dbag.AddTable(table1);
  var table2 = new MetaType("Order");
  table2.Columns.Add("Id", typeof(int));
  table2.Columns.Add("UserId", typeof(int));
  table2.Columns.Add("Amount", typeof(decimal));
  dbag.AddTable(table2);
```
```csharp
// common.csx:
#r "./dist/Synario.Util.dll"
#r "./dist/Synario.CodeModel.dll"
#r "./dist/Synario.BizModel.dll"
```
at the ipynb cell:
#load "./gen.csx"

report this error!

### VS Code Version

1.96.0 138f619c86f1199955d53b4166bef66ef252935c x64

### Jupyter Extension Version

latest

### Jupyter logs

```shell
Visual Studio Code (1.96.0, undefined, desktop)
Jupyter Extension Version: 2024.11.0.
Python Extension not installed.
Pylance Extension not installed.
Platform: win32 (x64).
Temp Storage folder ~\AppData\Roaming\Code\User\globalStorage\ms-toolsai.jupyter\version-2024.11.0
Workspace folder e:\netenv, Home = c:\Users\hjjls
16:19:07.300 [info] Starting Kernel (.NET (C#)) for 'e:\netenv\tool\lab\Synario.BizModel\_main.ipynb' (disableUI=true)
16:19:12.978 [info] Launching Raw Kernel .NET (C#) # dotnet
16:19:13.000 [info] Process Execution: dotnet interactive jupyter --default-kernel csharp c:\Users\~\AppData\Roaming\jupyter\runtime\kernel-v375ce052f33ab8ef7a2c273a4e5f6c6c334d0b392.json --http-port-range 2048-3000
    > cwd: e:\netenv\tool\lab\Synario.BizModel
16:19:22.475 [warn] Kernel completions not enabled for '.NET (C#)'. 
To enable Kernel completion for this language please add the following setting 
jupyter.completionTriggerCharacters = {c#: [<List of characters that will trigger completions>]}. 
 or the following: 
jupyter.completionTriggerCharacters = {csharp: [<List of characters that will trigger completions>]}. 
For more information please see https://aka.ms/vscodeJupyterCompletion
16:19:22.476 [info] Kernel successfully started
16:21:50.046 [warn] No nbextensions folder found for kernel ..net-csharp.dotnet.\.dotnet#interactive#jupyter#--default-kernel#csharp#{connection_file}#--http-port-range#2048-3000
16:22:29.166 [warn] Cell completed with errors iu [Error]: compilation error
    at n.execute (c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.11.0-win32-x64\dist\extension.node.js:297:4958) {
  ename: 'Error',
  evalue: 'compilation error',
  traceback: []
}
17:36:49.185 [warn] Cell completed with errors iu [Error]: compilation error
    at n.execute (c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.11.0-win32-x64\dist\extension.node.js:297:4958) {
  ename: 'Error',
  evalue: 'compilation error',
  traceback: []
}
17:36:58.475 [warn] Cell completed with errors iu [Error]: compilation error
    at n.execute (c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.11.0-win32-x64\dist\extension.node.js:297:4958) {
  ename: 'Error',
  evalue: 'compilation error',
  traceback: []
}
17:39:43.618 [info] Starting Kernel (.NET (C#)) for 'e:\netenv\tool\lab\newfeature.ipynb' (disableUI=true)
17:39:43.776 [info] Launching Raw Kernel .NET (C#) # dotnet
17:39:43.802 [info] Process Execution: dotnet interactive jupyter --default-kernel csharp c:\Users\~\AppData\Roaming\jupyter\runtime\kernel-v3c2fd5ef58d7c846e9a9a84af6bf202d1eccecfc5.json --http-port-range 2048-3000
    > cwd: e:\netenv\tool\lab
17:39:48.135 [info] Dispose Kernel 'e:\netenv\tool\lab\newfeature.ipynb' associated with 'e:\netenv\tool\lab\newfeature.ipynb'
17:39:48.154 [info] Process Execution: c:\Windows\System32\taskkill.exe /F /T /PID 15944
17:39:48.157 [warn] Failed to shutdown kernel, ..net-csharp.dotnet.\.dotnet#interactive#jupyter#--default-kernel#csharp#{connection_file}#--http-port-range#2048-3000 TypeError: Cannot read properties of undefined (reading 'dispose')
    at $_.shutdown (c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.11.0-win32-x64\dist\extension.node.js:304:13745)
    at q_.shutdown (c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.11.0-win32-x64\dist\extension.node.js:304:22578)
18:08:08.370 [warn] Cell completed with errors iu [Error]: compilation error
    at n.execute (c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.11.0-win32-x64\dist\extension.node.js:297:4958) {
  ename: 'Error',
  evalue: 'compilation error',
  traceback: []
}
18:11:06.011 [warn] Cell completed with errors iu [Error]: compilation error
    at n.execute (c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.11.0-win32-x64\dist\extension.node.js:297:4958) {
  ename: 'Error',
  evalue: 'compilation error',
  traceback: []
}
18:11:07.583 [warn] Cell completed with errors iu [Error]: compilation error
    at n.execute (c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.11.0-win32-x64\dist\extension.node.js:297:4958) {
  ename: 'Error',
  evalue: 'compilation error',
  traceback: []
}
18:11:08.244 [warn] Cell completed with errors iu [Error]: compilation error
    at n.execute (c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.11.0-win32-x64\dist\extension.node.js:297:4958) {
  ename: 'Error',
  evalue: 'compilation error',
  traceback: []
}
18:11:08.924 [warn] Cell completed with errors iu [Error]: compilation error
    at n.execute (c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.11.0-win32-x64\dist\extension.node.js:297:4958) {
  ename: 'Error',
  evalue: 'compilation error',
  traceback: []
}
18:14:35.261 [warn] Cell completed with errors iu [Error]: compilation error
    at n.execute (c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.11.0-win32-x64\dist\extension.node.js:297:4958) {
  ename: 'Error',
  evalue: 'compilation error',
  traceback: []
}
18:14:36.308 [warn] Cell completed with errors iu [Error]: compilation error
    at n.execute (c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.11.0-win32-x64\dist\extension.node.js:297:4958) {
  ename: 'Error',
  evalue: 'compilation error',
  traceback: []
}
18:14:37.042 [warn] Cell completed with errors iu [Error]: compilation error
    at n.execute (c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.11.0-win32-x64\dist\extension.node.js:297:4958) {
  ename: 'Error',
  evalue: 'compilation error',
  traceback: []
}
18:16:26.891 [warn] Cell completed with errors iu [Error]: compilation error
    at n.execute (c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.11.0-win32-x64\dist\extension.node.js:297:4958) {
  ename: 'Error',
  evalue: 'compilation error',
  traceback: []
}
18:16:27.690 [warn] Cell completed with errors iu [Error]: compilation error
    at n.execute (c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.11.0-win32-x64\dist\extension.node.js:297:4958) {
  ename: 'Error',
  evalue: 'compilation error',
  traceback: []
}
18:23:10.428 [warn] Cell completed with errors iu [Error]: compilation error
    at n.execute (c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.11.0-win32-x64\dist\extension.node.js:297:4958) {
  ename: 'Error',
  evalue: 'compilation error',
  traceback: []
}
18:23:27.501 [warn] Cell completed with errors iu [Error]: compilation error
    at n.execute (c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.11.0-win32-x64\dist\extension.node.js:297:4958) {
  ename: 'Error',
  evalue: 'compilation error',
  traceback: []
}
18:25:15.675 [warn] Cell completed with errors iu [Error]: compilation error
    at n.execute (c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.11.0-win32-x64\dist\extension.node.js:297:4958) {
  ename: 'Error',
  evalue: 'compilation error',
  traceback: []
}
18:34:35.161 [warn] Cell completed with errors iu [Error]: compilation error
    at n.execute (c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.11.0-win32-x64\dist\extension.node.js:297:4958) {
  ename: 'Error',
  evalue: 'compilation error',
  traceback: []
}
18:34:37.015 [warn] Cell completed with errors iu [Error]: compilation error
    at n.execute (c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.11.0-win32-x64\dist\extension.node.js:297:4958) {
  ename: 'Error',
  evalue: 'compilation error',
  traceback: []
}
18:36:11.161 [warn] Cell completed with errors iu [Error]: compilation error
    at n.execute (c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.11.0-win32-x64\dist\extension.node.js:297:4958) {
  ename: 'Error',
  evalue: 'compilation error',
  traceback: []
}
18:37:06.965 [warn] Cell completed with errors iu [Error]: compilation error
    at n.execute (c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.11.0-win32-x64\dist\extension.node.js:297:4958) {
  ename: 'Error',
  evalue: 'compilation error',
  traceback: []
}
```

### Running Jupyter locally or remotely?

None

**Comment by nczsl** [comment]
when i try -f net 8.0 of dotnet command ,this problem is soloved
