### ISSUE TITLE
Jupyter kernel fails after ~3minutes

### ISSUE THREAD

**Issue by mayurmadnani** [microsoft/vscode-jupyter#16337]
### Applies To

- [x] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

From a few weeks I am getting this weird error where the jupyter notebooks gets disconnected and then not able to recognize any python kernels. If there is a cell executing, it is stuck and kernel reset or interruption also does not work. The only way out is to close vscode and start again. I timed it and seems to be reproducible every 3 mins. Attached one such instance logs. Somehow trying out previous versions also didn't help.

![Image](https://github.com/user-attachments/assets/7fe4974c-8719-473d-99d4-2cf837b8249a)

### VS Code Version

Version: 1.96.2 (system setup) Commit: fabdb6a30b49f79a7aba0f2ad9df9b399473380f Date: 2024-12-19T10:22:47.216Z Electron: 32.2.6 ElectronBuildId: 10629634 Chromium: 128.0.6613.186 Node.js: 20.18.1 V8: 12.8.374.38-electron.0 OS: Windows_NT x64 10.0.26100

### Jupyter Extension Version

2024.11.0

### Jupyter logs

```shell
Visual Studio Code (1.96.2, wsl, desktop)
Jupyter Extension Version: 2024.11.0.
Python Extension Version: 2024.22.1.
Pylance Extension Version: 2024.12.1.
Platform: linux (x64).
Temp Storage folder ~/.vscode-server/data/User/globalStorage/ms-toolsai.jupyter/version-2024.11.0
Workspace folder ~/workspace/temp, Home = /home/mayur
23:23:09.360 [info] Telemetry level is off
23:23:09.361 [info] Experiments are disabled, only manually opted experiments are active.
23:23:09.639 [debug] Start refreshing Kernel Picker (1735062789639)
23:23:10.198 [trace] No controller, hence notebook communications cannot be initialized for editor ~/workspace/temp/Book.ipynb
23:23:10.199 [debug] Start refreshing Interpreter Kernel Picker
23:23:11.571 [trace] Search for KernelSpecs in Interpreter /bin/python3
23:23:11.572 [trace] Search for KernelSpecs in Interpreter ~/miniconda3/bin/python
23:23:11.573 [trace] Search for KernelSpecs in Interpreter ~/miniconda3/envs/py310/bin/python
23:23:11.574 [trace] Search for KernelSpecs in Interpreter ~/miniconda3/envs/py313/bin/python
23:23:11.574 [trace] Search for KernelSpecs in Interpreter ~/miniconda3/envs/venv/bin/python
23:23:11.575 [trace] Search for KernelSpecs in Interpreter /bin/python
23:23:11.588 [debug] Get Custom Env Variables, Class name = Pm, completed in 1949ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
23:23:11.588 [debug] Jupyter Paths /kernels: 
23:23:11.592 [debug] Kernel Spec Root Paths, /usr/share/jupyter/kernels, /usr/local/share/jupyter/kernels, ~/.local/share/jupyter/kernels
23:23:12.299 [debug] KernelProvider switched kernel to id = .jvsc74a57bd017fe52e937ac4df3c5b3a61ea03b64884e6169803108c807918a0b3ad1b3f8db./home/~/miniconda3/envs/venv/python./home/~/miniconda3/envs/venv/python.-m#ipykernel_launcher
23:23:12.300 [debug] start the kernel, options.disableUI=true for ~/workspace/temp/Book.ipynb
23:23:12.314 [debug] Controller selection change completed
23:23:12.393 [debug] Get Custom Env Variables, Class name = Pm, completed in 4ms, has a truthy return value, Arg 1: "~/workspace/temp", Arg 2: "RunPythonCode"
23:23:12.397 [info] Starting Kernel (Python Path: ~/miniconda3/envs/venv/bin/python, Conda, 3.10.13) for '~/workspace/temp/Book.ipynb' (disableUI=true)
23:23:12.399 [trace] Creating raw notebook for resource '~/workspace/temp/Book.ipynb'
23:23:12.473 [debug] Get Custom Env Variables, Class name = Pm, completed in 1ms, has a truthy return value, Arg 1: "~/workspace/temp/Book.ipynb", Arg 2: "RunPythonCode"
23:23:12.548 [trace] Hiding default KernelSpec ~/miniconda3/envs/venv/bin/python for interpreter ~/miniconda3/envs/venv/bin/python (KernelSpec file ~/miniconda3/envs/venv/share/jupyter/kernels/python3/kernel.json)
23:23:12.674 [debug] Launching kernel .jvsc74a57bd017fe52e937ac4df3c5b3a61ea03b64884e6169803108c807918a0b3ad1b3f8db./home/~/miniconda3/envs/venv/python./home/~/miniconda3/envs/venv/python.-m#ipykernel_launcher for ~/workspace/temp/Book.ipynb in //home/~/workspace/temp with ports 9001, 9000, 9004, 9002, 9003
23:23:14.249 [debug] Interpreter for Pylance for Notebook URI "~/workspace/temp/Book.ipynb" is ~/miniconda3/envs/venv/bin/python
23:23:14.376 [trace] Conda file is conda
23:23:14.566 [trace] Python API env change detected, update => '/bin/python'
23:23:14.569 [trace] Python API env change detected, update => '/bin/python3'
23:23:14.571 [trace] Python API env change detected, update => '/home/~/miniconda3/bin/python'
23:23:14.573 [trace] Python API env change detected, update => '/home/~/miniconda3/envs/py310/bin/python'
23:23:14.575 [trace] Python API env change detected, update => '/home/~/miniconda3/envs/py313/bin/python'
23:23:14.577 [trace] Python API env change detected, update => '/home/~/miniconda3/envs/venv/bin/python'
23:23:14.585 [debug] Refreshed Environments
23:23:15.586 [debug] End refreshing Kernel Picker (1735062789639)
23:23:16.717 [debug] Got env vars from Python Ext in 4328ms for ~/miniconda3/envs/venv/bin/python, with env var count 51.
23:23:16.717 [trace] Prepend PATH with python bin for ~/miniconda3/envs/venv/bin/python
23:23:16.718 [debug] Getting activated env variables, Class name = Sd, completed in 4330ms, has a truthy return value, Arg 1: "~/workspace/temp", Arg 2: "~/miniconda3/envs/venv/bin/python", Arg 3: undefined
23:23:16.723 [info] Process Execution: ~/miniconda3/envs/venv/bin/python -m pip list
23:23:16.730 [debug] Got env vars from Python Ext in 4258ms for ~/miniconda3/envs/venv/bin/python, with env var count 51.
23:23:16.730 [trace] Prepend PATH with python bin for ~/miniconda3/envs/venv/bin/python
23:23:16.731 [debug] Getting activated env variables, Class name = Sd, completed in 4259ms, has a truthy return value, Arg 1: "~/workspace/temp/Book.ipynb", Arg 2: "~/miniconda3/envs/venv/bin/python", Arg 3: undefined
23:23:16.735 [info] Process Execution: ~/miniconda3/envs/venv/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
23:23:16.741 [info] Process Execution: ~/miniconda3/envs/venv/bin/python -m ipykernel_launcher --f=/home/~/.local/share/jupyter/runtime/kernel-v3cdf37f3da6a6b66c68f001e3b3e6b3d2b713406b.json
    > cwd: //home/~/workspace/temp
23:23:16.741 [debug] Kernel process 11220.
23:23:17.073 [trace] ipykernel version & path 6.29.5, ~/miniconda3/envs/venv/lib/python3.10/site-packages/ipykernel/__init__.py for ~/miniconda3/envs/venv/bin/python
23:23:17.407 [debug] Kernel output 11220: To connect another client to this kernel, use:
--existing kernel-v3cdf37f3da6a6b66c68f001e3b3e6b3d2b713406b.json
23:23:17.665 [debug] Waiting for Raw Session to be ready in postStartRawSession
23:23:17.665 [debug] Waiting for Raw session to be ready, status: connected
23:23:17.665 [trace] Raw session connected
23:23:17.666 [debug] Waited for Raw session to be ready & got status: connected
23:23:17.666 [debug] Successfully waited for Raw Session to be ready in postStartRawSession
23:23:17.666 [debug] Kernel status is 'unknown' before requesting kernel info and after ready
23:23:17.666 [debug] Sending request for kernelInfo
23:23:17.717 [trace] Got response for requestKernelInfo
23:23:17.717 [debug] Successfully completed postStartRawSession after 1 attempt(s) in 51ms
23:23:17.720 [trace] Executing silently Code (idle) = import sys as _VSCODE_sys\nprint(_VSCODE_sys.executable); del _VSCODE_sys
23:23:17.735 [trace] Executing silently Code (completed) = import sys as _VSCODE_sys\nprint(_VSCODE_sys.executable); del _VSCODE_sys with 1 output(s)
23:23:17.736 [trace] Started running kernel initialization for ~/workspace/temp/Book.ipynb
23:23:17.737 [trace] Executing silently Code (idle) = try:\nimport ipywidgets as _VSCODE_ipywidgets\nprint("e976ee50-99ed-4aba-9b6b-9dcd5634d07d:IPy
23:23:17.826 [trace] Executing silently Code (completed) = try:\nimport ipywidgets as _VSCODE_ipywidgets\nprint("e976ee50-99ed-4aba-9b6b-9dcd5634d07d:IPy with 1 output(s)
23:23:17.826 [trace] Determined IPyWidgets Version as 8
23:23:17.827 [trace] Executing silently Code (idle) = def __VSCODE_inject_module():\ndef __VSCODE_call_function(function, callback, data=None):
23:23:17.845 [trace] Executing silently Code (completed) = def __VSCODE_inject_module():\ndef __VSCODE_call_function(function, callback, data=None): with 0 output(s)
23:23:17.845 [debug] Requesting Kernel info
23:23:17.846 [trace] Got Kernel info
23:23:17.846 [trace] End running kernel initialization, now waiting for idle
23:23:17.847 [trace] Waiting for idle on (kernel): 73f5243b-7558-4c99-ba07-e4081b737958 -> idle
23:23:17.847 [trace] Finished waiting for idle on (kernel): 73f5243b-7558-4c99-ba07-e4081b737958 -> idle
23:23:17.847 [trace] End running kernel initialization, session is idle
23:23:17.849 [trace] Registering Kernel Completion Provider from kernel venv (Python 3.10.13) for language python
23:23:17.850 [info] Kernel successfully started
23:23:29.127 [trace] IPyWidgetScriptSource.initialize
23:23:29.128 [trace] Registering commtarget jupyter.widget
23:23:29.131 [trace] Version of IPyWidgets 8 determined after 0.002s
23:23:29.131 [debug] getDataDirsImpl, Class name = Kr (started execution), Arg 1: "~/workspace/temp/Book.ipynb", Arg 2: "~/miniconda3/envs/venv/bin/python"
23:23:29.133 [debug] Get Custom Env Variables, Class name = Pm, completed in 1ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
23:23:29.133 [debug] Jupyter Paths : 
23:23:29.137 [debug] Get Custom Env Variables, Class name = Pm, completed in 1ms, has a truthy return value, Arg 1: "~/workspace/temp/Book.ipynb", Arg 2: "RunPythonCode"
23:23:29.138 [debug] Got env vars from Python Ext in 2ms for ~/miniconda3/envs/venv/bin/python, with env var count 51.
23:23:29.138 [trace] Prepend PATH with python bin for ~/miniconda3/envs/venv/bin/python
23:23:29.139 [debug] Getting activated env variables, Class name = Sd, completed in 3ms, has a truthy return value, Arg 1: "~/workspace/temp/Book.ipynb", Arg 2: "~/miniconda3/envs/venv/bin/python", Arg 3: undefined
23:23:29.143 [info] Process Execution: ~/miniconda3/envs/venv/bin/python /home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.11.0-linux-x64/pythonFiles/printJupyterDataDir.py
23:23:29.160 [debug] getDataDirsImpl, Class name = Kr, completed in 29ms, has a truthy return value, Arg 1: "~/workspace/temp/Book.ipynb", Arg 2: "~/miniconda3/envs/venv/bin/python", Return Value: <Uri:/home/~/.local/share/jupyter>, <Uri:/home/~/miniconda3/envs/venv/share/jupyter>, <Uri:/usr/local/share/jupyter>, <Uri:/usr/share/jupyter>
23:23:34.431 [debug] Handle Execution of Cells 0 for ~/workspace/temp/Book.ipynb
23:23:34.433 [trace] Execute Notebook ~/workspace/temp/Book.ipynb. Step 1
23:23:34.433 [trace] Connect to Kernel ~/workspace/temp/Book.ipynb. Step 2
23:23:34.434 [trace] Connected to Kernel ~/workspace/temp/Book.ipynb. Step 3
23:23:34.434 [trace] executeCell 0. Step 4
23:23:34.437 [trace] Cell Index:0 sent to kernel
23:23:34.445 [trace] Start cell 0 execution @ 1735062814444 (clear output)
23:23:34.445 [debug] Kernel acknowledged execution of cell 0 @ 1735062814444
23:23:34.456 [trace] Cell 0 completed in 0.012s (start: 1735062814444, end: 1735062814456)
23:23:34.457 [trace] Cell 0 executed successfully
23:23:39.769 [debug] Handle Execution of Cells 1 for ~/workspace/temp/Book.ipynb
23:23:39.770 [trace] Execute Notebook ~/workspace/temp/Book.ipynb. Step 1
23:23:39.771 [trace] Connect to Kernel ~/workspace/temp/Book.ipynb. Step 2
23:23:39.771 [trace] Connected to Kernel ~/workspace/temp/Book.ipynb. Step 3
23:23:39.771 [trace] executeCell 1. Step 4
23:23:39.771 [trace] Cell Index:1 sent to kernel
23:23:39.778 [trace] Start cell 1 execution @ 1735062819778 (clear output)
23:23:39.778 [debug] Kernel acknowledged execution of cell 1 @ 1735062819778
23:23:39.786 [trace] Cell 1 completed in 0.008s (start: 1735062819778, end: 1735062819786)
23:23:39.787 [trace] Cell 1 executed successfully
23:26:33.451 [debug] Disposing kernel associated with ~/workspace/temp/Book.ipynb, isClosed=true, reason = notebookClosed
23:26:33.451 [info] Dispose Kernel '~/workspace/temp/Book.ipynb' associated with '~/workspace/temp/Book.ipynb'
23:26:33.452 [debug] Cancel pending cells
23:26:33.453 [debug] Shutdown session 73f5243b-7558-4c99-ba07-e4081b737958, .jvsc74a57bd017fe52e937ac4df3c5b3a61ea03b64884e6169803108c807918a0b3ad1b3f8db./home/~/miniconda3/envs/venv/python./home/~/miniconda3/envs/venv/python.-m#ipykernel_launcher - start called from Error: 
	at L_.shutdown (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.11.0-linux-x64/dist/extension.node.js:304:1140)
	at L_.dispose (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.11.0-linux-x64/dist/extension.node.js:304:623)
	at bs (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.11.0-linux-x64/dist/extension.node.js:115:867)
	at e (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.11.0-linux-x64/dist/extension.node.js:285:32446)
	at d_.dispose (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.11.0-linux-x64/dist/extension.node.js:285:32691)
	at Sy.disposeOldKernel (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.11.0-linux-x64/dist/extension.node.js:285:23544)
	at Sy.<anonymous> (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.11.0-linux-x64/dist/extension.node.js:285:21600)
	at Sh.value (file:///home/~/.vscode-server/bin/fabdb6a30b49f79a7aba0f2ad9df9b399473380f/out/vs/workbench/api/node/extensionHostProcess.js:157:35593)
	at P.B (file:///home/~/.vscode-server/bin/fabdb6a30b49f79a7aba0f2ad9df9b399473380f/out/vs/workbench/api/node/extensionHostProcess.js:30:746)
	at P.C (file:///home/~/.vscode-server/bin/fabdb6a30b49f79a7aba0f2ad9df9b399473380f/out/vs/workbench/api/node/extensionHostProcess.js:30:816)
	at P.fire (file:///home/~/.vscode-server/bin/fabdb6a30b49f79a7aba0f2ad9df9b399473380f/out/vs/workbench/api/node/extensionHostProcess.js:30:1033)
	at gh.$acceptDocumentAndEditorsDelta (file:///home/~/.vscode-server/bin/fabdb6a30b49f79a7aba0f2ad9df9b399473380f/out/vs/workbench/api/node/extensionHostProcess.js:156:13127)
	at Dy.S (file:///home/~/.vscode-server/bin/fabdb6a30b49f79a7aba0f2ad9df9b399473380f/out/vs/workbench/api/node/extensionHostProcess.js:32:158049)
	at Dy.Q (file:///home/~/.vscode-server/bin/fabdb6a30b49f79a7aba0f2ad9df9b399473380f/out/vs/workbench/api/node/extensionHostProcess.js:32:157829)
	at Dy.M (file:///home/~/.vscode-server/bin/fabdb6a30b49f79a7aba0f2ad9df9b399473380f/out/vs/workbench/api/node/extensionHostProcess.js:32:156918)
	at Dy.L (file:///home/~/.vscode-server/bin/fabdb6a30b49f79a7aba0f2ad9df9b399473380f/out/vs/workbench/api/node/extensionHostProcess.js:32:156156)
	at Sh.value (file:///home/~/.vscode-server/bin/fabdb6a30b49f79a7aba0f2ad9df9b399473380f/out/vs/workbench/api/node/extensionHostProcess.js:32:154820)
	at P.B (file:///home/~/.vscode-server/bin/fabdb6a30b49f79a7aba0f2ad9df9b399473380f/out/vs/workbench/api/node/extensionHostProcess.js:30:746)
	at P.fire (file:///home/~/.vscode-server/bin/fabdb6a30b49f79a7aba0f2ad9df9b399473380f/out/vs/workbench/api/node/extensionHostProcess.js:30:964)
	at Vn.fire (file:///home/~/.vscode-server/bin/fabdb6a30b49f79a7aba0f2ad9df9b399473380f/out/vs/workbench/api/node/extensionHostProcess.js:32:9457)
	at Sh.value (file:///home/~/.vscode-server/bin/fabdb6a30b49f79a7aba0f2ad9df9b399473380f/out/vs/workbench/api/node/extensionHostProcess.js:175:13296)
	at P.B (file:///home/~/.vscode-server/bin/fabdb6a30b49f79a7aba0f2ad9df9b399473380f/out/vs/workbench/api/node/extensionHostProcess.js:30:746)
	at P.fire (file:///home/~/.vscode-server/bin/fabdb6a30b49f79a7aba0f2ad9df9b399473380f/out/vs/workbench/api/node/extensionHostProcess.js:30:964)
	at Vn.fire (file:///home/~/.vscode-server/bin/fabdb6a30b49f79a7aba0f2ad9df9b399473380f/out/vs/workbench/api/node/extensionHostProcess.js:32:9457)
	at Wm.A (file:///home/~/.vscode-server/bin/fabdb6a30b49f79a7aba0f2ad9df9b399473380f/out/vs/workbench/api/node/extensionHostProcess.js:32:12573)
	at Sh.value (file:///home/~/.vscode-server/bin/fabdb6a30b49f79a7aba0f2ad9df9b399473380f/out/vs/workbench/api/node/extensionHostProcess.js:32:10993)
	at P.B (file:///home/~/.vscode-server/bin/fabdb6a30b49f79a7aba0f2ad9df9b399473380f/out/vs/workbench/api/node/extensionHostProcess.js:30:746)
	at P.fire (file:///home/~/.vscode-server/bin/fabdb6a30b49f79a7aba0f2ad9df9b399473380f/out/vs/workbench/api/node/extensionHostProcess.js:30:964)
	at s6.acceptChunk (file:///home/~/.vscode-server/bin/fabdb6a30b49f79a7aba0f2ad9df9b399473380f/out/vs/workbench/api/node/extensionHostProcess.js:32:7940)
	at Sh.value (file:///home/~/.vscode-server/bin/fabdb6a30b49f79a7aba0f2ad9df9b399473380f/out/vs/workbench/api/node/extensionHostProcess.js:32:7226)
	at P.B (file:///home/~/.vscode-server/bin/fabdb6a30b49f79a7aba0f2ad9df9b399473380f/out/vs/workbench/api/node/extensionHostProcess.js:30:746)
	at P.fire (file:///home/~/.vscode-server/bin/fabdb6a30b49f79a7aba0f2ad9df9b399473380f/out/vs/workbench/api/node/extensionHostProcess.js:30:964)
	at vA.z (file:///home/~/.vscode-server/bin/fabdb6a30b49f79a7aba0f2ad9df9b399473380f/out/vs/workbench/api/node/extensionHostProcess.js:32:21944)
	at vA.acceptFrame (file:///home/~/.vscode-server/bin/fabdb6a30b49f79a7aba0f2ad9df9b399473380f/out/vs/workbench/api/node/extensionHostProcess.js:32:21750)
	at mA.n (file:///home/~/.vscode-server/bin/fabdb6a30b49f79a7aba0f2ad9df9b399473380f/out/vs/workbench/api/node/extensionHostProcess.js:32:20278)
	at file:///home/~/.vscode-server/bin/fabdb6a30b49f79a7aba0f2ad9df9b399473380f/out/vs/workbench/api/node/extensionHostProcess.js:32:17510
	at Socket.t (file:///home/~/.vscode-server/bin/fabdb6a30b49f79a7aba0f2ad9df9b399473380f/out/vs/workbench/api/node/extensionHostProcess.js:32:15451)
	at Socket.emit (node:events:518:28)
	at addChunk (node:internal/streams/readable:561:12)
	at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
	at Readable.push (node:internal/streams/readable:392:5)
	at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
23:26:33.454 [debug] Dispose Kernel process 11220.
23:26:33.458 [debug] Kernel got disposed, hence there is no longer a kernel associated with ~/workspace/temp/Book.ipynb
23:26:33.460 [debug] Notebook document ~/workspace/temp/Book.ipynb got closed
23:26:33.461 [debug] Cancel executions after closing notebook ~/workspace/temp/Book.ipynb
23:26:33.461 [debug] Cancel pending cells
23:26:33.461 [debug] Cancel executions after closing notebook ~/workspace/temp/Book.ipynb
23:26:33.469 [debug] KernelProcess Exited 11220, Exit Code - undefined 
23:26:33.513 [debug] Disposed Kernel process 11220.
23:26:33.515 [debug] Shutdown session 73f5243b-7558-4c99-ba07-e4081b737958, .jvsc74a57bd017fe52e937ac4df3c5b3a61ea03b64884e6169803108c807918a0b3ad1b3f8db./home/~/miniconda3/envs/venv/python./home/~/miniconda3/envs/venv/python.-m#ipykernel_launcher - shutdown complete
```

### Coding Language and Runtime Version

Python v3.10.13

### Language Extension Version (if applicable)

2024.22.1

### Anaconda Version (if applicable)

24.11.0

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Do you have continue or other such extension. Please can you disable all non Microsoft extensions and try again. Please me know if that makes a difference, we have found that some other extensions cause a few problems with jupyter execution

**Comment by mayurmadnani** [comment]
> Do you have continue or other such extension. Please can you disable all non Microsoft extensions and try again. Please me know if that makes a difference, we have found that some other extensions cause a few problems with jupyter execution

Oh wow! You pinpointed to the cause. I disabled Continue and now the kernel is responsive

**Comment by DonJayamanne** [comment]
Thank you for getting back

**Comment by mayurmadnani** [comment]
Hey @DonJayamanne , the issue is still happening. I don't have continue and I tried disabling all other plugins as well except for Python and jupyter ones. Does not happen on mac but reproducible on wsl system.

**Comment by DonJayamanne** [comment]
Please confirm you do not have any other extension installed, then share the following logs when you run into this issue

Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `trace`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel (use the command `Jupyter: Show Output` to get to the logs).

**Comment by mayurmadnani** [comment]
Hey @DonJayamanne, thanks for the follow up. Nevermind, this was an env issue. Lot of changes are going in jupyterlab which seemed to have caused this. I tried for a couple of weeks now, on a new conda env and with plugins reinstalled, and this is solved.
