### ISSUE TITLE
Error "Illegal value for token color" in notebook editor and interactive window

### ISSUE THREAD

**Issue by mariadelmarq** [microsoft/vscode-jupyter#1661]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. Ctrl+Shit+P  and select "Python: Create new Jupyter Notebook"

## Actual behavior

![image](https://user-images.githubusercontent.com/12743476/87626314-6b142100-c76f-11ea-92ec-ed758404afb8.png)

## Expected behavior

An empty code cell to start writing code. Also when opening existing jupyter notebooks, this covers the first code cell, making it inaccessible to edit/run.

### Your Jupyter and/or Python environment

-   **Jupyter server running:** Local
-   **Extension version:** v2020.8.94248-dev
-   **VS Code version:** 1.47.1
-   **Setting python.jediEnabled:** No setting found
-   **Setting python.languageServer:** Jedi
-   **Python and/or Anaconda version:** 3.7.7
-   **OS:** Windows 10 Education
-   **Virtual environment:** conda

## Developer Tools Console Output

[Embedded Page] Error: Illegal value for token color: webviewElement.ts:160
workbench.desktop.main.js:sourcemap:3864 [Embedded Page] Could not create web worker(s). Falling back to loading web worker code in main thread, which might cause UI freezes. Please see https://github.com/Microsoft/monaco-editor#faq
workbench.desktop.main.js:sourcemap:3864 [Embedded Page] Failed to construct 'Worker': Script at 'vscode-webview-resource://db7bd419-27be-44a4-8901-86c7131f1d93/file///c%3A/Users/mquiroga/AppData/Local/Temp/editor.worker.js' cannot be accessed from origin 'vscode-webview://db7bd419-27be-44a4-8901-86c7131f1d93'.
workbench.desktop.main.js:sourcemap:266 [Extension Host] Starting WebSocket: RAW/api/kernels/40a52acf-d368-4063-8315-41101374e147
workbench.desktop.main.js:sourcemap:266 [Extension Host] Kernel: connected (40a52acf-d368-4063-8315-41101374e147)
workbench.desktop.main.js:sourcemap:3864 [Embedded Page] Uncaught Error: Illegal value for token color: 

Error: Illegal value for token color: 
    at e.getId (vscode-webview-resource://db7bd419-27be-44a4-8901-86c7131f1d93/file///c%3A/Users/mquiroga/.vscode/extensions/ms-python.python-2020.8.94248-dev/out/datascience-ui/notebook/monaco.bundle.js:1:465553)
    at jo (vscode-webview-resource://db7bd419-27be-44a4-8901-86c7131f1d93/file///c%3A/Users/mquiroga/.vscode/extensions/ms-python.python-2020.8.94248-dev/out/datascience-ui/notebook/monaco.bundle.js:1:465290)
    at Function.e.createFromParsedTokenTheme (vscode-webview-resource://db7bd419-27be-44a4-8901-86c7131f1d93/file///c%3A/Users/mquiroga/.vscode/extensions/ms-python.python-2020.8.94248-dev/out/datascience-ui/notebook/monaco.bundle.js:1:466485)
    at Function.e.createFromRawTokenTheme (vscode-webview-resource://db7bd419-27be-44a4-8901-86c7131f1d93/file///c%3A/Users/mquiroga/.vscode/extensions/ms-python.python-2020.8.94248-dev/out/datascience-ui/notebook/monaco.bundle.js:1:465959)
    at e.get [as tokenTheme] (vscode-webview-resource://db7bd419-27be-44a4-8901-86c7131f1d93/file///c%3A/Users/mquiroga/.vscode/extensions/ms-python.python-2020.8.94248-dev/out/datascience-ui/notebook/monaco.bundle.js:1:475626)
    at e._toBinaryTokens (vscode-webview-resource://db7bd419-27be-44a4-8901-86c7131f1d93/file///c%3A/Users/mquiroga/.vscode/extensions/ms-python.python-2020.8.94248-dev/out/datascience-ui/notebook/monaco.bundle.js:1:538237)
    at e.tokenize2 (vscode-webview-resource://db7bd419-27be-44a4-8901-86c7131f1d93/file///c%3A/Users/mquiroga/.vscode/extensions/ms-python.python-2020.8.94248-dev/out/datascience-ui/notebook/monaco.bundle.js:1:538548)
    at Pe (vscode-webview-resource://db7bd419-27be-44a4-8901-86c7131f1d93/file///c%3A/Users/mquiroga/.vscode/extensions/ms-python.python-2020.8.94248-dev/out/datascience-ui/notebook/monaco.bundle.js:1:2444923)
    at t._updateTokensUntilLine (vscode-webview-resource://db7bd419-27be-44a4-8901-86c7131f1d93/file///c%3A/Users/mquiroga/.vscode/extensions/ms-python.python-2020.8.94248-dev/out/datascience-ui/notebook/monaco.bundle.js:1:2443836)
    at t._tokenizeOneInvalidLine (vscode-webview-resource://db7bd419-27be-44a4-8901-86c7131f1d93/file///c%3A/Users/mquiroga/.vscode/extensions/ms-python.python-2020.8.94248-dev/out/datascience-ui/notebook/monaco.bundle.js:1:2443483)
workbench.desktop.main.js:sourcemap:3864 [Embedded Page] Starting WebSocket: BOGUS_PVSC/api/kernels/40a52acf-d368-4063-8315-41101374e147
workbench.desktop.main.js:sourcemap:3864 [Embedded Page] Kernel: connected (40a52acf-d368-4063-8315-41101374e147)
workbench.desktop.main.js:sourcemap:266 [Extension Host] Starting WebSocket: RAW/api/kernels/0c760cfd-8a68-4ecb-b069-2d8a6ad7a410
workbench.desktop.main.js:sourcemap:266 [Extension Host] Kernel: connected (0c760cfd-8a68-4ecb-b069-2d8a6ad7a410)

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by burcaka** [comment]
Had the same problem when using the below theme:

https://marketplace.visualstudio.com/items?itemName=konstantin.plain

Switching to a different theme solved the issue.

Switching, and then switching back to the problem theme, as mentioned by @mariadelmarq, did not help in my case.

**Comment by M-duMycheaux** [comment]
Had the same issue, Bio syntax was the default theme, uninstalling Bio syntax and relaunching the software resolved that. thanks. But I need the Bio syntax theme as well.  How do I keep that plugin on and avoid this bug?

**Comment by rchiodo** [comment]
For notebooks, you could switch to VS code insiders. In insiders we're using a different editor which support all themes.

For the interactive window, there's no workaround. We just don't support that theme at the moment.

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987. You can experiment by using VS Code insiders, which defaults to the new notebook experience.
