### ISSUE TITLE
Failing to detect ipykernel module

### ISSUE THREAD

**Issue by y2kbugger** [microsoft/vscode-jupyter#2446]
## Steps to cause the bug to occur
1. Right click on script "Run in interactive window.

## Actual behavior
Loads forever.
Notifys that ipykernel is not installed
![image](https://user-images.githubusercontent.com/6101677/72289302-ca567480-3618-11ea-96e6-d0cc9e3996cf.png)

### Your Jupyter and/or Python environment
*Please provide as much info as you readily know*
- **Jupyter server running:**                       Local
- **Extension version:**                               2020.01
- **VS Code version:**                                1.39.2
- **Setting python.jediEnabled:**               true
- **Python and/or Anaconda version:**     3.6
- **OS:**                                                     Windows
- **Virtual environment:**                          conda

![image](https://user-images.githubusercontent.com/6101677/72289275-c0347600-3618-11ea-9889-015d229e6568.png)

## Developer Tools Console Output

```
Info Python Extension: 2020-01-13 15:33:43: Python Daemon: Failed executing an rpc method. Error: Traceback (most recent call last):  File "c:\Users\skmeenak\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\datascience\getServerInfo.py", line 12, in <module>    for si in server_list:  File "C:\ProgramData\CooperConda\lib\site-packages\notebook\notebookapp.py", line 1888, in list_running_servers    with io.open(os.path.join(runtime_dir, file_name), encoding='utf-8') as f:FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\skmeenak\\AppData\\Roaming\\jupyter\\runtime\\nbserver-15404.json'During handling of the above exception, another exception occurred:Traceback (most recent call last):  File "c:\Users\skmeenak\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\datascience\daemon\daemon_python.py", line 54, in _decorator    return func(self, *args, **kwargs)  File "c:\Users\skmeenak\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\datascience\daemon\daemon_python.py", line 133, in m_exec_file    return self._execute_and_capture_output(exec_file)  File "c:\Users\skmeenak\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\datascience\daemon\daemon_python.py", line 104, in _execute_and_capture_output    func()  File "c:\Users\skmeenak\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\datascience\daemon\daemon_python.py", line 130, in exec_file    runpy.run_path(file_name, globals())  File "C:\ProgramData\CooperConda\lib\runpy.py", line 263, in run_path    pkg_name=pkg_name, script_name=fname)  File "C:\ProgramData\CooperConda\lib\runpy.py", line 96, in _run_module_code    mod_name, mod_spec, pkg_name, script_name)  File "C:\ProgramData\CooperConda\lib\runpy.py", line 85, in _run_code    exec(code, run_globals)  File "c:\Users\skmeenak\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\datascience\getServerInfo.py", line 29, in <module>    result = subprocess.run(['jupyter', 'notebook', 'list', '--jsonlist'], capture_output=True)  File "C:\ProgramData\CooperConda\lib\subprocess.py", line 423, in run    with Popen(*popenargs, **kwargs) as process:TypeError: __init__() got an unexpected keyword argument 'capture_output'
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Cached data exists ActivatedEnvironmentVariables, <No Resource>
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: getActivatedEnvironmentVariables, Class name = b, completed in 1ms, Arg 1: undefined, Arg 2: undefined, Arg 3: true
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: [I 15:33:43.277 NotebookApp] JupyterLab extension loaded from C:\ProgramData\CooperConda\lib\site-packages\jupyterlab[I 15:33:43.278 NotebookApp] JupyterLab application directory is C:\ProgramData\CooperConda\share\jupyter\lab[I 15:33:43.280 NotebookApp] Serving notebooks from local directory: C:\Users\skmeenak\AppData\Local\Temp\10fdc1fc-a08f-4b42-a595-509969ab45b6[I 15:33:43.280 NotebookApp] The Jupyter Notebook is running at:[I 15:33:43.281 NotebookApp] http://localhost:8888/?token=74dea3721d973d3161da3c20162c4941be761ebf0b05c4f8[I 15:33:43.281 NotebookApp]  or http://127.0.0.1:8888/?token=74dea3721d973d3161da3c20162c4941be761ebf0b05c4f8[I 15:33:43.281 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).[C 15:33:43.287 NotebookApp]         To access the notebook, open this file in a browser:        file:///C:/Users/skmeenak/AppData/Roaming/jupyter/runtime/nbserver-11364-open.html    Or copy and paste one of these URLs:        http://localhost:8888/?token=74dea3721d973d3161da3c20162c4941be761ebf0b05c4f8     or http://127.0.0.1:8888/?token=74dea3721d973d3161da3c20162c4941be761ebf0b05c4f8
console.ts:137 [Extension Host] Warn Python Extension: 2020-01-13 15:33:43: Falling back to Python Execution Service due to failure in daemon { Error: Failed to execute using the daemon, Traceback (most recent call last):  File "c:\Users\skmeenak\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\datascience\getServerInfo.py", line 12, in <module>    for si in server_list:  File "C:\ProgramData\CooperConda\lib\site-packages\notebook\notebookapp.py", line 1888, in list_running_servers    with io.open(os.path.join(runtime_dir, file_name), encoding='utf-8') as f:FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\skmeenak\\AppData\\Roaming\\jupyter\\runtime\\nbserver-15404.json'During handling of the above exception, another exception occurred:Traceback (most recent call last):  File "c:\Users\skmeenak\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\datascience\daemon\daemon_python.py", line 54, in _decorator    return func(self, *args, **kwargs)  File "c:\Users\skmeenak\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\datascience\daemon\daemon_python.py", line 133, in m_exec_file    return self._execute_and_capture_output(exec_file)  File "c:\Users\skmeenak\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\datascience\daemon\daemon_python.py", line 104, in _execute_and_capture_output    func()  File "c:\Users\skmeenak\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\datascience\daemon\daemon_python.py", line 130, in exec_file    runpy.run_path(file_name, globals())  File "C:\ProgramData\CooperConda\lib\runpy.py", line 263, in run_path    pkg_name=pkg_name, script_name=fname)  File "C:\ProgramData\CooperConda\lib\runpy.py", line 96, in _run_module_code    mod_name, mod_spec, pkg_name, script_name)  File "C:\ProgramData\CooperConda\lib\runpy.py", line 85, in _run_code    exec(code, run_globals)  File "c:\Users\skmeenak\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\datascience\getServerInfo.py", line 29, in <module>    result = subprocess.run(['jupyter', 'notebook', 'list', '--jsonlist'], capture_output=True)  File "C:\ProgramData\CooperConda\lib\subprocess.py", line 423, in run    with Popen(*popenargs, **kwargs) as process:TypeError: __init__() got an unexpected keyword argument 'capture_output'    at t.PythonDaemonExecutionService.processResponse (c:\Users\skmeenak\.vscode\extensions\ms-python.python-2020.1.58038\src\client\common\process\pythonDaemon.ts:214:1)    at t.PythonDaemonExecutionService.processResponse [as execFileWithDaemon] (c:\Users\skmeenak\.vscode\extensions\ms-python.python-2020.1.58038\src\client\common\process\pythonDaemon.ts:229:1)  message:   'Failed to execute using the daemon, Traceback (most recent call last):\n  File "c:\\Users\\skmeenak\\.vscode\\extensions\\ms-python.python-2020.1.58038\\pythonFiles\\datascience\\getServerInfo.py", line 12, in <module>\n    for si in server_list:\n  File "C:\\ProgramData\\CooperConda\\lib\\site-packages\\notebook\\notebookapp.py", line 1888, in list_running_servers\n    with io.open(os.path.join(runtime_dir, file_name), encoding=\'utf-8\') as f:\nFileNotFoundError: [Errno 2] No such file or directory: \'C:\\\\Users\\\\skmeenak\\\\AppData\\\\Roaming\\\\jupyter\\\\runtime\\\\nbserver-15404.json\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "c:\\Users\\skmeenak\\.vscode\\extensions\\ms-python.python-2020.1.58038\\pythonFiles\\datascience\\daemon\\daemon_python.py", line 54, in _decorator\n    return func(self, *args, **kwargs)\n  File "c:\\Users\\skmeenak\\.vscode\\extensions\\ms-python.python-2020.1.58038\\pythonFiles\\datascience\\daemon\\daemon_python.py", line 133, in m_exec_file\n    return self._execute_and_capture_output(exec_file)\n  File "c:\\Users\\skmeenak\\.vscode\\extensions\\ms-python.python-2020.1.58038\\pythonFiles\\datascience\\daemon\\daemon_python.py", line 104, in _execute_and_capture_output\n    func()\n  File "c:\\Users\\skmeenak\\.vscode\\extensions\\ms-python.python-2020.1.58038\\pythonFiles\\datascience\\daemon\\daemon_python.py", line 130, in exec_file\n    runpy.run_path(file_name, globals())\n  File "C:\\ProgramData\\CooperConda\\lib\\runpy.py", line 263, in run_path\n    pkg_name=pkg_name, script_name=fname)\n  File "C:\\ProgramData\\CooperConda\\lib\\runpy.py", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File "C:\\ProgramData\\CooperConda\\lib\\runpy.py", line 85, in _run_code\n    exec(code, run_globals)\n  File "c:\\Users\\skmeenak\\.vscode\\extensions\\ms-python.python-2020.1.58038\\pythonFiles\\datascience\\getServerInfo.py", line 29, in <module>\n    result = subprocess.run([\'jupyter\', \'notebook\', \'list\', \'--jsonlist\'], capture_output=True)\n  File "C:\\ProgramData\\CooperConda\\lib\\subprocess.py", line 423, in run\n    with Popen(*popenargs, **kwargs) as process:\nTypeError: __init__() got an unexpected keyword argument \'capture_output\'\n' }
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:580
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:592
fire @ event.ts:580
acceptChunk @ ipc.net.ts:239
_register._socket.onData.e @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:182
addChunk @ _stream_readable.js:283
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onStreamRead @ internal/stream_base_commons.js:94
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: > C:\ProgramData\CooperConda\python.exe c:\Users\skmeenak\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\datascience\getServerInfo.py
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: Execute rpc method ping in DS Daemon
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: Execute rpc method ping
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: pinged with hello
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: > C:\ProgramData\CooperConda\python.exe (daemon) c:\Users\skmeenak\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\datascience\getServerInfo.py
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: Execute rpc method exec_file in DS Daemon
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: Execute rpc method exec_file
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: Exec file c:\Users\skmeenak\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\datascience\getServerInfo.py with args []
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: execute file c:\Users\skmeenak\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\datascience\getServerInfo.py
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: Execute rpc method ping in DS Daemon
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: Execute rpc method ping
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: pinged with hello
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: > C:\ProgramData\CooperConda\python.exe (daemon) c:\Users\skmeenak\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\datascience\getServerInfo.py
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: Execute rpc method exec_file in DS Daemon
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: Execute rpc method exec_file
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: Exec file c:\Users\skmeenak\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\datascience\getServerInfo.py with args []
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: execute file c:\Users\skmeenak\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\datascience\getServerInfo.py
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: Execute rpc method ping in DS Daemon
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: Execute rpc method ping
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: pinged with hello
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: > C:\ProgramData\CooperConda\python.exe (daemon) c:\Users\skmeenak\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\datascience\getServerInfo.py
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: Execute rpc method exec_file in DS Daemon
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: Execute rpc method exec_file
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: Exec file c:\Users\skmeenak\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\datascience\getServerInfo.py with args []
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: execute file c:\Users\skmeenak\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\datascience\getServerInfo.py
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: Execute rpc method ping in DS Daemon
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: Execute rpc method ping
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: pinged with hello
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: > C:\ProgramData\CooperConda\python.exe (daemon) c:\Users\skmeenak\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\datascience\getServerInfo.py
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: Execute rpc method exec_file in DS Daemon
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: Execute rpc method exec_file
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: Exec file c:\Users\skmeenak\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\datascience\getServerInfo.py with args []
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: execute file c:\Users\skmeenak\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\datascience\getServerInfo.py
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: Execute rpc method ping in DS Daemon
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: Execute rpc method ping
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: pinged with hello
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: > C:\ProgramData\CooperConda\python.exe (daemon) c:\Users\skmeenak\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\datascience\getServerInfo.py
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: Execute rpc method exec_file in DS Daemon
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: Execute rpc method exec_file
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: Exec file c:\Users\skmeenak\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\datascience\getServerInfo.py with args []
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: execute file c:\Users\skmeenak\.vscode\extensions\ms-python.python-2020.1.58038\pythonFiles\datascience\getServerInfo.py
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: Execute rpc method ping in DS Daemon
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: Execute rpc method ping
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:43: Python Daemon: pinged with hello
notificationsAlerts.ts:40 Data Science library ipykernel is not installed. Install?
onDidNotificationChange @ notificationsAlerts.ts:40
_register.model.onDidNotificationChange.e @ notificationsAlerts.ts:26
fire @ event.ts:580
addNotification @ notifications.ts:156
notify @ notificationService.ts:100
r @ mainThreadMessageService.ts:83
_showMessage @ mainThreadMessageService.ts:44
$showMessage @ mainThreadMessageService.ts:38
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:580
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:592
fire @ event.ts:580
acceptChunk @ ipc.net.ts:239
_register._socket.onData.e @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:182
addChunk @ _stream_readable.js:283
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onStreamRead @ internal/stream_base_commons.js:94
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:45: Python Daemon: Execute rpc method ping in DS Daemon
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:45: Python Daemon: Execute rpc method ping
console.ts:137 [Extension Host] Info Python Extension: 2020-01-13 15:33:45: Python Daemon: pinged with hello
```
Also it appears to be intermittent....at lease on one occasion today the user reported and showed me that it did "Work" and the ipython kernel was started. I couldn't tell whether it was daemon or fallback.

Let me know if you need any more details.

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by eervin123** [comment]
I was having similar symptoms and had a hell of a time solving the problem.  I finally realized that I had accidentally created two environments with the same name.  I deleted the environment and the folder with the same name, and now everything works as it should.  I have no idea if my issues are at all a clue to these other issues, but I thought I would at least share them here.  You can remove my comment if it is unhelpful.

**Comment by gmeinecke-sd** [comment]
I'm still experiencing this issue.
What is the best practice workflow for conda + vscode jupyter notebooks to avoid this issue?

**Comment by rchiodo** [comment]
> What is the best practice workflow for conda + vscode jupyter notebooks to avoid this issue?

Sorry but that's a little ambiguous. What exact issue are you having? IPyKernel not being detected? This can be caused by any number of things, some of which are outlined above. Your best bet is to 

1) Start VS code from the anaconda prompt after activating the environment you want
1) If that still doesn't work, turn on logging level ```info``` for ```jupyter.logging.level```. 
1) Look in the jupyter output tab for errors thrown by the kernel. They usually give some clue as to what the issue is. These can be things like pyzmq is not installed, dll not found, or other pip problems.

**Comment by gmeinecke-sd** [comment]
Thanks and sorry for the ambiguity. Yes, my issue was IPyKernel not being detected but launching vscode from an activated virtual environment seems to be doing the trick. Is that the recommended workflow to avoid IPyKernel detection issues?

**Comment by rchiodo** [comment]
> Is that the recommended workflow to avoid IPyKernel detection issues?

That's the recommended workflow if anything goes wrong with Conda. If you search 'conda' in the python extension [issues](https://github.com/microsoft/vscode-python/issues?q=is%3Aissue+is%3Aopen+conda) there's lots that can go wrong with conda activation. It works out better if you activate outside of VS code and just use that.
