### ISSUE TITLE
python extension can't convert .ipynb to .py

### ISSUE THREAD

**Issue by RayChen6** [microsoft/vscode-jupyter#3135]
I downloaded a vscode before, then I downloaded anaconda. And I found anaconda is very useful, especially jupyter, so I want to combine its function with vscode.

I have tried to operate jupyternotebook to the vscode for a long time, but it doesn't work even once. I'm very upset, so I came here for professional help.
I have to admit that I am a novice in this area, here is the specific situation.

OS：windows 10
the latest version of vscode and anaconda with jupyter

the situation is that I can't open a ipynb file in the format of py (with run cell icon, etc.)
when I click "import jupyter notebook to python code", it doesn't give a respond.

Then I try to use the #%% to create a test file, but when I click the run cell button, there comes an error report shows "Executing code failed : Error: Activating Python 3.7.3 64-bit ('base': conda) to run Jupyter failed with Error: StdErr from ShellExec, ϵͳ�Ҳ���ָ����·���� ."

I am desperately helpless, and I will appreciate your help!

**Comment by greazer** [comment]
I'm reproing this right now using VS Code 1.61-insiders and the latest Jupyter insiders extension.

**Comment by greazer** [comment]
More specifically, I chose: ```File->Convert Notebook to Python Script``` and I get an export error:

```Info 2021-09-21 13:34:57: Process Execution: > ~\AppData\Local\Programs\PythonCodingPack\python.exe -m jupyter nbconvert --version
> ~\AppData\Local\Programs\PythonCodingPack\python.exe -m jupyter nbconvert --version
Info 2021-09-21 13:34:57: Process Execution: > ~\AppData\Local\Programs\PythonCodingPack\python.exe -m jupyter nbconvert --version
> ~\AppData\Local\Programs\PythonCodingPack\python.exe -m jupyter nbconvert --version
Error 2021-09-21 13:34:58: Export failed Error: Importing notebooks requires Jupyter nbconvert to be installed.
    at g.importFromFile (c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.9.1001256920\out\client\extension.js:52:972930)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at s.export (c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.9.1001256920\out\client\extension.js:52:922146)
    at b.exportToFormat (c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.9.1001256920\out\client\extension.js:52:919661)
    at b.performExport (c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.9.1001256920\out\client\extension.js:52:918846)
    at b.export (c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.9.1001256920\out\client\extension.js:52:918360)
    at c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.9.1001256920\out\client\extension.js:90:268958
    at u.waitWithStatus (c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.9.1001256920\out\client\extension.js:90:232715)
    at k.importNotebookOnFile (c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.9.1001256920\out\client\extension.js:90:268881)
    at k.listenForErrors (c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.9.1001256920\out\client\extension.js:90:264660)
    at a._executeContributedCommand (c:\Users\jimg\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:94:112416)
```

**Comment by amunger** [comment]
latest issue is just dealing with exporting a notebook, not Interactive window
