### ISSUE TITLE
Failed to connect to Jupyter Notebook. Check that the Jupyter server URI...

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#3925]
@tionebrr commented on [Sat Nov 14 2020](https://github.com/microsoft/vscode-python/issues/14735)

## Environment data

-   VS Code version:
![image](https://user-images.githubusercontent.com/8854321/99162671-9187a000-2700-11eb-8023-1a29122a6859.png)

-   Extension version (available under the Extensions sidebar): v2020.11.358366026
-   OS and version: Win10 19041
-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Relevant/affected Python packages and their versions: N/A
-   Relevant/affected Python-related VS Code extensions and their versions: N/A
-   Value of the `python.languageServer` setting: What ?

## Expected behaviour

Start and run console

## Actual behaviour

Unable to connect

## Steps to reproduce:

1. Try to run a cell containing `print('Hello)`
2. Hit 'Shift+Enter'

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'RunByLine - experiment'
User belongs to experiment group 'CustomEditorSupport - control'
User belongs to experiment group 'pythonaa'
> conda --version
> pyenv root
> python3.7 c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3.7 c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3.6 c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3 c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -2 c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda info --json
Error 2020-11-15 05:15:31: Detection of Python Interpreter for Command python3 and args  failed as file  does not exist
Error 2020-11-15 05:15:31: Detection of Python Interpreter for Command py and args -3.6 failed as file Python 3.6 not found!

 -3.9-64 does not exist
Error 2020-11-15 05:15:31: Detection of Python Interpreter for Command py and args -3.7 failed as file Python 3.7 not found!

 -3.9-64 does not exist
Error 2020-11-15 05:15:31: Detection of Python Interpreter for Command py and args -2 failed as file Python 2 not found!

 -3.9-64 does not exist
Python interpreter path: ~\AppData\Local\Programs\Python\Python39\python.exe
Starting Jedi Python language engine.
> conda env list
Error 2020-11-15 05:15:31: Failed to get conda environment list from conda [Error: spawn conda ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:81:21)] {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn conda',
  path: 'conda',
  spawnargs: [ 'env', 'list' ]
}
> conda --version
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text d:\Desktop\MiniLimiteur\python\test.py
cwd: d:\Desktop\MiniLimiteur\python
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py pylint --disable=all --enable=F,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,unused-wildcard-import,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode,E0001,E0011,E0012,E0100,E0101,E0102,E0103,E0104,E0105,E0107,E0108,E0110,E0111,E0112,E0113,E0114,E0115,E0116,E0117,E0118,E0202,E0203,E0211,E0213,E0236,E0237,E0238,E0239,E0240,E0241,E0301,E0302,E0303,E0401,E0402,E0601,E0602,E0603,E0604,E0611,E0632,E0633,E0701,E0702,E0703,E0704,E0710,E0711,E0712,E1003,E1101,E1102,E1111,E1120,E1121,E1123,E1124,E1125,E1126,E1127,E1128,E1129,E1130,E1131,E1132,E1133,E1134,E1135,E1136,E1137,E1138,E1139,E1200,E1201,E1205,E1206,E1300,E1301,E1302,E1303,E1304,E1305,E1306,E1310,E1700,E1701 --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text d:\Desktop\MiniLimiteur\python\test.py
cwd: d:\Desktop\MiniLimiteur\python
Error 2020-11-15 05:15:32: Failed to get interpreter information for 'C:\Users\Beubeuh\AppData\Local\Microsoft\WindowsApps\python3.exe' [Error: Command failed: "C:\\Users\Beubeuh\AppData\Local\Microsoft\WindowsApps\python3.exe" "c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py" "c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\interpreterInfo.py"
Python was not found but can be installed from the Microsoft Store: https://go.microsoft.com/fwlink?linkID=2082640
	at ChildProcess.exithandler (child_process.js:304:12)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)] {
  killed: false,
  code: 9009,
  signal: null,
  cmd: '"C:\\\\Users\\Beubeuh\\AppData\\Local\\Microsoft\\WindowsApps\\python3.exe" "c:\\Users\\Beubeuh\\.vscode\\extensions\\ms-python.python-2020.11.358366026\\pythonFiles\\pyvsc-run-isolated.py" "c:\\Users\\Beubeuh\\.vscode\\extensions\\ms-python.python-2020.11.358366026\\pythonFiles\\interpreterInfo.py"'
}
Error 2020-11-15 05:15:32: Failed to get interpreter information for 'C:\Users\Beubeuh\AppData\Local\Microsoft\WindowsApps\python3.exe' [Error: Command failed: "C:\\Users\Beubeuh\AppData\Local\Microsoft\WindowsApps\python3.exe" "c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py" "c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\interpreterInfo.py"
Python was not found but can be installed from the Microsoft Store: https://go.microsoft.com/fwlink?linkID=2082640
	at ChildProcess.exithandler (child_process.js:304:12)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)] {
  killed: false,
  code: 9009,
  signal: null,
  cmd: '"C:\\\\Users\\Beubeuh\\AppData\\Local\\Microsoft\\WindowsApps\\python3.exe" "c:\\Users\\Beubeuh\\.vscode\\extensions\\ms-python.python-2020.11.358366026\\pythonFiles\\pyvsc-run-isolated.py" "c:\\Users\\Beubeuh\\.vscode\\extensions\\ms-python.python-2020.11.358366026\\pythonFiles\\interpreterInfo.py"'
}
Error 2020-11-15 05:15:32: Failed to get interpreter information for 'C:\Users\Beubeuh\AppData\Local\Microsoft\WindowsApps\python.exe' [Error: Command failed: "C:\\Users\Beubeuh\AppData\Local\Microsoft\WindowsApps\python.exe" "c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py" "c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\interpreterInfo.py"
Python was not found but can be installed from the Microsoft Store: https://go.microsoft.com/fwlink?linkID=2082640
	at ChildProcess.exithandler (child_process.js:304:12)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:430:11)
	at Socket.emit (events.js:223:5)
	at Pipe.<anonymous> (net.js:664:12)] {
  killed: false,
  code: 9009,
  signal: null,
  cmd: '"C:\\\\Users\\Beubeuh\\AppData\\Local\\Microsoft\\WindowsApps\\python.exe" "c:\\Users\\Beubeuh\\.vscode\\extensions\\ms-python.python-2020.11.358366026\\pythonFiles\\pyvsc-run-isolated.py" "c:\\Users\\Beubeuh\\.vscode\\extensions\\ms-python.python-2020.11.358366026\\pythonFiles\\interpreterInfo.py"'
}
Error 2020-11-15 05:15:32: Failed to get interpreter information for 'C:\Users\Beubeuh\AppData\Local\Microsoft\WindowsApps\python.exe' [Error: Command failed: "C:\\Users\Beubeuh\AppData\Local\Microsoft\WindowsApps\python.exe" "c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py" "c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\interpreterInfo.py"
Python was not found but can be installed from the Microsoft Store: https://go.microsoft.com/fwlink?linkID=2082640
	at ChildProcess.exithandler (child_process.js:304:12)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)] {
  killed: false,
  code: 9009,
  signal: null,
  cmd: '"C:\\\\Users\\Beubeuh\\AppData\\Local\\Microsoft\\WindowsApps\\python.exe" "c:\\Users\\Beubeuh\\.vscode\\extensions\\ms-python.python-2020.11.358366026\\pythonFiles\\pyvsc-run-isolated.py" "c:\\Users\\Beubeuh\\.vscode\\extensions\\ms-python.python-2020.11.358366026\\pythonFiles\\interpreterInfo.py"'
}
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: d:\Desktop\MiniLimiteur\python
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: d:\Desktop\MiniLimiteur\python
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: d:\Desktop\MiniLimiteur\python
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: d:\Desktop\MiniLimiteur\python
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: d:\Desktop\MiniLimiteur\python
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: d:\Desktop\MiniLimiteur\python
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py site --user-site
cwd: d:\Desktop\MiniLimiteur\python
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py site --user-site
cwd: d:\Desktop\MiniLimiteur\python
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py -c "import pylint"
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py -c "import pylint"
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py -c "import pylint"
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py -c "import pylint"
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\completion.py
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\pyvsc-run-isolated.py c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\completion.py

Linter 'pylint' is not installed. Please install it or select another linter".
Error: Module 'pylint' not installed.
Error 2020-11-15 05:15:33: stderr jediProxy Error (stderr) c:\Users\Beubeuh\.vscode\extensions\ms-python.python-2020.11.358366026\pythonFiles\completion.py:584: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).get_names instead.
  jedi.api.names(

```

</p>
</details>

Electron ts log:
![image](https://user-images.githubusercontent.com/8854321/99239014-c546f080-27fa-11eb-81ea-181f24f5ef6a.png)

---

@tionebrr commented on [Sat Nov 14 2020](https://github.com/microsoft/vscode-python/issues/14735#issuecomment-727495971)

As a note, everything was working fine before the latest VSCode update with Anaconda.
After the VSCode update, I was unable to launch an interactive console.
I removed Anaconda and made a clean install of Python 3.9 after the problem started.

---

@zoltix commented on [Sun Nov 15 2020](https://github.com/microsoft/vscode-python/issues/14735#issuecomment-727603491)

I have the same issue under archlinux.

---

@egorgam commented on [Sun Nov 15 2020](https://github.com/microsoft/vscode-python/issues/14735#issuecomment-727636229)

I have same issue with MacOS Big Sur (pushing Enter do nothing)
![Screenshot 2020-11-16 at 00 00 37](https://user-images.githubusercontent.com/13712792/99196665-e0841280-279e-11eb-935a-d8b8e74ad172.png)

---

@tionebrr commented on [Mon Nov 16 2020](https://github.com/microsoft/vscode-python/issues/14735#issuecomment-727875129)

I noticed that vscode-python extension v2020.10.332292344 is working fine.
So, for a workaround, just rollback your Python extension.
![image](https://user-images.githubusercontent.com/8854321/99239600-90876900-27fb-11eb-84ff-29b5477ada39.png)

**Comment by DonJayamanne** [comment]
Dup of https://github.com/microsoft/vscode-jupyter/issues/3916#issuecomment-732483236
