### ISSUE TITLE
Get started from scratch: failed connecting to kernel.

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode-jupyter#3959]
## Environment data
Version: 1.52.0-insider (user setup)
Commit: d19c7c52fd364dda47aa34d4284b4d3ff43c69b0
Date: 2020-11-17T06:05:20.789Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Python: 3.9 (newly installed from python.org)

Python ExtVer: v2020.11.367453362
Jupyter ExtVer: v2020.11.358541065

## Actual behaviour

Stuck on connecting to kernel, later timeout.

![image](https://user-images.githubusercontent.com/2351748/99487018-5dcaa580-29a0-11eb-92e8-24c063f31c5b.png)

![image](https://user-images.githubusercontent.com/2351748/99487048-76d35680-29a0-11eb-9248-3839a90ad417.png)

## Steps to reproduce:

1. Open an empty folder. 
2. Run command: Create new blank jupyter notebook, then it opens an `untitle.ipynb` (save to disk or not, leading to the same error)
3. input "print(1)" into the cell, click run button.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

![image](https://user-images.githubusercontent.com/2351748/99487321-00832400-29a1-11eb-91c0-391de05d02fb.png)

<p>

```
User belongs to experiment group 'NativeNotebookEditor'
Error 2020-11-18 13:10:12: Jupyter Kernel Spec not found for a local connection
Error 2020-11-18 13:10:16: Jupyter Kernel Spec not found for a local connection
Error 2020-11-18 13:10:17: Jupyter Kernel Spec not found for a local connection
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Error 2020-11-18 13:10:22: Failed to start the Daemon, StdErr:  Traceback (most recent call last):
  File "c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\vscode_datascience_helpers\daemon\__main__.py", line 126, in main
    daemon_module = importlib.import_module(args.daemon_module)
  File "C:\Users\zy199\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\vscode_datascience_helpers\kernel_launcher_daemon.py", line 22, in <module>
    from vscode_datascience_helpers.kernel_launcher import launch_kernel
  File "c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\vscode_datascience_helpers\kernel_launcher.py", line 14, in <module>
    from ipython_genutils.encoding import getdefaultencoding
ModuleNotFoundError: No module named 'ipython_genutils'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\pyvsc-run-isolated.py", line 26, in <module>
    runpy.run_module(module, run_name="__main__", alter_sys=True)
  File "C:\Users\zy199\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "C:\Users\zy199\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\zy199\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\vscode_datascience_helpers\daemon\__main__.py", line 137, in <module>
    main()
  File "c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\vscode_datascience_helpers\daemon\__main__.py", line 133, in main
    raise Exception("Failed to start daemon")
Exception: Failed to start daemon

Error 2020-11-18 13:10:22: Failed to start the Daemon, ProcEndEx [Error: Timeout waiting for daemon to start
	at Timeout._onTimeout (c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\out\client\extension.js:32:194215)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)]
Error 2020-11-18 13:10:22: Failed  to start the Daemon, Ex [Error: Timeout waiting for daemon to start
	at Timeout._onTimeout (c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\out\client\extension.js:32:194215)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)]
Error 2020-11-18 13:10:22: Pinging Daemon Failed, Class name = h, completed in 5002ms, has a falsy return value, Arg 1: {}, Return Value: undefined [Error: Timeout waiting for daemon to start
	at Timeout._onTimeout (c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\out\client\extension.js:32:194215)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)]
Error 2020-11-18 13:10:22: Failed to create daemon, Class name = h, completed in 5016ms, has a falsy return value, , Return Value: undefined [Error: Timeout waiting for daemon to start
	at Timeout._onTimeout (c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\out\client\extension.js:32:194215)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)]
Error 2020-11-18 13:10:22: Failed to create the daemon service, defaulting to activated environment [Error: Timeout waiting for daemon to start
	at Timeout._onTimeout (c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\out\client\extension.js:32:194215)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)]
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\pyvsc-run-isolated.py ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"e650950e-91d2-4564-ac10-ad843d90d170" --shell=9002 --transport="tcp" --iopub=9004 --f=C:\Users\zy199\AppData\Local\Temp\tmp-4648GBo15Y6hQ7Jy.json
cwd: c:\Users\zy199\Desktop\java
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\pyvsc-run-isolated.py ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"e650950e-91d2-4564-ac10-ad843d90d170" --shell=9002 --transport="tcp" --iopub=9004 --f=C:\Users\zy199\AppData\Local\Temp\tmp-4648GBo15Y6hQ7Jy.json
cwd: c:\Users\zy199\Desktop\java
Error 2020-11-18 13:10:52: Timed out waiting to get a heartbeat from kernel process.
Error 2020-11-18 13:10:52: Failed to connect raw kernel session: Error: Timed out waiting to get a heartbeat from kernel process.
Error 2020-11-18 13:10:52: failed to create INotebook in kernel [Error: Timed out waiting to get a heartbeat from kernel process.
	at m.waitForHeartbeat (c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\out\client\extension.js:49:646443)]
Error 2020-11-18 13:10:52: DataScience Error [Error: Timed out waiting to get a heartbeat from kernel process.
	at m.waitForHeartbeat (c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\out\client\extension.js:49:646443)]
Error 2020-11-18 13:11:14: Jupyter Kernel Spec not found for a local connection
Error 2020-11-18 13:11:14: Failed to connect raw kernel session: Error: Canceled
Error 2020-11-18 13:11:14: failed to create INotebook in kernel [s [Error]: Canceled
	at c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\out\client\extension.js:1:148377
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)]
Error 2020-11-18 13:11:14: DataScience Error [s [Error]: Canceled
	at c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\out\client\extension.js:1:148377
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)]
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Error 2020-11-18 13:11:17: Jupyter Kernel Spec not found for a local connection
Error 2020-11-18 13:11:17: Failed to connect raw kernel session: Error: Canceled
Error 2020-11-18 13:11:17: failed to create INotebook in kernel [s [Error]: Canceled
	at c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\out\client\extension.js:1:148377
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)]
Error 2020-11-18 13:11:17: DataScience Error [s [Error]: Canceled
	at c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\out\client\extension.js:1:148377
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)]
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Error 2020-11-18 13:11:19: Failed to start the Daemon, StdErr:  Traceback (most recent call last):
  File "c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\vscode_datascience_helpers\daemon\__main__.py", line 126, in main
    daemon_module = importlib.import_module(args.daemon_module)
  File "C:\Users\zy199\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\vscode_datascience_helpers\kernel_launcher_daemon.py", line 22, in <module>
    from vscode_datascience_helpers.kernel_launcher import launch_kernel
  File "c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\vscode_datascience_helpers\kernel_launcher.py", line 14, in <module>
    from ipython_genutils.encoding import getdefaultencoding
ModuleNotFoundError: No module named 'ipython_genutils'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\pyvsc-run-isolated.py", line 26, in <module>
    runpy.run_module(module, run_name="__main__", alter_sys=True)
  File "C:\Users\zy199\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "C:\Users\zy199\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\zy199\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\vscode_datascience_helpers\daemon\__main__.py", line 137, in <module>
    main()
  File "c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\vscode_datascience_helpers\daemon\__main__.py", line 133, in main
    raise Exception("Failed to start daemon")
Exception: Failed to start daemon

Error 2020-11-18 13:11:19: Failed to start the Daemon, ProcEndEx [Error: Timeout waiting for daemon to start
	at Timeout._onTimeout (c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\out\client\extension.js:32:194215)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)]
Error 2020-11-18 13:11:19: Failed  to start the Daemon, Ex [Error: Timeout waiting for daemon to start
	at Timeout._onTimeout (c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\out\client\extension.js:32:194215)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)]
Error 2020-11-18 13:11:19: Pinging Daemon Failed, Class name = h, completed in 5013ms, has a falsy return value, Arg 1: {}, Return Value: undefined [Error: Timeout waiting for daemon to start
	at Timeout._onTimeout (c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\out\client\extension.js:32:194215)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)]
Error 2020-11-18 13:11:19: Failed to create daemon, Class name = h, completed in 5023ms, has a falsy return value, , Return Value: undefined [Error: Timeout waiting for daemon to start
	at Timeout._onTimeout (c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\out\client\extension.js:32:194215)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)]
Error 2020-11-18 13:11:19: Failed to create the daemon service, defaulting to activated environment [Error: Timeout waiting for daemon to start
	at Timeout._onTimeout (c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\out\client\extension.js:32:194215)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)]
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\pyvsc-run-isolated.py ipykernel_launcher --ip=127.0.0.1 --stdin=9008 --control=9006 --hb=9005 --Session.signature_scheme="hmac-sha256" --Session.key=b"3a6c1f03-ff42-45bb-9fc7-9154ec7a3798" --shell=9007 --transport="tcp" --iopub=9009 --f=C:\Users\zy199\AppData\Local\Temp\tmp-4648dhdX1Djoulac.json
cwd: c:\Users\zy199\Desktop\java
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\pyvsc-run-isolated.py ipykernel_launcher --ip=127.0.0.1 --stdin=9008 --control=9006 --hb=9005 --Session.signature_scheme="hmac-sha256" --Session.key=b"3a6c1f03-ff42-45bb-9fc7-9154ec7a3798" --shell=9007 --transport="tcp" --iopub=9009 --f=C:\Users\zy199\AppData\Local\Temp\tmp-4648dhdX1Djoulac.json
cwd: c:\Users\zy199\Desktop\java
Error 2020-11-18 13:11:22: Failed to start the Daemon, StdErr:  Traceback (most recent call last):
  File "c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\vscode_datascience_helpers\daemon\__main__.py", line 126, in main
    daemon_module = importlib.import_module(args.daemon_module)
  File "C:\Users\zy199\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\vscode_datascience_helpers\kernel_launcher_daemon.py", line 22, in <module>
    from vscode_datascience_helpers.kernel_launcher import launch_kernel
  File "c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\vscode_datascience_helpers\kernel_launcher.py", line 14, in <module>
    from ipython_genutils.encoding import getdefaultencoding
ModuleNotFoundError: No module named 'ipython_genutils'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\pyvsc-run-isolated.py", line 26, in <module>
    runpy.run_module(module, run_name="__main__", alter_sys=True)
  File "C:\Users\zy199\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "C:\Users\zy199\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\zy199\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\vscode_datascience_helpers\daemon\__main__.py", line 137, in <module>
    main()
  File "c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\vscode_datascience_helpers\daemon\__main__.py", line 133, in main
    raise Exception("Failed to start daemon")
Exception: Failed to start daemon

Error 2020-11-18 13:11:22: Failed to start the Daemon, ProcEndEx [Error: Timeout waiting for daemon to start
	at Timeout._onTimeout (c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\out\client\extension.js:32:194215)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)]
Error 2020-11-18 13:11:22: Failed  to start the Daemon, Ex [Error: Timeout waiting for daemon to start
	at Timeout._onTimeout (c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\out\client\extension.js:32:194215)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)]
Error 2020-11-18 13:11:22: Pinging Daemon Failed, Class name = h, completed in 5003ms, has a falsy return value, Arg 1: {}, Return Value: undefined [Error: Timeout waiting for daemon to start
	at Timeout._onTimeout (c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\out\client\extension.js:32:194215)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)]
Error 2020-11-18 13:11:22: Failed to create daemon, Class name = h, completed in 5012ms, has a falsy return value, , Return Value: undefined [Error: Timeout waiting for daemon to start
	at Timeout._onTimeout (c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\out\client\extension.js:32:194215)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)]
Error 2020-11-18 13:11:22: Failed to create the daemon service, defaulting to activated environment [Error: Timeout waiting for daemon to start
	at Timeout._onTimeout (c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\out\client\extension.js:32:194215)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)]
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\pyvsc-run-isolated.py ipykernel_launcher --ip=127.0.0.1 --stdin=9013 --control=9011 --hb=9010 --Session.signature_scheme="hmac-sha256" --Session.key=b"fa159c97-f669-4707-a938-c0466f50f7d4" --shell=9012 --transport="tcp" --iopub=9014 --f=C:\Users\zy199\AppData\Local\Temp\tmp-4648ze1U891C3M4E.json
cwd: c:\Users\zy199\Desktop\java
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\pyvsc-run-isolated.py ipykernel_launcher --ip=127.0.0.1 --stdin=9013 --control=9011 --hb=9010 --Session.signature_scheme="hmac-sha256" --Session.key=b"fa159c97-f669-4707-a938-c0466f50f7d4" --shell=9012 --transport="tcp" --iopub=9014 --f=C:\Users\zy199\AppData\Local\Temp\tmp-4648ze1U891C3M4E.json
cwd: c:\Users\zy199\Desktop\java
> ~\AppData\Local\Programs\Python\Python39\python.exe -c "import os;print(os.path.realpath("C:\\Users\\zy199\\AppData\\Roaming\\jupyter\\kernels"))"
> ~\AppData\Local\Programs\Python\Python39\python.exe -c "import os;print(os.path.realpath("C:\\Users\\zy199\\AppData\\Roaming\\jupyter\\kernels"))"
Error 2020-11-18 13:11:24: Jupyter Kernel Spec not found for a local connection
Error 2020-11-18 13:11:30: Jupyter Kernel Spec not found for a local connection
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Error 2020-11-18 13:11:35: Failed to start the Daemon, StdErr:  Traceback (most recent call last):
  File "c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\vscode_datascience_helpers\daemon\__main__.py", line 126, in main
    daemon_module = importlib.import_module(args.daemon_module)
  File "C:\Users\zy199\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\vscode_datascience_helpers\kernel_launcher_daemon.py", line 22, in <module>
    from vscode_datascience_helpers.kernel_launcher import launch_kernel
  File "c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\vscode_datascience_helpers\kernel_launcher.py", line 14, in <module>
    from ipython_genutils.encoding import getdefaultencoding
ModuleNotFoundError: No module named 'ipython_genutils'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\pyvsc-run-isolated.py", line 26, in <module>
    runpy.run_module(module, run_name="__main__", alter_sys=True)
  File "C:\Users\zy199\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "C:\Users\zy199\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\zy199\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\vscode_datascience_helpers\daemon\__main__.py", line 137, in <module>
    main()
  File "c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\vscode_datascience_helpers\daemon\__main__.py", line 133, in main
    raise Exception("Failed to start daemon")
Exception: Failed to start daemon

Error 2020-11-18 13:11:35: Failed to start the Daemon, ProcEndEx [Error: Timeout waiting for daemon to start
	at Timeout._onTimeout (c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\out\client\extension.js:32:194215)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)]
Error 2020-11-18 13:11:35: Failed  to start the Daemon, Ex [Error: Timeout waiting for daemon to start
	at Timeout._onTimeout (c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\out\client\extension.js:32:194215)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)]
Error 2020-11-18 13:11:35: Pinging Daemon Failed, Class name = h, completed in 5004ms, has a falsy return value, Arg 1: {}, Return Value: undefined [Error: Timeout waiting for daemon to start
	at Timeout._onTimeout (c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\out\client\extension.js:32:194215)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)]
Error 2020-11-18 13:11:35: Failed to create daemon, Class name = h, completed in 5012ms, has a falsy return value, , Return Value: undefined [Error: Timeout waiting for daemon to start
	at Timeout._onTimeout (c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\out\client\extension.js:32:194215)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)]
Error 2020-11-18 13:11:35: Failed to create the daemon service, defaulting to activated environment [Error: Timeout waiting for daemon to start
	at Timeout._onTimeout (c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\out\client\extension.js:32:194215)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)]
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\pyvsc-run-isolated.py ipykernel_launcher --ip=127.0.0.1 --stdin=9018 --control=9016 --hb=9015 --Session.signature_scheme="hmac-sha256" --Session.key=b"f811e045-e594-4f3e-bcdf-e3001acf9497" --shell=9017 --transport="tcp" --iopub=9019 --f=C:\Users\zy199\AppData\Local\Temp\tmp-4648XBx9s9DvxsW2.json
cwd: ~\AppData\Local\Programs\Microsoft VS Code Insiders
> ~\AppData\Local\Programs\Python\Python39\python.exe c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\pythonFiles\pyvsc-run-isolated.py ipykernel_launcher --ip=127.0.0.1 --stdin=9018 --control=9016 --hb=9015 --Session.signature_scheme="hmac-sha256" --Session.key=b"f811e045-e594-4f3e-bcdf-e3001acf9497" --shell=9017 --transport="tcp" --iopub=9019 --f=C:\Users\zy199\AppData\Local\Temp\tmp-4648XBx9s9DvxsW2.json
cwd: ~\AppData\Local\Programs\Microsoft VS Code Insiders
Error 2020-11-18 13:11:49: Timed out waiting to get a heartbeat from kernel process.
Error 2020-11-18 13:11:52: Timed out waiting to get a heartbeat from kernel process.
Error 2020-11-18 13:12:05: Timed out waiting to get a heartbeat from kernel process.
Error 2020-11-18 13:12:05: Failed to connect raw kernel session: Error: Timed out waiting to get a heartbeat from kernel process.
Error 2020-11-18 13:12:05: failed to create INotebook in kernel [Error: Timed out waiting to get a heartbeat from kernel process.
	at m.waitForHeartbeat (c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\out\client\extension.js:49:646443)]
Error 2020-11-18 13:12:05: DataScience Error [Error: Timed out waiting to get a heartbeat from kernel process.
	at m.waitForHeartbeat (c:\Users\zy199\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.11.358541065\out\client\extension.js:49:646443)]

```

</p>
</details>

**Comment by rchiodo** [comment]
This is the problem:

```No module named 'ipython_genutils'```

The python interpreter you're using doesn't seem to have ipython installed correctly. 

If you create a new virtual environment and follow the same steps, does it work then?
