### ISSUE TITLE
IpyKernel install failure in virtual env

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#3996]
(jupyter_runner) (rchiodo/logger_api) D:\Source\jupyter_server>d:/Source/jupyter_server/.vscode/jupyter_runner/Scripts/python.exe c:\Users\Rich\.vscode\extensions\ms-python.python-2020.11.371526539\pythonFiles\pyvsc-run-isolated.py c:\Users\Rich\.vscode\extensions\ms-python.python-2020.11.371526539\pythonFiles\shell_exec.py d:/Source/jupyter_server/.vscode/jupyter_runner/Scripts/python.exe c:\Users\Rich\.vscode\extensions\ms-python.python-2020.11.371526539\pythonFiles\pyvsc-run-isolated.py pip install -U ipykernel --user C:/Users/Rich/AppData/Local/Temp/tmp-19260i0kOlQ9Y69rj.log
Executing command in shell >> d:/Source/jupyter_server/.vscode/jupyter_runner/Scripts/python.exe c:\Users\Rich\.vscode\extensions\ms-python.python-2020.11.371526539\pythonFiles\pyvsc-run-isolated.py pip install -U ipykernel --user
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
WARNING: You are using pip version 20.2.3; however, version 20.2.4 is available.
You should consider upgrading via the 'd:\Source\jupyter_server\.vscode\jupyter_runner\Scripts\python.exe -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "c:\Users\Rich\.vscode\extensions\ms-python.python-2020.11.371526539\pythonFiles\shell_exec.py", line 26, in <module>
    subprocess.check_call(shell_args, stdout=sys.stdout, stderr=sys.stderr)
  File "C:\Users\Rich\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['d:/Source/jupyter_server/.vscode/jupyter_runner/Scripts/python.exe', 'c:\\Users\\Rich\\.vscode\\extensions\\ms-python.python-2020.11.371526539\\pythonFiles\\pyvsc-run-isolated.py', 'pip', 'install', '-U', 'ipykernel', '--user']' returned non-zero exit status 1.

**Comment by DonJayamanne** [comment]
Looks like your virtual env was NOT detected as being a virtual env.
