### ISSUE TITLE
"%matplotlib notebook" not working in jupyter notebook

### ISSUE THREAD

**Issue by Bipul-Harsh** [microsoft/vscode-jupyter#4056]
## Environment data

-   VS Code version: 1.51.1
-   Jupyter Extension version (available under the Extensions sidebar): v2020.11.392013122
-   Python Extension version (available under the Extensions sidebar): 3.8.6
-   OS (Windows | Mac | Linux distro) and version: Windows 10 20H2
-   Python and/or Anaconda version: 3.8.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

Should show interactive window

## Actual behaviour

Error Reporting:
ReferenceError: IPython is not defined

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Install Python extension by Microsoft
2. Open Jupyter notebook (Inside vscode with help of extension)
3. Type "%matplotlib notebook"
4. Enter code:
##Start
import numpy as np
import matplitlib.pyplot as plt
import matplotlib.animation as animation
n = 100
x = np.random.randn(n)

def update(curr):
#check if animation is at the last frame, and if so, stop the animation a
if curr == n:
a.event_source.stop()
plt.cla()
bins = np.arange(-4, 4, 0.5)
plt.hist(x[:curr], bins=bins)
plt.axis([-4,4,0,30])
plt.gca().set_title('Sampling the Normal Distribution')
plt.gca().set_ylabel('Frequency')
plt.gca().set_xlabel('Value')
plt.annotate('n = {}'.format(curr), [3,27])

fig = plt.figure()
a = animation.FuncAnimation(fig, update, interval=100)
##END

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by Bipul-Harsh** [comment]
Even though its working when creating local server with cmd "jupyter notebook", but not working inside vscode.

**Comment by IanMatthewHuff** [comment]
@Bipul-Harsh Sorry about the issue. Pulling your logs here would be the most helpful thing. In VS Code settings set Jupyter->Logging->Level to "debug." Then re-run your scenario. After that copy out the contents of the Output window Jupyter tab. That should have most of the info to help us debug this. 

Also, when running your code in VS Code are you using the same environment as you are using when running "jupyter notebook" directly?

**Comment by Bipul-Harsh** [comment]
ReferenceError: IPython is not defined
    at eval (eval at runCodeHere (vscode-webview-resource://d1ff7912-58b4-4362-ab14-98502fc11542/file///c%3A/Users/bipul/.vscode/extensions/ms-toolsai.jupyter-2020.11.392013122/out/datascience-ui/notebook/vendors~nteract_transforms.bundle.js:2:12595), <anonymous>:926:1)
    at runCodeHere (vscode-webview-resource://d1ff7912-58b4-4362-ab14-98502fc11542/file///c%3A/Users/bipul/.vscode/extensions/ms-toolsai.jupyter-2020.11.392013122/out/datascience-ui/notebook/vendors~nteract_transforms.bundle.js:2:12595)
    at t.value (vscode-webview-resource://d1ff7912-58b4-4362-ab14-98502fc11542/file///c%3A/Users/bipul/.vscode/extensions/ms-toolsai.jupyter-2020.11.392013122/out/datascience-ui/notebook/vendors~nteract_transforms.bundle.js:2:13027)
    at Ta (vscode-webview-resource://d1ff7912-58b4-4362-ab14-98502fc11542/file///c%3A/Users/bipul/.vscode/extensions/ms-toolsai.jupyter-2020.11.392013122/out/datascience-ui/notebook/commons.initial.bundle.js:2:2398498)
    at Pa (vscode-webview-resource://d1ff7912-58b4-4362-ab14-98502fc11542/file///c%3A/Users/bipul/.vscode/extensions/ms-toolsai.jupyter-2020.11.392013122/out/datascience-ui/notebook/commons.initial.bundle.js:2:2401420)
    at vscode-webview-resource://d1ff7912-58b4-4362-ab14-98502fc11542/file///c%3A/Users/bipul/.vscode/extensions/ms-toolsai.jupyter-2020.11.392013122/out/datascience-ui/notebook/commons.initial.bundle.js:2:2414498
    at Object.t.unstable_runWithPriority (vscode-webview-resource://d1ff7912-58b4-4362-ab14-98502fc11542/file///c%3A/Users/bipul/.vscode/extensions/ms-toolsai.jupyter-2020.11.392013122/out/datascience-ui/notebook/commons.initial.bundle.js:2:25134)
    at Ms (vscode-webview-resource://d1ff7912-58b4-4362-ab14-98502fc11542/file///c%3A/Users/bipul/.vscode/extensions/ms-toolsai.jupyter-2020.11.392013122/out/datascience-ui/notebook/commons.initial.bundle.js:2:2414432)
    at xs (vscode-webview-resource://d1ff7912-58b4-4362-ab14-98502fc11542/file///c%3A/Users/bipul/.vscode/extensions/ms-toolsai.jupyter-2020.11.392013122/out/datascience-ui/notebook/commons.initial.bundle.js:2:2414208)
    at Es (vscode-webview-resource://d1ff7912-58b4-4362-ab14-98502fc11542/file///c%3A/Users/bipul/.vscode/extensions/ms-toolsai.jupyter-2020.11.392013122/out/datascience-ui/notebook/commons.initial.bundle.js:2:2413553)

**Comment by Bipul-Harsh** [comment]
This is what actually written in error.

**Comment by Bipul-Harsh** [comment]
Regarding the environment both are using the same python3 version installed in my pc. The jupyter notebook I run on cmd opens default web browser for interface while in vscode it with MS python extension it opens within it.

**Comment by Bipul-Harsh** [comment]
I think there might be some feature missing in the extension regarding IPython, as regarding normal plotting with matplotlib it didnt didnt give any error, but with Interactive plotting it gives error.

While running on browser offline with local server it works for interactive plotting also, so that could be the issue.

**Comment by Bipul-Harsh** [comment]
So, I hope I have provided the info needed

**Comment by IanMatthewHuff** [comment]
@Bipul-Harsh Thanks for the info. I poked around a bit more, and found that we don't actually support the notebook mode for matplot lib currently. Seems like you can try using the widget mode instead, which should work as we support IPyWidgets.

https://github.com/microsoft/vscode-jupyter/issues/1948
