### ISSUE TITLE
Add tests to run C# raw kernel

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4061]
A change broken running C# raw kernels.
Fix reverted in https://github.com/microsoft/vscode-jupyter/pull/4060
We need to ensure we have tests &   do not regress again.

**Comment by DonJayamanne** [comment]
.NET Interactive kernel does not run on CI
```
4950 Info 2020-12-07 21:06:36: > dotnet interactive jupyter --default-kernel csharp --http-port-range 1000-3000 /tmp/tmp-4950jJDwGDmr8xQx.json
4950 Info 2020-12-07 21:06:36: cwd: ~/work/vscode-jupyter/vscode-jupyter/tmp

Error: r]: Unable to read file '/home/runner/work/vscode-jupyter/vscode-jupyter/out/ipywidgets/dist/ipywidgets.js' (Error: Unable to resolve non-existing file '/home/runner/work/vscode-jupyter/vscode-jupyter/out/ipywidgets/dist/ipywidgets.js')
    at S.doReadAsFileStream (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:320:417)
    at async Object.readFileStream (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:493:669)
    at async Object.t.loadLocalResource (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:485:920)
    at async t.handleWebviewResourceRequest (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:494:95) {
  fileOperationResult: 1,
  options: undefined
}

Error: r]: Unable to read file '/home/runner/work/vscode-jupyter/vscode-jupyter/out/datascience-ui/ipywidgetsKernel/ipywidgetsKernel.js' (Error: Unable to resolve non-existing file '/home/runner/work/vscode-jupyter/vscode-jupyter/out/datascience-ui/ipywidgetsKernel/ipywidgetsKernel.js')
    at S.doReadAsFileStream (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:320:417)
    at async Object.readFileStream (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:493:669)
    at async Object.t.loadLocalResource (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:485:920)
    at async t.handleWebviewResourceRequest (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:494:95) {
  fileOperationResult: 1,
  options: undefined
}

Error: r]: Unable to read file '/home/runner/work/vscode-jupyter/vscode-jupyter/out/datascience-ui/ipywidgetsKernel/require.js' (Error: Unable to resolve non-existing file '/home/runner/work/vscode-jupyter/vscode-jupyter/out/datascience-ui/ipywidgetsKernel/require.js')
    at S.doReadAsFileStream (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:320:417)
    at async Object.readFileStream (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:493:669)
    at async Object.t.loadLocalResource (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:485:920)
    at async t.handleWebviewResourceRequest (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:494:95) {
  fileOperationResult: 1,
  options: undefined
}

4950 Info 2020-12-07 21:06:36: KernelProcess error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DotNet.Cli.Utils.EnvironmentProvider.get_SearchPaths()
   at Microsoft.DotNet.Cli.Utils.EnvironmentProvider.GetCommandPath(String commandName, String[] ext
4950 Warn 2020-12-07 21:06:36: StdErr from Kernel Process System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DotNet.Cli.Utils.EnvironmentProvider.get_SearchPaths()
   at Microsoft.DotNet.Cli.Utils.EnvironmentProvider.GetCommandPath(String commandName, String[] ext
4950 Info 2020-12-07 21:06:36: KernelProcess error: ensions)
   at Microsoft.DotNet.CommandFactory.PathCommandResolver.ResolveCommandPath(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.CommandFactory.AbstractPathBasedCommandResolver.Resolve(CommandResolverArguments commandResolver
4950 Warn 2020-12-07 21:06:36: StdErr from Kernel Process ensions)
   at Microsoft.DotNet.CommandFactory.PathCommandResolver.ResolveCommandPath(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.CommandFactory.AbstractPathBasedCommandResolver.Resolve(CommandResolverArguments commandResolver

4950 Info 2020-12-07 21:06:36: KernelProcess error: Arguments)
   at Microsoft.DotNet.CommandFactory.CompositeCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.CommandFactory.CommandResolver.TryResolveCommandSpec(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.CommandFactory.CommandFactoryUsingResolver.Create(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

4950 Warn 2020-12-07 21:06:36: StdErr from Kernel Process Arguments)
   at Microsoft.DotNet.CommandFactory.CompositeCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.CommandFactory.CommandResolver.TryResolveCommandSpec(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.CommandFactory.CommandFactoryUsingResolver.Create(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

```

**Comment by DonJayamanne** [comment]
Moving back to new issues to determine how we address this issue.

**Comment by DonJayamanne** [comment]
Fixed tests
* C# kernel sends mutliple outputs instead of one (the first output contains some JS code in an HTML output that seems to be very specific to Jupter UI).
* Also C# kernels dno't work if theres no jupyter installed

**Comment by joyceerhl** [comment]
Was trying to validate this, but it doesn't look like C# tests are running? https://github.com/microsoft/vscode-jupyter/runs/1540801476?check_suite_focus=true

**Comment by DonJayamanne** [comment]
They are running on PRs, see here https://github.com/microsoft/vscode-jupyter/runs/1540872513#step:33:12994
![Screen Shot 2021-01-04 at 12 10 15](https://user-images.githubusercontent.com/1948812/103575043-dec4fa00-4e85-11eb-8f69-69f253282bfd.png)

**Comment by IanMatthewHuff** [comment]
Validated. Test are running on PRs
