### ISSUE TITLE
Cannot export .ipynb file to .py file.

### ISSUE THREAD

**Issue by jekegren01** [microsoft/vscode-jupyter#4071]
## Environment data

-   Jupyter Extension version (available under the Extensions sidebar): v2020.11.392013122
-   Python Extension version (available under the Extensions sidebar): 3.9
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

I expected it to export to a .py file.

## Actual behaviour

I got an error. 

## Steps to reproduce:

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

</p>

![image](https://user-images.githubusercontent.com/62910279/100811483-9b432000-33ef-11eb-9b2f-c9caee89e3f4.png)

> /usr/local/opt/python@3.9/bin/python3.9 ~/.vscode/extensions/ms-toolsai.jupyter-2020.11.392013122/pythonFiles/pyvsc-run-isolated.py jupyter nbconvert --version
> /usr/local/opt/python@3.9/bin/python3.9 ~/.vscode/extensions/ms-toolsai.jupyter-2020.11.392013122/pythonFiles/pyvsc-run-isolated.py jupyter nbconvert --version
Error 2020-12-01 16:05:31: Export failed [r [Error]: Traceback (most recent call last):
  File "/Users/JacobEkegren/.vscode/extensions/ms-toolsai.jupyter-2020.11.392013122/pythonFiles/pyvsc-run-isolated.py", line 26, in <module>
    runpy.run_module(module, run_name="__main__", alter_sys=True)
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/JacobEkegren/Library/Python/3.9/lib/python/site-packages/jupyter.py", line 4, in <module>
    main()
  File "/Users/JacobEkegren/Library/Python/3.9/lib/python/site-packages/jupyter_core/command.py", line 285, in main
    command = _jupyter_abspath(subcommand)
  File "/Users/JacobEkegren/Library/Python/3.9/lib/python/site-packages/jupyter_core/command.py", line 124, in _jupyter_abspath
    raise Exception(
Exception: Jupyter command `jupyter-nbconvert` not found.

	at ChildProcess.<anonymous> (/Users/JacobEkegren/.vscode/extensions/ms-toolsai.jupyter-2020.11.392013122/out/client/extension.js:9:101413)
	at Object.onceWrapper (events.js:313:26)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)]

</details>

**Comment by rchiodo** [comment]
Thanks for the bug. It looks like you don't have nbconvert installed correctly into your interpreter. 

You can try fixing this by:

1. Creating a new environment from scratch. We should prompt you to install ipykernel which will download nbconvert.
1. Try installing nbconvert yourself into your 3.9 environment.

**Comment by greazer** [comment]
@jekegren01, please reopen if Rich's suggestion doesn't fix it for you.
