### ISSUE TITLE
Unable to connect to Jupyter notebook

### ISSUE THREAD

**Issue by jwguo321** [microsoft/vscode-jupyter#4075]
Hello, everyone 
I'm using a MacBook with Apple M1 chip,  jupyter extension seems not to work. 
Here are the details
## Environment data

-   VS Code version: .152.0-exploration
-   Jupyter Extension version: 2020.11.392013122
-   Python Extension version: 2020.11.371526539
-   OS (Windows | Mac | Linux distro) and version: macOS Big Sur 11.0.1
-   Python and/or Anaconda version: Python 3.8.5 and Anaconda 1.10.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda base
-   Jupyter server running: Local

## Expected behaviour

Successfully connected to the jupyter server

## Actual behaviour

Prompt "Failed to connect to Jupyter notebook. 
http://localhost:8888/
Error: Kernel Python 3.8.5 64-bit is not usable. Check the Jupyter output tab for more information."

## Logs

Error: Kernel Python 3.8.5 64-bit is not usable. Check the Jupyter output tab for more information.
	at v.createNewKernelSession (/Users/junwei/.vscode-exploration/extensions/ms-toolsai.jupyter-2020.11.392013122/out/client/extension.js:49:559716)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async v.connect (/Users/junwei/.vscode-exploration/extensions/ms-toolsai.jupyter-2020.11.392013122/out/client/extension.js:49:559183)
	at async m.startNew (/Users/junwei/.vscode-exploration/extensions/ms-toolsai.jupyter-2020.11.392013122/out/client/extension.js:49:554651)
	at async y.connect (/Users/junwei/.vscode-exploration/extensions/ms-toolsai.jupyter-2020.11.392013122/out/client/extension.js:49:525584)
	at async /Users/junwei/.vscode-exploration/extensions/ms-toolsai.jupyter-2020.11.392013122/out/client/extension.js:32:616325]
> /usr/bin/python3 ~/.vscode-exploration/extensions/ms-toolsai.jupyter-2020.11.392013122/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> /usr/bin/python3 ~/.vscode-exploration/extensions/ms-toolsai.jupyter-2020.11.392013122/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
[W 13:41:19.021 NotebookApp] Unexpected error while saving file: Untitled.ipynb [Errno 30] Read-only file system: '/Untitled.ipynb'
> /usr/bin/python3 (daemon) ~/.vscode-exploration/extensions/ms-toolsai.jupyter-2020.11.392013122/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> /usr/bin/python3 (daemon) ~/.vscode-exploration/extensions/ms-toolsai.jupyter-2020.11.392013122/pythonFiles/vscode_datascience_helpers/getServerInfo.py
[E 13:41:19.021 NotebookApp] {
      "Content-Type": "application/json",
      "Authorization": "token bd9faa94e7f0b7f9045b0cca84d3cb4b439766b67e68eb14",
      "Accept": "*/*",
      "Content-Length": "19",
      "User-Agent": "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)",
      "Accept-Encoding": "gzip,deflate",
      "Connection": "close",
      "Host": "localhost:8888"
    }
[E 13:41:19.021 NotebookApp] 500 POST /api/contents/?1606887679017 (127.0.0.1) 1.67ms referer=None

**Comment by rchiodo** [comment]
Thanks for the bug.

The root cause is here:
```
Unexpected error while saving file: Untitled.ipynb [Errno 30] Read-only file system: '/Untitled.ipynb'
```

This is happening because your remote server (which looks like you have it set to a server you started on your own machine) doesn't have write access to the root folder. 

Do you need to run your own server? You could pick 'Default' in the 'Specify local or remote Jupyter server for connections'
![image](https://user-images.githubusercontent.com/19672699/100915621-769b8680-3489-11eb-83e2-fc8b2f59db1b.png)

**Comment by aeharding** [comment]
I also am experiencing this problem. 

I am just running "default" and it still fails.

**Comment by jwguo321** [comment]
> I also am experiencing this problem.
> 
> I am just running "default" and it still fails.
> 
> ![image](https://user-images.githubusercontent.com/2166114/103366344-03853000-4a88-11eb-9f7b-369c527ab5fd.png)

Are you using VS Code stable or preview?  I changed my VS Code from preview version to a stable version, and the problem is gone.

**Comment by ckulas** [comment]
Had the same problem, also with the Insiders version. Jupyter tried to write in the / directory for me, which is of course not possible. I fixed it by passing a valid working directory in the Jupyter extension settings like so:

```
"jupyter.jupyterCommandLineArguments": [
        "<You home directory> "
    ]
```

**Comment by achintya-7** [comment]
> Had the same problem, also with the Insiders version. Jupyter tried to write in the / directory for me, which is of course not possible. I fixed it by passing a valid working directory in the Jupyter extension settings like so:
> 
> ```
> "jupyter.jupyterCommandLineArguments": [
>         "<You home directory> "
>     ]
> ```

Thank you, this worked for me finally after browsing through net for 2 hours
