### ISSUE TITLE
Export to HTML from command palette fails where export from toolbar succeeds

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#4155]
If I run the 'Export to HTML' command it fails with the following error:
```
Error 2020-12-07 20:58:07: Export failed [Error: Importing notebooks requires Jupyter nbconvert to be installed.
	at u.getExportInterpreter (/Users/Joyce/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.11.399280825/out/client/extension.js:32:528110)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async _.export (/Users/Joyce/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.11.399280825/out/client/extension.js:49:256389)
	at async m.export (/Users/Joyce/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.11.399280825/out/client/extension.js:32:256582)]
```

However if I export the exact same notebook from the webview-based notebook toolbar, the export succeeds, as my active Python environment does have nbconvert installed. Suggests we're checking if nbconvert is installed with the wrong interpreter in the command palette case. I have the same environment selected as my Python interpreter and active kernel.

**Comment by CaptainDario** [comment]
I encounter the same issue.
As stated above the only option seems to be to start jupyter manually and export from the web browser.

**Comment by joyceerhl** [comment]
@CaptainDario you should still be able to export from inside VSCode using the Export As button in the notebook toolbar:

![image](https://user-images.githubusercontent.com/30305945/103035348-fdd59a80-451b-11eb-993f-6c6d70e16692.png)

**Comment by CaptainDario** [comment]
Sadly that does not work for me. I get the following error message:

```
> e:\projects\DaKanjiRecognizer\.venv_dev\Scripts\python.exe c:\Users\dario\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py jupyter nbconvert c:\Users\dario\AppData\Local\Temp\523d4b3d-7196-434a-a8ac-fc6cc4b3d781\DaKanjiRecognizer.ipynb --to html --output tmp-19184x6gi4wMNl4oi.html --output-dir ~\AppData\Local\Temp --debug
Error 2020-12-23 22:20:49: Export failed [Error: 
	at a.executeCommand (c:\Users\dario\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:1:448888)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async a.export (c:\Users\dario\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:253800)
	at async _.exportToFormat (c:\Users\dario\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:252766)
	at async _.performExport (c:\Users\dario\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:251809)
	at async _.export (c:\Users\dario\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:251323)
	at async m.export (c:\Users\dario\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:32:265964)]
```

**Comment by joyceerhl** [comment]
That sounds like a different bug then. Is `nbconvert` installed into this environment? 
> e:\projects\DaKanjiRecognizer\.venv_dev\Scripts\python.exe

**Comment by CaptainDario** [comment]
Yes, it is installed in this environment. However the path you wrote is missing a slash (not sure if that was a copy and paste mistake)
When I start jupyter manually on the command line with:
```e:\projects\DaKanjiRecognizer\.venv_dev\Scripts\python.exe -m jupyter --port=8888```
I can export to .html.

**Comment by greazer** [comment]
This has been fixed. I no longer repro.
