### ISSUE TITLE
StdErr from ShellExec, stty: stdin isn't a terminal

### ISSUE THREAD

**Issue by pokey** [microsoft/vscode-jupyter#4157]
When I try to run a cell in a Jupyter notebook, I get the following error:

```
StdErr from ShellExec, stty: stdin isn't a terminal stty: stdin isn't a terminal stty: stdin isn't a terminal stty: stdin isn't a terminal for . /Users/pokey/.venv/flashcards-test/bin/activate && echo '718d24f2-8b10-48f3-8ad3-723876a19613' && python /Users/pokey/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/pyvsc-run-isolated.py /Users/pokey/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/printEnvVariables.py
```

## Environment data

-   VS Code version: Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
-   Jupyter Extension version (available under the Extensions sidebar): v2020.11.399280825
-   Python Extension version (available under the Extensions sidebar): v2020.11.371526539
-   OS (Windows | Mac | Linux distro) and version: macOS Catalina 10.15.7 (19H15)
-   Python and/or Anaconda version: Python 3.8.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local

## Expected behaviour

The cell runs

## Actual behaviour

The error message above

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Open a jupyter notebook
2. Run a cell

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Error 2020-12-08 15:36:01: Install Missing Dependencies, Class name = f, completed in 1783ms, has a falsy return value, Return Value: undefined [Error: StdErr from ShellExec, stty: stdin isn't a terminal
stty: stdin isn't a terminal
stty: stdin isn't a terminal
stty: stdin isn't a terminal
 for . /Users/pokey/.venv/flashcards-test/bin/activate && echo '718d24f2-8b10-48f3-8ad3-723876a19613' && python /Users/pokey/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/pyvsc-run-isolated.py /Users/pokey/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/printEnvVariables.py
	at P.getActivatedEnvironmentVariablesImpl (/Users/pokey/.vscode/extensions/ms-python.python-2020.11.371526539/out/client/extension.js:39:306435)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)]
Error 2020-12-08 15:36:01: Find kernel spec, Class name = T, completed in 3845ms, has a falsy return value, Arg 1: <Uri:/Users/pokey/src/flashcards-training/notebooks/scheduler-analysis.ipynb>, Arg 2: {"jupytext":{"formats":"ipynb,py:percent"},"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"}}, Arg 3: undefined, Arg 4: undefined, Return Value: undefined [Error: StdErr from ShellExec, stty: stdin isn't a terminal
stty: stdin isn't a terminal
stty: stdin isn't a terminal
stty: stdin isn't a terminal
 for . /Users/pokey/.venv/flashcards-test/bin/activate && echo '718d24f2-8b10-48f3-8ad3-723876a19613' && python /Users/pokey/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/pyvsc-run-isolated.py /Users/pokey/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/printEnvVariables.py
	at P.getActivatedEnvironmentVariablesImpl (/Users/pokey/.vscode/extensions/ms-python.python-2020.11.371526539/out/client/extension.js:39:306435)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)]
Error 2020-12-08 15:36:01: Exception attempting to start notebook:  [Error: StdErr from ShellExec, stty: stdin isn't a terminal
stty: stdin isn't a terminal
stty: stdin isn't a terminal
stty: stdin isn't a terminal
 for . /Users/pokey/.venv/flashcards-test/bin/activate && echo '718d24f2-8b10-48f3-8ad3-723876a19613' && python /Users/pokey/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/pyvsc-run-isolated.py /Users/pokey/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/printEnvVariables.py
	at P.getActivatedEnvironmentVariablesImpl (/Users/pokey/.vscode/extensions/ms-python.python-2020.11.371526539/out/client/extension.js:39:306435)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)]
Error 2020-12-08 15:36:01: DataScience Error [Error: StdErr from ShellExec, stty: stdin isn't a terminal
stty: stdin isn't a terminal
stty: stdin isn't a terminal
stty: stdin isn't a terminal
 for . /Users/pokey/.venv/flashcards-test/bin/activate && echo '718d24f2-8b10-48f3-8ad3-723876a19613' && python /Users/pokey/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/pyvsc-run-isolated.py /Users/pokey/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/printEnvVariables.py
	at P.getActivatedEnvironmentVariablesImpl (/Users/pokey/.vscode/extensions/ms-python.python-2020.11.371526539/out/client/extension.js:39:306435)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)]
Error 2020-12-08 15:36:01: DataScience Error [Error: StdErr from ShellExec, stty: stdin isn't a terminal
stty: stdin isn't a terminal
stty: stdin isn't a terminal
stty: stdin isn't a terminal
 for . /Users/pokey/.venv/flashcards-test/bin/activate && echo '718d24f2-8b10-48f3-8ad3-723876a19613' && python /Users/pokey/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/pyvsc-run-isolated.py /Users/pokey/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/printEnvVariables.py
	at P.getActivatedEnvironmentVariablesImpl (/Users/pokey/.vscode/extensions/ms-python.python-2020.11.371526539/out/client/extension.js:39:306435)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)]
```

</p>
</details>

**Comment by DonJayamanne** [comment]
Please confirm this option environment is 3.8 and it's a venv `Users/pokey/.venv/flashcards-test/bin/activate`

**Comment by DonJayamanne** [comment]
Please could you open the python output panel and copy the comments from that too, I'm interested in the first 10 lines of the output (to see what experiments this instance of vscode belongs to)

**Comment by DonJayamanne** [comment]
We have been looking into this issue for a few days now and found that some users managed to get this working switching to the latest version of VSCode insiders.

Please could you let us know whether it works for you when you use VSCode insiders. Total help narrow down the problem. 
Thanks again

**Comment by pokey** [comment]
Thanks for the quick response!  To answer your questions:

> Please confirm this option environment is 3.8 and it's a venv Users/pokey/.venv/flashcards-test/bin/activate

Yes it's a `venv`, but it is Python 3.7.3

> Please could you open the python output panel and copy the contents from that too, I'm interested in the first 10 lines of the output (to see what experiments this instance of vscode belongs to)

```
User belongs to experiment group 'AlwaysDisplayTestExplorer - control'
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'DeprecatePythonPath - experiment'
User belongs to experiment group 'RunByLine - experiment'
User belongs to experiment group 'CustomEditorSupport - control'
User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonSendEntireLineToREPLcf'
```

> Please could you let us know whether it works for you when you use VSCode insiders

Nope same issue with insiders' build 😕

Fwiw I have pyenv-virtualenv installed on my system, but I'm not using that for this virtualenv, and it appears that it shouldn't have an impact; when I open a terminal in VSCode here's what I get:

```sh
➜ source /Users/pokey/.venv/flashcards-test/bin/activate
➜ python --version
Python 3.7.3
➜ which python
/Users/pokey/.venv/flashcards-test/bin/python
```

Note that the first line wasn't typed by me, but automatically by VSCode
