### ISSUE TITLE
Can't select my custom kernel in the Interactive kernel selection window

### ISSUE THREAD

**Issue by akdor1154** [microsoft/vscode-jupyter#4201]
I have a custom jupyter kernel that runs `python` in the current Poetry-managed virtualenv, if there is one. Kernelspec:
```json
{
 "argv": [
  "poetry", "run", "python",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "Python 3 (Poetry)",
 "language": "python"
}
```

This works great in Jupyter Notebook (i.e. `pip install notebook; jupyter notebook .`). VSCode doesn't even show it in its kernel list.

- Kernel list is browsed by:
- Open a `.py` file
- Make a code cell by typing
  ```
  # %%
  print('hi')
  ```
- Hit shift+enter to Run Cell in Interactive Window
- (Interactive window opens with Jupyter Server and Kernel dropdowns; server is set to local)
- Click the current Python kernel up the top right of the interactive window to try and change it to the poetry one above
- Observe that Python 3 (Poetry) is missing

## Environment data

-   VS Code version: 1.51.1
-   Extension version (available under the Extensions sidebar): ms-python.python 2020.11.371526539
-   OS and version: Ubuntu 20.10 x64
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8 via Ubuntu 20.10 repos
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv as provided by Poetry
-   Relevant/affected Python packages and their versions: XXX
-   Relevant/affected Python-related VS Code extensions and their versions: XXX
-   Value of the `python.languageServer` setting: Jedi

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel </summary>

```
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'ShowExtensionSurveyPrompt - enabled'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'AA_testing - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'RunByLine - experiment'
User belongs to experiment group 'CustomEditorSupport - control'
User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonSendEntireLineToREPLcf'
> conda --version
> pyenv root
> python3.7 ~/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> ~/src/ow/fa/analyses/scratch/.venv/bin/python ~/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda info --json
Python interpreter path: ./.venv/bin/python
Starting Jedi Python language engine.
> conda env list
> conda --version
Error 2020-12-10 17:04:46: Failed to get conda environment list from conda [Error: spawn conda ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:81:21)] {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn conda',
  path: 'conda',
  spawnargs: [ 'env', 'list' ]
}
> ~/src/ow/fa/analyses/scratch/.venv/bin/python ~/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: ~/src/ow/fa/analyses/scratch
> ~/src/ow/fa/analyses/scratch/.venv/bin/python ~/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.prefix)"
cwd: ~/src/ow/fa/analyses/scratch
> ~/src/ow/fa/analyses/scratch/.venv/bin/python ~/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: ~/src/ow/fa/analyses/scratch
> ~/src/ow/fa/analyses/scratch/.venv/bin/python ~/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
cwd: ~/src/ow/fa/analyses/scratch
> ~/src/ow/fa/analyses/scratch/.venv/bin/python ~/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: ~/src/ow/fa/analyses/scratch
> ~/src/ow/fa/analyses/scratch/.venv/bin/python ~/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/pyvsc-run-isolated.py -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
cwd: ~/src/ow/fa/analyses/scratch
> ~/src/ow/fa/analyses/scratch/.venv/bin/python ~/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/pyvsc-run-isolated.py site --user-site
cwd: ~/src/ow/fa/analyses/scratch
> ~/src/ow/fa/analyses/scratch/.venv/bin/python ~/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/pyvsc-run-isolated.py site --user-site
cwd: ~/src/ow/fa/analyses/scratch
> ~/src/ow/fa/analyses/scratch/.venv/bin/python ~/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/pyvsc-run-isolated.py mypy --ignore-missing-imports --follow-imports=silent --strict --check-untyped-defs --disallow-untyped-calls ~/src/ow/fa/analyses/scratch/proportion_instore.py
cwd: ~/src/ow/fa/analyses/scratch
> ~/src/ow/fa/analyses/scratch/.venv/bin/python ~/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/pyvsc-run-isolated.py mypy --ignore-missing-imports --follow-imports=silent --strict --check-untyped-defs --disallow-untyped-calls ~/src/ow/fa/analyses/scratch/proportion_instore.py
cwd: ~/src/ow/fa/analyses/scratch
> ~/src/ow/fa/analyses/scratch/.venv/bin/python ~/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/pyvsc-run-isolated.py mypy --ignore-missing-imports --follow-imports=silent --strict --check-untyped-defs --disallow-untyped-calls ~/src/ow/fa/analyses/scratch/tagWhitelistPreprocessor/setup.py
cwd: ~/src/ow/fa/analyses/scratch
> ~/src/ow/fa/analyses/scratch/.venv/bin/python ~/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/pyvsc-run-isolated.py mypy --ignore-missing-imports --follow-imports=silent --strict --check-untyped-defs --disallow-untyped-calls ~/src/ow/fa/analyses/scratch/tagWhitelistPreprocessor/setup.py
cwd: ~/src/ow/fa/analyses/scratch
> ~/src/ow/fa/analyses/scratch/.venv/bin/python ~/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/pyvsc-run-isolated.py ~/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/completion.py
> ~/src/ow/fa/analyses/scratch/.venv/bin/python ~/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/pyvsc-run-isolated.py ~/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/completion.py
Error 2020-12-10 17:04:47: stderr jediProxy Error (stderr) /home/jarrad/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/completion.py:584: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).get_names instead.
  jedi.api.names(

##########Linting Output - mypy##########
Success: no issues found in 1 source file
##########Linting Output - mypy##########
Success: no issues found in 1 source file
Error 2020-12-10 17:07:19: stderr jediProxy Error (stderr) /home/jarrad/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/completion.py:592: DeprecationWarning: Providing the line is now done in the functions themselves like `Script(...).complete(line, column)`
  script = jedi.Script(
/home/jarrad/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/completion.py:592: DeprecationWarning: Providing the column is now done in the functions themselves like `Script(...).complete(line, column)`
  script = jedi.Script(

Error 2020-12-10 17:07:19: stderr jediProxy Error (stderr) /home/jarrad/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/completion.py:592: DeprecationWarning: Deprecated since version 0.17.0. Use the project API instead, which means Script(project=Project(dir, sys_path=sys_path)) instead.
  script = jedi.Script(
/home/jarrad/.vscode/extensions/ms-python.python-2020.11.371526539/pythonFiles/completion.py:626: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).infer instead.
  script.goto_definitions(), request["id"]

Starting Jedi Python language engine.
```
</details>

**Comment by DonJayamanne** [comment]
Thanks for reporting this issue.
I believe we have addressed this issue in our developement version of the extension.
Please could you download & install the following VSIX (its our latest development version of the extension).

Please extract the zip file and install the VSIX.
[ms-toolsai-jupyter-insiders.vsix-dev.zip](https://github.com/microsoft/vscode-jupyter/files/5675470/ms-toolsai-jupyter-insiders.vsix-dev.zip)

**Comment by akdor1154** [comment]
No luck with that visx sorry :(

Poetry doesn't appear in the list of *interpreters* but I don't expect it to because afaik this doesn't find kernelspecs. I'm referring to the list of *kernels* in the Interactive window (it doesn't appear there either, but I expect it to, hence this bug :) )

![Untitled](https://user-images.githubusercontent.com/6732831/101872123-d6f09d80-3bd8-11eb-8432-99775a3269ef.jpg)


<details><summary>Jupyter logs:</summary>

```
User belongs to experiment group 'NativeNotebookEditor'
Info 2020-12-11 17:40:50: Attempting to start a server because of preload conditions ...
Info 2020-12-11 17:40:50: ZMQ install verified.
Info 2020-12-11 17:40:51: Found existing keyfile at /home/jarrad/.config/Code - Insiders/User/globalStorage/ms-toolsai.jupyter/nbsecret
Info 2020-12-11 17:40:52: > ~/src/ow/dataplatforms/ml-recommender-api-dashboard/.venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.1.413829690-dev/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> ~/src/ow/dataplatforms/ml-recommender-api-dashboard/.venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.1.413829690-dev/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
Info 2020-12-11 17:40:52: > ~/src/ow/dataplatforms/ml-recommender-api-dashboard/.venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.1.413829690-dev/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/src/ow/dataplatforms/ml-recommender-api-dashboard/.venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.1.413829690-dev/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
Info 2020-12-11 17:40:52: > ~/src/ow/dataplatforms/ml-recommender-api-dashboard/.venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.1.413829690-dev/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> ~/src/ow/dataplatforms/ml-recommender-api-dashboard/.venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.1.413829690-dev/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
Info 2020-12-11 17:40:52: > ~/src/ow/dataplatforms/ml-recommender-api-dashboard/.venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.1.413829690-dev/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> ~/src/ow/dataplatforms/ml-recommender-api-dashboard/.venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.1.413829690-dev/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Info 2020-12-11 17:40:53: Python Daemon (pid: 35951): Execute rpc method prewarm_kernel in DS Daemon
Info 2020-12-11 17:40:53: Python Daemon (pid: 35951): Execute rpc method prewarm_kernel from /home/jarrad/src/ow/dataplatforms/ml-recommender-api-dashboard/.venv/bin/python
Info 2020-12-11 17:40:53: Python Daemon (pid: 35951): Pre-Warm DS Kernel in DS Kernel Launcher Daemon
Info 2020-12-11 17:40:53: Python Daemon (pid: 35951): Exec in DS Kernel Launcher Daemon (observable) ['/home/jarrad/src/ow/dataplatforms/ml-recommender-api-dashboard/.venv/bin/python', '/home/jarrad/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.1.413829690-dev/pythonFiles/vscode_datascience_helpers/../pyvsc-run-isolated.py', '/home/jarrad/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.1.413829690-dev/pythonFiles/vscode_datascience_helpers/kernel_prewarm_starter.py']
Info 2020-12-11 17:40:53: Python Daemon (pid: 35951): Exec in DS Kernel Launcher Daemon (observable)
Info 2020-12-11 17:40:53: Python Daemon (pid: 35951): Kernel launched, with PID 35953
Warn 2020-12-11 17:40:53: Python Daemon (pid: 35951): Waiting for Kernel to die 35953
Info 2020-12-11 17:40:53: Python Daemon (pid: 35951): Kernel launched, with PID as a daemon 35953
Info 2020-12-11 17:41:00: Loading webview. View is notset
Info 2020-12-11 17:41:00: Loading web view...
Info 2020-12-11 17:41:00: Webview panel created.
Info 2020-12-11 17:41:00: Waiting for jupyter server and web panel ...
Info 2020-12-11 17:41:00: Creating raw notebook for history://191c22b0-bb58-4c51-8b4d-ff704e5858ec
Info 2020-12-11 17:41:00: Getting preferred kernel for history://191c22b0-bb58-4c51-8b4d-ff704e5858ec
Info 2020-12-11 17:41:00: Searching for kernel based on {} for /home/jarrad/src/ow/dataplatforms/ml-recommender-api-dashboard/python/sql_01_sessions.py
Info 2020-12-11 17:41:00: Find kernel spec, Class name = E, completed in 52ms, has a falsy return value, Arg 1: <Uri:/home/jarrad/src/ow/dataplatforms/ml-recommender-api-dashboard/python/sql_01_sessions.py>, Arg 2: undefined, Arg 3: undefined, Return Value: undefined
Info 2020-12-11 17:41:00: installMissingDependencies /home/jarrad/src/ow/dataplatforms/ml-recommender-api-dashboard/.venv/bin/python
Info 2020-12-11 17:41:00: > ~/src/ow/dataplatforms/ml-recommender-api-dashboard/.venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.1.413829690-dev/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/src/ow/dataplatforms/ml-recommender-api-dashboard/.venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.1.413829690-dev/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
Info 2020-12-11 17:41:00: Loading kernelspec from /home/jarrad/src/ow/dataplatforms/ml-recommender-api-dashboard/.venv/share/jupyter/kernels/python3/kernel.json for /home/jarrad/src/ow/dataplatforms/ml-recommender-api-dashboard/.venv/bin/python
Info 2020-12-11 17:41:00: Loading kernelspec from /home/jarrad/.local/share/jupyter/kernels/.net-csharp/kernel.json for undefined
Info 2020-12-11 17:41:00: Loading kernelspec from /home/jarrad/.local/share/jupyter/kernels/.net-fsharp/kernel.json for undefined
Info 2020-12-11 17:41:00: Loading kernelspec from /home/jarrad/.local/share/jupyter/kernels/.net-powershell/kernel.json for undefined
Info 2020-12-11 17:41:00: Loading kernelspec from /home/jarrad/.local/share/jupyter/kernels/julia-1.0/kernel.json for undefined
Info 2020-12-11 17:41:00: Loading kernelspec from /home/jarrad/.local/share/jupyter/kernels/julia-1.4/kernel.json for undefined
Info 2020-12-11 17:41:00: Loading kernelspec from /home/jarrad/.local/share/jupyter/kernels/lp/kernel.json for undefined
Info 2020-12-11 17:41:00: Loading kernelspec from /home/jarrad/.local/share/jupyter/kernels/ml/kernel.json for undefined
Info 2020-12-11 17:41:00: Loading kernelspec from /home/jarrad/.local/share/jupyter/kernels/python3/kernel.json for undefined
Info 2020-12-11 17:41:00: Loading kernelspec from /home/jarrad/.local/share/jupyter/kernels/python37364bitvenvvenv9f0f5eb1faa342e8a7b3661482023987/kernel.json for undefined
Info 2020-12-11 17:41:00: Loading kernelspec from /home/jarrad/.local/share/jupyter/kernels/python37564bit0f1db75fda2440d5b933aee402256b0b/kernel.json for undefined
Info 2020-12-11 17:41:00: Loading kernelspec from /home/jarrad/.local/share/jupyter/kernels/python3poetry/kernel.json for undefined
Info 2020-12-11 17:41:00: Loading kernelspec from /home/jarrad/.local/share/jupyter/kernels/scala/kernel.json for undefined
Info 2020-12-11 17:41:00: Install Missing Dependencies, Class name = f, completed in 332ms, has a falsy return value, Return Value: 0
Info 2020-12-11 17:41:00: Find kernel spec, Class name = I, completed in 395ms, has a truthy return value, Arg 1: <Uri:/home/jarrad/src/ow/dataplatforms/ml-recommender-api-dashboard/python/sql_01_sessions.py>, Arg 2: undefined, Arg 3: undefined, Arg 4: undefined, Return Value: {"kind":"startUsingPythonInterpreter","interpreter":{"architecture":3,"path":"/home/jarrad/src/ow/dataplatforms/ml-recommender-api-dashboard/.venv/bin/python","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.8.6-final","major":3,"minor":8,"patch":6,"prerelease":["final"],"build":[],"version":"3.8.6-final"},"sysVersion":"3.8.6 (default, Sep 25 2020, 09:36:53) \n[GCC 10.2.0]","sysPrefix":"/home/jarrad/src/ow/dataplatforms/ml-recommender-api-dashboard/.venv","fileHash":"fe7beaf03c57c647f649edfcfc0c6c611f2c7846c3dd7a33602d0722fbe0c8cff3253e4422d8cb5d344e3fba199eb1094204ae0a0f7203f2fdb8291128cbca64","envName":".venv","type":"Venv","displayName":"Python 3.8.6 64-bit ('.venv')"}}
Error 2020-12-11 17:41:00: Jupyter Kernel Spec not found for a local connection
Info 2020-12-11 17:41:00: Computing working directory history://191c22b0-bb58-4c51-8b4d-ff704e5858ec
Info 2020-12-11 17:41:00: Connecting to raw session for history://191c22b0-bb58-4c51-8b4d-ff704e5858ec
Info 2020-12-11 17:41:00: No custom variables for Kernel as interpreter path is not defined for kernel
Info 2020-12-11 17:41:00: Python Daemon (pid: 35951): Execute rpc method start_prewarmed_kernel in DS Daemon
Info 2020-12-11 17:41:00: Python Daemon (pid: 35951): Execute rpc method start_prewarmed_kernel from /home/jarrad/src/ow/dataplatforms/ml-recommender-api-dashboard/.venv/bin/python
Info 2020-12-11 17:41:00: Python Daemon (pid: 35951): Start pre-warmed Kernel in DS Kernel Launcher Daemon 35953 with args ['ipykernel_launcher', '--ip=127.0.0.1', '--stdin=9003', '--control=9001', '--hb=9000', '--Session.signature_scheme="hmac-sha256"', '--Session.key=b"5851d697-e395-473d-b1d3-c21772ca8ecd"', '--shell=9002', '--transport="tcp"', '--iopub=9004', '--f=/tmp/tmp-35773N0QBNF8PYKEX.json']
Info 2020-12-11 17:41:00: > ~/src/ow/dataplatforms/ml-recommender-api-dashboard/.venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.1.413829690-dev/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/src/ow/dataplatforms/ml-recommender-api-dashboard/.venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.1.413829690-dev/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
Info 2020-12-11 17:41:00: Raw session started and connected
Started kernel Python 3.8.6 64-bit ('.venv')
Info 2020-12-11 17:41:00: Initial setup for history://191c22b0-bb58-4c51-8b4d-ff704e5858ec starting ...
Info 2020-12-11 17:41:00: Initialize config for plots for history://191c22b0-bb58-4c51-8b4d-ff704e5858ec
Info 2020-12-11 17:41:00: Kernel switching to busy
Info 2020-12-11 17:41:00: Kernel switching to idle
Info 2020-12-11 17:41:00: Initial setup complete for history://191c22b0-bb58-4c51-8b4d-ff704e5858ec
Info 2020-12-11 17:41:00: Finished connecting d2350973-08f6-4da9-a99b-3d8149c720be
Info 2020-12-11 17:41:00: Registering commtarget jupyter.widget
Info 2020-12-11 17:41:00: Adding sys info for 56afb896-5c56-45e7-b4fb-0970d6387573 0
Info 2020-12-11 17:41:00: No custom variables for Kernel as interpreter path is not defined for kernel
Info 2020-12-11 17:41:00: > ~/src/ow/dataplatforms/ml-recommender-api-dashboard/.venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.1.413829690-dev/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> ~/src/ow/dataplatforms/ml-recommender-api-dashboard/.venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.1.413829690-dev/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Info 2020-12-11 17:41:00: Sys info for 56afb896-5c56-45e7-b4fb-0970d6387573 0 complete
Info 2020-12-11 17:41:01: Python Daemon (pid: 36025): Execute rpc method exec_module in DS Daemon
Info 2020-12-11 17:41:01: Python Daemon (pid: 36025): Execute rpc method exec_module from /home/jarrad/src/ow/dataplatforms/ml-recommender-api-dashboard/.venv/bin/python
Info 2020-12-11 17:41:01: Python Daemon (pid: 36025): Exec module in DS Kernel Launcher Daemon ipykernel_launcher with args ['--ip=127.0.0.1', '--stdin=9008', '--control=9006', '--hb=9005', '--Session.signature_scheme="hmac-sha256"', '--Session.key=b"258a4032-e52e-4841-813c-786d7c81d167"', '--shell=9007', '--transport="tcp"', '--iopub=9009', '--f=/tmp/tmp-35773SbPYdbNPIgTc.json']
Info 2020-12-11 17:41:01: Python Daemon (pid: 36025): Exec in DS Kernel Launcher Daemon (observable) ipykernel_launcher with args ['--ip=127.0.0.1', '--stdin=9008', '--control=9006', '--hb=9005', '--Session.signature_scheme="hmac-sha256"', '--Session.key=b"258a4032-e52e-4841-813c-786d7c81d167"', '--shell=9007', '--transport="tcp"', '--iopub=9009', '--f=/tmp/tmp-35773SbPYdbNPIgTc.json']
Info 2020-12-11 17:41:01: Python Daemon (pid: 36025): Exec in DS Kernel Launcher Daemon (observable) ['/home/jarrad/src/ow/dataplatforms/ml-recommender-api-dashboard/.venv/bin/python', '-m', 'ipykernel_launcher', '--ip=127.0.0.1', '--stdin=9008', '--control=9006', '--hb=9005', '--Session.signature_scheme="hmac-sha256"', '--Session.key=b"258a4032-e52e-4841-813c-786d7c81d167"', '--shell=9007', '--transport="tcp"', '--iopub=9009', '--f=/tmp/tmp-35773SbPYdbNPIgTc.json']
Info 2020-12-11 17:41:01: Python Daemon (pid: 36025): Exec in DS Kernel Launcher Daemon (observable)
Info 2020-12-11 17:41:01: Python Daemon (pid: 36025): Kernel launched, with PID 36028
Warn 2020-12-11 17:41:01: Python Daemon (pid: 36025): Waiting for Kernel to die 36028
Info 2020-12-11 17:41:01: > ~/src/ow/dataplatforms/ml-recommender-api-dashboard/.venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.1.413829690-dev/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> ~/src/ow/dataplatforms/ml-recommender-api-dashboard/.venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.1.413829690-dev/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Info 2020-12-11 17:41:01: Python Daemon (pid: 36035): Execute rpc method prewarm_kernel in DS Daemon
Info 2020-12-11 17:41:01: Python Daemon (pid: 36035): Execute rpc method prewarm_kernel from /home/jarrad/src/ow/dataplatforms/ml-recommender-api-dashboard/.venv/bin/python
Info 2020-12-11 17:41:01: Python Daemon (pid: 36035): Pre-Warm DS Kernel in DS Kernel Launcher Daemon
Info 2020-12-11 17:41:01: Python Daemon (pid: 36035): Exec in DS Kernel Launcher Daemon (observable) ['/home/jarrad/src/ow/dataplatforms/ml-recommender-api-dashboard/.venv/bin/python', '/home/jarrad/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.1.413829690-dev/pythonFiles/vscode_datascience_helpers/../pyvsc-run-isolated.py', '/home/jarrad/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.1.413829690-dev/pythonFiles/vscode_datascience_helpers/kernel_prewarm_starter.py']
Info 2020-12-11 17:41:01: Python Daemon (pid: 36035): Exec in DS Kernel Launcher Daemon (observable)
Info 2020-12-11 17:41:01: Python Daemon (pid: 36035): Kernel launched, with PID 36037
Warn 2020-12-11 17:41:01: Python Daemon (pid: 36035): Waiting for Kernel to die 36037
Info 2020-12-11 17:41:01: Python Daemon (pid: 36035): Kernel launched, with PID as a daemon 36037
Info 2020-12-11 17:41:01: Web view react rendered
Info 2020-12-11 17:41:01: Request for onigasm file at /home/jarrad/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.1.413829690-dev/out/client/node_modules/onigasm/lib/onigasm.wasm
Info 2020-12-11 17:41:01: Request for tmlanguage file.
Info 2020-12-11 17:41:01: Searching for token colors ...
Info 2020-12-11 17:41:01: Attempting search for colors ...
Info 2020-12-11 17:41:01: Searching for token colors ...
Info 2020-12-11 17:41:01: Attempting search for colors ...
Info 2020-12-11 17:41:01: Searching for token colors ...
Info 2020-12-11 17:41:01: Attempting search for colors ...
Info 2020-12-11 17:41:01: Searching for token colors ...
Info 2020-12-11 17:41:01: Attempting search for colors ...
Info 2020-12-11 17:41:01: Searching for token colors ...
Info 2020-12-11 17:41:01: Attempting search for colors ...
Info 2020-12-11 17:41:01: Loading colors from /usr/share/code-insiders/resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 2020-12-11 17:41:01: Searching for token colors ...
Info 2020-12-11 17:41:01: Attempting search for colors ...
Info 2020-12-11 17:41:01: Loading colors from /usr/share/code-insiders/resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 2020-12-11 17:41:01: Loading colors from /usr/share/code-insiders/resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 2020-12-11 17:41:01: Loading colors from /usr/share/code-insiders/resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 2020-12-11 17:41:01: Loading colors from /usr/share/code-insiders/resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 2020-12-11 17:41:01: Loading colors from /usr/share/code-insiders/resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 2020-12-11 17:41:01: Searching for token colors ...
Info 2020-12-11 17:41:01: Attempting search for colors ...
Info 2020-12-11 17:41:01: Searching for token colors ...
Info 2020-12-11 17:41:01: Attempting search for colors ...
Info 2020-12-11 17:41:01: Loading colors from /usr/share/code-insiders/resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 2020-12-11 17:41:01: Loading colors from /usr/share/code-insiders/resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 2020-12-11 17:41:01: Attempting search for colors ...
Info 2020-12-11 17:41:01: Attempting search for colors ...
Info 2020-12-11 17:41:01: Attempting search for colors ...
Info 2020-12-11 17:41:01: Loading base colors from /usr/share/code-insiders/resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 2020-12-11 17:41:01: Loading base colors from /usr/share/code-insiders/resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 2020-12-11 17:41:01: Loading base colors from /usr/share/code-insiders/resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 2020-12-11 17:41:01: Attempting search for colors ...
Info 2020-12-11 17:41:01: Attempting search for colors ...
Info 2020-12-11 17:41:01: Attempting search for colors ...
Info 2020-12-11 17:41:01: Attempting search for colors ...
Info 2020-12-11 17:41:01: Attempting search for colors ...
Info 2020-12-11 17:41:01: Loading base colors from /usr/share/code-insiders/resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 2020-12-11 17:41:01: Loading base colors from /usr/share/code-insiders/resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 2020-12-11 17:41:01: Loading base colors from /usr/share/code-insiders/resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 2020-12-11 17:41:01: Loading base colors from /usr/share/code-insiders/resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 2020-12-11 17:41:01: Loading base colors from /usr/share/code-insiders/resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 2020-12-11 17:41:01: Using colors to generate CSS ...
Info 2020-12-11 17:41:01: Using colors to generate CSS ...
Info 2020-12-11 17:41:01: Using colors to generate CSS ...
Info 2020-12-11 17:41:01: Using colors to generate CSS ...
Info 2020-12-11 17:41:01: Using colors to generate CSS ...
Info 2020-12-11 17:41:01: Using colors to generate CSS ...
Info 2020-12-11 17:41:01: Using colors to generate CSS ...
Info 2020-12-11 17:41:01: Using colors to generate CSS ...
Info 2020-12-11 17:41:02: Submitting code for 56afb896-5c56-45e7-b4fb-0970d6387573
Info 2020-12-11 17:41:02: Wait for sys info for 56afb896-5c56-45e7-b4fb-0970d6387573 0
Info 2020-12-11 17:41:02: Kernel switching to busy
Info 2020-12-11 17:41:02: Kernel switching to idle
Info 2020-12-11 17:41:02: Kernel switching to busy
Info 2020-12-11 17:41:02: Kernel switching to idle
Info 2020-12-11 17:41:02: Adding hash for 1 = e8d99c2e0d5b with 6 lines
Info 2020-12-11 17:41:02: Kernel switching to busy
Info 2020-12-11 17:41:02: Kernel switching to idle
Info 2020-12-11 17:41:02: Finished execution for ed813eb1-c2fd-43ae-9b68-e7d4e425b10e
Info 2020-12-11 17:41:03: Attempting to start a server because of preload conditions ...
Info 2020-12-11 17:41:03: Cached data exists getEnvironmentVariables, <No Resource>
```

**Comment by DonJayamanne** [comment]
The root cause here is the fact that the poetry interpreter cannot be found in the interpreter list. This list is provided by the python extension. 
Transferring the issue to their repo.
