### ISSUE TITLE
Unable to create new blank Jupyter notebook via Notebook icon in start page

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-jupyter#4242]
Testing [Codespace Scenario: 1791](https://github.com/microsoft/vssaas-planning/issues/1791)

## Environment data

-   VS Code version: 1.52.0-insider (Codespace)
-   Jupyter Extension version (available under the Extensions sidebar): 2020.12.1
-   Python Extension version (available under the Extensions sidebar): 2020.11.2
-   OS (Windows | Mac | Linux distro) and version: Linux Codespace
-   Python and/or Anaconda version: 3.8.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local
## Expected behaviour

1. Click Notebook icon in Start Page.
2. Open blank Notebook in editor.

## Actual behaviour

1. Click Notebook icon in Start Page.
2. Shown the following prompt:

![image](https://user-images.githubusercontent.com/6413608/102384519-b1211b00-3f81-11eb-9750-8be87247fd2b.png)

**Comment by rchiodo** [comment]
This of course requires access to the codespaces beta.

**Comment by greazer** [comment]
Happens for me without codespaces.

User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'NativeNotebookEditor'
> ~\anaconda3\python.exe c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.411183155\pythonFiles\pyvsc-run-isolated.py -c "import jupyter"
> ~\anaconda3\python.exe c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.411183155\pythonFiles\pyvsc-run-isolated.py -c "import notebook"
> ~\anaconda3\python.exe c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.411183155\pythonFiles\pyvsc-run-isolated.py jupyter kernelspec --version
Error 2021-01-05 13:19:35: DataScience Error [SyntaxError: Unexpected token c in JSON at position 0
	at JSON.parse (<anonymous>)
	at r.loadContents (c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.411183155\out\client\extension.js:9:181157)
	at r.loadFromFile (c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.411183155\out\client\extension.js:9:180741)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async S.createNew (c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.411183155\out\client\extension.js:49:672162)
	at async p.openNotebook (c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.411183155\out\client\extension.js:49:398188)
	at async E.onMessage (c:\Users\jimg\.vscode-insiders\extensions\ms-python.python-2020.11.371526539\out\client\extension.js:39:872415)]

**Comment by IanMatthewHuff** [comment]
Validated, but I see issues for the sample page. Will file bug on that.
