### ISSUE TITLE
(latex) Support some sort of error diagnostics for LaTeX that other tools support

### ISSUE THREAD

**Issue by akberg** [microsoft/vscode-jupyter#4426]
## Environment data

-   VS Code version: 1.52.1
-   Jupyter Extension version: v2020.12.414227025
-   Python Extension version: v2020.12.424452561
-   OS (Windows | Mac | Linux distro) and version: Windows 10 build 19041
-   Python and/or Anaconda version: 3.8.0
-   Type of virtual environment used: N/A
-   Jupyter server running: Local 

## Expected behaviour

Not really sure was is expected, Jupyter preview ignores the extra tab alignment and shows the expected result if the syntax had been correct, Overleaf changes it to another newline (giving four rows in the example code) and reports the error, with some hints of the cause. I would expect jupyter-to-pdf to report the error with meaningful pointers to the notebook.

Is reporting this as a bug in the VSCode extension right, or is it more related to Jupyter in general? 

## Actual behaviour

The preview looks good. Converter aborts and prints the Latex error message with pointers to line numbers in the temporary notebook.tex file. This makes the inline Latex in the notebook hard to debug, especially when the preview looks fine.

Interpretation in Jupyter:
![jupyter interpretation of error](https://user-images.githubusercontent.com/25877966/105182484-5e60f300-5b2d-11eb-8296-0f2ec2e5f03d.png)
Interpretation in Overleaf:
![overleaf interpretation of error](https://user-images.githubusercontent.com/25877966/105182570-78023a80-5b2d-11eb-9ab4-33bc0cb24c4b.png)
Error report in Overleaf:
![overleaf error report](https://user-images.githubusercontent.com/25877966/105182623-8a7c7400-5b2d-11eb-8430-bd3db6d13d40.png)

## Steps to reproduce:

This was my erronous code, this alone in a markdown block should reproduce the error. The double ampersand is my error, giving two tabs instead of the one intended. 
`$s(t) = \int_{0}^{t} v(\tau) \, d\tau = \begin{cases} v_0t && \text{hvis } t < t_1 \\ 2v_0t_1 - \frac{v_0t_1^2}{t} && \text{ellers} \end{cases}$` 

Latex compiler's error message: "<temp path>/notebook.tex:689: Extra alignment tab changed to \cr"

## Logs

<details>

<summary>Output for <code>Jupyter: Export to PDF</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
. . .
[NbConvertApp] Building PDF
[NbConvertApp] Running xelatex 3 times: ['xelatex', 'c:\\Users\\Andreas\\AppData\\Local\\Temp\\854b45ba-b869-45c8-8e4e-871d68e810d6\\notebook.tex', '-quiet']
[NbConvertApp] CRITICAL | x failed: xelatex c:\Users\Andreas\AppData\Local\Temp\854b45ba-b869-45c8-8e4e-871d68e810d6\notebook.tex -quiet
c:/Users/Andreas/AppData/Local/Temp/854b45ba-b869-45c8-8e4e-871d68e810d6/notebo

ok.tex:655: Extra alignment tab has been changed to 

c:/Users/Andreas/AppData/Local/Temp/854b45ba-b869-45c8-8e4e-871d68e810d6/notebo

ok.tex:655: Extra alignment tab has been changed to 

c:/Users/Andreas/AppData/Local/Temp/854b45ba-b869-45c8-8e4e-871d68e810d6/notebo

ok.tex:689: Extra alignment tab has been changed to 

c:/Users/Andreas/AppData/Local/Temp/854b45ba-b869-45c8-8e4e-871d68e810d6/notebo

ok.tex:689: Extra alignment tab has been changed to 
Traceback (most recent call last):
  File "c:\users\andreas\appdata\local\programs\python\python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\andreas\appdata\local\programs\python\python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Andreas\AppData\Local\Programs\Python\Python38\Scripts\jupyter-nbconvert.EXE\__main__.py", line 7, in <module>
  File "c:\users\andreas\appdata\local\programs\python\python38\lib\site-packages\jupyter_core\application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "c:\users\andreas\appdata\local\programs\python\python38\lib\site-packages\traitlets\config\application.py", line 845, in launch_instance
    app.start()
  File "c:\users\andreas\appdata\local\programs\python\python38\lib\site-packages\nbconvert\nbconvertapp.py", line 350, in start
    self.convert_notebooks()
  File "c:\users\andreas\appdata\local\programs\python\python38\lib\site-packages\nbconvert\nbconvertapp.py", line 524, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "c:\users\andreas\appdata\local\programs\python\python38\lib\site-packages\nbconvert\nbconvertapp.py", line 489, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "c:\users\andreas\appdata\local\programs\python\python38\lib\site-packages\nbconvert\nbconvertapp.py", line 418, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "c:\users\andreas\appdata\local\programs\python\python38\lib\site-packages\nbconvert\exporters\exporter.py", line 181, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "c:\users\andreas\appdata\local\programs\python\python38\lib\site-packages\nbconvert\exporters\exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "c:\users\andreas\appdata\local\programs\python\python38\lib\site-packages\nbconvert\exporters\pdf.py", line 184, in from_notebook_node
    self.run_latex(tex_file)
  File "c:\users\andreas\appdata\local\programs\python\python38\lib\site-packages\nbconvert\exporters\pdf.py", line 154, in run_latex
    return self.run_command(self.latex_command, filename,
  File "c:\users\andreas\appdata\local\programs\python\python38\lib\site-packages\nbconvert\exporters\pdf.py", line 142, in run_command
    raise raise_on_failure(
nbconvert.exporters.pdf.LatexFailed: PDF creating failed, captured latex output:
Failed to run "xelatex c:\Users\Andreas\AppData\Local\Temp\854b45ba-b869-45c8-8e4e-871d68e810d6\notebook.tex -quiet" command:
c:/Users/Andreas/AppData/Local/Temp/854b45ba-b869-45c8-8e4e-871d68e810d6/notebo

ok.tex:655: Extra alignment tab has been changed to 

c:/Users/Andreas/AppData/Local/Temp/854b45ba-b869-45c8-8e4e-871d68e810d6/notebo

ok.tex:655: Extra alignment tab has been changed to 

c:/Users/Andreas/AppData/Local/Temp/854b45ba-b869-45c8-8e4e-871d68e810d6/notebo

ok.tex:689: Extra alignment tab has been changed to 

c:/Users/Andreas/AppData/Local/Temp/854b45ba-b869-45c8-8e4e-871d68e810d6/notebo

ok.tex:689: Extra alignment tab has been changed to 

	at a.executeCommand (c:\Users\Andreas\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:1:448888)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async a.export (c:\Users\Andreas\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:254436)
	at async _.exportToFormat (c:\Users\Andreas\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:252696)
	at async _.performExport (c:\Users\Andreas\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:251809)
	at async _.export (c:\Users\Andreas\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:251323)
	at async m.export (c:\Users\Andreas\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:32:265964)]
Error 2021-01-20 13:47:46: If you have not installed xelatex (TeX) you will need to do so before you can export to PDF, for further instructions go to https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex. 
To avoid installing xelatex (TeX) you might want to try exporting to HTML and using your browsers "Print to PDF" feature.
```

</p>
</details>

**Comment by rchiodo** [comment]
Thanks for the bug. I'm sorry but I don't understand what you mean by Jupyter preview? The jupyter extension does not have a preview for markdown cells. Are you referring to previewing a markdown file?

If that's the case you're asking for markdown errors to show up in jupyter notebooks as errors then?

**Comment by akberg** [comment]
I'm using some wrong terms, I guess, sorry! What I'm referring to is the rendering of markdown cells when they are not in focus:
![in focus](https://user-images.githubusercontent.com/25877966/105285400-9f501a80-5bb4-11eb-9955-cb6107a4a175.png)
![out of focus](https://user-images.githubusercontent.com/25877966/105285425-aa0aaf80-5bb4-11eb-90d5-7c057e91be46.png)
in which e.g. unknown commands are handled like this:
![unkknown command](https://user-images.githubusercontent.com/25877966/105285768-5b114a00-5bb5-11eb-9b9b-48a648038fe6.png)
and other syntax errors like missing \end are handled like this (slightly less elegant, harder to debug):
![missing \end{cases}](https://user-images.githubusercontent.com/25877966/105286665-0ec70980-5bb7-11eb-81c9-00254a13251c.png)
This markdown rendering is done by jupyter, right?

But yes, I guess what I'm asking for is of latex errors (or any other) that will prevent the notebook from compiling on export, to show up as errors in jupyter notebook. Or at least that the different methods of rendering and exporting handle errors and anomalies the same way. Right now, export to HTML works fine, as it handles this error the same way as the rendering in the notebook.

Looking back at when I was using jupyter hub, I'm guessing this same thing is what prevented me from exporting to PDF there (even less forgiving, as I wouldn't have a temporary tex-file to analyse locally).

**Comment by rchiodo** [comment]
Ah okay thanks. That makes more sense now. You're asking for a way to diagnose errors in your LaTex.

Actually jupyter does not do the rendering of LaTeX/Markdown for us. This is all done client side using a 3rd party library:
https://components.nteract.io/#latex

**Comment by greazer** [comment]
Thanks for the feedback! However, we don't have plans on adding this functionality at this time.
