### ISSUE TITLE
s.authentication.getPassword is not a function (similar to #4316)

### ISSUE THREAD

**Issue by otaj** [microsoft/vscode-jupyter#4451]
Was trying out new Jupyter native notebook in Insiders, but this started popping up. At first, I thought the issue is with the running of the cells, however, this error starts to show even when selecting Jupyter server

## Environment data

-   VS Code version: Insiders, build 1611306611
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025 - daily insiders channel
-   Python Extension version (available under the Extensions sidebar): v2021.1.502429796 - daily Insiders channel
-   OS (Windows | Mac | Linux distro) and version: Arch Linux - not really playing with "versions" there :D Though official build of insiders
-   Python and/or Anaconda version: Python 3.7 in conda environment, conda is 4.9.2, conda on remote is 4.8.3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Conda (on both sides, local and remote)
-   Jupyter server running: Remote (with a token, behind a VPN, HTTP)

## Expected behaviour

I wanted to try out the new look of the Jupyter native editor, because the "old" one feels too.. "clunky", however, I cannot even select an interpreter to be used for Jupyter. So expected behaviour is to be able to connect to Remote Jupyter (or even local one)

## Actual behaviour

Command 'Jupyter: Specify local or remote Jupyter server for connections' resulted in an error (Running the contributed command: 'jupyter.selectjupyteruri' failed.)

## Steps to reproduce:

Freshly installed VSCode Insiders (as of today, Jan 22, 2021) with Python, Jupyter, Pylance, etc with daily insiders channels
Get a notebook and try to connect to URI

## Logs

Logs for Jupyter extension don't show anything of interest in case of running the action, however the logs for ExtHost do

<details>

<summary>Output for <code>ExtHost</code> in the <code>Output</code> panel 
</summary>

<p>

```
[2021-01-22 10:55:13.454] [exthost] [error] TypeError: s.authentication.getPassword is not a function
	at l.getPassword (/home/otaj/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:518189)
	at l.retrieve (/home/otaj/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:525923)
	at u.getUriInternal (/home/otaj/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:49:579717)
	at u.getUri (/home/otaj/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:49:578864)
	at new u (/home/otaj/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:49:577279)
	at Object.t.resolveInstance (/home/otaj/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:255923)
	at /home/otaj/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:255125
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/home/otaj/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:255693)
	at /home/otaj/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:255125
	at /home/otaj/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:254069
	at Array.map (<anonymous>)
	at /home/otaj/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:254041
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/home/otaj/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:255693)
	at /home/otaj/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:255125
	at Object.t.resolve (/home/otaj/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:255392)
	at /home/otaj/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:246476
	at e._get (/home/otaj/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:246242)
	at e.get (/home/otaj/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:244953)
	at a.get (/home/otaj/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:49:854904)
	at /home/otaj/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:238618
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async /home/otaj/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:703465
	at async t.activate (/home/otaj/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:703175)
	at async Promise.all (index 0) jupyter.selectjupyteruri
```

</p>
</details>

**Comment by firegate22** [comment]
I guess there was just now new version... which is also my question... is there any way to get an updated "insiders" build (without "creating" / "building it" myself) where the actual fix is in? Daily/weekly insiders seems to be not active for this extension right now.

Or any way to get an older version - which one would the recommendation?

Thanks!

**Comment by rchiodo** [comment]
You can retrieve our latest from the last build that ran if you like.

Example:
https://github.com/microsoft/vscode-jupyter/actions/runs/504728737 and then find the vsix generated in the list of artifacts.

We're currently reworking how we release insiders bits but hope to have a way to use them soon.

**Comment by otaj** [comment]
Hi, @rchiodo , thank you, when I downloaded the generated vsix, it worked. Is there an ETA on when insiders bits will be actually available to auto update through VSCode?

And maybe one more, slightly unrelated question - is there an ETA on using this native notebook in non-insiders builds of VSCode and extension, i.e. the "standard" one? Thanks

**Comment by firegate22** [comment]
Many thanks - didn't know that and it helped me a lot!

**Comment by rchiodo** [comment]
> Is there an ETA on when insiders bits will be actually available to auto update through VSCode?

Sorry no ETA for this. I'll add an issue to our backlog to address this though as at least one customer (you) is asking for it.

Native notebook in non insiders is coming soon. Next month or two for a small subset of users (we'll likely have a flag to force it on).

**Comment by ShubhamVerma1811** [comment]
Hey, facing the same issue. I am new to python looked at above replies but couldn't understand.
All I wrote was print(2+2) in the cell and tried to run it.

**Comment by rchiodo** [comment]
@ShubhamVerma1811 the error is a result of a changed API in vscode insiders. You shouldn't be using a remote server URI with insiders anyway but if you do it will cause the error above. Our newest build will have the changes to both accommodate this API change and support remote for VS code insiders. You can install a preview of this build using the link above.

**Comment by ShubhamVerma1811** [comment]
Got it!
Not sure how to download the preview. I'll just wait for the official update.
Thanks
