### ISSUE TITLE
ReferenceError: Jupyter is not defined

### ISSUE THREAD

**Issue by mwh3780** [microsoft/vscode-jupyter#4539]
## Environment data

-   VS Code version: 
  Version: 1.52.1
  Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
  Date: 2020-12-16T16:30:02.420Z (1 mo ago)
  Electron: 9.3.5
  Chrome: 83.0.4103.122
  Node.js: 12.14.1
  V8: 8.3.110.13-electron.0
  OS: Darwin x64 20.2.0
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): v2021.1.502429796
-   OS (Windows | Mac | Linux distro) and version: macOS Big Sur 11.1 (20C69)
-   Python and/or Anaconda version: Conda 4.9.2, Python 3.6.12
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Conda
-   Jupyter server running: Local

## Expected behaviour

No errors

## Actual behaviour

Obtain the following error:
```
ReferenceError: Jupyter is not defined
    at eval (eval at runCodeHere (vscode-webview-resource://5f11081e-cf9c-4b8c-9372-abe6c817f287/file///Users/mwh3780/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/out/datascience-ui/notebook/vendors~nteract_transforms.bundle.js:2:12595), <anonymous>:1:1)
    at runCodeHere (vscode-webview-resource://5f11081e-cf9c-4b8c-9372-abe6c817f287/file///Users/mwh3780/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/out/datascience-ui/notebook/vendors~nteract_transforms.bundle.js:2:12595)
    at t.value (vscode-webview-resource://5f11081e-cf9c-4b8c-9372-abe6c817f287/file///Users/mwh3780/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/out/datascience-ui/notebook/vendors~nteract_transforms.bundle.js:2:13027)
    at La (vscode-webview-resource://5f11081e-cf9c-4b8c-9372-abe6c817f287/file///Users/mwh3780/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/out/datascience-ui/notebook/commons.initial.bundle.js:2:2403852)
    at Pa (vscode-webview-resource://5f11081e-cf9c-4b8c-9372-abe6c817f287/file///Users/mwh3780/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/out/datascience-ui/notebook/commons.initial.bundle.js:2:2406774)
    at vscode-webview-resource://5f11081e-cf9c-4b8c-9372-abe6c817f287/file///Users/mwh3780/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/out/datascience-ui/notebook/commons.initial.bundle.js:2:2419852
    at Object.t.unstable_runWithPriority (vscode-webview-resource://5f11081e-cf9c-4b8c-9372-abe6c817f287/file///Users/mwh3780/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/out/datascience-ui/notebook/commons.initial.bundle.js:2:25134)
    at Ms (vscode-webview-resource://5f11081e-cf9c-4b8c-9372-abe6c817f287/file///Users/mwh3780/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/out/datascience-ui/notebook/commons.initial.bundle.js:2:2419786)
    at xs (vscode-webview-resource://5f11081e-cf9c-4b8c-9372-abe6c817f287/file///Users/mwh3780/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/out/datascience-ui/notebook/commons.initial.bundle.js:2:2419562)
    at Es (vscode-webview-resource://5f11081e-cf9c-4b8c-9372-abe6c817f287/file///Users/mwh3780/.vscode/extensions/ms-toolsai.jupyter-2020.12.414227025/out/datascience-ui/notebook/commons.initial.bundle.js:2:2418907)
```

## Steps to reproduce:

Run following code in VS Code in a notebook
```
from IPython.core.magics.display import Javascript
Javascript('Jupyter.notebook.writable = true')
```

## Details

I recently inherited some code from a departed colleague and have been running into issues when trying to run some of his notebooks in VS Code. What’s odd is that the code runs fine when I use Chrome, yet doesn’t work in VS Code when I run the code as a notebook, but runs fine when running the code in a regular Python session in VS Code. This is a simple example of the errors I’m encountering as I’m encountering many more like this with different code, yet they are all throwing the same root error of `ReferenceError: Jupyter is not defined` While the error is referencing the Jupyter VS Code extension, I don’t know if that’s where the issue truly lies or is simply a symptom of the real problem.

## Logs

I didn't know what parts of you log you wanted so I zipped the directory of a session just running the code
[20210128T103600.zip](https://github.com/microsoft/vscode-jupyter/files/5889038/20210128T103600.zip)

Python session in VS Code
![python session vs code](https://user-images.githubusercontent.com/23129139/106176715-e611b780-6154-11eb-8206-7a1dee8bd050.png)

Notebook in Chrome
![notebook in chrome](https://user-images.githubusercontent.com/23129139/106176730-ead66b80-6154-11eb-9dee-26d4a05ad589.png)

Notebook in VS Code
![notebook in vs code](https://user-images.githubusercontent.com/23129139/106176738-ee69f280-6154-11eb-91d1-99a1c3767951.png)

**Comment by rchiodo** [comment]
Sorry but that code won't work in VS code. It's referencing 'Jupyter' in a javascript context. We do not have a jupyter global object in the HTML that we create to display notebook outputs.

**Comment by mwh3780** [comment]
Sorry I'm still a bit new to running notebooks in VS Code. So any call to Javascript as defined here that references "Jupyter" won't work regardless of what it's trying to accomplish?

**Comment by rchiodo** [comment]
Yes unless we somehow duplicate the internal structure of the Jupyter client javascript. Which is theoretically possible but not something a lot of people ask for.
