### ISSUE TITLE
plotly graphs do not display in an interact function

### ISSUE THREAD

**Issue by AWhetter** [microsoft/vscode-jupyter#4578]
## Environment data

-   VS Code version: 1.52.1
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: v2021.1.502429796
-   Python and/or Anaconda version: 3.9.1
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local

## Expected behaviour

From vscode's Python Interactive Window I expect to see the range slider followed by the graph rendered by plotly. As I change the values on the slider, the graph should update to the new values. This is what I see if I view the notebook in native jupyter in a browser.

## Actual behaviour

On running the cell, only the range slider shows. I can interact with the slider, but the graph still does not show.
If I comment out the call to `interact()` and uncomment the call to `update_graph()` and run the cell, the graph displays correctly.

## Steps to reproduce:

To create the venv I have done:

```bash
python -m venv venv
venv/bin/pip install jupyter pandas plotly
```

In a notebook cell I have the following:

```python
import ipywidgets as widgets
from ipywidgets import interact
import pandas as pd
pd.options.plotting.backend = "plotly"

def update_graph(rng):
    df = pd.DataFrame({"x": list(range(*rng)), "y": list(range(*rng))})
    fig = df.plot.scatter(x="x", y="y")
    fig.show()

interact(update_graph, rng=widgets.IntRangeSlider(value=(0, 10), min=0, max=20))
#update_graph([0, 10])
```

Note that although the logs complain about ipykernel not being installed, it is but I think it hasn't entered the venv by this point. I can run the kernel after everything has finished loading up.

## Logs

```
> /usr/bin/python ~/.vscode-oss/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/bin/python ~/.vscode-oss/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/bin/python ~/.vscode-oss/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> /usr/bin/python ~/.vscode-oss/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> /usr/bin/python ~/.vscode-oss/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> /usr/bin/python ~/.vscode-oss/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> /usr/bin/python ~/.vscode-oss/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/bin/python ~/.vscode-oss/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
Error 2021-01-30 11:03:23: Find kernel spec, Class name = I, completed in 15159ms, has a falsy return value, Arg 1: <Uri:/home/ashley/workspace/temp/jupyter_bug/Untitled.ipynb>, Arg 2: {"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.1-final"}}, Arg 3: undefined, Arg 4: undefined, Return Value: undefined [Error: IPyKernel not installed into interpreter Python 3.9.1 64-bit:/usr/bin/python
	at I.installDependenciesIntoInterpreter (/home/ashley/.vscode-oss/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:1:209187)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async I.getKernelForLocalRawConnection (/home/ashley/.vscode-oss/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:1:208204)]
Error 2021-01-30 11:03:23: Failed to determine if a notebook is active for the current editor [Error: IPyKernel not installed into interpreter Python 3.9.1 64-bit:/usr/bin/python
	at I.installDependenciesIntoInterpreter (/home/ashley/.vscode-oss/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:1:209187)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async I.getKernelForLocalRawConnection (/home/ashley/.vscode-oss/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:1:208204)]
Error 2021-01-30 11:03:23: Failed to determine if a notebook is active for the current editor [Error: IPyKernel not installed into interpreter Python 3.9.1 64-bit:/usr/bin/python
	at I.installDependenciesIntoInterpreter (/home/ashley/.vscode-oss/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:1:209187)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async I.getKernelForLocalRawConnection (/home/ashley/.vscode-oss/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:1:208204)]
Error 2021-01-30 11:03:23: DataScience Error [Error: IPyKernel not installed into interpreter Python 3.9.1 64-bit:/usr/bin/python
	at I.installDependenciesIntoInterpreter (/home/ashley/.vscode-oss/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:1:209187)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async I.getKernelForLocalRawConnection (/home/ashley/.vscode-oss/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:1:208204)]
> ~/workspace/temp/jupyter_bug/venv/bin/python3.9 ~/.vscode-oss/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/workspace/temp/jupyter_bug/venv/bin/python3.9 ~/.vscode-oss/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Started kernel Python 3
> ~/workspace/temp/jupyter_bug/venv/bin/python3.9 ~/.vscode-oss/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
```

**Comment by joyceerhl** [comment]
Thanks @AWhetter I was able to reproduce this behavior. I do also see it in our webview-based notebook editor. In our new native notebooks editor we display the graph but not the slider. I didn't see anything suspicious in the logs. Our team will discuss this at our weekly triage.

**Comment by DonJayamanne** [comment]
should be fixed with https://github.com/microsoft/vscode-jupyter/pull/10327
