### ISSUE TITLE
Unable to export to PDF

### ISSUE THREAD

**Issue by Midnitte** [microsoft/vscode-jupyter#4602]
Issue Type: <b>Bug</b>

Open notebook (.ipynb)
Click export > PDF

Output log:
```> E:\ProgramData\Anaconda3\python.exe c:\Users\Ryzen\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import nbconvert"
> E:\ProgramData\Anaconda3\python.exe c:\Users\Ryzen\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py jupyter nbconvert c:\Users\Ryzen\AppData\Local\Temp\55ba6c03-e681-4dc1-a5f0-afb4bf8bb84f\linear-algebra-reintro.ipynb --to pdf --output tmp-25876rw4KHgTB2mcr.pdf --output-dir ~\AppData\Local\Temp --debug
Error 2021-02-02 09:45:29: Export failed [Error: [NbConvertApp] Searching ['C:\\Program Files\\Microsoft VS Code', 'C:\\Users\\Ryzen\\.jupyter', 'E:\\ProgramData\\Anaconda3\\etc\\jupyter', 'C:\\ProgramData\\jupyter'] for config files
[NbConvertApp] Looking for jupyter_config in C:\ProgramData\jupyter
[NbConvertApp] Looking for jupyter_config in E:\ProgramData\Anaconda3\etc\jupyter
[NbConvertApp] Looking for jupyter_config in C:\Users\Ryzen\.jupyter
[NbConvertApp] Looking for jupyter_config in C:\Program Files\Microsoft VS Code
[NbConvertApp] Looking for jupyter_nbconvert_config in C:\ProgramData\jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in E:\ProgramData\Anaconda3\etc\jupyter
[NbConvertApp] Loaded config file: E:\ProgramData\Anaconda3\etc\jupyter\jupyter_nbconvert_config.json
[NbConvertApp] Looking for jupyter_nbconvert_config in C:\Users\Ryzen\.jupyter
[NbConvertApp] Loaded config file: C:\Users\Ryzen\.jupyter\jupyter_nbconvert_config.json
[NbConvertApp] Looking for jupyter_nbconvert_config in C:\Program Files\Microsoft VS Code
[NbConvertApp] Converting notebook c:\Users\Ryzen\AppData\Local\Temp\55ba6c03-e681-4dc1-a5f0-afb4bf8bb84f\linear-algebra-reintro.ipynb to pdf
[NbConvertApp] Notebook name is 'tmp-25876rw4KHgTB2mcr'
Traceback (most recent call last):
  File "E:\ProgramData\Anaconda3\Scripts\jupyter-nbconvert-script.py", line 10, in <module>
    sys.exit(main())
  File "E:\ProgramData\Anaconda3\lib\site-packages\jupyter_core\application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "E:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 845, in launch_instance
    app.start()
  File "E:\ProgramData\Anaconda3\lib\site-packages\nbconvert\nbconvertapp.py", line 350, in start
    self.convert_notebooks()
  File "E:\ProgramData\Anaconda3\lib\site-packages\nbconvert\nbconvertapp.py", line 524, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "E:\ProgramData\Anaconda3\lib\site-packages\nbconvert\nbconvertapp.py", line 489, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "E:\ProgramData\Anaconda3\lib\site-packages\nbconvert\nbconvertapp.py", line 418, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "E:\ProgramData\Anaconda3\lib\site-packages\nbconvert\exporters\exporter.py", line 181, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "E:\ProgramData\Anaconda3\lib\site-packages\nbconvert\exporters\exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "E:\ProgramData\Anaconda3\lib\site-packages\nbconvert\exporters\pdf.py", line 183, in from_notebook_node
    self.run_latex(tex_file)
  File "E:\ProgramData\Anaconda3\lib\site-packages\nbconvert\exporters\pdf.py", line 154, in run_latex
    self.latex_count, log_error, raise_on_failure)
  File "E:\ProgramData\Anaconda3\lib\site-packages\nbconvert\exporters\pdf.py", line 143, in run_command
    command=command, output=out))
nbconvert.exporters.pdf.LatexFailed: PDF creating failed, captured latex output:
Failed to run "xelatex notebook.tex -quiet" command:
C:\Users\Ryzen\AppData\Local\Programs\MiKTeX\tex/latex\tcolorbox\tcolorbox.sty:

1241: Undefined control sequence

C:\Users\Ryzen\AppData\Local\Programs\MiKTeX\tex/latex\tcolorbox\tcolorbox.sty:

1263: Undefined control sequence

Sorry, but xelatex did not succeed.



The log file hopefully contains the information to get MiKTeX going again:



  C:\Users\Ryzen\AppData\Local\MiKTeX\2.9\miktex\log\xelatex.log



	at a.executeCommand (c:\Users\Ryzen\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:1:448888)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async a.export (c:\Users\Ryzen\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:254436)
	at async _.exportToFormat (c:\Users\Ryzen\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:252696)
	at async _.performExport (c:\Users\Ryzen\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:251809)
	at async _.export (c:\Users\Ryzen\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:251323)
	at async m.export (c:\Users\Ryzen\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:32:265964)]
Error 2021-02-02 09:45:29: If you have not installed xelatex (TeX) you will need to do so before you can export to PDF, for further instructions go to https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex. 
To avoid installing xelatex (TeX) you might want to try exporting to HTML and using your browsers "Print to PDF" feature.```

Extension version: 2020.12.414227025
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700X Eight-Core Processor          (16 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (6.87GB free)|
|Process Argv|--crash-reporter-id 6053b33b-402f-4858-82c7-3cbe9d963fef|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383:30185418
pythonvspyt617cf:30244267
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
wsl2promptcf:30224613
vstry244:30250195
pythonvsdeb440:30248342
unusedprompt:30224610
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

<!-- generated by issue reporter -->

Output of sys.version and jupyter version
3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]
jupyter core     : 4.6.3
jupyter-notebook : 6.1.4
qtconsole        : 4.7.7
ipython          : 7.19.0
ipykernel        : 5.3.4
jupyter client   : 6.1.7
jupyter lab      : 2.2.6
nbconvert        : 6.0.7
ipywidgets       : 7.5.1
nbformat         : 5.0.8
traitlets        : 5.0.5

**Comment by IanMatthewHuff** [comment]
@Midnitte exporting to PDF can be a bit dicy as you need to have specific requirements installed on your machine for it to work. 

The error here looks like TeX might not be set up right on your system:

> Error 2021-02-02 09:45:29: If you have not installed xelatex (TeX) you will need to do so before you can export to PDF, for further instructions go to https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex. 

Have you set TeX up on this system?

This command here is the basic command that we are running:

> > E:\ProgramData\Anaconda3\python.exe c:\Users\Ryzen\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py jupyter nbconvert c:\Users\Ryzen\AppData\Local\Temp\55ba6c03-e681-4dc1-a5f0-afb4bf8bb84f\linear-algebra-reintro.ipynb --to pdf --output tmp-25876rw4KHgTB2mcr.pdf --output-dir ~\AppData\Local\Temp --debug

If you activate your Conda environment from the Anaconda prompt in a command prompt you can try running something like this:

>  python jupyter nbconvert c:\Users\Ryzen\AppData\Local\Temp\55ba6c03-e681-4dc1-a5f0-afb4bf8bb84f\linear-algebra-reintro.ipynb --to pdf --output tmp-25876rw4KHgTB2mcr.pdf --output-dir ~\AppData\Local\Temp --debug

You might have to tweak the paths a little bit. If that command is still erroring outside of VS Code then the configuration for PDF import won't work inside VS Code as well.
