### ISSUE TITLE
Test 'Switch kernels' randomly fails

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4626]
Looks like installing ipykernel into conda environment has failed (possible this is due to the upstream bug that was fixed recently in Python Extension - install ipykernel into conda when current interpreter is not conda)

* [ ] Download Python extension from blob store (instead of marketplace)
* [ ] We might want to add an integration tests case for this case (even though the fix was upstream).
	Switch to a conda kernel when active interpreter is non-conda
* [ ] Run smoke tests with Stable Python extension & rest of tests with Insiders Python Extension

<details>
<summary>Logs</summary>

2021-02-03T16:00:35.4588875Z 4426 Info 2021-02-03 16:00:34: Start Test Completed Switch kernels
2021-02-03T16:00:35.4589312Z 
2021-02-03T16:00:35.4591490Z Info Python Extension: 2021-02-03 16:00:34: Cached data exists getEnvironmentVariables, /home/runner/work/vscode-jupyter/vscode-jupyter/tmp/emptyPython44267g1MqX34bPR0.ipynb
2021-02-03T16:00:35.4592776Z 
2021-02-03T16:00:35.4594999Z 4426 Info 2021-02-03 16:00:34: Execute Cell 0 vscode-notebook-cell:/home/runner/work/vscode-jupyter/vscode-jupyter/tmp/emptyPython44267g1MqX34bPR0.ipynb#ch0000000 in kernelWithMetadata.ts
2021-02-03T16:00:35.4596207Z 
2021-02-03T16:00:35.4597671Z 4426 Info 2021-02-03 16:00:34: Cell Index:0, state:undefined, exec: undefined. User queued cell for execution
2021-02-03T16:00:35.4598263Z 
2021-02-03T16:00:35.4599522Z 4426 Info 2021-02-03 16:00:34: Cell Index:0, state:undefined, exec: undefined. Update cell state as it was enqueued
2021-02-03T16:00:35.4600123Z 
2021-02-03T16:00:35.4602124Z Info Python Extension: 2021-02-03 16:00:34: Cached data exists getEnvironmentVariables, /home/runner/work/vscode-jupyter/vscode-jupyter/tmp/emptyPython44267g1MqX34bPR0.ipynb
2021-02-03T16:00:35.4603271Z 
2021-02-03T16:00:35.4605866Z g [Error]: Unable to read file '/home/runner/work/vscode-jupyter/vscode-jupyter/out/ipywidgets/dist/ipywidgets.js' (Error: Unable to resolve non-existing file '/home/runner/work/vscode-jupyter/vscode-jupyter/out/ipywidgets/dist/ipywidgets.js')
2021-02-03T16:00:35.4608760Z     at l.doReadAsFileStream (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:28:20133)
2021-02-03T16:00:35.4611382Z     at async Object.readFileStream (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:47:30180)
2021-02-03T16:00:35.4613976Z     at async Object.i [as loadLocalResource] (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:47:22514)
2021-02-03T16:00:35.4616757Z     at async Ft.handleWebviewResourceRequest (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:47:30660) {
2021-02-03T16:00:35.4618313Z   fileOperationResult: 1,
2021-02-03T16:00:35.4618887Z   options: undefined
2021-02-03T16:00:35.4619317Z }
2021-02-03T16:00:35.4619564Z 
2021-02-03T16:00:35.4622476Z g [Error]: Unable to read file '/home/runner/work/vscode-jupyter/vscode-jupyter/out/datascience-ui/ipywidgetsKernel/ipywidgetsKernel.js' (Error: Unable to resolve non-existing file '/home/runner/work/vscode-jupyter/vscode-jupyter/out/datascience-ui/ipywidgetsKernel/ipywidgetsKernel.js')
2021-02-03T16:00:35.4625584Z     at l.doReadAsFileStream (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:28:20133)
2021-02-03T16:00:35.4628130Z     at async Object.readFileStream (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:47:30180)
2021-02-03T16:00:35.4630708Z     at async Object.i [as loadLocalResource] (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:47:22514)
2021-02-03T16:00:35.4633453Z     at async Ft.handleWebviewResourceRequest (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:47:30660) {
2021-02-03T16:00:35.4634993Z   fileOperationResult: 1,
2021-02-03T16:00:35.4635580Z   options: undefined
2021-02-03T16:00:35.4636005Z }
2021-02-03T16:00:35.4636252Z 
2021-02-03T16:00:35.4638969Z g [Error]: Unable to read file '/home/runner/work/vscode-jupyter/vscode-jupyter/out/datascience-ui/notebook/fontAwesomeLoader.js' (Error: Unable to resolve non-existing file '/home/runner/work/vscode-jupyter/vscode-jupyter/out/datascience-ui/notebook/fontAwesomeLoader.js')
2021-02-03T16:00:35.4641963Z     at l.doReadAsFileStream (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:28:20133)
2021-02-03T16:00:35.4644403Z     at async Object.readFileStream (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:47:30180)
2021-02-03T16:00:35.4647219Z     at async Object.i [as loadLocalResource] (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:47:22514)
2021-02-03T16:00:35.4650107Z     at async Ft.handleWebviewResourceRequest (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:47:30660) {
2021-02-03T16:00:35.4651652Z   fileOperationResult: 1,
2021-02-03T16:00:35.4652238Z   options: undefined
2021-02-03T16:00:35.4653158Z }
2021-02-03T16:00:35.4653417Z 
2021-02-03T16:00:35.4655105Z rejected promise not handled within 1 second: Error: Kernel Python 3.8.5 64-bit ('base': conda) is not usable. Check the Jupyter output tab for more information.
2021-02-03T16:00:35.4656989Z stack trace: Error: Kernel Python 3.8.5 64-bit ('base': conda) is not usable. Check the Jupyter output tab for more information.
2021-02-03T16:00:35.4769199Z     at JupyterSession.createNewKernelSession (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/jupyterSession.js:3306:15)
2021-02-03T16:00:35.4780616Z     at runMicrotasks (<anonymous>)
2021-02-03T16:00:35.4781573Z     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-02-03T16:00:35.4783504Z     at JupyterSession.connect (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/jupyterSession.js:3256:22)
2021-02-03T16:00:35.4785846Z     at JupyterSessionManager.startNew (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/jupyterSessionManager.js:3922:7)
2021-02-03T16:00:35.4788185Z     at getExistingSession (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/liveshare/hostJupyterServer.js:4068:290)
2021-02-03T16:00:35.4790747Z     at HostJupyterServer.createNotebookInstance (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/liveshare/hostJupyterServer.js:4084:38)
2021-02-03T16:00:35.4793840Z Kernel Python 3.8.5 64-bit ('base': conda) is not usable. Check the Jupyter output tab for more information.: Error: Kernel Python 3.8.5 64-bit ('base': conda) is not usable. Check the Jupyter output tab for more information.
2021-02-03T16:00:35.4796283Z     at JupyterSession.createNewKernelSession (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/jupyterSession.js:3306:15)
2021-02-03T16:00:35.4797726Z     at runMicrotasks (<anonymous>)
2021-02-03T16:00:35.4798627Z     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-02-03T16:00:35.4800411Z     at JupyterSession.connect (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/jupyterSession.js:3256:22)
2021-02-03T16:00:35.4802710Z     at JupyterSessionManager.startNew (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/jupyterSessionManager.js:3922:7)
2021-02-03T16:00:35.4805032Z     at getExistingSession (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/liveshare/hostJupyterServer.js:4068:290)
2021-02-03T16:00:35.4807816Z     at HostJupyterServer.createNotebookInstance (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/liveshare/hostJupyterServer.js:4084:38)
2021-02-03T16:00:35.4897625Z 
2021-02-03T16:00:35.4899371Z 4426 Info 2021-02-03 16:00:35: Python Daemon (pid: 4653): write to stderr: [I 16:00:35.181 NotebookApp] Creating new notebook in /
2021-02-03T16:00:35.4899977Z 
2021-02-03T16:00:35.4900219Z 
2021-02-03T16:00:35.4901528Z 4426 Info 2021-02-03 16:00:35: installMissingDependencies /usr/share/miniconda/bin/python
2021-02-03T16:00:35.4902177Z 
2021-02-03T16:00:35.4910480Z Info Python Extension: 2021-02-03 16:00:35: getActivatedEnvironmentVariables, Class name = P, completed in 1ms, has a truthy return value, Arg 1: undefined, Arg 2: {"architecture":3,"path":"/usr/share/miniconda/bin/python","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.8.5-final","major":3,"minor":8,"patch":5,"prerelease":["final"],"build":[],"version":"3.8.5-final"},"sysVersion":"3.8.5 (default, Sep  4 2020, 07:30:14) \n[GCC 7.3.0]","sysPrefix":"/usr/share/miniconda","fileHash":"afc1735bbf9bdf2030f72c76a7c393fdc81bd946f48b7ea5d6cff2cafb6cdd76eef6e3b88eb67af808849f5e48165957a76a788cbd2ad22d57603c65119006b3","companyDisplayName":"Anaconda, Inc.","envType":"Conda","envPath":"/usr/share/miniconda","envName":"base","displayName":"Python 3.8.5 64-bit ('base': conda)"}, Arg 3: true
2021-02-03T16:00:35.4915918Z 
2021-02-03T16:00:35.4917841Z 4426 Info 2021-02-03 16:00:35: Process Execution: > /usr/share/miniconda/bin/python ~/work/vscode-jupyter/vscode-jupyter/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
2021-02-03T16:00:35.4918807Z 
2021-02-03T16:00:35.4920609Z 4426 Info 2021-02-03 16:00:35: Message displayed to user 'Python 3.8.5 64-bit ('base': conda) requires ipykernel to be installed.', condition {"endsWith":"requires ipykernel to be installed."}
2021-02-03T16:00:35.4921469Z 
2021-02-03T16:00:35.4922891Z 4426 Info 2021-02-03 16:00:35: Exact Message found 'Python 3.8.5 64-bit ('base': conda) requires ipykernel to be installed.'
2021-02-03T16:00:35.4923516Z 
2021-02-03T16:00:35.4961262Z Info Python Extension: 2021-02-03 16:00:35: Get Interpreters in CacheableLocatorService, Class name = m, completed in 0ms, has a truthy return value, Arg 1: undefined, Arg 2: undefined, Return Value: []
2021-02-03T16:00:35.4962513Z 
2021-02-03T16:00:35.4964164Z Info Python Extension: 2021-02-03 16:00:35: Cached data exists getEnvironmentVariables, <No Resource>
2021-02-03T16:00:35.4967020Z Info Python Extension: 2021-02-03 16:00:35: > /opt/hostedtoolcache/Python/3.8.7/x64/bin/python ~/.vscode-insiders/extensions/ms-python.python-2021.1.502429796/pythonFiles/pyvsc-run-isolated.py -c "import pip"
2021-02-03T16:00:35.5007394Z Info Python Extension: 2021-02-03 16:00:35: > /opt/hostedtoolcache/Python/3.8.7/x64/bin/python ~/.vscode-insiders/extensions/ms-python.python-2021.1.502429796/pythonFiles/pyvsc-run-isolated.py -c "import pip"
2021-02-03T16:00:35.5008672Z 
2021-02-03T16:00:35.5270532Z 4426 Info 2021-02-03 16:00:35: Install Missing Dependencies, Class name = KernelDependencyService, completed in 277ms, has a truthy return value, Return Value: 2
2021-02-03T16:00:35.5273224Z 
2021-02-03T16:00:35.5281954Z 4426 Error 2021-02-03 16:00:35: Failed to change kernel IpyKernelNotInstalledError: IPyKernel not installed into interpreter Python 3.8.5 64-bit ('base': conda):/usr/share/miniconda/bin/python
2021-02-03T16:00:35.5286260Z     at JupyterSession.installDependenciesIntoInterpreter (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/jupyterSession.js:3529:15)
2021-02-03T16:00:35.5289456Z     at JupyterSession.createSession (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/jupyterSession.js:3441:7)
2021-02-03T16:00:35.5292330Z     at JupyterSession.createNewKernelSession (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/jupyterSession.js:3280:22)
2021-02-03T16:00:35.5295053Z     at JupyterSession.connect (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/jupyterSession.js:3256:22)
2021-02-03T16:00:35.5297762Z     at JupyterSessionManager.startNew (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/jupyterSessionManager.js:3922:7)
2021-02-03T16:00:35.5302798Z     at getExistingSession (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/liveshare/hostJupyterServer.js:4068:290)
2021-02-03T16:00:35.5305381Z     at HostJupyterServer.createNotebookInstance (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/liveshare/hostJupyterServer.js:4084:38) {
2021-02-03T16:00:35.5306837Z   reason: 2
2021-02-03T16:00:35.5307226Z }
2021-02-03T16:00:35.5307478Z 
2021-02-03T16:00:35.5315947Z 4426 Info 2021-02-03 16:00:35: Shutdown session -- complete
2021-02-03T16:00:35.5316376Z 
2021-02-03T16:00:35.5327847Z 4426 Error 2021-02-03 16:00:35: failed to create INotebook in kernel JupyterInvalidKernelError: Kernel Python 3.8.5 64-bit ('base': conda) is not usable. Check the Jupyter output tab for more information.
2021-02-03T16:00:35.5330720Z     at JupyterSession.createNewKernelSession (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/jupyterSession.js:3306:15)
2021-02-03T16:00:35.5333075Z     at JupyterSession.connect (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/jupyterSession.js:3256:22)
2021-02-03T16:00:35.5335384Z     at JupyterSessionManager.startNew (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/jupyterSessionManager.js:3922:7)
2021-02-03T16:00:35.5337696Z     at getExistingSession (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/liveshare/hostJupyterServer.js:4068:290)
2021-02-03T16:00:35.5340249Z     at HostJupyterServer.createNotebookInstance (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/liveshare/hostJupyterServer.js:4084:38) {
2021-02-03T16:00:35.5342738Z   kernelConnectionMetadata: {
2021-02-03T16:00:35.5343499Z     kernelModel: undefined,
2021-02-03T16:00:35.5344046Z     interpreter: {
2021-02-03T16:00:35.5344548Z       architecture: 3,
2021-02-03T16:00:35.5345428Z       path: '/usr/share/miniconda/bin/python',
2021-02-03T16:00:35.5345973Z       version: [$],
2021-02-03T16:00:35.5346788Z       sysVersion: '3.8.5 (default, Sep  4 2020, 07:30:14) \n[GCC 7.3.0]',
2021-02-03T16:00:35.5347610Z       sysPrefix: '/usr/share/miniconda',
2021-02-03T16:00:35.5351037Z       fileHash: 'afc1735bbf9bdf2030f72c76a7c393fdc81bd946f48b7ea5d6cff2cafb6cdd76eef6e3b88eb67af808849f5e48165957a76a788cbd2ad22d57603c65119006b3',
2021-02-03T16:00:35.5354288Z       companyDisplayName: 'Anaconda, Inc.',
2021-02-03T16:00:35.5355054Z       envType: 'Conda',
2021-02-03T16:00:35.5355777Z       envPath: '/usr/share/miniconda',
2021-02-03T16:00:35.5356463Z       envName: 'base',
2021-02-03T16:00:35.5357244Z       displayName: "Python 3.8.5 64-bit ('base': conda)"
2021-02-03T16:00:35.5357752Z     },
2021-02-03T16:00:35.5358235Z     kernelSpec: undefined,
2021-02-03T16:00:35.5359166Z     kind: 'startUsingPythonInterpreter'
2021-02-03T16:00:35.5359792Z   }
2021-02-03T16:00:35.5360137Z }
2021-02-03T16:00:35.5360388Z 
2021-02-03T16:00:35.5409190Z 4426 Info 2021-02-03 16:00:35: Message displayed to user 'Kernel Python 3.8.5 64-bit ('base': conda) is not usable. Check the Jupyter output tab for more information.', condition {"endsWith":"requires ipykernel to be installed."}
2021-02-03T16:00:35.5410188Z 
2021-02-03T16:00:35.5616991Z 4426 Error 2021-02-03 16:00:35: DataScience Error JupyterInvalidKernelError: Kernel Python 3.8.5 64-bit ('base': conda) is not usable. Check the Jupyter output tab for more information.
2021-02-03T16:00:35.5621923Z     at JupyterSession.createNewKernelSession (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/jupyterSession.js:3306:15)
2021-02-03T16:00:35.5624789Z     at JupyterSession.connect (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/jupyterSession.js:3256:22)
2021-02-03T16:00:35.5627549Z     at JupyterSessionManager.startNew (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/jupyterSessionManager.js:3922:7)
2021-02-03T16:00:35.5630299Z     at getExistingSession (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/liveshare/hostJupyterServer.js:4068:290)
2021-02-03T16:00:35.5633252Z     at HostJupyterServer.createNotebookInstance (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/liveshare/hostJupyterServer.js:4084:38) {
2021-02-03T16:00:35.5635234Z   kernelConnectionMetadata: {
2021-02-03T16:00:35.5636192Z     kernelModel: undefined,
2021-02-03T16:00:35.5636999Z     interpreter: {
2021-02-03T16:00:35.5637752Z       architecture: 3,
2021-02-03T16:00:35.5640012Z       path: '/usr/share/miniconda/bin/python',
2021-02-03T16:00:35.5640841Z       version: [$],
2021-02-03T16:00:35.5641926Z       sysVersion: '3.8.5 (default, Sep  4 2020, 07:30:14) \n[GCC 7.3.0]',
2021-02-03T16:00:35.5643360Z       sysPrefix: '/usr/share/miniconda',
2021-02-03T16:00:35.5647251Z       fileHash: 'afc1735bbf9bdf2030f72c76a7c393fdc81bd946f48b7ea5d6cff2cafb6cdd76eef6e3b88eb67af808849f5e48165957a76a788cbd2ad22d57603c65119006b3',
2021-02-03T16:00:35.5651390Z       companyDisplayName: 'Anaconda, Inc.',
2021-02-03T16:00:35.5652542Z       envType: 'Conda',
2021-02-03T16:00:35.5653608Z       envPath: '/usr/share/miniconda',
2021-02-03T16:00:35.5654619Z       envName: 'base',
2021-02-03T16:00:35.5655757Z       displayName: "Python 3.8.5 64-bit ('base': conda)"
2021-02-03T16:00:35.5656539Z     },
2021-02-03T16:00:35.5657368Z     kernelSpec: undefined,
2021-02-03T16:00:35.5658567Z     kind: 'startUsingPythonInterpreter'
2021-02-03T16:00:35.5659193Z   }
2021-02-03T16:00:35.5659600Z }
2021-02-03T16:00:35.5659850Z 
2021-02-03T16:00:35.5671190Z 4426 Error 2021-02-03 16:00:35: failed to start INotebook in kernel JupyterInvalidKernelError: Kernel Python 3.8.5 64-bit ('base': conda) is not usable. Check the Jupyter output tab for more information.
2021-02-03T16:00:35.5673751Z     at JupyterSession.createNewKernelSession (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/jupyterSession.js:3306:15)
2021-02-03T16:00:35.5676105Z     at JupyterSession.connect (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/jupyterSession.js:3256:22)
2021-02-03T16:00:35.5678412Z     at JupyterSessionManager.startNew (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/jupyterSessionManager.js:3922:7)
2021-02-03T16:00:35.5680744Z     at getExistingSession (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/liveshare/hostJupyterServer.js:4068:290)
2021-02-03T16:00:35.5683288Z     at HostJupyterServer.createNotebookInstance (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/liveshare/hostJupyterServer.js:4084:38) {
2021-02-03T16:00:35.5684947Z   kernelConnectionMetadata: {
2021-02-03T16:00:35.5685838Z     kernelModel: undefined,
2021-02-03T16:00:35.5686381Z     interpreter: {
2021-02-03T16:00:35.5686885Z       architecture: 3,
2021-02-03T16:00:35.5687716Z       path: '/usr/share/miniconda/bin/python',
2021-02-03T16:00:35.5688247Z       version: [$],
2021-02-03T16:00:35.5689059Z       sysVersion: '3.8.5 (default, Sep  4 2020, 07:30:14) \n[GCC 7.3.0]',
2021-02-03T16:00:35.5689888Z       sysPrefix: '/usr/share/miniconda',
2021-02-03T16:00:35.5693292Z       fileHash: 'afc1735bbf9bdf2030f72c76a7c393fdc81bd946f48b7ea5d6cff2cafb6cdd76eef6e3b88eb67af808849f5e48165957a76a788cbd2ad22d57603c65119006b3',
2021-02-03T16:00:35.5696556Z       companyDisplayName: 'Anaconda, Inc.',
2021-02-03T16:00:35.5697333Z       envType: 'Conda',
2021-02-03T16:00:35.5698057Z       envPath: '/usr/share/miniconda',
2021-02-03T16:00:35.5698734Z       envName: 'base',
2021-02-03T16:00:35.5699525Z       displayName: "Python 3.8.5 64-bit ('base': conda)"
2021-02-03T16:00:35.5700025Z     },
2021-02-03T16:00:35.5700511Z     kernelSpec: undefined,
2021-02-03T16:00:35.5701456Z     kind: 'startUsingPythonInterpreter'
2021-02-03T16:00:35.5702070Z   }
2021-02-03T16:00:35.5702421Z }
2021-02-03T16:00:35.5702668Z 
2021-02-03T16:00:35.5714340Z 4426 Error 2021-02-03 16:00:35: Failed to execute cells in CellExecutionQueue JupyterInvalidKernelError: Kernel Python 3.8.5 64-bit ('base': conda) is not usable. Check the Jupyter output tab for more information.
2021-02-03T16:00:35.5717016Z     at JupyterSession.createNewKernelSession (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/jupyterSession.js:3306:15)
2021-02-03T16:00:35.5719369Z     at JupyterSession.connect (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/jupyterSession.js:3256:22)
2021-02-03T16:00:35.5721684Z     at JupyterSessionManager.startNew (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/jupyterSessionManager.js:3922:7)
2021-02-03T16:00:35.5724026Z     at getExistingSession (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/liveshare/hostJupyterServer.js:4068:290)
2021-02-03T16:00:35.5727042Z     at HostJupyterServer.createNotebookInstance (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/liveshare/hostJupyterServer.js:4084:38) {
2021-02-03T16:00:35.5728718Z   kernelConnectionMetadata: {
2021-02-03T16:00:35.5729419Z     kernelModel: undefined,
2021-02-03T16:00:35.5729964Z     interpreter: {
2021-02-03T16:00:35.5730454Z       architecture: 3,
2021-02-03T16:00:35.5731276Z       path: '/usr/share/miniconda/bin/python',
2021-02-03T16:00:35.5731816Z       version: [$],
2021-02-03T16:00:35.5732633Z       sysVersion: '3.8.5 (default, Sep  4 2020, 07:30:14) \n[GCC 7.3.0]',
2021-02-03T16:00:35.5733467Z       sysPrefix: '/usr/share/miniconda',
2021-02-03T16:00:35.5736887Z       fileHash: 'afc1735bbf9bdf2030f72c76a7c393fdc81bd946f48b7ea5d6cff2cafb6cdd76eef6e3b88eb67af808849f5e48165957a76a788cbd2ad22d57603c65119006b3',
2021-02-03T16:00:35.5740264Z       companyDisplayName: 'Anaconda, Inc.',
2021-02-03T16:00:35.5741115Z       envType: 'Conda',
2021-02-03T16:00:35.5741847Z       envPath: '/usr/share/miniconda',
2021-02-03T16:00:35.5742528Z       envName: 'base',
2021-02-03T16:00:35.5743319Z       displayName: "Python 3.8.5 64-bit ('base': conda)"
2021-02-03T16:00:35.5743831Z     },
2021-02-03T16:00:35.5744300Z     kernelSpec: undefined,
2021-02-03T16:00:35.5745235Z     kind: 'startUsingPythonInterpreter'
2021-02-03T16:00:35.5745849Z   }
2021-02-03T16:00:35.5746204Z }
2021-02-03T16:00:35.5746454Z 
2021-02-03T16:00:35.5771475Z 4426 Info 2021-02-03 16:00:35: Cancel pending cells
2021-02-03T16:00:35.5772757Z 
2021-02-03T16:00:35.5774280Z 4426 Info 2021-02-03 16:00:35: Cell Index:0, state:1, exec: undefined. Execution cancelled
2021-02-03T16:00:35.5774978Z 
2021-02-03T16:00:35.5776344Z 4426 Info 2021-02-03 16:00:35: Cell Index:0, state:1, exec: undefined. Completed due to cancellation
2021-02-03T16:00:35.5777076Z 
2021-02-03T16:00:35.5778533Z 4426 Info 2021-02-03 16:00:35: Cell Index:0, state:1, exec: undefined. Update cell statue as idle and message as empty
2021-02-03T16:00:35.5779314Z 
2021-02-03T16:00:35.5850535Z Unhandled Promise Rejection with the message Error: Kernel Python 3.8.5 64-bit ('base': conda) is not usable. Check the Jupyter output tab for more information., Error, Kernel Python 3.8.5 64-bit ('base': conda) is not usable. Check the Jupyter output tab for more information., Error: Kernel Python 3.8.5 64-bit ('base': conda) is not usable. Check the Jupyter output tab for more information.
2021-02-03T16:00:35.5853587Z     at JupyterSession.createNewKernelSession (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/jupyterSession.js:3306:15)
2021-02-03T16:00:35.5856396Z     at JupyterSession.connect (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/jupyterSession.js:3256:22)
2021-02-03T16:00:35.5858845Z     at JupyterSessionManager.startNew (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/jupyterSessionManager.js:3922:7)
2021-02-03T16:00:35.5861201Z     at getExistingSession (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/liveshare/hostJupyterServer.js:4068:290)
2021-02-03T16:00:35.5863754Z     at HostJupyterServer.createNotebookInstance (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/liveshare/hostJupyterServer.js:4084:38)
2021-02-03T16:00:35.5865078Z 
2021-02-03T16:00:35.6368798Z 4426 Info 2021-02-03 16:00:35: Cell Index:0, state:2, exec: undefined. Cell cancelled & resolving
2021-02-03T16:00:35.6371246Z 
2021-02-03T16:00:35.6380234Z 4426 Info 2021-02-03 16:00:35: Cell Index:0, state:2, exec: undefined. Execution disposed
2021-02-03T16:00:35.6381791Z 
2021-02-03T16:00:36.4854071Z rejected promise not handled within 1 second: Error: Kernel Python 3.8.5 64-bit ('base': conda) is not usable. Check the Jupyter output tab for more information.
2021-02-03T16:00:36.4855525Z 
2021-02-03T16:00:36.4859826Z stack trace: Error: Kernel Python 3.8.5 64-bit ('base': conda) is not usable. Check the Jupyter output tab for more information.
2021-02-03T16:00:36.4863034Z     at JupyterSession.createNewKernelSession (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/jupyterSession.js:3306:15)
2021-02-03T16:00:36.4866667Z     at JupyterSession.connect (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/jupyterSession.js:3256:22)
2021-02-03T16:00:36.4869495Z     at JupyterSessionManager.startNew (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/jupyterSessionManager.js:3922:7)
2021-02-03T16:00:36.4872285Z     at getExistingSession (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/liveshare/hostJupyterServer.js:4068:290)
2021-02-03T16:00:36.4875459Z     at HostJupyterServer.createNotebookInstance (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/liveshare/hostJupyterServer.js:4084:38)
2021-02-03T16:00:36.4877108Z 
2021-02-03T16:00:36.4879756Z Kernel Python 3.8.5 64-bit ('base': conda) is not usable. Check the Jupyter output tab for more information.: Error: Kernel Python 3.8.5 64-bit ('base': conda) is not usable. Check the Jupyter output tab for more information.
2021-02-03T16:00:36.4882312Z     at JupyterSession.createNewKernelSession (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/jupyterSession.js:3306:15)
2021-02-03T16:00:36.4884661Z     at JupyterSession.connect (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/jupyterSession.js:3256:22)
2021-02-03T16:00:36.4887231Z     at JupyterSessionManager.startNew (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/jupyterSessionManager.js:3922:7)
2021-02-03T16:00:36.4889580Z     at getExistingSession (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/liveshare/hostJupyterServer.js:4068:290)
2021-02-03T16:00:36.4892149Z     at HostJupyterServer.createNotebookInstance (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/liveshare/hostJupyterServer.js:4084:38)
2021-02-03T16:00:36.4893700Z 
2021-02-03T16:00:49.8854288Z Test failing --- Cell 1 did not complete successfully
2021-02-03T16:00:49.8859431Z 
2021-02-03T16:00:49.8875154Z 4426 Info 2021-02-03 16:00:49: End Test Switch kernels

</details>

**Comment by greazer** [comment]
We should consider adding a test to detect this.

**Comment by DonJayamanne** [comment]
Related to #4947 (found issues in #4947 that are required here)

**Comment by IanMatthewHuff** [comment]
Validated via test success recently.
