### ISSUE TITLE
Native Notebooks, Pylance - Cells variables show as "not defined" until cell is "activated"

### ISSUE THREAD

**Issue by jaymegordo** [microsoft/vscode-jupyter#4654]
When opening an existing notebook, pylance seems to fail to recognize all cell variables, and marks them as "not defined" until the cell is switched to markdown then back to code.

Additionally, (maybe related maybe not), the cell sometimes can't be run until its converted to/from markdown/code. In this case I was able to run the cell even with the syntax errors.

I have been using native notebooks for 3+ months, and this issue has always happened with a large number of notebooks I've opened.

I have some startup errors in my logs, but not sure what they mean or if they're related.

## Environment data

-   VS Code version:  1.53.0-insider
-   Jupyter Extension version: v2020.12.414227025
-   Python Extension version: v2021.2.531887795-dev
-   OS (Windows | Mac | Linux distro) and version: Darwin x64 20.3.0
-   Python and/or Anaconda version: 3.7.9
-   Type of virtual environment used: conda
-   Jupyter server running: Local

## Expected behaviour

Cell variables are properly identified by pylance WITHOUT having to convert cell to markdown then back to code.

## Actual behaviour

Cell variables are highlighted as "not defined" until cell is converted to markdown then back to code.

## Steps to reproduce:

1. Load existing notebook
2. Variables are all highlighted "not defined"

https://user-images.githubusercontent.com/29611875/106940980-14544180-66d7-11eb-80ad-33304ee40a0a.mp4

## Logs

<details>

<p>

```
User belongs to experiment group 'NativeNotebookEditor'
Error 2021-02-04 10:36:00: Jupyter Kernel Spec not found for a local connection
> /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py jupyter kernelspec --version
> /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py jupyter kernelspec --version
> /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> /opt/miniconda3/envs/573/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /opt/miniconda3/envs/573/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Error 2021-02-04 10:36:24: Jupyter Kernel Spec not found for a local connection
> /opt/miniconda3/envs/553/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Error 2021-02-04 10:36:28: Kernel died [r [Error]: [IPKernelApp] WARNING | Unknown error in handling startup files:

	at t._next (/Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:758167)
	at t.__tryOrUnsub (/Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:5463)
	at t.next (/Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:4632)
	at t._next (/Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:3736)
	at t.next (/Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:3407)
	at t.next (/Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:8976)
	at /Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:9:107791
	at /Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:421842
	at /Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:422060
	at Immediate._onImmediate (/Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:423625)
	at processImmediate (internal/timers.js:456:21)] 
Started kernel Python 3.7.9 64-bit ('553': conda)
> /opt/miniconda3/envs/553/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Error 2021-02-04 10:36:29: Kernel died [r [Error]: [IPKernelApp] WARNING | Unknown error in handling startup files:

	at t._next (/Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:758167)
	at t.__tryOrUnsub (/Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:5463)
	at t.next (/Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:4632)
	at t._next (/Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:3736)
	at t.next (/Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:3407)
	at t.next (/Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:8976)
	at /Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:9:107791
	at /Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:421842
	at /Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:422060
	at Immediate._onImmediate (/Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:423625)
	at processImmediate (internal/timers.js:456:21)] 

```

</p>
</details>

**Comment by DonJayamanne** [comment]
Thanks for filing this issue.
* Please could you provide a copy of this notebook.
* Its possible we have addressed this issue, please could you try the following & let me know if it works for you (i.e. if problem has been resolved in our latest dev build).
	* Please install the following build of the Jupyter extension (this is our latest development version)
		* https://github.com/microsoft/vscode-jupyter/suites/1970139674/artifacts/39137516
	* Please install the following build of the Python extension (this is our latest development version)
		* Please install the following build of the Jupyter extension (this is out latest development version)

Note: You need to install both, as the Language Capabilities (intellisense, etc) are provided by Pylance & Python extension.

**Comment by jaymegordo** [comment]
@DonJayamanne thank you! The dev version has in fact fixed that issue.

My real issue I guess was that I couldn't update to the insiders version from within vscode, but that download link worked.

This was my error in the output > jupyter console:
> Error 2021-02-04 11:10:46: Handling channel failed, Class name = p, completed in 879ms, has a falsy return value, Arg 1: "daily", Arg 2: true, Return Value: undefined [Error: Failed with status 404, The specified resource does not exist., Uri https://pvsc.blob.core.windows.net/extension-builds-jupyter/ms-toolsai-jupyter-insiders.vsix

Hoping now that I've got the dev version installed it will continue to update correctly either daily/weekly.

## Logs

<details>

<p>

```
User belongs to experiment group 'NativeNotebookEditor'
Error 2021-02-04 10:36:00: Jupyter Kernel Spec not found for a local connection
> /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py jupyter kernelspec --version
> /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py jupyter kernelspec --version
> /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> /opt/miniconda3/envs/573/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /opt/miniconda3/envs/573/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Error 2021-02-04 10:36:24: Jupyter Kernel Spec not found for a local connection
> /opt/miniconda3/envs/553/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Error 2021-02-04 10:36:28: Kernel died [r [Error]: [IPKernelApp] WARNING | Unknown error in handling startup files:

	at t._next (/Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:758167)
	at t.__tryOrUnsub (/Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:5463)
	at t.next (/Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:4632)
	at t._next (/Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:3736)
	at t.next (/Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:3407)
	at t.next (/Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:8976)
	at /Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:9:107791
	at /Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:421842
	at /Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:422060
	at Immediate._onImmediate (/Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:423625)
	at processImmediate (internal/timers.js:456:21)] 
Started kernel Python 3.7.9 64-bit ('553': conda)
> /opt/miniconda3/envs/553/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Error 2021-02-04 10:36:29: Kernel died [r [Error]: [IPKernelApp] WARNING | Unknown error in handling startup files:

	at t._next (/Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:758167)
	at t.__tryOrUnsub (/Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:5463)
	at t.next (/Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:4632)
	at t._next (/Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:3736)
	at t.next (/Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:3407)
	at t.next (/Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:8976)
	at /Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:9:107791
	at /Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:421842
	at /Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:422060
	at Immediate._onImmediate (/Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:423625)
	at processImmediate (internal/timers.js:456:21)] 
Starting download for Insiders build.
Downloading https://pvsc.blob.core.windows.net/extension-builds-jupyter/ms-toolsai-jupyter-insiders.vsix...
Error 2021-02-04 11:10:46: Downloading insiders build of extension failed, Class name = f, completed in 859ms, has a falsy return value, , Return Value: undefined [Error: Failed with status 404, The specified resource does not exist., Uri https://pvsc.blob.core.windows.net/extension-builds-jupyter/ms-toolsai-jupyter-insiders.vsix
	at H.<anonymous> (/Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:720551)
	at H.emit (events.js:327:22)
	at H.onRequestResponse (/Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/node_modules/request.js:189:16870)
	at ClientRequest.emit (events.js:327:22)
	at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
	at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
	at TLSSocket.socketOnData (_http_client.js:469:22)
	at TLSSocket.emit (events.js:315:20)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:271:9)
	at TLSSocket.Readable.push (_stream_readable.js:212:10)
	at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)]
Error 2021-02-04 11:10:46: Installing insiders build of extension failed, Class name = f, completed in 864ms, has a falsy return value, , Return Value: undefined [Error: Failed with status 404, The specified resource does not exist., Uri https://pvsc.blob.core.windows.net/extension-builds-jupyter/ms-toolsai-jupyter-insiders.vsix
	at H.<anonymous> (/Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:720551)
	at H.emit (events.js:327:22)
	at H.onRequestResponse (/Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/node_modules/request.js:189:16870)
	at ClientRequest.emit (events.js:327:22)
	at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
	at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
	at TLSSocket.socketOnData (_http_client.js:469:22)
	at TLSSocket.emit (events.js:315:20)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:271:9)
	at TLSSocket.Readable.push (_stream_readable.js:212:10)
	at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)]
Error 2021-02-04 11:10:46: Handling channel failed, Class name = p, completed in 879ms, has a falsy return value, Arg 1: "daily", Arg 2: true, Return Value: undefined [Error: Failed with status 404, The specified resource does not exist., Uri https://pvsc.blob.core.windows.net/extension-builds-jupyter/ms-toolsai-jupyter-insiders.vsix
	at H.<anonymous> (/Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:47:720551)
	at H.emit (events.js:327:22)
	at H.onRequestResponse (/Users/Jayme/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/node_modules/request.js:189:16870)
	at ClientRequest.emit (events.js:327:22)
	at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
	at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
	at TLSSocket.socketOnData (_http_client.js:469:22)
	at TLSSocket.emit (events.js:315:20)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:271:9)
	at TLSSocket.Readable.push (_stream_readable.js:212:10)
	at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)]

```
</p>
</details>

**Comment by DonJayamanne** [comment]
Thank you very much for confirming the fix, I'll close this issue for now.

> Hoping now that I've got the dev version installed it will continue to update correctly either daily/weekly.

Unfortunately the daily/weekly development (insiders build) functionality doesn't work just yet. We're having a few technical issues in that space & its being tracked in a separate issue.

However when we do release a new version (some time in the next week or so), VSCode will update your copy to the latest version .

Closing this for now. Again, thanks for confirming the fix.
