### ISSUE TITLE
Jupyter interactive cannot use via remote ssh as it showed chunkLoadError

### ISSUE THREAD

**Issue by ibowennn** [microsoft/vscode-jupyter#4698]
Issue Type: <b>Bug</b>

When I use remote ssh connected to the ubuntu server, I cannot ordinarily open the .ipynb file and cannot open the interactive window when reading the .py file.
When I open the .ipynb file, the remote vscode window will reconnect repeatedly.
When I open the interactive window on the .py file, the interactive window cannot normally display, with a notion 
<img width="415" alt="图片1" src="https://user-images.githubusercontent.com/51699450/107189409-4db4e600-6a24-11eb-8d01-acdf3a96b849.png">

I check the Webview developer tools, there are following warnings:
![图片2](https://user-images.githubusercontent.com/51699450/107189424-54435d80-6a24-11eb-9a17-999b9001a2ec.png)

Extension version: 2020.12.414227025
VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.8.0-41-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz (12 x 1608)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (7.77GB free)|
|Process Argv|--folder-uri vscode-remote://ssh-remote%2Bfsk-remote/home/bowen/git/coding/python --crash-reporter-id fb7316d2-25cc-4b66-bbff-db82fd1cc005|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: fsk-remote|
|OS|Linux x64 5.8.0-41-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz (48 x 3247)|
|Memory (System)|94.28GB (75.92GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by IanMatthewHuff** [comment]
@ibowennn Quick clarification questions here. Are you using ssh to connect to that remote machine? Or are you using the VS Code ssh extension detailed here: https://code.visualstudio.com/docs/remote/ssh#:~:text=The%20Visual%20Studio%20Code%20Remote%20-%20SSH%20extension,files%20and%20folders%20anywhere%20on%20the%20remote%20filesystem.

**Comment by sergguta** [comment]
I have the same problem. I am connected by SSH through the Remote SSH extension. The python debugger works without problem in the remote server. How I can resolve this?

**Comment by sergguta** [comment]
> Issue Type: Bug
> 
> When I use remote ssh connected to the ubuntu server, I cannot ordinarily open the .ipynb file and cannot open the interactive window when reading the .py file.
> When I open the .ipynb file, the remote vscode window will reconnect repeatedly.
> When I open the interactive window on the .py file, the interactive window cannot normally display, with a notion
> <img alt="图片1" width="415" src="https://user-images.githubusercontent.com/51699450/107189409-4db4e600-6a24-11eb-8d01-acdf3a96b849.png">
> 
> I check the Webview developer tools, there are following warnings:
> ![图片2](https://user-images.githubusercontent.com/51699450/107189424-54435d80-6a24-11eb-9a17-999b9001a2ec.png)
> 
> Extension version: 2020.12.414227025
> VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
> OS version: Windows_NT x64 10.0.19042
> Remote OS version: Linux x64 5.8.0-41-generic
> 
> System Info
> A/B Experiments

¿do you can fix it?

**Comment by IanMatthewHuff** [comment]
That bug is a bit strange, I don't believe that I've seen it before. Could you try the following for me?

1. Navigate to the vscode extensions directory: https://code.visualstudio.com/docs/editor/extension-gallery#_where-are-extensions-installed
2. In that directory you should see a folder for the jupyter extension something like ms-toolsas.jupyter-2020.12.414227025.
3. Under that Jupyter directory please share what files are present in the following path. /out/datascience-ui/notebook

The files that are failing to load should be in there. In remote scenarios the extension should be copied fully over to the remote machine, so if the files are present there then we know that something is going wrong with the copy to the remote machine.

**Comment by ibowennn** [comment]
> @ibowennn Quick clarification questions here. Are you using ssh to connect to that remote machine? Or are you using the VS Code ssh extension detailed here: https://code.visualstudio.com/docs/remote/ssh#:~:text=The%20Visual%20Studio%20Code%20Remote%20-%20SSH%20extension,files%20and%20folders%20anywhere%20on%20the%20remote%20filesystem.

yes, I used the VS code extension in the link. The files in the ./out/datascience-ui/notebook are as followed:
![image](https://user-images.githubusercontent.com/51699450/107593751-0f4d4000-6c4b-11eb-98fd-35f3b3da5f91.png)

**Comment by ibowennn** [comment]
> > Issue Type: Bug
> > When I use remote ssh connected to the ubuntu server, I cannot ordinarily open the .ipynb file and cannot open the interactive window when reading the .py file.
> > When I open the .ipynb file, the remote vscode window will reconnect repeatedly.
> > When I open the interactive window on the .py file, the interactive window cannot normally display, with a notion
> > <img alt="图片1" width="415" src="https://user-images.githubusercontent.com/51699450/107189409-4db4e600-6a24-11eb-8d01-acdf3a96b849.png">
> > I check the Webview developer tools, there are following warnings:
> > ![图片2](https://user-images.githubusercontent.com/51699450/107189424-54435d80-6a24-11eb-9a17-999b9001a2ec.png)
> > Extension version: 2020.12.414227025
> > VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
> > OS version: Windows_NT x64 10.0.19042
> > Remote OS version: Linux x64 5.8.0-41-generic
> > System Info
> > A/B Experiments
> 
> ¿do you can fix it?

No, I haven't fix that. The bug appears frequently when I use VS code ssh extension via frp, and less when I was in the local area network.

**Comment by IanMatthewHuff** [comment]
Thanks, that info is helpful. One last question, have you ever seen this error when just running locally? Not SSH via LAN but just when running a notebook without using the ssh-extension at all? It looks to me like I might have to file an issue on the SSH extension here. That should be moving over all the files in the extension to the remote machine when running, but it looks like one of them is not getting transferred.

**Comment by ibowennn** [comment]
> Thanks, that info is helpful. One last question, have you ever seen this error when just running locally? Not SSH via LAN but just when running a notebook without using the ssh-extension at all? It looks to me like I might have to file an issue on the SSH extension here. That should be moving over all the files in the extension to the remote machine when running, but it looks like one of them is not getting transferred.

I didn't try to run the VS code locally, because the ubuntu server was somewhere else without a monitor. 
The error appears frequently when I use VS code ssh extension via frp, when I was at home and connect to the server at the workplace, and less when I was in the local area network.
The error in figure 1 located in the file "vendors~dataresource~geojson~modeldebug~nteract_transforms~nteract_transforms_vsdom.bundle.js"

**Comment by sergguta** [comment]
Hi, 

This is the complete error:

ChunkLoadError: Loading chunk vendors~dataresource~geojson~modeldebug~nteract_transforms~nteract_transforms_vsdom failed.
(error: vscode-webview-resource://6f034858-5c7d-459a-a8e8-957460ef80a4/file///home/sergiogutierrez/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/datascience-ui/notebook/vendors~dataresource~geojson~modeldebug~nteract_transforms~nteract_transforms_vsdom.bundle.js) at 
  
    in p
    in Unknown
    in ForwardRef
    in div
    in div
    in div
    in t
    in div
    in div
    in div
    in div
    in div
    in div
    in t
    in h
    in t
    in div
    in div
    in div
    in t
    in main
    in div
    in t
    in h
    in f

And this are the files in the path /home/sergiogutierrez/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/datascience-ui/notebook

![image](https://user-images.githubusercontent.com/49599234/107905364-72c1c100-6f1c-11eb-95ff-4bc172ffa58a.png)

The last week the jupyter notebooks worked in VS Code, but today I try create a jupyter notebook and come back to appear the same error.

I stay tuned if some one find the definitive solution to this error.

greetings

**Comment by kevinmcmanus** [comment]
I'm experiencing this problem too. Is there a workaround?

Thanks.

**Comment by IanMatthewHuff** [comment]
As of now I've filed an issue on the remote SSH extension to see if I can get some help investigating this.
https://github.com/microsoft/vscode-remote-release/issues/4479

If anyone would like, they could try rolling back remote SSH. If you open the VS Code command palette there is a Extensions: Install Specific Version of Extension... command. Try rolling back the remote SSH extension two versions. I believe the version to try would be 0.62 which was released in December 2020. You might also need to turn off auto extension updating when trying this so that the newest version is not pushed over that.

**Comment by ibowennn** [comment]
> As of now I've filed an issue on the remote SSH extension to see if I can get some help investigating this.
> [microsoft/vscode-remote-release#4479](https://github.com/microsoft/vscode-remote-release/issues/4479)
> 
> If anyone would like, they could try rolling back remote SSH. If you open the VS Code command palette there is a Extensions: Install Specific Version of Extension... command. Try rolling back the remote SSH extension two versions. I believe the version to try would be 0.62 which was released in December 2020. You might also need to turn off auto extension updating when trying this so that the newest version is not pushed over that.

I rolled back to remote SSH version 0.62, deleted .vscode-server folder in remote machine, and reconnect to the server. However, the error remains the same.

**Comment by ibowennn** [comment]
> As of now I've filed an issue on the remote SSH extension to see if I can get some help investigating this.
> [microsoft/vscode-remote-release#4479](https://github.com/microsoft/vscode-remote-release/issues/4479)
> 
> If anyone would like, they could try rolling back remote SSH. If you open the VS Code command palette there is a Extensions: Install Specific Version of Extension... command. Try rolling back the remote SSH extension two versions. I believe the version to try would be 0.62 which was released in December 2020. You might also need to turn off auto extension updating when trying this so that the newest version is not pushed over that.

Any more information I need to offer?

**Comment by ibowennn** [comment]
> As of now I've filed an issue on the remote SSH extension to see if I can get some help investigating this.
> [microsoft/vscode-remote-release#4479](https://github.com/microsoft/vscode-remote-release/issues/4479)
> 
> If anyone would like, they could try rolling back remote SSH. If you open the VS Code command palette there is a Extensions: Install Specific Version of Extension... command. Try rolling back the remote SSH extension two versions. I believe the version to try would be 0.62 which was released in December 2020. You might also need to turn off auto extension updating when trying this so that the newest version is not pushed over that.

Anymore information I need to offer?

**Comment by randywreed** [comment]
Same error using ssh remote in vs-code

**Comment by IanMatthewHuff** [comment]
Hey everyone. My apologies. I was out of the office for a bit after filing the issue in the VS Code remote repo. I asked this a bit further up on the thread, and it would be helpful to have confirmed. This error is only being seen when running via remote-ssh? If you disable the remote-ssh extension and just run against a python environment on your local machine do you see this issue? If anyone does see this locally and on remote, it would change how we investigate this. My current thought is that this is remote only as that's the only time that I've seen this reported, but that would be nice to confirm.

For those seeing this issue, a couple of things to try:
1. As above, try it with remote extension disabled locally with a python environment
2. Try uninstalling and reinstalling the extension (just in case there was an issue with downloading this specific file from the marketplace)
3. After seeing this error pull out any logging (you can save it to a file and drag that file to a comment here) from the "Remote - SSH" tab of the VS Code Output window. Might be something in there that we can use.

**Comment by ibowennn** [comment]
> Hey everyone. My apologies. I was out of the office for a bit after filing the issue in the VS Code remote repo. I asked this a bit further up on the thread, and it would be helpful to have confirmed. This error is only being seen when running via remote-ssh? If you disable the remote-ssh extension and just run against a python environment on your local machine do you see this issue? If anyone does see this locally and on remote, it would change how we investigate this. My current thought is that this is remote only as that's the only time that I've seen this reported, but that would be nice to confirm.
> 
> For those seeing this issue, a couple of things to try:
> 
> 1. As above, try it with remote extension disabled locally with a python environment
> 2. Try uninstalling and reinstalling the extension (just in case there was an issue with downloading this specific file from the marketplace)
> 3. After seeing this error pull out any logging (you can save it to a file and drag that file to a comment here) from the "Remote - SSH" tab of the VS Code Output window. Might be something in there that we can use.

I tried tips 1 and 2 before, which were useless.
Sometimes the connection could succeed, but most time the connection failed. I attached both log information below. The first log  I connect the server successfully.


The second log I failed to connect the server.

**Comment by ibowennn** [comment]
> Hey everyone. My apologies. I was out of the office for a bit after filing the issue in the VS Code remote repo. I asked this a bit further up on the thread, and it would be helpful to have confirmed. This error is only being seen when running via remote-ssh? If you disable the remote-ssh extension and just run against a python environment on your local machine do you see this issue? If anyone does see this locally and on remote, it would change how we investigate this. My current thought is that this is remote only as that's the only time that I've seen this reported, but that would be nice to confirm.
> 
> For those seeing this issue, a couple of things to try:
> 
> 1. As above, try it with remote extension disabled locally with a python environment
> 2. Try uninstalling and reinstalling the extension (just in case there was an issue with downloading this specific file from the marketplace)
> 3. After seeing this error pull out any logging (you can save it to a file and drag that file to a comment here) from the "Remote - SSH" tab of the VS Code Output window. Might be something in there that we can use.

I tried tips 1 and 2 before, which were useless.
Sometimes the connection could succeed, but most time the connection failed. I attached both log information below. The first log  I connect the server successfully.


The second log I failed to connect the server.

**Comment by ibowennn** [comment]
> Hey everyone. My apologies. I was out of the office for a bit after filing the issue in the VS Code remote repo. I asked this a bit further up on the thread, and it would be helpful to have confirmed. This error is only being seen when running via remote-ssh? If you disable the remote-ssh extension and just run against a python environment on your local machine do you see this issue? If anyone does see this locally and on remote, it would change how we investigate this. My current thought is that this is remote only as that's the only time that I've seen this reported, but that would be nice to confirm.
> 
> For those seeing this issue, a couple of things to try:
> 
> 1. As above, try it with remote extension disabled locally with a python environment
> 2. Try uninstalling and reinstalling the extension (just in case there was an issue with downloading this specific file from the marketplace)
> 3. After seeing this error pull out any logging (you can save it to a file and drag that file to a comment here) from the "Remote - SSH" tab of the VS Code Output window. Might be something in there that we can use.

I tried tips 1 and 2 before, which were useless.
Sometimes the connection could succeed, but most time the connection failed. I attached both log information below. The first log I connect the server successfully.
[success.txt](https://github.com/microsoft/vscode-jupyter/files/6097522/success.txt)

The second log I failed to connect the server.
[failed.txt](https://github.com/microsoft/vscode-jupyter/files/6097523/failed.txt)

**Comment by IanMatthewHuff** [comment]
@ibowennn Thanks for providing those logs. I just stuck the success and failure logs into a file diff and took a look.
![image](https://user-images.githubusercontent.com/812783/110365669-2426b480-7ffa-11eb-8bd5-42e67368f5c8.png)
Looks like in the failure log for the ssh logging there is an exception happening for a different extension installed on your vscode. Given that it's only in the failure log and not in the success log this seems like the most likely first culprit to check on.

From the logging it looks like it's something called coenraads.bracket-pair-colorizer-2.0.2.0 that is causing the issue. 
```
[00:19:26.566] Unhandled rejection: Error: Must invoke loadWASM first.
	at new u (c:\Users\Bowen\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-oniguruma\release\main.js:1:2701)
	at Object.createOnigString (c:\Users\Bowen\.vscode\extensions\coenraads.bracket-pair-colorizer-2-0.2.0\out\src\textMateLoader.js:53:48)
	at e.createOnigString (c:\Users\Bowen\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-textmate\release\main.js:1:6287)
	at e._tokenize (c:\Users\Bowen\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-textmate\release\main.js:1:8338)
	at e.tokenizeLine2 (c:\Users\Bowen\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-textmate\release\main.js:1:7637)
	at DocumentDecoration.tokenizeLine (c:\Users\Bowen\.vscode\extensions\coenraads.bracket-pair-colorizer-2-0.2.0\out\src\documentDecoration.js:232:55)
	at DocumentDecoration.tokenizeDocument (c:\Users\Bowen\.vscode\extensions\coenraads.bracket-pair-colorizer-2-0.2.0\out\src\documentDecoration.js:116:38)
	at DocumentDecorationManager.updateDocument (c:\Users\Bowen\.vscode\extensions\coenraads.bracket-pair-colorizer-2-0.2.0\out\src\documentDecorationManager.js:33:32)
	at c:\Users\Bowen\.vscode\extensions\coenraads.bracket-pair-colorizer-2-0.2.0\out\src\documentDecorationManager.js:94:30
```

The next step to take would be to uninstall that extension and try working with ssh-remote jupyter for a bit and see if the issue is resolved.

For what it's worth there do seem to be a number of extension issues recently filed on this extension that mention the same loadWASM error. And some of them also mention remote connections:
https://github.com/CoenraadS/Bracket-Pair-Colorizer-2/issues
https://github.com/CoenraadS/Bracket-Pair-Colorizer-2/issues/402

**Comment by ibowennn** [comment]
> @ibowennn Thanks for providing those logs. I just stuck the success and failure logs into a file diff and took a look.
> ![image](https://user-images.githubusercontent.com/812783/110365669-2426b480-7ffa-11eb-8bd5-42e67368f5c8.png)
> Looks like in the failure log for the ssh logging there is an exception happening for a different extension installed on your vscode. Given that it's only in the failure log and not in the success log this seems like the most likely first culprit to check on.
> 
> From the logging it looks like it's something called coenraads.bracket-pair-colorizer-2.0.2.0 that is causing the issue.
> 
> ```
> [00:19:26.566] Unhandled rejection: Error: Must invoke loadWASM first.
> 	at new u (c:\Users\Bowen\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-oniguruma\release\main.js:1:2701)
> 	at Object.createOnigString (c:\Users\Bowen\.vscode\extensions\coenraads.bracket-pair-colorizer-2-0.2.0\out\src\textMateLoader.js:53:48)
> 	at e.createOnigString (c:\Users\Bowen\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-textmate\release\main.js:1:6287)
> 	at e._tokenize (c:\Users\Bowen\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-textmate\release\main.js:1:8338)
> 	at e.tokenizeLine2 (c:\Users\Bowen\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-textmate\release\main.js:1:7637)
> 	at DocumentDecoration.tokenizeLine (c:\Users\Bowen\.vscode\extensions\coenraads.bracket-pair-colorizer-2-0.2.0\out\src\documentDecoration.js:232:55)
> 	at DocumentDecoration.tokenizeDocument (c:\Users\Bowen\.vscode\extensions\coenraads.bracket-pair-colorizer-2-0.2.0\out\src\documentDecoration.js:116:38)
> 	at DocumentDecorationManager.updateDocument (c:\Users\Bowen\.vscode\extensions\coenraads.bracket-pair-colorizer-2-0.2.0\out\src\documentDecorationManager.js:33:32)
> 	at c:\Users\Bowen\.vscode\extensions\coenraads.bracket-pair-colorizer-2-0.2.0\out\src\documentDecorationManager.js:94:30
> ```
> 
> The next step to take would be to uninstall that extension and try working with ssh-remote jupyter for a bit and see if the issue is resolved.
> 
> For what it's worth there do seem to be a number of extension issues recently filed on this extension that mention the same loadWASM error. And some of them also mention remote connections:
> https://github.com/CoenraadS/Bracket-Pair-Colorizer-2/issues
> [CoenraadS/Bracket-Pair-Colorizer-2#402](https://github.com/CoenraadS/Bracket-Pair-Colorizer-2/issues/402)

Thank you for your help.
I uninstall that extension. However, the error remains the same. Here is the new log of failure.
[failed.txt](https://github.com/microsoft/vscode-jupyter/files/6115498/failed.txt)

**Comment by roblourens** [comment]
I don't totally understand the issue now, I thought it was about the Python extension not working but now it is a different issue?

`The second log I failed to connect the server.` What exactly failed? What problem or error do you see? The log doesn't show a problem with connecting with SSH.

**Comment by IanMatthewHuff** [comment]
@roblourens There was one issue that the customer was seeing in the SSH-remote log involving another extension throwing an error, so they have disabled that and retried. The log in the post above yours was another failure log after disabling that extension. I saw a couple of failure messages in that log, but it looks like they might have succeeded after retries? I'm not used to looking at SSH-remote logs so confirmation that was a clean connection from the ssh-remote perspective is helpful to know.

**Comment by thistlillo** [comment]
I have the same problem. I am not using `.ipynb` files, but simple `.py` files with code sections (`# %%`).
The `.py` runs just fine in the remote shell, but shows these strange messages when run in the interactive console.

Using the latest of everything (as of April 14, 2021), connecting from a Windows 10 Pro notebook to a linux (Ubuntu 18) server using the ssh extension.

**Comment by danielesgit** [comment]
Hi everyone. Is there any news regarding this issue? I am using the ssh remote extension over ssh and since yesterday I am experiencing the same problem using cells from python files. local machine is Win10 Pro remote Ubuntu 20.04. Thanks.

**Comment by jeanmonet** [comment]
Connecting to WSL2 and opening `.ipynb` gives the following error. If I create a new notebook inside VSCode (connected to WSL2) and reload the window, the error appears immediately (multiple times in the same file):

```
ChunkLoadError: Loading chunk vendors~dataresource~geojson~modeldebug~nteract_transforms~nteract_transforms_vsdom failed.
(error: vscode-webview-resource://426d87ea-bbb5-452e-bdfd-000a9e828c35/file///home/usr/.vscode-server/extensions/ms-toolsai.jupyter-2021.5.745244803/out/datascience-ui/notebook/vendors~dataresource~geojson~modeldebug~nteract_transforms~nteract_transforms_vsdom.bundle.js) at 
  
    in p
    in Unknown
    in ForwardRef
    in span
    in div
    in div
    in div
    in t
    in div
    in div
    in div
    in div
    in div
    in div
    in t
    in h
    in t
    in div
    in div
    in div
    in t
    in main
    in div
    in t
    in h
    in f
```

![image](https://user-images.githubusercontent.com/15112920/115956233-f4753280-a4fb-11eb-80c9-7c45afa00958.png)

![image](https://user-images.githubusercontent.com/15112920/115956242-0a82f300-a4fc-11eb-9b40-ee5c9c751200.png)

Relevant extensions:
- Remote WSL: 0.54.6
- Jupyter: 2021.5.745244803
- Python: 2021.4.765268190

**Comment by PhilippRuchser** [comment]
> I have the same problem. I am not using `.ipynb` files, but simple `.py` files with code sections (`# %%`).
> The `.py` runs just fine in the remote shell, but shows these strange messages when run in the interactive console.

I have encountered a similar problem **in scripts where I do not output anything to sys.stdout**. 

If I execute the following cell from a `.py` file via SHIFT+ENTER and then inspect `x` in the interactive terminal, I receive the aforementioned error.

```python
# %%
import numpy as np

x = np.random.rand(3)
# %%
# [inspect `x` in the interactive terminal] -> error
```

However, I do not get the error when I have printed something in the script prior to the inspection in the interactive terminal. 

```python
# %%
import numpy as np

print("init stdout")
x = np.random.rand(3)
# %%
# [inspect `x` in the interactive terminal] -> no error
```

**Comment by janjagusch** [comment]
> > I have the same problem. I am not using `.ipynb` files, but simple `.py` files with code sections (`# %%`).
> > The `.py` runs just fine in the remote shell, but shows these strange messages when run in the interactive console.
> 
> I have encountered a similar problem **in scripts where I do not output anything to sys.stdout**.
> 
> If I execute the following cell from a `.py` file via SHIFT+ENTER and then inspect `x` in the interactive terminal, I receive the aforementioned error.
> 
> ```python
> # %%
> import numpy as np
> 
> x = np.random.rand(3)
> # %%
> # [inspect `x` in the interactive terminal] -> error
> ```
> 
> However, I do not get the error when I have printed something in the script prior to the inspection in the interactive terminal.
> 
> ```python
> # %%
> import numpy as np
> 
> print("init stdout")
> x = np.random.rand(3)
> # %%
> # [inspect `x` in the interactive terminal] -> no error
> ```

This worked for me.

- Create a Python file that contains a single line print statement
- In VS Code, run "Jupyter: Run Current File in Interactive Window"
- Afterwards you can use the interactive window normally

Thanks, @PhilippRuchser!

**Comment by ricardobns** [comment]
Following on the discoveries of @janjagusch @PhilippRuchser

**System setup**
Running VS Code on WSL2.  Extension versions are:
- Jupyter: 2021.5.745244803
- Python: 2021.4.765268190

Python interpreter is version 3.8.8 installed in an anaconda environment on WSL2 ('Python 3.8.8 64-bit ('base': conda)')

**Workaround**
1) Create a new .py file in the working directory
2) Add one line with a print statement (e.g. print("init stdout") )
3) Right-click and select Run Current File in Interactive Window

Once the three steps above are complete, I am able to continue using the interactive window and run cells in other files without errors.

Creating and running the file with the print statement:
![image](https://user-images.githubusercontent.com/76236469/117238977-78b2a880-ae60-11eb-8627-b8a04bd2d4f6.png)

Subsequently running other files in the same working directory:
![image](https://user-images.githubusercontent.com/76236469/117239607-b106b680-ae61-11eb-8ea2-5e211fa6c255.png)

**Comment by ericct** [comment]
I have the same problem, using remote-SSH (actually wrapped in code-server, but it's remote-ssh underneath). 

I can confirm the workaround detailed by @ricardobns but only for interactive python. It seems that the side effect has no consequence on notebooks. I've tried to also make a notebook with a print statement in the first cell, without success (it actually shows the problem on this cell).

On the remote host, VS Code is version 1.54.2.

On my local machine, using WSL2 (which uses the same remote-ssh approach), it works for me, on the contrary to other persons here. VS Code version is in this case 1.56.2.

**Comment by ericct** [comment]
I've just updated code-server to 3.10.2. VS Code is now at version 1.56.1 and both interactive code and notebooks work now.

If others could test with at least v 1.56.1 to see if the problem is solved, that would be great!

**Comment by IanMatthewHuff** [comment]
Hey everyone. This bug might have been mistakenly set as upstream so it wasn't getting actively looked into. @ericct and @ricardobns is your workaround still required with current vscode and Jupyter extension versions?
