### ISSUE TITLE
Unclear on how to use Lua kernel

### ISSUE THREAD

**Issue by Stanzilla** [microsoft/vscode-jupyter#4704]
## Environment data

-   VS Code version: 1.54-insiders
-   Jupyter Extension version (available under the Extensions sidebar): Version: 2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): v2021.2.531887795-dev
-   OS (Windows | Mac | Linux distro) and version: Windows
-   Python and/or Anaconda version: 3.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Remote (WSL)

## Expected behaviour

An UI hint that explains how to use Kernels that are not part of the preconfigured list

## Actual behaviour

No hint

## Steps to reproduce:

- Try to use the [iLua](https://github.com/guysv/ilua) kernel 

In comparison to the Python interpreter popup, the Jupyter Kernel one does not have an option to add one manually.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DavidKutu** [comment]
Thanks for letting us know @Stanzilla. 

We only check on specific places to look for kerneles, this is for performance reasons.
So all you need to do to get your lua kernel on VS code is:

1. Follow the instructions on the link you shared, the lua kernel should be on `<your folder>\ilua\~\.local\share\jupyter\kernels`
2. Copy that lua kernel to `C:\Users\<user>\AppData\Roaming\jupyter\kernels`
3. Reload VS code

With that the lua kernel should come up on the kernel picker:
![image](https://user-images.githubusercontent.com/20347396/107298765-d3d42b00-6a2a-11eb-8aa4-80dae2472b54.png)

**Comment by Stanzilla** [comment]
I did not have any of your paths, probably because I have the weird Store version of Python. I found `C:\Users\Stan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\share\jupyter\kernels\lua` though which does have a kernel.json file but it does not show up in VS Code. I should probably install Python normally and not via the Store.

**Comment by DavidKutu** [comment]
I see, we definitely need to look for those paths. Let me know if that fixes it for you. If that's it, I'll create a new issue to better support the store version.

**Comment by Stanzilla** [comment]
So I wish I could help more but iLua really does not like to be installed using the non-Store Python so I'm kinda stuck. Should probably still make an issue about supporting the Windows Store install of Python.

**Comment by DavidKutu** [comment]
I got it to work on the python from the website!

What error are you seeing now? We should be able to get it working.

**Comment by Stanzilla** [comment]
It fails installing Twisted:

```
ERROR: Command errored out with exit status 1: 'C:\Users\Stan\AppData\Local\Programs\Python\Python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Stan\\AppData\\Local\\Temp\\pip-install-6irluyki\\twisted_5d0f30fb942e45e8a5efc4c4756ed881\\setup.py'"'"'; __file__='"'"'C:\\Users\\Stan\\AppData\\Local\\Temp\\pip-install-6irluyki\\twisted_5d0f30fb942e45e8a5efc4c4756ed881\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Stan\AppData\Local\Temp\pip-record-491wu7y7\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Stan\AppData\Local\Programs\Python\Python39\Include\twisted' Check the logs for full command output.
```

**Comment by DavidKutu** [comment]
@Stanzilla maybe that's busted on python 3.9, I have it working on 3.8.5 (I know a million downloads, I hate that too). But this feels close.

**Comment by Stanzilla** [comment]
Okay, installed 3.8.7 (was the latest for 3.8 on the website) and installed everything again, 
copied Lua kernel from `C:\Users\Stan\AppData\Local\Programs\Python\Python38\share\jupyter\kernels` to `C:\Users\Stan\AppData\Roaming\Python\share\jupyter\kernels` which made it show up in VSCode. When trying to run the Notebook it timed out while waiting for the Kernel though. 

```
> ~\AppData\Local\Programs\Python\Python38\python.exe c:\Users\Stan\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> python -m ilua.app -c ~\AppData\Local\Temp\tmp-3064yFUnBAu0q5PM.json
cwd: c:\Users\Stan\Desktop
Error 2021-02-09 20:26:37: Timed out waiting to get a heartbeat from kernel process.
Error 2021-02-09 20:26:37: Failed to connect raw kernel session: Error: Timed out waiting to get a heartbeat from kernel process.
Error 2021-02-09 20:26:37: failed to create INotebook in kernel [Error: Timed out waiting to get a heartbeat from kernel process.
	at m.waitForHeartbeat (c:\Users\Stan\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:637256)]
Error 2021-02-09 20:26:37: DataScience Error [Error: Timed out waiting to get a heartbeat from kernel process.
	at m.waitForHeartbeat (c:\Users\Stan\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:637256)]
```

**Comment by DavidKutu** [comment]
1. Could you try running this on any terminal? `python -m ilua.app`
That should work by itself, if it doesn't there's something wrong with your installation of lua or ilua. Please share the error if that's the case.

2. Also, please try this, set this setting: `"jupyter.logging.level": "debug"` and try to select the kernel normally, then please share the contents of the OUTPUT panel in VS code. That'll give us more info.

**Comment by Stanzilla** [comment]
Yeah looks like that is the issue:

```
❯ python -m ilua.app
Traceback (most recent call last):
  File "C:\Users\Stan\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Stan\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Stan\AppData\Local\Programs\Python\Python38\lib\site-packages\ilua\app.py", line 27, in <module>
    main()
  File "C:\Users\Stan\AppData\Local\Programs\Python\Python38\lib\site-packages\ilua\app.py", line 24, in main
    ILuaApp().run()
  File "C:\Users\Stan\AppData\Local\Programs\Python\Python38\lib\site-packages\ilua\appbase.py", line 101, in run
    connection_file = ConnectionFile.generate()
  File "C:\Users\Stan\AppData\Local\Programs\Python\Python38\lib\site-packages\ilua\connection.py", line 57, in generate
    return cls(props)
  File "C:\Users\Stan\AppData\Local\Programs\Python\Python38\lib\site-packages\ilua\connection.py", line 40, in __init__
    os.mkdir(jupyter_runtime_dir(), 0o1700)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Stan\\AppData\\Roaming\\jupyter\\runtime'
```

**Comment by DavidKutu** [comment]
That is weird `C:\\Users\\Stan\\AppData\\Roaming\\jupyter\\runtime` should exist and contain a bunch of kernel connections.
Can you check if it does exist?

**Comment by Stanzilla** [comment]
There is no `jupyter` folder in `Roaming` here

**Comment by DavidKutu** [comment]
If I remember correctly, that comes from `pip install jupyter`, just make sure you're using the pip of your new Python 3.8

**Comment by Stanzilla** [comment]
Doesn't look like it?

```
 python -m pip install jupyter
Requirement already satisfied: jupyter in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (1.0.0)
Requirement already satisfied: jupyter-console in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from jupyter) (6.2.0)
Requirement already satisfied: ipykernel in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from jupyter) (5.4.3)
Requirement already satisfied: qtconsole in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from jupyter) (5.0.2)
Requirement already satisfied: ipywidgets in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from jupyter) (7.6.3)
Requirement already satisfied: notebook in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from jupyter) (6.2.0)
Requirement already satisfied: nbconvert in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from jupyter) (6.0.7)
Requirement already satisfied: jupyter-client in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from ipykernel->jupyter) (6.1.11)
Requirement already satisfied: ipython>=5.0.0 in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from ipykernel->jupyter) (7.20.0)
Requirement already satisfied: tornado>=4.2 in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from ipykernel->jupyter) (6.1)
Requirement already satisfied: traitlets>=4.1.0 in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from ipykernel->jupyter) (5.0.5)
Requirement already satisfied: backcall in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from ipython>=5.0.0->ipykernel->jupyter) (0.2.0)
Requirement already satisfied: pickleshare in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from ipython>=5.0.0->ipykernel->jupyter) (0.7.5)
Requirement already satisfied: jedi>=0.16 in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from ipython>=5.0.0->ipykernel->jupyter) (0.18.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from ipython>=5.0.0->ipykernel->jupyter) (3.0.14)
Requirement already satisfied: setuptools>=18.5 in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from ipython>=5.0.0->ipykernel->jupyter) (49.2.1)
Requirement already satisfied: decorator in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from ipython>=5.0.0->ipykernel->jupyter) (4.4.2)
Requirement already satisfied: pygments in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from ipython>=5.0.0->ipykernel->jupyter) (2.7.4)
Requirement already satisfied: colorama in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from ipython>=5.0.0->ipykernel->jupyter) (0.4.4)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from jedi>=0.16->ipython>=5.0.0->ipykernel->jupyter) (0.8.1)
Requirement already satisfied: wcwidth in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.0.0->ipykernel->jupyter) (0.2.5)
Requirement already satisfied: ipython-genutils in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from traitlets>=4.1.0->ipykernel->jupyter) (0.2.0)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from ipywidgets->jupyter) (1.0.0)
Requirement already satisfied: widgetsnbextension~=3.5.0 in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from ipywidgets->jupyter) (3.5.1)
Requirement already satisfied: nbformat>=4.2.0 in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from ipywidgets->jupyter) (5.1.2)
Requirement already satisfied: jupyter-core in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from nbformat>=4.2.0->ipywidgets->jupyter) (4.7.1)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from nbformat>=4.2.0->ipywidgets->jupyter) (3.2.0)
Requirement already satisfied: six>=1.11.0 in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->jupyter) (1.15.0)
Requirement already satisfied: attrs>=17.4.0 in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->jupyter) (20.3.0)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->jupyter) (0.17.3)
Requirement already satisfied: argon2-cffi in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from notebook->jupyter) (20.1.0)
Requirement already satisfied: jinja2 in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from notebook->jupyter) (2.11.3)
Requirement already satisfied: Send2Trash>=1.5.0 in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from notebook->jupyter) (1.5.0)
Requirement already satisfied: pyzmq>=17 in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from notebook->jupyter) (22.0.2)
Requirement already satisfied: prometheus-client in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from notebook->jupyter) (0.9.0)
Requirement already satisfied: terminado>=0.8.3 in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from notebook->jupyter) (0.9.2)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from jupyter-client->ipykernel->jupyter) (2.8.1)
Requirement already satisfied: pywin32>=1.0 in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from jupyter-core->nbformat>=4.2.0->ipywidgets->jupyter) (300)
Requirement already satisfied: pywinpty>=0.5 in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from terminado>=0.8.3->notebook->jupyter) (0.5.7)
Requirement already satisfied: cffi>=1.0.0 in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from argon2-cffi->notebook->jupyter) (1.14.4)
Requirement already satisfied: pycparser in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from cffi>=1.0.0->argon2-cffi->notebook->jupyter) (2.20)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from jinja2->notebook->jupyter) (1.1.1)
Requirement already satisfied: jupyterlab-pygments in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from nbconvert->jupyter) (0.1.2)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from nbconvert->jupyter) (1.4.3)
Requirement already satisfied: testpath in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from nbconvert->jupyter) (0.4.4)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from nbconvert->jupyter) (0.8.4)
Requirement already satisfied: entrypoints>=0.2.2 in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from nbconvert->jupyter) (0.3)
Requirement already satisfied: bleach in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from nbconvert->jupyter) (3.3.0)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from nbconvert->jupyter) (0.5.2)
Requirement already satisfied: defusedxml in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from nbconvert->jupyter) (0.6.0)
Requirement already satisfied: async-generator in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->jupyter) (1.10)
Requirement already satisfied: nest-asyncio in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->jupyter) (1.5.1)
Requirement already satisfied: webencodings in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from bleach->nbconvert->jupyter) (0.5.1)
Requirement already satisfied: packaging in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from bleach->nbconvert->jupyter) (20.9)
Requirement already satisfied: pyparsing>=2.0.2 in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from packaging->bleach->nbconvert->jupyter) (2.4.7)
Requirement already satisfied: qtpy in c:\users\stan\appdata\local\programs\python\python38\lib\site-packages (from qtconsole->jupyter) (1.9.0)

```

**Comment by rchiodo** [comment]
Closing as this issue seems like an installation problem of lua itself and not an issue with the jupyter extension.
