### ISSUE TITLE
Bad conda environment causes a notebook to not be able to be opened

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#4855]
Issue Type: <b>Bug</b>

When I tried to open it in VS Code stable
```
Unable to open 'Untitled.ipynb': Command failed: . /Users/penlv/miniconda2/bin/activate && conda activate /Users/penlv/miniconda2 && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /Users/penlv/.vscode/extensions/ms-python.python-2021.1.502429796/pythonFiles/pyvsc-run-isolated.py /Users/penlv/.vscode/extensions/ms-python.python-2021.1.502429796/pythonFiles/printEnvVariables.py # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<< Traceback (most recent call last): File "/Users/penlv/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 137, in main from ..activate import main as activator_main File "/Users/penlv/miniconda2/lib/python2.7/site-packages/conda/activate.py", line 23, in <module> from ._vendor.auxlib.compat import Utf8NamedTemporaryFile File "/Users/penlv/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/compat.py", line 10, in <module> from ._vendor.five import WhateverIO as StringIO, with_meta...
```

Extension version: 2021.2.0
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (17.81GB free)|
|Process Argv|--crash-reporter-id 299c833a-1961-40e9-a094-f10b65ea4e64|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30251590

```

</details>

**Comment by rchiodo** [comment]
We can't fix the conda failure, but opening a notebook shouldn't cause this to even run.

**Comment by rebornix** [comment]
```
  ERR Command failed: . /Users/penlv/miniconda2/bin/activate && conda activate /Users/penlv/miniconda2 && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /Users/penlv/.vscode/extensions/ms-python.python-2021.1.502429796/pythonFiles/pyvsc-run-isolated.py /Users/penlv/.vscode/extensions/ms-python.python-2021.1.502429796/pythonFiles/printEnvVariables.py

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/penlv/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 137, in main
        from ..activate import main as activator_main
      File "/Users/penlv/miniconda2/lib/python2.7/site-packages/conda/activate.py", line 23, in <module>
        from ._vendor.auxlib.compat import Utf8NamedTemporaryFile
      File "/Users/penlv/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/compat.py", line 10, in <module>
        from ._vendor.five import WhateverIO as StringIO, with_metaclass
      File "/Users/penlv/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/_vendor/five.py", line 80, in <module>
        absolute_to_nanoseconds = CoreServices.AbsoluteToNanoseconds
      File "/Users/penlv/miniconda2/lib/python2.7/ctypes/__init__.py", line 379, in __getattr__
        func = self.__getitem__(name)
      File "/Users/penlv/miniconda2/lib/python2.7/ctypes/__init__.py", line 384, in __getitem__
        func = self._FuncPtr((name_or_ordinal, self))
    AttributeError: dlsym(RTLD_DEFAULT, AbsoluteToNanoseconds): symbol not found

`$ /Users/penlv/miniconda2/bin/conda shell.posix activate`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=/Users/penlv/miniconda2/bin/conda
         CONDA_PYTHON_EXE=/Users/penlv/miniconda2/bin/python
               CONDA_ROOT=/Users/penlv/miniconda2
              CONDA_SHLVL=0
                     PATH=/Users/penlv/miniconda2/bin:/Users/penlv/miniconda2/condabin:/usr/loca
                          l/bin:/Users/penlv/.pyenv/shims:/Users/penlv/.nvm/versions/node/v12.14
                          .0/bin:/Users/penlv/miniconda2/bin:/Users/penlv/.cargo/bin:/usr/local/
                          bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion Tech Pre
                          view.app/Contents/Public:/usr/local/share/dotnet:~/.dotnet/tools:/Libr
                          ary/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/pe
                          nlv/.dotnet/tools
         PYTHONIOENCODING=utf-8
         PYTHONUNBUFFERED=1
           PYTHONWARNINGS=ignore
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
            shell level : 0
       user config file : /Users/penlv/.condarc
 populated config files : 
          conda version : 4.8.3
    conda-build version : not installed
         python version : 2.7.18.final.0
       virtual packages : __osx=10.16
       base environment : /Users/penlv/miniconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/penlv/miniconda2/pkgs
                          /Users/penlv/.conda/pkgs
       envs directories : /Users/penlv/miniconda2/envs
                          /Users/penlv/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.3 requests/2.22.0 CPython/2.7.18 Darwin/20.1.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

: Error: Command failed: . /Users/penlv/miniconda2/bin/activate && conda activate /Users/penlv/miniconda2 && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /Users/penlv/.vscode/extensions/ms-python.python-2021.1.502429796/pythonFiles/pyvsc-run-isolated.py /Users/penlv/.vscode/extensions/ms-python.python-2021.1.502429796/pythonFiles/printEnvVariables.py

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/penlv/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 137, in main
        from ..activate import main as activator_main
      File "/Users/penlv/miniconda2/lib/python2.7/site-packages/conda/activate.py", line 23, in <module>
        from ._vendor.auxlib.compat import Utf8NamedTemporaryFile
      File "/Users/penlv/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/compat.py", line 10, in <module>
        from ._vendor.five import WhateverIO as StringIO, with_metaclass
      File "/Users/penlv/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/_vendor/five.py", line 80, in <module>
        absolute_to_nanoseconds = CoreServices.AbsoluteToNanoseconds
      File "/Users/penlv/miniconda2/lib/python2.7/ctypes/__init__.py", line 379, in __getattr__
        func = self.__getitem__(name)
      File "/Users/penlv/miniconda2/lib/python2.7/ctypes/__init__.py", line 384, in __getitem__
        func = self._FuncPtr((name_or_ordinal, self))
    AttributeError: dlsym(RTLD_DEFAULT, AbsoluteToNanoseconds): symbol not found

`$ /Users/penlv/miniconda2/bin/conda shell.posix activate`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=/Users/penlv/miniconda2/bin/conda
         CONDA_PYTHON_EXE=/Users/penlv/miniconda2/bin/python
               CONDA_ROOT=/Users/penlv/miniconda2
              CONDA_SHLVL=0
                     PATH=/Users/penlv/miniconda2/bin:/Users/penlv/miniconda2/condabin:/usr/loca
                          l/bin:/Users/penlv/.pyenv/shims:/Users/penlv/.nvm/versions/node/v12.14
                          .0/bin:/Users/penlv/miniconda2/bin:/Users/penlv/.cargo/bin:/usr/local/
                          bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion Tech Pre
                          view.app/Contents/Public:/usr/local/share/dotnet:~/.dotnet/tools:/Libr
                          ary/Apple/usr/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/pe
                          nlv/.dotnet/tools
         PYTHONIOENCODING=utf-8
         PYTHONUNBUFFERED=1
           PYTHONWARNINGS=ignore
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
            shell level : 0
       user config file : /Users/penlv/.condarc
 populated config files : 
          conda version : 4.8.3
    conda-build version : not installed
         python version : 2.7.18.final.0
       virtual packages : __osx=10.16
       base environment : /Users/penlv/miniconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/penlv/miniconda2/pkgs
                          /Users/penlv/.conda/pkgs
       envs directories : /Users/penlv/miniconda2/envs
                          /Users/penlv/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.3 requests/2.22.0 CPython/2.7.18 Darwin/20.1.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.


	at ChildProcess.exithandler (child_process.js:312:12)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```

**Comment by DonJayamanne** [comment]
Shouldn't be an issue anymore.
Closing to validate

**Comment by roblourens** [comment]
Steps to verify?

**Comment by greazer** [comment]
Repro steps aren't clear. Many many changes have been made to how kernels are handled since this bug was opened. Therefore, marking as verified.
