### ISSUE TITLE
Notebook reverting to wrong Python version in 2021.2

### ISSUE THREAD

**Issue by deckchairdata** [microsoft/vscode-jupyter#4874]
## Environment data

-   VS Code version: 1.53.2
-   Jupyter Extension version (available under the Extensions sidebar): 2021.2.0 and 2021.2.576440691
-   Python Extension version (available under the Extensions sidebar): 2021.2.576481509
-   OS (Windows | Mac | Linux distro) and version: Mac Big Sur
-   Python and/or Anaconda version: 3.9.1 (pyenv)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Poetry 0.1.0, set in python.pythonPath
-   Jupyter server running: Local

## Expected behaviour

When I click on an ipynb file the kernel associated with the virtual environment should load and be listed top right.

This is with notebooks that worked up until yesterday's update.

## Actual behaviour

name of poetry virtual environment flashes up in top right, but down bottom right says 'Loading Python 3.9' - when kernel does load it isn't the venv version, but the pyenv version

Note that if at this point I save the notebook the incorrect version of Python seems to be saved with it.

Clicking on the kernel does not offer the correct kernel path as an option (and there is no way to enter it)

Note: reverting to 2020.12.414227025 fixes the problem

## Steps to reproduce:

Happens with any .ipynb, even new ones created to test.

## Logs
User belongs to experiment group 'jupyterTest'
> ~/.local/share/virtualenvs/DUN002_-_SN-F2J4UyfH-python/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.2.576440691/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> ~/.local/share/virtualenvs/DUN002_-_SN-F2J4UyfH-python/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.2.576440691/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> ~/.local/share/virtualenvs/DUN002_-_SN-F2J4UyfH-python/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.2.576440691/pythonFiles/pyvsc-run-isolated.py jupyter kernelspec --version
> ~/Library/Caches/pypoetry/virtualenvs/ggs6-[REDACTED]-KKFOGkOR-py3.9/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.2.576440691/pythonFiles/pyvsc-run-isolated.py pip list
> ~/Library/Caches/pypoetry/virtualenvs/ggs6-[REDACTED]-KKFOGkOR-py3.9/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.2.576440691/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/.local/share/virtualenvs/DUN002_-_SN-F2J4UyfH-python/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.2.576440691/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> ~/.local/share/virtualenvs/DUN002_-_SN-F2J4UyfH-python/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.2.576440691/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> ~/.local/share/virtualenvs/DUN002_-_SN-F2J4UyfH-python/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.2.576440691/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> ~/Library/Caches/pypoetry/virtualenvs/ggs005_-_cpi_valex-fg92Mh1i-py3.9/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.2.576440691/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/Library/Caches/pypoetry/virtualenvs/ggs6-[REDACTED]-KKFOGkOR-py3.9/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.2.576440691/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> ~/Library/Caches/pypoetry/virtualenvs/ggs005_-_cpi_valex-fg92Mh1i-py3.9/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.2.576440691/pythonFiles/pyvsc-run-isolated.py pip list
> ~/Library/Caches/pypoetry/virtualenvs/ggs005_-_cpi_valex-fg92Mh1i-py3.9/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.2.576440691/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/Library/Caches/pypoetry/virtualenvs/ggs005_-_cpi_valex-fg92Mh1i-py3.9/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.2.576440691/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Started kernel Python 3
> ~/Library/Caches/pypoetry/virtualenvs/ggs005_-_cpi_valex-fg92Mh1i-py3.9/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.2.576440691/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
Error 2021-02-18 16:26:33: [Error: command 'python.analysis.restartLanguageServer' already exists
	at b.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:87254)
	at Object.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:21021)
	at c.registerCommand (/Users/chris/.vscode/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:78:165256)
	at new r (/Users/chris/.vscode/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:59:227503)
	at Object.t.resolveInstance (/Users/chris/.vscode/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:44:268557)
	at /Users/chris/.vscode/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:44:267523
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/Users/chris/.vscode/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:44:268327)
	at /Users/chris/.vscode/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:44:267523
	at Object.t.resolve (/Users/chris/.vscode/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:44:267786)
	at /Users/chris/.vscode/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:44:258362
	at e._get (/Users/chris/.vscode/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:44:258128)
	at e.getTagged (/Users/chris/.vscode/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:44:256931)
	at e.getNamed (/Users/chris/.vscode/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:44:257023)
	at a.get (/Users/chris/.vscode/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:78:444709)
	at w.createRefCountedServer (/Users/chris/.vscode/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:52:33143)
	at async Object.getLanguageServer (/Users/chris/.vscode/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:52:6714)
	at async Function.create (/Users/chris/.vscode/extensions/ms-toolsai.jupyter-2021.2.576440691/out/client/extension.js:49:288580)
	at async O.getLanguageServer (/Users/chris/.vscode/extensions/ms-toolsai.jupyter-2021.2.576440691/out/client/extension.js:49:261642)
	at async O.handleChanges (/Users/chris/.vscode/extensions/ms-toolsai.jupyter-2021.2.576440691/out/client/extension.js:49:263717)
	at async O.loadAllCells (/Users/chris/.vscode/extensions/ms-toolsai.jupyter-2021.2.576440691/out/client/extension.js:49:270530)]
> ~/Library/Caches/pypoetry/virtualenvs/ggs005_-_cpi_valex-fg92Mh1i-py3.9/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.2.576440691/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Error 2021-02-18 16:26:48: [Error: command 'python.analysis.restartLanguageServer' already exists
	at b.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:87254)
	at Object.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:21021)
	at c.registerCommand (/Users/chris/.vscode/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:78:165256)
	at new r (/Users/chris/.vscode/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:59:227503)
	at Object.t.resolveInstance (/Users/chris/.vscode/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:44:268557)
	at /Users/chris/.vscode/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:44:267523
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/Users/chris/.vscode/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:44:268327)
	at /Users/chris/.vscode/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:44:267523
	at Object.t.resolve (/Users/chris/.vscode/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:44:267786)
	at /Users/chris/.vscode/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:44:258362
	at e._get (/Users/chris/.vscode/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:44:258128)
	at e.getTagged (/Users/chris/.vscode/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:44:256931)
	at e.getNamed (/Users/chris/.vscode/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:44:257023)
	at a.get (/Users/chris/.vscode/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:78:444709)
	at w.createRefCountedServer (/Users/chris/.vscode/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:52:33143)
	at async Object.getLanguageServer (/Users/chris/.vscode/extensions/ms-python.python-2021.2.576481509/out/client/extension.js:52:6714)
	at async Function.create (/Users/chris/.vscode/extensions/ms-toolsai.jupyter-2021.2.576440691/out/client/extension.js:49:288580)
	at async O.getLanguageServer (/Users/chris/.vscode/extensions/ms-toolsai.jupyter-2021.2.576440691/out/client/extension.js:49:261642)
	at async O.handleChanges (/Users/chris/.vscode/extensions/ms-toolsai.jupyter-2021.2.576440691/out/client/extension.js:49:263717)
	at async O.loadAllCells (/Users/chris/.vscode/extensions/ms-toolsai.jupyter-2021.2.576440691/out/client/extension.js:49:270530)]

<p>

```
XXX
```

</p>
</details>

**Comment by rchiodo** [comment]
Thanks for the bug. 

@deckchairdata can you include a screenshot of what you meant by the bottom right showing 'Loading Kernel ...'

Additionally can you include a screenshot of your kernel list. For example, mine looks like so:

![image](https://user-images.githubusercontent.com/19672699/108927808-e12a1180-75f5-11eb-9728-8e4c4e457a77.png)

I'm wondering if your old kernel is not listed because it's being replaced by something else we think is equivalent.

**Comment by deckchairdata** [comment]
Thanks for the reply. So after your message I went back to the latest Jupyter extension v2021.2.576440691 to recreate and get snap shots - and of course this time it all worked.

When it was failing the kernel list included a lot of old Pipenv created virtual environments. I create a virtual environment for every project and so there are a lot - also I recently moved over from Pipenv to Poetry, and several of the environments in the original list had been deleted.

What seems to have changed is that now those older kernels aren't listed any more - a lot of the cruft seems to have gone. So now my kernel list looks clean, as shown in the screenshot below, and I am no longer getting the same issue - the latest Jupyter Extension is now playing nice for me.

Is there a way to force a rebuild of the kernel cache, as it seems like me removing old Pipenv environments may have been what confused it? Also, is there a way to manually specify a kernel (like there is for Python Environments)? At the moment if the desired kernel doesn't appear in the list I don't know how to specify it.

Thanks again for all your work - if there are any other details I can give you that will help let me know.

Chris

PS when in my original message I said 'Loading...' I was wrong, I should have said 'Connecting to...'


<img width="697" alt="test_ipynb_—_GGS005_-_CPI_ValEx" src="https://user-images.githubusercontent.com/63471994/109052839-ef793b80-7690-11eb-8c75-2dc96be023cd.png">

**Comment by rchiodo** [comment]
Thanks for getting back to me. Glad it started working.

I'll try to answer your questions:

> Is there a way to force a rebuild of the kernel cache, as it seems like me removing old Pipenv environments may have been what confused it? 

This should happen on restart of VS code, but can take an update to VS code or the extension. The cache is actually stored here on my machine:
```C:\Users\Rich\AppData\Roaming\Code\User\globalStorage```

Deleting the files and folders there refreshes all caches. The problem with deleting everything there is that it also deletes the global data for all of VS code. So all first time notifications will popup again. It doesn't change your user settings though.

> Also, is there a way to manually specify a kernel (like there is for Python Environments)? At the moment if the desired kernel doesn't appear in the list I don't know how to specify it.

There's a couple of ways to manually specify a kernel. 

1. Create a new python environment and restart VS code. This should detect the new environment (see the cache problem above though) and create a new kernel in our list.
2. Create a new jupyter kernelspec.json file. You can see them if you type ```jupyter kernelspec list```. You can hand edit one if you want to add something custom. 

Unfortunately there's no automated way in VS code to generate a kernelspec (other than us finding the ones related to new python environments).

**Comment by deckchairdata** [comment]
Thanks!
