### ISSUE TITLE
Activating extension 'ms-toolsai.jupyter' failed: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api ms-toolsai.jupyter

### ISSUE THREAD

**Issue by takos22** [microsoft/vscode-jupyter#4891]
# Activating extension 'ms-toolsai.jupyter' failed

## Environment data

-   VS Code version: 1.52.1
-   Jupyter Extension version: v2021.2.576440691
-   Python Extension version: v2021.2.582707922
-   OS Windows version: 10.0.18363
-   Python version: 3.7.6
-   Type of virtual environment used virtualenv: 16.7.9
-   Jupyter server running: N/A

## Expected behaviour

Python extension starts.

## Actual behaviour

Python extension fails to start because Jupyter fails to start. This is what appears in the Developer console:
```
Activating extension 'ms-toolsai.jupyter' failed: [ms-toolsai.jupyter]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api ms-toolsai.jupyter.
Cannot activate extension 'Python' because it depends on extension 'ms-toolsai.jupyter', which failed to activate.
```

## Steps to reproduce:

1. Open a python file and wait for the python extension to start.
2. Wait for a notification to appear: 
![image](https://user-images.githubusercontent.com/59511469/108712389-fda34c80-7516-11eb-97d1-89317277aa73.png)
3. Open the developer console and find these errors:
![image](https://user-images.githubusercontent.com/59511469/108712521-2d525480-7517-11eb-9eb7-788d005b5217.png)

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Error 2021-02-22 13:51:41: extension activation failed Error: [ms-toolsai.jupyter]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api ms-toolsai.jupyter
    at a (c:\Users\...\AppData\Local\Programs\Microsoft VS Code\_\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:672:99)
    at Object.t.checkProposedApiEnabled (c:\Users\...\AppData\Local\Programs\Microsoft VS Code\_\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:672:567)
    at Object.onDidChangeCellLanguage (c:\Users\...\AppData\Local\Programs\Microsoft VS Code\_\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1037:307)
    at u.addEventHandlers (c:\Users\...\.vscode\extensions\ms-toolsai.jupyter-2021.2.576440691\out\client\extension.js:47:540495)
    at new u (c:\Users\...\.vscode\extensions\ms-toolsai.jupyter-2021.2.576440691\out\client\extension.js:47:538572)
    at Object.t.resolveInstance (c:\Users\...\.vscode\extensions\ms-toolsai.jupyter-2021.2.576440691\out\client\extension.js:47:261821)
    at c:\Users\...\.vscode\extensions\ms-toolsai.jupyter-2021.2.576440691\out\client\extension.js:47:261027
    at Array.map (<anonymous>)
    at Object.t.resolveInstance (c:\Users\...\.vscode\extensions\ms-toolsai.jupyter-2021.2.576440691\out\client\extension.js:47:261591)
    at c:\Users\...\.vscode\extensions\ms-toolsai.jupyter-2021.2.576440691\out\client\extension.js:47:261027
    at c:\Users\...\.vscode\extensions\ms-toolsai.jupyter-2021.2.576440691\out\client\extension.js:47:259975
    at Array.map (<anonymous>)
    at c:\Users\...\.vscode\extensions\ms-toolsai.jupyter-2021.2.576440691\out\client\extension.js:47:259947
    at Array.map (<anonymous>)
    at Object.t.resolveInstance (c:\Users\...\.vscode\extensions\ms-toolsai.jupyter-2021.2.576440691\out\client\extension.js:47:261591)
    at c:\Users\...\.vscode\extensions\ms-toolsai.jupyter-2021.2.576440691\out\client\extension.js:47:261027
    at Object.t.resolve (c:\Users\...\.vscode\extensions\ms-toolsai.jupyter-2021.2.576440691\out\client\extension.js:47:261290)
    at c:\Users\...\.vscode\extensions\ms-toolsai.jupyter-2021.2.576440691\out\client\extension.js:47:252391
    at e._get (c:\Users\...\.vscode\extensions\ms-toolsai.jupyter-2021.2.576440691\out\client\extension.js:47:252157)
    at e.get (c:\Users\...\.vscode\extensions\ms-toolsai.jupyter-2021.2.576440691\out\client\extension.js:47:250869)
    at a.get (c:\Users\...\.vscode\extensions\ms-toolsai.jupyter-2021.2.576440691\out\client\extension.js:49:886703)
    at c:\Users\...\.vscode\extensions\ms-toolsai.jupyter-2021.2.576440691\out\client\extension.js:47:244488
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at c:\Users\...\.vscode\extensions\ms-toolsai.jupyter-2021.2.576440691\out\client\extension.js:32:720131
    at t.activate (c:\Users\...\.vscode\extensions\ms-toolsai.jupyter-2021.2.576440691\out\client\extension.js:32:719841)
    at async Promise.all (index 2)
```

</p>
</details>

**Comment by takos22** [comment]
I updated my VSCode to 1.53.2 and it solved the issue.
