### ISSUE TITLE
Error in the notebooks when calling Jupyter.notebooks.save_checkpoint

### ISSUE THREAD

**Issue by ronglums** [microsoft/vscode-jupyter#4948]
On VS Code stable, webview notebooks.

 Example code here: https://github.com/microsoft/pybryt/blob/dev/pybryt/utils.py#L94
       display(Javascript("Jupyter.notebook.save_checkpoint();"))

Expected: no errors.
Actual: see the following error in VS Code notebooks. The notebooks checkpoint did save though. Same code doesn't result in an error in classic Jupyter.
    
ReferenceError: Jupyter is not defined
    at eval (eval at runCodeHere (vscode-webview-resource://7a10e355-6157-4ac7-93fc-596d1792100c/file///home/nirlevy/.vscode-server/extensions/ms-toolsai.jupyter-2021.2.576440691/out/datascience-ui/notebook/vendors~nteract_transforms.bundle.js:2:12595), <anonymous>:1:1)
    at runCodeHere (vscode-webview-resource://7a10e355-6157-4ac7-93fc-596d1792100c/file///home/nirlevy/.vscode-server/extensions/ms-toolsai.jupyter-2021.2.576440691/out/datascience-ui/notebook/vendors~nteract_transforms.bundle.js:2:12595)
    at t.value (vscode-webview-resource://7a10e355-6157-4ac7-93fc-596d1792100c/file///home/nirlevy/.vscode-server/extensions/ms-toolsai.jupyter-2021.2.576440691/out/datascience-ui/notebook/vendors~nteract_transforms.bundle.js:2:13027)
    at La (vscode-webview-resource://7a10e355-6157-4ac7-93fc-596d1792100c/file///home/nirlevy/.vscode-server/extensions/ms-toolsai.jupyter-2021.2.576440691/out/datascience-ui/notebook/commons.initial.bundle.js:2:2415259)
    at Pa (vscode-webview-resource://7a10e355-6157-4ac7-93fc-596d1792100c/file///home/nirlevy/.vscode-server/extensions/ms-toolsai.jupyter-2021.2.576440691/out/datascience-ui/notebook/commons.initial.bundle.js:2:2418181)
    at vscode-webview-resource://7a10e355-6157-4ac7-93fc-596d1792100c/file///home/nirlevy/.vscode-server/extensions/ms-toolsai.jupyter-2021.2.576440691/out/datascience-ui/notebook/commons.initial.bundle.js:2:2431259
    at Object.t.unstable_runWithPriority (vscode-webview-resource://7a10e355-6157-4ac7-93fc-596d1792100c/file///home/nirlevy/.vscode-server/extensions/ms-toolsai.jupyter-2021.2.576440691/out/datascience-ui/notebook/commons.initial.bundle.js:2:25134)
    at Ms (vscode-webview-resource://7a10e355-6157-4ac7-93fc-596d1792100c/file///home/nirlevy/.vscode-server/extensions/ms-toolsai.jupyter-2021.2.576440691/out/datascience-ui/notebook/commons.initial.bundle.js:2:2431193)
    at xs (vscode-webview-resource://7a10e355-6157-4ac7-93fc-596d1792100c/file///home/nirlevy/.vscode-server/extensions/ms-toolsai.jupyter-2021.2.576440691/out/datascience-ui/notebook/commons.initial.bundle.js:2:2430969)
    at Es (vscode-webview-resource://7a10e355-6157-4ac7-93fc-596d1792100c/file///home/nirlevy/.vscode-server/extensions/ms-toolsai.jupyter-2021.2.576440691/out/datascience-ui/notebook/commons.initial.bundle.js:2:2430314)

**Comment by DonJayamanne** [comment]
We don't support Jupyter extensions in VS Code. 
```display(Javascript("Jupyter.notebook.save_checkpoint();"))```
When this is run in Jupyter, their browser exposes a `Jupyter.notebook` object that interacts with the Jupyter editor. There's no such thing in VS Code, we dont support the Jupyter editor objectmodel or any of its API in the UI.

Also our Jupyter extension does not support checkpoints, hence not sure what we're after here.

Leaving for triage meeting to understand the requirements.

**Comment by DonJayamanne** [comment]
One solution is for us to create a global JS object that has the methods `Jupyter.notebook.save_checkpoint` which then invokes the save method of the document.
But this then leads to the assumption that VS Code notebooks supports all of the Jupyter Editor API, which I don't believe we want to support, where does this end?

On the flipside, this is a simple enough API to add, but checkpoints is not necessarily the same thing (Jupyter classic had checkpoint before Git integration in Jupyter, their way of keeping backups), I don't see the need for that in VS Code notebooks, Git works well enough and we have an awesome Notebook Diff tool as well.

Personally, I'd prefer not to support such work arounds/hacks. Lets discuss

**Comment by leestott** [comment]
@DonJayamanne thanks for the conversation so we will share the full example.
