### ISSUE TITLE
Mismatched vscode engine between vscode-pylance and vscode-jupyter

### ISSUE THREAD

**Issue by mlcdf** [microsoft/vscode-jupyter#4992]
Hello,

I have the following error when I try to install vscode-pylance on my machine (VS Code 1.53.2):

[2021-03-02 12:07:18.629] [renderer1] [error] ["Error: Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.53.2'.","    at [redacted]/.vscode-server/bin/622cb03f7e070a9670c94bae1a45d78d7181fbd4/out/vs/server/remoteExtensionHostAgent.js:107:91185","    at runMicrotasks (<anonymous>)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)"]

I think this is due to this commit : https://github.com/microsoft/vscode-jupyter/pull/4883/files

Workaround: I downgraded to vscode-jupyter to v2021.2.0 and vscode-pylance to v2021.2.3 and it works.

**Comment by DonJayamanne** [comment]
Thanks for filing this issue.
Did you attempt to install the pylance extension from the marketplace? or did you download the extensions.
Do you have the Python extension installed, & did you install that form the marketplace?

**Comment by zdog234** [comment]
I'm having the same issue trying to install from the marketplace (WSL 2 ubuntu 20.04)

**Comment by zdog234** [comment]
hmm,I have jupyter `2021.2.0` installed in windows and WSL, and pylance `2021.2.3` installed in windows, but when I try to "Install in WSL: Ubuntu-20.04", I'm getting `Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.53.2'.`

**Comment by DonJayamanne** [comment]
We're looking into this issue. 
# Temporary Work around
As a temporary work around, please download this Jupyter extension and install it https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-toolsai/vsextensions/jupyter/2021.2.603412351/vspackage

The link above is from the marketplace and points to a version thats compatible with the stable version of VS Code.

**Comment by DonJayamanne** [comment]
Issue moved to [microsoft/vscode #117986](https://github.com/microsoft/vscode/issues/117986) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jakebailey** [comment]
Are you sure that this isn't intended, as the insiders build says it needs 1.54.0-insiders, but their version of VS Code is the stable 1.53?

**Comment by DonJayamanne** [comment]
Re-opening this issue to track upstream issues.

**Comment by DonJayamanne** [comment]
Re-opening this issue to track upstream issues.

**Comment by zdog234** [comment]
@DonJayamanne fwiw, I am impressed that the  pylance / jupyter extensions caused this problem -- publishing an extension release based on a beta version of vscode is the kind of agile development I want my team to get to 😂

**Comment by jakebailey** [comment]
Pylance doesn't use any insiders features and only declares 1.51 as the minimum version; I'm pretty sure it's only involved thanks to some weird quirk/bug in VS Code where some installations check versions while some do not

**Comment by DonJayamanne** [comment]
Closing as upstream issue has been closed
