### ISSUE TITLE
ms-toolsai.jupyter fails to load and breaks entire python support in latest VSCode

### ISSUE THREAD

**Issue by PALuczak** [microsoft/vscode-jupyter#5032]
## Environment data

-   VS Code version: 1.54.0
-   Jupyter Extension version: v2021.3.619093157
-   Python Extension version: v2021.2.582707922
-   OS : Windows 10 20H2 19042.844
-   Python and/or Anaconda version: 3.8
-   Type of virtual environment used: conda
-   Jupyter server running: N/A

## Expected behaviour

Extensions load correctly (as they did in the previous version of VS Code).

## Actual behaviour

The extension fails to load and breaks the entire Python support.

## Steps to reproduce:

1. Update VSCode to 1.54.0
2. Open any .py file

## Available workaround:

Downgrade `ms-toolsai.jupyter` to v2020.12.414227025.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel 
</summary>

<p>

```
User belongs to experiment group 'pythonJoinMailingListVar3'
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'NativeNotebookEditor'
Error 2021-03-04 20:26:05: extension activation failed [Error: [ms-toolsai.jupyter]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api ms-toolsai.jupyter
	at f (c:\Users\pluczak\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:74959)
	at Object.p [as checkProposedApiEnabled] (c:\Users\pluczak\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:74906)
	at Object.onDidChangeCellLanguage (c:\Users\pluczak\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:40827)
	at u.addEventHandlers (c:\Users\pluczak\.vscode\extensions\ms-toolsai.jupyter-2021.3.619093157\out\client\extension.js:47:539257)
	at new u (c:\Users\pluczak\.vscode\extensions\ms-toolsai.jupyter-2021.3.619093157\out\client\extension.js:47:537528)
	at Object.t.resolveInstance (c:\Users\pluczak\.vscode\extensions\ms-toolsai.jupyter-2021.3.619093157\out\client\extension.js:47:238237)
	at c:\Users\pluczak\.vscode\extensions\ms-toolsai.jupyter-2021.3.619093157\out\client\extension.js:47:237443
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (c:\Users\pluczak\.vscode\extensions\ms-toolsai.jupyter-2021.3.619093157\out\client\extension.js:47:238007)
	at c:\Users\pluczak\.vscode\extensions\ms-toolsai.jupyter-2021.3.619093157\out\client\extension.js:47:237443
	at c:\Users\pluczak\.vscode\extensions\ms-toolsai.jupyter-2021.3.619093157\out\client\extension.js:47:236391
	at Array.map (<anonymous>)
	at c:\Users\pluczak\.vscode\extensions\ms-toolsai.jupyter-2021.3.619093157\out\client\extension.js:47:236363
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (c:\Users\pluczak\.vscode\extensions\ms-toolsai.jupyter-2021.3.619093157\out\client\extension.js:47:238007)
	at c:\Users\pluczak\.vscode\extensions\ms-toolsai.jupyter-2021.3.619093157\out\client\extension.js:47:237443
	at Object.t.resolve (c:\Users\pluczak\.vscode\extensions\ms-toolsai.jupyter-2021.3.619093157\out\client\extension.js:47:237706)
	at c:\Users\pluczak\.vscode\extensions\ms-toolsai.jupyter-2021.3.619093157\out\client\extension.js:47:228807
	at e._get (c:\Users\pluczak\.vscode\extensions\ms-toolsai.jupyter-2021.3.619093157\out\client\extension.js:47:228573)
	at e.get (c:\Users\pluczak\.vscode\extensions\ms-toolsai.jupyter-2021.3.619093157\out\client\extension.js:47:227285)
	at a.get (c:\Users\pluczak\.vscode\extensions\ms-toolsai.jupyter-2021.3.619093157\out\client\extension.js:49:886141)
	at c:\Users\pluczak\.vscode\extensions\ms-toolsai.jupyter-2021.3.619093157\out\client\extension.js:47:271313
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async c:\Users\pluczak\.vscode\extensions\ms-toolsai.jupyter-2021.3.619093157\out\client\extension.js:32:724727
	at async t.activate (c:\Users\pluczak\.vscode\extensions\ms-toolsai.jupyter-2021.3.619093157\out\client\extension.js:32:724437)
	at async Promise.all (index 0)]
```

</p>
</details>

**Comment by masaki9** [comment]
I think this is the same as https://github.com/microsoft/vscode/issues/118126 . The issue disappeared after I installed version 2021.3.593162453 and then reinstalled the latest version (2021.3.619093157) for some reason.

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, we are aware of this. Unfortunately this is an upstream issue and VS Code will be fixing this soon.
Here's the upstream VS Code issue https://github.com/microsoft/vscode/issues/118124
