### ISSUE TITLE
Conda environment names are shown as 'Python 3' in the list of Jupyter kernels.

### ISSUE THREAD

**Issue by masaki9** [microsoft/vscode-jupyter#5043]
## Environment data

-   VS Code version: 1.54.1 (Universal)
-   Jupyter Extension version (available under the Extensions sidebar): v2021.3.619093157
-   Python Extension version (available under the Extensions sidebar): v2021.2.582707922
-   OS (Windows | Mac | Linux distro) and version: macOS 11.2.2
-   Python and/or Anaconda version: Python 3.x (I replicated this issue with 3.7.10, 3.8.8, and 3.9.1.) Conda 4.9.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

I expect conda environment names to be properly displayed in the list of Jupyter kernels. As shown in the image below, the list of Python interpreters shows conda environment names properly. I expect something similar in the list of Jupyter kernels as well. 

![image](https://user-images.githubusercontent.com/40445257/110064881-d290d800-7d22-11eb-8521-33ac5b0897f7.png)

## Actual behaviour

Conda environment names are listed as 'Python 3' in the list of Jupyter kernels. In the image below, 'Python 3' should be displayed as Python 3.8.5 64 bit ('geopandas': conda).
![image](https://user-images.githubusercontent.com/40445257/110065064-37e4c900-7d23-11eb-920e-5b078de6f844.png)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Open Terminal. 
2. Create a new conda environment and install Python 3.x (e.g. 3.8) and ipykernel in the new environment. For example, you can run the following in Terminal:
```
conda create -n test1234 python=3.8
conda activate test1234
conda install ipykernel
```
3. Close Visual Studio Code if it is currently open.
4. Open Visual Studio Code.
5. Open a Python file in Visual Studio Code.
6. Right-click in the opened file to bring up the context menu and click "Run Current File in Interactive Window".
7. In the Jupyter interactive window, click on the current kernel label located at the top right next to 'Jupiter Server:local', to bring up the kernel list.
![image](https://user-images.githubusercontent.com/40445257/110065865-0a008400-7d25-11eb-9c39-31d5fde17adf.png)

8. Find the new Conda environment that you created earlier (e.g. test1234) in the list. You will see that it is listed as 'Python 3' instead of Python 3.8.8 64 bit ('test1234': conda).
![image](https://user-images.githubusercontent.com/40445257/110066132-9e6ae680-7d25-11eb-88d0-faa89cf6a1d7.png)

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
User belongs to experiment group 'jupyterTest'
Error 2021-03-04 20:32:15: Exception while attempting zmq : [Error: No native build was found for platform=darwin arch=arm64 runtime=electron abi=85 uv=1 armv=8 libc=glibc
	at Function.load.path (/Users/masaki/.vscode/extensions/ms-toolsai.jupyter-2021.3.619093157/out/client/node_modules/node-gyp-build/index.js:56:9)
	at load (/Users/masaki/.vscode/extensions/ms-toolsai.jupyter-2021.3.619093157/out/client/node_modules/node-gyp-build/index.js:21:30)
	at Object.<anonymous> (/Users/masaki/.vscode/extensions/ms-toolsai.jupyter-2021.3.619093157/out/client/node_modules/zeromq/lib/native.js:6:43)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:3:12841)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
	at Module.load (internal/modules/cjs/loader.js:1039:32)
	at Module._load (internal/modules/cjs/loader.js:932:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.s._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:27167)
	at Function._._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:23919)
	at Function.W._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:96:4637)
	at Module.require (internal/modules/cjs/loader.js:1079:19)
	at v (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:3:12287)
	at Object.<anonymous> (/Users/masaki/.vscode/extensions/ms-toolsai.jupyter-2021.3.619093157/out/client/node_modules/zeromq/lib/index.js:3:16)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:3:12841)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
	at Module.load (internal/modules/cjs/loader.js:1039:32)
	at Module._load (internal/modules/cjs/loader.js:932:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.s._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:27167)
	at Function._._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:23919)
	at Function.W._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:96:4637)
	at Module.require (internal/modules/cjs/loader.js:1079:19)
	at v (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:3:12287)
	at Object.<anonymous> (/Users/masaki/.vscode/extensions/ms-toolsai.jupyter-2021.3.619093157/out/client/extension.js:32:283721)
	at n (/Users/masaki/.vscode/extensions/ms-toolsai.jupyter-2021.3.619093157/out/client/extension.js:1:186)
	at d.zmqSupported (/Users/masaki/.vscode/extensions/ms-toolsai.jupyter-2021.3.619093157/out/client/extension.js:49:826984)
	at d.isSupportedForLocalLaunch (/Users/masaki/.vscode/extensions/ms-toolsai.jupyter-2021.3.619093157/out/client/extension.js:49:826634)
	at d.supported (/Users/masaki/.vscode/extensions/ms-toolsai.jupyter-2021.3.619093157/out/client/extension.js:49:826544)
	at Object.t.registerTypes (/Users/masaki/.vscode/extensions/ms-toolsai.jupyter-2021.3.619093157/out/client/extension.js:47:736520)
	at /Users/masaki/.vscode/extensions/ms-toolsai.jupyter-2021.3.619093157/out/client/extension.js:47:271156
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async /Users/masaki/.vscode/extensions/ms-toolsai.jupyter-2021.3.619093157/out/client/extension.js:32:724727
	at async t.activate (/Users/masaki/.vscode/extensions/ms-toolsai.jupyter-2021.3.619093157/out/client/extension.js:32:724437)
	at async Promise.all (index 0)]
> ~/opt/miniconda3/envs/geopandas/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.619093157/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> ~/opt/miniconda3/envs/geopandas/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.619093157/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> ~/miniforge3/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.619093157/pythonFiles/pyvsc-run-isolated.py pip list
> ~/opt/miniconda3/envs/geopandas/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.619093157/pythonFiles/pyvsc-run-isolated.py jupyter kernelspec --version
Starting Jupyter from ~/opt/miniconda3/envs/geopandas/bin/python with command line --no-browser --notebook-dir="/Users/masaki/Desktop/Temp/Test" --config=/var/folders/m7/p28y6lqj3s598ws5_pwt0lxw0000gn/T/cbb8a241-139d-4f93-b799-a07058a42894/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
> ~/opt/miniconda3/envs/geopandas/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.619093157/pythonFiles/pyvsc-run-isolated.py pip list
> ~/opt/miniconda3/envs/geopandas/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.619093157/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> ~/opt/miniconda3/envs/geopandas/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.619093157/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> ~/opt/miniconda3/envs/geopandas/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.619093157/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> ~/opt/miniconda3/envs/geopandas/bin/python (daemon) -m jupyter notebook --no-browser --notebook-dir="/Users/masaki/Desktop/Temp/Test" --config=/var/folders/m7/p28y6lqj3s598ws5_pwt0lxw0000gn/T/cbb8a241-139d-4f93-b799-a07058a42894/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
/Users/masaki/opt/miniconda3/envs/geopandas/lib/python3.8/site-packages/traitlets/traitlets.py:2196: FutureWarning: Supporting extra quotes around Unicode is deprecated in traitlets 5.0. Use '/Users/masaki/Desktop/Temp/Test' instead of '"/Users/masaki/Desktop/Temp/Test"' – or use CUnicode.
  warn(
[W 2021-03-04 20:33:44.682 LabApp] 'notebook_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-03-04 20:33:44.682 LabApp] 'config_file' was found in both NotebookApp and ServerApp. This is likely a recent change. This config will only be set in NotebookApp. Please check if you should also config these traits in ServerApp for your purpose.
[W 2021-03-04 20:33:44.682 LabApp] 'iopub_data_rate_limit' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-03-04 20:33:44.682 LabApp] 'iopub_data_rate_limit' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-03-04 20:33:44.682 LabApp] 'iopub_data_rate_limit' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2021-03-04 20:33:44.689 LabApp] JupyterLab extension loaded from /Users/masaki/opt/miniconda3/envs/geopandas/lib/python3.8/site-packages/jupyterlab
[I 2021-03-04 20:33:44.689 LabApp] JupyterLab application directory is /Users/masaki/opt/miniconda3/envs/geopandas/share/jupyter/lab
[I 20:33:44.692 NotebookApp] Serving notebooks from local directory: /Users/masaki/Desktop/Temp/Test
[I 20:33:44.692 NotebookApp] Jupyter Notebook 6.2.0 is running at:
[I 20:33:44.692 NotebookApp] http://localhost:8888/?token=e0fff4a3de75e05acd4149089c40389e6d56ae73386e36c2
> ~/opt/miniconda3/envs/geopandas/bin/python (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.619093157/pythonFiles/vscode_datascience_helpers/getServerInfo.py
[I 20:33:44.692 NotebookApp]  or http://127.0.0.1:8888/?token=e0fff4a3de75e05acd4149089c40389e6d56ae73386e36c2
> ~/opt/miniconda3/envs/geopandas/bin/python (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.619093157/pythonFiles/vscode_datascience_helpers/getServerInfo.py
[I 20:33:44.692 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 20:33:44.695 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/masaki/Library/Jupyter/runtime/nbserver-3388-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=e0fff4a3de75e05acd4149089c40389e6d56ae73386e36c2
     or http://127.0.0.1:8888/?token=e0fff4a3de75e05acd4149089c40389e6d56ae73386e36c2
[I 20:33:44.889 NotebookApp] Creating new notebook in /
> ~/opt/miniconda3/envs/geopandas/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.619093157/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/opt/miniconda3/envs/geopandas/bin/python (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.619093157/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> ~/opt/miniconda3/envs/geopandas/bin/python (daemon) ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.619093157/pythonFiles/vscode_datascience_helpers/getServerInfo.py
[I 20:33:45.219 NotebookApp] Kernel started: 9a38e423-d30f-43b3-ab92-5412d5cd73ad, name: python3
[W 20:33:45.225 NotebookApp] delete /t-0d43c87e-c789-4cef-a8ad-0aab1658446a.ipynb
[I 20:33:45.753 NotebookApp] Creating new notebook in /
> ~/opt/miniconda3/envs/geopandas/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2021.3.619093157/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
[I 20:33:46.079 NotebookApp] Kernel started: 757d8d68-a8bd-4f4e-86e4-5504f1c5d4fa, name: python3
[W 20:33:46.084 NotebookApp] delete /t-eff0ff72-0ddd-4c26-b974-9b6447f21f52.ipynb
```

</p>
</details>

**Comment by DonJayamanne** [comment]
Thanks for filing this issue please could you:

**Please could you enable logging as follows:**
* Open settings & go into `Jupyter->Logging`
* Open settings & go into `Python->Logging`
* Change the value to `debug`
* Reload VS Code,
* Attempt to repro the issue
* then copy the output from the `Jupyter` output panel.
* then copy the output from the `Python` output panel.

**Comment by DonJayamanne** [comment]
@masaki9
I believe the issue has been resolved.
* Please could  you install VS Code Insiders
* Download this build of the extesnion (this is our latest dev version), https://github.com/microsoft/vscode-jupyter/suites/2219486133/artifacts/45955787
* Go into the command palette and select install from VSIX (select this VSIX file you have downloaded)
* You might be asked to re-load VSCode, please
* Please ensure you have the latest version of the Python extension as well

Test and let us know if this works.
FYI - In VS Code Insiders, we have a new Notebook UI you can read more about that here
* See here for more information https://devblogs.microsoft.com/python/notebooks-are-getting-revamped/

**Comment by masaki9** [comment]
@DonJayamanne 

Thanks a lot for the fix. It works!

I tested it with Version: 1.55.0-insider (Universal) (Date: 2021-03-10T22:27:59.416Z) and Python Extension v2021.2.636928669.

**Comment by DonJayamanne** [comment]
Thanks for getting back to us and for being patient.
