### ISSUE TITLE
Unexpected token ' in JSON at position 0

### ISSUE THREAD

**Issue by leehbi** [microsoft/vscode-jupyter#5065]
## Environment data

-   VS Code version: 1.54.1
-   Jupyter Extension version (available under the Extensions sidebar): v2021.3.619093157
-   Python Extension version (available under the Extensions sidebar): v2021.2.625869727
-   OS (Windows | Mac | Linux distro) and version: Windows 10 20H2 19042.804
-   Python and/or Anaconda version: 3.9.1 Conda 4.9.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Conda
-   Jupyter server running: Local 

## Expected behaviour

Expect code to be run in interactive window when pressing control+enter

## Actual behaviour

VS code tries to open the interactive window but it closes immediately with the error bar : Unexpected token ' in JSON at position 0

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Enter some python code in the main window - press control+enter to run in the interactive window
or  Jupyer : Create new blank notebook gives the same error

## Logs

<details>
> ~\.conda\envs\py39\python.exe c:\Users\lee_h\.vscode\extensions\ms-toolsai.jupyter-2021.3.619093157\pythonFiles\pyvsc-run-isolated.py c:\Users\lee_h\.vscode\extensions\ms-toolsai.jupyter-2021.3.619093157\pythonFiles\normalizeForInterpreter.py print("Hello")
Error 2021-03-07 17:48:22: Install Missing Dependencies, Class name = g, completed in 3456ms, has a falsy return value, Return Value: undefined [SyntaxError: Unexpected token ' in JSON at position 0
	at JSON.parse (<anonymous>)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:9:100995
	at P.parseEnvironmentOutput (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:59:590369)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68457
	at Object.t.tracing (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:54321)
	at P.r.value (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68433)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68457
	at Object.t.tracing (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:54321)
	at P.r.value (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68433)
	at P.getActivatedEnvironmentVariablesImpl (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:59:589629)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)]
Error 2021-03-07 17:48:22: Find kernel spec, Class name = O, completed in 3587ms, has a falsy return value, Arg 1: <Uri:c:\Users\lee_h\Downloads\Test.py>, Arg 2: undefined, Arg 3: undefined, Arg 4: undefined, Return Value: undefined [SyntaxError: Unexpected token ' in JSON at position 0
	at JSON.parse (<anonymous>)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:9:100995
	at P.parseEnvironmentOutput (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:59:590369)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68457
	at Object.t.tracing (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:54321)
	at P.r.value (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68433)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68457
	at Object.t.tracing (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:54321)
	at P.r.value (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68433)
	at P.getActivatedEnvironmentVariablesImpl (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:59:589629)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)]
Error 2021-03-07 17:48:22: Get preferred local kernel connection, Class name = O, completed in 3588ms, has a falsy return value [SyntaxError: Unexpected token ' in JSON at position 0
	at JSON.parse (<anonymous>)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:9:100995
	at P.parseEnvironmentOutput (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:59:590369)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68457
	at Object.t.tracing (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:54321)
	at P.r.value (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68433)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68457
	at Object.t.tracing (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:54321)
	at P.r.value (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68433)
	at P.getActivatedEnvironmentVariablesImpl (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:59:589629)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)]
Error 2021-03-07 17:48:22: Exception attempting to start notebook:  [SyntaxError: Unexpected token ' in JSON at position 0
	at JSON.parse (<anonymous>)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:9:100995
	at P.parseEnvironmentOutput (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:59:590369)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68457
	at Object.t.tracing (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:54321)
	at P.r.value (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68433)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68457
	at Object.t.tracing (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:54321)
	at P.r.value (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68433)
	at P.getActivatedEnvironmentVariablesImpl (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:59:589629)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)]
Error 2021-03-07 17:48:22: DataScience Error [SyntaxError: Unexpected token ' in JSON at position 0
	at JSON.parse (<anonymous>)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:9:100995
	at P.parseEnvironmentOutput (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:59:590369)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68457
	at Object.t.tracing (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:54321)
	at P.r.value (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68433)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68457
	at Object.t.tracing (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:54321)
	at P.r.value (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68433)
	at P.getActivatedEnvironmentVariablesImpl (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:59:589629)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)]
Error 2021-03-07 17:48:22: Failed to initialize ipywidgetHandler [SyntaxError: Unexpected token ' in JSON at position 0
	at JSON.parse (<anonymous>)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:9:100995
	at P.parseEnvironmentOutput (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:59:590369)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68457
	at Object.t.tracing (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:54321)
	at P.r.value (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68433)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68457
	at Object.t.tracing (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:54321)
	at P.r.value (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68433)
	at P.getActivatedEnvironmentVariablesImpl (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:59:589629)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)]
Error 2021-03-07 17:48:22: DataScience Error [SyntaxError: Unexpected token ' in JSON at position 0
	at JSON.parse (<anonymous>)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:9:100995
	at P.parseEnvironmentOutput (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:59:590369)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68457
	at Object.t.tracing (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:54321)
	at P.r.value (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68433)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68457
	at Object.t.tracing (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:54321)
	at P.r.value (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68433)
	at P.getActivatedEnvironmentVariablesImpl (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:59:589629)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)]
Error 2021-03-07 17:48:23: Install Missing Dependencies, Class name = g, completed in 1031ms, has a falsy return value, Return Value: undefined [SyntaxError: Unexpected token ' in JSON at position 0
	at JSON.parse (<anonymous>)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:9:100995
	at P.parseEnvironmentOutput (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:59:590369)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68457
	at Object.t.tracing (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:54321)
	at P.r.value (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68433)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68457
	at Object.t.tracing (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:54321)
	at P.r.value (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68433)
	at P.getActivatedEnvironmentVariablesImpl (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:59:589629)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)]
Error 2021-03-07 17:48:23: Find kernel spec, Class name = O, completed in 1148ms, has a falsy return value, Arg 1: <Uri:c:\Users\lee_h\Downloads\Test.py>, Arg 2: undefined, Arg 3: undefined, Arg 4: undefined, Return Value: undefined [SyntaxError: Unexpected token ' in JSON at position 0
	at JSON.parse (<anonymous>)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:9:100995
	at P.parseEnvironmentOutput (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:59:590369)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68457
	at Object.t.tracing (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:54321)
	at P.r.value (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68433)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68457
	at Object.t.tracing (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:54321)
	at P.r.value (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68433)
	at P.getActivatedEnvironmentVariablesImpl (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:59:589629)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)]
Error 2021-03-07 17:48:23: Get preferred local kernel connection, Class name = O, completed in 1151ms, has a falsy return value [SyntaxError: Unexpected token ' in JSON at position 0
	at JSON.parse (<anonymous>)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:9:100995
	at P.parseEnvironmentOutput (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:59:590369)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68457
	at Object.t.tracing (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:54321)
	at P.r.value (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68433)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68457
	at Object.t.tracing (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:54321)
	at P.r.value (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68433)
	at P.getActivatedEnvironmentVariablesImpl (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:59:589629)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)]
Error 2021-03-07 17:48:23: Exception attempting to start notebook:  [SyntaxError: Unexpected token ' in JSON at position 0
	at JSON.parse (<anonymous>)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:9:100995
	at P.parseEnvironmentOutput (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:59:590369)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68457
	at Object.t.tracing (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:54321)
	at P.r.value (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68433)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68457
	at Object.t.tracing (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:54321)
	at P.r.value (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68433)
	at P.getActivatedEnvironmentVariablesImpl (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:59:589629)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)]
Error 2021-03-07 17:48:23: DataScience Error [SyntaxError: Unexpected token ' in JSON at position 0
	at JSON.parse (<anonymous>)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:9:100995
	at P.parseEnvironmentOutput (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:59:590369)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68457
	at Object.t.tracing (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:54321)
	at P.r.value (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68433)
	at c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68457
	at Object.t.tracing (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:54321)
	at P.r.value (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:1:68433)
	at P.getActivatedEnvironmentVariablesImpl (c:\Users\lee_h\.vscode\extensions\ms-python.python-2021.2.625869727\out\client\extension.js:59:589629)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)]
<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by leehbi** [comment]
Note, when I disabled Python : Use Isolation and restarted VS Code the problem went away.
