### ISSUE TITLE
Not able to install jupyter extension ["Error: Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.54.1'.","   

### ISSUE THREAD

**Issue by tkarth** [microsoft/vscode-jupyter#5104]
## Environment data

-   VS Code version: 1.54.1
-   Jupyter Extension version (available under the Extensions sidebar): v2021.4.625511240
-   Python Extension version (available under the Extensions sidebar): v2021.2.636928669
-   OS (Windows | Mac | Linux distro) and version: Windows  in WSL: Ubuntu 18,04

## Expected behaviour

extension is installed without problems

## Actual behaviour

[2021-03-10 08:44:09.778] [renderer1] [info] Trying to download 'ms-toolsai.jupyter' extension locally and install
[2021-03-10 08:44:14.467] [renderer1] [error] ["Error: Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.54.1'.","    at /home/XXXXX/.vscode-server/bin/f30a9b73e8ffc278e71575118b6bf568f04587c8/out/vs/server/remoteExtensionHostAgent.js:108:97446","    at runMicrotasks (<anonymous>)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)"]
[2021-03-10 08:44:14.522] [renderer1] [error] ["Error: getaddrinfo ENOTFOUND marketplace.visualstudio.com","    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)"]
[2021-03-10 08:44:14.593] [renderer1] [error] getaddrinfo ENOTFOUND marketplace.visualstudio.com: Error: getaddrinfo ENOTFOUND marketplace.visualstudio.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
[2021-03-10 08:54:24.725] [renderer1] [warning] Settings pattern "keyboard.*" doesn't match any settings

## Steps to reproduce:
try to install the extension on VS Code 1.54.1

**Comment by rchiodo** [comment]
We have multiple versions of the extension in the marketplace, each targeting different versions of VS code. The one you should use is this one:

![image](https://user-images.githubusercontent.com/19672699/110696114-879e1700-819f-11eb-8fc1-4bfe83b8e029.png)

The VS code extensions panel will find the latest one that works with your version of VS code. We recommend installing it from there.
