### ISSUE TITLE
Jupyter extension is not activating on codespaces

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-jupyter#5114]
## Environment data

-   VS Code version: Codespaces on the browser, using VS Code 1.55.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): 2021.4.625511240
-   Python Extension version (available under the Extensions sidebar): 2021.2.636928669
-   OS (Windows | Mac | Linux distro) and version: Windows 10

## Expected behaviour

When I open a Python file on codespaces, the Python extension activates

## Actual behaviour

The Python extension isn't activated when opening a Python file on codespaces. 

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Start a codespace out of https://github.com/Microsoft/python-sample-tweeterapp/. **Make sure to select the fixwarnings branch**, not the main one. 

2.  Open a Python file 
3. See the notification error that the Jupyter extension failed to activate. 

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'pythonDiscoveryModule'
User belongs to experiment group 'NativeNotebookEditor'
Error 2021-03-11 02:02:10: extension activation failed TypeError: s.notebook.onDidChangeCellLanguage is not a function
    at u.addEventHandlers (/root/.vscode-remote/extensions/ms-toolsai.jupyter-2021.4.625511240/out/client/extension.js:47:539381)
    at new u (/root/.vscode-remote/extensions/ms-toolsai.jupyter-2021.4.625511240/out/client/extension.js:47:537652)
    at Object.t.resolveInstance (/root/.vscode-remote/extensions/ms-toolsai.jupyter-2021.4.625511240/out/client/extension.js:47:238266)
    at /root/.vscode-remote/extensions/ms-toolsai.jupyter-2021.4.625511240/out/client/extension.js:47:237471
    at Array.map (<anonymous>)
    at Object.t.resolveInstance (/root/.vscode-remote/extensions/ms-toolsai.jupyter-2021.4.625511240/out/client/extension.js:47:238036)
    at /root/.vscode-remote/extensions/ms-toolsai.jupyter-2021.4.625511240/out/client/extension.js:47:237471
    at /root/.vscode-remote/extensions/ms-toolsai.jupyter-2021.4.625511240/out/client/extension.js:47:236419
    at Array.map (<anonymous>)
    at /root/.vscode-remote/extensions/ms-toolsai.jupyter-2021.4.625511240/out/client/extension.js:47:236391
    at Array.map (<anonymous>)
    at Object.t.resolveInstance (/root/.vscode-remote/extensions/ms-toolsai.jupyter-2021.4.625511240/out/client/extension.js:47:238036)
    at /root/.vscode-remote/extensions/ms-toolsai.jupyter-2021.4.625511240/out/client/extension.js:47:237471
    at Object.t.resolve (/root/.vscode-remote/extensions/ms-toolsai.jupyter-2021.4.625511240/out/client/extension.js:47:237734)
    at /root/.vscode-remote/extensions/ms-toolsai.jupyter-2021.4.625511240/out/client/extension.js:47:228831
    at e._get (/root/.vscode-remote/extensions/ms-toolsai.jupyter-2021.4.625511240/out/client/extension.js:47:228597)
    at e.get (/root/.vscode-remote/extensions/ms-toolsai.jupyter-2021.4.625511240/out/client/extension.js:47:227309)
    at a.get (/root/.vscode-remote/extensions/ms-toolsai.jupyter-2021.4.625511240/out/client/extension.js:49:886292)
    at /root/.vscode-remote/extensions/ms-toolsai.jupyter-2021.4.625511240/out/client/extension.js:47:271364
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at /root/.vscode-remote/extensions/ms-toolsai.jupyter-2021.4.625511240/out/client/extension.js:32:727156
    at t.activate (/root/.vscode-remote/extensions/ms-toolsai.jupyter-2021.4.625511240/out/client/extension.js:32:726866)
    at async Promise.all (index 0)

```

</p>
</details>

**Comment by luabud** [comment]
Opting out of the native notebooks experiment makes activation work.

**Comment by DonJayamanne** [comment]
Fixed, please re-try.

**Comment by luabud** [comment]
It worked! Thank you 😊
