### ISSUE TITLE
Getting message IPyKernel not installed when it is

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5335]
## Environment data

-   VS Code version: XXX
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A

From @GuillaumeDesforges

In my case, I'm in a workspace. Log is

```
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'pythonDiscoveryModule'
User belongs to experiment group 'pythonFindInterpreter'
User belongs to experiment group 'NativeNotebookEditor'
> ~/mycompany/mycompany-audit/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.5.689556049/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/mycompany/company-cli/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.5.689556049/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/mycompany/tap-shopify/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.5.689556049/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/mycompany/company-connectors/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.5.689556049/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/mycompany/etl-legacy/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.5.689556049/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/mycompany/company-extractors/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.5.689556049/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/mycompany/tap-sklik/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.5.689556049/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/mycompany/etl/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.5.689556049/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/mycompany/etl/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.5.689556049/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/mycompany/etl/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.5.689556049/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/mycompany/etl/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.5.689556049/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/mycompany/etl/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.5.689556049/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/mycompany/etl/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.5.689556049/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/mycompany/etl/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.5.689556049/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/mycompany/etl/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.5.689556049/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/mycompany/etl/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.5.689556049/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/mycompany/etl/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.5.689556049/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/mycompany/etl/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.5.689556049/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/mycompany/mycompany-audit/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.5.689556049/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/mycompany/mycompany-audit/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.5.689556049/pythonFiles/pyvsc-run-isolated.py pip list
> ~/mycompany/etl/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.5.689556049/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
Error 2021-03-26 15:24:03: Install Missing Dependencies, Class name = v, completed in 36248ms, has a falsy return value, Return Value: undefined [a [Error]: IPyKernel not installed into interpreter Python 3.8.7  ('.venv': venv):/home/user/mycompany/mycompany-audit/.venv/bin/python
	at v.installMissingDependencies (/home/user/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.5.689556049/out/client/extension.js:49:560244)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)] {
  category: 'noipykernel',
  reason: 2
}
Error 2021-03-26 15:24:03: Raw session failed to start because dependencies not installed
Error 2021-03-26 15:24:03: Exception attempting to start notebook:  [a [Error]: IPyKernel not installed into interpreter Python 3.8.7  ('.venv': venv):/home/user/mycompany/mycompany-audit/.venv/bin/python
	at v.installMissingDependencies (/home/user/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.5.689556049/out/client/extension.js:49:560244)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)] {
  category: 'noipykernel',
  reason: 2
}
Error 2021-03-26 15:24:03: DataScience Error [a [Error]: IPyKernel not installed into interpreter Python 3.8.7  ('.venv': venv):/home/user/mycompany/mycompany-audit/.venv/bin/python
	at v.installMissingDependencies (/home/user/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.5.689556049/out/client/extension.js:49:560244)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)] {
  category: 'noipykernel',
  reason: 2
}
Error 2021-03-26 15:24:03: DataScience Error [a [Error]: IPyKernel not installed into interpreter Python 3.8.7  ('.venv': venv):/home/user/mycompany/mycompany-audit/.venv/bin/python
	at v.installMissingDependencies (/home/user/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.5.689556049/out/client/extension.js:49:560244)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)] {
  category: 'noipykernel',
  reason: 2
}
Error 2021-03-26 15:24:03: Failed to initialize ipywidgetHandler [a [Error]: IPyKernel not installed into interpreter Python 3.8.7  ('.venv': venv):/home/user/mycompany/mycompany-audit/.venv/bin/python
	at v.installMissingDependencies (/home/user/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.5.689556049/out/client/extension.js:49:560244)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)] {
  category: 'noipykernel',
  reason: 2
}
Error 2021-03-26 15:24:03: DataScience Error [a [Error]: IPyKernel not installed into interpreter Python 3.8.7  ('.venv': venv):/home/user/mycompany/mycompany-audit/.venv/bin/python
	at v.installMissingDependencies (/home/user/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.5.689556049/out/client/extension.js:49:560244)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)] {
  category: 'noipykernel',
  reason: 2
}
```

Even though I have
```
[user@laptop:~/mycompany/mycompany-audit]$ .venv/bin/python -m pip list | grep ipykernel
ipykernel                5.5.0
```

**Comment by DonJayamanne** [comment]
From @GuillaumeDesforges

Hi @DonJayamanne thanks for your help

I am trying to work with items in `~/mycompany/mycompany-audit/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.5.689556049/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"`, not 'etl'.

The command 

```
~/mycompany/mycompany-audit/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.5.689556049/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
```

outputs nothing, then

```
~/mycompany/mycompany-audit/.venv/bin/python -c "import ipykernel"
```

outputs nothing as well.

However, doing

```
~/mycompany/etl/.venv/bin/python ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.5.689556049/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
```

gives the expected error

```
Traceback (most recent call last):
  File "/home/arsleust/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2021.5.689556049/pythonFiles/pyvsc-run- 
isolated.py", line 26, in <module>
    exec(code, ns, ns)
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'ipykernel'
```

**Comment by DonJayamanne** [comment]
From @GuillaumeDesforges

Please note that I have a bit of a weird environment. I work with remote SSH and have LD_LIBRARY_PATH set in my .profile, so I had to set in settings
```
  "terminal.integrated.shellArgs.linux": [
    "-l"
  ]
```

**Comment by DonJayamanne** [comment]
@GuillaumeDesforges

Thanks for providing the information you have. If you enable logging as mentioned below, I'll have fewer questions for your.

1. Please could you enable logging as follows:
	* Open settings & go into `Jupyter->Logging`
	* Change the value to `debug`
	* Reload VS Code,
	* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

1. Please could you provide the following information:
	* Python Extension version (available under the Extensions sidebar): XXX
	* OS (Windows | Mac | Linux distro) and version: XXX
	* Python and/or Anaconda version: XXX

I'd like to get to the bottom of this and get you ublocked.
Also we know a number of our users are having this same issue,

Thanks for your patience, & I'm certain we can get this fixed.

**Comment by GuillaumeDesforges** [comment]
Works now

VS Code
```
Version: 1.56.0-insider (system setup)
Commit: 550035808407c15252e581e8abe1b820b9d311ee
Date: 2021-04-02T05:15:44.248Z
Electron: 11.4.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
```

python extension
```
v2021.5.731969028-dev
```

pylance
```
v2021.4.0
```
