### ISSUE TITLE
VSCode note recognising conda environment and not running the cells

### ISSUE THREAD

**Issue by Flock1** [microsoft/vscode-jupyter#5390]
## Environment data

-   VS Code version: 1.54.3
-   Jupyter Extension version (available under the Extensions sidebar): v2021.3.684299474
-   Python Extension version (available under the Extensions sidebar): v2021.3.680753044
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 20.04
-   Python and/or Anaconda version: 3.8.3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Conda
-   Jupyter server running: Local

## Expected behaviour

Should work fine with the conda environment

## Actual behaviour

1) VSCode is not recognising the environment
2) Not running the cells. I get an error at the bottom right `invalid version - final` and it's getting from jupyter extension. 

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Install the python and jupyter extensions

## Logs

This is what I get in the `output` channel for `Python`:
```
Error 2021-04-02 10:12:01: Failed to parse version from path: /home/sarvagya/anaconda3/bin/python [Error: invalid version python
	at u (/home/sarvagya/.vscode/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:198256)
	at Object.c [as parseVersion] (/home/sarvagya/.vscode/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:197565)
	at p.buildPathEnvInfo (/home/sarvagya/.vscode/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29369)
	at e (/home/sarvagya/.vscode/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29057)
	at Array.map (<anonymous>)
	at /home/sarvagya/.vscode/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29222
	at async o (/home/sarvagya/.vscode/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:1:53891)]
Error 2021-04-02 10:12:01: Failed to parse version from path: /home/sarvagya/anaconda3/envs/pytorch/bin/python [Error: invalid version python
	at u (/home/sarvagya/.vscode/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:198256)
	at Object.c [as parseVersion] (/home/sarvagya/.vscode/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:197565)
	at p.buildPathEnvInfo (/home/sarvagya/.vscode/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29369)
	at p.resolveEnv (/home/sarvagya/.vscode/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:29309)
	at E.resolveEnv (/home/sarvagya/.vscode/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:29:4121)
	at t.PythonEnvsReducer.resolveEnv (/home/sarvagya/.vscode/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:61:762313)
	at async t.PythonEnvsResolver.resolveEnv (/home/sarvagya/.vscode/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:61:763669)
	at async u.doResolveEnv (/home/sarvagya/.vscode/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:61:757654)
	at async q.getInterpreterDetails (/home/sarvagya/.vscode/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:38813)
	at async C.getInterpreterDetails (/home/sarvagya/.vscode/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:61:741545)
	at async f.updateDisplay (/home/sarvagya/.vscode/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:61:729765)
	at async f.refresh (/home/sarvagya/.vscode/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:61:729292)]
```

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Error 2021-04-02 10:07:34: Exception attempting to start notebook:  [Error: invalid version -final
	at Object.u [as parseBasicVersion] (/home/sarvagya/.vscode/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:198256)
	at V (/home/sarvagya/.vscode/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:37379)
	at q.getInterpreterDetails (/home/sarvagya/.vscode/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:38849)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async C.getInterpreterDetails (/home/sarvagya/.vscode/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:61:741545)
	at async O.getKernelForLocalRawConnection (/home/sarvagya/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/out/client/extension.js:1:299798)]
Error 2021-04-02 10:07:34: DataScience Error [Error: invalid version -final
	at Object.u [as parseBasicVersion] (/home/sarvagya/.vscode/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:9:198256)
	at V (/home/sarvagya/.vscode/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:37379)
	at q.getInterpreterDetails (/home/sarvagya/.vscode/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:80:38849)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async C.getInterpreterDetails (/home/sarvagya/.vscode/extensions/ms-python.python-2021.3.680753044/out/client/extension.js:61:741545)
	at async O.getKernelForLocalRawConnection (/home/sarvagya/.vscode/extensions/ms-toolsai.jupyter-2021.3.684299474/out/client/extension.js:1:299798)]
```

</p>
</details>

**Comment by vsheg** [comment]
I have that problem, too

**Comment by claudiaregio** [comment]
Hi @Flock1 and @vsheg, will have someone take a look as soon as possible
