### ISSUE TITLE
Extension activation failed 

### ISSUE THREAD

**Issue by RicardoSQueen** [microsoft/vscode-jupyter#5422]
## Environment data

-   VS Code version: 1.55.0
-   Jupyter Extension version: 2021.5.702919634
-   Python Extension version: 2021.3.680753044
-   OS (Linux distro) and version: Linux x64 Manjaro kernel 5.11.6-1 
-   Python and/or Anaconda version: Python 3.9.2 conda 4.9.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

Extension is activated and is usable
## Actual behaviour

Extension is not activated and errors are raised in the console

## Steps to reproduce:

1. Open VSCode and wait for error to appear

## Logs
Observation: I was not having this issue until today, possibly because of an automatic update. Trying to revert the changes, the latest version that worked in my setup was version 2021.3.68...
<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>
<p>

```
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
Info 2021-04-06 16:00:05: ZMQ install verified.
Info 2021-04-06 16:00:05: id is 33078fd8-6ec3-4b87-83a9-b948386359a7
Error 2021-04-06 16:00:05: extension activation failed [Error: [ms-toolsai.jupyter]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api ms-toolsai.jupyter
	at g (/usr/share/vscodium-bin/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:77471)
	at _ (/usr/share/vscodium-bin/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:77418)
	at Object.onDidChangeCellExecutionState (/usr/share/vscodium-bin/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:40468)
	at new d (/home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:49:767343)
	at Object.t.resolveInstance (/home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:47:239927)
	at /home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:47:239132
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:47:239697)
	at /home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:47:239132
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:47:239697)
	at /home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:47:239132
	at /home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:47:238080
	at Array.map (<anonymous>)
	at /home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:47:238052
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:47:239697)
	at /home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:47:239132
	at Object.t.resolve (/home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:47:239395)
	at /home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:47:230492
	at e._get (/home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:47:230258)
	at e.get (/home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:47:228970)
	at a.get (/home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:49:818107)
	at /home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:47:273180
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async /home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:32:772757
	at async t.activate (/home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:32:772444)
	at async Promise.all (index 0)]
Error 2021-04-06 16:00:05: Failed to active the Jupyter Extension [Error: [ms-toolsai.jupyter]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api ms-toolsai.jupyter
	at g (/usr/share/vscodium-bin/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:77471)
	at _ (/usr/share/vscodium-bin/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:77418)
	at Object.onDidChangeCellExecutionState (/usr/share/vscodium-bin/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:40468)
	at new d (/home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:49:767343)
	at Object.t.resolveInstance (/home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:47:239927)
	at /home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:47:239132
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:47:239697)
	at /home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:47:239132
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:47:239697)
	at /home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:47:239132
	at /home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:47:238080
	at Array.map (<anonymous>)
	at /home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:47:238052
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:47:239697)
	at /home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:47:239132
	at Object.t.resolve (/home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:47:239395)
	at /home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:47:230492
	at e._get (/home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:47:230258)
	at e.get (/home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:47:228970)
	at a.get (/home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:49:818107)
	at /home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:47:273180
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async /home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:32:772757
	at async t.activate (/home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/extension.js:32:772444)
	at async Promise.all (index 0)]
Info 2021-04-06 16:00:06: Found existing keyfile at /home/ricardoqueen/.config/VSCodium/User/globalStorage/ms-toolsai.jupyter/nbsecret
Info 2021-04-06 16:00:06: Loading web panel for file:///media/LinuxFiles/Insync/PoliMail/Google%20Drive/Material%20Estudo/POLI%20UFRJ/2020.2/Processamento%20de%20Sinais/control.ipynb
Info 2021-04-06 16:00:06: Loading webview. View is notset
Info 2021-04-06 16:00:06: Attempting to start a server because of preload conditions ...
Info 2021-04-06 16:00:06: Loading web view...
Info 2021-04-06 16:00:06: Webview panel created.
Info 2021-04-06 16:00:06: Creating raw notebook for file:///media/LinuxFiles/Insync/PoliMail/Google%20Drive/Material%20Estudo/POLI%20UFRJ/2020.2/Processamento%20de%20Sinais/control.ipynb
Info 2021-04-06 16:00:06: Getting preferred kernel for file:///media/LinuxFiles/Insync/PoliMail/Google%20Drive/Material%20Estudo/POLI%20UFRJ/2020.2/Processamento%20de%20Sinais/control.ipynb
Info 2021-04-06 16:00:07: Trusting notebook...
Info 2021-04-06 16:00:07: Wrote trust for file:///media/LinuxFiles/Insync/PoliMail/Google%20Drive/Material%20Estudo/POLI%20UFRJ/2020.2/Processamento%20de%20Sinais/control.ipynb to /home/ricardoqueen/.config/VSCodium/User/globalStorage/ms-toolsai.jupyter/nbsignatures/4d1f2d56613fc241b08816c9885edd35a6e4eca54984ee87cf0671eeafbef7e2
Info 2021-04-06 16:00:08: Web view react rendered
Info 2021-04-06 16:00:08: Request for onigasm file at /home/ricardoqueen/.vscode-oss/extensions/ms-toolsai.jupyter-2021.5.702919634/out/client/node_modules/onigasm/lib/onigasm.wasm
Info 2021-04-06 16:00:08: Request for tmlanguage file.
Info 2021-04-06 16:00:08: Searching for token colors ...
Info 2021-04-06 16:00:08: Attempting search for colors ...
Info 2021-04-06 16:00:08: Searching for token colors ...
Info 2021-04-06 16:00:08: Attempting search for colors ...
Info 2021-04-06 16:00:08: Searching for token colors ...
Info 2021-04-06 16:00:08: Attempting search for colors ...
Info 2021-04-06 16:00:08: Searching for token colors ...
Info 2021-04-06 16:00:08: Attempting search for colors ...
Info 2021-04-06 16:00:09: Searching for token colors ...
Info 2021-04-06 16:00:09: Attempting search for colors ...
Info 2021-04-06 16:00:09: Loading colors from /usr/share/vscodium-bin/resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 2021-04-06 16:00:09: Searching for token colors ...
Info 2021-04-06 16:00:09: Attempting search for colors ...
Info 2021-04-06 16:00:09: Searching for token colors ...
Info 2021-04-06 16:00:09: Attempting search for colors ...
Info 2021-04-06 16:00:09: Loading colors from /usr/share/vscodium-bin/resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 2021-04-06 16:00:09: Loading colors from /usr/share/vscodium-bin/resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 2021-04-06 16:00:09: Loading colors from /usr/share/vscodium-bin/resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 2021-04-06 16:00:09: Loading colors from /usr/share/vscodium-bin/resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 2021-04-06 16:00:09: Loading colors from /usr/share/vscodium-bin/resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 2021-04-06 16:00:09: Loading colors from /usr/share/vscodium-bin/resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 2021-04-06 16:00:09: Searching for token colors ...
Info 2021-04-06 16:00:09: Attempting search for colors ...
Info 2021-04-06 16:00:09: Loading colors from /usr/share/vscodium-bin/resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 2021-04-06 16:00:09: Attempting search for colors ...
Info 2021-04-06 16:00:09: Attempting search for colors ...
Info 2021-04-06 16:00:09: Attempting search for colors ...
Info 2021-04-06 16:00:09: Attempting search for colors ...
Info 2021-04-06 16:00:09: Attempting search for colors ...
Info 2021-04-06 16:00:09: Attempting search for colors ...
Info 2021-04-06 16:00:09: Attempting search for colors ...
Info 2021-04-06 16:00:09: Loading base colors from /usr/share/vscodium-bin/resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 2021-04-06 16:00:09: Loading base colors from /usr/share/vscodium-bin/resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 2021-04-06 16:00:09: Loading base colors from /usr/share/vscodium-bin/resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 2021-04-06 16:00:09: Loading base colors from /usr/share/vscodium-bin/resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 2021-04-06 16:00:09: Loading base colors from /usr/share/vscodium-bin/resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 2021-04-06 16:00:09: Loading base colors from /usr/share/vscodium-bin/resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 2021-04-06 16:00:09: Loading base colors from /usr/share/vscodium-bin/resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 2021-04-06 16:00:09: Attempting search for colors ...
Info 2021-04-06 16:00:09: Loading base colors from /usr/share/vscodium-bin/resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 2021-04-06 16:00:09: Using colors to generate CSS ...
Info 2021-04-06 16:00:09: Using colors to generate CSS ...
Info 2021-04-06 16:00:09: Using colors to generate CSS ...
Info 2021-04-06 16:00:09: Using colors to generate CSS ...
Info 2021-04-06 16:00:09: Using colors to generate CSS ...
Info 2021-04-06 16:00:09: Using colors to generate CSS ...
Info 2021-04-06 16:00:09: Using colors to generate CSS ...
Info 2021-04-06 16:00:09: Using colors to generate CSS ...
```

</p>
</details>

**Comment by IanMatthewHuff** [comment]
@RicardoSQueen The Jupyter extension makes use of the VSCode proposed API for notebook support (see snip from log below). It looks like you are running VSCodium and not VSCode which is community driven and not officially supported via Microsoft. In VSCode our extension is explicitly allowed by VS Code to use the proposed API and it looks like VS Codium does not do the same thing.
`Error 2021-04-06 16:00:05: Failed to active the Jupyter Extension [Error: [ms-toolsai.jupyter]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api ms-toolsai.jupyter
`
If you want to keep using VSCodium and not VSCode you can try using that command line switch proposed above.
