### ISSUE TITLE
Jupyter and docker extensions don't play well with each other.

### ISSUE THREAD

**Issue by akanakia** [microsoft/vscode-jupyter#5563]
I am trying to launch and jupyter notebook in vs code but the extension fails with the following error log:

```
[2021-04-20 11:50:00.730] [renderer1] [error] Failed to connect to Jupyter notebook. 
http://localhost:8888/
TypeError: Only absolute URLs are supported: Error: 
	at new i (c:\Users\kckb075\.vscode\extensions\ms-python.python-2020.6.91350\out\client\extension.js:1:516819)
	at c:\Users\kckb075\.vscode\extensions\ms-python.python-2020.6.91350\out\client\extension.js:24:465743

TypeError: Only absolute URLs are supported
	at getNodeRequestOptions (c:\Users\kckb075\.vscode\extensions\ms-azuretools.vscode-docker-1.6.0\dist\extension.bundle.js:33:1629484)
	at c:\Users\kckb075\.vscode\extensions\ms-azuretools.vscode-docker-1.6.0\dist\extension.bundle.js:33:1630307
	at new Promise (<anonymous>)
	at fetch (c:\Users\kckb075\.vscode\extensions\ms-azuretools.vscode-docker-1.6.0\dist\extension.bundle.js:33:1629266)
	at Object.e.handleRequest (c:\Users\kckb075\.vscode\extensions\ms-python.python-2020.6.91350\out\client\node_modules\@jupyterlab\services.js:1:92015)
	at Object.e.makeRequest (c:\Users\kckb075\.vscode\extensions\ms-python.python-2020.6.91350\out\client\node_modules\@jupyterlab\services.js:1:90580)
	at c.newUntitled (c:\Users\kckb075\.vscode\extensions\ms-python.python-2020.6.91350\out\client\node_modules\@jupyterlab\services.js:3:394046)
	at t.ContentsManager.newUntitled (c:\Users\kckb075\.vscode\extensions\ms-python.python-2020.6.91350\out\client\node_modules\@jupyterlab\services.js:3:391190)
	at _.createSession (c:\Users\kckb075\.vscode\extensions\ms-python.python-2020.6.91350\out\client\extension.js:48:463368)
	at _.connect (c:\Users\kckb075\.vscode\extensions\ms-python.python-2020.6.91350\out\client\extension.js:48:460906)
	at t.JupyterSessionManager.startNew (c:\Users\kckb075\.vscode\extensions\ms-python.python-2020.6.91350\out\client\extension.js:48:457485)
	at m.connect (c:\Users\kckb075\.vscode\extensions\ms-python.python-2020.6.91350\out\client\extension.js:48:431176)
	at async c:\Users\kckb075\.vscode\extensions\ms-python.python-2020.6.91350\out\client\extension.js:24:464575
```

It looks very similar to issue #2172 where another extension was hijacking the node-fetch command but perhaps not the same thing as I'm not an expert. I would very much like to keep both extensions installed as they are integral to many of my projects. Is there a workaround to this besides having to uninstall the docker extension? Any help is much appreciated. Thank you.

**Comment by IanMatthewHuff** [comment]
@akanakia So this was an issue (with node fetch) that I believed that we had already resolved previously. It looks to me like you are working with an extremely old version of our Jupyter support. 

> at _.connect (c:\Users\kckb075\.vscode\extensions\ms-python.python-2020.6.91350\out\client\extension.js:48:460906)

Looks like June of last year? If you update to a newer version this should be resolved.

**Comment by greazer** [comment]
@akanakia, feel free to reopen if updating to the latest extensions doesn't work for you.
