### ISSUE TITLE
this.notebook.onDidChangeActiveNotebookKernel is not a function on insiders

### ISSUE THREAD

**Issue by s-glasmacher** [microsoft/vscode-jupyter#5583]
Issue Type: <b>Bug</b>

Can't open ipynb files anymore in VSCode Insiders version.

```
Error 2021-04-21 12:50:51: Exception while attempting zmq : [Error: /snap/core/current/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/node_modules/zeromq/prebuilds/linux-x64/electron.napi.glibc.node)
	at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
	at Object.Module._extensions..node (internal/modules/cjs/loader.js:1185:18)
	at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1846)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
	at Function.r._load (/snap/code-insiders/689/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:27794)
	at Function._._load (/snap/code-insiders/689/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:24510)
	at Function.a._load (/snap/code-insiders/689/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:96:59184)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at v (/snap/code-insiders/689/usr/share/code-insiders/resources/app/out/vs/loader.js:4:694)
	at load (/home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/node_modules/node-gyp-build/index.js:21:10)
	at Object.<anonymous> (/home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/node_modules/zeromq/lib/native.js:6:43)
	at Module.u._compile (/snap/code-insiders/689/usr/share/code-insiders/resources/app/out/vs/loader.js:4:1311)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
	at Function.r._load (/snap/code-insiders/689/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:27794)
	at Function._._load (/snap/code-insiders/689/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:24510)
	at Function.a._load (/snap/code-insiders/689/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:96:59184)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at v (/snap/code-insiders/689/usr/share/code-insiders/resources/app/out/vs/loader.js:4:694)
	at Object.<anonymous> (/home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/node_modules/zeromq/lib/index.js:3:16)
	at Module.u._compile (/snap/code-insiders/689/usr/share/code-insiders/resources/app/out/vs/loader.js:4:1311)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
	at Function.r._load (/snap/code-insiders/689/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:27794)
	at Function._._load (/snap/code-insiders/689/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:24510)
	at Function.a._load (/snap/code-insiders/689/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:96:59184)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at v (/snap/code-insiders/689/usr/share/code-insiders/resources/app/out/vs/loader.js:4:694)
	at Object.<anonymous> (/home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:32:336621)
	at n (/home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:1:186)
	at d.zmqSupported (/home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:49:758073)
	at d.isSupportedForLocalLaunch (/home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:49:757723)
	at d.supported (/home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:49:757633)
	at Object.t.registerTypes (/home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:47:806876)
	at /home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:47:273063
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:32:773548
	at async t.activate (/home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:32:773235)
	at async Promise.all (index 0)]
Error 2021-04-21 12:50:51: extension activation failed [TypeError: this.notebook.onDidChangeActiveNotebookKernel is not a function
	at new T (/home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:49:656347)
	at Object.t.resolveInstance (/home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:47:239967)
	at /home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:47:239172
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:47:239737)
	at /home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:47:239172
	at /home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:47:238120
	at Array.map (<anonymous>)
	at /home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:47:238092
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:47:239737)
	at /home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:47:239172
	at Object.t.resolve (/home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:47:239435)
	at /home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:47:230532
	at e._get (/home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:47:230298)
	at e.get (/home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:47:229010)
	at a.get (/home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:49:819305)
	at /home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:47:273220
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:32:773548
	at async t.activate (/home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:32:773235)
	at async Promise.all (index 0)]
Error 2021-04-21 12:50:51: Failed to active the Jupyter Extension [TypeError: this.notebook.onDidChangeActiveNotebookKernel is not a function
	at new T (/home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:49:656347)
	at Object.t.resolveInstance (/home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:47:239967)
	at /home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:47:239172
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:47:239737)
	at /home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:47:239172
	at /home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:47:238120
	at Array.map (<anonymous>)
	at /home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:47:238092
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:47:239737)
	at /home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:47:239172
	at Object.t.resolve (/home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:47:239435)
	at /home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:47:230532
	at e._get (/home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:47:230298)
	at e.get (/home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:47:229010)
	at a.get (/home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:49:819305)
	at /home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:47:273220
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:32:773548
	at async t.activate (/home/sarah/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.755784270/out/client/extension.js:32:773235)
	at async Promise.all (index 0)]
```

Extension version: 2021.6.755784270
VS Code version: Code - Insiders 1.56.0-insider (23a2409675bc1bde94f3532bc7c5826a6e99e4b6, 2021-04-21T05:13:27.110Z)
OS version: Linux x64 5.8.0-50-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz (8 x 3638)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|15.57GB (6.05GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox --crash-reporter-id 8b26a692-a502-4514-95df-6254d9f0d100|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551:30291412
vspre833cf:30267465
pythonptprofiler:30281269
vscnewfiletextcf:30288478
vshan820:30276952
pythondataviewer:30285072
vscus158cf:30286554
vscgsv2:30286872

```

</details>

**Comment by rchiodo** [comment]
There were breaking changes. The latest version of the jupyter extension should work now:

![image](https://user-images.githubusercontent.com/19672699/115588281-6db62080-a283-11eb-895c-8e45a2f9b818.png)
