### ISSUE TITLE
CDN download doesn't work on Windows for IPyWidgets

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#5695]
![image](https://user-images.githubusercontent.com/19672699/116597439-78ebfa80-a8da-11eb-9465-63e025830351.png)

We get this error here:
```
Error 2021-04-29 10:48:34: stat() failed for "C:\Users\aku91\AppData\Local\Temp\tmp-30180h7DyB574T1X8.js" [NoPermissions (FileSystemError) (FileSystemError): Error: EPERM: operation not permitted, stat 'c:\Users\aku91\AppData\Local\Temp\tmp-30180h7DyB574T1X8.js'

    at _handleError (c:\Users\aku91\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:156611)

    at runMicrotasks (<anonymous>)

    at processTicksAndRejections (internal/process/task_queues.js:93:5)

    at async m.localPathExists (c:\Users\aku91\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.795492900\out\client\extension.js:90:483841)

    at async t.CDNWidgetScriptSourceProvider.downloadFile (c:\Users\aku91\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.795492900\out\client\extension.js:54:452561)

    at async t.CDNWidgetScriptSourceProvider.downloadFromCDN (c:\Users\aku91\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.795492900\out\client\extension.js:54:451876)

    at async Promise.all (index 0)] {

  code: 'Unknown'

}
```

**Comment by DavidKutu** [comment]
fixed here: https://github.com/microsoft/vscode-jupyter/pull/5697

**Comment by DonJayamanne** [comment]
Validated
