### ISSUE TITLE
Jupyter notebook connect prompt occurring just on opening a folder

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#5814]
On opening one of the clones of vscode-jupyter or vscode-python on my machine, I wind up getting prompted to connect to a remote Jupyter kernel. I have no notebooks open, nor did I even intend to. 

![image](https://user-images.githubusercontent.com/11685408/117520016-0ecaf980-af5b-11eb-8ce2-b03a6ccabf27.png)

VSCode Stable: 1.56.0
Jupyter: v2021.6.811652604

Here's the log:
```User belongs to experiment group 'pythonJoinMailingListVar2'User belongs to experiment group 'pythonJediLSPcf'
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'pythonDiscoveryModulecf'
User belongs to experiment group 'pythonSurveyNotification'
User belongs to experiment group 'jupyterEnhancedDataViewer'
User belongs to experiment group 'NativeNotebookEditor'
Info 2021-05-07 16:52:34: Found existing keyfile at c:\Users\jimg\AppData\Roaming\Code\User\globalStorage\ms-toolsai.jupyter\nbsecret
Info 2021-05-07 16:52:40: Checking for server existence.
Info 2021-05-07 16:54:50: Checking for server usability.
Info 2021-05-07 16:54:50: Starting notebook server.
Info 2021-05-07 16:54:50: Connecting to history server
Error 2021-05-07 16:54:50: Error loading notebook controllers TypeError [ERR_INVALID_URL]: Invalid URL: remote
    at onParseError (internal/url.js:259:9)
    at new URL (internal/url.js:335:5)
    at h.extractJupyterServerHandleAndId (c:\Users\jimg\.vscode\extensions\ms-toolsai.jupyter-2021.6.811652604\out\client\extension.js:37:758776)
    at h.updateServerUri (c:\Users\jimg\.vscode\extensions\ms-toolsai.jupyter-2021.6.811652604\out\client\extension.js:37:759165)
    at h.startOrConnect (c:\Users\jimg\.vscode\extensions\ms-toolsai.jupyter-2021.6.811652604\out\client\extension.js:37:758043)
    at c:\Users\jimg\.vscode\extensions\ms-toolsai.jupyter-2021.6.811652604\out\client\extension.js:37:755340
    at Object.e.race (c:\Users\jimg\.vscode\extensions\ms-toolsai.jupyter-2021.6.811652604\out\client\extension.js:16:34512)
    at h.connectToNotebookServer (c:\Users\jimg\.vscode\extensions\ms-toolsai.jupyter-2021.6.811652604\out\client\extension.js:37:754674)
    at hostConnectToNotebookServer (c:\Users\jimg\.vscode\extensions\ms-toolsai.jupyter-2021.6.811652604\out\client\extension.js:90:169672)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at y.connectToNotebookServer (c:\Users\jimg\.vscode\extensions\ms-toolsai.jupyter-2021.6.811652604\out\client\extension.js:90:164579)
    at S.startServer (c:\Users\jimg\.vscode\extensions\ms-toolsai.jupyter-2021.6.811652604\out\client\extension.js:54:382973)
    at S.createServer (c:\Users\jimg\.vscode\extensions\ms-toolsai.jupyter-2021.6.811652604\out\client\extension.js:54:382059)
    at connect (c:\Users\jimg\.vscode\extensions\ms-toolsai.jupyter-2021.6.811652604\out\client\extension.js:90:179008)
    at T.getKernelConnectionMetadata (c:\Users\jimg\.vscode\extensions\ms-toolsai.jupyter-2021.6.811652604\out\client\extension.js:90:340776)
    at T.loadNotebookControllers (c:\Users\jimg\.vscode\extensions\ms-toolsai.jupyter-2021.6.811652604\out\client\extension.js:90:337531) {
  input: 'remote',
  vslsStack: [
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {}
  ],
  code: 'ERR_INVALID_URL'
}

**Comment by claudiaregio** [comment]
Thanks @greazer! Will triage with the team next week

**Comment by greazer** [comment]
Doesn't repro on insiders. I'm assuming this has been fixed somehow.
