### ISSUE TITLE
Can't open jupyter notebook files

### ISSUE THREAD

**Issue by Syndorik** [microsoft/vscode-jupyter#5828]
## Environment data

-   VS Code version: 1.57.0-insider 54d33cf14cf6c0e86880b5b74a5a3628de42bce9          x64                                                                                                                                    
-   Jupyter Extension version (available under the Extensions sidebar): 2021.6.831155446
-   Python Extension version (available under the Extensions sidebar): 2021.6.829598502-dev
-   OS (Windows | Mac | Linux distro) and version: Windows
-   Python and/or Anaconda version: 3.9.4
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local | Remote | Remote

## Expected behaviour

With new version of jupyter extension, it is not possible to open notebooks (vscode doesn't recognize it). By downgrading to the previous version it works

## Steps to reproduce:

1. Open a notebook with last jupyter extension

**Comment by giuseppefilitto** [comment]
Same here

## Environment data
- VS Code Version: 1.57.0-insider
Commit: 54d33cf14cf6c0e86880b5b74a5a3628de42bce9
Date: 2021-05-10T05:12:44.162Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin arm64 20.4.0

- Jupyter Extension version: v2021.6.831144556
- Python Extension version: v2021.5.829140558
- OS (Windows | Mac | Linux distro) and version: OS 11.3.1 
- Python and/or Anaconda version: 3.8.6, 3.9.1
- Type of virtual environment used: conda (Miniforge3)
- Jupyter server running: Local | Remote 

## Logs

```
electron/js2c/renderer_init.js:61 The vm module of Node.js is deprecated in the renderer process and will be removed.
t._load @ electron/js2c/renderer_init.js:61
log.ts:296   ERR Cannot have two contributions with the same id editor.contrib.acceptChangesButton: Error: Cannot have two contributions with the same id editor.contrib.acceptChangesButton
    at new ln (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:652:76088)
    at g._createInstance (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:625:1374)
    at g.createInstance (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:625:793)
    at i.createEditorControl (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2252:27035)
    at i.createEditor (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2252:26646)
    at i.create (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1440:57779)
    at l.doCreateEditorPane (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1808:9752)
    at l.doShowEditorPane (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1808:9327)
    at l.openEditor (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1808:9081)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2462:15947
    at mi.doShowEditor (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2462:16126)
    at mi.restoreEditors (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2462:9086)
    at new mi (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2462:4164)
    at g._createInstance (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:625:1374)
    at g.createInstance (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:625:793)
    at Function.createFromSerialized (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2462:4465)
    at ai.doCreateGroupView (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2481:7761)
    at Object.fromJSON (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2481:14771)
    at c._deserializeNode (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:142:59361)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:142:59204
    at Array.map (<anonymous>)
    at c._deserializeNode (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:142:59185)
    at c._deserialize (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:142:59090)
    at Function.deserialize (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:142:59024)
    at Function.deserialize (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:142:67922)
    at ai.doCreateGridControlWithState (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2481:14700)
    at ai.doCreateGridControlWithPreviousState (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2481:14283)
    at ai.doCreateGridControl (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2481:13860)
    at ai.createContentArea (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2481:11939)
    at ai.create (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:735:140270)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2519:63731
    at Array.forEach (<anonymous>)
    at M.renderWorkbench (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2519:63638)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2519:60823
    at g.invokeFunction (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:625:319)
    at M.startup (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2519:60454)
    at E.open (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2649:30050)
    at async file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/bootstrap-window.js:1:2841
console.ts:137 [Extension Host] (node:2510) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Code - Insiders Helper (Renderer) --trace-deprecation ...` to show where the warning was created) (at writeOut (internal/process/warning.js:43:3))
S @ console.ts:137
notificationsAlerts.ts:40 Extension activation failed, run the 'Developer: Toggle Developer Tools' command for more information.
onDidChangeNotification @ notificationsAlerts.ts:40
console.ts:137 [Extension Host] extension activation failed TypeError: s.notebook.onDidChangeNotebookCellExecutionState is not a function
	at new d (/Users/giuseppefilitto/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.831144556/out/client/extension.js:90:450992)
	at Object.t.resolveInstance (/Users/giuseppefilitto/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.831144556/out/client/extension.js:52:263270)
	at /Users/giuseppefilitto/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.831144556/out/client/extension.js:52:262475
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/Users/giuseppefilitto/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.831144556/out/client/extension.js:52:263040)
	at /Users/giuseppefilitto/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.831144556/out/client/extension.js:52:262475
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/Users/giuseppefilitto/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.831144556/out/client/extension.js:52:263040)
	at /Users/giuseppefilitto/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.831144556/out/client/extension.js:52:262475
	at /Users/giuseppefilitto/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.831144556/out/client/extension.js:52:261423
	at Array.map (<anonymous>)
	at /Users/giuseppefilitto/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.831144556/out/client/extension.js:52:261395
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/Users/giuseppefilitto/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.831144556/out/client/extension.js:52:263040)
	at /Users/giuseppefilitto/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.831144556/out/client/extension.js:52:262475
	at Object.t.resolve (/Users/giuseppefilitto/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.831144556/out/client/extension.js:52:262738)
	at /Users/giuseppefilitto/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.831144556/out/client/extension.js:52:253835
	at e._get (/Users/giuseppefilitto/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.831144556/out/client/extension.js:52:253601)
	at e.get (/Users/giuseppefilitto/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.831144556/out/client/extension.js:52:252313)
	at a.get (/Users/giuseppefilitto/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.831144556/out/client/extension.js:90:505543)
	at /Users/giuseppefilitto/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.831144556/out/client/extension.js:52:245938
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /Users/giuseppefilitto/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.831144556/out/client/extension.js:37:829598
	at async t.activate (/Users/giuseppefilitto/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.831144556/out/client/extension.js:37:829285)
	at async Promise.all (index 1) (at /Users/giuseppefilitto/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.831144556/out/client/extension.js:37:830117)
S @ console.ts:137
notificationsAlerts.ts:40 Cannot open resource with notebook editor type 'jupyter-notebook', please check if you have the right extension installed or enabled.
onDidChangeNotification @ notificationsAlerts.ts:40
```
