### ISSUE TITLE
Jupyter Extension activation failed.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/vscode-jupyter#5829]
## Environment data
VS Code version: 1.57.0-insider
Jupyter Extension version: 2021.6.831144556
Python Extension version: 2021.6.829598502-dev
OS (Windows | Mac | Linux distro) and version: Win10 Enterprise 64bit
Python and/or Anaconda version: Python 3.8.5 64bit (conda)

## Expected behaviour
Jupyter Extension works well.

## Actual behaviour
Jupyter Extension activation failed.
![image](https://user-images.githubusercontent.com/59192491/117803742-8e253980-b289-11eb-9827-da93bb28c36c.png)

## Toggle Developer Tools
```
extension activation failed TypeError: s.notebook.onDidChangeNotebookCellExecutionState is not a function
	at new d (c:\Users\vyizh12\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.831144556\out\client\extension.js:90:450992)
	at Object.t.resolveInstance (c:\Users\vyizh12\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.831144556\out\client\extension.js:52:263270)
	at c:\Users\vyizh12\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.831144556\out\client\extension.js:52:262475
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (c:\Users\vyizh12\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.831144556\out\client\extension.js:52:263040)
	at c:\Users\vyizh12\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.831144556\out\client\extension.js:52:262475
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (c:\Users\vyizh12\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.831144556\out\client\extension.js:52:263040)
	at c:\Users\vyizh12\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.831144556\out\client\extension.js:52:262475
	at c:\Users\vyizh12\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.831144556\out\client\extension.js:52:261423
	at Array.map (<anonymous>)
	at c:\Users\vyizh12\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.831144556\out\client\extension.js:52:261395
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (c:\Users\vyizh12\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.831144556\out\client\extension.js:52:263040)
	at c:\Users\vyizh12\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.831144556\out\client\extension.js:52:262475
	at Object.t.resolve (c:\Users\vyizh12\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.831144556\out\client\extension.js:52:262738)
	at c:\Users\vyizh12\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.831144556\out\client\extension.js:52:253835
	at e._get (c:\Users\vyizh12\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.831144556\out\client\extension.js:52:253601)
	at e.get (c:\Users\vyizh12\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.831144556\out\client\extension.js:52:252313)
	at a.get (c:\Users\vyizh12\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.831144556\out\client\extension.js:90:505543)
	at c:\Users\vyizh12\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.831144556\out\client\extension.js:52:245938
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\vyizh12\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.831144556\out\client\extension.js:37:829598
	at async t.activate (c:\Users\vyizh12\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.831144556\out\client\extension.js:37:829285)
	at async Promise.all (index 0) (at c:\Users\vyizh12\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.831144556\out\client\extension.js:37:830117)
```

**Comment by cpoptic** [comment]
+1 Same here.  Looks like the developers broke something in the latest update.

**Comment by ghtmtt** [comment]
same here

**Comment by ryanbrownnetworking777** [comment]
@blind-author  actually no that didn't work. It loads the file but it won't actually run the code.

**Comment by DonJayamanne** [comment]
I'm sorry you ran into this issue. There is a bug in VS Code Insiders, and we have craeted a new release that gets around this issue.
