### ISSUE TITLE
All IPyWidget tests are now failing in Funcitonal tests (100% of the time)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5842]
<details>
<summary>Details</summary>

```
 [0m[32m 0 passing[0m[90m (45m)[0m
2021-05-11T17:39:18.7110005Z [31m  20 failing[0m
2021-05-11T17:39:18.7110481Z 
2021-05-11T17:39:18.7111242Z [0m  1) DataScience IPyWidgets (With Direct Kernel)
2021-05-11T17:39:18.7111982Z        Notebook has 3 cells:
2021-05-11T17:39:18.7113969Z [0m[31m     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\vscode-jupyter\vscode-jupyter\out\test\datascience\uiTests\ipywidget.ui.functional.test.js)[0m[90m
2021-05-11T17:39:18.7115372Z       at listOnTimeout (internal/timers.js:531:17)
2021-05-11T17:39:18.7116369Z       at processTimers (internal/timers.js:475:7)
2021-05-11T17:39:18.7116924Z [0m
2021-05-11T17:39:18.7117473Z [0m  2) DataScience IPyWidgets (With Direct Kernel)
2021-05-11T17:39:18.7118361Z        Output displayed after executing a cell:
2021-05-11T17:39:18.7120212Z [0m[31m     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\vscode-jupyter\vscode-jupyter\out\test\datascience\uiTests\ipywidget.ui.functional.test.js)[0m[90m
2021-05-11T17:39:18.7121768Z       at listOnTimeout (internal/timers.js:531:17)
2021-05-11T17:39:18.7122418Z       at processTimers (internal/timers.js:475:7)
2021-05-11T17:39:18.7123037Z [0m
2021-05-11T17:39:18.7124015Z [0m  3) DataScience IPyWidgets (With Direct Kernel)
2021-05-11T17:39:18.7124585Z        Slider Widget:
2021-05-11T17:39:18.7126196Z [0m[31m     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\vscode-jupyter\vscode-jupyter\out\test\datascience\uiTests\ipywidget.ui.functional.test.js)[0m[90m
2021-05-11T17:39:18.7130188Z       at listOnTimeout (internal/timers.js:531:17)
2021-05-11T17:39:18.7130951Z       at processTimers (internal/timers.js:475:7)
2021-05-11T17:39:18.7131384Z [0m
2021-05-11T17:39:18.7132058Z [0m  4) DataScience IPyWidgets (With Direct Kernel)
2021-05-11T17:39:18.7133186Z        Text Widget:
2021-05-11T17:39:18.7135294Z [0m[31m     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\vscode-jupyter\vscode-jupyter\out\test\datascience\uiTests\ipywidget.ui.functional.test.js)[0m[90m
2021-05-11T17:39:18.7137251Z       at listOnTimeout (internal/timers.js:531:17)
2021-05-11T17:39:18.7137839Z       at processTimers (internal/timers.js:475:7)
2021-05-11T17:39:18.7138244Z [0m
2021-05-11T17:39:18.7139122Z [0m  5) DataScience IPyWidgets (With Direct Kernel)
2021-05-11T17:39:18.7139720Z        Checkbox Widget:
2021-05-11T17:39:18.7141401Z [0m[31m     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\vscode-jupyter\vscode-jupyter\out\test\datascience\uiTests\ipywidget.ui.functional.test.js)[0m[90m
2021-05-11T17:39:18.7142858Z       at listOnTimeout (internal/timers.js:531:17)
2021-05-11T17:39:18.7143430Z       at processTimers (internal/timers.js:475:7)
2021-05-11T17:39:18.7144023Z [0m
2021-05-11T17:39:18.7144516Z [0m  6) DataScience IPyWidgets (With Direct Kernel)
2021-05-11T17:39:18.7145016Z        Render ipysheets:
2021-05-11T17:39:18.7147134Z [0m[31m     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\vscode-jupyter\vscode-jupyter\out\test\datascience\uiTests\ipywidget.ui.functional.test.js)[0m[90m
2021-05-11T17:39:18.7148437Z       at listOnTimeout (internal/timers.js:531:17)
2021-05-11T17:39:18.7149025Z       at processTimers (internal/timers.js:475:7)
2021-05-11T17:39:18.7149449Z [0m
2021-05-11T17:39:18.7150284Z [0m  7) DataScience IPyWidgets (With Direct Kernel)
2021-05-11T17:39:18.7150898Z        Widget renders after closing and re-opening notebook:
2021-05-11T17:39:18.7153767Z [0m[31m     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\vscode-jupyter\vscode-jupyter\out\test\datascience\uiTests\ipywidget.ui.functional.test.js)[0m[90m
2021-05-11T17:39:18.7155466Z       at listOnTimeout (internal/timers.js:531:17)
2021-05-11T17:39:18.7156541Z       at processTimers (internal/timers.js:475:7)
2021-05-11T17:39:18.7157137Z [0m
2021-05-11T17:39:18.7157984Z [0m  8) DataScience IPyWidgets (With Direct Kernel)
2021-05-11T17:39:18.7158587Z        Widget renders after restarting kernel:
2021-05-11T17:39:18.7160385Z [0m[31m     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\vscode-jupyter\vscode-jupyter\out\test\datascience\uiTests\ipywidget.ui.functional.test.js)[0m[90m
2021-05-11T17:39:18.7161824Z       at listOnTimeout (internal/timers.js:531:17)
2021-05-11T17:39:18.7162380Z       at processTimers (internal/timers.js:475:7)
2021-05-11T17:39:18.7162779Z [0m
2021-05-11T17:39:18.7163243Z [0m  9) DataScience IPyWidgets (With Direct Kernel)
2021-05-11T17:39:18.7164262Z        Widget renders after interrupting kernel:
2021-05-11T17:39:18.7165894Z [0m[31m     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\vscode-jupyter\vscode-jupyter\out\test\datascience\uiTests\ipywidget.ui.functional.test.js)[0m[90m
2021-05-11T17:39:18.7167704Z       at listOnTimeout (internal/timers.js:531:17)
2021-05-11T17:39:18.7168263Z       at processTimers (internal/timers.js:475:7)
2021-05-11T17:39:18.7168797Z [0m
2021-05-11T17:39:18.7169664Z [0m  10) DataScience IPyWidgets (With Direct Kernel)
2021-05-11T17:39:18.7170234Z        Button Interaction across Cells:
2021-05-11T17:39:18.7171820Z [0m[31m     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\vscode-jupyter\vscode-jupyter\out\test\datascience\uiTests\ipywidget.ui.functional.test.js)[0m[90m
2021-05-11T17:39:18.7173415Z       at listOnTimeout (internal/timers.js:531:17)
2021-05-11T17:39:18.7173968Z       at processTimers (internal/timers.js:475:7)
2021-05-11T17:39:18.7174357Z [0m
2021-05-11T17:39:18.7174841Z [0m  11) DataScience IPyWidgets (With Direct Kernel)
2021-05-11T17:39:18.7175863Z        Search ipysheets with textbox in another cell:
2021-05-11T17:39:18.7177646Z [0m[31m     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\vscode-jupyter\vscode-jupyter\out\test\datascience\uiTests\ipywidget.ui.functional.test.js)[0m[90m
2021-05-11T17:39:18.7179097Z       at listOnTimeout (internal/timers.js:531:17)
2021-05-11T17:39:18.7179619Z       at processTimers (internal/timers.js:475:7)
2021-05-11T17:39:18.7180007Z [0m
2021-05-11T17:39:18.7180854Z [0m  12) DataScience IPyWidgets (With Direct Kernel)
2021-05-11T17:39:18.7181522Z        Update ipysheets cells with textbox & slider in another cell:
2021-05-11T17:39:18.7183185Z [0m[31m     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\vscode-jupyter\vscode-jupyter\out\test\datascience\uiTests\ipywidget.ui.functional.test.js)[0m[90m
2021-05-11T17:39:18.7184739Z       at listOnTimeout (internal/timers.js:531:17)
2021-05-11T17:39:18.7185276Z       at processTimers (internal/timers.js:475:7)
2021-05-11T17:39:18.7185662Z [0m
2021-05-11T17:39:18.7186129Z [0m  13) DataScience IPyWidgets (With Direct Kernel)
2021-05-11T17:39:18.7187246Z        Render ipyvolume (slider, color picker, figure):
2021-05-11T17:39:18.7199446Z [0m[31m     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\vscode-jupyter\vscode-jupyter\out\test\datascience\uiTests\ipywidget.ui.functional.test.js)[0m[90m
2021-05-11T17:39:18.7201931Z       at listOnTimeout (internal/timers.js:531:17)
2021-05-11T17:39:18.7202495Z       at processTimers (internal/timers.js:475:7)
2021-05-11T17:39:18.7203259Z [0m
2021-05-11T17:39:18.7203781Z [0m  14) DataScience IPyWidgets (With Direct Kernel)
2021-05-11T17:39:18.7204320Z        Render ipyvolume (figure):
2021-05-11T17:39:18.7205906Z [0m[31m     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\vscode-jupyter\vscode-jupyter\out\test\datascience\uiTests\ipywidget.ui.functional.test.js)[0m[90m
2021-05-11T17:39:18.7207602Z       at listOnTimeout (internal/timers.js:531:17)
2021-05-11T17:39:18.7208343Z       at processTimers (internal/timers.js:475:7)
2021-05-11T17:39:18.7208732Z [0m
2021-05-11T17:39:18.7209615Z [0m  15) DataScience IPyWidgets (With Direct Kernel)
2021-05-11T17:39:18.7210136Z        Render pythreejs:
2021-05-11T17:39:18.7211693Z [0m[31m     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\vscode-jupyter\vscode-jupyter\out\test\datascience\uiTests\ipywidget.ui.functional.test.js)[0m[90m
2021-05-11T17:39:18.7213300Z       at listOnTimeout (internal/timers.js:531:17)
2021-05-11T17:39:18.7213840Z       at processTimers (internal/timers.js:475:7)
2021-05-11T17:39:18.7214581Z [0m
2021-05-11T17:39:18.7215092Z [0m  16) DataScience IPyWidgets (With Direct Kernel)
2021-05-11T17:39:18.7215616Z        Render beakerx (plot):
2021-05-11T17:39:18.7217225Z [0m[31m     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\vscode-jupyter\vscode-jupyter\out\test\datascience\uiTests\ipywidget.ui.functional.test.js)[0m[90m
2021-05-11T17:39:18.7218944Z       at listOnTimeout (internal/timers.js:531:17)
2021-05-11T17:39:18.7219470Z       at processTimers (internal/timers.js:475:7)
2021-05-11T17:39:18.7219858Z [0m
2021-05-11T17:39:18.7220332Z [0m  17) DataScience IPyWidgets (With Direct Kernel)
2021-05-11T17:39:18.7221289Z        Render beakerx (histogram):
2021-05-11T17:39:18.7222863Z [0m[31m     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\vscode-jupyter\vscode-jupyter\out\test\datascience\uiTests\ipywidget.ui.functional.test.js)[0m[90m
2021-05-11T17:39:18.7224295Z       at listOnTimeout (internal/timers.js:531:17)
2021-05-11T17:39:18.7224836Z       at processTimers (internal/timers.js:475:7)
2021-05-11T17:39:18.7225222Z [0m
2021-05-11T17:39:18.7226175Z [0m  18) DataScience IPyWidgets (With Direct Kernel)
2021-05-11T17:39:18.7226739Z        Render bqplot:
2021-05-11T17:39:18.7228265Z [0m[31m     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\vscode-jupyter\vscode-jupyter\out\test\datascience\uiTests\ipywidget.ui.functional.test.js)[0m[90m
2021-05-11T17:39:18.7229669Z       at listOnTimeout (internal/timers.js:531:17)
2021-05-11T17:39:18.7230213Z       at processTimers (internal/timers.js:475:7)
2021-05-11T17:39:18.7230598Z [0m
2021-05-11T17:39:18.7231068Z [0m  19) DataScience IPyWidgets (With Direct Kernel)
2021-05-11T17:39:18.7231555Z        Render output and interact:
2021-05-11T17:39:18.7233525Z [0m[31m     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\vscode-jupyter\vscode-jupyter\out\test\datascience\uiTests\ipywidget.ui.functional.test.js)[0m[90m
2021-05-11T17:39:18.7234820Z       at listOnTimeout (internal/timers.js:531:17)
2021-05-11T17:39:18.7235576Z       at processTimers (internal/timers.js:475:7)
2021-05-11T17:39:18.7235989Z [0m
2021-05-11T17:39:18.7236469Z [0m  20) DataScience IPyWidgets (With Direct Kernel)
2021-05-11T17:39:18.7240200Z        Render k3d:
2021-05-11T17:39:18.7241645Z [0m[31m     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\vscode-jupyter\vscode-jupyter\out\test\datascience\uiTests\ipywidget.ui.functional.test.js)[0m[90m
2021-05-11T17:39:18.7243029Z       at listOnTimeout (in
```

</details>

**Comment by DonJayamanne** [comment]
woo hooo, then hopefully this should be easy to fix 
(knowing widgets, was afraid it would be complicated to track down the issue).

@IanMatthewHuff  Thanks for pointing the probable cause.

**Comment by DonJayamanne** [comment]
Validated
