### ISSUE TITLE
Kernel dies when trying to run file from different folder in interactive window

### ISSUE THREAD

**Issue by badjouras** [microsoft/vscode-jupyter#5854]
## Environment data

-   VS Code version: **1.56.1**
-   Jupyter Extension version (available under the Extensions sidebar): **v2021.6.832593372**
-   Python Extension version (available under the Extensions sidebar): **v2021.5.829140558**
-   OS (Windows | Mac | Linux distro) and version: Windows 10 Pro 20H2
-   Python and/or Anaconda version: **Python 3.8.10 64-bit**
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): **conda**
-   Jupyter server running: **Local**

## Expected behaviour

Run cell normally

## Actual behaviour

Kernel dies and throws the error:

Error: Kernel died with exit code 1. C:\Users\User\AppData\Roaming\Python\Python38\site-packages\traitlets\traitlets.py:2196: FutureWarning: Supporting extra quotes around Unicode is deprecated in traitlets 5.0. Use 'hmac-sha256' instead of '"hmac-sha256"' – or use CUnicode.
  warn(
C:\Users\User\AppData\Roaming\Python\Python38\site-packages\traitlets\traitlets.py:2151: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '4e2eb216-5553-4c34-b499-75fee1bd9544' instead of 'b"4e2eb216-5553-4c34-b499-75fee1bd9544"'.
  warn(
Traceback (most recent call last):
  File "C:\Users\User\anaconda3\envs\ANOVA\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User\anaconda3\envs\ANOVA\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\traitlets\config\application.py", line 844, in launch_instance
    app.initialize(argv)
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\traitlets\config\application.py", line 87, in inner
    return method(app, *args, **kwargs)
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\ipykernel\kernelapp.py", line 570, in initialize
    self.write_connection_file()
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\ipykernel\kernelapp.py", line 230, in write_connection_file
    write_connection_file(cf, ip=self.ip, key=self.session.key, transport=self.transport,
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\jupyter_client\connect.py", line 136, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Users\User\anaconda3\envs\ANOVA\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\jupyter_core\paths.py", line 461, in secure_write
    win32_restrict_file_to_user(fname)
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\jupyter_core\paths.py", line 387, in win32_restrict_file_to_user
    import win32api
ImportError: DLL load failed while importing win32api: The specified module could not be found.

## Steps to reproduce:

1. Open a folder in VS Code
2. Open a python file from a different folder
2. Try to run a cell from that file in interactive window with Shift+Enter

Notes: 
- The problem only happens when using the Anaconda python interpreter.
- Already tried reinstalling the python and jupyter extensions, and running 
`conda install ipykernel --update-deps`
as indicated [here](https://github.com/microsoft/vscode-jupyter/issues/5689#issuecomment-829538285)
- After the first time the kernel dies when running a file from a different folder, it will also occasionally die when running files from the currently opened folder.

**Comment by rchiodo** [comment]
Thanks for the issue. It sounds like you have this problem here:
https://stackoverflow.com/questions/58612306/how-to-fix-importerror-dll-load-failed-while-importing-win32api

The pywin32 problem is a known issue in some versions of conda. You have to figure out which version of pywin32 you should have and likely have to reinstall it. 

Did we install ipykernel into this environment or was it already there?

**Comment by badjouras** [comment]
Downgrading pywin32 to version 225 using conda seems to have solved the issue. Now I'm getting a Numpy ImportError in one of the workspaces though, don't know what that is all about. I'm going to reinstall Numpy in conda and see if that fixes it.

**Comment by greazer** [comment]
@badjouras, please reactivate if you continue to have problems
