### ISSUE TITLE
jupyter notebook Not opening in VS-Code Insiders - Ubuntu 20.04 after latest update of Insider version 

### ISSUE THREAD

**Issue by rohan-paul** [microsoft/vscode-jupyter#5855]
Hi, Not sure if this issue would be handled by VS-Code's Repo Maintenaiers.

When I try to launch a .ipynb file getting below.

![image](https://user-images.githubusercontent.com/12703975/117974665-73b39480-b34b-11eb-91b8-3715cb1f1dbb.png)

My VS-Code version details

![image](https://user-images.githubusercontent.com/12703975/117974459-351dda00-b34b-11eb-81bd-4f2dff122567.png)

Have tried uninstalling-and-reinstalling Python and vscode-jupyter extensions, didn't help.

### After enabling Developer-Tool getting these details when double-clicking on an .ipynb file.

```
workbench.desktop.main.js:62 [Extension Host] extension activation failed TypeError: s.notebook.onDidChangeNotebookCellExecutionState is not a function
    at new d (/home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:90:450992)
    at Object.t.resolveInstance (/home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:263462)
    at /home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:262667
    at Array.map (<anonymous>)
    at Object.t.resolveInstance (/home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:263232)
    at /home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:262667
    at Array.map (<anonymous>)
    at Object.t.resolveInstance (/home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:263232)
    at /home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:262667
    at /home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:261615
    at Array.map (<anonymous>)
    at /home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:261587
    at Array.map (<anonymous>)
    at Object.t.resolveInstance (/home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:263232)
    at /home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:262667
    at Object.t.resolve (/home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:262930)
    at /home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:254027
    at e._get (/home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:253793)
    at e.get (/home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:252505)
    at a.get (/home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:90:505543)
    at /home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:52:246130
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:37:829501
    at t.activate (/home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:37:829188)
    at async Promise.all (index 0) (at /home/paul/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.834931520/out/client/extension.js:37:830020)

```

**Comment by melMass** [comment]
I think this is related, if not I'll open a separate issue.
Since the latest insider I have
![image](https://user-images.githubusercontent.com/7041726/117987801-1dd6f080-b33b-11eb-99d3-aca72ce8821b.png)

And this is the error in the Dev Tools:

```ruby
extension activation failed TypeError: s.notebook.onDidChangeNotebookCellExecutionState is not a function
```

**Comment by melMass** [comment]
I was not reading right, yes it's the same error!

**Comment by melMass** [comment]
There is something strange, the Jupyter extension got updated 4 times in the last hour...

![image](https://user-images.githubusercontent.com/7041726/117988777-03514700-b33c-11eb-9613-0f9cd9723764.png)

**Comment by jaymegordo** [comment]
+1 same issue as melMass, can't run jupyter at all

**Comment by phinate** [comment]
+1

**Comment by DonJayamanne** [comment]
I'm sorry you are running into this issue, please could you ensure you have updated to the latest version of VS Code Insiders.
VS Code shipped a breaking change and we had to ship a new version of the extension to accommodate those changes.

# Solution Please update VSCode Insiders to the latest version

**Comment by DonJayamanne** [comment]
Closing this issue for now, please feel feel to re-open or file a new issue if this persists.

**Comment by melMass** [comment]
@DonJayamanne Thanks! Yes it's working!

**Comment by DonJayamanne** [comment]
@melMass once again I'm sorry about this whole fiasco..
