### ISSUE TITLE
 "Kernel died with exit code 1" fail in activating env (#5689 )

### ISSUE THREAD

**Issue by BinhKieu82** [microsoft/vscode-jupyter#5943]
Hi community,
I got the error of "Kernel died with exit code 1" when executing codes on the interactive window. I see the similar issue #5689 reported, but it already closed and cannot reopen or comment. Sorry if it might be a duplicate
With thanks.

## Environment data

-   VS Code version: 1.56.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6
-   Python Extension version (available under the Extensions sidebar): v2021.5
-   OS (Windows | Mac | Linux distro) and version: Win10
-   Python and/or Anaconda version: 3.5.5/1.7.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local | Remote | Local

## Expected behaviour

I would expect the env is right activated that enable me executing my jupyter lines of code

## Actual behaviour

Kernel died with exit code 1. Traceback (most recent call last): 
File "c:\Users\username\.vscode\extensions\ms-toolsai.jupyter-2021.6.832593372\pythonFiles\vscode_datascience_helpers\..\pyvsc-run-isolated.py", line 30, in <module> runpy.run_path(module, run_name="__main__") File "C:\Users\username\anaconda3\envs\env_name\lib\runpy.py", line 263, in run_path pkg_name=pkg_name, script_name=fname) File "C:\Users\username\anaconda3\envs\env_name\lib\runpy.py", line 96, in _run_module_code mod_name, mod_spec, pkg_name, script_name) File "C:\Users\username\anaconda3\envs\env_name\lib\runpy.py", line 85, in _run_code exec(code, run_globals) File "c:\Users\username\.vscode\extensions\ms-toolsai.jupyter-2021.6.832593372\pythonFiles\vscode_datascience_helpers\kernel_prewarm_starter.py", line 31, in <module> runpy.run_module(module, run_name="__main__", alter_sys=False) File "C:\Users\username\anaconda3\envs\env_name\lib\runpy.py", line 208, in run_module retur...

**Comment by DonJayamanne** [comment]
@BinhKieu82 I'm sorry for not getting back to you, somehow I missed this issue.
We've been working on the code that starts kernels, and have removed the code `pyvsc-run-isolated.py`... hopefully that will resolve the issues.

Please could you install the latest insiders version of VS Code and then install Jupyter extension and let us know if this has been resolved.
Thanks

**Comment by BinhKieu82** [comment]
Hi DonJayamanne,
Here are my VScode info, it is the latest version with Jupyter extension version of _v2021.6.832593372_

> _Version: 1.56.2 (user setup)
> Commit: 054a9295330880ed74ceaedda236253b4f39a335
> Date: 2021-05-12T17:13:13.157Z
> Electron: 12.0.4
> Chrome: 89.0.4389.114
> Node.js: 14.16.0
> V8: 8.9.255.24-electron.0
> OS: Windows_NT x64 10.0.18362_

I still got the similar outcome, it seems encountering the same issue:
```
Kernel died with exit code 1. Traceback (most recent call last):
  File "c:\Users\user_name\.vscode\extensions\ms-toolsai.jupyter-2021.6.832593372\pythonFiles\vscode_datascience_helpers\..\pyvsc-run-isolated.py", line 30, in <module>
    runpy.run_path(module, run_name="__main__")
  File "C:\Users\user_name\anaconda3\envs\env_name\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\user_name\anaconda3\envs\env_name\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\user_name\anaconda3\envs\env_name\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\user_name\.vscode\extensions\ms-toolsai.jupyter-2021.6.832593372\pythonFiles\vscode_datascience_helpers\kernel_prewarm_starter.py", line 31, in <module>
    runpy.run_module(module, run_name="__main__", alter_sys=False)
  File "C:\Users\user_name\anaconda3\envs\env_name\lib\runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "C:\Users\user_name\anaconda3\envs\env_name\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user_name\anaconda3\envs\env_name\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\user_name\anaconda3\envs\env_name\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "C:\Users\user_name\anaconda3\envs\env_name\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\Users\user_name\anaconda3\envs\env_name\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\user_name\anaconda3\envs\env_name\lib\site-packages\ipykernel\kernelapp.py", line 472, in initialize
    self.write_connection_file()
  File "C:\Users\user_name\anaconda3\envs\env_name\lib\site-packages\ipykernel\kernelapp.py", line 200, in write_connection_file
    iopub_port=self.iopub_port, control_port=self.control_port)
  File "C:\Users\user_name\anaconda3\envs\env_name\lib\site-packages\jupyter_client\connect.py", line 212, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Users\user_name\anaconda3\envs\env_name\lib\contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "C:\Users\user_name\anaconda3\envs\env_name\lib\site-packages\jupyter_client\connect.py", line 102, in secure_write
    with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\user_name\\AppData\\Local\\Temp\\tmp-92041JghRKurSHL4.json'

```
I've thought it's because of using python 3.5.5 but event with higher python version (3.6), switching between envs still encounter problems like this _**Error: Direct kernel connection broken**_

Kindly advise the solution, it stop me from working so long.
With thanks - Binh Kieu

**Comment by DonJayamanne** [comment]
@BinhKieu82 For some reason u don't have the right version. Please could you install the latest insiders version of the extension once again & try this out.

**Comment by BinhKieu82** [comment]
@DonJayamanne 
What i have done so far:
installed VScode insider version: 
> Version: 1.57.0-insider (user setup)
> Commit: fe1eafc80c07608de52a2f9c99fee103dea77f5e
> Date: 2021-06-04T12:21:40.077Z
> Electron: 12.0.9
> Chrome: 89.0.4389.128
> Node.js: 14.16.0
> V8: 8.9.255.25-electron.0
> OS: Windows_NT x64 10.0.18362

install Jupyter extension version: v2021.6.905800020
installed python extension version: v2021.6.908196464-dev

But still not able to switch to env with python 3.5.5, the error message seems the same:
> Kernel died with exit code 1. Traceback (most recent call last):
>   File "C:\Users\user_name\anaconda3\envs\env-p35\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "C:\Users\user_name\anaconda3\envs\env-p35\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\user_name\anaconda3\envs\env-p35\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
>     app.launch_new_instance()
>   File "C:\Users\user_name\anaconda3\envs\env-p35\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
>     app.initialize(argv)
>   File "C:\Users\user_name\anaconda3\envs\env-p35\lib\site-packages\decorator.py", line 232, in fun
>     return caller(func, *(extras + args), **kw)
>   File "C:\Users\user_name\anaconda3\envs\env-p35\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
>     return method(app, *args, **kwargs)
>   File "C:\Users\user_name\anaconda3\envs\env-p35\lib\site-packages\ipykernel\kernelapp.py", line 472, in initialize
>     self.write_connection_file()
>   File "C:\Users\user_name\anaconda3\envs\env-p35\lib\site-packages\ipykernel\kernelapp.py", line 200, in write_connection_file
>     iopub_port=self.iopub_port, control_port=self.control_port)
>   File "C:\Users\user_name\anaconda3\envs\env-p35\lib\site-packages\jupyter_client\connect.py", line 212, in write_connection_file
>     with secure_write(fname) as f:
>   File "C:\Users\user_name\anaconda3\envs\env-p35\lib\contextlib.py", line 59, in __enter__
>     return next(self.gen)
>   File "C:\Users\user_name\anaconda3\envs\env-p35\lib\site-packages\jupyter_client\connect.py", line 100, in secure_write
>     win32_restrict_file_to_user(fname)
>   File "C:\Users\user_name\anaconda3\envs\env-p35\lib\site-packages\jupyter_client\connect.py", line 53, in win32_restrict_file_to_user
>     import win32api
> ImportError: No module named 'win32api'

I also updated the latest version of VScode, jupyter & python extensions on VSCode official platform, but still not able to switch to env with python 3.5.5
Kindly share your thought.
Regards - Binh Kieu

**Comment by DonJayamanne** [comment]
Please try running the following against your Conda environment after activating it
`conda install ipykernel -U --force-reinstall`

**Comment by BinhKieu82** [comment]
I already installed ipykernel before, however, after running your command, the error came as:
> SafetyError: The package for ipykernel located at C:\Users\username\anaconda3\pkgs\ipykernel-4.10.0-py35_1
> appears to be corrupted. The path 'Scripts/jupyter-kernel-script.py'
> has an incorrect size.

Here is the ipykernel installed: _ipykernel                 4.10.0                   py35_1    conda-forge_
conda version is 4.8.4. I tried to upgrade to the latest 4.10.1 but no success.
The final outcome still the same, not able to switch to the env with python 3.5 in VScode. 
BTW, i don't want to use VScode insider, then I've tried both `conda install ipykernel --update-deps --force-reinstall` and `conda install ipykernel --update-all --force-reinstall
` on VScode

**Comment by DonJayamanne** [comment]
Hmm, at this stage not sure what I can do.
Please could you try running Jupyter in that environment. Basically your python environment doesn't seem to be setup propertly for Jupyter Kernels.
Please could you confirm it works with classic Jupyter. 
Else I'd suggest trying to create a new environment.

**Comment by BinhKieu82** [comment]
Hi, it seems envs switching work normal now. I don't know what exactly has been happened, but you can close this ticket.
Thank you for your great effort!
