### ISSUE TITLE
Unable to select kernel to run Python code

### ISSUE THREAD

**Issue by RobMOwen** [microsoft/vscode-jupyter#6040]
## Environment data

-   VS Code version: Insiders 1.57.0
-   Jupyter Extension version: v2021.6.892431424
-   Python Extension version: v2021.6.864643163-dev
-   OS: Windows 10
-   Python and/or Anaconda version: Python 3.9.5
-   Jupyter server running: Local

## Expected behaviour

When I run a cell (ctrl + enter) I'd expect to see the result underneath

## Actual behaviour

A text input bar appears at the top of the page asking to "select kernel for EXAMPLE.ipynb
If I enter something (assuming I'm meant to select a Python kernel?) nothing happens. Autocomplete doesn't work and there are no suggestions. 

## Steps to reproduce:

1. Write a simple bit of code in a shell - print("hello world")
2. It with Ctrl + enter
3. Notice the top bar asks you to select kernal
4. Notice that you can't select a kernel

**Comment by joyceerhl** [comment]
@RobMOwen If you open a Python file and run the Python: Select Interpreter command in the command palette, then select your Python 3.9.5 environment, does autocomplete work?

When you are asked to select a kernel, does a dropdown appear with a list of kernels that you can choose from? And are you saying that if you pick one of those kernels, nothing happens (the kernel is not selected)?

Could you please provide the contents of the Jupyter output panel? That contains detailed logging which might help us debug this issue. The output panel can be found here:

![image](https://user-images.githubusercontent.com/30305945/120255653-53d40a00-c241-11eb-9930-8ba2e5ede65d.png)

**Comment by RobMOwen** [comment]
> @RobMOwen If you open a Python file and run the Python: Select Interpreter command in the command palette, then select your Python 3.9.5 environment, does autocomplete work?

It does yes. It give me two options in this project - one in my Poetry path and one in `Program Files..`

![image](https://user-images.githubusercontent.com/59659109/120288030-b667ed00-c2b7-11eb-941f-df347c52d960.png)

If I select one, then run the cell (ctrl + enter) it prompts me to select the kernal again. This input box doesn't autocomplete:

![image](https://user-images.githubusercontent.com/59659109/120288630-54f44e00-c2b8-11eb-861e-0bd9e9158abb.png)

I tried manually pasting in the path (e.g. `C:\Program Files\Python39\python.exe`) but got the same result.

> Could you please provide the contents of the Jupyter output panel?
Here it is (there's no updated when I run the cell)
```
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'jupyterEnhancedDataViewer'
User belongs to experiment group 'NativeNotebookEditor'
Info 2021-06-01 09:17:20: ZMQ install verified.
Info 2021-06-01 09:17:20: Attempting to start a server because of preload conditions ...
Info 2021-06-01 09:17:20: Found existing keyfile at c:\Users\rob.owen\AppData\Roaming\Code - Insiders\User\globalStorage\ms-toolsai.jupyter\nbsecret
Info 2021-06-01 09:17:20: Check if Notebook is Trusted, Class name = p, completed in 0ms, has a truthy return value, Return Value: true
Info 2021-06-01 09:17:20: Cached data exists getEnvironmentVariables, <No Resource>
Info 2021-06-01 09:17:20: Attempting to start a server because of preload conditions ...
Info 2021-06-01 09:17:21: notebook communications already initialized for editor file:///c%3A/Users/rob.owen/GIT/zammad-insights/notebooks/examples.ipynb
Info 2021-06-01 09:17:26: Search all interpreters C:\Program Files\Python39\python.exe, C:\Users\rob.owen\AppData\Local\pypoetry\Cache\virtualenvs\zammad-insights-UGpSG7eu-py3.9\Scripts\python.exe
Info 2021-06-01 09:17:26: Search all interpreters C:\Program Files\Python39\python.exe, C:\Users\rob.owen\AppData\Local\pypoetry\Cache\virtualenvs\zammad-insights-UGpSG7eu-py3.9\Scripts\python.exe
Info 2021-06-01 09:17:26: Loading kernelspec from C:\Users\rob.owen\AppData\Local\pypoetry\Cache\virtualenvs\zammad-insights-UGpSG7eu-py3.9\share\jupyter\kernels\python3\kernel.json for C:\Users\rob.owen\AppData\Local\pypoetry\Cache\virtualenvs\zammad-insights-UGpSG7eu-py3.9\Scripts\python.exe
Info 2021-06-01 09:17:26: Process Execution: > ~\AppData\Local\pypoetry\Cache\virtualenvs\zammad-insights-UGpSG7eu-py3.9\Scripts\python.exe -c "import jupyter"
> ~\AppData\Local\pypoetry\Cache\virtualenvs\zammad-insights-UGpSG7eu-py3.9\Scripts\python.exe -c "import jupyter"
Info 2021-06-01 09:17:26: Process Execution: > ~\AppData\Local\pypoetry\Cache\virtualenvs\zammad-insights-UGpSG7eu-py3.9\Scripts\python.exe -c "import notebook"
> ~\AppData\Local\pypoetry\Cache\virtualenvs\zammad-insights-UGpSG7eu-py3.9\Scripts\python.exe -c "import notebook"
Info 2021-06-01 09:17:26: Process Execution: > ~\AppData\Local\pypoetry\Cache\virtualenvs\zammad-insights-UGpSG7eu-py3.9\Scripts\python.exe -c "import ipykernel"
> ~\AppData\Local\pypoetry\Cache\virtualenvs\zammad-insights-UGpSG7eu-py3.9\Scripts\python.exe -c "import ipykernel"
Info 2021-06-01 09:17:27: Process Execution: > ~\AppData\Local\pypoetry\Cache\virtualenvs\zammad-insights-UGpSG7eu-py3.9\Scripts\python.exe -m pip list
> ~\AppData\Local\pypoetry\Cache\virtualenvs\zammad-insights-UGpSG7eu-py3.9\Scripts\python.exe -m pip list
Info 2021-06-01 09:17:27: Kernel python395jvsc74a57bd0dedfe49aca034b433a445a3f928b1d5299caba939b718290b264f84336f28976 matches Python 3.9.5 64-bit ('zammad-insights-UGpSG7eu-py3.9': venv) based on interpreter path.
Info 2021-06-01 09:17:27: Kernel python395jvsc74a57bd0dedfe49aca034b433a445a3f928b1d5299caba939b718290b264f84336f28976 matches Python 3.9.5 64-bit ('zammad-insights-UGpSG7eu-py3.9': venv) based on interpreter path.
Info 2021-06-01 09:17:27: findPreferredKernel score for Python3, Python 3.9.5 64-bit ('zammad-insights-UGpSG7eu-py3.9': venv) is 4
Info 2021-06-01 09:17:27: findPreferredKernel score for Python 3.9.5 64-bit ('zammad-insights-UGpSG7eu-py3.9': venv) is 4
Info 2021-06-01 09:17:27: findPreferredKernel score for Python3, Python 3.9.5 64-bit is 104
Info 2021-06-01 09:17:27: findPreferredKernel score for Python 3.9.5 64-bit is 104
Info 2021-06-01 09:17:27: findKernel found Python 3.9.5 64-bit
Error 2021-06-01 09:17:27: Failed to create notebbook controller for .jvsc74a57bd0ac59ebe37160ed0dfa835113d9b8498d9f09ceb179beaac4002f036b9467c963.C:\Program Files\Python39\python.exe.C:\Program Files\Python39\python.exe [TypeError: i.NotebookRendererScript is not a constructor
	at c:\Users\rob.owen\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.892431424\out\client\extension.js:90:355069
	at Array.map (<anonymous>)
	at f.getRendererScripts (c:\Users\rob.owen\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.892431424\out\client\extension.js:90:355062)
	at new f (c:\Users\rob.owen\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.892431424\out\client\extension.js:90:352263)
	at M.createNotebookController (c:\Users\rob.owen\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.892431424\out\client\extension.js:90:348118)
	at c:\Users\rob.owen\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.892431424\out\client\extension.js:90:348012
	at Array.forEach (<anonymous>)
	at M.createNotebookControllers (c:\Users\rob.owen\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.892431424\out\client\extension.js:90:347987)
	at M.loadNotebookControllers (c:\Users\rob.owen\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.892431424\out\client\extension.js:90:346034)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)]
Error 2021-06-01 09:17:27: Failed to create notebbook controller for .jvsc74a57bd0dedfe49aca034b433a445a3f928b1d5299caba939b718290b264f84336f28976.C:\Users\rob.owen\AppData\Local\pypoetry\Cache\virtualenvs\zammad-insights-UGpSG7eu-py3.9\Scripts\python.exe.C:\Users\rob.owen\AppData\Local\pypoetry\Cache\virtualenvs\zammad-insights-UGpSG7eu-py3.9\Scripts\python.exe [TypeError: i.NotebookRendererScript is not a constructor
	at c:\Users\rob.owen\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.892431424\out\client\extension.js:90:355069
	at Array.map (<anonymous>)
	at f.getRendererScripts (c:\Users\rob.owen\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.892431424\out\client\extension.js:90:355062)
	at new f (c:\Users\rob.owen\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.892431424\out\client\extension.js:90:352263)
	at M.createNotebookController (c:\Users\rob.owen\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.892431424\out\client\extension.js:90:348118)
	at c:\Users\rob.owen\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.892431424\out\client\extension.js:90:348012
	at Array.forEach (<anonymous>)
	at M.createNotebookControllers (c:\Users\rob.owen\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.892431424\out\client\extension.js:90:347987)
	at M.loadNotebookControllers (c:\Users\rob.owen\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.892431424\out\client\extension.js:90:346034)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)]
Info 2021-06-01 09:17:27: Find kernel spec, Class name = D, completed in 6403ms, has a truthy return value, Arg 1: <Uri:c:\Users\rob.owen\GIT\zammad-insights\notebooks\examples.ipynb>, Arg 2: {"interpreter":{"hash":"ac59ebe37160ed0dfa835113d9b8498d9f09ceb179beaac4002f036b9467c963"},"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.5"}}, Arg 3: {"_isCancelled":false,"_emitter":null}, Return Value: {"kind":"startUsingPythonInterpreter","kernelSpec":{"specFile":"C:\\Users\\rob.owen\\AppData\\Roaming\\jupyter\\kernels\\python395jvsc74a57bd0ac59ebe37160ed0dfa835113d9b8498d9f09ceb179beaac4002f036b9467c963\\kernel.json","interpreterPath":"C:\\Program Files\\Python39\\python.exe","name":"python395jvsc74a57bd0ac59ebe37160ed0dfa835113d9b8498d9f09ceb179beaac4002f036b9467c963","argv":["python","-m","ipykernel_launcher","-f","{connection_file}"],"language":"python","path":"python","display_name":"Python 3.9.5 64-bit","metadata":{"interpreter":{"sysPrefix":"C:\\Program Files\\Python39","envType":"Unknown","envName":"","envPath":"","path":"C:\\Program Files\\Python39\\python.exe","architecture":3,"sysVersion":"3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]","version":{"raw":"3.9.5","major":3,"minor":9,"patch":5,"build":[],"prerelease":["final","0"]},"companyDisplayName":"PythonCore","displayName":"Python 3.9.5 64-bit"}},"env":{}},"interpreter":{"sysPrefix":"C:\\Program Files\\Python39","envType":"Unknown","envName":"","envPath":"","path":"C:\\Program Files\\Python39\\python.exe","architecture":3,"sysVersion":"3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]","version":{"raw":"3.9.5","major":3,"minor":9,"patch":5,"build":[],"prerelease":["final","0"]},"companyDisplayName":"PythonCore","displayName":"Python 3.9.5 64-bit"},"id":".jvsc74a57bd0ac59ebe37160ed0dfa835113d9b8498d9f09ceb179beaac4002f036b9467c963.C:\\Program Files\\Python39\\python.exe.C:\\Program Files\\Python39\\python.exe"}
Info 2021-06-01 09:17:27: PreferredConnection: .jvsc74a57bd0ac59ebe37160ed0dfa835113d9b8498d9f09ceb179beaac4002f036b9467c963.C:\Program Files\Python39\python.exe.C:\Program Files\Python39\python.exe found for NotebookDocument: file:///c%3A/Users/rob.owen/GIT/zammad-insights/notebooks/examples.ipynb
Info 2021-06-01 09:17:27: Process Execution: > ~\AppData\Local\pypoetry\Cache\virtualenvs\zammad-insights-UGpSG7eu-py3.9\Scripts\python.exe -m jupyter kernelspec --version
> ~\AppData\Local\pypoetry\Cache\virtualenvs\zammad-insights-UGpSG7eu-py3.9\Scripts\python.exe -m jupyter kernelspec --version
Info 2021-06-01 09:17:28: Creating daemon pool for C:\Users\rob.owen\AppData\Local\pypoetry\Cache\virtualenvs\zammad-insights-UGpSG7eu-py3.9\Scripts\python.exe with env variables count 75
Info 2021-06-01 09:17:28: Process Execution: > ~\AppData\Local\pypoetry\Cache\virtualenvs\zammad-insights-UGpSG7eu-py3.9\Scripts\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> ~\AppData\Local\pypoetry\Cache\virtualenvs\zammad-insights-UGpSG7eu-py3.9\Scripts\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
Info 2021-06-01 09:17:28: Process Execution: > ~\AppData\Local\pypoetry\Cache\virtualenvs\zammad-insights-UGpSG7eu-py3.9\Scripts\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> ~\AppData\Local\pypoetry\Cache\virtualenvs\zammad-insights-UGpSG7eu-py3.9\Scripts\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
Info 2021-06-01 09:17:28: Process Execution: > ~\AppData\Local\pypoetry\Cache\virtualenvs\zammad-insights-UGpSG7eu-py3.9\Scripts\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> ~\AppData\Local\pypoetry\Cache\virtualenvs\zammad-insights-UGpSG7eu-py3.9\Scripts\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
Info 2021-06-01 09:17:29: Creating daemon process for C:\Users\rob.owen\AppData\Local\pypoetry\Cache\virtualenvs\zammad-insights-UGpSG7eu-py3.9\Scripts\python.exe with env variables count 75
Info 2021-06-01 09:17:29: Process Execution: > ~\AppData\Local\pypoetry\Cache\virtualenvs\zammad-insights-UGpSG7eu-py3.9\Scripts\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> ~\AppData\Local\pypoetry\Cache\virtualenvs\zammad-insights-UGpSG7eu-py3.9\Scripts\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Info 2021-06-01 09:17:29: Python Daemon (pid: 24980): Execute rpc method prewarm_kernel in DS Daemon
Info 2021-06-01 09:17:29: Python Daemon (pid: 24980): Execute rpc method prewarm_kernel from C:\Users\rob.owen\AppData\Local\pypoetry\Cache\virtualenvs\zammad-insights-UGpSG7eu-py3.9\Scripts\python.exe
Info 2021-06-01 09:17:29: Python Daemon (pid: 24980): Pre-Warm DS Kernel in DS Kernel Launcher Daemon
Info 2021-06-01 09:17:29: Python Daemon (pid: 24980): Exec in DS Kernel Launcher Daemon (observable) ['C:\\Users\\rob.owen\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\zammad-insights-UGpSG7eu-py3.9\\Scripts\\python.exe', 'c:\\Users\\rob.owen\\.vscode-insiders\\extensions\\ms-toolsai.jupyter-2021.6.892431424\\pythonFiles\\vscode_datascience_helpers\\kernel_prewarm_starter.py']
Info 2021-06-01 09:17:29: Python Daemon (pid: 24980): Exec in DS Kernel Launcher Daemon (observable)
Info 2021-06-01 09:17:29: Python Daemon (pid: 24980): Kernel launched, with PID 4708
Warn 2021-06-01 09:17:29: Python Daemon (pid: 24980): Waiting for Kernel to die 4708
Info 2021-06-01 09:17:29: Python Daemon (pid: 24980): Kernel launched, with PID as a daemon 4708

```

**Comment by joyceerhl** [comment]
I believe that's happening because you have a pending VS Code Insiders update. What's the commit associated with your VS Code Insiders build? It should be this: 1e446dfadf588ec28b3fdba7ac083bfa1d45df3c

Please ensure you haven't disabled updates in your VS Code settings (setting name is "update.mode"), then check if you have a pending VS Code Insiders update. If you do, the Check For Updates entry in the help menu should instead say Restart To Update or Downloading Update:
![image](https://user-images.githubusercontent.com/30305945/120292147-e774fd00-c278-11eb-8262-31c20acddcce.png)

You may need to restart VS Code Insiders for the update to take. After that this issue should go away.

**Comment by greazer** [comment]
@RobMOwen, please reopen if the issue isn't resolved after updating per Joyce's instructions.
