### ISSUE TITLE
extension activation failed [TypeError: this.vscodeNotebook.onDidOpenNotebookDocument is not a function

### ISSUE THREAD

**Issue by mage1k99** [microsoft/vscode-jupyter#6095]
Version: 1.57.0-insider (user setup)
Commit: c324c61ad572be43a8696780e1aba3c1a2c46eee
Date: 2021-06-02T17:38:06.137Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: 

## Environment data

-   VS Code version: 1.57.0-insider (user setup)
-   Jupyter Extension version (available under the Extensions sidebar): v2021.5.842923320
-   Python Extension version (available under the Extensions sidebar): v2021.6.902307158
-   OS: Windows 10 x64 and version: 10.0.19042
-   Python and/or Anaconda version: 3.8.2
-   Type of virtual environment used venv
-   Jupyter server running: N/A

## Expected behaviour

Jupyter Not causing any issues with python extension and not causing extension host to crash.

## Actual behaviour

Extension Activation fails due to TypeError, and extensions fails to activated

## Steps to reproduce:

1. Updated the VSCode -Insider
2.  Extension loads, when loading python extension
3. Due to Jupyter fails , the whole extension python fails to load

## Logs

<details>

<summary>
Here are logs
</summary>

<p>

```
Error 2021-06-03 16:55:34: extension activation failed [TypeError: this.vscodeNotebook.onDidOpenNotebookDocument is not a function
	at new E (c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:90:287467)
	at Object.t.resolveInstance (c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:263462)
	at c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:262667
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:263232)
	at c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:262667
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:263232)
	at c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:262667
	at Object.t.resolve (c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:262930)
	at c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:254027
	at e._get (c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:253793)
	at e.get (c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:252505)
	at e.dynamicValue (c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:265671)
	at c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:262156
	at c (c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:261202)
	at c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:262096
	at c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:261615
	at Array.map (<anonymous>)
	at c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:261587
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:263232)
	at c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:262667
	at Object.t.resolve (c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:262930)
	at c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:254027
	at e._get (c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:253793)
	at e.get (c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:252505)
	at a.get (c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:90:516226)
	at c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:52:246130
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:37:826464
	at async t.activate (c:\Users\Mag\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.902307158\out\client\extension.js:37:826151)
	at async Promise.all (index 0)
	at async Promise.all (index 101)
	at async Promise.all (index 1)] {
  vslsStack: [
    CallSite {}, CallSite {}, CallSite {},
    CallSite {}, CallSite {}, CallSite {},
    CallSite {}, CallSite {}, CallSite {},
    CallSite {}, CallSite {}, CallSite {},
    CallSite {}, CallSite {}, CallSite {},
    CallSite {}, CallSite {}, CallSite {},
    CallSite {}, CallSite {}, CallSite {},
    CallSite {}, CallSite {}, CallSite {},
    CallSite {}, CallSite {}, CallSite {},
    CallSite {}, CallSite {}, CallSite {},
    CallSite {}, CallSite {}, CallSite {},
    CallSite {}, CallSite {}
  ]
}
```

</p>
</details>

**Comment by IanMatthewHuff** [comment]
@mage1k99 Hey there. The Jupyter extension in insiders sometimes needs to update to take breaking incoming changes from VS Code. The error that you are seeing looks like you have the new Jupyter, but you don't yet have today's build of VS Code - insiders. The commit should end with ad2a5 for the current insiders. Can you please try updating VSCode - insiders and try again?

**Comment by mage1k99** [comment]
Yes the issue is with new version, when I installed newer one there are no issues.

Hey I have Installed v2021.6.902307158,

Vscode Insiders says there are no updates, so manually downloaded and installed to check if the version got updated but its not updated.

Current commit has ended with eee46 (c324c61ad572be43a8696780e1aba3c1a2c46eee)

**Comment by joyceerhl** [comment]
@mage1k99 There is a new VS Code Insiders build which became available about 10 min ago. Could you please try downloading that, restarting VS Code, and trying again?

**Comment by mage1k99** [comment]
Yes, received it. Jupyter issue got fixed.

thanks for the support :)

closing the issue.
