### ISSUE TITLE
Fix visibleNotebookEditor test code issue in python enlistment

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#6101]
https://github.com/microsoft/vscode-jupyter/pull/6100

Per the PR above looks like python has this in the test code as well. Might break their tests so we should fix ASAP.

**Comment by joyceerhl** [comment]
Go to definition is currently broken in insiders as well. Will fix as part of this issue.

```
Error 2021-06-03 10:12:00: Starting language server, Class name = r, completed in 1ms, has a falsy return value, , Return Value: undefined TypeError: Cannot read property 'onDidOpenNotebookDocument' of undefined
    at l.get onDidOpenNotebookDocument [as onDidOpenNotebookDocument] (c:\Users\huer\.vscode-insiders\extensions\ms-python.python-2021.6.897246044-dev\out\client\extension.js:78:180756)
    at new a (c:\Users\huer\.vscode-insiders\extensions\ms-python.python-2021.6.897246044-dev\out\client\extension.js:59:183978)
    at new t.NotebookMiddlewareAddon (c:\Users\huer\.vscode-insiders\extensions\ms-python.python-2021.6.897246044-dev\out\client\extension.js:59:178815)
    at new y (c:\Users\huer\.vscode-insiders\extensions\ms-python.python-2021.6.897246044-dev\out\client\extension.js:9:446239)
    at r.startLanguageServer (c:\Users\huer\.vscode-insiders\extensions\ms-python.python-2021.6.897246044-dev\out\client\extension.js:59:240168)
```

**Comment by joyceerhl** [comment]
Opened a new issue for that: https://github.com/microsoft/vscode-jupyter/issues/6108

**Comment by IanMatthewHuff** [comment]
Validated. Via python tests not being broken.
