### ISSUE TITLE
Code in notebook cells sometimes renders as math symbols

### ISSUE THREAD

**Issue by kycutler** [microsoft/vscode-jupyter#6123]
## Environment data

-   VS Code version: 1.56.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.832593372
-   Python Extension version (available under the Extensions sidebar): v2021.5.842923320
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: N/A
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

Code should always be rendered as-is in plain text

## Actual behaviour

Code sometimes renders as math symbols

## Steps to reproduce:

1. Download this notebook: https://github.com/aamini/introtodeeplearning/blob/master/lab1/Part1_TensorFlow.ipynb
2. Open the file in the notebook editor and look at the third code cell:
  ![image](https://user-images.githubusercontent.com/67761731/120722050-e6fc8200-c483-11eb-88ce-bd5bd5c8789c.png)

Note the math rendering at the beginning of the `print()` statements. The plain code looks like this:
```python
sport = tf.constant("Tennis", tf.string)
number = tf.constant(1.41421356237, tf.float64)

print("`sport` is a {}-d Tensor".format(tf.rank(sport).numpy()))
print("`number` is a {}-d Tensor".format(tf.rank(number).numpy()))
```

This only happens in notebooks.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
User belongs to experiment group 'pythonJoinMailingListVar3'
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'pythonSurveyNotificationcf'
User belongs to experiment group 'jupyterEnhancedDataViewer'
Info 2021-06-03 16:19:23: ZMQ install verified.
Info 2021-06-03 16:19:23: id is 17963ce4-dfa5-44dc-a6e3-babeef0ad45d
Info 2021-06-03 16:19:23: Found existing keyfile at c:\Users\kycutler\AppData\Roaming\Code\User\globalStorage\ms-toolsai.jupyter\nbsecret
Info 2021-06-03 16:19:25: Search all interpreters 
Info 2021-06-03 16:19:31: Check if Notebook is Trusted, Class name = p, completed in 0ms, has a truthy return value, Return Value: true
Info 2021-06-03 16:19:31: Loading web panel for file:///c%3A/Users/kycutler/Downloads/top100/Part1_TensorFlow.ipynb
Info 2021-06-03 16:19:31: Loading webview. View is notset
Info 2021-06-03 16:19:31: Attempting to start a server because of preload conditions ...
Info 2021-06-03 16:19:31: Loading web view...
Info 2021-06-03 16:19:31: Webview panel created.
Info 2021-06-03 16:19:31: Creating raw notebook for file:///c%3A/Users/kycutler/Downloads/top100/Part1_TensorFlow.ipynb
Info 2021-06-03 16:19:31: Getting preferred kernel for file:///c%3A/Users/kycutler/Downloads/top100/Part1_TensorFlow.ipynb
Info 2021-06-03 16:19:31: Cached data exists getEnvironmentVariables, <No Resource>
Info 2021-06-03 16:19:31: Search all interpreters 
Info 2021-06-03 16:19:31: initialize CommonMessageCoordinator
Info 2021-06-03 16:19:31: Find kernel spec, Class name = x, completed in 150ms, has a falsy return value, Arg 1: <Uri:c:\Users\kycutler\Downloads\top100\Part1_TensorFlow.ipynb>, Arg 2: {"colab":{"name":"Part1_TensorFlow.ipynb","provenance":[],"collapsed_sections":["WBk0ZDWY-ff8"]},"kernelspec":{"name":"python3","display_name":"Python 3"},"accelerator":"GPU"}, Arg 3: undefined, Return Value: undefined
Info 2021-06-03 16:19:31: Computing working directory file:///c%3A/Users/kycutler/Downloads/top100/Part1_TensorFlow.ipynb
Error 2021-06-03 16:19:31: Failed to determine if a notebook is active for the current editor [i [Error]: Failed to find a kernelspec to use for ipykernel launch
	at w.createNotebookInstance (c:\Users\kycutler\.vscode\extensions\ms-toolsai.jupyter-2021.6.832593372\out\client\extension.js:90:441018)] {
  category: 'kernelspecnotfound'
}
Error 2021-06-03 16:19:31: DataScience Error [i [Error]: Failed to find a kernelspec to use for ipykernel launch
	at w.createNotebookInstance (c:\Users\kycutler\.vscode\extensions\ms-toolsai.jupyter-2021.6.832593372\out\client\extension.js:90:441018)] {
  category: 'kernelspecnotfound'
}
Error 2021-06-03 16:19:31: DataScience Error [i [Error]: Failed to find a kernelspec to use for ipykernel launch
	at w.createNotebookInstance (c:\Users\kycutler\.vscode\extensions\ms-toolsai.jupyter-2021.6.832593372\out\client\extension.js:90:441018)] {
  category: 'kernelspecnotfound'
}
Error 2021-06-03 16:19:31: Failed to initialize ipywidgetHandler [i [Error]: Failed to find a kernelspec to use for ipykernel launch
	at w.createNotebookInstance (c:\Users\kycutler\.vscode\extensions\ms-toolsai.jupyter-2021.6.832593372\out\client\extension.js:90:441018)] {
  category: 'kernelspecnotfound'
}
Info 2021-06-03 16:19:32: Web view react rendered
Info 2021-06-03 16:19:32: Request for onigasm file at c:\Users\kycutler\.vscode\extensions\ms-toolsai.jupyter-2021.6.832593372\out\client\node_modules\onigasm\lib\onigasm.wasm
Info 2021-06-03 16:19:32: Request for tmlanguage file.
Info 2021-06-03 16:19:32: Searching for token colors ...
Info 2021-06-03 16:19:32: Attempting search for colors ...
Info 2021-06-03 16:19:32: Searching for token colors ...
Info 2021-06-03 16:19:32: Attempting search for colors ...
Info 2021-06-03 16:19:32: Searching for token colors ...
Info 2021-06-03 16:19:32: Attempting search for colors ...
Info 2021-06-03 16:19:32: Searching for token colors ...
Info 2021-06-03 16:19:32: Attempting search for colors ...
Info 2021-06-03 16:19:33: Searching for token colors ...
Info 2021-06-03 16:19:33: Attempting search for colors ...
Info 2021-06-03 16:19:33: Loading colors from c:\Users\kycutler\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\dark_plus.json ...
Info 2021-06-03 16:19:33: Loading colors from c:\Users\kycutler\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\dark_plus.json ...
Info 2021-06-03 16:19:33: Loading colors from c:\Users\kycutler\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\dark_plus.json ...
Info 2021-06-03 16:19:33: Searching for token colors ...
Info 2021-06-03 16:19:33: Attempting search for colors ...
Info 2021-06-03 16:19:33: Loading colors from c:\Users\kycutler\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\dark_plus.json ...
Info 2021-06-03 16:19:33: Searching for token colors ...
Info 2021-06-03 16:19:33: Attempting search for colors ...
Info 2021-06-03 16:19:33: Loading colors from c:\Users\kycutler\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\dark_plus.json ...
Info 2021-06-03 16:19:33: Loading colors from c:\Users\kycutler\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\dark_plus.json ...
Info 2021-06-03 16:19:33: Searching for token colors ...
Info 2021-06-03 16:19:33: Attempting search for colors ...
Info 2021-06-03 16:19:33: Loading colors from c:\Users\kycutler\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\dark_plus.json ...
Info 2021-06-03 16:19:33: Loading colors from c:\Users\kycutler\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\dark_plus.json ...
Info 2021-06-03 16:19:33: Attempting search for colors ...
Info 2021-06-03 16:19:33: Attempting search for colors ...
Info 2021-06-03 16:19:33: Loading base colors from c:\Users\kycutler\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\dark_plus.json ...
Info 2021-06-03 16:19:33: Loading base colors from c:\Users\kycutler\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\dark_plus.json ...
Info 2021-06-03 16:19:33: Attempting search for colors ...
Info 2021-06-03 16:19:33: Attempting search for colors ...
Info 2021-06-03 16:19:33: Loading base colors from c:\Users\kycutler\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\dark_plus.json ...
Info 2021-06-03 16:19:33: Loading base colors from c:\Users\kycutler\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\dark_plus.json ...
Info 2021-06-03 16:19:33: Attempting search for colors ...
Info 2021-06-03 16:19:33: Attempting search for colors ...
Info 2021-06-03 16:19:33: Loading base colors from c:\Users\kycutler\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\dark_plus.json ...
Info 2021-06-03 16:19:33: Loading base colors from c:\Users\kycutler\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\dark_plus.json ...
Info 2021-06-03 16:19:33: Attempting search for colors ...
Info 2021-06-03 16:19:33: Attempting search for colors ...
Info 2021-06-03 16:19:33: Loading base colors from c:\Users\kycutler\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\dark_plus.json ...
Info 2021-06-03 16:19:33: Loading base colors from c:\Users\kycutler\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\dark_plus.json ...
Info 2021-06-03 16:19:33: Using colors to generate CSS ...
Info 2021-06-03 16:19:33: Using colors to generate CSS ...
Info 2021-06-03 16:19:33: Using colors to generate CSS ...
Info 2021-06-03 16:19:33: Using colors to generate CSS ...
Info 2021-06-03 16:19:33: Using colors to generate CSS ...
Info 2021-06-03 16:19:33: Using colors to generate CSS ...
Info 2021-06-03 16:19:33: Using colors to generate CSS ...
Info 2021-06-03 16:19:33: Using colors to generate CSS ...
```

</p>
</details>

**Comment by DonJayamanne** [comment]
@kycutler Thanks for reporting this issue.
Please could you try installing the VS Code Insiders version and letting us know how that works.
FYI - we're working on a new Notebook Interface and expect that to be rolled out soon (replacing the current UI).

**Comment by DavidKutu** [comment]
@kycutler, you can try the new notebook interface in stable by following these steps: https://github.com/microsoft/vscode-jupyter/wiki/Native-Notebook-Support-in-VS-Code

Please open a new issue if the bug persists on the new interface.
