### ISSUE TITLE
Jupyter Extension activation failed

### ISSUE THREAD

**Issue by ttSpace** [microsoft/vscode-jupyter#6127]
## Environment data

![image](https://user-images.githubusercontent.com/82852072/120737116-1365dc00-c520-11eb-887e-6fae783eb327.png)

## Expected behaviour

No error pops up.

## Actual behaviour

![image](https://user-images.githubusercontent.com/82852072/120737206-3b553f80-c520-11eb-9564-0456aeb18ed7.png)

## Steps to reproduce:

Do something for unittest. 

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
(node:8252) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Code - Insiders --trace-deprecation ...` to show where the warning was created) 
Extension activation failed, run the 'Developer: Toggle Developer Tools' command for more information.
onDidChangeNotification @ notificationsAlerts.ts:40

extension activation failed TypeError: this.vscodeNotebook.onDidOpenNotebookDocument is not a function
	at new E (c:\Users\vting\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.7.900356923-rc\out\client\extension.js:90:287366)
	at Object.t.resolveInstance (c:\Users\vting\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.7.900356923-rc\out\client\extension.js:52:263462)
	at c:\Users\vting\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.7.900356923-rc\out\client\extension.js:52:262667
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (c:\Users\vting\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.7.900356923-rc\out\client\extension.js:52:263232)
	at c:\Users\vting\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.7.900356923-rc\out\client\extension.js:52:262667
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (c:\Users\vting\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.7.900356923-rc\out\client\extension.js:52:263232)
	at c:\Users\vting\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.7.900356923-rc\out\client\extension.js:52:262667
	at Object.t.resolve (c:\Users\vting\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.7.900356923-rc\out\client\extension.js:52:262930)
	at c:\Users\vting\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.7.900356923-rc\out\client\extension.js:52:254027
	at e._get (c:\Users\vting\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.7.900356923-rc\out\client\extension.js:52:253793)
	at e.get (c:\Users\vting\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.7.900356923-rc\out\client\extension.js:52:252505)
	at e.dynamicValue (c:\Users\vting\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.7.900356923-rc\out\client\extension.js:52:265671)
	at c:\Users\vting\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.7.900356923-rc\out\client\extension.js:52:262156
	at c (c:\Users\vting\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.7.900356923-rc\out\client\extension.js:52:261202)
	at c:\Users\vting\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.7.900356923-rc\out\client\extension.js:52:262096
	at c:\Users\vting\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.7.900356923-rc\out\client\extension.js:52:261615
	at Array.map (<anonymous>)
	at c:\Users\vting\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.7.900356923-rc\out\client\extension.js:52:261587
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (c:\Users\vting\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.7.900356923-rc\out\client\extension.js:52:263232)
	at c:\Users\vting\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.7.900356923-rc\out\client\extension.js:52:262667
	at Object.t.resolve (c:\Users\vting\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.7.900356923-rc\out\client\extension.js:52:262930)
	at c:\Users\vting\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.7.900356923-rc\out\client\extension.js:52:254027
	at e._get (c:\Users\vting\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.7.900356923-rc\out\client\extension.js:52:253793)
	at e.get (c:\Users\vting\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.7.900356923-rc\out\client\extension.js:52:252505)
	at a.get (c:\Users\vting\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.7.900356923-rc\out\client\extension.js:90:516359)
	at c:\Users\vting\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.7.900356923-rc\out\client\extension.js:52:246130
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\vting\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.7.900356923-rc\out\client\extension.js:37:826544
	at async t.activate (c:\Users\vting\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.7.900356923-rc\out\client\extension.js:37:826231)
	at async Promise.all (index 0) (at c:\Users\vting\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.7.900356923-rc\out\client\extension.js:37:827063)
b @ console.ts:137
```

</p>
</details>

**Comment by DonJayamanne** [comment]
Thanks for filling this issue .
Curious, where did you get the Jupyter extension from?
War haven't officially released the version you have installed.

**Comment by ttSpace** [comment]
https://github.com/microsoft/vscode-jupyter/suites/2894817390/artifacts/64844784
@DonJayamanne you can get the version in here.

**Comment by chirayu-miles** [comment]
I'm currently facing this same issue as well.  It happened right after I updated the VS Code Insiders and restarted.

![image](https://user-images.githubusercontent.com/71426305/120741230-82541e00-c4a9-11eb-8b8b-f94a86c1dc8b.png)

**Comment by chirayu-miles** [comment]
Interestingly, it seems like the update hadn't fully completed (though it had restarted.). A second restart fixed the issue completely.

**Comment by DonJayamanne** [comment]
@ttSpace Thanks for the information. You've installed a version that's not officially released (hence bugs/incompatibilities are to be expected). Please could you install from the marketplace.

@chirayu-miles Thanks for confirming the fact that this has been fixed.
