### ISSUE TITLE
On a remote server, kernel picker doesn't show virtual environments

### ISSUE THREAD

**Issue by AndreaPi** [microsoft/vscode-jupyter#6169]
Issue Type: <b>Bug</b>

I use the `Remote - SSH` and `Python` extensions to run Python code on a remote server. I created a virtual environment `test_venv`on the remote server I connect to, which contains `pandas` and `jupyter`. I'm able to select this environment in VS Code:

![image](https://user-images.githubusercontent.com/8233615/120988168-98e6c780-c77e-11eb-896c-4acf501b2018.png)

I can run a simple Python script from VS Code using this interpreter:

```
import pandas as pd
filename = 'test.csv'
df = pd.read_csv(filename)
print(df)
```

This runs fine. However, if I try to run a Jupyter notebook which does the same things:

```
{
 "metadata": {
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": 3
  },
  "orig_nbformat": 2
 },
 "nbformat": 4,
 "nbformat_minor": 2,
 "cells": [
  {
   "source": [
    "import pandas as pd"
   ],
   "cell_type": "code",
   "metadata": {},
   "execution_count": null,
   "outputs": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "filename = 'test.csv'\n",
    "df = pd.read_csv(filename)\n",
    "print(df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ]
}
```
VS Code complains that `ipykernel is not installed`, and it doesn't run the notebook:

![image](https://user-images.githubusercontent.com/8233615/120989298-ae102600-c77f-11eb-9f33-650e6b46233e.png)

This means that VS Code uses the selected environment when running a Python script, but not when running a notebook, as also confirmed by the fact that it's trying to use Python 2.7 (the virtual environment has Python 3.8) . This is a major bug: basically you cannot run Jupyter notebooks with VS Code on remote servers.

Extension version: 2021.5.842923320
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 19.6.0
Remote OS version: Linux x64 5.4.0-52-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.87GB free)|
|Process Argv|--crash-reporter-id df4f7917-f728-4290-9500-a3632318c3e7|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: xxxx|
|OS|Linux x64 5.4.0-52-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz (80 x 2696)|
|Memory (System)|503.78GB (343.49GB free)|
|VM|0%|
</details>

**Comment by DavidKutu** [comment]
Thanks for the issue @AndreaPi.

- What version of the jupyter extension do you have installed?
- Did you select the Jupyter Server you wanted to connect to?

In the notebook interface, on the top right, there should be a button that says `Jupyter Server`.
![image](https://user-images.githubusercontent.com/20347396/121093979-b75eba00-c7a2-11eb-82bd-24e58f1cf7ef.png)

If you haven't already, please select you remote environment like that and let me know if that fixes your issue.

**Comment by AndreaPi** [comment]
Hi @DavidKutu,

**note** that my issue is specifically related to running VS Code on a remote server with the `Remote - SSH` extension v0.65.4. For all I know, it might not happen when running VS Code locally. Coming to your questions:

- Jupyter extension: v2021.6.832593372

- In the top right there are two buttons:
![image](https://user-images.githubusercontent.com/8233615/121262595-b322c180-c8b4-11eb-9143-d91ae5066de2.png)
One says `Jupyter Server: local` and the other one `Python 3: not started`. Neither solve my problem. 

   1. If I click on the first one (`Jupyter Server: local`) I can select one of these options:

       ![image](https://user-images.githubusercontent.com/8233615/121262969-3c39f880-c8b5-11eb-93e9-3e9f538ca8aa.png)

       I select `Default`, since I have no idea what URI to provide otherwise. If I then run the Jupyter notebook, I still have the same error.

   1. If I click on the second one (`Python 3: not started`) I can select only one of these options, none of which is right, meaning that none of them points to the virtual environment `test_venv` I created beforehand:

     ![image](https://user-images.githubusercontent.com/8233615/121263268-a783ca80-c8b5-11eb-96ef-50c98b898c3d.png)
     
     I select the second option (because that's the interpreter my virtual environment is using) and I still get an error:

     ![image](https://user-images.githubusercontent.com/8233615/121263440-e6b21b80-c8b5-11eb-9a26-ad0c361ee027.png)

     now VS Code is picking the right Python version, but **not** the virtual environment, so it complains that no `ipykernel is available` (`ipykernel` is installed in the virtual environment). 

Conclusion: your suggestion didn't solve my issue.

**Comment by AndreaPi** [comment]
The logs contain some ID information (including some id) that I'm not sure it's safe to share here. I doctored them a bit. Let me know if the result is still good for you, otherwise we'll have to find a way to communicate more privately. Maybe email?

```
User belongs to experiment group 'pythonJoinMailingListVar2'
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'pythonSurveyNotification'
User belongs to experiment group 'jupyterEnhancedDataViewer'
Info 2021-06-09 09:57:29: ZMQ install verified.
Info 2021-06-09 09:57:29: id is cba40327-b2df-4796-89c7-4f6e8399a9f5
Info 2021-06-09 09:57:30: Found existing keyfile at xxxx
Info 2021-06-09 09:57:31: Search all interpreters /usr/bin/python2, /usr/bin/python3, /bin/python2, /bin/python3
Info 2021-06-09 09:57:57: Checking if notebook is trusted
Info 2021-06-09 09:57:57: Check if Notebook is Trusted, Class name = p, completed in 160ms, has a truthy return value, Return Value: true
Info 2021-06-09 09:57:57: Loading web panel for file:///xxxx/DOE.ipynb
Info 2021-06-09 09:57:57: Loading webview. View is notset
Info 2021-06-09 09:57:57: Attempting to start a server because of preload conditions ...
Info 2021-06-09 09:57:57: Loading web view...
Info 2021-06-09 09:57:57: Webview panel created.
Info 2021-06-09 09:57:57: Creating raw notebook for file:///xxx/DOE.ipynb
Info 2021-06-09 09:57:57: Getting preferred kernel for file:///xxxx/DOE.ipynb
Info 2021-06-09 09:57:57: initialize CommonMessageCoordinator
Info 2021-06-09 09:57:59: findPreferredKernel score for Python 2.7.18 64-bit is 1
Info 2021-06-09 09:57:59: findPreferredKernel score for Python 3.8.5 64-bit is 3
Info 2021-06-09 09:57:59: findPreferredKernel score for Python 2.7.18 64-bit is 1
Info 2021-06-09 09:57:59: findPreferredKernel score for Python 3.8.5 64-bit is 3
Info 2021-06-09 09:57:59: Find kernel spec, Class name = x, completed in 1100ms, has a truthy return value, Arg 1: <Uri:xxx/DOE.ipynb>, Arg 2: {"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.7.10"}}, Arg 3: undefined, Return Value: {"kind":"startUsingPythonInterpreter","kernelSpec":{"specFile":"/home/andrea/.local/share/jupyter/kernels/python385jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6/kernel.json","interpreterPath":"/usr/bin/python3","name":"python385jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6","argv":["python","-m","ipykernel_launcher","-f","{connection_file}"],"language":"python","path":"python","display_name":"Python 3.8.5 64-bit","metadata":{"interpreter":{"architecture":3,"path":"/usr/bin/python3","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.8.5","major":3,"minor":8,"patch":5,"prerelease":[],"build":[],"version":"3.8.5"},"sysVersion":"3.8.5 (default, Jan 27 2021, 15:41:15) \n[GCC 9.3.0]","sysPrefix":"/usr","fileHash":"61571bc9ec4d85690c3cb081c99524fbfd20cd06ea92ac278079fb4ef721ffb2384952271934338ef50f161d2958a42d307ce29a220c420f30f25f31a748c855","envType":"Unknown","cachedEntry":true,"displayName":"Python 3.8.5 64-bit"}},"env":{}},"interpreter":{"architecture":3,"path":"/usr/bin/python3","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.8.5","major":3,"minor":8,"patch":5,"prerelease":[],"build":[],"version":"3.8.5"},"sysVersion":"3.8.5 (default, Jan 27 2021, 15:41:15) \n[GCC 9.3.0]","sysPrefix":"/usr","fileHash":"61571bc9ec4d85690c3cb081c99524fbfd20cd06ea92ac278079fb4ef721ffb2384952271934338ef50f161d2958a42d307ce29a220c420f30f25f31a748c855","envType":"Unknown","cachedEntry":true,"displayName":"Python 3.8.5 64-bit"},"id":".python385jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6.python./usr/bin/python3.Python 3.8.5 64-bit"}
Info 2021-06-09 09:57:59: Computing working directory file:///xxxx/DOE.ipynb
Info 2021-06-09 09:57:59: Connecting to raw session for file:///xxxx/DOE.ipynb with connection {"kind":"startUsingPythonInterpreter","kernelSpec":{"specFile":"/home/andrea/.local/share/jupyter/kernels/python385jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6/kernel.json","interpreterPath":"/usr/bin/python3","name":"python385jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6","argv":["python","-m","ipykernel_launcher","-f","{connection_file}"],"language":"python","path":"python","display_name":"Python 3.8.5 64-bit","metadata":{"interpreter":{"architecture":3,"path":"/usr/bin/python3","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.8.5","major":3,"minor":8,"patch":5,"prerelease":[],"build":[],"version":"3.8.5"},"sysVersion":"3.8.5 (default, Jan 27 2021, 15:41:15) \n[GCC 9.3.0]","sysPrefix":"/usr","fileHash":"61571bc9ec4d85690c3cb081c99524fbfd20cd06ea92ac278079fb4ef721ffb2384952271934338ef50f161d2958a42d307ce29a220c420f30f25f31a748c855","envType":"Unknown","cachedEntry":true,"displayName":"Python 3.8.5 64-bit"}},"env":{}},"interpreter":{"architecture":3,"path":"/usr/bin/python3","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.8.5","major":3,"minor":8,"patch":5,"prerelease":[],"build":[],"version":"3.8.5"},"sysVersion":"3.8.5 (default, Jan 27 2021, 15:41:15) \n[GCC 9.3.0]","sysPrefix":"/usr","fileHash":"61571bc9ec4d85690c3cb081c99524fbfd20cd06ea92ac278079fb4ef721ffb2384952271934338ef50f161d2958a42d307ce29a220c420f30f25f31a748c855","envType":"Unknown","cachedEntry":true,"displayName":"Python 3.8.5 64-bit"},"id":".python385jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6.python./usr/bin/python3.Python 3.8.5 64-bit"}
Info 2021-06-09 09:57:59: Starting raw kernel Python 3.8.5 64-bit
Info 2021-06-09 09:57:59: installMissingDependencies /usr/bin/python3
Info 2021-06-09 09:57:59: Cached data exists getEnvironmentVariables, <No Resource>
Info 2021-06-09 09:57:59: Process Execution: > /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2021.6.832593372/pythonFiles/pyvsc-run-isolated.py pip list
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2021.6.832593372/pythonFiles/pyvsc-run-isolated.py pip list
Info 2021-06-09 09:57:59: Process Execution: > /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2021.6.832593372/pythonFiles/pyvsc-run-isolated.py pip list
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2021.6.832593372/pythonFiles/pyvsc-run-isolated.py pip list
Info 2021-06-09 09:57:59: Cached data exists getEnvironmentVariables, <No Resource>
Info 2021-06-09 09:57:59: Process Execution: > /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2021.6.832593372/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2021.6.832593372/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
Info 2021-06-09 09:57:59: Process Execution: > /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2021.6.832593372/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2021.6.832593372/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
Info 2021-06-09 09:57:59: Process Execution: > ~/vscode_venv/bin/python ~/.vscode-server/extensions/ms-toolsai.jupyter-2021.6.832593372/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/vscode_venv/bin/python ~/.vscode-server/extensions/ms-toolsai.jupyter-2021.6.832593372/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
Info 2021-06-09 09:58:00: Process Execution: > /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2021.6.832593372/pythonFiles/pyvsc-run-isolated.py -c "import pip"
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2021.6.832593372/pythonFiles/pyvsc-run-isolated.py -c "import pip"
Info 2021-06-09 09:58:00: Process Execution: > /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2021.6.832593372/pythonFiles/pyvsc-run-isolated.py -c "import pip"
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2021.6.832593372/pythonFiles/pyvsc-run-isolated.py -c "import pip"
Error 2021-06-09 09:58:00: Install Missing Dependencies, Class name = v, completed in 1073ms, has a falsy return value, Return Value: undefined [a [Error]: IPyKernel not installed into interpreter Python 3.8.5 64-bit:/usr/bin/python3
	at v.installMissingDependencies (/home/andrea/.vscode-server/extensions/ms-toolsai.jupyter-2021.6.832593372/out/client/extension.js:90:244799)] {
  category: 'noipykernel',
  reason: 1
}
Error 2021-06-09 09:58:00: Raw session failed to start because dependencies not installed
Info 2021-06-09 09:58:00: Shutdown session -- complete
Error 2021-06-09 09:58:00: Failed to determine if a notebook is active for the current editor [a [Error]: IPyKernel not installed into interpreter Python 3.8.5 64-bit:/usr/bin/python3
	at v.installMissingDependencies (/home/andrea/.vscode-server/extensions/ms-toolsai.jupyter-2021.6.832593372/out/client/extension.js:90:244799)] {
  category: 'noipykernel',
  reason: 1
}
Error 2021-06-09 09:58:00: DataScience Error [a [Error]: IPyKernel not installed into interpreter Python 3.8.5 64-bit:/usr/bin/python3
	at v.installMissingDependencies (/home/andrea/.vscode-server/extensions/ms-toolsai.jupyter-2021.6.832593372/out/client/extension.js:90:244799)] {
  category: 'noipykernel',
  reason: 1
}
Error 2021-06-09 09:58:00: DataScience Error [a [Error]: IPyKernel not installed into interpreter Python 3.8.5 64-bit:/usr/bin/python3
	at v.installMissingDependencies (/home/andrea/.vscode-server/extensions/ms-toolsai.jupyter-2021.6.832593372/out/client/extension.js:90:244799)] {
  category: 'noipykernel',
  reason: 1
}
Error 2021-06-09 09:58:00: Failed to initialize ipywidgetHandler [a [Error]: IPyKernel not installed into interpreter Python 3.8.5 64-bit:/usr/bin/python3
	at v.installMissingDependencies (/home/andrea/.vscode-server/extensions/ms-toolsai.jupyter-2021.6.832593372/out/client/extension.js:90:244799)] {
  category: 'noipykernel',
  reason: 1
}
Info 2021-06-09 09:58:00: Web view react rendered
Info 2021-06-09 09:58:00: Request for onigasm file at /home/andrea/.vscode-server/extensions/ms-toolsai.jupyter-2021.6.832593372/out/client/node_modules/onigasm/lib/onigasm.wasm
Info 2021-06-09 09:58:00: Request for tmlanguage file.
Info 2021-06-09 09:58:00: Searching for token colors ...
Info 2021-06-09 09:58:00: Attempting search for colors ...
Info 2021-06-09 09:58:00: Searching for token colors ...
Info 2021-06-09 09:58:00: Attempting search for colors ...
Info 2021-06-09 09:58:00: Searching for token colors ...
Info 2021-06-09 09:58:00: Attempting search for colors ...
Info 2021-06-09 09:58:00: Searching for token colors ...
Info 2021-06-09 09:58:00: Attempting search for colors ...
Info 2021-06-09 09:58:02: Creating daemon process for /home/andrea/vscode_venv/bin/python with env variables count 55
Info 2021-06-09 09:58:02: Process Execution: > ~/vscode_venv/bin/python ~/.vscode-server/extensions/ms-toolsai.jupyter-2021.6.832593372/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> ~/vscode_venv/bin/python ~/.vscode-server/extensions/ms-toolsai.jupyter-2021.6.832593372/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Info 2021-06-09 09:58:02: Python Daemon (pid: 539944): Execute rpc method prewarm_kernel in DS Daemon
Info 2021-06-09 09:58:02: Python Daemon (pid: 539944): Execute rpc method prewarm_kernel from /home/andrea/vscode_venv/bin/python
Info 2021-06-09 09:58:02: Python Daemon (pid: 539944): Pre-Warm DS Kernel in DS Kernel Launcher Daemon
Info 2021-06-09 09:58:02: Python Daemon (pid: 539944): Exec in DS Kernel Launcher Daemon (observable) ['/home/andrea/vscode_venv/bin/python', '/home/andrea/.vscode-server/extensions/ms-toolsai.jupyter-2021.6.832593372/pythonFiles/vscode_datascience_helpers/../pyvsc-run-isolated.py', '/home/andrea/.vscode-server/extensions/ms-toolsai.jupyter-2021.6.832593372/pythonFiles/vscode_datascience_helpers/kernel_prewarm_starter.py']
Info 2021-06-09 09:58:02: Python Daemon (pid: 539944): Exec in DS Kernel Launcher Daemon (observable)
Info 2021-06-09 09:58:02: Python Daemon (pid: 539944): Kernel launched, with PID 539946
Warn 2021-06-09 09:58:02: Python Daemon (pid: 539944): Waiting for Kernel to die 539946
Info 2021-06-09 09:58:02: Python Daemon (pid: 539944): Kernel launched, with PID as a daemon 539946
Info 2021-06-09 09:58:05: Executing cell NotebookImport#0
Info 2021-06-09 09:58:05: Waiting for jupyter server and web panel ...
Info 2021-06-09 09:58:05: Creating raw notebook for file:///xxx/DOE.ipynb
Info 2021-06-09 09:58:05: Getting preferred kernel for file:///xxx/DOE.ipynb
Info 2021-06-09 09:58:05: findPreferredKernel score for Python 2.7.18 64-bit is 1
Info 2021-06-09 09:58:05: findPreferredKernel score for Python 3.8.5 64-bit is 3
Info 2021-06-09 09:58:05: findPreferredKernel score for Python 2.7.18 64-bit is 1
Info 2021-06-09 09:58:05: findPreferredKernel score for Python 3.8.5 64-bit is 3
Info 2021-06-09 09:58:05: Find kernel spec, Class name = x, completed in 2ms, has a truthy return value, Arg 1: <Uri:/xxx/DOE.ipynb>, Arg 2: {"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.7.10"}}, Arg 3: undefined, Return Value: {"kind":"startUsingPythonInterpreter","kernelSpec":{"specFile":"/home/andrea/.local/share/jupyter/kernels/python385jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6/kernel.json","interpreterPath":"/usr/bin/python3","name":"python385jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6","argv":["python","-m","ipykernel_launcher","-f","{connection_file}"],"language":"python","path":"python","display_name":"Python 3.8.5 64-bit","metadata":{"interpreter":{"architecture":3,"path":"/usr/bin/python3","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.8.5","major":3,"minor":8,"patch":5,"prerelease":[],"build":[],"version":"3.8.5"},"sysVersion":"3.8.5 (default, Jan 27 2021, 15:41:15) \n[GCC 9.3.0]","sysPrefix":"/usr","fileHash":"61571bc9ec4d85690c3cb081c99524fbfd20cd06ea92ac278079fb4ef721ffb2384952271934338ef50f161d2958a42d307ce29a220c420f30f25f31a748c855","envType":"Unknown","cachedEntry":true,"displayName":"Python 3.8.5 64-bit"}},"env":{}},"interpreter":{"architecture":3,"path":"/usr/bin/python3","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.8.5","major":3,"minor":8,"patch":5,"prerelease":[],"build":[],"version":"3.8.5"},"sysVersion":"3.8.5 (default, Jan 27 2021, 15:41:15) \n[GCC 9.3.0]","sysPrefix":"/usr","fileHash":"61571bc9ec4d85690c3cb081c99524fbfd20cd06ea92ac278079fb4ef721ffb2384952271934338ef50f161d2958a42d307ce29a220c420f30f25f31a748c855","envType":"Unknown","cachedEntry":true,"displayName":"Python 3.8.5 64-bit"},"id":".python385jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6.python./usr/bin/python3.Python 3.8.5 64-bit"}
Info 2021-06-09 09:58:05: Computing working directory file:///xxx/DOE.ipynb
Info 2021-06-09 09:58:05: Connecting to raw session for file:///xxx/DOE.ipynb with connection {"kind":"startUsingPythonInterpreter","kernelSpec":{"specFile":"/home/andrea/.local/share/jupyter/kernels/python385jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6/kernel.json","interpreterPath":"/usr/bin/python3","name":"python385jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6","argv":["python","-m","ipykernel_launcher","-f","{connection_file}"],"language":"python","path":"python","display_name":"Python 3.8.5 64-bit","metadata":{"interpreter":{"architecture":3,"path":"/usr/bin/python3","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.8.5","major":3,"minor":8,"patch":5,"prerelease":[],"build":[],"version":"3.8.5"},"sysVersion":"3.8.5 (default, Jan 27 2021, 15:41:15) \n[GCC 9.3.0]","sysPrefix":"/usr","fileHash":"61571bc9ec4d85690c3cb081c99524fbfd20cd06ea92ac278079fb4ef721ffb2384952271934338ef50f161d2958a42d307ce29a220c420f30f25f31a748c855","envType":"Unknown","cachedEntry":true,"displayName":"Python 3.8.5 64-bit"}},"env":{}},"interpreter":{"architecture":3,"path":"/usr/bin/python3","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.8.5","major":3,"minor":8,"patch":5,"prerelease":[],"build":[],"version":"3.8.5"},"sysVersion":"3.8.5 (default, Jan 27 2021, 15:41:15) \n[GCC 9.3.0]","sysPrefix":"/usr","fileHash":"61571bc9ec4d85690c3cb081c99524fbfd20cd06ea92ac278079fb4ef721ffb2384952271934338ef50f161d2958a42d307ce29a220c420f30f25f31a748c855","envType":"Unknown","cachedEntry":true,"displayName":"Python 3.8.5 64-bit"},"id":".python385jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6.python./usr/bin/python3.Python 3.8.5 64-bit"}
Info 2021-06-09 09:58:05: Starting raw kernel Python 3.8.5 64-bit
Info 2021-06-09 09:58:05: installMissingDependencies /usr/bin/python3
Info 2021-06-09 09:58:05: Cached data exists getEnvironmentVariables, <No Resource>
Info 2021-06-09 09:58:05: Process Execution: > /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2021.6.832593372/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2021.6.832593372/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
Info 2021-06-09 09:58:05: Process Execution: > /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2021.6.832593372/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2021.6.832593372/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
Info 2021-06-09 09:58:06: Searching for token colors ...
Info 2021-06-09 09:58:06: Attempting search for colors ...
Warn 2021-06-09 09:58:06: Color theme Monokai not found. Using default colors.
Info 2021-06-09 09:58:06: Attempting search for colors ...
Warn 2021-06-09 09:58:06: Color theme Monokai not found. Using default colors.
Warn 2021-06-09 09:58:06: Color theme Monokai not found. Using default colors.
Info 2021-06-09 09:58:06: Attempting search for colors ...
Warn 2021-06-09 09:58:06: Color theme Monokai not found. Using default colors.
Info 2021-06-09 09:58:06: Searching for token colors ...
Info 2021-06-09 09:58:06: Attempting search for colors ...
Warn 2021-06-09 09:58:06: Color theme Monokai not found. Using default colors.
Info 2021-06-09 09:58:06: Attempting search for colors ...
Warn 2021-06-09 09:58:06: Color theme Monokai not found. Using default colors.
Warn 2021-06-09 09:58:06: Color theme Monokai not found. Using default colors.
Info 2021-06-09 09:58:06: Attempting search for colors ...
Warn 2021-06-09 09:58:06: Color theme Monokai not found. Using default colors.
Info 2021-06-09 09:58:06: Searching for token colors ...
Info 2021-06-09 09:58:06: Attempting search for colors ...
Warn 2021-06-09 09:58:06: Color theme Monokai not found. Using default colors.
Info 2021-06-09 09:58:06: Attempting search for colors ...
Warn 2021-06-09 09:58:06: Color theme Monokai not found. Using default colors.
Info 2021-06-09 09:58:06: Searching for token colors ...
Info 2021-06-09 09:58:06: Attempting search for colors ...
Warn 2021-06-09 09:58:06: Color theme Monokai not found. Using default colors.
Info 2021-06-09 09:58:06: Attempting search for colors ...
Warn 2021-06-09 09:58:06: Color theme Monokai not found. Using default colors.
Warn 2021-06-09 09:58:06: Color theme Monokai not found. Using default colors.
Info 2021-06-09 09:58:06: Attempting search for colors ...
Warn 2021-06-09 09:58:06: Color theme Monokai not found. Using default colors.
Warn 2021-06-09 09:58:06: Color theme Monokai not found. Using default colors.
Info 2021-06-09 09:58:06: Attempting search for colors ...
Warn 2021-06-09 09:58:06: Color theme Monokai not found. Using default colors.
```

**Comment by DavidKutu** [comment]
Thanks @AndreaPi. 

This line 
`Info 2021-06-09 09:57:31: Search all interpreters /usr/bin/python2, /usr/bin/python3, /bin/python2, /bin/python3`
clearly shows that we're not finding your venv.
That's really strange since you can find it in the interpreter picker, we should be getting the same list in the kernel picker.

**Comment by DavidKutu** [comment]
I have another couple of questions/suggestions @AndreaPi.

- Could you please update the Jupyter release to the latest version?
- The python file and the notebook you're running, are they on the same folder?

**Comment by AndreaPi** [comment]
Installing the new Jupyter release (which came out after I opened the issue) solved everything! Thank ypu @DavidKutu . Closing the issue now
