### ISSUE TITLE
无法解析 debugpy 输出

### ISSUE THREAD

**Issue by felix3913** [microsoft/vscode-jupyter#6262]
at _.parseConnectInfo (/home/felix/.vscode/extensions/ms-toolsai.jupyter-2021.6.999230701/out/client/extension.js:90:160684)
at _.connectToLocal (/home/felix/.vscode/extensions/ms-toolsai.jupyter-2021.6.999230701/out/client/extension.js:90:161211)
at _.connect (/home/felix/.vscode/extensions/ms-toolsai.jupyter-2021.6.999230701/out/client/extension.js:90:159088)
at _.startDebugSession (/home/felix/.vscode/extensions/ms-toolsai.jupyter-2021.6.999230701/out/client/extension.js:90:158235)
at D.submitCode (/home/felix/.vscode/extensions/ms-toolsai.jupyter-2021.6.999230701/out/client/extension.js:37:636138)
at D.handleRunByLine (/home/felix/.vscode/extensions/ms-toolsai.jupyter-2021.6.999230701/out/client/extension.js:37:624081)

**Comment by claudiaregio** [comment]
@felix3913 Could you provide more details on the enhancement you'd like to see?

**Comment by felix3913** [comment]
Sorry, no more information.

**Comment by greazer** [comment]
Thanks for the feedback! However, we don't have enough information to take action here.
