### ISSUE TITLE
Jupyter extension cannot load

### ISSUE THREAD

**Issue by cfs2000** [microsoft/vscode-jupyter#6511]
Issue Type: <b>Bug</b>

Since i dit the last update today, i cannot run my python files into interactive windows (jupyter).

The issue I get : 
' Extension activation failed, run the 'Developer: Toggle Developer Tools' command for more information. '
 or 'Command 'Jupyter: Run Current File in Interactive Window' resulted in an error (command 'jupyter.runFileInteractive' not found)'

My Toggle Developer Tool displays : ERR Unexpected error getting editor overrides: 
TypeError: _.filter is not a function
log.ts:296   ERR Unexpected error getting editor overrides: TypeError: ue.filter is not a function
log.ts:296   ERR Unexpected error getting editor overrides: TypeError: _.filter is not a function
log.ts:296   ERR Unexpected error getting editor overrides: TypeError: ue.filter is not a function
log.ts:296   ERR Unexpected error getting editor overrides: TypeError: _.filter is not a function
log.ts:296   ERR Unexpected error getting editor overrides: TypeError: ue.filter is not a function
log.ts:296   ERR Unexpected error getting editor overrides: TypeError: _.filter is not a function
log.ts:296   ERR Unexpected error getting editor overrides: TypeError: ue.filter is not a function
log.ts:296   ERR Unexpected error getting editor overrides: TypeError: _.filter is not a function
log.ts:296   ERR Unexpected error getting editor overrides: TypeError: ue.filter is not a function
log.ts:296   ERR Unexpected error getting editor overrides: TypeError: _.filter is not a function
log.ts:296   ERR Unexpected error getting editor overrides: TypeError: ue.filter is not a function
event.ts:487 [a75] potential listener LEAK detected, having 175 listeners already. MOST frequent listener (1):
check @ event.ts:487
event.ts:488     at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:58:58492
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:58:60975
    at new Promise (<anonymous>)
    at Object.x [as toPromise] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:58:60956)
    at k.whenInitialized (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:4475)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:3211
    at f (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:68:11213)
    at Object.onFirstListenerAdd (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:3202)
    at _event._event (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:872)
    at l.set input [as input] (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:4229)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:76:7162
check @ event.ts:488
log.ts:296   ERR _.filter is not a function: TypeError: _.filter is not a function
    at P.getUserConfiguredCustomEditors (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2149:72200)
    at L.onResourceEditorOpening (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2149:78157)
    at L.onEditorOpening (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2149:78058)
    at Object.open (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2149:77027)
    at _.onGroupWillOpenEditor (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2151:14923)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2151:8725
    at c.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at Ii.openEditor (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2394:14285)
    at _.openEditor (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2151:15351)
    at s.createWebview (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1614:2326)
    at p.show (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1614:5061)
log.ts:296   ERR Unexpected error getting editor overrides: TypeError: _.filter is not a function
log.ts:296   ERR Unexpected error getting editor overrides: TypeError: ue.filter is not a function
log.ts:296   ERR Unexpected error getting editor overrides: TypeError: _.filter is not a function
log.ts:296   ERR Unexpected error getting editor overrides: TypeError: ue.filter is not a function
notificationsAlerts.ts:40 Extension activation failed, run the 'Developer: Toggle Developer Tools' command for more information.
onDidChangeNotification @ notificationsAlerts.ts:40
abstractExtensionService.ts:796 Activating extension 'ms-toolsai.jupyter' failed: o.getConfiguration(...).get(...).find is not a function.
_logMessageInConsole @ abstractExtensionService.ts:796
log.ts:296   ERR _.filter is not a function: TypeError: _.filter is not a function
    at P.getUserConfiguredCustomEditors (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2149:72200)
    at L.onResourceEditorOpening (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2149:78157)
    at L.onEditorOpening (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2149:78058)
    at Object.open (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2149:77027)
    at _.onGroupWillOpenEditor (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2151:14923)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2151:8725
    at c.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at Ii.openEditor (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2394:14285)
    at j (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2318:15156)
    at HTMLDivElement.<anonymous> (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2318:15338)
log.ts:296   ERR _.filter is not a function: TypeError: _.filter is not a function
    at P.getUserConfiguredCustomEditors (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2149:72200)
    at L.onResourceEditorOpening (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2149:78157)
    at L.onEditorOpening (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2149:78058)
    at Object.open (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2149:77027)
    at _.onGroupWillOpenEditor (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2151:14923)
    at file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2151:8725
    at c.fire (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:60:1836)
    at Ii.openEditor (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2394:14285)
    at Ii.doCloseActiveEditor (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2394:19347)
    at Ii.doCloseEditor (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2394:18695)
    at Ii.doCloseEditorWithDirtyHandling (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2394:18548)
    at async Ii.closeEditor (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2394:18379)
    at async h.run (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:171:30887)
log.ts:296   ERR Unexpected error getting editor overrides: TypeError: _.filter is not a function
log.ts:296   ERR Unexpected error getting editor overrides: TypeError: ue.filter is not a function
log.ts:296   ERR Unexpected error getting editor overrides: TypeError: _.filter is not a function
log.ts:296   ERR Unexpected error getting editor overrides: TypeError: ue.filter is not a function
notificationsAlerts.ts:40 Command 'Jupyter: Run Current File in Interactive Window' resulted in an error (command 'jupyter.runFileInteractive' not found)
onDidChangeNotification @ notificationsAlerts.ts:40

Extension version: 2021.3.684299474
VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.81GB (0.85GB free)|
|Process Argv|--crash-reporter-id d33e5334-4e14-41de-9922-c2eeabf03b64|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200cf:30331938
binariesv615:30325510
vsccppwt:30329788
aatestflight:30331711

```

</details>

**Comment by joyceerhl** [comment]
Your version info suggests you are on a much older version of both VS Code and the Jupyter extension. The latest VS Code is 1.57.1 and the latest Jupyter version is v2021.6.999662501. Could you please try upgrading and letting us know how that works for you?

**Comment by claudiaregio** [comment]
@cfs2000 if working with Python you'll likely want to update the Python extension too

**Comment by cfs2000** [comment]
After updating VS code and python extension, it all worked well again, thank you !
