### ISSUE TITLE
Auto install ipykernel doesn't work on Devcontainer/Codespaces

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#6559]
1. Create a Codespace from https://github.com/kieferrm/vscode-remote-python
2. Switch active interpreter to /usr/bin/python3
3. Install pip with `sudo apt update && sudo apt install python3-pip`
4. Open interactive window or notebook and try to run cells
5. 🐛 ipykernel install fails with the following spew:

<details>

```
vscode ➜ /workspaces/vscode-remote-python (main ✗) $ /usr/bin/python3 /home/vscode/.vscode-remote/extensions/ms-python.python-2021.6.944021595/pythonFiles/shell_exec.py /usr/bin/python3 -m pip install -U --force-reinstall ipykernel --user /tmp/tmp-663b0naQ0jTIxQ9.log
Executing command in shell >> /usr/bin/python3 -m pip install -U --force-reinstall ipykernel --user
Collecting ipykernel
  Using cached https://files.pythonhosted.org/packages/b6/4a/b9e7d67637549e1b75c2946e93e35740ea63a521d7d455343e6a8a8a7b91/ipykernel-6.0.1-py3-none-any.whl
Collecting tornado>=4.2 (from ipykernel)
  Using cached https://files.pythonhosted.org/packages/bf/fa/2befee379094720b54065daa9c6117f3edb7d35f86cde0f50b3a28ecfadf/tornado-6.1-cp37-cp37m-manylinux1_x86_64.whl
Collecting jupyter-client (from ipykernel)
  Using cached https://files.pythonhosted.org/packages/88/4e/50fcf8b38d9c08d5b4839c1650e595f6bfa4fc9b419e2b800db8f14ee532/jupyter_client-6.2.0-py3-none-any.whl
Collecting ipython>=7.23.1 (from ipykernel)
  Using cached https://files.pythonhosted.org/packages/f7/b2/733ea4551a04866bbcfbbade4d9d2c82c829cf1cc6fac1ac5974b8c7f756/ipython-7.25.0-py3-none-any.whl
Collecting debugpy>=1.0.0 (from ipykernel)
  Using cached https://files.pythonhosted.org/packages/84/89/bb91c5e3b676721d3a9c13489767b2ec83c7035464e68e8e2fe477ad4566/debugpy-1.3.0-cp37-cp37m-manylinux1_x86_64.whl
Collecting importlib-metadata<4; python_version < "3.8.0" (from ipykernel)
  Using cached https://files.pythonhosted.org/packages/52/d0/bdb31463f2d9ca111e39b268518e9baa3542ef73ca449b711a7b4da69764/importlib_metadata-3.10.1-py3-none-any.whl
Collecting traitlets>=4.1.0 (from ipykernel)
  Using cached https://files.pythonhosted.org/packages/f6/7d/3ecb0ebd0ce8dcdfa7bd47ab85c1d4a521e6770ef283d0824f5804994dfe/traitlets-5.0.5-py3-none-any.whl
Collecting jupyter-core>=4.6.0 (from jupyter-client->ipykernel)
  Using cached https://files.pythonhosted.org/packages/53/40/5af36bffa0af3ac71d3a6fc6709de10e4f6ff7c01745b8bc4715372189c9/jupyter_core-4.7.1-py3-none-any.whl
Collecting python-dateutil>=2.1 (from jupyter-client->ipykernel)
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting nest-asyncio>=1.5 (from jupyter-client->ipykernel)
  Using cached https://files.pythonhosted.org/packages/52/e2/9b37da54e6e9094d2f558ae643d1954a0fa8215dfee4fa261f31c5439796/nest_asyncio-1.5.1-py3-none-any.whl
Collecting pyzmq>=13 (from jupyter-client->ipykernel)
  Using cached https://files.pythonhosted.org/packages/2d/4b/256767441a6c4223fbc7c3eab1b3762d9d70b657899d844228a782f48af3/pyzmq-22.1.0-cp37-cp37m-manylinux1_x86_64.whl
Collecting pickleshare (from ipython>=7.23.1->ipykernel)
  Using cached https://files.pythonhosted.org/packages/9a/41/220f49aaea88bc6fa6cba8d05ecf24676326156c23b991e80b3f2fc24c77/pickleshare-0.7.5-py2.py3-none-any.whl
Collecting matplotlib-inline (from ipython>=7.23.1->ipykernel)
  Using cached https://files.pythonhosted.org/packages/7f/de/6c111d687335729cf8c156394c8d119b0dc3c34b6966ff2a2f7fe4aa79cf/matplotlib_inline-0.1.2-py3-none-any.whl
Collecting setuptools>=18.5 (from ipython>=7.23.1->ipykernel)
  Using cached https://files.pythonhosted.org/packages/a2/e1/902fbc2f61ad6243cd3d57ffa195a9eb123021ec912ec5d811acf54a39f8/setuptools-57.1.0-py3-none-any.whl
Collecting jedi>=0.16 (from ipython>=7.23.1->ipykernel)
  Using cached https://files.pythonhosted.org/packages/f9/36/7aa67ae2663025b49e8426ead0bad983fee1b73f472536e9790655da0277/jedi-0.18.0-py2.py3-none-any.whl
Collecting pygments (from ipython>=7.23.1->ipykernel)
  Using cached https://files.pythonhosted.org/packages/a6/c9/be11fce9810793676017f79ffab3c6cb18575844a6c7b8d4ed92f95de604/Pygments-2.9.0-py3-none-any.whl
Collecting pexpect>4.3; sys_platform != "win32" (from ipython>=7.23.1->ipykernel)
  Using cached https://files.pythonhosted.org/packages/39/7b/88dbb785881c28a102619d46423cb853b46dbccc70d3ac362d99773a78ce/pexpect-4.8.0-py2.py3-none-any.whl
Collecting prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 (from ipython>=7.23.1->ipykernel)
  Using cached https://files.pythonhosted.org/packages/1e/34/1d9880ac1339ad4c6697b330e7a507584105613751318249d9e820faa25f/prompt_toolkit-3.0.19-py3-none-any.whl
Collecting decorator (from ipython>=7.23.1->ipykernel)
  Using cached https://files.pythonhosted.org/packages/6a/36/b1b9bfdf28690ae01d9ca0aa5b0d07cb4448ac65fb91dc7e2d094e3d992f/decorator-5.0.9-py3-none-any.whl
Collecting backcall (from ipython>=7.23.1->ipykernel)
  Using cached https://files.pythonhosted.org/packages/4c/1c/ff6546b6c12603d8dd1070aa3c3d273ad4c07f5771689a7b69a550e8c951/backcall-0.2.0-py2.py3-none-any.whl
Collecting typing-extensions>=3.6.4; python_version < "3.8" (from importlib-metadata<4; python_version < "3.8.0"->ipykernel)
  Using cached https://files.pythonhosted.org/packages/2e/35/6c4fff5ab443b57116cb1aad46421fb719bed2825664e8fe77d66d99bcbc/typing_extensions-3.10.0.0-py3-none-any.whl
Collecting zipp>=0.5 (from importlib-metadata<4; python_version < "3.8.0"->ipykernel)
  Using cached https://files.pythonhosted.org/packages/92/d9/89f433969fb8dc5b9cbdd4b4deb587720ec1aeb59a020cf15002b9593eef/zipp-3.5.0-py3-none-any.whl
Collecting ipython-genutils (from traitlets>=4.1.0->ipykernel)
  Using cached https://files.pythonhosted.org/packages/fa/bc/9bd3b5c2b4774d5f33b2d544f1460be9df7df2fe42f352135381c347c69a/ipython_genutils-0.2.0-py2.py3-none-any.whl
Collecting six>=1.5 (from python-dateutil>=2.1->jupyter-client->ipykernel)
  Using cached https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl
Collecting parso<0.9.0,>=0.8.0 (from jedi>=0.16->ipython>=7.23.1->ipykernel)
  Using cached https://files.pythonhosted.org/packages/a9/c4/d5476373088c120ffed82f34c74b266ccae31a68d665b837354d4d8dc8be/parso-0.8.2-py2.py3-none-any.whl
Collecting ptyprocess>=0.5 (from pexpect>4.3; sys_platform != "win32"->ipython>=7.23.1->ipykernel)
  Using cached https://files.pythonhosted.org/packages/22/a6/858897256d0deac81a172289110f31629fc4cee19b6f01283303e18c8db3/ptyprocess-0.7.0-py2.py3-none-any.whl
Collecting wcwidth (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=7.23.1->ipykernel)
  Using cached https://files.pythonhosted.org/packages/59/7c/e39aca596badaf1b78e8f547c807b04dae603a433d3e7a7e04d67f2ef3e5/wcwidth-0.2.5-py2.py3-none-any.whl
Installing collected packages: tornado, ipython-genutils, traitlets, jupyter-core, six, python-dateutil, nest-asyncio, pyzmq, jupyter-client, pickleshare, matplotlib-inline, setuptools, parso, jedi, pygments, ptyprocess, pexpect, wcwidth, prompt-toolkit, decorator, backcall, ipython, debugpy, typing-extensions, zipp, importlib-metadata, ipykernel
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 386, in run
    use_user_site=options.use_user_site,
  File "/usr/lib/python3/dist-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 760, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 382, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/usr/lib/python3/dist-packages/pip/_internal/wheel.py", line 215, in move_wheel_files
    prefix=prefix,
  File "/usr/lib/python3/dist-packages/pip/_internal/locations.py", line 165, in distutils_scheme
    i.finalize_options()
  File "/usr/lib/python3.7/distutils/command/install.py", line 274, in finalize_options
    raise DistutilsOptionError("can't combine user with prefix, "
distutils.errors.DistutilsOptionError: can't combine user with prefix, exec_prefix/home, or install_(plat)base
Traceback (most recent call last):
  File "/home/vscode/.vscode-remote/extensions/ms-python.python-2021.6.944021595/pythonFiles/shell_exec.py", line 26, in <module>
    subprocess.check_call(shell_args, stdout=sys.stdout, stderr=sys.stderr)
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'install', '-U', '--force-reinstall', 'ipykernel', '--user']' returned non-zero exit status 2.
```

</details>

6. Run `/usr/bin/python3 -m pip install ipykernel` and installation completes successfully
7. 🐛 Retry running cells. Newly installed ipykernel is not detected
8. 🐛 ipykernel install is attempted twice, once for main kernel and once for backup kernel used for fast switching

**Comment by joyceerhl** [comment]
We're failing to detect installed ipykernel:

Terminal:
![image](https://user-images.githubusercontent.com/30305945/124680650-a7a6c400-de7b-11eb-84ac-d03e8b3bf99e.png)

Jupyter logs:
```
Error 2021-07-06 23:55:47: Install Missing Dependencies, Class name = w, completed in 7317ms, has a falsy return value, Return Value: undefined a [Error]: IPyKernel not installed into interpreter Python 3.7.3 64-bit:/usr/bin/python3
    at w.handleKernelDependencyResponse (/home/vscode/.vscode-remote/extensions/ms-toolsai.jupyter-2021.6.999662501/out/client/extension.js:90:244702)
    at w.installMissingDependencies (/home/vscode/.vscode-remote/extensions/ms-toolsai.jupyter-2021.6.999662501/out/client/extension.js:90:244075)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  category: 'noipykernel',
  reason: 2
}
Error 2021-07-06 23:55:47: Raw session failed to start because dependencies not installed
Info 2021-07-06 23:55:47: Shutdown session -- complete
Error 2021-07-06 23:55:47: Exception attempting to start notebook:  a [Error]: IPyKernel not installed into interpreter Python 3.7.3 64-bit:/usr/bin/python3
    at w.handleKernelDependencyResponse (/home/vscode/.vscode-remote/extensions/ms-toolsai.jupyter-2021.6.999662501/out/client/extension.js:90:244702)
    at w.installMissingDependencies (/home/vscode/.vscode-remote/extensions/ms-toolsai.jupyter-2021.6.999662501/out/client/extension.js:90:244075)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  category: 'noipykernel',
  reason: 2,
  vslsStack: [ CallSite {}, CallSite {}, CallSite {}, CallSite {} ]
}
Info 2021-07-06 23:55:47: Closing interactive window: Interactive - #1
Error 2021-07-06 23:55:47: DataScience Error a [Error]: IPyKernel not installed into interpreter Python 3.7.3 64-bit:/usr/bin/python3
    at w.handleKernelDependencyResponse (/home/vscode/.vscode-remote/extensions/ms-toolsai.jupyter-2021.6.999662501/out/client/extension.js:90:244702)
    at w.installMissingDependencies (/home/vscode/.vscode-remote/extensions/ms-toolsai.jupyter-2021.6.999662501/out/client/extension.js:90:244075)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  category: 'noipykernel',
  reason: 2,
  vslsStack: [ CallSite {}, CallSite {}, CallSite {}, CallSite {} ]
}

```

**Comment by greazer** [comment]
See also: microsoft/vscode-python#15632 and #5116
