### ISSUE TITLE
Insiders tests in Python extension are taking 6 hours to resolve/time out due to Jupyter issues.

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode-jupyter#6592]
June 23, 9:37am https://github.com/microsoft/vscode-python/runs/2897176821?check_suite_focus=true

![image](https://user-images.githubusercontent.com/51720070/123180044-5d672100-d43f-11eb-86ce-45708fc72a39.png)

<details>
<summary> Insider tests raw logs </summary>

<p>

```
2021-06-23T16:40:07.4278859Z Reading package lists...
2021-06-23T16:40:07.6181818Z Building dependency tree...
2021-06-23T16:40:07.6203435Z Reading state information...
2021-06-23T16:40:07.8487414Z xvfb is already the newest version (2:1.20.9-2ubuntu1.2~20.04.2).
2021-06-23T16:40:07.8488261Z 0 upgraded, 0 newly installed, 0 to remove and 13 not upgraded.
2021-06-23T16:40:07.8534788Z [command]/usr/bin/xvfb-run --auto-servernum node --no-force-async-hooks-checks ./out/test/standardTest.js
2021-06-23T16:40:08.1919979Z ****************************************************************************************************
2021-06-23T16:40:08.1922870Z Start Standard tests
2021-06-23T16:40:08.4633104Z Downloading VS Code insiders from https://update.code.visualstudio.com/latest/linux-x64/insider
2021-06-23T16:40:12.0621814Z Downloaded VS Code insiders into .vscode-test/vscode-insiders
2021-06-23T16:40:12.0750119Z Installing Jupyter Extension
2021-06-23T16:40:12.3062868Z Installing extensions...
2021-06-23T16:40:12.5431127Z Installing extension 'ms-toolsai.jupyter'...
2021-06-23T16:40:13.1246587Z (node:2094) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
2021-06-23T16:40:13.1248776Z (Use `code-insiders --trace-deprecation ...` to show where the warning was created)
2021-06-23T16:40:13.9823631Z Extension 'ms-toolsai.jupyter' v2021.7.963708582 was successfully installed.
2021-06-23T16:40:14.2074136Z (node:2094) UnhandledPromiseRejectionWarning: Canceled: Canceled
2021-06-23T16:40:14.2077120Z     at Object.L [as canceled] (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:5:1157)
2021-06-23T16:40:14.2079610Z     at R.cancel (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:9:63097)
2021-06-23T16:40:14.2082035Z     at R.dispose (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:9:63237)
2021-06-23T16:40:14.2084400Z     at q.dispose (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:9:63499)
2021-06-23T16:40:14.2087016Z     at j (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:3434)
2021-06-23T16:40:14.2089275Z     at d.clear (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:3894)
2021-06-23T16:40:14.2091532Z     at dispose (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:3873)
2021-06-23T16:40:14.2093771Z     at h.dispose (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:4408)
2021-06-23T16:40:14.2096144Z     at h.dispose (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cliProcessMain.js:11:7244)
2021-06-23T16:40:14.2098459Z     at j (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:3434)
2021-06-23T16:40:14.2100915Z     at /home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:3640
2021-06-23T16:40:14.2103404Z     at Object.dispose (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:3712)
2021-06-23T16:40:14.2105797Z     at Object.j [as dispose] (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:3573)
2021-06-23T16:40:14.2108150Z     at /home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cliProcessMain.js:14:41606
2021-06-23T16:40:14.2109512Z     at Map.forEach (<anonymous>)
2021-06-23T16:40:14.2111351Z     at Me.dispose (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cliProcessMain.js:14:41593)
2021-06-23T16:40:14.2113691Z     at j (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:3434)
2021-06-23T16:40:14.2118969Z     at d.clear (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:3894)
2021-06-23T16:40:14.2120957Z     at dispose (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:3873)
2021-06-23T16:40:14.2122798Z     at a.dispose (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:4408)
2021-06-23T16:40:14.2124772Z     at Object.v [as main] (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cliProcessMain.js:17:48030)
2021-06-23T16:40:14.2125903Z     at runMicrotasks (<anonymous>)
2021-06-23T16:40:14.2126719Z     at processTicksAndRejections (internal/process/task_queues.js:93:5)
2021-06-23T16:40:14.2128311Z     at async R (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:12:13996)
2021-06-23T16:40:14.2132045Z (node:2094) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2021-06-23T16:40:14.2135385Z (node:2094) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2021-06-23T16:40:14.2211797Z Installing Pylance Extension
2021-06-23T16:40:14.4023116Z Installing extensions...
2021-06-23T16:40:14.5777886Z Installing extension 'ms-python.vscode-pylance'...
2021-06-23T16:40:15.2436079Z (node:2116) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
2021-06-23T16:40:15.2438302Z (Use `code-insiders --trace-deprecation ...` to show where the warning was created)
2021-06-23T16:40:20.5123197Z Extension 'ms-python.vscode-pylance' v2021.6.2 was successfully installed.
2021-06-23T16:40:20.6685619Z (node:2116) UnhandledPromiseRejectionWarning: Canceled: Canceled
2021-06-23T16:40:20.6688626Z     at Object.L [as canceled] (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:5:1157)
2021-06-23T16:40:20.6691088Z     at R.cancel (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:9:63097)
2021-06-23T16:40:20.6693482Z     at R.dispose (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:9:63237)
2021-06-23T16:40:20.6696245Z     at q.dispose (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:9:63499)
2021-06-23T16:40:20.6698547Z     at j (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:3434)
2021-06-23T16:40:20.6701165Z     at d.clear (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:3894)
2021-06-23T16:40:20.6703626Z     at dispose (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:3873)
2021-06-23T16:40:20.6741121Z     at h.dispose (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:4408)
2021-06-23T16:40:20.6743451Z     at h.dispose (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cliProcessMain.js:11:7244)
2021-06-23T16:40:20.6745552Z     at j (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:3434)
2021-06-23T16:40:20.6747473Z     at /home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:3640
2021-06-23T16:40:20.6749454Z     at Object.dispose (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:3712)
2021-06-23T16:40:20.6751512Z     at Object.j [as dispose] (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:3573)
2021-06-23T16:40:20.6753563Z     at /home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cliProcessMain.js:14:41606
2021-06-23T16:40:20.6754748Z     at Map.forEach (<anonymous>)
2021-06-23T16:40:20.6756334Z     at Me.dispose (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cliProcessMain.js:14:41593)
2021-06-23T16:40:20.6758407Z     at j (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:3434)
2021-06-23T16:40:20.6760317Z     at d.clear (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:3894)
2021-06-23T16:40:20.6762260Z     at dispose (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:3873)
2021-06-23T16:40:20.6765176Z     at a.dispose (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:4408)
2021-06-23T16:40:20.6767191Z     at Object.v [as main] (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cliProcessMain.js:17:48030)
2021-06-23T16:40:20.6768332Z     at runMicrotasks (<anonymous>)
2021-06-23T16:40:20.6769137Z     at processTicksAndRejections (internal/process/task_queues.js:93:5)
2021-06-23T16:40:20.6770718Z     at async R (/home/runner/work/vscode-python/vscode-python/.vscode-test/vscode-insiders/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:12:13996)
2021-06-23T16:40:20.6776112Z (node:2116) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2021-06-23T16:40:20.6780008Z (node:2116) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2021-06-23T16:40:20.6838822Z Starting vscode insiders with args ./src/testMultiRootWkspc/smokeTests --enable-proposed-api --timeout 5000
2021-06-23T16:40:21.0940126Z Found .vscode-test/vscode-insiders matching latest Insiders release. Skipping download.
2021-06-23T16:40:21.4631167Z Warning: 'timeout' is not in the list of known options, but still passed to Electron/Chromium.
2021-06-23T16:40:21.4632256Z 
2021-06-23T16:40:21.4634087Z Warning: 'sandbox' is not in the list of known options, but still passed to Electron/Chromium.
2021-06-23T16:40:21.4634645Z 
2021-06-23T16:40:21.5079585Z [90m[main 2021-06-23T16:40:21.507Z][0m window: using vscode-file:// protocol and V8 cache options: bypassHeatCheck
2021-06-23T16:40:21.5080750Z 
2021-06-23T16:40:21.5581044Z [90m[main 2021-06-23T16:40:21.557Z][0m update#setState idle
2021-06-23T16:40:21.5581550Z 
2021-06-23T16:40:24.1366022Z (node:2382) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
2021-06-23T16:40:24.1368788Z (Use `code-insiders --trace-deprecation ...` to show where the warning was created)
2021-06-23T16:40:24.1369580Z 
2021-06-23T16:40:51.5736697Z [90m[main 2021-06-23T16:40:51.572Z][0m update#setState checking for updates
2021-06-23T16:40:51.5737672Z 
2021-06-23T16:40:51.6249081Z [90m[main 2021-06-23T16:40:51.624Z][0m update#setState idle
2021-06-23T16:40:51.6250152Z 
2021-06-23T16:43:25.2085360Z Error: Failed to initialize Python extension for tests after 3 minutes
2021-06-23T16:43:25.2088119Z     at activatePythonExtensionScript (/home/runner/work/vscode-python/vscode-python/out/test/index.js:58:16)
2021-06-23T16:43:25.2089829Z     at Object.run (/home/runner/work/vscode-python/vscode-python/out/test/index.js:85:15)
2021-06-23T16:43:25.2090450Z 
2021-06-23T17:40:51.6436179Z [90m[main 2021-06-23T17:40:51.642Z][0m update#setState checking for updates
2021-06-23T17:40:51.6437213Z 
2021-06-23T17:40:51.8402047Z [90m[main 2021-06-23T17:40:51.839Z][0m update#setState idle
2021-06-23T17:40:51.8402871Z 
2021-06-23T18:40:51.7455493Z [90m[main 2021-06-23T18:40:51.743Z][0m update#setState checking for updates
2021-06-23T18:40:51.7456553Z 
2021-06-23T18:40:51.9524604Z [90m[main 2021-06-23T18:40:51.951Z][0m update#setState idle
2021-06-23T18:40:51.9525646Z 
2021-06-23T19:40:51.8231326Z [90m[main 2021-06-23T19:40:51.822Z][0m update#setState checking for updates
2021-06-23T19:40:51.8232292Z 
2021-06-23T19:40:52.0345140Z [90m[main 2021-06-23T19:40:52.033Z][0m update#setState idle
2021-06-23T19:40:52.0345649Z 
2021-06-23T20:40:51.8549721Z [90m[main 2021-06-23T20:40:51.854Z][0m update#setState checking for updates
2021-06-23T20:40:51.8550727Z 
2021-06-23T20:40:52.0623315Z [90m[main 2021-06-23T20:40:52.061Z][0m update#setState idle
2021-06-23T20:40:52.0624124Z 
2021-06-23T21:40:51.9443845Z [90m[main 2021-06-23T21:40:51.942Z][0m update#setState checking for updates
2021-06-23T21:40:51.9445268Z 
2021-06-23T21:40:52.1361990Z [90m[main 2021-06-23T21:40:52.135Z][0m update#setState idle
2021-06-23T21:40:52.1362918Z 
2021-06-23T22:37:48.3658741Z ##[error]The operation was canceled.
```
</p>
</details>

June 23, 2:04pm https://github.com/microsoft/vscode-python/runs/2899210736 (going to cancel it)

![image](https://user-images.githubusercontent.com/51720070/123180120-812a6700-d43f-11eb-9127-532130c6571c.png)

**Comment by DonJayamanne** [comment]
I'm assuming these have since been resolved.
