### ISSUE TITLE
Session cannot generate requests

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode-jupyter#6604]
Issue Type: <b>Bug</b>

# Behaviour

Get a "Session cannot generate requests" without any additional details.

## Expected

At least a button to restart VS Code, Python, the world … whatever needs restarting to fix this Session.

## Actual

No button or action to get out of this.

## Steps to reproduce:

1. I was running a Notebook in a Dev Container, all working.
2. Got a "Kernel is dead" error.
3. Hit "Restart", hoping this would fix it.
5. Now I get a "Session cannot generate requests" without any additional details.

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.3
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): unknown
-   Value of the `python.languageServer` setting: Jedi

<details>

<summary>"Python" channel in the OUTPUT panel</summary>

<p>

```
Error 2021-07-09 19:27:46: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://dev-container+7b22686f737450617468223a222f55736572732f64696769746172616c642f7265706f732f6465766469762d6d6574726963732d616e642d616e616c79736573222c2273657474696e6773223a7b22636f6e74657874223a226465736b746f702d6c696e7578227d7d/root/.config/Code - Insiders/User/settings.json' (Error: Unable to resolve non-existing file 'vscode-remote://dev-container+7b22686f737450617468223a222f55736572732f64696769746172616c642f7265706f732f6465766469762d6d6574726963732d616e642d616e616c79736573222c2273657474696e6773223a7b22636f6e74657874223a226465736b746f702d6c696e7578227d7d/root/.config/Code - Insiders/User/settings.json')
	at _handleError (/vscode/vscode-server-insiders/bin/x64/2d23c42a936db1c7b3b06f918cde29561cc47cd6-insider/out/vs/server/remoteExtensionHostProcess.js:84:167834)
	at async y.readText (/root/.vscode-server-insiders/extensions/ms-python.python-2021.7.1012204448-dev/out/client/extension.js:9:344114)
	at async p.doesFileNeedToBeFixed (/root/.vscode-server-insiders/extensions/ms-python.python-2021.7.1012204448-dev/out/client/extension.js:59:589055)
	at async /root/.vscode-server-insiders/extensions/ms-python.python-2021.7.1012204448-dev/out/client/extension.js:59:588182
	at async Promise.all (index 0)
	at async p.getFilesToBeFixed (/root/.vscode-server-insiders/extensions/ms-python.python-2021.7.1012204448-dev/out/client/extension.js:59:588128)
	at async p.updateTestSettings (/root/.vscode-server-insiders/extensions/ms-python.python-2021.7.1012204448-dev/out/client/extension.js:59:587755)] {
  code: 'FileNotFound'
}
Error 2021-07-09 19:27:46: Diagnostic Code: InvalidPythonInterpreterDiagnostic, Message: No Python interpreter is selected. You need to select a Python interpreter to enable features such as IntelliSense, linting, and debugging.
Error 2021-07-09 19:40:35: stderr jediProxy Error (stderr) /root/.vscode-server-insiders/extensions/ms-python.python-2021.7.1012204448-dev/pythonFiles/completion.py:596: DeprecationWarning: Providing the line is now done in the functions themselves like `Script(...).complete(line, column)`
  sys_path=sys.path,

Error 2021-07-09 19:40:35: stderr jediProxy Error (stderr) /root/.vscode-server-insiders/extensions/ms-python.python-2021.7.1012204448-dev/pythonFiles/completion.py:596: DeprecationWarning: Providing the column is now done in the functions themselves like `Script(...).complete(line, column)`
  sys_path=sys.path,
/root/.vscode-server-insiders/extensions/ms-python.python-2021.7.1012204448-dev/pythonFiles/completion.py:596: DeprecationWarning: Deprecated since version 0.17.0. Use the project API instead, which means Script(project=Project(dir, sys_path=sys_path)) instead.
  sys_path=sys.path,

Error 2021-07-09 19:40:35: stderr jediProxy Error (stderr) /root/.vscode-server-insiders/extensions/ms-python.python-2021.7.1012204448-dev/pythonFiles/completion.py:624: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).infer instead.
  script.goto_definitions(), request["id"]

Error 2021-07-09 19:40:44: stderr jediProxy Error (stderr) /root/.vscode-server-insiders/extensions/ms-python.python-2021.7.1012204448-dev/pythonFiles/completion.py:601: DeprecationWarning: Deprecated since version 0.16.0. Use Script(...).goto instead.
  script.goto_assignments(follow_imports=True), request["id"]

Error 2021-07-09 19:40:44: stderr jediProxy Error (stderr) Traceback (most recent call last):
  File "/root/.vscode-server-insiders/extensions/ms-python.python-2021.7.1012204448-dev/pythonFiles/completion.py", line 657, in watch
    response = self._process_request(rq)
  File "/root/.vscode-server-insiders/extensions/ms-python.python-2021.7.1012204448-dev/pythonFiles/completion.py", line 601, in _process_request
    script.goto_assignments(follow_imports=True), request["id"]
  File "/root/.vscode-server-insiders/extensions/ms-python.python-2021.7.1012204448-dev/pythonFiles/lib/python/jedi/api/__init__.py", line 353, in goto_assignments
    **kwargs)
  File "/root/.vscode-server-insiders/extensions/ms-python.python-2021.7.1012204448-dev/pythonFiles/lib/python/jedi/api/helpers.py", line 486, in wrapper
    column, line_len, line, line_string))
ValueError: `column` parameter (17) is not in a valid range (0-1) for line 1 ('{\n').


Error 2021-07-09 19:40:44: stderr jediProxy Error (stderr) Traceback (most recent call last):
  File "/root/.vscode-server-insiders/extensions/ms-python.python-2021.7.1012204448-dev/pythonFiles/completion.py", line 657, in watch
    response = self._process_request(rq)
  File "/root/.vscode-server-insiders/extensions/ms-python.python-2021.7.1012204448-dev/pythonFiles/completion.py", line 601, in _process_request
    script.goto_assignments(follow_imports=True), request["id"]
  File "/root/.vscode-server-insiders/extensions/ms-python.python-2021.7.1012204448-dev/pythonFiles/lib/python/jedi/api/__init__.py", line 353, in goto_assignments
    **kwargs)
  File "/root/.vscode-server-insiders/extensions/ms-python.python-2021.7.1012204448-dev/pythonFiles/lib/python/jedi/api/helpers.py", line 486, in wrapper
    column, line_len, line, line_string))
ValueError: `column` parameter (17) is not in a valid range (0-1) for line 1 ('{\n').


```

</p>
</details>

Extension version: 2021.8.1013163132
VS Code version: Code - Insiders 1.58.0-insider (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-07T12:08:00.172Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No
Remote OS version: Linux x64 5.10.25-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (17.36GB free)|
|Process Argv|--enable-proposed-api donjayamanne.kusto --crash-reporter-id 4cf0a6f0-aaf8-4da3-9b2b-81f6c639c12b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container @ desktop-linux|
|OS|Linux x64 5.10.25-linuxkit|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (8 x 2400)|
|Memory (System)|1.94GB (1.41GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
vspre833:30321513
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscorehov:30301224
00j7a122:30294756
vscod805:30301674
pythonvspyt200:30323110
vscextlang:30310088
vsccppwtct:30312693
bridge0708:30335490

```

</details>

**Comment by claudiaregio** [comment]
@digitarald Could you provide the logs from the Jupyter output?

**Comment by mcchong** [comment]
Also seeing this bug since latest update on linux, unfortunately don't have time to add any info.

**Comment by DonJayamanne** [comment]
@mcchong Please could you file a separate issue with provide the output from the Jupyter output panel.
Closing this issue as its stale.
