### ISSUE TITLE
ipykernel not found in env that has it

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#6644]
## Environment data

-   VS Code version: 1.58
-   Jupyter Extension version: v2021.8.1013163132
-   Python Extension version: v2021.6.944021595
-   Pylance Extension version: v2021.7.2

## Steps to reproduce: 
1. Follow instructions here https://github.com/holoviz/holoviz/blob/master/doc/installation.rst *but* replace "anaconda-project run jupyter notebook" command with "anaconda-project run", followed by "code ."
2. Open "Setup" notebook 
3. Change Python interpreter to the provided holoviz one
4. Reload to resolve diagnostics
5. Reload again and select corresponding kernel to holoviz env
6. Try to run first code cell
7. Get modal message prompting to install ipykernel, select install 

## Expected behavior
For ipykernel to install and be able to run cells

## Actual behavior
Stuck in endless loop of being told to install ipykernel when trying to run cell 

**Edit: I checked in through Conda CLI that ipykernel is actually installed here, yet I am stuck in the endless loop because it appears not to be finding it.

**Comment by DonJayamanne** [comment]
@claudiaregio Please could you try this again & upload the logs from `Jupyter` output panel.

**Comment by rdillinger** [comment]
This just started for today - everything worked fine yesterday, no changes didn't even close my code down, went to run today and getting message that ipykernel is not installed or needs updated.

**Comment by DonJayamanne** [comment]
@rdillinger Please could you create a new issue with the details requestd in the issue template.

**Comment by rdillinger** [comment]
Hi, yes, happy to, can you remind me what steps I need to take to get the complete log output? The main jupyter error I'm getting is that it is trying to exec an import ipykernel and failing (this either wasn't happening yesterday or wasn't failing yesterday).

Info 2021-07-23 14:50:54: Process Execution: > ~\anaconda3\python.exe -c "import ipykernel"
> ~\anaconda3\python.exe -c "import ipykernel"
Info 2021-07-23 14:50:54: Process Execution: > ~\anaconda3\python.exe -c "import ipykernel"
> ~\anaconda3\python.exe -c "import ipykernel"
Error 2021-07-23 14:50:59: Install Missing Dependencies, Class name = w, completed in 11234ms, has a falsy return value, Return Value: undefined [a [Error]: IPyKernel not installed into interpreter Python 3.7.3 64-bit ('anaconda3': conda):C:\Users\dillinra\anaconda3\python.exe
	at w.handleKernelDependencyResponse (c:\Users\dillinra\.vscode\extensions\ms-toolsai.jupyter-2021.8.1054968649\out\client\extension.js:90:246461)
	at w.installMissingDependencies (c:\Users\dillinra\.vscode\extensions\ms-toolsai.jupyter-2021.8.1054968649\out\client\extension.js:90:245644)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)] {
  category: 'noipykernel',
  reason: 1
}
Error 2021-07-23 14:50:59: Raw session failed to start because dependencies not installed
Info 2021-07-23 14:50:59: Shutdown session -- complete

**Comment by DonJayamanne** [comment]
@rdillinger 
* What version of Jupyter extension do you have now?
* Please could you roll back to the previous version of the Jupyter extension & try it out

**Comment by rdillinger** [comment]
@DonJayamanne  - I just tried every extension back 5 months. Extensions prior to one month ago results in a complete "cannot launch notebook" error. Extension versions within the last month all (now) are resulting in the same kernel error and log results.

This was generated with Jupyter version 2021.6.999406279.

Info 2021-07-23 16:12:21: Starting raw kernel Python 3.7.3 64-bit ('anaconda3': conda)
Info 2021-07-23 16:12:21: installMissingDependencies C:\Users\dillinra\anaconda3\python.exe
Info 2021-07-23 16:12:29: Cached data exists getEnvironmentVariables, <No Resource>
Info 2021-07-23 16:12:30: Process Execution: > ~\anaconda3\python.exe -c "import ipykernel"
> ~\anaconda3\python.exe -c "import ipykernel"
Info 2021-07-23 16:12:30: Process Execution: > ~\anaconda3\python.exe -c "import ipykernel"
> ~\anaconda3\python.exe -c "import ipykernel"
Error 2021-07-23 16:12:36: Install Missing Dependencies, Class name = w, completed in 14749ms, has a falsy return value, Return Value: undefined [a [Error]: IPyKernel not installed into interpreter Python 3.7.3 64-bit ('anaconda3': conda):C:\Users\dillinra\anaconda3\python.exe
	at w.handleKernelDependencyResponse (c:\Users\dillinra\.vscode\extensions\ms-toolsai.jupyter-2021.6.999406279\out\client\extension.js:90:244702)
	at w.installMissingDependencies (c:\Users\dillinra\.vscode\extensions\ms-toolsai.jupyter-2021.6.999406279\out\client\extension.js:90:244075)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)] {
  category: 'noipykernel',
  reason: 1
}
Error 2021-07-23 16:12:36: Raw session failed to start because dependencies not installed
Info 2021-07-23 16:12:36: Shutdown session -- complete

**Comment by DonJayamanne** [comment]
@rdillinger 
So it doesn't work in any version of Jupyter. Hence I dont think its a regression at our end.
Pelase could you do me a favor, please ensure you have the latest version of the extesnion.
Replicate the issue & then:
* Copy all of the output from the `Jupyter` output panel, and upload that here.
* Screenshot of VSCode (I'd like to see the Kernel selected, on the top right)./
* Provide the following information:
	* What version of Python
	* Are you using the base conda environment or a specific conda environment
* Try the following in a terminal
	* Activate the conda environment you are using in the notebook
	* Run the following code
	* `python -c 'import ipykernel;print(ipykernel.__version__)'`
	* Let me what you get

**Comment by rdillinger** [comment]
Hi, Yes. 
![image](https://user-images.githubusercontent.com/8728250/126844254-9b21fa8b-e67e-4f4d-bc73-feb8136c319a.png)
I will be back in a moment with the log after using the most current extension version.

**Comment by rdillinger** [comment]
[JupyterError Output Log.txt](https://github.com/microsoft/vscode-jupyter/files/6871359/JupyterError.Output.Log.txt)

**Comment by rdillinger** [comment]
The main thing is that everything has worked very well for months, then today it just stopped - I hadn't run any package upgrades, version upgrades, and I hadn't even closed my code. I just walked away from computer, and when I came back, I was getting the error message in the screenshot above. 

After troubleshooting today, I'm not sure if the logs would be identical to ones I would have seen when this message first appeared, but I appreciate your help!

**Comment by DonJayamanne** [comment]
@rdillinger are you still running into this issue with the latest versions of the Python & Jupyter extesnions?

**Comment by rdillinger** [comment]
Hi,

Yes, I've been unable to run jupyter files since I reported it.
________________________________

**Comment by DonJayamanne** [comment]
Can you launch Jupyter using the command line? Out side vs code?
Based on your previous messages this seems to be the case. Meaning something else has changed outside vscode. 

> ctivate the conda environment you are using in the notebook - when I try to run conda activate conda in terminal, it gives me an error message about conda not being a recognized command

This would happen with updates to the OS or the like (that results in changes to your startup shell scripts, hence breaking conda in the terminals)

**Comment by DonJayamanne** [comment]
Please confirm it works in your terminal. if not, then i'm sorry, but I'm not sure we can do anything as its outside the control of VS Code.
You might want to check setting up conda for your shell `conda init` or the like.

**Comment by rdillinger** [comment]
My it group runs periodic windows updates, but they'd never broken the shell scripts before with them. It could be that. I generally don't run in command line, only inside vscode. How would I get it running again?
________________________________

**Comment by rdillinger** [comment]
Thank you, I'll try that, fingers crossed
________________________________

**Comment by DonJayamanne** [comment]
Thanks, I'm closing this issue as its outside the control of VS Code.
Do let us know if that works.

**Comment by rdillinger** [comment]
Hi,

I don't think it's an outside of vscode problem. I can run jupyter notebook perfectly, same kernel and python instance. I'm only getting an error connecting to the kernel inside vscode. I ran the conda inits, and that did not resolve the error.
________________________________

**Comment by DonJayamanne** [comment]
>  ran the conda inits, and that did not resolve the error.

THanks for the feedback, however I'm a little confused now. 

* Does conda work in the terminal in vscode (using VS Codes termina)?
* Does conda work in the terminal outside vscode?
* Please could you provide the following information:
	* VS Code version
	* Jupyter extenison version
	* Conda version
	* Python version
	* Outputs from your `Jupyter Output` panel when you get the errors

**Comment by rdillinger** [comment]
Hi,

Conda doesn't work in the vscode terminal, but it does work outside of vscode in both the anaconda terminal and the regular terminal.

Vscode version: 1.59.1
Python version: 3.7.3
Conda version: 4.7.10
Jupyter ext version: I have tried every version created in the last 6 months.
________________________________

**Comment by rdillinger** [comment]
Hi, also, regarding output, I only get two pop up boxes, one says to reinstall or change the kernel (neither option succeeds), and a message box that says ipykernel is not installed (which I've checked, and it is installed)
________________________________

**Comment by DonJayamanne** [comment]
> but it does work outside of vscode in both the anaconda terminal and the regular terminal.

* What's your terminal inside vscode & outside vscode?
* Try toggling the value in your settings to see if this makes a difference (please try true & false)
`terminal.integrated.inheritEnv`

> Hi, also, regarding output, I only get two pop up boxes, 

Go into the command palette and select `Jupyter: Show Output`. on the bottom you'll see an output panel with the name `Jupyter`, please copy the contents from that screen (you might want to maximize the screen to copy all of the output)

**Comment by rdillinger** [comment]
Hi,

Outside vscode I'm referring to the conda terminal and a regular windows terminal.

Here the jupyter output from vscode.

Thank you
________________________________

**Comment by DonJayamanne** [comment]
Ok, so it looks like conda isn't working at all in VS Code.
Basically this isn't a problem with the extension or VS Code, but something to do with your setup.

Here are a few things i'll need:
* What shell are you using? Powershell or command prompt or other in VS Code?

**Comment by rdillinger** [comment]
I can use any of those. I dont use a shell directly for much these days, but when I do it's usually command prompt or powershell.

Thank you, appreciate the help

________________________________

**Comment by DonJayamanne** [comment]
Please could you provide the information requested. Thanks

**Comment by rdillinger** [comment]
Hi sorry I was not forgetting about this, I am traveling and not able to work today. Friday?
________________________________
