### ISSUE TITLE
Jupyter Export to py

### ISSUE THREAD

**Issue by cidmedeiros** [microsoft/vscode-jupyter#6671]
After the new update on the Jupyter Notebook, the exporting notebook to .py version feature is no longer responsive. You click the button Export, and absolutely nothing happens.

Version: 1.58.1 (user setup)
Commit: 2aeda6b18e13c4f4f9edf6667158a6b8d408874b
Date: 2021-07-13T06:58:28.115Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by claudiaregio** [comment]
Hi @cidmedeiros, I am able to reproduce this issue.

**Comment by mjpieters** [comment]
I see the same, the error in the extensions host log is:

```
[2021-07-28 14:35:11.279] [exthost] [error] TypeError: Cannot assign to read only property 'cells' of object '#<Object>'
    at f.serialize (/Users/mj/.vscode/extensions/ms-toolsai.jupyter-2021.8.1054968649/out/client/extension.js:24:257700)
    at f.serializeNotebookDocument (/Users/mj/.vscode/extensions/ms-toolsai.jupyter-2021.8.1054968649/out/client/extension.js:24:257528)
    at getContent (/Users/mj/.vscode/extensions/ms-toolsai.jupyter-2021.8.1054968649/out/client/extension.js:90:285261)
    at m.export (/Users/mj/.vscode/extensions/ms-toolsai.jupyter-2021.8.1054968649/out/client/extension.js:37:301125)
    at m.<anonymous> (/Users/mj/.vscode/extensions/ms-toolsai.jupyter-2021.8.1054968649/out/client/extension.js:37:300171)
    at m.<anonymous> (/Users/mj/.vscode/extensions/ms-toolsai.jupyter-2021.8.1054968649/out/client/extension.js:90:529736)
    at S._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:120585)
    at S.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:121023)
    at c._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:12743)
    at c._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:12435)
    at c._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:11097)
    at c._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:9900)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:8004
    at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1726)
    at h.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15777)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:29836
    at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1726)
    at h.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15777)
    at r._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:21035)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:17921
    at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1726)
    at u.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:13138)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12486
    at Socket._ (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:13107)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) jupyter.exportAsPythonScript
```

**Comment by DonJayamanne** [comment]
@mjpieters Thanks for sharing that information, & I'm sorry you're running into this issue.
Please note, this issue has been fixed in Insider build of VS Code and you'll have the fix in the next release (next week).

**Comment by mjpieters** [comment]
> @mjpieters Thanks for sharing that information, & I'm sorry you're running into this issue.
> Please note, this issue has been fixed in Insider build of VS Code and you'll have the fix in the next release (next week).

I am on the insider build release cycle, and indeed, exporting now works! :-)

**Comment by DonJayamanne** [comment]
Thanks for getting back with a confirmation
