### ISSUE TITLE
Kernel died with exit code 1 when trying to run jupyter notebook in VS code

### ISSUE THREAD

**Issue by Metaming** [microsoft/vscode-jupyter#6716]
Got some issue after the recent update of VS code.
 Great thanks if you could give any hint.

## Environment data

-   VS Code version: 1.58.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1013163132
-   Python Extension version (available under the Extensions sidebar): v2021.6.944021595
-   OS (Windows | Mac | Linux distro) and version: Windows_NT x64 10.0.19041
-   Python and/or Anaconda version: 3.6.5 64-bit ('base': conda)
-   Type of virtual environment used: conda
-   Jupyter server running: Local 

## Expected behaviour

run through codes in jupyter notebook

## Actual behaviour

Kernel died when start running the cell (but using jupyter notebook can run through directly) 

Kernel died with exit code 1. Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Users\Username\AppData\Roaming\Python\Python36\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "D:\Users\Username\AppData\Roaming\Python\Python36\site-packages\traitlets\config\application.py", line 663, in launch_instance
    app.initialize(argv)
  File "D:\Users\Username\AppData\Roaming\Python\Python36\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\Users\Username\AppData\Roaming\Python\Python36\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "D:\Users\Username\AppData\Roaming\Python\Python36\site-packages\ipykernel\kernelapp.py", line 570, in initialize
    self.write_connection_file()
  File "D:\Users\Username\AppData\Roaming\Python\Python36\site-packages\ipykernel\kernelapp.py", line 232, in write_connection_file
    iopub_port=self.iopub_port, control_port=self.control_port)
  File "D:\Users\Username\AppData\Roaming\Python\Python36\site-packages\jupyter_client\connect.py", line 158, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "D:\Users\Username\AppData\Roaming\Python\Python36\site-packages\jupyter_core\paths.py", line 461, in secure_write
    win32_restrict_file_to_user(fname)
  File "D:\Users\Username\AppData\Roaming\Python\Python36\site-packages\jupyter_core\paths.py", line 387, in win32_restrict_file_to_user
    import win32api
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by DavidKutu** [comment]
@Metaming could you upload the output from the `Jupyter` output panel? (View | Output)

Thanks.

**Comment by Metaming** [comment]
[kernal_error_2021-07-20.docx](https://github.com/microsoft/vscode-jupyter/files/6844813/kernal_error_2021-07-20.docx)

Many thanks @DavidKutu

**Comment by Metaming** [comment]
> [kernal_error_2021-07-20.docx](https://github.com/microsoft/vscode-jupyter/files/6844813/kernal_error_2021-07-20.docx)
> 
> Many thanks @DavidKutu

Hi, @DavidKutu, could you confirm if the output I sent was the one you required? 

Please feel free to let me know if you need additional information. 

Great thanks!

**Comment by greazer** [comment]
@Metaming, please update to the latest jupyter extension. This problem should be fixed there.

**Comment by DonJayamanne** [comment]
@Metaming just wanted to check if this is working for you
