### ISSUE TITLE
Running cell stopped working 

### ISSUE THREAD

**Issue by ofiryaish** [microsoft/vscode-jupyter#6800]
I'm using the latest version.

I succeed to run cell, and now it is not working for me anymore, and I get this message:

```
Traceback (most recent call last):
  File "/users/agnon/year2016/yaishof/.local/lib/python3.6/site-packages/nbformat/validator.py", line 12, in <module>
    from jsonschema import ValidationError
  File "/users/agnon/year2016/yaishof/.local/lib/python3.6/site-packages/jsonschema/__init__.py", line 11, in <module>
    from jsonschema.exceptions import (
  File "/users/agnon/year2016/yaishof/.local/lib/python3.6/site-packages/jsonschema/exceptions.py", line 9, in <module>
    import attr
ModuleNotFoundError: No module named 'attr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/users/agnon/year2016/yaishof/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1054968649/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py", line 54, in _decorator
    return func(self, *args, **kwargs)
  File "/users/agnon/year2016/yaishof/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1054968649/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py", line 108, in m_exec_module_observable
    self._start_notebook(args, cwd, env)
  File "/users/agnon/year2016/yaishof/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.1054968649/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py", line 154, in _start_notebook
    from notebook import notebookapp as app
  File "/users/agnon/year2016/yaishof/.local/lib/python3.6/site-packages/notebook/notebookapp.py", line 85, in <module>
    from .services.contents.manager import ContentsManager
  File "/users/agnon/year2016/yaishof/.local/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 17, in <module>
    from nbformat import sign, validate as validate_nb, ValidationError
  File "/users/agnon/year2016/yaishof/.local/lib/python3.6/site-packages/nbformat/__init__.py", line 32, in <module>
    from .validator import validate, ValidationError
  File "/users/agnon/year2016/yaishof/.local/lib/python3.6/site-packages/nbformat/validator.py", line 23, in <module>
    raise ImportError(str(e) + verbose_msg)
ImportError: No module named 'attr'

    Jupyter notebook format depends on the jsonschema package:

        https://pypi.python.org/pypi/jsonschema

    Please install it first.
    

Failed to run jupyter as observable with args notebook --no-browser --notebook-dir="/data/yaishof/deg_project_revision/deg_project_revision_TF_1" --config=/tmp/de01b7d8-a0bd-4e82-8364-04db3be26581/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
```

I already got those packages, so I don't know what the problem is. In addition, in any environment, I got the same problem 
I tried to reinstall but got the same issue.
What can be the problem

Thank you,
Ofir

**Comment by joyceerhl** [comment]
@ofiryaish Some quick questions:

1. Which environment are you trying to use? It's possible that we are starting a kernel corresponding to the wrong environment
2. If you create a fresh virtual environment and reinstall all your dependencies there, then select that environment to run cells in, does that help?
3. Could you please share the full Jupyter output log? The output above appears to be a small snippet.

Thanks!

**Comment by ofiryaish** [comment]
Sorry for the late response. 
After a couple of reinstalling of the Visual code on the server, it started to work.
