### ISSUE TITLE
Cannot specify number of threads for kernel?

### ISSUE THREAD

**Issue by pagnani** [microsoft/vscode-jupyter#6803]
## Environment data

-   VS Code version: 1.59.0-insider (Universal)
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1055544705
-   Python Extension version (available under the Extensions sidebar): v2021.7.1060902895
-   OS (Windows | Mac | Linux distro) and version: MAC OS X BigSur
-   Python and/or Anaconda version: Python 3.8.8 (default, Apr 13 2021, 12:59:45)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local 

## Expected behaviour

Julia kernel 1.6.2 (8 threads) starts

## Actual behaviour

Kernel does not start

## Steps to reproduce:

Create a 8 threads julia kernel with
```
using IJulia
installkernel("Julia_8_threads", env=Dict("JULIA_NUM_THREADS"=>"8"))
```
Jupyter: Create new blank notebook (from VSCODE) -> set kernel to Julia_8_threads. 

The kernel does not start: Timed out waiting to get a heartbeat from kernel process. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
1. XXX

## Logs

/Applications/Julia-1.6.app/Contents/Resources/julia/bin/julia -i --color=yes ~/.julia/packages/IJulia/e8kqU/src/kernel.jl /var/folders/3r/g2x6wc792nx9j1zvy02vj_tw0000gn/T/tmp-80853YO9nRm0bExu3.json
cwd: /
Error 2021-07-26 09:23:47: Disposing kernel process due to an error [Error: timeout
	at Timeout.<anonymous> (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:52:781106)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)]
Error 2021-07-26 09:23:47: Timed out waiting to get a heartbeat from kernel process.
Error 2021-07-26 09:23:47: Raw session failed to start in given timeout
Error 2021-07-26 09:23:47: failed to create INotebook in kernel, UI Disabled = false [_ [Error]: 
	at new o (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:16:34883)
	at new _ (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:37:559661)
	at w.connect (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:37:561521)
	at async E.createNotebookInstance (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:90:447450)

Error: Timed out waiting to get a heartbeat from kernel process. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
	at b.launch (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:52:775919)] {
  category: 'timeout',
  originalException: [i [Error]: Timed out waiting to get a heartbeat from kernel process. 
  View Jupyter [log](command:jupyter.viewOutput) for further details.
  	at b.launch (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:52:775919)] {
    category: 'timeout'
  }
}
Error 2021-07-26 09:23:47: DataScience Error [i [Error]: Timed out waiting to get a heartbeat from kernel process. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
	at b.launch (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:52:775919)] {
  category: 'timeout'
}
Error 2021-07-26 09:23:47: failed to start INotebook in kernel, UI Disabled = false [_ [Error]: 
	at new o (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:16:34883)
	at new _ (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:37:559661)
	at w.connect (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:37:561521)
	at async E.createNotebookInstance (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:90:447450)

Error: Timed out waiting to get a heartbeat from kernel process. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
	at b.launch (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:52:775919)] {
  category: 'timeout',
  originalException: [i [Error]: Timed out waiting to get a heartbeat from kernel process. 
  View Jupyter [log](command:jupyter.viewOutput) for further details.
  	at b.launch (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:52:775919)] {
    category: 'timeout'
  }
}
Error 2021-07-26 09:23:47: Failed to execute cells in CellExecutionQueue [_ [Error]: 
	at new o (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:16:34883)
	at new _ (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:37:559661)
	at w.connect (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:37:561521)
	at async E.createNotebookInstance (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:90:447450)

Error: Timed out waiting to get a heartbeat from kernel process. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
	at b.launch (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:52:775919)] {
  category: 'timeout',
  originalException: [i [Error]: Timed out waiting to get a heartbeat from kernel process. 
  View Jupyter [log](command:jupyter.viewOutput) for further details.
  	at b.launch (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:52:775919)] {
    category: 'timeout'
  }
}

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by joyceerhl** [comment]
@pagnani The log suggests we failed to start your Julia kernel (the number of threads should be unrelated). Would you mind providing the following information please?
1. Try running simple code that doesn't configure the number of threads and see if the issue persists. If it does persist then this just means there's something wrong with how we're starting Julia kernels in general, or there may be some kernel misconfiguration 
2. Please provide the full Jupyter output log--the log above appears to be truncated

Apologies for the trouble and thank you in advance!

**Comment by pagnani** [comment]
Sorry @joyceerhl, I should have specify it in the original report: the problem is present only when I try to set the number of threads. I have another perfectly functioning kernel (julia 1.6.2) with only 1 thread. Also it might be of interest that the 8 threads kernel which I'm trying to use works perfectly as a Jupyther notebook (on chrome). 

WRT to the log, please find below what I believe is the complete one. Is there a clean way to fetch it other than copy and paste from the output tab of VSCODE?

```
> /Applications/Julia-1.6.app/Contents/Resources/julia/bin/julia -i --color=yes --project=@. ~/.julia/packages/IJulia/e8kqU/src/kernel.jl /var/folders/3r/g2x6wc792nx9j1zvy02vj_tw0000gn/T/tmp-80853AoIsOU3pqtIB.json
cwd: /
Started kernel Julia 1.6.2
> /Applications/Julia-1.6.app/Contents/Resources/julia/bin/julia -i --color=yes --project=@. ~/.julia/packages/IJulia/e8kqU/src/kernel.jl /var/folders/3r/g2x6wc792nx9j1zvy02vj_tw0000gn/T/tmp-80853X9L2q91nxLXe.json
cwd: /
> /Applications/Julia-1.6.app/Contents/Resources/julia/bin/julia -i --color=yes ~/.julia/packages/IJulia/e8kqU/src/kernel.jl /var/folders/3r/g2x6wc792nx9j1zvy02vj_tw0000gn/T/tmp-80853bVwbJWmH2AlZ.json
cwd: /
Error 2021-07-26 19:26:56: Disposing kernel process due to an error [Error: timeout
	at Timeout.<anonymous> (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:52:781106)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)]
Error 2021-07-26 19:26:56: Timed out waiting to get a heartbeat from kernel process.
Error 2021-07-26 19:26:56: Raw session failed to start in given timeout
Error 2021-07-26 19:26:56: failed to create INotebook in kernel, UI Disabled = true [_ [Error]: 
	at new o (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:16:34883)
	at new _ (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:37:559661)
	at w.connect (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:37:561521)
	at async E.createNotebookInstance (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:90:447450)

Error: Timed out waiting to get a heartbeat from kernel process. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
	at b.launch (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:52:775919)] {
  category: 'timeout',
  originalException: [i [Error]: Timed out waiting to get a heartbeat from kernel process. 
  View Jupyter [log](command:jupyter.viewOutput) for further details.
  	at b.launch (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:52:775919)] {
    category: 'timeout'
  }
}
Error 2021-07-26 19:26:56: failed to start INotebook in kernel, UI Disabled = true [_ [Error]: 
	at new o (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:16:34883)
	at new _ (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:37:559661)
	at w.connect (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:37:561521)
	at async E.createNotebookInstance (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:90:447450)

Error: Timed out waiting to get a heartbeat from kernel process. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
	at b.launch (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:52:775919)] {
  category: 'timeout',
  originalException: [i [Error]: Timed out waiting to get a heartbeat from kernel process. 
  View Jupyter [log](command:jupyter.viewOutput) for further details.
  	at b.launch (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:52:775919)] {
    category: 'timeout'
  }
}
Error 2021-07-26 19:26:56: Failed to execute cells in CellExecutionQueue [_ [Error]: 
	at new o (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:16:34883)
	at new _ (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:37:559661)
	at w.connect (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:37:561521)
	at async E.createNotebookInstance (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:90:447450)

Error: Timed out waiting to get a heartbeat from kernel process. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
	at b.launch (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:52:775919)] {
  category: 'timeout',
  originalException: [i [Error]: Timed out waiting to get a heartbeat from kernel process. 
  View Jupyter [log](command:jupyter.viewOutput) for further details.
  	at b.launch (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:52:775919)] {
    category: 'timeout'
  }
}
> /Applications/Julia-1.6.app/Contents/Resources/julia/bin/julia -i --color=yes ~/.julia/packages/IJulia/e8kqU/src/kernel.jl /var/folders/3r/g2x6wc792nx9j1zvy02vj_tw0000gn/T/tmp-80853qdYlVvm4AVf2.json
cwd: /
Error 2021-07-26 19:28:48: Disposing kernel process due to an error [Error: timeout
	at Timeout.<anonymous> (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:52:781106)
	at listOnTimeout (internal/timers.js:554:17)
	at processTimers (internal/timers.js:497:7)]
Error 2021-07-26 19:28:48: Timed out waiting to get a heartbeat from kernel process.
Error 2021-07-26 19:28:48: Raw session failed to start in given timeout
Error 2021-07-26 19:28:48: failed to create INotebook in kernel, UI Disabled = false [_ [Error]: 
	at new o (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:16:34883)
	at new _ (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:37:559661)
	at w.connect (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:37:561521)
	at async E.createNotebookInstance (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:90:447450)

Error: Timed out waiting to get a heartbeat from kernel process. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
	at b.launch (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:52:775919)] {
  category: 'timeout',
  originalException: [i [Error]: Timed out waiting to get a heartbeat from kernel process. 
  View Jupyter [log](command:jupyter.viewOutput) for further details.
  	at b.launch (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:52:775919)] {
    category: 'timeout'
  }
}
Error 2021-07-26 19:28:48: DataScience Error [i [Error]: Timed out waiting to get a heartbeat from kernel process. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
	at b.launch (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:52:775919)] {
  category: 'timeout'
}
Error 2021-07-26 19:28:48: failed to start INotebook in kernel, UI Disabled = false [_ [Error]: 
	at new o (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:16:34883)
	at new _ (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:37:559661)
	at w.connect (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:37:561521)
	at async E.createNotebookInstance (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:90:447450)

Error: Timed out waiting to get a heartbeat from kernel process. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
	at b.launch (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:52:775919)] {
  category: 'timeout',
  originalException: [i [Error]: Timed out waiting to get a heartbeat from kernel process. 
  View Jupyter [log](command:jupyter.viewOutput) for further details.
  	at b.launch (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:52:775919)] {
    category: 'timeout'
  }
}
Error 2021-07-26 19:28:48: Failed to execute cells in CellExecutionQueue [_ [Error]: 
	at new o (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:16:34883)
	at new _ (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:37:559661)
	at w.connect (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:37:561521)
	at async E.createNotebookInstance (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:90:447450)

Error: Timed out waiting to get a heartbeat from kernel process. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
	at b.launch (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:52:775919)] {
  category: 'timeout',
  originalException: [i [Error]: Timed out waiting to get a heartbeat from kernel process. 
  View Jupyter [log](command:jupyter.viewOutput) for further details.
  	at b.launch (/Users/pagnani/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.8.1055544705/out/client/extension.js:52:775919)] {
    category: 'timeout'
  }
}
```

**Comment by rchiodo** [comment]
Can you try setting this value to a higher number and see if that fixes the problem?

```
"jupyter.jupyterLaunchTimeout" : 60000
```

Julia can be slow on startup sometimes and it looks like it's exceeding our timeout.

**Comment by pagnani** [comment]
Hi @rchiodo 

I doubled it (set to 120000) and still no heartbeat ... Also, for what matters,  I do not believe that time should be so long as julia kernel startup time does not depend on the number of threads you set.

**Comment by rchiodo** [comment]
If it's not taking longer then it must be the julia kernel isn't returning a heartbeat for some reason. That's what it looks like anyway.

According to the kernel API, they should return a heartbeat whenever we [ping ](https://jupyter-client.readthedocs.io/en/stable/messaging.html#heartbeat-for-kernels) the heartbeat port. And it does with single threaded mode. I don't know why it's not in multithreaded mode. Might be a bug in the kernel.

**Comment by DonJayamanne** [comment]
@pagnani are you still running into the same issues with the latest version of the Jupyter extension?

**Comment by pagnani** [comment]
Did not try in a while ... I'll report here as soon as i get my hands on my
computer

**Comment by DonJayamanne** [comment]
Lets close this for now, do feel free to create a new issue if this problem persists.
