### ISSUE TITLE
Figures not loading: "ReferenceError: atob is not defined"

### ISSUE THREAD

**Issue by grudloff** [microsoft/vscode-jupyter#6815]
## Environment data

-   VS Code version: 1.59.0-insider (user setup)
-   Jupyter Extension version: v2021.8.1066828098
-   Python Extension version: v2021.7.1060902895
-   OS and version: Windows_NT x64 10.0.19041
-   Python and/or Anaconda version: Python 3.8.5 & Conda 4.10.3
-   Type of virtual environment used : conda
-   Jupyter server running: Local

After the last update of vscode, all my notebooks were unable to render figures. Installing previous versions of the extensions didn't fix the issue. Here is a full log from one of the figures:

<details>
  <summary>Log</summary>

  ```
 ReferenceError: atob is not defined
	at d (c:\Users\Usuario\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\ipynb\dist\ipynbMain.js:1:138755)
	at y (c:\Users\Usuario\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\ipynb\dist\ipynbMain.js:1:143435)
	at v (c:\Users\Usuario\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\ipynb\dist\ipynbMain.js:1:143731)
	at Array.map (<anonymous>)
	at c:\Users\Usuario\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\ipynb\dist\ipynbMain.js:1:144883
	at c:\Users\Usuario\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\ipynb\dist\ipynbMain.js:1:145125
	at c:\Users\Usuario\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\ipynb\dist\ipynbMain.js:1:145132
	at Array.map (<anonymous>)
	at e.jupyterNotebookModelToNotebookData (c:\Users\Usuario\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\ipynb\dist\ipynbMain.js:1:144441)
	at e.NotebookSerializer.deserializeNotebook (c:\Users\Usuario\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\extensions\ipynb\dist\ipynbMain.js:1:146368)
	at _.$dataToNotebook (c:\Users\Usuario\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:211883)
	at d._doInvokeHandler (c:\Users\Usuario\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:12819)
	at d._invokeHandler (c:\Users\Usuario\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:12503)
	at d._receiveRequest (c:\Users\Usuario\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:11107)
	at d._receiveOneMessage (c:\Users\Usuario\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:10142)
	at c:\Users\Usuario\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:8039
	at u.fire (c:\Users\Usuario\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
	at l.fire (c:\Users\Usuario\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15825)
	at c:\Users\Usuario\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:30061
	at u.fire (c:\Users\Usuario\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
	at l.fire (c:\Users\Usuario\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15825)
	at r._receiveMessage (c:\Users\Usuario\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:21091)
	at c:\Users\Usuario\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:17969
	at u.fire (c:\Users\Usuario\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
	at v.acceptChunk (c:\Users\Usuario\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:13186)
	at c:\Users\Usuario\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12534
	at Socket.w (c:\Users\Usuario\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:13219)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
  ```
</details>

**Comment by grudloff** [comment]
> Dupe of #[microsoft/vscode#129212](https://github.com/microsoft/vscode/issues/129212)
> 
> Should be fixed in tomorrow's VS code insiders build.

Are you sure its the same issue? I am positive it should be a vscode issue though, should I post it there instead?

**Comment by rchiodo** [comment]
@DonJayamanne do you have any thoughts?

There's another VS code issue which matches what you're seeing @grudloff :
https://github.com/microsoft/vscode/issues/129393

**Comment by DonJayamanne** [comment]
I've closed the upstream issue mentioning where it has been fixed.
