### ISSUE TITLE
Installing ipykernel results in error

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#6896]
Testing #6821

1) create a dev container off https://github.com/microsoft/vscode-remote-try-python
2) create untitled notebook with python code cells
3) select Python 3.9 kernel
4) run cells
5) follow the prompt to install ipykernel
-> 

```
$ /usr/local/bin/python /home/vscode/.vscode-server-insiders/extensions/ms-python.python-2021.7.1060902895/pythonFiles/shell_exec.py /usr/local/bin/python -m pip install -U ipykernel --user /tmp/tmp-4090QrK3GXIexwoZ.log
Executing command in shell >> /usr/local/bin/python -m pip install -U ipykernel --user
ERROR: Can not combine '--user' and '--target'
Traceback (most recent call last):
  File "/home/vscode/.vscode-server-insiders/extensions/ms-python.python-2021.7.1060902895/pythonFiles/shell_exec.py", line 26, in <module>
    subprocess.check_call(shell_args, stdout=sys.stdout, stderr=sys.stderr)
  File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/python', '-m', 'pip', 'install', '-U', 'ipykernel', '--user']' returned non-zero exit status 1.
```

**Comment by DonJayamanne** [comment]
Hmm, some windows users are also running into this https://github.com/microsoft/vscode-python/issues/16844#issuecomment-891155447
& whats interesting is the fact that the `-u` flag doesn't exist.
