### ISSUE TITLE
Unable to run notebooks due to kernel crash

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-jupyter#6919]
## Environment data

-   VS Code version:
Version : 1.59.0-insider (user setup)
Commit : 0f22f2d343e33b03e8033d1083513072f58ece21
Date : 2021-07-29T05:13:10.735Z
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1077987658
-   Python Extension version (available under the Extensions sidebar): v2021.7.1060902895
-   OS (Windows | Mac | Linux distro) and version: Windows
-   Python and/or Anaconda version: 3.9.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): none
-   Jupyter server running: Local

## Expected behaviour

I'd like to run notebooks or interactive windows

## Actual behaviour

While connecting to the kernel, I get the following error:

```
Info 2021-07-29 15:57:07: KernelProcess Exit Exit - 1 Traceback (most recent call last):
  File "C:\Users\raymondzhao\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\raymondzhao\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\raymondzhao\AppData\Roaming\Python\Python39\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\raymondzhao\AppData\Roaming\Python\Python39\site-packages\ipykernel\kernelapp.py", line 38, in <module>
    from .iostream import IOPubThread
  File "C:\Users\raymondzhao\AppData\Roaming\Python\Python39\site-packages\ipykernel\iostream.py", line 27, in <module>
    from jupyter_client.session import extract_header
  File "C:\Users\raymondzhao\AppData\Roaming\Python\Python39\site-packages\jupyter_client\session.py", line 41, in <module>
    from jupyter_client.jsonutil import extract_dates, squash_dates, date_default
  File "C:\Users\raymondzhao\AppData\Roaming\Python\Python39\site-packages\jupyter_client\jsonutil.py", line 10, in <module>
    from dateutil.parser import parse as _dateutil_parse
  File "C:\Users\raymondzhao\AppData\Roaming\Python\Python39\site-packages\dateutil\parser\__init__.py", line 2, in <module>
    from ._parser import parse, parser, parserinfo, ParserError
  File "C:\Users\raymondzhao\AppData\Roaming\Python\Python39\site-packages\dateutil\parser\_parser.py", line 45, in <module>
    from decimal import Decimal
  File "C:\Users\raymondzhao\AppData\Local\Programs\Python\Python39\lib\decimal.py", line 3, in <module>
    from _decimal import *
AttributeError: module 'numbers' has no attribute 'Number'
```

## Steps to reproduce:

1. Run a notebook cell or an interactive cell in a Python file

**Comment by claudiaregio** [comment]
Hi @rzhao271, are you running code to connect to the kernel? The "AttributeError: module 'numbers' has no attribute 'Number'" makes me think you are running code to connect to the kernel. Could you provide a screen recording of what you are doing when you get this error please?

**Comment by rzhao271** [comment]
TIL having a `numbers.py` file in the workspace is a bad idea 👀 

Thanks @joyceerhl!
