### ISSUE TITLE
Kernel died with exit 1 code : Out of disk space 

### ISSUE THREAD

**Issue by Neoanarika** [microsoft/vscode-jupyter#7182]
## Environment data

-   VS Code version:  1.59.0
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1236758218
-   Python Extension version (available under the Extensions sidebar): v2021.8.1105858891
-   OS (Windows | Mac | Linux distro) and version: Linux
-   Python and/or Anaconda version: conda 4.10.3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Remote 

## Expected behaviour

Jupyter notebook connects to kernel

## Actual behaviour

Fails to get connect and the kernel dies with exit code 1, returns the following traceback

Kernel died with exit code 1. /home/mingliang/anaconda3/envs/dgflowenv/lib/python3.7/site-packages/traitlets/traitlets.py:2199: FutureWarning: Supporting extra quotes around Unicode is deprecated in traitlets 5.0. Use 'hmac-sha256' instead of '"hmac-sha256"' – or use CUnicode.
  FutureWarning)
/home/mingliang/anaconda3/envs/dgflowenv/lib/python3.7/site-packages/traitlets/traitlets.py:2154: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use 'c9cfe903-f888-4749-82d9-6b2236f0fe55' instead of 'b"c9cfe903-f888-4749-82d9-6b2236f0fe55"'.
  FutureWarning)
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mingliang/anaconda3/envs/dgflowenv/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/mingliang/anaconda3/envs/dgflowenv/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mingliang/anaconda3/envs/dgflowenv/lib/python3.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/mingliang/anaconda3/envs/dgflowenv/lib/python3.7/site-packages/traitlets/config/application.py", line 844, in launch_instance
    app.initialize(argv)
  File "/home/mingliang/anaconda3/envs/dgflowenv/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in inner
    return method(app, *args, **kwargs)
  File "/home/mingliang/anaconda3/envs/dgflowenv/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 570, in initialize
    self.write_connection_file()
  File "/home/mingliang/anaconda3/envs/dgflowenv/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 232, in write_connection_file
    iopub_port=self.iopub_port, control_port=self.control_port)
  File "/home/mingliang/anaconda3/envs/dgflowenv/lib/python3.7/site-packages/jupyter_client/connect.py", line 137, in write_connection_file
    f.write(json.dumps(cfg, indent=2))
  File "/home/mingliang/anaconda3/envs/dgflowenv/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home/mingliang/anaconda3/envs/dgflowenv/lib/python3.7/site-packages/jupyter_core/paths.py", line 474, in secure_write
    yield f
OSError: [Errno 28] No space left on device

**Comment by rchiodo** [comment]
Thanks for the bug but I believe the error message there is indicating what the problem is. That drive has no space left. We need to be able to write the connection_file in order to connect to the kernel.
