### ISSUE TITLE
Session cannot generate requests on displaying invalid code

### ISSUE THREAD

**Issue by agent031** [microsoft/vscode-jupyter#7190]
## Expected behaviour

Running these:

```
import numpy as np


N = 100
L = np.random.random((N, N))
A = np.identity(N) - 0.1* (np.identity - L)

A
```

Should print a python error due to this operation: `(np.identity - L)`.

## Actual behaviour

Ι get the following error:

```
Error: Session cannot generate requests
Error: Session cannot generate requests
at w.executeCodeCell (c:\Users\chris\.vscode\extensions\ms-toolsai.jupyter-2021.8.1236758218\out\client\extension.js:90:327199)
at w.execute (c:\Users\chris\.vscode\extensions\ms-toolsai.jupyter-2021.8.1236758218\out\client\extension.js:90:326520)
at w.start (c:\Users\chris\.vscode\extensions\ms-toolsai.jupyter-2021.8.1236758218\out\client\extension.js:90:322336)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5)

```
## Steps to reproduce:

Run the above python code in three cells.

**Comment by rchiodo** [comment]
Thanks for the bug.

I can't seem to repro the issue. I get this:

![image](https://user-images.githubusercontent.com/19672699/129937530-d9c750ed-4213-4e9d-9de8-6f629338c2d0.png)


My only guess is that your version of numpy or ipykernel is crashing the kernel with that code.

My versions are these:

![image](https://user-images.githubusercontent.com/19672699/129937772-8836fad2-8781-42cf-8e7a-0f0608c5730f.png)

What versions do you have?

**Comment by rchiodo** [comment]
Please reopen if you can provide the information. Thanks.
