### ISSUE TITLE
Sending Text to Jupyter Interactive Window

### ISSUE THREAD

**Issue by joetoth** [microsoft/vscode-jupyter#7429]
Issue Type: <b>Bug</b>

When "Send Selection To Interactive Window" is checked and the Jupyter window is not open, I shift+enter in a python file the Jupyter windows opens, the line is executed, but my current python file editor changes to 'interative.interative-1' and just says error. 
If I close this window and open the python file, everything works properly from then on.

If I start by using a cell #%% I don't have this issue of the editor changing.

Extension version: 2021.9.1001205359
VS Code version: Code - Insiders 1.61.0-insider (Universal) (a3fce6207d9364afcfccaa55efc82ff8a392fdd5, 2021-09-06T08:00:26.354Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.94GB free)|
|Process Argv|--crash-reporter-id 8302b51b-7f2b-4d74-9873-4b0d4892aed7|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by joyceerhl** [comment]
It sounds like your Python file editor is not pinned, i.e. its title is italicized in the editor tab, and that causes the opened interactive window to replace the open Python file. Is that accurate?

**Comment by joetoth** [comment]
Yes. With pinning it keeps the current file open and another tab is opened.
<img width="1007" alt="Screen Shot 2021-09-06 at 7 06 53 PM" src="https://user-images.githubusercontent.com/13778/132264892-7f1d91c0-5098-49b4-8eec-3ff55c6f4ee9.png">

Here is a screenshot of the new tab with the error. I'm guessing this is not the user experience we want, just the original editor open. 
<img width="806" alt="Screen Shot 2021-09-06 at 7 10 00 PM" src="https://user-images.githubusercontent.com/13778/132265003-0f92cf42-42bb-41c1-a71c-fbd4118a8461.png">
Let me know if you need anything else.

Thanks!!!

**Comment by joyceerhl** [comment]
@joetoth, when you see 'The editor could not be opened due to an unexpected error', can you run the 'Toggle Developer Tools' command and paste the output from that? This may be a bug in VS Code itself. /cc @rebornix

**Comment by joetoth** [comment]
notebookPerformance.ts:22 Skipping overwrite of notebook perf value: extensionActivated
console.ts:137 [Extension Host] Creating notebook concat (at console.log (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/microsoft-authentication/dist/extension.js:1:130079))
log.ts:301   ERR Error: Unable to resolve resource vscode-interactive:Interactive-1.interactive
    at a.doCreateReferencedObject (textModelResolverService.ts:80)
    at a.doCreateReferencedObject (textModelResolverService.ts:77)
    at async i.acquire (lifecycle.ts:380)
    at async createModelReference (textModelResolverService.ts:198)
    at async Yr.resolve (textResourceEditorInput.ts:190)
    at async Ya.setInput (textResourceEditor.ts:66)
    at async h.doSetInput (editorControl.ts:262)
    at async h.doOpenEditor (editorControl.ts:140)
    at async h.openEditor (editorControl.ts:108)
    at async editorGroupView.ts:1076
notificationsAlerts.ts:42 Unable to open 'Interactive-1.interactive': Unable to resolve resource vscode-interactive:Interactive-1.interactive.
notebookPerformance.ts:22 Skipping overwrite of notebook perf value: customMarkdownLoaded
VM11:14 Registering custom require.js for Jupyter Kernel
VM11:2151 Window.require = function
VM11:2152 Window.requirejs = function
console.ts:137 [Extension Host] Starting WebSocket: RAW/api/kernels/51fcf281-ca62-4a66-bf51-466d740b2242 (at console.e.<computed> [as log] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/microsoft-authentication/dist/extension.js:1:130079))
console.ts:137 [Extension Host] Kernel: connected (51fcf281-ca62-4a66-bf51-466d740b2242) (at console.e.<computed> [as log] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/microsoft-authentication/dist/extension.js:1:130079))
VM20:42 IPyWidget kernel initializing...
DevTools failed to load source map: Could not parse content for vscode-webview://18831b49-93ea-425f-b7b7-c9742dc66511/ipywidgets.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for vscode-webview://18831b49-93ea-425f-b7b7-c9742dc66511/ipywidgetsKernel.js.map: Unexpected end of JSON input
console.ts:137 [Extension Host] Kernel: starting (51fcf281-ca62-4a66-bf51-466d740b2242) (at console.e.<computed> [as log] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/microsoft-authentication/dist/extension.js:1:130079))
VM20:42 Received IPyWidgets_kernelOptions in ScriptManager
VM20:42 Received IPyWidgetMessages.IPyWidgets_kernelOptions
VM20:10 Starting WebSocket: BOGUS_PVSC/api/kernels/51fcf281-ca62-4a66-bf51-466d740b2242
VM20:10 Kernel: connected (51fcf281-ca62-4a66-bf51-466d740b2242)
log.ts:301   ERR Unable to resolve resource vscode-interactive:Interactive-1.interactive: Error: Unable to resolve resource vscode-interactive:Interactive-1.interactive
    at a.doCreateReferencedObject (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…tents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2420:113153)
    at a.doCreateReferencedObject (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…tents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2420:113116)
    at async i.acquire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:17:14802)
    at async createModelReference (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…tents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2420:114789)
    at async Yr.resolve (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ntents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1698:45866)
    at async Ya.setInput (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…tents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2385:107621)
    at async h.doSetInput (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ntents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2385:33596)
    at async h.doOpenEditor (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ntents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2385:31996)
    at async h.openEditor (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ntents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2385:31644)
    at async vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders…ntents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2587:16913
﻿
​

**Comment by greazer** [comment]
This has been fixed in tomorrow's insider's build.

**Comment by joetoth** [comment]
Confirmed. Thanks!!!
