### ISSUE TITLE
Kernel died with exit code 1

### ISSUE THREAD

**Issue by clayms** [microsoft/vscode-jupyter#7444]
Issue Type: <b>Bug</b>

When using <kbd>Shift</kbd>+<kbd>Enter</kbd> to run `import os` from a python file, I get the error in the Jupyter Output logs shown below.

The bug is that I am not trying to run  anything from `"o:\Notes\pythonEx\email.py"`, I don't even have that file open!  The file I am running single line `import os` is in a completely different directory!  

Are you telling me that the Jupyter extension scans the entire workspace and if a single line is incorrect or incomplete in ***any*** file, then the entire Jupyter extension will fail?!  This is insane!

Inconsistently, the second or third time I attempt to run the simple line `import os` it will work.

```
Kernel died with exit code 1. Traceback (most recent call last):
  File "D:\Users\user1\Miniconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Users\user1\Miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Users\user1\Miniconda3\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "D:\Users\user1\Miniconda3\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "D:\Users\user1\Miniconda3\lib\site-packages\ipykernel\connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "D:\Users\user1\Miniconda3\lib\site-packages\IPython\__init__.py", line 56, in <module>
    from .terminal.embed import embed
  File "D:\Users\user1\Miniconda3\lib\site-packages\IPython\terminal\embed.py", line 17, in <module>
    from IPython.terminal.ipapp import load_default_config
  File "D:\Users\user1\Miniconda3\lib\site-packages\IPython\terminal\ipapp.py", line 28, in <module>
    from IPython.core.magics import (
  File "D:\Users\user1\Miniconda3\lib\site-packages\IPython\core\magics\__init__.py", line 18, in <module>
    from .code import CodeMagics, MacroToEdit
  File "D:\Users\user1\Miniconda3\lib\site-packages\IPython\core\magics\code.py", line 23, in <module>
    from urllib.request import Request, urlopen
  File "D:\Users\user1\Miniconda3\lib\urllib\request.py", line 86, in <module>
    import email
  File "o:\Notes\pythonEx\email.py", line 10, in <module>
    from email.mime.multipart import MIMEMultipart
ModuleNotFoundError: No module named 'email.mime'; 'email' is not a package
```

Extension version: 2021.8.2031190714
VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.14393
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz (2 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|8.00GB (1.55GB free)|
|Process Argv|--crash-reporter-id 1e88d7ed-dfc2-42ed-b5d3-970568cb872e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes516:30244333
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonf5test824cf:30361778
vsdyn478:30356813
pythonvspyt187:30362782
pydsgst2:30361792
vscus224cf:30358040
vssid140:30362080

```

</details>

**Comment by IanMatthewHuff** [comment]
Hey @clayms sorry about the issue here, and some of the other issues that I've seen you file. We've just moved the Interactive Window over the new VS Code native notebook interface, and there are a few hitches we are still ironing out here.

What you are reproing here isn't something that I've seen reported before. Looking at that error chain what it looks like to me is that we are dealing with an issue here with module path resolution. In o:\Notes\pythonEx you have an email.py file, and when request.py looks to do 'import email' it's picking that up as opposed to the basic python e-mail package. Did you open up the interactive window via a file that was located in o:\Notes\pythonEx? What might be happening here is when the IW is launched from a file in that directory the current working directory is updated to that directory an that directory is added to sys.path. Does that sound like your scenario here?

**Comment by DonJayamanne** [comment]
Closing this issue as removing the `email.py` file should fix this
