### ISSUE TITLE
Failed to request creation of interactive window from VS Code.

### ISSUE THREAD

**Issue by clayms** [microsoft/vscode-jupyter#7446]
Issue Type: <b>Bug</b>

> Failed to request creation of interactive window from VS Code.

This is the message I get when using <kbd>Shift</kbd>+<kbd>Enter</kbd> from a python file to start the Interactive Window Pane and execute the Python code.  Strangely, the Interactive Window does ***occasionally*** start, but does not connect to the Python Kernel.  I have to run code directly in the Interactive Window to connect to the Python Kernel.  Trying to use <kbd>Shift</kbd>+<kbd>Enter</kbd> or any of the commands to either run `To`, `From`, or entire file in the Interactive Window fails with the same message. 

Another strange thing is on the same computer with the same VS Code installation, but a different workspace, everything works just fine.  

![image](https://user-images.githubusercontent.com/12793783/132403871-9f93f2c3-f1d6-4f57-b369-6c2679258454.png)

The Output tab `Jupyter` error log is below:

```
Error 2021-09-07 16:38:04: DataScience Error [Error: Failed to request creation of interactive window from VS Code.
	at t.NativeInteractiveWindow.createReadyPromise (d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\extension.js:24:100065)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async _.getOrCreate (d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\extension.js:90:274719)
	at async r.addCode (d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\extension.js:52:897110)
	at async runSelectionOrLine (d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\extension.js:52:886788)]
```

---------

Seems likely to be related to https://github.com/microsoft/vscode-jupyter/issues/7322 
also to https://github.com/microsoft/vscode-jupyter/issues/7445

-----------

In the same workspace that has the issue above, when <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> and selecting `Jupyter: Create Interactive Window`

![image](https://user-images.githubusercontent.com/12793783/132404952-b014c20f-52af-4609-b1ef-e0c77da2004c.png)

The Output tab `Jupyter` error log for this error is below:

```
Error 2021-09-07 17:36:59: Failed to change kernel, re-throwing [_ [Error]: 
	at new o (d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\extension.js:16:41638)
	at new _ (d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\extension.js:32:13834)
	at d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\extension.js:52:996319
	at processTicksAndRejections (internal/process/task_queues.js:93:5)

Error: Invalid response: 501 Not Implemented
	at d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\node_modules\@jupyterlab\services.js:3:585643
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async t.SessionManager.startNew (d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\node_modules\@jupyterlab\services.js:3:577167)] {
  category: 'unknown',
  originalException: [t [Error]: Invalid response: 501 Not Implemented
  	at d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\node_modules\@jupyterlab\services.js:3:585643
  	at processTicksAndRejections (internal/process/task_queues.js:93:5)
  	at async t.SessionManager.startNew (d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\node_modules\@jupyterlab\services.js:3:577167)] {
    response: R [Response] {
      size: 0,
      timeout: 0,
      [Symbol(Body internals)]: [Object],
      [Symbol(Response internals)]: [Object]
    }
  }
}
Info 2021-09-07 17:36:59: Shutdown session -- complete
Error 2021-09-07 17:36:59: failed to create INotebook in kernel, UI Disabled = false [_ [Error]: 
	at new o (d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\extension.js:16:41638)
	at new _ (d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\extension.js:32:13834)
	at d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\extension.js:52:996319
	at processTicksAndRejections (internal/process/task_queues.js:93:5)

Error: Invalid response: 501 Not Implemented
	at d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\node_modules\@jupyterlab\services.js:3:585643
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async t.SessionManager.startNew (d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\node_modules\@jupyterlab\services.js:3:577167)] {
  category: 'unknown',
  originalException: [t [Error]: Invalid response: 501 Not Implemented
  	at d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\node_modules\@jupyterlab\services.js:3:585643
  	at processTicksAndRejections (internal/process/task_queues.js:93:5)
  	at async t.SessionManager.startNew (d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\node_modules\@jupyterlab\services.js:3:577167)] {
    response: R [Response] {
      size: 0,
      timeout: 0,
      [Symbol(Body internals)]: [Object],
      [Symbol(Response internals)]: [Object]
    }
  }
}
Error 2021-09-07 17:36:59: DataScience Error [_ [Error]: 
	at new o (d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\extension.js:16:41638)
	at new _ (d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\extension.js:32:13834)
	at d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\extension.js:52:996319
	at processTicksAndRejections (internal/process/task_queues.js:93:5)

Error: Invalid response: 501 Not Implemented
	at d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\node_modules\@jupyterlab\services.js:3:585643
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async t.SessionManager.startNew (d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\node_modules\@jupyterlab\services.js:3:577167)] {
  category: 'unknown',
  originalException: [t [Error]: Invalid response: 501 Not Implemented
  	at d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\node_modules\@jupyterlab\services.js:3:585643
  	at processTicksAndRejections (internal/process/task_queues.js:93:5)
  	at async t.SessionManager.startNew (d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\node_modules\@jupyterlab\services.js:3:577167)] {
    response: R [Response] {
      size: 0,
      timeout: 0,
      [Symbol(Body internals)]: [Object],
      [Symbol(Response internals)]: [Object]
    }
  }
}
Error 2021-09-07 17:36:59: failed to start INotebook in kernel, UI Disabled = false [_ [Error]: 
	at new o (d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\extension.js:16:41638)
	at new _ (d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\extension.js:32:13834)
	at d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\extension.js:52:996319
	at processTicksAndRejections (internal/process/task_queues.js:93:5)

Error: Invalid response: 501 Not Implemented
	at d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\node_modules\@jupyterlab\services.js:3:585643
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async t.SessionManager.startNew (d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\node_modules\@jupyterlab\services.js:3:577167)] {
  category: 'unknown',
  originalException: [t [Error]: Invalid response: 501 Not Implemented
  	at d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\node_modules\@jupyterlab\services.js:3:585643
  	at processTicksAndRejections (internal/process/task_queues.js:93:5)
  	at async t.SessionManager.startNew (d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\node_modules\@jupyterlab\services.js:3:577167)] {
    response: R [Response] {
      size: 0,
      timeout: 0,
      [Symbol(Body internals)]: [Object],
      [Symbol(Response internals)]: [Object]
    }
  }
}
Error 2021-09-07 17:36:59: DataScience Error [_ [Error]: 
	at new o (d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\extension.js:16:41638)
	at new _ (d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\extension.js:32:13834)
	at d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\extension.js:52:996319
	at processTicksAndRejections (internal/process/task_queues.js:93:5)

Error: Invalid response: 501 Not Implemented
	at d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\node_modules\@jupyterlab\services.js:3:585643
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async t.SessionManager.startNew (d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\node_modules\@jupyterlab\services.js:3:577167)] {
  category: 'unknown',
  originalException: [t [Error]: Invalid response: 501 Not Implemented
  	at d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\node_modules\@jupyterlab\services.js:3:585643
  	at processTicksAndRejections (internal/process/task_queues.js:93:5)
  	at async t.SessionManager.startNew (d:\Users\user1\.vscode\extensions\ms-toolsai.jupyter-2021.8.2031190714\out\client\node_modules\@jupyterlab\services.js:3:577167)] {
    response: R [Response] {
      size: 0,
      timeout: 0,
      [Symbol(Body internals)]: [Object],
      [Symbol(Response internals)]: [Object]
    }
  }
}
```

Extension version: 2021.8.2031190714
VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.14393
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz (2 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|8.00GB (0.61GB free)|
|Process Argv|--crash-reporter-id 1e88d7ed-dfc2-42ed-b5d3-970568cb872e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes516:30244333
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonf5test824cf:30361778
vsdyn478:30356813
pythonvspyt187:30362782
pydsgst2:30361792
vscus224cf:30358040
vssid140:30362080

```

</details>

**Comment by IanMatthewHuff** [comment]
Tracking resolution in #7448
