### ISSUE TITLE
Missing newly created kernel in list of kernels

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode-jupyter#7712]
Version: 1.61.0-insider (Universal)
Commit: 214ac689ca9874a8a4be386f73d5cb60e15af25e
Date: 2021-09-28T05:14:06.244Z
Electron: 13.4.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

Jupyter: v2021.9.1001281857
Python: v2021.9.1246542782
Python: 3.9.1

After doing this: https://github.com/microsoft/vscode-jupyter/issues/7707#issuecomment-929476857

I still don't see my new env in the list of kernels but I do see it activated in terminal

**Comment by DonJayamanne** [comment]
@tanhakabir 
* Please could you enable debug logging in Python & jupyter extnesion as follows:
```json
"python.logging.level": "debug",
"jupyter.logging.level": "debug",
```
* Reload VSCode
* Confirm the new env appears in interpreter list & not in list of kernels (please wait for a minute or so, for python ext to activate & juypyter to search all kernels - we cache things, hence you'll see kernels immediately, but these are from the cache)
* Go into the `Python` & `Jupyter` output panels & past their content here

**Comment by tanhakabir** [comment]
I don't see the env in the interpreter list either.

**Comment by tanhakabir** [comment]
<details>
<summary>Jupyter</summary>
Info 2021-09-28 11:00:14: Experimentation service retrieved: [object Object]
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'jupyterEnhancedDataViewer'
Info 2021-09-28 11:00:14: ZMQ install verified.
Info 2021-09-28 11:00:15: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
Info 2021-09-28 11:00:17: Process Execution: > /usr/local/bin/python3 -c "import ipykernel"
> /usr/local/bin/python3 -c "import ipykernel"
Info 2021-09-28 11:00:17: Process Execution: > /usr/local/bin/python3 -c "import ipykernel"
> /usr/local/bin/python3 -c "import ipykernel"
Info 2021-09-28 11:00:17: Process Execution: > /usr/local/bin/python3 -m pip list
> /usr/local/bin/python3 -m pip list
Info 2021-09-28 11:00:17: Process Execution: > /usr/local/bin/python3 -m pip list
> /usr/local/bin/python3 -m pip list
Info 2021-09-28 11:00:19: Creating daemon process for /usr/local/bin/python3 with env variables count 0
Info 2021-09-28 11:00:19: Process Execution: > /usr/local/bin/python3 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /usr/local/bin/python3 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Info 2021-09-28 11:00:19: Process Execution: > /usr/local/bin/python3 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /usr/local/bin/python3 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Info 2021-09-28 11:00:19: Python Daemon (pid: 61384): Execute rpc method prewarm_kernel in DS Daemon
Info 2021-09-28 11:00:19: Python Daemon (pid: 61384): Execute rpc method prewarm_kernel from /usr/local/bin/python3
Info 2021-09-28 11:00:19: Python Daemon (pid: 61384): Pre-Warm DS Kernel in DS Kernel Launcher Daemon
Info 2021-09-28 11:00:19: Python Daemon (pid: 61384): Exec in DS Kernel Launcher Daemon (observable) ['/usr/local/bin/python3', '/Users/tanha/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001281857/pythonFiles/vscode_datascience_helpers/kernel_prewarm_starter.py']
Info 2021-09-28 11:00:19: Python Daemon (pid: 61384): Exec in DS Kernel Launcher Daemon (observable)
Info 2021-09-28 11:00:19: Python Daemon (pid: 61384): Kernel launched, with PID 61385
Warn 2021-09-28 11:00:19: Python Daemon (pid: 61384): Waiting for Kernel to die 61385
Info 2021-09-28 11:00:19: Python Daemon (pid: 61384): Kernel launched, with PID as a daemon 61385
</details>

<details>
<summary>Python</summary>
User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'pythonDeprecatePythonPath'
User belongs to experiment group 'pythonSortEnvs'
User belongs to experiment group 'pythonRunFailedTestsButtonDisplayed'
User belongs to experiment group 'pythonRefreshTestsButtonDisplayed'
User belongs to experiment group 'pythonRememberDebugConfig'
Info 2021-09-28 11:00:14: Testing: Setting up watcher for /Users/tanha/Documents/GitHub/data-science
Info 2021-09-28 11:00:14: Searching for conda.
Info 2021-09-28 11:00:14: Probing conda binary: conda
Info 2021-09-28 11:00:14: Watcher disabled
Info 2021-09-28 11:00:14: Searching for workspace virtual envs in: /Users/tanha/Documents/GitHub/data-science
Info 2021-09-28 11:00:14: Getting roots
Info 2021-09-28 11:00:14: Found roots
Info 2021-09-28 11:00:14: Watcher disabled
Info 2021-09-28 11:00:14: Found: /usr/bin/python --> /System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Info 2021-09-28 11:00:14: Found: /usr/bin/python2 --> /System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Info 2021-09-28 11:00:14: Found: /usr/bin/python2.7 --> /System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Info 2021-09-28 11:00:14: Found: /usr/bin/python3 --> /usr/bin/python3
Info 2021-09-28 11:00:14: Found: /usr/lib/python2.7 --> /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
Info 2021-09-28 11:00:14: Getting roots
Info 2021-09-28 11:00:14: Found roots
Info 2021-09-28 11:00:14: Start watching root /Users/tanha/Documents/GitHub/data-science for globs ["python","*/python","*/bin/python"]
Info 2021-09-28 11:00:14: Start watching: /Users/tanha/Documents/GitHub/data-science with pattern python using VSCode API
Info 2021-09-28 11:00:14: Start watching: /Users/tanha/Documents/GitHub/data-science with pattern */python using VSCode API
Info 2021-09-28 11:00:14: Start watching: /Users/tanha/Documents/GitHub/data-science with pattern */bin/python using VSCode API
Info 2021-09-28 11:00:14: Found: /usr/local/bin/python3 --> /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9
Info 2021-09-28 11:00:14: Found: /usr/local/bin/python3.9 --> /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9
Info 2021-09-28 11:00:14: Found: /Users/tanha/opt/anaconda3/bin/python --> /Users/tanha/opt/anaconda3/bin/python3.8
Info 2021-09-28 11:00:14: Found: /Users/tanha/opt/anaconda3/bin/python3 --> /Users/tanha/opt/anaconda3/bin/python3.8
Info 2021-09-28 11:00:14: Found: /Users/tanha/opt/anaconda3/bin/python3.8 --> /Users/tanha/opt/anaconda3/bin/python3.8
Info 2021-09-28 11:00:14: Found: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3 --> /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9
Info 2021-09-28 11:00:14: Found: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 --> /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9
Info 2021-09-28 11:00:14: Found interpreter for /usr/bin/python,/Users/tanha/.vscode-insiders/extensions/ms-python.python-2021.9.1246542782/pythonFiles/interpreterInfo.py
Info 2021-09-28 11:00:14: Found interpreter for /usr/bin/python3,/Users/tanha/.vscode-insiders/extensions/ms-python.python-2021.9.1246542782/pythonFiles/interpreterInfo.py
Info 2021-09-28 11:00:14: [Error: Command failed: "/usr/lib/python2.7" "/Users/tanha/.vscode-insiders/extensions/ms-python.python-2021.9.1246542782/pythonFiles/interpreterInfo.py"
/bin/sh: /usr/lib/python2.7: is a directory

	at ChildProcess.exithandler (child_process.js:317:12)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1048:16)
	at Socket.<anonymous> (internal/child_process.js:439:11)
	at Socket.emit (events.js:315:20)
	at Pipe.<anonymous> (net.js:673:12)] {
  killed: false,
  code: 126,
  signal: null,
  cmd: '"/usr/lib/python2.7" "/Users/tanha/.vscode-insiders/extensions/ms-python.python-2021.9.1246542782/pythonFiles/interpreterInfo.py"'
}
Info 2021-09-28 11:00:14: Found interpreter for /usr/local/bin/python3,/Users/tanha/.vscode-insiders/extensions/ms-python.python-2021.9.1246542782/pythonFiles/interpreterInfo.py
Info 2021-09-28 11:00:14: Found interpreter for /Users/tanha/opt/anaconda3/bin/python,/Users/tanha/.vscode-insiders/extensions/ms-python.python-2021.9.1246542782/pythonFiles/interpreterInfo.py
Info 2021-09-28 11:00:15: conda info --json: {
  "GID": 20,
  "UID": 501,
  "active_prefix": "/Users/tanha/opt/anaconda3",
  "active_prefix_name": "base",
  "av_data_dir": "/Users/tanha/opt/anaconda3/etc/conda",
  "av_metadata_url_base": "https://repo.anaconda.com/pkgs/main",
  "channels": [
    "https://repo.anaconda.com/pkgs/main/osx-64",
    "https://repo.anaconda.com/pkgs/main/noarch",
    "https://repo.anaconda.com/pkgs/r/osx-64",
    "https://repo.anaconda.com/pkgs/r/noarch"
  ],
  "conda_build_version": "3.20.5",
  "conda_env_version": "4.10.1",
  "conda_location": "/Users/tanha/opt/anaconda3/lib/python3.8/site-packages/conda",
  "conda_prefix": "/Users/tanha/opt/anaconda3",
  "conda_private": false,
  "conda_shlvl": 1,
  "conda_version": "4.10.1",
  "config_files": [
    "/Users/tanha/.condarc"
  ],
  "default_prefix": "/Users/tanha/opt/anaconda3",
  "env_vars": {
    "CIO_TEST": "<not set>",
    "CONDA_DEFAULT_ENV": "base",
    "CONDA_EXE": "/Users/tanha/opt/anaconda3/bin/conda",
    "CONDA_PREFIX": "/Users/tanha/opt/anaconda3",
    "CONDA_PROMPT_MODIFIER": "(base) ",
    "CONDA_PYTHON_EXE": "/Users/tanha/opt/anaconda3/bin/python",
    "CONDA_ROOT": "/Users/tanha/opt/anaconda3",
    "CONDA_SHLVL": "1",
    "CURL_CA_BUNDLE": "<not set>",
    "PATH": "/Users/tanha/opt/anaconda3/bin:/Users/tanha/opt/anaconda3/condabin:/Users/tanha/.nvm/versions/node/v15.7.0/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Library/Apple/usr/bin",
    "PYTHONIOENCODING": "utf-8",
    "PYTHONUNBUFFERED": "1",
    "REQUESTS_CA_BUNDLE": "<not set>",
    "SSL_CERT_FILE": "<not set>",
    "VSCODE_CODE_CACHE_PATH": "/Users/tanha/Library/Application Support/Code - Insiders/CachedData/214ac689ca9874a8a4be386f73d5cb60e15af25e"
  },
  "envs": [
    "/Users/tanha/opt/anaconda3",
    "/Users/tanha/opt/anaconda3/envs/golden_scenario_env"
  ],
  "envs_dirs": [
    "/Users/tanha/opt/anaconda3/envs",
    "/Users/tanha/.conda/envs"
  ],
  "netrc_file": "/Users/tanha/.netrc",
  "offline": false,
  "pkgs_dirs": [
    "/Users/tanha/opt/anaconda3/pkgs",
    "/Users/tanha/.conda/pkgs"
  ],
  "platform": "osx-64",
  "python_version": "3.8.5.final.0",
  "rc_path": "/Users/tanha/.condarc",
  "requests_version": "2.24.0",
  "root_prefix": "/Users/tanha/opt/anaconda3",
  "root_writable": true,
  "site_dirs": [],
  "sys.executable": "/Users/tanha/opt/anaconda3/bin/python",
  "sys.prefix": "/Users/tanha/opt/anaconda3",
  "sys.version": "3.8.5 (default, Sep  4 2020, 02:22:02) \n[Clang 10.0.0 ]",
  "sys_rc_path": "/Users/tanha/opt/anaconda3/.condarc",
  "user_agent": "conda/4.10.1 requests/2.24.0 CPython/3.8.5 Darwin/20.6.0 OSX/10.16",
  "user_rc_path": "/Users/tanha/.condarc",
  "virtual_pkgs": [
    [
      "__osx",
      "10.16",
      "0"
    ],
    [
      "__unix",
      "0",
      "0"
    ],
    [
      "__archspec",
      "1",
      "x86_64"
    ]
  ]
}

Info 2021-09-28 11:00:15: Found conda via filesystem probing: conda
Info 2021-09-28 11:00:15: Searching for conda environments using conda
Info 2021-09-28 11:00:15: conda info --json: {
  "GID": 20,
  "UID": 501,
  "active_prefix": "/Users/tanha/opt/anaconda3",
  "active_prefix_name": "base",
  "av_data_dir": "/Users/tanha/opt/anaconda3/etc/conda",
  "av_metadata_url_base": "https://repo.anaconda.com/pkgs/main",
  "channels": [
    "https://repo.anaconda.com/pkgs/main/osx-64",
    "https://repo.anaconda.com/pkgs/main/noarch",
    "https://repo.anaconda.com/pkgs/r/osx-64",
    "https://repo.anaconda.com/pkgs/r/noarch"
  ],
  "conda_build_version": "3.20.5",
  "conda_env_version": "4.10.1",
  "conda_location": "/Users/tanha/opt/anaconda3/lib/python3.8/site-packages/conda",
  "conda_prefix": "/Users/tanha/opt/anaconda3",
  "conda_private": false,
  "conda_shlvl": 1,
  "conda_version": "4.10.1",
  "config_files": [
    "/Users/tanha/.condarc"
  ],
  "default_prefix": "/Users/tanha/opt/anaconda3",
  "env_vars": {
    "CIO_TEST": "<not set>",
    "CONDA_DEFAULT_ENV": "base",
    "CONDA_EXE": "/Users/tanha/opt/anaconda3/bin/conda",
    "CONDA_PREFIX": "/Users/tanha/opt/anaconda3",
    "CONDA_PROMPT_MODIFIER": "(base) ",
    "CONDA_PYTHON_EXE": "/Users/tanha/opt/anaconda3/bin/python",
    "CONDA_ROOT": "/Users/tanha/opt/anaconda3",
    "CONDA_SHLVL": "1",
    "CURL_CA_BUNDLE": "<not set>",
    "PATH": "/Users/tanha/opt/anaconda3/bin:/Users/tanha/opt/anaconda3/condabin:/Users/tanha/.nvm/versions/node/v15.7.0/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Library/Apple/usr/bin",
    "PYTHONIOENCODING": "utf-8",
    "PYTHONUNBUFFERED": "1",
    "REQUESTS_CA_BUNDLE": "<not set>",
    "SSL_CERT_FILE": "<not set>",
    "VSCODE_CODE_CACHE_PATH": "/Users/tanha/Library/Application Support/Code - Insiders/CachedData/214ac689ca9874a8a4be386f73d5cb60e15af25e"
  },
  "envs": [
    "/Users/tanha/opt/anaconda3",
    "/Users/tanha/opt/anaconda3/envs/golden_scenario_env"
  ],
  "envs_dirs": [
    "/Users/tanha/opt/anaconda3/envs",
    "/Users/tanha/.conda/envs"
  ],
  "netrc_file": "/Users/tanha/.netrc",
  "offline": false,
  "pkgs_dirs": [
    "/Users/tanha/opt/anaconda3/pkgs",
    "/Users/tanha/.conda/pkgs"
  ],
  "platform": "osx-64",
  "python_version": "3.8.5.final.0",
  "rc_path": "/Users/tanha/.condarc",
  "requests_version": "2.24.0",
  "root_prefix": "/Users/tanha/opt/anaconda3",
  "root_writable": true,
  "site_dirs": [],
  "sys.executable": "/Users/tanha/opt/anaconda3/bin/python",
  "sys.prefix": "/Users/tanha/opt/anaconda3",
  "sys.version": "3.8.5 (default, Sep  4 2020, 02:22:02) \n[Clang 10.0.0 ]",
  "sys_rc_path": "/Users/tanha/opt/anaconda3/.condarc",
  "user_agent": "conda/4.10.1 requests/2.24.0 CPython/3.8.5 Darwin/20.6.0 OSX/10.16",
  "user_rc_path": "/Users/tanha/.condarc",
  "virtual_pkgs": [
    [
      "__osx",
      "10.16",
      "0"
    ],
    [
      "__unix",
      "0",
      "0"
    ],
    [
      "__archspec",
      "1",
      "x86_64"
    ]
  ]
}

Info 2021-09-28 11:00:15: Found conda environment: /Users/tanha/opt/anaconda3/bin/python
Info 2021-09-28 11:00:15: Searching for conda.
Info 2021-09-28 11:00:15: Cached data exists KeyPrefix=Cache_Method_Output_m.getEnvList-Args=
Info 2021-09-28 11:00:15: Found conda environment: /Users/tanha/opt/anaconda3/envs/golden_scenario_env/bin/python
Info 2021-09-28 11:00:15: Searching for conda.
Info 2021-09-28 11:00:15: Cached data exists KeyPrefix=Cache_Method_Output_m.getEnvList-Args=
Info 2021-09-28 11:00:15: Found interpreter for /Users/tanha/opt/anaconda3/envs/golden_scenario_env/bin/python,/Users/tanha/.vscode-insiders/extensions/ms-python.python-2021.9.1246542782/pythonFiles/interpreterInfo.py
Info 2021-09-28 11:00:15: Environments added to cache [{"name":"","location":"","kind":"global-other","executable":{"filename":"/usr/bin/python","sysPrefix":"/System/Library/Frameworks/Python.framework/Versions/2.7","ctime":-1,"mtime":-1},"display":"Python 2.7.16 64-bit","version":{"major":2,"minor":7,"micro":16,"release":{"level":"final","serial":0},"sysVersion":"2.7.16 (default, Aug 30 2021, 14:43:11) \n[GCC Apple LLVM 12.0.5 (clang-1205.0.19.59.6) [+internal-os, ptrauth-isa=deploy"},"arch":3,"distro":{"org":""},"source":["path env var"]},{"name":"","location":"","kind":"global-other","executable":{"filename":"/usr/local/bin/python3","sysPrefix":"/Library/Frameworks/Python.framework/Versions/3.9","ctime":-1,"mtime":-1},"display":"Python 3.9.1 64-bit","version":{"major":3,"minor":9,"micro":1,"release":{"level":"final","serial":0},"sysVersion":"3.9.1 (v3.9.1:1e5d33e9b9, Dec  7 2020, 12:10:52) \n[Clang 6.0 (clang-600.0.57)]"},"arch":3,"distro":{"org":""},"source":["path env var"]},{"name":"base","location":"/Users/tanha/opt/anaconda3","kind":"virt-conda","executable":{"filename":"/Users/tanha/opt/anaconda3/bin/python","sysPrefix":"/Users/tanha/opt/anaconda3","ctime":-1,"mtime":-1},"display":"Python 3.8.5 64-bit ('base': conda)","version":{"major":3,"minor":8,"micro":5,"release":{"level":"final","serial":0},"sysVersion":"3.8.5 (default, Sep  4 2020, 02:22:02) \n[Clang 10.0.0 ]"},"arch":3,"distro":{"org":"Anaconda, Inc."},"source":["path env var"]},{"name":"golden_scenario_env","location":"/Users/tanha/opt/anaconda3/envs/golden_scenario_env","kind":"virt-conda","executable":{"filename":"/Users/tanha/opt/anaconda3/envs/golden_scenario_env/bin/python","sysPrefix":"/Users/tanha/opt/anaconda3/envs/golden_scenario_env","ctime":-1,"mtime":-1},"display":"Python 3.7.11 64-bit ('golden_scenario_env': conda)","version":{"major":3,"minor":7,"micro":11,"release":{"level":"final","serial":0},"sysVersion":"3.7.11 (default, Jul 27 2021, 07:03:16) \n[Clang 10.0.0 ]"},"arch":3,"distro":{"org":"Anaconda, Inc."},"source":[]},{"name":"","location":"","kind":"global-other","executable":{"filename":"/usr/bin/python3","sysPrefix":"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8","ctime":-1,"mtime":-1},"display":"Python 3.8.2 64-bit","version":{"major":3,"minor":8,"micro":2,"release":{"level":"final","serial":0},"sysVersion":"3.8.2 (default, Jun  8 2021, 11:59:35) \n[Clang 12.0.5 (clang-1205.0.22.11)]"},"arch":3,"distro":{"org":""},"source":["path env var"]}]
Info 2021-09-28 11:00:15: Display locator refreshing progress, Class name = g, completed in 1ms, has a falsy return value, , Return Value: undefined
Info 2021-09-28 11:00:15: Hide locator refreshing progress, Class name = g, completed in 0ms, has a falsy return value, , Return Value: undefined
Info 2021-09-28 11:00:15: Display locator refreshing progress, Class name = g, completed in 0ms, has a falsy return value, , Return Value: undefined
Info 2021-09-28 11:00:15: Hide locator refreshing progress, Class name = g, completed in 0ms, has a falsy return value, , Return Value: undefined
Info 2021-09-28 11:00:15: Display locator refreshing progress, Class name = g, completed in 0ms, has a falsy return value, , Return Value: undefined
Info 2021-09-28 11:00:15: Hide locator refreshing progress, Class name = g, completed in 0ms, has a falsy return value, , Return Value: undefined
Python interpreter path: /usr/local/bin/python3
Info 2021-09-28 11:00:15: Display locator refreshing progress, Class name = g, completed in 0ms, has a falsy return value, , Return Value: undefined
Info 2021-09-28 11:00:15: Hide locator refreshing progress, Class name = g, completed in 0ms, has a falsy return value, , Return Value: undefined
Starting Pylance language server.
Info 2021-09-28 11:00:17: Activation Commands received undefined for shell bash
Info 2021-09-28 11:00:17: getActivatedEnvironmentVariables, Class name = C, completed in 1442ms, has a falsy return value, Arg 1: undefined, Arg 2: {"sysPrefix":"/Library/Frameworks/Python.framework/Versions/3.9","envType":"Global","envName":"","envPath":"","path":"/usr/local/bin/python3","architecture":3,"sysVersion":"3.9.1 (v3.9.1:1e5d33e9b9, Dec  7 2020, 12:10:52) \n[Clang 6.0 (clang-600.0.57)]","version":{"raw":"3.9.1","major":3,"minor":9,"patch":1,"build":[],"prerelease":["final","0"]},"displayName":"Python 3.9.1 64-bit"}, Arg 3: false
Info 2021-09-28 11:00:17: Activation Commands received undefined for shell bash
Info 2021-09-28 11:00:17: getActivatedEnvironmentVariables, Class name = C, completed in 1485ms, has a falsy return value, Arg 1: undefined, Arg 2: {"sysPrefix":"/Library/Frameworks/Python.framework/Versions/3.9","envType":"Global","envName":"","envPath":"","path":"/usr/local/bin/python3","architecture":3,"sysVersion":"3.9.1 (v3.9.1:1e5d33e9b9, Dec  7 2020, 12:10:52) \n[Clang 6.0 (clang-600.0.57)]","version":{"raw":"3.9.1","major":3,"minor":9,"patch":1,"build":[],"prerelease":["final","0"]},"displayName":"Python 3.9.1 64-bit"}, Arg 3: false
Info 2021-09-28 11:00:17: Cached data exists getEnvironmentVariables, /Users/tanha/Documents/GitHub/data-science
Info 2021-09-28 11:00:17: Starting language server, Class name = r, completed in 465ms, has a falsy return value, , Return Value: undefined
Info 2021-09-28 11:00:17: Cached data exists getEnvironmentVariables, /Users/tanha/Library/Application Support/Code - Insiders/User/settings.json
Info 2021-09-28 11:00:17: [object Object]. Shell identified as undefined 
Info 2021-09-28 11:00:17: Shell path 'zsh'
Info 2021-09-28 11:00:17: Shell path identified as shell 'zsh'
Info 2021-09-28 11:00:17: Terminal shell path 'zsh' identified as shell 'zsh'
Info 2021-09-28 11:00:17: [object Object]. Shell identified as zsh 
Info 2021-09-28 11:00:17: Shell identified as 'zsh'
Info 2021-09-28 11:00:17: Cached data exists getEnvironmentVariables, <No Resource>
Info 2021-09-28 11:00:17: Cached data exists getEnvironmentVariables, <No Resource>
Info 2021-09-28 11:00:17: Cached data exists getEnvironmentVariables, /Users/tanha/Library/Application Support/Code - Insiders/User/settings.json
Info 2021-09-28 11:00:17: Searching for conda.
Info 2021-09-28 11:00:18: conda info --json: {
  "GID": 20,
  "UID": 501,
  "active_prefix": "/Users/tanha/opt/anaconda3",
  "active_prefix_name": "base",
  "av_data_dir": "/Users/tanha/opt/anaconda3/etc/conda",
  "av_metadata_url_base": "https://repo.anaconda.com/pkgs/main",
  "channels": [
    "https://repo.anaconda.com/pkgs/main/osx-64",
    "https://repo.anaconda.com/pkgs/main/noarch",
    "https://repo.anaconda.com/pkgs/r/osx-64",
    "https://repo.anaconda.com/pkgs/r/noarch"
  ],
  "conda_build_version": "3.20.5",
  "conda_env_version": "4.10.1",
  "conda_location": "/Users/tanha/opt/anaconda3/lib/python3.8/site-packages/conda",
  "conda_prefix": "/Users/tanha/opt/anaconda3",
  "conda_private": false,
  "conda_shlvl": 1,
  "conda_version": "4.10.1",
  "config_files": [
    "/Users/tanha/.condarc"
  ],
  "default_prefix": "/Users/tanha/opt/anaconda3",
  "env_vars": {
    "CIO_TEST": "<not set>",
    "CONDA_DEFAULT_ENV": "base",
    "CONDA_EXE": "/Users/tanha/opt/anaconda3/bin/conda",
    "CONDA_PREFIX": "/Users/tanha/opt/anaconda3",
    "CONDA_PROMPT_MODIFIER": "(base) ",
    "CONDA_PYTHON_EXE": "/Users/tanha/opt/anaconda3/bin/python",
    "CONDA_ROOT": "/Users/tanha/opt/anaconda3",
    "CONDA_SHLVL": "1",
    "CURL_CA_BUNDLE": "<not set>",
    "PATH": "/Users/tanha/opt/anaconda3/bin:/Users/tanha/opt/anaconda3/condabin:/Users/tanha/.nvm/versions/node/v15.7.0/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Library/Apple/usr/bin",
    "PYTHONIOENCODING": "utf-8",
    "PYTHONUNBUFFERED": "1",
    "REQUESTS_CA_BUNDLE": "<not set>",
    "SSL_CERT_FILE": "<not set>",
    "VSCODE_CODE_CACHE_PATH": "/Users/tanha/Library/Application Support/Code - Insiders/CachedData/214ac689ca9874a8a4be386f73d5cb60e15af25e"
  },
  "envs": [
    "/Users/tanha/opt/anaconda3",
    "/Users/tanha/opt/anaconda3/envs/golden_scenario_env"
  ],
  "envs_dirs": [
    "/Users/tanha/opt/anaconda3/envs",
    "/Users/tanha/.conda/envs"
  ],
  "netrc_file": "/Users/tanha/.netrc",
  "offline": false,
  "pkgs_dirs": [
    "/Users/tanha/opt/anaconda3/pkgs",
    "/Users/tanha/.conda/pkgs"
  ],
  "platform": "osx-64",
  "python_version": "3.8.5.final.0",
  "rc_path": "/Users/tanha/.condarc",
  "requests_version": "2.24.0",
  "root_prefix": "/Users/tanha/opt/anaconda3",
  "root_writable": true,
  "site_dirs": [],
  "sys.executable": "/Users/tanha/opt/anaconda3/bin/python",
  "sys.prefix": "/Users/tanha/opt/anaconda3",
  "sys.version": "3.8.5 (default, Sep  4 2020, 02:22:02) \n[Clang 10.0.0 ]",
  "sys_rc_path": "/Users/tanha/opt/anaconda3/.condarc",
  "user_agent": "conda/4.10.1 requests/2.24.0 CPython/3.8.5 Darwin/20.6.0 OSX/10.16",
  "user_rc_path": "/Users/tanha/.condarc",
  "virtual_pkgs": [
    [
      "__osx",
      "10.16",
      "0"
    ],
    [
      "__unix",
      "0",
      "0"
    ],
    [
      "__archspec",
      "1",
      "x86_64"
    ]
  ]
}

Info 2021-09-28 11:00:18: Display locator refreshing progress, Class name = g, completed in 0ms, has a falsy return value, , Return Value: undefined
Info 2021-09-28 11:00:18: Hide locator refreshing progress, Class name = g, completed in 0ms, has a falsy return value, , Return Value: undefined
Info 2021-09-28 11:00:19: Activation Commands received undefined for shell bash
Info 2021-09-28 11:00:19: Activation Commands received undefined for shell bash
Info 2021-09-28 11:00:19: getActivatedEnvironmentVariables, Class name = C, completed in 8ms, has a falsy return value, Arg 1: <Uri:/Users/tanha/Documents/GitHub/data-science>, Arg 2: {"sysPrefix":"/Library/Frameworks/Python.framework/Versions/3.9","envType":"Global","envName":"","envPath":"","path":"/usr/local/bin/python3","architecture":3,"sysVersion":"3.9.1 (v3.9.1:1e5d33e9b9, Dec  7 2020, 12:10:52) \n[Clang 6.0 (clang-600.0.57)]","version":{"raw":"3.9.1","major":3,"minor":9,"patch":1,"build":[],"prerelease":["final","0"]},"displayName":"Python 3.9.1 64-bit"}, Arg 3: false
Info 2021-09-28 11:00:19: getActivatedEnvironmentVariables, Class name = C, completed in 9ms, has a falsy return value, Arg 1: <Uri:/Users/tanha/Documents/GitHub/data-science>, Arg 2: {"sysPrefix":"/Library/Frameworks/Python.framework/Versions/3.9","envType":"Global","envName":"","envPath":"","path":"/usr/local/bin/python3","architecture":3,"sysVersion":"3.9.1 (v3.9.1:1e5d33e9b9, Dec  7 2020, 12:10:52) \n[Clang 6.0 (clang-600.0.57)]","version":{"raw":"3.9.1","major":3,"minor":9,"patch":1,"build":[],"prerelease":["final","0"]},"displayName":"Python 3.9.1 64-bit"}, Arg 3: false
Info 2021-09-28 11:01:14: Cached data exists getEnvironmentVariables, extension-output-ms-toolsai.jupyter-#1
Info 2021-09-28 11:03:15: Cached data exists getEnvironmentVariables, /Users/tanha/Library/Application Support/Code - Insiders/User/settings.json
Info 2021-09-28 11:03:32: Cached data exists getEnvironmentVariables, extension-output-ms-toolsai.jupyter-#1
Info 2021-09-28 11:03:59: Cached data exists getEnvironmentVariables, /Users/tanha/Library/Application Support/Code - Insiders/User/settings.json
Info 2021-09-28 11:03:59: Cached data exists getEnvironmentVariables, extension-output-ms-python.python-#1
</details>

**Comment by DonJayamanne** [comment]
> I don't see the env in the interpreter list either.

Moving this issue to Python repo.
