### ISSUE TITLE
Ipykernel not detected in poetry environment

### ISSUE THREAD

**Issue by NomeChomsky** [microsoft/vscode-jupyter#7743]
## Environment data

-   Version: 1.60.2 (user setup)
Commit: 7f6ab5485bbc008386c4386d08766667e155244e
Date: 2021-09-22T12:00:31.514Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000
-   Jupyter Extension version v2021.8.2041215044
-   Python Extension version v2021.9.1246542782
-   OS (Windows | Mac | Linux distro) and version: WSL2
-   Python and/or Anaconda version: 3.8
-   Type of virtual environment used Poetry
-   Jupyter server running: Local

## Expected behaviour
When I try to run code inside a jupyter notebook, or an interactive window, I expect vscode to find ipykernel inside the  interpreter I've selected (a poetry environment) to run the interactive window. I'm then expecting to be able to run code from the jupyter window inside the poetry virtual environment

## Actual behaviour

After selecting the correct poetry environment in the dropdown, and then pressing play on the code, I get an error notification saying 'Running cells with 'Python 3.8.5 64-bit ('django-signally-py3.8': poetry)' requires ipykernel installed or requires an update'

I can either select re-install, change kernel or cancel. If I select re-install, it says 'Could not install ipykernel. If pip is not available, please use the package manager of your choice to manually install this library into your Python environment.' When I do that, with `poetry add ipykernel`, poetry tells me ipykernel is already installed.  It seems vscode can't see that ipykernel is already inside that particular virtual environment, and therefore it cannot run.

## Steps to reproduce:

1. Create a  poetry env in WSL2 vscode
2. Select that env as the interpreter for the project
3. Open an .ipynb file with code inside
4. Try to run it

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Info 2021-09-29 16:50:52: Cancel pending cells
Info 2021-09-29 16:54:26: Execute Cells request 1 0
Info 2021-09-29 16:54:26: Execute Cell 0 file:///home/phillyharper/dask/dask/MyNotebook.ipynb
Info 2021-09-29 16:54:26: Starting Notebook in kernel.ts id = .jvsc74a57bd055debaa9f2ed4c69b21cbf018c935240c3bc1c8453ea540bbb73b1c2bcdc6886./home/phillyharper/.cache/pypoetry/virtualenvs/django_signally-JCl81_Vu-py3.8/bin/python./home/phillyharper/.cache/pypoetry/virtualenvs/django_signally-JCl81_Vu-py3.8/bin/python.-m#ipykernel_launcher
Info 2021-09-29 16:54:26: Creating raw notebook for file:///home/phillyharper/dask/dask/MyNotebook.ipynb
Info 2021-09-29 16:54:26: Getting preferred kernel for file:///home/phillyharper/dask/dask/MyNotebook.ipynb
Info 2021-09-29 16:54:26: Computing working directory file:///home/phillyharper/dask/dask/MyNotebook.ipynb
Info 2021-09-29 16:54:26: Connecting to raw session for file:///home/phillyharper/dask/dask/MyNotebook.ipynb with connection {"kind":"startUsingPythonInterpreter","kernelSpec":{"specFile":"/home/phillyharper/.cache/pypoetry/virtualenvs/django_signally-JCl81_Vu-py3.8/share/jupyter/kernels/python3/kernel.json","interpreterPath":"/home/phillyharper/.cache/pypoetry/virtualenvs/django_signally-JCl81_Vu-py3.8/bin/python","name":"python385jvsc74a57bd055debaa9f2ed4c69b21cbf018c935240c3bc1c8453ea540bbb73b1c2bcdc6886","argv":["python","-m","ipykernel_launcher","-f","{connection_file}"],"language":"python","path":"python","display_name":"Python 3.8.5 64-bit ('django_signally-JCl81_Vu-py3.8': poetry)"},"interpreter":{"sysPrefix":"/home/phillyharper/.cache/pypoetry/virtualenvs/django_signally-JCl81_Vu-py3.8","envType":"Poetry","envName":"django_signally-JCl81_Vu-py3.8","envPath":"/home/phillyharper/.cache/pypoetry/virtualenvs/django_signally-JCl81_Vu-py3.8","path":"/home/phillyharper/.cache/pypoetry/virtualenvs/django_signally-JCl81_Vu-py3.8/bin/python","architecture":3,"sysVersion":"3.8.5 (default, Jan 27 2021, 15:41:15) \n[GCC 9.3.0]","version":{"raw":"3.8.5","major":3,"minor":8,"patch":5,"build":[],"prerelease":["final","0"]},"displayName":"Python 3.8.5 64-bit ('django_signally-JCl81_Vu-py3.8': poetry)"},"id":".jvsc74a57bd055debaa9f2ed4c69b21cbf018c935240c3bc1c8453ea540bbb73b1c2bcdc6886./home/phillyharper/.cache/pypoetry/virtualenvs/django_signally-JCl81_Vu-py3.8/bin/python./home/phillyharper/.cache/pypoetry/virtualenvs/django_signally-JCl81_Vu-py3.8/bin/python.-m#ipykernel_launcher"}
Info 2021-09-29 16:54:26: Starting raw kernel Python 3.8.5 64-bit ('django_signally-JCl81_Vu-py3.8': poetry)
Info 2021-09-29 16:54:26: installMissingDependencies /home/phillyharper/.cache/pypoetry/virtualenvs/django_signally-JCl81_Vu-py3.8/bin/python
Info 2021-09-29 16:54:26: Process Execution: > ~/.cache/pypoetry/virtualenvs/django_signally-JCl81_Vu-py3.8/bin/python -c "import ipykernel"
> ~/.cache/pypoetry/virtualenvs/django_signally-JCl81_Vu-py3.8/bin/python -c "import ipykernel"
Error 2021-09-29 16:54:28: Install Missing Dependencies, Class name = _, completed in 2493ms, has a falsy return value, Return Value: undefined [a [Error]: IPyKernel not installed into interpreter Python 3.8.5 64-bit ('django_signally-JCl81_Vu-py3.8': poetry):/home/phillyharper/.cache/pypoetry/virtualenvs/django_signally-JCl81_Vu-py3.8/bin/python
	at _.handleKernelDependencyResponse (/home/phillyharper/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.2041215044/out/client/extension.js:54:291495)
	at _.installMissingDependencies (/home/phillyharper/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.2041215044/out/client/extension.js:54:291076)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)] {
  category: 'noipykernel',
  reason: 1
}
Error 2021-09-29 16:54:28: Raw session failed to start because dependencies not installed
Info 2021-09-29 16:54:28: Shutdown session -- complete
Error 2021-09-29 16:54:28: failed to create INotebook in kernel, UI Disabled = false [a [Error]: IPyKernel not installed into interpreter Python 3.8.5 64-bit ('django_signally-JCl81_Vu-py3.8': poetry):/home/phillyharper/.cache/pypoetry/virtualenvs/django_signally-JCl81_Vu-py3.8/bin/python
	at _.handleKernelDependencyResponse (/home/phillyharper/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.2041215044/out/client/extension.js:54:291495)
	at _.installMissingDependencies (/home/phillyharper/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.2041215044/out/client/extension.js:54:291076)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)] {
  category: 'noipykernel',
  reason: 1
}
Error 2021-09-29 16:54:28: DataScience Error [a [Error]: IPyKernel not installed into interpreter Python 3.8.5 64-bit ('django_signally-JCl81_Vu-py3.8': poetry):/home/phillyharper/.cache/pypoetry/virtualenvs/django_signally-JCl81_Vu-py3.8/bin/python
	at _.handleKernelDependencyResponse (/home/phillyharper/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.2041215044/out/client/extension.js:54:291495)
	at _.installMissingDependencies (/home/phillyharper/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.2041215044/out/client/extension.js:54:291076)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)] {
  category: 'noipykernel',
  reason: 1
}
Error 2021-09-29 16:54:28: failed to start INotebook in kernel, UI Disabled = false [a [Error]: IPyKernel not installed into interpreter Python 3.8.5 64-bit ('django_signally-JCl81_Vu-py3.8': poetry):/home/phillyharper/.cache/pypoetry/virtualenvs/django_signally-JCl81_Vu-py3.8/bin/python
	at _.handleKernelDependencyResponse (/home/phillyharper/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.2041215044/out/client/extension.js:54:291495)
	at _.installMissingDependencies (/home/phillyharper/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.2041215044/out/client/extension.js:54:291076)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)] {
  category: 'noipykernel',
  reason: 1
}
Error 2021-09-29 16:54:28: Failed to execute cells in CellExecutionQueue [a [Error]: IPyKernel not installed into interpreter Python 3.8.5 64-bit ('django_signally-JCl81_Vu-py3.8': poetry):/home/phillyharper/.cache/pypoetry/virtualenvs/django_signally-JCl81_Vu-py3.8/bin/python
	at _.handleKernelDependencyResponse (/home/phillyharper/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.2041215044/out/client/extension.js:54:291495)
	at _.installMissingDependencies (/home/phillyharper/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.2041215044/out/client/extension.js:54:291076)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)] {
  category: 'noipykernel',
  reason: 1
}
Info 2021-09-29 16:54:28: Cancel pending cells
```

</p>
</details>

**Comment by NomeChomsky** [comment]
This is solved. This was an issue with poetry being convinced something was installed when it wasn't.

**Comment by rchiodo** [comment]
Glad to hear it's working. Thanks.
