### ISSUE TITLE
Failing to create Data Viewer 

### ISSUE THREAD

**Issue by MombasaRaha** [microsoft/vscode-jupyter#7744]
## Environment data

-   VS Code version: 1.60.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.2041215044
-   Python Extension version (available under the Extensions sidebar): v2021.9.1246542782
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: Python 3.8.8 64-bit
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

View the selected variables in Data Viewer

## Actual behaviour

Trying to display the variables in Data Viewer with no success

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

import pandas as pd
df = pd.read_csv(csv_file, nrows=15)
pjk = df.iloc[[1],[0]]
str = pjk.to_string(index = False)
locae = int(str[-2:]) -1
df = pd.read_csv(csv_file, skiprows=locae, low_memory=False)

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Info 2021-09-29 17:14:09: Execute Cells request 1 0
Info 2021-09-29 17:14:09: Execute Cell 0 untitled:Untitled-1.ipynb?jupyter-notebook
Info 2021-09-29 17:14:09: Notebook Session status untitled:Untitled-1.ipynb?jupyter-notebook # Busy
Info 2021-09-29 17:14:10: Notebook Session status untitled:Untitled-1.ipynb?jupyter-notebook # Idle
Info 2021-09-29 17:14:16: Searching for token colors ...
Info 2021-09-29 17:14:16: Attempting search for colors ...
Info 2021-09-29 17:14:16: Loading colors from c:\Users\3053424\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\light_plus.json ...
Info 2021-09-29 17:14:16: Notebook Session status untitled:Untitled-1.ipynb?jupyter-notebook # Busy
Info 2021-09-29 17:14:16: Attempting search for colors ...
Info 2021-09-29 17:14:16: Loading base colors from c:\Users\3053424\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\light_plus.json ...
Info 2021-09-29 17:14:16: Notebook Session status untitled:Untitled-1.ipynb?jupyter-notebook # Idle
Info 2021-09-29 17:14:16: Notebook Session status untitled:Untitled-1.ipynb?jupyter-notebook # Busy
Info 2021-09-29 17:14:16: Using colors to generate CSS ...
Info 2021-09-29 17:14:16: Notebook Session status untitled:Untitled-1.ipynb?jupyter-notebook # Idle
Info 2021-09-29 17:14:16: Notebook Session status untitled:Untitled-1.ipynb?jupyter-notebook # Busy
Info 2021-09-29 17:14:16: Notebook Session status untitled:Untitled-1.ipynb?jupyter-notebook # Idle
Info 2021-09-29 17:14:16: Notebook Session status untitled:Untitled-1.ipynb?jupyter-notebook # Busy
Info 2021-09-29 17:14:16: Notebook Session status untitled:Untitled-1.ipynb?jupyter-notebook # Idle
Info 2021-09-29 17:14:16: Notebook Session status untitled:Untitled-1.ipynb?jupyter-notebook # Busy
Info 2021-09-29 17:14:16: Notebook Session status untitled:Untitled-1.ipynb?jupyter-notebook # Idle
Info 2021-09-29 17:14:16: Notebook Session status untitled:Untitled-1.ipynb?jupyter-notebook # Busy
Info 2021-09-29 17:14:16: Notebook Session status untitled:Untitled-1.ipynb?jupyter-notebook # Idle
Info 2021-09-29 17:14:16: Notebook Session status untitled:Untitled-1.ipynb?jupyter-notebook # Busy
Info 2021-09-29 17:14:16: Notebook Session status untitled:Untitled-1.ipynb?jupyter-notebook # Idle
Info 2021-09-29 17:14:16: Notebook Session status untitled:Untitled-1.ipynb?jupyter-notebook # Busy
Info 2021-09-29 17:14:16: Notebook Session status untitled:Untitled-1.ipynb?jupyter-notebook # Idle
Info 2021-09-29 17:14:16: Notebook Session status untitled:Untitled-1.ipynb?jupyter-notebook # Busy
Info 2021-09-29 17:14:16: Notebook Session status untitled:Untitled-1.ipynb?jupyter-notebook # Idle
Info 2021-09-29 17:14:16: Notebook Session status untitled:Untitled-1.ipynb?jupyter-notebook # Busy
Info 2021-09-29 17:14:16: Notebook Session status untitled:Untitled-1.ipynb?jupyter-notebook # Idle
Info 2021-09-29 17:14:16: Notebook Session status untitled:Untitled-1.ipynb?jupyter-notebook # Busy
Info 2021-09-29 17:14:16: Notebook Session status untitled:Untitled-1.ipynb?jupyter-notebook # Idle
Info 2021-09-29 17:14:16: Notebook Session status untitled:Untitled-1.ipynb?jupyter-notebook # Busy
Info 2021-09-29 17:14:16: Notebook Session status untitled:Untitled-1.ipynb?jupyter-notebook # Idle
Info 2021-09-29 17:14:16: Notebook Session status untitled:Untitled-1.ipynb?jupyter-notebook # Busy
Info 2021-09-29 17:14:16: Notebook Session status untitled:Untitled-1.ipynb?jupyter-notebook # Idle
Info 2021-09-29 17:14:16: Notebook Session status untitled:Untitled-1.ipynb?jupyter-notebook # Busy
Info 2021-09-29 17:14:16: Notebook Session status untitled:Untitled-1.ipynb?jupyter-notebook # Idle
Info 2021-09-29 17:14:18: Loading webview. View is notset
Info 2021-09-29 17:14:18: Loading web view...
Info 2021-09-29 17:14:18: Webview panel created.
Info 2021-09-29 17:14:18: Process Execution: > ~\Anaconda3\python.exe -c "import pandas;print(pandas.__version__)"
> ~\Anaconda3\python.exe -c "import pandas;print(pandas.__version__)"
Info 2021-09-29 17:14:18: Web view react rendered
Info 2021-09-29 17:14:18: Searching for token colors ...
Info 2021-09-29 17:14:18: Attempting search for colors ...
Info 2021-09-29 17:14:18: Searching for token colors ...
Info 2021-09-29 17:14:18: Attempting search for colors ...
Info 2021-09-29 17:14:18: Loading colors from c:\Users\3053424\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\light_plus.json ...
Info 2021-09-29 17:14:18: Loading colors from c:\Users\3053424\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\light_plus.json ...
Info 2021-09-29 17:14:18: Attempting search for colors ...
Info 2021-09-29 17:14:18: Loading base colors from c:\Users\3053424\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\light_plus.json ...
Info 2021-09-29 17:14:18: Attempting search for colors ...
Info 2021-09-29 17:14:18: Loading base colors from c:\Users\3053424\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\light_plus.json ...
Info 2021-09-29 17:14:18: Using colors to generate CSS ...
Info 2021-09-29 17:14:18: Using colors to generate CSS ...
Info 2021-09-29 17:14:19: Notebook Session status untitled:Untitled-1.ipynb?jupyter-notebook # Busy
Info 2021-09-29 17:14:19: Notebook Session status untitled:Untitled-1.ipynb?jupyter-notebook # Idle
Error 2021-09-29 17:14:19: Failure during variable extraction:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-fc10f46e658f> in <module>
----> 1 print(_VSCODE_getDataFrameInfo(df))

<ipython-input-2-9babb6f1fe0e> in _VSCODE_getDataFrameInfo(df)
    192     for n in _VSCODE_builtins.range(0, _VSCODE_builtins.len(columnNames)):
    193         column_type = columnTypes[n]
--> 194         column_name = str(columnNames[n])
    195         colobj = {}
    196         colobj["key"] = column_name

TypeError: 'str' object is not callable
Error 2021-09-29 17:14:19: [Error: Failure during variable extraction:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-fc10f46e658f> in <module>
----> 1 print(_VSCODE_getDataFrameInfo(df))

<ipython-input-2-9babb6f1fe0e> in _VSCODE_getDataFrameInfo(df)
    192     for n in _VSCODE_builtins.range(0, _VSCODE_builtins.len(columnNames)):
    193         column_type = columnTypes[n]
--> 194         column_name = str(columnNames[n])
    195         colobj = {}
    196         colobj["key"] = column_name

TypeError: 'str' object is not callable
	at f.extractJupyterResultText (c:\Users\3053424\.vscode\extensions\ms-toolsai.jupyter-2021.8.2041215044\out\client\extension.js:90:260929)
	at f.deserializeJupyterResult (c:\Users\3053424\.vscode\extensions\ms-toolsai.jupyter-2021.8.2041215044\out\client\extension.js:90:261047)
	at f.getDataFrameInfo (c:\Users\3053424\.vscode\extensions\ms-toolsai.jupyter-2021.8.2041215044\out\client\extension.js:90:257930)
	at async r.ensureInitialized (c:\Users\3053424\.vscode\extensions\ms-toolsai.jupyter-2021.8.2041215044\out\client\extension.js:52:865631)
	at async r.getDataFrameInfo (c:\Users\3053424\.vscode\extensions\ms-toolsai.jupyter-2021.8.2041215044\out\client\extension.js:52:864485)
	at async C.prepDataFrameInfo (c:\Users\3053424\.vscode\extensions\ms-toolsai.jupyter-2021.8.2041215044\out\client\extension.js:52:857301)
	at async C.showData (c:\Users\3053424\.vscode\extensions\ms-toolsai.jupyter-2021.8.2041215044\out\client\extension.js:52:855160)
	at async f.create (c:\Users\3053424\.vscode\extensions\ms-toolsai.jupyter-2021.8.2041215044\out\client\extension.js:52:862686)]
Info 2021-09-29 17:14:19: notebook communications already initialized for editor untitled:Untitled-1.ipynb?jupyter-notebook

```

</p>
</details>

**Comment by rchiodo** [comment]
Thanks for the bug.

This error here is the problem:

```
<ipython-input-2-9babb6f1fe0e> in _VSCODE_getDataFrameInfo(df)
    192     for n in _VSCODE_builtins.range(0, _VSCODE_builtins.len(columnNames)):
    193         column_type = columnTypes[n]
--> 194         column_name = str(columnNames[n])
    195         colobj = {}
    196         colobj["key"] = column_name
```

It looks like you might have redefined the global 'str' function? 

What happens if you run this code in a cell?

```
x = 29
print(str(x))
```

If that still works then perhaps one of the columns in your csv isn't translatable to a string. Although I think that would give a different error.

**Comment by MombasaRaha** [comment]
Actually, that doesn't work either, comes up with this error 
`'str' object is not callable`
 so looks like you're right about that, no idea how I managed to do that though.

**Comment by MombasaRaha** [comment]
Would you know how to resolve this issue?

**Comment by rchiodo** [comment]
This might work to tell you were 'str' is defined:

```
print(str.__module__)
```

Otherwise you might debug a python file and see what the debugger says for 'str'. It's likely a global variable.

**Comment by MombasaRaha** [comment]
Great, thanks for the help.
