### ISSUE TITLE
Right click "Convert a Notebook to Python Script" doesn't work.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#7783]
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

1. Open a workspace
2. Right click on an ipynb file
3. Choose "Convert a Notebook to a Python Script"

Fails. Here's the log from an attempt I made. Note that my default Python interpreter is not set to PythonCodingPack\python.exe. However, it IS the python that's found first based on my Windows System Path setting. Guessing that's where this is coming from. 

```Info 2021-10-01 11:55:22: Process Execution: > ~\AppData\Local\Programs\PythonCodingPack\python.exe -m jupyter nbconvert --version
> ~\AppData\Local\Programs\PythonCodingPack\python.exe -m jupyter nbconvert --version
Info 2021-10-01 11:55:22: Process Execution: > ~\AppData\Local\Programs\PythonCodingPack\python.exe -m jupyter nbconvert --version
> ~\AppData\Local\Programs\PythonCodingPack\python.exe -m jupyter nbconvert --version
Error 2021-10-01 11:55:22: Export failed [Error: Importing notebooks requires Jupyter nbconvert to be installed.
	at g.importFromFile (c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.9.1001286107\out\client\extension.js:52:973776)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async s.export (c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.9.1001286107\out\client\extension.js:52:923161)
	at async b.exportToFormat (c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.9.1001286107\out\client\extension.js:52:920676)
	at async b.performExport (c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.9.1001286107\out\client\extension.js:52:919861)
	at async b.export (c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.9.1001286107\out\client\extension.js:52:919375)
	at async g.export (c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.9.1001286107\out\client\extension.js:37:290037)
	at async l._executeContributedCommand (c:\Users\jimg\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:94:111612)]
Info 2021-10-01 11:55:51: Notebook Closed file:///c%3A/Users/jimg/Repos/covid-19-data-1/SampleNbsAndScripts/test4nb.ipynb
```

### VS Code Version

Version: 1.61.0-insider (user setup) Commit: 4fbe0344a0cedaf2a04edef728c9a3f27777cc6c Date: 2021-09-29T05:38:00.706Z Electron: 13.5.0 Chrome: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Windows_NT x64 10.0.22468

### Jupyter Extension Version

v2021.9.1001286107

### Jupyter logs

```shell
See above
```

**Comment by heysujal** [comment]
hi @greazer . I want to fix this issue . I am familiar with python. Can you guide me on how to fix this issue?

**Comment by greazer** [comment]
Thanks @heysujal! Are you running into this bug? 

We'd love to have some help. That being said, the work that has to be done to fix this is either in the Jupyter extension or the Python extension and *possibly* VS Code core (depending on the results of the investigation, which hasn't been done yet). You can take a look at the Contributing.md files in each of these repos to see how to get started, building and debugging each extension. 

Also for the record, indeed the system path is what is causing PythonCodingPack\python.exe to be found and used on my machine.

**Comment by DavidKutu** [comment]
Just adding my 2 cents. This works for me, it might be a python environment issue.

**Comment by DonJayamanne** [comment]
Same here, works for me too. I wouldn't call this a regression.
Its just an existing but in the code & causing it to not work for some situations.

**Comment by heysujal** [comment]
https://github.com/microsoft/vscode-jupyter/issues/5222#issuecomment-909625520
I think this should be done.

> Actually after removing access to any python.exe from my path, I'm expectedly getting the "nbconvert needs to be installed" error, but curiously it's still looking at the PythonCodingPack path. I have no idea why that would be:
> 
> ```
> Info 2021-10-01 13:00:43: Process Execution: > ~\AppData\Local\Programs\PythonCodingPack\python.exe -c "import nbconvert"
> > ~\AppData\Local\Programs\PythonCodingPack\python.exe -c "import nbconvert"
> Info 2021-10-01 13:00:43: Process Execution: > ~\AppData\Local\Programs\PythonCodingPack\python.exe -c "import nbconvert"
> > ~\AppData\Local\Programs\PythonCodingPack\python.exe -c "import nbconvert"
> Info 2021-10-01 13:00:45: Process Execution: > ~\AppData\Local\Programs\PythonCodingPack\python.exe -m jupyter nbconvert --version
> > ~\AppData\Local\Programs\PythonCodingPack\python.exe -m jupyter nbconvert --version
> Info 2021-10-01 13:00:45: Process Execution: > ~\AppData\Local\Programs\PythonCodingPack\python.exe -m jupyter nbconvert --version
> > ~\AppData\Local\Programs\PythonCodingPack\python.exe -m jupyter nbconvert --version
> Error 2021-10-01 13:00:45: Export failed [Error: Importing notebooks requires Jupyter nbconvert to be installed.
> 	at g.importFromFile (c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.9.1001286107\out\client\extension.js:52:973776)
> 	at runMicrotasks (<anonymous>)
> 	at processTicksAndRejections (internal/process/task_queues.js:93:5)
> 	at async s.export (c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.9.1001286107\out\client\extension.js:52:923161)
> 	at async b.exportToFormat (c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.9.1001286107\out\client\extension.js:52:920676)
> 	at async b.performExport (c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.9.1001286107\out\client\extension.js:52:919861)
> 	at async b.export (c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.9.1001286107\out\client\extension.js:52:919375)
> 	at async c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.9.1001286107\out\client\extension.js:90:269135
> 	at async u.waitWithStatus (c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.9.1001286107\out\client\extension.js:90:232892)
> 	at async k.importNotebookOnFile (c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.9.1001286107\out\client\extension.js:90:269058)
> 	at async k.listenForErrors (c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.9.1001286107\out\client\extension.js:90:264837)
> 	at async l._executeContributedCommand (c:\Users\jimg\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:94:111612)]
> Info 2021-10-01 13:00:47: Process Execution: > ~\anaconda3\envs\myenv\python.exe -c "import ipykernel"
> > ~\anaconda3\envs\myenv\python.exe -c "import ipykernel"
> Info 2021-10-01 13:00:47: Process Execution: > ~\anaconda3\envs\myenv\python.exe -m pip list
> > ~\anaconda3\envs\myenv\python.exe -m pip list
> Info 2021-10-01 13:00:48: Install Missing Dependencies, Class name = E, completed in 19161ms, has a falsy return value, Return Value: undefined
> Info 2021-10-01 13:00:48: Kernel launching with ports 9000,9001,9002,9003,9004. Start port is 9000
> ```

@greazer  I also faced same issue then I installed `jupyter` , `notebook` , and `nbconvert`.
Then issue got fixed.
Now all we no to do is to give prompt to install these three packages.

**Comment by rchiodo** [comment]
This should fix this problem:
https://github.com/microsoft/vscode-python/pull/17614

**Comment by rchiodo** [comment]
This should be working after Ian's change.
