### ISSUE TITLE
Better handling the situation when`ipykernel` missing

### ISSUE THREAD

**Issue by maxwellzh** [microsoft/vscode-jupyter#7787]
On running a cell in the notebook, if `ipykernel` is missing, current behavior is to install `ipykernel` with 
```
conda install ipykernel -y
```

However, **if you don't have `jupyter` installed**, it just asks you to re-install ipykernel again and again.
<img width="535" alt="截屏2021-10-02 下午5 59 23" src="https://user-images.githubusercontent.com/32546978/135711741-6e314930-c6c0-4077-a6a3-9665bac6fdb0.png">

The output of jupyter extension:
<img width="1398" alt="截屏2021-10-02 下午6 00 17" src="https://user-images.githubusercontent.com/32546978/135711771-78299321-dfc2-42b1-bc92-b6f583ed8c9d.png">

So I guess the current way of handling the missing ipykernel is to try `python -c "import ipykernel"`, and if it fails, reports the user to re-install ipykernel. 

I also manually execute this command:
<img width="818" alt="截屏2021-10-02 下午6 00 36" src="https://user-images.githubusercontent.com/32546978/135711830-cbe30e3d-c896-4df2-81ab-9ef0afeabcfd.png">
And finally found that it was due to the missing `jupyter` package.

So the quick fix is :
```
conda install jupyter -y
```

```

**Comment by maxwellzh** [comment]
This has been reported before #6272, but that issue was closed.

**Comment by DonJayamanne** [comment]
Sorry the current solution didn't work.
Please let me know if your are able to repro that issue. 
Installing Jupyter isn't required.

**Comment by DonJayamanne** [comment]
If possible, please could you:
* Remove ipytjon_genutils
* are you using a notebook or interactive window?
* replicate the issue
* Provided the output from `jupyter` output panel.
* Provided the version infor for vscode, python and Jupyter extension
* Finally the output from the terminal when installing ipykernel.

Sorry, but I need all of the above to ensure I can fix this, would very much sorry you're help here. Thanks again

**Comment by maxwellzh** [comment]
@DonJayamanne For the info:
1. I'm using interactive window.
2. vscode `1.60.2`, python 3.9.7/3.8.11, python extension `v2021.9.1246542782`, Jupyter extension `v2021.8.2041215044`

Follow your instruction, I did
1. `conda uninstall jupyter ipytjon_genutils -y`.
2. open a notebook, and run cell (and it asks for re-installing the ipykernel).
<img width="1211" alt="截屏2021-10-02 下午10 12 38" src="https://user-images.githubusercontent.com/32546978/135720528-4089555b-c348-4eee-9080-078143ff6fb2.png">
<img width="309" alt="截屏2021-10-02 下午10 12 48" src="https://user-images.githubusercontent.com/32546978/135720572-a0b4eddd-0d0b-4c81-b62d-13b6284f33fa.png">

3.  extension ouput
<details>

```
Info 2021-10-02 22:13:27: Attempting to start a server because of preload conditions ...
Info 2021-10-02 22:13:27: Setting setActiveController for file:///home/zhenghh/Transducer-dev/egs/aishell/test.ipynb
Info 2021-10-02 22:13:27: Intiailize notebook communications for editor file:///home/zhenghh/Transducer-dev/egs/aishell/test.ipynb
Info 2021-10-02 22:13:27: Resolving notebook UI Comms (resolve) for file:///home/zhenghh/Transducer-dev/egs/aishell/test.ipynb
Info 2021-10-02 22:13:27: initialize CommonMessageCoordinator
Info 2021-10-02 22:13:27: Process Execution: > ~/miniconda3/envs/test/bin/python -m pip list
> ~/miniconda3/envs/test/bin/python -m pip list
Info 2021-10-02 22:13:27: IPyWidgetMessageDispatcher.initialize
Info 2021-10-02 22:13:27: Find preferred kernel for file:///home/zhenghh/Transducer-dev/egs/aishell/test.ipynb with metadata {"orig_nbformat":4,"language_info":{"name":"python","version":"3.9.7","mimetype":"text/x-python","codemirror_mode":{"name":"ipython","version":3},"pygments_lexer":"ipython3","nbconvert_exporter":"python","file_extension":".py"},"kernelspec":{"name":"python3","display_name":"Python 3.9.7 64-bit ('rnnt': conda)"},"interpreter":{"hash":"e699c423508c35950bbf70abd05f55c055b584a632c1ab99d1c4575520c0bafb"}} & preferred interpreter {"sysPrefix":"/home/zhenghh/miniconda3/envs/test","envType":"Conda","envName":"test","envPath":"/home/zhenghh/miniconda3/envs/test","path":"/home/zhenghh/miniconda3/envs/test/bin/python","architecture":3,"sysVersion":"3.8.11 (default, Aug  3 2021, 15:09:35) \n[GCC 7.5.0]","version":{"raw":"3.8.11","major":3,"minor":8,"patch":11,"build":[],"prerelease":["final","0"]},"companyDisplayName":"Anaconda, Inc.","displayName":"Python 3.8.11 64-bit ('test': conda)"}
Info 2021-10-02 22:13:27: findPreferredKernel score for speclanguage=python, Python 2.7.17 64-bit is -1
Info 2021-10-02 22:13:27: findPreferredKernel score for Python 2.7.17 64-bit is 1
Info 2021-10-02 22:13:27: findPreferredKernel score for speclanguage=python, Python 3.6.9 64-bit is -1
Info 2021-10-02 22:13:27: findPreferredKernel score for Python3, Python 3.6.9 64-bit is 2
Info 2021-10-02 22:13:27: findPreferredKernel score for Python 3.6.9 64-bit is 2
Info 2021-10-02 22:13:27: findPreferredKernel score for speclanguage=python, Python 3.8.11 64-bit ('test': conda) is -1
Info 2021-10-02 22:13:27: findPreferredKernel score for Python3, Python 3.8.11 64-bit ('test': conda) is 2
Info 2021-10-02 22:13:27: findPreferredKernel score for Python 3.8.11 64-bit ('test': conda) is 2
Info 2021-10-02 22:13:27: findPreferredKernel score for speclanguage=python, Python 3.9.1 64-bit ('base': conda) is -1
Info 2021-10-02 22:13:27: findPreferredKernel score for Python3, Python 3.9.1 64-bit ('base': conda) is 2
Info 2021-10-02 22:13:27: findPreferredKernel score for Python 3.9.1 64-bit ('base': conda) is 2
Info 2021-10-02 22:13:27: findPreferredKernel score for Python3, Python 3.9.7 64-bit ('rnnt': conda) is 116
Info 2021-10-02 22:13:27: findPreferredKernel score for Python 3.9.7 64-bit ('rnnt': conda) is 116
Info 2021-10-02 22:13:27: findKernel found Python 3.9.7 64-bit ('rnnt': conda)
Info 2021-10-02 22:13:27: Find kernel spec, Class name = x, completed in 39ms, has a truthy return value, Arg 1: <Uri:/home/zhenghh/Transducer-dev/egs/aishell/test.ipynb>, Arg 2: {"orig_nbformat":4,"language_info":{"name":"python","version":"3.9.7","mimetype":"text/x-python","codemirror_mode":{"name":"ipython","version":3},"pygments_lexer":"ipython3","nbconvert_exporter":"python","file_extension":".py"},"kernelspec":{"name":"python3","display_name":"Python 3.9.7 64-bit ('rnnt': conda)"},"interpreter":{"hash":"e699c423508c35950bbf70abd05f55c055b584a632c1ab99d1c4575520c0bafb"}}, Arg 3: {"_isCancelled":false,"_emitter":{"_disposed":false,"_listeners":{"_first":{"next":{},"prev":{}},"_last":{"next":{},"prev":{}},"_size":1}}}, Return Value: {"kind":"startUsingPythonInterpreter","kernelSpec":{"specFile":"/home/zhenghh/.local/share/jupyter/kernels/python397jvsc74a57bd0e699c423508c35950bbf70abd05f55c055b584a632c1ab99d1c4575520c0bafb/kernel.json","interpreterPath":"/home/zhenghh/miniconda3/envs/rnnt/bin/python","name":"python397jvsc74a57bd0e699c423508c35950bbf70abd05f55c055b584a632c1ab99d1c4575520c0bafb","argv":["python","-m","ipykernel_launcher","-f","{connection_file}"],"language":"python","path":"python","display_name":"Python 3.9.7 64-bit ('rnnt': conda)","metadata":{"interpreter":{"sysPrefix":"/home/zhenghh/miniconda3/envs/rnnt","envType":"Conda","envName":"rnnt","envPath":"/home/zhenghh/miniconda3/envs/rnnt","path":"/home/zhenghh/miniconda3/envs/rnnt/bin/python","architecture":3,"sysVersion":"3.9.7 (default, Sep 16 2021, 13:09:58) \n[GCC 7.5.0]","version":{"raw":"3.9.7","major":3,"minor":9,"patch":7,"build":[],"prerelease":["final","0"]},"companyDisplayName":"Anaconda, Inc.","displayName":"Python 3.9.7 64-bit ('rnnt': conda)"}},"env":{}},"interpreter":{"sysPrefix":"/home/zhenghh/miniconda3/envs/rnnt","envType":"Conda","envName":"rnnt","envPath":"/home/zhenghh/miniconda3/envs/rnnt","path":"/home/zhenghh/miniconda3/envs/rnnt/bin/python","architecture":3,"sysVersion":"3.9.7 (default, Sep 16 2021, 13:09:58) \n[GCC 7.5.0]","version":{"raw":"3.9.7","major":3,"minor":9,"patch":7,"build":[],"prerelease":["final","0"]},"companyDisplayName":"Anaconda, Inc.","displayName":"Python 3.9.7 64-bit ('rnnt': conda)"},"id":".jvsc74a57bd0e699c423508c35950bbf70abd05f55c055b584a632c1ab99d1c4575520c0bafb./home/zhenghh/miniconda3/envs/rnnt/bin/python./home/zhenghh/miniconda3/envs/rnnt/bin/python.-m#ipykernel_launcher"}
Info 2021-10-02 22:13:27: PreferredConnection: .jvsc74a57bd0e699c423508c35950bbf70abd05f55c055b584a632c1ab99d1c4575520c0bafb./home/zhenghh/miniconda3/envs/rnnt/bin/python./home/zhenghh/miniconda3/envs/rnnt/bin/python.-m#ipykernel_launcher found for NotebookDocument: file:///home/zhenghh/Transducer-dev/egs/aishell/test.ipynb
Info 2021-10-02 22:13:27: TargetController found ID: .jvsc74a57bd0e699c423508c35950bbf70abd05f55c055b584a632c1ab99d1c4575520c0bafb./home/zhenghh/miniconda3/envs/rnnt/bin/python./home/zhenghh/miniconda3/envs/rnnt/bin/python.-m#ipykernel_launcher for document file:///home/zhenghh/Transducer-dev/egs/aishell/test.ipynb
Info 2021-10-02 22:13:27: Setting controller affinity for file:///home/zhenghh/Transducer-dev/egs/aishell/test.ipynb .jvsc74a57bd0e699c423508c35950bbf70abd05f55c055b584a632c1ab99d1c4575520c0bafb./home/zhenghh/miniconda3/envs/rnnt/bin/python./home/zhenghh/miniconda3/envs/rnnt/bin/python.-m#ipykernel_launcher
Info 2021-10-02 22:13:27: Created and initailized CommonMessageCoordinator
Info 2021-10-02 22:13:27: Attach Coordinator for file:///home/zhenghh/Transducer-dev/egs/aishell/test.ipynb
Info 2021-10-02 22:13:27: KernelProvider switched kernel to id = .jvsc74a57bd03612b25d2960302137dec726782d4998218844e7c411297ebdcb5d43a94312a5./home/zhenghh/miniconda3/envs/test/bin/python./home/zhenghh/miniconda3/envs/test/bin/python.-m#ipykernel_launcher
Info 2021-10-02 22:13:27: Starting Notebook in kernel.ts id = .jvsc74a57bd03612b25d2960302137dec726782d4998218844e7c411297ebdcb5d43a94312a5./home/zhenghh/miniconda3/envs/test/bin/python./home/zhenghh/miniconda3/envs/test/bin/python.-m#ipykernel_launcher
Info 2021-10-02 22:13:27: Creating raw notebook for file:///home/zhenghh/Transducer-dev/egs/aishell/test.ipynb
Info 2021-10-02 22:13:27: Getting preferred kernel for file:///home/zhenghh/Transducer-dev/egs/aishell/test.ipynb
Info 2021-10-02 22:13:27: Computing working directory file:///home/zhenghh/Transducer-dev/egs/aishell/test.ipynb
Info 2021-10-02 22:13:27: Connecting to raw session for file:///home/zhenghh/Transducer-dev/egs/aishell/test.ipynb with connection {"kind":"startUsingPythonInterpreter","kernelSpec":{"specFile":"/home/zhenghh/.local/share/jupyter/kernels/python3811jvsc74a57bd03612b25d2960302137dec726782d4998218844e7c411297ebdcb5d43a94312a5/kernel.json","interpreterPath":"/home/zhenghh/miniconda3/envs/test/bin/python","name":"python3811jvsc74a57bd03612b25d2960302137dec726782d4998218844e7c411297ebdcb5d43a94312a5","argv":["python","-m","ipykernel_launcher","-f","{connection_file}"],"language":"python","path":"python","display_name":"Python 3.8.11 64-bit ('test': conda)","metadata":{"interpreter":{"sysPrefix":"/home/zhenghh/miniconda3/envs/test","envType":"Conda","envName":"test","envPath":"/home/zhenghh/miniconda3/envs/test","path":"/home/zhenghh/miniconda3/envs/test/bin/python","architecture":3,"sysVersion":"3.8.11 (default, Aug  3 2021, 15:09:35) \n[GCC 7.5.0]","version":{"raw":"3.8.11","major":3,"minor":8,"patch":11,"build":[],"prerelease":["final","0"]},"companyDisplayName":"Anaconda, Inc.","displayName":"Python 3.8.11 64-bit ('test': conda)"}},"env":{}},"interpreter":{"sysPrefix":"/home/zhenghh/miniconda3/envs/test","envType":"Conda","envName":"test","envPath":"/home/zhenghh/miniconda3/envs/test","path":"/home/zhenghh/miniconda3/envs/test/bin/python","architecture":3,"sysVersion":"3.8.11 (default, Aug  3 2021, 15:09:35) \n[GCC 7.5.0]","version":{"raw":"3.8.11","major":3,"minor":8,"patch":11,"build":[],"prerelease":["final","0"]},"companyDisplayName":"Anaconda, Inc.","displayName":"Python 3.8.11 64-bit ('test': conda)"},"id":".jvsc74a57bd03612b25d2960302137dec726782d4998218844e7c411297ebdcb5d43a94312a5./home/zhenghh/miniconda3/envs/test/bin/python./home/zhenghh/miniconda3/envs/test/bin/python.-m#ipykernel_launcher"}
Info 2021-10-02 22:13:27: Starting raw kernel Python 3.8.11 64-bit ('test': conda)
Info 2021-10-02 22:13:27: installMissingDependencies /home/zhenghh/miniconda3/envs/test/bin/python
Info 2021-10-02 22:13:27: Process Execution: > ~/miniconda3/envs/test/bin/python -c "import ipykernel"
> ~/miniconda3/envs/test/bin/python -c "import ipykernel"
Error 2021-10-02 22:13:27: Install Missing Dependencies, Class name = _, completed in 62ms, has a falsy return value, Return Value: undefined [a [Error]: IPyKernel not installed into interpreter Python 3.8.11 64-bit ('test': conda):/home/zhenghh/miniconda3/envs/test/bin/python
	at _.handleKernelDependencyResponse (/home/zhenghh/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.2041215044/out/client/extension.js:54:291495)
	at _.installMissingDependencies (/home/zhenghh/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.2041215044/out/client/extension.js:54:291076)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)] {
  category: 'noipykernel',
  reason: 1
}
Error 2021-10-02 22:13:27: Raw session failed to start because dependencies not installed
Info 2021-10-02 22:13:27: Shutdown session -- complete
Error 2021-10-02 22:13:27: failed to create INotebook in kernel, UI Disabled = true [a [Error]: IPyKernel not installed into interpreter Python 3.8.11 64-bit ('test': conda):/home/zhenghh/miniconda3/envs/test/bin/python
	at _.handleKernelDependencyResponse (/home/zhenghh/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.2041215044/out/client/extension.js:54:291495)
	at _.installMissingDependencies (/home/zhenghh/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.2041215044/out/client/extension.js:54:291076)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)] {
  category: 'noipykernel',
  reason: 1
}
Error 2021-10-02 22:13:27: failed to start INotebook in kernel, UI Disabled = true [a [Error]: IPyKernel not installed into interpreter Python 3.8.11 64-bit ('test': conda):/home/zhenghh/miniconda3/envs/test/bin/python
	at _.handleKernelDependencyResponse (/home/zhenghh/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.2041215044/out/client/extension.js:54:291495)
	at _.installMissingDependencies (/home/zhenghh/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.2041215044/out/client/extension.js:54:291076)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)] {
  category: 'noipykernel',
  reason: 1
}
Info 2021-10-02 22:13:28: IPyWidgetMessageDispatcher.initialize
Info 2021-10-02 22:13:48: Execute Cells request 1 0
Info 2021-10-02 22:13:48: Execute Cell 0 file:///home/zhenghh/Transducer-dev/egs/aishell/test.ipynb
Info 2021-10-02 22:13:49: Starting Notebook in kernel.ts id = .jvsc74a57bd03612b25d2960302137dec726782d4998218844e7c411297ebdcb5d43a94312a5./home/zhenghh/miniconda3/envs/test/bin/python./home/zhenghh/miniconda3/envs/test/bin/python.-m#ipykernel_launcher
Info 2021-10-02 22:13:49: Creating raw notebook for file:///home/zhenghh/Transducer-dev/egs/aishell/test.ipynb
Info 2021-10-02 22:13:49: Getting preferred kernel for file:///home/zhenghh/Transducer-dev/egs/aishell/test.ipynb
Info 2021-10-02 22:13:49: Computing working directory file:///home/zhenghh/Transducer-dev/egs/aishell/test.ipynb
Info 2021-10-02 22:13:49: Connecting to raw session for file:///home/zhenghh/Transducer-dev/egs/aishell/test.ipynb with connection {"kind":"startUsingPythonInterpreter","kernelSpec":{"specFile":"/home/zhenghh/.local/share/jupyter/kernels/python3811jvsc74a57bd03612b25d2960302137dec726782d4998218844e7c411297ebdcb5d43a94312a5/kernel.json","interpreterPath":"/home/zhenghh/miniconda3/envs/test/bin/python","name":"python3811jvsc74a57bd03612b25d2960302137dec726782d4998218844e7c411297ebdcb5d43a94312a5","argv":["python","-m","ipykernel_launcher","-f","{connection_file}"],"language":"python","path":"python","display_name":"Python 3.8.11 64-bit ('test': conda)","metadata":{"interpreter":{"sysPrefix":"/home/zhenghh/miniconda3/envs/test","envType":"Conda","envName":"test","envPath":"/home/zhenghh/miniconda3/envs/test","path":"/home/zhenghh/miniconda3/envs/test/bin/python","architecture":3,"sysVersion":"3.8.11 (default, Aug  3 2021, 15:09:35) \n[GCC 7.5.0]","version":{"raw":"3.8.11","major":3,"minor":8,"patch":11,"build":[],"prerelease":["final","0"]},"companyDisplayName":"Anaconda, Inc.","displayName":"Python 3.8.11 64-bit ('test': conda)"}},"env":{}},"interpreter":{"sysPrefix":"/home/zhenghh/miniconda3/envs/test","envType":"Conda","envName":"test","envPath":"/home/zhenghh/miniconda3/envs/test","path":"/home/zhenghh/miniconda3/envs/test/bin/python","architecture":3,"sysVersion":"3.8.11 (default, Aug  3 2021, 15:09:35) \n[GCC 7.5.0]","version":{"raw":"3.8.11","major":3,"minor":8,"patch":11,"build":[],"prerelease":["final","0"]},"companyDisplayName":"Anaconda, Inc.","displayName":"Python 3.8.11 64-bit ('test': conda)"},"id":".jvsc74a57bd03612b25d2960302137dec726782d4998218844e7c411297ebdcb5d43a94312a5./home/zhenghh/miniconda3/envs/test/bin/python./home/zhenghh/miniconda3/envs/test/bin/python.-m#ipykernel_launcher"}
Info 2021-10-02 22:13:49: Starting raw kernel Python 3.8.11 64-bit ('test': conda)
Info 2021-10-02 22:13:49: installMissingDependencies /home/zhenghh/miniconda3/envs/test/bin/python
Info 2021-10-02 22:13:49: Process Execution: > ~/miniconda3/envs/test/bin/python -c "import ipykernel"
> ~/miniconda3/envs/test/bin/python -c "import ipykernel"
Info 2021-10-02 22:13:56: Process Execution: > ~/miniconda3/envs/test/bin/python -m pip list
> ~/miniconda3/envs/test/bin/python -m pip list
Error 2021-10-02 22:14:10: Install Missing Dependencies, Class name = _, completed in 21366ms, has a falsy return value, Return Value: undefined [a [Error]: IPyKernel not installed into interpreter Python 3.8.11 64-bit ('test': conda):/home/zhenghh/miniconda3/envs/test/bin/python
	at _.handleKernelDependencyResponse (/home/zhenghh/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.2041215044/out/client/extension.js:54:291495)
	at _.installMissingDependencies (/home/zhenghh/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.2041215044/out/client/extension.js:54:291076)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)] {
  category: 'noipykernel',
  reason: 2
}
Error 2021-10-02 22:14:10: Raw session failed to start because dependencies not installed
Info 2021-10-02 22:14:10: Shutdown session -- complete
Error 2021-10-02 22:14:10: failed to create INotebook in kernel, UI Disabled = false [a [Error]: IPyKernel not installed into interpreter Python 3.8.11 64-bit ('test': conda):/home/zhenghh/miniconda3/envs/test/bin/python
	at _.handleKernelDependencyResponse (/home/zhenghh/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.2041215044/out/client/extension.js:54:291495)
	at _.installMissingDependencies (/home/zhenghh/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.2041215044/out/client/extension.js:54:291076)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)] {
  category: 'noipykernel',
  reason: 2
}
Error 2021-10-02 22:14:10: DataScience Error [a [Error]: IPyKernel not installed into interpreter Python 3.8.11 64-bit ('test': conda):/home/zhenghh/miniconda3/envs/test/bin/python
	at _.handleKernelDependencyResponse (/home/zhenghh/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.2041215044/out/client/extension.js:54:291495)
	at _.installMissingDependencies (/home/zhenghh/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.2041215044/out/client/extension.js:54:291076)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)] {
  category: 'noipykernel',
  reason: 2
}
Error 2021-10-02 22:14:10: failed to start INotebook in kernel, UI Disabled = false [a [Error]: IPyKernel not installed into interpreter Python 3.8.11 64-bit ('test': conda):/home/zhenghh/miniconda3/envs/test/bin/python
	at _.handleKernelDependencyResponse (/home/zhenghh/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.2041215044/out/client/extension.js:54:291495)
	at _.installMissingDependencies (/home/zhenghh/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.2041215044/out/client/extension.js:54:291076)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)] {
  category: 'noipykernel',
  reason: 2
}
Error 2021-10-02 22:14:10: Failed to execute cells in CellExecutionQueue [a [Error]: IPyKernel not installed into interpreter Python 3.8.11 64-bit ('test': conda):/home/zhenghh/miniconda3/envs/test/bin/python
	at _.handleKernelDependencyResponse (/home/zhenghh/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.2041215044/out/client/extension.js:54:291495)
	at _.installMissingDependencies (/home/zhenghh/.vscode-server/extensions/ms-toolsai.jupyter-2021.8.2041215044/out/client/extension.js:54:291076)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)] {
  category: 'noipykernel',
  reason: 2
}
Info 2021-10-02 22:14:10: Cancel pending cells
```

</details>

4. terminal output
<details>

```
/home/zhenghh/miniconda3/envs/test/bin/python /home/zhenghh/.vscode-server/extensions/ms-python.python-2021.9.1246542782/pythonFiles/shell_exec.py conda install --name test --update-deps --force-reinstall ipykernel -y /tmp/tmp-48882Aexh2iSR6J01.log
(base) zhenghh@ubuntu:~/Transducer-dev/egs/aishell$ /home/zhenghh/miniconda3/envs/test/bin/python /home/zhenghh/.vscode-server/extensions/ms-python.python-2021.9.1246542782/pythonFiles/shell_exec.py conda install --name test --update-deps --force-reinstall ipykernel -y /tmp/tmp-48882Aexh2iSR6J01.log
Executing command in shell >> conda install --name test --update-deps --force-reinstall ipykernel -y
Collecting package metadata (current_repodata.json): done
Solving environment: \ Solving environment: done
done

## Package Plan ##

  environment location: /home/zhenghh/miniconda3/envs/test

  added / updated specs:
    - _libgcc_mutex
    - _openmp_mutex
    - backcall
    - ca-certificates
    - certifi
    - debugpy
    - decorator
    - entrypoints
    - ipykernel
    - ipython
    - jedi
    - jupyter_client
    - jupyter_core
    - ld_impl_linux-64
    - libffi
    - libgcc-ng
    - libgomp
    - libsodium
    - libstdcxx-ng
    - matplotlib-inline
    - ncurses
    - nest-asyncio
    - openssl
    - parso
    - pexpect
    - pickleshare
    - pip
    - prompt-toolkit
    - ptyprocess
    - pygments
    - python-dateutil
    - python=3.8
    - pyzmq
    - readline
    - setuptools
    - six
    - sqlite
    - tk
    - tornado
    - traitlets
    - wcwidth
    - wheel
    - xz
    - zeromq
    - zlib


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    setuptools-58.0.4          |   py38h06a4308_0         790 KB
    ------------------------------------------------------------
                                           Total:         790 KB

The following packages will be UPDATED:

  decorator                              5.0.9-pyhd3eb1b0_0 --> 5.1.0-pyhd3eb1b0_0
  setuptools                          52.0.0-py38h06a4308_0 --> 58.0.4-py38h06a4308_0
  tk                                      8.6.10-hbc83047_0 --> 8.6.11-h1ccaba5_0
  typing_extensions                   3.10.0.0-pyhca03da5_0 --> 3.10.0.2-pyh06a4308_0



Downloading and Extracting Packages
setuptools-58.0.4    | 790 KB    | ################################################ | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(base) zhenghh@ubuntu:~/Transducer-dev/egs/aishell$ 
```

</details>

5. try to run the cell once more, and same message is raised.
<img width="317" alt="截屏2021-10-02 下午10 19 50" src="https://user-images.githubusercontent.com/32546978/135720879-7d924e5b-4505-47ca-b5a4-62c3be221445.png">

**Comment by DonJayamanne** [comment]
Oh wow, you are able to repro this consistently. That's interesting (not in a good way).
Finally, please activate your test environment and run
* pip list
* conda list

I'd like to replicate this at my end and fix this.
I'll be in touch with you tomorrow or the day. Once again thank you very much for this info, hopefully we can fix this once and for all.
I'll try to look into this ASAP (its the weekends for me, but will definitely have something on Monday).

Again, thanks a lot for your patience and feedback

**Comment by maxwellzh** [comment]
Sorry for disturbing your weekend. For the convenience, I create a new clean environment ( and also the issue exists). So there're just a few packages
* pip list

```
Package           Version
----------------- ---------
backcall          0.2.0
certifi           2021.5.30
debugpy           1.4.1
decorator         5.1.0
entrypoints       0.3
ipykernel         6.2.0
ipython           7.27.0
jedi              0.18.0
jupyter-client    7.0.1
jupyter-core      4.7.1
matplotlib-inline 0.1.2
nest-asyncio      1.5.1
parso             0.8.2
pexpect           4.8.0
pickleshare       0.7.5
pip               21.0.1
prompt-toolkit    3.0.17
ptyprocess        0.7.0
Pygments          2.10.0
python-dateutil   2.8.2
pyzmq             22.2.1
setuptools        58.0.4
six               1.16.0
tornado           6.1
traitlets         5.1.0
wcwidth           0.2.5
wheel             0.37.0
```

* conda list

```
# packages in environment at /home/zhenghh/miniconda3/envs/test-notebook:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
backcall                  0.2.0              pyhd3eb1b0_0  
ca-certificates           2021.7.5             h06a4308_1  
certifi                   2021.5.30        py38h06a4308_0  
debugpy                   1.4.1            py38h295c915_0  
decorator                 5.1.0              pyhd3eb1b0_0  
entrypoints               0.3                      py38_0  
ipykernel                 6.2.0            py38h06a4308_1  
ipython                   7.27.0           py38hb070fc8_0  
jedi                      0.18.0           py38h06a4308_1  
jupyter_client            7.0.1              pyhd3eb1b0_0  
jupyter_core              4.7.1            py38h06a4308_0  
ld_impl_linux-64          2.35.1               h7274673_9  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgomp                   9.3.0               h5101ec6_17  
libsodium                 1.0.18               h7b6447c_0  
libstdcxx-ng              9.3.0               hd4cf53a_17  
matplotlib-inline         0.1.2              pyhd3eb1b0_2  
ncurses                   6.2                  he6710b0_1  
nest-asyncio              1.5.1              pyhd3eb1b0_0  
openssl                   1.1.1l               h7f8727e_0  
parso                     0.8.2              pyhd3eb1b0_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pip                       21.0.1           py38h06a4308_0  
prompt-toolkit            3.0.17             pyhca03da5_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pygments                  2.10.0             pyhd3eb1b0_0  
python                    3.8.11          h12debd9_0_cpython  
python-dateutil           2.8.2              pyhd3eb1b0_0  
pyzmq                     22.2.1           py38h295c915_1  
readline                  8.1                  h27cfd23_0  
setuptools                58.0.4           py38h06a4308_0  
six                       1.16.0             pyhd3eb1b0_0  
sqlite                    3.36.0               hc218d9a_0  
tk                        8.6.11               h1ccaba5_0  
tornado                   6.1              py38h27cfd23_0  
traitlets                 5.1.0              pyhd3eb1b0_0  
wcwidth                   0.2.5              pyhd3eb1b0_0  
wheel                     0.37.0             pyhd3eb1b0_1  
xz                        5.2.5                h7b6447c_0  
zeromq                    4.3.4                h2531618_0  
zlib                      1.2.11               h7b6447c_3
```

BTW. The issue only happens in my remote machine (Ubuntu 20.04), while my local machine (MacOS) can normally runs Jupyter cells

**Comment by DonJayamanne** [comment]
Thanks
Personal notes 
https://issueexplorer.com/issue/ipython/ipykernel/759

**Comment by rchiodo** [comment]
We may have to install ipython_genutils ourself?

**Comment by DonJayamanne** [comment]
@maxwellzh Looks like you are running into a bug filed here https://github.com/ipython/ipykernel/issues/755
Basically ipykernel itself was busted & the update hasn't been pushed to the main channel. 

We'll try to get this fixed asap.

# Solution 
In the mean time, please use `conda install -c conda-forge ipykernel`

**Comment by DonJayamanne** [comment]
**Verification**
* Create a new conda environment
* Ensure you have `default` as the only conda channel
	* Run `conda config --show channels`
	* Use https://conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#config-channels to alter the list of channels (remove `conda-forge` if its in the list)
* Select above env as a kernel in a notebook
* Run a cell
* When prompted to install ipykenrel, install it
	* Confirm the installation in the terminal includes the cli `<conda> install -c conda-forge ipykernel....`
	* Just look for `conda-forge` in the terminal CLI used to install ipykernel
* Once installed, confirm the cell runs to completion
