### ISSUE TITLE
After updates, cannot connect to remote servers. 

### ISSUE THREAD

**Issue by yangyxt** [microsoft/vscode-jupyter#7875]
## Environment data

-   VS Code version: 1.61.0
-   Jupyter Extension version (available under the Extensions sidebar): v2021.9.1001312534
-   Python Extension version (available under the Extensions sidebar): v2021.10.1317843341
-   OS (Windows | Mac | Linux distro) and version: CentOS 7
-   Python and/or Anaconda version: Python 3.6.7, conda 4.10.3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda. (base env)
-   Jupyter server running: Remote

## Expected behaviour

Successfully connect to Jupyter notebook Server launched under a PBS interactive job. Several weeks ago the same method succeeded.

## Actual behaviour

Launch an Jupyter notebook server under a PBS interactive job, the URI is input to the Jupyter server option. According to the command-line interface, no new notebook is created. 

Whereas, launching a Jupyter notebook server in login node, can be accessed by the jupyter notebook when the URI is assigned. 

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment]
Thanks for coming this issue and sorry you area thinking into this.

* Please could you provide the logs from the Jupyter output panel.
* Also please could you provide some steps to repro this.
* When you stay it doesn't work, what do you mean by that, can you not see them kennels, or doesn't the kennel start, etc

**Comment by DonJayamanne** [comment]
Sorry, but code server is not something we support, would help if you provide the logs and information requested above.

**Comment by 0x0L** [comment]
```
jupyter ext v2021.8.12
python ext v2021.10.1317843341
```

```
code-server: v3.12.0
VS Code: v1.60.0
Commit: b37ff28a0a582aee84a8f961755d0cb40a4081db
Date: 2021-09-16T20:08:09Z (3 wks ago)
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36
```

```
[2021-10-13 14:18:46.791] [exthost] [error] Activating extension ms-toolsai.jupyter failed due to an error:
[2021-10-13 14:18:46.791] [exthost] [error] Error: Cannot find module '/home/testuser/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.8.12/out/client/extension'
Require stack:
- /usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/loader.js
- /usr/lib/code-server/vendor/modules/code-oss-dev/out/bootstrap-amd.js
- /usr/lib/code-server/vendor/modules/code-oss-dev/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
	at Function.Module._load (internal/modules/cjs/loader.js:745:27)
	at Function.u._load (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:28329)
	at Function.E._load (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:24906)
	at Function.o._load (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:59872)
	at Module.require (internal/modules/cjs/loader.js:961:19)
	at Module.require (/usr/lib/code-server/vendor/modules/code-oss-dev/extensions/git/dist/main.js:2:515806)
	at require (internal/modules/cjs/helpers.js:92:18)
	at Function.t [as __$__nodeRequire] (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/loader.js:5:101)
	at p._loadCommonJSModule (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:26315)
	at p._doActivateExtension (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:12594)
	at p._activateExtension (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:11695)
	at Object.actualActivateExtension (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:9236)
	at c._activateExtension (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:87973)
	at /usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:87655
	at Array.map (<anonymous>)
	at c._activateExtensions (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:87643)
	at c.activateByEvent (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:84977)
	at p._activateByEvent (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:10175)
	at /usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:19973
	at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

`/home/testuser/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.8.12/out/client/` does not exist

**Comment by DonJayamanne** [comment]
Looks like the Jupyter extension was not installed correctly as the times area missing.

> home/testuser/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.8.12/out/client/ does not exist

Closing this issue as it's a bug in the installation of the extension. Code server needed to install the extension correctly. Individual extensions aren't rresponsible for installation of extensions.
