### ISSUE TITLE
Unable to connect to remote jupyter server

### ISSUE THREAD

**Issue by paw-lu** [microsoft/vscode-jupyter#8148]
## Environment data

-   VS Code version: 1.61.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.9.1101343141
-   Python Extension version (available under the Extensions sidebar): v2021.10.1365161279
-   OS (Windows | Mac | Linux distro) and version: macOS 11.6
-   Python and/or Anaconda version: 4.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv
-   Jupyter server running: Remote

## Expected behaviour

Trying to connect to a remote Jupyter server for the first time. I have a Jupyter server running. If I go to http://localhost:8000/ via a browser, I can see and interact with the Jupyter Lab UI as expected. I expect inputting this address into VS Code will result in me being able to interact with the server through the editor.

## Actual behaviour

However if I try to input this address into VS Code, I get a password promt—which I fill—then nothing. Trying to run a cell results in VS Code asking for a kernel, but it has no options.

## Steps to reproduce:

1. Create a new notebook
2. Click on `Jupyter Server` on the bottom right
3. Select `Existing`
4. Input same address as browser uses

<img width="598" alt="Screen Shot 2021-11-02 at 4 49 46 PM" src="https://user-images.githubusercontent.com/30049606/139967146-98d26935-62c4-460f-b866-a45dbb7d86d9.png">

5. Get prompt to reload VS Code. Select `Reload`.
6. Get warning that connection may be insecure. Select `Yes`.

<img width="454" alt="Screen Shot 2021-11-02 at 4 53 48 PM" src="https://user-images.githubusercontent.com/30049606/139967412-89f7da1d-5427-4ebd-ae7a-1b29981a89dc.png">

7. Sometimes get a password prompt. Fill it out.
8. Attempt to run a cell
9. Get prompt to select a kernel. No kernel is available

![Kapture 2021-11-02 at 16 57 50](https://user-images.githubusercontent.com/30049606/139967725-0a9278f0-e5ff-4288-9d05-10e4565b7385.gif)

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Info 2021-11-02 17:02:15: Experimentation service retrieved: [object Object]
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'jupyterEnhancedDataViewer'
Info 2021-11-02 17:02:15: Checking for server existence.
Info 2021-11-02 17:02:15: Checking for server usability.
Info 2021-11-02 17:02:15: Starting notebook server.
Info 2021-11-02 17:02:15: Connecting to history server
Info 2021-11-02 17:02:15: Creating jupyter server: c1300479-f3b3-4a6d-a8c7-28c688bf2d18
Info 2021-11-02 17:02:15: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
Info 2021-11-02 17:02:17: Process Execution: > ~/.pyenv/versions/3.9.5/bin/python3.9 -c "import jupyter"
> ~/.pyenv/versions/3.9.5/bin/python3.9 -c "import jupyter"
Info 2021-11-02 17:02:17: Process Execution: > ~/.pyenv/versions/3.9.5/bin/python3.9 -c "import jupyter"
> ~/.pyenv/versions/3.9.5/bin/python3.9 -c "import jupyter"
Info 2021-11-02 17:02:17: Process Execution: > ~/.pyenv/versions/3.9.5/bin/python3.9 -c "import notebook"
> ~/.pyenv/versions/3.9.5/bin/python3.9 -c "import notebook"
Info 2021-11-02 17:02:17: Process Execution: > ~/.pyenv/versions/3.9.5/bin/python3.9 -c "import notebook"
> ~/.pyenv/versions/3.9.5/bin/python3.9 -c "import notebook"
Info 2021-11-02 17:02:28: Creating server with settings : {"baseUrl":"http://localhost:8000/","appUrl":"","wsUrl":"ws://localhost:8000/","token":"","init":{"cache":"no-store","credentials":"same-origin","headers":{"Cookie":"_xsrf=2|bc7d5f6b|14273c5d4626e7971040c83f14403dbb|1635897748; username-localhost-8000=\"2|1:0|10:1635897748|23:username-localhost-8000|44:YWI2NTRjY2YwMzhkNGExNDhlNTlhNGU1OWIxNzAxOGE=|f0b6e76f4fef81c679a4b8cae526e873b3e0b19124ae7d2bd0ca8276ab23792f\"; expires=Fri, 03 Dec 2021 00:02:28 GMT; HttpOnly; Path=/","X-XSRFToken":"2|bc7d5f6b|14273c5d4626e7971040c83f14403dbb|1635897748"}}}
Info 2021-11-02 17:02:28: Disposing session manager
Info 2021-11-02 17:02:28: SessionManager - dispose contents manager
Info 2021-11-02 17:02:28: ShutdownSessionAndConnection - dispose session manager
Info 2021-11-02 17:02:28: Finished disposing jupyter session manager
Info 2021-11-02 17:02:28: Find preferred kernel for undefined with metadata {} & preferred interpreter {}
Info 2021-11-02 17:02:28: findPreferredKernel score for early-stopping-ne is -1
Info 2021-11-02 17:02:28: findPreferredKernel score for early-stopping-ne is -1
Info 2021-11-02 17:02:28: findPreferredKernel score for speclanguage=python, ai-allocation is -1
Info 2021-11-02 17:02:28: findPreferredKernel score for ai-allocation is 1
Info 2021-11-02 17:02:28: findPreferredKernel score for speclanguage=python, ai-to-def is -1
Info 2021-11-02 17:02:28: findPreferredKernel score for ai-to-def is 1
Info 2021-11-02 17:02:28: findPreferredKernel score for speclanguage=python, baseline-roi is -1
Info 2021-11-02 17:02:28: findPreferredKernel score for baseline-roi is 1
Info 2021-11-02 17:02:28: findPreferredKernel score for speclanguage=python, feature-return is -1
Info 2021-11-02 17:02:28: findPreferredKernel score for feature-return is 1
Info 2021-11-02 17:02:28: findPreferredKernel score for speclanguage=python, kcam is -1
Info 2021-11-02 17:02:28: findPreferredKernel score for kcam is 1
Info 2021-11-02 17:02:28: findPreferredKernel score for speclanguage=python, raf-study is -1
Info 2021-11-02 17:02:28: findPreferredKernel score for raf-study is 1
Info 2021-11-02 17:02:28: findPreferredKernel score for speclanguage=python, sparse-importance is -1
Info 2021-11-02 17:02:28: findPreferredKernel score for sparse-importance is 1
Info 2021-11-02 17:02:28: findPreferredKernel score for speclanguage=python, train-v-serve-cost is -1
Info 2021-11-02 17:02:28: findPreferredKernel score for train-v-serve-cost is 1
Info 2021-11-02 17:02:28: findPreferredKernel score for speclanguage=python, training-return is -1
Info 2021-11-02 17:02:28: findPreferredKernel score for training-return is 1
Info 2021-11-02 17:02:28: findPreferredKernel score for speclanguage=python, feature-importance-over-time is -1
Info 2021-11-02 17:02:28: findPreferredKernel score for feature-importance-over-time is 1
Info 2021-11-02 17:02:28: findPreferredKernel score for speclanguage=python, baseline-v0-roi is -1
Info 2021-11-02 17:02:28: findPreferredKernel score for baseline-v0-roi is 1
Info 2021-11-02 17:02:28: findPreferredKernel score for speclanguage=python, ai-demand is -1
Info 2021-11-02 17:02:28: findPreferredKernel score for ai-demand is 1
Info 2021-11-02 17:02:28: findPreferredKernel score for speclanguage=python, feature-proposals-2021-h2 is -1
Info 2021-11-02 17:02:28: findPreferredKernel score for feature-proposals-2021-h2 is 1
Info 2021-11-02 17:02:28: findPreferredKernel score for speclanguage=python, embedding-roi is -1
Info 2021-11-02 17:02:28: findPreferredKernel score for embedding-roi is 1
Info 2021-11-02 17:02:28: findPreferredKernel score for speclanguage=python, ai-cpu-demand is -1
Info 2021-11-02 17:02:28: findPreferredKernel score for ai-cpu-demand is 1
Info 2021-11-02 17:02:28: findPreferredKernel score for speclanguage=python, time-series-demand is -1
Info 2021-11-02 17:02:28: findPreferredKernel score for time-series-demand is 1
Info 2021-11-02 17:02:28: findPreferredKernel score for speclanguage=python, feature-baselines-2021-h2 is -1
Info 2021-11-02 17:02:28: findPreferredKernel score for feature-baselines-2021-h2 is 1
Info 2021-11-02 17:02:28: findPreferredKernel score for speclanguage=python, early-stopping-ne is -1
Info 2021-11-02 17:02:28: findPreferredKernel score for early-stopping-ne is 1
Info 2021-11-02 17:02:28: findPreferredKernel score for speclanguage=python, adlogger-clawback is -1
Info 2021-11-02 17:02:28: findPreferredKernel score for adlogger-clawback is 1
Info 2021-11-02 17:02:28: findPreferredKernel score for speclanguage=python, Python 3 (ipykernel) is -1
Info 2021-11-02 17:02:28: findPreferredKernel score for Python 3 (ipykernel) is 1
Info 2021-11-02 17:02:28: Find remote kernel spec, Class name = y, completed in 13519ms, has a truthy return value, Arg 1: undefined, Arg 2: {"type":"jupyter","baseUrl":"http://localhost:8000/","token":"null","hostName":"localhost","localLaunch":false,"valid":true,"displayName":"http://localhost:8000/?token=null","rootDirectory":"","url":"http://localhost:8000/"}, Arg 3: undefined, Arg 4: <argument cannot be serialized for logging>, Return Value: {"kind":"startUsingKernelSpec","kernelSpec":{"name":"ai-allocation","argv":["/home/pawlu/.cache/pypoetry/virtualenvs/ai-allocation-y0lOGhSm-py3.8/bin/python","-m","ipykernel_launcher","-f","{connection_file}"],"language":"python","path":"/home/pawlu/.cache/pypoetry/virtualenvs/ai-allocation-y0lOGhSm-py3.8/bin/python","display_name":"ai-allocation","metadata":{},"env":{}},"id":".ai-allocation./home/pawlu/.cache/pypoetry/virtualenvs/ai-allocation-y0lOGhSm-py3.8/python..-m#ipykernel_launcher"}
Info 2021-11-02 17:02:28: Connecting to process for history server
Info 2021-11-02 17:02:28: Connecting server c1300479-f3b3-4a6d-a8c7-28c688bf2d18 kernelSpec ai-allocation
Connecting to Jupyter server at http://localhost:8000/
Info 2021-11-02 17:02:28: Creating server with settings : {"baseUrl":"http://localhost:8000/","appUrl":"","wsUrl":"ws://localhost:8000/","token":"","init":{"cache":"no-store","credentials":"same-origin","headers":{"Cookie":"_xsrf=2|bc7d5f6b|14273c5d4626e7971040c83f14403dbb|1635897748; username-localhost-8000=\"2|1:0|10:1635897748|23:username-localhost-8000|44:YWI2NTRjY2YwMzhkNGExNDhlNTlhNGU1OWIxNzAxOGE=|f0b6e76f4fef81c679a4b8cae526e873b3e0b19124ae7d2bd0ca8276ab23792f\"; expires=Fri, 03 Dec 2021 00:02:28 GMT; HttpOnly; Path=/","X-XSRFToken":"2|bc7d5f6b|14273c5d4626e7971040c83f14403dbb|1635897748"}}}
Info 2021-11-02 17:02:29: Starting a new session for kernel id = .ai-allocation./home/pawlu/.cache/pypoetry/virtualenvs/ai-allocation-y0lOGhSm-py3.8/python..-m#ipykernel_launcher, name = ai-allocation
Error 2021-11-02 17:02:30: Failed to change kernel, re-throwing _ [Error]: 
    at new o (/Users/pawlu/.vscode/extensions/ms-toolsai.jupyter-2021.9.1101343141/out/client/extension.js:16:44235)
    at new _ (/Users/pawlu/.vscode/extensions/ms-toolsai.jupyter-2021.9.1101343141/out/client/extension.js:32:15254)
    at /Users/pawlu/.vscode/extensions/ms-toolsai.jupyter-2021.9.1101343141/out/client/extension.js:52:996429
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

Error: Invalid response: 500 Internal Server Error
    at /Users/pawlu/.vscode/extensions/ms-toolsai.jupyter-2021.9.1101343141/out/client/node_modules/@jupyterlab/services.js:3:589118
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at t.SessionManager.startNew (/Users/pawlu/.vscode/extensions/ms-toolsai.jupyter-2021.9.1101343141/out/client/node_modules/@jupyterlab/services.js:3:580642) {
  category: 'unknown',
  originalException: t [Error]: Invalid response: 500 Internal Server Error
      at /Users/pawlu/.vscode/extensions/ms-toolsai.jupyter-2021.9.1101343141/out/client/node_modules/@jupyterlab/services.js:3:589118
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at t.SessionManager.startNew (/Users/pawlu/.vscode/extensions/ms-toolsai.jupyter-2021.9.1101343141/out/client/node_modules/@jupyterlab/services.js:3:580642) {
    response: R [Response] {
      size: 0,
      timeout: 0,
      [Symbol(Body internals)]: [Object],
      [Symbol(Response internals)]: [Object]
    },
    vslsStack: [ CallSite {}, CallSite {}, CallSite {} ]
  }
}
Info 2021-11-02 17:02:30: Shutdown session -- complete
Error 2021-11-02 17:02:30: Failed to connect to server _ [Error]: 
    at new o (/Users/pawlu/.vscode/extensions/ms-toolsai.jupyter-2021.9.1101343141/out/client/extension.js:16:44235)
    at new _ (/Users/pawlu/.vscode/extensions/ms-toolsai.jupyter-2021.9.1101343141/out/client/extension.js:32:15254)
    at /Users/pawlu/.vscode/extensions/ms-toolsai.jupyter-2021.9.1101343141/out/client/extension.js:52:996429
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

Error: Invalid response: 500 Internal Server Error
    at /Users/pawlu/.vscode/extensions/ms-toolsai.jupyter-2021.9.1101343141/out/client/node_modules/@jupyterlab/services.js:3:589118
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at t.SessionManager.startNew (/Users/pawlu/.vscode/extensions/ms-toolsai.jupyter-2021.9.1101343141/out/client/node_modules/@jupyterlab/services.js:3:580642) {
  category: 'unknown',
  originalException: t [Error]: Invalid response: 500 Internal Server Error
      at /Users/pawlu/.vscode/extensions/ms-toolsai.jupyter-2021.9.1101343141/out/client/node_modules/@jupyterlab/services.js:3:589118
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at t.SessionManager.startNew (/Users/pawlu/.vscode/extensions/ms-toolsai.jupyter-2021.9.1101343141/out/client/node_modules/@jupyterlab/services.js:3:580642) {
    response: R [Response] {
      size: 0,
      timeout: 0,
      [Symbol(Body internals)]: [Object],
      [Symbol(Response internals)]: [Object]
    },
    vslsStack: [ CallSite {}, CallSite {}, CallSite {} ]
  }
}
Info 2021-11-02 17:02:30: Killing server because of error Error: Invalid response: 500 Internal Server Error
Info 2021-11-02 17:02:30: Disposing HostJupyterServer
Info 2021-11-02 17:02:30: Shutting down notebooks for c1300479-f3b3-4a6d-a8c7-28c688bf2d18
Info 2021-11-02 17:02:30: Shut down session manager : existing
Info 2021-11-02 17:02:30: Disposing session manager
Info 2021-11-02 17:02:30: SessionManager - dispose contents manager
Info 2021-11-02 17:02:30: ShutdownSessionAndConnection - dispose session manager
Info 2021-11-02 17:02:30: Finished disposing jupyter session manager
Info 2021-11-02 17:02:30: Shutdown server - dispose conn info
Info 2021-11-02 17:02:30: Finished disposing HostJupyterServer
Error 2021-11-02 17:02:30: Error loading notebook controllers _ [Error]: 
    at new o (/Users/pawlu/.vscode/extensions/ms-toolsai.jupyter-2021.9.1101343141/out/client/extension.js:16:44235)
    at new _ (/Users/pawlu/.vscode/extensions/ms-toolsai.jupyter-2021.9.1101343141/out/client/extension.js:32:15254)
    at /Users/pawlu/.vscode/extensions/ms-toolsai.jupyter-2021.9.1101343141/out/client/extension.js:52:996429
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

Error: Invalid response: 500 Internal Server Error
    at /Users/pawlu/.vscode/extensions/ms-toolsai.jupyter-2021.9.1101343141/out/client/node_modules/@jupyterlab/services.js:3:589118
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at t.SessionManager.startNew (/Users/pawlu/.vscode/extensions/ms-toolsai.jupyter-2021.9.1101343141/out/client/node_modules/@jupyterlab/services.js:3:580642) {
  category: 'unknown',
  originalException: t [Error]: Invalid response: 500 Internal Server Error
      at /Users/pawlu/.vscode/extensions/ms-toolsai.jupyter-2021.9.1101343141/out/client/node_modules/@jupyterlab/services.js:3:589118
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at t.SessionManager.startNew (/Users/pawlu/.vscode/extensions/ms-toolsai.jupyter-2021.9.1101343141/out/client/node_modules/@jupyterlab/services.js:3:580642) {
    response: R [Response] {
      size: 0,
      timeout: 0,
      [Symbol(Body internals)]: [Object],
      [Symbol(Response internals)]: [Object]
    },
    vslsStack: [ CallSite {}, CallSite {}, CallSite {} ]
  }
}
Error 2021-11-02 17:02:30: Failed to find & set preferred controllers _ [Error]: 
    at new o (/Users/pawlu/.vscode/extensions/ms-toolsai.jupyter-2021.9.1101343141/out/client/extension.js:16:44235)
    at new _ (/Users/pawlu/.vscode/extensions/ms-toolsai.jupyter-2021.9.1101343141/out/client/extension.js:32:15254)
    at /Users/pawlu/.vscode/extensions/ms-toolsai.jupyter-2021.9.1101343141/out/client/extension.js:52:996429
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

Error: Invalid response: 500 Internal Server Error
    at /Users/pawlu/.vscode/extensions/ms-toolsai.jupyter-2021.9.1101343141/out/client/node_modules/@jupyterlab/services.js:3:589118
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at t.SessionManager.startNew (/Users/pawlu/.vscode/extensions/ms-toolsai.jupyter-2021.9.1101343141/out/client/node_modules/@jupyterlab/services.js:3:580642) {
  category: 'unknown',
  originalException: t [Error]: Invalid response: 500 Internal Server Error
      at /Users/pawlu/.vscode/extensions/ms-toolsai.jupyter-2021.9.1101343141/out/client/node_modules/@jupyterlab/services.js:3:589118
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at t.SessionManager.startNew (/Users/pawlu/.vscode/extensions/ms-toolsai.jupyter-2021.9.1101343141/out/client/node_modules/@jupyterlab/services.js:3:580642) {
    response: R [Response] {
      size: 0,
      timeout: 0,
      [Symbol(Body internals)]: [Object],
      [Symbol(Response internals)]: [Object]
    },
    vslsStack: [ CallSite {}, CallSite {}, CallSite {} ]
  }
}
```

</p>
</details>

**Comment by rchiodo** [comment]
Thanks for the issue. How did you start your jupyter server? It should have some output like so:

```
[C 08:49:22.431 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/aku91/AppData/Roaming/jupyter/runtime/nbserver-11240-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=38ae5762572ada077f81c5a62eacae662594aecbec62c7d9
     or http://127.0.0.1:8888/?token=38ae5762572ada077f81c5a62eacae662594aecbec62c7d9
```
The browser may be caching the token, but we still need it to connect.

**Comment by paw-lu** [comment]
Thanks for the follow up @rchiodo—appreciated!

You are right that the browser is caching some auth. When I log in via another browser, I am asked for a password prompt:

<img width="395" alt="Screen Shot 2021-11-03 at 1 58 47 PM" src="https://user-images.githubusercontent.com/30049606/140191787-410a90a7-eb9f-4368-a650-c97513024cdc.png">


I mentioned it above in the original issue—but I also get a password prompt on VS Code (step 7 above).


For your original question—started via:

```
% jupyter lab --no-browser --port=PORT
[I 2021-11-03 13:57:09.448 ServerApp] Jupyter Server 1.9.0 is running at:
[I 2021-11-03 13:57:09.448 ServerApp] http://localhost:PORT/lab
[I 2021-11-03 13:57:09.448 ServerApp]  or http://127.0.0.1:PORT/lab
```

In this case PORT is then forwarded to 8000 like in the example in the original issue.

**Comment by rchiodo** [comment]
Does the password work in the browser but not inside of VS code?

**Comment by paw-lu** [comment]
Password does work in browser. It does not seem to work in VS Code.

I get a prompt in VS Code. When I fill out the prompt nothing happens, I get no confirmation or feedback, and trying to run cell gives blank kernel selection reported above.

**Comment by rchiodo** [comment]
Feedback would likely be on the command line where you started jupyter lab. It might show that we passed the wrong password

**Comment by rchiodo** [comment]
Oh wait you said it was port forwarding to 8000? So jupyter lab is not actually on the localhost. I wonder if our password detection logic isn't working. 

Internally we try to connect to the ```url/tree```. That may not be appropriate anymore with newer versions of jupyter.
https://github.com/microsoft/vscode-jupyter/blob/bd63750c91e6e23dacdfb99c24d88086e0d1acd4/src/client/datascience/jupyter/jupyterPasswordConnect.ts#L221

**Comment by paw-lu** [comment]
> It might show that we passed the wrong password

I'll give this a shot, but pretty sure (due to multiple attempts) that I'm passing the correct password here.

> Oh wait you said it was port forwarding to 8000?

eh used the wrong terminology (sorry!), technically it's tunneled. As seen in screenshot below, Jupyter Lab is still accessed in the browser via `localhost`

> Internally we try to connect to the url/tree.

Trying to connect to `localhost:8000/tree` seems to work out

<img width="407" alt="Screen Shot 2021-11-03 at 2 57 57 PM" src="https://user-images.githubusercontent.com/30049606/140198920-2432a5d2-0604-4f33-895f-9f7b9a6003c5.png">

**Comment by paw-lu** [comment]
> Feedback would likely be on the command line where you started jupyter lab.

You're right!

<details>
<summary>Logs</summary>

```log
[W 2021-11-03 15:02:40.823 ServerApp] 404 GET /hub/api (::1) 2.07ms referer=None
[I 2021-11-03 15:02:41.088 NotebookApp] 302 GET /tree? (::1) 0.85ms
[I 2021-11-03 15:03:02.192 ServerApp] 302 POST /login? (::1) 3.19ms
[I 2021-11-03 15:03:03.076 ServerApp] Creating new notebook in /
[I 2021-11-03 15:03:03.077 ServerApp] Loading Jupytext configuration file at /home/pawlu/.config/jupytext/jupytext.toml
[I 2021-11-03 15:03:03.084 ServerApp] Loading Jupytext configuration file at /home/pawlu/.config/jupytext/jupytext.toml
[I 2021-11-03 15:03:03.088 ServerApp] Saving Untitled.ipynb
[I 2021-11-03 15:03:03.448 ServerApp] Saving Untitled.py in format py:percent
[E 2021-11-03 15:03:04.032 ServerApp] Failed to run command:
    ['/home/pawlu/.cache/pypoetry/virtualenvs/ai-allocation-y0lOGhSm-py3.8/bin/python', '-m', 'ipykernel_launcher', '-f', '/home/pawlu/.local/share/jupyter/runtime/kernel-b762c7af-713b-42fc-97ac-ee7b9e7313b3.json']
        PATH={PATH_REMOVED}
        with kwargs:
    {'stdin': -1, 'stdout': None, 'stderr': None, 'cwd': '/data/users/pawlu/Documents', 'start_new_session': True}

[E 2021-11-03 15:03:04.033 ServerApp] Uncaught exception POST /api/sessions?1635976983652 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8000', method='POST', uri='/api/sessions?1635976983652', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/pawlu/.local/pipx/venvs/jupyterlab/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/home/pawlu/.local/pipx/venvs/jupyterlab/lib/python3.9/site-packages/jupyter_server/services/sessions/handlers.py", line 67, in post
        model = await sm.create_session(
      File "/home/pawlu/.local/pipx/venvs/jupyterlab/lib/python3.9/site-packages/jupyter_server/services/sessions/sessionmanager.py", line 91, in create_session
        kernel_id = await self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "/home/pawlu/.local/pipx/venvs/jupyterlab/lib/python3.9/site-packages/jupyter_server/services/sessions/sessionmanager.py", line 99, in start_kernel_for_session
        kernel_id = await self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "/home/pawlu/.local/pipx/venvs/jupyterlab/lib/python3.9/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 187, in start_kernel
        kernel_id = await ensure_async(self.pinned_superclass.start_kernel(self, **kwargs))
      File "/home/pawlu/.local/pipx/venvs/jupyterlab/lib/python3.9/site-packages/jupyter_server/utils.py", line 178, in ensure_async
        result = await obj
      File "/home/pawlu/.local/pipx/venvs/jupyterlab/lib/python3.9/site-packages/jupyter_client/multikernelmanager.py", line 483, in start_kernel
        await fut
      File "/home/pawlu/.local/pipx/venvs/jupyterlab/lib/python3.9/site-packages/jupyter_client/multikernelmanager.py", line 460, in _add_kernel_when_ready
        await kernel_awaitable
      File "/home/pawlu/.local/pipx/venvs/jupyterlab/lib/python3.9/site-packages/jupyter_client/manager.py", line 661, in start_kernel
        self.kernel = await self._launch_kernel(kernel_cmd, **kw)
      File "/home/pawlu/.local/pipx/venvs/jupyterlab/lib/python3.9/site-packages/jupyter_client/manager.py", line 642, in _launch_kernel
        res = launch_kernel(kernel_cmd, **kw)
      File "/home/pawlu/.local/pipx/venvs/jupyterlab/lib/python3.9/site-packages/jupyter_client/launcher.py", line 132, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "/home/pawlu/.pyenv/versions/3.9.5/lib/python3.9/subprocess.py", line 951, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/home/pawlu/.pyenv/versions/3.9.5/lib/python3.9/subprocess.py", line 1821, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: '/home/pawlu/.cache/pypoetry/virtualenvs/ai-allocation-y0lOGhSm-py3.8/bin/python'
[W 2021-11-03 15:03:04.044 ServerApp] Unhandled error
[E 2021-11-03 15:03:04.045 ServerApp] {
      "Cookie": "_xsrf=2|0f41ff0e|e13659a6eb585a5c9cc7c1742c0448f7|1635976981; username-localhost-8000=\"2|1:0|10:1635976982|23:username-localhost-8000|44:MDQwMTc0ZWNiMDg4NDliZTg2YzdkM2U4YzhkMjRhOGE=|0822dd683e4d9932cd8622ebbe3ec562079acae2c7cdc74c745026df84643051\"; expires=Fri, 03 Dec 2021 22:03:02 GMT; HttpOnly; Path=/",
      "X-Xsrftoken": "2|0f41ff0e|e13659a6eb585a5c9cc7c1742c0448f7|1635976981",
      "Content-Type": "text/plain;charset=UTF-8",
      "Accept": "*/*",
      "Content-Length": "159",
      "User-Agent": "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)",
      "Accept-Encoding": "gzip,deflate",
      "Connection": "close",
      "Host": "localhost:8000"
    }
[E 2021-11-03 15:03:04.045 ServerApp] 500 POST /api/sessions?1635976983652 (::1) 26.10ms referer=None
[W 2021-11-03 15:03:04.310 ServerApp] delete /default-e2e8d32a-fff5-4441-a3ed-d1a732f37d18.ipynb
[E 2021-11-03 15:03:04.314 ServerApp] Uncaught exception DELETE /api/contents/default-e2e8d32a-fff5-4441-a3ed-d1a732f37d18.ipynb?1635976983961 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8000', method='DELETE', uri='/api/contents/default-e2e8d32a-fff5-4441-a3ed-d1a732f37d18.ipynb?1635976983961', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/pawlu/.local/pipx/venvs/jupyterlab/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/home/pawlu/.local/pipx/venvs/jupyterlab/lib/python3.9/site-packages/jupyter_server/services/contents/handlers.py", line 229, in delete
        await ensure_async(cm.delete(path))
      File "/home/pawlu/.local/pipx/venvs/jupyterlab/lib/python3.9/site-packages/jupyter_server/services/contents/manager.py", line 284, in delete
        self.delete_file(path)
      File "/home/pawlu/.local/pipx/venvs/jupyterlab/lib/python3.9/site-packages/jupyter_server/services/contents/filemanager.py", line 498, in delete_file
        send2trash(os_path)
      File "/home/pawlu/.local/pipx/venvs/jupyterlab/lib/python3.9/site-packages/send2trash/plat_other.py", line 211, in send2trash
        trash_move(path_b, dest_trash, topdir)
      File "/home/pawlu/.local/pipx/venvs/jupyterlab/lib/python3.9/site-packages/send2trash/plat_other.py", line 116, in trash_move
        os.rename(src, op.join(filespath, destname))
    OSError: [Errno 18] Invalid cross-device link: b'/data/users/pawlu/Documents/default-e2e8d32a-fff5-4441-a3ed-d1a732f37d18.ipynb' -> b'/home/pawlu/.local/share/Trash/files/default-e2e8d32a-fff5-4441-a3ed-d1a732f37d18.ipynb'
[W 2021-11-03 15:03:04.320 ServerApp] Unhandled error
[E 2021-11-03 15:03:04.321 ServerApp] {
      "Cookie": "_xsrf=2|0f41ff0e|e13659a6eb585a5c9cc7c1742c0448f7|1635976981; username-localhost-8000=\"2|1:0|10:1635976982|23:username-localhost-8000|44:MDQwMTc0ZWNiMDg4NDliZTg2YzdkM2U4YzhkMjRhOGE=|0822dd683e4d9932cd8622ebbe3ec562079acae2c7cdc74c745026df84643051\"; expires=Fri, 03 Dec 2021 22:03:02 GMT; HttpOnly; Path=/",
      "X-Xsrftoken": "2|0f41ff0e|e13659a6eb585a5c9cc7c1742c0448f7|1635976981",
      "Accept": "*/*",
      "User-Agent": "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)",
      "Accept-Encoding": "gzip,deflate",
      "Connection": "close",
      "Host": "localhost:8000"
    }
[E 2021-11-03 15:03:04.321 ServerApp] 500 DELETE /api/contents/default-e2e8d32a-fff5-4441-a3ed-d1a732f37d18.ipynb?1635976983961 (::1) 12.40ms referer=None
```


</details>

**Comment by rchiodo** [comment]
@paw-lu are you still having this issue? Sorry we never noticed your reply.

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
