### ISSUE TITLE
remote jupyter kernel dies suddenly and have to restart vscode to recover it

### ISSUE THREAD

**Issue by Qiuzhuang** [microsoft/vscode-jupyter#8212]
Error 2021-11-09 10:56:35: DataScience Error Error: Kernel is dead
    at f._sendKernelShellControl (/Users/lian/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001312534/out/client/node_modules/@jupyterlab/services.js:3:431671)
    at f.sendShellMessage (/Users/lian/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001312534/out/client/node_modules/@jupyterlab/services.js:3:431440)
    at f.requestExecute (/Users/lian/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001312534/out/client/node_modules/@jupyterlab/services.js:3:433992)
    at _.requestExecute (/Users/lian/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001312534/out/client/extension.js:32:19215)
    at w.executeCodeCell (/Users/lian/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001312534/out/client/extension.js:52:300924)
    at w.execute (/Users/lian/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001312534/out/client/extension.js:52:300551)
    at w.start (/Users/lian/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001312534/out/client/extension.js:52:296215)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at t.CellExecutionQueue.executeQueuedCells (/Users/lian/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001312534/out/client/extension.js:52:310950)
    at t.CellExecutionQueue.start (/Users/lian/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001312534/out/client/extension.js:52:310490)

1.62.0-insider version with extensions:
jupyter: v2021.9.1001312534
pylance: v2021.11.0
python: v2021.10.1365161279

**Comment by rchiodo** [comment]
Thanks for the bug. Can you include the rest of your log? It's likely some code that you ran caused the kernel to crash.

**Comment by Qiuzhuang** [comment]
Here is the log that happens today again:

Info 2021-11-10 10:20:34: Experimentation service retrieved: [object Object]
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
> /usr/bin/python3 -c "import jupyter"
> /usr/bin/python3 -c "import jupyter"
> /usr/bin/python3 -c "import notebook"
> /usr/bin/python3 -c "import notebook"
> /usr/bin/python3 -m jupyter kernelspec --version
> /usr/bin/python3 -m jupyter kernelspec --version
Connecting to Jupyter server at http://ids:8888/
http://ids:8888/: Kernel started: 22a0f141-9f12-4caa-8e2e-22d3f2557ec0
> /usr/bin/python3 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> /usr/bin/python3 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> /usr/bin/python3 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> /usr/bin/python3 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> /usr/bin/python3 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> /usr/bin/python3 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
http://ids:8888/: Kernel started: 7a60e84a-bb35-4b81-89d7-50ffe0558f70
http://ids:8888/: Creating new notebook 
Error 2021-11-10 10:27:51: SessionManager:getKernelSpecs failure:  Error: Poll (@jupyterlab/services:SessionManager#specs) is disposed.
    at o.dispose (/Users/lian/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001312534/out/client/node_modules/@jupyterlab/services.js:3:107551)
    at t.SessionManager.dispose (/Users/lian/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001312534/out/client/node_modules/@jupyterlab/services.js:3:580355)
    at m.dispose (/Users/lian/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001312534/out/client/extension.js:52:986674)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at y.listKernels (/Users/lian/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001312534/out/client/extension.js:90:252288)
    at M.updateRemoteConnections (/Users/lian/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001312534/out/client/extension.js:54:355205)
    at M.onDidOpenNotebookDocument (/Users/lian/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001312534/out/client/extension.js:54:352464)
Error 2021-11-10 10:27:51: Failed to find & set preferred controllers FetchError: request to http://ids:8888/api/kernels?1636511271873 failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/Users/lian/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001312534/out/client/extension.js:16:254546)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:469:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Error 2021-11-10 10:33:21: DataScience Error Error: Kernel is dead
    at f._sendKernelShellControl (/Users/lian/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001312534/out/client/node_modules/@jupyterlab/services.js:3:431671)
    at f.sendShellMessage (/Users/lian/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001312534/out/client/node_modules/@jupyterlab/services.js:3:431440)
    at f.requestExecute (/Users/lian/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001312534/out/client/node_modules/@jupyterlab/services.js:3:433992)
    at _.requestExecute (/Users/lian/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001312534/out/client/extension.js:32:19215)
    at w.executeCodeCell (/Users/lian/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001312534/out/client/extension.js:52:300924)
    at w.execute (/Users/lian/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001312534/out/client/extension.js:52:300551)
    at w.start (/Users/lian/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001312534/out/client/extension.js:52:296215)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at t.CellExecutionQueue.executeQueuedCells (/Users/lian/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001312534/out/client/extension.js:52:310950)
    at t.CellExecutionQueue.start (/Users/lian/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001312534/out/client/extension.js:52:310490)


Notice that I just enable jupyter logging as warn level.

**Comment by rchiodo** [comment]
Your jupyter extension version is rather old. Can you upgrade and try again?

That should also change the logging level to 'debug' (it's our new default). Which hopefully will give us a lot more information. Your current log is just showing the session being destroyed, but not what is causing it.

**Comment by Qiuzhuang** [comment]
updated to newest version fixed this. Thanks.

**Comment by rchiodo** [comment]
Thanks for verifying.
