### ISSUE TITLE
Launching Tensorboard through VS code produces: from grpc._cython import cygrpc as _cygrpc ImportError

### ISSUE THREAD

**Issue by natephysics** [microsoft/vscode-jupyter#8231]
When I run the Python: Launch Tensorboard command in VS code I get an error:
from grpc._cython import cygrpc as _cygrpc 
ImportError

Tensorboard works fine if I run it directly from the terminal and open it in the browser. There is something specific about running it through VS code using the Python: Launch Tensorboard command that breaks it. 

Additional information: I have 2 windows 10 Pro systems (19043.1266 vs 19043.1288), both running the same version of VS code, conda, the python VS code extension, using the same virtual environment, and the other system doesn't have this issue. It's unclear to me why.  It is possible the settings in VS code are different between the two systems. 

## Environment data

-   VS Code version: 1.16.2
-   Extension version (available under the Extensions sidebar): v2021.10.1365161279
-   OS and version: Windows 10 Pro, 19043.1266
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.3, conda 4.8.3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda  (see attached)
-   Relevant/affected Python packages and their versions: tensorboard 2.6.0, tensorboard-data-server 0.6.0, tensorboard-plugin-wit 1.8.0
-   Relevant/affected Python-related VS Code extensions and their versions: N/A
-   Value of the `python.languageServer` setting: Pylance

## Expected behaviour

When running Python: Launch Tensorboard, a Tensorboard browser window should be available in VS code.

## Steps to reproduce:

In VS code, run Python: Launch Tensorboard 

I wasn't able to reproduce this issue on my laptop despite being a near clone of the desktop software environment. 

## Attempts to test/resolve issue:
I've tried the following:
-   Reinstalled Anaconda with Anaconda3-2021.05-Windows-x86_64
-   Reinstalled Anaconda with Anaconda3-2020.07-Windows-x86_64 (because this was the same version that was working without issue on my laptop)
-   Reinstalled the VS code python extension 
-   Reinstalled VS code
-   Used the base environment instead of the conda environment I normally use. 

## Attached
Env file:
[enviroment.yaml.txt](https://github.com/microsoft/vscode-python/files/7461350/enviroment.yaml.txt)
executable)"

## Logs

User belongs to experiment group 'pythonaa'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'pythonDeprecatePythonPath'
User belongs to experiment group 'pythonRunFailedTestsButtonDisplayed'
User belongs to experiment group 'pythonRefreshTestsButtonDisplayed'
User belongs to experiment group 'pythonRememberDebugConfig'
> conda info --json
> ~\anaconda3\python.exe ~\.vscode\extensions\ms-python.python-2021.10.1365161279\pythonFiles\interpreterInfo.py
> ~\anaconda3\envs\pytorch\python.exe -c "import sys;print(sys.executable)"
> ~\anaconda3\Scripts\conda.exe info --json
> ~\anaconda3\envs\pytorch\python.exe -c "import sys;print(sys.executable)"
Starting Pylance language server.
> ~\anaconda3\envs\pytorch\python.exe -c "import sys;print(sys.
Error 2021-11-02 14:25:18: Diagnostic Code: InvalidPythonInterpreterDiagnostic, Message: No Python interpreter is selected. You need to select a Python interpreter to enable features such as IntelliSense, linting, and debugging.
Diagnostic Code: InvalidPythonInterpreterDiagnostic, Message: No Python interpreter is selected. You need to select a Python interpreter to enable features such as IntelliSense, linting, and debugging.
> ~\anaconda3\envs\pytorch\python.exe -c "import sys;print(sys.executable)"
> ~\anaconda3\envs\pytorch\python.exe -c "import sys;print(sys.executable)"
> ~\anaconda3\envs\pytorch\python.exe -c "import sys;print(sys.executable)"
> ~\anaconda3\envs\pytorch\python.exe -c "import sys;print(sys.executable)"
> ~\anaconda3\envs\pytorch\python.exe -c "import sys;print(sys.executable)"
> ~\anaconda3\Scripts\conda.exe info --json
> ~\anaconda3\envs\pytorch\python.exe ~\.vscode\extensions\ms-python.python-2021.10.1365161279\pythonFiles\interpreterInfo.py
> "~\anaconda3\Scripts\activate && conda activate pytorch && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\natep\.vscode\extensions\ms-python.python-2021.10.1365161279\pythonFiles\printEnvVariables.py"
> "~\anaconda3\Scripts\activate && conda activate pytorch && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\natep\.vscode\extensions\ms-python.python-2021.10.1365161279\pythonFiles\printEnvVariables.py"
> ~\anaconda3\envs\pytorch\python.exe -c "import torch_tb_profiler; print(torch_tb_profiler.__version__)"
> ~\anaconda3\envs\pytorch\python.exe -c "import tensorboard; print(tensorboard.__version__)"
> ~\anaconda3\envs\pytorch\python.exe ~\.vscode\extensions\ms-python.python-2021.10.1365161279\pythonFiles\tensorboard_launcher.py outputs
Error 2021-11-02 14:31:11: Traceback (most recent call last):
  File "c:\Users\natep\.vscode\extensions\ms-python.python-2021.10.1365161279\pythonFiles\tensorboard_launcher.py", line 36, in <module>

Error 2021-11-02 14:31:11:     main(logdir)
  File "c:\Users\natep\.vscode\extensions\ms-python.python-2021.10.1365161279\pythonFiles\tensorboard_launcher.py", line 17, in main
    tb = program.TensorBoard()
  File "C:\Users\natep\anaconda3\envs\pytorch\lib\site-packages\tensorboard\lazy.py", line 65, in __getattr__
    return getattr(load_once(self), attr_name)
  File "C:\Users\natep\anaconda3\envs\pytorch\lib\site-packages\tensorboard\lazy.py", line 97, in wrapper

Error 2021-11-02 14:31:11:     cache[arg] = f(arg)
  File "C:\Users\natep\anaconda3\envs\pytorch\lib\site-packages\tensorboard\lazy.py", line 50, in load_once

Error 2021-11-02 14:31:11:     module = load_fn()
  File "C:\Users\natep\anaconda3\envs\pytorch\lib\site-packages\tensorboard\__init__.py", line 99, in program

Error 2021-11-02 14:31:11:     return importlib.import_module("tensorboard.program")
  File "C:\Users\natep\anaconda3\envs\pytorch\lib\importlib\__init__.py", line 127, in import_module

Error 2021-11-02 14:31:11:     return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import

Error 2021-11-02 14:31:11:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load

Error 2021-11-02 14:31:11:   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked

Error 2021-11-02 14:31:11:   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked

Error 2021-11-02 14:31:11:   File "<frozen importlib._bootstrap_external>", line 783, in exec_module

Error 2021-11-02 14:31:11:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

Error 2021-11-02 14:31:11:   File "C:\Users\natep\anaconda3\envs\pytorch\lib\site-packages\tensorboard\program.py", line 52, in <module>

Error 2021-11-02 14:31:11:     from tensorboard.backend import application
  File "C:\Users\natep\anaconda3\envs\pytorch\lib\site-packages\tensorboard\backend\application.py", line 44, in <module>

Error 2021-11-02 14:31:11:     from tensorboard.plugins.core import core_plugin
  File "C:\Users\natep\anaconda3\envs\pytorch\lib\site-packages\tensorboard\plugins\core\core_plugin.py", line 32, in <module>

Error 2021-11-02 14:31:11:     from tensorboard.util import grpc_util
  File "C:\Users\natep\anaconda3\envs\pytorch\lib\site-packages\tensorboard\util\grpc_util.py", line 24, in <module>

Error 2021-11-02 14:31:11:     import grpc
  File "C:\Users\natep\anaconda3\envs\pytorch\lib\site-packages\grpc\__init__.py", line 23, in <module>

Error 2021-11-02 14:31:11:     from grpc._cython import cygrpc as _cygrpc
  ImportError
Error 2021-11-02 14:31:11: : DLL load failed while importing cygrpc: The specified module could not be found.

**Comment by natephysics** [comment]
> This sounds like the problem here:
> 
> ```
>  DLL load failed while importing cygrpc: The specified module could not be found.
> ```
> 
> Sounds like some path for tensorboard is not being set correctly.

I agree with you but it's strange that Tensorboard was working fine from the terminal (even the vs code terminal) but errored out when loading from VS code. So it wasn't as simple as Tensorboard not working. I tried hashing this out for a while but got nowhere and had to move on. I rolled the computer back to a snapshot of the system before the error had occurred and resycned the code with the repository. Working fine now but I still have no clue what the source of the problem was.
