### ISSUE TITLE
Cannot open tensorboard by extension when conneting remote server

### ISSUE THREAD

**Issue by RickyYXY** [microsoft/vscode-jupyter#8232]
### VS Code version

1.62.1

### Extension version

v2021.11.1422169775

### OS type

Linux

### OS version

18.04

### Python distribution

Anaconda

### Python version

3.8.12

### Language server

Pylance

### Expected behaviour

When I click button above "from torch.utils.tensorboard import SummaryWriter", it should open tensorboard as usual.

### Actual behaviour

I don't know why it failed to open and give me an error message in the right-bottom corner:
Launch TensorBoard failed，Error: Command failed: . activate droidenv && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/yxy/.vscode-server/extensions/ms-python.python-2021.11.1422169775/pythonFiles/printEnvVariables.py 
bash: activate: No such file or directory
I haven't change any of my configuration in my server, it just suddenly happend........

### Steps to reproduce

just 
from torch.utils.tensorboard import SummaryWriter at a sever env and click open button for the session, I think

### Logs

Error 2021-11-10 16:05:43: getActivatedEnvironmentVariables, Class name = T, completed in 56ms, has a falsy return value, Arg 1: undefined, Arg 2: {"sysPrefix":"/home/yxy/.conda/envs/droidenv","envType":"Conda","envName":"droidenv","envPath":"/home/yxy/.conda/envs/droidenv","path":"/home/yxy/.conda/envs/droidenv/bin/python","architecture":3,"sysVersion":"3.8.12 | packaged by conda-forge | (default, Sep 29 2021, 19:52:28) \n[GCC 9.4.0]","version":{"raw":"3.8.12","major":3,"minor":8,"patch":12,"build":[],"prerelease":["final","0"]},"displayName":"Python 3.8.12 64-bit ('droidenv': conda)"}, Arg 3: true [Error: Command failed: . activate droidenv && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/yxy/.vscode-server/extensions/ms-python.python-2021.11.1422169775/pythonFiles/printEnvVariables.py
bash: activate: No such file or directory

	at ChildProcess.exithandler (child_process.js:308:12)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1048:16)
	at Socket.<anonymous> (internal/child_process.js:439:11)
	at Socket.emit (events.js:315:20)
	at Pipe.<anonymous> (net.js:673:12)] {
  killed: false,
  code: 1,
  signal: null,
  cmd: ". activate droidenv && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/yxy/.vscode-server/extensions/ms-python.python-2021.11.1422169775/pythonFiles/printEnvVariables.py"
}

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rchiodo** [comment]
@karthiknadig this sounds like a conda activation failure, not a tensorboard problem.
