### ISSUE TITLE
Unable to Launch Jupyter Notebook in Integrated Terminal and Then Connect

### ISSUE THREAD

**Issue by apockoffork** [microsoft/vscode-jupyter#8314]
## Environment data

Version: 1.62.3
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:00:36.721Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.0-90-generic

Jupyter Extension Version: 2021.10.1101450599
Python Extension Version: 2021.11.1422169775

Linux Ubuntu 18.04
Python Version: 3.6

I'm using a remote workspace with the SSH extension.

## Steps to reproduce:

1. Open or start a new python notebook.
2. Add a line such as `print(1)` to the first cell. 
3. Open integrated vscode terminal.
4. Start Jupyter with `jupyter notebook`
5. Run `select local or remote Jupyter server for connections`
6. Enter the url for the Jupyter server (In my case I have a token configured)
7. Asked to reload. Reload the window.
8. When the window reloads the notebook is the active tab.
9. The jupyter process running in the terminal was stopped when I reloaded. 
10. Select the integrated terminal and restart jupyter with `jupyter notebook`. 
11. Select the first cell in the notebook and run it.
12. Prompted to select a kernel. Doesn't detect the currently running server.
13. Redo the `select local or remote Jupyter server for connections` and reselect my running server.
14. Prompted to reload

and so on.

If a notebook is the tab that's open when I reload vscode and I want to run the server from the integrated terminal I get stuck in  a loop where it never connects to the server.

If I have vscode open to a non-notebook (blank for example) tab when I reload, then start the server in the terminal, then switch to the notebook it correctly connects. 

I should be able to load vscode. Start my server in the terminal and then start interacting with my notebook.

## Logs

```
Info 2021-11-19 09:59:35: Experimentation service retrieved: [object Object]
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'jupyterEnhancedDataViewer'
Info 2021-11-19 09:59:36: Checking for server existence.
Info 2021-11-19 09:59:36: Checking for server usability.
Info 2021-11-19 09:59:36: Starting notebook server.
Info 2021-11-19 09:59:36: Connecting to history server
Info 2021-11-19 09:59:36: Creating jupyter server: 5c533fbf-6673-4bc9-97fe-3b9ccef0bc63
Info 2021-11-19 09:59:36: Creating server with settings : {"baseUrl":"http://localhost:8888/","appUrl":"","wsUrl":"ws://localhost:8888/","token":"123456","appendToken":true,"init":{"cache":"no-store","credentials":"same-origin"}}
Info 2021-11-19 09:59:36: Disposing session manager
Info 2021-11-19 09:59:36: SessionManager - dispose contents manager
Info 2021-11-19 09:59:36: ShutdownSessionAndConnection - dispose session manager
Info 2021-11-19 09:59:36: Finished disposing jupyter session manager
Error 2021-11-19 09:59:36: findKernel crashed [FetchError: request to http://localhost:8888/api/kernels?1637333976353 failed, reason: connect ECONNREFUSED 127.0.0.1:8888
	at ClientRequest.<anonymous> (/home/dferguson/.vscode-server/extensions/ms-toolsai.jupyter-2021.10.1101450599/out/client/extension.js:16:335949)
	at ClientRequest.emit (events.js:315:20)
	at Socket.socketErrorListener (_http_client.js:469:9)
	at Socket.emit (events.js:315:20)
	at emitErrorNT (internal/streams/destroy.js:106:8)
	at emitErrorCloseNT (internal/streams/destroy.js:74:3)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)]
Info 2021-11-19 09:59:36: Find remote kernel spec, Class name = y, completed in 54ms, has a falsy return value, Arg 1: undefined, Arg 2: {"type":"jupyter","baseUrl":"http://localhost:8888/","token":"123456","hostName":"localhost","localLaunch":false,"valid":true,"displayName":"http://localhost:8888/?token=123456","rootDirectory":"","url":"http://localhost:8888/?token=123456"}, Arg 3: undefined, Arg 4: <argument cannot be serialized for logging>, Return Value: undefined
Info 2021-11-19 09:59:36: Connecting to process for history server
Info 2021-11-19 09:59:36: Connecting server 5c533fbf-6673-4bc9-97fe-3b9ccef0bc63 kernelSpec unknown
Connecting to Jupyter server at http://localhost:8888/
Info 2021-11-19 09:59:36: Creating server with settings : {"baseUrl":"http://localhost:8888/","appUrl":"","wsUrl":"ws://localhost:8888/","token":"123456","appendToken":true,"init":{"cache":"no-store","credentials":"same-origin"}}
Error 2021-11-19 09:59:36: Backing file not supported: TypeError: request to http://localhost:8888/api/contents?1637333976373 failed, reason: connect ECONNREFUSED 127.0.0.1:8888
Info 2021-11-19 09:59:36: Starting a new session for kernel id = undefined, name = 
Error 2021-11-19 09:59:36: SessionManager cannot enumerate kernelspecs. Returning default {}.
Info 2021-11-19 09:59:36: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
Error 2021-11-19 09:59:36: Failed to change kernel, re-throwing [_ [Error]: 
	at new o (/home/dferguson/.vscode-server/extensions/ms-toolsai.jupyter-2021.10.1101450599/out/client/extension.js:16:45317)
	at new _ (/home/dferguson/.vscode-server/extensions/ms-toolsai.jupyter-2021.10.1101450599/out/client/extension.js:46:16466)
	at /home/dferguson/.vscode-server/extensions/ms-toolsai.jupyter-2021.10.1101450599/out/client/extension.js:66:1005724
	at processTicksAndRejections (internal/process/task_queues.js:93:5)

FetchError: request to http://localhost:8888/api/sessions?1637333976398 failed, reason: connect ECONNREFUSED 127.0.0.1:8888
	at ClientRequest.<anonymous> (/home/dferguson/.vscode-server/extensions/ms-toolsai.jupyter-2021.10.1101450599/out/client/extension.js:16:335949)
	at ClientRequest.emit (events.js:315:20)
	at Socket.socketErrorListener (_http_client.js:469:9)
	at Socket.emit (events.js:315:20)
	at emitErrorNT (internal/streams/destroy.js:106:8)
	at emitErrorCloseNT (internal/streams/destroy.js:74:3)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)] {
  category: 'unknown',
  originalException: [FetchError: request to http://localhost:8888/api/sessions?1637333976398 failed, reason: connect ECONNREFUSED 127.0.0.1:8888
  	at ClientRequest.<anonymous> (/home/dferguson/.vscode-server/extensions/ms-toolsai.jupyter-2021.10.1101450599/out/client/extension.js:16:335949)
  	at ClientRequest.emit (events.js:315:20)
  	at Socket.socketErrorListener (_http_client.js:469:9)
  	at Socket.emit (events.js:315:20)
  	at emitErrorNT (internal/streams/destroy.js:106:8)
  	at emitErrorCloseNT (internal/streams/destroy.js:74:3)
  	at processTicksAndRejections (internal/process/task_queues.js:80:21)]
}
Info 2021-11-19 09:59:36: Shutdown session -- complete
Error 2021-11-19 09:59:36: Failed to connect to server [_ [Error]: 
	at new o (/home/dferguson/.vscode-server/extensions/ms-toolsai.jupyter-2021.10.1101450599/out/client/extension.js:16:45317)
	at new _ (/home/dferguson/.vscode-server/extensions/ms-toolsai.jupyter-2021.10.1101450599/out/client/extension.js:46:16466)
	at /home/dferguson/.vscode-server/extensions/ms-toolsai.jupyter-2021.10.1101450599/out/client/extension.js:66:1005724
	at processTicksAndRejections (internal/process/task_queues.js:93:5)

FetchError: request to http://localhost:8888/api/sessions?1637333976398 failed, reason: connect ECONNREFUSED 127.0.0.1:8888
	at ClientRequest.<anonymous> (/home/dferguson/.vscode-server/extensions/ms-toolsai.jupyter-2021.10.1101450599/out/client/extension.js:16:335949)
	at ClientRequest.emit (events.js:315:20)
	at Socket.socketErrorListener (_http_client.js:469:9)
	at Socket.emit (events.js:315:20)
	at emitErrorNT (internal/streams/destroy.js:106:8)
	at emitErrorCloseNT (internal/streams/destroy.js:74:3)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)] {
  category: 'unknown',
  originalException: [FetchError: request to http://localhost:8888/api/sessions?1637333976398 failed, reason: connect ECONNREFUSED 127.0.0.1:8888
  	at ClientRequest.<anonymous> (/home/dferguson/.vscode-server/extensions/ms-toolsai.jupyter-2021.10.1101450599/out/client/extension.js:16:335949)
  	at ClientRequest.emit (events.js:315:20)
  	at Socket.socketErrorListener (_http_client.js:469:9)
  	at Socket.emit (events.js:315:20)
  	at emitErrorNT (internal/streams/destroy.js:106:8)
  	at emitErrorCloseNT (internal/streams/destroy.js:74:3)
  	at processTicksAndRejections (internal/process/task_queues.js:80:21)]
}
Info 2021-11-19 09:59:36: Killing server because of error Error: request to http://localhost:8888/api/sessions?1637333976398 failed, reason: connect ECONNREFUSED 127.0.0.1:8888
Info 2021-11-19 09:59:36: Disposing HostJupyterServer
Info 2021-11-19 09:59:36: Shutting down notebooks for 5c533fbf-6673-4bc9-97fe-3b9ccef0bc63
Info 2021-11-19 09:59:36: Shut down session manager : existing
Info 2021-11-19 09:59:36: Disposing session manager
Info 2021-11-19 09:59:36: SessionManager - dispose contents manager
Info 2021-11-19 09:59:36: ShutdownSessionAndConnection - dispose session manager
Info 2021-11-19 09:59:36: Finished disposing jupyter session manager
Info 2021-11-19 09:59:36: Shutdown server - dispose conn info
Info 2021-11-19 09:59:36: Finished disposing HostJupyterServer
Error 2021-11-19 09:59:36: Error loading notebook controllers [_ [Error]: 
	at new o (/home/dferguson/.vscode-server/extensions/ms-toolsai.jupyter-2021.10.1101450599/out/client/extension.js:16:45317)
	at new _ (/home/dferguson/.vscode-server/extensions/ms-toolsai.jupyter-2021.10.1101450599/out/client/extension.js:46:16466)
	at /home/dferguson/.vscode-server/extensions/ms-toolsai.jupyter-2021.10.1101450599/out/client/extension.js:66:1005724
	at processTicksAndRejections (internal/process/task_queues.js:93:5)

FetchError: request to http://localhost:8888/api/sessions?1637333976398 failed, reason: connect ECONNREFUSED 127.0.0.1:8888
	at ClientRequest.<anonymous> (/home/dferguson/.vscode-server/extensions/ms-toolsai.jupyter-2021.10.1101450599/out/client/extension.js:16:335949)
	at ClientRequest.emit (events.js:315:20)
	at Socket.socketErrorListener (_http_client.js:469:9)
	at Socket.emit (events.js:315:20)
	at emitErrorNT (internal/streams/destroy.js:106:8)
	at emitErrorCloseNT (internal/streams/destroy.js:74:3)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)] {
  category: 'unknown',
  originalException: [FetchError: request to http://localhost:8888/api/sessions?1637333976398 failed, reason: connect ECONNREFUSED 127.0.0.1:8888
  	at ClientRequest.<anonymous> (/home/dferguson/.vscode-server/extensions/ms-toolsai.jupyter-2021.10.1101450599/out/client/extension.js:16:335949)
  	at ClientRequest.emit (events.js:315:20)
  	at Socket.socketErrorListener (_http_client.js:469:9)
  	at Socket.emit (events.js:315:20)
  	at emitErrorNT (internal/streams/destroy.js:106:8)
  	at emitErrorCloseNT (internal/streams/destroy.js:74:3)
  	at processTicksAndRejections (internal/process/task_queues.js:80:21)]
}
Error 2021-11-19 09:59:36: Failed to find & set preferred controllers [_ [Error]: 
	at new o (/home/dferguson/.vscode-server/extensions/ms-toolsai.jupyter-2021.10.1101450599/out/client/extension.js:16:45317)
	at new _ (/home/dferguson/.vscode-server/extensions/ms-toolsai.jupyter-2021.10.1101450599/out/client/extension.js:46:16466)
	at /home/dferguson/.vscode-server/extensions/ms-toolsai.jupyter-2021.10.1101450599/out/client/extension.js:66:1005724
	at processTicksAndRejections (internal/process/task_queues.js:93:5)

FetchError: request to http://localhost:8888/api/sessions?1637333976398 failed, reason: connect ECONNREFUSED 127.0.0.1:8888
	at ClientRequest.<anonymous> (/home/dferguson/.vscode-server/extensions/ms-toolsai.jupyter-2021.10.1101450599/out/client/extension.js:16:335949)
	at ClientRequest.emit (events.js:315:20)
	at Socket.socketErrorListener (_http_client.js:469:9)
	at Socket.emit (events.js:315:20)
	at emitErrorNT (internal/streams/destroy.js:106:8)
	at emitErrorCloseNT (internal/streams/destroy.js:74:3)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)] {
  category: 'unknown',
  originalException: [FetchError: request to http://localhost:8888/api/sessions?1637333976398 failed, reason: connect ECONNREFUSED 127.0.0.1:8888
  	at ClientRequest.<anonymous> (/home/dferguson/.vscode-server/extensions/ms-toolsai.jupyter-2021.10.1101450599/out/client/extension.js:16:335949)
  	at ClientRequest.emit (events.js:315:20)
  	at Socket.socketErrorListener (_http_client.js:469:9)
  	at Socket.emit (events.js:315:20)
  	at emitErrorNT (internal/streams/destroy.js:106:8)
  	at emitErrorCloseNT (internal/streams/destroy.js:74:3)
  	at processTicksAndRejections (internal/process/task_queues.js:80:21)]
}
Info 2021-11-19 09:59:36: Process Execution: > /usr/bin/python -c "import jupyter"
> /usr/bin/python -c "import jupyter"
Info 2021-11-19 09:59:36: Process Execution: > /usr/bin/python -c "import jupyter"
> /usr/bin/python -c "import jupyter"
Info 2021-11-19 09:59:36: Process Execution: > /usr/bin/python -c "import notebook"
> /usr/bin/python -c "import notebook"
Info 2021-11-19 09:59:36: Process Execution: > /usr/bin/python -c "import notebook"
> /usr/bin/python -c "import notebook"
Info 2021-11-19 09:59:37: Process Execution: > /usr/bin/python -m jupyter kernelspec --version
> /usr/bin/python -m jupyter kernelspec --version
Info 2021-11-19 09:59:37: Process Execution: > /usr/bin/python -m jupyter kernelspec --version
> /usr/bin/python -m jupyter kernelspec --version
Info 2021-11-19 09:59:37: Registering dummy command feature
```

**Comment by DonJayamanne** [comment]
Thanks for filling this issue.
Please could you start the Jupyter server in a terminal outside vscode.
When you start it in a terminal in vacode and release vscode, then that's killed.

Also not the option to enter a Jupyter server url is for remote servers, for local you don't need to start Jupyter you're self. 

Let me know if that works.

**Comment by apockoffork** [comment]
I can definitely start the server in a separate terminal and everything will work.

I'm using a remote development setup where vscode is connecting to my remote machine over ssh. It's much more convenient to launch my jupyter server from within the integrated terminal as it automatically connects and sets up the remote machine. The server is a "remote" server as it is running on the remote machine.

If this is just a workflow that the jupyter extension team isn't planning to support that's fine. More than anything the general behavior is confusing. If I load vscode and then start the server and then hover over the jupyter server connection indicator in the status bar the bottom of the screen it shows the url of the server I'm starting in my terminal but I can't get it to re-establish a connection (Or establish an initial connection) if I have navigated to the notebook tab before I start the server.

**Comment by DonJayamanne** [comment]
Thanks for the clarification and I'm sorry this workflow doesn't have the best experience right now .

The only alternatives I have is to not start Jupyter and let vscode start it for you in the background (ir go back to local server, change to `Default`, you can then look at the logs and find them uri of Jupyter that was started and try to connect to that.

Unfortunately this scenario isn't supported right no.
Closing this in favor of https://github.com/microsoft/vscode-jupyter/issues/1367
