### ISSUE TITLE
Fix tensor board tests for python 3.10

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-jupyter#8470]
```
  1) TensorBoard session creation
       If python.tensorBoard.logDirectory is provided, do not prompt user to pick a log directory:
     Error: Timeout of 25000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/vscode-python/vscode-python/path with spaces/out/test/tensorBoard/tensorBoardSession.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  2) TensorBoard session creation
       Core functionality
         Golden path: TensorBoard session starts successfully and webview is shown:
     Error: Timeout of 25000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/vscode-python/vscode-python/path with spaces/out/test/tensorBoard/tensorBoardSession.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  3) TensorBoard session creation
       Core functionality
         When webview is closed, session is killed:
     Error: Timeout of 25000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/vscode-python/vscode-python/path with spaces/out/test/tensorBoard/tensorBoardSession.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  4) TensorBoard session creation
       Installation prompt message
         Install profiler only
           In experiment: true, has torch imports: true, is profiler package installed: false, TensorBoard installed:
     Error: Timeout of 25000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/vscode-python/vscode-python/path with spaces/out/test/tensorBoard/tensorBoardSession.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  5) TensorBoard session creation
       Installation prompt message
         No prompt
           In experiment: false, has torch imports: false, is profiler package installed: true, TensorBoard installed:
     Error: Timeout of 25000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/vscode-python/vscode-python/path with spaces/out/test/tensorBoard/tensorBoardSession.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  6) TensorBoard session creation
       Installation prompt message
         No prompt
           In experiment: false, has torch imports: false, is profiler package installed: false, TensorBoard installed:
     Error: Timeout of 25000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/vscode-python/vscode-python/path with spaces/out/test/tensorBoard/tensorBoardSession.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  7) TensorBoard session creation
       Installation prompt message
         No prompt
           In experiment: false, has torch imports: false, is profiler package installed: false, TensorBoard installed:
     Error: Timeout of 25000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/vscode-python/vscode-python/path with spaces/out/test/tensorBoard/tensorBoardSession.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  8) TensorBoard session creation
       Installation prompt message
         No prompt
           In experiment: false, has torch imports: true, is profiler package installed: true, TensorBoard installed:
     Error: Timeout of 25000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/vscode-python/vscode-python/path with spaces/out/test/tensorBoard/tensorBoardSession.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  9) TensorBoard session creation
       Installation prompt message
         No prompt
           In experiment: false, has torch imports: true, is profiler package installed: false, TensorBoard installed:
     Error: Timeout of 25000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/vscode-python/vscode-python/path with spaces/out/test/tensorBoard/tensorBoardSession.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  10) TensorBoard session creation
       Installation prompt message
         No prompt
           In experiment: false, has torch imports: true, is profiler package installed: false, TensorBoard installed:
     Error: Timeout of 25000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/vscode-python/vscode-python/path with spaces/out/test/tensorBoard/tensorBoardSession.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  11) TensorBoard session creation
       Installation prompt message
         No prompt
           In experiment: true, has torch imports: false, is profiler package installed: true, TensorBoard installed:
     Error: Timeout of 25000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/vscode-python/vscode-python/path with spaces/out/test/tensorBoard/tensorBoardSession.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  12) TensorBoard session creation
       Installation prompt message
         No prompt
           In experiment: true, has torch imports: false, is profiler package installed: false, TensorBoard installed:
     Error: Timeout of 25000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/vscode-python/vscode-python/path with spaces/out/test/tensorBoard/tensorBoardSession.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  13) TensorBoard session creation
       Installation prompt message
         No prompt
           In experiment: true, has torch imports: false, is profiler package installed: false, TensorBoard installed:
     Error: Timeout of 25000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/vscode-python/vscode-python/path with spaces/out/test/tensorBoard/tensorBoardSession.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  14) TensorBoard session creation
       Installation prompt message
         No prompt
           In experiment: true, has torch imports: true, is profiler package installed: true, TensorBoard installed:
     Error: Timeout of 25000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/vscode-python/vscode-python/path with spaces/out/test/tensorBoard/tensorBoardSession.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  15) TensorBoard session creation
       Error messages
         If installing the profiler package fails, do not show error, continue to create session:
     Error: Timeout of 25000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/vscode-python/vscode-python/path with spaces/out/test/tensorBoard/tensorBoardSession.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  16) TensorBoard session creation
       Error messages
         If user opts not to install profiler package and tensorboard is already installed, continue to create session:
     Error: Timeout of 25000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/vscode-python/vscode-python/path with spaces/out/test/tensorBoard/tensorBoardSession.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  17) TensorBoard session creation
       Jump to source
         Resolves filepaths without displaying prompt:
     Error: Timeout of 25000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/vscode-python/vscode-python/path with spaces/out/test/tensorBoard/tensorBoardSession.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  18) TensorBoard session creation
       Jump to source
         Display quickpick to user if filepath is not on disk:
     Error: Timeout of 25000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/vscode-python/vscode-python/path with spaces/out/test/tensorBoard/tensorBoardSession.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```

**Comment by DonJayamanne** [comment]
Upstream issue has been resolved
