### ISSUE TITLE
jupyter won't work on vs-code 

### ISSUE THREAD

**Issue by aquaresima** [microsoft/vscode-jupyter#8532]
## Environment data

-   VS Code version: 1.62.00
-   Jupyter Extension version (available under the Extensions sidebar): 2021.9.100 (6 October 2021)
-   Python Extension version (available under the Extensions sidebar): 3.9
-   OS (Windows | Mac | Linux distro) and version: Linux Arch
-   Python and/or Anaconda version: v2021.12.1559732655
-   Type of virtual environment used: virtualenv
-   Jupyter server running: Local

## Expected behaviour
Running a jupyter server

## Actual behaviour
The extension does not load. Whichever action fails.
It works if I run `$ code --enable-proposed-api ms-toolsai.jupyter ` (as it is suggested in the error)

##Logs

```
console.ts:137 [Extension Host] extension activation failed Error: [ms-toolsai.jupyter]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api ms-toolsai.jupyter
    at S (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:81081)
    at w (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:81028)
    at Object.onDidChangeCellMetadata (/usr/lib/code/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:41477)
    at u.addEventHandlers (/home/cocconat/.vscode-oss/extensions/ms-toolsai.jupyter-2021.10.100/out/client/extension.js:52:570428)
    at new u (/home/cocconat/.vscode-oss/extensions/ms-toolsai.jupyter-2021.10.100/out/client/extension.js:52:569096)
    at Object.t.resolveInstance (/home/cocconat/.vscode-oss/extensions/ms-toolsai.jupyter-2021.10.100/out/client/extension.js:52:269067)
    at /home/cocconat/.vscode-oss/extensions/ms-toolsai.jupyter-2021.10.100/out/client/extension.js:52:268272
    at Array.map (<anonymous>)
    at Object.t.resolveInstance (/home/cocconat/.vscode-oss/extensions/ms-toolsai.jupyter-2021.10.100/out/client/extension.js:52:268837)
    at /home/cocconat/.vscode-oss/extensions/ms-toolsai.jupyter-2021.10.100/out/client/extension.js:52:268272
    at /home/cocconat/.vscode-oss/extensions/ms-toolsai.jupyter-2021.10.100/out/client/extension.js:52:267220
    at Array.map (<anonymous>)
    at /home/cocconat/.vscode-oss/extensions/ms-toolsai.jupyter-2021.10.100/out/client/extension.js:52:267192
    at Array.map (<anonymous>)
    at Object.t.resolveInstance (/home/cocconat/.vscode-oss/extensions/ms-toolsai.jupyter-2021.10.100/out/client/extension.js:52:268837)
    at /home/cocconat/.vscode-oss/extensions/ms-toolsai.jupyter-2021.10.100/out/client/extension.js:52:268272
    at Object.t.resolve (/home/cocconat/.vscode-oss/extensions/ms-toolsai.jupyter-2021.10.100/out/client/extension.js:52:268535)
    at /home/cocconat/.vscode-oss/extensions/ms-toolsai.jupyter-2021.10.100/out/client/extension.js:52:259632
    at e._get (/home/cocconat/.vscode-oss/extensions/ms-toolsai.jupyter-2021.10.100/out/client/extension.js:52:259398)
    at e.get (/home/cocconat/.vscode-oss/extensions/ms-toolsai.jupyter-2021.10.100/out/client/extension.js:52:258110)
    at a.get (/home/cocconat/.vscode-oss/extensions/ms-toolsai.jupyter-2021.10.100/out/client/extension.js:90:383850)
    at /home/cocconat/.vscode-oss/extensions/ms-toolsai.jupyter-2021.10.100/out/client/extension.js:52:246955
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /home/cocconat/.vscode-oss/extensions/ms-toolsai.jupyter-2021.10.100/out/client/extension.js:37:734295
    at t.activate (/home/cocconat/.vscode-oss/extensions/ms-toolsai.jupyter-2021.10.100/out/client/extension.js:37:733982)
    at async Promise.all (index 1)
log.ts:301   ERR [Extension Host] (node:77851) DeprecationWarning: uuidv4() is deprecated. Use v4() from the uuid module i`nstead.
console.ts:137 [Extension Host] (node:77851) DeprecationWarning: uuidv4() is deprecated. Use v4() from the uuid module instead.
```

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, looks like you are using OSS, when using OSS, you must pass the argument. when using a pre-built version of VS Code, things should work as expected.
