### ISSUE TITLE
Error: NO notebook document for 'vscode-interactive:Interactive-2.interactive'

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#8599]
```
Error: NO notebook document for 'vscode-interactive:Interactive-2.interactive'
/vs/workbench/api/common/extHostNotebook.ts#136:18
/vs/workbench/api/common/extHostNotebookKernels.ts#260:25
/vs/workbench/services/extensions/common/rpcProtocol.ts#472:16
/vs/workbench/services/extensions/common/rpcProtocol.ts#457:31
/vs/workbench/services/extensions/common/rpcProtocol.ts#373:18
/vs/workbench/services/extensions/common/rpcProtocol.ts#295:9
at /out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:8910 
/vs/base/common/event.ts#611:15
/vs/base/parts/ipc/common/ipc.net.ts#636:4
at /out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:34332 
/vs/base/common/event.ts#611:15
/vs/base/parts/ipc/common/ipc.net.ts#636:4
/vs/base/parts/ipc/common/ipc.net.ts#956:34
at /out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:21011 
/vs/base/common/event.ts#611:15
/vs/base/parts/ipc/common/ipc.net.ts#380:17
at /out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:14857 
/vs/base/parts/ipc/node/ipc.net.ts#60:3
at Socket.emit (events.js
at addChunk (internal/streams/readable.js:309:12) 
at readableAddChunk (internal/streams/readable.js:284:9) 
at Socket.Readable.push (internal/streams/readable.js:223:10) 
at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

Error from telemetry. I ran into this as well sometimes when opening a second IW.

**Comment by DonJayamanne** [comment]
Here are some of my findings:
* We don't have smoke tests for IW
* Some how the stable version of Jupyter is in the smoke tests
	* Stable version is some how (for some reason) launching IW, hence we see errors


**We might want to re-write the smoke tests (or do we even need them anymore)**
* In the past we added this because we weren't using webpack, and some files would get excluded accidentally, and things would fall over (now that webpack will pull all dependencies things should work)
* Also smoke tests are a bit weird, basically we start the extenion with all extenssion code deleted
	* Build the VSIX
	* Install the VSIX
	* Then delete all of the extension code so that the tests will not use the compiled code, but will use the VSIX installed into VS Code... (yes sounds compilcated)
	* We couild have a separate smoke test - install VSIX and write a seprate extesnion to test the extension (that extensino doesn't have any Jupyter code, easier to manage & understand what's going on)
	* I.e. this new extension can be the driver for the tests (that's what we try to do today)

**Comment by DonJayamanne** [comment]
Note: These are messages on the CI server (in our tests). Seems to be in smoke tests.

**Comment by rchiodo** [comment]
I believe we get these on CI too:

Here's an example from running on main:
```
2022-01-18T19:11:43.0559375Z 5447 Info 19:11:43: Setting setActiveController for vscode-interactive:Interactive-1.interactive
2022-01-18T19:11:43.0564113Z _performCellEdits [{"resource":{"$mid":1,"fsPath":"Interactive-1.interactive","external":"vscode-interactive:Interactive-1.interactive","path":"Interactive-1.interactive","scheme":"vscode-interactive"},"cellEdit":{"editType":5,"metadata":{"custom":{"metadata":{"language_info":{"name":"python","version":"3.10.1"},"kernelspec":{"name":"python3","language":"python","display_name":"Python 3.10.1 64-bit"},"interpreter":{"hash":"cb97df56ba86fb780e352b12b1dae0f9fbf99e248012bb1503a21d208b7c5a8b"}}}}}}]
2022-01-18T19:11:43.0565067Z 
2022-01-18T19:11:43.0570619Z NO notebook document for 'vscode-interactive:Interactive-1.interactive': Error: NO notebook document for 'vscode-interactive:Interactive-1.interactive'
2022-01-18T19:11:43.0572123Z     at F.getNotebookDocument (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:141335)
2022-01-18T19:11:43.0573506Z     at u.$acceptNotebookAssociation (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:155874)
2022-01-18T19:11:43.0578016Z     at i._doInvokeHandler (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:13800)
2022-01-18T19:11:43.0580093Z     at i._invokeHandler (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:13484)
2022-01-18T19:11:43.0581225Z     at i._receiveRequest (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:12146)
2022-01-18T19:11:43.0582379Z     at i._receiveOneMessage (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:10824)
2022-01-18T19:11:43.0583459Z     at /home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:8933
2022-01-18T19:11:43.0584534Z     at l.fire (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
2022-01-18T19:11:43.0585604Z     at r.fire (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:18969)
2022-01-18T19:11:43.0586667Z     at /home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:34378
2022-01-18T19:11:43.0587732Z     at l.fire (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
2022-01-18T19:11:43.0588787Z     at r.fire (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:18969)
2022-01-18T19:11:43.0590068Z     at s._receiveMessage (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:23550)
2022-01-18T19:11:43.0591208Z     at /home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:21084
2022-01-18T19:11:43.0592268Z     at l.fire (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
2022-01-18T19:11:43.0593365Z     at E.acceptChunk (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:15800)
2022-01-18T19:11:43.0594432Z     at /home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:14930
2022-01-18T19:11:43.0595498Z     at Socket.b (/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/VSCode-linux-x64/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:13833)
2022-01-18T19:11:43.0596045Z     at Socket.emit (events.js:315:20)
2022-01-18T19:11:43.0596375Z     at addChunk (internal/streams/readable.js:309:12)
2022-01-18T19:11:43.0596750Z     at readableAddChunk (internal/streams/readable.js:284:9)
2022-01-18T19:11:43.0597153Z     at Socket.Readable.push (internal/streams/readable.js:223:10)
2022-01-18T19:11:43.0597556Z     at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
2022-01-18T19:11:43.0597752Z 
```

**Comment by rchiodo** [comment]
I believe this is an issue in core. We might be changing the selected notebook to nothing and it doesn't handle it.
