### ISSUE TITLE
Debugging can fail if in the middle of execution.

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#8684]
Tests seem to randomly fail with an error like so:

```
3883 Error 00:54:22: Cell execution failed without request, for cell Index 1 Error: custom request failed
2022-01-13T00:54:22.6282630Z     at vscode-file://vscode-app/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:1499:7618
2022-01-13T00:54:22.6283553Z     at runMicrotasks (<anonymous>)
2022-01-13T00:54:22.6284102Z     at processTicksAndRejections (internal/process/task_queues.js:93:5)
2022-01-13T00:54:22.6284981Z 3883 Warn 00:54:22: Cell completed with errors Error: custom request failed
2022-01-13T00:54:22.6286048Z     at vscode-file://vscode-app/home/runner/work/vscode-jupyter/vscode-jupyter/.vscode-test/vscode-linux-x64-insiders/VSCode-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:1499:7618
2022-01-13T00:54:22.6286999Z     at runMicrotasks (<anonymous>)
2022-01-13T00:54:22.6287543Z     at processTicksAndRejections (internal/process/task_queues.js:93:5)
2022-01-13T00:54:22.6288440Z 3883 Info 00:54:22: Cell Index:1, state:3, exec: undefined. Completed with errors
```

This exception is thrown by VS code itself when trying to send a debug request. 

In the cases where this is happening, the kernel may be in the middle of executing a line of code. 

We might:
- Try this in a loop
- Not fail the cell execution (by try catching the debug request?)
-

**Comment by rchiodo** [comment]
It's also strange is that when this failure occurs, the IW thinks it's still debugging on tests after this point that aren't actually doing any debugging.

**Comment by rchiodo** [comment]
I believe the line in the IW that causes the failure is this one:
https://github.com/microsoft/vscode-jupyter/blob/c60dcfdc13062f69bccbed9df6dcde61086d1a23/src/client/datascience/jupyter/interactiveWindowDebugger.ts#L90
