### ISSUE TITLE
Flaky IW debugging tests

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#8719]
I've run into this 3 times in the past 2 days
https://pipelines.actions.githubusercontent.com/KyBlh4sBTj8eoTzBTvt0CAApvyyj3PXuc4Tbg2yHyMGda4Kk7D/_apis/pipelines/1/runs/27526/signedlogcontent/9?urlExpires=2022-01-17T23%3A26%3A17.7375333Z&urlSigningMethod=HMACV1&urlSignature=lupF5%2BNWehFnwkBDOgtEcSXTjR4wqZ5HvW29Idgy8jE%3D

```
2022-01-17T23:23:05.9460376Z   1) VSCode Notebook - Run By Line
2022-01-17T23:23:05.9461600Z        "before each" hook for "Does not stop in other cell":
2022-01-17T23:23:05.9462738Z      Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/vscode-jupyter/vscode-jupyter/out/test/datascience/debugger.vscode.test.js)
2022-01-17T23:23:05.9463335Z       at listOnTimeout (internal/timers.js:554:17)
2022-01-17T23:23:05.9463677Z       at processTimers (internal/timers.js:497:7)
2022-01-17T23:23:05.9463852Z 
2022-01-17T23:23:05.9464095Z   2) Interactive window debugging
2022-01-17T23:23:05.9464385Z        Debug a cell from a python file:
2022-01-17T23:23:05.9464928Z      Error: Invalid number of code lenses returned
2022-01-17T23:23:05.9465259Z       at Timeout.<anonymous> (src/test/common.ts:354:20)
2022-01-17T23:23:05.9465596Z       at listOnTimeout (internal/timers.js:554:17)
2022-01-17T23:23:05.9465932Z       at processTimers (internal/timers.js:497:7)
```

**Comment by amunger** [comment]
VSCode Notebook - Run By Line "before each" hook for "Does not stop in other cell": Error: Timeout of 120000ms exceeded.
https://github.com/microsoft/vscode-jupyter/runs/4833846419?check_suite_focus=true

**Comment by amunger** [comment]
should be fixed by added tear down to stop previous debug sessions
