### ISSUE TITLE
No play button on Jupyter cells for a remote file system

### ISSUE THREAD

**Issue by Sseziwa** [microsoft/vscode-jupyter#8841]
## Environment data

-   VS Code version: 1.63.2 (Universal)
-   Jupyter Extension version (available under the Extensions sidebar): v2021.11.1001550889
-   Python Extension version (available under the Extensions sidebar): v2021.12.1559732655
-   OS (Windows | Mac | Linux distro) and version: macOS 11.6.2
-   Python and/or Anaconda version: python 3.9.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Remote

## Expected behaviour

Buttons to execute cells in a Jupyter notebook are displayed

## Actual behaviour

Cells are displayed but there's no means of executing them

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. I've set up a SSH FS mount of a remote file system
2. Open a notebook in the remote file system
![Screen Recording 2022-01-28 at 4 09 41 PM](https://user-images.githubusercontent.com/18307555/151622487-8c6a966d-8ec2-43cb-9c52-33b3c67200d4.gif)

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Error 16:10:17: Failed to find & set preferred controllers [t [Error]: Invalid response: 404 Not Found
	at Function.create (/Users/smukasa/.vscode/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/node_modules/@jupyterlab/services.js:1:74644)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Object.t.listRunning (/Users/smukasa/.vscode/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/node_modules/@jupyterlab/services.js:15:8583)
	at async m.getRunningKernels (/Users/smukasa/.vscode/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:1234352)
	at async Promise.all (index 0)
	at async b.listKernels (/Users/smukasa/.vscode/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:104:289387)
	at async L.loadNotebookControllersImpl (/Users/smukasa/.vscode/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:1412470)
	at async Promise.all (index 1)] {
  response: A [Response] {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://localhost:8443/hub/smukasa/api/kernels?1643228797146',
      status: 404,
      statusText: 'Not Found',
      headers: [I [Headers]],
      counter: 1
    }
  },
  traceback: ''
}
```

</p>
</details>

**Comment by Sseziwa** [comment]
The URL for the remote server was incorrect (among some other issues), resolved now.
