### ISSUE TITLE
Kernel dies after interruption

### ISSUE THREAD

**Issue by grudloff** [microsoft/vscode-jupyter#8945]
## Environment data

-   VS Code version: 1.64.0 
-   Jupyter Extension version: v2022.1.1001775990
-   Python Extension version: v2022.0.1786462952
-   OS and version: Windows_NT x64 10.0.19043
-   Python and/or Anaconda version: Python 3.9.7 &  conda 4.10.3
-   Type of virtual environment used: Anaconda
-   Jupyter server running: Local

## Actual behaviour

If I interrupt a running cell the kernel dies.

## Logs

<details>

<p>

```
Info 12:16:25: Interrupt kernel execution
Info 12:16:25: Cancel pending cells
Info 12:16:25: Interrupting kernel: python396jvsc74a57bd0434ef728c16ae87739179d593b2a5ca7a96305c1d5164569cdfc0df7f6e276d2
Info 12:16:25: Interrupting kernel via Signals
Info 12:16:25: Cell 2 executed with state Idle
(...)
Info 12:16:25: Cell 46 executed with state Idle
Error 12:16:25: Disposing session as kernel process died ExitCode: 1, Reason: C:\Users\Usuario\.conda\envs\pytorch-gpu\lib\site-packages\traitlets\traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
C:\Users\Usuario\.conda\envs\pytorch-gpu\lib\site-packages\traitlets\traitlets.py:2157: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '8882db69-05a2-414a-8d0d-22b603cc4ebf' instead of 'b"8882db69-05a2-414a-8d0d-22b603cc4ebf"'.
  warn(

Info 12:16:25: Dispose Kernel process
Error 12:16:25: Raw kernel process exited code: 1
Error 12:16:25: Error in waiting for cell to complete [Error: Canceled future for execute_request message before replies were done
	at t.KernelShellFutureHandler.dispose (c:\Users\Usuario\.vscode\extensions\ms-toolsai.jupyter-2022.1.1001775990\out\client\extension.js:51:432353)
	at c:\Users\Usuario\.vscode\extensions\ms-toolsai.jupyter-2022.1.1001775990\out\client\extension.js:66:307599
	at Map.forEach (<anonymous>)
	at y._clearKernelState (c:\Users\Usuario\.vscode\extensions\ms-toolsai.jupyter-2022.1.1001775990\out\client\extension.js:66:307585)
	at y.dispose (c:\Users\Usuario\.vscode\extensions\ms-toolsai.jupyter-2022.1.1001775990\out\client\extension.js:66:301017)
	at c:\Users\Usuario\.vscode\extensions\ms-toolsai.jupyter-2022.1.1001775990\out\client\extension.js:51:194444
	at t.swallowExceptions (c:\Users\Usuario\.vscode\extensions\ms-toolsai.jupyter-2022.1.1001775990\out\client\extension.js:16:2495)
	at dispose (c:\Users\Usuario\.vscode\extensions\ms-toolsai.jupyter-2022.1.1001775990\out\client\extension.js:51:194423)
	at t.RawSession.dispose (c:\Users\Usuario\.vscode\extensions\ms-toolsai.jupyter-2022.1.1001775990\out\client\extension.js:113:303296)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)]
Info 12:16:25: Cancel all remaining cells true || Success
Info 12:16:25: Cancel pending cells
Info 12:16:25: Cell 0 executed with state Success
```

</p>
</details>

Seems to have something to do with traitlets? I guess downgrading to traitlets<5 would do the trick.

edit: typo

**Comment by grudloff** [comment]
Downgrading to the previous jupyter extension version did the trick.

**Comment by rchiodo** [comment]
I believe this was caused by the removal of the special code in the daemon to handle interrupting.

**Comment by Alvie** [comment]
@rchiodo  has this issue been fixed? I seem to be having the exact same issue as described here:

https://github.com/microsoft/vscode-jupyter/issues/8946

With the kernel dieing after installing CUDNN; some sort of problem with extra quotes in traitlets but I'm not sure

**Comment by rchiodo** [comment]
Yes this issue has been fixed. This issue was related to interrupting on windows. Can you open another issue?

**Comment by smeyanoff** [comment]
My solution was drop Anaconda and install Python by VS Code Instructions...
