### ISSUE TITLE
Jupyter doesn't see python kernels (normal and anaconda env)

### ISSUE THREAD

**Issue by adamsatyr** [microsoft/vscode-jupyter#8954]
## Environment data

-   VS Code version: Version: 1.64.0 (system setup)
-   Jupyter Extension version (available under the Extensions sidebar): v2022.1.1001775990
-   Python Extension version (available under the Extensions sidebar): v2022.0.1786462952
-   OS (Windows | Mac | Linux distro) and version: Windows_NT x64 10.0.19042
-   Python and/or Anaconda version: 3.9 and 3.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): ALL
-   Jupyter server running: Local

## Expected behaviour

Jupyter should find at least one environment and everything was working fine until it didn't. 

## Actual behaviour

No environment/kernels available/detected.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

UNKNOWN, just started to not work. I reinstalled and restarted almost everything, only didn't reinstall the whole system.
Started with numpy not having some libraries (with no changes to anything), I reinstalled Anaconda, restarted everything. Anaconda works in Poweshell and loads correctly. I tried every trick to reset and do it right. Nothing worked. 

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Only Jupyter:Variables is there. And empty.
```

</p>
</details>

**Comment by rchiodo** [comment]
Thanks for the issue. Jupyter output log can be found here:

![image](https://user-images.githubusercontent.com/19672699/153036731-ac20947f-9fd9-4336-9257-20405ffa5cf4.png)

Can you try posting the contents of that panel? It should show the results from us trying to find kernels.

**Comment by adamsatyr** [comment]
Ok, I found it. Edited into original post.

**Comment by rchiodo** [comment]
Can you include the python output as well? We ask the python extension for the list of interpreters on the machine. That output makes it look like the python extension didn't find any.

**Comment by adamsatyr** [comment]
Infinite stream of:
```
[ERROR 2022-1-8 19:40:23.137]: No python is installed or a refresh has not already been triggered
```
Well, seems like it is not jupyter problem...

**Comment by adamsatyr** [comment]
```
Experiment 'pythonaacf' is active
Experiment 'pythonTensorboardExperiment' is active
Experiment 'PythonPyTorchProfiler' is active
Experiment 'pythonDeprecatePythonPath' is active
[ERROR 2022-1-8 11:42:26.290]: [SyntaxError: Invalid regular expression: /c:(\\|/)Users(\\|/)[user_name](\\|/)[path](\\|/)[patch](\\|/)[patch]/: Range out of order in character class
	at new RegExp (<anonymous>)
	at h (c:\Users\[user_name]\.vscode\extensions\ms-python.python-2022.0.1786462952\out\client\extension.js:104:312461)
	at d.getDisplayCommands (c:\Users\[user_name]\.vscode\extensions\ms-python.python-2022.0.1786462952\out\client\extension.js:104:312240)
	at d.logProcess (c:\Users\[user_name]\.vscode\extensions\ms-python.python-2022.0.1786462952\out\client\extension.js:104:311978)
	at s.emit (events.js:315:20)
	at shellExec (c:\Users\[user_name]\.vscode\extensions\ms-python.python-2022.0.1786462952\out\client\extension.js:52:33373)
	at Object.t.shellExecute (c:\Users\[user_name]\.vscode\extensions\ms-python.python-2022.0.1786462952\out\client\extension.js:24:74106)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Object.t.getInterpreterInfo (c:\Users\[user_name]\.vscode\extensions\ms-python.python-2022.0.1786462952\out\client\extension.js:104:31827)
	at async c.p [as workerFunc] (c:\Users\[user_name]\.vscode\extensions\ms-python.python-2022.0.1786462952\out\client\extension.js:52:5037)
	at async start (c:\Users\[user_name]\.vscode\extensions\ms-python.python-2022.0.1786462952\out\client\extension.js:104:29648)]
```

Begging of log

**Comment by rchiodo** [comment]
Okay I'll transfer your issue to the python team.
