### ISSUE TITLE
Extension host terminated unexpectedly. code: 7

### ISSUE THREAD

**Issue by albert-ying** [microsoft/vscode-jupyter#8967]
This happen every few minutes

The console output:

```

vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/browser/parts/views/customView.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/contrib/scm/browser/scmViewlet.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/contrib/scm/browser/mainPanel.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/contrib/scm/browser/mainPane.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/contrib/scm/browser/repositoryPanel.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/contrib/scm/browser/repositoryPane.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/base/browser/ui/splitview/panelview.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/platform/electron/node/electron.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/platform/electron/electron-sandbox/electron.js:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
abstractExtensionService.ts:928 [RDebugger.r-debugger]: Cannot register 'r.rpath.windows'. This property is already registered.
_logMessageInConsole @ abstractExtensionService.ts:928
abstractExtensionService.ts:928 [RDebugger.r-debugger]: Cannot register 'r.rpath.mac'. This property is already registered.
_logMessageInConsole @ abstractExtensionService.ts:928
abstractExtensionService.ts:928 [RDebugger.r-debugger]: Cannot register 'r.rpath.linux'. This property is already registered.
_logMessageInConsole @ abstractExtensionService.ts:928
log.ts:301  INFO IExtensionHostStarter.start() took 42 ms.
log.ts:313   ERR [Extension Host] (node:57816) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Electron --trace-deprecation ...` to show where the warning was created)
console.ts:137 [Extension Host] (node:57816) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Electron --trace-deprecation ...` to show where the warning was created)
I @ console.ts:137
console.ts:137 [Extension Host] Monkey Patch is active.
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.r.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/r/syntaxes/r.tmLanguage.json.
New grammar file: file:///Users/A.Y/.vscode/extensions/ikuyadeu.r-2.3.8/syntax/r.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope text.tex.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/latex/syntaxes/TeX.tmLanguage.json.
New grammar file: file:///Users/A.Y/.vscode/extensions/james-yu.latex-workshop-8.23.0/syntax/TeX.tmLanguage.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope text.tex.latex.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/latex/syntaxes/LaTeX.tmLanguage.json.
New grammar file: file:///Users/A.Y/.vscode/extensions/james-yu.latex-workshop-8.23.0/syntax/LaTeX.tmLanguage.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope text.bibtex.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/latex/syntaxes/Bibtex.tmLanguage.json.
New grammar file: file:///Users/A.Y/.vscode/extensions/james-yu.latex-workshop-8.23.0/syntax/Bibtex.tmLanguage.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope text.tex.markdown_latex_combined.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/latex/syntaxes/markdown-latex-combined.tmLanguage.json.
New grammar file: file:///Users/A.Y/.vscode/extensions/james-yu.latex-workshop-8.23.0/syntax/markdown-latex-combined.tmLanguage.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.cpp.embedded.latex.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/latex/syntaxes/cpp-grammar-bailout.tmLanguage.json.
New grammar file: file:///Users/A.Y/.vscode/extensions/james-yu.latex-workshop-8.23.0/syntax/cpp-grammar-bailout.tmLanguage.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope text.bibtex.
Old grammar file: file:///Users/A.Y/.vscode/extensions/james-yu.latex-workshop-8.23.0/syntax/Bibtex.tmLanguage.json.
New grammar file: file:///Users/A.Y/.vscode/extensions/torn4dom4n.latex-support-3.10.0/grammars/Bibtex.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope text.tex.latex.
Old grammar file: file:///Users/A.Y/.vscode/extensions/james-yu.latex-workshop-8.23.0/syntax/LaTeX.tmLanguage.json.
New grammar file: file:///Users/A.Y/.vscode/extensions/torn4dom4n.latex-support-3.10.0/grammars/LaTeX.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope text.tex.
Old grammar file: file:///Users/A.Y/.vscode/extensions/james-yu.latex-workshop-8.23.0/syntax/TeX.tmLanguage.json.
New grammar file: file:///Users/A.Y/.vscode/extensions/torn4dom4n.latex-support-3.10.0/grammars/TeX.json
register @ TMScopeRegistry.ts:45
console.ts:137 [Extension Host] capabilities resolved immediately
​ Registering custom require.js for Jupyter Kernel
eval @ unknown
​ Window.require = function
​ Window.requirejs = function
​ Attempt Initialize IpyWidgets kernel.js [object Object]
​ Notebook preload (https://file%2B.vscode-resource.vscode-webview.net/Users/A.Y/.vscode/extensions/ms-toolsai.jupyter-2022.1.1001775990/out/ipywidgets/dist/ipywidgets.js) looks like a module but does not export an activate function
r @ notebookWebviewPreloads.js:3
​ Attempt Initialize IpyWidgets kernel.js undefined
​ IPyWidget kernel initializing...
​ Jupyter Notebook Renderer activated
​ request [object Object]
​ Rendering mimeType image/png [object Object]
console.ts:137 [Extension Host] error Error: command 'assorted-biscuits.configLanguage' already exists
    at u.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:28683)
    at Object.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:107:30423)
    at Object.<anonymous> (/Users/A.Y/.vscode/extensions/codebiscuits.assorted-biscuits-0.0.22/src/activate.ts:156:29)
    at Generator.next (<anonymous>)
    at a (/Users/A.Y/.vscode/extensions/codebiscuits.assorted-biscuits-0.0.22/bundled/extension.js:1:2053)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
console.ts:137 [Extension Host] Sent to UI true
console.ts:137 [Extension Host] Starting WebSocket: ws://localhost:8954/api/kernels/a08a0d7b-91b9-4ef1-b98a-48c78919aa4d
​ Received IPyWidgets_kernelOptions in ScriptManager
​ Received IPyWidgetMessages.IPyWidgets_kernelOptions
​ request [object Object]
​ Rendering mimeType image/png [object Object]
console.ts:137 [Extension Host] Sent to UI true
log.ts:313   ERR request cancelled: Error: request cancelled
    at /Users/A.Y/.vscode/extensions/ms-toolsai.jupyter-2022.1.1001775990/out/client/extension.js:66:685154
    at /Users/A.Y/.vscode/extensions/ms-toolsai.jupyter-2022.1.1001775990/out/client/extension.js:66:685448
    at Immediate.<anonymous> (/Users/A.Y/.vscode/extensions/ms-toolsai.jupyter-2022.1.1001775990/out/client/extension.js:66:685811)
    at processImmediate (internal/timers.js:461:21)
​ request [object Object]
​ Rendering mimeType image/png [object Object]
console.ts:137 [Extension Host] Sent to UI true
​ request [object Object]
​ Rendering mimeType image/png [object Object]
console.ts:137 [Extension Host] Sent to UI true
log.ts:313   ERR request cancelled: Error: request cancelled
    at /Users/A.Y/.vscode/extensions/ms-toolsai.jupyter-2022.1.1001775990/out/client/extension.js:66:685154
    at /Users/A.Y/.vscode/extensions/ms-toolsai.jupyter-2022.1.1001775990/out/client/extension.js:66:685448
    at Immediate.<anonymous> (/Users/A.Y/.vscode/extensions/ms-toolsai.jupyter-2022.1.1001775990/out/client/extension.js:66:685811)
    at processImmediate (internal/timers.js:461:21)
​ request [object Object]
​ Rendering mimeType image/png [object Object]
console.ts:137 [Extension Host] Sent to UI true
abstractExtensionService.ts:645 Extension host (LocalProcess) terminated unexpectedly. Code: 7, Signal: null
_onExtensionHostCrashed @ abstractExtensionService.ts:645
log.ts:313   ERR Extension host (LocalProcess) terminated unexpectedly. The following extensions were running: vscode.microsoft-authentication, vscode.ipynb, vscode.debug-auto-launch, vscode.git-base, asvetliakov.vscode-neovim, cssho.vscode-svgviewer, ctf0.ghosttext, cweijan.vscode-office, dlasagno.wal-theme, donjayamanne.githistory, fabiospampinato.vscode-todo-plus, geddski.macros, Gruntfuggly.activitusbar, hoovercj.vscode-power-mode, iocave.monkey-patch, ionutvmi.path-autocomplete, oderwat.indent-rainbow, TabNine.tabnine-vscode, voldikss.vscode-browser-completion, WakaTime.vscode-wakatime, vscode.git, vscode.configuration-editing, vscode.json-language-features, vscode.typescript-language-features, aaron-bond.better-comments, ms-toolsai.jupyter, ms-toolsai.jupyter-renderers, vscode.github-authentication, vscode.github, iocave.customize-ui, CodeBiscuits.assorted-biscuits, ms-python.python, vscode.emmet, vscode.merge-conflict, eamodio.gitlens, felipecaputo.git-project-manager, GitHub.copilot-nightly, Gruntfuggly.todo-tree, PKief.material-icon-theme, ms-python.vscode-pylance
notificationsAlerts.ts:42 Extension host terminated unexpectedly.
onDidChangeNotification @ notificationsAlerts.ts:42
log.ts:313   ERR [stored file working copy] handleSaveError(33) - exit - resulted in a save error: Canceled: Canceled file:///cs109b_hw1.ipynb
notificationsAlerts.ts:42 Failed to save 'cs109b_hw1.ipynb': Canceled
onDidChangeNotification @ notificationsAlerts.ts:42
localProcessExtensionHost.ts:325 Extension Host
localProcessExtensionHost.ts:326 /Users/A.Y/.vscode/extensions/codebiscuits.assorted-biscuits-0.0.22/bundled/extension.js:10
renderers.js:2 Jupyter Notebook Renderer activated
renderers.js:2 request L
renderers.js:2 Rendering mimeType image/png Object
log.ts:313   ERR Cannot read property 'onDidChangeContent' of undefined: TypeError: Cannot read property 'onDidChangeContent' of undefined
    at a.resolveTextModel (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1923:176904)
DevTools failed to load source map: Could not load content for https://file+.vscode-resource.vscode-webview.net/Users/A.Y/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.6/out/client_renderer/renderers.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
```

**Comment by rchiodo** [comment]
Thanks for the issue.

Does this repro if you disable everything except the jupyter extension (and maybe the python extension as you need that to run a kernel).

What is your version of other extensions besides the jupyter extension (I can see which version that is in the log output)?

Error code 7 is E2BIG which means something passed too much data to something else.

Does this repro with other notebooks? Can you share the notebook?

**Comment by albert-ying** [comment]
This is resolved by disabling the extension `Assorted Biscuits`
