### ISSUE TITLE
ImportError: TopDown: IProgress not found. error about tqdm and iprogress happened when using mmcv

### ISSUE THREAD

**Issue by viviyogurt** [microsoft/vscode-jupyter#9023]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

## MacBook Pro M1, 2020 Apple M1 16GB
What I have done:
I have tried the solutions mentioned in https://ipywidgets.readthedocs.io/en/stable/user_install.html and I have tried the following solutions and the problem exist:
```
!pip install --upgrade jupyter_client
from ipywidgets import IProgress
from tqdm import tqdm
!pip install ipywidgets
!jupyter nbextension enable --py widgetsnbextension
conda install -c conda-forge tqdm
```
## Code:
```
from mmpose.datasets import build_dataset
from mmpose.models import build_posenet
from mmpose.apis import train_model
import mmcv

# build dataset
datasets = [build_dataset(cfg.data.train)]


# build model
model = build_posenet(cfg.model)

# create work_dir
mmcv.mkdir_or_exist(cfg.work_dir)

# train model
train_model(
    model, datasets, cfg, distributed=False, validate=True, meta=dict())

```
### Expected results: 
Output the training log like:

```
2021-12-09 00:33:13,960 - mmpose - INFO - Start running, host: sjin@gpu-comp-105, work_dir: /userhome/35/sjin/WORK/mmpose/work_dirs/res50_cats_128x128
2021-12-09 00:33:13,965 - mmpose - INFO - Hooks will be executed in the following order:
before_run:
(VERY_HIGH   ) StepLrUpdaterHook                  
(NORMAL      ) CheckpointHook                     
(NORMAL      ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
(VERY_LOW    ) TensorboardLoggerHook   
```           
 -------------------- 
.....

But What I get like:
```
File "[/home/XXX/miniconda3/envs/pytorch_venv/lib/python3.7/site-packages/tqdm/std.py]()", line 1147, in __del__
    self.close()
  File "[/home/XXX/miniconda3/envs/pytorch_venv/lib/python3.7/site-packages/tqdm/notebook.py]()", line 286, in close
    self.disp(bar_style='danger', check_delay=False)
AttributeError: 'tqdm' object has no attribute 'disp'
=> num_images: 1000
=> load 1104 samples
load checkpoint from torchvision path: [torchvision://resnet50]()
Downloading: "[https://download.pytorch.org/models/resnet50-0676ba61.pth]()" to [/home/yannan/.cache/torch/hub/checkpoints/resnet50-0676ba61.pth]()
...
...
...
ImportError: TopDown: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
```

### VS Code Version

Version: 1.64.0 Commit: 5554b12acf27056905806867f251c859323ff7e9 Date: 2022-02-03T04:20:22.135Z Electron: 13.5.2 Chromium: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Darwin arm64 20.5.0

### Jupyter Extension Version

v2022.1.1201831736

### Jupyter logs

```shell
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
=> num_images: 1000
=> load 1104 samples
load checkpoint from torchvision path: torchvision://resnet50
Downloading: "https://download.pytorch.org/models/resnet50-0676ba61.pth" to /home/yannan/.cache/torch/hub/checkpoints/resnet50-0676ba61.pth
ImportError: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
/tmp/ipykernel_812689/3831953464.py in <module>
      9 
     10 # build model
---> 11 model = build_posenet(cfg.model)
     12 
     13 # create work_dir

~/workWithYang/mmpose/mmpose/models/builder.py in build_posenet(cfg)
     37 def build_posenet(cfg):
     38     """Build posenet."""
---> 39     return POSENETS.build(cfg)
     40 
     41 
~/miniconda3/envs/pytorch_venv/lib/python3.7/site-packages/mmcv/utils/registry.py in build(self, *args, **kwargs)
    210 
    211     def build(self, *args, **kwargs):
--> 212         return self.build_func(*args, **kwargs, registry=self)
    213 
    214     def _add_children(self, registry):

~/miniconda3/envs/pytorch_venv/lib/python3.7/site-packages/mmcv/cnn/builder.py in build_model_from_cfg(cfg, registry, default_args)
     25         return Sequential(*modules)
     26     else:
---> 27         return build_from_cfg(cfg, registry, default_args)
     28 
     29 

~/miniconda3/envs/pytorch_venv/lib/python3.7/site-packages/mmcv/utils/registry.py in build_from_cfg(cfg, registry, default_args)
     53     except Exception as e:
     54         # Normal TypeError does not print class name.
---> 55         raise type(e)(f'{obj_cls.__name__}: {e}')
     56 
     57 

ImportError: TopDown: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
```

### Coding Language and Runtime Version

Python v3.7.11 

### Language Extension Version (if applicable)

v2022.0.1814523869

### Anaconda Version (if applicable)

conda 4.11.0

### Running Jupyter locally or remotely?

Local

**Comment by viviyogurt** [comment]
Hope you could help me with this problem and thus I could finish the homework😭

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, looking for this issue on stackoverflow, it seems to be unrelated to VS Code, see here https://stackoverflow.com/questions/67998191/importerror-iprogress-not-found-please-update-jupyter-and-ipywidgets-although

Note:
* Please activate the conda environment first, before you attempt to install the packages
	* I.e. first activate conda in the terminal using `conda activate pytorch_venv`
	* Then run the commands to install the packages

Note, please do not mix and match pip install with conda, this will corrupt your conda environment.
I'm going to close this issue for now as there are existing stackover flow issues pointing to solutions.
If they still don't work, please feel free to re-open this issue and we'd be able to help.

**Comment by naourass** [comment]
I dont use Conda and still have this problem.

**Comment by dlwlgus53** [comment]
I had same problem and I fixed it.
do thiks

pip install jupyter
