### ISSUE TITLE
Failed to connect to the remote Jupyter Server (google dataproc)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#9099]
### Discussed in https://github.com/microsoft/vscode-jupyter/discussions/9098

<div type='discussions-op-text'>

<sup>Originally posted by **TarjinderSingh** February 23, 2022</sup>
I have been unsuccessfully trying to use the remote Jupyter Server function for a while, and finally thought I should ask for help!

I have a Jupyter Notebook running on port 8123 on Google Dataproc, and I can access the notebook fine (normally) after port forwarding at `localhost:8123` in my browser. However, I keep failing to connect to the remote Jupyter Server using vscode, with the following error message that I don't quite understand, ending with `SessionManager cannot enumerate kernelspecs. Returning default {}.`

Am I missing something, and is there something fixable for me to access the Notebook?

```
Info 18:50:02: Notebook Closed vscode-interactive:Interactive-1.interactive
Info 18:50:02: Closing interactive window: vscode-interactive:Interactive-1.interactive
Info 18:50:02: Creating server with settings : {"baseUrl":"https://localhost:8123/","appUrl":"","wsUrl":"wss://localhost:8123/","token":"12345","appendToken":true,"init":{"cache":"no-store","credentials":"same-origin"}}
[I 18:50:02.330 NotebookApp] Kernel shutdown: a6901b75-a9e9-41d0-b793-870f3506eefb
Info 18:50:04: Starting interactive window with controller ID ms-toolsai.jupyter/.jvsc74a57bd0f8e3ce338964ead362a45c6e0e786e8b405b1b1657107be6f98479240d02113f./Users/tsingh/anaconda3/envs/schema2/python./Users/tsingh/anaconda3/envs/schema2/python.-m#ipykernel_launcher
Info 18:50:04: Setting setActiveController for vscode-interactive:Interactive-1.interactive
Info 18:50:04: TargetController found ID: .jvsc74a57bd0f8e3ce338964ead362a45c6e0e786e8b405b1b1657107be6f98479240d02113f./Users/tsingh/anaconda3/envs/schema2/python./Users/tsingh/anaconda3/envs/schema2/python.-m#ipykernel_launcher (Interactive) for document vscode-interactive:Interactive-1.interactive
Info 18:50:04: Setting controller affinity for vscode-interactive:Interactive-1.interactive .jvsc74a57bd0f8e3ce338964ead362a45c6e0e786e8b405b1b1657107be6f98479240d02113f./Users/tsingh/anaconda3/envs/schema2/python./Users/tsingh/anaconda3/envs/schema2/python.-m#ipykernel_launcher (Interactive)
Info 18:50:04: Process Execution: > ~/anaconda3/envs/schema2/bin/python -m pip list
> ~/anaconda3/envs/schema2/bin/python -m pip list
Info 18:50:04: Starting Notebook in kernel.ts id = .jvsc74a57bd0f8e3ce338964ead362a45c6e0e786e8b405b1b1657107be6f98479240d02113f./Users/tsingh/anaconda3/envs/schema2/python./Users/tsingh/anaconda3/envs/schema2/python.-m#ipykernel_launcher
[I 18:50:04.725 NotebookApp] Creating new notebook in 
Info 18:50:04: installMissingDependencies ~/anaconda3/envs/schema2/bin/python
Info 18:50:04: IPykernel found previously in this environment ~/anaconda3/envs/schema2/bin/python
Info 18:50:04: Spec argv[0] updated from '/Users/tsingh/anaconda3/envs/schema2/bin/python' to '~/anaconda3/envs/schema2/bin/python'
Info 18:50:04: Starting a new session for kernel id = .jvsc74a57bd0f8e3ce338964ead362a45c6e0e786e8b405b1b1657107be6f98479240d02113f./Users/tsingh/anaconda3/envs/schema2/python./Users/tsingh/anaconda3/envs/schema2/python.-m#ipykernel_launcher, name = python374jvsc74a57bd0f8e3ce338964ead362a45c6e0e786e8b405b1b1657107be6f98479240d02113f
[I 18:50:04.979 NotebookApp] Kernel started: b1f6326c-637f-4fb6-82fb-279a63f7bc47, name: python374jvsc74a57bd0f8e3ce338964ead362a45c6e0e786e8b405b1b1657107be6f98479240d02113f
Info 18:50:05: Waiting for idle on (kernel): b1f6326c-637f-4fb6-82fb-279a63f7bc47 -> unknown
[W 18:50:05.034 NotebookApp] delete /Untitled-2-jvsc-272d630a-d76f-4344-acac-81534fecab10.ipynb
Info 18:50:06: Finished waiting for idle on (kernel): b1f6326c-637f-4fb6-82fb-279a63f7bc47 -> idle
Info 18:50:06: Started session for kernel .jvsc74a57bd0f8e3ce338964ead362a45c6e0e786e8b405b1b1657107be6f98479240d02113f./Users/tsingh/anaconda3/envs/schema2/python./Users/tsingh/anaconda3/envs/schema2/python.-m#ipykernel_launcher
Info 18:50:06: Waiting for idle (session) kernel .jvsc74a57bd0f8e3ce338964ead362a45c6e0e786e8b405b1b1657107be6f98479240d02113f./Users/tsingh/anaconda3/envs/schema2/python./Users/tsingh/anaconda3/envs/schema2/python.-m#ipykernel_launcher
Info 18:50:06: Waiting for idle on (kernel): b1f6326c-637f-4fb6-82fb-279a63f7bc47 -> idle
Info 18:50:06: Finished waiting for idle on (kernel): b1f6326c-637f-4fb6-82fb-279a63f7bc47 -> idle
Info 18:50:06: Finished connecting kernel .jvsc74a57bd0f8e3ce338964ead362a45c6e0e786e8b405b1b1657107be6f98479240d02113f./Users/tsingh/anaconda3/envs/schema2/python./Users/tsingh/anaconda3/envs/schema2/python.-m#ipykernel_launcher
Info 18:50:06: Executing silently Code (idle) = import sys\nprint(sys.executable)
Info 18:50:07: Executing silently Code (completed) = import sys\nprint(sys.executable)
Info 18:50:07: Executing silently Code (idle) = import site\nsite.addsitedir(site.getusersitepackages())\n__vsc_ipynb_file__ = 'Untitled-2'\n%config Co
Info 18:50:07: Executing silently Code (completed) = import site\nsite.addsitedir(site.getusersitepackages())\n__vsc_ipynb_file__ = 'Untitled-2'\n%config Co
Info 18:50:07: Waiting for idle on (kernel): b1f6326c-637f-4fb6-82fb-279a63f7bc47 -> idle
Info 18:50:07: Finished waiting for idle on (kernel): b1f6326c-637f-4fb6-82fb-279a63f7bc47 -> idle
Info 18:50:07: Executing silently Code (idle) = __file__ = 'Untitled-2'
Info 18:50:07: Creating server with settings : {"baseUrl":"https://localhost:8123/","appUrl":"","wsUrl":"wss://localhost:8123/","token":"12345","appendToken":true,"init":{"cache":"no-store","credentials":"same-origin"}}
Info 18:50:07: Executing silently Code (completed) = __file__ = 'Untitled-2'
Error 18:50:22: SessionManager cannot enumerate kernelspecs. Returning default {}.
Error 18:50:27: SessionManager cannot enumerate kernelspecs. Returning default {}.
```</div>

**Comment by DonJayamanne** [comment]
@TarjinderSingh

Can you confirm opening a browser session in incognito mode (private session) and navigating to the url `https://localhost:8123/` brings up Jupyter.
If it does come up, are you prompted for a token and then enter the valid token, are you able to successfully connect to Jupyter and run a notebook?

**Comment by TarjinderSingh** [comment]
@DonJayamanne I can confirm that I am able to connect to https://localhost:8123 to bring up Jupyter, put in the correct token, and run a notebook. I can access the kernel and start running code as expected.

**Comment by TarjinderSingh** [comment]
To follow up, I tried to play around a little more and was able to connect at `http://localhost:8123/?token=12345` but *not* `https://localhost:8123/?token=12345` using a Jupyter notebook. No idea why, the former works pretty well. Weirdly enough, my setup has three notebook kernels, and the Jupyter notebook can connect to all three. However, Python interactive mode can only connect to one of the three kernels; the other two just simply doesn't work. Not sure how to debug that though.

While running Spark at `http://localhost:8123`, I did get the following error, but I assume that is it something separate in dataproc.

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/opt/conda/miniconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/conda/miniconda3/lib/python3.8/site-packages/sparkmonitor/kernelextension.py", line 117, in run
    self.onrecv(msg)
  File "/opt/conda/miniconda3/lib/python3.8/site-packages/sparkmonitor/kernelextension.py", line 132, in onrecv
    sendToFrontEnd({
  File "/opt/conda/miniconda3/lib/python3.8/site-packages/sparkmonitor/kernelextension.py", line 216, in sendToFrontEnd
    monitor.send(msg)
  File "/opt/conda/miniconda3/lib/python3.8/site-packages/sparkmonitor/kernelextension.py", line 51, in send
    self.comm.send(msg)
AttributeError: 'ScalaMonitor' object has no attribute 'comm'
```

**Comment by DonJayamanne** [comment]
Closing this in favour of https://github.com/microsoft/vscode-jupyter/issues/12268
