### ISSUE TITLE
"No active notebook document to debug" when try to debug a notebook that doesn't have focus

### ISSUE THREAD

**Issue by NickCrews** [microsoft/vscode-jupyter#9239]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Have at least two editor panes/windows open at the same time, at least one of them a notebook file. If you click the "Debug Cell" button, one of two things happen:

- If the notebook cell has focus, then it works as expected.
- If the notebook does NOT have focus, then a dialog appears in the bottom right saying "No active notebook document to debug", and nothing else happens
![Kapture 2022-03-04 at 10 44 49](https://user-images.githubusercontent.com/10820686/156815084-2794901c-c9f0-4c95-a2d6-a099927a2dcf.gif)

### VS Code Version

Version: 1.65.0 Commit: b5205cc8eb4fbaa726835538cd82372cc0222d43 Date: 2022-03-02T11:11:20.886Z (2 days ago) Electron: 13.5.2 Chromium: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Darwin x64 21.3.0

### Jupyter Extension Version

v2022.2.1010630101

### Jupyter logs

```shell
This output is from when the debug run succeeds (see the gif above). When the error dialog shows up, nothing is emitted from the logs. But I'll include this anyway, just in case.

Info 17:44:31: Executing silently Code (idle) = import ipykernel\nprint(ipykernel.__version__)
Info 17:44:31: Executing silently Code (completed) = import ipykernel\nprint(ipykernel.__version__)
Info 17:44:32: Executing silently Code (idle) = import debugpy\ndebugpy.debug_this_thread()
Info 17:44:32: Executing silently Code (completed) = import debugpy\ndebugpy.debug_this_thread()
Info 17:44:33: Execute Cells request 0
Info 17:44:33: Execute Cell 0 /workspaces/noatak/notebooks/dedupe/donor_dedupe.ipynb
Info 17:44:33: Cell 0 executed with state Success
Warn 17:44:33: StdErr from Kernel Process [IPKernelApp] ERROR | Exception in control handler:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 281, in process_control
    await result
  File "/opt/conda/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 856, in debug_request
    reply_content = await reply_content
  File "/opt/conda/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 426, in do_debug_request
    return await self.debugger.process_request(msg)
  File "/opt/conda/lib/python3.9/site-packages/ipykernel/debugger.py", line 595, in process_request
    self.stop()
  File "/opt/conda/lib/python3.9/site-packages/ipykernel/debugger.py", line 348, in stop
    self.debugpy_client.disconnect_tcp_socket()
  File "/opt/conda/lib/python3.9/site-packages/ipykernel/debugger.py", line 232, in disconnect_tcp_socket
    self.debugpy_stream.socket.disconnect(self._get_endpoint())
  File "zmq/backend/cython/socket.pyx", line 640, in zmq.backend.cython.socket.Socket.disconnect
zmq.error.ZMQError: No such file or directory
```

### Coding Language and Runtime Version

c python 3.9.7

### Language Extension Version (if applicable)

Python extension (from microsoft) v2022.2.1924087327

### Anaconda Version (if applicable)

running `! conda --version` in the notebook gives `conda 4.10.3`

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
thanks for the bug, it's probably a new regression since that bug is pretty old, although it doesn't seem to behave well in the previous version either.
It looks like it's just trying to debug a cell on whichever window has focus, which can be seen when two notebooks are open side by side.

**Comment by roblourens** [comment]
That error is probably fixed, but now the context keys are not right because the debug options go away when a text editor is focused, so that is not right.

**Comment by DonJayamanne** [comment]
No longer repros.
