### ISSUE TITLE
'Show variable in Data Viewer' shows 'Install Pandas' popup even though pandas IS installed in PDM environment

### ISSUE THREAD

**Issue by CodeCox** [microsoft/vscode-jupyter#9304]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

In the `Jupyter Variables` tab I want to view the details of a pandas dataframe. I select `Click to view a  Jupyter variable`  next to the dataframe variable (ie.`df` in the screenshot) - and the 'Data Viewer' is prompting me to install pandas incorrectly.

![image](https://user-images.githubusercontent.com/44036684/157428922-a6b19851-2e23-40e9-af20-65aef89fa902.png)

Pandas is installed and working so I do not expect to see this popup!

![image](https://user-images.githubusercontent.com/44036684/157429301-def10c93-c0a7-470d-8254-da4aa2e39b15.png)

NB!
I am using [PDM](https://pdm.fming.dev/) to manage my environment.
(Perhaps this may be the reason the `Data Viewer` is not recognising the pandas installation?)

### VS Code Version

Version: 1.65.1 (user setup) Commit: 8908a9ca0f221f36507231afb39d2d8d1e182702 Date: 2022-03-08T02:06:27.846Z Electron: 13.5.2 Chromium: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Windows_NT x64 10.0.19044

### Jupyter Extension Version

Jupyter  v2022.2.1030672458 

### Jupyter logs

```shell
Visual Studio Code (1.65.1, undefined, desktop)
Jupyter Extension Version: 2022.2.1030672458.
Python Extension Version: 2022.2.1924087327.
Info 10:18:26: ZMQ install verified.
Info 10:18:27: Experiment status for python is {"enabled":false,"optInto":[],"optOutFrom":[]}
Info 10:18:27: Interrupt requested & no kernel.
Info 10:18:27: Setting setActiveController for c:\Users\spikes\pdmrepo\jlab\fun\bug.ipynb
Info 10:18:27: Getting activation commands for C:\Users\spikes\AppData\Local\Programs\Python\Python310\python.exe are not cached. May take a while.
Info 10:18:27: KernelProvider switched kernel to id = .pdm-kernel.C:\Users\spikes\AppData\Local\Programs\Python\Python310\python.exe.C:\Users\spikes\AppData\Local\Programs\Python\Python310\python.exe.-m#ipykernel_launcher
Info 10:18:27: Creating controller for jupyter-notebook with interpreter ~\AppData\Local\Programs\Python\Python310\python.exe
Info 10:18:27: Find preferred kernel for c:\Users\spikes\pdmrepo\jlab\fun\bug.ipynb with metadata {"kernelspec":{"display_name":"pdm-kernel","language":"python","name":"pdm-kernel"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.10.2"},"orig_nbformat":4} & preferred interpreter ~\AppData\Local\Programs\Python\Python310\python.exe
Info 10:18:27: findKernel found pdm-kernel
Info 10:18:27: PreferredConnection: .pdm-kernel.C:\Users\spikes\AppData\Local\Programs\Python\Python310\python.exe.C:\Users\spikes\AppData\Local\Programs\Python\Python310\python.exe.-m#ipykernel_launcher found for NotebookDocument: c:\Users\spikes\pdmrepo\jlab\fun\bug.ipynb
Info 10:18:27: TargetController found ID: .pdm-kernel.C:\Users\spikes\AppData\Local\Programs\Python\Python310\python.exe.C:\Users\spikes\AppData\Local\Programs\Python\Python310\python.exe.-m#ipykernel_launcher for document c:\Users\spikes\pdmrepo\jlab\fun\bug.ipynb
Info 10:18:27: Setting controller affinity for c:\Users\spikes\pdmrepo\jlab\fun\bug.ipynb .pdm-kernel.C:\Users\spikes\AppData\Local\Programs\Python\Python310\python.exe.C:\Users\spikes\AppData\Local\Programs\Python\Python310\python.exe.-m#ipykernel_launcher
Info 10:18:27: Process Execution: > ~\AppData\Local\Programs\Python\Python310\python.exe -m pip list
> ~\AppData\Local\Programs\Python\Python310\python.exe -m pip list
Info 10:18:28: Registering dummy command feature
Info 10:18:51: Loading webview. View is notset
Info 10:18:51: Loading web view...
Info 10:18:51: Webview panel created.
Info 10:18:52: Web view react rendered
Info 10:18:53: Searching for token colors ...
Info 10:18:53: Attempting search for colors ...
Info 10:18:53: Loading colors from c:\Users\spikes\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\light_vs.json ...
Info 10:18:53: Attempting search for colors ...
Info 10:18:53: Loading base colors from c:\Users\spikes\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\light_vs.json ...
Info 10:18:53: Using colors to generate CSS ...
Info 10:19:09: Execute Cells request 0, 1, 2, 3
Info 10:19:09: Execute Cell 0 c:\Users\spikes\pdmrepo\jlab\fun\bug.ipynb
Info 10:19:09: Starting Notebook in kernel.ts id = .pdm-kernel.C:\Users\spikes\AppData\Local\Programs\Python\Python310\python.exe.C:\Users\spikes\AppData\Local\Programs\Python\Python310\python.exe.-m#ipykernel_launcher
Info 10:19:09: Creating raw notebook for c:\Users\spikes\pdmrepo\jlab\fun\bug.ipynb
Info 10:19:09: Getting preferred kernel for c:\Users\spikes\pdmrepo\jlab\fun\bug.ipynb
Info 10:19:09: Computing working directory c:\Users\spikes\pdmrepo\jlab\fun\bug.ipynb
Info 10:19:09: Execute Cell 1 c:\Users\spikes\pdmrepo\jlab\fun\bug.ipynb
Info 10:19:09: Execute Cell 2 c:\Users\spikes\pdmrepo\jlab\fun\bug.ipynb
Info 10:19:09: Execute Cell 3 c:\Users\spikes\pdmrepo\jlab\fun\bug.ipynb
Info 10:19:09: Starting raw kernel pdm-kernel for interpreter ~\AppData\Local\Programs\Python\Python310\python.exe
Info 10:19:09: installMissingDependencies ~\AppData\Local\Programs\Python\Python310\python.exe
Info 10:19:09: IPyKernel found previously in this environment ~\AppData\Local\Programs\Python\Python310\python.exe
Info 10:19:10: Kernel launching with ports 9000,9001,9002,9003,9004. Start port is 9000
Info 10:19:10: Process Execution: > ~\AppData\Local\Programs\Python\Python310\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> ~\AppData\Local\Programs\Python\Python310\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
Info 10:19:10: Creating daemon process for ~\AppData\Local\Programs\Python\Python310\python.exe with env variables count 61
Info 10:19:10: Process Execution: > ~\AppData\Local\Programs\Python\Python310\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_interrupt_daemon -v --ppid 10052
> ~\AppData\Local\Programs\Python\Python310\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_interrupt_daemon -v --ppid 10052
Warn 10:19:10: Stderr output when getting ipykernel version & path Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'ipykernel' for ~\AppData\Local\Programs\Python\Python310\python.exe
Info 10:19:10: get interrupthandle daemon
Info 10:19:10: Process Execution: > ~\AppData\Local\Programs\Python\Python310\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"2bbc8f87-7766-4ad7-9920-82c8ac028d45" --shell=9002 --transport="tcp" --iopub=9004 --f=C:\Users\spikes\AppData\Local\Temp\tmp-100523ba1TrLmWKpG.json
> ~\AppData\Local\Programs\Python\Python310\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"2bbc8f87-7766-4ad7-9920-82c8ac028d45" --shell=9002 --transport="tcp" --iopub=9004 --f=C:\Users\spikes\AppData\Local\Temp\tmp-100523ba1TrLmWKpG.json
Info 10:19:10: Process Execution: cwd: c:\Users\spikes\pdmrepo\jlab\fun
cwd: c:\Users\spikes\pdmrepo\jlab\fun
Warn 10:19:11: StdErr from Kernel Process c:\Users\spikes\pdmrepo\jlab\__pypackages__\3.10\lib\traitlets\traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(

Warn 10:19:11: StdErr from Kernel Process c:\Users\spikes\pdmrepo\jlab\__pypackages__\3.10\lib\traitlets\traitlets.py:2157: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '2bbc8f87-7766-4ad7-9920-82c8ac028d45' instead of 'b"2bbc8f87-7766-4ad7-9920-82c8ac028d45"'.
  warn(

Info 10:19:11: Kernel Output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing C:\Users\spikes\AppData\Local\Temp\tmp-100523ba1TrLmWKpG.json

Info 10:19:11: Raw session started and connected
Started kernel pdm-kernel
Info 10:19:11: Finished connecting 72872c8f-bb0f-431a-81db-fa002ee4323e
Info 10:19:11: Executing silently Code (idle) = import sys\nprint(sys.executable)
Info 10:19:12: Executing silently Code (completed) = import sys\nprint(sys.executable)
Info 10:19:12: UpdateWorkingDirectoryAndPath in Kernel
Info 10:19:12: Executing silently Code (idle) = import site\nsite.addsitedir(site.getusersitepackages())\nimport os\nimport sys\n%cd "c:\Users\spikes\pd
Info 10:19:12: Executing silently Code (completed) = import site\nsite.addsitedir(site.getusersitepackages())\nimport os\nimport sys\n%cd "c:\Users\spikes\pd
Info 10:19:12: Waiting for idle on (kernel): 9f1653fe-7a06-4646-be18-d2299e16147b -> idle
Info 10:19:12: Finished waiting for idle on (kernel): 9f1653fe-7a06-4646-be18-d2299e16147b -> idle
Info 10:19:12: Cell 0 executed with state Success
Info 10:19:12: Cell 1 executed with state Success
Info 10:19:12: Cell 2 executed with state Success
Info 10:19:12: Executing silently Code (idle) = # Query Jupyter server for the info about a dataframe\nimport json as _VSCODE_json\nimport builtins as
Info 10:19:12: Cell 3 executed with state Idle
Info 10:19:12: Executing silently Code (completed) = # Query Jupyter server for the info about a dataframe\nimport json as _VSCODE_json\nimport builtins as
Info 10:19:12: Executing silently Code (idle) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 10:19:12: Executing silently Code (idle) = # Query Jupyter server for the info about a dataframe\nimport json as _VSCODE_json\nimport builtins as
Info 10:19:12: Executing silently Code (completed) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 10:19:13: Executing silently Code (completed) = # Query Jupyter server for the info about a dataframe\nimport json as _VSCODE_json\nimport builtins as
Info 10:19:13: Executing silently Code (idle) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 10:19:13: Executing silently Code (completed) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 10:19:13: Executing silently Code (idle) = # Query Jupyter server for the info about a dataframe\nimport json as _VSCODE_json\nimport builtins as
Info 10:19:13: Executing silently Code (idle) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(df))
Info 10:19:13: Executing silently Code (completed) = # Query Jupyter server for the info about a dataframe\nimport json as _VSCODE_json\nimport builtins as
Info 10:19:13: Executing silently Code (idle) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 10:19:13: Executing silently Code (idle) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(df))
Info 10:19:13: Executing silently Code (completed) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(df))
Info 10:19:13: Executing silently Code (completed) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 10:19:13: Executing silently Code (completed) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(df))
Info 10:19:13: Executing silently Code (idle) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(df))
Info 10:19:13: Executing silently Code (completed) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(df))
Info 10:24:06: Loading webview. View is notset
Info 10:24:06: Loading web view...
Info 10:24:06: Webview panel created.
Info 10:24:06: Executing silently Code (idle) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 10:24:06: Executing silently Code (idle) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 10:24:06: Process Execution: > ~\AppData\Local\Programs\Python\Python310\python.exe -c "import pandas;print(pandas.__version__)"
> ~\AppData\Local\Programs\Python\Python310\python.exe -c "import pandas;print(pandas.__version__)"
Info 10:24:06: Executing silently Code (completed) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 10:24:07: Executing silently Code (completed) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 10:24:07: Executing silently Code (idle) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(df))
Info 10:24:07: Executing silently Code (idle) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(df))
Info 10:24:07: Executing silently Code (completed) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(df))
Info 10:24:07: Executing silently Code (completed) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(df))
Warn 10:24:07: Failed to get version of Pandas to use Data Viewer [i [Error]: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pandas'

	at ChildProcess.<anonymous> (c:\Users\spikes\.vscode\extensions\ms-toolsai.jupyter-2022.2.1030672458\out\client\extension.js:2:161231)
	at Object.onceWrapper (events.js:422:26)
	at ChildProcess.emit (events.js:315:20)
	at maybeClose (internal/child_process.js:1048:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)] {
  category: 'unknown'
}
Info 10:24:07: Web view react rendered
Info 10:24:07: Searching for token colors ...
Info 10:24:07: Attempting search for colors ...
Info 10:24:07: Searching for token colors ...
Info 10:24:07: Attempting search for colors ...
Info 10:24:07: Loading colors from c:\Users\spikes\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\light_vs.json ...
Info 10:24:07: Loading colors from c:\Users\spikes\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\light_vs.json ...
Info 10:24:07: Attempting search for colors ...
Info 10:24:07: Attempting search for colors ...
Info 10:24:07: Loading base colors from c:\Users\spikes\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\light_vs.json ...
Info 10:24:07: Loading base colors from c:\Users\spikes\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\light_vs.json ...
Info 10:24:07: Using colors to generate CSS ...
Info 10:24:07: Using colors to generate CSS ...
Error 10:24:23: [Error: Python package 'pandas' is required for viewing data.
	at v.installMissingDependencies (c:\Users\spikes\.vscode\extensions\ms-toolsai.jupyter-2022.2.1030672458\out\client\extension.js:2:327571)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async v.checkAndInstallMissingDependencies (c:\Users\spikes\.vscode\extensions\ms-toolsai.jupyter-2022.2.1030672458\out\client\extension.js:2:326970)
	at async r.ensureInitialized (c:\Users\spikes\.vscode\extensions\ms-toolsai.jupyter-2022.2.1030672458\out\client\extension.js:2:333360)
	at async r.getDataFrameInfo (c:\Users\spikes\.vscode\extensions\ms-toolsai.jupyter-2022.2.1030672458\out\client\extension.js:2:332324)
	at async x.prepDataFrameInfo (c:\Users\spikes\.vscode\extensions\ms-toolsai.jupyter-2022.2.1030672458\out\client\extension.js:2:323294)
	at async x.showData (c:\Users\spikes\.vscode\extensions\ms-toolsai.jupyter-2022.2.1030672458\out\client\extension.js:2:321068)
	at async f.create (c:\Users\spikes\.vscode\extensions\ms-toolsai.jupyter-2022.2.1030672458\out\client\extension.js:2:330000)]
Info 10:24:23: Executing silently Code (idle) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 10:24:23: Executing silently Code (idle) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 10:24:23: Executing silently Code (idle) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 10:24:23: Executing silently Code (completed) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 10:24:23: Executing silently Code (completed) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 10:24:23: Executing silently Code (completed) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 10:24:23: Executing silently Code (idle) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(df))
Info 10:24:23: Executing silently Code (idle) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(df))
Info 10:24:23: Executing silently Code (completed) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(df))
Info 10:24:23: Executing silently Code (idle) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(df))
Info 10:24:23: Executing silently Code (completed) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(df))
Info 10:24:23: Executing silently Code (completed) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(df))
Info 10:28:53: Searching for token colors ...
Info 10:28:53: Attempting search for colors ...
Info 10:28:53: Loading colors from c:\Users\spikes\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\light_vs.json ...
Info 10:28:53: Attempting search for colors ...
Info 10:28:53: Loading base colors from c:\Users\spikes\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\theme-defaults\themes\light_vs.json ...
Info 10:28:53: Executing silently Code (idle) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 10:28:53: Executing silently Code (idle) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 10:28:53: Using colors to generate CSS ...
Info 10:28:53: Executing silently Code (completed) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 10:28:53: Executing silently Code (completed) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 10:28:53: Executing silently Code (idle) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(df))
Info 10:28:53: Executing silently Code (idle) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(df))
Info 10:28:53: Executing silently Code (completed) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(df))
Info 10:28:53: Executing silently Code (completed) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(df))
Info 10:44:45: Executing silently Code (idle) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 10:44:45: Executing silently Code (idle) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 10:44:45: Executing silently Code (idle) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 10:44:45: Executing silently Code (completed) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 10:44:45: Executing silently Code (completed) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 10:44:45: Executing silently Code (completed) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 10:44:45: Executing silently Code (idle) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(df))
Info 10:44:45: Executing silently Code (idle) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(df))
Info 10:44:45: Executing silently Code (completed) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(df))
Info 10:44:45: Executing silently Code (idle) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(df))
Info 10:44:45: Executing silently Code (completed) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(df))
Info 10:44:45: Executing silently Code (completed) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(df))
```

### Coding Language and Runtime Version

Python 3.10.2

### Language Extension Version (if applicable)

Python v2022.2.1924087327

### Anaconda Version (if applicable)

NA - I'm using PDM!

### Running Jupyter locally or remotely?

Local

**Comment by rchiodo** [comment]
Thanks for the bug. Yes PDM is not a supported scenario (at least as far as us detecting installation).

**Comment by rchiodo** [comment]
You might be able to work around this problem by creating an ```.env``` file in the same folder as the notebook.

It would contain something like so:

```
PYTHONPATH=C:\Users\USERNAME\AppData\Roaming\pdm\venv\lib\site-packages\pdm\pep582
```

(Based on the feedback on this issue: https://github.com/pdm-project/pdm/issues/848)

**Comment by CodeCox** [comment]
@rchiodo Thank you for looking into this issue even though PDM is not officially supported!

The short answer to your suggestion is that it does not work **FOR THE `Data Viewer`.** _But I suspect the answer is just a tweak away along this line of inquiry._

The longer answer is that I have looked at the PDM issue you reference to get my initial notebook setup working. The `ipykernel` was not being found in my PDM environment.  The .ENV `PYTHONPATH` setting fix works for this, but I chose to then use the alternative option mentioned there ie. the `kernel.json` because it gives me a named kernel that I can select from the dropdown list. Here's my kernel spec:
```
{
 "argv": [
  "C:\\Users\\spikes\\AppData\\Local\\Programs\\Python\\Python310\\python.exe",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "pdm-kernel",
 "language": "python",
 "env": {"PYTHONPATH": "C:\\Users\\spikes\\AppData\\Roaming\\pdm\\venv\\Lib\\site-packages\\pdm\\pep582"}
}
```
As you can see from my earlier screenshot, my notebook runs just fine with this kernel config - the `pandas` installation is found by the import and  the cells execute successfully (thanks to this PYTHONPATH env setting!). 

So a part/portion of my VSCode setup does recognise that `pandas` is installed - however just not the `Data Viewer` part! I concluded that the `Data Viewer` component was doing something different or looking at something else?

**Comment by rchiodo** [comment]
Ah we likely don't add the .env variables just when checking. The only other thing would be to add that PYTHONPATH globally.

**Comment by CodeCox** [comment]
I have `PYTHONPATH` set globally as a WIndows environment variable. and I can see  the correct value in the CLI  using `$env:PYTHONPATH`.  But I don't thing this is being used by VScode. I still needed to set `PYTHONPATH` in the `.ENV` file or `kernel.json` file  before VScode was able to find the `ipykernel`.  

Where and what global setting did you have in mind? (The Pylance Intellisense uses `python.analysis.extraPaths` - does your check use this setting?)

**Comment by rchiodo** [comment]
We run this code here:

```
python -c import pandas;print(pandas.__version__)
```
If that works from the command line, theoretically it should work from within our code too.

**Comment by CodeCox** [comment]
I had to add quotes, but otherwise both these commands work!

- PS C:\Users\spikes\pdmrepo\jlab> python -c "import pandas;print(pandas.__version__)"
1.4.1

- PS C:\Users\spikes\pdmrepo\jlab> pdm run python -c "import pandas;print(pandas.__version__)"
1.4.1

**Comment by rchiodo** [comment]
Did you activate PDM first? (Not sure if PDM has an activation step, or something you put into the path)

It's likely it would have to work from a non pdm activated console. We don't know how to activate PDM, so the python we launch wouldn't run with the same environment as one in a PDM console.

**Comment by rchiodo** [comment]
This might be obvious, but you need to restart ALL instances of VS code if you added PYTHONPATH to your global environment.

**Comment by CodeCox** [comment]
Ok - you narrowed it down!

### "check has to work from a non pdm activated console"
- PDM does not have an activation step. The `pdm run <script>`  command ensures the correct environment  for the script by looking for a __pypackages__ folder. 
- To cut  a long story short , your check works when I run it in my project folder but It fails when run outside my project folder.
- My project folder is basically the vscode workspace. Which means your check is not being run in the current workspace?

PS. I ran your check with and without `pdm run` in my project folder. I need to think about why it succeeded without `pdm run`

**Comment by CodeCox** [comment]
Thanks - I reckon that's probably the cause of my problem - but I need some time to think it thru.  Python env's are messy - so I want to understand why your setup works for my conda and poetry environments. Also I noticed differences in ennvironment values depending on whether VSsode was started from the `Windows Start Menu`  or with `code .`  on the CLI eg. I think CWD is effected .  VScode also 'remembers' some settings based on initial usage so that also comes into play. 

I'll pickup on this again tomorrow. ciao for now.

**Comment by CodeCox** [comment]
### Restatement of issue:
Unlike in Poetry or Conda venvs, PDM looks for packages in the nearest `__pypackges__`  up the folder hierarchy.  The `CWD` context that the Data Viewer check is using does not have a `__pypackages__` with a `pandas` installation, therefore it fails.
_(I think the check would succeed if it was run in the context of the `current workspace` , and also this change of `dir` would not have any negative consequences if a virtual env was present!)_

### Workaround:
I had to resort to hardcoding  a known absolute path in my `.ENV`  file to appease the Data Viewer check:

```
PYTHONPATH=C:\Users\spikes\pdmrepo\jlab\__pypackages__\3.10\lib
```

This appends a specific bit of info to my global pdm-enabled `PYTHONPATH` specifically for the VSCode Extension (Terminal is not effected!) . 

### Notes:
- It's an ugly hack but the Data Viewer check use-case does not seem relevant to my workflow, as far as I can tell. 
- Annoyingly, I was not able to get `${workspaceFolder}` _variable substitution_ to work hence the problematic absolute path.
- It will eventually break when the `<major.minor>` version pf my Interpreter changes (but  I have to make a few similar tweaks anyway when the time comes).
