### ISSUE TITLE
render_traceback failure when running kernel

### ISSUE THREAD

**Issue by jpcoding** [microsoft/vscode-jupyter#9306]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When I have the following errors:  typo or use an undefined variable, functions not defined, cells not run prior. 
The whole notebook will keep running, can't interrupt the single cell, have to restart the kernel. 

### VS Code Version

1.64.2

### Jupyter Extension Version

v2022.1.1301854968

### Coding Language and Runtime Version

Python3.8.10

**Comment by rchiodo** [comment]
Thanks for the bug. 

Can you give an example notebook that will keep running cells? For me this notebook will stop after the first cell:

![image](https://user-images.githubusercontent.com/19672699/157497738-7d5337ea-87b8-43c0-ab43-1b200efad3a5.png)

How are you running all of the cells? With run all? Or with selecting them and clicking the run button on each?

**Comment by jpcoding** [comment]
import numpy as np
data=np.fromfile("fileNotExist.data",dtype=np.float32)
![image](https://user-images.githubusercontent.com/30496825/157498351-07dfe1d4-b6b8-445b-89cf-ae28927b4030.png)

**Comment by rchiodo** [comment]
Can you include your jupyter output log? I'm wondering if the kernel just crashed instead. (that cell comes back immediately for me).

![image](https://user-images.githubusercontent.com/19672699/157499041-7648ba7a-ef91-4566-8d17-1f9d415254a9.png)

**Comment by jpcoding** [comment]
Info 11:40:20: Execute Cells request 24
Info 11:40:20: Execute Cell 24 ~/data/cleared1800x3600/sz2_study/test.ipynb
Warn 11:40:21: StdErr from Kernel Process [IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/home/jp/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3251, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_112112/4155688225.py", line 2, in <module>
    data=np.fromfile("fileNotExist.data",dtype=np.float32)
FileNotFoundError: [Errno 2] No such file or directory: 'fileNotExist.data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jp/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'FileNotFoundError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jp/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3191, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/home/jp/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3268, in run_code
    self.showtraceback(running_compiled_code=True)
  File "/home/jp/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/home/jp/.local/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/home/jp/.local/lib/python3.8/site-packages/IPython/core/ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/home/jp/.local/lib/python3.8/site-packages/IPython/core/ultratb.py", line 852, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/home/jp/.local/lib/python3.8/site-packages/IPython/core/ultratb.py", line 786, in format_exception_as_a_whole
    records = self.get_records(etb, number_of_lines_of_context, tb_offset)
  File "/home/jp/.local/lib/python3.8/site-packages/IPython/core/ultratb.py", line 830, in get_records
    style = stack_data.style_with_executing_node(style, "bg:ansiyellow")
  File "/home/jp/.local/lib/python3.8/site-packages/stack_data/core.py", line 412, in style_with_executing_node
    class NewStyle(style):
  File "/usr/lib/python3/dist-packages/pygments/style.py", line 91, in __new__
    ndef[4] = colorformat(styledef[3:])
  File "/usr/lib/python3/dist-packages/pygments/style.py", line 58, in colorformat
    assert False, "wrong color format %r" % text
AssertionError: wrong color format 'ansiyellow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jp/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AssertionError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jp/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2814, in _run_cell
    return runner(coro)
  File "/home/jp/.local/lib/python3.8/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/home/jp/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3012, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/home/jp/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3210, in run_ast_nodes
    self.showtraceback()
  File "/home/jp/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/home/jp/.local/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/home/jp/.local/lib/python3.8/site-packages/IPython/core/ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/home/jp/.local/lib/python3.8/site-packages/IPython/core/ultratb.py", line 852, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/home/jp/.local/lib/python3.8/site-packages/IPython/core/ultratb.py", line 786, in format_exception_as_a_whole
    records = self.get_records(etb, number_of_lines_of_context, tb_offset)
  File "/home/jp/.local/lib/python3.8/site-packages/IPython/core/ultratb.py", line 830, in get_records
    style = stack_data.style_with_executing_node(style, "bg:ansiyellow")
  File "/home/jp/.local/lib/python3.8/site-packages/stack_data/core.py", line 412, in style_with_executing_node
    class NewStyle(style):
  File "/usr/lib/python3/dist-packages/pygments/style.py", line 91, in __new__
    ndef[4] = colorformat(styledef[3:])
  File "/usr/lib/python3/dist-packages/pygments/style.py", line 58, in colorformat
    assert False, "wrong color format %r" % text
AssertionError: wrong color format 'ansiyellow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jp/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AssertionError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jp/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 357, in dispatch_shell
    await result
  File "/home/jp/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 652, in execute_request
    reply_content = await reply_content
  File "/home/jp/.local/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 359, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/jp/.local/lib/python3.8/site-packages/ipykernel/zmqshell.py", line 532, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/home/jp/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2768, in run_cell
    result = self._run_cell(
  File "/home/jp/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2819, in _run_cell
    self.showtraceback(running_compiled_code=True)
  File "/home/jp/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/home/jp/.local/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/home/jp/.local/lib/python3.8/site-packages/IPython/core/ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/home/jp/.local/lib/python3.8/site-packages/IPython/core/ultratb.py", line 852, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/home/jp/.local/lib/python3.8/site-packages/IPython/core/ultratb.py", line 786, in format_exception_as_a_whole
    records = self.get_records(etb, number_of_lines_of_context, tb_offset)
  File "/home/jp/.local/lib/python3.8/site-packages/IPython/core/ultratb.py", line 830, in get_records
    style = stack_data.style_with_executing_node(style, "bg:ansiyellow")
  File "/home/jp/.local/lib/python3.8/site-packages/stack_data/core.py", line 412, in style_with_executing_node
    class NewStyle(style):
  File "/usr/lib/python3/dist-packages/pygments/style.py", line 91, in __new__
    ndef[4] = colorformat(styledef[3:])
  File "/usr/lib/python3/dist-packages/pygments/style.py", line 58, in colorformat
    assert False, "wrong color format %r" % text
AssertionError: wrong color format 'ansiyellow'

**Comment by jpcoding** [comment]
Jupyter suggested the following issue after I restart the kernel
https://github.com/ipython/ipython/issues/2049



Info 11:42:04: Restart requested file:///home/jp/data/cleared1800x3600/sz2_study/test.ipynb
Info 11:42:04: Restart kernel execution
Info 11:42:04: Cancel pending cells
Info 11:42:04: Starting raw kernel Python 3.8.10 64-bit
Info 11:42:04: installMissingDependencies /bin/python3
Info 11:42:04: IPykernel found previously in this environment /bin/python3
Info 11:42:04: Restarting c83d0faa-d2d3-4390-9597-8d87333d9932
Info 11:42:04: Cancel all remaining cells true || Idle
Info 11:42:04: Cancel pending cells
Info 11:42:04: Cell 24 executed with state Idle
Info 11:42:04: Kernel launching with ports 9000,9001,9002,9003,9004. Start port is 9000
Info 11:42:04: No custom variables for Kernel as interpreter is not conda, but is Global
Info 11:42:04: Process Execution: > /bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> /bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
Info 11:42:05: Process Execution: > /bin/python3 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"17912dd5-b363-441b-be78-879b30f1e2a4" --shell=9002 --transport="tcp" --iopub=9004 --f=/tmp/tmp-107874q1skdt6gXvEK.json
> /bin/python3 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"17912dd5-b363-441b-be78-879b30f1e2a4" --shell=9002 --transport="tcp" --iopub=9004 --f=/tmp/tmp-107874q1skdt6gXvEK.json
Info 11:42:05: Process Execution: cwd: ~/data/cleared1800x3600/sz2_study
cwd: ~/data/cleared1800x3600/sz2_study
Info 11:42:05: ipykernel version 6.8.0 for /bin/python3
Info 11:42:05: ipykernel location ~/.local/lib/python3.8/site-packages/ipykernel/__init__.py for /bin/python3
Warn 11:42:05: StdErr from Kernel Process /home/jp/.local/lib/python3.8/site-packages/traitlets/traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(

Warn 11:42:05: StdErr from Kernel Process /home/jp/.local/lib/python3.8/site-packages/traitlets/traitlets.py:2157: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '17912dd5-b363-441b-be78-879b30f1e2a4' instead of 'b"17912dd5-b363-441b-be78-879b30f1e2a4"'.
  warn(

Info 11:42:05: Kernel Output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing /tmp/tmp-107874q1skdt6gXvEK.json

Info 11:42:06: Got new session 8de9dd1e-5095-47ab-ba99-971e996dd784
Info 11:42:06: Started new restart session
Info 11:42:06: Dispose Kernel process
Error 11:42:06: Error in waiting for cell to complete [Error: Canceled future for execute_request message before replies were done
	at t.KernelShellFutureHandler.dispose (/home/jp/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:51:432353)
	at /home/jp/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:307599
	at Map.forEach (<anonymous>)
	at y._clearKernelState (/home/jp/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:307585)
	at y.dispose (/home/jp/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:66:301017)
	at /home/jp/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:51:194444
	at t.swallowExceptions (/home/jp/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:16:2495)
	at dispose (/home/jp/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:51:194423)
	at t.RawSession.dispose (/home/jp/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:113:303296)]
Info 11:42:06: Executing silently Code (idle) = import sys\nprint(sys.executable)
Info 11:42:06: Executing silently Code (completed) = import sys\nprint(sys.executable)
Info 11:42:06: UpdateWorkingDirectoryAndPath in Kernel
Info 11:42:06: Executing silently Code (idle) = import site\nsite.addsitedir(site.getusersitepackages())\nimport os\nimport sys\n%cd "/home/jp/data/clea
Info 11:42:06: Executing silently Code (completed) = import site\nsite.addsitedir(site.getusersitepackages())\nimport os\nimport sys\n%cd "/home/jp/data/clea
Info 11:42:06: Waiting for idle on (kernel): 8de9dd1e-5095-47ab-ba99-971e996dd784 -> idle
Info 11:42:06: Finished waiting for idle on (kernel): 8de9dd1e-5095-47ab-ba99-971e996dd784 -> idle

**Comment by rchiodo** [comment]
Yeah the kernel crashed. Same issue as this one:
https://github.com/ipython/ipython/issues/12704

Your python environment is kinda mismatched. You have Python 3.8 with a much newer IPython. They're likely not compatible. 

You could try:
- Switching to Python 3.10
- Upgrading IPython to the latest bits (```python -m pip install --upgrade IPython``` and ```python -m pip install --upgrade ipykernel```))
