### ISSUE TITLE
support detecting packages in environments created using conda-pack

### ISSUE THREAD

**Issue by vaclavbelak** [microsoft/vscode-jupyter#9330]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

After an upgrade of Jupyter plugin from `2022.2.1010630101` to `2022.2.1020642448` (or later) I no longer can run any notebook - it results it the following error:

```The kernel failed to start due to the missing module 'ipykernel_launcher'. Consider installing this module. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
[Learn more](https://aka.ms/kernelFailuresMissingModule)
```

This is perhaps related to the issue https://github.com/microsoft/vscode-jupyter/issues/9231 . The kernel is global and thus cannot be activated. As a result, the site packages are perhaps not added correctly to the path. The kernel is run remotely inside docker.

### VS Code Version

Version: 1.65.1 Commit: 8908a9ca0f221f36507231afb39d2d8d1e182702 Date: 2022-03-08T02:09:03.269Z Electron: 13.5.2 Chromium: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Linux x64 5.13.0-35-generic

### Jupyter Extension Version

v2022.2.1030672458

### Jupyter logs

```shell
Visual Studio Code (1.65.1, attached-container, desktop)
Jupyter Extension Version: 2022.2.1030672458.
Python Extension Version: 2022.2.1924087327.
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'jupyterEnhancedDataViewer'
Info 10:34:32: ZMQ install verified.
Info 10:34:33: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
Info 10:34:33: Interrupt requested & no kernel.
Info 10:34:33: Setting setActiveController for ~/agentx-data/notebooks/attribution-distribution.ipynb
Info 10:34:33: KernelProvider switched kernel to id = .jvsc74a57bd08fe3fdd79557649874facada13d04ddbe1317ce212365feed75b53cbfabab89f./agentx/bin/python./agentx/bin/python.-m#ipykernel_launcher
Info 10:34:33: Starting Notebook in kernel.ts id = .jvsc74a57bd08fe3fdd79557649874facada13d04ddbe1317ce212365feed75b53cbfabab89f./agentx/bin/python./agentx/bin/python.-m#ipykernel_launcher
Info 10:34:33: Creating raw notebook for ~/agentx-data/notebooks/attribution-distribution.ipynb
Info 10:34:33: Getting preferred kernel for ~/agentx-data/notebooks/attribution-distribution.ipynb
Info 10:34:33: Computing working directory ~/agentx-data/notebooks/attribution-distribution.ipynb
Info 10:34:33: Starting raw kernel Python 3.8.10 64-bit for interpreter /agentx/bin/python
Info 10:34:33: installMissingDependencies /agentx/bin/python
Info 10:34:33: IPyKernel found previously in this environment /agentx/bin/python
Info 10:34:33: Kernel launching with ports 9000,9001,9002,9003,9004. Start port is 9000
Info 10:34:33: Registering dummy command feature
Info 10:34:34: Process Execution: > /agentx/bin/python -m pip list
> /agentx/bin/python -m pip list
Info 10:34:34: Process Execution: > /agentx/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> /agentx/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
Info 10:34:34: Adding env Variable PYTHONNOUSERSITE to /agentx/bin/python
Info 10:34:34: Process Execution: > /agentx/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"c5b38cba-137f-479e-859e-69ee56326647" --shell=9002 --transport="tcp" --iopub=9004 --f=/tmp/tmp-46658ITQgjBs6LwFB.json
> /agentx/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"c5b38cba-137f-479e-859e-69ee56326647" --shell=9002 --transport="tcp" --iopub=9004 --f=/tmp/tmp-46658ITQgjBs6LwFB.json
Info 10:34:34: Process Execution: cwd: ~/agentx-data/notebooks
cwd: ~/agentx-data/notebooks
Warn 10:34:34: StdErr from Kernel Process /agentx/bin/python: No module named ipykernel_launcher

Error 10:34:34: Disposing kernel process due to an error [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /agentx/bin/python: No module named ipykernel_launcher...
	at ChildProcess.<anonymous> (/home/agentx/.vscode-server/extensions/ms-toolsai.jupyter-2022.2.1030672458/out/client/extension.js:2:793563)
	at ChildProcess.emit (events.js:327:22)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)] {
  category: 'kerneldied',
  exitCode: 1,
  stdErr: '/agentx/bin/python: No module named ipykernel_launcher\n'
}
Error 10:34:34: /agentx/bin/python: No module named ipykernel_launcher

Info 10:34:34: Dispose Kernel process
Error 10:34:34: Failed to connect raw kernel session: Error: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /agentx/bin/python: No module named ipykernel_launcher...
Error 10:34:34: failed to create INotebook in kernel, UI Disabled = true [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /agentx/bin/python: No module named ipykernel_launcher...
	at ChildProcess.<anonymous> (/home/agentx/.vscode-server/extensions/ms-toolsai.jupyter-2022.2.1030672458/out/client/extension.js:2:793563)
	at ChildProcess.emit (events.js:327:22)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)] {
  category: 'kerneldied',
  exitCode: 1,
  stdErr: '/agentx/bin/python: No module named ipykernel_launcher\n'
}
Error 10:34:34: failed to start INotebook in kernel, UI Disabled = true [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /agentx/bin/python: No module named ipykernel_launcher...
	at ChildProcess.<anonymous> (/home/agentx/.vscode-server/extensions/ms-toolsai.jupyter-2022.2.1030672458/out/client/extension.js:2:793563)
	at ChildProcess.emit (events.js:327:22)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)] {
  category: 'kerneldied',
  exitCode: 1,
  stdErr: '/agentx/bin/python: No module named ipykernel_launcher\n'
}
Info 10:34:34: ipykernel version 6.9.1 for /agentx/bin/python
Info 10:34:34: ipykernel location ~/.local/lib/python3.8/site-packages/ipykernel/__init__.py for /agentx/bin/python
Info 10:34:36: Creating controller for jupyter-notebook with interpreter /agentx/bin/python
Info 10:34:36: Find preferred kernel for ~/agentx-data/notebooks/attribution-distribution.ipynb with metadata {"kernelspec":{"display_name":"Python 3 (ipykernel)","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.8.10"}} & preferred interpreter /agentx/bin/python
Info 10:34:36: findKernel found base (Python 3.8.5)
Info 10:34:36: PreferredConnection: .jvsc74a57bd04c2b8563932708ac4f64e3bc4797ea8eb43fc7530baa7f01daadf5b46d7b1fd4./opt/miniconda/python./opt/miniconda/python.-m#ipykernel_launcher found for NotebookDocument: ~/agentx-data/notebooks/attribution-distribution.ipynb
Info 10:34:36: TargetController found ID: .jvsc74a57bd04c2b8563932708ac4f64e3bc4797ea8eb43fc7530baa7f01daadf5b46d7b1fd4./opt/miniconda/python./opt/miniconda/python.-m#ipykernel_launcher for document ~/agentx-data/notebooks/attribution-distribution.ipynb
Info 10:34:36: Setting controller affinity for ~/agentx-data/notebooks/attribution-distribution.ipynb .jvsc74a57bd04c2b8563932708ac4f64e3bc4797ea8eb43fc7530baa7f01daadf5b46d7b1fd4./opt/miniconda/python./opt/miniconda/python.-m#ipykernel_launcher
Info 10:34:53: Execute Cells request 2
Info 10:34:53: Execute Cell 2 ~/agentx-data/notebooks/attribution-distribution.ipynb
Info 10:34:53: Starting Notebook in kernel.ts id = .jvsc74a57bd08fe3fdd79557649874facada13d04ddbe1317ce212365feed75b53cbfabab89f./agentx/bin/python./agentx/bin/python.-m#ipykernel_launcher
Info 10:34:53: Creating raw notebook for ~/agentx-data/notebooks/attribution-distribution.ipynb
Info 10:34:53: Getting preferred kernel for ~/agentx-data/notebooks/attribution-distribution.ipynb
Info 10:34:53: Computing working directory ~/agentx-data/notebooks/attribution-distribution.ipynb
Info 10:34:53: Starting raw kernel Python 3.8.10 64-bit for interpreter /agentx/bin/python
Info 10:34:53: installMissingDependencies /agentx/bin/python
Info 10:34:53: IPyKernel found previously in this environment /agentx/bin/python
Info 10:34:53: Kernel launching with ports 9008,9009,9010,9011,9012. Start port is 9000
Info 10:34:53: Adding env Variable PYTHONNOUSERSITE to /agentx/bin/python
Info 10:34:53: Process Execution: > /agentx/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> /agentx/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
Info 10:34:53: Process Execution: > /agentx/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9011 --control=9009 --hb=9008 --Session.signature_scheme="hmac-sha256" --Session.key=b"08943eb3-65de-4242-8f99-4e06e6c9fc06" --shell=9010 --transport="tcp" --iopub=9012 --f=/tmp/tmp-46658MGuUX4D5SnW8.json
> /agentx/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9011 --control=9009 --hb=9008 --Session.signature_scheme="hmac-sha256" --Session.key=b"08943eb3-65de-4242-8f99-4e06e6c9fc06" --shell=9010 --transport="tcp" --iopub=9012 --f=/tmp/tmp-46658MGuUX4D5SnW8.json
Info 10:34:53: Process Execution: cwd: ~/agentx-data/notebooks
cwd: ~/agentx-data/notebooks
Warn 10:34:54: StdErr from Kernel Process /agentx/bin/python: No module named ipykernel_launcher

Error 10:34:54: Disposing kernel process due to an error [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /agentx/bin/python: No module named ipykernel_launcher...
	at ChildProcess.<anonymous> (/home/agentx/.vscode-server/extensions/ms-toolsai.jupyter-2022.2.1030672458/out/client/extension.js:2:793563)
	at ChildProcess.emit (events.js:327:22)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)] {
  category: 'kerneldied',
  exitCode: 1,
  stdErr: '/agentx/bin/python: No module named ipykernel_launcher\n'
}
Error 10:34:54: /agentx/bin/python: No module named ipykernel_launcher

Info 10:34:54: Dispose Kernel process
Error 10:34:54: Failed to connect raw kernel session: Error: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /agentx/bin/python: No module named ipykernel_launcher...
Error 10:34:54: failed to create INotebook in kernel, UI Disabled = false [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /agentx/bin/python: No module named ipykernel_launcher...
	at ChildProcess.<anonymous> (/home/agentx/.vscode-server/extensions/ms-toolsai.jupyter-2022.2.1030672458/out/client/extension.js:2:793563)
	at ChildProcess.emit (events.js:327:22)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)] {
  category: 'kerneldied',
  exitCode: 1,
  stdErr: '/agentx/bin/python: No module named ipykernel_launcher\n'
}
Warn 10:34:54: Kernel Error [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /agentx/bin/python: No module named ipykernel_launcher...
	at ChildProcess.<anonymous> (/home/agentx/.vscode-server/extensions/ms-toolsai.jupyter-2022.2.1030672458/out/client/extension.js:2:793563)
	at ChildProcess.emit (events.js:327:22)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)] {
  category: 'kerneldied',
  exitCode: 1,
  stdErr: '/agentx/bin/python: No module named ipykernel_launcher\n'
}
Error 10:34:54: failed to start INotebook in kernel, UI Disabled = false [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /agentx/bin/python: No module named ipykernel_launcher...
	at ChildProcess.<anonymous> (/home/agentx/.vscode-server/extensions/ms-toolsai.jupyter-2022.2.1030672458/out/client/extension.js:2:793563)
	at ChildProcess.emit (events.js:327:22)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)] {
  category: 'kerneldied',
  exitCode: 1,
  stdErr: '/agentx/bin/python: No module named ipykernel_launcher\n'
}
Error 10:34:54: Failed to execute cells in CellExecutionQueue [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /agentx/bin/python: No module named ipykernel_launcher...
	at ChildProcess.<anonymous> (/home/agentx/.vscode-server/extensions/ms-toolsai.jupyter-2022.2.1030672458/out/client/extension.js:2:793563)
	at ChildProcess.emit (events.js:327:22)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)] {
  category: 'kerneldied',
  exitCode: 1,
  stdErr: '/agentx/bin/python: No module named ipykernel_launcher\n'
}
Info 10:34:54: Cancel pending cells
Info 10:34:54: Cell 2 executed with state Idle
Info 10:34:54: Process Execution: > /agentx/bin/python -c "import ipykernel"
> /agentx/bin/python -c "import ipykernel"
Info 10:34:54: ipykernel version 6.9.1 for /agentx/bin/python
Info 10:34:54: ipykernel location ~/.local/lib/python3.8/site-packages/ipykernel/__init__.py for /agentx/bin/python
Info 10:34:54: Process Execution: > /agentx/bin/python -c "import ipykernel"
> /agentx/bin/python -c "import ipykernel"
```

### Coding Language and Runtime Version

Python 3.8.10

### Language Extension Version (if applicable)

v2022.2.1924087327

### Running Jupyter locally or remotely?

Remote

**Comment by amunger** [comment]
Sorry you're running into this. We made some recent fixes and perhaps not all of them made it into the latest release. You could try the pre-release to see if it works with that.
Also, does it still work when you go back to `2022.2.1010630101`?

**Comment by vaclavbelak** [comment]
Thanks for looking into this! Yes, it does work on `2022.2.1010630101`. I still get the same error with the current pre-release.

**Comment by DonJayamanne** [comment]
@vaclavbelak Thanks for confirming the fact that it works with the previous release.

* Please provide the output for this in the terminal
`/agentx/bin/python --version`
* Please could you type the following in a terminal and let me know the output?
`/agentx/bin/python -c "import ipykernel;print(ipykernel.__file__)"`
* Please could you type the following in a terminal and let me know the output? (please make note of the `-s` flag)
`/agentx/bin/python -c "import ipykernel;print(ipykernel.__file__)"`
* Please could you type the following in a terminal and let me know the output?
`/agentx/bin/python -c "import sys;print(sys.path)"`
* Please could you type the following in a terminal and let me know the output? (please make note of the `-s` flag)
`/agentx/bin/python -s -c "import sys;print(sys.path)"`
* Please could you type the following in a terminal and let me know the output?
`python -c "import site;print(site.getusersitepackages())"`

**Comment by vaclavbelak** [comment]
Here're the outputs:
```
$ /agentx/bin/python --version
Python 3.8.10

$ /agentx/bin/python -c "import ipykernel;print(ipykernel.__file__)"
/home/agentx/.local/lib/python3.8/site-packages/ipykernel/__init__.py

$ /agentx/bin/python -c "import ipykernel;print(ipykernel.__file__)"
/home/agentx/.local/lib/python3.8/site-packages/ipykernel/__init__.py

$ /agentx/bin/python -s -c "import ipykernel;print(ipykernel.__file__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'ipykernel'

$ /agentx/bin/python -c "import sys;print(sys.path)"
['', '/agentx/lib/python38.zip', '/agentx/lib/python3.8', '/agentx/lib/python3.8/lib-dynload', '/home/agentx/.local/lib/python3.8/site-packages', '/home/agentx/agentx-data/schnitzel/pipeline/agentx_research', '/agentx/lib/python3.8/site-packages']

$ /agentx/bin/python -s -c "import sys;print(sys.path)"
['', '/agentx/lib/python38.zip', '/agentx/lib/python3.8', '/agentx/lib/python3.8/lib-dynload', '/agentx/lib/python3.8/site-packages']

$ python -c "import site;print(site.getusersitepackages())"
/home/agentx/.local/lib/python3.8/site-packages

**Comment by DonJayamanne** [comment]
@vaclavbelak has the problem been resolved with the latest release? If not please could you try using the latest pre-release version?

**Comment by vaclavbelak** [comment]
Thanks a lot for getting back to me Don, really appreciate your help!

I tried the latest release `v2022.3.1000901801`, with the same result:
```
Running cells with 'Python 3.8.10 64-bit' requires ipykernel package.
Run the following command to install 'ipykernel' into the Python environment. 
Command: '/agentx/bin/python -m pip install ipykernel -U --user --force-reinstall'
```
I actually tried to run the suggested command, but that didn't help.

I also tried the current pre-release `v2022.4.1000912146` with the same result.

I am attaching the screenshot of the kernels dropdown. The `agentx` environment is created by a `conda-pack` inside a different docker container and then `conda-unpack`ed inside my working container (in order to essentially get rid of unnecessary build-time-only dependencies / libraries). 

![image](https://user-images.githubusercontent.com/9254281/161785370-3b883b26-5754-4c3e-add6-fc22571a8075.png)

**Comment by DonJayamanne** [comment]
> conda-pack

that  explains it. the environment is something that probably needs activation or has the activation scripts, even though you might not activate them.

**Comment by vaclavbelak** [comment]
Yes! After installing the `ipykernel` into the kernel's environment, it started to work. The issue was that the `/agentx` dir (i.e., the unpacked conda environment) was not writable (owned by `root`) and so the `ipykernel` ended up inside the `~/.local` dir where it wasn't seen by the Jupyter plugin. Once I made it writable and properly activated it, it started to work.

Thanks a million Don for your help and for providing this excellent support for Python notebooks in the first-place!

**Comment by rchiodo** [comment]
Skipping verification as customer worked around problem? Not sure what steps we'd take to repro the issue.
