### ISSUE TITLE
Export to html fails with jinja template problem

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#9468]
Nightly build is failing with this error:

```
CSSHTMLHeaderPreprocessor [NbConvertApp] Attempting to load template index.html.j2 [NbConvertApp]     template_paths: /opt/hostedtoolcache/Python/3.9.10/x64/share/jupyter/nbconvert/templates/lab:/opt/hostedtoolcache/Python/3.9.10/x64/share/jupyter/nbconvert/templates/base:/home/runner/.local/share/jupyter:/home/runner/.local/share/jupyter/nbconvert/templates:/home/runner/.local/share/jupyter/nbconvert/templates/compatibility:/opt/hostedtoolcache/Python/3.9.10/x64/share/jupyter:/opt/hostedtoolcache/Python/3.9.10/x64/share/jupyter/nbconvert/templates:/opt/hostedtoolcache/Python/3.9.10/x64/share/jupyter/nbconvert/templates/compatibility:/usr/local/share/jupyter:/usr/local/share/jupyter/nbconvert/templates:/usr/local/share/jupyter/nbconvert/templates/compatibility:/usr/share/jupyter:/usr/share/jupyter/nbconvert/templates:/usr/share/jupyter/nbconvert/templates/compatibility:/opt/hostedtoolcache/Python/3.9.10/x64/share/jupyter/nbconvert/templates Traceback (most recent call last):   File "/opt/hostedtoolcache/Python/3.9.10/x64/bin/jupyter-nbconvert", line 8, in <module>     sys.exit(main())   File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/jupyter_core/application.py", line 264, in launch_instance     return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)   File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/traitlets/config/application.py", line 846, in launch_instance     app.start()   File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 369, in start     self.convert_notebooks()   File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 541, in convert_notebooks     self.convert_single_notebook(notebook_filename)   File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 506, in convert_single_notebook     output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)   File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 435, in export_single_notebook     output, resources = self.exporter.from_filename(notebook_filename, resources=resources)   File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 190, in from_filename     return self.from_file(f, resources=resources, **kw)   File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 208, in from_file     return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)   File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/nbconvert/exporters/html.py", line 210, in from_notebook_node     return super().from_notebook_node(nb, resources, **kw)   File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 392, in from_notebook_node     output = self.template.render(nb=nb_copy, resources=resources)   File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render     self.environment.handle_exception()   File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/jinja2/environment.py", line 926, in handle_exception     raise rewrite_traceback_stack(source=source)   File "/opt/hostedtoolcache/Python/3.9.10/x64/share/jupyter/nbconvert/templates/lab/index.html.j2", line 3, in top-level template code     {% from 'jupyter_widgets.html.j2' import jupyter_widgets %}   File "/opt/hostedtoolcache/Python/3.9.10/x64/share/jupyter/nbconvert/templates/lab/base.html.j2", line 260, in top-level template code     {% set div_id = uuid4() %}   File "/opt/hostedtoolcache/Python/3.9.10/x64/share/jupyter/nbconvert/templates/base/display_priority.j2", line 1, in top-level template code     {%- extends 'base/null.j2' -%}   File "/opt/hostedtoolcache/Python/3.9.10/x64/share/jupyter/nbconvert/templates/base/null.j2", line 24, in top-level template code     {%- block header -%}   File "/opt/hostedtoolcache/Python/3.9.10/x64/share/jupyter/nbconvert/templates/lab/index.html.j2", line 9, in block 'header'     {%- block html_head -%}   File "/opt/hostedtoolcache/Python/3.9.10/x64/share/jupyter/nbconvert/templates/lab/index.html.j2", line 36, in block 'html_head'     {% block notebook_css %}   File "/opt/hostedtoolcache/Python/3.9.10/x64/share/jupyter/nbconvert/templates/lab/index.html.j2", line 37, in block 'notebook_css'     {{ resources.include_css("static/index.css") }}   File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/nbconvert/exporters/html.py", line 216, in resources_include_css     return jinja2.Markup(code) AttributeError: module 'jinja2' has no attribute 'Markup'
```

I can't seem to repro locally. Maybe only on linux does it fail.

**Comment by HankSheehan** [comment]
I'm seeing the same issue. It seems to be that Jinja2 updated and changed where you should import the Markup object from.

https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-1-0

`Markup and escape should be imported from MarkupSafe`

**Comment by rchiodo** [comment]
We probably need another condition here:
https://github.com/microsoft/vscode-jupyter/blob/3cc21c33d477b35cb5183bcb0ca2ca1a96ec87bc/src/kernels/jupyter/import-export/jupyterImporter.ts#L71

**Comment by rchiodo** [comment]
No it looks like this is a bug in nbconvert. Here:
https://github.com/jupyter/nbconvert/issues/1736

**Comment by rchiodo** [comment]
We might forcefully pin jinja2 to something older for the meantime.

**Comment by rchiodo** [comment]
Workaround, downgrade jinja2 to 3.0.3

```
python -m pip install jinja2@3.0.3
```

**Comment by fayddelight** [comment]
> Workaround, downgrade jinja2 to 3.0.3
> 
> ```
> python -m pip install -I jinja2==3.0.3
> ```

thanks that worked for me!

**Comment by LizMcQuillan** [comment]
Downgrading jinga2 doesn't resolve this issue for me. Any other workarounds?

**Comment by thehappycheese** [comment]
Ran into this problem today in vs code - Python 3.9. The work-around suggested by [rchiodo](https://github.com/rchiodo) above worked perfectly for me.

**Comment by MrNickArcher** [comment]
Ran into this problem today. again - Python 3.9. The work-around suggested by [rchiodo](https://github.com/rchiodo) above worked again.
