### ISSUE TITLE
Jupyter notebooks can't run using insiders version

### ISSUE THREAD

**Issue by kyaki** [microsoft/vscode-jupyter#9511]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Updated my VSC-insiders this morning and now I can't run jupyter notebooks, it seems to be having trouble starting the kernel. I was using this notebook fine before the update, and it will work in the regular VSC, but something must have broke in the latest insders update.  I have tried starting different kernels using different python versions, but none of them work. 

### VS Code Version

1.66.0-insider

### Jupyter Extension Version

v2022.4.1000891004

### Jupyter logs

```shell
Info 18:06:42: Execute Cells request 0
Info 18:06:42: Execute Cell 0 ~/projects/BB-499/BB-499_analysis.ipynb
Info 18:06:42: Starting Notebook in kernel.ts id = .jvsc74a57bd0e5083375c393fea27a2cbfaf1c5ebe587d437e1d86df363a30887befcfea78b6./home/kyaki/v_envi/general/python./home/kyaki/v_envi/general/python.-m#ipykernel_launcher for ~/projects/BB-499/BB-499_analysis.ipynb
Info 18:06:42: Checking for server existence.
Info 18:06:42: Checking for server usability.
Info 18:06:42: Starting notebook server.
Info 18:06:42: Connecting to server
Info 18:06:42: Launching server
Info 18:06:42: Starting Notebook
Info 18:06:43: Generating custom default config at /tmp/c0d959a1-287a-4f23-83ae-dc2e00a1eda2/jupyter_notebook_config.py
Info 18:06:43: Starting Jupyter Notebook
Starting Jupyter from ~/.pyenv/versions/3.8.6/bin/python with command line --no-browser --notebook-dir="/home/kyaki/projects/BB-499" --KernelManager.autorestart=False --config=/tmp/c0d959a1-287a-4f23-83ae-dc2e00a1eda2/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
Info 18:06:43: Process Execution: > ~/.pyenv/versions/3.8.6/bin/python -m jupyter notebook --no-browser --notebook-dir="/home/kyaki/projects/BB-499" --KernelManager.autorestart=False --config=/tmp/c0d959a1-287a-4f23-83ae-dc2e00a1eda2/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
> ~/.pyenv/versions/3.8.6/bin/python -m jupyter notebook --no-browser --notebook-dir="/home/kyaki/projects/BB-499" --KernelManager.autorestart=False --config=/tmp/c0d959a1-287a-4f23-83ae-dc2e00a1eda2/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
Info 18:06:43: Waiting for Jupyter Notebook
pyenv: jupyter-notebook: command not found
Info 18:06:44: pyenv: jupyter-notebook: command not found


The `jupyter-notebook' command exists in these Python versions:
Info 18:06:44: pyenv: jupyter-notebook: command not found

The `jupyter-notebook' command exists in these Python versions:

  3.8.6

Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.
Info 18:06:44: pyenv: jupyter-notebook: command not found

The `jupyter-notebook' command exists in these Python versions:
  3.8.6

Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.

Error 18:06:44: failed to create INotebook in kernel, UI Disabled = false [i [Error]: Jupyter server crashed. Unable to connect. 
Error code from jupyter: 127
pyenv: jupyter-notebook: command not found


The `jupyter-notebook' command exists in these Python versions:

  3.8.6

Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.

	at t.JupyterConnectionWaiter.rejectStartPromise (/home/kyaki/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.4.1000891004/out/extension.js:2:357343)
	at t._complete (/home/kyaki/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.4.1000891004/out/extension.js:2:358006)
	at t.n (/home/kyaki/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.4.1000891004/out/extension.js:2:3281174)
	at t.__tryOrUnsub (/home/kyaki/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.4.1000891004/out/extension.js:2:3281416)
	at t.complete (/home/kyaki/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.4.1000891004/out/extension.js:2:3281309)
	at t._complete (/home/kyaki/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.4.1000891004/out/extension.js:2:3279789)
	at t.complete (/home/kyaki/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.4.1000891004/out/extension.js:2:3279488)
	at ChildProcess.<anonymous> (/home/kyaki/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.4.1000891004/out/extension.js:2:821596)
	at Object.onceWrapper (node:events:510:26)
	at ChildProcess.emit (node:events:402:35)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)] {
  category: 'jupyterconnection'
}
Warn 18:06:44: Kernel Error [i [Error]: Jupyter server crashed. Unable to connect. 
Error code from jupyter: 127
pyenv: jupyter-notebook: command not found


The `jupyter-notebook' command exists in these Python versions:

  3.8.6

Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.

	at t.JupyterConnectionWaiter.rejectStartPromise (/home/kyaki/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.4.1000891004/out/extension.js:2:357343)
	at t._complete (/home/kyaki/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.4.1000891004/out/extension.js:2:358006)
	at t.n (/home/kyaki/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.4.1000891004/out/extension.js:2:3281174)
	at t.__tryOrUnsub (/home/kyaki/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.4.1000891004/out/extension.js:2:3281416)
	at t.complete (/home/kyaki/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.4.1000891004/out/extension.js:2:3281309)
	at t._complete (/home/kyaki/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.4.1000891004/out/extension.js:2:3279789)
	at t.complete (/home/kyaki/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.4.1000891004/out/extension.js:2:3279488)
	at ChildProcess.<anonymous> (/home/kyaki/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.4.1000891004/out/extension.js:2:821596)
	at Object.onceWrapper (node:events:510:26)
	at ChildProcess.emit (node:events:402:35)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)] {
  category: 'jupyterconnection'
}
Info 18:06:44: Process Execution: > ~/v_envi/general/bin/python -c "import ipykernel"
> ~/v_envi/general/bin/python -c "import ipykernel"
Info 18:06:44: Dispose kernel file:///home/kyaki/projects/BB-499/BB-499_analysis.ipynb
```

### Running Jupyter locally or remotely?

Remote

**Comment by DonJayamanne** [comment]
Thanks for filing thi s issue, I believe I know what's caused this issue
