### ISSUE TITLE
python is not installed

### ISSUE THREAD

**Issue by MXA404** [microsoft/vscode-jupyter#9532]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

before the jupyter notebook was working fine and the python interpreter are listed in the interpreters but now i can't find them and each time i run a jupyter notebook an error window shows up which contains Python is not installed i install it again but still not working the only kernel on notebook is python 3 and it does not work at all

can you please help

### VS Code Version

the last version downloaded and updated

### Jupyter Extension Version

last version for extension from vs code

### Coding Language and Runtime Version

python

**Comment by rchiodo** [comment]
Thanks for the issue.

Can you go to this pane:

![image](https://user-images.githubusercontent.com/19672699/160879765-6b8999d3-7eca-4436-b2e3-2530446d2ee4.png)

And pick the 'Jupyter' tab and the 'Python' tab and upload the contents of both of them?

We use the python extension to detect python on your machine, so hopefully its output will show why it thinks there's no python installed.

**Comment by MXA404** [comment]
I tried running the jupyter notebook but nothing come up except the windows * usually, when using only the python file it works fine but when i run the jupyter notebook it does not work

![image](https://user-images.githubusercontent.com/102682889/160887481-d6260e69-4875-432a-ab3f-293c0c752540.png)

**Comment by rchiodo** [comment]
Thanks.

Those output logs should tell us why. From your screen shot I suspect the python extension is failing to find python too.

**Comment by MXA404** [comment]
so how can I fix it?

**Comment by rchiodo** [comment]
You need to send us the logs. Then we might be able to tell you how to fix it. 

Logs are here:

![image](https://user-images.githubusercontent.com/19672699/160909499-5f5653f9-2ef1-472f-b15a-5ad9ea8bad45.png)

And here:
![image](https://user-images.githubusercontent.com/19672699/160909575-2340a483-4071-4e84-a041-2a6cd062bfcd.png)

Just copy the contents of those two panes into a comment in this issue. It should say something about what is going wrong.

**Comment by MXA404** [comment]
jupyter:
Visual Studio Code (1.65.2, undefined, desktop)
Jupyter Extension Version: 2022.2.1030672458.
Python Extension Version: 2022.2.1924087327.
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
Info 22:49:22: ZMQ install verified.
Info 22:49:24: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
Warn 22:49:24: Unable to create a controller for jupyter-notebook without an active interpreter.
Info 22:49:27: Find preferred kernel for c:\Users\alshe\Downloads\scanCONTROL-Windows-SDK-4-1\scanCONTROL Windows SDK 4.1\C++ SDK (+python bindings)\python_bindings\examples\ScreenO3d.ipynb with metadata {"language_info":{"name":"python"},"orig_nbformat":4} & preferred interpreter 
Info 22:49:27: Notebook Closed c:\Users\alshe\Downloads\scanCONTROL-Windows-SDK-4-1\scanCONTROL Windows SDK 4.1\C++ SDK (+python bindings)\python_bindings\examples\ScreenO3d.ipynb

python:
Experiment 'pythonaacf' is active
Experiment 'pythonTensorboardExperiment' is active
Experiment 'pythonSurveyNotification' is active
Experiment 'PythonPyTorchProfiler' is active
Experiment 'pythonDeprecatePythonPath' is active
Experiment 'pythonInterpreterInfoPinned' is active
[ERROR 2022-2-30 22:49:24.403]: [SyntaxError: Invalid regular expression: /c:(\\|/)Users(\\|/)alshe(\\|/)Downloads(\\|/)scanCONTROL-Windows-SDK-4-1(\\|/)scanCONTROL Windows SDK 4.1(\\|/)C++ SDK (+python bindings)(\\|/)python_bindings(\\|/)examples/: Nothing to repeat
	at new RegExp (<anonymous>)
	at h (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:104:314759)
	at d.getDisplayCommands (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:104:314538)
	at d.logProcess (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:104:314276)
	at s.emit (events.js:315:20)
	at shellExec (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:52:33373)
	at Object.t.shellExecute (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:24:74737)
	at async Object.t.getInterpreterInfo (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:104:31805)
	at async c.p [as workerFunc] (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:52:5037)
	at async start (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:104:29626)]
[ERROR 2022-2-30 22:49:24.407]: [SyntaxError: Invalid regular expression: /c:(\\|/)Users(\\|/)alshe(\\|/)Downloads(\\|/)scanCONTROL-Windows-SDK-4-1(\\|/)scanCONTROL Windows SDK 4.1(\\|/)C++ SDK (+python bindings)(\\|/)python_bindings(\\|/)examples/: Nothing to repeat
	at new RegExp (<anonymous>)
	at h (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:104:314759)
	at d.getDisplayCommands (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:104:314538)
	at d.logProcess (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:104:314276)
	at s.emit (events.js:315:20)
	at shellExec (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:52:33373)
	at Object.t.shellExecute (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:24:74737)
	at async Object.t.getInterpreterInfo (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:104:31805)
	at async c.p [as workerFunc] (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:52:5037)
	at async start (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:104:29626)]
[ERROR 2022-2-30 22:49:27.213]: [SyntaxError: Invalid regular expression: /c:(\\|/)Users(\\|/)alshe(\\|/)Downloads(\\|/)scanCONTROL-Windows-SDK-4-1(\\|/)scanCONTROL Windows SDK 4.1(\\|/)C++ SDK (+python bindings)(\\|/)python_bindings(\\|/)examples/: Nothing to repeat
	at new RegExp (<anonymous>)
	at h (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:104:314759)
	at d.getDisplayCommands (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:104:314538)
	at d.logProcess (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:104:314276)
	at s.emit (events.js:315:20)
	at shellExec (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:52:33373)
	at Object.t.shellExecute (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:24:74737)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Object.t.getInterpreterInfo (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:104:31805)
	at async c.p [as workerFunc] (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:52:5037)
	at async start (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:104:29626)]
[ERROR 2022-2-30 22:49:27.214]: [SyntaxError: Invalid regular expression: /c:(\\|/)Users(\\|/)alshe(\\|/)Downloads(\\|/)scanCONTROL-Windows-SDK-4-1(\\|/)scanCONTROL Windows SDK 4.1(\\|/)C++ SDK (+python bindings)(\\|/)python_bindings(\\|/)examples/: Nothing to repeat
	at new RegExp (<anonymous>)
	at h (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:104:314759)
	at d.getDisplayCommands (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:104:314538)
	at d.logProcess (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:104:314276)
	at s.emit (events.js:315:20)
	at shellExec (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:52:33373)
	at Object.t.shellExecute (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:24:74737)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Object.t.getInterpreterInfo (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:104:31805)
	at async c.p [as workerFunc] (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:52:5037)
	at async start (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:104:29626)]
[ERROR 2022-2-30 22:49:27.215]: [SyntaxError: Invalid regular expression: /c:(\\|/)Users(\\|/)alshe(\\|/)Downloads(\\|/)scanCONTROL-Windows-SDK-4-1(\\|/)scanCONTROL Windows SDK 4.1(\\|/)C++ SDK (+python bindings)(\\|/)python_bindings(\\|/)examples/: Nothing to repeat
	at new RegExp (<anonymous>)
	at h (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:104:314759)
	at d.getDisplayCommands (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:104:314538)
	at d.logProcess (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:104:314276)
	at s.emit (events.js:315:20)
	at shellExec (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:52:33373)
	at Object.t.shellExecute (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:24:74737)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Object.t.getInterpreterInfo (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:104:31805)
	at async c.p [as workerFunc] (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:52:5037)
	at async start (c:\Users\alshe\.vscode\extensions\ms-python.python-2022.2.1924087327\out\client\extension.js:104:29626)]
Starting Pylance language server.
Diagnostic Code: InvalidPythonInterpreterDiagnostic, Message: No Python interpreter is selected. You need to select a Python interpreter to enable features such as IntelliSense, linting, and debugging.

**Comment by rchiodo** [comment]
Thanks. This looks like a problem with a regular expression in the python extension. I'm transferring your issue there.
