### ISSUE TITLE
Can't get to kernels.

### ISSUE THREAD

**Issue by Imane219** [microsoft/vscode-jupyter#9541]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When I open a .ipynb file and try to run a cell, vscode reminds me to select a kernel but doesn't give me kernel options:
![image](https://user-images.githubusercontent.com/48405078/160985705-01340626-d709-4049-80f7-dbd39e233730.png)
By the way, there isn't a 'select kernel' button on the right.(Jupyter extension is enabled.)

I can only fix this by disable and enable jupyter extension:
![image](https://user-images.githubusercontent.com/48405078/160986306-b3c56055-a461-4274-975e-1764c18a38d8.png)

Once I close the vscode window, I need to reload jupyter extension to get to my kernels, which is quite troublesome.Do you know how can I fix it?

### VS Code Version

1.65.2

### Jupyter Extension Version

v2022.3.1000762011

### Jupyter logs

```shell
Visual Studio Code (1.65.2, undefined, desktop)
Jupyter Extension Version: 2022.3.1000762011.
Python Extension Version: 2022.2.1924087327.
用户属于实验组 'jupyterTestcf'
用户属于实验组 'jupyterEnhancedDataViewer'
Info 13:56:55: ZMQ install verified.
Info 13:56:55: Preferred kernel connection found in cache .jvsc74a57bd06b750eca66b2db11c37c4a63f06fedd6ec40d9dfa4ca31a2738c60986b814367.C:\D\anaconda\envs\pytorch\python.exe.C:\D\anaconda\envs\pytorch\python.exe.-m#ipykernel_launcher
Info 13:56:55: PreferredConnection: .jvsc74a57bd06b750eca66b2db11c37c4a63f06fedd6ec40d9dfa4ca31a2738c60986b814367.C:\D\anaconda\envs\pytorch\python.exe.C:\D\anaconda\envs\pytorch\python.exe.-m#ipykernel_launcher found for NotebookDocument: c:\D\0\experiments\adversarial_distillation\test.py.ipynb
Info 13:56:55: Early registration of controller for Kernel connection .jvsc74a57bd06b750eca66b2db11c37c4a63f06fedd6ec40d9dfa4ca31a2738c60986b814367.C:\D\anaconda\envs\pytorch\python.exe.C:\D\anaconda\envs\pytorch\python.exe.-m#ipykernel_launcher
Info 13:56:55: TargetController found ID: .jvsc74a57bd06b750eca66b2db11c37c4a63f06fedd6ec40d9dfa4ca31a2738c60986b814367.C:\D\anaconda\envs\pytorch\python.exe.C:\D\anaconda\envs\pytorch\python.exe.-m#ipykernel_launcher for document c:\D\0\experiments\adversarial_distillation\test.py.ipynb
Info 13:56:55: Setting controller affinity for c:\D\0\experiments\adversarial_distillation\test.py.ipynb .jvsc74a57bd06b750eca66b2db11c37c4a63f06fedd6ec40d9dfa4ca31a2738c60986b814367.C:\D\anaconda\envs\pytorch\python.exe.C:\D\anaconda\envs\pytorch\python.exe.-m#ipykernel_launcher
Info 13:56:55: Checking for server existence.
Info 13:56:55: Checking for server usability.
Info 13:56:55: Starting notebook server.
Info 13:56:55: Connecting to server
Info 13:56:55: Connecting to process server
Info 13:56:55: Connecting server kernel http://127.0.0.1:8888/
连接到位于 http://127.0.0.1:8888/ 的 Jupyter 服务器
Info 13:56:55: Creating server with settings : {"baseUrl":"http://127.0.0.1:8888/","appUrl":"","wsUrl":"ws://127.0.0.1:8888/","token":"2f701f53f9054cfe7da60c366e6b40dcc6eb8c78783de09a","appendToken":true,"init":{"cache":"no-store","credentials":"same-origin"}}
Info 13:56:55: Connection complete server
Info 13:56:55: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
Info 13:56:55: Server started.
Info 13:56:55: Creating controller for jupyter-notebook with interpreter C:\D\anaconda\envs\pytorch\python.exe
Info 13:56:55: Creating server with settings : {"baseUrl":"http://127.0.0.1:8888/","appUrl":"","wsUrl":"ws://127.0.0.1:8888/","token":"2f701f53f9054cfe7da60c366e6b40dcc6eb8c78783de09a","appendToken":true,"init":{"cache":"no-store","credentials":"same-origin"}}
Info 13:56:55: Disposing session manager
Info 13:56:55: SessionManager - dispose contents manager
Info 13:56:55: ShutdownSessionAndConnection - dispose session manager
Info 13:56:55: Finished disposing jupyter session manager
Error 13:56:55: Failed to get remote kernel connections [FetchError: request to http://127.0.0.1:8888/api/kernels?1648706215403 failed, reason: connect ECONNREFUSED 127.0.0.1:8888
	at ClientRequest.<anonymous> (c:\Users\14456\.vscode\extensions\ms-toolsai.jupyter-2022.3.1000762011\out\client\extension.js:2:3955403)
	at ClientRequest.emit (events.js:315:20)
	at Socket.socketErrorListener (_http_client.js:469:9)
	at Socket.emit (events.js:315:20)
	at emitErrorNT (internal/streams/destroy.js:106:8)
	at emitErrorCloseNT (internal/streams/destroy.js:74:3)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)]
Info 13:56:55: Creating server with settings : {"baseUrl":"http://127.0.0.1:8888/","appUrl":"","wsUrl":"ws://127.0.0.1:8888/","token":"2f701f53f9054cfe7da60c366e6b40dcc6eb8c78783de09a","appendToken":true,"init":{"cache":"no-store","credentials":"same-origin"}}
Info 13:56:55: Disposing session manager
Info 13:56:55: SessionManager - dispose contents manager
Info 13:56:55: ShutdownSessionAndConnection - dispose session manager
Error 13:56:55: SessionManager cannot enumerate kernelspecs. Returning default {}.
Info 13:56:55: Finished disposing jupyter session manager
Error 13:56:55: Failed to get remote kernel connections [FetchError: request to http://127.0.0.1:8888/api/kernels?1648706215436 failed, reason: connect ECONNREFUSED 127.0.0.1:8888
	at ClientRequest.<anonymous> (c:\Users\14456\.vscode\extensions\ms-toolsai.jupyter-2022.3.1000762011\out\client\extension.js:2:3955403)
	at ClientRequest.emit (events.js:315:20)
	at Socket.socketErrorListener (_http_client.js:469:9)
	at Socket.emit (events.js:315:20)
	at emitErrorNT (internal/streams/destroy.js:106:8)
	at emitErrorCloseNT (internal/streams/destroy.js:74:3)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)]
Error 13:56:55: SessionManager cannot enumerate kernelspecs. Returning default {}.
Info 13:56:56: Registering dummy command feature
Info 13:56:56: Process Execution: > C:\D\anaconda\envs\pytorch\python.exe -m pip list
> C:\D\anaconda\envs\pytorch\python.exe -m pip list
Info 13:56:57: Got activated conda env vars ourselves for C:\D\anaconda\envs\pytorch\python.exe in 1804
```

### Coding Language and Runtime Version

Python 3.8.12

### Language Extension Version (if applicable)

Python Extension. v2022.2.1924087327

### Anaconda Version (if applicable)

conda 4.12.0

### Running Jupyter locally or remotely?

Remote

**Comment by IanMatthewHuff** [comment]
@Imane219 Question here. Exactly what type of setup are you connecting to? It looks to me like you have a remote server configured, but are just running it locally on the same machine?

**Comment by Enrico68** [comment]
same problem here

**Comment by Imane219** [comment]
> @Imane219 Question here. Exactly what type of setup are you connecting to? It looks to me like you have a remote server configured, but are just running it locally on the same machine?

It seems like jupyter extension will automatically connect to remote server once I reload it. But it failed, and the logs are described above. 
![image](https://user-images.githubusercontent.com/48405078/161881066-9785c5f7-eaf7-40f3-8147-055a87442bd4.png)

If I choose to manually specify server, it pop up the bellowing error:
![image](https://user-images.githubusercontent.com/48405078/161880431-b0aff667-4287-4daf-9979-a3e2346ae6cc.png)

**Comment by Enrico68** [comment]
Sorry was using VS-Codium. Installed VS-Code fixed the problem
