### ISSUE TITLE
Jupyter won't activate with new Insiders

### ISSUE THREAD

**Issue by alyssajotice** [microsoft/vscode-jupyter#9590]
## Environment data

VS Code:
Version: 1.67.0-insider (user setup)
Commit: 345f572e37ca69dc143c9fecb5f851fba9fcce8c
Date: 2022-04-05T10:43:52.479Z
Electron: 17.3.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.22000

-   Jupyter Extension version (available under the Extensions sidebar): v2022.3.1000901801
-   Python Extension version (available under the Extensions sidebar): v2022.4.0
-   Python and/or Anaconda version: 3.7.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): n/a
-   Jupyter server running: Local | Remote |: Local

Computer:
System type	64-bit operating system, x64-based processor
Edition	Windows 11 Enterprise
Version	21H2
Installed on	‎10/‎11/‎2021
OS build	22000.556
Experience	Windows Feature Experience Pack 1000.22000.556.0

On today's version of Insiders, Jupyter will not activate because it is using notebook APIs that have been removed by VS Code. 

`onDidChangeCellMetadata` has been removed in favor of `onDidChangeNotebookDocument`.

The pre-release version of the extension works as expected. I see Jupyter has adopted the new APIs in the pre-release version of the extension, but the Release Version currently does not work. 

New APIs: https://github.com/microsoft/vscode/blob/cdb839aa63e04f939bf8587b009621ed2712220e/src/vscode-dts/vscode.proposed.notebookDocumentEvents.d.ts

<details>
  <summary>Console:</summary>

  ```
[Extension Host] extension activation failed TypeError: s.notebooks.onDidChangeCellMetadata is not a function
    at u.addEventHandlers (c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2022.3.1000901801\out\extension.js:2:735175)
    at new u (c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2022.3.1000901801\out\extension.js:2:733840)
    at Object.t.resolveInstance (c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2022.3.1000901801\out\extension.js:2:2667221)
    at c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2022.3.1000901801\out\extension.js:2:2669159
    at Array.map (<anonymous>)
    at Object.t.resolveInstance (c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2022.3.1000901801\out\extension.js:2:2666995)
    at c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2022.3.1000901801\out\extension.js:2:2669159
    at Object.t.resolve (c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2022.3.1000901801\out\extension.js:2:2669422)
    at c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2022.3.1000901801\out\extension.js:2:2652835
    at e._get (c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2022.3.1000901801\out\extension.js:2:2652601)
    at e.get (c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2022.3.1000901801\out\extension.js:2:2651244)
    at e.dynamicValue (c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2022.3.1000901801\out\extension.js:2:2674821)
    at c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2022.3.1000901801\out\extension.js:2:2668648
    at c (c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2022.3.1000901801\out\extension.js:2:2667664)
    at c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2022.3.1000901801\out\extension.js:2:2668588
    at c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2022.3.1000901801\out\extension.js:2:2668077
    at Array.map (<anonymous>)
    at c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2022.3.1000901801\out\extension.js:2:2668049
    at Array.map (<anonymous>)
    at Object.t.resolveInstance (c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2022.3.1000901801\out\extension.js:2:2666995)
    at c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2022.3.1000901801\out\extension.js:2:2669159
    at Object.t.resolve (c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2022.3.1000901801\out\extension.js:2:2669422)
    at c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2022.3.1000901801\out\extension.js:2:2652835
    at e._get (c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2022.3.1000901801\out\extension.js:2:2652601)
    at e.get (c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2022.3.1000901801\out\extension.js:2:2651244)
    at a.get (c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2022.3.1000901801\out\extension.js:2:1109349)
    at c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2022.3.1000901801\out\extension.js:2:4538183
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2022.3.1000901801\out\extension.js:2:4535892
    at e.activate (c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2022.3.1000901801\out\extension.js:2:4535127)
    at _activate (c:\Users\allytice\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:8154)
    at _waitForDepsThenActivate (c:\Users\allytice\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:8096)
    at _initialize (c:\Users\allytice\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:7460) (at c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2022.3.1000901801\out\extension.js:2:4538891)

```
</details>

## Expected behaviour
Jupyter activates in VS Code Insiders. 

## Actual behaviour
Jupyter does not activate.

## Steps to reproduce:
Install today's Insiders. Install latest stable version of Jupyter notebooks. Open a .ipynb file and try to activate extension. 

<img width="344" alt="image" src="https://user-images.githubusercontent.com/22576531/161786498-3cb57865-777d-4e53-91b5-f650852619c9.png">

**Comment by firegate22** [comment]
I can confirm this :(

**Comment by rchiodo** [comment]
Thanks for the issue but I believe this is expected. Insiders can break extensions. You should be able to switch to the preview version of the Jupyter extension instead.

**Comment by DonJayamanne** [comment]
Re-opening as I think we'll need to fix this, else all users on insiders with stable builds are broken.
This is one of the main reasons why we're warned about using proposed API.
We can discuss in stand up whether we need to fix or not, hence opening for now.

**Comment by DonJayamanne** [comment]
> ou should be able to switch to the preview version of the Jupyter extension instead.

Closing as this is the solution or install VS Code stable.

**Comment by firegate22** [comment]
Hey folks: I don't know if that belongs here or to the remote ssh extension, but it's not possible to switch to the pre-release versions of extensions via remote ssh.

Just fyi:
https://github.com/microsoft/vscode-remote-release/issues/6575

**Comment by Kein** [comment]
Having the same issue:
Jupyter v2021.9.1101343141
Vscode 1.67.1

**Comment by rchiodo** [comment]
@Kein that version of the extension isn't supported on VS code 1.67. Extensions are not generally forwards compatible.

**Comment by Kein** [comment]
@rchiodo that is latest available to me from defaul MS marketplace repo

**Comment by rchiodo** [comment]
Not sure what marketplace you're looking at, but the latest should be this one (as of me writing this comment)

![image](https://user-images.githubusercontent.com/19672699/167720550-6466a087-e1ee-4761-a02d-78cfebefd7ef.png)

That's for stable.
