### ISSUE TITLE
Interactive plots not working via remote ssh

### ISSUE THREAD

**Issue by pasassi** [microsoft/vscode-jupyter#9597]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I have a working environment in a remote server that have GPUs. I work in ubuntu 20.04 and the server also runs ubuntu 20.04, I like the remote ssh extension for running my scripts and notebooks in the server. However, when trying to plot interactive plots, these do not render.

For instance, working with matplotlib I am able to plot inline plots with ```%matplotlib inline``` but when I use ```%matplotlib widget``` or ```%matplotlib qt``` (interactive) the cell runs properly but nothing is showed (In the case of "qt" the cells keeps running, as it does in a local environment until the pop up window with the figure is closed).

Interactive plots are very useful for getting fast insights in some figures. 

I also tried opening a parallel ```ssh -X user@server``` connection as I found in this [answer](https://stackoverflow.com/questions/57152770/open-a-matplotlib-figure-through-ssh-tunnel-of-vscode)

But still no luck.

### VS Code Version

Version: 1.66.0 Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5 Date: 2022-03-30T05:50:41.156Z Electron: 17.2.0 Chromium: 98.0.4758.109 Node.js: 16.13.0 V8: 9.8.177.11-electron.0 OS: Linux x64 5.13.0-39-generic

### Jupyter Extension Version

v2022.3.1000901801

### Jupyter logs

```shell
There are no outputs
```

### Coding Language and Runtime Version

Python v3.8.10

### Language Extension Version (if applicable)

Python v2022.4.0

### Running Jupyter locally or remotely?

Remote

**Comment by rchiodo** [comment]
Thanks for the issue.

`%matplotlib qt5` is definitely never going to work. It would be displaying the UI on the remote machine. 
`%matplotlib widget` should work. 

Can you go to 'Help | Toggle Developer Tools' and copy the contents of the console log here? It might be the widget can't be loaded from the CDN for some reason.

**Comment by pasassi** [comment]
Hi thanks for your reply.
Here it is the console log output after running the cell with ```%matplotlib widget```

At the beginning this is the output
```
WidgetManager: Loading class LayoutModel:@jupyter-widgets/base:1.2.0
ipywidgets.js:2 require promise
ipywidgets.js:2 WidgetManager: Loading class MPLCanvasModel:jupyter-matplotlib:^0.10.5
```
After some minutes new logs are showed:
```
ipywidgetsKernel.js:2 Timeout waiting to get widget source for jupyter-matplotlib, ^0.10.5
(anonymous) @ ipywidgetsKernel.js:2
setTimeout (async)
n.loadWidgetScript @ ipywidgetsKernel.js:2
loadWidgetScript @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgets.js:2
Promise.catch (async)
loadClass @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
j @ ipywidgets.js:2
e._make_model @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
j @ ipywidgets.js:2
e.new_model @ ipywidgets.js:2
e.handle_comm_open @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
_handleCommOpen @ ipywidgetsKernel.js:2
await in _handleCommOpen (async)
_handleMessage @ ipywidgetsKernel.js:2
await in _handleMessage (async)
(anonymous) @ ipywidgetsKernel.js:2
Promise.then (async)
_onWSMessage @ ipywidgetsKernel.js:2
e.handleMessage @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
u @ ipywidgetsKernel.js:2
e.handleMessage @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
u @ ipywidgetsKernel.js:2
e.handleKernelMessage @ ipywidgetsKernel.js:2
fire @ notebookWebviewPreloads.js:3
(anonymous) @ notebookWebviewPreloads.js:3
postMessage (async)
(anonymous) @ main.js:1034
channel.port1.onmessage @ main.js:281
```
```
ipywidgets.js:2 require promise
```
```
workbench.desktop.main.js:1287 Error: Unable to read file 'vscode-remote://ssh-remote+medusa16/vscode-resource?{"requestResourcePath":"/home/psassi/datos/deep-profiles/jupyter-matplotlib.js"}' (Error: Unable to resolve nonexistent file 'vscode-remote://ssh-remote+medusa16/vscode-resource?{"requestResourcePath":"/home/psassi/datos/deep-profiles/jupyter-matplotlib.js"}')
    at p.doReadFileStream (workbench.desktop.main.js:610:33842)
    at async w (workbench.desktop.main.js:1287:33393)
    at async n.loadResource (workbench.desktop.main.js:1350:19549)
```

```
VM13:4          GET https://vscode-remote+ssh-002dremote-002bmedusa16.vscode-resource.vscode-webview.net/home/psassi/datos/deep-profiles/jupyter-matplotlib.js net::ERR_ABORTED 404
req.load @ VM13:4
load @ VM13:4
load @ VM13:4
fetch @ VM13:4
check @ VM13:4
enable @ VM13:4
enable @ VM13:4
eval @ VM13:4
eval @ VM13:4
each @ VM13:4
enable @ VM13:4
init @ VM13:4
eval @ VM13:4
setTimeout (async)
req.nextTick @ VM13:4
o @ VM13:4
requirejs @ VM13:4
(anonymous) @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
Promise.catch (async)
loadClass @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
j @ ipywidgets.js:2
e._make_model @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
j @ ipywidgets.js:2
e.new_model @ ipywidgets.js:2
e.handle_comm_open @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
_handleCommOpen @ ipywidgetsKernel.js:2
await in _handleCommOpen (async)
_handleMessage @ ipywidgetsKernel.js:2
await in _handleMessage (async)
(anonymous) @ ipywidgetsKernel.js:2
Promise.then (async)
_onWSMessage @ ipywidgetsKernel.js:2
e.handleMessage @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
u @ ipywidgetsKernel.js:2
e.handleMessage @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
u @ ipywidgetsKernel.js:2
e.handleKernelMessage @ ipywidgetsKernel.js:2
fire @ notebookWebviewPreloads.js:3
(anonymous) @ notebookWebviewPreloads.js:3
postMessage (async)
(anonymous) @ main.js:1034
channel.port1.onmessage @ main.js:281
```
```
ipywidgets.js:2 Could not instantiate widget
(anonymous) @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
s @ ipywidgets.js:2
Promise.then (async)
A @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
j @ ipywidgets.js:2
e._make_model @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
j @ ipywidgets.js:2
e.new_model @ ipywidgets.js:2
e.handle_comm_open @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
_handleCommOpen @ ipywidgetsKernel.js:2
await in _handleCommOpen (async)
_handleMessage @ ipywidgetsKernel.js:2
await in _handleMessage (async)
(anonymous) @ ipywidgetsKernel.js:2
Promise.then (async)
_onWSMessage @ ipywidgetsKernel.js:2
e.handleMessage @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
u @ ipywidgetsKernel.js:2
e.handleMessage @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
u @ ipywidgetsKernel.js:2
e.handleKernelMessage @ ipywidgetsKernel.js:2
fire @ notebookWebviewPreloads.js:3
(anonymous) @ notebookWebviewPreloads.js:3
postMessage (async)
(anonymous) @ main.js:1034
channel.port1.onmessage @ main.js:281
ipywidgets.js:2 Error: Could not create a model.
    at ipywidgets.js:2:3545904
    at async g._handleCommOpen (ipywidgetsKernel.js:2:36487)
    at async g._handleMessage (ipywidgetsKernel.js:2:38387)
(anonymous) @ ipywidgets.js:2
Promise.catch (async)
e.handle_comm_open @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
_handleCommOpen @ ipywidgetsKernel.js:2
await in _handleCommOpen (async)
_handleMessage @ ipywidgetsKernel.js:2
await in _handleMessage (async)
(anonymous) @ ipywidgetsKernel.js:2
Promise.then (async)
_onWSMessage @ ipywidgetsKernel.js:2
e.handleMessage @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
u @ ipywidgetsKernel.js:2
e.handleMessage @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
u @ ipywidgetsKernel.js:2
e.handleKernelMessage @ ipywidgetsKernel.js:2
fire @ notebookWebviewPreloads.js:3
(anonymous) @ notebookWebviewPreloads.js:3
postMessage (async)
(anonymous) @ main.js:1034
channel.port1.onmessage @ main.js:281
```

```
ipywidgetsKernel.js:2 Exception opening new comm
_handleCommOpen @ ipywidgetsKernel.js:2
await in _handleCommOpen (async)
_handleMessage @ ipywidgetsKernel.js:2
await in _handleMessage (async)
(anonymous) @ ipywidgetsKernel.js:2
Promise.then (async)
_onWSMessage @ ipywidgetsKernel.js:2
e.handleMessage @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
u @ ipywidgetsKernel.js:2
e.handleMessage @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
u @ ipywidgetsKernel.js:2
e.handleKernelMessage @ ipywidgetsKernel.js:2
fire @ notebookWebviewPreloads.js:3
(anonymous) @ notebookWebviewPreloads.js:3
postMessage (async)
(anonymous) @ main.js:1034
channel.port1.onmessage @ main.js:281
```

```
ipywidgets.js:2 WidgetManager: Loading class LayoutModel:@jupyter-widgets/base:1.2.0
```

```
ipywidgets.js:2 require promise
```

```
ipywidgets.js:2 Uncaught (in promise) Error: Module jupyter-matplotlib, semver range ^0.10.5 is not registered as a widget module
    at vC.loadClass (ipywidgets.js:2:3954334)
    at vC.loadClass (ipywidgets.js:2:4213737)
    at vC.<anonymous> (ipywidgets.js:2:3553069)
    at ipywidgets.js:2:3549781
    at Object.next (ipywidgets.js:2:3549886)
    at ipywidgets.js:2:3548822
    at new Promise (<anonymous>)
    at j (ipywidgets.js:2:3548567)
    at vC.e._make_model (ipywidgets.js:2:3552948)
    at vC.<anonymous> (ipywidgets.js:2:3552802)
loadClass @ ipywidgets.js:2
loadClass @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
j @ ipywidgets.js:2
e._make_model @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
j @ ipywidgets.js:2
e.new_model @ ipywidgets.js:2
e.handle_comm_open @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
_handleCommOpen @ ipywidgetsKernel.js:2
Promise.then (async)
e.register_model @ ipywidgets.js:2
register_model @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
j @ ipywidgets.js:2
e.new_model @ ipywidgets.js:2
e.handle_comm_open @ ipywidgets.js:2
(anonymous) @ ipywidgets.js:2
_handleCommOpen @ ipywidgetsKernel.js:2
await in _handleCommOpen (async)
_handleMessage @ ipywidgetsKernel.js:2
await in _handleMessage (async)
(anonymous) @ ipywidgetsKernel.js:2
Promise.then (async)
_onWSMessage @ ipywidgetsKernel.js:2
e.handleMessage @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
u @ ipywidgetsKernel.js:2
e.handleMessage @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
(anonymous) @ ipywidgetsKernel.js:2
u @ ipywidgetsKernel.js:2
e.handleKernelMessage @ ipywidgetsKernel.js:2
fire @ notebookWebviewPreloads.js:3
(anonymous) @ notebookWebviewPreloads.js:3
postMessage (async)
(anonymous) @ main.js:1034
channel.port1.onmessage @ main.js:281
ipywidgets.js:2 Uncaught (in promise) Error: Module jupyter-matplotlib, semver range ^0.10.5 is not registered as a widget module
    at vC.loadClass (ipywidgets.js:2:3954334)
    at vC.loadClass (ipywidgets.js:2:4213737)
    at vC.<anonymous> (ipywidgets.js:2:3553069)
    at ipywidgets.js:2:3549781
    at Object.next (ipywidgets.js:2:3549886)
    at ipywidgets.js:2:3548822
    at new Promise (<anonymous>)
    at j (ipywidgets.js:2:3548567)
    at vC.e._make_model (ipywidgets.js:2:3552948)
    at vC.<anonymous> (ipywidgets.js:2:3552802)
```

Some of this errors keep showing

**Comment by rchiodo** [comment]
That means we couldn't read from the CDN on that machine and the widget isn't available in the python environment. 

Can you double check that you have ipympl in that environment? (https://github.com/matplotlib/ipympl#installation)

And from the remote machine can you get to here: https://www.jsdelivr.com/?query=jupyter-matplotlib?

Our jupyter output should be saying something about accessing the CDN. You can get to that here:

![image](https://user-images.githubusercontent.com/19672699/162019004-cc99d034-8daf-4327-a768-4f0a226c6cfe.png)

**Comment by pasassi** [comment]
I tried:
```
pip install ipympl
```

All requirements are allready satisfied.

Doing ```curl https://www.jsdelivr.com/?query=jupyter-matplotlib``` gives as output of the website in html.

This is the output of Jupyter after running a cell with ```%matplotlib widget``` 👍🏽 

```
Info 13:34:42: Execute Cells request 25
Info 13:34:42: Execute Cell 25 ~/datos/deep-profiles/don.ipynb
Info 13:34:42: [32mFetch Script for {"moduleName":"jupyter-matplotlib","moduleVersion":"^0.10.5"}
Info 13:34:42: [32mFetch Script for jupyter-matplotlib
Info 13:34:42: [32mScript for jupyter-matplotlib, is https://vscode-remote%2Bssh-002dremote-002bmedusa16.vscode-resource.vscode-webview.net/home/psassi/.vscode-server/extensions/ms-toolsai.jupyter-2022.3.1000901801/tmp/scripts/nbextensions/0b7f98d43c5cf81204bc03586c65837e474ad47fa6c81de3bcb3d42a9441fac0index.js from local
Info 13:34:42: [32mFetch Script for {"moduleName":"jupyter-matplotlib","moduleVersion":"^0.10.5"}
Info 13:34:42: [32mFetch Script for jupyter-matplotlib
Info 13:34:42: [32mFetch Script for {"moduleName":"jupyter-matplotlib","moduleVersion":"^0.10.5"}
Info 13:34:42: [32mFetch Script for jupyter-matplotlib
Info 13:34:42: [32mScript for jupyter-matplotlib, is https://vscode-remote%2Bssh-002dremote-002bmedusa16.vscode-resource.vscode-webview.net/home/psassi/.vscode-server/extensions/ms-toolsai.jupyter-2022.3.1000901801/tmp/scripts/nbextensions/0b7f98d43c5cf81204bc03586c65837e474ad47fa6c81de3bcb3d42a9441fac0index.js from local
Info 13:34:42: [32mScript for jupyter-matplotlib, is https://vscode-remote%2Bssh-002dremote-002bmedusa16.vscode-resource.vscode-webview.net/home/psassi/.vscode-server/extensions/ms-toolsai.jupyter-2022.3.1000901801/tmp/scripts/nbextensions/0b7f98d43c5cf81204bc03586c65837e474ad47fa6c81de3bcb3d42a9441fac0index.js from local
Error 13:34:42: Widget load failure [object Object] {
  className: 'MPLCanvasModel',
  moduleName: 'jupyter-matplotlib',
  moduleVersion: '^0.10.5',
  cdnsUsed: false,
  isOnline: true,
  timedout: false,
  error: {}
}
Error 13:34:42: Widget load failure [object Object] {
  className: 'ToolbarModel',
  moduleName: 'jupyter-matplotlib',
  moduleVersion: '^0.10.5',
  cdnsUsed: false,
  isOnline: true,
  timedout: false,
  error: {}
}
Error 13:34:42: Widget load failure [object Object] {
  className: 'ToolbarModel',
  moduleName: 'jupyter-matplotlib',
  moduleVersion: '^0.10.5',
  cdnsUsed: false,
  isOnline: true,
  timedout: false,
  error: {}
}
Info 13:34:42: Cell 25 executed with state Success
```

Apparently the CDN is set to ```cdnsUsed: false``` But I don't really know what is CDN.

**Comment by rchiodo** [comment]
Our CDN setting is here:

![image](https://user-images.githubusercontent.com/19672699/162025761-ca2d3fc1-3312-4b69-acbc-8813f523a581.png)

**Comment by pasassi** [comment]
When running:

```
import ipywidgets
ipywidgets.__version__
```
This is the version
'7.6.5'

**Comment by rchiodo** [comment]
Can you try these two pieces of code?

```
import ipywidgets as widgets
widgets.IntSlider()
```
Should show a slider

```
import ipywidgets as widgets
widgets.Text(value='Hello World!', disabled=True)
```
Should show a disable text box

**Comment by pasassi** [comment]
> Our CDN setting is here:
> 
> ![image](https://user-images.githubusercontent.com/19672699/162025761-ca2d3fc1-3312-4b69-acbc-8813f523a581.png)

In my remote settings I have the following:

"jupyter.widgetScriptSources": [
        "jsdelivr.com",
        "unpkg.com"
    ]

**Comment by pasassi** [comment]
> import ipywidgets as widgets
> widgets.Text(value='Hello World!', disabled=True)

Both pieces of code run Ok!
![Screenshot from 2022-04-06 13-51-47](https://user-images.githubusercontent.com/67416815/162026989-7ceb1ee4-1a2c-4e27-97db-efbb6f60784a.png)

**Comment by rchiodo** [comment]
Hmm, this here is puzzling:
```
workbench.desktop.main.js:1287 Error: Unable to read file 'vscode-remote://ssh-remote+medusa16/vscode-resource?{"requestResourcePath":"/home/psassi/datos/deep-profiles/jupyter-matplotlib.js"}' (Error: Unable to resolve nonexistent file 'vscode-remote://ssh-remote+medusa16/vscode-resource?{"requestResourcePath":"/home/psassi/datos/deep-profiles/jupyter-matplotlib.js"}')
    at p.doReadFileStream (workbench.desktop.main.js:610:33842)
    at async w (workbench.desktop.main.js:1287:33393)
    at async n.loadResource (workbench.desktop.main.js:1350:19549)
```

That path isn't one we'd ask for. I wonder if this is a request from within another widget (not our code) and it's not rerouted correctly in remote SSH. 

Unfortunately I can't get ssh to anything to work right now so I can't try your scenario in remote SSH (just remote WSL which works fine).

**Comment by rchiodo** [comment]
What's the exact code you're using for plotting?

I was able to setup an SSH connection finally and it's working for me with this code here:

![image](https://user-images.githubusercontent.com/19672699/162037168-1ad86a46-4fcf-4fdb-ae2f-a6568a29fffb.png)

**Comment by rchiodo** [comment]
My setup is latest VS code stable and latest Jupyter Extension stable.

**Comment by rchiodo** [comment]
No it is interactive:

![image](https://user-images.githubusercontent.com/19672699/162041174-6cc14e04-c253-4fe6-b99c-7f862c7f6c35.png)

And it's using the ipywidget renderer
![image](https://user-images.githubusercontent.com/19672699/162041305-5032a4a8-75cd-486c-9efa-813bd86e1e82.png)

So that same code for you doesn't work?

Here's the exact cells I ran:

```
import ipywidgets as widgets
print(widgets.__version__)
import ipympl
print(ipympl.__version__)
import matplotlib
print(matplotlib.__version__)
```

```
%matplotlib widget
```

```
import matplotlib.pyplot as plt
import numpy as np
import os

x = np.arange(10)

fig = plt.figure()
plt.plot(x)
```
```

**Comment by pasassi** [comment]
Here it is an example running in my local environment:

![Screenshot from 2022-04-06 15-14-53](https://user-images.githubusercontent.com/67416815/162041345-688b09a9-f291-44ec-866e-b99c72eb2a6d.png)

As you can see, in the bottom is displayed the x and y coordinates and the value of the field between square brackets.

**Comment by pasassi** [comment]
In my remote, following your example:

![Screenshot from 2022-04-06 15-20-06](https://user-images.githubusercontent.com/67416815/162042153-05a1538e-d5de-4b8d-a662-fd364a0ff1f2.png)

**Comment by rchiodo** [comment]
What's listed in your remote extensions?

**Comment by rchiodo** [comment]
Oh and I think you clicked on the '...' next to the text. What does the </> next to the image show?

**Comment by pasassi** [comment]
Remote extensions:

![Screenshot from 2022-04-06 15-26-03](https://user-images.githubusercontent.com/67416815/162043233-1ca6c66e-1505-4452-a1c1-94b21ee4dcdb.png)

**Comment by pasassi** [comment]
When I click on </>

![Screenshot from 2022-04-06 15-27-53](https://user-images.githubusercontent.com/67416815/162043512-254068e8-211e-45f2-baf7-54e322d78d3b.png)

there is no output

**Comment by rchiodo** [comment]
And you still have the widget errors in the 'Developer Console'?

**Comment by pasassi** [comment]
I've just created a new virtual-environment from scratch.

I only installed matplotlib, numpy and ipympl

Same problem

**Comment by pasassi** [comment]
> And you still have the widget errors in the 'Developer Console'?

Yes, the same errors are displayed

**Comment by rchiodo** [comment]
Is it the same version of ipywidgets? Mine is slightly newer.

My ipywidget output is this:

![image](https://user-images.githubusercontent.com/19672699/162044331-5f67745b-4bed-44b5-86a2-a778a85150c3.png)

(Running out of ideas on why it wouldn't work). And without us being able to repro, it's unlikely we can fix this.

**Comment by pasassi** [comment]
I just updated to 7.7.0 and still no output

**Comment by rchiodo** [comment]
Can you copy the entirety of the 'Help | Developer Tools' console to a file and upload it?

There should be a bunch of stuff before the error you're seeing. If those other outputs are missing, maybe there's a problem loading the jupyter extension's stuff into the webview.

For example, I have this stuff in my working console:

![image](https://user-images.githubusercontent.com/19672699/162046219-1da895f2-d67d-445e-a6ef-d53baaee0345.png)

The one that I think likely matters is the custom require.js.

**Comment by pasassi** [comment]
Here it is the entire console output:

[Full_output.txt](https://github.com/microsoft/vscode-jupyter/files/8429860/Full_output.txt)

**Comment by rchiodo** [comment]
Are you sure that's the whole thing? It's missing a bunch of stuff that happens before we even try running the kernel.

Oh maybe all the levels are not set. What does this drop down show? You need to pick all of the levels:

![image](https://user-images.githubusercontent.com/19672699/162057586-9ffabccf-ceef-4fb3-b52b-33fbc795f47b.png)

**Comment by pasassi** [comment]
Verbose was missing!

[Full_output2.txt](https://github.com/microsoft/vscode-jupyter/files/8430126/Full_output2.txt)

**Comment by rchiodo** [comment]
Did you clear it? That looks like just the output after the failure. Can you reload the VS code window and send the full log from startup? 

For example, there should be something from the remote ssh extension in there:

![image](https://user-images.githubusercontent.com/19672699/162060385-f2351d2e-c43b-495f-93ea-44a7c15bc908.png)

**Comment by pasassi** [comment]
Sorry for that again!

I restarted VScode and run the cells again:

[Full_output3.txt](https://github.com/microsoft/vscode-jupyter/files/8430169/Full_output3.txt)

**Comment by rchiodo** [comment]
Oh and then like a minute later you get the rest of it? I think the problem might be in the remote extension host then. We can't communicate from the desktop UI to the remote extension where the scripts are actually being loaded. 

We've had some complaints along these lines before. I wonder if we can instead just load these files directly from the CDN from within the webview itself (instead of trying to send ourselves a message to get them).

**Comment by rchiodo** [comment]
@roblourens @alexdima @tanhakabir Do you know of any instances where messages might get dropped between the desktop client and the remote extension host?

I think what's happening is this:
- UI makes request to remote host for a widget script
- Request lands here: https://github.com/microsoft/vscode-jupyter/blob/f0e4c167df6a3784ae3e7fa5bfd0411e7134e7f1/src/kernels/ipywidgets-message-coordination/ipyWidgetScriptSource.node.ts#L217
- Request succeeds (meaning we find the script) as indicated by the log output `Info 13:34:42: �[32mScript for jupyter-matplotlib, is https://vscode-remote%2Bssh-002dremote-002bmedusa16.vscode-resource.vscode-webview.net/home/psassi/.vscode-server/extensions/ms-toolsai.jupyter-2022.3.1000901801/tmp/scripts/nbextensions/0b7f98d43c5cf81204bc03586c65837e474ad47fa6c81de3bcb3d42a9441fac0index.js from local`
- Message is posted to UI with the contents of the script.
- Script fails to get there as indicated in the delay in the console output from the user.
- Eventually it times out and user gets this: ```ipywidgets.js:2 Could not instantiate widget```


The reason I ask is because I see this in the output log which I thought might indicate the message queue being bottled up:

```
workbench.desktop.main.js:71 [Extension Host] ApplicationInsights:Sender (2) ['Ingestion endpoint could not be reached 80 consecu…y be resulting telemetry loss. Most recent error:', {…}]
```

**Comment by alexdima** [comment]
@rchiodo At the lowest level messages cannot be dropped. All messages from the desktop client to the remote extension host are sequentialized and assigned sequential ids. If either party receives a message id that is not sequential, it will detect this and will [ask the other party to resend their messages](https://github.com/microsoft/vscode/blob/d3b7727faefd31c8bf145cd0033339c0d57981de/src/vs/base/parts/ipc/common/ipc.net.ts#L946-L959). This might only happen after multiple reconnection attempts, where multiple TCP/IP sockets are involved between both sides, in which case messages might be delivered out of order across multiple sockets. But otherwise, in a normal session (i.e. without any reconnection), TCP/IP guarantees in order and lossless delivery. Given this issue does not specify anything about reconnection, simply TCP/IP guarantees in order and lossless delivery here.

However, I think there are some higher-level message passing protocols built on top of this `extHost.protocol` that might be specific to notebooks and I don't know enough about them to have an opinion if they could be dropping messages or not. cc @rebornix

**Comment by mjbvz** [comment]
@rchiodo I don't have a great grasp of the issue but if you think there's a problem with messages being dropped, you can try debugging the webview communications:

- Receiving message in renderer from webview: https://github.com/microsoft/vscode/blob/1e0d2c2f013b5208e61aa0c5516f4c6371dd7da1/src/vs/workbench/contrib/webview/browser/webviewElement.ts#L241

- Receiving message in webview from renderer: https://github.com/microsoft/vscode/blob/996345f4fae8fc3cf1881cb19313097b034f4a90/src/vs/workbench/contrib/webview/browser/pre/main.js#L1030


Or the notebook communications (which uses the webview message passing api):

- Receiving message in renderer from notebook's webview: https://github.com/microsoft/vscode/blob/9d673ebe3464057f9836b6193f70ce9afa01fca1/src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts#L557

- Receiving in notebook's webview from renderer: https://github.com/microsoft/vscode/blob/9d673ebe3464057f9836b6193f70ce9afa01fca1/src/vs/workbench/contrib/notebook/browser/view/renderers/webviewPreloads.ts#L1059


Webviews should work fine in remote ssh AFAIK so my guess would be either that something isn't loading properly or that there's something special with the notebook code

**Comment by rchiodo** [comment]
Thanks @mjbvz but the problem doesn't repro locally. It's only on the customer's machine. 

Is there logging we can add to trace what might be happening?

**Comment by mjbvz** [comment]
Not today. However if you think the issue is somewhere in VS Code core, perhaps you can start by adding some travel logging to where notebooks send/receive messages. It's going to be pretty chatty and I'm not sure it will actual help identify the issue though

Do you have any extra tracing/logging you can add on the Jupyter side based on what you think may be happening?

**Comment by rchiodo** [comment]
I could likely add more tracing on the Web side. On the extension side, this message is in indicating we sent something:

```
Info 13:34:42: �[32mScript for jupyter-matplotlib, is https://vscode-remote%2Bssh-002dremote-002bmedusa16.vscode-resource.vscode-webview.net/home/psassi/.vscode-server/extensions/ms-toolsai.jupyter-2022.3.1000901801/tmp/scripts/nbextensions/0b7f98d43c5cf81204bc03586c65837e474ad47fa6c81de3bcb3d42a9441fac0index.js from local
```

**Comment by greazer** [comment]
May be affected by https://github.com/microsoft/vscode/issues/138784

**Comment by greazer** [comment]
After discussion, suggestion was to add logging within vscode core.
