### ISSUE TITLE
VSC  Insider 1.67 and Jupyter NB extension incompatible

### ISSUE THREAD

**Issue by ekhomin** [microsoft/vscode-jupyter#9602]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Unable to select a kernel using Remote SSH when working with IPYNB files.
Unable to run Jupyter NB on Remote SSH.

### VS Code Version

Version: 1.67.0-insider (user setup) Commit: 345f572e37ca69dc143c9fecb5f851fba9fcce8c Date: 2022-04-05T10:43:52.479Z Electron: 17.3.1 Chromium: 98.0.4758.141 Node.js: 16.13.0 V8: 9.8.177.13-electron.0 OS: Windows_NT x64 10.0.19042

### Jupyter Extension Version

v2022.3.1000901801

### Jupyter logs

```shell
Visual Studio Code - Insiders (1.67.0-insider, ssh-remote, desktop)
Jupyter Extension Version: 2022.3.1000901801.
Python Extension Version: 2022.4.0.
Workspace folder ~/prefect
Info 05:30:57: ZMQ install verified.
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
Error 05:31:01: extension activation failed [TypeError: s.notebooks.onDidChangeCellMetadata is not a function
	at u.addEventHandlers (/home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:735175)
	at new u (/home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:733840)
	at Object.t.resolveInstance (/home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2667221)
	at /home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2669159
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2666995)
	at /home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2669159
	at Object.t.resolve (/home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2669422)
	at /home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2652835
	at e._get (/home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2652601)
	at e.get (/home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2651244)
	at e.dynamicValue (/home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2674821)
	at /home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2668648
	at c (/home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2667664)
	at /home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2668588
	at /home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2668077
	at Array.map (<anonymous>)
	at /home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2668049
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2666995)
	at /home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2669159
	at Object.t.resolve (/home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2669422)
	at /home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2652835
	at e._get (/home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2652601)
	at e.get (/home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2651244)
	at a.get (/home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:1109349)
	at /home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:4538183
	at async /home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:4535892
	at async e.activate (/home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:4535127)
	at async S._activate (/home/ekhomin/.vscode-server-insiders/bin/345f572e37ca69dc143c9fecb5f851fba9fcce8c/out/vs/workbench/api/node/extensionHostProcess.js:85:8154)
	at async S._waitForDepsThenActivate (/home/ekhomin/.vscode-server-insiders/bin/345f572e37ca69dc143c9fecb5f851fba9fcce8c/out/vs/workbench/api/node/extensionHostProcess.js:85:8096)
	at async S._initialize (/home/ekhomin/.vscode-server-insiders/bin/345f572e37ca69dc143c9fecb5f851fba9fcce8c/out/vs/workbench/api/node/extensionHostProcess.js:85:7460)]
Error 05:31:01: Failed to active the Jupyter Extension [TypeError: s.notebooks.onDidChangeCellMetadata is not a function
	at u.addEventHandlers (/home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:735175)
	at new u (/home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:733840)
	at Object.t.resolveInstance (/home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2667221)
	at /home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2669159
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2666995)
	at /home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2669159
	at Object.t.resolve (/home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2669422)
	at /home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2652835
	at e._get (/home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2652601)
	at e.get (/home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2651244)
	at e.dynamicValue (/home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2674821)
	at /home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2668648
	at c (/home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2667664)
	at /home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2668588
	at /home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2668077
	at Array.map (<anonymous>)
	at /home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2668049
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (/home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2666995)
	at /home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2669159
	at Object.t.resolve (/home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2669422)
	at /home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2652835
	at e._get (/home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2652601)
	at e.get (/home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:2651244)
	at a.get (/home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:1109349)
	at /home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:4538183
	at async /home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:4535892
	at async e.activate (/home/ekhomin/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:4535127)
	at async S._activate (/home/ekhomin/.vscode-server-insiders/bin/345f572e37ca69dc143c9fecb5f851fba9fcce8c/out/vs/workbench/api/node/extensionHostProcess.js:85:8154)
	at async S._waitForDepsThenActivate (/home/ekhomin/.vscode-server-insiders/bin/345f572e37ca69dc143c9fecb5f851fba9fcce8c/out/vs/workbench/api/node/extensionHostProcess.js:85:8096)
	at async S._initialize (/home/ekhomin/.vscode-server-insiders/bin/345f572e37ca69dc143c9fecb5f851fba9fcce8c/out/vs/workbench/api/node/extensionHostProcess.js:85:7460)]
```

### Running Jupyter locally or remotely?

Remote

**Comment by firegate22** [comment]
Good morning: search first: https://github.com/microsoft/vscode-jupyter/issues/9590

**Comment by rchiodo** [comment]
Thanks for the issue. This is not something we support in the insiders build. Insiders can break extensions at any time. Please see the comments in #9590
