### ISSUE TITLE
Python/Jupyter pre-release extension installation fails on Remote SSH

### ISSUE THREAD

**Issue by firegate22** [microsoft/vscode-jupyter#9651]
- VSCode Version: 
Version: 1.67.0-insider (Universal)
Commit: f050b17dacedba13962244b13c70084a473d08f7
Date: 2022-04-06T05:15:27.397Z (8 hrs ago)
- Local OS Version: macOs 12.3.1 / arm
- Remote OS Version: Centos 7
- Remote Extension/Connection Type: SSH
- Logs:

Steps to Reproduce:

1. Start SSH Session
2. Get the popup, hey Python and Jupyter extensions have pre-release versions or install / switch to pre-release on the extension page
3.  Error (but the extensions shows the pre-release state), but afaik that's not the case 

Note: I removed the vs code server on the remote host and did a new installation (starting from locally with the remote extensions versions), but it actually just installs the stable version on the remote and then the switch is not possible. It should actually consider and install the same version that is used locally, shouldn't it?

Can't install pre-release version of 'ms-toolsai.jupyter' extension because it is not compatible with the current version of Visual Studio Code - Insiders (version 1.67.0-insider).

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?:No

logs: 
[2022-04-06 15:51:45.599] [renderer1] [info] Downloading the 'ms-toolsai.jupyter' extension locally and install
[2022-04-06 15:51:45.626] [renderer1] [error] Can't install pre-release version of 'ms-toolsai.jupyter' extension because it is not compatible with the current version of Visual Studio Code - Insiders (version 1.67.0-insider).: IncompatiblePreRelease: Can't install pre-release version of 'ms-toolsai.jupyter' extension because it is not compatible with the current version of Visual Studio Code - Insiders (version 1.67.0-insider).
    at l.checkAndGetCompatible (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3132:5311)
    at async l.downloadAndInstall (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3132:4068)
    at async l.installFromGallery (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3132:3238)
    at async Promise.all (index 0)
    at async Object.j [as settled] (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:71:22545)
    at async Ms.installFromGallery (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3126:22894)

**Comment by DonJayamanne** [comment]
> [2022-04-06 15:51:45.626] [renderer1] [error] Can't install pre-release version of 'ms-toolsai.jupyter' extension because it is not compatible with the current version of Visual Studio Code - Insiders (version 1.67.0-insider).: IncompatiblePreRelease: Can't install pre-release version of 'ms-toolsai.jupyter' extension because it is not compatible with the current version of Visual Studio Code - Insiders (version 1.67.0-insider).

This is an error thrown by VS Code, not sure what an extension can do about this.

@tanhakabir I'm transferring this back to VS Code.
