### ISSUE TITLE
The kernel failed to start due to the missing module ''...'

### ISSUE THREAD

**Issue by TomBugnon** [microsoft/vscode-jupyter#9672]
### Applies To

- [X] Notebooks (.ipynb files)
- [x] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Hi all,

I am connected on a server using Remote SSH v0.78
On the server I have a basic python3.10 environment created with conda, in which I only installed ipykernel installed (with conda).
IPython works properly.
When opening a notebook in  VSCode or trying to run a cell I get the following error in red beneath the cell: 
```
The kernel failed to start due to the missing module ''numpy''. Consider installing this module.

View Jupyter [log](command:jupyter.viewOutput) for further details.
```

Note that I tried with another environment with several other installed packages and the missing module was `msvcrt`, not numpy

If I install jupyter/jupyterlab in my environment I have no issue running jupyter in the browser but same error in vscode.

I tried a couple other versions of Jupyter extension with no luck.

Thanks for your help

### VS Code Version

Version: 1.66.1 Commit: 8dfae7a5cd50421d10cd99cb873990460525a898 Date: 2022-04-06T14:49:47.400Z (6 days ago) Electron: 17.2.0 Chromium: 98.0.4758.109 Node.js: 16.13.0 V8: 9.8.177.11-electron.0 OS: Darwin x64 19.6.0

### Jupyter Extension Version

v2022.3.1000901801

### Jupyter logs

```shell
Info 12:40:29: Execute Cells request 0
Info 12:40:29: Execute Cell 0 ~/projects/ecephys/ecephys/units/example.ipynb
Info 12:40:29: Starting Notebook in kernel.ts id = .jvsc74a57bd0490ceddc62b74534fb609617b3a61fa04e4a00d7e135c84747e97ad6c1b1875e./home/tbugnon/miniconda3/envs/jupyter/python./home/tbugnon/miniconda3/envs/jupyter/python.-m#ipykernel_launcher for ~/projects/ecephys/ecephys/units/example.ipynb
Info 12:40:29: Creating raw notebook for ~/projects/ecephys/ecephys/units/example.ipynb
Info 12:40:29: Getting preferred kernel for ~/projects/ecephys/ecephys/units/example.ipynb
Info 12:40:29: Computing working directory ~/projects/ecephys/ecephys/units/example.ipynb
Info 12:40:29: Starting raw kernel jupyter (Python 3.10.4) for interpreter ~/miniconda3/envs/jupyter/bin/python
Info 12:40:29: Kernel launching with ports 9061,9062,9063,9064,9065. Start port is 9000
Info 12:40:30: Process Execution: > ~/miniconda3/envs/jupyter/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> ~/miniconda3/envs/jupyter/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
Info 12:40:30: Adding env Variable PYTHONNOUSERSITE to ~/miniconda3/envs/jupyter/bin/python
Info 12:40:30: Process Execution: > ~/miniconda3/envs/jupyter/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9064 --control=9062 --hb=9061 --Session.signature_scheme="hmac-sha256" --Session.key=b"604cf390-9c98-4fb6-ae92-006936ccb906" --shell=9063 --transport="tcp" --iopub=9065 --f=/tmp/tmp-3795732geL9umyTFuSm.json
> ~/miniconda3/envs/jupyter/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9064 --control=9062 --hb=9061 --Session.signature_scheme="hmac-sha256" --Session.key=b"604cf390-9c98-4fb6-ae92-006936ccb906" --shell=9063 --transport="tcp" --iopub=9065 --f=/tmp/tmp-3795732geL9umyTFuSm.json
Info 12:40:30: Process Execution: cwd: ~/projects/ecephys/ecephys/units
cwd: ~/projects/ecephys/ecephys/units
Warn 12:40:30: StdErr from Kernel Process Traceback (most recent call last):
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/subprocess.py", line 69, in <module>
    import msvcrt

Warn 12:40:30: StdErr from Kernel Process ModuleNotFoundError: No module named 'msvcrt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/site-packages/ipykernel/connect.py", line 8, in <module>
    from subprocess import Popen, PIPE
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/subprocess.py", line 75, in <module>
    import select
  File "/home/tbugnon/projects/ecephys/ecephys/units/select.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

Error 12:40:30: Disposing kernel process due to an error [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: Traceback (most recent call last):
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/subprocess.py", line 69, in <module>
    import msvcrt
ModuleNotFoundError: No module named 'msvcrt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/site-packages/ipykernel/connect.py", line 8, in <module>
    from subprocess import Popen, PIPE
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/subprocess.py", line 75, in <module>
    import select
  File "/home/tbugnon/projects/ecephys/ecephys/units/select.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'...
	at ChildProcess.<anonymous> (/home/tbugnon/.vscode-server/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:512309)
	at ChildProcess.emit (node:events:402:35)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)] {
  category: 'kerneldied',
  kernelConnectionMetadata: {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: '/home/tbugnon/.vscode-server/extensions/ms-toolsai.jupyter-2022.3.1000901801/temp/jupyter/kernels/python3104jvsc74a57bd0490ceddc62b74534fb609617b3a61fa04e4a00d7e135c84747e97ad6c1b1875e/kernel.json',
      interpreterPath: '/home/tbugnon/miniconda3/envs/jupyter/bin/python',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'python3104jvsc74a57bd0490ceddc62b74534fb609617b3a61fa04e4a00d7e135c84747e97ad6c1b1875e',
      argv: [Array],
      language: 'python',
      path: 'python',
      display_name: "Python 3.10.4 ('jupyter')",
      metadata: [Object],
      env: {},
      interrupt_mode: undefined
    },
    interpreter: {
      id: '/home/tbugnon/miniconda3/envs/jupyter/bin/python',
      sysPrefix: '/home/tbugnon/miniconda3/envs/jupyter',
      envType: 'Conda',
      envName: 'jupyter',
      envPath: '/home/tbugnon/miniconda3/envs/jupyter',
      path: '/home/tbugnon/miniconda3/envs/jupyter/bin/python',
      architecture: 3,
      sysVersion: '3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0]',
      version: [Object],
      companyDisplayName: 'Anaconda, Inc.',
      displayName: "Python 3.10.4 ('jupyter')",
      detailedDisplayName: "Python 3.10.4 ('jupyter': conda)"
    },
    id: '.jvsc74a57bd0490ceddc62b74534fb609617b3a61fa04e4a00d7e135c84747e97ad6c1b1875e./home/tbugnon/miniconda3/envs/jupyter/python./home/tbugnon/miniconda3/envs/jupyter/python.-m#ipykernel_launcher'
  },
  exitCode: 1,
  stdErr: 'Traceback (most recent call last):\n' +
    '  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/subprocess.py", line 69, in <module>\n' +
    '    import msvcrt\n' +
    "ModuleNotFoundError: No module named 'msvcrt'\n" +
    '\n' +
    'During handling of the above exception, another exception occurred:\n' +
    '\n' +
    'Traceback (most recent call last):\n' +
    '  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/runpy.py", line 196, in _run_module_as_main\n' +
    '    return _run_code(code, main_globals, None,\n' +
    '  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/runpy.py", line 86, in _run_code\n' +
    '    exec(code, run_globals)\n' +
    '  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/site-packages/ipykernel_launcher.py", line 15, in <module>\n' +
    '    from ipykernel import kernelapp as app\n' +
    '  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/site-packages/ipykernel/__init__.py", line 2, in <module>\n' +
    '    from .connect import *\n' +
    '  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/site-packages/ipykernel/connect.py", line 8, in <module>\n' +
    '    from subprocess import Popen, PIPE\n' +
    '  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/subprocess.py", line 75, in <module>\n' +
    '    import select\n' +
    '  File "/home/tbugnon/projects/ecephys/ecephys/units/select.py", line 1, in <module>\n' +
    '    import numpy as np\n' +
    "ModuleNotFoundError: No module named 'numpy'\n"
}
Error 12:40:30: Traceback (most recent call last):
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/subprocess.py", line 69, in <module>
    import msvcrt
ModuleNotFoundError: No module named 'msvcrt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/site-packages/ipykernel/connect.py", line 8, in <module>
    from subprocess import Popen, PIPE
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/subprocess.py", line 75, in <module>
    import select
  File "/home/tbugnon/projects/ecephys/ecephys/units/select.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

Info 12:40:30: Dispose Kernel process
Error 12:40:30: Failed to connect raw kernel session: Error: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: Traceback (most recent call last):
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/subprocess.py", line 69, in <module>
    import msvcrt
ModuleNotFoundError: No module named 'msvcrt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/site-packages/ipykernel/connect.py", line 8, in <module>
    from subprocess import Popen, PIPE
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/subprocess.py", line 75, in <module>
    import select
  File "/home/tbugnon/projects/ecephys/ecephys/units/select.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'...
Error 12:40:30: failed to create INotebook in kernel, UI Disabled = false [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: Traceback (most recent call last):
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/subprocess.py", line 69, in <module>
    import msvcrt
ModuleNotFoundError: No module named 'msvcrt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/site-packages/ipykernel/connect.py", line 8, in <module>
    from subprocess import Popen, PIPE
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/subprocess.py", line 75, in <module>
    import select
  File "/home/tbugnon/projects/ecephys/ecephys/units/select.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'...
	at ChildProcess.<anonymous> (/home/tbugnon/.vscode-server/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:512309)
	at ChildProcess.emit (node:events:402:35)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)] {
  category: 'kerneldied',
  kernelConnectionMetadata: {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: '/home/tbugnon/.vscode-server/extensions/ms-toolsai.jupyter-2022.3.1000901801/temp/jupyter/kernels/python3104jvsc74a57bd0490ceddc62b74534fb609617b3a61fa04e4a00d7e135c84747e97ad6c1b1875e/kernel.json',
      interpreterPath: '/home/tbugnon/miniconda3/envs/jupyter/bin/python',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'python3104jvsc74a57bd0490ceddc62b74534fb609617b3a61fa04e4a00d7e135c84747e97ad6c1b1875e',
      argv: [Array],
      language: 'python',
      path: 'python',
      display_name: "Python 3.10.4 ('jupyter')",
      metadata: [Object],
      env: {},
      interrupt_mode: undefined
    },
    interpreter: {
      id: '/home/tbugnon/miniconda3/envs/jupyter/bin/python',
      sysPrefix: '/home/tbugnon/miniconda3/envs/jupyter',
      envType: 'Conda',
      envName: 'jupyter',
      envPath: '/home/tbugnon/miniconda3/envs/jupyter',
      path: '/home/tbugnon/miniconda3/envs/jupyter/bin/python',
      architecture: 3,
      sysVersion: '3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0]',
      version: [Object],
      companyDisplayName: 'Anaconda, Inc.',
      displayName: "Python 3.10.4 ('jupyter')",
      detailedDisplayName: "Python 3.10.4 ('jupyter': conda)"
    },
    id: '.jvsc74a57bd0490ceddc62b74534fb609617b3a61fa04e4a00d7e135c84747e97ad6c1b1875e./home/tbugnon/miniconda3/envs/jupyter/python./home/tbugnon/miniconda3/envs/jupyter/python.-m#ipykernel_launcher'
  },
  exitCode: 1,
  stdErr: 'Traceback (most recent call last):\n' +
    '  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/subprocess.py", line 69, in <module>\n' +
    '    import msvcrt\n' +
    "ModuleNotFoundError: No module named 'msvcrt'\n" +
    '\n' +
    'During handling of the above exception, another exception occurred:\n' +
    '\n' +
    'Traceback (most recent call last):\n' +
    '  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/runpy.py", line 196, in _run_module_as_main\n' +
    '    return _run_code(code, main_globals, None,\n' +
    '  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/runpy.py", line 86, in _run_code\n' +
    '    exec(code, run_globals)\n' +
    '  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/site-packages/ipykernel_launcher.py", line 15, in <module>\n' +
    '    from ipykernel import kernelapp as app\n' +
    '  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/site-packages/ipykernel/__init__.py", line 2, in <module>\n' +
    '    from .connect import *\n' +
    '  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/site-packages/ipykernel/connect.py", line 8, in <module>\n' +
    '    from subprocess import Popen, PIPE\n' +
    '  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/subprocess.py", line 75, in <module>\n' +
    '    import select\n' +
    '  File "/home/tbugnon/projects/ecephys/ecephys/units/select.py", line 1, in <module>\n' +
    '    import numpy as np\n' +
    "ModuleNotFoundError: No module named 'numpy'\n"
}
Warn 12:40:30: Kernel Error [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: Traceback (most recent call last):
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/subprocess.py", line 69, in <module>
    import msvcrt
ModuleNotFoundError: No module named 'msvcrt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/site-packages/ipykernel/connect.py", line 8, in <module>
    from subprocess import Popen, PIPE
  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/subprocess.py", line 75, in <module>
    import select
  File "/home/tbugnon/projects/ecephys/ecephys/units/select.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'...
	at ChildProcess.<anonymous> (/home/tbugnon/.vscode-server/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:512309)
	at ChildProcess.emit (node:events:402:35)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)] {
  category: 'kerneldied',
  kernelConnectionMetadata: {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: '/home/tbugnon/.vscode-server/extensions/ms-toolsai.jupyter-2022.3.1000901801/temp/jupyter/kernels/python3104jvsc74a57bd0490ceddc62b74534fb609617b3a61fa04e4a00d7e135c84747e97ad6c1b1875e/kernel.json',
      interpreterPath: '/home/tbugnon/miniconda3/envs/jupyter/bin/python',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'python3104jvsc74a57bd0490ceddc62b74534fb609617b3a61fa04e4a00d7e135c84747e97ad6c1b1875e',
      argv: [Array],
      language: 'python',
      path: 'python',
      display_name: "Python 3.10.4 ('jupyter')",
      metadata: [Object],
      env: {},
      interrupt_mode: undefined
    },
    interpreter: {
      id: '/home/tbugnon/miniconda3/envs/jupyter/bin/python',
      sysPrefix: '/home/tbugnon/miniconda3/envs/jupyter',
      envType: 'Conda',
      envName: 'jupyter',
      envPath: '/home/tbugnon/miniconda3/envs/jupyter',
      path: '/home/tbugnon/miniconda3/envs/jupyter/bin/python',
      architecture: 3,
      sysVersion: '3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0]',
      version: [Object],
      companyDisplayName: 'Anaconda, Inc.',
      displayName: "Python 3.10.4 ('jupyter')",
      detailedDisplayName: "Python 3.10.4 ('jupyter': conda)"
    },
    id: '.jvsc74a57bd0490ceddc62b74534fb609617b3a61fa04e4a00d7e135c84747e97ad6c1b1875e./home/tbugnon/miniconda3/envs/jupyter/python./home/tbugnon/miniconda3/envs/jupyter/python.-m#ipykernel_launcher'
  },
  exitCode: 1,
  stdErr: 'Traceback (most recent call last):\n' +
    '  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/subprocess.py", line 69, in <module>\n' +
    '    import msvcrt\n' +
    "ModuleNotFoundError: No module named 'msvcrt'\n" +
    '\n' +
    'During handling of the above exception, another exception occurred:\n' +
    '\n' +
    'Traceback (most recent call last):\n' +
    '  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/runpy.py", line 196, in _run_module_as_main\n' +
    '    return _run_code(code, main_globals, None,\n' +
    '  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/runpy.py", line 86, in _run_code\n' +
    '    exec(code, run_globals)\n' +
    '  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/site-packages/ipykernel_launcher.py", line 15, in <module>\n' +
    '    from ipykernel import kernelapp as app\n' +
    '  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/site-packages/ipykernel/__init__.py", line 2, in <module>\n' +
    '    from .connect import *\n' +
    '  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/site-packages/ipykernel/connect.py", line 8, in <module>\n' +
    '    from subprocess import Popen, PIPE\n' +
    '  File "/home/tbugnon/miniconda3/envs/jupyter/lib/python3.10/subprocess.py", line 75, in <module>\n' +
    '    import select\n' +
    '  File "/home/tbugnon/projects/ecephys/ecephys/units/select.py", line 1, in <module>\n' +
    '    import numpy as np\n' +
    "ModuleNotFoundError: No module named 'numpy'\n"
}
Info 12:40:30: Process Execution: > ~/miniconda3/envs/jupyter/bin/python -c "import ipykernel"
> ~/miniconda3/envs/jupyter/bin/python -c "import ipykernel"
Info 12:40:30: ipykernel version 6.9.1 for ~/miniconda3/envs/jupyter/bin/python
Info 12:40:30: ipykernel location ~/miniconda3/envs/jupyter/lib/python3.10/site-packages/ipykernel/__init__.py for ~/miniconda3/envs/jupyter/bin/python
Info 12:40:30: Dispose kernel file:///home/tbugnon/projects/ecephys/ecephys/units/example.ipynb
Info 12:40:30: Process Execution: > ~/miniconda3/envs/jupyter/bin/python -c "import ipykernel"
> ~/miniconda3/envs/jupyter/bin/python -c "import ipykernel"
```

### Coding Language and Runtime Version

Python v3.10.4

### Language Extension Version (if applicable)

v2022.4.1

### Anaconda Version (if applicable)

4.11.0

### Running Jupyter locally or remotely?

Remote

**Comment by rchiodo** [comment]
Thanks for the issue.

We don't actually use jupyter to launch a kernel but rather launch it directly. So our startup is slightly different.

I believe this is the root cause though:

```
    '  File "/home/tbugnon/projects/ecephys/ecephys/units/select.py", line 1, in <module>\n' +
    '    import numpy as np\n' +
    "ModuleNotFoundError: No module named 'numpy'\n"
```

You have a module named 'select.py' which is messing up the loading of the kernel. This code exists in subprocess.py:

```
try:
    import msvcrt    <-- This fails (as expected)
    import _winapi
    _mswindows = True
except ModuleNotFoundError:
    _mswindows = False
    import _posixsubprocess
    import select   <-- This is importing your module instead of the builtin select.
    import selectors
```


You should rename your 'select.py' to something else. 

This likely works in Jupyter because the current working directory is different.

**Comment by TomBugnon** [comment]
Thanks for the lightning fast response. Moving the notebook elsewhere or renaming `select.py` does the trick. That was sneaky ha
Best
