### ISSUE TITLE
Code autocompletion no longer works for available installed libraries or loaded functions from libraries

### ISSUE THREAD

**Issue by pehkawn** [microsoft/vscode-jupyter#9724]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

As the headline states, code autocompletion no longer works for installed third-party libraries, functions from loaded third-party libraries, and variables stored in the environment. This used to work before a recent update to VS Code and extensions came a few days/weeks ago.

### VS Code Version

1.66.2

### Jupyter Extension Version

v2022.3.1000901801

### Jupyter logs

```shell
Visual Studio Code (1.66.2, undefined, desktop)
Jupyter Extension Version: 2022.3.1000901801.
Python Extension Version: 2022.4.1.
Workspace folder ~/path/to/folder/
Info 15:40:32: ZMQ install verified.
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
Info 15:40:33: Preferred kernel connection found in cache .jvsc74a57bd04f3954d651899a5d99c746c1b71d4210ccd4fbf98e873a93aaa5d3e1db1e72a0./home/user/.julia/conda/3/python./home/user/.julia/conda/3/python.-m#ipykernel_launcher
Info 15:40:33: PreferredConnection: .jvsc74a57bd04f3954d651899a5d99c746c1b71d4210ccd4fbf98e873a93aaa5d3e1db1e72a0./home/user/.julia/conda/3/python./home/user/.julia/conda/3/python.-m#ipykernel_launcher found for NotebookDocument: ~/path/to/folder/file.ipynb
Info 15:40:33: Early registration of controller for Kernel connection .jvsc74a57bd04f3954d651899a5d99c746c1b71d4210ccd4fbf98e873a93aaa5d3e1db1e72a0./home/user/.julia/conda/3/python./home/user/.julia/conda/3/python.-m#ipykernel_launcher
Info 15:40:33: TargetController found ID: .jvsc74a57bd04f3954d651899a5d99c746c1b71d4210ccd4fbf98e873a93aaa5d3e1db1e72a0./home/user/.julia/conda/3/python./home/user/.julia/conda/3/python.-m#ipykernel_launcher for document ~/path/to/folder/file.ipynb
Info 15:40:33: Setting controller affinity for ~/path/to/folder/file.ipynb .jvsc74a57bd04f3954d651899a5d99c746c1b71d4210ccd4fbf98e873a93aaa5d3e1db1e72a0./home/user/.julia/conda/3/python./home/user/.julia/conda/3/python.-m#ipykernel_launcher
Info 15:40:33: Setting setActiveController for ~/path/to/folder/file.ipynb
Info 15:40:33: KernelProvider switched kernel to id = .jvsc74a57bd040d3a090f54c6569ab1632332b64b2c03c39dcf918b08424e98f38b5ae0af88f#ir./opt/anaconda3/python..r#--slave#-e#irkernel::main()#--args#{connection_file}
Info 15:40:33: Starting Notebook in kernel.ts id = .jvsc74a57bd040d3a090f54c6569ab1632332b64b2c03c39dcf918b08424e98f38b5ae0af88f#ir./opt/anaconda3/python..r#--slave#-e#irkernel::main()#--args#{connection_file} for ~/path/to/folder/file.ipynb
Info 15:40:33: Creating raw notebook for ~/path/to/folder/file.ipynb
Info 15:40:33: Getting preferred kernel for ~/path/to/folder/file.ipynb
Info 15:40:33: Computing working directory ~/path/to/folder/file.ipynb
Info 15:40:33: Starting raw kernel R for interpreter 
Info 15:40:33: Kernel launching with ports 9000,9001,9002,9003,9004. Start port is 9000
Info 15:40:33: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
Info 15:40:34: Launching Raw Kernel & not daemon R # R
Error 15:40:34: Failed to get activated environment variables ourselves SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /home/user/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:826522
    at r.getCondaEnvVariablesImpl (/home/user/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:820002)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error 15:40:34: getCondaEnvVariables, Class name = r, completed in 888ms, has a falsy return value SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /home/user/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:826522
    at r.getCondaEnvVariablesImpl (/home/user/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:820002)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Info 15:40:35: Registering dummy command feature
Info 15:40:37: Got activated conda env vars ourselves for /opt/anaconda3/bin/python in 2485
Info 15:40:37: Adding env Variable PYTHONNOUSERSITE to /opt/anaconda3/bin/python
Info 15:40:37: Process Execution: > R --slave -e IRkernel::main() --args /tmp/tmp-40980f4jeEUj3pnqK.json
> R --slave -e IRkernel::main() --args /tmp/tmp-40980f4jeEUj3pnqK.json
Info 15:40:37: Process Execution: cwd: ~/Jobb/Kurs og studier/QRM1807 Mulitilevel modelling/Assignment3
cwd: ~/Jobb/Kurs og studier/QRM1807 Mulitilevel modelling/Assignment3
Info 15:40:37: Process Execution: > ~/.julia/conda/3/bin/python -m pip list
> ~/.julia/conda/3/bin/python -m pip list
Warn 15:40:39: StdErr from Kernel Process ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

Warn 15:40:39: StdErr from Kernel Process ✔ ggplot2 3.3.5     ✔ purrr   0.3.4
✔ tibble  3.1.6     ✔ dplyr   1.0.8
✔ tidyr   1.2.0     ✔ stringr 1.4.0
✔ readr   2.1.2     ✔ forcats 0.5.1

Warn 15:40:39: StdErr from Kernel Process 

Warn 15:40:39: StdErr from Kernel Process 
Attaching package: ‘magrittr’


Warn 15:40:39: StdErr from Kernel Process The following object is masked from ‘package:purrr’:

    set_names


Warn 15:40:39: StdErr from Kernel Process The following object is masked from ‘package:tidyr’:

    extract


Info 15:40:41: Got activated conda env vars ourselves for /opt/anaconda3/envs/renv/bin/python in 7146
Info 15:40:41: Process Execution: > /opt/anaconda3/envs/renv/bin/python -m pip list
> /opt/anaconda3/envs/renv/bin/python -m pip list
Info 15:40:45: Raw session started and connected
Started kernel R
Info 15:40:45: Finished connecting 30a3e572-42cb-4b6c-962d-6b82f24c9234
Info 15:40:45: Waiting for idle on (kernel): 11733a8f-f85d-4b91-a869-62613bb2c7cd -> idle
Info 15:40:45: Finished waiting for idle on (kernel): 11733a8f-f85d-4b91-a869-62613bb2c7cd -> idle
Info 15:51:29: Execute Cells request 1
Info 15:51:29: Execute Cell 1 ~/path/to/folder/file.ipynb
Info 15:51:29: Cell 1 executed with state Success
Info 15:52:02: Execute Cells request 1
Info 15:52:02: Execute Cell 1 ~/path/to/folder/file.ipynb
Info 15:52:02: Cell 1 executed with state Success
Info 15:52:51: Execute Cells request 1
Info 15:52:51: Execute Cell 1 ~/path/to/folder/file.ipynb
Info 15:52:52: Cancel all remaining cells true || Error || undefined
Info 15:52:52: Cancel pending cells
Info 15:52:52: Cell 1 executed with state Error
Info 16:01:30: Execute Cells request 2
Info 16:01:30: Execute Cell 2 ~/path/to/folder/file.ipynb
Info 16:01:30: Cell 2 executed with state Success
Info 16:07:50: Loading webview. View is notset
Info 16:07:50: Loading web view...
Info 16:07:50: Webview panel created.
Info 16:07:50: Web view react rendered
Info 16:07:50: Searching for token colors ...
Info 16:07:50: Attempting search for colors ...
Info 16:07:50: Loading colors from /home/user/.vscode/extensions/teabyii.ayu-1.0.5/ayu-light-bordered.json ...
Info 16:07:50: Attempting search for colors ...
Info 16:07:50: Loading base colors from /home/user/.vscode/extensions/teabyii.ayu-1.0.5/ayu-light-bordered.json ...
Info 16:07:50: Using colors to generate CSS ...
```

### Coding Language and Runtime Version

R version 4.1.3

### Language Extension Version (if applicable)

v2.4.0

### Anaconda Version (if applicable)

4.11.0

### Running Jupyter locally or remotely?

Local

**Comment by rchiodo** [comment]
Thanks for the issue. It looks to me like you're using R? This should be an issue on the R extension then. This one I believe:
https://github.com/REditorSupport/vscode-R/issues/1074

**Comment by pehkawn** [comment]
> Thanks for the issue. It looks to me like you're using R? This should be an issue on the R extension then. This one I believe: [REditorSupport/vscode-R#1074](https://github.com/REditorSupport/vscode-R/issues/1074)

This seems to be issue I'm having. Thanks!
