### ISSUE TITLE
can not connect to remote jupyter server

### ISSUE THREAD

**Issue by jasstionzyf** [microsoft/vscode-jupyter#9756]
## Environment data

-   VS Code version: 1.66
-   Jupyter Extension version (available under the Extensions sidebar): 
-   Python Extension version (available under the Extensions sidebar): 
-   OS Windows and version: 11
-   Python and/or Anaconda version: 3.8
-   Type of virtual environment used:  conda
-   Jupyter server running: Remote

## Actual behaviour

error:
Error 08:55:33: failed to create INotebook in kernel, UI Disabled = false [a [Error]: The Jupyter notebook server failed to launch in time
at S.waitForIdleOnSession (c:\Users\jasstion.vscode\extensions\ms-toolsai.jupyter-2022.4.1000912146\out\extension.node.js:2:165021)
at async S.createNewKernelSession (c:\Users\jasstion.vscode\extensions\ms-toolsai.jupyter-2022.4.1000912146\out\extension.node.js:2:389702)
at async S.connect (c:\Users\jasstion.vscode\extensions\ms-toolsai.jupyter-2022.4.1000912146\out\extension.node.js:2:388538)
at async m.startNew (c:\Users\jasstion.vscode\extensions\ms-toolsai.jupyter-2022.4.1000912146\out\extension.node.js:2:396682)
at async s (c:\Users\jasstion.vscode\extensions\ms-toolsai.jupyter-2022.4.1000912146\out\extension.node.js:2:357093)
at async C.createNotebookInstance (c:\Users\jasstion.vscode\extensions\ms-toolsai.jupyter-2022.4.1000912146\out\extension.node.js:2:357277)
at async C.createNotebook (c:\Users\jasstion.vscode\extensions\ms-toolsai.jupyter-2022.4.1000912146\out\extension.node.js:2:358476)] {
category: 'timeout',
kernelConnectionMetadata: {
kind: 'startUsingRemoteKernelSpec',
interpreter: undefined,
kernelSpec: {
specFile: undefined,
interpreterPath: undefined,
isRegisteredByVSC: undefined,
name: 'imageai',
argv: [Array],
language: 'python',
path: '/data1/apps/miniconda3/envs/test/bin/python',
display_name: 'imageAI',
metadata: [Object],
env: {},
interrupt_mode: undefined
},
id: 'http://gpu0.dev.yufei.com:8888/..imageai./data1/apps/miniconda3/envs/test/bin/python..-m#ipykernel_launcher',
baseUrl: 'http://gpu0.dev.yufei.com:8888/'
}
}
Warn 08:55:33: Kernel Error [a [Error]: The Jupyter notebook server failed to launch in time
at S.waitForIdleOnSession (c:\Users\jasstion.vscode\extensions\ms-toolsai.jupyter-2022.4.1000912146\out\extension.node.js:2:165021)
at async S.createNewKernelSession (c:\Users\jasstion.vscode\extensions\ms-toolsai.jupyter-2022.4.1000912146\out\extension.node.js:2:389702)
at async S.connect (c:\Users\jasstion.vscode\extensions\ms-toolsai.jupyter-2022.4.1000912146\out\extension.node.js:2:388538)
at async m.startNew (c:\Users\jasstion.vscode\extensions\ms-toolsai.jupyter-2022.4.1000912146\out\extension.node.js:2:396682)
at async s (c:\Users\jasstion.vscode\extensions\ms-toolsai.jupyter-2022.4.1000912146\out\extension.node.js:2:357093)
at async C.createNotebookInstance (c:\Users\jasstion.vscode\extensions\ms-toolsai.jupyter-2022.4.1000912146\out\extension.node.js:2:357277)
at async C.createNotebook (c:\Users\jasstion.vscode\extensions\ms-toolsai.jupyter-2022.4.1000912146\out\extension.node.js:2:358476)] {
category: 'timeout',
kernelConnectionMetadata: {
kind: 'startUsingRemoteKernelSpec',
interpreter: undefined,
kernelSpec: {
specFile: undefined,
interpreterPath: undefined,
isRegisteredByVSC: undefined,
name: 'imageai',
argv: [Array],
language: 'python',
path: '/data1/apps/miniconda3/envs/test/bin/python',
display_name: 'imageAI',
metadata: [Object],
env: {},
interrupt_mode: undefined
},
id: 'http://gpu0.dev.yufei.com:8888/..imageai./data1/apps/miniconda3/envs/test/bin/python..-m#ipykernel_launcher',
baseUrl: 'http://gpu0.dev.yufei.com:8888/'
}

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment]
thanks for filling this issue.
please could you fill in the rest of the issue template to help us with this issue.
eg provide three following information:
python, os info, steps required to replicate this issue at our end, provide the full logs from the output window.

**Comment by rchiodo** [comment]
Closing for lack of information. Please reopen if you can provide the jupyter output logs.
