### ISSUE TITLE
Export for HTML and PDF fails

### ISSUE THREAD

**Issue by guger** [microsoft/vscode-jupyter#9816]
## Environment data

-   VS Code version: 1.66.2 (Universal)
-   Jupyter Extension version (available under the Extensions sidebar): v2022.3.1000901801
-   Python Extension version (available under the Extensions sidebar): v2022.4.1
-   OS (Windows | Mac | Linux distro) and version: macOS Monterey 12.3.1
-   Python and/or Anaconda version: 3.9.12
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): -
-   Jupyter server running: Local
-   LaTeX version: MacTex Version 3.141592653 (TeX Live 2021)
-   nbconvert: 6.5.0
-   jupyter: 1.0.0
-   jupyter-core: 4.10.0

## Expected behaviour

I want to export a pdf of my jupyter notebook (.ipynb) file, using the VSCode Jupyter Extension `Export` -> `PDF`.

## Actual behaviour

The PDF as well as the HTML does not work.

## Steps to reproduce:

1. Open a Jupyter notebook in VSCode with the given prerequisites.
2. Try to export the notebook to pdf. 

## Logs

<details>

<summary>Output for <code>Jupyter Export to PDF</code> using <code>nbconvert</code>: (in details)
</summary>

<p>

```
Info 13:30:28: Process Execution: > /opt/homebrew/bin/python3 -m jupyter nbconvert /var/folders/1y/j228qgqn77jbvrqsk9b05b9c0000gn/T/3563a4c8-8fb9-41a5-ad7d-970042783579/SymbolicTranspNet.ipynb --to pdf --output tmp-1155Mn8FYXPkXL2t.pdf --output-dir /var/folders/1y/j228qgqn77jbvrqsk9b05b9c0000gn/T --debug
> /opt/homebrew/bin/python3 -m jupyter nbconvert /var/folders/1y/j228qgqn77jbvrqsk9b05b9c0000gn/T/3563a4c8-8fb9-41a5-ad7d-970042783579/SymbolicTranspNet.ipynb --to pdf --output tmp-1155Mn8FYXPkXL2t.pdf --output-dir /var/folders/1y/j228qgqn77jbvrqsk9b05b9c0000gn/T --debug
Error 13:30:28: Export failed [Error: [NbConvertApp] Searching ['/', '/Users/dguger/.jupyter', '/Users/dguger/Library/Python/3.9/etc/jupyter', '/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[NbConvertApp] Looking for jupyter_config in /etc/jupyter
[NbConvertApp] Looking for jupyter_config in /usr/local/etc/jupyter
[NbConvertApp] Looking for jupyter_config in /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/etc/jupyter
[NbConvertApp] Looking for jupyter_config in /Users/dguger/Library/Python/3.9/etc/jupyter
[NbConvertApp] Looking for jupyter_config in /Users/dguger/.jupyter
[NbConvertApp] Looking for jupyter_config in /
[NbConvertApp] Looking for jupyter_nbconvert_config in /etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /usr/local/etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /Users/dguger/Library/Python/3.9/etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /Users/dguger/.jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/traitlets/traitlets.py", line 537, in get
    value = obj._trait_values[self.name]
KeyError: 'template_paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/jupyter_core/application.py", line 269, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/opt/homebrew/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 414, in start
    self.convert_notebooks()
  File "/opt/homebrew/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 582, in convert_notebooks
    cls = get_exporter(self.export_format)
  File "/opt/homebrew/lib/python3.9/site-packages/nbconvert/exporters/base.py", line 101, in get_exporter
    if getattr(exporter(config=config), "enabled", True):
  File "/opt/homebrew/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 341, in __init__
    super().__init__(config=config, **kw)
  File "/opt/homebrew/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 117, in __init__
    self._init_preprocessors()
  File "/opt/homebrew/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 507, in _init_preprocessors
    conf = self._get_conf()
  File "/opt/homebrew/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 525, in _get_conf
    for path in map(Path, self.template_paths):
  File "/opt/homebrew/lib/python3.9/site-packages/traitlets/traitlets.py", line 577, in __get__
    return self.get(obj, cls)
  File "/opt/homebrew/lib/python3.9/site-packages/traitlets/traitlets.py", line 540, in get
    default = obj.trait_defaults(self.name)
  File "/opt/homebrew/lib/python3.9/site-packages/traitlets/traitlets.py", line 1580, in trait_defaults
    return self._get_trait_default_generator(names[0])(self)
  File "/opt/homebrew/lib/python3.9/site-packages/traitlets/traitlets.py", line 977, in __call__
    return self.func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 536, in _template_paths
    template_names = self.get_template_names()
  File "/opt/homebrew/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 620, in get_template_names
    raise ValueError(
ValueError: No template sub-directory with name 'latex' found in the following paths:
	/Users/dguger/Library/Jupyter
	/Users/dguger/Library/Python/3.9/share/jupyter
	/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/share/jupyter
	/usr/local/share/jupyter
	/usr/share/jupyter

	at a.executeCommand (/Users/dguger/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:979748)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async a.export (/Users/dguger/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:986562)
	at async _.exportToFormat (/Users/dguger/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:994081)
	at async _.performNbConvertExport (/Users/dguger/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:993365)
	at async _.performExport (/Users/dguger/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:993001)
	at async _.exportImpl (/Users/dguger/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:992450)
	at async _.export (/Users/dguger/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:992183)
	at async b.export (/Users/dguger/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:95367)
	at async m._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:30752)]
Error 13:30:28: If you have not installed xelatex (TeX) you will need to do so before you can export to PDF, for further instructions go to https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex. 
To avoid installing xelatex (TeX) you might want to try exporting to HTML and using your browsers "Print to PDF" feature.
```

</p>
</details>

<details>
<summary>Output for <code>Jupyter Export to HTML</code>: (in details)
</summary>

<p>

```
Info 13:29:29: Process Execution: > /opt/homebrew/bin/python3 -m jupyter nbconvert /var/folders/1y/j228qgqn77jbvrqsk9b05b9c0000gn/T/32053d2e-c8cc-4e57-abb2-79f9ea78cbdb/SymbolicTranspNet.ipynb --to html --output tmp-1155zNk12NwjKJlI.html --output-dir /var/folders/1y/j228qgqn77jbvrqsk9b05b9c0000gn/T --debug
> /opt/homebrew/bin/python3 -m jupyter nbconvert /var/folders/1y/j228qgqn77jbvrqsk9b05b9c0000gn/T/32053d2e-c8cc-4e57-abb2-79f9ea78cbdb/SymbolicTranspNet.ipynb --to html --output tmp-1155zNk12NwjKJlI.html --output-dir /var/folders/1y/j228qgqn77jbvrqsk9b05b9c0000gn/T --debug
Error 13:29:30: Export failed [Error: [NbConvertApp] Searching ['/', '/Users/dguger/.jupyter', '/Users/dguger/Library/Python/3.9/etc/jupyter', '/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[NbConvertApp] Looking for jupyter_config in /etc/jupyter
[NbConvertApp] Looking for jupyter_config in /usr/local/etc/jupyter
[NbConvertApp] Looking for jupyter_config in /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/etc/jupyter
[NbConvertApp] Looking for jupyter_config in /Users/dguger/Library/Python/3.9/etc/jupyter
[NbConvertApp] Looking for jupyter_config in /Users/dguger/.jupyter
[NbConvertApp] Looking for jupyter_config in /
[NbConvertApp] Looking for jupyter_nbconvert_config in /etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /usr/local/etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /Users/dguger/Library/Python/3.9/etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /Users/dguger/.jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/traitlets/traitlets.py", line 537, in get
    value = obj._trait_values[self.name]
KeyError: 'template_paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/jupyter_core/application.py", line 269, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/opt/homebrew/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 414, in start
    self.convert_notebooks()
  File "/opt/homebrew/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 582, in convert_notebooks
    cls = get_exporter(self.export_format)
  File "/opt/homebrew/lib/python3.9/site-packages/nbconvert/exporters/base.py", line 101, in get_exporter
    if getattr(exporter(config=config), "enabled", True):
  File "/opt/homebrew/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 341, in __init__
    super().__init__(config=config, **kw)
  File "/opt/homebrew/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 117, in __init__
    self._init_preprocessors()
  File "/opt/homebrew/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 507, in _init_preprocessors
    conf = self._get_conf()
  File "/opt/homebrew/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 525, in _get_conf
    for path in map(Path, self.template_paths):
  File "/opt/homebrew/lib/python3.9/site-packages/traitlets/traitlets.py", line 577, in __get__
    return self.get(obj, cls)
  File "/opt/homebrew/lib/python3.9/site-packages/traitlets/traitlets.py", line 540, in get
    default = obj.trait_defaults(self.name)
  File "/opt/homebrew/lib/python3.9/site-packages/traitlets/traitlets.py", line 1580, in trait_defaults
    return self._get_trait_default_generator(names[0])(self)
  File "/opt/homebrew/lib/python3.9/site-packages/traitlets/traitlets.py", line 977, in __call__
    return self.func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 536, in _template_paths
    template_names = self.get_template_names()
  File "/opt/homebrew/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 620, in get_template_names
    raise ValueError(
ValueError: No template sub-directory with name 'lab' found in the following paths:
	/Users/dguger/Library/Jupyter
	/Users/dguger/Library/Python/3.9/share/jupyter
	/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/share/jupyter
	/usr/local/share/jupyter
	/usr/share/jupyter

	at a.executeCommand (/Users/dguger/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:979748)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async a.export (/Users/dguger/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:985907)
	at async _.exportToFormat (/Users/dguger/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:994151)
	at async _.performNbConvertExport (/Users/dguger/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:993365)
	at async _.performExport (/Users/dguger/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:993001)
	at async _.exportImpl (/Users/dguger/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:992450)
	at async _.export (/Users/dguger/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:992183)
	at async b.export (/Users/dguger/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:95367)
	at async m._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:30752)]
```

</p>
</details>

**Comment by IanMatthewHuff** [comment]
@guger Could you please share a pip list of the packages that are in your target environment? Looks like our export things that you have everything, but something is still missing or incorrect in that env.

**Comment by guger** [comment]
Sure, here's the list of packages in my env:

```
Package              Version
-------------------- -----------
appnope              0.1.3
argon2-cffi          21.3.0
argon2-cffi-bindings 21.2.0
asttokens            2.0.5
attrs                21.4.0
backcall             0.2.0
beautifulsoup4       4.11.1
black                22.3.0
bleach               5.0.0
cffi                 1.15.0
click                8.1.2
control              0.9.1
cycler               0.11.0
debugpy              1.6.0
decorator            5.1.1
defusedxml           0.7.1
distlib              0.3.4
entrypoints          0.4
executing            0.8.3
fastjsonschema       2.15.3
filelock             3.6.0
fonttools            4.33.0
ipykernel            6.13.0
ipython              8.2.0
ipython-genutils     0.2.0
ipywidgets           7.7.0
jedi                 0.18.1
Jinja2               3.1.1
jsonschema           4.4.0
jupyter              1.0.0
jupyter-client       7.3.0
jupyter-console      6.4.3
jupyter-core         4.10.0
jupyterlab-pygments  0.2.2
jupyterlab-widgets   1.1.0
kiwisolver           1.4.2
MarkupSafe           2.1.1
matplotlib           3.5.1
matplotlib-inline    0.1.3
mistune              0.8.4
mpmath               1.2.1
mypy-extensions      0.4.3
nbclient             0.6.0
nbconvert            6.5.0
nbformat             5.3.0
nest-asyncio         1.5.5
networkx             2.8
notebook             6.4.11
numpy                1.22.3
packaging            21.3
pandas               1.4.2
pandocfilters        1.5.0
parso                0.8.3
pathspec             0.9.0
pexpect              4.8.0
pickleshare          0.7.5
Pillow               9.1.0
pip                  22.0.4
platformdirs         2.5.2
prometheus-client    0.14.1
prompt-toolkit       3.0.29
psutil               5.9.0
ptyprocess           0.7.0
pure-eval            0.2.2
pycparser            2.21
Pygments             2.11.2
pyparsing            3.0.8
pyrsistent           0.18.1
python-dateutil      2.8.2
pytz                 2022.1
pyzmq                22.3.0
qtconsole            5.3.0
QtPy                 2.0.1
scipy                1.8.0
Send2Trash           1.8.0
setuptools           60.10.0
six                  1.16.0
soupsieve            2.3.2.post1
stack-data           0.2.0
sympy                1.10.1
tbcontrol            0.2.1
terminado            0.13.3
testpath             0.6.0
tinycss2             1.1.1
tomli                2.0.1
tornado              6.1
tqdm                 4.64.0
traitlets            5.1.1
typing_extensions    4.2.0
virtualenv           20.14.1
wcwidth              0.2.5
webencodings         0.5.1
wheel                0.37.1
widgetsnbextension   3.6.0
```

**Comment by IanMatthewHuff** [comment]
So the PDF failure looks like TeX might not be installed on your system? Exporting to PDF has a number of requirements that are needed to run: https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex

The HTML failure is odder though. That should work without anything extra. Could you maybe try just re-installing nbconvert? Per this thread it seems like a possible issue just with nbconvert in general: https://stackoverflow.com/questions/63958574/no-template-sub-directory-with-name-lab-found-in-the-following-paths

**Comment by guger** [comment]
I'm sure tex is correctly installed, as I'm using LaTeX regularly, my MacTex version is updated and everything else using LaTeX is working fine.

Unfortunately, re-installing nbconvert doesn't solve the problem, but it looks like there is a problem finding the template paths, but the template paths occured in the log when removing nbconvert.

```
Found existing installation: nbconvert 6.5.0
Uninstalling nbconvert-6.5.0:
  Would remove:
    /opt/homebrew/bin/jupyter-dejavu
    /opt/homebrew/bin/jupyter-nbconvert
    /opt/homebrew/lib/python3.9/site-packages/nbconvert-6.5.0.dist-info/*
    /opt/homebrew/lib/python3.9/site-packages/nbconvert/*
    /opt/homebrew/share/jupyter/nbconvert/templates/asciidoc/conf.json
    /opt/homebrew/share/jupyter/nbconvert/templates/asciidoc/index.asciidoc.j2
    /opt/homebrew/share/jupyter/nbconvert/templates/base/celltags.j2
    /opt/homebrew/share/jupyter/nbconvert/templates/base/display_priority.j2
    /opt/homebrew/share/jupyter/nbconvert/templates/base/jupyter_widgets.html.j2
    /opt/homebrew/share/jupyter/nbconvert/templates/base/mathjax.html.j2
    /opt/homebrew/share/jupyter/nbconvert/templates/base/null.j2
    /opt/homebrew/share/jupyter/nbconvert/templates/basic/conf.json
    /opt/homebrew/share/jupyter/nbconvert/templates/basic/index.html.j2
    /opt/homebrew/share/jupyter/nbconvert/templates/classic/base.html.j2
    /opt/homebrew/share/jupyter/nbconvert/templates/classic/conf.json
    /opt/homebrew/share/jupyter/nbconvert/templates/classic/index.html.j2
    /opt/homebrew/share/jupyter/nbconvert/templates/classic/static/style.css
    /opt/homebrew/share/jupyter/nbconvert/templates/compatibility/display_priority.tpl
    /opt/homebrew/share/jupyter/nbconvert/templates/compatibility/full.tpl
    /opt/homebrew/share/jupyter/nbconvert/templates/lab/base.html.j2
    /opt/homebrew/share/jupyter/nbconvert/templates/lab/conf.json
    /opt/homebrew/share/jupyter/nbconvert/templates/lab/index.html.j2
    /opt/homebrew/share/jupyter/nbconvert/templates/lab/static/index.css
    /opt/homebrew/share/jupyter/nbconvert/templates/lab/static/theme-dark.css
    /opt/homebrew/share/jupyter/nbconvert/templates/lab/static/theme-light.css
    /opt/homebrew/share/jupyter/nbconvert/templates/latex/base.tex.j2
    /opt/homebrew/share/jupyter/nbconvert/templates/latex/conf.json
    /opt/homebrew/share/jupyter/nbconvert/templates/latex/display_priority.j2
    /opt/homebrew/share/jupyter/nbconvert/templates/latex/document_contents.tex.j2
    /opt/homebrew/share/jupyter/nbconvert/templates/latex/index.tex.j2
    /opt/homebrew/share/jupyter/nbconvert/templates/latex/null.j2
    /opt/homebrew/share/jupyter/nbconvert/templates/latex/report.tex.j2
    /opt/homebrew/share/jupyter/nbconvert/templates/latex/style_bw_ipython.tex.j2
    /opt/homebrew/share/jupyter/nbconvert/templates/latex/style_bw_python.tex.j2
    /opt/homebrew/share/jupyter/nbconvert/templates/latex/style_ipython.tex.j2
    /opt/homebrew/share/jupyter/nbconvert/templates/latex/style_jupyter.tex.j2
    /opt/homebrew/share/jupyter/nbconvert/templates/latex/style_python.tex.j2
    /opt/homebrew/share/jupyter/nbconvert/templates/markdown/conf.json
    /opt/homebrew/share/jupyter/nbconvert/templates/markdown/index.md.j2
    /opt/homebrew/share/jupyter/nbconvert/templates/python/conf.json
    /opt/homebrew/share/jupyter/nbconvert/templates/python/index.py.j2
    /opt/homebrew/share/jupyter/nbconvert/templates/reveal/base.html.j2
    /opt/homebrew/share/jupyter/nbconvert/templates/reveal/conf.json
    /opt/homebrew/share/jupyter/nbconvert/templates/reveal/index.html.j2
    /opt/homebrew/share/jupyter/nbconvert/templates/reveal/static/custom_reveal.css
    /opt/homebrew/share/jupyter/nbconvert/templates/rst/conf.json
    /opt/homebrew/share/jupyter/nbconvert/templates/rst/index.rst.j2
    /opt/homebrew/share/jupyter/nbconvert/templates/script/conf.json
    /opt/homebrew/share/jupyter/nbconvert/templates/script/script.j2
    /opt/homebrew/share/jupyter/nbconvert/templates/webpdf/conf.json
    /opt/homebrew/share/jupyter/nbconvert/templates/webpdf/index.pdf.j2
```

**Comment by IanMatthewHuff** [comment]
Does nbconvert work from the command line outside of vscode? Something like:
jupyter nbconvert --to html notebook.ipynb

**Comment by IanMatthewHuff** [comment]
@guger If the nbconvert command doesn't work from the command line then it won't be able to work from vs code either as we are calling the same command to do the convert. Might need to try re-installing jupyter or creating a new environment to see if that works. I'm closing this issue for now, but if the command is working from the command line, but not working from vs code, just ping back and I can reopen and investigate.

**Comment by hafizusmanabbasi** [comment]
i am facing the same issue

**Comment by guger** [comment]
@hafizusmanabbasi Are you using macOS with Python installed via homebrew?

**Comment by mihaiconstantin** [comment]
@greazer I am facing the same issue, and the answer is yes--I use `python` installed via `homebrew`.

**Comment by usmanabbasi360** [comment]
> @hafizusmanabbasi Are you using macOS with Python installed via homebrew?

No, using windows 10 , but solved the issue after research of 24 hours but unfortunately I could'nt remember . but one thing I would like to mention is that there is an extention in vscode 'Markdown PDF' that might solved this problem

**Comment by bartoli** [comment]
I am getting this too.
In my case, jupyter was installed outside of python by pip install jupyter --prefix=XXXX
Indeed, templates are now in XXXX/jupyter/share/nbconvert/templates, and i guess they are searched in PYTHON_ROOT/share/... ?

**Comment by guger** [comment]
@bartoli It seems like this issue is related to nbconvert directly, please make some noise there: [https://github.com/jupyter/nbconvert/issues/1773](https://github.com/jupyter/nbconvert/issues/1773)
