### ISSUE TITLE
Running a cell in fails to start the Kernel

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-jupyter#9817]
Testing #9768

In step 12 of "Test Connecting to a kernel" I rant the cell and got this:

![image](https://user-images.githubusercontent.com/38270282/165780348-19204808-a55b-4f3f-83cd-e69606388bf1.png)

The `log` link in that output didn't work. This error was in the console:
```
  ERR command 'jupyter.viewOutput' not found: Error: command 'jupyter.viewOutput' not found
    at v._tryExecuteCommand (https://main.vscode-cdn.net/insider/7fc8af4e2d8f50a3950b809b9beab86fa5135f29/out/vs/workbench/workbench.web.main.js:1722:3532)
    at v.executeCommand (https://main.vscode-cdn.net/insider/7fc8af4e2d8f50a3950b809b9beab86fa5135f29/out/vs/workbench/workbench.web.main.js:1722:3414)
    at async i.open (https://main.vscode-cdn.net/insider/7fc8af4e2d8f50a3950b809b9beab86fa5135f29/out/vs/workbench/workbench.web.main.js:595:16111)
    at async open (https://main.vscode-cdn.net/insider/7fc8af4e2d8f50a3950b809b9beab86fa5135f29/out/vs/workbench/workbench.web.main.js:595:17885)
````

Jupyter output:
```
Visual Studio Code - Insiders (1.67.0-insider, undefined, vscode.dev)
Jupyter Extension Version: 2022.4.1001201006.
Python Extension not installed.
Opened workspace folder.
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 16:48:30.830: Creating server with url : http://localhost:8888/
info 16:48:30.887: Checking for server existence.
info 16:48:30.888: Checking for server usability.
info 16:48:30.889: Starting notebook server.
info 16:48:30.889: Connecting to server
info 16:48:30.890: Connecting to process server
info 16:48:30.890: Connecting server kernel http://localhost:8888/
Connecting to Jupyter server at http://localhost:8888/
info 16:48:30.890: Creating server with url : http://localhost:8888/
info 16:48:30.891: Connection complete server
info 16:48:30.891: Server started.
info 16:48:30.892: Creating server with url : http://localhost:8888/
info 16:48:30.898: Creating server with url : http://localhost:8888/
info 16:48:38.500: Creating server with url : http://localhost:8888/
info 16:48:38.501: Find preferred kernel for Untitled-1.ipynb with metadata {"orig_nbformat":4,"language_info":{"name":"python"}} & preferred interpreter 
info 16:48:38.507: Preferred Remote kernel for Untitled-1.ipynb is undefined
info 16:48:38.508: findKernel found Python 3 (ipykernel)
info 16:48:38.509: PreferredConnection: http://localhost:8888/..python3./C:/Users/alros/AppData/Local/Programs/Python/Python39/python.exe./.-m#ipykernel_launcher found for NotebookDocument: Untitled-1.ipynb
info 16:48:38.509: TargetController found ID: http://localhost:8888/..python3./C:/Users/alros/AppData/Local/Programs/Python/Python39/python.exe./.-m#ipykernel_launcher for document Untitled-1.ipynb
info 16:48:38.510: Creating server with url : http://localhost:8888/
info 16:48:57.894: Execute Cell 0 Untitled-1.ipynb
info 16:48:57.895: Starting Notebook id = http://localhost:8888/..python3./C:/Users/alros/AppData/Local/Programs/Python/Python39/python.exe./.-m#ipykernel_launcher for Untitled-1.ipynb (disableUI=false)
error 16:48:59.465: Failed to change kernel TypeError: Right-hand side of 'instanceof' is not an object
error 16:48:59.469: failed to create INotebook in kernel, UI Disabled = false Error: Kernel Python 3 (ipykernel) is not usable. Check the Jupyter output tab for more information.
warn 16:48:59.469: Error occurred while trying to start the kernel, options.disableUI=false Error: Kernel Python 3 (ipykernel) is not usable. Check the Jupyter output tab for more information.
warn 16:48:59.470: Kernel Error, context = start Error: Kernel Python 3 (ipykernel) is not usable. Check the Jupyter output tab for more information.
error 16:48:59.471: Error in execution Error: No matching bindings found for serviceIdentifier: Symbol(IRawNotebookProvider)
error 16:48:59.471: Error in execution (get message for cell) Error: No matching bindings found for serviceIdentifier: Symbol(IRawNotebookProvider)
```

**Comment by alexr00** [comment]
I am a jupyter noob, so maybe I missed something important.

**Comment by rchiodo** [comment]
I think your kernel is crashing and it looks like the kernel error handling code doesn't work in web at the moment. Thanks, good find as all of my testing the kernels worked :)

I need to fix the 'viewOutput' command to work too.

**Comment by amunger** [comment]
The error message seems to be better now:

> Failed to start the Kernel. 
> Kernel .venvBad is not usable. Check the Jupyter output tab for more information. 
> View Jupyter [log](command:jupyter.viewOutput) for further details.

**Comment by rchiodo** [comment]
That's what I'd expect. Thanks.
