### ISSUE TITLE
Failed to start the Daemon: ipython: error: argument -v: expected one argument

### ISSUE THREAD

**Issue by mzaiprog** [microsoft/vscode-jupyter#9838]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Using runAll fails because of wrong internal command line parameter usage: -v
Tested code cell contains:

print("TEST")

### VS Code Version

Version: 1.66.2 (user setup) Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977 Date: 2022-04-11T07:46:01.075Z Electron: 17.2.0 Chromium: 98.0.4758.109 Node.js: 16.13.0 V8: 9.8.177.11-electron.0 OS: Windows_NT x64 10.0.19043

### Jupyter Extension Version

 v2022.3.1000901801

### Jupyter logs

```shell
Visual Studio Code (1.66.2, undefined, desktop)
Jupyter Extension Version: 2022.3.1000901801.
Python Extension Version: 2022.4.1.
Workspace folder d:\Data\eclipse-workspace\PY_Env\PY_Buchungen
Info 16:05:04: ZMQ install verified.
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'jupyterEnhancedDataViewer'
Info 16:05:05: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
Info 16:05:05: Process Execution: > d:\Data\eclipse-workspace\PY_Env\Scripts\ipython.exe -m pip list
> d:\Data\eclipse-workspace\PY_Env\Scripts\ipython.exe -m pip list
Info 16:05:17: Creating controller for jupyter-notebook with interpreter d:\Data\eclipse-workspace\PY_Env\Scripts\ipython.exe
Info 16:05:17: Setting setActiveController for d:\Data\eclipse-workspace\PY_Env\PY_Buchungen\Test.ipynb
Info 16:05:17: KernelProvider switched kernel to id = .jvsc74a57bd01d32b7032e119eddcdb779ca89d616b57d86eafda50cdf5d0b0e977fea4bcede.d:\Data\eclipse-workspace\PY_Env\Scripts\ipython.exe.d:\Data\eclipse-workspace\PY_Env\Scripts\ipython.exe.-m#ipykernel_launcher
Info 16:05:17: Starting Notebook in kernel.ts id = .jvsc74a57bd01d32b7032e119eddcdb779ca89d616b57d86eafda50cdf5d0b0e977fea4bcede.d:\Data\eclipse-workspace\PY_Env\Scripts\ipython.exe.d:\Data\eclipse-workspace\PY_Env\Scripts\ipython.exe.-m#ipykernel_launcher for d:\Data\eclipse-workspace\PY_Env\PY_Buchungen\Test.ipynb
Info 16:05:17: Creating raw notebook for d:\Data\eclipse-workspace\PY_Env\PY_Buchungen\Test.ipynb
Info 16:05:17: Getting preferred kernel for d:\Data\eclipse-workspace\PY_Env\PY_Buchungen\Test.ipynb
Info 16:05:17: Computing working directory d:\Data\eclipse-workspace\PY_Env\PY_Buchungen\Test.ipynb
Info 16:05:17: Preferred kernel connection found in cache .jvsc74a57bd01d32b7032e119eddcdb779ca89d616b57d86eafda50cdf5d0b0e977fea4bcede.d:\Data\eclipse-workspace\PY_Env\Scripts\ipython.exe.d:\Data\eclipse-workspace\PY_Env\Scripts\ipython.exe.-m#ipykernel_launcher
Info 16:05:17: PreferredConnection: .jvsc74a57bd01d32b7032e119eddcdb779ca89d616b57d86eafda50cdf5d0b0e977fea4bcede.d:\Data\eclipse-workspace\PY_Env\Scripts\ipython.exe.d:\Data\eclipse-workspace\PY_Env\Scripts\ipython.exe.-m#ipykernel_launcher found for NotebookDocument: d:\Data\eclipse-workspace\PY_Env\PY_Buchungen\Test.ipynb
Info 16:05:17: TargetController found ID: .jvsc74a57bd01d32b7032e119eddcdb779ca89d616b57d86eafda50cdf5d0b0e977fea4bcede.d:\Data\eclipse-workspace\PY_Env\Scripts\ipython.exe.d:\Data\eclipse-workspace\PY_Env\Scripts\ipython.exe.-m#ipykernel_launcher for document d:\Data\eclipse-workspace\PY_Env\PY_Buchungen\Test.ipynb
Info 16:05:17: Setting controller affinity for d:\Data\eclipse-workspace\PY_Env\PY_Buchungen\Test.ipynb .jvsc74a57bd01d32b7032e119eddcdb779ca89d616b57d86eafda50cdf5d0b0e977fea4bcede.d:\Data\eclipse-workspace\PY_Env\Scripts\ipython.exe.d:\Data\eclipse-workspace\PY_Env\Scripts\ipython.exe.-m#ipykernel_launcher
Info 16:05:17: Starting raw kernel PY_Env (Python 3.10.4) for interpreter d:\Data\eclipse-workspace\PY_Env\Scripts\ipython.exe
Info 16:05:17: Kernel launching with ports 9000,9001,9002,9003,9004. Start port is 9000
Info 16:05:17: Process Execution: > d:\Data\eclipse-workspace\PY_Env\Scripts\ipython.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> d:\Data\eclipse-workspace\PY_Env\Scripts\ipython.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
Info 16:05:17: Adding env Variable PYTHONNOUSERSITE to d:\Data\eclipse-workspace\PY_Env\Scripts\ipython.exe
Info 16:05:17: Creating daemon process for d:\Data\eclipse-workspace\PY_Env\Scripts\ipython.exe with env variables count 60
Info 16:05:17: Process Execution: > d:\Data\eclipse-workspace\PY_Env\Scripts\ipython.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_interrupt_daemon -v --ppid 8176
> d:\Data\eclipse-workspace\PY_Env\Scripts\ipython.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_interrupt_daemon -v --ppid 8176
Info 16:05:18: Registering dummy command feature
Info 16:05:18: ipykernel version 6.13.0 for d:\Data\eclipse-workspace\PY_Env\Scripts\ipython.exe
Info 16:05:18: ipykernel location d:\Data\eclipse-workspace\PY_Env\lib\site-packages\ipykernel\__init__.py for d:\Data\eclipse-workspace\PY_Env\Scripts\ipython.exe
Error 16:05:22: Failed to start the Daemon, StdErr:  usage: ipython [-h] [--debug] [--show-config] [--show-config-json] [--quiet]
               [--init] [--autoindent] [--no-autoindent] [--automagic]
               [--no-automagic] [--pdb] [--no-pdb] [--pprint] [--no-pprint]
               [--color-info] [--no-color-info] [--ignore-cwd]
               [--no-ignore-cwd] [--nosep] [--autoedit-syntax]
               [--no-autoedit-syntax] [--simple-prompt] [--no-simple-prompt]
               [--banner] [--no-banner] [--confirm-exit] [--no-confirm-exit]
               [--term-title] [--no-term-title] [--classic] [--quick] [-i]
               [--log-level TerminalIPythonApp.log_level]
               [--profile-dir ProfileDir.location]
               [--profile TerminalIPythonApp.profile]
               [--ipython-dir TerminalIPythonApp.ipython_dir]
               [--config TerminalIPythonApp.extra_config_file]
               [--autocall TerminalInteractiveShell.autocall]
               [--colors TerminalInteractiveShell.colors]
               [--logfile TerminalInteractiveShell.logfile]
               [--logappend TerminalInteractiveShell.logappend]
               [-c TerminalIPythonApp.code_to_run]
               [-m TerminalIPythonApp.module_to_run]
               [--ext TerminalIPythonApp.extra_extensions]
               [--gui TerminalIPythonApp.gui]
               [--pylab [TerminalIPythonApp.pylab]]
               [--matplotlib [TerminalIPythonApp.matplotlib]]
               [--cache-size TerminalInteractiveShell.cache_size]
               [extra_args ...]
ipython: error: argument -v: expected one argument

Error 16:05:22: Failed to start the Daemon, ProcEndEx Error: Timeout waiting for daemon to start
    at Timeout._onTimeout (c:\Users\m.ziebeck\.vscode\extensions\ms-toolsai.jupyter-2022.3.1000901801\out\extension.js:2:838521)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
Error 16:05:22: Failed  to start the Daemon, Ex Error: Timeout waiting for daemon to start
    at Timeout._onTimeout (c:\Users\m.ziebeck\.vscode\extensions\ms-toolsai.jupyter-2022.3.1000901801\out\extension.js:2:838521)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
Error 16:05:22: Pinging Daemon Failed, Class name = d, completed in 5003ms, has a falsy return value, Arg 1: {}, Return Value: undefined Error: Timeout waiting for daemon to start
    at Timeout._onTimeout (c:\Users\m.ziebeck\.vscode\extensions\ms-toolsai.jupyter-2022.3.1000901801\out\extension.js:2:838521)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
Error 16:05:22: Failed to create daemon, Class name = d, completed in 5029ms, has a falsy return value, , Return Value: undefined Error: Timeout waiting for daemon to start
    at Timeout._onTimeout (c:\Users\m.ziebeck\.vscode\extensions\ms-toolsai.jupyter-2022.3.1000901801\out\extension.js:2:838521)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
Error 16:05:22: Failed to create the daemon service, defaulting to activated environment Error: Timeout waiting for daemon to start
    at Timeout._onTimeout (c:\Users\m.ziebeck\.vscode\extensions\ms-toolsai.jupyter-2022.3.1000901801\out\extension.js:2:838521)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
Info 16:05:23: Process Execution: > d:\Data\eclipse-workspace\PY_Env\Scripts\ipython.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"8a57c57a-3eeb-4ce6-96c1-ea756bf8a9a0" --shell=9002 --transport="tcp" --iopub=9004 --f=C:\Users\M0FA2~1.ZIE\AppData\Local\Temp\tmp-8176kPDAkQoqX5t9.json
> d:\Data\eclipse-workspace\PY_Env\Scripts\ipython.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"8a57c57a-3eeb-4ce6-96c1-ea756bf8a9a0" --shell=9002 --transport="tcp" --iopub=9004 --f=C:\Users\M0FA2~1.ZIE\AppData\Local\Temp\tmp-8176kPDAkQoqX5t9.json
Info 16:05:23: Process Execution: cwd: d:\Data\eclipse-workspace\PY_Env\PY_Buchungen
cwd: d:\Data\eclipse-workspace\PY_Env\PY_Buchungen
Warn 16:05:23: StdErr from Kernel Process [TerminalIPythonApp] WARNING | Unrecognized alias: 'ip', it will have no effect.

Warn 16:05:23: StdErr from Kernel Process [TerminalIPythonApp] WARNING | Unrecognized alias: 'stdin', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'control', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'hb', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'shell', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'transport', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'iopub', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'f', it will have no effect.

Info 16:05:24: Kernel Output: ---------------------------------------------------------------------------
MultipleInstanceError                     Traceback (most recent call last)
File C:\Program Files\Python310\lib\runpy.py:209, in run_module(mod_name, init_globals, run_name, alter_sys)
Warn 16:05:24: StdErr from Kernel Process d:\Data\eclipse-workspace\PY_Env\lib\site-packages\IPython\core\interactiveshell.py:2845: UserWarning: Unknown failure executing module: <ipykernel_launcher>
  warn('Unknown failure executing module: <%s>' % mod_name)

Info 16:05:24: Kernel Output: ---------------------------------------------------------------------------
MultipleInstanceError                     Traceback (most recent call last)
File C:\Program Files\Python310\lib\runpy.py:209, in run_module(mod_name, init_globals, run_name, alter_sys)
    207     run_name = mod_name
    208 if alter_sys:
--> 209     return _run_module_code(code, init_globals, run_name, mod_spec)
    210 else:
    211     # Leave the sys module alone
    212     return _run_code(code, {}, init_globals, run_name, mod_spec)

File C:\Program Files\Python310\lib\runpy.py:96, in _run_module_code(code, init_globals, mod_name, mod_spec, pkg_name, script_name)
     94 with _TempModule(mod_name) as temp_module, _ModifiedArgv0(fname):
     95     mod_globals = temp_module.module.__dict__
---> 96     _run_code(code, mod_globals, init_globals,
     97               mod_name, mod_spec, pkg_name, script_name)
     98 # Copy the globals of the temporary module, as they
     99 # may be cleared when the temporary module goes away
    100 return mod_globals.copy()

File C:\Program Files\Python310\lib\runpy.py:86, in _run_code(code, run_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)
     78         pkg_name = mod_spec.parent
     79 run_globals.update(__name__ = mod_name,
     80                    __file__ = fname,
     81                    __cached__ = cached,
   (...)
     84                    __package__ = pkg_name,
     85                    __spec__ = mod_spec)
---> 86 exec(code, run_globals)
     87 return run_globals

File d:\Data\eclipse-workspace\PY_Env\lib\site-packages\ipykernel_launcher.py:17, in <module>
     13     del sys.path[0]
     15 from ipykernel import kernelapp as app
---> 17 app.launch_new_instance()

File d:\Data\eclipse-workspace\PY_Env\lib\site-packages\traitlets\config\application.py:844, in Application.launch_instance(cls, argv, **kwargs)
    838 @classmethod
    839 def launch_instance(cls, argv=None, **kwargs):
    840     """Launch a global instance of this Application
    841 
    842     If a global instance already exists, this reinitializes and starts it
    843     """
--> 844     app = cls.instance(**kwargs)
    845     app.initialize(argv)
    846     app.start()

File d:\Data\eclipse-workspace\PY_Env\lib\site-packages\traitlets\config\configurable.py:549, in SingletonConfigurable.instance(cls, *args, **kwargs)
    547     return cls._instance
    548 else:
--> 549     raise MultipleInstanceError(
    550         "An incompatible sibling of '%s' is already instanciated"
    551         " as singleton: %s" % (cls.__name__, type(cls._instance).__name__)
    552     )

MultipleInstanceError: An incompatible sibling of 'IPKernelApp' is already instanciated as singleton: TerminalIPythonApp

Error 16:05:24: Disposing kernel process due to an error o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: [TerminalIPythonApp] WARNING | Unrecognized alias: 'ip', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'stdin', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'control', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'hb', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'shell', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'transport', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'iopub', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'f', it will have no effect.
d:\Data\eclipse-workspace\PY_Env\lib\site-packages\IPython\core\interactiveshell.py:2845: UserWarning: Unknown failure executing module: <ipykernel_launcher>
  warn('Unknown failure executing module: <%s>' % mod_name)...
    at ChildProcess.<anonymous> (c:\Users\m.ziebeck\.vscode\extensions\ms-toolsai.jupyter-2022.3.1000901801\out\extension.js:2:512309)
    at ChildProcess.emit (node:events:402:35)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  category: 'kerneldied',
  kernelConnectionMetadata: {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: undefined,
      interpreterPath: 'd:\\Data\\eclipse-workspace\\PY_Env\\Scripts\\ipython.exe',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'python3104jvsc74a57bd01d32b7032e119eddcdb779ca89d616b57d86eafda50cdf5d0b0e977fea4bcede',
      argv: [Array],
      language: 'python',
      path: 'python',
      display_name: "Python 3.10.4 ('PY_Env')",
      metadata: [Object],
      env: {},
      interrupt_mode: undefined
    },
    interpreter: {
      id: 'D:\\DATA\\ECLIPSE-WORKSPACE\\PY_ENV\\SCRIPTS\\IPYTHON.EXE',
      sysPrefix: 'd:\\Data\\eclipse-workspace\\PY_Env',
      envType: 'Venv',
      envName: 'PY_Env',
      envPath: 'd:\\Data\\eclipse-workspace\\PY_Env',
      path: 'd:\\Data\\eclipse-workspace\\PY_Env\\Scripts\\ipython.exe',
      architecture: 3,
      sysVersion: '3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]',
      version: [Object],
      displayName: "Python 3.10.4 ('PY_Env')",
      detailedDisplayName: "Python 3.10.4 ('PY_Env': venv)"
    },
    id: '.jvsc74a57bd01d32b7032e119eddcdb779ca89d616b57d86eafda50cdf5d0b0e977fea4bcede.d:\\Data\\eclipse-workspace\\PY_Env\\Scripts\\ipython.exe.d:\\Data\\eclipse-workspace\\PY_Env\\Scripts\\ipython.exe.-m#ipykernel_launcher'
  },
  exitCode: -1,
  stdErr: "[TerminalIPythonApp] WARNING | Unrecognized alias: 'ip', it will have no effect.\r\n" +
    "[TerminalIPythonApp] WARNING | Unrecognized alias: 'stdin', it will have no effect.\r\n" +
    "[TerminalIPythonApp] WARNING | Unrecognized alias: 'control', it will have no effect.\r\n" +
    "[TerminalIPythonApp] WARNING | Unrecognized alias: 'hb', it will have no effect.\r\n" +
    "[TerminalIPythonApp] WARNING | Unrecognized alias: 'shell', it will have no effect.\r\n" +
    "[TerminalIPythonApp] WARNING | Unrecognized alias: 'transport', it will have no effect.\r\n" +
    "[TerminalIPythonApp] WARNING | Unrecognized alias: 'iopub', it will have no effect.\r\n" +
    "[TerminalIPythonApp] WARNING | Unrecognized alias: 'f', it will have no effect.\r\n" +
    'd:\\Data\\eclipse-workspace\\PY_Env\\lib\\site-packages\\IPython\\core\\interactiveshell.py:2845: UserWarning: Unknown failure executing module: <ipykernel_launcher>\r\n' +
    "  warn('Unknown failure executing module: <%s>' % mod_name)\r\n"
}
Error 16:05:24: [TerminalIPythonApp] WARNING | Unrecognized alias: 'ip', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'stdin', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'control', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'hb', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'shell', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'transport', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'iopub', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'f', it will have no effect.
d:\Data\eclipse-workspace\PY_Env\lib\site-packages\IPython\core\interactiveshell.py:2845: UserWarning: Unknown failure executing module: <ipykernel_launcher>
  warn('Unknown failure executing module: <%s>' % mod_name)

Info 16:05:24: Dispose Kernel process
Error 16:05:24: Failed to connect raw kernel session: Error: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: [TerminalIPythonApp] WARNING | Unrecognized alias: 'ip', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'stdin', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'control', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'hb', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'shell', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'transport', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'iopub', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'f', it will have no effect.
d:\Data\eclipse-workspace\PY_Env\lib\site-packages\IPython\core\interactiveshell.py:2845: UserWarning: Unknown failure executing module: <ipykernel_launcher>
  warn('Unknown failure executing module: <%s>' % mod_name)...
```

### Coding Language and Runtime Version

Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] IPython 8.3.0

### Language Extension Version (if applicable)

Python Extension v2022.4.1

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
It looks like your configuration has IPython as the environment to start the kernel, rather than just python.exe. I don't believe this is supported. Could you selecting a kernel that points to a python.exe and see if that works?

Do you have a setting that specifies using ipython.exe as your interpreter?

**Comment by mzaiprog** [comment]
Thank you very much for the quick answer. When choosing the interpreter, I probably clicked on ipython by mistake. With your advice, I have once again intensified my attempts to activate python as an interpreter. This turned out to be quite difficult.

My Solution:
- Remove ipython.exe & ipython3.exe from scripts directory.
- vscode now complains about missing interpreter
- Select interpreter: python.exe from venv/scripts
- Select python kernel venv/scripts/python.exe
- Restore ipython.exe & ipython3.exe into venv/scripts directory

Problem solved. Thanks
