### ISSUE TITLE
Data viewer crashes when inspecting jupyter data frame variable

### ISSUE THREAD

**Issue by martinleo666** [microsoft/vscode-jupyter#9889]
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Data viewer crashes on any spark data frame variable, regardless of whether it contains data or was created out of an empty list. I use databricks-connect 9.1.13 for spark.

Does not apply to 
 - normal .py files (without # %% markers)
 - spark data frames, that have been converted to pandas data frames
- my other windows machine (this is a mac)

Urls and pathes have been anonymized

### VS Code Version

1.66.2

### Jupyter Extension Version

v2022.3.1000901801

### Jupyter logs

```shell
Info 14:46:55: Kernel Output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing /var/folders/lt/gnj5lvrn7f926knh9ltmyhhc0000gn/T/tmp-18075p906p9AwDRD1.json
View job details at https://westeurope.azuredatabricks.net/?o=xxx#/setting/clusters/xxx-xxx-xxx/sparkUi
View job details at https://westeurope.azuredatabricks.net/?o=xxx#/setting/clusters/xxx-xxx-xxx/sparkUi
View job details at https://westeurope.azuredatabricks.net/?o=xxx#/setting/clusters/xxx-xxx-xxx/sparkUi
View job details at https://westeurope.azuredatabricks.net/?o=xxx#/setting/clusters/xxx-xxx-xxx/sparkUi
View job details at https://westeurope.azuredatabricks.net/?o=xxx#/setting/clusters/xxx-xxx-xxx/sparkUi

Info 14:46:55: Executing silently Code (completed) = import builtins\nbuiltins.print(_VSCODE_getDataFrameInfo(df))
Error 14:46:55: [SyntaxError: Unexpected token V in JSON at position 0
	at JSON.parse (<anonymous>)
	at g.deserializeJupyterResult (/Users/xxx/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:576269)
	at getDataFrameInfo (/Users/xxx/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:572372)
	at async r.ensureInitialized (/Users/xxx/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:963574)
	at async r.getDataFrameInfo (/Users/xxx/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:962377)
	at async x.prepDataFrameInfo (/Users/xxx/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:953270)
	at async x.showData (/Users/xxx/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:951044)
	at async f.create (/Users/xxx/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:960055)]
Info 14:46:55: Executing silently Code (idle) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 14:46:55: Executing silently Code (completed) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 14:46:55: Executing silently Code (idle) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 14:46:55: Executing silently Code (idle) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 14:46:55: Executing silently Code (completed) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 14:46:55: Executing silently Code (completed) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
```

### Coding Language and Runtime Version

Python v3.8.10

### Running Jupyter locally or remotely?

Local

**Comment by rchiodo** [comment]
Thanks for the issue. 

I think the spark data frame must have something in it that cannot be converted to JSON (it's how we send the data to VS code). I'm surprised pandas isn't crashing when converting it though.

Internally we use this code here to convert whatever the variable is into a dataframe.
https://github.com/microsoft/vscode-jupyter/blob/c346a7ecce5a921fbcb53b2e823a429b6c39fb29/pythonFiles/vscode_datascience_helpers/dataframes/vscodeDataFrame.py#L91

You could try running that function yourself on your spark dataframe with code like so (after your failure):
```
df = _VSCODE_convertToDataFrame(spark_df)
``
And then turn that into json
```
json = _VSCODE_getDataFrameInfo(df)
```

The resulting json should then be printable and you can see what might be invalid.

In the meantime, if you could give us some sample code that generates an invalid spark data frame, we should be able to repro locally.

**Comment by martinleo666** [comment]
Hey Rich, thank you for your quick reply.

I used these lines to throw the error:

~~~
import pyspark.sql.functions as SF
schema = ST.StructType([
    ST.StructField("id", ST.StringType(),True)
])
spark_df = spark.createDataFrame([["1"]], schema)
~~~

And I executed this code after the data viewer crashed:
~~~
df = _VSCODE_convertToDataFrame(spark_df)
json = _VSCODE_getDataFrameInfo(df)
print(json)
~~~

And got this nice json output :-/
~~~
View job details at https://westeurope.azuredatabricks.net/?o=xxx#/setting/clusters/xxx-xxx-xxx/sparkUi
View job details at https://westeurope.azuredatabricks.net/?o=xxx#/setting/clusters/xxx-xxx-xxx/sparkUi
{"columns": [{"key": "index", "name": "index", "type": "int64"}, {"key": "id", "name": "id", "type": "object"}], "indexColumn": "index", "rowCount": 1}

~~~
Btw, the new df variable now can be perfectly inspected by the data viewer. spark_df still crashes.

Just guessing, but could it be that the "V" in the error message refers to the "V" from "View job details at http://..." from the console output?

**Comment by martinleo666** [comment]
This could be misunderstood, the variable json really just contains this text:
`{"columns": [{"key": "index", "name": "index", "type": "int64"}, {"key": "id", "name": "id", "type": "object"}], "indexColumn": "index", "rowCount": 1}`
The other text is just output.

**Comment by martinleo666** [comment]
This might actually have to do with the console messages from Spark. I am currently comparing the behavior of the notebooks on two different computers. On my Mac, all output from spark is printed not only in the Jupyter output window, but also just below the Jupyter cell, where stdout appears, when I run print(1).

For example, if I run a `SparkSession.builder.getOrCreate() ` I get this as stderr below the corresponding cell:

~~~
22/05/04 22:24:49 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
22/05/04 22:24:51 WARN MetricsSystem: Using default name SparkStatusTracker for source because neither spark.metrics.namespace nor spark.app.id is set.
22/05/04 22:24:52 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
22/05/04 22:24:52 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
~~~

VS Code says its type is `application/vnd.code.notebook.stderr`

I also took a closer look at those `_VSCODE_`  functions.  `_VSCODE_getDataFrameInfo` calls `_VSCODE_convertToDataFrame` and this eventually calls `df.toPandas()`.
If I call `pdf = spark_df.toPandas()` inside an empty cell I always get the above mentioned output with 

~~~
View job details at ...
~~~
Which according to VS Code is type of `application/vnd.code.notebook.stdout`.

This output seems to come from databricks-connect. I have also been looking for a long time for a way to turn off this output. Unfortunately without success. I guess databricks-connect is closed source.
On the other hand, these messages are also displayed on my other Windows machine, but there only in the Jupyter output window, not below the Jupyter cell. And on that machine the Data Viewer works perfectly fine.

However, I am also at my wit's end here. I hope that this info is useful to anyone.

**Comment by martinleo666** [comment]
I also tried to capture stdout:

~~~
%%capture txt
print(1)
spark_df.toPandas()
print(2)
~~~

The result looks like this.

~~~
View job details at https://westeurope.azuredatabricks.net/...
View job details at https://westeurope.azuredatabricks.net/...
~~~
It's type is `application/vnd.code.notebook.stdout`. The variable `txt` contains only the lines "1" and "2". 

Btw, these lines get printed right after `answer = self.gateway_client.send_command(command)` in `py4j/java_gateway.py` gets executed.

I also tried to turn off the spark logging `spark.sparkContext.setLogLevel("OFF")`  Unfortunately no success.

**Comment by zoof** [comment]
I believe this is the same issue and for me at least, this seems particular to a Windows environment.  I have no problems viewing data of any sort on Linux but on Windows, the kernel crashes when I try to view a DataFrame -- Series, lists, anything else present no problem.

VSCode version 1.71.1
Jupyter version 2022.8.1002431955
Miniconda Python version 2.9.13

**Comment by DonJayamanne** [comment]
@zoof @martinleo666 
Please could you install the latest vscode insiders and the pre-release versions of the Jupyter and Python extensions.
Let me know if you still run into this issue
Optionally please wait for the latest stable version of the Jupyter extension and vscode, to be relaesed some time this week.

**Comment by martinleo666** [comment]
@DonJayamanne 
Works for me :-) Tested with ...
VS Code 1.74.0-insider
Python v2022.19.13351014 Pre-Release
Jupyter v2023.1.1003411034 Pre-Release

**Comment by martinleo666** [comment]
Thank you!

**Comment by ezpikinz** [comment]
I am having the same issue and have tried using VSCode Insiders with pre-release extensions. I also assume the unexpected "V" is the first character from "View job details at https.." that is trying to be parsed as JSON. 

However, Data Viewer does work for spark dataframes when opening from the debugger variables.

This is the Jupyter log when trying to open a spark dataframe in data viewer from Jupyter Variables.

`10:50:01.694 [error] [SyntaxError: Unexpected token V in JSON at position 0
	at JSON.parse (<anonymous>)
	at xv.deserializeJupyterResult (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:134800)
	at xv.getDataFrameInfo (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:132434)
	at async jk.ensureInitialized (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:553407)
	at async jk.getDataFrameInfo (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:552232)
	at async wk.prepDataFrameInfo (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:540256)
	at async wk.showData (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:537833)]`
