### ISSUE TITLE
Closing Interactive window opens terminal

### ISSUE THREAD

**Issue by hookxs** [microsoft/vscode-jupyter#9998]
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Since one of the latest updates whenever I close the Interactive window (by clicking the X of the tab, not by ctrl+f4) a new terminal window is opened (unless it already exists).

### VS Code Version

Version: 1.67.1 (user setup) Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d Date: 2022-05-06T12:37:03.389Z Electron: 17.4.1 Chromium: 98.0.4758.141 Node.js: 16.13.0 V8: 9.8.177.13-electron.0 OS: Windows_NT x64 10.0.22000

### Jupyter Extension Version

v2022.4.1011282140

### Jupyter logs

```shell
Visual Studio Code (1.67.1, undefined, desktop)
Jupyter Extension Version: 2022.4.1011282140.
Python Extension Version: 2022.6.1.
Workspace folder c:\Users\xxx\Box Sync\Python\ais
error 12:32:2.952: Exception while attempting zmq : [Error: The specified module could not be found.
\\?\c:\Users\xxx\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\out\node_modules\zeromq\prebuilds\win32-x64\electron.napi.node
	at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
	at Object.Module._extensions..node (node:internal/modules/cjs/loader:1246:18)
	at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1812)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
	at Function.s._load (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:32307)
	at Function.b._load (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:28750)
	at Function._._load (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:61719)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at h (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:699)
	at load (c:\Users\xxx\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\out\node_modules\node-gyp-build\index.js:1:628)
	at Object.<anonymous> (c:\Users\xxx\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\out\node_modules\zeromq\lib\native.js:1:198)
	at Module.u._compile (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1313)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
	at Function.s._load (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:32307)
	at Function.b._load (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:28750)
	at Function._._load (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:61719)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at h (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:699)
	at Object.<anonymous> (c:\Users\xxx\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\out\node_modules\zeromq\lib\index.js:1:144)
	at Module.u._compile (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1313)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
	at Function.s._load (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:32307)
	at Function.b._load (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:28750)
	at Function._._load (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:61719)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at h (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:699)
	at Object.92747 (c:\Users\xxx\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\out\extension.node.js:2:4028080)
	at __webpack_require__ (c:\Users\xxx\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\out\extension.node.js:2:4801729)
	at u.zmqSupported (c:\Users\xxx\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\out\extension.node.js:2:539428)
	at u.isSupportedForLocalLaunch (c:\Users\xxx\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\out\extension.node.js:2:539171)
	at u.get isSupported [as isSupported] (c:\Users\xxx\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\out\extension.node.js:2:539081)
	at t.registerTypes (c:\Users\xxx\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\out\extension.node.js:2:551117)
	at c:\Users\xxx\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\out\extension.node.js:2:4806637
	at c:\Users\xxx\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\out\extension.node.js:2:4807386
	at c:\Users\xxx\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\out\extension.node.js:2:4807394
	at e.activate (c:\Users\xxx\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\out\extension.node.js:2:4807516)
	at Function._callActivateOptional (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:88:17454)
	at Function._callActivate (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:88:17119)
	at c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:88:14937
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async _activate (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:8180)
	at async _waitForDepsThenActivate (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:8122)
	at async _initialize (c:\Users\xxx\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:7486)] {
  code: 'ERR_DLOPEN_FAILED'
}
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 12:32:3.226: Old kernelSpecs (created by Jupyter extension) stored in directory C:\Users\xxx\AppData\Roaming\jupyter\kernels\__old_vscode_kernelspecs
info 12:32:3.232: Attempting to start a server because of preload conditions ...
info 12:32:3.255: Checking for server existence.
info 12:32:3.255: Checking for server usability.
info 12:32:3.256: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
info 12:32:3.970: Process Execution: > ~\miniconda3\envs\ais\python.exe -m pip list
> ~\miniconda3\envs\ais\python.exe -m pip list
info 12:32:3.972: Process Execution: > ~\miniconda3\envs\ais\python.exe -c "import jupyter"
> ~\miniconda3\envs\ais\python.exe -c "import jupyter"
info 12:32:3.975: Process Execution: > ~\miniconda3\envs\ais\python.exe -c "import notebook"
> ~\miniconda3\envs\ais\python.exe -c "import notebook"
info 12:32:4.210: Process Execution: > ~\miniconda3\envs\ais\python.exe -m jupyter kernelspec --version
> ~\miniconda3\envs\ais\python.exe -m jupyter kernelspec --version
info 12:32:4.589: Starting notebook server.
info 12:32:4.589: Connecting to server
info 12:32:4.589: Launching server
info 12:32:4.589: Starting Notebook
info 12:32:4.611: Generating custom default config at C:\Users\xxx\AppData\Local\Temp\90501c52-6a00-4082-a6d5-590bf19a0e6b\jupyter_notebook_config.py
info 12:32:4.611: Starting Jupyter Notebook
Starting Jupyter from ~\miniconda3\envs\ais\python.exe with command line --no-browser --notebook-dir="c:\\Users\\xxx\\Box Sync\\Python\\ais" --config=C:\Users\xxx\AppData\Local\Temp\90501c52-6a00-4082-a6d5-590bf19a0e6b\jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
info 12:32:4.634: Creating daemon pool for c:\Users\xxx\miniconda3\envs\ais\python.exe with env variables count 68
info 12:32:4.637: Process Execution: > ~\miniconda3\envs\ais\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 7104
> ~\miniconda3\envs\ais\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 7104
info 12:32:4.639: Process Execution: > ~\miniconda3\envs\ais\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 7104
> ~\miniconda3\envs\ais\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 7104
info 12:32:4.642: Process Execution: > ~\miniconda3\envs\ais\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 7104
> ~\miniconda3\envs\ais\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v --ppid 7104
info 12:32:4.927: Process Execution: > ~\miniconda3\envs\ais\python.exe (daemon) -m jupyter notebook --no-browser --notebook-dir="c:\\Users\\xxx\\Box Sync\\Python\\ais" --config=C:\Users\xxx\AppData\Local\Temp\90501c52-6a00-4082-a6d5-590bf19a0e6b\jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
> ~\miniconda3\envs\ais\python.exe (daemon) -m jupyter notebook --no-browser --notebook-dir="c:\\Users\\xxx\\Box Sync\\Python\\ais" --config=C:\Users\xxx\AppData\Local\Temp\90501c52-6a00-4082-a6d5-590bf19a0e6b\jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
info 12:32:4.928: Waiting for Jupyter Notebook
c:\Users\xxx\miniconda3\envs\ais\lib\site-packages\traitlets\traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'c:\\\\Users\\\\xxx\\\\Box Sync\\\\Python\\\\ais' instead of '"c:\\\\Users\\\\xxx\\\\Box Sync\\\\Python\\\\ais"' if you require traitlets >=5.
  warn(
info 12:32:5.762: c:\Users\xxx\miniconda3\envs\ais\lib\site-packages\traitlets\traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'c:\\\\Users\\\\xxx\\\\Box Sync\\\\Python\\\\ais' instead of '"c:\\\\Users\\\\xxx\\\\Box Sync\\\\Python\\\\ais"' if you require traitlets >=5.
  warn(

[I 12:32:06.189 NotebookApp] Serving notebooks from local directory: c:\\Users\\xxx\\Box Sync\\Python\\ais
info 12:32:6.190: c:\Users\xxx\miniconda3\envs\ais\lib\site-packages\traitlets\traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'c:\\\\Users\\\\xxx\\\\Box Sync\\\\Python\\\\ais' instead of '"c:\\\\Users\\\\xxx\\\\Box Sync\\\\Python\\\\ais"' if you require traitlets >=5.
  warn(
[I 12:32:06.189 NotebookApp] Serving notebooks from local directory: c:\\Users\\xxx\\Box Sync\\Python\\ais

[I 12:32:06.189 NotebookApp] Jupyter Notebook 6.4.7 is running at:
info 12:32:6.190: c:\Users\xxx\miniconda3\envs\ais\lib\site-packages\traitlets\traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'c:\\\\Users\\\\xxx\\\\Box Sync\\\\Python\\\\ais' instead of '"c:\\\\Users\\\\xxx\\\\Box Sync\\\\Python\\\\ais"' if you require traitlets >=5.
  warn(
[I 12:32:06.189 NotebookApp] Serving notebooks from local directory: c:\\Users\\xxx\\Box Sync\\Python\\ais
[I 12:32:06.189 NotebookApp] Jupyter Notebook 6.4.7 is running at:

[I 12:32:06.189 NotebookApp] http://localhost:8888/?token=b93d32977ceb2266eb14b1b43d08a8a23c2ceb8b415534db
info 12:32:6.190: c:\Users\xxx\miniconda3\envs\ais\lib\site-packages\traitlets\traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'c:\\\\Users\\\\xxx\\\\Box Sync\\\\Python\\\\ais' instead of '"c:\\\\Users\\\\xxx\\\\Box Sync\\\\Python\\\\ais"' if you require traitlets >=5.
  warn(
[I 12:32:06.189 NotebookApp] Serving notebooks from local directory: c:\\Users\\xxx\\Box Sync\\Python\\ais
[I 12:32:06.189 NotebookApp] Jupyter Notebook 6.4.7 is running at:
[I 12:32:06.189 NotebookApp] http://localhost:8888/?token=b93d32977ceb2266eb14b1b43d08a8a23c2ceb8b415534db

info 12:32:6.191: Process Execution: > ~\miniconda3\envs\ais\python.exe (daemon) ~\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\pythonFiles\vscode_datascience_helpers\getServerInfo.py
> ~\miniconda3\envs\ais\python.exe (daemon) ~\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\pythonFiles\vscode_datascience_helpers\getServerInfo.py
[I 12:32:06.189 NotebookApp]  or http://127.0.0.1:8888/?token=b93d32977ceb2266eb14b1b43d08a8a23c2ceb8b415534db
info 12:32:6.192: c:\Users\xxx\miniconda3\envs\ais\lib\site-packages\traitlets\traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'c:\\\\Users\\\\xxx\\\\Box Sync\\\\Python\\\\ais' instead of '"c:\\\\Users\\\\xxx\\\\Box Sync\\\\Python\\\\ais"' if you require traitlets >=5.
  warn(
[I 12:32:06.189 NotebookApp] Serving notebooks from local directory: c:\\Users\\xxx\\Box Sync\\Python\\ais
[I 12:32:06.189 NotebookApp] Jupyter Notebook 6.4.7 is running at:
[I 12:32:06.189 NotebookApp] http://localhost:8888/?token=b93d32977ceb2266eb14b1b43d08a8a23c2ceb8b415534db
[I 12:32:06.189 NotebookApp]  or http://127.0.0.1:8888/?token=b93d32977ceb2266eb14b1b43d08a8a23c2ceb8b415534db

info 12:32:6.193: Process Execution: > ~\miniconda3\envs\ais\python.exe (daemon) ~\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\pythonFiles\vscode_datascience_helpers\getServerInfo.py
> ~\miniconda3\envs\ais\python.exe (daemon) ~\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\pythonFiles\vscode_datascience_helpers\getServerInfo.py
[I 12:32:06.189 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
info 12:32:6.193: c:\Users\xxx\miniconda3\envs\ais\lib\site-packages\traitlets\traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'c:\\\\Users\\\\xxx\\\\Box Sync\\\\Python\\\\ais' instead of '"c:\\\\Users\\\\xxx\\\\Box Sync\\\\Python\\\\ais"' if you require traitlets >=5.
  warn(
[I 12:32:06.189 NotebookApp] Serving notebooks from local directory: c:\\Users\\xxx\\Box Sync\\Python\\ais
[I 12:32:06.189 NotebookApp] Jupyter Notebook 6.4.7 is running at:
[I 12:32:06.189 NotebookApp] http://localhost:8888/?token=b93d32977ceb2266eb14b1b43d08a8a23c2ceb8b415534db
[I 12:32:06.189 NotebookApp]  or http://127.0.0.1:8888/?token=b93d32977ceb2266eb14b1b43d08a8a23c2ceb8b415534db
[I 12:32:06.189 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).

[C 12:32:06.195 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///C:/Users/xxx/AppData/Roaming/jupyter/runtime/nbserver-12832-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=b93d32977ceb2266eb14b1b43d08a8a23c2ceb8b415534db
     or http://127.0.0.1:8888/?token=b93d32977ceb2266eb14b1b43d08a8a23c2ceb8b415534db
info 12:32:6.196: c:\Users\xxx\miniconda3\envs\ais\lib\site-packages\traitlets\traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'c:\\\\Users\\\\xxx\\\\Box Sync\\\\Python\\\\ais' instead of '"c:\\\\Users\\\\xxx\\\\Box Sync\\\\Python\\\\ais"' if you require traitlets >=5.
  warn(
[I 12:32:06.189 NotebookApp] Serving notebooks from local directory: c:\\Users\\xxx\\Box Sync\\Python\\ais
[I 12:32:06.189 NotebookApp] Jupyter Notebook 6.4.7 is running at:
[I 12:32:06.189 NotebookApp] http://localhost:8888/?token=b93d32977ceb2266eb14b1b43d08a8a23c2ceb8b415534db
[I 12:32:06.189 NotebookApp]  or http://127.0.0.1:8888/?token=b93d32977ceb2266eb14b1b43d08a8a23c2ceb8b415534db
[I 12:32:06.189 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 12:32:06.195 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///C:/Users/xxx/AppData/Roaming/jupyter/runtime/nbserver-12832-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=b93d32977ceb2266eb14b1b43d08a8a23c2ceb8b415534db
     or http://127.0.0.1:8888/?token=b93d32977ceb2266eb14b1b43d08a8a23c2ceb8b415534db

info 12:32:6.591: Connecting to process server
info 12:32:6.591: Connecting server kernel http://localhost:8888/
info 12:32:6.591: Creating server with url : http://localhost:8888/
info 12:32:6.608: Connection complete server
info 12:32:6.608: Server started.
info 12:32:6.670: Process Execution: > ~\miniconda3\envs\ais\python.exe (daemon) ~\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\pythonFiles\vscode_datascience_helpers\getServerInfo.py
> ~\miniconda3\envs\ais\python.exe (daemon) ~\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\pythonFiles\vscode_datascience_helpers\getServerInfo.py
info 12:32:6.670: Process Execution: > ~\miniconda3\envs\ais\python.exe (daemon) ~\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\pythonFiles\vscode_datascience_helpers\getServerInfo.py
> ~\miniconda3\envs\ais\python.exe (daemon) ~\.vscode\extensions\ms-toolsai.jupyter-2022.4.1011282140\pythonFiles\vscode_datascience_helpers\getServerInfo.py
info 12:32:41.274: Starting interactive window for resoruce 
info 12:32:41.355: Attempting to start a server because of preload conditions ...
info 12:32:41.359: TargetController found ID: .jvsc74a57bd001e2abf9ecdc39552c488084409e12805b5756f98a1fafb8b56a4943cd82a42b.c:\Users\xxx\miniconda3\envs\ais\python.exe.c:\Users\xxx\miniconda3\envs\ais\python.exe.-m#ipykernel_launcher (Interactive) for document Interactive-1.interactive
info 12:32:41.474: Starting Notebook id = .jvsc74a57bd001e2abf9ecdc39552c488084409e12805b5756f98a1fafb8b56a4943cd82a42b.c:\Users\xxx\miniconda3\envs\ais\python.exe.c:\Users\xxx\miniconda3\envs\ais\python.exe.-m#ipykernel_launcher for Interactive-1.interactive (disableUI=false)
[I 12:32:41.480 NotebookApp] Creating new notebook in 
info 12:32:41.513: installMissingDependencies c:\Users\xxx\miniconda3\envs\ais\python.exe, ui.disabled=false for resource 
info 12:32:41.582: Process Execution: > ~\miniconda3\envs\ais\python.exe -c "import ipykernel"
> ~\miniconda3\envs\ais\python.exe -c "import ipykernel"
info 12:32:41.714: Registering dummy command feature
info 12:32:41.919: Spec argv[0] updated from 'c:\Users\xxx\miniconda3\envs\ais\python.exe' to 'c:\Users\xxx\miniconda3\envs\ais\python.exe'
info 12:32:41.927: Adding env Variable PYTHONNOUSERSITE to c:\Users\xxx\miniconda3\envs\ais\python.exe
[I 12:32:42.016 NotebookApp] Kernel started: 9c2683dc-d244-4036-ac76-e7b292b8cf8f, name: python399jvsc74a57bd001e2abf9ecdc39552c488084409e12805b5756f98a1fafb8b56a4943cd82a42b
info 12:32:42.29: Waiting for idle on (kernel): 9c2683dc-d244-4036-ac76-e7b292b8cf8f -> unknown
[W 12:32:42.036 NotebookApp] delete /default-13131fc0-dfcd-4655-afc6-7f7a2bdd0ce5.ipynb
info 12:32:43.58: Finished waiting for idle on (kernel): 9c2683dc-d244-4036-ac76-e7b292b8cf8f -> idle
info 12:32:43.58: Started session for kernel .jvsc74a57bd001e2abf9ecdc39552c488084409e12805b5756f98a1fafb8b56a4943cd82a42b.c:\Users\xxx\miniconda3\envs\ais\python.exe.c:\Users\xxx\miniconda3\envs\ais\python.exe.-m#ipykernel_launcher
info 12:32:43.59: Finished connecting kernel .jvsc74a57bd001e2abf9ecdc39552c488084409e12805b5756f98a1fafb8b56a4943cd82a42b.c:\Users\xxx\miniconda3\envs\ais\python.exe.c:\Users\xxx\miniconda3\envs\ais\python.exe.-m#ipykernel_launcher
info 12:32:43.67: Executing silently Code (idle) = import types as _VSCODE_types\nimport os\nimport hashlib as _VSCODE_hashlib\nfrom IPython import get_ip
info 12:32:43.95: Executing silently Code (completed) = import types as _VSCODE_types\nimport os\nimport hashlib as _VSCODE_hashlib\nfrom IPython import get_ip
info 12:32:43.95: Waiting for idle on (kernel): 9c2683dc-d244-4036-ac76-e7b292b8cf8f -> idle
info 12:32:43.95: Finished waiting for idle on (kernel): 9c2683dc-d244-4036-ac76-e7b292b8cf8f -> idle
info 12:32:45.672: Disposing kernel .jvsc74a57bd001e2abf9ecdc39552c488084409e12805b5756f98a1fafb8b56a4943cd82a42b.c:\Users\xxx\miniconda3\envs\ais\python.exe.c:\Users\xxx\miniconda3\envs\ais\python.exe.-m#ipykernel_launcher for notebook Interactive-1.interactive due to selection of another kernel or closing of the notebook
info 12:32:45.672: Dispose kernel vscode-interactive:Interactive-1.interactive
info 12:32:45.675: Closing interactive window: vscode-interactive:Interactive-1.interactive
[I 12:32:45.679 NotebookApp] Kernel shutdown: 9c2683dc-d244-4036-ac76-e7b292b8cf8f
```

### Coding Language and Runtime Version

python 3.9

### Running Jupyter locally or remotely?

Local

**Comment by IanMatthewHuff** [comment]
@hookxs Could you possibly show a gif of this happening? I'm playing around with this myself locally and I've been unable to repro so far. Might help if I can see the full context.

**Comment by hookxs** [comment]
Hi @IanMatthewHuff, here is the gif. I don't know how much it shows because it really is just as I described - if some terminal is not already open then by clicking the X of the tab of the jupyter interactive window a new terminal is created. It does so on windows/linux and local/remote-ssh, consistently every time. It didn't use to be like that, it started with one of recent updates of either VS code or Jupyter or Python extensions. I don't use any special custom settings, except using default terminal "cmd" and not powershell on windows (but like I said, the bug happens on linux as well).

![close_interactive_opens_terminal](https://user-images.githubusercontent.com/18164339/168258492-21ef6a9a-0138-45b2-bdde-ef516c8a3bd6.gif)

**Comment by IanMatthewHuff** [comment]
@hookxs That's very odd, thanks for the GIF. @Tyriar or @meganrogge is this possibly something that I should move to VS Code core repo? I don't believe that we have control over what is happening here from the Juypter side unless I'm missing something.

**Comment by meganrogge** [comment]
Can you share your settings.json file and also do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
/"needs-more-info"

**Comment by hookxs** [comment]
Settings (renamed to .txt):
[settings.json.txt](https://github.com/microsoft/vscode-jupyter/files/8737009/settings.json.txt)

Log (not sure I did that right, let me know if anything).
[log.txt](https://github.com/microsoft/vscode-jupyter/files/8737033/log.txt)

Thanks

**Comment by achillesdawn** [comment]
Seconding this issue, I will be happy to provide any info needed.
